### ISSUE TITLE
right align all numbers on Study View

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10006]
- molecular profiles
![Screen Shot 2023-02-07 at 5 31 05 PM](https://user-images.githubusercontent.com/1334004/217381514-5b4f0787-9d0f-412e-a380-8339f303a62b.png)
- case lists
![Screen Shot 2023-02-07 at 5 31 29 PM](https://user-images.githubusercontent.com/1334004/217381597-f0142da7-5f69-47a2-9c71-95ddb8104f00.png)
- treatment per patient
   ![Screen Shot 2023-02-07 at 5 31 59 PM](https://user-images.githubusercontent.com/1334004/217381700-46aa26a8-025d-45e2-abc0-8b8cb3391112.png)

**Comment by sawaisinghh** [comment]
Hii @inodb I want to work on this issue. please assign me.
