### ISSUE TITLE
Make dropdown menu the will allow filtering of the fusion charts

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#10029]
On the right of the screen there is a pie chart and list of all gene pairs for which there are fusions.  Clicking on a pie slice allows the user to filter the list on the right.  It is often hard or impossible to select the right slice.  We need to introduce a drop down with this same list of pairs and use that to filter instead.  @tmazor @Sjoerd-van-Hagen, should we allow mult-select?  Should/does this also filter the table below?

The dropdown should use the [React-Select library](https://react-select.com/home), which we already use widely in the application.  

@Sjoerd-van-Hagen As you pointed out, the pie chart selection is currently broken.  My assumption is that the initial state of the page should list ALL items, unfiltered.  Right now it seems to be filtered initially because not all of the gene pairs on the right are represented in the list on the left.  @Sjoerd-van-Hagen can you comment in this ticket on on how it should work?  

![image](https://user-images.githubusercontent.com/186521/219795697-888cbb78-e6e2-4722-bfef-e7f75804c7d9.png)

**Comment by tmazor** [comment]
We should definitely allow multi-select. And, selecting something in this dropdown should filter the table as well as the graphical depictions of the fusions shown to the left of the pie chart.

**Comment by fuzhaoyuan** [comment]
The fusion pie chart will be replaced by a new bar chart. Stay tuned.
