### ISSUE TITLE
typo in oncoprint tab: "(23 samples / 61 samples)"

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1004]
http://bit.ly/1qqiSJW

![image](https://cloud.githubusercontent.com/assets/840895/14260645/86e9ee3a-fa7a-11e5-855b-838fcad480fd.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1005

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1023
