### ISSUE TITLE
tweak oncoprint "add track" UI for OncoPrint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#10057]
The current UI requires careful click after selecting and click "Add Track" button.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/840895/221905604-3eabca29-037d-48c8-ab70-5b4fd9954ad4.png">

<img width="787" alt="image" src="https://user-images.githubusercontent.com/840895/221906026-97a17b64-62f7-4486-a890-d139ffbcc4f8.png">

Here is a proposed tweak of the UI:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/840895/221907773-b029e8bd-bf9a-456a-91ff-c82898d3be84.png">

cc @tmazor

**Comment by AgniveshChaubey** [comment]
Hii @jjgao, can you please provide a bit more context on this issue?

**Comment by sawaisinghh** [comment]
@jjgao can I work on this issue. I might be able to fix this.

**Comment by anoy007** [comment]
Hi @jjgao,
I will fix this UI but please guide me how to setup this project in Ubuntu first.
