### ISSUE TITLE
top right logout button disappeared

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10064]
GENIE portal:

<img width="189" alt="image" src="https://user-images.githubusercontent.com/1334004/223469206-2786aaab-e717-4b11-a837-8d564c9b6c40.png">
 MSK portal:
MSK portal:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/1334004/223469300-448a1c01-3b45-476b-b57a-69d59d398a0a.png">

One can't download API tokens anymore, so critical to restore

Is this related to the below feature?

https://github.com/cBioPortal/cbioportal-frontend/pull/4498

**Comment by dippindots** [comment]
This is now fixed, this was related to the mismatch between the front-end and the backend.
