### ISSUE TITLE
Handle treatment data with only SUBTYPE (e.g. radiation)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#10069]
For the treatment charts on study view, it appears that we are only looking at events of type treatment with subtype AND agent attributes.   This seems to exclude radiation treatment, which only has a subtype. 

This can be seen for this [patient](https://www.cbioportal.org/patient?studyId=lgg_ucsf_2014&caseId=P01#navCaseIds=lgg_ucsf_2014:P01,lgg_ucsf_2014:P02,lgg_ucsf_2014:P04,lgg_ucsf_2014:P05,lgg_ucsf_2014:P06,lgg_ucsf_2014:P07,lgg_ucsf_2014:P08,lgg_ucsf_2014:P09,lgg_ucsf_2014:P10,lgg_ucsf_2014:P11,lgg_ucsf_2014:P12,lgg_ucsf_2014:P13,lgg_ucsf_2014:P15,lgg_ucsf_2014:P16,lgg_ucsf_2014:P17,lgg_ucsf_2014:P18,lgg_ucsf_2014:P21,lgg_ucsf_2014:P24,lgg_ucsf_2014:P25,lgg_ucsf_2014:P26,lgg_ucsf_2014:P27,lgg_ucsf_2014:P28,lgg_ucsf_2014:P29)

And here is the patient isolated in study view.  We can see radiation doesn't show up in treatment chart. 
https://bit.ly/3ZsQqZ7

- [ ] confirm that current logic looks only at treatment -> subtype -> agent 
- [ ] fallback to treatment -> subtype when there is no agent

**Comment by haynescd** [comment]
When Treatments are queried for the endpoint "/treatments/patient" (used to display treatments in studyview) the clinical event data is filtered using ClinicalEventKeyCode ("AGENT", "AGENT_CLASS", or "AGENT_TARGET"). Default is set to "AGENT"

https://github.com/cBioPortal/cbioportal/blob/2f3653ab4b7cd7e1ba1767d1b23660eab7f634f4/web/src/main/java/org/cbioportal/web/TreatmentController.java#L61


This is filtered here.
https://github.com/cBioPortal/cbioportal/blob/2f3653ab4b7cd7e1ba1767d1b23660eab7f634f4/persistence/persistence-mybatis/src/main/resources/org/cbioportal/persistence/mybatis/TreatmentMapper.xml#L19

**Comment by haynescd** [comment]
The current logic only looks at treatments that have "AGENT"

**Comment by haynescd** [comment]
Issue related to how data is structured in study and not a direct bug in cBioPortal
