### ISSUE TITLE
Selected pathway table page resets upon unselecting a group

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#10085]
This happens on the group comparison page.

Current behavior: By default we display the first page of the table even if the selected pathway is in another page.
Expected behavior: Skip to the page where the selected pathway is.

To reproduce:
- Go to https://cbioportal.org/comparison/pathways?sessionId=5cf89323e4b0ab413787436c&featureFlags=group_comparison_pathways
- Select `TP3` pathway from the table
![image](https://user-images.githubusercontent.com/3604198/225449618-ccd4c206-624b-4ce7-b3c3-844ce4a7569a.png)
- Unselect `Show TCGA PanCancer Atlas pathways only` (below the pathway selection table)
![image](https://user-images.githubusercontent.com/3604198/225449712-bf18c107-0b07-4613-96eb-56a5b86b281a.png)
- Unselect `(A) Metastasis` group (on the top of the page)
![image](https://user-images.githubusercontent.com/3604198/225449795-68d8bdcf-b047-41bb-aff3-54e70c9ea0d5.png)

To fix the issue, we should be able to call  the `findPageOfSelectedPathway` before rendering the component. See the [componentWillUpdate](https://github.com/cBioPortal/cbioportal-frontend/blob/abfb106e94dde45ea6032c085f9e2940dfb2b07a/src/shared/lib/pathwayMapper/PathwayMapperTable.tsx#L198-L207) function.

**Comment by Selwan7131** [comment]
I was trying to solve this bug but I get conflict in react versions specified in the root and the needed by the packages. if you have any suggestions please refer to me.
