### ISSUE TITLE
BPC CRC queries don't include CNA?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#10089]
I'm very confused, but somehow when I run queries in the BPC CRC cohort, OncoPrint isn't showing copy number alterations.

For example: query for EGFR
![image](https://user-images.githubusercontent.com/10508276/226224942-d63834d8-d23e-4e7b-a23f-d30703a847ae.png)
https://genie.cbioportal.org/results/oncoprint?cancer_study_list=crc_public_genie_bpc&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cstructural_variants%2Ccna&case_set_id=crc_public_genie_bpc_cnaseq&gene_list=EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit 

But in study view & on plots tab, I can see samples with amplifications:
![image](https://user-images.githubusercontent.com/10508276/226224983-b7f382c1-2181-406b-9545-ad7bf624a2c2.png)

If I query EGFR in BPC NSCLC, I see amplifications. Same if I query EGFR in MSK-IMPACT on public portal. So it doesn't seem like a general bug but somehow specific to this study?

**Comment by inodb** [comment]
@tmazor I do see the copy numbers now in the oncoprint when clicking on your link:

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1334004/226358370-68bf3035-4208-425b-9a17-8c1a8f20a47e.png">

maybe some temp glitch?
