### ISSUE TITLE
BPC CRC & NSCLC don't show domains on mutations tab

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#10090]
Mutations tab is missing domain structures:
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/10508276/226227008-552547d5-35fd-4d4d-9fab-203b4ffb46a0.png">
https://genie.cbioportal.org/results/mutations?cancer_study_list=crc_public_genie_bpc&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cstructural_variants%2Ccna&case_set_id=crc_public_genie_bpc_cnaseq&gene_list=APC%2520TP53%2520KRAS%2520PIK3CA&geneset_list=%20&tab_index=tab_visualize&Action=Submit&mutations_gene=TP53&mutations_transcript_id=ENST00000269305

I see the same issue when querying BPC CRC & BPC NSCLC, although public genie 13.0 is ok, as is public portal - for example, this is the same gene in public portal:
![image](https://user-images.githubusercontent.com/10508276/226227029-050aa3bc-76f9-46a2-8da3-59655a614efb.png)

**Comment by inodb** [comment]
@tmazor i do see the domains here on my end when clicking the link

**Comment by leexgh** [comment]
@tmazor I can see the domains too

**Comment by tmazor** [comment]
Thanks for checking - I see the now too
