### ISSUE TITLE
Kill the download tab on cBioportal query page

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#10111]
Right now we are showing the query form in the homepage download tab even though this feature is no longer supported.  Pending @cBioPortal/product approval, perhaps we can just get rid of the entire tab.

![image](https://user-images.githubusercontent.com/186521/228634776-b4a62899-b203-46cc-8c55-ac903313eda4.png)

**Comment by alisman** [comment]
@inodb @jjgao can we now just get rid of this tab entirely?  (instead of keeping it around to inform people that they can now use the download tab of results view)

**Comment by inodb** [comment]
@alisman seems fine to retire
