### ISSUE TITLE
Download data from treatment per patient/ sample

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10122]
No download feature currently, would be helpful to download both summary data and full data as a user can do with other tables

<img width="403" alt="image" src="https://user-images.githubusercontent.com/1334004/231207707-6fe86762-67e6-42a9-8b9d-eba49e863bd5.png">

Link: https://genie.cbioportal.org/study/summary?id=nsclc_public_genie_bpc

**Comment by Player256** [comment]
Hey @inodb I want to work on this issue. I wanted to understand where this context is coming from https://github.com/cBioPortal/cbioportal-frontend/blob/c5d86bab7202d9988631380aa82322c624618bdf/src/pages/studyView/chartHeader/ChartHeader.tsx#L274
