### ISSUE TITLE
Add a configuration property to control max number of studies in study view page

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#10125]
This is enforced only on query page.  

It disables the Explore button when more than the limit is reached:

![image](https://user-images.githubusercontent.com/186521/231514771-daa936de-f616-46ef-835b-4cbd451a71b7.png)

The current limit of 50 is hardcoded in studyLimitedReached method of QueryContainer.  We need to link this up with configuration and backend configuration.

- [x] Introduce new configuration property in frontend (with default to 50) (search for enable_cross_study_expression for example in frontend codebase)
- [x] Introduce new configuration property in backend (see https://github.com/cBioPortal/cbioportal/pull/10073 for example

**Comment by pvannierop** [comment]
@alisman Would it be possible to (optionally) limit based on the number of samples/patients that are selected?

**Comment by haynescd** [comment]
@pvannierop Sounds good. Will incorporate
