### ISSUE TITLE
Possible wrong mapping when using negative Entrez id values in staging files

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1013]
In some BRCA staging files we find **negative** entrez ids, like in `data_CNA.txt`. The problem with this is that the `ImportTabDelimData.java` process accepts negative entrez ids and looks them up using `daoGene.getGene(Long.parseLong(entrez));` . This would be fine if it were not for the fact that each cBioPortal installation will assign **different** negative entrez ids to different symbols, see `DaoGene.addGeneWithoutEntrezGeneId` which just uses a sequential negative count.

This means that the entry in `data_CNA.txt` with Hugo=MIR4433 and Entrez=-1035 could end up in a completely different "gene"  than MIR4433...

**Comment by pieterlukasse** [comment]
As discussed with @jjgao, the solution will be:
- [ ] in validator, block any negative entrez id values
- [ ] in loader, we should also ignore negative entrez gene IDs and use Hugo symbols (as a temporary backwards compatible solution for now, to support old staging files with negative entrez id values).

**Comment by fedde-s** [comment]
Since thehyve/cbioportal@5b8b04b9f70bdfbe2d5e1f5ac772f70ab690f763, the validator considers Entrez gene IDs that are not positive integers an error, in the sense that it implies the file cannot be loaded.

**Comment by fedde-s** [comment]
On Pieter’s request, thehyve/cbioportal@be7a038858fa5084a0592d926c02f815a2cbd5d5 makes the validator allow non-numeric Entrez identifiers with a warning that says the gene will be skipped. Only negative Entrez IDs will be reported as unloadable.

**Comment by pieterlukasse** [comment]
fixed in #1020 for mutation data (https://github.com/cBioPortal/cbioportal/pull/1020/commits/5052fb61beeb496ae57636300b3f6a551b793240)
and in https://github.com/cBioPortal/cbioportal/commit/9152c07 for CNA, mRNA, Methylation

**Comment by pieterlukasse** [comment]
:warning:  still missing for FUSION data (in `ImportFusionData.java`)
