### ISSUE TITLE
Outbound links to CIViCdb appear to be broken

### ISSUE THREAD

**Issue by acoffman** [cBioPortal/cbioportal#10139]
Hi! 👋 

I am a developer with the [CIViC project](https://civicdb.org) and we noticed that cBioPortal links to our resource are currently broken.

This appears to be the result of two different issues both stemming from the rollout of v2 of our platform.

The first issue is that we have rolled out a new [GraphQL API](https://civicdb.org/api/graphiql) to replace our previous one and cBioPortal has not been updated to use the new API. 

We realize people cannot port their integrations immediately (or may not even be aware of the new version) so we do maintain the old API in a static/readonly mode for the time being. As such, existing integrations will not be broken, they will just receive stale data, frozen as of the retirement of CIViC v1.

The second issue (and the one that is actually causing the current breakage) is the formatting of the links (ex: https://civicdb.org/events/genes/30/summary/variants/78/summary#variant). These are links to the front end of the old webapp rather than the stable [permalink format](https://civic.readthedocs.io/en/latest/api/v2/linking.html) we document for linking to CIViC entities. These links are maintained across versions of the web app and will be backwards and forwards compatible.

It seems like there are two items here to consider, one smaller and one larger. In the short term, if its possible to somewhat easily update the way the URLs are constructed to use the permalink format, they will start to function again and resolve to entities on the new site. The bigger lift will be updating cBioPortal to use the new API so that it will have access to the latest data in CIViC.

We are happy to help with using the new API or any other questions you might have, just let us know!

Thanks,
Adam

**Comment by inodb** [comment]
@acoffman thanks for reaching out and helping us to fix this! This is working again using the new GraphQL API
