### ISSUE TITLE
Integration test failure

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#10173]
This issue is blocking the backend release...

Currently, the Integration test is failing because we updated cbioportal-docker-compose solution: https://github.com/cBioPortal/cbioportal-docker-compose/blob/master/data/init.sh#L2. 
And the latest database updated on the geneset version from `msigdb_6.1` to `msigdb_7.5.1`.
These updates are causing study_es_0 to fail to load.

**Comment by inodb** [comment]
Hurray 🎊
