### ISSUE TITLE
duplicate SV intragenic records

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10208]
This functionality is currently hidden via a feature flag, but when enabled one can see duplicate SV intragenic records:

![image](https://github.com/cBioPortal/cbioportal/assets/1334004/48bf11c5-cbf6-42f7-ad83-baf363700a8b)

There is a bug in the `structuralVariantsByGene` function in `ResultsViewPageStore.ts`. It adds both genes which is fine when intragenic was only one gene, but not now that `gene1 === gene2` it does not work

And also duplicate fusion records in the Mutations tab:

<img width="1404" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/22309533/c533e364-ef97-49ea-9a62-029b9305850b">

The bug is in the `structuralVariantsReportByGene` function in `ResultsViewPageStore.ts`.

**Comment by fuzhaoyuan** [comment]
The same bug also happens in the Mutations tab.
