### ISSUE TITLE
403 on tags/fetch when show_unauthorized_studies=true

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#10221]
v5.3.9 on Centos 7
When opening the home page after logging in, I get a 403 for

    POST https://server.url/api/studies/tags/fetch

this request includes a list of all study IDs on the server.
I have 

    authorization=true`
    skin.home_page.show_unauthorized_studies=true

and my account has access to some studies but not all.

 My global_message doesn't even contain any study tags but some studies do have tags set.

This doesn't happen if I have access to all studies or if I disable the show unauthorized. It did work in 3.7.22 FWIW.

Should perhaps ```getTagsForMultipleStudies``` be tagged with ```T(org.cbioportal.utils.security.AccessLevel).LIST``` instead of  ```T(org.cbioportal.utils.security.AccessLevel).READ``` ?

**Comment by inodb** [comment]
@j-hudecek Thanks for reporting! What cBioPortal version is this?

 @jagnathan did you run into this issue?

**Comment by inodb** [comment]
@jagnathan good point, I don't think we should return study tags if they don't have access

@j-hudecek do you just see a 403 error in the console or is there an actual for the user?

**Comment by j-hudecek** [comment]
I would agree if it was just an error in the console but what I see is a error screen that covers everything with no way to dismiss it
![image](https://github.com/cBioPortal/cbioportal/assets/5654699/70194fba-044b-4828-a916-8746262063c5)
So this combination of settings is completely unusable

**Comment by j-hudecek** [comment]
Do you have an estimate when could this be resolved? Is changing the permissions the way to go or would it need some more refactoring?

**Comment by jagnathan** [comment]
hi @j-hudecek the PR will fix the issue on the backend. On the frontend there is a change required which will be fixed by @BasLee. If you are building your own version, then you can use this cbioportal-frontend commit as a temporary fix: https://github.com/jagnathan/cbioportal-frontend/commit/ca4179437ff0575cef19c5130d4a687e5c636aa9

**Comment by jagnathan** [comment]
FYI: The study tags are not used on any studies in cbioportal.org and genie.cbioportal.org

**Comment by jagnathan** [comment]
The PR for adding the swagger annotations - https://github.com/cBioPortal/cbioportal/pull/10101 
Issue for swagger validation is https://github.com/cBioPortal/cbioportal/issues/9414
