### ISSUE TITLE
tweak blca_mskcc_signet_ring_impact

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1024]
- [x] change study id to blca_plasmacytoid_mskcc_2016
 - [x] add oncotree_code "blca" to all samples
 - [x] "Lynph node status" and "Tumor TNM stage" should have type of STRING not NUMBER
 - [x] SAMPLE_CLASS should all be "Tumor"
 - [x] Is IMPACTv5 the same as IMPACT410? If so, we should use IMPACT410.

**Comment by chenh4** [comment]
@jjgao 
Those 5 items have been updated at Triage portal at 
http://dashi-dev.cbio.mskcc.org:28080/triage/study.do?cancer_study_id=blca_plasmacytoid_mskcc_2016#summary

Do you want to double check before push it out to public portal? For Lymph node status, am not sure if this is how they want to present, but I think it's fine for now. 

Thanks,
Annice

**Comment by jjgao** [comment]
@chenh4 thanks, it looks great. Please push out.

**Comment by chenh4** [comment]
@jjgao 
discuss with JJ about the CANCER_TYPE values on April 12th 11:00am?
