### ISSUE TITLE
New feature in the study view: Study view tables for specific mutations

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1028]
The following two tables would be extremely useful:

1 - Number and ratio of truncating mutations to all mutations (a user should be able to set a threshold for minimum number of mutations)
2 - Number and ratio of hotspot mutations to all mutations (same user filter as above)

**Comment by jjgao** [comment]
@zhx828 let's put this to our to-do list. We can wait until refactoring is done since we have waited so long :)

**Comment by zhx828** [comment]
@jjgao this seems like a ticket related to https://github.com/cbioportal/cbioportal/issues/5213?

**Comment by milen-sage** [comment]
Sorry if I am adding noise, do you happen to have a study data model?

We are considering various options for organizing HTAN datasets in more general container categories (e.g. study including multiple datasets of potentially different types) and could interoperate at the onset; if this is not relevant to the study concept you are considering please ignore :)
