### ISSUE TITLE
oncoprint: support the same gene on different rows

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1033]
From #929:

- in query select  "Colorectal Adenocarcinoma (TCGA, Provisional)" and "Colorectal Adenocarcinoma (TCGA, Nature 2012)"
- in genes box set: `KRAS: MUT=G12; KRAS:MUT=G13`  

You will get the following:
- in cross-cancer histogram there are **still** 67 + 62 mutated cases (**which is wrong as this is the same as for =G12**)
- in oncoprint linked out from histogram (when clicking ["click to view details" link](http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_cna_seq&case_ids=&gene_list=KRAS:%20MUT=G12;%20KRAS:%20MUT=G13%20%20%20%20&gene_set_choice=user-defined-list&Action=Submit)) there are 0 and 0 cases on 2 oncoprint lanes

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1416

**Comment by pieterlukasse** [comment]
I tested the oncoprint fix for a single study and this works fine :+1: 

![image](https://cloud.githubusercontent.com/assets/2900303/16652433/edb35a10-444a-11e6-8848-6feae3eb5c89.png)

**Comment by pieterlukasse** [comment]
The cross-cancer histogram issue is not fixed, but this is in another issue (still reported in #929). So this one can be closed indeed.

**Comment by pieterlukasse** [comment]
Just tested this on /beta now, but not yet working. Should it be on /beta already?

see http://www.cbioportal.org/beta/index.do?cancer_study_list=brca_metabric&cancer_study_id=brca_metabric&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_metabric_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_metabric_cna&Z_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_metabric_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=ERBB2%3AMUT%3B%0D%0AERBB2%3AHOMDEL%3B&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

**Comment by pieterlukasse** [comment]
And this one fails on /beta as well: http://www.cbioportal.org/beta/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TP53%3A+MUT%3DE56*%3B%0D%0ATP53%3A+MUT%3DR175H%3B&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit

![image](https://cloud.githubusercontent.com/assets/2900303/17020359/724b259a-4f41-11e6-8a01-b9838dc2b363.png)
