### ISSUE TITLE
cbioportal-container exited with code 1

### ISSUE THREAD

**Issue by dultragab** [cBioPortal/cbioportal#10334]
Hello,
I am trying to run the docker container following the instructions highlighted [here](https://docs.cbioportal.org/deployment/docker/).
I am using WSL, specifically debian, alongside docker desktop.

I have been able to successfully run the ./init.sh script and etc whilst installing ,however, whenever I 'docker compose up' the containers, I get the following error repeating on my terminal:

cbioportal-container                   | Database connection success
cbioportal-container                   | Migrating database if necessary...
cbioportal-container                   | (1146, "Table 'cbioportal.patient_list' doesn't exist")
cbioportal-container                   | Running statements for version: 1.1.0
cbioportal-container                   |        Executing statement: CREATE TABLE sample_list LIKE patient_list;
cbioportal-container exited with code 1

Can anyone help me figure out how to fix this? It seems to be trying to create a table based on patient_list but patient list doesnt seem to exist.

What am I doing wrong here?
Thanks for the help.

**Comment by officialasishkumar** [comment]
Hi @dultragab , 

Try deleting all the images and containers and starting fresh. Also what was the output you got when you typed `./init.sh`?

**Comment by deyazoubi** [comment]
Hi  @officialasishkumar,
Hi @dultragab did the issue solved from your side?
I'm facing the same issue, although I have started everything from scratch  (cbioportal 5.3.15 , MySQL 5.7, mango 4.2)
cbioportal-container                   | mysqld is alive
cbioportal-container                   | Database connection success
cbioportal-container                   | Migrating database if necessary...
cbioportal-container                   | Running statements for version: 1.1.0
cbioportal-container                   | 	Executing statement: CREATE TABLE sample_list LIKE patient_list;
cbioportal-container                   | (1146, "Table 'cbioportal.patient_list' doesn't exist")
cbioportal-container                   | Running statements for version: 1.1.0
cbioportal-container                   | Executing statement: CREATE TABLE sample_list LIKE patient_list;
cbioportal-container exited with code 1


here is the output of the  ./init.sh
sudo ./init.sh

--2023-08-22 15:07:30--  https://raw.githubusercontent.com/cBioPortal/cbioportal/v5.3.6/db-scripts/src/main/resources/cgds.sql
Resolving [raw.githubusercontent.com](http://raw.githubusercontent.com/) ([raw.githubusercontent.com](http://raw.githubusercontent.com/))... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to [raw.githubusercontent.com](http://raw.githubusercontent.com/) ([raw.githubusercontent.com](http://raw.githubusercontent.com/))|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30598 (30K) [text/plain]
Saving to: ‘cgds.sql’

cgds.sql                                100%[=============================================================================>] 29.88K  --.-KB/s    in 0s

2023-08-22 15:07:31 (58.4 MB/s) - ‘cgds.sql’ saved [30598/30598]

--2023-08-22 15:07:31--  https://github.com/cBioPortal/datahub/raw/master/seedDB/seedDB_hg19_archive/seed-cbioportal_hg19_v2.12.14.sql.gz
Resolving [github.com](http://github.com/) ([github.com](http://github.com/))... 140.82.121.3
Connecting to [github.com](http://github.com/) ([github.com](http://github.com/))|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/cBioPortal/datahub/master/seedDB/seedDB_hg19_archive/seed-cbioportal_hg19_v2.12.14.sql.gz [following]
--2023-08-22 15:07:31--  https://raw.githubusercontent.com/cBioPortal/datahub/master/seedDB/seedDB_hg19_archive/seed-cbioportal_hg19_v2.12.14.sql.gz
Resolving [raw.githubusercontent.com](http://raw.githubusercontent.com/) ([raw.githubusercontent.com](http://raw.githubusercontent.com/))... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to [raw.githubusercontent.com](http://raw.githubusercontent.com/) ([raw.githubusercontent.com](http://raw.githubusercontent.com/))|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51337072 (49M) [application/octet-stream]
Saving to: ‘seed.sql.gz’

seed.sql.gz                             100%[=============================================================================>] 48.96M   251MB/s    in 0.2s

2023-08-22 15:07:31 (251 MB/s) - ‘seed.sql.gz’ saved [51337072/51337072]

--2023-08-22 15:07:31--  https://cbioportal-datahub.s3.amazonaws.com/lgg_ucsf_2014.tar.gz
Resolving [cbioportal-datahub.s3.amazonaws.com](http://cbioportal-datahub.s3.amazonaws.com/) ([cbioportal-datahub.s3.amazonaws.com](http://cbioportal-datahub.s3.amazonaws.com/))... 52.217.229.73, 52.217.100.100, 3.5.20.197, ...
Connecting to [cbioportal-datahub.s3.amazonaws.com](http://cbioportal-datahub.s3.amazonaws.com/) ([cbioportal-datahub.s3.amazonaws.com](http://cbioportal-datahub.s3.amazonaws.com/))|52.217.229.73|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1472561 (1.4M) [application/x-tar]
Saving to: ‘lgg_ucsf_2014.tar.gz’

lgg_ucsf_2014.tar.gz                    100%[=============================================================================>] 1.40M  2.03MB/s    in 0.7s

2023-08-22 15:07:32 (2.03 MB/s) - ‘lgg_ucsf_2014.tar.gz’ saved [1472561/1472561]

lgg_ucsf_2014/
lgg_ucsf_2014/data_timeline_surgery.txt
lgg_ucsf_2014/data_timeline_treatment.txt
lgg_ucsf_2014/data_mutations_extended.txt
lgg_ucsf_2014/data_mutations_mskcc.txt
lgg_ucsf_2014/data_timeline_specimen.txt
lgg_ucsf_2014/meta_mutations_extended.txt
lgg_ucsf_2014/meta_clinical_sample.txt
lgg_ucsf_2014/data_clinical_patient.txt
lgg_ucsf_2014/LICENSE
lgg_ucsf_2014/data_timeline_status.txt
lgg_ucsf_2014/meta_study.txt
lgg_ucsf_2014/meta_clinical_patient.txt
lgg_ucsf_2014/meta_timeline_treatment.txt
lgg_ucsf_2014/meta_timeline_status.txt
lgg_ucsf_2014/data_clinical_sample.txt
lgg_ucsf_2014/case_lists/
lgg_ucsf_2014/case_lists/cases_all.txt
lgg_ucsf_2014/case_lists/cases_sequenced.txt
lgg_ucsf_2014/meta_timeline_specimen.txt
lgg_ucsf_2014/meta_timeline_surgery.txt


thanks

**Comment by officialasishkumar** [comment]
Hey @deyazoubi, Sorry for the late reply. Were you able to fix it?

If not can you share the operating system that you are using?

**Comment by deyazoubi** [comment]
Hi @officialasishkumar, 
thank you for your reply, The problem is solved by setting the portal.properties db.user to root instead of cbio_user
db.user=root
db.password=somepassword
