### ISSUE TITLE
Filter mutations tab with OQL

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1034]
From #929.
- in query select  "Colorectal Adenocarcinoma (TCGA, Provisional)" and "Colorectal Adenocarcinoma (TCGA, Nature 2012)"
- in genes box set: `KRAS: MUT=G12`

You will get the following:
- in cross-cancer histogram there are 67 + 62 mutated cases 
- in mutations tab there are 185 mutations in the table, but only 67+10+1+2+2+1+1+2+9=95 in lollipop view (**so only first study  in lollipop and no OQL filtering applied?**) 
- in oncoprint linked out from histogram (when clicking ["click to view details" link](http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_cna_seq&case_ids=&gene_list=KRAS:%20MUT=G12&gene_set_choice=user-defined-list&Action=Submit)) there are 67 and 62 cases

**Comment by pieterlukasse** [comment]
related to #507?
