### ISSUE TITLE
Use json instead of portal.properties?

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#10352]
Some of the frontend configuration requires complex data structures for subproperties.  These are difficult to present in portal.properties, but easy to represent in json.    However, we don't really want to make people maintain to separate configuration files.  For this reason it would be nice to use JSON for all configuration.  @inodb thought there might be support of this in Spring. Could this be part of refactor?

**Comment by inodb** [comment]
@JREastonMarks agree that separation of the props would be ideal, but the distinction isn't always that clear cut as some properties need to be passed to both backend and frontend. We could keep a separate file for frontend only props if we want, but we prolly need to continue to have a way to pass props to both (currently this is done in `frontend_config.jsp`)

Spring boot provides some framework for property configuration:

https://docs.spring.io/spring-boot/docs/2.1.13.RELEASE/reference/html/boot-features-external-config.html

It also supports YAML/JSON property files. There are a few properties in the backend as well where we've been running into issues with not being able to pass nested data structures

**Comment by JREastonMarks** [comment]
I think this might need to be its own RFC/initiative. I know that this can be done as part of moving properties to different files or format for storage. I am wondering if our current approach is the best approach especially with all the updates we get with the Spring framework upgrade.
