### ISSUE TITLE
"apply log scale" doesn't work for rnaseq vs clinical data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1035]
![image](https://cloud.githubusercontent.com/assets/840895/14384587/e0a152f0-fd69-11e5-8140-5a844709fb3e.png)

![image](https://cloud.githubusercontent.com/assets/840895/14384593/e9f535d8-fd69-11e5-92cb-76b9a1ea8341.png)

**Comment by yichaoS** [comment]
https://github.com/cBioPortal/cbioportal/pull/1036
