### ISSUE TITLE
Study view page can't hide the clinical chart by default even priority is set to 0

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#10351]
See this example https://beta.cbioportal.mskcc.org/study/summary?id=um_tcga
And `other_patient_id` `other_sample_id` can't be hidden by default even if the priority is set to `0`

Related pr:
https://github.com/cBioPortal/cbioportal-frontend/pull/4598
Related document:
https://docs.cbioportal.org/deployment/customization/studyview/#priorities

**Comment by alisman** [comment]
@dippindots I cannot reproduce this.  I think you meant "uvm_tcga" right? From my experiments, if I set prioirity to 

-1: hidden from add chart list
0: the chart is hidden by default but appears in the add chart list.
1: chart is on be default 

Note that this is NOT true for these standard clinical attributes, which have hard coded priorities which cannot be overridden from data (whether that is desirable is separate question)

CANCER_TYPE: 3000,
        CANCER_TYPE_DETAILED: 2000,
        GENOMIC_PROFILES_SAMPLE_COUNT: 1000,
        CASE_LISTS_SAMPLE_COUNT: 1000,
        OS_SURVIVAL: 400,
        DFS_SURVIVAL: 300,
        DSS_SURVIVAL: 250,
        PFS_SURVIVAL: 250,
        MUTATED_GENES_TABLE: 90,
        STRUCTURAL_VARIANT_GENES_TABLE: 85,
        STRUCTURAL_VARIANTS_TABLE: 85,
        CNA_GENES_TABLE: 80,
        PATIENT_TREATMENTS_TABLE: 75,
        PATIENT_TREATMENT_GROUPS_TABLE: 75,
        PATIENT_TREATMENT_TARGET_TABLE: 75,
        SAMPLE_TREATMENTS_TABLE: 75,
        SAMPLE_TREATMENT_GROUPS_TABLE: 75,
        SAMPLE_TREATMENT_TARGET_TABLE: 75,
        CLINICAL_EVENT_TYPE_COUNTS_TABLE: 75,
        CANCER_STUDIES: 70,
        SEQUENCED: 60,
        HAS_CNA_DATA: 50,
        SAMPLE_COUNT: 40,
        MUTATION_COUNT: 30,
        FRACTION_GENOME_ALTERED: 20,
        GENDER: 9,
        SEX: 9,
        AGE: 9,
        RACE: 8,
        ETHNICITY: 8,
        SAMPLE_TYPE: 8,
        HISTOLOGY: 8,
        TUMOR_TYPE: 8,
        SUBTYPE: 8,
        TUMOR_SITE: 8,
        'X-VS-Y-FRACTION_GENOME_ALTERED-MUTATION_COUNT': 200,

**Comment by dippindots** [comment]
@alisman I can still reproduce this issue I believe:
If you go to study: https://beta.cbioportal.mskcc.org/study/summary?id=msk_met_2021
And you also need to remove a line from the frontend code (the portal will initially display 20 clinical charts by default. These charts are prioritized from high to low. Additional clinical charts are initially hidden but can be easily selected by users through the 'Add charts' dropdown menu.)
Comment out this line: https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/pages/studyView/StudyViewPageStore.ts#L7534

After you local dev mode is up, click `Reset Charts`and you will see the e.g. `Met Count` and `Met Site Count` still show up although they have `priority=0`
