### ISSUE TITLE
Change design for adding X vs Y charts

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10362]
Mockup from design hackathon:

https://docs.google.com/presentation/d/1t9wLcQ58RG6KQnOkngExer3b-dt-x1yNzo8NJ9mueRM/edit?pli=1#slide=id.g2450dd32ba9_0_50

**Comment by dassudip2001** [comment]
I can fix this issue

**Comment by alisman** [comment]
@gblaih this ticket is associated with plots tab to study view ticket

**Comment by alisman** [comment]
@gblaih close this as duplicate of https://github.com/cBioPortal/cbioportal/issues/10443
