### ISSUE TITLE
biojava dependencies error

### ISSUE THREAD

**Issue by serlej** [cBioPortal/cbioportal#1038]
Hi, I am getting error on Biojava dependencies below, when building core. 

Biojava site claims that http://biojava.org/wikis/BioJava:GetStarted/

BioJava, as of release 4.0.0 is available through Maven Central. or

You can get the latest version of BioJava3+ from the download page BioJava (v) (requires Java 1.6+).
(link to download is not working)

[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project org.mskcc.cbio:core:jar:1.1.0: The following artifacts could not be resolved: org.biojava:biojava3-core:jar:3.0.7, org.biojava:biojava3-structure:jar:3.0.7: Failure to find org.biojava:biojava3-core:jar:3.0.7 in http://www.biojava.org/download/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of biojava-maven-repo has elapsed or updates are forced

**Comment by fedde-s** [comment]
We’re also facing this issue at The Hyve, and so is our client @awernibi. The upstream repository http://www.biojava.org/download/maven/ seems to have been removed as BioJava is now available from the Maven Central Repository (http://search.maven.org/#search|ga|1|g%3A%22org.biojava%22), but the only 3.x release still hosted there is 3.0, not 3.0.7. cBioPortal should probably adopt the 4.x series, or in the meantime fall back to 3.0.

**Comment by holtgrewe** [comment]
Does anyone know of a workaround Can I somehow obtain the jars and place them into `~/.m2`?

**Comment by heuermh** [comment]
The former site hosting for http://biojava.org is down, including unfortunately the biojava maven repository. Some content has been migrated to https://github.com/biojava/biojava.github.io but not javadoc, downloads, or the maven repository yet.

I'm familiar with cBioPortal and could help migrate to a newer version available on Maven Central.

In the meantime, we're trying hard to migrate the missing content over.  I'm sorry for the inconvenience.

**Comment by heuermh** [comment]
@fedde-s Migration from 3.0.7 to 4.2.0 in your code base should be relatively straightforward; take a look at my pull request here for help.  There may be some binary incompatibilities that only surface at runtime though, so take care in testing after making the change.

**Comment by fedde-s** [comment]
@heuermh Thank you for your effort and information! I see that @inodb has been assigned to the pull request (#1065). I’ll look how far he has gotten tomorrow, and try it out myself too then.
