### ISSUE TITLE
Data download in study view - enable download of table vs just underlying data

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#10389]
In the study view, it would be useful to add an additional download option to allow the download of the actual table data. At the moment, we only support the download of the underlying data. 

It would be nice to have both options, and we could call the items:
 - table data
 - underlying data (or per sample data)

<img width="825" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/11892704/efb5fdf0-5d26-4722-b2b4-f3c9176638d8">

**Comment by alisman** [comment]
@schultzn this is fixed for all clinical data tables
