### ISSUE TITLE
filter submission unselect in chart does not show all options

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10390]
https://www.cbioportal.org/study/summary?id=msk_impact_2017
- click one cancer type, hit submit
- deselect that cancer type
- can't see all values:

<img width="738" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/1334004/db756965-d43b-4655-a486-ec151ff33fa6">

**Comment by alisman** [comment]
@inodb i think this is in manual submit mode when you use checkboxes to DE-select.  We now prevent user from doing that. The manual submit mode should be rendered unecessary by performance improvements.

**Comment by inodb** [comment]
correct, this is fixed with the banner thingy
