### ISSUE TITLE
MySQL server migration

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#10391]
Currently, we are using MySQL 5.7, by the end of November, all production databases should run MySQL 8.
- [x] Test connection string with the new MySQL 8 database
- [x] Make a snapshot and create a shallow MySQL 8 database
  - [x] Make sure the study importing process is still working with MySQL 8
- [x] Change the production databases
- [x] Delete old MySQL 5.7 database after 1-2 weeks

**Comment by inodb** [comment]
@dippindots I think this is fully completed right?
