### ISSUE TITLE
Improve cBioPortal citation section on the home page

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#10400]
- Change text to: Please cite: [cBioPortal](https://docs.cbioportal.org/user-guide/faq/#how-do-i-cite-the-cbioportal) (add book icon on the right)
- Remove backend configuration parameter: `skin_citation_rule_text`
- Change frontend implementation to always show the default text

**Comment by inodb** [comment]
Fixed in https://github.com/cBioPortal/cbioportal-frontend/commit/358cbcaa5ec00f316e2d1ce9376a35aadb87ed00. Book icon worked also when adding it to the config parameter, so didn't have to remove it
