### ISSUE TITLE
CNA data accesible if only gene-linked

### ISSUE THREAD

**Issue by jgarces02** [cBioPortal/cbioportal#10415]
Hi, 

I'm using the R package (_cbioportalR_) for retrieving all data and have encountered a problem with some patients who have a clear CNA but are not linked to any gene. For instance, there's a clear amp1q (among others) in this patient, but when downloading it through the package, only CNAs with linked genes (ie, CNAs involving chr11 but not chr1) appear. Would be any way to get all the CNA information? Or perhaps I'm misunderstanding something, please?

![image](https://github.com/cBioPortal/cbioportal/assets/27858969/74fd18b8-fa71-4846-84d7-ab54cc3d964b)

![image](https://github.com/cBioPortal/cbioportal/assets/27858969/e7b47ea4-de28-4fb0-a667-23c4a90c9d30)

Thanks in advance.

**Comment by karissawhiting** [comment]
Hi @jgarces02,

From your example, it looks like the data returned by the package is consistent with the copy number data in the portal (5 copy number alterations in those genes listed that meet the threshold). This is discrete copy number data (https://docs.cbioportal.org/file-formats/#discrete-copy-number-data) and by default returns CNAs that meet a threshold value (this has more info about thresholds: https://docs.cbioportal.org/user-guide/faq/#what-is-gistic-what-is-rae). 

If you are looking for more in depth CNA data, I recommend downloading the segmentation data. For example:

``` r
library(cbioportalR)
set_cbioportal_db("msk")
#> ✔ You are successfully connected!
#> ✔ base_url for this R session is now set to "cbioportal.mskcc.org/api"
get_segments_by_sample("P-0088083-T01-IH4")
#> The following parameters were used in query:
#> Study ID: "mskimpact"
#> Molecular Profile ID: "Not Applicable"
#> Genes: "All available genes"
#> # A tibble: 107 × 10
#>    uniqueSampleKey  uniquePatientKey patientId  start    end segmentMean studyId
#>    <chr>            <chr>            <chr>      <int>  <int>       <dbl> <chr>  
#>  1 UC0wMDg4MDgzLVQ… UC0wMDg4MDgzOm1… P-0088083 8.09e5 1.13e7      0.0249 mskimp…
#>  2 UC0wMDg4MDgzLVQ… UC0wMDg4MDgzOm1… P-0088083 1.22e7 1.23e7     -0.420  mskimp…
#>  3 UC0wMDg4MDgzLVQ… UC0wMDg4MDgzOm1… P-0088083 1.23e7 5.14e7     -0.0277 mskimp…
#>  4 UC0wMDg4MDgzLVQ… UC0wMDg4MDgzOm1… P-0088083 5.14e7 5.38e7      0.407  mskimp…
#>  5 UC0wMDg4MDgzLVQ… UC0wMDg4MDgzOm1… P-0088083 5.55e7 1.15e8     -0.151  mskimp…
#>  6 UC0wMDg4MDgzLVQ… UC0wMDg4MDgzOm1… P-0088083 1.15e8 1.15e8      0.478  mskimp…
#>  7 UC0wMDg4MDgzLVQ… UC0wMDg4MDgzOm1… P-0088083 1.15e8 1.17e8     -0.112  mskimp…
#>  8 UC0wMDg4MDgzLVQ… UC0wMDg4MDgzOm1… P-0088083 1.18e8 1.18e8      0.550  mskimp…
#>  9 UC0wMDg4MDgzLVQ… UC0wMDg4MDgzOm1… P-0088083 1.18e8 1.21e8     -0.193  mskimp…
#> 10 UC0wMDg4MDgzLVQ… UC0wMDg4MDgzOm1… P-0088083 1.21e8 2.15e8      0.859  mskimp…
#> # ℹ 97 more rows
#> # ℹ 3 more variables: sampleId <chr>, chromosome <chr>, numberOfProbes <int>
```

Hope this helps!

**Comment by jgarces02** [comment]
Totally, I was working the previous version of cBioPortalR and I didn't have this function 😞 

Thanks a lot for the suggestion, it's working perfectly!
