### ISSUE TITLE
OncoKB levels not getting properly picked on mutations comparison page

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#10421]
https://genie.cbioportal.org/comparison/mutations?comparisonId=648cc689a9c90a1e68bebdd5

The T790M should have L1/R1 but is showing a 3B. After discussing with @zhx828 , looks like the cancer type info is not getting pulled.

**Comment by inodb** [comment]
@gblaih I recall we had some discussions about this. The trickiness stems from that there could be samples with a different cancer type grouped in one row. In my notes I saw something like:

> Logic:
When all cancer types are the same, pass that to OncoKB
If not: Make it same as unknown primary (show highest level)

Do you remember what we did here?

**Comment by gblaih** [comment]
> Logic:
> When all cancer types are the same, pass that to OncoKB
> If not: Make it same as unknown primary (show highest level)

Yes, this is what should be happening. I'm thinking the cause of the issue may be that "Cancer Type Detailed" is being used rather than "Cancer Type". I can take a look and fix this.
