### ISSUE TITLE
Study view - table - "select all" - do not deselect previous selected

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#10422]
- open study view, e.g. https://www.cbioportal.org/study/summary?id=msk_impact_2017
- search a term in a table such as Cancer Type Detailed table
- click "Select all"
- search another team
- click "Select all"
- Problem: the ones selected the first time will be deselected if they are not part of the results in the second search

<img width="401" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/840895/19db8431-40b2-4fe2-9704-f2962a7bc8e0">

**Comment by Dannn-tech** [comment]
Hi can you assign me this issue please ?

**Comment by parthiv360** [comment]
Hey, @jjgao   can you please assign this issue to me? Thanks a lot.

**Comment by alisman** [comment]
@Robert-Kramar @parthiv360 can do this ticket?  you should be able to assign it to yourself, no?

**Comment by Paras20222** [comment]
Can You Please share a video describing the issue

**Comment by ManishPrajapat001** [comment]
Can you  please guide me in finding the files which have this feature ? @alisman

**Comment by Ankuristic** [comment]
@alisman @jjgao   could i start working on this issue. or someboody has already assign on this issiue . please tell us

**Comment by khaledfahmy123** [comment]
Hi there, i would love to work on this.. I've put together a pull request to address the issue. Could you please take a moment to review it and let me know if there are any modifications or adjustments needed
