### ISSUE TITLE
Arrow buttons for timeline tooltip when there are more than one events

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10447]
<img width="424" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/1334004/17c94a59-b7f8-4dcc-b03b-f0cca7d53147">

Would be nice to have some left and right buttons in the top of this tooltip, so one can click to navigate to the next and previous event

[This patient](https://www.cbioportal.org/patient?studyId=lgg_tcga_pan_can_atlas_2018&caseId=TCGA-CS-6669) has two events which fall on the same day.  

![image](https://github.com/cBioPortal/cbioportal/assets/186521/1c06637e-071d-4336-9f6c-37e65a486a75)

In the tooltip, we want to add arrow buttons to allow user the cycle through the events.  This is exact same functionality as is currently invoked using spacebar or arrow keys.   We just want it to use buttons instead.

![image](https://github.com/cBioPortal/cbioportal/assets/186521/8130769c-8176-43d8-bf11-8a4645fa9bdd)

**Comment by 2001sahil** [comment]
is this issue still open i would like to work on it.

**Comment by alisman** [comment]
@inodb i'm confused here about "next/previous patient".  do you mean next previous event (in set of overlapping events)

**Comment by inodb** [comment]
@alisman srry yes, next and previous event. Updated the description

**Comment by ShreeBohara** [comment]
Can i work on this issue?

**Comment by alisman** [comment]
@ShreeBohara it's already taken.
