### ISSUE TITLE
CIVIC annotations not working - "Error fetching Civic data"

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#10455]
CIVIC annotations not working in Mutations tab - "Error fetching Civic data"

<img width="837" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/11892704/ba5cc0e8-a8fa-4f7b-a9f4-f03443da26aa">

https://bit.ly/39hVtDd

See:

> The CIViC V1 REST API will officially be retired on November 1st, 2023. All CIViC integrations should transition to our new V2 GraphQL API. The new API is more powerful and provides access to the newest CIViC data model, features, and data. The easiest way to get started is to try out queries and browse the documentation in the GraphiQL sandbox

Duplicate of: https://github.com/cBioPortal/cbioportal/issues/9521

**Comment by alisman** [comment]
@inodb i thought we had turned off Civic annotation until @leexgh's work is done.  Seems like there are api changes required and that this might not get done for a while?

**Comment by alisman** [comment]
@leexgh can you confirm that we are waiting for the Civic team to update their GraphQL api, beforewhich we cannot turn back on civic annotation?

**Comment by leexgh** [comment]
@alisman Yes, most of the coding was done, now waiting for the new API to finish the implementation. Before that we still can't turn it back. See the original ticket here: https://github.com/cBioPortal/cbioportal/issues/9521
