### ISSUE TITLE
Swagger-UI html injection vulnerablility

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#10458]
According to google group user, there is an html injection vulnerability in the Swagger-UI page:

https://groups.google.com/g/cbioportal/c/0rCXekX9lpk

**Comment by alisman** [comment]
@haynescd @JREastonMarks  am i right to assume we are upgrading the Swagger UI in 6.0 and this should go away?  If so, we can close this.

**Comment by JREastonMarks** [comment]
We have not tested this in 6.0 so we don't know if it will be resolved.

**Comment by JREastonMarks** [comment]
This issue is resolved in 6.0.

Closing ticket.
