### ISSUE TITLE
Critical Vulnerabilities in the backend code

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#10468]
From AWS vulnerability scanner (This is on version: 5.4.1)
![image002](https://github.com/cBioPortal/cbioportal/assets/12956870/3a5b142d-0221-4716-b01f-e1c57e7b6486)
![image003](https://github.com/cBioPortal/cbioportal/assets/12956870/c047dd0f-7b4c-4547-a145-16a724253cbb)
![image004](https://github.com/cBioPortal/cbioportal/assets/12956870/eac682a0-0111-44b1-8f46-f54857857b98)

**Comment by JREastonMarks** [comment]
Closing this ticket in anticipation of 6.0 release which addresses many of these issues.
Please see here for an up to date list of known issues:
https://sonarcloud.io/project/overview?id=cBioPortal_cbioportal
