### ISSUE TITLE
Change quick help note in network view

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#1047]
Change the quick help note at the top of the network view as follows: 
Double-click nodes/edges for details. Right-click edges for detailed process-level network view.

**Comment by ugurdogrusoz** [comment]
Also add a button at the bottom of the Details tab for Interactions with the label "Detailed process (SBGN)" does the same thing as right-clicking on an interaction and pops up the SBGN view.

**Comment by ugurdogrusoz** [comment]
Please rename this button as originally specified!

**Comment by istemi-bahceci** [comment]
This is fixed now
