### ISSUE TITLE
feedback on beta v6

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#10484]
Overall looks good! I still have more testing to do, but here are a few issues I found so far:

1) Study view missing 'Study Page Help' in the upper right:
![image](https://github.com/cBioPortal/cbioportal/assets/10508276/6625b826-2dc9-433b-819e-08d933973e4b)
As far as I can tell, this feature is also missing on all other pages

2) Homepage is missing link to GENIE:
![image](https://github.com/cBioPortal/cbioportal/assets/10508276/07623907-1823-46d7-8462-7ddd4ec1dbb9)

3) Missing arm-level CNA in group comparison (the data exists in study view, so I assume this means the whole feature of group comparison for categorical/binary data isn't turned on)
prod: 
![image](https://github.com/cBioPortal/cbioportal/assets/10508276/dbfa222b-1caa-43f4-8893-fd21e11cc215)
beta: 
![image](https://github.com/cBioPortal/cbioportal/assets/10508276/7270a861-72d4-4277-9036-44a9e3d0f048)

4) Beta has a cytoband for QNG1 that is missing in prod. This seems like beta is better than prod, but since they're supposed to be the same - why is this different?
prod: 
![image](https://github.com/cBioPortal/cbioportal/assets/10508276/5c617aee-4855-40f4-b277-9f16527b4ad9)
https://www.cbioportal.org/comparison/mrna?comparisonId=6138b02de6ebe01a6ee2de0b&unselectedGroups=%5B%22NA%22%2C%22LGG_IDHmut-non-codel%22%5D
beta: 
![image](https://github.com/cBioPortal/cbioportal/assets/10508276/1bb78220-346a-4f98-b392-59b967fae6cc)
https://beta.cbioportal.org/comparison/mrna?comparisonId=6138b02de6ebe01a6ee2de0b&unselectedGroups=%5B%22NA%22%2C%22LGG_IDHmut-non-codel%22%5D

5) The current login page displays important text about logging in and includes the cBioPortal logo. The new portal needs to include all this same information & logo (and please remove the 'Login with OAuth 2.0' text). The overall formatting of the prod page is also much nicer, so can we just generally replicate that page in terms of content and style?
prod:
![image](https://github.com/cBioPortal/cbioportal/assets/10508276/17b0d355-86ff-4689-a615-69fcfb117f75)
beta:
![image](https://github.com/cBioPortal/cbioportal/assets/10508276/870bb2ce-fdeb-46b9-a2ac-7111294bf5d8)

6) Looks like we dropped support for logging in with Microsoft? Was that intentional? Do we have users using Microsoft auth? If so, we need to add it back.

7) Has this been tested in a fully authenticated portal?

7) When I signout in the prod portal, it brings me back to cbioportal.org. When I sign out in beta, it leaves me on this signout page:
![image](https://github.com/cBioPortal/cbioportal/assets/10508276/cb8fd97e-bde1-4a34-8b1f-a193496c77cb)
I think the prod behavior is better - users shoud be returned to cbioportal after logging out

**Comment by JREastonMarks** [comment]
1) Fixed - We added a new feature to let us turn on and off help on any site
2) We don't have this configured for Beta (That is a Public exclusive thing)
3) Not turned on
4) I see cytobans on both of these genes
5) Updated login. 
6) We don't have Microsoft configured yet. That should be soon.
7) Yes, MSK is testing it in PROD
8) Sign out takes you back to home page

**Comment by tmazor** [comment]
1. looks good!
2. ok
3. can you please turn it on so I can test those tabs too?
4. I still don't see a cytoband in prod. If you click the link I included above, you see one?
5. looks good!
6. -
7. great
8. looks good!

**Comment by tmazor** [comment]
3. I think binary/categorical group comparison is actually not released yet in prod? And I'm only seeing it because I turned on the setting to test at some point? Is that true @inodb @alisman ? 
4. this is clearly my browser being weird, don't worry about this - I can see the cytoband in other browsers/in a private window

**Comment by JREastonMarks** [comment]
Closed as I believe we have addressed all these issues
