### ISSUE TITLE
Bookmark filter for study subsets based on custom case selection does not work

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#10486]
To reproduce, try to paste in a long list of patient IDs using the Custom Selection button in the study view, then try to bookmark that cohort using the bookmark button. If the case list is short, this work, but it looks like it does not work for long case lists (bookmark seems truncated, and the shortened URL is not available). 

<img width="1098" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/11892704/343a1783-7b67-45d1-b0f4-333d27638a47">

**Comment by alisman** [comment]
@schultzn unfortunately both Bitly and the browser itself have a URL length limit that we are definately reaching here.  (We have a clever way of getting around this when we link to the patient page with cohort navigation).   The only solution for this would be to save these lists to Mongo and retrieve them using hashes.  We do this already for results view, so we could extend it here if necessary.

**Comment by schultzn** [comment]
Got it. If we offer the functionality, it should work. So we we should either disable the feature (maybe depending on the length of the resulting URL) or implement the same solution we have for the Results view. What do you think?

**Comment by alisman** [comment]
@schultzn agreed that it should at least not break.  i will add a limit.   if you think it's an important use case to be able to send around links to large adhoc sets of samples then we should do it.   i suppose virtual study also accomplishes the same thing?  maybe if the list is too long we give them option in the bookmark dialog to create a virtual study?

**Comment by alisman** [comment]
@schultzn another update.  i found a bug that was causing the limit to be much smaller than necessary.  with my PR we can now handle about 7k samples/patients without breaking.   i will put some messaging in as well when the length is too great.  we can discuss further to prioritize a solution to support bigger lists or direct users to virtual study
