### ISSUE TITLE
Targeted by drug interaction problems in network view

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#1048]
- Targeted by Drug interaction edges are not displayed in the right color (they should be orange as in the legend).
- Targeted by Drug interactions should not try to open up an SBGN view!

**Comment by istemi-bahceci** [comment]
@ugurdogrusoz should be fixed now

**Comment by ugurdogrusoz** [comment]
First part is fixed but I still see right-clicking on these edges trying to open up SBGN view?

**Comment by istemi-bahceci** [comment]
Fixed second part also.
