### ISSUE TITLE
Add select all button for columns on SV data

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10488]
Currently need to manually select all columns and state is not remembered

![image](https://github.com/cBioPortal/cbioportal/assets/1334004/ece40e29-8b3a-4cf2-ae29-1cccf1d7b63f)

https://www.cbioportal.org/results/structuralVariants?cancer_study_list=msk_impact_2017&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cstructural_variants%2Ccna&case_set_id=msk_impact_2017_cnaseq&gene_list=TMPRSS2&geneset_list=%20&tab_index=tab_visualize&Action=Submit

**Comment by shubhankarsharma876** [comment]
@inodb Can you assign this issue to me. I think I can fix this by providing a button to select all the columns as described above.

**Comment by alisman** [comment]
@shubhankarsharma876 please go ahead
