### ISSUE TITLE
Use PC2 beta service to get latest Paxtools in network view

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#1049]
Let’s use the PC2 service in the beta site to get the latest Paxtools (beta.pathwaycommons.org/pc2/) in the network view

**Comment by istemi-bahceci** [comment]
I'm getting a server side error when I try to use beta.pathwaycommons.org/pc2/ service.

![image](https://cloud.githubusercontent.com/assets/8645080/14599103/262f466e-055e-11e6-96b0-ec936202d303.png)

**Comment by istemi-bahceci** [comment]
This issue should be  fixed, Igor fixed server settings on PC side.
