### ISSUE TITLE
Padding adjustments required for "What's New" right navigation (Bullet Markers)

### ISSUE THREAD

**Issue by shubhankarsharma876** [cBioPortal/cbioportal#10507]
# Padding adjustments required for "What's New" right navigation (Bullet Markers)
***
<div align="center">
<img width="271" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/71379135/f52e3c5f-c518-4a69-b199-1fb1dbf03a00">
</div>

***

- The bullet markers are extending beyond the boundary. We can rectify this issue by making styling corrections. The misalignment affects the entire "What's New" block for all main headings. Can I make this ? @alisman

**Comment by alisman** [comment]
@shubhankarsharma876 yes please!  thanks

**Comment by shubhankarsharma876** [comment]
> @shubhankarsharma876 yes please!  thanks

@alisman Sorry the last suggested issue by you is still pending. Going little busy with the schedule but soon will fix all the issues. Including this one to.  Thank you!

**Comment by Chohankoti** [comment]
Hey there, @alisman I am interested to work on this, Is it possible to assign it to me

**Comment by olzhasmukayev** [comment]
@alisman 

Hello! Can I fix this issue?

**Comment by kartik20144** [comment]
I have gone through the documentation and codebase. I want to work on this issue. Please assign it to me. Thank You.
