### ISSUE TITLE
feature : "Clarify Selection Mechanism in 'Select Genomic Profiles' "

### ISSUE THREAD

**Issue by karan-joshi-1** [cBioPortal/cbioportal#10503]
For the 'Select Genomic Profiles' section, visual cues could be improved to indicate that multiple options are selectable, or if only one can be chosen, it should be made clear.
![Screenshot 2023-12-21 060053](https://github.com/cBioPortal/cbioportal/assets/128008084/d003688f-12fd-43aa-811a-62167481d1e8)

**Proposal**
we should have a tooltip ( like we have helping text for other section)  just below the  'Select Genomic Profiles' dynamically changing based on selection we have : if multiple suggest only one can be chosen or if a  singal selection has been made suggest multiple can be  chosen.
@alisman

**Comment by karan-joshi-1** [comment]
@alisman what do you think about this

**Comment by alisman** [comment]
@karan-joshi-1 thanks for this suggestion.  @tmazor can you weigh in on this?  to me the checkboxes already signify multiple selection (as opposed to radio buttons which are exclusive).

**Comment by tmazor** [comment]
Thanks for the suggestion @karan-joshi-1, but I agree with @alisman - to me the checkboxes are a clear indication that multiple selections are possible - and for many studies, multiple checkboxes will be selected by default, which also helps make that clear.

**Comment by alisman** [comment]
Thanks @tmazor.  And thanks @karan-joshi-1 for the idea.
