### ISSUE TITLE
Clicking within OncoKB tooltip on patient view initiates zoom into IGV viewer

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#10510]
To replicate try this case:
https://cbioportal.mskcc.org/patient?studyId=mskimpact&caseId=P-0098818

Hover over OncoKB icon for the FGFR2 events, then click on the Therapeutic Implications tab ... for some reason it activates the IGV track below and zooms into the genome. 

<img width="1142" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/11892704/ceffd8e6-7fd0-431c-80de-b0019585141a">

**Comment by onursumer** [comment]
Good catch! Seems like the action is recognized as a click on the row. Actually, clicking anywhere inside the tooltip triggers the same behavior. Also, this is not specific to OncoKB tooltip. Same thing happens with any other tooltip. We need to distinguish between clicking on the actual row and clicking inside a tooltip.
