### ISSUE TITLE
Trim unused functionality from menus and toolbar in SBGN network view

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#1052]
We should get rid of the functionality that we don't expect to be used (mostly curation abilities such as adding new nodes/edges to the network).

**Comment by ugurdogrusoz** [comment]
Functionality to get rid off from the menus (and corresponding tools from the toolbar):
- File > New, Load, Samples
- Edit > Select/Edit, Add X (all 4 add's)
- Help > How to Use

**Comment by istemi-bahceci** [comment]
Done.

**Comment by ugurdogrusoz** [comment]
Corresponding tools from the toolbar should also be deleted.
