### ISSUE TITLE
Mutational signatures broken

### ISSUE THREAD

**Issue by nr23730** [cBioPortal/cbioportal#10538]
The patient view of a patient with mutational signature data is currently broken:
```
{"type":"ErrorBoundary","log":"TypeError: /\\(([^)]+)\\)/.exec(...) is null","url":"https://www.cbioportal.org/patient?studyId=mbn_sfu_2023&caseId=BLGSP-71-06-00005"}
```
Example: https://www.cbioportal.org/patient?studyId=mbn_sfu_2023&caseId=BLGSP-71-06-00005

Tested on private and public v6.0.0.

I was able to find out that the function is located in `/src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts`

**Comment by inodb** [comment]
@nr23730 thanks for reporting! Should be fixed now
