### ISSUE TITLE
Incorrect placement of info boxes in SBGN network view

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#1053]
Incorrect placement of info boxes (when there are 3 or more; easy to reproduce). Metin thinks the original SBGN-ML model from Paxtools has this error. So, the fix needs to be done in Paxtools.

**Comment by istemi-bahceci** [comment]
This should be fixed, I've performed tests on local paxtools graph results, as soon as paxtools deployment of beta service of PC2 is updated we should be able to see the correct results
