### ISSUE TITLE
Comparison session issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#10553]
Reported by a user: https://groups.google.com/g/cbioportal/c/zCCPhq2H_go/m/CotvVZOcAAAJ

The following two sessions are not working:

- https://www.cbioportal.org/comparison?comparisonId=65a9a998b01fff74fbb75efd
- https://www.cbioportal.org/comparison?comparisonId=65a9a3de1095f74ff799d4e0

![image](https://github.com/cBioPortal/cbioportal/assets/840895/825db547-811d-4fb3-a789-63f6a7bdc6a9)

**Comment by JREastonMarks** [comment]
Associated Sentry Entry: https://memorial-sloan-kettering.sentry.io/issues/4889540871/?project=236782&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1

**Comment by alisman** [comment]
Problem is resolved by clearing cache.  Suggests that there's a problem with mechanism to clear cache after data update.
