### ISSUE TITLE
mvn install fails with issue on biojava3 and mskcc

### ISSUE THREAD

**Issue by Tcheutchoua-Steve** [cBioPortal/cbioportal#1058]
After following the installation procedures on the wiki, 
while running mvn -DskipTests -e -X clean install 

on the build from source menu page, had the following errors. 

[cbiobug.txt](https://github.com/cBioPortal/cbioportal/files/218261/cbiobug.txt)

**Comment by fedde-s** [comment]
This issue has already been reported in #1038, marking this one as a duplicate.

**Comment by Tcheutchoua-Steve** [comment]
Thanks for the info @fedde-s

**Comment by fedde-s** [comment]
I believe this issue has been resolved by 021400434bcd5789f51df4c59e8070e33f513abb
