### ISSUE TITLE
/tutorials broken in v6

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10584]
https://www.cbioportal.org/tutorials

Should go to:

https://docs.cbioportal.org/user-guide/overview/#tutorial-slides

**Comment by alisman** [comment]
@uklineale this would be good just to familiarize yourself with routing in spring.  @haynescd is the absolute MASTER of this so you can ask him for help!  it'll be a one-liner.  

Another thing you might research is how to configure spring 6 for an SPA (Single Page Application).   See if you can find any guidance on the internet about this.  We shouldn't have to ennumerate every route like we are currently doing.
