### ISSUE TITLE
Remove JSP files

### ISSUE THREAD

**Issue by JREastonMarks** [cBioPortal/cbioportal#10585]
Beginning in version 6.0.0 we have moved to using Thymeleaf and no longer need JSPs. These JSP files can now be removed from the source code. These files are located in src/main/resources/webapp/jsp folder.

**Comment by amanbhardwaj12072003** [comment]
Hey @JREastonMarks, I'm willing to work on this issue. Can you please let me know if I just need to delete them as is, or if you're expecting something else?

**Comment by JREastonMarks** [comment]
Thank you @amanbhardwaj12072003. I'll assign you the ticket and review your PR.

**Comment by JREastonMarks** [comment]
Thanks @amanbhardwaj12072003 for working on this

**Comment by amanbhardwaj12072003** [comment]
My pleasure @JREastonMarks, would love to continue my contributions. Thanks!
