### ISSUE TITLE
retrieve ndex tooltip information dynamically

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10595]
There is an endpoint to get information about the networks in ndex: https://iquery-cbio-dev.ucsd.edu/integratedsearch/v1/source.

We can use those to populate this tooltip rather than hardcoding it as it is now:

![image](https://github.com/cBioPortal/cbioportal/assets/1334004/84c7d31a-a0dc-4f86-a233-c61b0f093d2c)

See e.g. [this link](https://www.cbioportal.org/results/pathways?cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&pathways_source=NDEx%20Cancer%20Pathways)

**Comment by MrunalKashid02** [comment]
can i take this issue to start as i am beginner

**Comment by Veer0x1** [comment]
I would like to work on this issue.

**Comment by SAHU-01** [comment]
@inodb I was successful in dynamically populating that tooltip but regarding the hardcoded urls ; unlike the "name" and "number of networks"  I was'nt able to find exact matching urls in the endpoint, how do you suggest I move ahead with the urls ?

Here's what it looks like now, I've just added a "#" for the timing in place of the urls:
<img width="368" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/71656941/52a56989-6587-43ec-8c6b-4d78ae828e1d">
