### ISSUE TITLE
Can't view charts in the drop down menu after clearing all charts from study view page.

### ISSUE THREAD

**Issue by angelicaochoa** [cBioPortal/cbioportal#1060]
<img width="382" alt="screen shot 2016-04-13 at 10 52 22 pm" src="https://cloud.githubusercontent.com/assets/15623749/14515818/4350d000-01cb-11e6-92c2-f6d7dbaca039.png">

**Comment by zhx828** [comment]
This issue should be solved in https://github.com/cBioPortal/cbioportal/pull/1405
