### ISSUE TITLE
remove gene track in oncoprint feature

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10612]
It's currently possible to remove clinical tracks:

![image](https://github.com/cBioPortal/cbioportal/assets/1334004/97c14119-cee9-402d-9120-636388117a98)

But not gene tracks:

![image](https://github.com/cBioPortal/cbioportal/assets/1334004/0a6b0901-5b7c-4c58-a594-083ac27d544b)

Can we make it possible to remove gene tracks? Maybe ok if results view does not update?

**Comment by VivekJaiswal18** [comment]
Can I be assigned this issue.

**Comment by kushalnareda** [comment]
Would it be possible to elaborate on this more
do you want to have one track beside the clinical track its a little hard to understand
![Screenshot 2024-02-23 at 9 23 13 PM](https://github.com/cBioPortal/cbioportal/assets/128476254/5edfc886-6635-4089-af06-e1a37c968862)
