### ISSUE TITLE
/news route should go to configured news page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10632]
e.g.

cbioportal.org/news -> https://docs.cbioportal.org/news/

genie.cbioportal.org/news -> https://docs.cbioportal.org/news-genie/

I guess the GENIE example might change in the future (as we might have a single instance), but it would still be useful that the news route would go to the configured news page for other local installations

There might be a configuration property already as the current News button on genie.cbioportal.org does go to the correct page

**Comment by SAHU-01** [comment]
@inodb  in the **_application.properties_** file, to the _**skin.documentation.news**_ property, the .md file assigned based on the instance [ex. News.md for cbioportal.org/news  and News-Genie.md for genie.cbioportal.org/news], is likely the configuration property currently used.
A proof of which can be found in [here](https://docs.cbioportal.org/deployment/customization/customizing-your-instance-of-cbioportal/).
And this PR [4342](https://github.com/cBioPortal/cbioportal-frontend/pull/4342) does the rest of frontend task.

For any local instance as long as the documentation is followed, I believe this logic would work, do you still suggest setting up of a new configuration for /news route?

**Comment by inodb** [comment]
@SAHU-01 Great digging! Thank you!

I see, so it's handled by the fronted atm, see e.g. https://frontend.cbioportal.org/news. But doesn't work when accessing thru the backend, https://cbioportal.org/news

I filed a PR for this, so it just passes it on to be handled at the frontend: https://github.com/cBioPortal/cbioportal/pull/10658
