### ISSUE TITLE
v6 embedding in MSK CIS not working

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10649]
- [x] Users see a `ReferenceError` for the `postLoad` function (couldn't get full error log for this). I'm guessing the `postLoadForMskCIS` (this prolly only shows up because the api-legacy page is missing)
- [ ] the legacy API to map DMP to the proper study has moved from `/api-legacy/cis/P-0047549-T01-IM6` to `/cis/P-0047549-T01-IM6` (the API was enabled on beta in [this k8s config](https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/commit/a95e575cb81ff67a4173f0c024ba41b7f045123d))

**Comment by JREastonMarks** [comment]
@inodb how about "/darwin/{sampleid}" should that also be "/api-legacy/darwin/{sample}"?

**Comment by inodb** [comment]
@JREastonMarks Thanks! Yes that's correct
