### ISSUE TITLE
Don't show NA on Study View by default

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10661]
Many charts are hard to read because the NA bar is large, prolly better to hide them by default

Alternatively we can e.g. show NAs by default when more than X% has data

**Comment by amanbhardwaj12072003** [comment]
Hi @inodb, Looking forward to working on this issue. Can you please let me know how to reproduce this issue? Also which charts are you specifically talking about?

**Comment by Paras20222** [comment]
Hi @inodb , could you please explain how to reproduce this issue?

**Comment by nouralmulhem** [comment]
Hey @inodb would like to tackle this one, would you please provide us with how to reproduce this?
