### ISSUE TITLE
Mutational Signatures Improvements

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10675]
- [x] Lot of whitespace initially between chart and interactable component. Maybe we can have some expand-like animation of the bottom chart, so the table controls are more visible on page load?

**Comment by TJMKuijpers** [comment]
3) We could make the margin dynamic to add a bit of white space to the plot (when % is selected)
4) We can hide the chart element unless a signature is clicked. By hiding the element, the white space between the top of the figure and the table should be decreased. I believe we show text underneath the plot saying "Select a signature from the table to show the reference plot". Only have to make sure that users know that they can click the table to show the reference plot.
5) This is probably how the charts in study view are implemented. We did not touch upon it but maybe it is possible to conditionally add information?

**Comment by inodb** [comment]
@MatthijsPon

For 2: Could this be because the SBS count includes synonymous and noncoding variants? I.e. it is not a count of the mutations imported into cBioPortal but rather a total count of what's in the MAF?

**Comment by MatthijsPon** [comment]
@inodb Yes, that explains the difference between 259 and 219. I used the whole MAF without further filtering for [SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator?tab=readme-ov-file) to get the counts. It might be good to add a disclaimer of sorts to the total counts? The 9/50 I cannot explain, I think that is caused by the frontend. @TJMKuijpers Do you know?

**Comment by tmazor** [comment]
New comment:
<img width="315" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/10508276/13a83bea-1a38-4355-ae10-68258a5b2d65">

Remove the tooltip

Change 'Variant Class' to 'Mutational Signature Type'

Update the data so the text in the dropbox isn't dependent on the tooltip:
eg Mutations Signatures SBS --> Single Base Substitutions (SBS), COSMIC

**Comment by tmazor** [comment]
Add the option to set the y-axis - default to 100% still good, but let the user change that if all percentages are small

**Comment by inodb** [comment]
@alisman offered to help with slider
