### ISSUE TITLE
Update mysql:mysql-connector-java Version

### ISSUE THREAD

**Issue by JREastonMarks** [cBioPortal/cbioportal#10679]
Currently the mysql:mysql-connector-java 8.0.16 and needs to be updated to address security issues with that version of the connector.

**Comment by amanbhardwaj12072003** [comment]
Hey @JREastonMarks, I'm wondering if we just need to change the "mysql-connector-java" version to the latest one? Thanks!

**Comment by JREastonMarks** [comment]
If not the latest something with no listed vulnerabilities found here:
https://mvnrepository.com/artifact/mysql/mysql-connector-java

**Comment by amanbhardwaj12072003** [comment]
Sure @JREastonMarks, but where is version 8.0.16 stated in the pom.xml? In the application.properties it's 5.1.48 instead. Please correct me if I'm wrong. Thanks!
<img width="1440" alt="Screenshot 2024-03-01 at 11 02 01 PM" src="https://github.com/cBioPortal/cbioportal/assets/95973608/1f5d3ea1-80e1-4eef-9161-a8b9c4e3e889">

**Comment by JREastonMarks** [comment]
That's fine. We can still try moving it up to a higher version number.

**Comment by amanbhardwaj12072003** [comment]
Okay, so will it be fine if I just update it to a version with no listed vulnerabilities and make a PR?

**Comment by JREastonMarks** [comment]
Yeppers, thank you.

**Comment by JREastonMarks** [comment]
Merged, thanks @amanbhardwaj12072003 !
