### ISSUE TITLE
Studyview clinical data tab lists Overall Survival column twice, but not OS_MONTHS column

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#10696]
This would seem to suggest that OS_MONTHS could NEVER have made it to table:
```
            // filter out survival attributes (only keep 'OS_STATUS' attribute)
            // create a dict which contains all survival attribute Ids that will be excluded from study view
            // get all survival attribute Ids into a dict
            let survivalAttributeIdsDict = createSurvivalAttributeIdsDict(
                this.survivalClinicalAttributesPrefix.result
            );
            // omit 'OS_STATUS' from dict
            survivalAttributeIdsDict = _.omit(survivalAttributeIdsDict, [
                'OS_STATUS',
            ]);

            return Promise.resolve(
                _.filter(
                    this.clinicalAttributes.result,
                    attribute =>
                        !(
                            attribute.clinicalAttributeId in
                            survivalAttributeIdsDict
                        )
                )
            );
```

**Comment by alisman** [comment]
@inodb the curation team has reported an issue with study view clinical data tab.  1) Survival status appears twice.  2) OS_MONTHS doesn't appear--where they say it once did appear.   The code above leads me to believe that it never did appear.   Do you have any memory about this?

![image](https://github.com/cBioPortal/cbioportal/assets/186521/585dc9d5-00a1-43e4-b462-5c2c55048bf6)

**Comment by alisman** [comment]
We have decided to allow OS_* for the columns on the clincialda data table.   But continue to disallow them for the charts.
```
_.omit(survivalAttributeIdsDict, [
                'OS_STATUS',
            ]);
```

**Comment by alisman** [comment]
@gblaih can you see why Overall Survival Status disapears from this https://www.cbioportal.org/study/clinicalData?id=laml_tcga?

Results in e2e error

**Comment by inodb** [comment]
@sbabyanusha does this fix the issue you found?
