### ISSUE TITLE
Numeric entries can be added to the Search Query

### ISSUE THREAD

**Issue by ashishjain1988** [cBioPortal/cbioportal#107]
There is no check for the numeric entries and if we search some number the user interface is crashing.

**Comment by jjgao** [comment]
Confirmed. Should be warning messages.

![image](https://cloud.githubusercontent.com/assets/840895/11066365/e9cf3cb0-8795-11e5-8691-1d91cb54c8ab.png)

**Comment by jjgao** [comment]
@adamabeshouse ?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/888
