### ISSUE TITLE
query using patientids issue

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#1073]
I am dissecting the URL's parameters and I encountered the `patient_case_select` which can be `patient` or `sample`.
If I use `case_set_id=-1`, `case_ids=SAMPLE1` and `patient_case_select=sample` it works fine. 
If I switch to `case_set_id=-1`, `case_ids=PATIENT1` and `patient_case_select=patient` it does not work. 

Actual example:
http://www.cbioportal.org/index.do?cancer_study_id=acc_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&data_priority=0&case_set_id=-1&case_ids=TCGA-OR-A5LT-01&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=ZFPM1&tab_index=tab_visualize&Action=Submit
is fine

http://www.cbioportal.org/index.do?cancer_study_id=acc_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&data_priority=0&case_set_id=-1&case_ids=TCGA-OR-A5LT&patient_case_select=patient&gene_set_choice=user-defined-list&gene_list=ZFPM1&tab_index=tab_visualize&Action=Submit
is not. 

Should this have worked? If not, what should the query have looked like to query using a patientId?

**Comment by zheins** [comment]
The reason this doesn't work is that on the query page when a patient ID is selected, it is actually being converted into its sample id(s) before the query is made. There is a bit of code cleanup that needs to happen in the QueryBuilder class to allow patient ids to be sent directly in the query. 

@jjgao what do you think?

**Comment by jjgao** [comment]
I am closing this since this issue is likely out of date. Please feel free to reopen with new urls.
