### ISSUE TITLE
Add a link to cbioportal newsletter to the right bar on the home page

### ISSUE THREAD

**Issue by AnikaBongaarts** [cBioPortal/cbioportal#10741]
Add text under "What is new" section with following text: 
"Read the latest cBioPortal Newsletter! Subscribe via [LinkedIn](https://www.linkedin.com/pulse/april-update-hello-cbioportal-community-cbioportal-22vle/) or [Google Groups](https://groups.google.com/g/cbioportal-news)"

A  very rough draft can be found in the image attached.
For the two links make two bottons 1 for email subscribe and one for LinkedIn subscribe

![image (6)](https://github.com/cBioPortal/cbioportal/assets/149793785/f466996f-e1f8-46bd-9759-7c48677f9bd1)

**Comment by SURAJ-SHARMA27** [comment]
@AnikaBongaarts mam can assign this issue to me
