### ISSUE TITLE
png download is broken for group comparison clinical data

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10742]
https://www.cbioportal.org/results/comparison?cancer_study_list=paad_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=rna_seq_v2_mrna_median_Zscores&case_set_id=paad_tcga_pan_can_atlas_2018_rna_seq_v2_mrna&gene_list=CSF1R%253AEXP%253E1%250ACSF1R%253AEXP%253C0&geneset_list=%20&tab_index=tab_visualize&Action=Submit&comparison_subtab=clinical

**Comment by ADTmux** [comment]
Hey, can I work on this?

**Comment by alisman** [comment]
@ADTmux yes please do!

**Comment by ADTmux** [comment]
Is the issue still open?
