### ISSUE TITLE
Failed to Load Sample Cancer Study

### ISSUE THREAD

**Issue by serlej** [cBioPortal/cbioportal#1075]
Several issues 
1. $PORTAL_HOME/core/src/main/scripts/cbioportalImporter.py --jvm-args "-Dspring.profiles.active=dbcp -cp $CONNECTOR_JAR:$CORE_JAR" --command import-study --meta-filename portal-study/meta_study.txt **Missing property files** **Documentation issue**
2. This version of the portal is out of sync with the database. You must run the **database migration script **located at PORTAL_HOME/core/src/main/scripts/migrate_db.py before continuing
Portal Version of DB: 1.1.0
DB Version: 0.0.0

**Comment by zheins** [comment]
Hi @serlej. If you'd like an immediate fix for issue 2, try running the sql at https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/resources/db/migration.sql on your database or use the python script mentioned. We have not updated our downloadable seed database with the recent schema changes that have been made - this should be resolved soon.

Do you have more details about issue 1? What specific error are you getting?

**Comment by serlej** [comment]
Thanks Zachary. It worked. It looks like wiki is pretty old and does not match current code on loading of the data.
