### ISSUE TITLE
Show summary stats on homepage

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10755]
- Currently we list this when loading the page:
    <img width="247" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/1334004/2c3937c1-52e4-4c31-9149-916be2dc5b8e">
    Maybe we can list: total nr of studies like this + total number of samples instead:
<img width="1039" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/1334004/dbecc74b-87ce-4bfb-86d0-182966a46b1f">
- Once you select something it should reflect the selection state as it currently does, e.g.:
<img width="702" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/1334004/d771772b-341b-4809-8496-5b62c03f983f">

**Comment by Hackmey** [comment]
Hey! Can you please specify which file I have to work on.

**Comment by inodb** [comment]
Thanks so much for offering @GarvitDadheech! Go for it - happy to assist! Note that in general we don't assign tickets outside of core contributors
