### ISSUE TITLE
in study view on mouseover of entire row show looking glass icon

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10762]
On Study View Page: https://www.cbioportal.org/study/summary?id=msk_impact_2017

<img width="371" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/1334004/40c0ef17-36ef-44df-817f-389f08f2011a">

The current icon only shows up when hovering over the gene name, but it does not show up when e.g. hovering near the checkbox icon. Let's change this to show the icon when hovering over any part in the row

**Comment by GarvitDadheech** [comment]
Hey @inodb , I want to solve this issue. Can you please assign it to me ?

**Comment by arishta-dev** [comment]
Hi @inodb I have put up a fix for this issue : https://github.com/cBioPortal/cbioportal-frontend/pull/5059
