### ISSUE TITLE
Use NP consistently in download tab

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10789]
For mutations data it is currently listed as NS (not sequenced) instead of NP (not profiled), but for CNA and SV it shows NP. Not profiled and not sequenced are synonyms. See this [link](https://www.cbioportal.org/results/download?cancer_study_list=msk_impact_2017&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cstructural_variants%2Ccna&case_set_id=msk_impact_2017_cnaseq&gene_list=SOS1%2520EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit):

![image](https://github.com/cBioPortal/cbioportal/assets/1334004/e89fbefa-444f-417c-a61a-9fee90d52e84)

e.g. mut:

```
DY_ID	SAMPLE_ID	SOS1	EGFR
msk_impact_2017	P-0000901-T01-IM3	NS	WT
```

vs cna:

```
STUDY_ID	SAMPLE_ID	SOS1	EGFR
msk_impact_2017	P-0000901-T01-IM3	NP	0
```

vs SV:

```
STUDY_ID	SAMPLE_ID	SOS1	EGFR
msk_impact_2017	P-0000901-T01-IM3	NP	NA
```

Discussion point: should SV also show WT like mut?

**Comment by vkonga** [comment]
Hi @inodb. As I understood, in mutations column (EGFR values should change to NP). I am interested to work on this good first issue.

**Comment by arishta-dev** [comment]
hi @inodb I have put up a PR to solve this issue:
please review https://github.com/cBioPortal/cbioportal-frontend/pull/5057
Thanks!
