### ISSUE TITLE
Percentage altered incorrectly displays 0% on small number of samples

### ISSUE THREAD

**Issue by zheins** [cBioPortal/cbioportal#1078]
![image](https://cloud.githubusercontent.com/assets/10240498/14612803/2461b6d8-0567-11e6-8ba2-e8a3f2def71d.png)

Should this maybe be displayed as "<1%"?

**Comment by jjgao** [comment]
Maybe when it's <3%, we should use fraction e.g. 0.3%.

**Comment by adamabeshouse** [comment]
For both the oncoprint and the header?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1203
