### ISSUE TITLE
Portal homepage fails when cancer type "ALL" is not present

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1083]
The code https://github.com/cBioPortal/cbioportal/blob/rc/core/src/main/java/org/mskcc/cbio/portal/util/internal/AccessControlImpl.java#L88 adds a dummy "all" cancer study with "all" cancer type to the cancer study list. This potentially conflicts with "ALL (Acute Lymphoid Leukemia)". I also causes an exception in the code at https://github.com/cBioPortal/cbioportal/blob/rc/core/src/main/java/org/mskcc/cbio/portal/servlet/PortalMetaDataJSON.java#L248 when the table `type_of_cancer` does not have a record for cancer type "all".

**Comment by pieterlukasse** [comment]
@n1zea144 : seems to be old code. Do we really need this dummy record "all" to be added on the fly? 

Seems to be a (partial) security issue as well since "Acute Lymphoid Leukemia" cancer type is added to the map `visibleTypeOfCancerMap` regardless of their access rights to studies of this cancer type.

**Comment by jjgao** [comment]
@pieterlukasse do we still have the problem?

**Comment by pieterlukasse** [comment]
@jjgao the code is still there in `rc`. @n1zea144 can you please check?

**Comment by jjgao** [comment]
Is this the same as https://github.com/cBioPortal/cbioportal/issues/2459? Is it still a bug?
