### ISSUE TITLE
Explain gene lists used for "Mutated Genes" and "CNA Genes" tables on study view

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1086]
The "Mutated Genes" and "CNA Genes" tables on the study view need a little info icon that describes that we only look at cancer genes in these tables. We also need to make that list available for viewing and download somewhere.

**Comment by jjgao** [comment]
@zhx828 @yichaoS could you add a link to the gene list. I remember @yichaoS has implemented a page of all cancer genes.

**Comment by zhx828** [comment]
@jjgao @schultzn @yichaoS is this page up to date? http://www.cbioportal.org/cancer_gene_list.jsp Is there any difference between the public and private instances?

**Comment by zhx828** [comment]
Just talked to JJ, we can link to cancer_gene_list.jsp for now. Later on, this page will be updated.
