### ISSUE TITLE
curated non-redundant studies has mixed genome builds

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#10883]
I selected the curated non-redundant studies and everything shows up with a warning. Looks like there are 2 GRCh38 studies included in the list. I vaguely remember a conversation in which we said to exclude GRCh38 studies from the curated non-redundant list for this reason, but perhaps others remember better? @ritikakundra @schultzn @inodb 

![image](https://github.com/cBioPortal/cbioportal/assets/10508276/14dffdf8-3b74-4f18-a2f8-01fd1c3783a1)

![image](https://github.com/cBioPortal/cbioportal/assets/10508276/cf1ae69f-58f6-4020-a097-121d5d7920b9)

**Comment by inodb** [comment]
Fixed in https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/commit/d207b95944ff6982169cce198f43768ef5e40508. CC @sbabyanusha @rmadupuri @ritikakundra
