### ISSUE TITLE
Importer broken

### ISSUE THREAD

**Issue by holtgrewe** [cBioPortal/cbioportal#1091]
When importing the `brca` study from the public data set list with current `rc` version.

```
ERROR: brca/tcga/meta_RNA_Seq_v2_expression_median_normals.txt: Could not determine the file type. Please check your meta files for correct configuration.; value encountered: 'genetic_alteration_type: MRNA_EXPRESSION_NORMALS, datatype: Z-SCORE'
Traceback (most recent call last):
  File "/app/core/src/main/scripts/importer/cbioportalImporter.py", line 328, in <module>
    main(parsed_args)
  File "/app/core/src/main/scripts/importer/cbioportalImporter.py", line 317, in main
    process_directory(jvm_args, study_directory)
  File "/app/core/src/main/scripts/importer/cbioportalImporter.py", line 173, in process_directory
    raise RuntimeError('Invalid meta file: ' + f)
RuntimeError: Invalid meta file: brca/tcga/meta_RNA_Seq_v2_expression_median_normals.txt
```

**Comment by fedde-s** [comment]
The `rc` branch has recently incorporated a major update in [the data loading scripts](https://github.com/thehyve/cbioportal/wiki/Data-Loading), and the format of the data files has changed. See [this wiki page on the new data format](https://github.com/thehyve/cbioportal/wiki/File-Formats) and  [this page on the differences with the old format](https://github.com/thehyve/cbioportal/wiki/Data-Loading-:-What-You-Need-To-Change) for details—these pages will be incorporated into the main documentation when the release candidate becomes a release. Unfortunately, this means that not all data files formatted for the current release are accepted by the new one. The new data loading pipeline includes a validation script that can point out any (potential) errors in data sets prior to loading, it is documented on [this page](https://github.com/thehyve/cbioportal/wiki/Using-the-dataset-validator).

**Comment by holtgrewe** [comment]
Thanks for the information!

**Comment by holtgrewe** [comment]
For the record, (some of) the public zips that can be downloaded have `Entrez_Gene_Id` set to `0`. A mapping between HUGO and Entrez ID can be downloaded [here](http://tinyurl.com/zyoc54t).

The following snippet can be used for fixing the `data_mutation_extended.txt` files

```
#!/usr/bin/env python3

import sys

HUGO_TO_ENTREZ = "hugo_to_entrez.txt"

mapping = {}
with open(HUGO_TO_ENTREZ, 'rt') as f:
    for line in f:
        if not line:
            continue
        arr = line.strip().split('\t')
        if len(arr) != 2:
            continue
        mapping[arr[0]] = arr[1]

for line in sys.stdin:
    arr = line.strip().split('\t')
    if arr[0] in mapping:
        arr[1] = mapping[arr[0]]
    line = '\t'.join(arr)
    print(line, file=sys.stdout)
```

**Comment by fedde-s** [comment]
cBioPortal (at least the rc version) already does fall back to using the gene symbol column if no Entrez identifier is given, and since [the MAF specification](https://wiki.nci.nih.gov/display/TCGA/Mutation+Annotation+Format+%28MAF%29+Specification) does sort of define '0' to mean ‘Unknown’ and more people seem to use it as such, I was already making a fix to fall back to the symbol in that case too. I will suggest it for merging into the rc branch soon.

**Comment by holtgrewe** [comment]
Is there a plan yet when the public data zips will be upgraded to the new data format?

**Comment by fedde-s** [comment]
@n1zea144, can you comment on this question?
