### ISSUE TITLE
label alignments in new OncoPrint

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1092]
Nice work on the new OncoPrints - they look great in the new pancanatlas portal!!!

A few tiny requests:
- Can you line up the gene symbol with the frequency?
- in the legend, can you line up the label and the vertical center of the glyph?

the frequencies look nice and crisp, but the gene symbol does not - why?
Also, is there any way you can make the actual oncoprint slightly crisper?

![image](https://cloud.githubusercontent.com/assets/11892704/14724868/b74ad778-07e6-11e6-9951-8b012dd9fa8e.png)

**Comment by adamabeshouse** [comment]
Are the crispness issues (labels, oncoprint) only on retina displays? If so, it's related to a rendering property called devicePixelRatio, I'll look into fixing this.

**Comment by schultzn** [comment]
It could be - I don't think I have a non-retina display to test on.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1165

addresses some of the issues.

Still to address: label alignment and oncoprint crispness

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1185 oncoprint crispness done!
