### ISSUE TITLE
[Mutations tab] add gene column to downloaded file from mutations table

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#10932]
Currently gene name is not in the table. After downloading data for multiple genes, you would have to figure out which file is for which gene. There are two options - either would work:
1. add a gene column into the downloaded file
2. name the file with gene

Option 1 would be preferable (e.g. users may want to combine data together) if it won't add too much technical complexity.

**Comment by charanbhatia** [comment]
@jjgao @heuermh can you assign this issue to me?

**Comment by chandanSahoo-cs** [comment]
can you assign this issue to me

**Comment by singhsayan** [comment]
Hi @jjgao,

I’m interested in taking on this issue to add a gene column to the downloaded mutation files. My approach would involve using Node.js and Express for handling the server-side functionality and leveraging the fs module for file manipulation.

I believe this will enhance data usability for users. If this aligns with the project’s direction, please assign the issue to me. Looking forward to your feedback!

Best,
Sayan

**Comment by dakshika-chaudhary** [comment]
I am interested please assign this issue to me

**Comment by arishta-dev** [comment]
Hi @jjgao,
I am a new contributor here. 
I have put a PR for the approach 1 (adding a new Gene column). I have added necessary details and screenshot of before/after change.  
https://github.com/cBioPortal/cbioportal-frontend/pull/5049
Please do let me know if anything else is required from my end. Thanks!

**Comment by LakshayPuhal** [comment]
I would like to work in this issue.
