### ISSUE TITLE
Frontend dev docs

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10947]
For the frontend explain one needs to start the browser in insecure mode to enable opening localhost with a self signed certificate

**Comment by Priyankagarai** [comment]
Hi @inodb 
I would like to work on this issue. Could you please assign it to me?
Additionally, I would appreciate it if you could provide more details or clarify the issue

**Comment by dubeanant** [comment]
Hi @inodb,
I have started working on this issue, so please assign it to me.

**Comment by sanyakapoor27** [comment]
"docs/development/Build-Different-Frontend.md" just wanted to confirm would this be the correct file path?

**Comment by dakshika-chaudhary** [comment]
I would like to contribute to this please assign this issue to me, @inodb
