### ISSUE TITLE
Info box placement issue (Paxtools) in SBGN network view

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#1094]
To reproduce:
- Select "TP53 and MDM2/4 alterations in GBM" under Example Queries
- Select interaction from TP53 to PTEN (type controls-expression-of) and pop up its SBGN view
- Both of the two info boxes of the nucleic acid feature in Cytosol named "PTEN mRNA" are placed at the top of the node but overflowing node boundaries.
![infobox-placement-bug](https://cloud.githubusercontent.com/assets/3874988/14734108/ebdcf70c-0870-11e6-9349-eaea14295c82.png)

**Comment by ugurdogrusoz** [comment]
Here is another (more serious) problem with info box placement:
- Select "TP53 and MDM2/4 alterations in GBM" under Example Queries
- Select interaction from CHEK1 to HUS1 (type in-complex-with) and pop up its SBGN view
- The macromolecule named p-5S-BRCA1 in one of the big complexes in nucleoplasm has a total of 6 state variables but only one of them is shown and it's in a completely irrelevant location (see selected node its seleced infox in the attached screenshot). There is one other such info box placed incorrectly in the same map.
![infobox-placement-bug-2](https://cloud.githubusercontent.com/assets/3874988/14734452/334cff90-0873-11e6-824b-d44f8764942c.png)

**Comment by istemi-bahceci** [comment]
Paxtools instance on beta service was not up to date, Igor made another deployment and everything should be fine now.
