### ISSUE TITLE
Minimize number of SBGN network view related files

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#1095]
Onur says we should reduce the number of SBGN network view related files. Perhaps we could minify using gulp? @onursumer or @jjgao could guide?

**Comment by onursumer** [comment]
I think [sbgnviz](https://github.com/iVis-at-Bilkent/sbgnviz-js) already has gulp support, but the current PR  #941 has source files, instead of minimized binaries.

**Comment by ugurdogrusoz** [comment]
As discussed yesterday, let's first have an attempt to separate the network view into a different repository. If successful, minimized versions could be pushed to the portal every now and then.

**Comment by ugurdogrusoz** [comment]
I think this is obsolete, now that we plan to migrate the network views to React.
