### ISSUE TITLE
Crash on network query

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#1096]
@pieterlukasse discovered the following error:

http://www.cbioportal.org/alpha/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=brca_tcga_rna_seq_v2_mrna_median_Zscores&Z_SCORE_THRESHOLD=2.0&genetic_profile_ids_PROFILE_PROTEIN_EXPRESSION=brca_tcga_rppa_Zscores&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_all&case_ids=&patient_case_select=sample&gene_set_choice=prostate-cancer%3A-ar-and-steroid-synthesis-enzymes-%2830-genes%29&gene_list=AKR1C3+AR+CYB5A+CYP11A1+CYP11B1+CYP11B2+CYP17A1+CYP19A1+CYP21A2+HSD17B1+HSD17B10+HSD17B11+HSD17B12+HSD17B13+HSD17B14+HSD17B2+HSD17B3+HSD17B4+HSD17B6+HSD17B7+HSD17B8+HSD3B1+HSD3B2+HSD3B7+RDH5+SHBG+SRD5A1+SRD5A2+SRD5A3+STAR&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&#network

**Comment by ugurdogrusoz** [comment]
Was due to a layout bug. Should be fixed with the next pull request and merge.

**Comment by pieterlukasse** [comment]
Feel free to close it if you were able to reproduce it and fix it.
