### ISSUE TITLE
Add custom data datatype option in plots tab

### ISSUE THREAD

**Issue by gblaih** [cBioPortal/cbioportal#10970]
Currently, custom data is part of the Clinical Attribute datatype in the plots tab. Add a separate custom data datatype option for custom data.

![image](https://github.com/user-attachments/assets/215c17e7-e1ef-41ea-af3b-ef4cd714da9e)

**Comment by Andrew1031** [comment]
Hi, I would love to contribute to cbioportal. Can I work on this as my 1st issue?
