### ISSUE TITLE
Network view, "View --> Remove Highlights" bug

### ISSUE THREAD

**Issue by ozgunbabur** [cBioPortal/cbioportal#1098]
On the network view, when I click View --> Remove Highlights, all the genes' genomic data (large circles) becomes displayed. And after that, the only way to hide them again is to select and deselect.

**Comment by istemi-bahceci** [comment]
Could not reproduce this on Ubuntu 14.04 using chromium browser with the following query:  
![image](https://cloud.githubusercontent.com/assets/8645080/14967190/cc95524e-10be-11e6-936b-2f3f5bedfb57.png) . @ozgunbabur  Could  you give some details about environment, browser and the query that you are using ?

**Comment by ozgunbabur** [comment]
You are right, it does not happen all the time. Here is how to get the bug:

1. Do what you did (same dataset and same gene set).

2. Go to the network tab and select RB1 and BRCA1 together, pressing shift key.

3. Do View --> Highlight Neighbors and View --> Remove Highlights in sequence.

4. Didn't you get the bug? Then continue doing steps 2 and 3 with some other gene pairs. Sometimes it takes a long time the bug to appear. But once it happens, it happens all the time.
