### ISSUE TITLE
Network view, drugs are not FDA approved

### ISSUE THREAD

**Issue by ozgunbabur** [cBioPortal/cbioportal#1099]
I noticed that in the network view, if I choose to display drug target relations, all the drugs come with a white background indicating they are not FDA approved. However, there should be at least some FDA-approved drugs when I have certain genes in my view like EGFR.

Also all drugs have a "n/a" tooltip text. If this is not due to a bug, maybe not displaying a tooltip text is better than displaying n/a.

**Comment by istemi-bahceci** [comment]
This issue is fixed, will be included in next pull request.
