### ISSUE TITLE
Network view, about navigation to detailed view

### ISSUE THREAD

**Issue by ozgunbabur** [cBioPortal/cbioportal#1100]
When I left-click on an edge in the network view, the edge is selected. When I right-click on that edge, a new window opens with a detailed view about this edge, but the edge on the simple view is not selected.

I think the edge should be selected with both clicks because after I navigate to the detailed view and come back to the simple view, I am losing which edge was right-clicked.

**Comment by istemi-bahceci** [comment]
I've added this functionality, It will be included in next pull request.
