### ISSUE TITLE
Clickhouse mutation profile has 5 fewer samples

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#11016]
https://rfc80-msk.cbioportal.aws.mskcc.org/study/summary?id=gbc_msk_chile_2021%2Cblca_mskcc_solit_2014%2Cblca_tcga

Mutations profile has 5 fewer samples than it used to.

**Comment by alisman** [comment]
@onursumer  this is sql which is returning mutation=255 when legacy returns 260.   we need to figure who's right.
```
SELECT
    replaceOne(gp.stable_id, concat(sgp.cancer_study_identifier,'_'), '') AS value,
    gp.name AS label,
    count(distinct sgp.sample_unique_id) AS count
FROM sample_to_gene_panel_derived sgp
         JOIN sample_derived sd ON sgp.sample_unique_id = sd.sample_unique_id
         JOIN sample_profile sp ON sd.internal_id = sp.sample_id
         JOIN genetic_profile gp ON sp.genetic_profile_id = gp.genetic_profile_id
WHERE
        sgp.sample_unique_id IN (

        SELECT sample_unique_id
        FROM sample_derived
        WHERE cancer_study_identifier IN
              (
                  'gbc_msk_chile_2021'
                  )
    )
  AND sgp.alteration_type = 'MUTATION_EXTENDED'
  --AND gp.genetic_alteration_type = 'MUTATION_EXTENDED'
GROUP BY gp.stable_id, gp.name, sgp.cancer_study_identifier





```

**Comment by onursumer** [comment]
We have 255 samples for the `gbc_msk_chile_2021_mutations` genetic profile. The query below returns `255` both for clickhouse and mysql

```SQL
SELECT
    count(*) as SAMPLE_COUNT
FROM sample_profile
JOIN genetic_profile ON sample_profile.GENETIC_PROFILE_ID = genetic_profile.GENETIC_PROFILE_ID
WHERE genetic_profile.STABLE_ID = 'gbc_msk_chile_2021_mutations'
```

The [legacy SQL](https://github.com/cBioPortal/cbioportal/blob/f7fdc1a4e5247d5b07066c1f4d17b5e9a0089f0b/src/main/resources/org/cbioportal/persistence/mybatis/GenePanelMapper.xml#L119) to get gene panel data for the profiles returns `260` for all 3 profiles:

![gene_panels](https://github.com/user-attachments/assets/331cecda-76c5-4331-84c1-f3ecaa673142)

But, actually this SQL also marks what's profiled or not:

https://github.com/cBioPortal/cbioportal/blob/f7fdc1a4e5247d5b07066c1f4d17b5e9a0089f0b/src/main/resources/org/cbioportal/persistence/mybatis/GenePanelMapper.xml#L21

Filtering for `profiled` results in `255` profiled samples:

![filter_for_profiled](https://github.com/user-attachments/assets/1de26282-3acd-4848-af9a-d17ebb7c9279)

In legacy implementation, probably we forget to use the `profiled` info further along the process.
