### ISSUE TITLE
Use MySQL8 for Docker Compose

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#11022]
Upgrade our Docker Compose setup to use MySQL8: https://github.com/cBioPortal/cbioportal-docker-compose/blob/master/.env#L3

**Comment by kesrishubham2510** [comment]
Hi @inodb, if no one is looking into this, can you please assign this to me ?

**Comment by inodb** [comment]
@kesrishubham2510 thanks so much for offering! Someone has just started working on this, but lmk if you see any other tickets you're interested in
