### ISSUE TITLE
FUSION data is not retrieved by new data manager/oncoprint

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1102]
Fusion data is present in some studies, like prostate cancer studies (e.g. [see this query](http://www.cbioportal.org/index.do?cancer_study_list=prad_su2c_2015&cancer_study_id=prad_su2c_2015&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=prad_su2c_2015_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=prad_su2c_2015_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=prad_su2c_2015_rna_seq_mrna_median_Zscores&Z_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=prad_su2c_2015_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=prostate-cancer%3A-ar-signaling-%2810-genes%29&gene_list=TMPRSS2+ERG+SLC45A3+ETV1&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit))

The documentation for the _old_ and _new_ ways of loading data both fail to describe how to make correct fusion data files that will also successfully work in the oncoprint display. The problem seems to be due to the fact that the new data manager layer used by oncoprint expects the **fusion data** to be part of the **mutations** genetic profile. But making a meta file as described in the documentation makes a new separate genetic profile and loads all fusion data into this other genetic profile. 

Possible solutions:
- adjust loader code at `ImportProfileData` to exceptionally load Fusion data into the genetic profile of mutations. This means mutation data should also always be loaded first.
- OR adjust oncoprint/data manager layer to retrieve the data from the Fusion genetic profile. This can be a confusing change as the Fusion genetic profile will have to be "visible" in the query page. Also many other places in the application that retrieve mutation data will need to be adjusted to also consider the extra Fusion genetic profile...

**Comment by pieterlukasse** [comment]
@jjgao, @n1zea144  : can you please comment on the possible solutions? I think the first one is better, and by far the easiest one. I just need to confirm whether the fusion data is indeed loaded into the mutations genetic profile. Can you confirm this?

**Comment by pieterlukasse** [comment]
This issue seems to break the "Plots" tab as well, since apparently the `ImportFusionData` class does not add any samples to the database (but it looks like it expects to reuse the "mutations" profile instead?)

```
 u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> 
 <pre>java.lang.IllegalArgumentException: Could not find any samples for genetic profile ID:  383
	org.mskcc.cbio.portal.dao.DaoGeneticAlteration.getGeneticAlterationMap(DaoGeneticAlteration.java:184)
	org.mskcc.cbio.portal.dao.DaoGeneticAlteration.getGeneticAlterationMap(DaoGeneticAlteration.java:162)
	org.mskcc.cbio.portal.dao.GeneticAlterationUtil.getGeneticAlterationDataRow(GeneticAlterationUtil.java:90)
	org.mskcc.cbio.portal.servlet.GetGeneticProfilesJSON.doPost(GetGeneticProfilesJSON.java:154)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.mskcc.cbio.portal.util.XssFilter.doFilter(XssFilter.java:65)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:302)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
```

**Comment by jjgao** [comment]
@pieterlukasse fusion data are currently added as mutation data.

**Comment by jjgao** [comment]
@pieterlukasse as we discussed, the fusion data data and mutation data should be using the same profile ID. In the validator, we should allow multiple mutation files for the same mutation profile ID.

**Comment by zheins** [comment]
I just ran into this in something I was working on - we need to multiple mutation files to have the same mutation stable id, as @jjgao mentioned. We have some extremely large studies that we had to split the mafs up on.

**Comment by pieterlukasse** [comment]
part of it (at least allowing multiple mutation files in the loader) is solved in #1212

**Comment by pieterlukasse** [comment]
@jjgao @zheins I just heard from a client that this data is now also missing in cbioportal.org

**Comment by pieterlukasse** [comment]
Apparently these 2 queries would normally also return FUSION data:

http://www.cbioportal.org/beta/index.do?cancer_study_list=prad_tcga_pub&cancer_study_id=prad_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=prad_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=prad_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=prad_tcga_pub_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TMPRSS2&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&
 
http://www.cbioportal.org/beta/index.do?cancer_study_list=luad_tcga&cancer_study_id=luad_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=luad_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=luad_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=luad_tcga_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=ALK&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

**Comment by zheins** [comment]
First example: TMPRSS2 does not have any fusions in the data.

Second example: the study luad_tcga does not have fusion data. luad_tcga_pub does however and will correctly display the fusions if queried.

**Comment by n1zea144** [comment]
Regarding curation of TCGA data,@zheins is correct.  Looks like fusion data was manually curated for the public study.  Fusion data is not generated from the Firehouse output.

**Comment by pieterlukasse** [comment]
@zheins does this mean that the following query should have fusion data: 

http://www.cbioportal.org/index.do?cancer_study_list=luad_tcga_pub&cancer_study_id=luad_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=luad_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=luad_tcga_pub_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=luad_tcga_pub_rna_seq_v2_mrna_median_Zscores&Z_SCORE_THRESHOLD=2.0&genetic_profile_ids_PROFILE_PROTEIN_EXPRESSION=luad_tcga_pub_rppa_Zscores&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=luad_tcga_pub_all&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=ERG+ETV1+ETV4+FLI1&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

It seems to be missing. Can you add an example for this study?

**Comment by zheins** [comment]
@pieterlukasse Its not missing - fusion data only exists for ALK, RET, and ROS1 in `luad_tcga_pub`. We're working on revamping the way structural variants are expressed in the portal so that fusions will be easier to find.

http://www.cbioportal.org/index.do?cancer_study_list=luad_tcga_pub&cancer_study_id=luad_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=luad_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=luad_tcga_pub_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=luad_tcga_pub_rna_seq_v2_mrna_median_Zscores&Z_SCORE_THRESHOLD=2.0&genetic_profile_ids_PROFILE_PROTEIN_EXPRESSION=luad_tcga_pub_rppa_Zscores&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=luad_tcga_pub_all&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=ALK%0D%0ARET%0D%0AROS1&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

**Comment by pieterlukasse** [comment]
@zheins I see it, thanks. Was the mentioning of  ERG, ETV1, ETV4, and FLI1 in your previous comment a typo? Or did these genes have some data in the past?

**Comment by zheins** [comment]
No, those are the genes with fusions in that study. I looked directly in the data_fusions.txt file for that study.

**Comment by pieterlukasse** [comment]
@awernibi - these last comments were related to one of your questions.
