### ISSUE TITLE
Sling alternatives

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#11057]
The goal of this process is to answer the following questions for alternatives to Sling:

1. is it faster than sling
2. can it handle giant table without segmentation
3. does it have good error handling
4. Is it independent of the resources of the system on which it's executed

**Comment by zainasir** [comment]
This Architectural Design Record will be used to track current findings and future research.

## Issue

To integrate Clickhouse Cloud into cbioportal, we have been using Sling as the data migration mechanism. Sling has some reliability issues:
* Large table, such as [clinical_event](https://github.com/cBioPortal/cbioportal/blob/master/src/main/resources/db-scripts/cgds.sql#L652) with 27,000,000 rows, need to be segmented into smaller tables.
* Sling's performance is questionable (Need a measure of performance).

## Alternatives

* [Clickhouse Local](https://clickhouse.com/docs/en/cloud/migration/clickhouse-local)
* [DLT](https://dlthub.com/docs/pipelines/sql_database_mysql/load-data-with-python-from-sql_database_mysql-to-clickhouse)

## Status

UNDECIDED. We are still researching alternatives to Sling.

## Details

### Clickhouse Local
[Clickhouse Local](https://clickhouse.com/docs/en/cloud/migration/clickhouse-local) is a native pivot method that reads data from mysql and inserts into clickhouse cloud without saving the data locally.

#### Comparison with Sling
* Performance: The speed is considerably variable but through multiple tests, it was discovered that on average, the transfer speed is approximately 60,000 rows/sec.
* Segmentation: Can handle large tables without the need for segmentation.
* Error Handling: Currently, no error handling mechanisms have been found that can allow us to ensure reliability.
* System Resource Usage: Needs more research.

### DLT
[DLT](https://dlthub.com/docs/pipelines/sql_database_mysql/load-data-with-python-from-sql_database_mysql-to-clickhouse) is 3rd-party tool that can also be a viable solution. More time needs to be spent with this tool to explore its viability and effectiveness.

## Edits and remarks

Feel free to add edits to this document or add remarks/comments below.
