### ISSUE TITLE
genie BPC mets data inconsistent between clinical & generic assay

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#11115]
I'm not sure if this is an issue in the data or with generic assay or something else, but the counts differ between eg Distant Mets: Bone (clinical attribute) vs DMETS_DX_BONE (generic assay).

I think the clinical attribute is patient-level but the generic assay is coming through as sample level (even though it says Patient level)

Here I've filtered to DMETS_DX_BONE = NA but looking at Distant Mets: Bone, but Distant Mets: Bone is not all NA.
![image](https://github.com/user-attachments/assets/319cc826-778e-4a6b-af3d-5bbb5d022739)

@ritikakundra @dippindots any thoughts on if this is a data or generic assay issue?

**Comment by fuzhaoyuan** [comment]
Thank you @tmazor for finding this! Yeah I don't think we've added patient level filtering for generic assay yet. I'll work to bring it on.

**Comment by fuzhaoyuan** [comment]
@tmazor I tried on the production genie and it behaves the same

**Comment by tmazor** [comment]
Agreed - there's no difference between production & clickhouse, but I think it's in issue in both places.

**Comment by tmazor** [comment]
Adding some additional detail:

Without any filtering applied, the starting values are off
<img width="406" alt="image" src="https://github.com/user-attachments/assets/ed798a06-a476-4d85-93ea-7aa464c9c359">
https://genie.cbioportal.org/study/summary?id=nsclc_public_genie_bpc

The sum of the counts in DMETS_DX_BONE add up to the number of samples while the sum of the counts for Distant Mets: Bone add up to the number of patients in the study.

**Comment by fuzhaoyuan** [comment]
The data issue is being investigated in #11173

**Comment by alisman** [comment]
@tmazor  the data is fixed for this
