### ISSUE TITLE
move cbioportal-session SERVER_PORT off 5000

### ISSUE THREAD

**Issue by Wade-Webster** [cBioPortal/cbioportal#11119]
[The IANA has long considered port 5000 (along with 1900) for network device discovery](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=88).

Using 5000 creates conflicts system-level conflicts for MacOS Airplay Receiver, Intel Graphics Command Center, and developer conflicts for Node.js, Heroku, ASP.NET Core, Docker Registry, etc.

This invariably creates a number of headaches for anyone trying to use the "quick start" Docker Deployment guide.

**Comment by iishitahere** [comment]
Hello! I’d like to work on this issue regarding the port conflict with port 5000 in the Docker deployment. I propose to modify the Docker configuration to use a different default port (such as 5001 or 8080) and update the documentation to guide users who may still need port 5000. I believe this will help reduce conflicts with MacOS AirPlay Receiver, Intel Graphics Command Center, and other developer tools that use port 5000.

Please let me know if there are any specific guidelines or if I should proceed with these changes.
Thank you!

**Comment by Srayash** [comment]
hey @Wade-Webster @alisman I've made a PR(#11126) addressing this issue, kindly review and provide feedback or merge.
Thanks!
