### ISSUE TITLE
Remove calls to System.exit() from command logic

### ISSUE THREAD

**Issue by morungos** [cBioPortal/cbioportal#1113]
We've found a few issues for failing tests in https://github.com/cBioPortal/cbioportal/pull/963. Ultimately, the problem is that some of the `main()` methods call `System.exit()`, which kills the JVM. This makes testing impossible.

We should refactor all the classes that expose a `main()` to be a `Runnable`, where the `main()` invokes the `Runnable.run` and turns any thrown exceptions into a non-zero exit status. The classes can then be tested through their `Runnable` interfaces, and there's no logic left to speak of in `main()`.

At least: that's now up for discussion.

**Comment by fedde-s** [comment]
I don’t think System.exit() strictly makes testing impossible, there’s things like http://stefanbirkner.github.io/system-rules/index.html#ExpectedSystemExit and `SecurityManager`s. But having the main() function as a separate outer layer that basically does nothing but map out which exception types yield which exit statuses for this particular command may be a valid idea.

**Comment by fedde-s** [comment]
It may then make sense to subclass `Runnable` put that mapping logic in a separate function, and have all of the `main` functions do nothing but call that function. It would help standardising the meaning of exit statuses like the BSDs aim to do in their [sysexits](https://www.freebsd.org/cgi/man.cgi?query=sysexits&sektion=3) header, although I don’t know if that’s worth the effort in this case.

**Comment by ecerami** [comment]
@morungos:  @pieterlukasse will fix.

**Comment by morungos** [comment]
Excellent. @fedde-s is right, `System.exit()` doesn't directly make testing impossible. It just much easier to test a very few paths involving `System.exit()` rather than the number we have now. And I would recommend standardising exit status, as this will be the normal pipeliney way to notify failure, which will always be a possible outcome.

**Comment by pieterlukasse** [comment]
hi @morungos, I did a quick change to help in this discussion (not tested yet). Is your proposal something like this https://github.com/thehyve/cbioportal/commit/1bf83decc33fe6c5d23d3d17065b12e21b450188
?

**Comment by morungos** [comment]
Yes, exactly like that! Good one.

**Comment by morungos** [comment]
This is beginning to bug me, as any failing test of the increasingly tight validation on import is throwing a `System.exit()` all the time, breaking the tests and therefore making packaging harder. As a transitional measure, we might want to move the tests -- all the importer tests -- into a new Maven subcomponent and use Failsafe instead, so that we don't have these issues. Or maybe @fedde-s's solution will work, although how it gets around the Surefire limitations, I am not sure.

**Comment by fedde-s** [comment]
The pull request is an implementation of the fix we had already agreed on, with an abstract class between the Runnable interface and the script classes in order to reduce repeated boilerplate code and to keep command-line behaviour such as the choice of exit status consistent. Would that not resolve this issue after all?

**Comment by morungos** [comment]
It would, when it's in `rc`. I'd need to rework some of my code to handle parts of that, but I think it'll assist in debugging a lot when the tests switch to using a `run` method from a `main` method. e.g., `TestPanCancerStudySummaryImport` calls a bunch of these, so if there's a load error (and there seems to be in some cases) we get a `System.exit()` and a Surefire fail. So these tests are also worth looking at.

**Comment by pieterlukasse** [comment]
@morungos maybe you can help us tests #1224 as well?

**Comment by morungos** [comment]
Sure, definitely. I think we also got a better handle on integration testing in the branch for the sprint on architecture/repository work too, so it might even be worth looking into that. Basically, that would involve moving the integration tests (as these mostly are) into a separate component, running them against built jar file, and probably using failsafe rather than surefire. But that's all long term, I'll test this next week -- we need it.

**Comment by morungos** [comment]
OK, I can now test clean, but we need a few more fixes here. I've added them in https://github.com/morungos/cbioportal/commit/5abb40bccda2821c0e50f9268ba8528318e270a3. 

Some tests still fail or error, but the JVM doesn't exit now, so at least packaging happens.

**Comment by fedde-s** [comment]
@morungos: Can I cherry-pick that commit into my PR? Or do you want me to include the small but otherwise unrelated fixes after it (morungos@29bee489fce23d9c2e9d54303f1eaa27c3a0a521 and its parent) as well?

**Comment by morungos** [comment]
@fedde-s You can do whatever works. The other tests I can cherry pick into some other PR to make testing clean again if you like. Multi-user PRs are not exactly clean in Github, so whatever works.

**Comment by fedde-s** [comment]
@morungos is this issue resolved now?

**Comment by morungos** [comment]
As far as I'm concerned, yes. OK to close.
