### ISSUE TITLE
For functional impact show gray benign dot

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#11150]
The functional impact column should show a gray dot for benign predictions:

![image](https://github.com/user-attachments/assets/2c0c12ee-d3e6-4a91-8ca5-a8864f05c424)

See [URL](https://www.cbioportal.org/results/mutations?cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&mutations_gene=NRAS)

**Comment by nbentoneves** [comment]
I’m interested in helping. Can I work on this one?
Thanks

**Comment by 0PrashantYadav0** [comment]
@inodb If the issue is still valid i would like on work on this
