### ISSUE TITLE
Curated Set of NR Studies contains one hg38 study

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#11151]
... and warning/error message are showing. Should we exclude the hg38 study as a quick fix?

![Nov-01-2024 10-04-43](https://github.com/user-attachments/assets/66b06132-09f2-4693-af6a-64bd86021646)

**Comment by rmadupuri** [comment]
fixed in https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/pull/235
