### ISSUE TITLE
For custom selection of patients/samples allow multiple types of whitespace

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#11273]
![image](https://github.com/user-attachments/assets/d9453afe-4cfb-4240-8d6f-911541df1195)

The custom selection field is very stringent on the [Study View](https://www.cbioportal.org/study/summary?id=summit_2018). It only allows newlines, let's also allow spaces/tabs/commas

**Comment by anshuman-rai-27** [comment]
hey i undertood the requirements plz assign me this issue

**Comment by anshuman-rai-27** [comment]
hey but was wondering that spaces may create problem as if someone puts space here and there it may create problem so would suggest using tabs new line and commas for seperation only , @inodb , should i include space functionality too ?

**Comment by LakshayPuhal** [comment]
I would like to work on this issue.

**Comment by karthik-nair-20** [comment]
Hello @inodb ,

I hope you are doing well

I wanted to inform that I have drafted a PR https://github.com/cBioPortal/cbioportal-frontend/pull/5071 for this Request, I would really appreciate it if you could take a moment to review my solution and share your feedback.


Best,
Karthik
