### ISSUE TITLE
New docker file has different location for scripts than in the documentation

### ISSUE THREAD

**Issue by sstein93** [cBioPortal/cbioportal#11301]
Hello,

In a previous version of the docker file, the location of the importGenePanel.pl script was in `/cbioportal/core/src/main/scripts/` and now it's in /core/scripts/. So the command for importing gene panels is now 

```
docker-compose run cbioportal bash -c 'cd /core/scripts/ && ./importGenePanel.pl --data /path/to/genePanel.txt'
```

And this returns a "Directory does not exist" error, but is still in the documentation for uploading gene panels: https://docs.cbioportal.org/deployment/docker/import_data/

```
docker-compose run cbioportal bash -c 'cd /cbioportal/core/src/main/scripts/ && ./importGenePanel.pl --data /path/to/genePanel.txt'
```

Thanks,
Shayna

**Comment by adarsh7raj** [comment]
does the  documentation need to be changed ?
