### ISSUE TITLE
Data Loading Issues

### ISSUE THREAD

**Issue by zheins** [cBioPortal/cbioportal#1138]
MAF importing: If Entrez_Gene_Id is invalid, we should fall back to Hugo_Symbol instead of skipping the row. @pieterlukasse is this behavior applied to other data types? It seems like this is just a one off bug by the way the code is structured.

Clinical data importing: Backwards compatibility issues bug where MIXED is not being passed into the attribute type enum.

**Comment by pieterlukasse** [comment]
@zheins : yes, this behavior is applied to all data types. Rationale was to align this with the validation (part of which was discussed in #823). We allow entrez column to be empty (now also in Validator). This would be the recommended way of providing data out of pipelines where the entrez id value is not reliable and you want hugo symbol to be the default. 

To comment on the "fall back" idea: I see no good reason to let *cBioPortal* make such "fall back" calls (but maybe you can list some here?). I think it is fine if you have your own good reasons to make this "fall back" decision for your own data, but I would ask you to please do this by making Entrez empty in your data files and *not* implementing such a fall back logic in this part of code.

**Comment by jjgao** [comment]
https://github.com/cBioPortal/cbioportal/pull/4114 should solve it.
