### ISSUE TITLE
Remove CAISIS_ clinical attributes from timeline code

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#1139]
Once the `CAISIS_` prefixed clinical attributes are removed from the database the clinical timeline code should be updated accordingly, see https://github.com/cBioPortal/cbioportal/pull/926.

**Comment by jjgao** [comment]
@inodb moved to To-Do.

**Comment by jjgao** [comment]
@inodb I guess we can close this now that we are working on the new code? Do we still need to keep the CAISIS_ logic?

**Comment by inodb** [comment]
Yeah this is fine to close. Caisis logic shouldn't be necessary any more
