### ISSUE TITLE
Show all Samples badge is "off"

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1147]
Not sure if this is an issue in production, but I am seeing this in the release candidate.

When I see an OncoPrint, I see the "Show all Samples" badge.

![screenshot_845](https://cloud.githubusercontent.com/assets/1009066/14924183/2e737b7e-0e0f-11e6-8dea-c9f6cd13e4f8.png)

The badge would look much nicer if it was left aligned to the text above, and there was a little more white space below the text.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1165
