### ISSUE TITLE
Case Set:  : in Oncoprint

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1149]
In the release branch, when a new OncoPrint is generated, I see the following at the top:

Case Set: : 

Depending on the amount of data you get, that's the main text you see while the OncoPrint is being rendered.

Can we just remove the text "Case Set: :" until the data is ready?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1165
