### ISSUE TITLE
Clicking "Show all Samples" badges causes strange jitter effect

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1150]
In the release candidate branch, if I click "Show all Samples" within an Oncoprint, I get a flash or a rectangle which then disappears.  Clicking the badge again, and I see the same rectangle flash by.

**Comment by adamabeshouse** [comment]
Ah ha, this is the loading bar appearing and quickly disappearing. I'll add 'Loading' to it to make it clearer.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1165
