### ISSUE TITLE
Do we really want the condensed view to the default for new OncoPrint?

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1151]
(In release candidate):

Do we really want the condensed view to the default for new OncoPrint?

![screenshot_846](https://cloud.githubusercontent.com/assets/1009066/14924429/860f1a0e-0e10-11e6-9203-5c06e3fab1bc.png)

I liked the "old" way better, and this what most users are used to.

**Comment by jjgao** [comment]
This is experimental.. To play on the safe side, we should probably use the old view by default.

@schultzn @adamabeshouse what do you think?

**Comment by adamabeshouse** [comment]
It's a one-line change to use the old style, so whatever is preferred works with me.

**Comment by schultzn** [comment]
For large studies, I don't think it makes a lot of sense to be fully zoomed in. I always zoom out immediately to see the big picture.
As a compromise, we could zoom out when the study size is greater than 200?

As an example, for the query below, there is no reason to hide the white spaces between columns:
http://bit.ly/1SNyp1p

The page should look like this:
![image](https://cloud.githubusercontent.com/assets/11892704/15031360/0fede9ee-1226-11e6-8817-489f3372239c.png)

What does everybody think?

**Comment by schultzn** [comment]
@ecerami by the way, here is our TP53 OncoPrint row
![image](https://cloud.githubusercontent.com/assets/11892704/15031400/5fe65328-1226-11e6-93de-06461e15d9f8.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1203
