### ISSUE TITLE
OncoPrint Legend gets cut off

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1152]
(In release candidate):  

OncoPrint legend gets cut off:

![screenshot_847](https://cloud.githubusercontent.com/assets/1009066/14924456/af04bbee-0e10-11e6-9c27-458593a1ae56.png)

See the text "Genetic alteration with the line straight through it..."

**Comment by adamabeshouse** [comment]
I'm unable to replicate, which study is this?

**Comment by ecerami** [comment]
This is for our DFCI instance / study.

**Comment by adamabeshouse** [comment]
Hm, does it happen every time?

**Comment by ecerami** [comment]
It was not every time.  Just some of the time.

**Comment by jjgao** [comment]
@adamabeshouse try clicking another tab, e.g. Plots, and clicking back to OncoPrint.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1203
