### ISSUE TITLE
New place for documentation

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1161]
The current wiki is not ideal for documenting the system as it is not part of the code itself. We therefore would like to propose to have the documentation in a folder that is part of the project, e.g. located in a subfolder like `/docs`. 

See also our proposal here: https://github.com/thehyve/cbioportal/tree/documentationTest

**Comment by pieterlukasse** [comment]
@jjgao , @ecerami , @n1zea144 , @schultzn : in this new form, developers can submit changes to the code and respective documentation in the same PR.

**Comment by jjgao** [comment]
@pieterlukasse Thank you! It looks great!

https://github.com/thehyve/cbioportal/tree/documentationTest/docs

**Comment by inodb** [comment]
Nice! I agree that it's much better to couple documentation and code. 

I would also opt to use smth like readthedocs to make it a little nicer to read: http://read-the-docs.readthedocs.io/en/latest/getting_started.html#in-markdown. It basically adds a custom readthedocs skin to html generated from the markdown in your repo, some search functions and you can easily retrieve documentation from older tagged releases. Could be done in a separate PR.

**Comment by pieterlukasse** [comment]
@inodb just the search function is already a great argument ;)   I agree it would be a nice next step.

**Comment by pieterlukasse** [comment]
merged in rc already done
