### ISSUE TITLE
Clinical data import aborts if sample duplicated incorrectly

### ISSUE THREAD

**Issue by zheins** [cBioPortal/cbioportal#1174]
First, @n1zea144 @jjgao, do we want to abort import if a sample is present twice in a clinical file?

Secondly, I'm getting this error even though I've checked that the sample is not duplicated in the file. It does occur in other clinical files though.

**Comment by jjgao** [comment]
@zheins I don't think we should abort. Some warning might be useful.

**Comment by jjgao** [comment]
@n1zea144 closing.
