### ISSUE TITLE
Oncoprint menu

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#1204]
@schultzn @jjgao 

We've been talking about maybe using a dropdown menu (e.g. 'File', 'Edit', 'View',... -style) instead of the toolbar icons. Here is one proposal, comments welcomed.

The current items are
-Add clinical track
-Sort by
-Patient/sample switch
-Mutation color settings
-Show/hide unaltered cases
-Show/hide whitespace between columns
-Download
-Zooming controls
- Show/hide clinical legends

The proposal is to leave the zooming controls as-is, and put the rest into menus as follows:
[Clinical Tracks] [Sort] [Mutation Color] [View] [Download]

In the view menu, have patient/sample switch, show/hide unaltered cases, show/hide whitespace, show/hide clinical legends

**Comment by jjgao** [comment]
@adamabeshouse sounds good to me.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1287
