### ISSUE TITLE
Too many layout calls on interaction filtering in network view

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#1207]
In both dialogs for modifying interactions by type and source, we are calling layout too many times (each time a type / source checkbox is checked/unchecked). Instead, we should
- cancel / ignore all changes when X is clicked to close the dialog, and
- apply all changes once and apply layout if associated flag (Auto Layout on Changes) is checked when OK is clicked to close the dialog

**Comment by istemi-bahceci** [comment]
Fixed
