### ISSUE TITLE
Validator improvement : Allow only 'LIVING' and 'DECEASED' for OS_STATUS

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#1213]
Validator should throw a warning if OS_STATUS is not 'LIVING' or 'DECEASED'.
The survival plot shows up as empty plot otherwise.

**Comment by pieterlukasse** [comment]
@fedde-s an extra requirement: give error if fields known to be PATIENT_ATTRIBUTES (like OS_STATUS) are found in SAMPLE_ATTRIBUTES file and vice-versa.

**Comment by fedde-s** [comment]
This should be fixed now that aa9a48cb1d5601a840267aabc86f5bc6482edd5a is in v1.3.1.
