### ISSUE TITLE
Validator should give error when no case list option is present

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1214]
Currently it is possible to load a study without case lists. However this gives an exception in the portal. 
![image002](https://cloud.githubusercontent.com/assets/2900303/15186387/20e54612-179d-11e6-992e-dd3ccf3caf21.jpg)

At the study in the UI (selecting a few genes) to see oncoprint, the following message is given:
![image004](https://cloud.githubusercontent.com/assets/2900303/15186385/1fd69000-179d-11e6-8c8b-db79b42ddeee.jpg)

**Comment by pieterlukasse** [comment]
solution would be to give error if no case lists are found `AND` the study metadata parameter `add_global_case_list` is false or not given.

**Comment by fedde-s** [comment]
Validation for the presence of the case list `<study_id>_all` has been implemented in the referenced pull request and released as part of v1.2.5. @pieterlukasse, does that solve your issue?

**Comment by fedde-s** [comment]
I will assume it does and close this issue.
