### ISSUE TITLE
does genomespace block loading of cbioportal?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1217]
We should probably not load anything from genomespace when loading up the cbioportal main page.

![image](https://cloud.githubusercontent.com/assets/840895/15194030/ba956b20-178e-11e6-97d5-f7d18ca3e683.png)

**Comment by jjgao** [comment]
will be removed in Andy's new interface.

**Comment by jjgao** [comment]
I still see the same message pop up and the js files are still loaded. Can we remove them?

![image](https://user-images.githubusercontent.com/840895/29473528-1c29ebb8-8426-11e7-89be-9ebcc99c75cd.png)

**Comment by inodb** [comment]
This is not fixed in beta. I still see it showing up: http://www.cbioportal.org/beta/index.do?session_id=595408da498e5df2e291c896&show_samples=false&

![screen shot 2017-10-10 at 12 50 49 pm](https://user-images.githubusercontent.com/1334004/31399283-c6b5ebb0-adb9-11e7-981f-21fb60a742cd.png)

**Comment by jjgao** [comment]
We would need to bring GenomeSpace button back: https://github.com/cBioPortal/cbioportal/issues/3156

But no ajex calls should be made (ideally the js file should not be loaded) until the button is clicked (or at least until the "Download Data" tab is clicked).

**Comment by jjgao** [comment]
Not sure if any code is still running.
