### ISSUE TITLE
Validator & Loader Expression Data NULL-flavours

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#1221]
Whilst testing expression data loading in the plots-tab, it turns out the front-end only accepts NaN and NA as valid empty values:

plotsUtil.js:
```
var isEmpty = function(inputVal) {
    if (inputVal !== "NaN" && inputVal !== "NA") {
        return false;
    }
    return true;
};
```

The validator/loader/front-end should be synchronised

**Comment by pieterlukasse** [comment]
this means we need to be somewhat stricter in the `NULL_VALUES` in some of the Validator classes in `validateData.py`

**Comment by pieterlukasse** [comment]
Other places found where `NA` is used as null/empty value: 
- DataTable.js `if(aData[i] !== 'NA'){`
- BarChart.js `if(returnValue === "NA" || returnValue === '' || returnValue === 'NaN'){`
- survivalCurveProxy.js `if (_datum.time !== "NA" && (_datum.status !== "NA" `
- oncoprint*.js 
- ....etc 

"NA" seems to be the standard scenario that is taken care of in the frontend code.
