### ISSUE TITLE
Error in validating timeline file.

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#1227]
cancer_study_identifier: xxxxx
genetic_alteration_type: TIMELINE
datatype: TIMELINE
data_filename: data_timeline_specimen.txt

ERROR: meta_timeline_specimen.txt: Could not determine the file type. Please check your meta files for correct configuration.; value encountered: 'genetic_alteration_type: TIMELINE, datatype: TIMELINE'

**Comment by aderidder** [comment]
Hi,
There were some issues with the validator and we've created a fix. 

The following needs to be changed in timeline files:
* change genetic_alteration_type to CLINICAL
* STOP_DATE is now a mandatory column (third column). The values should be blank when STOP_DATE is not used. 

@pieterlukasse the loader code should be improved in how it handles the sometimes optional column STOP_DATE

**Comment by pieterlukasse** [comment]
@priti88 can you confirm that the solution indicated by @aderidder works? We can make further improvements to the loader code at a later stage (e.g. if there is a need to have the columns in any order or if someone really wants to leave out the whole STOP_DATE column....but I think these are not so important now)

**Comment by priti88** [comment]
@pieterlukasse : I added STOP_DATE Column. But, the validator fails with error:
ERROR: data_timeline_specimen.txt: lines [2, 3, 4, (17 more)]: column 3: Blank cell found in column; value encountered: ''' (in column 'STOP_DATE')'

**Comment by pieterlukasse** [comment]
@priti88 : did you use the fix PR #1230 ? Sorry, it was not very clear in Sander's comment.

**Comment by priti88** [comment]
No. I did not 
Can you send a PR for our branch as well ? :)

**Comment by pieterlukasse** [comment]
@priti88 :ok, I'll do that tomorrow

**Comment by pieterlukasse** [comment]
Hi @priti88  : I checked this, and you will need to merge #1277 PR first because @aderidder included some documentation update in #1230 and your custom "rc" branch does not yet have the new `/docs` folder.

**Comment by pieterlukasse** [comment]
@priti88 : see #1279. You can test this one on your branch. Please report back here if it solved the problem.

**Comment by priti88** [comment]
It is solved.
