### ISSUE TITLE
supporting multiple studies in data-manager

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1231]
In order to support cross-study query, we need to be able to pull data across studies in data-manager. The current data manager API and data structure cannot support it well. Can we modify it?

For example, to get genetic data, we can pass in the follow parameters (just a dump example -- you don't have to follow exactly).

```
[
{
cancer_study_id: brca_tcga,
sample_ids: [s1, s2, s3],
profile_id: [p1, p2]
},
{
cancer_study_id: brca_mskcc,
sample_ids: [sm1, sm2, sm3],
profile_id: [pm1, pm2]
},
...
]
``

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1493/files
