### ISSUE TITLE
Cancer Genes List Documentation

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#124]
Is the Cancer Genes List functionality already supported, e.g. providing a list of genes within a targeted panel?

If so, can someone please add a wiki page with documentation?

**Comment by yichaoS** [comment]
I created a cancer gene list page for the new function "Enrichment analysis". It's just a plain list. Please check http://miso-dev.cbio.mskcc.org:28080/or-analysis-portal/cancer_gene_list.jsp  If this works, I'll put in Wiki.

**Comment by ecerami** [comment]
This is a duplicate of #426.  Closing.
