### ISSUE TITLE
New study view tables should show more data

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1241]
The old study view tables had 10 rows of data plus the header, now we are down to 8 rows. Can you use  smaller font and less spacing to show more data again?

Also, the search box should just say "Search" instead of "Input a keyword".

Thanks!

**Comment by schultzn** [comment]
Maybe the gene column could get a little more space, so that we can show a little more than CDKN...

![image](https://cloud.githubusercontent.com/assets/11892704/15295200/6e22d336-1b5d-11e6-9383-9631127d1de7.png)

**Comment by zhx828** [comment]
@schultzn 👌
