### ISSUE TITLE
New Oncoprint sorting

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1243]
I suggest to sort mutations in the OncoPrints in the following way:
1 - Truncating 
2 - In Frame ins / del
3 - Missense

The legend should be sorted the same way. And fusions should be moved up, right after the copy-number events and before the mutations.

![image](https://cloud.githubusercontent.com/assets/11892704/15301253/d04821a2-1b7a-11e6-940f-a8727e9f93d2.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1246
