### ISSUE TITLE
Gene duplication breaks OncoPrint and Mutations Tab

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1244]
http://bit.ly/1Nw3zKx

![image](https://cloud.githubusercontent.com/assets/11892704/15304819/9f625b62-1b8d-11e6-9d31-6c73a67fbca4.png)

![image](https://cloud.githubusercontent.com/assets/11892704/15304822/a5f913c6-1b8d-11e6-8af2-78d8b7dacf5a.png)

**Comment by adamabeshouse** [comment]
@schultzn Do we want to style the rows at all to indicate the difference? Maybe show the corresponding line of OQL in a tooltip for the row?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1416
