### ISSUE TITLE
Missing HGVSp_Short validation for mutation data

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1249]
Validation for column `HGVSp_Short` needs to be implemented to give an error if _more than one_ value is given in this column. 
- [x] part1 :if column value is `p.V600E` then it is OK. If column value contains a list of values like `p.V600E, p.V610E,etc`, then user should get an error. 
  Documentation in https://github.com/cBioPortal/cbioportal/blob/rc/docs/File-Formats.md#data-file-5 should also be adjusted to be a bit more explicit about this. 
- [ ] part 2: check how much work it would be to validate the column value using the hgvs package https://pypi.python.org/pypi/hgvs/  (consider updating installation documentation, Docker file, etc). Alternatively,  could this  also be solved with a simple regex check?

**Comment by morungos** [comment]
@pieterlukasse @fedde-s I had a similar issue in a previous system. I think you'll want probably regex, as there is *huge* variation in compliant HGVS. Not least, you're allow three-letter codes for the amino acids, which I have no idea whether the portal will recognize that p.G12D is exactly the same as p.Gly12Asp (they should be merged statistically, to be strict). Either you'll need to canonicalize the formats on import, or just be stricter and allow only a subset. Genome Nexus could change this, as it's probably more a Genome Nexus problem.

**Comment by pieterlukasse** [comment]
@morungos : thanks for the comments!

I would like to suggest the following approach: we fix the most urgent "part 1" first (this could be submitted as a PR on its own) and leave "part 2" for later. At this moment I'm not into the details of Genome Nexus, but I image we will still like to support the staging files and proper validation of these, regardless of how the storage and backend code of mutation data is implemented.

**Comment by fedde-s** [comment]
@pieterlukasse A ‘value’ would probably be anything starting with the substring ‘p.’, not preceded by a letter. I suspect that the HGVS syntaxes for alleles involving multiple mutations, as in `p.[S73R;N103del]` and `p.[S73R];[N103del]`, may not be supported either.

**Comment by fedde-s** [comment]
As of v1.2.5, the validator will report an error if values contain commas, additional `p.` prefixes, or allele syntaxes, as implemented by the pull request that referenced this issue. @pieterlukasse, can the issue be closed now?

**Comment by pieterlukasse** [comment]
@fedde-s I like the solution in the PR and the extra information you added 👍  

One point that we could work on before closing this is to update the documentation regarding this. 
- Does the documentation clearly state how this field should be filled? 
- Can we add something about whether it is possible to add multiple AA changes for 1 mutation (e.g. using multiple lines of the MAF, one per AA change)?

**Comment by fedde-s** [comment]
Does @sandertan know whether the questions asked [above](https://github.com/cBioPortal/cbioportal/issues/1249#issuecomment-248960284) can be answered by now, if any data curator wonders about them?

**Comment by sandertan** [comment]
Good point, I'm busy with an update regarding documentation on the cBio MAF format and can add some more info regarding this field.

https://github.com/cBioPortal/cbioportal/compare/master...thehyve:docu_maf_format if you're curious, not ready for review though.

**Comment by fedde-s** [comment]
Is this still an issue?

**Comment by jjgao** [comment]
I am closing it. Please reopen if anyone sees a reason.
