### ISSUE TITLE
error when redeploying war

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1253]
SEVERE: The web application [/cbioportal] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.

**Comment by morungos** [comment]
See: http://stackoverflow.com/a/26261752/2140998

I think I've seen this before: then it was another factor relating to container web database setup. It's fixable, but really, I am going right off war file deployment.
