### ISSUE TITLE
Copy Number Chart shows incorrect number of profiled samples

### ISSUE THREAD

**Issue by awernibi** [cBioPortal/cbioportal#1254]
This is an issue in rc.
The number of profiled samples in the CNA genes chart is zero, even though there are alterations reported.
![image](https://cloud.githubusercontent.com/assets/13519768/15356413/d3280c5a-1cf8-11e6-9e1c-e2667b6e7589.png)

This is a screenshot from dataset Acute Myeloid Leukemia (TCGA, NEJM 2013) in beta.
The release version shows 45 profiled samples.

In one of our company internal data sets, the frequencies are unexpected:
![image](https://cloud.githubusercontent.com/assets/13519768/15356508/78c03f52-1cf9-11e6-8afc-ec2862effab4.png)

**Comment by zhx828** [comment]
@jjgao This is the question I asked before. I will take a look about this.
