### ISSUE TITLE
Add missing UQ constraint to `gene` table

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1266]
Add the constraint as discussed in #805 (see https://github.com/cBioPortal/cbioportal/pull/805#issuecomment-179274725 and https://github.com/cBioPortal/cbioportal/pull/805#issuecomment-180355753)

**Comment by fedde-s** [comment]
This may be problematic for now, as the seed database from which new instances are initialised (https://github.com/thehyve/cbioportal/wiki/Import-the-Seed-Database) contains (incorrect) records that violate the constraint. This means that the database migration script would crash unless people repopulate their gene table first, and I think the procedure to do this isn’t documented in an easy-to-find place.

**Comment by pieterlukasse** [comment]
You can use a query like below to check if the `gene` table has invalid values:

```sql
Select count(*) as NR_INVALID_GENES from 
(Select HUGO_GENE_SYMBOL, count(*) FROM gene group by HUGO_GENE_SYMBOL having count(*) > 1) as dup_genes
```
and if `NR_INVALID_GENES > 0`, report this in the migration output instead of adding the constraint. So people can fix it manually. In this case, also do *not* update the `info` table with the new version number.

NB: when increasing the DB version, be aware that the PR #1364 is changing the way this is checked in the code. So maybe wait for that one to be merged first.

**Comment by pieterlukasse** [comment]
OR we can make a new version of the Seed Database as part of the solution here. And then let the migration script for the UQ constraint fail (as it should) in the cases where HUGO_GENE_SYMBOL is ambiguous.

**Comment by fedde-s** [comment]
Would it be in any way possible to update the gene table in an existing production database without invalidating all studies? I imagine foreign keys to the gene table will be referentially incoherent before it is fully repopulated, and some outdated ones will be broken even afterwards, so re-importing them from the staging files would probably be preferable after all.

**Comment by pieterlukasse** [comment]
That is a decision each site has to make for their own (i.e. how to repair it). But they can only take this decision if they know there is a problem. This fix should help site admins see the problem in the first place. And because it provides an updated Seed DB, it also helps other to avoid this problem in the future.

**Comment by pieterlukasse** [comment]
assigning to @sheridancbio since he is also reviewing the related PR https://github.com/cBioPortal/cbioportal/pull/1807
