### ISSUE TITLE
Mutations tab issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1268]
trying to make a figure mapping the mutations within ERCC2 from the following study:
Bladder Urothelial Carcinoma (Dana Farber & MSKCC, Cancer Discov 2014)

http://bit.ly/1sx9Ag5

The Oncoprint shows the mutations:
![image](https://cloud.githubusercontent.com/assets/840895/15458590/2413e69c-206a-11e6-9fae-c1e2d71dc6dc.png)

But in the mutations tab, I get the following:
![image](https://cloud.githubusercontent.com/assets/840895/15458594/2928be8c-206a-11e6-819a-a335c9a5b0fd.png)

**Comment by onursumer** [comment]
We are getting NullPointerException for this query. Looks like we are trying to get the data based on this genetic profile id: **blca_dfarber_mskcc_2014_mutations**. But the actual id in our database is **blca_dfarber-mskcc_2014_mutations**

The server side code should be modified to prevent NullPointerException in case invalid profile id is provided. We also need to modify client side code to query with the correct profile id.

**Comment by onursumer** [comment]
This is where we fail on the front-end: https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/js/src/DataProxyFactory.js#L54

**Comment by jjgao** [comment]
I see. We should change the code to use the mutation profile that is selected by the user.

**Comment by onursumer** [comment]
Using `window.QuerySession.getMutationProfileId()` instead of `window.QuerySession.getCancerStudyIds()` should fix the front-end
