### ISSUE TITLE
Duplicated data only flagged in ImportTabDelimData

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1270]
The check implemented in `storeGeneticAlterations` results in an `else` block that only gives a warning for duplicated entries (see https://github.com/cBioPortal/cbioportal/blob/rc/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportTabDelimData.java#L448). This seems to be intentional for CNA data (according to comments dating back to 2011), but is applied to all data (e.g. also mRNA). Questions: 
- is this still applicable? 
- should it indeed be for all data types processed by this importer class or should it be limited only to CNA data?

**Comment by pieterlukasse** [comment]
@n1zea144 , @jjgao : can you comment on this?

**Comment by pieterlukasse** [comment]
data duplication is also found in expression data in the TCGA data batch, so it does not happen only in CNA data...

**Comment by jjgao** [comment]
closing this but feel free to reopen.
