### ISSUE TITLE
Survival curve/data(?) issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1280]
http://bit.ly/1U7MzGS

![image](https://cloud.githubusercontent.com/assets/840895/15509411/78f2224a-21a1-11e6-8aee-5631d477c321.png)

**Comment by yichaoS** [comment]
![screen shot 2016-05-31 at 11 20 46 am](https://cloud.githubusercontent.com/assets/5973438/15680066/32b96e9c-2722-11e6-9928-ad9b5bd22f97.png)
