### ISSUE TITLE
Cancer type Validation improvement

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1283]
One minor issue found in the validator is that if your study refers to say 'brca' and your cancer type file refers to something else, say 'test', you will not get an error from the validator if 'brca' exists in DB. This can be improved: if a cancer type is defined in the cancer type file (in the study folder), then the study's meta property `type_of_cancer` should be validated against this and *not* against DB. DB validation for `type_of_cancer` in study meta file should only be done when the cancer type file is missing.

**Comment by fedde-s** [comment]
In short: if any cancer types are defined in the study folder (in a cancer type file), the cancer type of the study must be one of those. A study that defines three cancer types but uses a fourth is invalid, even if that fourth one is defined in the database. Only a study that defines none depends on which cancer types are defined in the database.

**Comment by pieterlukasse** [comment]
not so relevant anymore, according to recent discussion. Cancer types parsed are mentioned in report.
