### ISSUE TITLE
Oncoprints fails to render on OSX Safari and older version of Chrome/Windows

### ISSUE THREAD

**Issue by morungos** [cBioPortal/cbioportal#1289]
JavaScript error is as follows:

```
[Error] TypeError: null is not an object (evaluating 'self.ctx.viewportWidth')
    initializeMatrices (oncoprint-bundle.js, line 3866)
    getWebGLContextAndSetUpMatrices (oncoprint-bundle.js, line 3868)
    getWebGLContextAndSetUpMatricesAndShaders (oncoprint-bundle.js, line 3871)
    OncoprintWebGLCellView (oncoprint-bundle.js, line 3712)
    Oncoprint (oncoprint-bundle.js, line 165)
    CreateCBioPortalOncoprintWithToolbar (setup.js, line 261)
    (anonymous function) (setup-main.js, line 2)
    l (jquery.min.js, line 3)
    fireWith (jquery.min.js, line 3)
    ready (jquery.min.js, line 3)
    S (jquery.min.js, line 3)
[Log] by sample list (cbioportal-datamanager.js, line 923)
```

**Comment by pieterlukasse** [comment]
Actually on a 1.3.2 installation I get this in *Chrome*:

```
oncoprint-bundle.js?1.0:3860 Uncaught TypeError: Cannot read property 'viewportWidth' of nullinitializeMatrices @ oncoprint-bundle.js?1.0:3860getWebGLContextAndSetUpMatrices @ oncoprint-bundle.js?1.0:3862getWebGLContextAndSetUpMatricesAndShaders @ oncoprint-bundle.js?1.0:3865OncoprintWebGLCellView @ oncoprint-bundle.js?1.0:3712Oncoprint @ oncoprint-bundle.js?1.0:163window.CreateCBioPortalOncoprintWithToolbar @ setup.js?1.0:369(anonymous function) @ setup-main.js?1.0:2l @ jquery.min.js?1.0:3fireWith @ jquery.min.js?1.0:3ready @ jquery.min.js?1.0:3S @ jquery.min.js?1.0:3
```
on line:
```
        gl_matrix.mat4.ortho(pMatrix, 0, self.ctx.viewportWidth, self.ctx.viewportHeight, 0, -5, 1000); // y axis inverted so that y increases down like SVG
```

**Comment by pieterlukasse** [comment]
@adamabeshouse this is the issue I mentioned

**Comment by pieterlukasse** [comment]
Same query seems to work in IE11

**Comment by adamabeshouse** [comment]
I can't recreate this on my end. But the problem has to be that webGL isn't available in your browser (please confirm with webglreport.com) , which we should handle more gracefully.

**Comment by pieterlukasse** [comment]
@adamabeshouse thanks for the webgl report link. These are the results (see below). I think that it is indeed due to the combination of old Chrome/Windows on this Citrix environment. 

![pasted image at 2017_01_12 01_45 pm](https://cloud.githubusercontent.com/assets/2900303/21890661/04bb8f7a-d8cf-11e6-95ed-dc9096c4a529.png)

![pasted image at 2017_01_12 01_54 pm](https://cloud.githubusercontent.com/assets/2900303/21890666/10ba5d1a-d8cf-11e6-8551-f7bda42a04ab.png)

**Comment by pieterlukasse** [comment]
@adamabeshouse I agree that catching this and showing a clear message on the UI would be the best solution. Perhaps the message can also contain the link to the test site http://webglreport.com/

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/issues/2060
