### ISSUE TITLE
OQL gene editor should check if a valid mutation is entered.

### ISSUE THREAD

**Issue by shrumit** [cBioPortal/cbioportal#1307]
Currently the gene editor box validates even if an incorrect mutation is entered. Example: "BRCA1: MUT = GIBBERISH" or "BRCA1: GIBBERISH" (where the latter is shorthand for the former) validate correctly.

The user doesn't know that they've entered an invalid mutation ("GIBBERISH") until they hit Submit and see that the Oncoprint chart has nothing. Every gene seems to have a manageable list of mutations which can be validated against before a user submits. 

I'm not sure if someone is already working on this but this is something I'd like to explore. It also ties in with the rest of my GSOC project (autosuggesting mutation keywords).

**Comment by JiaoJiao123** [comment]
@shrumit Are you working on this? It looks interesting to me. I can add the mutation validator.

**Comment by shrumit** [comment]
@JiaoJiao123 I am currently working on this as a part of Summer of Code.

**Comment by JiaoJiao123** [comment]
@shrumit ok sounds good.
