### ISSUE TITLE
oncoprint: adding clinical tracks not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1318]
![image](https://cloud.githubusercontent.com/assets/840895/15825618/85dcd104-2bd2-11e6-8366-d959333bbd18.png)

**Comment by jjgao** [comment]
Sometimes, it returns but very slow. The dropdown box is not always working either.

**Comment by adamabeshouse** [comment]
@jjgao Looks like it's working again, but it is still very slow. I'm not sure what could speed the SQL query up, since it looks like the only link from study to clinical attributes is through several joins, including through the clinical data.

**Comment by jjgao** [comment]
@adamabeshouse but I thought the old API was not as slow.

One option: can we add a cache `Map<Study, Set<Attribute>>` to the new implementation?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1337
