### ISSUE TITLE
coexpression tab not working in firefox

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1324]
somehow it is related to oncoprint code:

![image](https://cloud.githubusercontent.com/assets/840895/15860211/2a428478-2c96-11e6-94a5-51018a9151ba.png)

@yichaoS @adamabeshouse could you look into that?

**Comment by schultzn** [comment]
It seems to affect the Enrichments tab too. Tried Firefox 46.0.1 and 47.0

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1337
