### ISSUE TITLE
clinical data column headers are not readable 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1330]
See screenshot (last 4 columns). Perhaps we should at least add a tooltip to these column headers? 

And URL: http://www.cbioportal.org/study.do?cancer_study_id=brca_tcga#clinical

![image](https://cloud.githubusercontent.com/assets/2900303/15888669/12d0721e-2d68-11e6-8930-c322ede90d39.png)

**Comment by DarioS** [comment]
Allowing the user to click and drag the separating line between adjacent columns to make some columns narrower and others wider would also help.

**Comment by pieterlukasse** [comment]
A tooltip is now visible in fix #1333. 
@zhx828 : maybe you can also implement @DarioS suggestion in a new PR? Or maybe the title could just wrap over two lines if needed?

**Comment by zhx828** [comment]
@DarioS @pieterlukasse  Thanks for the suggestion. #1338 has been created to track the program of resizable column.
