### ISSUE TITLE
slider filter not reset in clinical data table

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1331]
When clicking "Reset" link to reset the filters, text filters are reset/emptied but the slider (numeric) filters are not reset visually. See screenshot of the slider after reset (last column):

![image](https://cloud.githubusercontent.com/assets/2900303/15888848/e8bcdd2c-2d68-11e6-9e55-8d3b983599d4.png)

**Comment by zhx828** [comment]
@pieterlukasse I tried to fix that before, didn't work out. Will take a look again.

**Comment by pieterlukasse** [comment]
solved in #1333
