### ISSUE TITLE
Mutation recurrence in OncoPrint in samples with multiple mutations in the same gene: Recurrent mutation should determine the color

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1332]
If there is at least one recurrent mutation, the color of the mutation glyph should be dark. Currently, it is the opposite. In other words, recurrent mutations trump non-recurrent ones when determining the glyph color.

**Comment by adamabeshouse** [comment]
@schultzn The current version is based on this discussion: https://github.com/cBioPortal/cbioportal/issues/971#issuecomment-207139632

So is that choice revised? Or do you mean that, for example, if a patient has a non-recurrent inframe and a recurrent missense mutation, we should display the dark version of the inframe glyph?

**Comment by schultzn** [comment]
I was referring to samples with multiple missense mutations. If at least one of them is recurrent, that should be indicated in the OncoPrint.

See the example below… L858R is a recurrent EGFR mutation.

This is the query:
http://bit.ly/24BpemX

**Comment by adamabeshouse** [comment]
Ah, I see now, thanks for clarifying.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1346
