### ISSUE TITLE
migrate_db.py executes SQL in random order, making release uninstallable

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#1341]
Since `migrate_db.py` stores the SQL blocks for the different database versions in a Python dictionary and then executes them by looping over the dictionary, the blocks are executed in undefined order, varying from one installation to another. This makes the current release arbitrarily uninstallable on some machines.

**Comment by fedde-s** [comment]
@pieterlukasse: I just saw you encounter this bug.

**Comment by fedde-s** [comment]
This may also be the reason why I ran into the unreproducible issue #1234 earlier.

**Comment by pieterlukasse** [comment]
should be solved in #1343
