### ISSUE TITLE
layout issue in enrichments tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1349]
![image](https://cloud.githubusercontent.com/assets/840895/15953061/84f8f28a-2e94-11e6-91e4-593421ddc094.png)

**Comment by jjgao** [comment]
@yichaoS please also work on this.

**Comment by yichaoS** [comment]
? I couldn't reproduce this issue. May I have an URL with the false layout?

**Comment by jjgao** [comment]
http://bit.ly/2ckaHsL
