### ISSUE TITLE
508 compliance for Study view

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1351]
Issue: we're trying to make the main Study view 508 compliant. The checkboxes in the CNA and Mutation tables are not compliant due to them not having a label (see screenshot). 
- [x] One easy solution is to give them the title attribute, which suffices for 508

**Comment by pieterlukasse** [comment]
@fedde-s can you add the 508 Wave tool screenshot here showing the errors mentioned above?

**Comment by fedde-s** [comment]
![screenshot_study_view](https://cloud.githubusercontent.com/assets/4929431/15963232/a44a5bac-2f10-11e6-8ec9-fcaa9f1ee5b5.png)

**Comment by pieterlukasse** [comment]
@zhx828 so I am specifically referring to the checkboxes below in my copy of the screenshot:

![image](https://cloud.githubusercontent.com/assets/2900303/15964900/1ea10da6-2f1b-11e6-8a03-79c7ff32517a.png)

But if you could proactively add labels to the other items as well that would be great :smiley:

**Comment by fedde-s** [comment]
These fixes have been merged and solved, and the study view has been further made Section 508-compliant as part of pull requests #1494 and #1497.
