### ISSUE TITLE
Shorten study name if it is too long on patient view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#137]
The overview becomes all messed up if the study name is too long:

![screen shot 2015-07-29 at 3 50 47 pm](https://cloud.githubusercontent.com/assets/1334004/8968172/9c2b9702-3609-11e5-808c-51966f7600ad.png)

https://cbioportal.mskcc.org/case.do?cancer_study_id=nsclc_cbe_rielyg_5680_mi&case_id=p_GR_alk_001#nav_case_ids=p_GR_alk_001,p_GR_alk_002,p_GR_alk_003,p_GR_alk_004,p_GR_alk_005,p_GR_alk_006,p_GR_alk_007

**Comment by jjgao** [comment]
@inodb could you prioritize this?

**Comment by inodb** [comment]
Done
