### ISSUE TITLE
Fix images in validator documentation

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#1375]
The images of HTML screenshots seems to have disappeared from validator document:
https://github.com/cBioPortal/cbioportal/blob/master/docs/Using-the-dataset-validator.md

**Comment by fedde-s** [comment]
The images have been restored and updated as of v1.2.5, as implemented by the pull request that referenced this issue. @priti88, can this be closed?

**Comment by pieterlukasse** [comment]
they even have a nice 3D effect to them now  👍 I'll close it. @priti88 feel free to reopen if you disagree.
