### ISSUE TITLE
Mutation view hangs when gene length is NULL and pfam_graphics is not available

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1378]
Example: 

http://www.cbioportal.org/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TBC1D3K+LOC101060389+&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

![image](https://cloud.githubusercontent.com/assets/2900303/16111078/43e93c60-33b1-11e6-978b-a0c5c1afb29f.png)

**Comment by pieterlukasse** [comment]
@onursumer how to deal with this scenario? Can you check this?

**Comment by onursumer** [comment]
@pieterlukasse : I think we should still try to show the diagram without pfam domains, or at least the table without the diagram. This requires some improvement in the mutation mapper library.

**Comment by pieterlukasse** [comment]
@onursumer : at least the table would be nice. Showing a diagram when the length of the gene is unknown is harder, then you would have to infer from other data....

**Comment by jjgao** [comment]
table showed up now, but not the diagram.

![image](https://user-images.githubusercontent.com/840895/43276056-844ebb0c-90d1-11e8-9494-b7fd25a6d117.png)

**Comment by jjgao** [comment]
@onursumer maybe at least display a message.

Is it possible to analyze all genes and see how many more have this problem? Is it fixable from the data? cc'ing @inodb too.

**Comment by pieterlukasse** [comment]
@jjgao this issue is still present. See

https://www.cbioportal.org/results/mutations?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=brca_tcga&case_set_id=brca_tcga_cnaseq&data_priority=0&gene_list=TBC1D3K%2520TBC1D3D&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&tab_index=tab_visualize

**Comment by jjgao** [comment]
@onursumer any update on this?

**Comment by ecerami** [comment]
@onursumer @pieterlukasse:  looks like this now may be fixed?  can we close?

**Comment by jjgao** [comment]
closed this one and open [an issue](https://github.com/genome-nexus/genome-nexus/issues/374) in Genome Nexus.
