### ISSUE TITLE
No easy-to-find documentation on configuring Study search options

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1380]
At one of our installations we got the request to change the list of studies displayed at the search box (see screenshot):

![image](https://cloud.githubusercontent.com/assets/2900303/16119271/0d21dc1c-33db-11e6-9968-671e88df9811.png)

Is this configurable? How to do it? If not, could we add a portal.properties for this, or let it be based on the list of studies in the portal (taking into account authorization settings for the user)?

**Comment by fedde-s** [comment]
This has been solved in the hotfix release now.
