### ISSUE TITLE
TCGA staging files issues

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1382]
New fresh ticket to keep track of issues in the most recent staging files

- [x] many files have `[Not Available]` in the `Entrez_Gene_Id` column. This is not supported. The supported values are: empty cell or `0` for missing value, or a number
- [x] SAMPLE_ID and PATIENT_ID are duplicated in clinical files (e.g. 4 columns instead of 2)
- [x] missing case lists
- [x] invalid non-numeric values in clinical NUMERIC columns
- [x] empty files. E.g. `data_RNA_Seq_v2_expression_median.txt` was empty in brca study

@jochemb: please add other items if any.

**Comment by zheins** [comment]
All these items are taken care of now in the post processing.

**Comment by zheins** [comment]
Theres another weird issue where some of the mafs from firehose do not have consistent number of columns throughout the file. Post processing now fixes this as well.

**Comment by zheins** [comment]
Post processing current is doing the following:

        1. Remove null values with NA in all files
        2. Remove '.' characters in the MAF with NA
        3. Remove '+' chacters from numberical values from clinical files
        4. Check that all tcga patient/sample ids are truncated
        5. Remove duplicate samples in the clinical files
        6. Replace empty cells (replace-empty-cell.py)
        7. Composite.Element.Ref should be Composite.Element.REF
        8. Remove OTHER_PATIENT_ID from the sample clinical file
        9. Remove hg18
        10. Ensure no [Not Available] in Entrez_Gene_Id Columns
        11. Case lists tcga barcode truncation
        12. Fix mafs with inconsistent columns
        13. Remove .merged file (bug in annotation)

**Comment by pieterlukasse** [comment]
@zheins thanks for the update. We will test here and let you know. One request from my side: can you please log the firehose MAF file issue at firehose and report the ticket nr here? I would like to understand this better.

**Comment by pieterlukasse** [comment]
@zheins here are the remaining issues for **BRCA**

- [ ] let `HER2_COPY_NUMBER` and `CENT17_COPY_NUMBER` have type `STRING` in data_bcr_clinical_data_patient.txt
- [ ] change ids `days_to_patient_progression_free` and `days_to_tumor_progression`  to ALL CAPS in data_bcr_clinical_data_patient.txt
- [ ] just to be sure nothing is wrong in processing, check why there is no clinical data for patients `TCGA-3C-AAAU, TCGA-AN-A0FG, TCGA-E2-A1IP, (2 more)` in data_bcr_clinical_data_patient.txt while there are samples for these patients in data_bcr_clinical_data_sample.txt
- [ ] there are still duplicates in data_bcr_clinical_data_sample.txt : `TCGA-A7-A13G-01 (already defined on line 54), TCGA-B6-A1KC-01 (already defined on line 71), TCGA-A7-A26E-01 (already defined on line 465), (14 more)`
- [ ] in data_CNA.txt there are duplicated lines: `645425 (already defined on line 213), 51463 (already defined on line 1316), 284565 (already defined on line 1340), (62 more)`
- [ ] in data_expression_median.txt there are duplicated lines: `119016 (already defined on line 3524), 6209 (already defined on line 3912), 50810 (already defined on line 1374), (54 more)`
- [ ] in many files there is Entrez_gene_id=0 . This is only allowed in MAF files, because there it has a meaning when accompanied by Hugo_gene_symbol=Unknown. So please make Entrez_gene_id empty in all files that are not MAF and where it is 0 now.

**Comment by pieterlukasse** [comment]
@zheins here are the remaining issues for PRAD

- [ ] basically the same errors as in BRCA, with a few additional ones below:
- [ ] Value in column 'Verification_Status' is invalid: should be empty instead of `[Not Available]` in data_mutations_extended.txt.
- [ ] Value in column 'Validation_Status' is invalid: should be empty instead of `[Not Available]`, or `---` in data_mutations_extended.txt.

**Comment by zheins** [comment]
The issues with the samples being in bcr_sample and not bcr_patient is a data source issue - not a processing issue.

For duplicated lines, they aren't actually duplicated. They have different ORFs or Hugo Symbols that map to the same entrez id with sometimes different values. We don't really have a way of handling this in the import - I think prior to this we just imported the last row. We can delete the "duplicate" but we could potentially be losing information in the file. Same for the expression/meth files.. @n1zea144 can you comment? Should we just pass through what we get from Firehose?

**Comment by n1zea144** [comment]
I just placed placed the latest tarballs that Zack created on the http server:

85e76851f2f05f1d53b39f788f188fe7  /data/zack/brca.tar.gz
7a61640df9b9f6da1e8ea982bda97777  /data/zack/prad.tar.gz

I'd prefer to pass the data through, the logic of the scripts package will handle duplicate rows of data.

**Comment by pieterlukasse** [comment]
we've got our first version of the data without blocking errors :tada:
