### ISSUE TITLE
use preprocessed methylation data from firehose

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1384]
I just noticed that Broad has a new file e.g.

http://gdac.broadinstitute.org/runs/stddata__2016_01_28/data/STAD/20160128/

gdac.broadinstitute.org_STAD.Methylation_Preprocess.Level_3.2016012800.0.0.tar.gz

There is a file called STAD.meth.by_min_expr_corr.data. We should be just using this file instead of calculating by ourselves.

**Comment by n1zea144** [comment]
Moving to pipelines tracker.
