### ISSUE TITLE
CCLE data mistake?

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1406]
The public study loaded at 
http://www.cbioportal.org/study?id=cellline_ccle_broad#summary

seems to have a mistake in the clinical attribute data. 
![image](https://cloud.githubusercontent.com/assets/2900303/16302960/3ca0a126-394e-11e6-826b-cc0c077df988.png)

The values in "Tumor type" seem to be switched with "Cancer type". 

@schultzn, @jjgao  : what do you think? Adding the values in "Tumor type" to "Cancer type" would also yield a more useful pan-cancer histogram for this pan-cancer study.

**Comment by pieterlukasse** [comment]
@zheins @n1zea144 could you check this one please?

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #275](https://github.com/cBioPortal/datahub/issues/275) via [**ZenHub**](https://www.zenhub.com/)
