### ISSUE TITLE
Samples with 0 mutations should show up as 0 in the # mutations clinical track

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1418]
They are currently showing as undefined... should be 0 and sorted on the other end.

http://bit.ly/292eQk7

![image](https://cloud.githubusercontent.com/assets/11892704/16428243/05eca11c-3d3f-11e6-9fa6-ccc16412eee8.png)

**Comment by adamabeshouse** [comment]
@schultzn: Same for fraction genome altered?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1421

**Comment by schultzn** [comment]
Yes
