### ISSUE TITLE
Study view: Mutation count vs CNA plot log x bug

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#143]
There is a bug in the Mutation Count vs CNA plot in the study view. If one activates log scale on the x-axis before having activated it on the y-axis, the dots are at incorrect locations:

![mutationcount_vs_cna_bug](https://cloud.githubusercontent.com/assets/1334004/9010460/09a84e44-3775-11e5-8849-d5a162d2b36d.gif)

**Comment by inodb** [comment]
This is on current mskcc portal btw

**Comment by zhx828** [comment]
@inodb Thanks. Will work on it

**Comment by zhx828** [comment]
Exist in mskimpact dataset
