### ISSUE TITLE
Add support for hg38 in data validation script

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1437]
Most of the portal (except for patient view > genome overview plot) is not bound to a specific genome build version. Therefore it would be good to be more flexible about this in the data validation script, which currently only allows hg19/GRCh37. 

Changes needed:
- meta file for mutation data should get a new attribute, just like already present in segment data: `reference_genome_id`. E.g. `reference_genome_id: hg19`
- table `genetic_profile` should store the value for this attribute (both for segment data as for mutation data)
- validation script should check if the new study being validated has the _same_ genome build as stored for previous studies in the target portal (where the data will be loaded). It should give an error if this is not the case. Nb: this is because although the portal supports multiple genome builds, they can't be mixed up in the same installation because of possible differences in the genes present in each build (`gene` table in portal is not versioned). 
- validation script should check if the build used in mutation _data_ file is the same as specified in the new _meta_ file attribute.

For later (other ticket perhaps):
- let patient view genome overview display the chromosome lengths based on the genome build found in the `genetic_profile` table.

**Comment by pieterlukasse** [comment]
@oplantalech can you please reference the PRs that solve this issue?

**Comment by oplantalech** [comment]
@pieterlukasse The last thing I did regarding hg38 was #2671. One of the things I did in this PR was removing documentation regarding hg38 because I didn't work on that during my internship and I assumed cBioPortal supported hg38. But if now we want to implement that, we can take a look on the changes I did to implement mouse.

**Comment by jjgao** [comment]
closing this. Please feel free to reopen.
