### ISSUE TITLE
Building from Maven Wiki Page Has Multiple Errors?

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1446]
On the current "Building from Source" Wiki page:  https://github.com/cBioPortal/cbioportal/blob/master/docs/Build-from-Source.md

We have two problems:
1.  At the top of the page, we say:

First, set your $PORTAL_HOME environment variable to point at your cbioportal.org check-out. (so that $PORTAL_HOME/src/main/resources/portal.properties exists and is properly populated)

However, the previous pre-build page already contains instructions on setting $PORTAL_HOME.
1.  Three sentences later, we contradict ourselves:

If you have placed your properties in the default location, e.g. src/main/resources, your PORTAL_HOME must point to this exact directory. For example:

export PORTAL_HOME="/Users/ecerami/dev/cbioportal/src/main/resources"

What should PORTAL_HOME actually be pointing to?

(Assigning to myself, but tagging @aderidder, since he seems to have written the text;  also tagging @pieterlukasse, in case he knows.  Please add your comments below, and I will update the wiki doc).

**Comment by pieterlukasse** [comment]
I would say PORTAL_HOME should point to `Users/ecerami/dev/cbioportal/` in your example. This is based on my experience until now. 

But I found at least one commit that seems to change this, so I'm afraid I'm outdated on this point: https://github.com/cBioPortal/cbioportal/commit/b101762  @zheins can you comment on this?

**Comment by zheins** [comment]
@n1zea144 can you comment? I know we made some changes for the docker branch and for some other logging issues we had.
