### ISSUE TITLE
Loading sample study wiki page:  questions

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1447]
On the current wiki page for loading a sample study:  https://github.com/cBioPortal/cbioportal/blob/master/docs/Load-Sample-Cancer-Study.md

Why does this page mention all the individual steps for loading a study?  Can't we just use the single importer script to load everything within one directory?

Are all the CONNECTOR_JAR and CORE_JAR steps also really required?  (Seems very complicated)

Tagging @aderidder @pieterlukasse

**Comment by ecerami** [comment]
Also, this command does not actually run:

$PORTAL_HOME/core/src/main/scripts/cbioportalImporter.py --jvm-args "-Dspring.profiles.active=dbcp -cp $CONNECTOR_JAR:$CORE_JAR" --command import-study --meta-filename portal-study/meta_study.txt

cbioportalImporter.py is now located under scripts/importer.  But, the --jvm-args also no longer seems to be supported.

**Comment by pieterlukasse** [comment]
This page is indeed outdated and can be removed.
