### ISSUE TITLE
Seed database is out of date

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1449]
The current seed database does not work with the current code.

We need to download the current seed database:  http://cbio.mskcc.org/cancergenomics/public-portal/downloads/cbioportal-seed.sql.gz

apply the migration script: https://github.com/cBioPortal/cbioportal/blob/master/docs/Updating-your-cBioPortal-installation.md

And, then replace the seed database.

**Comment by pieterlukasse** [comment]
related to #767

**Comment by ersinciftci** [comment]
New seed database is uploaded here: https://storage.googleapis.com/cbiostorage-1/cbioportal-seed.sql.gz
