### ISSUE TITLE
Travis occassionally fails

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1454]
I made a few small changes to docs today, and got back a travis failure message:

https://travis-ci.org/cBioPortal/cbioportal/builds/142465187

According to @ersinciftci:

These 2 tests fail sometimes depending on the Junit test running order 
(which is random): 

TestWebService.testGetCancerStudySetProfileID:334 expected:<1> but was:<0> 
TestWebService.testGetCancerStudySetPrivateProfile:351 expected:<1> but 
was:<0> 

We are aware of this and someone was working on it, I don't remember if 
it was @morungos  or @inodb or @pieterlukasse , I'll check and fix myself if no one is 
working on it. For now you can restart the build by clicking the Restart 
Job button in the upper right corner. 

Has anyone already volunteered to fix this one?

**Comment by inodb** [comment]
I'm not working on this.

I did fix some of the problems with the screenshot test occasionally failing by adding a retry: https://github.com/cBioPortal/cbioportal/pull/1402

**Comment by morungos** [comment]
Can't remember this specific case, but it shouldn't be happening unless the DB running the tests isn't being fully transactional, i.e., I hope it's all under InnoDB. However, if it isn't, I'd expect more than this to fail. 

Another possibility is weird caching. I really don't like the caching behaviour much, because `DaoCancerStudy.deleteCancerStudy` can get executed and rolled back, but the cache, of course, won't be. So maybe a teardown that clears the cache will sort it, but that might be needed in a bunch of places.

**Comment by pieterlukasse** [comment]
I think that one of the improvements that could be made in this test class is to make it self sufficient. It seems to depend on a pre-existing study `study_tcga_pub` which is added by some other test step. The current setup is probably based on the initial idea of having a global "mini seed DB" for *all* the tests, filled with data that could be used in all the tests. Although I think this could be a nice idea, in practice I think it can be quite hard to have every test developer add their test data to the same "mini seed DB" without breaking other tests. Therefore we already started making some of the tests self sufficient (at least for some of their data, like gene list - see for example tests where we add dummy genes before running a test, such as `daoGene.addGene(new CanonicalGene(999999672, "TESTBRCA1"));` )

**Comment by ecerami** [comment]
Assigning to @ersinciftci as no one else has specifically signed up to fix this.

**Comment by ersinciftci** [comment]
TestImportTabDelimData.testImportmRnaData2:348 expected:<[9]> but was:<[NaN]>
is randomly failing too. This is a bigger issue that I'll focus after the rearch Sprint 3.

**Comment by ersinciftci** [comment]
I think this is not happening anymore.
