### ISSUE TITLE
Mismatched PMID field type in study API

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#1456]
[DBStudy.java](https://github.com/cBioPortal/cbioportal/blob/rc/business/src/main/java/org/mskcc/cbio/portal/model/DBStudy.java#L21) expects the PMID retrieved from the database to be parseable as an integral number, but in [the database](https://github.com/cBioPortal/cbioportal/blob/hotfix/core/src/main/resources/db/cgds.sql#L83) it is stored as a text string. This makes the study API throw exceptions if a study has been loaded listing a non-numeric value in its metadata file.

**Comment by fedde-s** [comment]
Updated links as I forgot to link to a specific version of the files above:
- [DBStudy.java](https://github.com/cBioPortal/cbioportal/blob/v1.7.2/business/src/main/java/org/mskcc/cbio/portal/model/DBStudy.java#L21)
- [the database schema](https://github.com/cBioPortal/cbioportal/blob/v1.7.2/db-scripts/src/main/resources/cgds.sql#L120)

**Comment by jjgao** [comment]
Does @ersinciftci read it out as String now in the new code?

**Comment by sheridancbio** [comment]
The new api model does output PMID as String. See: model/src/main/java/org/cbioportal/model/CancerStudy.java

**Comment by fedde-s** [comment]
I believe that has been fixed by pull request https://github.com/cBioPortal/cbioportal/pull/2979.
