### ISSUE TITLE
Seed database is currently 7GB and could be much smaller

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1460]
Seed database is currently 7GB;  almost 5 GB is devoted to PDB.  Would be great if we could make this much smaller.

**Comment by fedde-s** [comment]
I believe this is being addressed in pull request #1696.

**Comment by sheridancbio** [comment]
Yes, The PDB portion has been split out (and will disappear altogether soon once that functionality moves to genome-nexus / pdb-annotation and dynamic browser queries to mutation assessor) by thehyve and a new seed is nearly ready (I am reviewing)

**Comment by sandertan** [comment]
We can probably close this issue, current sizes:
- Seed: 49.7 MB
- Only PDB: 747 MB

https://github.com/cBioPortal/datahub/blob/master/seedDB/

**Comment by fedde-s** [comment]
Yes, I think it would make sense to track any further needs for enhancements in a separate issue if necessary. If anyone disagrees, feel free to re-open.
