### ISSUE TITLE
Bar graphs not shown correctly

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#1477]
The X axis in the Diagnosis Age and Mutation Count do not correspond to the bars displayed above, in this study: http://www.cbioportal.org/study?id=paac_jhu_2014#summary

There are no NAs on the data in both Diagnosis Age and Mutation Count, but the plots indicate the opposite. The bars pointing on NAs in Mutation Count should correspond to the previous value in the axis (>240), but this does not happen in the Diagnosis Age (according to the plot, there should be 8 NAs, while there are 13 people that were more than 60 years older when diagnosed).

**Comment by pieterlukasse** [comment]
@zhx828 : could you please check this one?

**Comment by JiaoJiao123** [comment]
@pieterlukasse @zhx828 I will look into this, wondering if it is related to something I worked on earlier.
