### ISSUE TITLE
Expression data missing in rc oncoprint

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1478]
Hi @adamabeshouse, it looks like oncoprint is broken in `rc` for expression data. Perhaps since #1416?

I fire the same query in my local environment (`rc`) and on cbioportal.org and in the `rc` version I don't get the expression data. See screenshots:

Query: http://www.cbioportal.org/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=brca_tcga_rna_seq_v2_mrna_median_Zscores&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_3way_complete&case_ids=&patient_case_select=sample&gene_set_choice=prostate-cancer%3A-ar-signaling-%2810-genes%29&gene_list=SOX9+RAN+TNK2+EP300+PXN+NCOA2+AR+NRIP1+NCOR1+NCOR2&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

**master**
![image](https://cloud.githubusercontent.com/assets/2900303/16762959/124c72e6-4827-11e6-92ed-9ad0da6b72a9.png)

**rc**
![image](https://cloud.githubusercontent.com/assets/2900303/16762874/bb44b5f8-4826-11e6-86f5-1215067ce5b6.png)

**master (on my local env - for completeness)**
![image](https://cloud.githubusercontent.com/assets/2900303/16763095/a3e7a20c-4827-11e6-921e-49216d533b3e.png)

**Comment by pieterlukasse** [comment]
found by @awernibi

**Comment by adamabeshouse** [comment]
Good catch, this is a bug due to a bad design decision. I'll fix this immediately.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1483

**Comment by fendor** [comment]
It seems the bug still or occurs again:

[cBioPortal](http://www.cbioportal.org/index.do?cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=coadread_tcga_pub_mrna_merged_median_Zscores&Z_SCORE_THRESHOLD=0.1&data_priority=0&case_set_id=coadread_tcga_pub_3way_complete&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=KRAS&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&)

[cBioPortalBeta](http://www.cbioportal.org/beta/index.do?cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=coadread_tcga_pub_mrna_merged_median_Zscores&Z_SCORE_THRESHOLD=0.1&data_priority=0&case_set_id=coadread_tcga_pub_3way_complete&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=KRAS&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&)

On our local version, which is up to date with the rc, the same problem happens.

**Comment by adamabeshouse** [comment]
The fix hasn't been merged yet :)

**Comment by pieterlukasse** [comment]
@adamabeshouse it still occurs on /beta:

http://www.cbioportal.org/beta/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=brca_tcga_rna_seq_v2_mrna_median_Zscores&Z_SCORE_THRESHOLD=1&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_3way_complete&case_ids=&patient_case_select=sample&gene_set_choice=prostate-cancer%3A-ar-signaling-%2810-genes%29&gene_list=SOX9+RAN+TNK2+EP300+PXN+NCOA2+AR+NRIP1+NCOR1+NCOR2&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

Any plans to update /beta?
