### ISSUE TITLE
Improve and simplify the installation procedure by having intermediate success screen

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1485]
The current installation procedure includes a data loading step before starting the web server. This is to avoid an error message on the home page when there are no studies loaded. I think this step could be skipped if we can improve the home page for the scenarios where there are no studies yet (discussed in #1455).
My _preferred_ option would be to have something like tomcat does now as well: even before you install any web applications, you can already see that the tomcat installation went well (see screenshot). I.e. the installation documentation would describe the steps up to getting the homepage to work. When going to the homepage for the first time, users will be greeted by a nice green success banner (just like with tomcat), telling them that the installation executed successfully and that they can proceed with the next step, which is _data loading_.

Tomcat example (for inspiration):
![image](https://cloud.githubusercontent.com/assets/2900303/16648155/fa93540a-4432-11e6-90ad-e69e32093cc0.png)

cBioPortal idea:

![image](https://cloud.githubusercontent.com/assets/2900303/16648135/dcf0fd26-4432-11e6-8786-e63ae7137646.png)

**instead** of the current message:

![image](https://cloud.githubusercontent.com/assets/2900303/16648195/26d8002e-4433-11e6-9ab4-babe56d7db4f.png)

Also discussed with @ecerami and @ersinciftci and they like the idea.

**Comment by pieterlukasse** [comment]
@inodb what do you think of this idea? I think this will help people starting with cBioPortal

**Comment by fedde-s** [comment]
Yes, the message that reports a correctly set-up installation as a database connection error is still occasionally confusing people.

**Comment by inodb** [comment]
@pieterlukasse Yes, this would be a great feature!

**Comment by fedde-s** [comment]
Has this been resolved now that the entire homepage has been replaced by one written in a different  language?
