### ISSUE TITLE
Remove unimplemented OQL features from documentation

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#1496]
In particular, as noticed by @pieterlukasse, the syntactic sugar (e.g. `CNA >= GAIN` or just `CNA` for `AMP HOMDEL`)

**Comment by pieterlukasse** [comment]
@adamabeshouse thanks for adding the ticket. I would like to propose a review of the documentation at http://www.cbioportal.org/onco_query_lang_desc.jsp. So:
- [ ] test each of the examples listed there
- [ ] remove or fix the ones that don't work

New users will probably follow these examples first, before trying their own. @schultzn : can you also help with this one, testing and giving feedback on what can be removed and what should be fixed?

**Comment by pieterlukasse** [comment]
there is also a small bug in the label shown when using OQL. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/2900303/16869639/10e9af8c-4a7e-11e6-804f-5cce9725c931.png)

The expression was on `D96` but the label only shows `96` (I assume it is just a problem with the label - haven't tested further yet). 

One small request from a user was: could the expression be shown on the screen itself instead of only at the pop-up? In this way it is easier to use it in a presentation or document/article. Otherwise you have to edit the figure to add these expressions manually.

**Comment by schultzn** [comment]
I don’t see the same issue in a similar query … see below

I don’t understand the user request. What do you mean by “expression”? mRNA expression level?

**Comment by pieterlukasse** [comment]
@schultzn with "expression" I meant the OQL query, e.g.  `BRCA1:MUT=D96`, sorry for the confusion. 

In your last message it looks like you intended to add a screenshot, but I think that failed somehow. Can you try again?

**Comment by schultzn** [comment]
I responded via email - maybe that does not support including images. I will try again later via the web interface.

I don’t see how an OncoPrint would permanently show the OQL text, i.e. the actual mutation. There is simply no space in this compact visualization.

Niki.

**Comment by adamabeshouse** [comment]
It seems like there may be some miscommunication here.. 

@pieterlukasse I see the issue and I am in the process of fixing it - the issue is that since the amino acid is really redundant information as far as filtering goes, it's not stored during parsing, and so isn't available when printing the query out.

**Comment by pieterlukasse** [comment]
@schultzn : yes, space is quite limited. Maybe we can make it a view option? We already have some options there, so perhaps we could add it there (see screenshot):
![image](https://cloud.githubusercontent.com/assets/2900303/16909396/c6a35e8a-4cd2-11e6-90c1-cf5a7f9375ac.png)

**Comment by schultzn** [comment]
I still don’t see how you would visualize the exact mutation strings. Can you make a mockup?

**Comment by adamabeshouse** [comment]
@pieterlukasse For what it's worth, if you click on "Modify Query" the whole expression would be there.

**Comment by pieterlukasse** [comment]
Hi @schultzn , something like this:

![image](https://cloud.githubusercontent.com/assets/2900303/16941710/15594552-4d92-11e6-9bea-30061e1c5db0.png)

So when "Show OQL filters" is checked, some extra space could be made such that the complete OQL strings are shown.

**Comment by pieterlukasse** [comment]
### Regarding this ticket:
@adamabeshouse  our client is actually asking to keep all the documented features, so e.g. `CNA >= GAIN` should stay. So instead of removing from documentation, implement what is documented. @schultzn what do you think? Or should some of the documented features really be removed?

### Regarding the new "Show OQL filters"  feature: 
I will log a new ticket for that.

**Comment by schultzn** [comment]
Thanks. Keep in mind though that an OQL string could be very long - how do you plan to deal with those?

**Comment by schultzn** [comment]
I don’t think these documented features are necessary to have - all functionality is still available via combinations of categories. So it depends on how much extra work it is.

**Comment by pieterlukasse** [comment]
@schultzn thanks. @adamabeshouse can you give an idea about this? Is it feasible for you to let the implementation match the documentation? Please let us know if you think it is better to remove some of the documentation options in the short term until they are really available in OQL (depends a bit on how fast the issues could be solved).

**Comment by schultzn** [comment]
It is a very simple change to modify the OQL description from:

 CCNE1:  CNA >= GAIN
which can also be written:

 CCNE1:  GAIN AMP


to:

 CCNE1:  GAIN AMP


No functionality lost!

Keep it simple?

What other documented commands are not working?

Niki.

**Comment by adamabeshouse** [comment]
@pieterlukasse @schultzn It wouldn't be too much work to implement if it's wanted.

**Comment by schultzn** [comment]
Up to you… :-)

**Comment by adamabeshouse** [comment]
@schultzn I've never seen this before - what does this mean? Should it be removed?

![image](https://cloud.githubusercontent.com/assets/636232/17264577/e6cb1126-55b5-11e6-8b08-f8a12603dd02.png)


If so, then the only 2 discrepancies between documentation and implementation are:
- `CNA >= ...` is documented and not implemented
- `MUTATED` is documented as an allowed keyword, but implementation only allows `MUT`

**Comment by schultzn** [comment]
Let’s discuss with JJ - this is OQL specific for RPPA protein data, and we should keep it.

N

**Comment by pieterlukasse** [comment]
@adamabeshouse thanks for reviewing it! The PHOSPHO example you mentioned is probably a feature that just works via the `gene_alias` table and is not a OQL specific feature. 

@awernibi can you confirm this list of issues or have you found more documentation issues?

**Comment by adamabeshouse** [comment]
Ah ha, okay very good to know, thanks.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/issues/1496
