### ISSUE TITLE
Wiki Page Describing Clinical Data File Format needs Clarifications

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#15]
I am trying to load a simple clinical data file.

But, nothing is going in.

I think this is because I am misunderstanding the clinical file format described here:  https://github.com/cBioPortal/cbioportal/wiki/File-Formats#clinical-data

I am happy to fix the docs, but need some help from others with a few questions:

1.  Is it possible to load a clinical data file with only a PATIENT_ID column (e.g. no SAMPLE_ID)?
2.  If the above is true, I think it is correct to say that one must specify:

one of (PATIENT_ID or SAMPLE_ID) or (PATIENT_ID followed by SAMPLE_ID)

These lines are also a little confusing:  "A clinical data file is a two dimensional matrix with a sample id per row and a clinical attribute per column.  For each sample-attribute, an atomic value represents the clinical attribute for that sample."  

Should it be:  "A clinical data file is a two dimensional matrix with multiple clinical attributes which can be attached to either a patient or a sample."?

**Comment by ecerami** [comment]
Related to this, I will be checking in two (small) changes.

1.  If you file failed to contain a PATIENT_ID or SAMPLE_ID, you now get an error:

Reading data from:  /Users/ecerami/Desktop/firehose/profile_out/data_clinical.txt
 --> total number of lines:  3686
Aborting!  Could not find:  PATIENT_ID or SAMPLE_ID in your file.
Please check your file format and try again.

2.  The tool now reports back total number of records actually added, e.g.

Reading data from:  /Users/ecerami/Desktop/firehose/profile_out/data_clinical.txt
 --> total number of lines:  3686
36850 records inserted into clinical_patient
Total number of patient specific clinical attributes added:  18425
Total number of sample specific clinical attributes added:  0
Success!

If a total of 0 records is added, you get an error message.

**Comment by n1zea144** [comment]
Thanks for catching this Ethan.  A clinical data file requires both a PATIENT_ID and SAMPLE_ID column.  Once we started to support multiple samples/patient, we needed a way to capture the mapping between patients and their samples.  In addition to capturing patient and sample attributes, the clinical data file serves this purpose.

The documentation you found is out of data.  What you say is correct.

**Comment by n1zea144** [comment]
Should I close this issue or will you?

**Comment by ecerami** [comment]
ok, thanks.  I will fix the docs and close.


Sent from mobile phone.  Please excuse typos.

-------- Original message --------

**Comment by ecerami** [comment]
Thanks.  I have updated the wiki docs on this to clarify that both PATIENT_ID and SAMPLE_ID is required.   All described here:  https://github.com/cBioPortal/cbioportal/wiki/File-Formats#clinical-data.  Closing.
