### ISSUE TITLE
Valid Characters for Sample Id etc...

### ISSUE THREAD

**Issue by fendor** [cBioPortal/cbioportal#1502]
What characters are allowed for the Case_lists, Sample_Ids etc... and which cause problems?

We noticed that characters like semicolon, underscore, paranthesis and hyphen are no problems, but characters like colon, or slash do cause problems in the web application although they are correctly inserted into the database.

Also the oncoprint shows unknown Stable_ids as undefined, and does not report any problems.

**Comment by fendor** [comment]
We tested the Characters by introducing a fake study with the valid an invalid characters.

Problems were searched in the Data Set Study overview or Oncoprint view.

 These Characters cause problems in either data set view or Oncoprint: 

"/,"&'+<>"

These special Characters work for almost sure since the cBioPortal uses it itself:

"-.();_"

Adn these tested Characters worked and are most probably ok:

"$!#%*:=?@[]` {}|~"

Exceptions were: 

Data Set:  Internal Exception, InterIdUtil threw an NullPointer

Oncoprint: Sample couldn't be correctly displayed and values weren't displayed correctly.

**Comment by jjgao** [comment]
here are valid characters: https://github.com/cBioPortal/datahub/issues/192
