### ISSUE TITLE
Cross cancer page hangs when studies have no CNA data

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1514]
When selecting "CNA data only" query for studies where _no_ CNA data is present, then cross-cancer histogram page will hang with a javascript error. See screenshot. This is the URL to reproduce it: 

http://www.cbioportal.org/cross_cancer.do?cancer_study_list=&cancer_study_id=all&data_priority=2&case_ids=&patient_case_select=sample&gene_set_choice=glioblastoma%3A-tp53-pathway-(4-genes)&gene_list=CDKN2A+MDM2+MDM4+TP53&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&Action=Submit#crosscancer/overview/2/CDKN2A%20MDM2%20MDM4%20TP53/blca_bgi%2Cpaac_jhu_2014

![image](https://cloud.githubusercontent.com/assets/2900303/16986967/cd5e6cf2-4e89-11e6-9669-b7d8c14d5617.png)

![image](https://cloud.githubusercontent.com/assets/2900303/16986780/b9c5c7b8-4e88-11e6-834f-704f7d346046.png)

A related issue is also found when a similar query is done, but now containing a mix of studies _with_ and _without_ CNA data. The page tries to display a warning banner with the study names of the studies where no CNA data is found, but the banner contains an empty list. See screenshot. This is the URL to reproduce it: 

http://www.cbioportal.org/cross_cancer.do?cancer_study_list=&cancer_study_id=all&data_priority=2&case_ids=&patient_case_select=sample&gene_set_choice=glioblastoma%3A-tp53-pathway-(4-genes)&gene_list=CDKN2A+MDM2+MDM4+TP53&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&Action=Submit#crosscancer/overview/2/CDKN2A%20MDM2%20MDM4%20TP53/blca_bgi%2Cbrca_tcga%2Cpaac_jhu_2014

![image](https://cloud.githubusercontent.com/assets/2900303/16986808/e678ba7c-4e88-11e6-812a-287a8132b2da.png)

**Comment by pieterlukasse** [comment]
@yichaoS @JiaoJiao123 @jjgao known issue?

**Comment by pieterlukasse** [comment]
@yichaoS @JiaoJiao123 @jjgao : I'm looking at this one now...still present

**Comment by pieterlukasse** [comment]
@jjgao this bug is still present

**Comment by jjgao** [comment]
We are replace cross_cancer.do and reimplementing it in index.do. Will check later.

**Comment by pieterlukasse** [comment]
the issue is different now...the studies will be listed in the cross cancer histogram as if they have no alterations for the selected gene, while in reality there is no CNA data... Will close the current ticket, which is solved, and open a new one.
