### ISSUE TITLE
Inconsistent sample counts in oncoprint

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1515]
The oncoprint overview shows inconsistent sample counts. See screenshot. URL to reproduce this:

http://cbioportal-test.thehyve.net/cbioportal/index.do?cancer_study_list=thca_tcga&cancer_study_id=thca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=thca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=thca_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=thca_tcga_all&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=BRAF&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

Screenshot (i.e. is it 567 samples or 511?):
![image](https://cloud.githubusercontent.com/assets/2900303/16988537/06deef2c-4e91-11e6-8f19-6710f199530a.png)

Notify: @adamabeshouse

**Comment by pieterlukasse** [comment]
is actually related to one of the points mentioned in #1417

**Comment by pieterlukasse** [comment]
and is widespread over all studies/case lists. Here another example using breast cancer study:

![image](https://cloud.githubusercontent.com/assets/2900303/16988781/dbbcc6e2-4e91-11e6-9b29-1202a872c283.png)

**Comment by pieterlukasse** [comment]
adding @n1zea144 and @zheins to the discussion as well

**Comment by adamabeshouse** [comment]
I think this is an import/backend error - everything agrees on the page except for the case set name, which includes '(1202 samples)'.

I have a screenshot from the console which may illustrate what's going on here:

![image](https://cloud.githubusercontent.com/assets/636232/17070422/d6607a92-5029-11e6-9eda-cd6da799e688.png)

**Comment by adamabeshouse** [comment]
The data problem remains but https://github.com/cBioPortal/cbioportal/pull/1569 makes the UX issue moot by not displaying the case set description, which is what includes the sometimes erroneous sample count.
