### ISSUE TITLE
Show OQL filters in oncoprint

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1527]
Request from a user: could the OQL filter be shown on the screen itself instead of only at the pop-up? 

This not only improves the view itself, it also makes it easier to use it in a presentation or document/article. Otherwise you have to edit the figure to add these expressions manually. 

**Solution proposal:**

Make it a view option. We already have some view options. So add a new option "Show OQL expressions" as shown in screenshot below:

![image](https://cloud.githubusercontent.com/assets/2900303/16941710/15594552-4d92-11e6-9bea-30061e1c5db0.png)

When "Show OQL filters" is checked, some extra space should be made such that the complete OQL filter strings can be shown.

**Comment by pieterlukasse** [comment]
Notify: @adamabeshouse @schultzn @awernibi

**Comment by adamabeshouse** [comment]
From implementation standpoint, it's quite simply doable.

**Comment by pieterlukasse** [comment]
comment on one of the comments @schultzn made "Keep in mind though that an OQL string could be very long - how do you plan to deal with those?" 
- would it be an option to show up to a specific width and let the user click on a "..." button to display the complete filter if so desired? Or put a slider between both parts (the labels and the oncoprint) to make it resizable?

**Comment by adamabeshouse** [comment]
It's doable but it would be quite a bit of work.

**Comment by jjgao** [comment]
@adamabeshouse 

(1) I think it'd be nice to show in different style. Could you make a screenshot with the same font and we can decide whether that looks fine.

(2) good idea.

**Comment by schultzn** [comment]
I agree with JJ.
