### ISSUE TITLE
ATTR_ID is not matched in clinical_attribute and clinical_patient

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#1528]
The cases I found out are CLIN_M_Stage, CLIN_N_Stage and CLIN_T_Stage in clinical_attibute but CLIN_M_STAGE, CLIN_N_STAGE and CLIN_T_STAGEin clinial_patient

**Comment by zheins** [comment]
@zhx828 this is a bug in the ImportCaisesClinicalXML script. I'll take a look at it.
