### ISSUE TITLE
Oncoprint hanging for specific OQL expression

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1532]
steps to reproduce:

- Select `brca provisional` study
- fill in OQL as : `TP53:MUT=E56*;TP53:MUT=R175H;`

URL: 

http://www.cbioportal.org/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TP53%3AMUT%3DE56*%3BTP53%3AMUT%3DR175H%3B&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit

Screenshot:
![image](https://cloud.githubusercontent.com/assets/2900303/17062385/0ad4d986-5033-11e6-823d-07bae2283306.png)

Notify:
@adamabeshouse

**Comment by adamabeshouse** [comment]
This works in `rc`
