### ISSUE TITLE
File Formats | Data Clinical files | PATIENT_ID instead of Patient Identifier

### ISSUE THREAD

**Issue by als2076** [cBioPortal/cbioportal#1543]
Hi,

This affects both the [data_clinical_patient.txt] (https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#the-patient-file) and [data_clinical_sample.txt] (https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#the-samples-file)

Should PATIENT_ID be Patient Identifier instead?

Thanks,
Alex

**Comment by angelicaochoa** [comment]
@als2076 PATIENT_ID is correct. I think what you're seeing on the file formats page is the metadata about the clinical attributes
