### ISSUE TITLE
Tiny Bug in Oncoprint page

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#1556]
Two small bugs:
1) 'Show all samples' button in Oncoprint page does not work.
2) Case Set description is missing a colon. 

http://www.cbioportal.org/index.do?cancer_study_list=luad_tcga&cancer_study_id=luad_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=luad_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=luad_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=luad_tcga_all&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=EGFR&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1564
