### ISSUE TITLE
Mouse over Gene tip code duplication 

### ISSUE THREAD

**Issue by fendor** [cBioPortal/cbioportal#1561]
When you view an sample you can see every gene that is present in the sample.
On Mouse Over genes display an link which directs to an description of the gene. 
We wanted to alter this link, in the source code, there are three places where a similar link is defined.

I request that the code in [cna.jsp](https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/WEB-INF/jsp/patient_view/cna.jsp) on line 120 namely:
`var tip = "<a href=\"http://www.ncbi.nlm.nih.gov/gene/"
                                    +entrez+"\">NCBI Gene</a>";`
be replaced with 
`var tip = OncoKB.str.getNCBIGeneLink(entrez);`

Same with [mutations.jsp](https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/WEB-INF/jsp/patient_view/mutations.jsp)

**Comment by awernibi** [comment]
Seems to be in line 130 in [cna.jsp](https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/WEB-INF/jsp/patient_view/cna.jsp)

In our local cBioPortal instance, we replaced the entire Entrez Gene Annotation with Ensembl 70.  After applying the suggested change, we had to modify the Link only on one spot. However, putting this URL into the settings in addition would be helpful.

**Comment by zhx828** [comment]
Also need to change the NCBI protocal to https

**Comment by pieterlukasse** [comment]
@zhx828 would be nice to have a portal property for this.
