### ISSUE TITLE
Variant allele frequency plot invalid value <path> attribute

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#157]
On the patient view:

This link
https://cbioportal.mskcc.org/case.do?cancer_study_id=mskimpact&case_id=P-0000476

gives the following error in the console:
```
Error: Invalid value for <path> attribute 
```
originates from ``AlleleFreqPlot.js``

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/423
