### ISSUE TITLE
sample cancer study vs documentation

### ISSUE THREAD

**Issue by scottsdca** [cBioPortal/cbioportal#158]
The sample cancer study data has a "case_lists" directory however the File Formats documentation only mentions a "patient_lists" directory.  I originally thought that this was just a bug in the either the documentation or the sample study data and that they referring to the same thing.

However, when I compared the content of the "cases_lists/cases_all.txt" and "data_clinical.txt" files I became doubtful.  Based on the documentation for Patient Lists, I would expect to see patient identifiers on the last line of "case_lists/cases_all.txt" (as well as every other file in the case_lists directory for that matter).  However, when I compare cases_all.txt to data_clinical.txt it tells me that cases_all.txt has sample ids not patient ids.

At this point I'm totally confused.  Do I put patient ids (per the documentation) or samples id (per what I'm seeing the sample data) in  case_lists/*.txt? Also is there a difference between case_lists and patient_lists? If so, what is it?

Thanks - Scott

**Comment by zheins** [comment]
Hi @scottsdca, sorry for the confusion. This inconsistency in patient/sample references will be fixed soon, which happened when the portal started allowing patients to have multiple samples.

You need to put sample ids in the case lists file. All the case lists should go into a subdirectory named "case_lists". We corrected the documentation to reflect this on Oct. 2nd.

Take a look [here](https://github.com/cBioPortal/cbioportal/wiki/File-Formats#case-lists) to see how case list files should be structured, which is now up to date with the current version of the portal.
