### ISSUE TITLE
Loading of some data sets hangs

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#16]
I am trying to load mutation data and a bunch of case sets.  For example:

$PORTAL_HOME/core/src/main/scripts/cbioportalImporter.py --jvm-args "-cp $CONNECTOR_JAR:$PORTAL_HOME/core/target/core-1.0-SNAPSHOT.jar" --command import-study-data --meta-filename profile_out/meta_mutations_extended.txt --data-filename profile_out/data_mutations_extended.txt

$PORTAL_HOME/core/src/main/scripts/cbioportalImporter.py --jvm-args "-cp $CONNECTOR_JAR:$PORTAL_HOME/core/target/core-1.0-SNAPSHOT.jar" --command import-patient-list --meta-filename profile_out/case_lists

Both of these commands just seem to hang, and I get no output.  But, when I check the database, all (or most) of the data is there.

Very strange.  I will try to fix.  But, just curious if any one else has seen this?

**Comment by ecerami** [comment]
I think this is due to stdout and stderr blocking issues in core/src/main/scripts/cbioportal_common.py.

Here is my proposed fix.  Looping in @n1zea144 for code review:

	     print >> OUTPUT_FILE, ("Executing command: " + java_home +
	                            "/bin/java {}\n".format(args).replace('(\'', '').replace('\', \'', ' ').replace('\')', ''))
	-    process = Popen([ java_home + '/bin/java']+list(args), stdout=PIPE, stderr=PIPE)
	+    process = Popen([ java_home + '/bin/java']+list(args), stdout=PIPE, stderr=STDOUT)
	     ret = []
	     while process.poll() is None:
	         line = process.stdout.readline()
	         if line != '' and line.endswith('\n'):
	             print >> OUTPUT_FILE, line.rstrip()
	             ret.append(line[:-1])
	-    stdout, stderr = process.communicate()
	-    print >> OUTPUT_FILE, stdout
	-    ret += stdout.split('\n')
	-    if stderr != '':
	-        print >> OUTPUT_FILE, stderr
	-        ret += stderr.split('\n')
	-    ret.remove('')
	     return ret

**Comment by n1zea144** [comment]
I may be the only one that has run this code (and only on the sample dataset).  This fix seems reasonable, and we are still capturing output from the classes in the scripts package.

**Comment by ecerami** [comment]
thanks, Ben.  I will push out these changes then.
