### ISSUE TITLE
Hugo_symbol not looked at in data_CNA.txt importing

### ISSUE THREAD

**Issue by zheins** [cBioPortal/cbioportal#1615]
If both `Hugo_symbol` and `Entrez_Gene_Id` columns are present in CNA file, the hugo symbol is not used if the entrez gene Id cannot be found, causing the record to be skipped.

**Comment by jjgao** [comment]
@angelicaochoa could you please check if this is still a problem?

**Comment by angelicaochoa** [comment]
@jjgao I'll investigate

**Comment by jjgao** [comment]
It seems like a easy bug to fix -- would be great if you can, so we can close this issue :)

**Comment by angelicaochoa** [comment]
@jjgao I made a pr here https://github.com/cBioPortal/cbioportal/pull/4114
