### ISSUE TITLE
Markup errors in ReadtheDocs documentation

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#1620]
The markup on https://cbioportal.readthedocs.io/en/hotfix/File-Formats.html was written for GitHub, and copied to ReadtheDocs without adjustments in pull request #1546. This has caused several syntax elements to show up verbatim in the document rather than being typeset:
- [x] HTML escape sequences in the explanation of the `data_filename` fields of most metadata files  
  ![screen shot 2016-08-25 at 12 22 42](https://cloud.githubusercontent.com/assets/4929431/17965814/c40a3266-6abe-11e6-97ca-1e38ad099660.png)
- [x] level-five headers under [Clinical Data → Data Files](https://cbioportal.readthedocs.io/en/hotfix/File-Formats.html#data-files)  
  ![screen shot 2016-08-25 at 12 24 17](https://cloud.githubusercontent.com/assets/4929431/17965835/ebf3867e-6abe-11e6-9536-6eee53611241.png)
- [x] a hyperlink in the description of patient attribute files
  ![screen shot 2016-08-25 at 12 46 36](https://cloud.githubusercontent.com/assets/4929431/17966489/17d06fde-6ac2-11e6-853f-700b79afe7c4.png)
- [ ] the table under [Expression Data → Supported stable_id values for MRNA_EXPRESSION](https://cbioportal.readthedocs.io/en/hotfix/File-Formats.html#supported-stable-id-values-for-mrna-expression)  
  ![screen shot 2016-08-25 at 12 25 40](https://cloud.githubusercontent.com/assets/4929431/17965875/1323e6bc-6abf-11e6-84e1-fd6681ca7a18.png)
- [x] the emoji escape sequences `:warning:`, `:information_source`, `:arrow_up:` and `:arrow_down:` in various places
  ![screen shot 2016-08-25 at 12 31 51](https://cloud.githubusercontent.com/assets/4929431/17966056/f349daee-6abf-11e6-8848-0595bfef4f46.png)
- [x] and finally, an internal link in the description of the `groups` metadatum of studies, which was probably already broken when we moved away from GitHub’s wiki feature  
  ![screen shot 2016-08-25 at 12 51 28](https://cloud.githubusercontent.com/assets/4929431/17966596/b2f0cc98-6ac2-11e6-85dd-1c63fc9ecf95.png)

**Comment by fedde-s** [comment]
@inodb, could you look at this?

**Comment by inodb** [comment]
@fedde-s Sorry didn't see this message. I don't have much time to look into this at the moment.

There are some non-trivial things issues listed. The table & the level 5 header problems are related to the recommonmark parser for sphinx not implementing the full set of markdown features (e.g. the tables). I've seen a few projects move over to recommonmark over sphinx: https://recommonmark.readthedocs.io/en/latest/.

**Comment by fedde-s** [comment]
@inodb I see, thanks for the info! As I understand the documentation, the way to include tables with the Markdown dialect used by recommonmark is using [HTML blocks](http://spec.commonmark.org/0.26/#html-blocks). And the problem with that particular level 5 header is probably this requirement in [the paragraph on ATX headings](http://spec.commonmark.org/0.26/#atx-headings): “The opening sequence of # characters must be followed by a space or by the end of line.”. So it might be trivial after all!

**Comment by fedde-s** [comment]
And it seems like 
<table>
  <tr>
    <td>
        Those HTML block-based tables
    </td>
    <td>
        work
    </td>
  </tr>
  <tr>
    <td>
        on GitHub
    </td>
    <td>
        as well.
    </td>
  </tr>
</table>

**Comment by inodb** [comment]
@fedde-s Nice find! Do you think you have time to update this?

**Comment by fedde-s** [comment]
Great, thanks for fixing it @inodb!

**Comment by fedde-s** [comment]
It seems like the pull request linked above did not fix the `MRNA_EXPRESSION` stable ID table.

**Comment by inodb** [comment]
@fedde-s oops missed that, thanks for checking! I submitted another PR (#1944)

**Comment by fedde-s** [comment]
Fixed in the next minor release now that #1944 has been merged into the development branch for it: https://cbioportal.readthedocs.io/en/hotfix/File-Formats.html#supported-stable-id-values-for-mrna-expression
