### ISSUE TITLE
Order of mutations within the Mutations Tab

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1621]
Currently, if you enter a bunch of genes, e.g. NRAS EGFR KRAS, the OncoPrint respects the order of the genes, but the Mutations tab re-orders in alphabetical order.  The mutations tab should respect the same order.  

(forwarding this request from Chris, and assigning to JJ for triage)

**Comment by jjgao** [comment]
@onursumer maybe we can address this in the refactored tab?

**Comment by onursumer** [comment]
The refactored tab, by default, respects the order. In the legacy code there is an additional alphabetical sorting.
