### ISSUE TITLE
Sample selection on study view page: Duplicate IDs are not selected at all

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1627]
I noticed (for several searches) that a few cases were missing from the selected samples even though the sample IDs were correct and present in the study. After the fact I realized that there were some duplicate cases in my query. The cases that were missing were precisely those that were duplicated in the list— i.e., they were present twice in my list, but they weren’t returned at all.

Not sure who to assign this to - Hongxin, can you reassign if needed?

**Comment by zhx828** [comment]
This issue should be solved in https://github.com/cBioPortal/cbioportal/pull/1405
