### ISSUE TITLE
some links are broken at readthedocs.io

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#1631]
https://cbioportal.readthedocs.io/en/hotfix/Import-the-Seed-Database.html
There are two broken links on this page:
- the "downloads" link is broken : https://cbioportal.readthedocs.io/Downloads.html#seed-database
- the "follow the prebuild steps" is broken : https://cbioportal.readthedocs.io/Pre-Build-Steps.html#prepare_database

A test of all links on all pages would be a good idea.

**Comment by inodb** [comment]
Guess you could build the docs in Travis and add the nitpicky flag: http://stackoverflow.com/questions/14492743/have-sphinx-report-broken-links

**Comment by fedde-s** [comment]
Some more adjustments that should be resolved before moving to directing people to readthedocs.io as the main source of documentation are listed in PR #1620.

**Comment by sheridancbio** [comment]
I think I have found the "proper" target for fixing one of the broken links.
This:
https://cbioportal.readthedocs.io/en/latest/Import-the-Seed-Database.html
contains a broken link to:
https://cbioportal.readthedocs.io/Downloads.html#seed-database
but there is a functioning page here which appears to be what is intended:
https://cbioportal.readthedocs.io/en/latest/Downloads.html#seed-database

It may be that many broken links can be fixed by adding the path stem "/en/latest" into the url.

**Comment by fedde-s** [comment]
These are relative links to paths in the same directory though, and if viewed on GitHub or elsewhere these files will not be in the `/en/latest` directory.

**Comment by fedde-s** [comment]
Might the `#fragment` identifier in these slash-free relative URLs the issue? That is the only difference I see between links that do work and links that don't. 

Two things I found:
- The [CommonMark specification](http://spec.commonmark.org/0.27/#example-470) explicitly mentions fragment identifiers within the current page and to a page referenced by full URL.
- [Documentation for Recommonmark bridge](https://recommonmark.readthedocs.io/en/latest/#links) that I believe to be used in generating the HTML for <https://cbioportal.readthedocs.io/> mentions how it uses a Sphinx feature I am not familiar with for such links.

**Comment by fedde-s** [comment]
The CommonMark spec does mention [an alternative syntax for link destinations](http://spec.commonmark.org/0.27/#link-destination): the URL may be enclosed in angle brackets, as such:
```markdown
[link text](</url>)
```

Might this fix the way that our Readthedocs documentation handles it? [This link](<#issuecomment-319312073>) to my previous comment demonstrates that GitHub seems to support the angle bracket syntax.

**Comment by inodb** [comment]
we're not using readthedocs anymore
