### ISSUE TITLE
When portal contains only studies with only expression data, it will fail to display any

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1639]
When portal contains only studies with expression data, it will fail to display any. But in some use cases a client could initially want to load some studies that contain only expression data. This should also work. 

@oplantalech : can you please add the details (the Java line) that was the cause for this?

**Comment by oplantalech** [comment]
@pieterlukasse I tried to reproduce the error in an instance with the current master version, and I found no errors!
