### ISSUE TITLE
3D structure viewer not coming up in some cases

### ISSUE THREAD

**Issue by cccsander** [cBioPortal/cbioportal#1652]
Example: GATA3

http://www.cbioportal.org/cross_cancer.do?cancer_study_list=&cancer_study_id=all&data_priority=0&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=KRAS+EGFR+GATA3&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&Action=Submit#crosscancer/overview/0/KRAS%20EGFR%20GATA3/skcm_tcga%2Cuvm_tcga

**Comment by cccsander** [comment]
@jjgao @onursumer

**Comment by onursumer** [comment]
This seems to be related to #1379.
Fixed by #1540, but the code is not merged/released yet.
