### ISSUE TITLE
URL shorteners don't work on cross-cancer query. URL too long?

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1666]
Here is a single gene cross-cancer query:

http://www.cbioportal.org/cross_cancer.do?cancer_study_list=&cancer_study_id=all&data_priority=0&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=MFSD1&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&Action=Submit#crosscancer/overview/0/MFSD1/hnc_mskcc_2016%2Csarc_mskcc%2Csarc_tcga%2Cthyroid_mskcc_2016%2Cacc_tcga%2Cchol_jhu_2013%2Cchol_nccs_2013%2Cchol_nus_2012%2Cchol_tcga%2Cgbc_shanghai_2014%2Cblca_bgi%2Cblca_dfarber_mskcc_2014%2Cblca_mskcc_solit_2012%2Cblca_mskcc_solit_2014%2Cblca_plasmacytoid_mskcc_2016%2Cblca_tcga%2Cblca_tcga_pub%2Cmm_broad%2Cmds_tokyo_2011%2Ces_dfarber_broad_2014%2Ces_iocurie_2014%2Ccoadread_dfci_2016%2Ccoadread_genentech%2Ccoadread_mskcc%2Ccoadread_tcga%2Ccoadread_tcga_pub%2Cbrca_bccrc%2Cbrca_bccrc_xenograft_2014%2Cbrca_broad%2Cbrca_metabric%2Cbrca_sanger%2Cbrca_tcga%2Cbrca_tcga_pub%2Cbrca_tcga_pub2015%2Ccesc_tcga%2Clgg_tcga%2Clgg_ucsf_2014%2Clgggbm_tcga_pub%2Cpcpg_tcga%2Cescc_icgc%2Cescc_ucla_2014%2Cegc_tmucih_2015%2Chnsc_broad%2Chnsc_jhu%2Chnsc_mdanderson_2013%2Chnsc_tcga%2Chnsc_tcga_pub%2Cnpc_nusingapore%2Clihc_amc_prv%2Clihc_riken%2Clihc_tcga%2Cliad_inserm_fr_2014%2Cnsclc_tcga_broad_2016%2Cpaac_jhu_2014%2Cpaad_icgc%2Cpaad_qcmg_uq_2016%2Cpaad_tcga%2Cpaad_utsw_2015%2Cpanet_jhu_2011%2Cpanet_shanghai_2013%2Cmeso_tcga%2Cplmeso_nyu_2015%2Cnepc_wcm_2016%2Cprad_broad%2Cprad_broad_2013%2Cprad_fhcrc%2Cprad_mich%2Cprad_mskcc%2Cprad_mskcc_2014%2Cprad_mskcc_cheny1_organoids_2014%2Cprad_su2c_2015%2Cprad_tcga%2Cprad_tcga_pub%2Ccscc_dfarber_2015%2Crms_nih_2014%2Ctgct_tcga%2Ctet_nci_2014%2Cthca_tcga%2Cthca_tcga_pub%2Cucec_tcga%2Cucec_tcga_pub%2Call_stjude_2013%2Call_stjude_2015%2Claml_tcga%2Claml_tcga_pub%2Ccll_iuopa_2015%2Clcll_broad_2013%2Cacbc_mskcc_2015%2Cnbl_amc_2012%2Cnbl_ucologne_2015%2Cmbl_broad_2012%2Cmbl_icgc%2Cmbl_pcgp%2Cesca_broad%2Cesca_tcga%2Cstad_pfizer_uhongkong%2Cstad_tcga%2Cstad_tcga_pub%2Cstad_uhongkong%2Cstad_utokyo%2Cuvm_tcga%2Cacyc_fmi_2014%2Cacyc_mda_2015%2Cacyc_mskcc_2013%2Cacyc_sanger_2013%2Cccrcc_irc_2014%2Cccrcc_utokyo_2013%2Ckirc_bgi%2Ckirc_tcga%2Ckirc_tcga_pub%2Cnccrcc_genentech_2014%2Csclc_clcgp%2Csclc_jhu%2Csclc_ucologne_2015%2Cluad_broad%2Cluad_mskcc_2015%2Cluad_tcga%2Cluad_tcga_pub%2Cluad_tsp%2Clusc_tcga%2Clusc_tcga_pub%2Ccellline_ccle_broad%2Ccellline_nci60%2Cscco_mskcc%2Cmpnst_mskcc%2Cskcm_broad%2Cskcm_broad_dfarber%2Cskcm_tcga%2Cskcm_yale%2Cdesm_broad_2015%2Cthym_tcga%2Cucs_jhu_2014%2Cucs_tcga%2Cgbm_tcga%2Cgbm_tcga_pub%2Cgbm_tcga_pub2013%2Ckich_tcga%2Ckich_tcga_pub%2Ckirp_tcga%2Curcc_mskcc_2016%2Cdlbc_broad_2012%2Cdlbc_tcga%2Cmcl_idibips_2013%2Cpcnsl_mayo_2015%2Cctcl_columbia_2015%2Cov_tcga%2Cov_tcga_pub

**Comment by shivanshsoni** [comment]
Sir, We can use google URL shortener for this
We just have to write a small code to redirect it to a new shortened link(after shortening URL by using google URL shortener through a code)

just check it out:
Shortened URL of above link::   https://goo.gl/YqECYp 

After using this you can easily distribute it to others.

**Comment by adamabeshouse** [comment]
seems fixed
