### ISSUE TITLE
Remove redundant TCGA projects from the tumor type map

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1668]
Is there an easy way to not show the redundant TCGA projects in this plot? We could remove all published TCGA projects and only keep provisional? 

That would make the plot much more useful. Btw, I just came up with the name Tennis Court Plot for it.

![image](https://cloud.githubusercontent.com/assets/11892704/18532402/dbdd8ffa-7aa9-11e6-89bf-8ca72b48b751.png)

**Comment by jjgao** [comment]
Tennis Court Plot IT IS! :)

We can definitely write some code show provisional studies only. There were also some discussion in RFC 26 to completely replace this plot.
