### ISSUE TITLE
'NA' in Entrez_Gene_Id in CNA data causing gene removal

### ISSUE THREAD

**Issue by chenh4** [cBioPortal/cbioportal#1671]
In data_CNA.txt, if a gene has Hugo_Symbol but 'NA' in Entrez_Gene_Id col, this gene will be removed from the CNA mutation section for all samples (to be specific, the ones w/ CNAs ) on the cBioPortal. Leaving it blank in Entrez_Gene_Id is fine; the gene will go in.

**Comment by fedde-s** [comment]
Indeed, I believe this is the convention we initially agreed on. Using `NA` to indicate that no gene information is available may lead to confusion (and incorrect loading and display of the data), as NA is a valid gene symbol: http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:12811

**Comment by fedde-s** [comment]
This also applies to expression data and methylation data. RPPA data has a special case that says NA means that no gene symbol is available though, if I remember correctly this was necessary to load Firehose data.

**Comment by fedde-s** [comment]
Should we document this more clearly in File-Formats.md or do you propose to change the convention?

**Comment by zheins** [comment]
@fedde-s I think the issue is that NA is not a valid Entrez_Gene_Id, and as such should be allowed in that column. The correct behavior would be if NA is found in that column just look at the Hugo_Symbol instead.

Is this correct @chenh4?

**Comment by fedde-s** [comment]
That depends. Defining NA as a way to specify that no gene ID is available may lead to mistakes as NA is a valid gene symbol (and some code

**Comment by fedde-s** [comment]
@zheins: I have seen code, at least in `DaoGeneOptimized`, that attempts to a column as either an Entrez ID if it is numeric or as a symbol if not, not sure if that will lead to problems if we allow NA as a second way to express missing values.

**Comment by fedde-s** [comment]
If the Entrez ID is not missing but simply unknown to the portal, falling back on the gene symbol will sometimes lead to the data being loaded as a different gene than was specified by the Entrez ID. That's why we agreed to ignore the Hugo_Symbol column if an Entrez ID is given.

**Comment by zheins** [comment]
@fedde-s that sounds like more of a data problem doesn't it? I would think you'd still want to check the symbol column in that case to try and salvage the record if the hugo symbol is valid. NA is pretty standard across our formats. If the entrez columns - which is supposed to be a number - has an NA in it, intuitively the import code should then try the hugo symbol. 

I guess this is more of a consistency thing in how we specify if a field does not contain data. Some of the import scripts allow NA in the entrez column and fall back to the symbol, while some do not. For instance, in the `ImportFusionData class`, NA is accepted and causes the importer to look at the hugo symbol. If we're going to say no NA in this field, it should at least be consistent across all datatypes.

**Comment by fedde-s** [comment]
The `Gene` table does vary between cBioPortal installations, as Entrez IDs are retracted and replaced over time as new insights are discovered, and gene symbols are revised and reused to refer to different genes. But if we can make sure that the column will never be parsed as a gene symbol, I can agree with adding NA as an alternative way to specify missing Entrez IDs in CNA, expression, and methylation data.

**Comment by pieterlukasse** [comment]
@zheins I agree we need to be consistent throughout the different formats 👍  It would be best if we deprecate logic like `DaoGeneOptimized.guessGene()` and use something new for all the `Import...` classes. This new approach could be in the form of two new well defined methods, e.g. `getGeneByEntrezId()` and `getGeneByHugoSymbol()` . Then `getGeneByEntrezId()` could return null if it is not a valid entrez, and we could fall back to `getGeneByHugoSymbol()`

**Comment by chenh4** [comment]
Thanks all. @zheins, yes, if NA is found in that column just look at the Hugo_Symbol instead or replacing NA by a blank is also fine.

**Comment by fedde-s** [comment]
Is this still an issue, or can it be closed?
