### ISSUE TITLE
support priority studies in the query interface

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1681]
Currently we have hard code mskimpact for priority category. We need to make it into properties file.

e.g.

```
# settings for priority studies
# e.g. priority_studies=cancer_study_1#category1;cancer_study_2#category1;cancer_study_3#category2
priority_studies=
```

**Comment by jjgao** [comment]
@adamabeshouse could you prioritize this? It'd be great if we can put it out in this release (v1.3.0). Thanks!

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1718
