### ISSUE TITLE
Absent "Mass spec"-column under Datasets

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#1694]
Hi,

Now that it's possible to load mass spectrometry data, it would be nice if there would be a column under "Datasets" to easily see which studies contain samples with this data.

Kind regards,
Sander

**Comment by fedde-s** [comment]
See [the comment I just made in the pull request that addresses this](https://github.com/cBioPortal/cbioportal/pull/1738#issuecomment-260949758).

**Comment by sandertan** [comment]
Design choice to not have it in. In future we might want to replace "RPPA" column with "Protein level" column.
