### ISSUE TITLE
Mutation file format docs do not mention correct column for Amino_Acid_Change

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#17]
In this wiki document:

https://github.com/cBioPortal/cbioportal/wiki/File-Formats#mutation-data

we do not specify the column name for "Amino_Acid_Change".  Assigning to self.

**Comment by ecerami** [comment]
Actually, it seems that the only column where you can specify amino acid change must now be specified as: HGVSp_Short.  Is this on purpose, or maybe just temporary?  @schultzn @n1zea144 @jjgao

**Comment by onursumer** [comment]
This is on purpose. HGVSp_Short represents the protein change value coming from the VEP annotator.

We also have another column (Amino_Acid_Change) for custom annotations, but this value has not made its way to the front-end yet.

**Comment by ecerami** [comment]
but, what about others who don't have VEP annotated data?  (this is true of most other installs).  this also doesn't match the format details on the wiki.  can we consider a more generic solution?


Sent from mobile phone.  Please excuse typos.

-------- Original message --------

**Comment by n1zea144** [comment]
Perhaps we should support an annotation property in the meta file for mutations?  Based on this property the import code does the right thing?

**Comment by ecerami** [comment]
A while back (back in the old days!), I remember we had this same problem in TCGA where each sequencing center labeled the amino acid change differently, e.g. AMINO_ACID_CHANGE, AA_CHANGE, PROTEIN_CHANGE, etc.  The MAF reader had the "smarts" to figure out which columns were specified, and pick out the right amino acid change column.  If we did this, then the code would always work, regardless of MAF variations, and no need to configure anything.  Thoughts?

**Comment by schultzn** [comment]
I thought are still supporting Protein_Change in the absence of VEP annotations?

**Comment by ecerami** [comment]
@schultzn: As far as I can tell, only HGVSp_Short is recognized.  Hence, if you have a MAF with Protein_Change or AA_Change, mutations just appear as "MUTATED", but have no amino acid change details.

**Comment by jjgao** [comment]
I think we can fall back on Amino_Acid_Change if HGVSp_Short does not exist or is empty.

**Comment by ecerami** [comment]
Ah, that's true.  AMINO_ACID_CHANGE is in the code.  But, if it's specified, it is stored in a separate field called aminoAcidChange, and only proteinChange is actually stored in the database.

I am looking at this:  https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/maf/MafUtil.java

    record.setProteinChange(TabDelimitedFileUtil.getPartString(getColumnIndex(PROTEIN_CHANGE), parts));

and 

    public static final String PROTEIN_CHANGE = "HGVSp_Short";

And in ExtendedMutationUtil:

		String proteinChange = record.getProteinChange();

		// if protein change is not valid, then use the string "MUTATED"
		if (!isValidProteinChange(proteinChange))
		{
			proteinChange = "MUTATED";
		}

**Comment by onursumer** [comment]
I think if AMINO_ACID_CHANGE column exists in the MAF but not HGVSp_Short column, then we should set the protein change value to AMINO_ACID_CHANGE column value. Do we also need to consider other custom column names to get protein change value, or does AMINO_ACID_CHANGE suffice?

**Comment by onursumer** [comment]
Now importing Amino_Acid_Change column with the commit https://github.com/cBioPortal/cbioportal/commit/9a2f1cd24dde762790612b101bcdc25a3b7d876f

**Comment by ecerami** [comment]
Thanks, @onursumer!  I will update the wiki later today, and close out...

**Comment by ecerami** [comment]
Hi @onursumer.  I am trying to find this bug fix.  Do you know which branch you committed to?  Tx.

**Comment by onursumer** [comment]
Somehow it created another tree in master branch, I think I was out of
sync. Just merged and pushed it to the master branch. Let me know if it
works now.

**Comment by ecerami** [comment]
Hurray!  this now works.  I have also updated the wiki doc to explain this:  https://github.com/cBioPortal/cbioportal/wiki/File-Formats#mutation-data.  Closing...
