### ISSUE TITLE
File-Formats.md unclear on representing missing values

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#1702]
Since the dataset validation script was added, we agreed on how to represent missing/inapplicable values in the various file types. Most of these agreements have barely or not been documented in `File-Formats.md`: the only specifications I could find is that missing measurements in Expression data files (and continuous CNA and Methylation, which use the same format) are represented by the string `NA`, and the `STOP_DATE` column of timeline data should be blank in certain cases. Additionally, in mutation data files the gene symbol can be `Unknown` and the Entrez gene ID can be 0.

I know of these conventions that have yet to be documented:
- [ ] missing measurements in discrete CNA data files are represented by `NA`, just as in continuous CNA data files
- [ ] the same holds for protein expression data files
- [ ] in the columns `Hugo_Gene_Symbol` and `Entrez_Gene_Id` occuring in most file formats, unknowns are represented by blank cells (to avoid confusion with the [valid legacy gene symbol NA](http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:12811))
- [ ] in all columns of mutation data files that do not specify otherwise, unknowns are represented by blank cells [as specified by the MAF format](https://wiki.nci.nih.gov/display/TCGA/Mutation+Annotation+Format+%28MAF%29+Specification#MutationAnnotationFormat%28MAF%29Specification-MAFfilefields)
- [ ] missing values for clinical attributes can be represented by `[not applicable]`, `[not available]`, `[pending]`, `[discrepancy]`, `[completed]`, `[null]`, `na`, any capitalised versions of these, or blank cells
- [ ] missing values in GISTIC recurrent CNA gene files are represented as blank fields

I don’t know if missing values are allowed in any columns of gene fusion, MutSig recurrent mutation and segment-wise CNA data files, nor any unspecified columns in timeline data.

**Comment by fedde-s** [comment]
I think this can make generating data files very frustrating, and it is likely the cause of multiple other reported issues such as #1671

**Comment by jjgao** [comment]
@fedde-s should we keep this open?

**Comment by fedde-s** [comment]
I haven't personally run into problems with this lately, but I haven't much been involved with data curation or maintenance of the data loading pipeline. I haven't noticed it being solved though, so if it does still bother someone who has (e.g. @sandertan), they could re-open it or report a more targeted issue.
