### ISSUE TITLE
Beta: Remove truncating mutations only when OncoKB is not selected

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1713]
In the new OncoPrint filter, filters should only remove truncating mutations when the OncoKB filter is turned on (prior knowledge). When only recurrence filters are used, truncating mutations should still be shown.

![image](https://cloud.githubusercontent.com/assets/11892704/18841214/0112e7d2-83df-11e6-8d7a-b451285db202.png)

**Comment by adamabeshouse** [comment]
Closing for now because we're only filtering missense mutations for the time being. When we begin filtering other types, this will come up.
