### ISSUE TITLE
Beta: Study view download button needs a tooltip

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1715]
It also seems confusing that the sample and patient count light up when hovering over the download button

![image](https://cloud.githubusercontent.com/assets/11892704/18841336/5df7292c-83df-11e6-8bd5-a364389e90de.png)

**Comment by jjgao** [comment]
@zhx828 let's remove the dotted line and clickable from both and add a browse icon before download for viewing patients.
