### ISSUE TITLE
Beta: Selecting mutated samples in the study view does not seem to work

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1716]
![image](https://cloud.githubusercontent.com/assets/11892704/18841377/88a2064c-83df-11e6-90a1-ef826d078030.png)

**Comment by jjgao** [comment]
@schultzn That's one of the change we made -- you have to click on the "Select" button on the botton-right of the table.

**Comment by schultzn** [comment]
Maybe make that button red or orange when it shows up? That was not intuitive for me. Maybe also Rename to “Select Samples”.
