### ISSUE TITLE
Error message when there is no session.service.url in the properties file

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1723]
Reported by Aaron:

When there is no `session.service.url` in portal.properties, he got the following error:

`Could not resolve placeholder 'session.service.url' in string value "${session.service.url}"`

Is it possible to resolve this? For example,  DFCI has their own portal.properties file. Ideally they don't have to add a url for that since they are not using it for the moment.

**Comment by jjgao** [comment]
@mandawilson I assume we can close this?

**Comment by mandawilson** [comment]
Yes, we can close this.  The error went away when Aaron updated his branch.
