### ISSUE TITLE
Beta: Study View Mut vs CNA plot --> change Plotly default to selection instead of zooming

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1726]
Beta: Study View Mut vs CNA plot --> change Plotly default to selection instead of zooming

Same as in Volvano plot on Enrichments tab

**Comment by yichaoS** [comment]
fixed under: https://github.com/cBioPortal/iViz/pull/296/commits/3685d725ec479db2a0802d45ee6eee6d6ac9f04d
