### ISSUE TITLE
Beta: Study view de-selection of cases does not work after selecting samples in CNA vs Mut plot

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1727]

**Comment by zhx828** [comment]
@schultzn this is expected. @jjgao

**Comment by zhx828** [comment]
@schultzn JJ just explained it to me. Working on it now.

**Comment by zhx828** [comment]
This issue may have been solved in https://github.com/cBioPortal/cbioportal/pull/1762 But if the issue continues to persist, please help me write down the issue in details(which study, how to reproduce the issue etc.) Thanks in advance.
