### ISSUE TITLE
Beta: Rename OncoPrint Legend and Mutation Color UI

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1735]
Suggestions:

Legend
Change Missense Mutation (recurrent / prior knowledge) -- > Missense Mutation (putative driver)
Change Missense Mutation (non-recurrent/ no prior knowledge) --> Missense mutations (putative passenger)

In the Mutation Color menu, rename section to Putative Drivers (based on recurrence and prior knowledge)

OncoKB --> OncoKB driver annotation

Hide non-recurrent ... --> Hide putative passenger mutations

**Comment by schultzn** [comment]
I like the new color defaults - but it's probably best to also do the sorting by default.

**Comment by schultzn** [comment]
Also please rename "Recurrence" in the Sort menu to "Driver / Passenger"

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/issues/1751
