### ISSUE TITLE
Validation (-u option) not working in rc

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1748]
Validation stopped working after api moved to api-legacy. See also https://github.com/cBioPortal/cbioportal/pull/1710#issuecomment-251356273

Notify: 
@ersinciftci

**Comment by fedde-s** [comment]
@pieterlukasse I believe this has been fixed and released, is that right?

**Comment by pieterlukasse** [comment]
seems good 👍
