### ISSUE TITLE
Problems with #1618 (Gene Panel)

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1749]
Please check the comments at

 https://github.com/cBioPortal/cbioportal/pull/1618#discussion_r81719150

https://github.com/cBioPortal/cbioportal/pull/1618/files#r81744087

Summary: rc needs some fixing based on changes from #1618 

Notify: 

@zheins

**Comment by zheins** [comment]
@pieterlukasse are there still issues? I'm trying to remember if we discussed any of these and came up with solutions. 

The point of not all samples being in the `sample_profile` table, that is the point of the new data type and import script. The pom fix I believe was addressed by @sheridancbio.

**Comment by pieterlukasse** [comment]
Hi @zheins , I think the first comment was not yet addressed in code, only in a follow-up comment by @sheridancbio .

**Comment by zheins** [comment]
I think making a default gene panel that includes no genes would solve this issue. @sheridancbio, @pieterlukasse does this sound good?

**Comment by jjgao** [comment]
@zheins @pieterlukasse any remaining issues on this?

**Comment by jjgao** [comment]
@zheins @pieterlukasse can we close this one?
