### ISSUE TITLE
Style of CN Segments subtabs

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1756]
The styles of CN Segments sbutabs are different from other tabs, such as Mutations. Please try to use the same styles.

And there is a bug when you switch to another tab and switch back. Every time, all genes appended again.

![image](https://cloud.githubusercontent.com/assets/840895/19113741/0dcbc132-8ad9-11e6-9ef7-8d21cd4f5537.png)

![image](https://cloud.githubusercontent.com/assets/840895/19113760/21b291f8-8ad9-11e6-8ab0-f5565a3fec64.png)

**Comment by JiaoJiao123** [comment]
fixed in PR #1752
