### ISSUE TITLE
Disease free plot flat for laml study

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1759]
see http://www.cbioportal.org/study?id=laml_tcga#summary

This seems to be due to the fact that Disease free status info is missing.

**Comment by pieterlukasse** [comment]
@zheins

**Comment by zheins** [comment]
This is just what is in the file in terms of values for `DFS_STATUS`:

67 DiseaseFree
132 [Not Available]

I also double checked the raw data from firehose to confirm there isn't a processing issue. These numbers appear correct.

**Comment by pieterlukasse** [comment]
Maybe we should contact Firehose team? Did you check the input or output data of Firehose?

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #276](https://github.com/cBioPortal/datahub/issues/276) via [**ZenHub**](https://www.zenhub.com/)
