### ISSUE TITLE
Studyview filtering: de-selecting last table selection resets filters

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#176]
Steps:
1. Go to the study view for a study
2. Select a pie-chart slice
3. Select a table row
4. Click on the same row again to de-select it

What happens:
De-selecting the selected row clears all filters. From what I could see, the de-selection triggers a filter call with null for the pie-chart, which results in its reset. 

Expected behaviour:
I would have expected the pie-chart filter to remain

This behaviour is not limited to the pie-chart; I think all filters are reset after de-selecting the last selected table row. 

Cheers,
Sander

**Comment by ecerami** [comment]
Hongxin, could you take a look at this?
