### ISSUE TITLE
Plots not displaying mutation annotation

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#1769]
![screen shot 2016-10-07 at 10 57 47 am](https://cloud.githubusercontent.com/assets/5973438/19194923/5a27aca8-8c7d-11e6-88e8-8d6ac1e7cd76.png)
![screen shot 2016-10-07 at 10 58 03 am](https://cloud.githubusercontent.com/assets/5973438/19194927/5bd59100-8c7d-11e6-8fe1-d78a053b9789.png)

**Comment by jjgao** [comment]
@yichaoS I'll close this since it is likely that they were not consistent in using upper/lower cases in sample ids.
