### ISSUE TITLE
Broken import scripts

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#177]
Steps:
1. go to the command-line
2. call one of the import-scripts (or via cbioportalImporter.py)

What happens:
java.sql.SQLException: java.lang.NullPointerException
	at org.mskcc.cbio.portal.dao.JdbcUtil.getDbConnection(JdbcUtil.java:97)

Expected behaviour:
After switching to an old branch and recompiling, functionality worked correctly. It probably has something to do with the deletion of the ds=initDataSource()

Cheers,
Sander

**Comment by ecerami** [comment]
@jjgao:  could you take a look into this?

**Comment by tlangs** [comment]
It looks like the code that initializes the DataSource was removed. Reintroducing it fixed the import scripts.

**Comment by n1zea144** [comment]
This has already been fixed.  An additional command line argument had to be passed to the JVM.  The documentation has been updated accordingly.
