### ISSUE TITLE
session-service may be broken (bookmark tab)

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#1778]
I've been looking at the new 1.3.0 release
**session.service.url** may not be set right in the configuration. The bookmarks tab shows a very long URL rather than the condensed url with the session service identifier.

example page:
http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_id=lusc_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lusc_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lusc_tcga_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=lusc_tcga_cnaseq&case_ids=&gene_list=AKT1%20TP53&gene_set_choice=user-defined-list&Action=Submit&show_samples=false

@jjgao @mandawilson

**Comment by jjgao** [comment]
@sheridancbio we decided not to release it on the public portal before we put authentication in session service.
