### ISSUE TITLE
pathology report tab blank under chrome with no .pdf viewer

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#1779]
I have tried a few different studies, and a handful of samples from each. I have not been able to get a patient view pathology tab result to display. Example links:

http://www.cbioportal.org/case.do?cancer_study_id=ov_tcga&case_id=TCGA-09-1665
http://www.cbioportal.org/case.do?cancer_study_id=lusc_tcga_pub&case_id=TCGA-46-3767

Test brower: Chrome  53.0.2785.143
@cBioPortal/frontend

**Comment by jjgao** [comment]
Maybe a one-time glitch when pulling data from datahub. Seems working now.

**Comment by sheridancbio** [comment]
@inodb commented that there were problems accessing the tab under firefox as well .. the generated content could be saved as a .pdf file or user could choose an application to view it, but under Chrome it generates a blank tab. (maybe because of default pop-up blocking or some other chrome setting?) Maybe we should do some more testing and see if it can work more smoothly with chrome.

**Comment by sheridancbio** [comment]
@zheins clarified that under chrome, we have seen before that if no pdf viewer is installed then the default behavior (at least for mskcc configured mac chrome installs) is to silently ignore the linked content rather than prompting the user for a choice of how to handle the content.

If there is a way to have chrome detect a missing .pdf viewer in javascript, we should probably put a warning message into the tab saying that "pathology reports may not be displayed in your browser because no .pdf file viewer is installed <such as {suggested viewer}>"

**Comment by jjgao** [comment]
@sheridancbio I think it's actually Chrome's bug... I was hope Chrome will fix itself :)

**Comment by jjgao** [comment]
duplicated with #1586
