### ISSUE TITLE
Problem with copy number segmentation import

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#178]
Description:
In order to create a scatterplot, I required the copy number segmentation for the public dataset. I downloaded the data (https://tcga-data.nci.nih.gov/docs/publications/brca_2012/brca_hg19_qc.merged.seg) and followed the instructions on the wiki page https://github.com/cBioPortal/cbioportal/wiki/File-Formats#segmented-data for the meta-data file.

Steps:
My first attempt was via the cbioimporter.py. However, it did not give the meta-data file to ImportCopyNumberSegmentData. This seems due to: IMPORTER_REQUIRES_METADATA for ImportCopyNumberSegmentData being false in cbioportal_common.py

Second attempt was calling calling ImportCopyNumberSegmentData directly with the data and the meta-data file. This resulted in 
Exception in thread "main" java.lang.Exception: Unknown reference genome id: null
	at org.mskcc.cbio.portal.scripts.ImportCopyNumberSegmentData.getRefGenId(ImportCopyNumberSegmentData.java:199)

This seems due to importCopyNumberSegmentFileMetadata expecting more/other properties in the meta-data file: reference_genome_id, description, filename

Adding these three items to the meta-data file indeed allowed me to import the data.

Expected Behaviour:
cbioimporter.py should pass the meta-data file to the ImportCopyNumberSegmentData
The wiki page text should be updated to include missing properties

Cheers,
Sander

**Comment by ecerami** [comment]
is this blocking any of your current work?  Just wondering how to prioritize...

**Comment by aderidder** [comment]
No it's not blocking. I managed to import the data by adding the
 reference_genome_id, description and filename to the metadata file.

**Comment by pieterlukasse** [comment]
Assigning to @fedde-s to ensure validation and documentation get aligned

**Comment by pieterlukasse** [comment]
fyi : I fixed the ImportCopyNumberSegmentData issue in #PR529

**Comment by pieterlukasse** [comment]
Remaining TODO:
The wiki page text should be updated to mention the meta file

**Comment by fedde-s** [comment]
@pieterlukasse has been reviewing the entries for nearly all supported data types, to align them with the requirements revealed over the course of the development of the validation script and overhauled data loading scripts (issue #528). He has updated the document locally on the The Hyve fork of the wiki, with the intention of merging it back once the validator and loading script improvements are merged to rc. I believe this issue can be closed when that is complete.

**Comment by pieterlukasse** [comment]
issue solved and wiki is updated (at The Hyve branch). This will automatically go with the PR. So closing this issue.
