### ISSUE TITLE
Study View issues

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#1780]
- [x] Table oversize after clicking table icon in the pie chart
  <img width="413" alt="screen shot 2016-10-09 at 7 49 12 pm" src="https://cloud.githubusercontent.com/assets/5400599/19224713/7b13298c-8e59-11e6-9bb5-ac66f03d0aeb.png">
- [x] MSKIMPACT should include DARWIN_SEX

**Comment by jjgao** [comment]
@zhx828 update?
