### ISSUE TITLE
Why didn't treatments show in different lines in timeline

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1784]
e.g. P-0004294

**Comment by jjgao** [comment]
@inodb do you know why? Is it solved in the new code?

**Comment by inodb** [comment]
@jjgao Not sure yet, ill check it out

**Comment by inodb** [comment]
Problem was related to these cases not having SUBTYPE. Instead we now split the treatment track either on SUBTYPE and AGENT or TREATMENT_TYPE and AGENT: https://github.com/cBioPortal/cbioportal-frontend/pull/287
