### ISSUE TITLE
oncoprint tab very slow.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1786]
- [ ] The result page pulls the list of clinical attributes attributes when it's loading. It should be changed -- load only when the dropdown is clicked.
- [x] Another issue is that all samples are posted to the backend to get the list of attributes making the database query joining 5 tables.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1787

**Comment by adamabeshouse** [comment]
done in refactor
