### ISSUE TITLE
Loading "Mutation count" is slow

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1788]
Loading "Mutation count" seems to be slow. We should try to improve the performance. 

![image](https://cloud.githubusercontent.com/assets/840895/19253114/de667f62-8f16-11e6-8926-020f94184e6c.png)

**Comment by adamabeshouse** [comment]
Separate call for missense by position equality, then can use group by and count to do all in single query

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1842
