### ISSUE TITLE
No banner on incompatible database schema

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#1790]
As documented on [Updating your cBioPortal installation](https://github.com/cBioPortal/cbioportal/blob/master/docs/Updating-your-cBioPortal-installation.md#first-time), along with the migration script we added a banner to notify administrators when their database schema version is incompatible with the deployed version of cBioPortal and needs to be updated. The current release (1.3.0) does not display any warnings when running against the previous version of the database (1.2.1), but instead hangs when opening any view that uses clinical attributes.

**Comment by pieterlukasse** [comment]
Solved as part of #1422. Best is to move the solution out into a new PR. @sheridancbio @zheins what do you think?

**Comment by zheins** [comment]
@pieterlukasse Yes that sounds good to me. Would #1422 fix this problem though? This seems like it might be something else.

**Comment by pieterlukasse** [comment]
@zheins yes, the changes in `DbVersionException.java`, `QueryBuilder.java` and `index.jsp` ensure that DB errors also lead to the error page.

**Comment by fedde-s** [comment]
@pieterlukasse Is that what you mean by &ldquo;to move the solution out into a new PR&rdquo;? Fixing the warning for administrators is a bugfix, while the schema adjustment could debatably be better off in the next major release (`rc`).

**Comment by pieterlukasse** [comment]
@fedde-s yes, split up in 2 PRs: one with the solution for the error page, one with the schema change.

**Comment by pieterlukasse** [comment]
banner PR #1806

**Comment by fedde-s** [comment]
I believe that this issue has been fixed now that #1806 has been released.
