### ISSUE TITLE
Missing mRNA expression Z-score data for University of Michigan (Grasso et al., Nature 2012) PRAD study

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1791]
http://www.cbioportal.org/index.do?cancer_study_list=prad_mich&cancer_study_id=prad_mich&genetic_profile_ids=prad_mich_mrna_median_Zscores&data_priority=0&case_set_id=prad_mich_all&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TP53&clinical_param_selection=null&tab_index=tab_download&Action=Submit

**Comment by fedde-s** [comment]
Isn't this bug more about the public data, which is maintained in [this repository](https://github.com/cBioPortal/datahub), rather than about the cBioPortal code?
