### ISSUE TITLE
OncoPrint mutation colors tweaks

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1797]
- [x] move oncokb to the first
- [x] select oncokb and hotspots by default
- [x] deselect cbioportal and cosmic by default
- [x] do not load cbioportal or cosmic data until they are selected
- [x] handling the case when oncokb is not available

**Comment by jjgao** [comment]
cosmic data seems huge:

http://www.cbioportal.org/index.do?cancer_study_list=prad_tcga&cancer_study_id=prad_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=prad_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=prad_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=prad_tcga_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=GNAS%3A+MUT%3B%0D%0AGNAS%3A+AMP+GAIN%3B&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit

![image](https://cloud.githubusercontent.com/assets/840895/19539957/48302d84-962a-11e6-9020-ebfb27ea2d88.png)

**Comment by jjgao** [comment]
Pieter just reported:

"ideas on why http://www.cbioportal.org/index.do?cancer_study_list=cellline_ccle_broad&cancer_study_id=cellline_ccle_broad&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=cellline_ccle_broad_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=cellline_ccle_broad_CNA&Z_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=cellline_ccle_broad_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TTN+TP53+LRP1B+BRCA1+BRCA2+KRAS+NRAS+BRAF&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&clinicallist=TUMOR_TYPE& takes ~30 sec just to download the data?"

![image](https://cloud.githubusercontent.com/assets/840895/22110227/edad06d8-de28-11e6-8dd2-d0e6773d8c26.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2093
