### ISSUE TITLE
Failed to run mysql migration script

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#1799]
<img width="1279" alt="screen shot 2016-10-12 at 11 15 23 am" src="https://cloud.githubusercontent.com/assets/12956870/19315855/591b6df6-906d-11e6-911d-38c91fd4170e.png">

**Comment by sheridancbio** [comment]
This bug probably makes sense --- when using CREATE TABLE statements with a MyISAM engine, the FOREIGN KEY clauses are silently ignored. But an explicit ALTER TABLE ADD FOREIGN KEY would likely fail with a MyISAM engine.
However, I think that I was able to run the migration script on the cgds_public database here (which is running MyISAM) and have it not throw an error.
Are you running under mysql? and what version are you using?

**Comment by kalletlak** [comment]
I changed engine to **Innodb**. I think the problem is because of gene_panel in line https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/resources/db/migration.sql#L59. gene_panel table doesn't exist at the time of executing this line. I moved this after the creation of tables and it worked without any errors.

**Comment by sheridancbio** [comment]
I see. This is a direct bug. I am fixing it in hotfix, and I will test if if runs under MyISAM and try to make it work under either engine if possible.

**Comment by sheridancbio** [comment]
Ok, now that I have tried it under a MyISAM engine, the ALTER TABLE `tablename` ADD FOREIGN KEY ...

**Comment by sheridancbio** [comment]
I have pushed the bugfix to rc and made a pull request for hotfix which will merge to master at the next update. (assigned @jjgao)

**Comment by fedde-s** [comment]
Is #1801 a duplicate of this one?

**Comment by fedde-s** [comment]
I think it might not be, as the output of the migration script suggests that the error in #1801 only occurs on the line where a foreign key is added to an InnoDB table, but references a MyISAM table. Hence it may well be a separate bug in the migration script.
