### ISSUE TITLE
JSmol

### ISSUE THREAD

**Issue by seqseek** [cBioPortal/cbioportal#18]
Hi cBioPortal team,

I have successfully installed a local portal. But the JSmol is not working properly somehow.   It complains that the file downloaded from pdb doesn't have supported format.  I think the error is associated with the binary file format (*.gz) since manually loading the ".pdb" file locally works just fine.   Because you guys made it work,  would you please share some experience with me about tackling this error?  Am I missing some settings?   Thank you!

Best,
Seqseek

**Comment by jjgao** [comment]
We are going to switch to another 3D structure viewer soon.
