### ISSUE TITLE
Clinical attributes validation failing after #1746 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1804]
The validation of clinical attributes is failing after changes in #1746 because now there are multiple versions of clinical attributes, one for each study. 

Actually, the validation can now be simplified and restricted to a fixed set of attributes, as done in #1567. 

So the solution for this issue would be: 
- [ ] simplify the validation by removing the call to /api-legacy/clinicalattributes/patients and /api-legacy/clinicalattributes/samples, and remove respective validation.

**Comment by fedde-s** [comment]
Indeed, the feature in #1746 broke the validation just before 1.3.0 was released. I should fix this, there needs to be a bugfix release for this as soon as possible

**Comment by pieterlukasse** [comment]
@jjgao @ersinciftci one could also interpret this problem as an effect of a bug in /api-legacy/clinicalattributes: this "legacy" api does not reflect the legacy behavior. Our solution involves not using this api at all anymore in the validation, aligning with #1746. However, I am wondering whether there are other parts that perhaps still rely on this legacy api?

**Comment by pieterlukasse** [comment]
@jjgao @ersinciftci one could also interpret this problem as an effect of a bug in /api-legacy/clinicalattributes/patients and /clinicalattributes/samples: we think this "legacy" api might not be reflecting the legacy behavior (although we didn't check this in detail). Our solution involves not using this api at all anymore in the validation, aligning with #1746. However, I am wondering whether there are other parts that perhaps still rely on this legacy api?
