### ISSUE TITLE
oncoprint download data reflects unfiltered mutations

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#1810]

**Comment by jjgao** [comment]
@adamabeshouse could you clarify?

**Comment by adamabeshouse** [comment]
@jjgao i.e. if you filter the mutations through the putative driver/passenger interface, then in the download tab the mutations that have been filtered out are still present. Is this desired behavior or should we propagate this state to the download tab?

**Comment by jjgao** [comment]
@adamabeshouse we need to discuss with @schultzn. It also affects other tabs: Mutex, Mutations, Enrichments, Survival, and maybe others.
