### ISSUE TITLE
Genome Nexus: isoform support

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1812]
Enable support canonical/default set of isoforms, using e.g. UniProt Canonical, Ensembl. canonical, UCSC canonical, MSK canonical, etc. different instance of portals are allowed to pick different sets of default canonical isoforms.

**Comment by onursumer** [comment]
I think this is partially implemented with https://github.com/cBioPortal/genome-nexus/pull/11. But for now we only have two isoform override sources: UniProt canonical and MSK canonical.

@jjgao : Do we have override files for other sources like Ensemble, UCSC, etc?

**Comment by jjgao** [comment]
@onursumer we don't but we can add them later.

**Comment by onursumer** [comment]
This issue was moved to cBioPortal/genome-nexus#20
