### ISSUE TITLE
Genome Nexus: cancer hotspots

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1814]
- [ ] modeling cancer hotspots data in GN
- [ ] pull cancer htospots to annotate mutations

**Comment by onursumer** [comment]
Basic algorithm:

- Allow users to Query Genome nexus by variant: /variant_annotation/cancer_hotspots/{variant}
- Get the `VariantAnnotation` for the provided variant
- Query www.cancerhotspots.org for each `TranscriptConsequence` in the `VariantAnnotation`
- If the `TranscriptConsequence` corresponds to a hotspot mutation, create a `Hotspot` instance and cache it.
- Return the list of `Hotspot`s as the result of the query.

**Comment by onursumer** [comment]
This issue was moved to cBioPortal/genome-nexus#18
