### ISSUE TITLE
Remove mutation annotation data from portal

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1816]
- [ ] Remove mutation_event table
- [ ] Add a few more columns in mutaiton table, e.g. chr, start, end, mutation_type, etc
- [ ] Connect portal front-end to Genome Nexus

**Comment by onursumer** [comment]
Recently I have started a document, which may be useful for breaking down the mutation data:

https://docs.google.com/spreadsheets/d/1sIqvf4_thfi2N8EyxHDzNeC4Cj5kk-8IZl1fSUsjB9k/edit?usp=sharing

**Comment by jjgao** [comment]
I don't think we will do this. Let's close it.
