### ISSUE TITLE
Patient view patient and sample information tooltip bug in IE

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1820]
In IE, the patient view patient and sample information tooltip does not show up when hovering over the patient or sample IDs.

http://www.cbioportal.org/case.do?cancer_study_id=ucec_tcga_pub&case_id=TCGA-BK-A0CC

![image](https://cloud.githubusercontent.com/assets/11892704/19452248/56a72456-947e-11e6-915e-363ab61eb2de.png)

**Comment by schultzn** [comment]
Screenshot above is from Chrome

**Comment by jjgao** [comment]
@inodb please check if this is fixed in the new patient view.

**Comment by inodb** [comment]
@jjgao yes we fixed this way back in the new frontend, will double check it's still working

**Comment by inodb** [comment]
Works in the new patient view: http://www.cbioportal.org/beta/case.do?cancer_study_id=ucec_tcga_pub&case_id=TCGA-BK-A0CC
