### ISSUE TITLE
ClinicalDataController exposes internal id of Cancer Studies

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#1824]
In general we have tried to avoid exposing internal ids. We should discuss whether we need to expose this in the web API.

**Comment by ersinciftci** [comment]
@sheridancbio We don't actually expose internal IDs like you saw when you tried the endpoints, I ignore internal ids with @JsonIgnore, and replace them with stable ids using @JsonProperty in mixins.

**Comment by sheridancbio** [comment]
For an example using cgds_public, try:
/studies/{studyId}/samples/{sampleId}/clinical-data
with  studyId: brca_tcga and sample id: TCGA-BH-A0B2-01 and attributeId: CANCER_TYPE  and projection: detailed.
http://localhost:8080/cbioportal/api/studies/brca_tcga/samples/TCGA-BH-A0B2-01/clinical-data?attributeId=CANCER_TYPE&projection=DETAILED&pageSize=1000&pageNumber=0&direction=ASC

Result (with internal id for cancerStudyId) :
[
  {
    "attrId": "CANCER_TYPE",
    "attrValue": "Breast Cancer",
    "clinicalAttribute": {
      "attrId": "CANCER_TYPE",
      "displayName": "Cancer Type",
      "description": "Disease type",
      "datatype": "STRING",
      "patientAttribute": false,
      "priority": "1",
      "cancerStudyId": 473
    },
    "id": "TCGA-BH-A0B2-01"
  }
]

**Comment by ersinciftci** [comment]
Ah I see, for got to add the new property to the mixin. I'll add test cases to make sure that the properties we want to hide is indeed not return in the response.

**Comment by ersinciftci** [comment]
Fixed.
