### ISSUE TITLE
convertExpressionZscores not working with CNA files having only Entrez IDs

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#1830]
The [documentation](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#discrete-copy-number-data) for Discrete CNA files allows to have one or both of Hugo Symbol and Entrez Gene ID. However, when I use a Discrete CNA file containing only Entrez Gene IDs to generate expression Z-scores, the script does not work. If I add the Hugo Gene Symbols in the Discrete CNA file, then the script works. Therefore, the script should be updated to handle this cases or the documentation changed.

**Comment by jjgao** [comment]
we have rewritten the code in python and will remove the requirement of using CNA data.

@yichaoS @rmadupuri please update documentation about zscores for using python script once it's done.
