### ISSUE TITLE
GSVA - Support gene sets in query page UI

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1831]
Tasks:
- [x] Add GSVA checkbox to the "Select Genomic Profiles" UI section
- [x] Implement the API between the query page and the pop-up page(s)
- [x] Add button and context menu for selecting genesets from selected GSVA profile. 

See Fig 1a(I), Fig 1a(II), Fig 1b of [RFC 28 document](https://docs.google.com/document/d/1g5HPPXrLqJQmfxP1RcWGA6-QdcHCTLr_JAuQklQdfMs/edit).

**Comment by pieterlukasse** [comment]
will assign to @oplantalech and @sandertan. For now the button can directly open the "Hierarchy pop-up" instead of showing a choice between this and a volcano plot, since we are leaving the volcano plot for later.

**Comment by oplantalech** [comment]
You can find all the changes in this branch: https://github.com/thehyve/cbioportal/tree/gsva_query_button

@pieterlukasse @sandertan

**Comment by sandertan** [comment]
- [ ] Allow query with only gene sets (no genes)

**Comment by pieterlukasse** [comment]
querying only gene sets is also done
