### ISSUE TITLE
GSVA - Oncoprint changes

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1833]
Tasks: 
- [x] Add heatmap-like visualization to oncoprint. Do this by porting the heatmap branch to rc (1.4.0) and doing some necessary issue fixing 
- [x] Add gene set tracks to the oncoprint visualization
- [x] Implement hierarchical clustering algorithm and use this to order the tracks and columns in the oncoprint

See figure 3, figure 4 of [RFC 28 document](https://docs.google.com/document/d/1g5HPPXrLqJQmfxP1RcWGA6-QdcHCTLr_JAuQklQdfMs/edit).

**Comment by fedde-s** [comment]
Working on porting the heatmap branch from Pamela's pull request #1625 to the current major release candidate.

**Comment by fedde-s** [comment]
In progress in pull request #1847.

**Comment by pieterlukasse** [comment]
I will be helping with task 3: hierarchical clustering.

**Comment by fedde-s** [comment]
This is ready to be review in pull request #2186.
