### ISSUE TITLE
GSVA - Data validation and data loader additions

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1835]
Tasks: 
- [x] Add support for gene set data in validator (python). Validate "GSVA gene set scores" file 
- [x] Document how to load the test study with GSVA data.
- [x] Add support for gene set data in loader (java). Code for loading "GSVA gene set scores" file 
- [x] Add support for *gene set x genes* data loading (java) and *gene set hierarchy* data loading (java) 

See Appendix 3 of [RFC 28 document](https://docs.google.com/document/d/1g5HPPXrLqJQmfxP1RcWGA6-QdcHCTLr_JAuQklQdfMs/edit).

**Comment by pieterlukasse** [comment]
*python part* assigned to @sandertan

**Comment by sandertan** [comment]
- [ ] Add support for gene set data in validator (python). Validate "GSVA gene set scores" file
In branch: https://github.com/thehyve/cbioportal/tree/gsva_validate_score_pvalues

**Comment by sandertan** [comment]
https://github.com/thehyve/cbioportal/tree/geneset_importer

**Comment by pieterlukasse** [comment]
implemented in #2113 , now ready for review.
