### ISSUE TITLE
Genome Nexus: integrate ClinVar

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1856]
... and make it to the portal / MutationMapper, similar to PeCan (https://pecan.stjude.org/#/proteinpaint/tp53)

![image](https://cloud.githubusercontent.com/assets/840895/19892323/b784b1e2-a01a-11e6-8b24-a75e9189bab9.png)

**Comment by onursumer** [comment]
This issue was moved to cBioPortal/genome-nexus#16
