### ISSUE TITLE
validator does not take the gene_symbol_disambiguation.txt configuration into account when reporting about ambiguous genes

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1870]
The validator reports this as an ambiguity problem:

`Gene alias maps to multiple Entrez ids (983/5424), please specify which one you mean or choose a non-ambiguous symbol	CDC2`

While the data loader code takes the file `/core/src/main/resources/gene_symbol_disambiguation.txt` into consideration and is able to find the entrez id that should be used. The validator should also use this information (perhaps via a new api?). 

This seems to be the current content of `/core/src/main/resources/gene_symbol_disambiguation.txt` (https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/resources/gene_symbol_disambiguation.txt):

```
#Gene_Symbol	Entrez_Gene_ID
MLL2	8085
CDC2	983
```

**Comment by pieterlukasse** [comment]
hey @sheridancbio , given your recent efforts on gene symbols and disambiguation, I thought of sharing this issue with you ;)  Did you know we had this file? Do you think it could be useful? Or should we remove it?

**Comment by jjgao** [comment]
we should aim to remove the file: https://github.com/cBioPortal/cbioportal/issues/6189#issuecomment-515715857
