### ISSUE TITLE
Remove cache for study data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#188]
Given the pain of restarting tomcat-server after data importing, maybe we should get rid of all cache related to study in the following classes.
* DaoCancerStudy
* DaoGeneticProfile
* DaoPatient
* DaoSample
* Any other classes?

We can test the performance on the web site and see if it slow down noticeably.

If the performance if not a issue, after removing the cache, I would propose to add two columns in the cancer_study table "import_status" and "time_of_status". Before starting import a study, import_status is be set to "importing". When import is done, set to "complete". On the front end, we only display studies with status of complete. When a user visit a study with status of importing, we can display a msg like "The study is being updated. Please come back in a few minutes."

**Comment by jjgao** [comment]
It wasn't working because of performance issue

**Comment by j-hudecek** [comment]
Perhaps there could be a different mechanism for reloading the cache? I was thinking about scanning a directory for a particular file once every n seconds, if it is found delete it and reload all caches (blocking all requests while it's going on). This would avoid restarting the container which can cause lose your session which can be annoying.

**Comment by n1zea144** [comment]
We've been running some dynamic cache reloader code internally for a few months (we used the cancer study table itself to store info about a study's state) and we just couldn't get it working just right (JJ has info about the most recent issues), so we turned it off, but we are willing to revisit this.
