### ISSUE TITLE
Replace Chi-squared Test by Exact Test

### ISSUE THREAD

**Issue by DarioS** [cBioPortal/cbioportal#1883]
The Chi-squared test produces inaccurate p-values if the sample sizes of the two groups of samples are unbalanced. [A new test](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004071) provides an exact p-value that calculates correct probabilities in all situations. This could replace the current log-rank test.

**Comment by jjgao** [comment]
@DarioS: Thanks for the info. Do you know if there is any available code preferably in Javascript?

**Comment by DarioS** [comment]
An implementation of ExaLT is [available within](http://compbio.cs.brown.edu/projects/survival/) Raphael Lab's Software website. It's written in C++ and R, and an alternative implementation is in MATLAB. It wouldn't be as easy to incorporate into cBioPortal as I thought.

**Comment by jjgao** [comment]
I'm closing this since we don't have the resource to work on it right now.
