### ISSUE TITLE
Plots tab does not work if missing cna data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1886]
even if there is expression data. Example study: blca_mskcc_solit_2015

The study only have mutation and expression data. The Plots tab does not work.

![image](https://cloud.githubusercontent.com/assets/840895/20122450/ae770fde-a5e5-11e6-9a63-a8073a40d3a2.png)

**Comment by yichaoS** [comment]
https://github.com/cBioPortal/cbioportal/pull/1888
