### ISSUE TITLE
Fusion glyph not displaying in OncoPrint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1891]
e.g. http://bit.ly/2g8Lvuq

**Comment by adamabeshouse** [comment]
@jjgao fusion is no longer a kind of mutation, it's its own command, so you should write `ERG:FUSION`. `ERG: MUT=FUSION` will look for mutations with the amino acid change "FUSION". Let me know if I should re-add that functionality for backwards compatibility.

**Comment by adamabeshouse** [comment]
We determined in Slack that we're dropping the `MUT=FUSION` syntax, and added documentation for the new `FUSION` keyword: https://github.com/cBioPortal/cbioportal/pull/1900
