### ISSUE TITLE
Should GeneticProfile.geneticAlterationType be an enum which stringifies in JSON, rather than a string?

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#1898]

**Comment by ersinciftci** [comment]
Yeah I was going to make it an enum but I wasn't sure what possible values it can has, do you have a list @adamabeshouse?

**Comment by sheridancbio** [comment]
Fairly recently I converted this class to be a true enum .. maybe this is appropriate?
https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/model/GeneticAlterationType.java

**Comment by sheridancbio** [comment]
I see that in core GeneticProfile has a data member which is already an instance of GeneticAlternationType:
https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/model/GeneticProfile.java

I guess this discussion is about the model module class:
https://github.com/cBioPortal/cbioportal/blob/rc/model/src/main/java/org/cbioportal/model/GeneticProfile.java

It may make sense to move the enum GeneticAlterationType out of core and into the model module and use it there?

**Comment by ersinciftci** [comment]
@sheridancbio what do you mean by true enum? why is it not a Java `enum` type?

**Comment by sheridancbio** [comment]
GeneticAlterationType *is* now a simple Java enum type. Previously it was a combination of static constants and selector methods.

**Comment by sheridancbio** [comment]
Ah .. I see the confusion .. rc has not yet been merged into master. Here is the rc branch version of the class ... sorry for giving the wrong link before.

https://github.com/cBioPortal/cbioportal/blob/rc/core/src/main/java/org/mskcc/cbio/portal/model/GeneticAlterationType.java

**Comment by ersinciftci** [comment]
Oh ok, cool :) I'll just move it to the model module then in my next PR.

**Comment by ersinciftci** [comment]
Actually it's used in 113 files, so I'll just add the enum type in GeneticProfile model for now(just like SampleType in Sample model), won't change the old one.

**Comment by ersinciftci** [comment]
Merged in this PR https://github.com/cBioPortal/cbioportal/pull/1906
