### ISSUE TITLE
Source Build contains hardcoded NEWS section

### ISSUE THREAD

**Issue by serverhorror** [cBioPortal/cbioportal#19]
Hello,

The source build currently contains a lot of hardcoded information like the NEWS and FAQ pages.

Especially the NEWS page is confusing to users as you mention all the imports that are available on the cbioportal.org site but are not available for local installations.

thanks,
Martin

**Comment by ecerami** [comment]
This is definitely an issue, and I have noted the same problem for local installations.

You can hack your way out of it by modifying the JSP pages, but as a general solution, we need to extend the cBioSkins project that we started a while back, to fix this -- such that, all of this info can be configurable via portal.properties.

**Comment by serverhorror** [comment]
Are you sure that this kind of content should even be part of cbioportal?

I think the application itself should only have these top level navigation points:

* Home
* Data Sets
* Web API
* About

*Maybe* the *R/MATLAB* part. But that's about it. The TUTORIALS, NEWS, TOOLS and other sections aren't necessary in my opinion.

For a matter of fact right now they do more harm as they are external links which are very much frowned upon in the organization I'm currently working for. Everything that somehow leads to external things is evil! Pure evil!11eleven!!1one! (IP protection kicks in which is not a matter of logic but rather some arbitrary decision made by the legal departement)

**Comment by jjgao** [comment]
Now you can turn on/off tabs with pull #150 or point to different locations with pull #513.
