### ISSUE TITLE
enrichments rppa plots div missing in this particular query

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#1917]
![screen shot 2016-11-22 at 12 15 35 pm](https://cloud.githubusercontent.com/assets/5973438/20533969/7a3c4342-b0ad-11e6-9430-2a31a5eb8fa9.png)
![screen shot 2016-11-22 at 12 15 39 pm](https://cloud.githubusercontent.com/assets/5973438/20533970/7a400518-b0ad-11e6-81e6-dca056635974.png)

**Comment by pieterlukasse** [comment]
Hi @yichaoS, is this happening always? Which gene did you query? Are you sure you cleared your browser's cache (sometimes this is the issue).
