### ISSUE TITLE
Reset button is confusing when removing columns in clinical tab

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1925]
Steps to reproduce: 

1. go to http://www.cbioportal.org/study?id=blca_tcga#clinical
2. click "Show/Hide columns"
3. deselect *all* columns. A message on the right side appears with the option to Reset the filter. See screenshot
4. click the Reset option. Nothing happens

Screenshot:

![image](https://cloud.githubusercontent.com/assets/2900303/20569745/76b1c77a-b1a1-11e6-8c80-8a64004c58b0.png)

Desired solution: 
- do not show the Reset option if no columns are selected

**Comment by pieterlukasse** [comment]
@zhx828 were you aware of this one?

**Comment by zhx828** [comment]
@pieterlukasse No, I wasn't. I will fix this. Thanks for letting me know.

**Comment by stefanches7** [comment]
@pieterlukasse what is the original functionality of this button? flushing filters?

**Comment by zhx828** [comment]
@stefanches7 Yes, it is. Totally forgot about the issue. I will fix it ASAP.

**Comment by stefanches7** [comment]
@zhx828 you could actually leave this one to me , seems like a nice way to start contributing and dig code a little bit.

So to the issue, even if some channels are checked, isn't reset still idle with no filters entered?

From what I saw, I would suggest "reset" clickable to appear only after some filter is entered and disappear after it has been clicked.

**Comment by zhx828** [comment]
@stefanches7 the source code actually located in here, we use it as dependency in portal. https://github.com/cBioPortal/enhanced-fixed-datatable/tree/study-view-clinical

**Comment by stefanches7** [comment]
@zhx828 thanks for a tip!

**Comment by stefanches7** [comment]
[https://github.com/cBioPortal/enhanced-fixed-datatable/pull/50](url)

**Comment by jjgao** [comment]
Closing this one. I has been reimplemented in the new study view.
