### ISSUE TITLE
Generic implementation of SAMLUserDetailsService is missing

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1934]
Currently there is only a mskcc specific implementation at `core/src/main/java/org/mskcc/cbio/portal/authentication/saml/MSKCCPortalUserDetailsService.java`. Would be good to have a generic one where perhaps details like the location of `mail` and `displayName` are configurable, or parsed in a more flexible way than currently implemented.

**Comment by n1zea144** [comment]
Yes, this is a good idea.  We actually have an project going with our GSOC student which involves splitting off the security code from core and moving it into a separate security module.  Its in a new security-rearchitecture branch.  It would be a good opportunity to address this issue.
[security-rearchitecture](https://github.com/cBioPortal/cbioportal/tree/security-rearchitecture)

**Comment by pieterlukasse** [comment]
solved now by #2068
