### ISSUE TITLE
GSVA - add hierarchy popup UI 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1935]
The hierarchy popup UI  should allow for easy selection of gene sets through a hierarchy. The leaf nodes of the hierarchy tree should contain the gene set entries, with extra information regarding the GSVA Score, p-value and number of genes that are part of this gene set.

See Fig 1c of [RFC 28 document](https://docs.google.com/document/d/1g5HPPXrLqJQmfxP1RcWGA6-QdcHCTLr_JAuQklQdfMs/edit).

**Comment by pieterlukasse** [comment]
@inodb I will need some help if I am to implement this using React. What do you think? Should I use React for this already? And if yes, can you point me to the guidelines of how to do this. I am planning of just adding this to the portal module. It is a popup that will appear on the query page, similar to how GISTIC and MUTSIG lists are shown for selecting genes.

**Comment by inodb** [comment]
@pieterlukasse Ideally, yes. Maybe best to discuss with @adufilie, since he's working on changing this component. Otherwise you can maybe implement it in a way, such that he can easily update it to React when he gets to that point.

**Comment by sandertan** [comment]
https://github.com/thehyve/cbioportal/tree/geneset_hierarchy-popup

- [ ] Query web service for JSON with gene set hierarchy data
- [ ] Use hard coded test JSON to parse data and build tree
- [ ] Select only gene sets (leafs), no nodes.

**Comment by adufilie** [comment]
I was tasked by @ecerami to recreate the current popups in React. Is this a completely new popup or is it a replacement for the existing one?

**Comment by sandertan** [comment]
Hi @adufilie this is a new popup, of which the button is shown when geneset genetic profiles are selected (new feature). We based it on the code of the Mutsig and Gistic popup.

**Comment by sandertan** [comment]
@adufilie The tree was created with the same JQuery Plugin as used to select a study on the Query page [https://www.jstree.com](https://www.jstree.com). It was relatively easy to implement; after parsing a JSON with the relevant data, Jstree does all of the work to format it nicely. 

This is the code that does the tree-building. flatData is the parsed JSON data.

```
	$('#jstree_genesets').jstree({
		"plugins": ['checkbox', 'search'],
		"checkbox": {},
		"core" : {
			"data" : flatData,
			"themes": {
				"icons":false
			} 
		}
	});
	$('#jstree_genesets').jstree(true).open_all();
```

We still want to implement a search and filter feature, as described in figure 1c and 1d of [RFC28](https://docs.google.com/document/d/1g5HPPXrLqJQmfxP1RcWGA6-QdcHCTLr_JAuQklQdfMs/edit).

Here are some screenshots to get an impression of the functionality:

<img width="1280" alt="screen shot 2017-02-07 at 15 48 22" src="https://cloud.githubusercontent.com/assets/9624990/22696065/1dafe3fe-ed4d-11e6-9abf-82d7bb1bae5f.png">
<img width="1280" alt="screen shot 2017-02-07 at 15 48 26" src="https://cloud.githubusercontent.com/assets/9624990/22696068/1dcd41ec-ed4d-11e6-8f19-da1bea87b2ea.png">
<img width="1280" alt="screen shot 2017-02-07 at 15 49 05" src="https://cloud.githubusercontent.com/assets/9624990/22696069/1ddff3a0-ed4d-11e6-9b37-2913b40cd5ed.png">
<img width="1280" alt="screen shot 2017-02-07 at 15 49 16" src="https://cloud.githubusercontent.com/assets/9624990/22696067/1dc9afc8-ed4d-11e6-9106-e638800e1501.png">

**Comment by ecerami** [comment]
thanks @sandertan.  I have also reached out to @pieterlukasse about this, as I am not yet sure if we / @adufilie are prepared to port this over to the new architecture right now.

**Comment by sandertan** [comment]
@ecerami @adufilie @pieterlukasse The code for the popup, tree and geneset selection can be found in `genesets.js`.

https://github.com/thehyve/cbioportal/blob/40bf96e56a9fc16576750e574fb23da168feafca/portal/src/main/webapp/js/src/genesets.js
