### ISSUE TITLE
GSVA - add option to expand gene set tracks in oncoprint heatmap like visualization

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1938]
Add an extra "expand" feature to the gene set tracks added in #1833 

See figure 5 of [RFC 28 document](https://docs.google.com/document/d/1g5HPPXrLqJQmfxP1RcWGA6-QdcHCTLr_JAuQklQdfMs/edit).

**Comment by fedde-s** [comment]
The implementation for this is waiting for review in pull request #2190.
