### ISSUE TITLE
Change oncokb.url property to show.oncokb in property.EXAMPLE

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#1940]
The current implementation does give users the flexibility to enable/disable OncoKB annotation but not  in an intuitive way. And OncoKB team wouldn't be able to change the URL for all cBioPortal instances if there is any URL change. We propose to change the oncokb.url to show.oncokb in property.EXAMPLE but still keep the functionality of oncokb.url

**Comment by pieterlukasse** [comment]
good idea :+1: 
@kretep: maybe an idea for the CIVIC integration you are making?

**Comment by zhx828** [comment]
Issue has been solved in pull request https://github.com/cBioPortal/cbioportal/pull/1941
