### ISSUE TITLE
GSVA - add GSVA data to co-expression tab

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#1943]
It should be possible to select GSVA genetic profiles in the co-expression tab, as described in Figure 7 of  [RFC 28 document](https://docs.google.com/document/d/1g5HPPXrLqJQmfxP1RcWGA6-QdcHCTLr_JAuQklQdfMs/edit).

**Comment by sandertan** [comment]
https://github.com/thehyve/cbioportal/tree/gsva_plots
