### ISSUE TITLE
Copy data in clinical table on study view not working

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1959]
No data is copied to the clipboard when pressing the copy button in the clinical data table of the study view

**Comment by zhx828** [comment]
@schultzn I just found the issue, will fix it very soon. But looks like the library we are using has a limitation on the file size (https://github.com/zeroclipboard/zeroclipboard/issues/529)
@jjgao should we disable the Copy button for bigger studies until they fix the issue?

**Comment by zhx828** [comment]
I think I will go ahead disable the button for bigger studies since it's not usable. I will keep an eye on the issue I mentioned, if any changes apply to the library I will do another fix.
