### ISSUE TITLE
Multiple samples per patient in the clinical annotation track of an OncoPrint: Mixed is sometimes labeled incorrectly 

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1960]
In this query, some patients with multiple samples are incorrectly annotated as "Mixed". When there are multiple samples, but they are all either Primary or Metastasis, they should show up in the respective category.

http://bit.ly/2gHjqdw

![image](https://cloud.githubusercontent.com/assets/11892704/20773988/4e8c5e3c-b722-11e6-85ae-10024633e248.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1967
