### ISSUE TITLE
Results tab headers should not wrap into a second row

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1973]
We should implement something similar to what we have on the Mutations tab when there are two many genes (see second screenshot below)

![image](https://cloud.githubusercontent.com/assets/11892704/20937018/07c3b4b0-bbb3-11e6-9463-438104753e14.png)

![image](https://cloud.githubusercontent.com/assets/11892704/20937092/63158ea6-bbb3-11e6-80fd-a7e89a70e075.png)

**Comment by jjgao** [comment]
@JiaoJiao123 could you help on this?

**Comment by jjgao** [comment]
@alisman can we do a quick fix for this?
