### ISSUE TITLE
TCGA PDF reports not showing up

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1976]
http://www.cbioportal.org/case.do?cancer_study_id=brca_tcga_pub2015&sample_id=TCGA-AR-A1AJ-01

**Comment by jjgao** [comment]
It's because Chrome is no longer support PDF viewer by default.

https://support.google.com/chrome/answer/6213030?hl=en

**Comment by jjgao** [comment]
We should add a message for Chrome users.

**Comment by jjgao** [comment]
This will be fixed in the new patient view
