### ISSUE TITLE
How to decide the altered/unaltered criteria of mRNA expression?

### ISSUE THREAD

**Issue by CharlesChuange** [cBioPortal/cbioportal#1988]
When I used enrichment and oncoprint to analysis mRNA expression data, it showed that Upregulation/downregulation and altered/unaltered to me.
I want to know how to determine the criteria to seperate two group(up/down and altered/unaltered)? 
What is the algorithm or method?
Please tell me,  thank you!!

**Comment by jjgao** [comment]
For mRNA, it simply that any samples with an expression absolute value greater than the specified (default 2) z-score threshold are considered altered. For one-side query, you would need to use [Onco Query Language](http://www.cbioportal.org/onco_query_lang_desc.jsp).

**Comment by CharlesChuange** [comment]
thank you!!
