### ISSUE TITLE
Enrichments analysis drops custom case lists after adding new genes to query

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1995]
It looks like when adding new genes to a query directly from the enrichments tab, custom case lists are lost... You can add a gene once, but after that, the case list is lost and you can't modify the query any further.

To reproduce, pick any custom case list, run a query, add a gene from the enrichments tab, run the query, and then look at the case list in "modify query".

**Comment by jjgao** [comment]
This issue will be solved once we enable session service -- it's already solved on msk-portal.

**Comment by jjgao** [comment]
actaully it's not.

**Comment by jjgao** [comment]
@yichaoS Could you look into this?
