### ISSUE TITLE
Trailing tab when downloading mutation data

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2]
This is very low priority but just wanted to mention it. When downloading mutation data from a study

![screen shot 2015-04-07 at 12 05 46 pm](https://cloud.githubusercontent.com/assets/1334004/7027659/ba03af6a-dd1e-11e4-9ac1-e6d5d9245b9b.png)

the resulting tsv has a trailing tab

![screen shot 2015-04-07 at 12 06 05 pm](https://cloud.githubusercontent.com/assets/1334004/7027688/dfc8e954-dd1e-11e4-9ef5-c8fbb31a9acc.png)

This could cause problems when reading the tsv. For instance when using pandas read_csv in python an extra column is created.

Not sure if this applies to other tsvs one can download from the cBioPortal as well.

**Comment by jjgao** [comment]
I'll be fixed by https://github.com/cBioPortal/cbioportal/issues/5189
