### ISSUE TITLE
Duplicate clinical attributes in Plots tab

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#2000]
Some clinical attributes appears to show up twice in the Plots tab. 

I checked this also in a local database where the clin attr is only once in database (I believe).

<img width="633" alt="screen shot 2016-12-21 at 18 11 23" src="https://cloud.githubusercontent.com/assets/9624990/21398784/0800a17a-c7a9-11e6-8f8c-6066643e3311.png">

**Comment by inodb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Grok Copy Number Data needs in patient view](https://trello.com/c/r8h31CER/12-grok-copy-number-data-needs-in-patient-view)

**Comment by sandertan** [comment]
I can not reproduce this anymore, it looks like it's fixed 👍
