### ISSUE TITLE
/api/clinical-data/fetch no response for lgg_ucsf_2014 P04_Pri

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2010]
On page

https://cbioportal-pr-2009.herokuapp.com/case.do?cancer_study_id=ucec_tcga_pub&case_id=TCGA-BK-A0CC

The API does not return any data for:

```
curl 'https://cbioportal-pr-2009.herokuapp.com/api/clinical-data/fetch?clinicalDataType=SAMPLE&projection=DETAILED' -H 'Content-Type: application/json' -H 'Accept: application/json'  -H 'Connection: keep-alive' --data-binary '[{"id":"TCGA-BK-A0CC-01","studyId":"lgg_ucsf_2014"}]' --compressed
```

But there is clinical data in the tooltip of the sample, i.e.:

![screen shot 2016-12-22 at 7 01 07 pm](https://cloud.githubusercontent.com/assets/1334004/21444171/04d9c2b2-c879-11e6-9ae1-d34946902452.png)

**Comment by ersinciftci** [comment]
@inodb in the request body, `id` is changed to `entityId` in the latest merged API changes, it seems like it's not reflected here. I added this change later to the PR, it was not in the initial version, so it's possible that you generated the typescript client library from an earlier version of the PR instead of the latest rc?

**Comment by inodb** [comment]
@ecerami It's slightly odd because there's another page that is working with `id`, e.g.: 

```
curl 'http://cbioportal-pr-2009.herokuapp.com//api/clinical-data/fetch?clinicalDataType=SAMPLE&projection=DETAILED'  -H 'Connection: keep-alive' --data-binary '[{"id":"P04_Pri","studyId":"lgg_ucsf_2014"},{"id":"P04_Rec1","studyId":"lgg_ucsf_2014"},{"id":"P04_Rec2","studyId":"lgg_ucsf_2014"},{"id":"P04_Rec3","studyId":"lgg_ucsf_2014"}]' --compressed
```


I think branch `release-1.4.0` doesn't have that `entityId` change yet. Should we update that branch with the latest changes in `rc`?

**Comment by alisman** [comment]
I think I did generate the client based on the latest api changes in rc.   When I regenerate the api based on release-1.4.0 there are a lot of ts errors.  I will try to fix these and see if it resolves the issue.

**Comment by inodb** [comment]
Problem seems to be solved, I just went over my limit API calls on heroku, so have to wait a few mins ;)
