### ISSUE TITLE
Oncoprint: Restore the zooming buttons / slider / text input

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2018]
Per Niki's request, let's restore them int he menu. We can still keep the current zooming function in the mini-map.

- [x] restore zoom buttons, slider and text input
- [x] always hide the birds eye view by default when opening oncoprint (no cookie / local storage)
- [x] remove the while section when loading oncoprint
- [x] remove the white space under oncoprint by default

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2020 solves the first three issues here

**Comment by adamabeshouse** [comment]
Some problems with #2020 so #2037 is ready for merging.
