### ISSUE TITLE
New OncoPrint shows incorrect coverage

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2019]
This is for MSK-IMPACT patients:

![image](https://cloud.githubusercontent.com/assets/11892704/21529031/bde94680-cd04-11e6-8734-370054812735.png)

**Comment by adamabeshouse** [comment]
@schultzn what gene is that?

**Comment by adamabeshouse** [comment]
Hm, looks like there's something wrong with the gene panel API. I'll look into this today.

**Comment by schultzn** [comment]
Thanks!

**Comment by adamabeshouse** [comment]
@inodb queried dashi for me, and found that there's no gene panel data for samples in IMPACT:
```
mysql> select distinct(panel_id) from sample_profile where genetic_profile_id in (8809,8810);
+----------+
| panel_id |
+----------+
|     NULL |
+----------+
1 row in set (0.02 sec)
```

By convention agreed on w/ @zheins and @sheridancbio, if there's no gene panel data for a sample, we assume it's been whole-exome sequenced.

So I don't think there's a bug in the code, there's something wrong with the data in the database.

**Comment by schultzn** [comment]
There should be data there … MSK-IMPACT uses three different panels, and we should try to capture that information.

**Comment by jjgao** [comment]
@n1zea144 could you look into that?

**Comment by jjgao** [comment]
@zheins @schultzn any update on this?

**Comment by pieterlukasse** [comment]
Showing "whole exome" is wrong in case of proteomics. Here a screenshot when hovering CPTAC data:

![image](https://cloud.githubusercontent.com/assets/2900303/25137337/c47fd518-2457-11e7-8154-dd05e634e9e6.png)

Let me know if this needs to be logged in a separate ticket.

**Comment by jjgao** [comment]
The problem with IMPACT seems solved.

@pieterlukasse The gene panel currently only refers to mutation data, but I agree it's confusing.
