### ISSUE TITLE
OncoPrint: Distinguish between sample and gene not sequenced

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2029]
In the new OncoPrint feature, can we distinguish between whether an entire sample or just the gene was not sequenced? I suggest to change the tooltip to:
"Sample not sequenced" and "Gene not sequenced in this sample".

![image](https://cloud.githubusercontent.com/assets/11892704/21687301/bbb0ec64-d336-11e6-9694-e7f21d12f27a.png)

**Comment by adamabeshouse** [comment]
@schultzn Do you mean if the sample wasn't sequenced in the queried genes, or if it wasn't sequenced at all?

**Comment by schultzn** [comment]
If the entire sample wasn't sequenced, the text could say: "Sample not sequenced". If, however, some genes were sequenced, but others were not, and there is no sequencing data for a given gene, the text could read: "Gene not sequenced in this sample"

**Comment by adamabeshouse** [comment]
I understand, I'm asking if by "sample not sequenced" you mean "genes queried for the oncoprint not sequenced in sample", or if you mean "sample not sequenced at all." I haven't been familiar with the latter case being possible in the portal, so I think it's the former, but just wanted to make sure.

**Comment by schultzn** [comment]
I mean the latter. We have information on that per sample, it is called “With Mutation Data”

**Comment by jjgao** [comment]
@adamabeshouse there is a case/sample list called "case_sequenced". If a samples is _not_ in this case list, it is not sequenced at all.

**Comment by adamabeshouse** [comment]
@jjgao it will always be called `${study stable id}_case_sequenced` ?

**Comment by adamabeshouse** [comment]
@jjgao @schultzn bump :)

**Comment by jjgao** [comment]
@adamabeshouse yes.

**Comment by adamabeshouse** [comment]
@jj @schultzn several of these samples have CNA data, so the tooltip will say "not sequenced" but it will show a deletion. For example in `all_target_phase1`

**Comment by schultzn** [comment]
Maybe our term "not sequenced" is incorrect... should be "no mutation data"

**Comment by adamabeshouse** [comment]
What should I show if a sample has CNA but no mutation data? As it is now, if it has a CNA alteration, the only indication that there's no mutation data will be in the tooltip, because the CNA alteration will cover the grey N/S rectangle.

**Comment by schultzn** [comment]
This is tricky… maybe grey out the middle of the rectangle, where the mutation call would normally show up?

**Comment by adamabeshouse** [comment]
Should I do that in general, and no longer gray out the entire rectangle ever? Or only if there's a CNA?

**Comment by schultzn** [comment]
no... for MSK-IMPACT samples, we typically have both CNA and mutation data for the same gene and sample. There are, however, some TCGA samples for which we have only one or the other - here, it will be important to show what data types are missing.

**Comment by jjgao** [comment]
@schultzn @adamabeshouse: Maybe we can discuss in person and try to find out all the scenarios we need to handle?

**Comment by pieterlukasse** [comment]
@adamabeshouse @jjgao please also consider enforcing the presence of `${study stable id}_case_sequenced` by adding a rule in the validation script, or at least giving a warning if this is missing.
