### ISSUE TITLE
Uncheck "Sort by mutation type" not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2065]
http://bit.ly/2jsDpeu

![image](https://cloud.githubusercontent.com/assets/840895/21945370/ea5b5d7e-d9a8-11e6-8083-de049cc2a8f7.png)

**Comment by adamabeshouse** [comment]
The issue here is that it's still sorting by driver/passenger, and truncating are always considered passenger.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2071
