### ISSUE TITLE
WT vs NS sorting should not have higher priority than gene alteration sorting

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2066]
![image](https://cloud.githubusercontent.com/assets/840895/21945395/071724d4-d9a9-11e6-97ed-fe4eae644bbd.png)

**Comment by adamabeshouse** [comment]
notes to self:
make comparator accept direction as parameter
sign is sign of decision, magnitude is priority
not yet sure how this will interact with PrecomputedComparator system, since need to take the largest priority

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2121
