### ISSUE TITLE
Internet Explorer User Warning

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#207]
I've noticed a lot of people accessing cBioPortal through IE. Many features don't work in IE, so I think it would be good to:
- Detect the browser everywhere on the portal
- If the browser is IE, show a warning bar somewhere (top/bottom)

**Comment by onursumer** [comment]
There is a `detectBrowser` function in cbio-util.js which I was using for JSmol related issues. I think it can also be applicable for this issue.

https://github.com/cBioPortal/cbioportal/blob/93c310ac54a85c48fa6cbc9b72c4c6d03add817b/portal/src/main/webapp/js/src/cbio-util.js#L195

**Comment by n1zea144** [comment]
We have this.

B

**Comment by n1zea144** [comment]
We should update the text and add it to other entry points (study summary, patient view, etc)

B

**Comment by n1zea144** [comment]
![image001](https://cloud.githubusercontent.com/assets/366003/9536197/433490d6-4cf7-11e5-94ef-99423770d789.png)

**Comment by jjgao** [comment]
@inodb have we done anything about this one?
