### ISSUE TITLE
CNA table in Study View only displays "cancer genes"

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2082]
CNA table in Study View only displays "cancer genes" configured in `core/src/main/resources/cbio_cancer_genes.txt`. Other genes are **never** displayed, no matter how many CNA events are found for these in a study. This is surprising, especially when compared to how the Mutation table is filled in the same Study View (see summary below).

#### Mutations table in Study View

Displays complete list of:
- Top 500 genes with 2 or more mutations in study
- All cbio cancer genes with 1 or more mutations in study (partly overlapping with top 500 above)
- All genes identified as significantly mutated for this study by MUTSIG, containing mutations in this study (partly overlapping with both items above)

#### CNA table in Study View

Displays complete list of:
- Only the cbio cancer genes with 1 or more AMP / DEL in study 

## Discussion

In my opinion it seems this could lead to the omission of many potentially interesting genes. I tried to quantify this below using the BRCA study: 

**Mutations:** 
![installation report az](https://cloud.githubusercontent.com/assets/2900303/22152862/08ceb4b4-df25-11e6-84c2-a0750a82e116.png)
**CNA:**

![installation report az 1](https://cloud.githubusercontent.com/assets/2900303/22152864/0ae47cb6-df25-11e6-9e52-d2bac6055088.png)

**Comment by pieterlukasse** [comment]
Notify: @jjgao @schultzn

**Comment by schultzn** [comment]
This is by design - if we showed all genes here, the table would be unusable, as it would be dominated by the most frequent large amplification. I agree that we should also use GISTIC peak information, if available. Maybe users can have the option to switch between "all" and "cancer genes".

**Comment by jjgao** [comment]
We will put all mutations and CNAs in the summary tab in the new patient view and sort them by OncoKB by default.

Currently we only sort by whether a mutation / cna is oncogenic and the associated levels. Maybe we should also sort genes (oncokb genes go first).

**Comment by jjgao** [comment]
I misunderstood.

For the study view page, it maybe too many data to load all CN-altered genes. Maybe we should move the query to the backend (when selected samples change).

One option is only displaying the top xx mutated / cn-altered genes for the selected samples. Another option is to paginating (need backend pagination api support).

add @zhx828 and @ersinciftci to the thread.

**Comment by pieterlukasse** [comment]
@jjgao thanks. Yes, an option to also show the top xx mutated / cn-altered genes would be great. I think this is also @schultzn means with his "switch" option.

**Comment by zhx828** [comment]
https://github.com/cBioPortal/cbioportal/pull/2338 is related to this topic.

**Comment by pieterlukasse** [comment]
@zhx828 can you explain a bit more how the PR you mentioned is related? Did you implement the "switch" option there?

**Comment by zhx828** [comment]
@pieterlukasse Just thought it is cancer gene related. So linked that pull request here!.

**Comment by pieterlukasse** [comment]
Hi @zhx828 , do you have updates on how this is working now in study view? I noticed that the table in http://www.cbioportal.org/study?id=brca_tcga#summary downloads as ~11,000 genes. So I guess the top 500 is not applicable anymore? But it doesn't seem to be all genes either (one of our tests in another local study seemed to contradict this).

**Comment by zhx828** [comment]
@pieterlukasse we removed the threshold in here https://github.com/cBioPortal/cbioportal/pull/3306/files Still not all genes are shown unless it appears twice or more.

**Comment by pieterlukasse** [comment]
thanks @zhx828. One question: what about the CNA part? Has this been changed/fixed as well?
