### ISSUE TITLE
Default "onelogin.com" SAML example not working

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2089]
The example documented at https://github.com/cBioPortal/cbioportal/blob/master/docs/Authenticating-Users-via-SAML.md for integrating with Onelogin.com does not seem to be working. The behavior I get is an endless loop between my local cBioPortal and onelogin.com IDP, where cBioPortal(Spring security actually...it never gets to our code) thinks the user is "authenticated" but "anonymous" and returns access denied and returns to the onelogin.com page, which redirects back to cBioPortal...etc...hence a loop...

I would like to get this working, so that the documentation in #2068 can be completed/validated.

**Comment by pieterlukasse** [comment]
@n1zea144 @ecerami could you help me by checking if you also get the same problem?

**Comment by n1zea144** [comment]
@pieterlukasse I had the exact same issue when I tried to get it working for a GSoC student.

**Comment by pieterlukasse** [comment]
is working now in #2068
