### ISSUE TITLE
Make Website Layout Internet Explorer 11 Compliant

### ISSUE THREAD

**Issue by DarioS** [cBioPortal/cbioportal#2092]
A lot of biologists use browsers like Internet Explorer or Microsoft Edge. Could the user interface be robust enough to be rendered correctly in Internet Explorer?

**Comment by DarioS** [comment]
This is related to #207, although that issue seemed to suggest that cBioPortal should work on versions greater than 9, which it doesn't.

**Comment by jjgao** [comment]
We only support IE11 or above.
