### ISSUE TITLE
NullPointerException in PortalMetaDataJSON

### ISSUE THREAD

**Issue by ihorvath64** [cBioPortal/cbioportal#21]
Hi,

I'm getting a NullPointerException in PortalMetaDataJSON while accessing the home page:

```java
SEVERE: Servlet.service() for servlet [portal_meta_data_json] in context with path [/cbio] threw exception
java.lang.NullPointerException
		at org.mskcc.cbio.portal.servlet.PortalMetaDataJSON.doGet(PortalMetaDataJSON.java:246)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
...
```

The offending line is
```visibleTypeOfCancerMap.put(typeOfCancerId, typeOfCancerMap.get(typeOfCancerId).getName());```
so I'm guessing ```typeOfCancerMap.get(typeOfCancerId)``` is returning null there.
We loaded the sample study following the steps on the Wiki, and the database tables look fine.

Any ideas?

Thanks,

  Istvan

**Comment by ecerami** [comment]
I have seen this issue myself.  First step, can you indicate which branch you are building from?

**Comment by ihorvath64** [comment]
Thanks for the quick reply.
I'm building from master.

**Comment by ecerami** [comment]
ok, good.  next step:  Have you imported the seed database described here:  https://github.com/cBioPortal/cbioportal/wiki/Import-the-Seed-Database

(this seed database has been updated recently).

**Comment by ecerami** [comment]
did reloading the new seed database fix this problem...?

**Comment by ihorvath64** [comment]
Sorry, got distracted. Will try to reload the database today to see if that helps.
Thanks so far :)

**Comment by ihorvath64** [comment]
Yes, that solved it!
The updated seed file had 551 rows in type_of_cancer vs. 452 rows in the old one.

Thanks for helping!

**Comment by ecerami** [comment]
hurray!
