### ISSUE TITLE
Oncoprint heatmap legends break when most recent track is removed

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#2106]
In 1.4.2-SNAPSHOT as currently running on cbioportal.org, enabling heatmap tracks via the Oncoprint menu bar adds a nice legend shared between the heatmap tracks:
![Oncoprint including heatmap view with functioning legend](https://cloud.githubusercontent.com/assets/4929431/22507136/49e3e2cc-e884-11e6-979c-731f9ae78990.png)

But when the track most recently added to the Oncoprint (not necessarily the bottom one, if the tracks have been reordered after adding) is removed via its track options menu, the legend itself disappears from its row:
![Oncoprint view missing the last heatmap track and part of the heatmap legend](https://cloud.githubusercontent.com/assets/4929431/22507030/c2a04eea-e883-11e6-93e0-f6c92a537015.png)

Some experimentation makes me believe that this is about removing the track most recently given as the target argument to the `oncoprint.shareRuleSet()` method to use an existing GradientRuleSet's legend. As expected, the rest of the legend row only disappears completely after removing all tracks it was shared between.

**Comment by fedde-s** [comment]
@adamabeshouse, can you reproduce this?

**Comment by adamabeshouse** [comment]
I can reproduce it, I'll look into it today. I think I've seen this before and I thought I remember fixing it...

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2117

**Comment by fedde-s** [comment]
Until the pull request is merged this issue is still present in both development branches, so I'll leave it open for clarity in case other people run into it.

**Comment by fedde-s** [comment]
Fixed in `hotfix` by #2117.
