### ISSUE TITLE
undocumented google analytics option

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2107]
There is a portal property that can be added to `portal.properties` to enable google analytics on your own instance, but this is not yet documented. 

The property is `google_analytics_profile_id` and perhaps it could be documented here:
https://github.com/cBioPortal/cbioportal/blob/master/docs/Customizing-your-instance-of-cBioPortal.md

**Comment by pieterlukasse** [comment]
@jjgao maybe you can easily document this based on an existing example?

**Comment by pieterlukasse** [comment]
maybe not very interesting for most local installations holding private data anyway...

**Comment by pieterlukasse** [comment]
@inodb any thoughts on this one? For us it is not a big priority, as long as the default is to have _no_ analytics.

**Comment by inodb** [comment]
still a good first issue

**Comment by jjgao** [comment]
Let's just finish it. I added it to the next sprint.
