### ISSUE TITLE
Some mutations have no keyword

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#2122]
In the `mutation_event` table, some mutations have `NULL` in the `KEYWORD` column. Is this a bug or intentional?

**Comment by serval2412** [comment]
In file core/src/main/resources/db/cgds.sql, I can read this:
    311 CREATE TABLE `mutation_event` (
    312   `MUTATION_EVENT_ID` int(255) NOT NULL auto_increment,
    313   `ENTREZ_GENE_ID` int(11) NOT NULL,
...
    339   `KEYWORD` varchar(50) DEFAULT NULL COMMENT 'e.g. truncating, V200 Missense, E338del, ',

I may be wrong but I'd say intentional

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/cbioportal/issues/2756
