### ISSUE TITLE
Oncoprint failing to load in /beta version

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2124]
Oncoprint page hangs in /beta version. See this query: http://www.cbioportal.org/beta/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=prostate-cancer%3A-ar-signaling-%2810-genes%29&gene_list=SOX9+RAN+TNK2+EP300+PXN+NCOA2+AR+NRIP1+NCOR1+NCOR2&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit

Error seems to be in one of the calls to `geneticprofiledata`:  "Unknown column 'genetic_alteration.GENETIC_ENTITY_ID" 

@sheridancbio looks like the /beta DB is not migrated yet to 2.0.0? 

```
Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'genetic_alteration.GENETIC_ENTITY_ID' in 'on clause'
### The error may exist in org/mskcc/cbio/portal/persistence/ProfileDataMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select         gene.HUGO_GENE_SYMBOL as hugo_gene_symbol,         gene.ENTREZ_GENE_ID as entrez_gene_id,         genetic_profile.STABLE_ID as genetic_profile_id,         genetic_alteration.VALUES as `values`,         cancer_study.CANCER_STUDY_IDENTIFIER as study_id     from genetic_alteration inner join gene on genetic_alteration.GENETIC_ENTITY_ID = gene.GENETIC_ENTITY_ID                             inner join genetic_profile on genetic_profile.GENETIC_PROFILE_ID = genetic_alteration.GENETIC_PROFILE_ID                             inner join cancer_study on genetic_profile.CANCER_STUDY_ID=cancer_study.CANCER_STUDY_ID     where genetic_profile.STABLE_ID in  (  ? )  and         gene.HUGO_GENE_SYMBOL in  (  ? , ? , ? , ? , ? , ? , ? , ? , ? , ? )
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'genetic_alteration.GENETIC_ENTITY_ID' in 'on clause'
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'genetic_alteration.GENETIC_ENTITY_ID' in 'on clause'
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:973)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	org.mskcc.cbio.portal.util.XssFilter.doFilter(XssFilter.java:65)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
```

**Comment by pieterlukasse** [comment]
@inodb I think it would be good to have at least 1 screenshot test for oncoprint

**Comment by sheridancbio** [comment]
I've added @ersinciftci to this issue, since this probably requires action by the frontend refactoring team. When rolling out rc, it is necessary to transition the database to the 2.0.x schema. We put a temporary "bridge" schema in place before the end of the year which supported 2.0.x but was backwards compatible to 1.4.x .. but if we are rolling out rc, we need to transition a database to use the new schema so that rc will function properly with the new database.

I very much agree that a unit test for oncoprint is needed.

**Comment by sheridancbio** [comment]
@JiaoJiao123 @n1zea144 should also be aware of this broken /beta functionality.

**Comment by jjgao** [comment]
looks like it's fixed.
