### ISSUE TITLE
Link from cross cancer bar is not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#213]

**Comment by armish** [comment]
Confirming this behavior:
![screen recording 2015-09-14 at 01 48 pm](https://cloud.githubusercontent.com/assets/7809/9857242/6f63877c-5ae7-11e5-8ec8-196ba3e0eb53.gif)

This is also of concern to NCI's Dashboard project, where genes have links out to cBioPortal. For example: http://ctd2-dashboard.nci.nih.gov/#/subject/552170
![image 2015-09-14 at 1 50 43 pm](https://cloud.githubusercontent.com/assets/7809/9857294/b442d4d8-5ae7-11e5-9fc0-addcfd101f4f.png)
