### ISSUE TITLE
Oncoprint not working in IE11

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2141]
@adamabeshouse : this is what I found:

![image](https://cloud.githubusercontent.com/assets/2900303/22994560/a2cc835a-f3c7-11e6-9d46-5be9db80a919.png)

You could use an alternative to log2, like here: http://stackoverflow.com/questions/27853445/alternative-for-math-log2

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2116
