### ISSUE TITLE
Bug in Study View selected samples count

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#2142]
If you look into this study : http://www.cbioportal.org/study?id=brca_tcga#summary
and select cancer type detailed “Breast Invasive Ductal Carcinoma" . 
It says Selected:822 samples / 815 patients . 
Total Breast Invasive Ductal Carcinoma samples are "821"

**Comment by zhx828** [comment]
@priti88 thanks for reporting the issue, actually we found this issue as well and it had been fixed this morning, thanks to @kalletlak please see there https://github.com/cBioPortal/iViz/pull/368 We will prioritize to release the changes.
