### ISSUE TITLE
Problem in business/pom.xml ?

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2145]
When building, all the modules get a "compiled" portal.properties file. Except the `business` module. Apparently this is the only one where the portal.properties file (in `business/target/classes/portal.properties`) does not contain the replaced variables but still has the original "not compiled" portal.properties file. This leads to errors when `GlobalProperties.java` takes this version as the properties file (it looks for any portal.properties in the classpath). 

Apparently something is wrong in `business/pom.xml`...tried to fix it but no luck until now.

**Comment by pieterlukasse** [comment]
@inodb @jjgao @oplantalech

**Comment by jjgao** [comment]
@pieterlukasse I am closing this since it's too old. Please feel free to reopen.
