### ISSUE TITLE
incorrect gene panel information showing up in Oncoprint

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2147]
In this internal example, some samples show up as WXS, instaed of IMPACTxxx
http://bit.ly/2kNSveP

for example:
https://cbioportal.mskcc.org/case.do?cancer_study_id=mskimpact&case_id=P-0006311

**Comment by adamabeshouse** [comment]
I think this must be a data issue, since everything else seems to be working...there's definitely gene panel data for that sample?

**Comment by schultzn** [comment]
If you go to the patient view, you can see gene panel data for each of the two samples.

**Comment by adamabeshouse** [comment]
I think there's something wrong with the API @zheins @sheridancbio, the response from the server isn't giving any data back for  P-0006311-T01-IM5, which on the frontend we interpret as meaning it's WXS

**Comment by adamabeshouse** [comment]
must be caused by https://github.com/cBioPortal/cbioportal/issues/3067

**Comment by adamabeshouse** [comment]
looks fixed in /beta
