### ISSUE TITLE
support patient id in the custom case set input box

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#216]

**Comment by jjgao** [comment]
Currently only sample IDs are supported. 

![image](https://cloud.githubusercontent.com/assets/840895/10232296/dc2103a0-6855-11e5-906b-199713cc155d.png)

We should add an option to support sample IDs too, similar to what we do in the study view select box.

![image](https://cloud.githubusercontent.com/assets/840895/10232328/10934738-6856-11e5-815d-4b9fc69df713.png)

**Comment by jjgao** [comment]
@zheins: please start from the rc branch.

**Comment by zheins** [comment]
Pull request #323
