### ISSUE TITLE
Patient view gene alteration frequencies tooltip text should say "patient"

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2170]
The patient view gene alteration frequencies tooltip text should say "patient" instead of "sample" ... 

1 sample (14.3%) in this study has mutated CTNNB1, out of which 1 (14.3%) has CTNNB1 K335 missense mutations.

**Comment by jjgao** [comment]
@schultzn but we don't have the statistics (%) on patients in our API yet.
