### ISSUE TITLE
Custom x-axis for survival plots

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2176]
It would be nice if the survival curves could have a custom x-axis, e.g. show only the first 5 years of follow-up. This would only change the visualization, not the statistics.

**Comment by jjgao** [comment]
@yichaoS @zhx828: we need a way to zoom in to the left part (first 5 years) by default.

**Comment by jjgao** [comment]
Maybe we can do this when refactoring??

**Comment by jjgao** [comment]
@zhx828 we can consider this as well when we working on the zooming for bar chart and density plot.

Let's prioritize it.

**Comment by alisman** [comment]
@jjgao @zhx828 would this be a good project for @dippindots ?

**Comment by jjgao** [comment]
@alisman I think this is a good one.
