### ISSUE TITLE
show cancer type / cancer type detailed first for MSK Impact-Heme

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#2179]
We are close to importing IMPACT-Heme into the cBioPortal.  One thing we would like to do is show cancer type and cancer type detailed first on the study page - like we do for MSK-IMPACT:

[IMPACT-Heme triage portal](http://dashi-dev.cbio.mskcc.org:28080/triage/study?id=mskimpact_heme#summary)

Can we get this into the RC branch over the next few days?

**Comment by jjgao** [comment]
@zhx828 Let's always put cancer type and cancer type detailed first unless there is only one cancer type.
