### ISSUE TITLE
new styling issues

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2194]
- [ ] `Data Sets` is selected in the home page. (maybe add a `Home` button)
 ![image](https://cloud.githubusercontent.com/assets/840895/23769399/4215079a-04dd-11e7-9f41-468cb6163ed6.png)
- [ ] The top buttons move to the left on: https://cbioportal-release-1-5-0.herokuapp.com/study?id=acc_tcga#summary.
- [ ] Remove MSKCC logo on top right.

**Comment by jjgao** [comment]
please fix them in the `release-1.5.0` branch

**Comment by oplantalech** [comment]
Menu bar is shifted to the right (under the cBioPortal logo) in the study view:
![captura de pantalla 2017-03-13 a les 14 59 30](https://cloud.githubusercontent.com/assets/20278013/23857514/deef7e60-07fd-11e7-8c18-40b996d951e7.png)
