### ISSUE TITLE
Loading of mutation lollipops can be very slow (local install only)

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#22]
(Note:  this only appears to happen w/i my local installation, following the wiki docs, and not on the production site).

But, in a nutshell, I have noticed that loading of mutation lollipops can be quite slow.

So far, I have traced it to this request:  http://localhost:8080/cbioportal/getPfamSequence.json?geneSymbol=EGFR

this one request can take 1-2 seconds on my local machine, and seems to account for most of the delay.

looking into this further, and also looping in @onursumer, as I think he may have worked on this a while back...

**Comment by onursumer** [comment]
Just a quick note: Ideally we should avoid fixing mutation mapper front-end related problems in portal. Specifically, we should avoid directly modifying https://github.com/cBioPortal/cbioportal/blob/stable/portal/src/main/webapp/js/lib/mutationMapper.js. That file is generated by https://github.com/cBioPortal/mutation-mapper.

Fixes/improvements on the server side are welcome though.

**Comment by ecerami** [comment]
I think the delay is on the server side.  but, I will dig deeper...

**Comment by ecerami** [comment]
So far, I think the problem is that we are connecting to the Uniprot Web API each time we need to re-draw the mutation lollipop.  This is done here:  https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/servlet/PfamSequenceServlet.java#L227

**Comment by ecerami** [comment]
Actually, looks like we are connecting to UniProt even if we only have one accession ID.  That's an easy fix I can make, e.g. if there is only one ID, don't go to UniProt.  But, why do we need to go to Uniprot at all to draw the mutation figure...?
