### ISSUE TITLE
CIViC icon is not aligned with others under crosscancer page annotation column

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2205]
I generated the screenshot by selecting all studies and querying for BRAF
![screen shot 2017-03-10 at 4 12 31 pm](https://cloud.githubusercontent.com/assets/5400599/23813586/86a85cc4-05ad-11e7-80d3-2db9f78dc6ab.png)

**Comment by oplantalech** [comment]
@zhx828 I can't reproduce your issue. I have tried it in Chrome, Firefox and Safari...
![captura de pantalla 2017-04-10 a les 13 26 45](https://cloud.githubusercontent.com/assets/20278013/24862874/c7a2cc46-1dfe-11e7-9298-f5a43c329f32.png)

**Comment by schultzn** [comment]
It looks like @zhx828 is using a data set with a variant that has a long AA change (note that the column is wider in his example). Are you both using different versions of the CCLE? I know we have some annotation differences between the public set and the one we are using within MSK.

**Comment by oplantalech** [comment]
@schultzn Thank you for the comment, I think that was the reason behind the issue.
