### ISSUE TITLE
Newly added heatmap tracks disappear when disabling clustering

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#2211]
When I sort an Oncoprint view that includes a heat map (e.g. [this one](http://www.cbioportal.org/beta/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=brca_tcga_rna_seq_v2_mrna_median_Zscores&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_rna_seq_v2_mrna&case_ids=&patient_case_select=sample&gene_set_choice=glioblastoma%3A-tp53-pathway-%284-genes%29&gene_list=CDKN2A+MDM2+MDM4+TP53&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&heatmap_track_groups=brca_tcga_rna_seq_v2_mrna_median_Zscores%2CCDKN2A%2CMDM2%2CMDM4%2CTP53&)) by the clustering order of the heat map (a new feature in 1.5.x, added by pull request #1998), and then use the Heatmap menu to add another gene to it, the new track appears unclustered. When I then sort the tracks by something else (e.g. by data), the track disappears until I re-enable clustering. This was not the behaviour I expected.

**Comment by fedde-s** [comment]
@pieterlukasse, is this intentional?

**Comment by fedde-s** [comment]
This is related to the more noticeable remaining issue in pull request #2190 of the effort to support sample-wise gene set scores.

**Comment by pieterlukasse** [comment]
fixed in #2215

**Comment by fedde-s** [comment]
Fix has been released a while ago already by now.
