### ISSUE TITLE
IGV copy-number view shows amplified regions as deleted

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2216]
The value of this segment is 0.7, but IGV.js shows it as deleted (blue), which it should to for negative values.

https://cbioportal.mskcc.org/index.do?session_id=58c9701b498e5df2e29110db&show_samples=false&

![image](https://cloud.githubusercontent.com/assets/11892704/23960344/1bfec00a-097e-11e7-90bd-43e8fde9d4b8.png)

**Comment by jjgao** [comment]
@JiaoJiao123 could you look into this when you have a chance? Not urgent. There may be a bug in IGV.

**Comment by jjgao** [comment]
@JiaoJiao123 maybe the gsoc student can help with this?

**Comment by JiaoJiao123** [comment]
@jjgao Thank you for letting me know. We will look into this.
