### ISSUE TITLE
compile the cbioportal source code with maven

### ISSUE THREAD

**Issue by sunyounglee** [cBioPortal/cbioportal#2225]
Hi, I'm trying to compile the cbioportal source code on my server (Amazon Ec2).
I'm using tomcat8. I removed some lines following the document (Note for those running Tomcat6).

When I compile the source code with maven "mvn -DskipTests clean install" , It seems to me
that something is wrong.. It is still proceeding (~2days).
Am I doing something wrong? Could you let me know how I can get the 'cbioportal.war'?

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Apache Maven
[INFO] Maven Model
[INFO] Maven Artifact
[INFO] Maven Plugin API
[INFO] Maven Builder Support
[INFO] Maven Model Builder
[INFO] Maven Settings
[INFO] Maven Settings Builder
[INFO] Maven Repository Metadata Model
[INFO] Maven Aether Provider
[INFO] Maven Core
[INFO] Maven Compat
[INFO] Maven Embedder
[INFO] Apache Maven Distribution
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Maven 3.3.9
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ maven ---
[INFO] Deleting /root/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-bytecode-version) @ maven ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (ban-known-bad-maven-versions) @ maven ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ maven ---
[INFO] 
[INFO] --- apache-rat-plugin:0.11:check (rat-check) @ maven ---
[INFO] 64 implicit excludes (use -debug for more details).
[INFO] Exclude: src/test/resources*/**
[INFO] Exclude: src/test/projects/**
[INFO] Exclude: src/test/remote-repo/**
[INFO] Exclude: **/*.odg
[INFO] Exclude: bootstrap/**
[INFO] Exclude: README.bootstrap.txt
[INFO] Exclude: .repository/**
[INFO] Exclude: .maven/spy.log
[INFO] Exclude: .java-version
[INFO] Exclude: DEPENDENCIES
[INFO] 31303 resources included (use -debug for more details)

It still be here..

Thank you.

**Comment by fedde-s** [comment]
The output suggests that for some reason, instead of cBioPortal, Maven is trying to build Maven itself. For completeness: did you run the command from a working directory that contains the cBioPortal source code? There should be a file named `pom.xml` and folders named `src, `core`, `web`, `business` and `portal`, among other things.

**Comment by sunyounglee** [comment]
Thank you. The problem is solved !
