### ISSUE TITLE
Sequenced sample numbers are wrong

### ISSUE THREAD

**Issue by awernibi** [cBioPortal/cbioportal#2232]
In "DATA SETS" the mutation frequencies are based on a wrong number of samples, which leads to mutation frequencies of more than 100%. 

![image](https://cloud.githubusercontent.com/assets/13519768/24204813/de40a836-0f19-11e7-9de7-701cda8aae7d.png)

In the expression overview there is something fundamentially wrong. It seems like almost all sequenced samples in the TCGA Colorectal study have a KRAS mutation. Oncoprint shows something different (<50%). It is very unlikely, that the intersection between sequenced samples and samples with RNASeq data have such a high mutation rate.

![image](https://cloud.githubusercontent.com/assets/13519768/24205469/c6151394-0f1b-11e7-9c6a-63babbec28f9.png)

**Comment by awernibi** [comment]
The mutation frequency issue on top seems to overlap with #597

**Comment by zhx828** [comment]
@awernibi thanks for pointing that out. I will take a look.

**Comment by zhx828** [comment]
@jjgao @zheins Could you take a look this study? 
1. It only contains 223 sequenced samples in the `coadread_tcga_sequenced ` list but APC(for example) has been mutated 870 times within 403 samples which causes the Freq more than 100%.

2. The sample `TCGA-AA-3980-01` is in _sequenced list but not in _all list.

**Comment by zhx828** [comment]
@awernibi I think the issue has been solved. Please let me know if you see any other datasets have similar issue.

**Comment by awernibi** [comment]
The first issue (mutation freq > 100%) seems to be solved. Ty.

For the second issue (mutation rate in the overlap between RNASeq data and sequencing data) it looks much better now. 
However, only a small fraction of sequenced samples are shown as sequenced (case list: _All Complete Tumors_, 7 samples). The correct case list to take for this purpose would be the _Sequenced Tumors_ case list (223 samples). 
![image](https://cloud.githubusercontent.com/assets/13519768/24907617/2b494a0e-1ebd-11e7-875c-e011419fbe96.png)

**Comment by zhx828** [comment]
@yichaoS could you take a look?
