### ISSUE TITLE
Beta: study view in Chrome is not wide enough - does not fit three large panels width wise

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2233]
![image](https://cloud.githubusercontent.com/assets/11892704/24215459/34121084-0f0f-11e7-8f7d-199015df8e9a.png)

Also ... logo is too close to the edge at the top

**Comment by jjgao** [comment]
@zhx828 could you close this if it's solved?

**Comment by zhx828** [comment]
@jjgao I will close the issue once I see the changes applied in beta portal.
