### ISSUE TITLE
OncoPrint OncoKB annotations: missing truncating mutations

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2234]
Truncating mutations are not annotated as oncogenic with OncoKB icon in the Oncoprints.. but they are properly annotated in the mutation details tab... 

![image](https://cloud.githubusercontent.com/assets/11892704/24215680/e0f24cba-0f0f-11e7-926a-1c0f25f02055.png)

![image](https://cloud.githubusercontent.com/assets/11892704/24215706/f2d70a24-0f0f-11e7-88c1-9b2ca2a6ab06.png)

**Comment by jjgao** [comment]
This is related to the other topic to filter/render mutations of all types based on oncokb annotation.

@adamabeshouse I'll discuss with you.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2254
