### ISSUE TITLE
Code clean-up: remove *oncotator*.java

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2237]
All oncotator related classes can probably be removed (or `cgds.sql` needs to be updated) since it looks like they depend on the table `oncotator_cache` which does not exist in `cgds.sql` 

Example in `DaoOncotatorCache.java`:
```
"INSERT INTO oncotator_cache (`CACHE_KEY`,`GENE_SYMBOL`, `GENOME_CHANGE`, `PROTEIN_CHANGE`," +
                                " `VARIANT_CLASSIFICATION`," +
...
```

**Comment by pieterlukasse** [comment]
@sheridancbio agree?

**Comment by sheridancbio** [comment]
I'm not familiar with the oncotator codebase. There is probably a great deal we can purge from the core Dao package (and others), and this is an obvious example.

I think @onursumer may be familiar with the replacement of oncotator. I'll ask around, but I think you are right; oncotator may not be used at all any more now that we are using genome nexus.

**Comment by sheridancbio** [comment]
Onur confirms that we can purge oncotator code.

**Comment by pieterlukasse** [comment]
solved by pending PR. Closing here...
