### ISSUE TITLE
After disabling CIViC, the annotation column still shows two loading gif

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2245]
![screen shot 2017-03-23 at 8 04 42 pm](https://cloud.githubusercontent.com/assets/5400599/24275177/f77268cc-1003-11e7-9ecd-f0a29678e0db.png)

**Comment by fedde-s** [comment]
I understand that this occurs in the mutation tab for both cross-cancer and single-study queries?

**Comment by zhx828** [comment]
@fedde-s yes. It effects both pages. I didn't see the integration in the patient view though.

**Comment by fedde-s** [comment]
Indeed, looking at the code, it seems like the patient view only inserts the loading spinners if CIViC is enabled, but this conditional is missing in the two versions of the mutation tab. I proposed to add the conditional in pull request #2252.

**Comment by zhx828** [comment]
@fedde-s left a comment there.
