### ISSUE TITLE
error: importing the sample study

### ISSUE THREAD

**Issue by sunyounglee** [cBioPortal/cbioportal#2250]
Hello, all..

I'm trying to import sample study.. However, after I excuted the command:
./metaImport.py -s ../../../test/scripts/test_data/study_es_0/ -n -o
I got the error message below:

#######################################################################
Overriding Warnings. Importing study now
#######################################################################

Data loading step using: /root/cbioportal/scripts/target/scripts-1.4.2.jar

Checked DB schema version: (expected: 1.4.0) (found: 1.3.0)
Error, probably due to this version of the portal being out of sync with the database. Run the database migration script located at PORTAL_HOME/core/src/main/scripts/migrate_db.py before continuing.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
Traceback (most recent call last):
  File "./metaImport.py", line 115, in <module>
    cbioportalImporter.main(args)
  File "/root/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 329, in main
    check_version(jvm_args)
  File "/root/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 137, in check_version
    run_java(*args)
  File "/root/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 679, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
RuntimeError: Aborting due to error while executing step.

Could anyone let me know how I can import completely? 
The issue #2069 is same as my problem.. How did you fix it?

Thank you.

**Comment by sandertan** [comment]
Hi @sunyounglee , it looks like you're using cBioPortal 1.4.x with a seed database of cBioPortal 1.3.x. Unfortunately the seed database on Datahub that your probably downloaded is not up to date. It will be updated soon though!

In the meanwhile, you can manually update your database with `PORTAL_HOME/core/src/main/scripts/migrate_db.py`, described [here](https://github.com/cBioPortal/cbioportal/blob/master/docs/Updating-your-cBioPortal-installation.md#running-the-migration-script). 

If you are starting with a new cBioPortal instance, you can also use the latest cBioPortal (1.5.0), and test the new seed database which is located [here](https://github.com/cBioPortal/datahub/tree/seed-v140/seedDB). This seed will be released to the master branch when it's tested and approved.

**Comment by sunyounglee** [comment]
Thank you. It worked !
