### ISSUE TITLE
Beta: broken query in the study view of the Metabric Breast Cancer

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#2251]
In the [study view of the Metabric Breast Cancer](http://www.cbioportal.org/beta/study?id=brca_metabric#summary), when performing a query with the genes AKT1, PIK3CA, PTEN with the samples that have Integrative Cluster = 8, this error appears:
![captura de pantalla 2017-03-27 a les 16 24 05](https://cloud.githubusercontent.com/assets/20278013/24361475/514ab1fc-130a-11e7-8869-232891b34b2d.png)

This error does not happen in version 1.4.3 (www.cbioportal.org), only on www.cbioportal.org/beta.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao this one seems quite serious but I am not sure how often it occurs, can you involve the right person?

**Comment by zhx828** [comment]
@adamabeshouse this is the form screenshot study view submits to query page. Could you take a quick look if there is anything wrong in the form? Thanks.

<img width="874" alt="screen shot 2017-03-27 at 10 51 14 am" src="https://cloud.githubusercontent.com/assets/5400599/24362625/532daad0-12db-11e7-904a-de9238aeff6a.png">

**Comment by oplantalech** [comment]
It seems that the bug is not specific to the Metabric Breast Cancer study. The same error happens in this cases:
- [Bladder Urothelial Carcinoma (TCGA, provisional)](http://www.cbioportal.org/beta/study?id=blca_tcga#summary) querying for KRAS for the samples with NO Adjuvant Postoperative Pharmaceutical Therapy Administered Indicator;
- http://www.cbioportal.org/beta/study?id=laml_tcga_pub#summary querying for KRAS for the samples that have Trasplant Type = 0.

**Comment by adamabeshouse** [comment]
@zhx828 everything looks right to me

**Comment by kalletlak** [comment]
I think this issue not cancer study specific. Getting this error whenever I try to query filtered samples/patients in the particular study

**Comment by jjgao** [comment]
it is fixed. It was database privilege issue: https://github.com/cBioPortal/cbioportal/issues/2263.
