### ISSUE TITLE
Study view hangs when a sample ID contains &

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#2266]
I loaded a study with a sample_id which contained the character `&`, and this caused errors when initializing the study view, specifically in two calls (`mutation.json` and `cna.json`). The problem seems to be when retrieving the IDs of the queried samples with `request.getParameter` (line 399 of `MutationsJSON.java` in the case of the mutations call), as it returns `&amp;` instead of `&`. The documentation does not specify that `&` (or other characters) are not allowed for a `study_id`.

**Comment by zhx828** [comment]
@oplantalech does the issue still exist? Are we allowing `&` in the study_id now?

**Comment by oplantalech** [comment]
@zhx828 Yes. I managed to load a study with the study id `brca_tcga&` and that's what happens when I go to the study view:
![captura de pantalla 2018-01-08 a les 10 29 12](https://user-images.githubusercontent.com/20278013/34664985-e6024f90-f45e-11e7-81c3-136133d72fb1.png)

**Comment by zhx828** [comment]
There is no easy way to solve this issue. I believe in most pages we use &
as separator. I would strongly suggest in the study id, we don’t allow to
use this character.

Hongxin

**Comment by jjgao** [comment]
We should probably have some rules (regex) for ids (study, patient, sample, profile, etc), and use validator to enforce them. I would make a strick rule, e.g. `[a-zA-Z_][a-zA-Z0-9_-]+`
