### ISSUE TITLE
Beta: New patient view only works for patient IDs, not sample IDs

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2271]
This one works:
http://www.cbioportal.org/beta/case.do#/patient?caseId=TCGA-A8-A08Z&studyId=brca_tcga_pub2015

But this one, which is linked to from within the portal, does not:
http://www.cbioportal.org/beta/case.do#/patient?caseId=TCGA-A8-A08Z-01&studyId=brca_tcga_pub2015

**Comment by alisman** [comment]
@jjgao We support legacy parameter sample_id, but I'm not sure how we can distinguish between patient ID and sample ID if the param name is the same (case ID).  If it's true that suffix -Integer is reliable patter, then we could handle that.

**Comment by inodb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New patient view only works for patient IDs, not sample IDs](https://trello.com/c/gEGeWZUs/212-new-patient-view-only-works-for-patient-ids-not-sample-ids)

**Comment by alisman** [comment]
Hi Niki, this is actually a problem with link rather than the page.  I believe the link should have sampleId param instead of caseId given that the value is a sampleId.   I believe I found the broken links on the Mutation tab of the study view.  Will fix.
