### ISSUE TITLE
Beta: New patient view is not showing allele counts when hovering over mutant allele frequency

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2272]
http://www.cbioportal.org/beta/case.do#/patient?caseId=TCGA-A8-A08Z&studyId=brca_tcga_pub2015

Allele counts should show up like in this example from the old patient view:
![image](https://cloud.githubusercontent.com/assets/11892704/24580159/382dda3a-16d1-11e7-80d9-e0edc53a2e9f.png)

**Comment by ecerami** [comment]
Good point.  Need to fix for release.

**Comment by onursumer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Not showing allele counts when hovering](https://trello.com/c/ouM8gqSJ/209-not-showing-allele-counts-when-hovering)
