### ISSUE TITLE
Incorrect sorting of clinical attribute (string) containing empty values

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#2274]
When sorting a column which contains empty values, the column is not sorted correctly. For example the `Diffuse Architecture` column. The problem only occurs for columns that contain strings. For integer attributes it seems that empty values are grouped and filled values are also correctly ordered.

http://www.cbioportal.org/study?id=acc_tcga#

![screen shot 2017-04-03 at 15 26 02](https://cloud.githubusercontent.com/assets/9624990/24611388/38519260-1882-11e7-854f-31485010ea5d.png)

**Comment by zhx828** [comment]
@sandertan the issue has been addressed in #2308, could you take a look? Thanks.

**Comment by sandertan** [comment]
@zhx828 Thanks! I've tested it and the issue seems to be solved.
