### ISSUE TITLE
 'sort by cosmic' not working properly

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2277]
http://www.cbioportal.org/beta/case.do#/patient?caseId=TCGA-3B-A9HP

**Comment by onursumer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cosmic column sort doesn't work as desired](https://trello.com/c/e84zlVKZ/210-cosmic-column-sort-doesn-t-work-as-desired)
