### ISSUE TITLE
Style the pagenation control so that it can stand out 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2281]
since we are paginating, we should make it super obvious that there are more data.

**Comment by ecerami** [comment]
@jjgao:  I assume you mean "Style the pagination control"?  Can you explain more what this mean?  Mutation tab?

**Comment by jjgao** [comment]
@ecerami: yes, style :). Mutations/CNA tables in the summary tab.

With pagenation, it happens quite often that our users overlook that there are more mutations / CNA events -- we have received a few emails on that. It would be good if we can make it obvious that there are more mutations by clicking the next page.

**Comment by onursumer** [comment]
Fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/291
