### ISSUE TITLE
support scroll instead of pagenation in table

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2282]
(this is probably for future) for the tables is it possible to use scroll instead of pagenation but still do lazy loading, ie. load when user scroll down. I saw many sites doing that nowadays.

**Comment by ersinciftci** [comment]
https://www.nngroup.com/articles/infinite-scrolling/ I agree with this article, i.e. I don't think cBioPortal is a kind of a site that would benefit from infinite scrolling.

**Comment by adamabeshouse** [comment]
"Show more" may be an implementation of this instinct?

**Comment by jjgao** [comment]
@ersinciftci good point. I am happy with the "show more" button.
