### ISSUE TITLE
New style issue: Study view has a lot of white space below the header

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2287]
With the new style (which I love) the study view has some extra white space below the header that could be removed.

http://www.cbioportal.org/study?id=coadread_tcga_pub#summary

![image](https://cloud.githubusercontent.com/assets/11892704/24635415/4423951a-18a1-11e7-9d19-712032f781a4.png)

**Comment by alisman** [comment]
@schultzn I think this is currently improved.  when this page gets refactored it will be brought into better alignment with rest of the site. i'm gonna close but let me know if it still bothers you.
