### ISSUE TITLE
Patient view: mouse over on cBioPortal column in mutation table not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#229]
We used to have a cross-cancer histogram when hovering the number in the cBioPortal column.

**Comment by adamabeshouse** [comment]
Can you put a screenshot/replication instructions?

**Comment by jjgao** [comment]
e.g. in the page below, nothing happens after hovering the numbers on the cBioPortal column. 

http://www.cbioportal.org/case.do?cancer_study_id=ucec_tcga_pub&case_id=TCGA-BK-A0CC

**Comment by adamabeshouse** [comment]
Do you think this is related to my code?

**Comment by jjgao** [comment]
@inodb: could you help look into this? We also want to change the number for truncating mutations. Let's discuss.

**Comment by jjgao** [comment]
@inodb if you haven't started working on this, I'll take this issue. I need to make some other changes as well.

**Comment by inodb** [comment]
@jjgao Haven't started on this yet, so please do
