### ISSUE TITLE
Study view hangs with ldap authentication and no sequenced or cna case list

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#2291]
Study view hangs with ldap authentication and no sequenced or cna case list:
![captura de pantalla 2017-04-05 a les 12 16 47](https://cloud.githubusercontent.com/assets/20278013/24713208/3c824f74-1a25-11e7-8d83-3b2e984fbb72.png)

This happens because cBioPortal is trying to retrieve non-existing case lists (sequenced and/or cna), and a 403 error is returned. However, in a system with no authentication, non-existing case lists return an empty list: http://www.cbioportal.org/api/sample-lists/prad_mskcc_2014_dummy/sample-ids.

These calls are made because the study view always shows the pie charts for 'With mutation data' and 'With CNA data'. For example, if there are no samples with mutation data, the pie chart shows all samples with mutation data = NO. 

This issue is probably related with the PR #2138 that @mandawilson did.

**Comment by oplantalech** [comment]
I think pie charts should not be shown if there is no data for them. Also, to make troubleshooting easier, I think the error that should be returned is a 404 instead of a 403.

**Comment by zhx828** [comment]
@oplantalech thanks for pointing out. I will send out the fix today.
