### ISSUE TITLE
Support mouse genomes

### ISSUE THREAD

**Issue by murphycj** [cBioPortal/cbioportal#2293]
Would be nice if cBio supported mouse genomes. There are probably around a dozen or so studies with sequencing data from mouse tumors (endogenous mouse tumors, not xenographs). I' am going to start looking into modifying the code myself, but I thought I would just put the request out there.

**Comment by Sjoerd-van-Hagen** [comment]
Hi Charles,

There is already support for mouse data in cBioPortal. Please contact us if
you need help.

Best,

Sjoerd.

**Comment by murphycj** [comment]
Ok thanks!
