### ISSUE TITLE
Co-expression tab not appearing in certain contexts where it is expected to show up

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#2297]
Recently some users reported us an issue regarding the co-expression tab: they loaded a study with expression data, but when they were querying genes the co-expression tab was not showing up. We believe this error appears because they load only **Z-score data**. 

Co-expression is calculated on the non-normalized expression data, so although it makes sense for the tab not to appear when studies do not contain these data, it is not clear enough for users. It might be useful to enable the co-expression tab when there is only Z-score expression data with a message stating that the study does not contain non-normalized data and co-expression cannot be calculated.

While looking into this issue, I also discovered that the co-expression tab is only enabled if there is mRNA data which does not contain Z-scores. But it should be also enabled if there is **RPPA data**.

@jj @pieterlukasse can you take a look at this issue?

**Comment by pieterlukasse** [comment]
This is the part in `global_variables.jsp` that has some influence on whether co-expression tab should appear:
```java 
GeneticProfile final_gp = CoExpUtil.getPreferedGeneticProfile(cancerStudyId);
    if (final_gp != null) {
        showCoexpTab = true;
    } 
```
As Oleguer indicated, `CoExpUtil.getPreferedGeneticProfile` will only return a profile if there is also a "non-z-score" mrna profile in the study. If not, it returns `null` and `showCoexpTab` remains `false`.
