### ISSUE TITLE
Wiki :  Broken links - Drug target and clinical-trial data

### ISSUE THREAD

**Issue by xiuchengquek** [cBioPortal/cbioportal#23]
Not a big deal here but the link at to the PDQ cancer page at [wiki page](https://github.com/cBioPortal/cbioportal/wiki/Import-the-Seed-Database#drug-target-and-clinical-trial-data) is broken.

**Comment by ecerami** [comment]
Do you know the correct link?  I can update the wiki doc.

**Comment by xiuchengquek** [comment]
I think the its either 
1. http://www.cancer.gov/about-cancer/treatment/clinical-trials/search - Exact search 
2. http://www.cancer.gov/publications/pdq - Overview of the pdq program

**Comment by ecerami** [comment]
Thanks for reporting this.  I have updated the wiki.  Closing.
