### ISSUE TITLE
Tighten up / remove white space on new patient view page

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#2300]
Reported by @schultzn.

@alisman @jjgao:  Discussed this with @brittanystoroz today, and she said she had time to work on this next week.

**Comment by ecerami** [comment]
@brittanystoroz:  Just spoke with Aaron on slack, and he has already started to work on tightening of the new patient view.

So, better if you go back to your original plan, and work on the home page components.

**Comment by jjgao** [comment]
A few things we can do [from standup discussion today]

- [ ] remove headers
- [ ] add "XX mutations" and "XX copy number altered genes" after the search box of mutaitons and cna tables
- [ ] set row padding to 3px
- [ ] set the margin between toolbar and table to 5px
- [ ] reduce the margin under the genomic overview section
- [ ] remove the pagenation control at the bottom

**Comment by onursumer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Even more compact patient view](https://trello.com/c/Ni3UMp2Y/216-even-more-compact-patient-view)

**Comment by onursumer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Even more compact patient view](https://trello.com/c/Ni3UMp2Y/216-even-more-compact-patient-view)
