### ISSUE TITLE
Figure out a solution for visibility of cna table below mutation table

### ISSUE THREAD

**Issue by ersinciftci** [cBioPortal/cbioportal#2305]
For this patient http://www.cbioportal.org/beta/case.do#/patient?caseId=TCGA-BK-A0CC&studyId=ucec_tcga_pub , there are 8 mutations in the second page of the table. So when I go to the second page when I'm centered on the bottom of the table, like:

<img width="1672" alt="screen shot 2017-04-10 at 11 24 26 am" src="https://cloud.githubusercontent.com/assets/3595704/24869168/545472b2-1de0-11e7-862a-010ae015fcbf.png">

the mutation table disappears because there are fewer number of elements in it now:

<img width="1657" alt="screen shot 2017-04-10 at 11 25 49 am" src="https://cloud.githubusercontent.com/assets/3595704/24869207/7b227fce-1de0-11e7-9653-10c83f7a63b1.png">

I don't know the solution to this, either we shouldn't have more than one table in one tab, or we should jump to top of the table whenever paging is changed.

**Comment by alisman** [comment]
Solution: reduce default rows size to 10 and jump top on navigation.
