### ISSUE TITLE
handling uncalled events in the patient view page (supporting cfDNA projects)

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2306]
- [x] [data format] decide whether a mutation is called or uncalled mutation in MAF -- check the current MAF to see if there is indication about uncalled events, if not, contact Nick.
- [x] [database] import uncalled mutations with `_uncalled` profile
- [x] [web api] get both called and uncalled mutation profiles on patient view page
- [x] [UI] use light color for the sample label for uncalled events in the mutations table
- [ ] Change pipeline to divide mutations in a uncalled and called txt. Or change importer to do it based on a specific column.

**Comment by jjgao** [comment]
About database, another option is to import the uncalled events in the same mutation table with a different mutation profile. Not sure which more makes more sense.

**Comment by inodb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [cfDNA uncalled indicator](https://trello.com/c/YkmIgRXv/241-cfdna-uncalled-indicator)
