### ISSUE TITLE
random blue color in the header

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2309]
![image](https://cloud.githubusercontent.com/assets/840895/24882426/03e165c2-1e0f-11e7-8544-f8176d1bcd6e.png)

http://www.cbioportal.org/beta/case.do#/patient?caseId=TCGA-BK-A0CC&studyId=ucec_tcga_pub

**Comment by inodb** [comment]
Fixed: https://github.com/cBioPortal/cbioportal-frontend/pull/281
