### ISSUE TITLE
Patient clinical attributes header -- styling issues

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2315]
@jjgao  pointed out some weird color/styling things in the clinical attributes list in the header.  Opening/closing parens different color. Commas with colors etc.  Perhaps discuss with him.

![image](https://cloud.githubusercontent.com/assets/186521/24919782/c07d5e9a-1eb2-11e7-9288-1422b287659a.png)

**Comment by inodb** [comment]
Fixed in: https://github.com/cBioPortal/cbioportal-frontend/pull/281
