### ISSUE TITLE
TS errors associated wtih LazyMobXCache causing builds to fail

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2316]
LazyMobXCache.spec.ts

These tests are throwing TS error.  

You can see them here:
https://travis-ci.org/cBioPortal/cbioportal-frontend/builds/220981598

I wasn't able to see errors locally until i re-installed all node modules.  (delete node_modules, then run npm install).

**Comment by alisman** [comment]
I commented out tests in itnegration branch just to get build green again

**Comment by alisman** [comment]
@adufilie pointed out this issue introduced by update to chai typings (deepEqual).  If we have to work around it, we can just cast the second param of deepEqual as any and that fixes it.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/282
