### ISSUE TITLE
MUTATED protein_change in public portal

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2324]
There are many mutations in the public portal database with protein_change MUTATED for different reasons.

For example: 
- `Splice_Region` or `Splice_Site` mutations
- in `brca_igr_2015_mutations` the tumor_seq_allele was asigned to `NA` for `Frame_shift_del`; 

```
select gp.stable_id, chr, start_position, end_position, reference_allele, tumor_seq_allele, protein_change, mutation_type
from mutation_event me, mutation m, genetic_profile gp
where me.mutation_event_id = m.mutation_event_id
and m.genetic_profile_id=gp.genetic_profile_id
and me.protein_change='MUTATED';
```

**Comment by zheins** [comment]
Before fix attempts:

mysql> select cancer_study_identifier from cancer_study where cancer_study_id in (select cancer_study_id from patient where internal_id in (select patient_id from sample where internal_id in (select distinct sample_id from mutation where mutation_event_id in (select mutation_event_id from mutation_event where protein_change = "MUTATED"))));
116 rows in set (20.51 sec)

Query JJ posted above returns 27447 records.

**Comment by zheins** [comment]
@jjgao I ran a utility to fix this issue. The query you posted above now only returns 2015 records.

There are now only 55 studies that have variants that are "MUTATED".

I can work with @ritikakundra to determine if any of the rest of the studies need to be reannotated/imported. If there are 'NA' values for fields needed to do annotation my utility can't fix them directly in the DB.

**Comment by ritikakundra** [comment]
brca_igr_2015_mutations is fine in the msk portal. Need to update the public with that version.

**Comment by zheins** [comment]
[bad_annotations.txt](https://github.com/cBioPortal/cbioportal/files/959560/bad_annotations.txt)

**Comment by jjgao** [comment]
tracked here https://github.com/cBioPortal/datahub/issues/114
