### ISSUE TITLE
Uploading multiple mutation datasets does not work correctly

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#233]
Description
For one of our studies, we have 3 datasets with mutation data. If you upload a set and use a stable id <studyId>_mutations, the uploaded data works as expected (you get your mutations and the lollipops). If you have more than one set, you have more than one stable id. However, when you deviate from the <studyId>_mutations stable id, the mutation data is not shown.

Steps
Easiest way to see the problem is to take a single mutations dataset. 
First, set the stable id to <studyId>_mytest_mutations and upload the data
The data is not shown properly (no mutation data and lollipops).
Now set the stable id to  <studyId>_mutations and upload the data
The data is shown properly

Expected behaviour
You should be able to upload multiple sets of mutation data. 

The problem may be mutation_details.jsp (DataProxyFactory.getDefaultMutationDataProxy();) and DataProxyFactory.js (servletParams.geneticProfiles = PortalGlobals.getCancerStudyId() + “_mutations";)

Cheers,
Sander

**Comment by jjgao** [comment]
Hi Sander, Dealing with multiple mutation files is tricky. For the moments, is it possible for you to combine the mutation data into one? If not, what is the reason? Thanks.

**Comment by aderidder** [comment]
Hi JJ,

The three sets are:
Complete Genomics DNA Seq
Illumina GAII RNA Seq
Illumina HiSeq2000 RNA Seq
In all three we annotate the data with vcfToMAF (vep81). I discussed it
with someone here and he said combining the two RNA seq probably isn't a
problem, but combining it with the DNA Seq probably is?

Thanks

2015-09-14 18:08 GMT+02:00 JianJiong Gao <notifications@github.com>:

> Hi Sander, Dealing with multiple mutation files is tricky. For the
> moments, is it possible for you to combine the mutation data into one? If
> not, what is the reason? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cBioPortal/cbioportal/issues/233#issuecomment-140127257>
> .
>



-- 
E.   sander@thehyve.nl
T.   +31(0)30 700 9713
W.  www.thehyve.nl

the hyve

**Comment by pieterlukasse** [comment]
Update: for now, we implemented a validation to allow only 1 mutation file per study.
