### ISSUE TITLE
prioritize known drivers over truncating mutations in oncoprint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2335]
In samples with multiple mutations, we still need to prioritize known drivers over truncating mutations.

![image](https://cloud.githubusercontent.com/assets/840895/25009925/5f3b4630-2036-11e7-933f-7d0569bb892e.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2344
