### ISSUE TITLE
use oncokb genes to sort mutations and CNAs tables in patient view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2337]
In the CNAs and Mutations tables, we sort them by the annotation column. When there is nothing in the annotation column, can we sort the genes, ie. OncoKB genes comes first, by default.

This is not urgent.

**Comment by jjgao** [comment]
Maybe the solution is just differentiate oncokb icon for oncokb gene vs non-oncokb genes.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/issues/2365
