### ISSUE TITLE
fix tooltips for CNA and MUT in genomic overview

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2339]

**Comment by adamabeshouse** [comment]
what is the desired behavior? It looks like in production there's no tooltip at all: http://www.cbioportal.org/case.do?cancer_study_id=coadread_tcga_pub&case_id=TCGA-AG-3999

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/311
