### ISSUE TITLE
Cytoband == NULL crashes CNA table

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#2343]
According to the data model, cytoband can be NULL. However, in 552306093e1dcf875b495042a43265c0c626bb7c code was added which gives an error when cytoband is NULL. This causes the CNA table in the Study View to crash.

![screen shot 2017-04-14 at 14 36 40](https://cloud.githubusercontent.com/assets/9624990/25043456/707a8d94-2120-11e7-8408-9291c024a952.png)

**Comment by zhx828** [comment]
@sandertan could you help me review the pull request above? Thanks.
