### ISSUE TITLE
Initial sort column for COSMIC table is broken

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#2346]
Line that needs to be fixed: https://github.com/cBioPortal/cbioportal-frontend/blob/integration/src/shared/components/cosmic/CosmicMutationTable.tsx#L47

(`Occurrence` is misspelled as `Occurence`)

**Comment by adamabeshouse** [comment]
proof of why this should be enum :)

**Comment by onursumer** [comment]
Referencing by a variable string is always unsafe... But, this bug is also a proof of a missing test case :)
