### ISSUE TITLE
3D hotspot difference between production and beta

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2354]
Is 3dhotspot enabled for public website? 

ACE E510K is marked as 3d hotspot in beta but not in production. Checked with the 3dhotspot.org, looks like it is a hotspot. @onursumer could you double check? Thanks.

Production:
http://www.cbioportal.org/case.do?cancer_study_id=skcm_tcga&case_id=TCGA-BF-A1PV

Beta:
http://www.cbioportal.org/beta/case.do?cancer_study_id=skcm_tcga&case_id=TCGA-BF-A1PV#/patient?caseId=TCGA-BF-A1PV&studyId=skcm_tcga

**Comment by onursumer** [comment]
We recently improved hotspot matching logic: https://github.com/cBioPortal/cbioportal-frontend/pull/278. Probably that's why we were missing this mutation in production.
