### ISSUE TITLE
Gistic info vary from beta and production

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2355]
In production, we don't have Gistic info for CDKN2A DeepDel, but in beta we have the info as screenshot
![screen shot 2017-04-17 at 10 51 22 am](https://cloud.githubusercontent.com/assets/5400599/25092484/f83866a6-235b-11e7-923e-34b0d16d3bb3.png)

Production:
http://www.cbioportal.org/case.do?cancer_study_id=skcm_tcga&case_id=TCGA-BF-AAP0

Beta:
http://www.cbioportal.org/beta/case.do?cancer_study_id=skcm_tcga&case_id=TCGA-BF-AAP0#/patient?caseId=TCGA-BF-AAP0&studyId=skcm_tcga

**Comment by onursumer** [comment]
I remember discussing this with @jjgao. This is due to different API data. New API reports more Gistic values than the legacy one. I think there was a bug in the legacy implementation.
