### ISSUE TITLE
mRNA column should be hidden for multi-samples for CNA table (Patient view)

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2357]
https://cbioportal.mskcc.org/beta/case.do#/patient?caseId=P-0002265&studyId=mskimpact

![image](https://cloud.githubusercontent.com/assets/840895/25092694/d901db4a-235c-11e7-8a31-846ca71326b0.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/296

**Comment by jjgao** [comment]
@adamabeshouse this is not only for multi-sample. Single sample that has no mrna data also has the problem. Please make sure it's fixed.

**Comment by adamabeshouse** [comment]
@jjgao done https://github.com/cBioPortal/cbioportal-frontend/pull/305
