### ISSUE TITLE
COSMIC info are different between production and beta

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2360]
`LRRIQ3	Q245Tfs*7 ` only counted with 1 occurrences in beta but 4 in production.

Cosmic ID: http://cancer.sanger.ac.uk/cosmic/mutation/overview?id=1344232

Production:
http://www.cbioportal.org/case.do?cancer_study_id=skcm_tcga&case_id=TCGA-D3-A1Q1

Beta:
http://www.cbioportal.org/beta/case.do?cancer_study_id=skcm_tcga&case_id=TCGA-D3-A1Q1#/patient?caseId=TCGA-D3-A1Q1&studyId=skcm_tcga

**Comment by onursumer** [comment]
Look like legacy code was matching `LRRIQ3 Truncating Q245Tfs*7` to a `LRRIQ3 Truncating K244fs*17` mutation. Refactored code, however, is matching the same mutation to `LRRIQ3 Truncating Q245fs*7`. Now we are matching COSMIC by position. (Legacy was matching 245 to 244)

@jjgao any comments?
