### ISSUE TITLE
Variant allele frequency is calculated differently between production and beta

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2361]
Production:
http://www.cbioportal.org/case.do?cancer_study_id=lgg_ucsf_2014&case_id=P01
![screen shot 2017-04-17 at 11 29 21 am](https://cloud.githubusercontent.com/assets/5400599/25093673/4f02b838-2361-11e7-9347-4b811479bdd1.png)

Beta:
http://www.cbioportal.org/beta/case.do?cancer_study_id=lgg_ucsf_2014&case_id=P01#/patient?caseId=P01&studyId=lgg_ucsf_2014
![screen shot 2017-04-17 at 11 29 45 am](https://cloud.githubusercontent.com/assets/5400599/25093687/56b1137c-2361-11e7-9ee8-5b43f12416fb.png)

**Comment by adamabeshouse** [comment]
I believe this is fixed now. The curves still look different, but I actually think the new one makes more sense...it seems like just a difference of bandwidth for the kernel density estimation.
![image](https://cloud.githubusercontent.com/assets/636232/25107474/9a393b24-239d-11e7-92eb-296a011c9fb5.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/297

**Comment by adamabeshouse** [comment]
nevermind, it was broken, because of the case where tumorAltCount or tumorRefCount = -1

here it is now:
![image](https://cloud.githubusercontent.com/assets/636232/25156360/08666476-2468-11e7-9ea8-6df039c62b9c.png)
