### ISSUE TITLE
Question about downloaded file of mutations table

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2363]
In downloaded file, we don't put in data we get from other resources like `Allele Feq`, `Annotation`, `COSMIC` etc. Should we remove the header for those columns as well? @jjgao @alisman 

Link: http://www.cbioportal.org/beta/case.do?cancer_study_id=lgg_ucsf_2014&case_id=P04#/patient?caseId=P04&studyId=lgg_ucsf_2014

File: [table.txt](https://github.com/cBioPortal/cbioportal/files/925971/table.txt)

**Comment by onursumer** [comment]
@jjgao @zhx828 I think it is a good idea to have the cosmic count in the downloaded file, I will add a download function for that column.

**Comment by alisman** [comment]
@onursumer is this done?

**Comment by onursumer** [comment]
I just fixed the cosmic count download value, but we never concluded whether we should remove the headers or not. So, the question is still open :)

**Comment by alisman** [comment]
@onursumer i suppose we don't know based on initial column data whether the column is async?  I mean, if we did, this would be easy, right?

**Comment by alisman** [comment]
@jjgao @ecerami can you comment on this?

**Comment by alisman** [comment]
@onursumer is it possible to do this easily?  that is, do we know whether a column is async or not? If so, then lets hide them.

**Comment by onursumer** [comment]
I still have mixed feelings about this issue... For now we can simply hide the columns which do not implement the `download` function.

Ideally we should find a better way to deal with `async` columns. But that is not trivial at this point.

**Comment by jjgao** [comment]
duplicate with #2672
