### ISSUE TITLE
make MSKTable sort a stable sort

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#2365]

**Comment by adamabeshouse** [comment]
zip list with positions

**Comment by fedde-s** [comment]
Something I noticed: looks like the second argument to the callback of `Array.prototype.map()` is a nice tool to transform an array of anythings into an array of `(preSortIndex, anything)` tuples.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/302/files
