### ISSUE TITLE
use discretecnacache for CNA table

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#2367]

**Comment by onursumer** [comment]
@adamabeshouse Is this for lazy loading the entire table data?

**Comment by adamabeshouse** [comment]
yeah well the idea would be to load all the table data and use it for the mutations. that way we don't double-load data

**Comment by adamabeshouse** [comment]
actually, we should just load the CNA data into the cache - that would work better for our purposes, and we can do that with `LazyMobXCache#addData`.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/301
