### ISSUE TITLE
New patient view: oncokb tooltip not readable, rendered on wrong place

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2368]
steps to reproduce:

1- Go to http://www.cbioportal.org/beta/case.do#/patient?caseId=06-081&studyId=prad_fhcrc
2- scroll down to CNA items at the bottom of the page. 
3- hover over one of the items (see screenshot)

![image](https://cloud.githubusercontent.com/assets/2900303/25123835/0f4a8d00-242a-11e7-8456-effbaa21e312.png)

Interestingly, next time I hover with the mouse over the icons, the tooltip is displayed correctly. So it seems to happen only at the first time it is called. See screenshot:

![image](https://cloud.githubusercontent.com/assets/2900303/25123896/41f40448-242a-11e7-8075-075e02f5f511.png)

**Comment by sandertan** [comment]
Also appears to happen in the mutation table. First hover:

<img width="1280" alt="screen shot 2017-04-18 at 13 42 22" src="https://cloud.githubusercontent.com/assets/9624990/25129110/e9a93db8-243c-11e7-8cfa-80cc56e5092c.png">

Second hover:

<img width="1280" alt="screen shot 2017-04-18 at 13 42 26" src="https://cloud.githubusercontent.com/assets/9624990/25129117/ef6e82d0-243c-11e7-8fd8-eded179f6e93.png">

**Comment by onursumer** [comment]
@jjgao @pieterlukasse I don't think this one is critical. It is **readable** if you scroll down. It is just a positioning issue due to lazy loading of the data.

**Comment by pieterlukasse** [comment]
@onursumer I wasn't able to scroll down...then the tooltip disappears.

**Comment by onursumer** [comment]
@pieterlukasse you are right, you also need to be hovering on the card itself while scrolling down to prevent it from disabling.

No matter what, we need to fix the positioning issue. I just don't think it is critical at the moment though.
