### ISSUE TITLE
Mutation API client needs to be updated

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#2371]
As well as the corresponding API call which retrieves the mutation data.

**Comment by adamabeshouse** [comment]
Im almost done doing this

**Comment by alisman** [comment]
awesome!

**Comment by onursumer** [comment]
Thanks Adam!

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/300
