### ISSUE TITLE
Validator Flexibility and Issues

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2374]
Following are a few issues that the Validator either needs to allow the validation for or just show a warning rather than failure:

1. Allow values like 1.5 or -1.5 in data_CNA.txt.
2. Should not fail if Validation Status is Unknown (same goes for mutation status). Maybe make it a warning.
3. meta_fusion should allow stable id to be mutations instead of fusion. If not, then importer should not fail.
4. CNA files should be allowed to have an additional column of cytoband other than hugo_symbol and Entrez_gene_id.
5. Just a suggestion: Can the validator run completely clinical files don't have meta headers?
6. Fails when values are null or NA.

**Comment by fedde-s** [comment]
File-Formats.md does not document what the biological meaning of these values would be, and what cBioPortal should do when encountering them. So we'd have to make sure that the importer will load them into the database a way that the portal (and programmers) know how to deal with, before we adjust the validator to allow them through to the loader.

**Comment by fedde-s** [comment]
As for clinical data files that do not define the metadata of their attributes: unfortunately this is no longer possible since the changes in https://github.com/cBioPortal/cbioportal/pull/1746 now require each study to define its own attributes, and studies can no longer reuse attributes previously defined by other studies.

**Comment by fedde-s** [comment]
And could you clarify your point about NA values? The validation script already approves various representations of missing values that are known not to break the loader or the portal, such as the value `NA` in most columns of most genetic data files, and the phrases `[Not Applicable]`, `[Not Available]`, `[Pending]`, `[Discrepancy]`, `[Completed]`, `[null]`, `NA` and blank columns in clinical data.

**Comment by fedde-s** [comment]
If generating the metadata comments for clinical data files is difficult in your setup, might it perhaps be useful to define a format for some separate study data file that holds the information? It has not been enough of an issue for us so far to spend time on working it out, but that could simplify the minimal clinical data file file format.

**Comment by fedde-s** [comment]
Given that my questions for clarification have been unanswered for over a year, I'll assume that this is no longer an issue.
