### ISSUE TITLE
study view "reset all" not always working 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2376]
Steps to reproduce:
1- go to http://www.cbioportal.org/study?id=gbm_tcga#summary
2- select "with mutation data"= YES
3- select from "mutation count" range (see screenshot)
4- then click reset all. In some cases this will not reset the selected samples (it removes the filter "crumbs" though)
5- alternatively repeat step 2 many times (clicking many times on YES part of pie chart). Then try step 3. It will in some cases fail to render the selection from step 3 (see second screenshot)
![image](https://cloud.githubusercontent.com/assets/2900303/25176372/3410aef6-24fe-11e7-8e54-40bdbb16ff86.png)

![image](https://cloud.githubusercontent.com/assets/2900303/25176696/5d892000-24ff-11e7-883d-952f7f6981f9.png)

**Comment by pieterlukasse** [comment]
@zhx828

**Comment by pieterlukasse** [comment]
Cannot reproduce anymore.

**Comment by pieterlukasse** [comment]
@jjgao the pie chart "with mutation" is gone. Is this expected?

**Comment by zhx828** [comment]
@pieterlukasse yes. It has been transformed to a the quick filter
![Screen Shot 2019-06-25 at 11 10 09 AM](https://user-images.githubusercontent.com/5400599/60110289-ddb3f800-9739-11e9-8e96-b704d8b9b63d.png)

**Comment by pieterlukasse** [comment]
Ok, thanks. Seems to be working fine :+1:
