### ISSUE TITLE
OncoKB search getting called with no queryVariants (from cna table)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2379]
This causes service to return 500 and error dialog to show.  I silenced it with onError in the promise

**Comment by onursumer** [comment]
I think this is because we try to fetch OncoKB search data even if discrete CNA data result is empty.

**Comment by alisman** [comment]
Yes, this should be fixed by me latest PR

**Comment by onursumer** [comment]
Fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/314
