### ISSUE TITLE
Oncoprint can get really wide on Firefox

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#238]
Same oncoprint shows really wide page on firefox whereas chrome keeps correct formatting:

http://www.cbioportal.org/index.do?cancer_study_list=gbm_tcga&cancer_study_id=gbm_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=gbm_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=gbm_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=gbm_tcga_cnaseq&case_ids=&gene_set_choice=user-defined-list&gene_list=PTEN&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit#or_analysis

FF
![screen shot 2015-09-14 at 1 09 46 pm](https://cloud.githubusercontent.com/assets/1334004/9856329/f53df2f2-5ae1-11e5-96e0-4dfd801a102e.png)

Chrome
![screen shot 2015-09-14 at 1 10 08 pm](https://cloud.githubusercontent.com/assets/1334004/9856334/fccd263c-5ae1-11e5-8b32-b09b0b11667a.png)

**Comment by jjgao** [comment]
Duplicated with #360
