### ISSUE TITLE
Genomic profiles for fusions only do not display properly on portal

### ISSUE THREAD

**Issue by zheins** [cBioPortal/cbioportal#2391]
If the `GENETIC_ALTERATION_TYPE` is not `MUTATION_EXTENDED`, the profile will not display on the portal. We have datasets that only contain `FUSION` data, so calling it this doesn't really make sense. It would probably be better to support this other genetic alteration type.

@jjgao, @n1zea144 what do you think?

**Comment by n1zea144** [comment]
@zheins I agree.  I would support the FUSION GENETIC_ALTERATION_TYPE.
