### ISSUE TITLE
Splice site mutations in OncoPrint shown with wrong color

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2413]
These RB1 splice site mutations should be identified as truncating and likely oncogenic - they should be black.

http://bit.ly/2pTz7lC

![image](https://cloud.githubusercontent.com/assets/11892704/25806690/12293500-33d2-11e7-8c53-28367d2f41b4.png)

**Comment by adamabeshouse** [comment]
This is what I'm getting back from oncoKB about this mutation:
![image](https://cloud.githubusercontent.com/assets/636232/25976872/a610a7ca-3685-11e7-9a41-d800183890d6.png)

**Comment by adamabeshouse** [comment]
@zhx828 do you see anything wrong with my query?

**Comment by zhx828** [comment]
@adamabeshouse I will look into this issue.

**Comment by zhx828** [comment]
@schultzn @adamabeshouse found the issue(https://github.com/oncokb/oncokb/issues/612) I will schedule the fix ASAP.

**Comment by zhx828** [comment]
Issue has been solved in https://github.com/oncokb/oncokb/pull/616
