### ISSUE TITLE
Timeline axis / labels disappear in patient view at some zoom levels

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2417]
Chrome on OS X, zoom level 90%

http://www.cbioportal.org/case.do#/patient?caseId=P04&studyId=lgg_ucsf_2014

![image](https://cloud.githubusercontent.com/assets/11892704/25819876/62502cd4-33fd-11e7-9646-2edf4554b27f.png)

**Comment by jjgao** [comment]
duplicate with #2882
