### ISSUE TITLE
splice mutations not linked to truncating mutations / OncoKB in OncoPrints

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2420]
The RB1 splice site mutations should appear as black in this OncoPrint:
http://bit.ly/2pZv1bD

In the Mutations Tab, they are correctly annotated as known drivers.

**Comment by adamabeshouse** [comment]
I'm sure this is caused by the same thing as https://github.com/cBioPortal/cbioportal/issues/2413

**Comment by adamabeshouse** [comment]
Why do you say they're not linked to truncating? They look to me to be colored as truncating passengers

**Comment by zhx828** [comment]
I think the issue has been solved, similar to #2413 @adamabeshouse could you double check? Thanks.

**Comment by adamabeshouse** [comment]
![image](https://cloud.githubusercontent.com/assets/636232/26170848/d7c921ae-3b10-11e7-9fc6-8654e30fe529.png)

@zhx828 @schultzn confirmed
