### ISSUE TITLE
Stratton signatures in the patient view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2421]
@adamabeshouse just wanted to keep track of this task. We should do it at certain point.

**Comment by ecerami** [comment]
+1 to this idea.

**Comment by adamabeshouse** [comment]
@zheins maybe you could help with the backend side of this, integrating this https://github.com/mskcc/mutation-signatures into the import pipeline, writing the results into a new table?

**Comment by jjgao** [comment]
@jxu8 or @zhx828 could you adding the links to all the related pull request here?

**Comment by jxu8** [comment]
Hi JJ, 
Here is the one in the cbioportal repo:
https://github.com/cBioPortal/cbioportal/pull/4392

Here is the merged one in the cbioportal-frontend repo:
https://github.com/cBioPortal/cbioportal-frontend/pull/1287

**Comment by jjgao** [comment]
@jxu8 thanks.

**Comment by zhx828** [comment]
This is a duplicate issue of #5571. Should we close? @jjgao
