### ISSUE TITLE
enhance oncoprint filtering

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2422]
Thinking of have a new dropdown `Filter` in the oncoprint menu so that we can filter the oncoprint (initially maybe just mutations), for exmaple:

1. by mutation type
1. by position
1. by driver vs passenger
1. by somatic vs germline

**Comment by adamabeshouse** [comment]
yeah, like an "advanced filter" interface, like you'd have on seamless for filtering restaurants?

**Comment by adamabeshouse** [comment]
this isn't really "filtering", its coloring, right?

**Comment by adamabeshouse** [comment]
sure. so that would be instead of by type? so radio: type, germline vs somatic, none

**Comment by jjgao** [comment]
Maybe we can add another option in addition to `Type` and `Putative drivers based on`.

"Mutation status" => by default, select both "Somatic" and "Germline". And provide an option to "Hide germline"?

Or maybe we don't need this any more once we have germline/somatic in oql? @schultzn

**Comment by schultzn** [comment]
I think a user should be able to show either germline, or somatic, or both.

**Comment by adamabeshouse** [comment]
Im confused - do we want to be able to not see/sort by germline status? or just to be able to hide by germline status? or both?

**Comment by jjgao** [comment]
@adamabeshouse: I had some discussion with Niki. We would like to make some change to the Mutation Color menu.

- [ ] change "Mutation Color" to "Mutations"
- [ ] have two section in the dropdown: "Color by" and "Filter"
- [ ] have three options in "Color by" section: "Type", "Somatic vs Germline", "Putative drivers vs VUS", all selected by default.
- [ ] have two options in "Filter" section: "Show VUS", "Show germline mutations", all selected by default

**Comment by adamabeshouse** [comment]
sounds good. so dont add "Somatic vs Germline" to the Sort menu?

**Comment by jjgao** [comment]
@schultzn do you see any use case to sort by "Somatic vs Germline"?

![image](https://user-images.githubusercontent.com/840895/49617550-0e416980-f983-11e8-9311-fa10e8c32b6e.png)

**Comment by schultzn** [comment]
Hmm… maybe. We could prioritize germline vs somatic (spot by germline first, then somatic), vs mix them (sort by alterations in other genes and ignore mutation status).

**Comment by adamabeshouse** [comment]
is it starting to be weird to have sort and color completely parallel in different menus? now that theres 3 items its starting to seem a lot to me
