### ISSUE TITLE
svgtopdf.do Internal Server Error in mskcc portal downloading oncoprint

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#243]
In the MSKCC portal, trying to download an oncoprint pdf elicits a 500 error (visible in the console)

https://cbioportal.mskcc.org/index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit

**Comment by jjgao** [comment]
Seems working now.

**Comment by adamabeshouse** [comment]
Weird.. @schultzn is it working for you now too?

**Comment by adamabeshouse** [comment]
Could not replicate
