### ISSUE TITLE
TCGA GBM 2008 study doesn't have mutations genomic profile option

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2432]
When querying GBM Nature 2008 TCGA study, there are options for copy number and expression but not for mutations:
![image](https://cloud.githubusercontent.com/assets/10508276/25968647/4fc9a68e-3660-11e7-8aa9-1443da578446.png)

@ecerami and I investigated and it appears that the genomic profile for mutations is set to not show for some reason:
![image](https://cloud.githubusercontent.com/assets/10508276/25968782/ac4d9d5c-3660-11e7-9377-8486ab03288e.png)

@ritikakundra I think you might already be working on this, but wanted to have a record of it.

**Comment by ritikakundra** [comment]
@tmazor : I have fixed this. Privatel portal shows the mutations profile. Will be pushing it to public portal soon.

**Comment by tmazor** [comment]
Awesome! Thanks @ritikakundra!
