### ISSUE TITLE
Patient View - clinical data search error

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#2433]
Looks like if I use the search field to look for an attribute that does not exist, I cannot get back to the original attribute list if I clear the search field without having to reload the page or click on the clinical data tab.  Maybe this is how its suppose to work?

![image](https://cloud.githubusercontent.com/assets/366003/26008684/d0aa1c94-3713-11e7-8205-c424ea75209b.png)

**Comment by jjgao** [comment]
Looks like it's not working at all.

**Comment by jjgao** [comment]
@inodb maybe you can help with this?

**Comment by inodb** [comment]
Looks already fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/357

**Comment by alisman** [comment]
Yes, fixed.  We need to get it out in hotfix.
