### ISSUE TITLE
possible data issue for case lists of msk_impact_2017

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2440]
for msk_impact_2017, we ahe 10945 samples for case lists _sequenced and _cna, but only 10944 for _cnaseq. Could you check if the data is correct?

![image](https://cloud.githubusercontent.com/assets/840895/26079086/8ac6c14a-398f-11e7-8a16-53c83f2c4cb3.png)

**Comment by ritikakundra** [comment]
@zackheins This sample is not being counted in CNA caselists but is in the CNA file:http://www.cbioportal.org/case.do#/patient?caseId=P-0012622&navCaseIds=P-0012622&studyId=msk_impact_2017
