### ISSUE TITLE
Add Chart search function on Study View should not be case-sensitive

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2443]
I think the Add Chart search function on the Study View is currently case-sensitive - and it should probably not be.

**Comment by zhx828** [comment]
@schultzn The search box is case-insensitive. But it does have an issue that the result will be incorrect if you have space in your keywords. I will fix that. Could you give me an example which made you think this is case-sensitive?

**Comment by schultzn** [comment]
I think it had to do with spaces - thanks!

**Comment by zhx828** [comment]
Thanks Niki. Just verified this issue has been solved.
