### ISSUE TITLE
patient view isn't showing data from second sample

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2457]
I pulled up all patients with multiple samples from the LGG Provisional TCGA and it appears that mutations & copy number calls from the second sample aren't being displayed
![image](https://cloud.githubusercontent.com/assets/10508276/26211589/cb666a2e-3bc0-11e7-9a58-fdb5a5b696a5.png)

There's a copy number track up top for the second sample, but there isn't a mutation track for the second sample. In the mutation & copy number lists, there are only calls from the first sample. I'm seeing this same problem in all patients with multiple samples in this dataset. 

This is happening in some but not all other datasets. Patients with multiple samples from the GBM Provisional dataset have a similar problem, although sometimes only the mutations from the second tumor appear and sometimes it's only the mutations from the first one. Meanwhile, patients with multiple samples in the UCSF LGG dataset looks to be totally fine.

In discussing this with @Tamba32 and @ersinciftci, it appears that the underlying data (mutations & copy number calls in the second sample) are missing from the data table, which is why it doesn't show up.

**Comment by jjgao** [comment]
@ritikakundra could you look into this case when you have time? Not urgent.

**Comment by ritikakundra** [comment]
@jjgao I checked the re-annotated maf, as well as the published version and both, don't have the 02 sample in the genomic file. Is there any other place to verify?

**Comment by jjgao** [comment]
@ritikakundra maybe it's in other data files?

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #277](https://github.com/cBioPortal/datahub/issues/277) via [**ZenHub**](https://www.zenhub.com/)
