### ISSUE TITLE
If type_of_cancer for a study does not exists, query page breaks

### ISSUE THREAD

**Issue by zheins** [cBioPortal/cbioportal#2459]
If after updating the `type_of_cancer` table a `type_of_cancer_id` no longer exists that a current study is using, the query page study selector breaks.

An error can be seen in the console:

`java.lang.RuntimeException: Cancer type record not found for: all
    org.mskcc.cbio.portal.servlet.PortalMetaDataJSON.doGet(PortalMetaDataJSON.java:247)
...`

While this is a data issue that should be fixed in the db level when it occurs, it might be good to put in some checks for this situation so that the query page doesn't entirely break due to one study having an invalid type of cancer.

**Comment by jjgao** [comment]
@zheins not sure about the solution here. If we have a database dependency, is it even possible to remove a type_of_cancer of cancer that a study is linked to?

**Comment by ersinciftci** [comment]
Not sure about the solution either, I guess you shouldn't be able to delete a type if it's referred by a study? just like @jjgao said.

**Comment by jjgao** [comment]
If a manually step is necessary in this case, we should document it.

The ideal solution is that, when a node a changed in OncoTree, the OncoTree API should have a history so that cBioPortal can know what changes to apply. Then we can try to automated it.

cc'ing @n1zea144 as well.

**Comment by ersinciftci** [comment]
Unassigning myself, not sure if it's still a valid issue.
