### ISSUE TITLE
Validator: data_CNA should allow 1.5 and -1.5 values

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2461]
For the public study: msk_impact_2017, validator should not throw an error for decimal vale of 1.5 and -1.5
![screen shot 2017-05-18 at 8 52 28 pm](https://cloud.githubusercontent.com/assets/12007862/26228964/fb8dabb8-3c0b-11e7-99cc-27acb7295bdd.png)

**Comment by pieterlukasse** [comment]
can you motivate this further? Thanks.

**Comment by pieterlukasse** [comment]
@sandertan could you follow-up on this one after @ritikakundra has added some more details about why this is needed?

**Comment by ritikakundra** [comment]
Values 1.5 and -1.5 are part of many CNA datasets and are considered as AMP and Del by the portal. We don't want to manipulate the data manually for the validator to pass, rather have it as a warning.

**Comment by pieterlukasse** [comment]
solution: we document 1.5 as valid value. Change validator accordingly (so no warnings, no errors).

**Comment by sandertan** [comment]
This has been merged to hotfix, and is in master 1.7.3
