### ISSUE TITLE
Validator: meta_fusions should either allow fusion or mutations in stable ID

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2462]
The file formats for meta_fusion has stable_id as mutations but validator fails unless it says fusion. Importer fails to import fusion data when stable_id fusion.
![screen shot 2017-05-18 at 8 58 33 pm](https://cloud.githubusercontent.com/assets/12007862/26229083/047174ac-3c0d-11e7-8b8b-2ac1f25a3262.png)

**Comment by pieterlukasse** [comment]
Yes, should be lower case "fusion". The importer still needs some updates, like https://github.com/cBioPortal/cbioportal/issues/1314, https://github.com/cBioPortal/cbioportal/issues/1102

**Comment by pieterlukasse** [comment]
Bug in loader?

**Comment by fedde-s** [comment]
At some point, a decision was made to only support the stable ID ‘fusion’, as reflected in commit aee9eb0c3ad9722e6ff450de53dd9d25f7427403. I vaguely remember that the reasoning behind this was that, while the database does store the two types of data in the same profile, this was a behind-the-scense implementation detail that might potentially change in the future.

**Comment by fedde-s** [comment]
The reasoning I mentioned was clarified in this comment last year: https://github.com/cBioPortal/cbioportal/pull/1438#issuecomment-229983745

**Comment by sandertan** [comment]
@ritikakundra this one is also merged to hotfix and in 1.7.3
