### ISSUE TITLE
Validator: TCGA has many different file types which are not defined in file formats

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2464]
The validator will fail if it finds files not defined in our file formats. Maybe this becomes a warning instead of error.
ov_tcga_pub:
![screen shot 2017-05-18 at 9 18 05 pm](https://cloud.githubusercontent.com/assets/12007862/26229474/f22cd216-3c0f-11e7-9d0d-832e402aabfc.png)

**Comment by pieterlukasse** [comment]
can you share the specific errors in this case?

**Comment by ritikakundra** [comment]
Checking on all the files which are not part of the file formats in the database

**Comment by pieterlukasse** [comment]
solutions: filter out legacy files from datahub. Add a new flag to validator to give warning instead of error if flag is turned on.

**Comment by sandertan** [comment]
@ritikakundra do you have an updated version of `ov_tcga_pub`? I don't get as much green in the validation report as you do...

**Comment by ritikakundra** [comment]
@sandertan https://github.com/cBioPortal/datahub/pull/77

**Comment by sandertan** [comment]
![screen shot 2017-08-29 at 16 24 27](https://user-images.githubusercontent.com/9624990/29826112-b5bf7c58-8cd6-11e7-8f83-0e75fc623e5e.png)

Do we want to ignore these files, or load them? It shouldn't be too difficult to modify the validator and importer to load them right?

@pieterlukasse @n1zea144

**Comment by pieterlukasse** [comment]
I will check with @sandertan
