### ISSUE TITLE
Validator: Verification and Validation if NA, validator fails

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2465]
Validator fails when MAF is NA for Verification and Validation Status. 
![screen shot 2017-05-18 at 9 35 06 pm](https://cloud.githubusercontent.com/assets/12007862/26229787/2bca776a-3c12-11e7-9a1c-053f12613699.png)

**Comment by sandertan** [comment]
Hi Ritika,

I fixed this in https://github.com/cBioPortal/cbioportal/pull/2221. The code change is in master since 1.5.1 or 1.60. So if you update, this should be fine. Can you try it out and close this issue if it's working?

Sander

**Comment by ritikakundra** [comment]
@sandertan Are you still failing for other text like Unknown or something we use internally a lot REDACTED?

**Comment by sandertan** [comment]
@ritikakundra These are currently the allowed values ([source](https://github.com/cBioPortal/cbioportal/blob/9add92df0bb333296e24d168b2aae74a37465062/core/src/main/scripts/importer/validateData.py#L1187)):

Verification_Status: verified, unknown, na
Validation_Status: untested, inconclusive, valid, invalid, na

The validator is case insensitive for these values, so Unknown is allowed for Verification_Status

I can add Redacted to the list of values for Validation_Status. [This](https://github.com/cBioPortal/cbioportal/blob/c628bfc06e0f7446b4c2a51892f7acc8b6087325/core/src/main/java/org/mskcc/cbio/portal/scripts/MutationFilter.java#L127) part of the code rejects these from the database.

**Comment by ritikakundra** [comment]
@sandertan Yes please add them. This is part of the nomenclature for many of our studies.

**Comment by jjgao** [comment]
@ritikakundra I am closing these old thread about validator. If any of them are still there, please reopen.
