### ISSUE TITLE
Validator: TCGA IDS are different in different genomic files

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2467]
Some studies will have short TCGA IDs and some full Ids with trailing strings. Need to figure
![screen shot 2017-05-18 at 10 04 46 pm](https://cloud.githubusercontent.com/assets/12007862/26230331/0802f3a8-3c16-11e7-9c4a-1861ef343c93.png)
 out what is the best way to tackle it.

**Comment by pieterlukasse** [comment]
I think we should write a simple clean-up step to get all sample ids in the same shape, e.g. :
 `TCGA-02-0001-01`

**Comment by pieterlukasse** [comment]
actions: harmonize the barcodes and removing normal samples (maybe @yichaoS can help)
