### ISSUE TITLE
Data base schema import failure

### ISSUE THREAD

**Issue by cbio1** [cBioPortal/cbioportal#2478]
hi,

I am truly amazed by your work of cbioportal!

Just tried to install the local copy. followed every steps and tried to import the database schema. and it reported
ERROR 1071 (42000) at line 321: Specified key was too long; max key length is 767 bytes
hacked the .sql file 
![image](https://cloud.githubusercontent.com/assets/28907745/26375439/91baf1d4-3fce-11e7-91d4-ab1d8d416057.png)
by reducing the varchar(400) to varhar(255) and it worked.

hopefully this hack wont damage the whole system after they are installed?

thanks!

**Comment by jjgao** [comment]
Looks like Innodb has a limitation on that.

https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by cbio1** [comment]
Thanks jjgao.

While I continued the configuration, i found two versions of the schema sql import file:

one is the current repo's version:
https://github.com/cBioPortal/cbioportal/blob/master/db-scripts/src/main/resources/cgds.sql

another one is referenced in the installation doc page:
https://cbioportal.readthedocs.io/en/latest/Docker-Prerequisites.html

which does provide a varchar(255) version of the mutation_event table:
https://raw.githubusercontent.com/cBioPortal/cbioportal/v1.3.1/core/src/main/resources/db/cgds.sql

Hope this helps!

**Comment by sheridancbio** [comment]
Yes, if you are using a mysql configuration with character encoding UTF8 then varchar(255) is the longest key element allowed. In our production databases we currently are using varchar(255) for TUMOR_SEQ_ALLELES because we switched to UTF8 encoding recently. We had an issue with long discussion of this topic ( #1801 ). I see that that issue was closed and I was supposed to create a new issue to track the update of the database installation documentation to carefully explain all the options to installers. I'll check the documentation and create that issue (or alter this issue so that what is needed is spelled out here)

**Comment by fedde-s** [comment]
I'm running into this issue as well, when I run the latest mysql:8.0 [from Docker Hub](https://hub.docker.com/_/mysql/). I could work around it by reverting to mysql:5.7 for now, but we should solve it eventually.

**Comment by fedde-s** [comment]
For completeness, I'm using the latest seed DB from Datahub, not the outdated ones you linked.

**Comment by fedde-s** [comment]
Could we change `cgds.sql` to use a `varchar(255)`, if that's the solution? Maybe even in v1.13.1 or v1.14.0, since it is a bugfix?

**Comment by fedde-s** [comment]
If it's too much for v1.13.1, we should probably add a warning that we only support MySQL up to 5.7.x for now, to both the system requirements page and the page on loading the seed db.

**Comment by jjgao** [comment]
@fedde-s good point. Could you add it to the document?

**Comment by fedde-s** [comment]
@jjgao and @sheridancbio, I suggested some documentation to keep people from running into this issue in #4333.

**Comment by jjgao** [comment]
@fedde-s thank you.

**Comment by fedde-s** [comment]
A recommendation to use MySQL 5.7 or lower, in which utf8 was not the default encoding, is now documented in the documentation of the `master` development branch and will be included in the next (minor) release. This, I believe, will fix the critical part of the issue. Do reopen or comment if you have a different perspective.
