### ISSUE TITLE
Sample study import failed

### ISSUE THREAD

**Issue by cbio1** [cBioPortal/cbioportal#2479]
hi,

I am truly amazed by your work of cbioportal!

Just tried to install the local copy. followed every steps and tried to import the sample study and got:
Warnings / Errors:
-------------------
0.  CDKN2AP14ARF in the cbio cancer gene list config file [resources/cbio_cancer_genes.txt] is not a HUGO gene symbol. You should either update this file or update the `gene` and `gene_alias` tables to fix this.; 1x
1.  CDKN2AP16INK4A in the cbio cancer gene list config file [resources/cbio_cancer_genes.txt] is not a HUGO gene symbol. You should either update this file or update the `gene` and `gene_alias` tables to fix this.; 1x
2.  EGFRVIII in the cbio cancer gene list config file [resources/cbio_cancer_genes.txt] is not a HUGO gene symbol. You should either update this file or update the `gene` and `gene_alias` tables to fix this.; 1x

i couldnt find the mentioned cbio_cancer_genes.txt file.
Do I have to pass this step in order to make the system work?

thanks!

**Comment by jjgao** [comment]
@cbio1 please don't worry about these errors. These are special gene symbols we use here internally.

**Comment by cbio1** [comment]
i just realized that these are not fatal errors and they are just warnings.  Thanks!
