### ISSUE TITLE
Current public portal has samples with ID: `--normal-id`

### ISSUE THREAD

**Issue by armish** [cBioPortal/cbioportal#248]
Realized this when looking at [this cross-cancer query](http://www.cbioportal.org/cross_cancer.do?cancer_study_list=&cancer_study_id=all&data_priority=1&case_ids=&gene_set_choice=user-defined-list&gene_list=BHLHE41&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit#crosscancer/overview/1/BHLHE41/sarc_mskcc%2Csarc_tcga%2Cacc_tcga%2Cchol_jhu_2013%2Cchol_nccs_2013%2Cchol_nus_2012%2Cblca_bgi%2Cblca_mskcc_solit_2012%2Cblca_mskcc_solit_2014%2Cblca_tcga%2Cblca_tcga_pub%2Cmm_broad%2Ccoadread_genentech%2Ccoadread_mskcc%2Ccoadread_tcga%2Ccoadread_tcga_pub%2Clgg_tcga%2Cpcpg_tcga%2Cbrca_bccrc%2Cbrca_bccrc_xenograft_2014%2Cbrca_broad%2Cbrca_sanger%2Cbrca_tcga%2Cbrca_tcga_pub%2Ccesc_tcga%2Cescc_icgc%2Chnsc_broad%2Chnsc_jhu%2Chnsc_tcga%2Chnsc_tcga_pub%2Cnpc_nusingapore%2Clihc_amc_prv%2Clihc_riken%2Clihc_tcga%2Csclc_clcgp%2Csclc_jhu%2Ccellline_ccle_broad%2Ccellline_nci60%2Cpaad_icgc%2Cpaad_tcga%2Cprad_broad%2Cprad_broad_2013%2Cprad_mich%2Cprad_mskcc%2Cprad_mskcc_2014%2Cprad_mskcc_cheny1_organoids_2014%2Cprad_su2c_2015%2Cprad_tcga%2Cprad_tcga_pub%2Cthca_tcga%2Cthca_tcga_pub%2Cucec_tcga%2Cucec_tcga_pub%2Claml_tcga%2Claml_tcga_pub%2Cmbl_broad_2012%2Cmbl_icgc%2Cmbl_pcgp%2Cmpnst_mskcc%2Cesca_broad%2Cesca_tcga%2Cstad_pfizer_uhongkong%2Cstad_tcga%2Cstad_tcga_pub%2Cstad_uhongkong%2Cstad_utokyo%2Cacyc_mskcc%2Ckirc_bgi%2Ckirc_tcga%2Ckirc_tcga_pub%2Cluad_broad%2Cluad_tcga%2Cluad_tcga_pub%2Cluad_tsp%2Clusc_tcga%2Clusc_tcga_pub%2Cscco_mskcc%2Cskcm_broad%2Cskcm_broad_dfarber%2Cskcm_tcga%2Cskcm_yale%2Cucs_tcga%2Cgbm_tcga%2Cgbm_tcga_pub%2Cgbm_tcga_pub2013%2Ckirp_tcga%2Ckich_tcga%2Ckich_tcga_pub%2Cdlbc_tcga%2Cov_tcga%2Cov_tcga_pub):

![image 2015-09-15 at 3 42 18 pm](https://cloud.githubusercontent.com/assets/7809/9887988/81aaf256-5bc0-11e5-9574-28b840e72b0f.png)

looks like all of these are coming from TCGA studies; so I assume it has something to do with the importer code (cc: @jjgao @n1zea144)

**Comment by jjgao** [comment]
I've manually fixed the database. We need to look into the cause.

**Comment by armish** [comment]
Just came across this post during a random search on BioStars: http://www.cbioportal.org/case.do?sample_id=Val.Stat&cancer_study_id=luad_tcga

Seems relevant.
