### ISSUE TITLE
Non-oncogenic mutations in cancer (oncokb) gene should have a high priority

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2480]
For example, in this case, the EGFR mutation should be displayed in the first page.

http://www.cbioportal.org/case.do#/patient?caseId=TCGA-50-5066&studyId=nsclc_tcga_broad_2016

We should use a slightly different icon for VUS in cancer genes V.S. VUS in other genes.

**Comment by pieterlukasse** [comment]
@oplantalech FYI - this is relevant to know when sorting the entries in new patient view.
