### ISSUE TITLE
Fail to load portal if authorization and authentication are invalid

### ISSUE THREAD

**Issue by mandawilson** [cBioPortal/cbioportal#2485]
Examine the portal.properties for authorization and authentication when the application loads and log / exit if they are improper, e.g. authorization=true and authenticate=false.  Maybe in ServletContextListener.contextInitialized() --- apparently if you throw a runtime exception in this method it stops the deployment of the web application.  Currently when authorization=true and authenticate=false the portal throws an exception on the study page, but not on the homepage so someone might deploy the portal and not realize right away that there is a problem.

See #2483 for more information.

@sheridancbio @pieterlukasse

**Comment by sheridancbio** [comment]
Some options:

1. the most general approach would be to develop a configuration validator which had a set of rules to model and test the space of configuration choices for the portal. If a configuration was invalid, then on deployment the portal would only show a page reporting the validation results.
1. an easier approach would be (as suggested in the description of this issue) to do a partial detection of mis-configuration (starting with just this one improper combination, or maybe scanning the properties file for other setting combinations which were improper). If a problem was detected, we could throw an exception during startup to prevent the launch of the web application.
1. a kludgy "fix" would be to force (during property parsing/loading or at webapp initialization) authenticate to be true any time authorization were set as true.
1. a slightly better fix would be to combine these two properties into one, which had three levels to choose from for the "securityPolicy" : {"allVisitorsHaveFullAcccess", "authenticatedUsersHaveFullAccess", "usersHaveAccessByAuthentication"}
1. perhaps the easiest way forward would be to put a comment in the properties file : "Don't set authorization to true unless you also set authenticate to true", or to make a guide explaining how to configure the application.

In any case, it seems likely that there are other configuration option settings (or combinations) which could cause trouble.

**Comment by jjgao** [comment]
@mandawilson @sheridancbio should we keep this open?
