### ISSUE TITLE
Variant allele frequencies in the patient view should always show two digits

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2490]
Variant allele frequencies in the patient view should always show two digits:

In this example, two variants show 0.3 and 0.5, respectively, when 0.30 and 0.50 would be better, to match the other entries in the column:
https://cbioportal.mskcc.org/case.do#/patient?sampleId=P-0012922-T01-IM5&studyId=mskimpact

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/391
