### ISSUE TITLE
mRNA microarray column values blank instead of 0

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2493]
The reason why the mRNA microarray column shows up blank instead of zero is that the property mrnaMicroarraySampleCount does not exist in the data (unless it's > 0).  We could handle this in frontend but should it be normalized by api code?

![image](https://cloud.githubusercontent.com/assets/186521/26469204/13b3802c-4167-11e7-8287-61072061f012.png)

@ersinciftci

**Comment by jjgao** [comment]
@alisman let's handle it in the front end. The reason is that they were not profiled with mRNA.
