### ISSUE TITLE
cBioPortal cancer gene list needs some documentation

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2496]
This list needs some documentation:
https://cbioportal.mskcc.org/cancer_gene_list.jsp

How do we define the genes, what are the sources?

And it could be sorted alphabetically. 

We should also call it cBioPortal Cancer Gene List

The tooltip in the patient view that links to this should say: "This table shows cBioPortal cancer genes with 1 or more mutations, as well as any gene with 2 or more mutations", not "This table shows cbio cancer genes with 1 or more mutations, as well as any gene with 2 or more mutations" (cBioPortal instead of cbio)

**Comment by jjgao** [comment]
@zhx828 could you change it in the study view?

@schultzn: maybe we should make this list / table into OncoKB?

**Comment by zhx828** [comment]
@jjgao @schultzn should we remove the page now since we now show all genes?

**Comment by schultzn** [comment]
Yes - for now. But we really need a way to not show all genes by default. It would be nice to have users switch between cancer genes / all genes.

**Comment by jjgao** [comment]
Maybe we can use the oncokb cancer gene to filter the list in the frontend? The user can choose to turn on/off the filter?

**Comment by schultzn** [comment]
Yes, that would be good. It should probably turned on by default, but there should be a visible option for users to change it. Almost like a radio button at the top of the table.

**Comment by jjgao** [comment]
Created another issue to track the cancer genes filtering option: https://github.com/cBioPortal/cbioportal/issues/5716

@zhx828 for the current ticket, please remove the cancer genes page as we will be using OncoKB cancer genes.
