### ISSUE TITLE
Parse splice_region mutation type

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#2497]
We might want to add `splice_region` to the `_mutationStyleMap` in `mutationMappers.js` as **Splice Region**. 

[Splice Region](http://www.sequenceontology.org/miso/current_svn/term/SO:0001902)
A region surrounding a cis_splice site, either within 1-3 bases of the exon or 3-8 bases of the intron.

This differs from [Splice Site](http://www.sequenceontology.org/browser/current_svn/term/SO:0000162):
Consensus region of primary transcript bordering junction of splicing. A region that overlaps exactly 2 base and adjacent_to splice_junction.

This unofficial MAF variant classification type is added by vcf2maf and mentioned in this issue: https://github.com/mskcc/vcf2maf/issues/88#issuecomment-256231861. @ckandoth @jjgao Does anyone of you know what would be best?

![screen shot 2017-05-26 at 14 10 19](https://cloud.githubusercontent.com/assets/9624990/26494030/247c5b20-421d-11e7-8969-57e2220b1275.png)

http://www.cbioportal.org/index.do?cancer_study_list=skcm_tcga&cancer_study_id=skcm_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=skcm_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=skcm_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=skcm_tcga_all&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=ADAMTS6&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

**Comment by pieterlukasse** [comment]
@jjgao @onursumer any thoughts on this?
