### ISSUE TITLE
Pan-Sample Summary Stats

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#25]
As discussed with @schultzn, I / we would like a way to visualize / summarize genomic alterations across multiple cancer types within one study.  For example, if you have a large study (such as MSK-IMPACT or DFCI Profile), there should be a way to enter a gene or gene set, and see the frequency of alterations across all cancer types within that study.  I have gotten this request about 5 times since starting at DFCI, and therefore think it is high priority for us.  Again, not sure of timeline, but my group can volunteer for implementation.  Starting this issue to gather initial feedback.

One thought also is that if one queries across some very large set of samples, e.g. >2K, we replace the OncoPrint tab (which is too slow for this many samples), and replace with a summary stats tab.

**Comment by schultzn** [comment]
Thanks Ethan. I think JJ had a simple idea for this. His workaround was to allow tables of sample counts to also be visualized as bar charts. 

You can then: 
1 - select a gene from the frequency table on the study view (which updates all sample counts to indicate only tumors with a mutation in that gene)
2 - Visualize the tumor counts as a bar chart.

N
