### ISSUE TITLE
OncoKB sorting is not working for this case

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2504]
https://cbioportal.mskcc.org/case.do?cancer_study_id=mskimpact&sample_id=P-0006554-T01-IM5#/patient?sampleId=P-0006554-T01-IM5&studyId=mskimpact

**Comment by onursumer** [comment]
@zhx828 Does https://github.com/cBioPortal/cbioportal-frontend/pull/370 also fix this issue?

**Comment by zhx828** [comment]
@onursumer it does

**Comment by alisman** [comment]
@onursumer can you verify this is fixed on beta site?
