### ISSUE TITLE
OncoKB tooltip only shows abstracts, not PMIDs

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2512]
This is only for integration branch.

For the case IDH1 R132H in patient case.do?cancer_study_id=lgg_ucsf_2014&case_id=P05
![screen shot 2017-05-31 at 2 50 22 pm](https://cloud.githubusercontent.com/assets/5400599/26648447/81f7dfee-4610-11e7-8eec-e969c777f4d9.png)
It should show three citations, one abstract, two PMIDs. But now it only shows one abstract.
![screen shot 2017-05-31 at 2 49 16 pm](https://cloud.githubusercontent.com/assets/5400599/26648475/96477806-4610-11e7-93f4-37d65f34e256.png)

**Comment by adamabeshouse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: OncoKB tooltip only shows abstracts not PMIDs](https://trello.com/c/IHR08mxz/299-bug-oncokb-tooltip-only-shows-abstracts-not-pmids)

**Comment by adamabeshouse** [comment]
I'm not seeing this bug on local..

![image](https://cloud.githubusercontent.com/assets/636232/26805444/ed8f9e38-4a19-11e7-8480-c0c00491a419.png)

**Comment by adamabeshouse** [comment]
fixed
![image](https://cloud.githubusercontent.com/assets/636232/26805768/79f4ffa2-4a1b-11e7-9863-49703c0a1bb5.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/379

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/382
