### ISSUE TITLE
After disable OncoKB in property file, the loading gif still exist in new patient view

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2518]
![screen shot 2017-06-01 at 11 08 12 am](https://cloud.githubusercontent.com/assets/5400599/26686337/9e28897a-46ba-11e7-8dee-49916f366932.png)

**Comment by onursumer** [comment]
Currently, OncoKB is always enabled for the Mutation Table on the front-end even if the back-end config file disables it. We need to update the front-end code to dynamically enable/disable annotations.

**Comment by onursumer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Expose annotation related configuration parameters in portal.properties to the front-end](https://trello.com/c/PeIMHZOI/300-expose-annotation-related-configuration-parameters-in-portalproperties-to-the-front-end)
