### ISSUE TITLE
 Brain Lower Grade Glioma (TCGA, Provisional)

### ISSUE THREAD

**Issue by alexpenson** [cBioPortal/cbioportal#2522]
When I click on
Brain Lower Grade Glioma (TCGA, Provisional)
I get a "Server Error"
![image](https://cloud.githubusercontent.com/assets/3246599/26701019/7ca1a1be-46ed-11e7-9952-08b587a0f96c.png)

**Comment by alisman** [comment]
Was this on public portal?

**Comment by alexpenson** [comment]
No sorry https://cbioportal.mskcc.org/beta/

**Comment by alisman** [comment]
@inodb i think this is the same data type issue we discussed.

**Comment by ugurdogrusoz** [comment]
I got the same problem on http://www.cbioportal.org/beta/ when I selected CNS/Brain and Glioblastoma (Cell 2013) study

**Comment by jjgao** [comment]
same problem as #2527
