### ISSUE TITLE
Different mutation counts in cross-cancer vs new patient view

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2523]
There seems to be a mismatch between the cross-cancer view and the new patient view when it comes to counting number of mutations. 

**Steps to reproduce:**

1- In query page, filter studies for word "lung" (12 studies in total)
2- Select all studies
3- In gene box type this specific mutation: `BRAF:MUT=G469A` and submit query
4- Change Y-Axis value to "Absolute counts" (see screenshot below)

![image](https://cloud.githubusercontent.com/assets/2900303/26725136/54b11e72-479d-11e7-935d-e248c99e5aa0.png)

5- Notice that it shows 3 cases. 
6- Go to "Mutations" tab. Filter on `G469A`. Here there are also 3 cases (screenshot below).

![image](https://cloud.githubusercontent.com/assets/2900303/26725161/7d302514-479d-11e7-822d-8cc6f1746764.png)

7- Click on the first sample (TCGA-55-7913-01). This will take you to the **new patient view**.
8 - Hover the "Cohort" column value for the row containing the mutation. Notice that it states that there are **11 samples with this mutation instead of just 3** (screenshot below).
![image](https://cloud.githubusercontent.com/assets/2900303/26725275/0ba319fa-479e-11e7-8b66-ba3c47c2f639.png)

**Question:** is this a bug in cross-cancer / mutation view or in the new API + patient view? @onursumer @ersinciftci @alisman ?

**Comment by alisman** [comment]
@ersinciftci  Seems like disparity is in API response.  Here are CURLS for two responsible calls:

OLD:
curl 'http://www.cbioportal.org/crosscancerquery.json' -H 'Cookie: _ga=GA1.2.1001394910.1473780923; fs_uid=www.fullstory.com`1XDVW`5629499534213120:5651442522128384; JSESSIONID=60D900E71CEEFB73CDF9898CD2C890EB.ajp13dashi2; __utmt=1; __utma=162744046.1001394910.1473780923.1496348639.1496414589.362; __utmb=162744046.5.10.1496414589; __utmc=162744046; __utmz=162744046.1495734463.351.9.utmcsr=localhost:8080|utmccn=(referral)|utmcmd=referral|utmcct=/index.do; results-tab=null' -H 'Origin: http://www.cbioportal.org' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://www.cbioportal.org/cross_cancer.do?cancer_study_list=&cancer_study_id=all&data_priority=0&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=BRAF%3AMUT%3DG469A&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&Action=Submit' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data 'gene_list=BRAF%3AMUT%3DG469A&data_priority=0&cancer_study_list=nsclc_tcga_broad_2016%2Cnsclc_unito_2016%2Csclc_clcgp%2Csclc_jhu%2Csclc_ucologne_2015%2Cluad_broad%2Cluad_mskcc_2015%2Cluad_tcga%2Cluad_tcga_pub%2Cluad_tsp%2Clusc_tcga%2Clusc_tcga_pub' --compressed

NEW
curl 'http://www.cbioportal.org/api/genetic-profiles/nsclc_tcga_broad_2016_mutations/variant-counts/fetch' -H 'Origin: http://www.cbioportal.org' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Referer: http://www.cbioportal.org/case.do' -H 'Cookie: _ga=GA1.2.1001394910.1473780923; fs_uid=www.fullstory.com`1XDVW`5629499534213120:5651442522128384; JSESSIONID=60D900E71CEEFB73CDF9898CD2C890EB.ajp13dashi2; __utmt=1; results-tab=null; __utma=162744046.1001394910.1473780923.1496348639.1496414589.362; __utmb=162744046.4.10.1496414589; __utmc=162744046; __utmz=162744046.1495734463.351.9.utmcsr=localhost:8080|utmccn=(referral)|utmcmd=referral|utmcct=/index.do' -H 'Connection: keep-alive' --data-binary '[{"entrezGeneId":7157},{"entrezGeneId":673,"keyword":"BRAF G469 missense"},{"entrezGeneId":136242,"keyword":"PRSS37 truncating"},{"entrezGeneId":7062,"keyword":"TCHH R864 missense"},{"entrezGeneId":7007,"keyword":"TECTA R937 missense"},{"entrezGeneId":149647,"keyword":"FAM71A D38 missense"},{"entrezGeneId":390154,"keyword":"OR5T3 S293 missense"},{"entrezGeneId":54510,"keyword":"PCDH18 R582 missense"},{"entrezGeneId":80243,"keyword":"PREX2 Q1234 missense"},{"entrezGeneId":2686,"keyword":"GGT7 R287 missense"},{"entrezGeneId":118461,"keyword":"C10ORF71 A96 missense"},{"entrezGeneId":148022,"keyword":"TICAM1 Q119 missense"},{"entrezGeneId":6794,"keyword":"STK11 truncating"},{"entrezGeneId":2195,"keyword":"FAT1 truncating"}]' --compressed

**Comment by onursumer** [comment]
Maybe it is related to the keyword? The tooltip says "BRAF G469 missense mutations", it may not be equivalent to "BRAF G496A mutations".

**Comment by ersinciftci** [comment]
@pieterlukasse @alisman in the 6th step, Mutations tab doesn't even open for me, console gives `VM1510:383 Uncaught TypeError: Expected a function` error. But besides that, this is not a bug. In the first case, you are looking at `G469A`, but the Cohort column tooltip in patient view shows `G469` count, which includes all `G469A`, `G469R`, `G469V`, `G469S`, and `G469L`.
