### ISSUE TITLE
DATATYPE vocabulary discussion

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2531]
It's probably also a good idea to re-do / re-design the DATATYPE vocabulary so that we can use them in the code.

- CONTINUES: mrna_rnaseq_rpkm, mrna_rnaseq_fpkm, mrna_microarray, methylation_hm450, methylation_hm27 ...
- Z-SCORE: mrna_rnaseq_rpkm_zscores, ...
- MAF: mutations
- DISCRETE: cna_discrete
- LOG2: cna_log2
- ...

**Comment by pieterlukasse** [comment]
@jjgao could you list the types that are currently not covered in the code?

**Comment by jjgao** [comment]
@pieterlukasse the problem is that the current ones are not really usable. For example, CONTINUES is used to encode rnaseq, microarray_rna, methylation, etc and we still need to use the profile name to decide what the profile is. Ideally we should not use profile name in the logic of the code. For example, currently we have a lot of logic that depends on a zscore profile ending with _zsores.

**Comment by ersinciftci** [comment]
Unassigning myself, not sure if it's still a valid issue.

**Comment by jjgao** [comment]
@ritikakundra @rmadupuri I am wondering if you see the same problem (inconsistent data types) and would like too address this?
