### ISSUE TITLE
New query page: Back button does not go back to home page anymore

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2532]
After starting a query from the new query page, the back button no longer goes back to the home page

**Comment by alisman** [comment]
@schultzn Hi Niki, I'm seeing the same behavior in the legacy site (current cbioportal.org).  If from the homepage I query for a single study, when I arrive at results page, it takes two clicks of back button to return to homepage.    Interestingly, the cross cancer page does not do this.  A single click takes me back to homepage.  
I can try to figure out why it does this, but I just want to make sure I'm not mistaken in my understanding.

**Comment by jjgao** [comment]
Maybe duplicate with #2727

**Comment by alisman** [comment]
@adamabeshouse one reason for this is oncopring use of history.pushState to store filter state (e.g. show_samples) in URL.  I tested and if instead we use replaceState it has same effect without creating a new history item (which then affects back button behavior).  Is this ok?

**Comment by adamabeshouse** [comment]
@alisman good catch, yes absolutely that sounds like desired behavior - hitting the back button wouldn't change the filter state anyway so that's just a bug.
