### ISSUE TITLE
Plots and Mutation tabs not working in new beta portal

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2533]
http://www.cbioportal.org/beta/index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit&show_samples=false&

![image](https://cloud.githubusercontent.com/assets/11892704/26791235/6ad590c2-49e4-11e7-8e81-69e3e8ce7e3f.png)

![image](https://cloud.githubusercontent.com/assets/11892704/26791254/77d77b14-49e4-11e7-9899-dbd5bd742a8d.png)

**Comment by onursumer** [comment]
Seems like this is related to the `_.rest` function call within the mutation mapper library. The new frontend code somehow overrides the global `underscore` with `lodash`. Call signatures of the `rest` function within those two libraries do not match at all:

Lodash: https://lodash.com/docs/4.17.4#rest
Underscore: http://underscorejs.org/#rest

**Comment by alisman** [comment]
Thanks Onur!  I can fix this.   I thought I was calling the no conflict on lodash, but I'll look again.
