### ISSUE TITLE
New patient view: Patient and sample IDs no longer linked

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2536]
The sample IDs and patient IDs used to link to the URL of the specific sample or patient. This was useful when trying to get out of a list of queued samples. Is this by design or an oversight?

![image](https://cloud.githubusercontent.com/assets/11892704/26812961/f4780ea4-4a48-11e7-8021-011f020ceedb.png)

**Comment by jjgao** [comment]
@schultzn it's a oversight.

@alisman is it possible to trim the url when click on a patient/sample ID?
