### ISSUE TITLE
Cross-Cancer overview: incorrect mutation count and frequency

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#2537]
When I [query](http://www.cbioportal.org/cross_cancer.do?session_id=59365a3c498e5df2e29199a8) for 2 mutations (in the same gene) over all studies, I encountered 2 issues:
1. The 'Alteration frequency' and 'Absolute counts' are calculated from the first mutation only. 
2. The 'Alteration frequency' is calculated incorrectly (might be rounding error, see Query 2 below)

### Query 1
```
EGFR: MUT = G719S
EGFR: MUT = T790M
```

_Mouseover MSK-IMPACT:_ Gene set altered in 0% of 10944 cases. 
_Absolute counts MSK-IMPACT:_ **5**

### Query 2
```
EGFR: MUT = T790M
```
_Mouseover MSK-IMPACT_: Gene set altered in **0.5%** of 10944 cases.
_Absolute counts MSK-IMPACT_: **57**

_Click on MSK-IMPACT bar_: Altered in 57 (**0.6%**) of 10335 sequenced cases/patients (10335 total)
57/10335 = 0.00551, so Oncoprint view is correct with 0.6%
### Query 3
```
EGFR: MUT = G719S
```
_Mouseover MSK-IMPACT:_ Gene set altered in 0% of 10944 cases. 
_Absolute counts MSK-IMPACT_: **5**

### Styling
Furthermore, I'd like to suggest some styling improvements to this page:
- The Y-axis ticks for absolute count show one decimal. For absolute count, it makes more sense to show integers.
- 'Absolute counts' should be named 'Absolute count'. The other plot is also singular ('Alteration frequency'). Or both should be plural.

**Comment by jjgao** [comment]
We are reimplementing cross cancer query with the virtual study effort. Let's check on these issues once that feature is release.

**Comment by jjgao** [comment]
I am closing the issue since we have retired cross_cancer.do.
