### ISSUE TITLE
spinning wheel on Mutations tab

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#2552]
Hi, 
I am testing the cbioportal  1.7.0 release. The Mutations tab can not be loaded up. Here is the link to reproduce.
http://www.cbioportal.org/beta/index.do?Action=Submit&genetic_profile_ids=chol_nus_2012_mutations&case_set_id=chol_nus_2012_all&cancer_study_id=chol_nus_2012&gene_list=TP53&tab_index=tab_visualize&#mutation_details
<img width="1378" alt="screen shot 2017-06-07 at 5 16 46 pm" src="https://user-images.githubusercontent.com/17375786/26901966-91232286-4ba5-11e7-9b9a-188560f3fefc.png">
if you can get this fixed that would be great, thank you!

**Comment by alisman** [comment]
Duplicates #2533.   Thanks!  This will be fixed shortly.
