### ISSUE TITLE
incorrect anchor link in DataSet view

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#2557]
in DataSet view when mouse hovering over any of study names, the URL points to www.cbioportal.org instead of localhost. 
<img width="1583" alt="screen shot 2017-06-07 at 3 40 36 pm" src="https://user-images.githubusercontent.com/17375786/26931838-cbfffa34-4c2f-11e7-8d9c-511853560b81.png">

**Comment by alisman** [comment]
duplicate
