### ISSUE TITLE
spinning wheel on Annotation column

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#2558]
Hi, 
the left most icon on the Annotation column is not loaded, how can I fix it? thanks!
<img width="1615" alt="screen shot 2017-06-08 at 10 40 51 am" src="https://user-images.githubusercontent.com/17375786/26934552-aaa336c8-4c37-11e7-9a6f-c017719d2abc.png">

**Comment by alisman** [comment]
@onursumer this is fixed, right?

**Comment by onursumer** [comment]
@alisman I think this issue is the same as #2518.
@khzhu can you make sure that your portal instance is configured with `show.oncokb=true` in `portal.properties`?

**Comment by khzhu** [comment]
Yes, it was set to true in our portal.properties file.

On Jun 12, 2017, at 2:26 PM, onursumer <notifications@github.com<mailto:notifications@github.com>> wrote:

 show.oncokb

**Comment by alisman** [comment]
@khzhu can you tell us what the network panels shows?

**Comment by khzhu** [comment]
Please see attached screenshot, thanks!
[cid:2CB6EEA8-D1D9-4AEA-BE63-DA290FF765FF]
Kelsey
On Jun 13, 2017, at 3:40 PM, alisman <notifications@github.com<mailto:notifications@github.com>> wrote:


@khzhu<https://github.com/khzhu> can you tell us what the network panels shows?

**Comment by alisman** [comment]
sorry I think there was a problem uploaded the screenshot.  Nothing available.

**Comment by khzhu** [comment]
Sorry!
We've not used the network tab in our internal portal. So, everything in the network panel is default, a control wheel and zoom in/out icons, no any pathway network views.
Kelsey
On Jun 13, 2017, at 3:48 PM, alisman <notifications@github.com<mailto:notifications@github.com>> wrote:


sorry I think there was a problem uploaded the screenshot. Nothing available.

**Comment by onursumer** [comment]
@khzhu I think what @alisman meant with the network panel is the network panel within the `Chrome Developer Tools`. I don't think this issue is anything to do with the cBioPortal network tab.

**Comment by khzhu** [comment]
I see, thank you! normally use JetBrain extensions, that was why could not pop into my head.
It is good to get the cBioPortal network view working, thanks for JJ.
Kelsey
On Jun 14, 2017, at 4:46 PM, onursumer <notifications@github.com<mailto:notifications@github.com>> wrote:


@khzhu<https://github.com/khzhu> I think what @alisman<https://github.com/alisman> meant with the network panel is the network panel within the Chrome Developer Tools. I don't think this issue is anything to do with the cBioPortal network tab.

**Comment by khzhu** [comment]
The spinning wheel might be caused by missing copy number alternations in the data set. I loaded 84 patients samples today, all have copy number alternations data, and did not see any spinning wheels (see attach
<img width="587" alt="screen shot 2017-05-25 at 12 58 09 pm" src="https://user-images.githubusercontent.com/17375786/27199156-04bf3110-51e3-11e7-96fc-8551fd5c0ebd.png">
ment). 
My observation is if “Copy Number Alternations are not available” message printed on the bottom of the page, then I see spinning wheel instead of OncoKB icon.

**Comment by khzhu** [comment]
The spinning wheel might be caused by missing copy number alternations in the dataset. I loaded 84 patients samples today, all have copy number alternations data, and did not see any spinning wheels. My observation is if “Copy Number Alternations are not available” message printed on the bottom of page then I will see spinning wheel instead of OncoKB icon.

**Comment by khzhu** [comment]
<img width="1885" alt="screen shot 2017-06-15 at 3 53 07 pm" src="https://user-images.githubusercontent.com/17375786/27199406-d9ddf386-51e3-11e7-9857-92f02706e448.png">

**Comment by alisman** [comment]
@khzhu can you check again?  We made some fixes recently that may have resolved this.

**Comment by khzhu** [comment]
Tested. No more spinning, cheers!!
Kelsey

On Jul 5, 2017, at 10:25 AM, alisman <notifications@github.com<mailto:notifications@github.com>> wrote:


@khzhu<https://github.com/khzhu> can you check again? We made some fixes recently that may have resolved this.
