### ISSUE TITLE
mutations page search feature searches invisible data

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2562]
When searching on the mutations page, the fields that are being searched include invisible data. In this example, I have made all columns visible and I search for "55". The only fields with "55" are the start/end position, but if this field was being searched then all the EGFR mutations should be found, and only 2 of them are. Thanks to @ersinciftci , we figured out that the "mutationId" field for both of these mutations includes "55" so it appears that the search feature is searching the invisible "mutationID" field.

![image](https://user-images.githubusercontent.com/10508276/26993618-e6f590da-4d31-11e7-8f4d-520525af4909.png)

http://www.cbioportal.org/index.do?cancer_study_list=lgg_tcga&cancer_study_id=lgg_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=IDH1+EGFR+IDH2&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

**Comment by jjgao** [comment]
@onursumer maybe this can be fixed in the new code.

**Comment by onursumer** [comment]
This is by default fixed within the new code, we don't have any hidden filters for the new mutation table. I don't think it is worth fixing the legacy code.
