### ISSUE TITLE
Handle zeros in study download page

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2570]
API will return undefined where we have zero.  We will show this as blank cell in UI.

**Comment by alisman** [comment]
@ersinciftci did you make change to api for this?

**Comment by alisman** [comment]
Tamba, Ersin says that api is always returning 0 and that frontend handles it differently depending on column.  Can you make sure that we print whatever we get from api?

**Comment by alisman** [comment]
Just took a look at this.  It's only for columns which are now hidden, like mRNA.  They are blank.  SHould be zero.

**Comment by Tamba32** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [All the other 1.7.1 issues](https://trello.com/c/UP9qKBYW/315-all-the-other-171-issues)
