### ISSUE TITLE
Patient view fails when user does not have access to a study with mutation data

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#2576]
Function metaData in DaoSampleProfile.java uses a join on id2MutationProfile.keySet() which, if the user does not have access to any study with mutation data leads to the query failing and the patient view showing an Oops error message.

**Comment by jjgao** [comment]
@aderidder could you clarify?

**Comment by aderidder** [comment]
Hi JJ,
Install a new cbioportal instance with a clean database
Import a single study, without mutation data
Go to the study view, select a patient, which takes you to the patient view
The patient view dies with aan Oops! An error occurred while trying to connect to the database.

The reason is that patient view at some point calls the function called metaData in DaoSampleProfile.java 
This function attempts to fill a Map called id2MutationProfile. However, as there is no mutation profile available, the Map will be empty. 
The SQL statement calls StringUtils.join with the empty set and the where part becomes 
`where 'GENETIC_PROFILE_ID' in () `
Which when executed fails, resulting in an Exception and the Oops.

**Comment by jjgao** [comment]
@aderidder Thank you. Looks like you have found the solution :) Would you please send a patch and ask @ersinciftci to review?

**Comment by ersinciftci** [comment]
@aderidder What version of cbioportal are you using? The latest version with the new patient view is not supposed to use `DaoSampleProfile.java`, so is it possible you are running an older version of cbioportal?

**Comment by aderidder** [comment]
@ersinciftci Yes our version here is an older one and we were unaware that that piece of code is being phased out. Glad it's already fixed in the new version then.
