### ISSUE TITLE
mis-linked path reports

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2586]
This path report is mis-linked.

http://www.cbioportal.org/beta/case.do#/patient?caseId=B103&studyId=blca_bgi&tab=pathologyReportTab

One way to fix it: looking for file names starting with (instead of containing) the patient id.

**Comment by ecerami** [comment]
@jjgao:  is this a new bug specific to recent refactoring?

**Comment by jjgao** [comment]
@ecerami yes.

**Comment by jjgao** [comment]
@inodb if this is easy to fix, could you do a quick patch?

**Comment by inodb** [comment]
@jjgao ok ill have a look

**Comment by inodb** [comment]
Deployed in production, still needs to be deployed for `beta`
