### ISSUE TITLE
Many gene validation errors

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2587]
@jjgao   I see this alot.   It occurs when I select from dropdown of suggested gene sets, which ought to be valid.

Can you advise, assign this to the right person?

![image](https://user-images.githubusercontent.com/186521/27138687-0c44b6fc-50ef-11e7-978d-8c52677c7505.png)

**Comment by jjgao** [comment]
I'll try to fix it in this round.

**Comment by ecerami** [comment]
Fixed.
