### ISSUE TITLE
Pancreatic Adenocarcinoma (QCMG) not loading

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#2594]
https://cbioportal.mskcc.org/study?id=paad_qcmg_uq_2016#summary
got exception from mutation.json and cna.json

**Comment by ersinciftci** [comment]
Probably a data problem, because the file that throws `NullPointerException` hasn't changed since 2014. Assigning to @jjgao .

**Comment by inodb** [comment]
@jjgao @ersinciftci Yeah it is a data issue. There seem to be some SAMPLE_IDs with a space in the STABLE_ID. They are of the form `"PANC {digit}"` where `{digit}` is for instance 198. @ritikakundra could you update this when you have time? Not sure what repo these are stored Thanks!

**Comment by ritikakundra** [comment]
Fixed the meta files and updated datahub for the same.

**Comment by ritikakundra** [comment]
@jjgao Can we close this?
