### ISSUE TITLE
Study view crashes when clinical attribute contains special characters

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2595]
Steps to reproduce:

- take a test study and edit the clinical data file. e.g. in `/cbioportal/core/src/test/scripts/test_data/study_es_3/data_samples.txt` change column id `DAYS_TO_COLLECTION` to `% DAYS_TO_COLLECTION` (so add a % and a white space in front of it)
- load the test study
- open study view. It will fail to load with http 400 on request http://localhost:8080/cbioportal/api-legacy/clinicaldata/samples and study view will hang (see screenshot below)

![image](https://user-images.githubusercontent.com/2900303/27180688-e93d7a4a-51d4-11e7-8b05-b5abbc813907.png)

**Comment by jensreeder** [comment]
Hi,

While loading data into a local instance, I encountered a similar behavior when the column id contains a . (dot) character.
Validator and loader handle it just fine, but the javascript then interprets the . as a js properties accessor and the summary page fails to load. Would be great if the validator catches these cases.

**Comment by zhx828** [comment]
@pieterlukasse does the issue still exist after switching to new API?

**Comment by sandertan** [comment]
@pieterlukasse I tested this, and the study view displays correctly when there's an attribute ID with % in it. In this screenshot, I gave the Subtype column the clinical attribute id `% DAYS_TO_COLLECTION`. Still want to restrict the attributes to alphanumeric and underscores, in #2596? If so, we need to add it to the documentation as well.

![screen shot 2018-01-09 at 17 04 23](https://user-images.githubusercontent.com/9624990/34730273-31968a74-f55f-11e7-84fb-8ea6714e4a4c.png)

**Comment by pieterlukasse** [comment]
thanks @sandertan , did you also test with `.` (dot)? See @jensreeder's comment above.

**Comment by sandertan** [comment]
@pieterlukasse Good point. With a `.` in the attribute name, the diagram is not drawn.

![screen shot 2018-02-05 at 16 10 33](https://user-images.githubusercontent.com/9624990/35811627-39cb8858-0a8f-11e8-9902-80c985015bc1.png)

**Comment by pieterlukasse** [comment]
@zhx828 any news on this one?

**Comment by zhx828** [comment]
@pieterlukasse apparently I missed this ticket, sorry for the delay. Do we have any public database having this issue?

**Comment by zhx828** [comment]
I don't think this ticket still applicable in the new study view. Please let me know if you still see the issues. Close for now.
