### ISSUE TITLE
weird character when selecting mRNA/protein genomic profiles

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2598]
There's a weird and unnecessary "A" when selecting mRNA/protein in the query page, before the plus/minus: "Enter a z-score threshold Â±:"

![image](https://user-images.githubusercontent.com/10508276/27200341-60f9ee08-51e7-11e7-81aa-7a7737f4d52e.png)

**Comment by tmazor** [comment]
There's also a weird "A-" where there should be an "X" if I select from Recurrently Mutated Genes when modifying a query (but not if I start a query that way). And the spacing of the search bar and the arrows to scroll through pages of mutations is off.

![image](https://user-images.githubusercontent.com/10508276/27200625-7225ab12-51e8-11e7-8545-b3452605b54b.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/407

I can't reproduce the A- bug in chrome, safari, or firefox on mac. What system/browser are you using?

**Comment by tmazor** [comment]
I'm using chrome on mac and I can also see it when I use safari

**Comment by alisman** [comment]
@adamabeshouse I know what this bug is.   Only happens on deployed site.  Not locally.  Will fix.

**Comment by alisman** [comment]
@tmazor hi Tali, I'm confused about the second issue with dialog. Can we chat on GoogleHangouts?  You could send me an email at lisman.aaron@gmail.com
