### ISSUE TITLE
cBio Skins -- Enhanced

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#26]
Another high priority item for us, which I can volunteer us for...  We need a way to fully customize a local installation -- from turning on/off all tabs, creating news pages, setting logos, about pages, footers, etc.  Ideally, the whole thing can be configured and documented via portal.properties.  

I have hacked my way to a solution, but this is a complete hack in modifying JSP pages, and not easy to maintain.  Also, doesn't help others who want to cusotmize their install.  Starting this now to gather requirements.

**Comment by n1zea144** [comment]
We've talked about a way to support multiple skins in one instance of the portal (same WAR file can support different look/feel based on user login).  This would be a great feature.

**Comment by ecerami** [comment]
As I notice specific items that need "skin" enhancements, I will add them as comments...

first one relates to the login page.  screenshot should explain the issues...

![screenshot_65](https://cloud.githubusercontent.com/assets/1009066/7779248/01ed0b96-00a1-11e5-8c23-95587864049f.png)

**Comment by ecerami** [comment]
This is now done!
