### ISSUE TITLE
possible issue with MutSig labels

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2600]
In the TCGA Pancreatic Adenocarcinoma study, there are many mutations labeled as significant by MutSig that have only been identified in 1 sample. That strikes me as weird. It's the same in the non-beta version of cBioPortal so it's not a new thing. I have trouble believing that a gene can be significantly recurrently mutated with just a single mutation.

![image](https://user-images.githubusercontent.com/10508276/27201959-bc65c1a8-51ed-11e7-86d8-8ab87839e666.png)

**Comment by jjgao** [comment]
@ritikakundra could you help look into this? e.g. whether the mutsig list is up to date in the file. Thanks.

**Comment by ritikakundra** [comment]
@jjgao Files look fine but am not sure what value of q is considered for it to be significant?

**Comment by jjgao** [comment]
@ritikakundra I vaguely remember we only pick genes with q<0.1. Could you check the Q-value of some of the genes that are altered in only one sample?

**Comment by ritikakundra** [comment]
Here are some examples for q value:
CCDC158
0.0912

TIGD6
0.000079

and most have 
<7.11e-14

**Comment by jjgao** [comment]
This is strange. We should probably just remove the MutSig results for this study. I suspect that the results were mixed up because of the many versions of mutation data in the TCGA pancreas project.

@ritikakundra could you do that?

**Comment by ritikakundra** [comment]
@jjgao Sure

**Comment by ritikakundra** [comment]
@jjgao This is a provisional study, can I manually remove files? If so do you where they are. I can do it on datahub but I don't know where the files are?

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #278](https://github.com/cBioPortal/datahub/issues/278) via [**ZenHub**](https://www.zenhub.com/)
