### ISSUE TITLE
Dataset page: study is linked out to cbioportal.org even the instance is running on localhost

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2608]
![screen shot 2017-06-19 at 5 42 06 pm](https://user-images.githubusercontent.com/5400599/27307214-a263cfbc-5516-11e7-90d5-0a134ca2c6f3.png)

**Comment by alisman** [comment]
Hey @Tamba32 I thought we fixed this, no?

**Comment by Tamba32** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [All the other 1.7.1 issues](https://trello.com/c/UP9qKBYW/315-all-the-other-171-issues)
