### ISSUE TITLE
Study category list width is different (smaller) in Safari and IE

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2618]
See screenshot.  The top is Safari.  Note that the width of the of the list is narrower in Safari and that the little count icons are clipped.  Same is true in IE.  Could just be different way they handle scrolling.  Please investigate this issue and what if anything can be done to resolve it.  Let me know if this is confusing. 

![image](https://user-images.githubusercontent.com/186521/27352534-1022da26-55cf-11e7-983a-2873389956be.png)

**Comment by Tamba32** [comment]
So I have tried fiddling with the IE side of this issue with the past couple of hours and it seems like the best that can be done with CSS is I can set the `-ms-overflow-style` to `-ms-autohiding-scrollbar` and then it will have the same behavior of that of a Chrome scroll bar in that it only appears on scroll.  However the scroll bar does still overlap the content a bit.  

I read many posts claiming that by adding `ms-overflow-style: scrollbar` to `body` or `html`, the overlapping could be prevented but unfortunately I did not see those results in my testing.


On my version of Safari, there was no scrollbar overlap issue.

**Comment by alisman** [comment]
Hi Tamba, we just figured out a simple solution to this.  We just set overflow:scroll on the div and that causes all browsers to place scrollbar outside of div.   I think this is a fine solution.

**Comment by Tamba32** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [All the other 1.7.1 issues](https://trello.com/c/UP9qKBYW/315-all-the-other-171-issues)

**Comment by Tamba32** [comment]
https://github.com/cBioPortal/cbioportal/issues/2625
