### ISSUE TITLE
hide DOWNLOAD DATA tab for Modify Query

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2631]
Or we can just include the query component like we current do.

![image](https://user-images.githubusercontent.com/840895/27439515-18b7a820-5736-11e7-8de8-a50156f3431c.png)

**Comment by Tamba32** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [All the other 1.7.1 issues](https://trello.com/c/UP9qKBYW/315-all-the-other-171-issues)
