### ISSUE TITLE
OQL parser issue: Uncaught SyntaxError

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#264]
Uncaught SyntaxError: Expected ";", [ \t\r], [\-.@\/a-zA-Z0-9] or [\n] but end of input found.
parse @ oql-parser-8-15.js:1428
parse @ cbioportal-datamanager.js:16

Steps to reproduce: 
- Go to http://cbioportal-test.thehyve.net/cbioportal/ 
- select "Multi cancer study test" 
- In gene set fill : A2M: AMP A2ML1

Desired fixes:
- The syntax error should be caught at the UI, so the user can fix it
- Still, if any exception occurs in javascript, the cbioportal-datamanager.js should handle this properly and throw this up, perhaps as a promise failure

**Comment by adamabeshouse** [comment]
The syntax error being caught at the UI is a feature we will certainly implement as we integrate the data manager into the oncoprint.

What do you think are the advantages of failing gracefully here? I'm not convinced the descriptive exception is worse than a failed promise. In a sense nothing should work at all as long as the OQL query is not valid - that indicates something in the pipeline has gone wrong.

**Comment by pieterlukasse** [comment]
I think giving this back as a promise failure is the only way of giving the calling party some control over what to do when something fails. Since the promise structure is asynchronous, I cannot wrap it in a try /catch block. Now the OQL javascript throws an exception, but this is not handled anywhere and is therefore also not visible for the user. As I see it, we have two alternatives worth exploring: 
1- let the underlying data manager layer display the error message in the UI (but in my opinion this should not really be in scope for such a layer)
2- give eventual errors back as failed promises

**Comment by pieterlukasse** [comment]
btw, complementing my last comment, now regarding the syntax error I talked about: I think this one needs to be handled at the query form page (it already catches some errors, but apparently not all of them).

**Comment by adamabeshouse** [comment]
I hear what you're saying, but my point is that if we get to this page and have invalid OQL, then something has gone totally wrong, so I don't think we should gracefully fail or support this situation - it's invalid/undefined behavior.

**Comment by pieterlukasse** [comment]
ok, but where will we display to the user that something has gone wrong? What the user gets now is a blank/incomplete page. We could give him some feedback. Things can go wrong for other reasons as well during the web-service request processing. I still think that the data manager layer should stick to the promise paradigm, i.e. if something fails, it returns a failed promise (and perhaps in this case the message text of the failure could still be "something went totally wrong"  ) . If the data manager layer/API does not keep to a clear paradigm, it will be hard to program using it. 
All this said, I still agree with you that the specific OQL issue above should be solved. But I would suggest this is taken up as a separate issue. I will log a separate bug for it.

**Comment by adamabeshouse** [comment]
I just think that this is a case where the data manager does truly fail, in a sense, so it shouldn't return a failed promise, it should error out with an exception which the user can catch if they wish

**Comment by pieterlukasse** [comment]
I would agree if it weren't that catching the exception is a problem if it occurs in the asynchronous part of the code. I.e. my code receives the promise object immediately, so there is no error to catch. The error occurs somewhere after my code receives the promise and before .then() is called.

**Comment by adamabeshouse** [comment]
ah right good point, sorry a bit slow today. That's a good idea, I'll put that in now.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/335

**Comment by pieterlukasse** [comment]
hi @adamabeshouse : I tested this while testing another fix and found out that it is still not really fixed (i.e. the original problem described in this ticket). I don't get the javascript error anymore, but the expression A2M: AMP A2ML1  will result in only  A2M: AMP while the gene A2ML1 is left out. Apparently there is a sintax error in my expression (or the parser has a bug) which is not handled yet.

**Comment by jjgao** [comment]
Thanks, @pieterlukasse.

@adamabeshouse: we should put proper unit test code in place for OQL soon.

**Comment by adamabeshouse** [comment]
Hi @jjgao and @pieterlukasse, what is happening is that A2ML1 is being understood as an amino acid change. In order for the desired behavior from this input, we have to implement smart recognition of amino acid changes. To get what you're looking for, you must delineate the gene queries by either a semicolon or a newline.

**Comment by jjgao** [comment]
@adamabeshouse you are right. Let's not worry about that for now.
