### ISSUE TITLE
Endless spinning oncoKB for a sample in pancancer site

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2655]
http://www.cbioportal.org/pancanatlas/case.do#/patient?studyId=pan_can_atlas_mc3_caller_2p&caseId=TCGA-EB-A85I

This case oncoKB spins endlessly.

**Comment by zheins** [comment]
All the samples I've checked in the genie-private portal have this issue: http://www.cbioportal.org/genie-private/case.do#/patient?studyId=genie_akt1&caseId=GENIE-MSK-P-0006227

**Comment by sheridancbio** [comment]
Here are additional cases from testing of various schultz-tomcat portals:
http://www.cbioportal.org/sclc/case.do#/patient?studyId=sclc_ucologne_2015&caseId=S02292
http://www.cbioportal.org/sclc/case.do#/patient?studyId=sclc_ucologne_2015&caseId=S02296
http://www.cbioportal.org/sclc/case.do#/patient?studyId=sclc_ucologne_2015&caseId=S02241
http://www.cbioportal.org/sclc/case.do#/patient?studyId=sclc_ucologne_2015&sampleId=S00050

http://www.cbioportal.org/pdx/case.do#/patient?studyId=brca_bccrc_xenograft_2014&caseId=SA500
http://www.cbioportal.org/pdx/case.do#/patient?studyId=brca_bccrc_xenograft_2014&caseId=SA531
http://www.cbioportal.org/pdx/case.do#/patient?studyId=brca_bccrc_xenograft_2014&caseId=SA535

http://www.cbioportal.org/immunotherapy/case.do#/patient?studyId=skcm_pici_msk_2016&caseId=PR11217
