### ISSUE TITLE
Pancan instance has only one study category, should probably have flat list of studies

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2656]
The pan can site has only one category of studies ("other").  Seems silly to display that category.  Instead, we should just hide the category column (as we when maxTreeDepth is set to 0).  

I looked a little at how to determine the count of cancer types (filter state should not affect this count) in store.  It didn't seem as I easy as I had hoped.  

**Important:** we don't want a filtered list to trigger this mode.  

![image](https://user-images.githubusercontent.com/186521/27563380-45d80eaa-5a9f-11e7-9fc8-de38581fa0e0.png)

**Comment by Tamba32** [comment]
You can set `skin.query.max_tree_depth` to 0 in portal properties.  A full explanation is available in the docs: https://github.com/cBioPortal/cbioportal/blob/master/docs/Customizing-your-instance-of-cBioPortal.md

**Comment by inodb** [comment]
I just updated the props here as @Tamba32 suggested for genie and pancan. So closing this
