### ISSUE TITLE
First step of validation script decoupling 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2660]
It would be nice to be able to get the portal version via an API call. In this way, we can check in the validation script if the portal that is being queried for some of the validation steps is at the expected version. 

Being able to check the version will also enable us to later on move out the scripts/importer package (validation and data loading scripts) from the core module, and let both parts follow their own release cycles.

**Comment by pieterlukasse** [comment]
Notify: @ersinciftci @jjgao

**Comment by ersinciftci** [comment]
Makes sense, it can return DB version as well. I can work on it after I return back from vacation in 1.5 weeks. Or someone else can do it and I can review it when I'm back.

**Comment by pieterlukasse** [comment]
Good idea to let it return both DB version and portal version :+1: 
@ersinciftci we will wait for your implementation. It will help solve https://cbioportal.slack.com/messages/C1EF6T2DT/p1497426061133303

**Comment by ersinciftci** [comment]
@pieterlukasse I'll finally have time to do this tomorrow I hope.

**Comment by ersinciftci** [comment]
Ready as an internal API called Info API http://cbioportal-rc.herokuapp.com/api/swagger-ui.html
