### ISSUE TITLE
Modify query issues when selecting samples

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#2669]
2 related issues:

## Issue 1
In 1.7.0, when selecting samples from Study Summary, querying a gene, modifying query and requery, this error appears:
```
Request-URI Too Large

The requested URL's length exceeds the capacity limit for this server.
```

**Example** 
Study View of Genie: http://www.cbioportal.org/genie/study?id=genie_public#summary
Select Glioblastoma Multiforme from Cancer Type Detailed.
Query PTEN.
Modify Query.
Add KRAS to query and submit.

## Issue 2
When the number of samples is very large, in Modify Query `Error: Bad Request` is displayed:

**Example**
Study View of MSK Impact: http://www.cbioportal.org/study?id=msk_impact_2017#summary
Select Patient's Vital Status: ALIVE
Query for KRAS.
Modify Query.
`Error: Bad Request` in the Select Patient/Case Set section. 
This issue is related to https://github.com/cBioPortal/cbioportal/issues/2668

**Comment by alisman** [comment]
@adamabeshouse this is fixed by the batching, correct?

**Comment by adamabeshouse** [comment]
yes these are both fixed
