### ISSUE TITLE
Patient view: Tumors column empty when downloading data for patient with multiple samples

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2672]
The new patient view has a download option already, which is great :+1: 

![image](https://user-images.githubusercontent.com/2900303/27645350-2777f41a-5c26-11e7-821d-785672e55a7b.png)

However, when there are multiple samples, the `Tumors` column of the CSV is empty. See screenshot below:

![image](https://user-images.githubusercontent.com/2900303/27645001-51100732-5c25-11e7-8deb-d582f73fed49.png)

**Desired solution:**

- When there are multiple samples, each sample should be a new row in the CSV. In the example above, the Gene IDH1 / Protein Change R132C will be the first 4 rows of the CSV, with the only difference being the value in the `Tumors` column. 
- The `Tumors` column would contain the SAMPLE_ID. 

**Alternative solution:**
- When there are multiple samples, each sample should be a new **column** in the CSV. This is now proposed in https://github.com/cBioPortal/cbioportal-frontend/pull/443

**Comment by ecerami** [comment]
@pieterlukasse:  discussed this with @jjgao and others.  If you have time to fix, we prefer to have a single Tumors column with all sample IDs.  Please let me know if you can create a new PR to do this.  Otherwise, we will put in the "icebox" for now.  tx.

**Comment by pieterlukasse** [comment]
The column is not empty anymore, but contains the sample id. In case of multiple samples, the rows are duplicated and only sample id is different (see screenshot below). I would like to hereby close this issue and propose to reopen this issue, or perhaps a new one if there is a need to change the current implementation.
@ecerami , @jjgao please feel free to reopen if you disagree.  

![image](https://user-images.githubusercontent.com/2900303/59925401-55cba680-9438-11e9-9cd3-96d41e545ff6.png)
(screenshot: data downloaded from https://www.cbioportal.org/patient?caseId=P04&studyId=lgg_ucsf_2014#navCaseIds=lgg_ucsf_2014:P01,lgg_ucsf_2014:P02,lgg_ucsf_2014:P04,lgg_ucsf_2014:P05,lgg_ucsf_2014:P06,lgg_ucsf_2014:P07,lgg_ucsf_2014:P08,lgg_ucsf_2014:P09,lgg_ucsf_2014:P10,lgg_ucsf_2014:P11,lgg_ucsf_2014:P12,lgg_ucsf_2014:P13,lgg_ucsf_2014:P15,lgg_ucsf_2014:P16,lgg_ucsf_2014:P17,lgg_ucsf_2014:P18,lgg_ucsf_2014:P21,lgg_ucsf_2014:P24,lgg_ucsf_2014:P25,lgg_ucsf_2014:P26,lgg_ucsf_2014:P27,lgg_ucsf_2014:P28,lgg_ucsf_2014:P29)
