### ISSUE TITLE
add checked gene to query button on enrichments tab doesn't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2673]
If I check a gene in the table on the enrichments tab and then click the "add checked gene to query" button, nothing happens. I'm pretty sure that's supposed to initiate a new query immediately.

**Comment by ecerami** [comment]
@tmazor:  do you think this is a new bug, specific to the recent refactoring, or a long-standing bug?

**Comment by tmazor** [comment]
It's related to the 1.7.1 release I think, because it works in the beta portal running 1.7.0

**Comment by jjgao** [comment]
@tmazor it seems working now. Could you verify?

**Comment by tmazor** [comment]
@jj It's still not working for me.
This is the query I'm running:
http://www.cbioportal.org/index.do?session_id=5953d544498e5df2e291c446&show_samples=false&#enrichementTabDiv&
I check off "NF1" and then click the button and nothing happens.

**Comment by jjgao** [comment]
@tmazor thanks, I can reproduce now with you link.

![image](https://user-images.githubusercontent.com/840895/27872801-f3a7246a-6177-11e7-841f-5b5572a94bed.png)

**Comment by adamabeshouse** [comment]
@alisman I think the best way to do this is to move this logic into the QueryStore and expose methods to the page.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/448
https://github.com/cBioPortal/cbioportal/pull/2700
