### ISSUE TITLE
gistic labels differ between 1.7.0 and 1.7.1

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2687]
The genes labeled with a (G) are different between 1.7.0 and 1.7.1. See screenshot below of the same study:

In the beta portal running 1.7.0 several genes are labeled in the CNA genes table with a (G) indicating significance by gistic:
![image](https://user-images.githubusercontent.com/10508276/27747323-a2f4c762-5d98-11e7-9108-e4e5ebcc0385.png)

In the production portal running 1.7.1 none of those genes are labeled with a (G):
![image](https://user-images.githubusercontent.com/10508276/27747333-aa9f6742-5d98-11e7-9085-b608dce3a088.png)

If I scroll down farther on 1.7.1 then there are some genes labeled with a (G):
![image](https://user-images.githubusercontent.com/10508276/27747383-e4f38c48-5d98-11e7-96c9-50731968ad29.png)

But those genes are not labeled on 1.7.0:
![image](https://user-images.githubusercontent.com/10508276/27747391-ef410dce-5d98-11e7-80d3-85aace012929.png)

**Comment by ecerami** [comment]
@tmazor:  can you paste in URLs where you see this issue?

**Comment by tmazor** [comment]
I can't replicate this anymore, so either it got fixed or it was a weird fluke.
