### ISSUE TITLE
message if a sample does not exist

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2688]
Currently below is the message:

![image](https://user-images.githubusercontent.com/840895/27750564-57c12354-5da6-11e7-9ffc-758ba080994d.png)

Can we change it to "This sample does not exist"?

**Comment by ecerami** [comment]
@jjgao:  what URL brought you to this error?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/445

**Comment by jjgao** [comment]
fixed.
