### ISSUE TITLE
Showing mutation frequency instead of gene frequency in patient view Cohort column

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2690]
This issue was brought up by few pathologists in MSK. The percentage in Cohort column is confusing since each row is representing protein change instead of just a gene. So the column should show mutation freq 16.0% instead of 44.4% in the example below. 
![screen shot 2017-07-05 at 10 16 01 am](https://user-images.githubusercontent.com/5400599/27868535-013b95be-616b-11e7-8c38-741227d2588c.png)

Also, the header is saying the column is for mutation frequency.
![screen shot 2017-07-05 at 10 16 19 am](https://user-images.githubusercontent.com/5400599/27868542-068e883c-616b-11e7-872c-c4b42bce56db.png)

http://www.cbioportal.org/case.do#/patient?sampleId=P-0001272-T01-IM3&studyId=msk_impact_2017

**Comment by ecerami** [comment]
@zhx828:  I don't have access to the MSK cBioPortal, so not sure if I follow.  Can you paste in an example from the public site?

**Comment by zhx828** [comment]
@ecerami: Sorry, I updated the example above and will remember to use a public example for next time.

**Comment by onursumer** [comment]
@zhx828 Good catch!

**Comment by onursumer** [comment]
![mutation_with_no_keyword](https://user-images.githubusercontent.com/3604198/27930296-18403a18-6264-11e7-9d31-acd73385231e.png)

@zhx828 @ecerami @jjgao Apparently, we don't always have the `mutation freq` value. It depends on the `keyword`, and for some mutations we don't have the `keyword` (see the screenshot).

If we want to switch to mutation freq, then we need to decide what to show in case of no value. Should it be just `0%`, or `<0.1%`, or something else? Or should we try to fix this on the backend, and make sure that we always generate the `mutation freq` value for cohort column?

**Comment by jjgao** [comment]
We need to fix the mutation events without a keyword. Proposal: just to use gene + protein change as key work. We need to write some code to change the import script and a migration script.

**Comment by jjgao** [comment]
@schultzn what do you think on this?

**Comment by schultzn** [comment]
I am not sure I am following this one - what is "keyword"?

Would it be sufficient if we left everything as is but show the mutation frequency instead?

**Comment by jjgao** [comment]
@schultzn 

In [the example above](http://www.cbioportal.org/case.do#/patient?sampleId=P-0001272-T01-IM3&studyId=msk_impact_2017), for "TP53 P278Lfs*67", the tooltip indicates: "4538 samples (44.1%) in this study have mutated TP53, out of which 1683 (16.4%) have TP53 truncating mutations."

44.1% is the gene mutation frequency, and 16.4% is the "keyword" mutation frequency. We currently  display 44.1% in the text. Would it be more appropriate to display 16.4% instead?

Or maybe we should use the frequency for the specific mutation? The same amino acid change? The same protein position? Or the same DNA change?
