### ISSUE TITLE
Mutation Frequency should not just be shown as 0.0% when it is small fraction

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2691]
![screen shot 2017-07-03 at 5 10 32 pm](https://user-images.githubusercontent.com/5400599/27807974-8d2f8cd8-6012-11e7-889e-f14019311f78.png)

 https://cbioportal.mskcc.org/case.do#/patient?sampleId=P-0012358-T01-IM5&studyId=mskimpact

**Comment by ecerami** [comment]
@zhx828:  what do you suggest as a fix?  Perhaps, if less that 0.1%, we could just show <0.1%?

**Comment by zhx828** [comment]
I think it is a great idea.

**Comment by inodb** [comment]
deployed
