### ISSUE TITLE
pre-calculate "Fraction of genome altered"

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2696]
Currently it is calculated on the fly based on segment data.

https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/dao/DaoCopyNumberSegment.java#L136

It can be pre-calculated similar to mutation counts. We can use threshold of 0.2.

**Comment by ecerami** [comment]
@jjgao:  should we label this for "refactoring", or is this independent of refactoring?

**Comment by jjgao** [comment]
@ersinciftci It'd be great to do this soon. I think it should be straightforward and will improve the performance.
