### ISSUE TITLE
Local Install -- Networks are sometimes super small

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#27]
On my local installation, I have noticed that the network tab appears, but (sometimes, but not always) appears to be empty.  Example attached.  It looks as if there is no network, but it's actually there, just super tiny.  If you zoom in, you can see the network.  Has anyone else experienced / seen this?

![screenshot_61](https://cloud.githubusercontent.com/assets/1009066/7732321/1ea5109c-fef5-11e4-998b-003548b33bc5.png)

**Comment by ecerami** [comment]
Looping in @onursumer, to see if he has any advice....

**Comment by ecerami** [comment]
Anyone available to help debug this...?

**Comment by onursumer** [comment]
The network tab, specifically CytoscapeWeb, is really outdated, and reproducing & debugging flash player bugs is tricky. I think we should switch to cytoscape.js to have a better/modern network view...

**Comment by ecerami** [comment]
Hi @onursumer.  I agree we should switch to cytoscape.js, but that is likely a long / many months project.  In the meantime, we are stuck with maintaining the Flash-based view.  And, any help you can provide in debugging this would be much appreciated :-)

**Comment by jjgao** [comment]
@ecerami @onursumer Now we have switched to cytoscape.js, could you check if the the issue is solved and close the ticket? Thanks.

**Comment by ecerami** [comment]
This seems to be fixed in the latest release.  Closing for now.
