### ISSUE TITLE
Add link to Firehose on data sets page

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#2702]
At the bottom of this page:

http://www.cbioportal.org/data_sets.jsp

We have the text:

Data sets of published studies were curated from literature. Data sets of provisional TCGA studies were downloaded from Broad Firehose (http://gdac.broadinstitute.org) and updated quarterly.

Can we tweak the text and make Broad Firehose into a link?

e.g. 

Data sets of published studies were curated from literature. Data sets of provisional TCGA studies were downloaded from the [Broad Institute Firehose](http://gdac.broadinstitute.org) and updated quarterly.

**Comment by ersinciftci** [comment]
Needs to be fixed in portal.properties of public instance, assigning to @jjgao .

**Comment by jjgao** [comment]
fixed in properties file. Will fix in the next release.
