### ISSUE TITLE
Download icon should point to the raw file

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#2707]
Currently the download link for studies points to for example 
https://github.com/cBioPortal/datahub/blob/master/public/paac_jhu_2014.tar.gz
This leads some browsers to download the HTML of the github page and save it as paac_jhu_2014.tar.gz. It's also not very helpful as every user who wants to download the study will have to click the download button which leads to https://github.com/cBioPortal/datahub/raw/master/public/paac_jhu_2014.tar.gz
This would be a much better target for the link. It allows directly downloading the source data.

**Comment by ecerami** [comment]
According to @jjgao:  the link should be:

https://media.githubusercontent.com/media/cBioPortal/datahub/master/public/{{study_id}}.tar.gz
