### ISSUE TITLE
Running cbioportal through apache proxy now fails to load studies

### ISSUE THREAD

**Issue by AndyBlake** [cBioPortal/cbioportal#2711]
It is trying to load them through localhost:8080/cbioportal even though the server is running https://domain.name/cbioportal
![screen shot 2017-07-07 at 18 33 31](https://user-images.githubusercontent.com/1448122/27969458-d7d167f6-6342-11e7-902f-b0293b600ada.png)

Any advice on what to do to fix this?

**Comment by ecerami** [comment]
We need more information on this.  How exactly did you get this error message?

**Comment by AndyBlake** [comment]
Hiya
Happy to provide. Latest master branch. Works great when loading directly
via the localhost 8080 in tomcat but when /cbioportal is apache proxied
through to localhost:8080/cbioportal the javascript stuff doesn't pick up
the domain properly and tries to use localhost:8080 rather than the url it
is actually running on. Happy to provide any further details.
Kind regards
Andy

On 10 Jul 2017 9:04 p.m., "ecerami" <notifications@github.com> wrote:

We need more information on this. How exactly did you get this error
message?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cBioPortal/cbioportal/issues/2711#issuecomment-314219679>,
or mute the thread

**Comment by ecerami** [comment]
@alisman:  any advice on this issue?

**Comment by jjgao** [comment]
Strange. We also use apache linking to tomcat on our production server, but it seems working well.

**Comment by AndyBlake** [comment]
FIXED !!  Thanks all for looking.

ProxyPreserveHost on
fixed it
