### ISSUE TITLE
OncoKB integration MutationMapper

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2718]
OncoKB is not working

**Comment by onursumer** [comment]
We need to set these globals somewhere before loading the mutations tab:

```JavaScript
window.showCivic
window.showHotspot
window.showMyCancerGenome
window.showOncoKB
window.oncoKBApiUrl
```

**Comment by onursumer** [comment]
PR https://github.com/cBioPortal/cbioportal-frontend/pull/461 is related to this issue. But the actual parameter setting should be implemented on the `cBioPortal/cbioportal` repository
