### ISSUE TITLE
MutationMapper - Too many tabs for genes

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2721]
Deal with queries of many genes. Currently showing all the gene tabs does not look good

**Comment by onursumer** [comment]
We may want to use a component like this: http://maslianok.github.io/react-responsive-tabs/

**Comment by ecerami** [comment]
@inodb:  dumb question:  what does MutationMapper mean?

**Comment by inodb** [comment]
As Onur mentioned: the mutations tab on the results page
