### ISSUE TITLE
Bug in OQL Parser

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#2722]
Reported by user:

1.  Select TCGA Lung Adeno
2.  In the gene set box, enter: PIM2:exp>0 
3.  Click submit

On the results page, you just get a Download Data progress bar that never goes away.

If you change the query to:  PIM2: exp > 0

everything works.

**Comment by adamabeshouse** [comment]
what was your actual process here? did you paste `PIM2:exp>0` then manually adjust by hand to get to `PIM2: exp > 0`? If so, then I've found the issue and will upload shortly.

**Comment by ecerami** [comment]
Deployed by @inodb.  Closing.
