### ISSUE TITLE
Web Browser Back button should preserve state

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#2727]
I go to cbioportal, click the Download tab, and enter a query...

I get a page with the results.

If I now click the browser back button, I end up back on the cBioPortal page with "complete amnesia", e.g. none of my criteria are there anymore.

**Comment by jjgao** [comment]
Instead of going to another page, download a file.

**Comment by jjgao** [comment]
Maybe also change `Submit Query` to `Download`.

**Comment by onursumer** [comment]
@alisman @jjgao: I think the easiest way is to add a `Content-Disposition` header, see https://stackoverflow.com/a/10616753.

Adding a line like this on the server side works fine as far as I tested: `response.setHeader("Content-Disposition", "attachment;filename=download.txt");`

A quick question: what should the default download file name be? `download.txt`, or something more specific?
