### ISSUE TITLE
Confusing Patient Clinical Attribute Statistics in Study View

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#273]
When uploading your clinical data, you tell whether certain attributes are sample or patient clinical attributes. E.g. Gender - Patient Attribute; Subtype - Sample Attribute
When you head to the study-view you would get the nice overview with the number of males, females etc.

However, when you have a patients with multiple samples, the patient attributes statistics are unexpected. For example, if you have one male patient with one sample and one female patient with four samples, the Gender pie-chart shows 1 male, 4 females. This is confusing, as I would have expected one male and one female, as gender is a patient attribute.

I'm not really sure how to improve this in an easy way that makes sense, as I know that we use it to select samples. Perhaps some text/message/warning/mouseover/? to indicate that patient attributes are now sample attributes? Other ideas?

**Comment by jjgao** [comment]
We have some plan on this. Hongxin is going to separate the patient and sample data in the underlying data model. After that, we will solve this problem.

**Comment by aderidder** [comment]
That's great news. Thanks for the info!

2015-10-15 21:30 GMT+02:00 JianJiong Gao <notifications@github.com>:

> We have some plan on this. Hongxin is going to separate the patient and
> sample data in the underlying data model. After that, we will solve this
> problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cBioPortal/cbioportal/issues/273#issuecomment-148497860>
> .
>



-- 
E.   sander@thehyve.nl
T.   +31(0)30 700 9713
W.  www.thehyve.nl

the hyve

**Comment by zhx828** [comment]
This issue has been solved in new version of Study View. Related info: 
https://github.com/cBioPortal/cbioportal/pull/1405
https://github.com/cBioPortal/iViz/releases/tag/v1.0.1
