### ISSUE TITLE
Results Page:: Mutation Tab:  Civic shows all variants on the page instead of the target variant

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#2734]
Results page mutation table civic tooltip shows information for all civic variants (all variants available on the page). It should only show information for the variant specific to that mutation.

http://cbioportal-frontend-pr-455.herokuapp.com/#/query?geneList=BRCA1%20BRCA2%20BRCA3%20EGFR%20TP53%20PTEN%20KRAS%20NRAS&mutationsGeneTab=TP53&sampleListId=sarc_tcga_all&studyId=sarc_tcga

![civic_variants](https://user-images.githubusercontent.com/3604198/28144356-08e97370-6739-11e7-9863-0bb83dc83805.png)

**Comment by jjgao** [comment]
@oplantalech we would have ti fix this problem before we can release it. Could you please prioritize since we are building a release candidate?  Thanks.

**Comment by oplantalech** [comment]
@jjgao @onursumer I fixed it in cbioportal/cbioportal-frontend#455.
