### ISSUE TITLE
Results Page:: Mutation Tab:  Filtering should be enabled for Sample ID and Cancer Type columns

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#2741]

**Comment by ecerami** [comment]
Which page does this issue refer to?  results page:: mutation tab?

**Comment by onursumer** [comment]
It refers to the `MutationTable`. And for now only affects results page :: mutation tab, since those columns are not included in the patient view mutation table.

**Comment by onursumer** [comment]
Actually, I am not sure if it is a good idea to enable filtering for Cancer Type column, since it is a lazily loaded column.

Maybe for now just enable filtering for Sample Id column. @adamabeshouse @alisman @inodb what do you think?

**Comment by inodb** [comment]
@onursumer I think both could be useful. But yeah sample id would be great
