### ISSUE TITLE
Bug in survival plot in study view

### ISSUE THREAD

**Issue by Sjoerd-van-Hagen** [cBioPortal/cbioportal#2743]
In the survival plot in the study view, after selecting a subset, the first event in both the subsets is not displayed in the plot.

This is best illustrated by taking a very small study, like http://www.cbioportal.org/study?id=chol_nus_2012#summary

With no subset selected, everything is fine:
![image](https://user-images.githubusercontent.com/9987381/28212418-988419ea-68a1-11e7-81c9-6b47d557854e.png)

Now I select the TP53 mutants and get this:
![image](https://user-images.githubusercontent.com/9987381/28212455-b9d45dd0-68a1-11e7-8307-1f0f35f0164f.png)

Now the first event is at 3.8 months.

If I do the same using the survival plot in the results page I do get the right results:
![image](https://user-images.githubusercontent.com/9987381/28212554-4326d860-68a2-11e7-85e3-ed01438a2c5b.png)

What is also interesting is that there is a difference in how people quitting the study are handled. In the study view there is a small vertical mark on 12.3, I suspect the last time this person was known to be alive. In the results page it is basically disregarded altogether. There the survival plot only plots the 7 deceased people. Is this on purpose?

**Comment by Sjoerd-van-Hagen** [comment]
@sandertan @jjgao

**Comment by jjgao** [comment]
this issue seems to be solved.
