### ISSUE TITLE
add link to github in footer

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2744]
https://github.com/cBioPortal/

**Comment by cmdrwebdev** [comment]
Hi @jjgao is this still open? Can i work on this?

**Comment by jjgao** [comment]
@cmdrwebdev yes, still open. Feel free to work on it and send a pull request to hotfix branch. Thanks.

**Comment by jjgao** [comment]
@cmdrwebdev we are prioritizing this one. Are you working on it? Thanks.
