### ISSUE TITLE
URL specific to CN segments tab doesn't load IGV

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2751]
If I go to the URL for CN Segments (right click & open in new window), it doesn't load IGV and just provides an option to download. But if I click away to any other tab and then click back to CN Segments, it loads properly.

Go here:
http://www.cbioportal.org/index.do?session_id=59690649498e5df2e292870c&show_samples=false&clinicallist=AGE&#igv_tab

And it will look like this:
![image](https://user-images.githubusercontent.com/10508276/28228215-7f297436-68ab-11e7-878d-86e23bd3ab8d.png)

Click to any other tab and then click back to CN Segments and it will load:
![image](https://user-images.githubusercontent.com/10508276/28228267-c4051150-68ab-11e7-969a-63acae7c2bea.png)

**Comment by tmazor** [comment]
Similar thing happens with the Bookmark tab. Going directly to the specific URL results in a page without any URLs:
http://www.cbioportal.org/index.do?session_id=59690649498e5df2e292870c&show_samples=false&clinicallist=AGE&#bookmark_email
![image](https://user-images.githubusercontent.com/10508276/28228755-c9524dce-68ad-11e7-8d48-27139ee497d6.png)

But if you click to another tab and then click back, the links appear:
![image](https://user-images.githubusercontent.com/10508276/28228779-dcda6a70-68ad-11e7-8dd3-9e9538d77e66.png)

**Comment by jjgao** [comment]
Let's keep it in mind when refactoring the tabs.

**Comment by jjgao** [comment]
The link to the cn segments tab has resolved. Let's test the bookmark tab once it's refactored.
