### ISSUE TITLE
typo on "visualize your data" page

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2755]
The ampersand between the two citations is showing up as "&amp;":

![image](https://user-images.githubusercontent.com/10508276/28284024-b0dfc47c-6afd-11e7-8046-2272a169d968.png)

**Comment by jjgao** [comment]
@alisman and could you also change "2. We host data for you": remove the first point and add a last point "Please <contact us> for details." Also add a period in "Private data..."
