### ISSUE TITLE
add tcga lgg publication dataset

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2762]
There is a provisional dataset for the TCGA LGG project but there should also be a dataset reflecting the publication: http://www.nejm.org/doi/full/10.1056/NEJMoa1402121#t=article

**Comment by jjgao** [comment]
Thansk @tmazor.

@ritikakundra do we have a list of TCGA publications that have not been curated? https://cancergenome.nih.gov/publications

**Comment by ritikakundra** [comment]
@jjgao No, we don't have that. I can use Prerna's help to cross check with the link you shared.

**Comment by jjgao** [comment]
@ritikakundra That would be helpful. We should curate all the published TCGA studies.

**Comment by ritikakundra** [comment]
@jjgao We have a list ready. We will schedule the data release as we finish the list.

**Comment by jjgao** [comment]
We will capture this issue here: https://github.com/cBioPortal/datahub/issues/183
