### ISSUE TITLE
hide Mutual Exclusivity tab if only one gene is queried

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2765]

**Comment by ersinciftci** [comment]
@jj I thought when we started the refactoring project last year, we decided not to hide any tabs, we would just indicate the reason why there is no data in the tab, instead of hiding it. So the user would know that they would get the data if they query multiple genes, otherwise they won't even know that this feature exists if we hide it.

**Comment by jjgao** [comment]
@ersinciftci Sorry I forgot we decided not to hide any tabs. I think it may be still better to hide tabs if certain analysis features are not available. For example, in the query below, Co-exp and Survival tabs are remove because the data are not available. Otherwise one would click and find out it's not available. I am not particularly worried about people not knowing our features.

http://www.cbioportal.org/index.do?session_id=5984b326498e5df2e2938178&show_samples=false&
![image](https://user-images.githubusercontent.com/840895/28980381-a23182e0-791b-11e7-8d0e-5e267c991abd.png)

http://www.cbioportal.org/index.do?session_id=5984b343498e5df2e293817b&show_samples=false&
![image](https://user-images.githubusercontent.com/840895/28980360-969cfd9c-791b-11e7-85eb-69f20a2876d0.png)

**Comment by ecerami** [comment]
@jjgao and I discussed.  We are going with the suggestion, e.g. hide tab is only one gene is queried.

**Comment by alisman** [comment]
@ersinciftci I finally got a chance to look at this.  This really should be done on backend in 
portal/src/main/webapp/WEB-INF/jsp/visualize.jsp
There is a QueryBuilder object that should have gene list on it but I'm just not enough of a java person to handle this and I think it would be a lot more efficient for a java person to do it.
