### ISSUE TITLE
OncoPrint: do not load patient/sample attribute list until needed

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2766]

**Comment by ecerami** [comment]
@jjgao:  can you provide more detail on this?  are you referring to the pull-down menu in the OncoPrint?  Is the goal to improve performance?

**Comment by jjgao** [comment]
@ecerami yes, for performance reason. Currently the list of attributes were retrieved from backend when loading up the tab, before the list is useful (the user click on the drop down button). It's a minor improvement.

**Comment by adamabeshouse** [comment]
done in refactor
