### ISSUE TITLE
OQL issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#277]
http://bit.ly/1M2db8v

**Comment by jjgao** [comment]
![image](https://cloud.githubusercontent.com/assets/840895/10525169/36fd93d2-7351-11e5-93ed-0afdd5258159.png)

**Comment by adamabeshouse** [comment]
confused....this should be fixed by the other pull request, it's covered in the test...

https://github.com/cBioPortal/cbioportal/pull/318/files#diff-3b71e5412e16cacc305eaf242b9ffa4eR55

**Comment by adamabeshouse** [comment]
@jjgao is this still an issue?

**Comment by adamabeshouse** [comment]
@zheins is this related to something you worked on?
