### ISSUE TITLE
Use property/env variable to specify frontend version

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2778]
Currently we can only change frontend version by changing `portal/pom.xml`. We should change this to an environment variable/property so on heroku we can for instance just change the env variable of the instance instead of having to make changes to the `cbioportal` repo's `pom` file. The latter will then only have to be done at the final stage when we deploy officially.

**Comment by jjgao** [comment]
@inodb I have mixed feelings about this. On one hand, it's a good idea to free frontend from backend. On the other hand, the frontend is still tightly connected to the current `portal` and `core` modules. Only specific versions of portal-frontend and portal can work together. For the moment, I think it may be still better to check in the frontend version into a file (not necessary `pom.xml` though).

Once we discard the `portal` and `core` modules and the API is more stable, we can decouple the frontend. We still need to find a way to specify which API version is working for which frontend version.

**Comment by inodb** [comment]
@jjgao I think it would be very useful for review on Heroku at the moment. Currently we do the same thing during development using our `localDev=true` trick, but it's more tricky to share a URL, since you have to make changes to the pom file on the backend. It would for the start just be for internal development use.

If we are going to expand the use of this feature to other portal maintainers I agree that it would be better to first have better warning messages when the frontend & api mismatch.

**Comment by jjgao** [comment]
@inodb maybe in addition to the checked in version, we can support it in props file (which overrides the checked-in one)? We don't have to document it in order to keep it just for dev purposes for now.

**Comment by inodb** [comment]
@jjgao yes, exactly
