### ISSUE TITLE
Oncoprint shows wrong label for unknown/other mutations

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2779]
When a mutation type is not recognized by the frontend, it displays as "other" in the Mutations tab (see screenshot below):

![image](https://user-images.githubusercontent.com/2900303/28362738-da8cf57a-6c7d-11e7-90d0-ed70319fc85c.png)

However, in Oncoprint, these same mutations are labelled as "Truncating" (screenshot below):

![image](https://user-images.githubusercontent.com/2900303/28362824-4a0322ee-6c7e-11e7-9b72-5add0947b035.png)

Desired solution:
- oncoprint should display label "Other" for unknown mutations
- perhaps the color for "Other" should not be purple as this is already the color for Fusions in the oncoprint

**Comment by jjgao** [comment]
@pieterlukasse Is this a study in the public portal?

Agreed we should pick a different color for `other` types, but maybe not purple. How about a orange-ish color?

**Comment by pieterlukasse** [comment]
@jjgao I took this one from a local test, not sure if it occurs in any public study. 

Orange-ish color is already used for Promoter (5'flank) region mutations. We will need another color.

**Comment by jjgao** [comment]
@adamabeshouse @onursumer would it be possible to isolate the util code for determining the color from the Mutations component and use the same code in other places, e.g oncoprint and patient view?

**Comment by adamabeshouse** [comment]
@jjgao definitely, I think @onursumer has already written code for this purpose.

**Comment by jjgao** [comment]
@adamabeshouse great. It might be a good opportunity to do this when refactoring the oncoprint tab.

**Comment by jjgao** [comment]
@adamabeshouse could you work on this?

**Comment by adamabeshouse** [comment]
@jjgao @pieterlukasse I just implemented the feature, but in trying to test it I found an inconsistency: for oncoprint, OQL, everywhere except mutations tab, we map "targeted_region" to inframe, but for mutations tab, we map "targeted_region" to "other". If you have time, please review our maps:

for oncoprint, oql, etc:
https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/shared/lib/oql/accessors.ts#L16

mutations tab:
https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/shared/lib/getCanonicalMutationType.ts#L30

**Comment by jjgao** [comment]
@adamabeshouse let's map `targeted_region` to `other`. It was a hack to map to `in_frame` due to some annotation error (which we have corrected).

**Comment by adamabeshouse** [comment]
@jjgao done
