### ISSUE TITLE
pan-lung study doesn't load oncokb annotations

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2782]
In the 1.8.0 beta release, in the pan-lung dataset, OncoKB annotations fail to load in the mutations tab:

http://www.cbioportal.org/beta/index.do?session_id=596f5c39498e5df2e292b9c4&show_samples=false&
![image](https://user-images.githubusercontent.com/10508276/28369244-0722850a-6c65-11e7-9468-30520d2a4c10.png)

I looked at a few other studies and they didn't have this problem so this may be unique to pan-lung

**Comment by tmazor** [comment]
This also happens for the MSK-IMPACT study so may be a problem for pan-cancer studies in general

**Comment by onursumer** [comment]
I think the reason is that clinical data fetch API is failing: `identifiers size must be between 1 and 1000`. Since OncoKB depends on clinical data, it also fails.

**Comment by onursumer** [comment]
Fixing #2813 should also fix this issue.
