### ISSUE TITLE
mutation tab shows error for copy number when copy number doesn't exist

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2784]
In the beta portal, on the mutations tab, there is a copy number column that shows "error" in studies that don't have copy number. This column probably shouldn't be displayed if there's no copy number, or if it is displayed, should say "N/A" rather than "error"

http://www.cbioportal.org/beta/index.do?session_id=596f5ec4498e5df2e292b9ea&show_samples=false&#mutation_details

![image](https://user-images.githubusercontent.com/10508276/28370384-2a3bee16-6c68-11e7-996e-bd629fee3229.png)

**Comment by jjgao** [comment]
Agreed. We should not display that column if no cna data.

**Comment by jjgao** [comment]
Similarly, if there is no Allele Freq data, can we hide the column?
