### ISSUE TITLE
avoid sending duplicate query to civic

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2794]
For the same mutation / alteration, only one query should be sent.

http://www.cbioportal.org/beta/index.do?session_id=596f9fa3498e5df2e292bdfd

![image](https://user-images.githubusercontent.com/840895/28382165-3d041ee2-6c8b-11e7-9944-8258ddc26ff7.png)

**Comment by oplantalech** [comment]
@jjgao @inodb I fixed the issue in the PR cbioportal/cbioportal-frontend#483.
