### ISSUE TITLE
How to deal with Pancan studies in the bar chart

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2796]
The pancan studies are currently not displayed in the bar chart. 

![image](https://user-images.githubusercontent.com/840895/28387180-166a4a98-6c9c-11e7-9b8e-ac60516c9bc3.png)

I think we should still get them into the chart. Should we add a category PanCan for studies under mixed cancer type. Thoughts, @ecerami @schultzn ?

![image](https://user-images.githubusercontent.com/840895/28387294-7fbd1bb0-6c9c-11e7-9a09-2df0ac4e5617.png)

In the long run, we should count cancer types / tissues per sample when we have oncotree code for every sample / study.

**Comment by ecerami** [comment]
@jjgao:  I think it will be hard to integrate the pan-cancer studies w/o having them swamp all the other studies in the bar graph.  Perhaps, a simpler option is to have text like:

The portal contains 162 studies (details).  This includes X pan-cancer studies with XXX samples, and the following cancer-type specific data sets...
