### ISSUE TITLE
Patient View Page tries to go to OncoKB

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#28]
When I open up a patient view page on my local installation, I see spinning circles next to each gene.  

![screenshot_62](https://cloud.githubusercontent.com/assets/1009066/7733825/ca7a4d74-feff-11e4-9a2c-9ef8274a5864.png)

Trying to debug this, I see an error message in the console about not being able to connect to oncokb:

![screenshot_63](https://cloud.githubusercontent.com/assets/1009066/7733863/06552684-ff00-11e4-8f31-cfd1531503d4.png)

**Comment by ecerami** [comment]
Looping in @zhx828.  Perhaps, this is just a simple setting that I need to turn off...?

**Comment by zhx828** [comment]
@ecerami It should make a test connection first. If the oncokb website is not accessible, these loading gifs should not exist at all. Let me do a quick fix.

**Comment by ecerami** [comment]
thanks so much, @zhx828.  Just updated code from master, and verified that bug is fixed.
