### ISSUE TITLE
Somatic/Germline mutation rate on mutations tab

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2801]
We are missing somactic and germline mutation rate at the top of the page on the new mutations tab. Is this critical @jjgao ?
![screen shot 2017-07-20 at 12 20 42 pm](https://user-images.githubusercontent.com/1334004/28427991-e1dc074e-6d45-11e7-9f76-cbb867ed4bb8.png)

**Comment by jjgao** [comment]
@inodb yes that's important for the release. It's ok that we don't have it for tomorrow.

**Comment by inodb** [comment]
@jjgao ok thanks!

**Comment by inodb** [comment]
This might require a new endpoint (it uses a servlet)
