### ISSUE TITLE
civic annotation doesn't load in pan-lung study

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2802]
The civic annotation just spins as if loading but nothing ever happens. I see this with pan-lung & MSK-IMPACT although it works in all other studies that I've looked at.

http://www.cbioportal.org/beta/index.do?session_id=5970deb3498e5df2e292caa6&show_samples=false&

![image](https://user-images.githubusercontent.com/10508276/28429526-089c75f8-6d4b-11e7-8826-d6e519527a9b.png)

**Comment by jjgao** [comment]
I think it may be the same cause as OncoKB.
