### ISSUE TITLE
mutations tab lollipop diagram isn't loading for CDKN2A

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2803]
On the mutations tab, the CDKN2A gene structure/lollipop diagram just doesn't load. I've tried a bunch of genes and so far this problem is specific to CDKN2A -- I've looked in several studies and this is a consistent problem. I've been on this page for several minutes and it's just showing those three dots as if it's trying to load, but it never succeeds.

![image](https://user-images.githubusercontent.com/10508276/28429726-b99382fc-6d4b-11e7-8e9f-23ff5c2ada94.png)

**Comment by jjgao** [comment]
mygene.info returns two uniprot entries:

http://mygene.info/v3/gene/1029?fields=uniprot

Let's pick the first for now.
