### ISSUE TITLE
cosmic pop-up formatting issue

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2804]
The box that says "1-10 of 19" in the example below is taller than the arrow buttons on either side of it.

This is in chrome:
![image](https://user-images.githubusercontent.com/10508276/28430334-244af024-6d4e-11e7-8eb1-8d6a95a7ecf6.png)

In Firefox, the menu for how many to show is also very tall:
![image](https://user-images.githubusercontent.com/10508276/28430418-7c90a3aa-6d4e-11e7-88e0-d92b3d0dda70.png)

**Comment by onursumer** [comment]
![cosmic_tooltip](https://user-images.githubusercontent.com/3604198/28690372-ecaf2416-72e6-11e7-9a6d-b764837850fa.png)

After the recent changes, this is what we have now. This is even worse I guess :)

**Comment by tmazor** [comment]
haha no, that's definitely not better!

**Comment by inodb** [comment]
This has not been deployed yet, so just reopening
