### ISSUE TITLE
mutation assessor column has inconsistent values

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2805]
Sometimes a mutation is "NA" and sometimes it's "[Not Available]" and sometimes it's just blank:

http://www.cbioportal.org/beta/index.do?session_id=5970d5dc498e5df2e292c9ec&show_samples=false&
![image](https://user-images.githubusercontent.com/10508276/28430848-f673070c-6d4f-11e7-94d3-73cc38976ac8.png)

http://www.cbioportal.org/beta/index.do?session_id=5970deb3498e5df2e292caa6&show_samples=false&
![image](https://user-images.githubusercontent.com/10508276/28430867-09a22164-6d50-11e7-8fc1-3b7ca2cfcd36.png)

http://www.cbioportal.org/beta/index.do?session_id=5970e98f498e5df2e292cb62&show_samples=false&
![image](https://user-images.githubusercontent.com/10508276/28431127-20085a94-6d51-11e7-91fa-16b8bd4f7d70.png)

**Comment by jjgao** [comment]
Use empty for NA, [Not Available], etc.

**Comment by tmazor** [comment]
I know there's a fix coming for this -- can it also apply to patient view mutation table @onursumer ?

http://www.cbioportal.org/beta/case.do#/patient?sampleId=TCGA-02-2483-01&studyId=gbm_tcga_pub2013
![image](https://user-images.githubusercontent.com/10508276/28791321-0fbb1832-75fa-11e7-8e96-a2f2a9fe434f.png)
