### ISSUE TITLE
Move CIVIC annotation position

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2812]
Currently CIVIC is after the hotspots indicator. Since CIVIC is a knowledge base it would probably make more sense to have it with the other knowledge bases. First oncokb, then CIVIC then mycancergenome.

**Comment by jjgao** [comment]
If turned off, CIVIC should not take a space.. Same should apply to any disabled icons. Let's put CIVIC after OncoKB.

**Comment by onursumer** [comment]
@jjgao should we also update the sort priority? I mean sort by OncoKB, and then by Civic, and then by my cancer genome, and then hotspots.

**Comment by jjgao** [comment]
@onursumer sounds good.
