### ISSUE TITLE
Period in Sample ID or Gene

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#2820]
I just noticed that querying a sample id (`testsample.1`) that contains a `.` from the Clinical Data tab, results in `{"message":"Sample not found in study teststudy: testsample"}`

When I manually add a `/` behind the sample id in the URL, the page loads successfully. This is similar to a bug @fedde-s found and reported in Slack:

https://cbioportal.slack.com/archives/C1J0T1Y5A/p1498748533757864

**Comment by jjgao** [comment]
Is it related to API?

**Comment by fedde-s** [comment]
@jjgao: yes, we identified that a Spring annotation used in the API code was truncating parameters containing dots after the last slash of URI paths. I think @ersinciftci then found that it was recognising the dot and remaining characters as a filename extension. This is the example I gave:

> the list of all genes on <http://www.cbioportal.org/api/genes> lists a gene with the symbol `H3.X`, but <http://www.cbioportal.org/api/genes/H3.X> queries for a non-existent gene named `H3` (@ersin)

**Comment by fedde-s** [comment]
Pull request #2821 seems to address this.
