### ISSUE TITLE
Results view page cancer type column solely relies on clinical data

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#2823]
In case clinical data is not available, we should try to populate the cancer type column by using the study cancer type.

But probably we should only do this if there is no more than one study for the specific query. (i.e: it should not be a mixed or virtual study)

**Comment by jjgao** [comment]
@onursumer a sample is alway belong to a study so we can always fall back to the cancer type of the study that the sample belongs to.

**Comment by jjgao** [comment]
The problem is how can you get the main cancer type (it's not in the type_of_cancer table). 

And ultimately I think we may want to address it in the backend business layer.

**Comment by jjgao** [comment]
Looks like we are using cancer type detailed and it is solved.
