### ISSUE TITLE
IE issue - Mutation Mapper Controls too big

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2826]
![screen shot 2017-07-21 at 6 59 31 pm](https://user-images.githubusercontent.com/1334004/28485335-c5a18d90-6e46-11e7-8ed5-6666cf779fae.png)

**Comment by jjgao** [comment]
@inodb thinking of doing it in 1.8.1.

**Comment by inodb** [comment]
@jjgao ok

**Comment by onursumer** [comment]
This is how it looks now in IE with the release 1.8.0:

![mutation_mapper_1 8 0_ie](https://user-images.githubusercontent.com/3604198/28978252-3fb5e28a-7913-11e7-9f1e-009d22d129bd.png)
