### ISSUE TITLE
two cancer studies are missing from the bar chart

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#2828]
for three cancer studies only Bad_BRCA study was displayed in bar chart. 
<img width="1729" alt="screen shot 2017-07-22 at 5 03 18 pm" src="https://user-images.githubusercontent.com/17375786/28494563-68a60610-6f00-11e7-8a95-8c33f0615123.png">

**Comment by Tamba32** [comment]
Hi @khzhu.  The bar chart should now show all the same studies as shown in the "Query, Select Studies" component, except those with `cancerTypeId`s of `other` or `mixed`.

**Comment by khzhu** [comment]
@Tamba32, thank you!
any reasons not including cancer type of other/mixed. The reason I am asking is because we have a quite number studies in this category.

**Comment by jjgao** [comment]
@khzhu it's because other/mixed will dominate the chart in many of our instances including the public portal and they don't really provide much info. 

We will try to use sample level tumor type to populate the bar chart in the future and hopeful will solve the problem.

**Comment by khzhu** [comment]
@jjgao ,  I see. Thank you so much for your detailed explanation!
