### ISSUE TITLE
something wrong about METHYLATION attribute and METHYLATION legend

### ISSUE THREAD

**Issue by leedonghn4** [cBioPortal/cbioportal#283]
http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit&clinicallist=FRACTION_GENOME_ALTERED,COPY_NUMBER,MRNA_DATA,CANCER_TYPE,METHYLATION&

**Comment by adamabeshouse** [comment]
ah it looks like the problem is a divide by zero error when the lower and upper bound of the data range are the same

**Comment by adamabeshouse** [comment]
I don't see the problem still happening in rc - it looks like METHYLATION has been changed from a numerical clinical attribute into a categorical one. I'll change in general though

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/319
