### ISSUE TITLE
strange vertical scroll bar 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2832]
http://www.cbioportal.org/beta/index.do?session_id=59764965498e5df2e292f55f

![image](https://user-images.githubusercontent.com/840895/28540690-3d02edea-7084-11e7-8632-7113e304d35c.png)

**Comment by onursumer** [comment]
After spending some time with @jjgao, we figured out that there is a hidden `div` is causing the scroll bar problem.

Looks like that `div` is added by the `ResizeDetector` library which is used to auto adjust tab paging on `div` resize. I think for now it is okay to disable page adjusting on resize. We can find a better way to detect resize later...

**Comment by inodb** [comment]
@onursumer nice find!!

**Comment by onursumer** [comment]
Actually here is the solution: https://github.com/maslianok/react-resize-detector/issues/6

**Comment by jjgao** [comment]
Somehow the vertical bar still show up for a second.

![](https://media.giphy.com/media/l41JHMaF44gwFiOC4/giphy.gif)

**Comment by onursumer** [comment]
looks like it is because we never merged my fix, but just closed the PR: https://github.com/cBioPortal/cbioportal-frontend/pull/513 :)
