### ISSUE TITLE
samples in tcga studies don't have cancer type

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2834]
Some samples in the TCGA GBM Cell 2013 study (issue #2819 ) and all samples in TCGA Breast Invasive Carcioma Cell 2015 (below) don't have a cancer type

http://www.cbioportal.org/beta/index.do?session_id=59763788498e5df2e292f40b&show_samples=false&
![image](https://user-images.githubusercontent.com/10508276/28543884-5b53a55e-708f-11e7-8e50-e83d51f9cf86.png)

**Comment by jjgao** [comment]
This is related to https://github.com/cBioPortal/iViz/issues/553
