### ISSUE TITLE
ERROR in showing CNA data in mutations tab

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2839]
![screen shot 2017-07-24 at 6 31 37 pm](https://user-images.githubusercontent.com/12007862/28547894-166df70e-709f-11e7-8dc1-eb835b9ba2ef.png)

When I loaded CNA for mskimpact for KRAS, some showed error

**Comment by ritikakundra** [comment]
![screen shot 2017-07-24 at 6 38 44 pm](https://user-images.githubusercontent.com/12007862/28547934-4a463636-709f-11e7-92ba-aa8751100e6c.png)

**Comment by inodb** [comment]
Duplicate of #2784
