### ISSUE TITLE
Drop down search does not show the right results on homepage

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2840]
Don't know if this falls in this release but when I use tcga - provisional option from drop down, I still get non provisional options. 
![screen shot 2017-07-24 at 6 20 29 pm](https://user-images.githubusercontent.com/12007862/28548002-90e07d0e-709f-11e7-8dba-e7b773baacb9.png)

**Comment by inodb** [comment]
Good catch, yes this is an issue in current deploy as well, so should be a hotfix

**Comment by jjgao** [comment]
@ritikakundra "tcga -provisional" means TCGA studies but not provisional ones.
