### ISSUE TITLE
predefined gene list for angiogenesis includes wrong gene name

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2843]
Reported by user:
  IL8 is not recognized as a valid gene yet it is included in one of your predefined gene sets (Angiogenesis).  Can you please modify the Angiogenesis gene set to include CXCL8 instead?

**Comment by jjgao** [comment]
This is strange. It is already fixed [in the code](https://github.com/cBioPortal/cbioportal/blob/hotfix/core/src/main/resources/gene_sets.txt) but didn't pick up in the frontend. Maybe some caching issue?

**Comment by tmazor** [comment]
Weird. I did a hard refresh and I still get IL8

**Comment by inodb** [comment]
fixed now
