### ISSUE TITLE
Mutations tab refactoring: Somatic and germline mutation frequencies are missing

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2844]
Somatic and germline mutation frequencies are missing from the new mutations tab. Was this done on purpose? See the BRCA1/2 example:

http://www.cbioportal.org/beta/index.do?tab_index=tab_visualize&cancer_study_list=ov_tcga_pub&cancer_study_id=ov_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ov_tcga_pub_mutations&Z_SCORE_THRESHOLD=2.0&case_set_id=ov_tcga_pub_3way_complete&case_ids=&gene_list=BRCA1+BRCA2&gene_set_choice=user-defined-list&Action=Submit#mutation_details&show_samples=false&

![image](https://user-images.githubusercontent.com/11892704/28586006-46f2ccdc-7140-11e7-801e-6ae9aaa65051.png)
![image](https://user-images.githubusercontent.com/11892704/28586013-4d508362-7140-11e7-957d-fd4558dba0e6.png)

**Comment by jjgao** [comment]
duplicate with #2801
