### ISSUE TITLE
Mutations tab refactoring: Germline / somatic information

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2845]
Was this changed on purpose? It used to be G vs S, with a glyph /color for each. Now it is plain text.

Also, the MS column should be shown by default when germline mutations are present.

http://www.cbioportal.org/beta/index.do?tab_index=tab_visualize&cancer_study_list=ov_tcga_pub&cancer_study_id=ov_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ov_tcga_pub_mutations&Z_SCORE_THRESHOLD=2.0&case_set_id=ov_tcga_pub_3way_complete&case_ids=&gene_list=BRCA1+BRCA2&gene_set_choice=user-defined-list&Action=Submit#mutation_details&show_samples=false&

![image](https://user-images.githubusercontent.com/11892704/28586130-afb30282-7140-11e7-88e3-fcc0e0dfcff4.png)

![image](https://user-images.githubusercontent.com/11892704/28586141-b96a13ce-7140-11e7-9681-3be9e915b47a.png)

**Comment by jjgao** [comment]
@schultzn maybe we should the same style as in the patient view page? Or would you prefer the old way?

![image](https://user-images.githubusercontent.com/840895/28586389-9cd700ae-7141-11e7-84e5-3a35c6b625ed.png)

http://www.cbioportal.org/case.do#/patient?sampleId=TCGA-61-2109-01&studyId=ov_tcga_pub

**Comment by schultzn** [comment]
good idea... maybe show the germline box by default, but also have the column option?

**Comment by jjgao** [comment]
Sounds good.
