### ISSUE TITLE
Mutations tab refactoring: NA for Mutation Assessor

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2846]
I prefer the old way of showing nothing when Mutation Assessor data was not available

Now we have NA and [Not Available]
![image](https://user-images.githubusercontent.com/11892704/28586195-ed0619d0-7140-11e7-99d5-819f2abe00de.png)

![image](https://user-images.githubusercontent.com/11892704/28586203-f1ace8a6-7140-11e7-9a32-c0f2c7803495.png)

**Comment by jjgao** [comment]
duplicate with #2805
