### ISSUE TITLE
Mutations tab refactoring: Tooltip for read counts has empty line

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2848]
The tooltip for read counts has an empty line that seems unnecessary.

The bolding in the previous implementation was useful.

![image](https://user-images.githubusercontent.com/11892704/28586452-e6c7df3a-7141-11e7-8909-85a0cbc3864a.png)
![image](https://user-images.githubusercontent.com/11892704/28586458-ed658a0e-7141-11e7-9aee-df64ccb8f358.png)

**Comment by schultzn** [comment]
Ignore the comment about bolding.

But the empty line at the end affects all tooltips

**Comment by onursumer** [comment]
This seems to be fixed with release 1.8.0
