### ISSUE TITLE
Mutations tab refactoring: y-axis customization is missing option to enter number

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2851]
It would be nice if a user could enter the value for the y-axis threshold... or at least see what the selection is when moving the slider.

![image](https://user-images.githubusercontent.com/11892704/28586744-c52effc4-7142-11e7-9c1f-cc5964547cde.png)

**Comment by jjgao** [comment]
Remove `1` and make `313` as a input.
