### ISSUE TITLE
Mutations tab refactoring: PDB chain description is missing

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2852]
![image](https://user-images.githubusercontent.com/11892704/28586874-294b3b26-7143-11e7-95aa-03952729b0e1.png)

Did this get moved somewhere, or missing altogether?

**Comment by onursumer** [comment]
It is missing, good catch.

**Comment by onursumer** [comment]
here is the content: https://github.com/cBioPortal/mutation-mapper/blob/1475afb5a42c18a3859f45741c68908b34d08692/src/template/pdb_panel/pdb_help_tip.html
