### ISSUE TITLE
Mutations tab refactoring: Initial loading of table longer than before

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2855]
It seems to take longer now to load data ... once loaded though, everything is faster.

Try this query -- click on Mutations tab:

http://www.cbioportal.org/beta/index.do?session_id=59778638498e5df2e293029e&show_samples=false&

vs

http://www.cbioportal.org/index.do?session_id=59778638498e5df2e293029e&show_samples=false&

**Comment by jjgao** [comment]
It is related to #2825 and will be fixed once #2836 is merged.
