### ISSUE TITLE
Mutations tab refactoring: Behavior of y-axis scaling changed a little

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2856]
After manually editing the y-axis, the y-axis would still auto-adjust to show sub-selections of smaller numbers... now it won't anymore.

**Comment by jjgao** [comment]
You mean the animation? I am not sure if we can still support that.

**Comment by schultzn** [comment]
No, not the animation… just the automated adjustment to smaller numbers. I can show you in person.

**Comment by schultzn** [comment]
Did you still need me to explain?
