### ISSUE TITLE
Cap on /mutations/fetch?projects ?

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#2859]
I tried to  query the MSK-IMPACT dataset by starting on the study summary page and then adding genes of interested on the query builder page.  After from submission, I don't get anything under the Mutations Tab.  After some digging, seems as those there is a cap on /mutations/fetch?projects to 1000 samples.  Here is a URL and some screenshots below.

[https://cbioportal.mskcc.org/beta/index.do?session_id=59779309498e5df2e293036e&show_samples=false&](https://cbioportal.mskcc.org/beta/index.do?session_id=59779309498e5df2e293036e&show_samples=false&)

![image](https://user-images.githubusercontent.com/366003/28589490-66fec6be-714c-11e7-839d-8499f975e07e.png)

![image](https://user-images.githubusercontent.com/366003/28589556-a9552df0-714c-11e7-9dbc-1aa6f467b636.png)

**Comment by jjgao** [comment]
On public beta: http://www.cbioportal.org/beta/index.do?session_id=5935a639498e5df2e291988a

**Comment by ersinciftci** [comment]
Should be fixed after this https://github.com/cBioPortal/cbioportal/issues/2836 is merged.
