### ISSUE TITLE
Lollipop diagram will not load

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#2860]
After submitting query, the Mutations-CDKN2A tab does not load the lollipop diagram (the others render if there are mutations in the genes).

Here is URL:

[https://cbioportal.mskcc.org/beta/index.do?session_id=597794c8498e5df2e293038c&show_samples=false&](https://cbioportal.mskcc.org/beta/index.do?session_id=597794c8498e5df2e293038c&show_samples=false&)

![image](https://user-images.githubusercontent.com/366003/28589676-1a06f0a6-714d-11e7-89f0-255d1b120a22.png)

**Comment by jjgao** [comment]
duplicate with #2803

**Comment by schultzn** [comment]
I can't even get the OncoPrint to load for this example.
