### ISSUE TITLE
Samples with 0 mutations should still have a mutations track in the patient view

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2865]
http://www.cbioportal.org/case.do#/patient?studyId=msk_impact_2017&caseId=P-0000291&navCaseIds=P-0000291

In this case, it is not clear that the sample was sequenced for mutations...  we should just have a track there and indicate that there are 0 mutations. This is especially confusing in patients with multiple samples.

![image](https://user-images.githubusercontent.com/11892704/28637473-a48f3356-720f-11e7-98ab-b7f06b215e10.png)

**Comment by jjgao** [comment]
@alisman could you fix it if not hard.

@JiaoJiao123 in the new igv.js based view, please also take this into consideration.

**Comment by jjgao** [comment]
@adamabeshouse this can simplified once #2944 is done.
