### ISSUE TITLE
Slow query

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2866]
http://www.cbioportal.org/index.do?session_id=59790054498e5df2e293143b

**Comment by jjgao** [comment]
OncoKB query slows it down. @zhx828 @adamabeshouse Is there any way we can improve?

![image](https://user-images.githubusercontent.com/840895/28680749-41f09a4e-72c5-11e7-99d5-eae431ed25a5.png)

**Comment by zhx828** [comment]
@jjgao I can take a look what's going on at OncoKB side. It shouldn't this slow.

**Comment by jjgao** [comment]
@zhx828 any insights?

**Comment by zhx828** [comment]
@jjgao I'm still working on it. I don't see any recent changes may affect the performance significantly.

**Comment by adamabeshouse** [comment]
@zhx828 @jjgao I don't see any issues with the query, no redundant/repeated mutations in the query. So I think if there's an issue it would have to be in the backend.

**Comment by zhx828** [comment]
@adamabeshouse yes, this should be at OncoKB side. I will make some changes ASAP.

**Comment by zhx828** [comment]
The performance has been improved at OncoKB side. But due to the nature of the OncoKB caching mechanism, the first load is still slow, I will try to take a look what I can do.
