### ISSUE TITLE
Two-column layout

### ISSUE THREAD

**Issue by adefelicibus** [cBioPortal/cbioportal#2867]
Is it possible to hide the right column of the layout?

In template.tag I found this:
```java
if (fixedWidth == "true") {
    bodyClasses += "fixedWidth";
} 
if (twoColumn == "true" ||  defaultRightColumn == "true") {
    bodyClasses += " twoColumn";
} 
if (noMargin == "true") {
    bodyClasses += " noMargin";
} 
if (cssClass != null) {
    bodyClasses += " " + cssClass;
}
```

but I couldn't find where I'm supposed to set this variables.
I'm not familiar with React, so may I'm missing something.

**Comment by adefelicibus** [comment]
Well, I changed the line below on index.jsp and got what I needed.

```java
<t:template title="<%=siteTitle%>" cssClass="homePage" defaultRightColumn="false" twoColumn="false" fixedWidth="true">
```
Maybe it should be an option in portal.properties.

**Comment by jjgao** [comment]
@adefelicibus good idea to make it into portal.properties. Please feel free to send a pull request to us.
