### ISSUE TITLE
Mutations tab refactoring: Mutations not loading with Study Summary sample selection

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#2868]
When using a selection of samples from the Study Summary, the mutations in the Mutations View do not load.

http://www.cbioportal.org/beta/index.do?session_id=5976417d498e5df2e292f4b3&show_samples=true&clinicallist=NO_CONTEXT_MUTATION_SIGNATURE,METASTATIC_SITE&

![screen shot 2017-07-27 at 14 20 05](https://user-images.githubusercontent.com/9624990/28670050-3c83f3e6-72d7-11e7-83ca-4342665483dd.png)

**Comment by jjgao** [comment]
duplicate with #2859.
