### ISSUE TITLE
Warning message when using 1.8.0 in Safari

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#2870]
![screen shot 2017-07-27 at 17 06 59](https://user-images.githubusercontent.com/9624990/28677646-739bf34e-72ee-11e7-88d4-1741f0cbecfa.png)
 
I guess this has been implemented here: https://github.com/cBioPortal/cbioportal-frontend/pull/442

**Comment by jjgao** [comment]
- [ ] We need to support Safari.
- [ ] Change the message to: "* You current browser is not fully supported. * Please consider using Chrome, Firefox, Safari, or IE11."
- [ ] Add an option "Do not show again"

**Comment by alisman** [comment]
@Tamba32 what's status on this?
