### ISSUE TITLE
Format Validation Status column

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#2872]
The validation status column used to have glyph-icons with colors similar to the mutation status column. Now it is just plain text.

**Comment by jjgao** [comment]
@onursumer let's hide the Validation Status column by default (and plain text is find in that case). @schultzn please comment if you think otherwise.

**Comment by schultzn** [comment]
Agreed.

**Comment by jjgao** [comment]
For consistency with MS, let's format it.
