### ISSUE TITLE
patient/samples not showing up in clinical data tab

### ISSUE THREAD

**Issue by ao508** [cBioPortal/cbioportal#2876]
In example I ran into:
- imported split clinical data for a study (`data_clinical_patient.txt`, `data_clinical_sample.txt`)
- rows that appear in the clinical tab on study summary page only appear for patient/samples that have data in both of those db tables that we import into

Ex: 

| pid/sid | has patient clin data | has sample clin data | shows up in clin tab |
|--------|---------------------|--------------------- |--------------------- |
| pt 1      | yes                            | yes                              | yes                             |
| pt 2      | yes                           | yes                              | yes                             |  
| pt 3      | no                            | yes                              | no                               |

Please feel free to reach out to me for more clarification on the issue or if you have any questions.

@inodb Are you the right person to talk to?

**Comment by jjgao** [comment]
@angelicaochoa do you have a link to an example patient?

**Comment by jjgao** [comment]
@inodb could you follow up?

**Comment by inodb** [comment]
ok!

**Comment by inodb** [comment]
We couldn't reproduce this problem, but will leave open for now
