### ISSUE TITLE
Data release issues

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2877]
lung_msk_2017
- [x] Why `MSI Score`, `MSI Comment`, `MSI Type` are all NA. If that's the case, remove the attributes.
- [x] `Sample coverage` should be number instead of string.
- [x] Maybe remove OncoKB Levels b/c it'll change over time and therefore may not be consistent with what's on patient view.
- [x] Remove attribute `12-245 Part C consented`
- [x] Do we have a `oncotree_code` attribute:YES
- [x] Gene Panel data should be curated with the latest gene panel format.

odg_msk_2017
- [x] Remove attribute `IDH1 Mutation` -- it's redundant? Or at least resolve the three NA cases.
- [x] Rename attribute `Msk dept` to "Institute Source" (same as lung_msk_2017) and use value MSKCC and Non-MSKCC
- [x] Is possible to resolve the NA in `1q/19q status`?
- [x] Do we have a `oncotree_code` attribute
- [x] Gene Panel data should be curated with the latest gene panel format.

mel_tsam_liang_2017
- [x] Is `Site of Sample` the same as `Sample Site`? Maybe `Sub-site` can be `Sample sub-site`?
- [x] What is `Primary Depth`?
- [x] Does `Metastasis` indicate whether the sample is metastatic? If so, use Sample_type.
- [x] What is `In Transit`?:disease is in transit.
- [ ] There are two mRNA expression profiles. Are they both z-scores profile? Only z-scores should be queryable. 

bcc_unige_2016
- [x] remove `MRNA Data` and `SCNA Analysis`
- [x] do we need `Other Sample ID`?
- [x] remove `Multiple Tumors`
- [x] add `oncotree_code` -- can `Histological type details` but useful?
- [x] curate the sequencing panel in the right gene panel format (if data not available, reach out to the authors). Rename `CancerPanel` to `bcc_unige_2016_cancer_panel`.

prad_mskcc_2017
- [x] `Mutation Count` should be number (why there are two Mutation Count chart -- one is empty)
- [x] `Sample coverage` should be number
- [ ] Why Gleason is missing for many samples
- [x] add `oncotree_code` 
- [x] Gene Panel data should be curated with the latest gene panel format.

skcm_vanderbilt_mskcc_2015
- [x] Is the sequencing done on WES or Panel (msk-impact?) If panel, curate gene panel.
- [x] `RECIST burden of disease` should be number

skcm_ucla_2016
- [x] remove `BRAF mutation` and `NF1 mutation` attributes

**Comment by ritikakundra** [comment]
@jjgao Thanks for the feedback. Will make the changes.
