### ISSUE TITLE
Patient view cohort column - >100%

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2879]
The cohort percentage shows up as 104.9% in patient view in latest release-1.8.0

![screen shot 2017-07-27 at 5 07 25 pm](https://user-images.githubusercontent.com/1334004/28692357-320a8724-72ee-11e7-88d7-d202e71c9941.png)
 
http://localhost:3000/#/patient?caseId=P04&studyId=lgg_ucsf_2014

**Comment by ersinciftci** [comment]
Small Amazon DB needs to be migrated to 2.3.1 to get this one fixed. So closing it.
