### ISSUE TITLE
change link to study view from patient view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2880]
currently "study.do?cancer_study_id=ucec_tcga_pub". Please change to "study?id=ucec_tcga_pub"

**Comment by adamabeshouse** [comment]
so this would also change how we link to study view from anywhere in the portal, not just patient view, right?

**Comment by jjgao** [comment]
yes, anywhere. @adamabeshouse 

We can still keep the alias `study.do` and `cancer_study_id` in case people bookmarked them. But we should always use the version `study?id=[study_id]` in all places in the code.
