### ISSUE TITLE
Old style URL conversion calls sample-lists on patient view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2881]
It seems that old style URL conversion causes sample-lists to be called infinitely:

<img width="261" alt="screen shot 2017-08-08 at 7 06 23 pm" src="https://user-images.githubusercontent.com/1334004/29098365-0c123232-7c6d-11e7-939d-679a378b7b35.png">

This old style url gives unlimited sample-lists calls on cbioportal:

http://www.cbioportal.org/case.do?cancer_study_id=lgg_ucsf_2014&case_id=P04

But this new one works fine:

http://cbioportal.org/case.do#/patient?caseId=P04&studyId=lgg_ucsf_2014

`sample-lists` shouldn't even be called on patient view, which makes this particularly odd

**Comment by jjgao** [comment]
I don't understand this issue.

**Comment by ecerami** [comment]
@inodb:  can you explain this a bit more?  is this a bug?  what exactly is the issue?

**Comment by inodb** [comment]
@ecerami @jjgao I've tried to update the description a bit. This is only a bug for old style URLs. You can't actually get this bug when navigating from cbioportal.org, but if you open an old style URL from google you might get this issue. The page does work fine, so it's prolly not that big of an issue. Could just cause a big server load if there's a lot of people accessing the patient view this way.

I'm not sure yet what causes the bug, but it has something to do with rewriting the old URL to the new one.

**Comment by jjgao** [comment]
@inodb that's strange. Does the "old style url" page the same?

**Comment by inodb** [comment]
@jjgao Sorry, what do you mean?

**Comment by jjgao** [comment]
@inodb sorry. I mean what's the difference in the code between the two?

**Comment by inodb** [comment]
@jjgao there is some rewrite taking place from old to new parameters: 

https://github.com/cbioportal/cbioportal-frontend/blob/c039dfc8f966f5f285fa2dd615a69d24fc5458d2/src/appBootstrapper.jsx#L74-L79.

Other than that code should be the same. I see the same in the frontend repo, so it's not related to the integration of the frontend and backend:

http://cbioportal-frontend.herokuapp.com/?cancer_study_id=lgg_ucsf_2014&case_id=P04#/patient?caseId=P04&studyId=lgg_ucsf_2014
