### ISSUE TITLE
standardize colors on study summary

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2884]
Currently, the pie charts all use colors in the same order -- so if there's only one value for the entire pie chart, then the pie chart is blue. However, this leads to a very non-intuitive situation for studies that have mutations but no copy number: both of those pie charts are blue, but in one case blue=yes and in the other blue=no (see http://www.cbioportal.org/study?id=mbl_sickkids_2016#summary for example). That's very counter-intuitive as a user. I think that there should be a standard color for yes/no pie charts: blue should always be yes and red should always be no.

A slightly different version of this could also apply to a few other common charts with standard values -- for example, for gender & survival, I think there are color-value associations that are more intuitive than others (e.g. blue=male, red=deceased).

Having some set colors like this will also provide more consistency across studies, which I think benefits all users.

**Comment by jjgao** [comment]
Thanks @tmazor. Hyve is interested in fixing this by assigning fixed colors for certain attributes.

**Comment by tmazor** [comment]
Great -- thanks @jjgao!

@pieterlukasse @zhx828 let me know there's anything I can do to help when you work on this!

**Comment by jjgao** [comment]
@zhx828 as discussed, for the moment, let's hash the case-insensitive values to the same colors.

**Comment by zhx828** [comment]
The issue has been solved in https://github.com/cBioPortal/cbioportal-frontend/pull/1462
