### ISSUE TITLE
"show more" should change when max items is reached

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2885]
When the maximum number of items is reached, can the "show more" button change to either "show less" or get greyed out?

Screenshot below is from cosmic pop-up, but I think the same applies to the list of mutations on the mutations tab.

![image](https://user-images.githubusercontent.com/10508276/28729779-a66899a0-739b-11e7-9438-69f6fb6e1c8f.png)

**Comment by jjgao** [comment]
It will be fixed with #2894
