### ISSUE TITLE
lollipop diagram axis labels overlap

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2886]
For ATRX, the last two labels on the x-axis overlap each other.

http://www.cbioportal.org/beta/index.do?session_id=597b798f498e5df2e2932dd1&show_samples=false&#mutation_details
![image](https://user-images.githubusercontent.com/10508276/28730050-9fbf3bd0-739c-11e7-9f89-bc3082065358.png)

**Comment by jjgao** [comment]
copy from legacy code to fix it.
