### ISSUE TITLE
display mutation diagram even if there is no mutations

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2888]
http://www.cbioportal.org/beta/index.do?session_id=59764965498e5df2e292f55f&show_samples=false&

![image](https://user-images.githubusercontent.com/840895/28734132-6bb8ca20-73ad-11e7-9fca-7d2a41ef7577.png)

**Comment by onursumer** [comment]
Looks like this is already fixed with release 1.8.0
