### ISSUE TITLE
mutation assessor is NA for a mutation that should be "high"

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2892]
IDH1 R132H mutation is listed with Mutation Assessor impact "NA" when it should be "High". This is happening in at least 2 studies. Other IDH1 mutations are properly annotated.

http://www.cbioportal.org/beta/index.do?session_id=597f717d498e5df2e2934835&show_samples=false&
![image](https://user-images.githubusercontent.com/10508276/28791620-0e349c9e-75fb-11e7-992c-28ef36e4a540.png)

http://www.cbioportal.org/beta/index.do?session_id=5970819f498e5df2e292c5f6&show_samples=false&
![image](https://user-images.githubusercontent.com/10508276/28791718-4c5790f8-75fb-11e7-8cb2-3ca61961cd29.png)

**Comment by jjgao** [comment]
This is data issue -- it happens to the old site too. We are going to update the MA integration with their api and will solve this problem.
