### ISSUE TITLE
mutations tab columns are too wide

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2893]
When the default loading of the mutations tab has the cancer type hidden, the COSMIC & # mut in sample columns are so wide that the numbers start to the right of the column name

http://www.cbioportal.org/beta/index.do?session_id=597f717d498e5df2e2934835&show_samples=false&
![image](https://user-images.githubusercontent.com/10508276/28791882-d236b3ca-75fb-11e7-83e2-fac051c30150.png)

**Comment by jjgao** [comment]
Maybe `COSMIC` and `# MUT IN SAMPLE` should have a max-width?
