### ISSUE TITLE
update cancer gene list to the oncokb list

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2902]
Update the txt file and the links from pages.

http://oncokb.org/#/cancerGenes

http://oncokb.org/api/v1/utils/cancerGeneList

**Comment by jjgao** [comment]
@zhx828 can we do this soon? or better wait for the refactored page?

**Comment by zhx828** [comment]
@jjgao I think we should do this in the new study view refactoring effort.

**Comment by jjgao** [comment]
@zhx828 ok.

**Comment by jjgao** [comment]
@zhx828 are we going to show all mutated genes and CNA genes in the new study view?

**Comment by zhx828** [comment]
@jjgao we will.
