### ISSUE TITLE
Share OncoKB annotation between OncoPrint and Mutations tabs

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2903]
Currently, the OncoPrint and Mutations tabs load the same OncoKB annotation separately. When refactoring OncoPrint, it would be great if we can put the date in the store that can be shared between the two tabs. By doing that, we will also remove duplicate loading code.

**Comment by jjgao** [comment]
The same is true for the core mutations data.

**Comment by adamabeshouse** [comment]
done in refactor
