### ISSUE TITLE
Mutation Rate information is missing for some queries

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#2909]
http://www.cbioportal.org/beta/index.do?session_id=597b6dbc498e5df2e2932d63&show_samples=false&

![missing_mutation_rate](https://user-images.githubusercontent.com/3604198/28900081-9960d3c4-77bc-11e7-9685-9420855cd4c5.png)

A quick debug shows that we are fetching all the samples in order to calculate the mutation rates. But the `samples` end point is limited to 1000: ```"sampleIdentifiers size must be between 1 and 1000"```

**Comment by alisman** [comment]
@onursumer @adamabeshouse Lets discuss what to do here.  It seems for any resource where we are subject to a limit like this, we need to make multiple fetches.
