### ISSUE TITLE
Mutation table too condensed

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2917]
Lets either reposition the icon or add more padding.

![pasted image at 2017_08_02 11_19 pm](https://user-images.githubusercontent.com/186521/28937492-05847046-7859-11e7-84f6-c3b1973d9fbd.png)

This is minor: the table seems a little too dense, and the OncoKB level annotation is at the edge of the cell. Maybe add a pixel more of padding on either side? Just a thought...

**Comment by alisman** [comment]
@zhx828 There is a slight different I think in the height/placement of the onkcokb indicator when it has two indicator bubbles (vs. only one). This results in the above issue.   Unless I'm mistaken, I think it would be better to adjust icon than to add more padding.

**Comment by zhx828** [comment]
@alisman I agree with you. Just verified. I will update the oncokb style.
