### ISSUE TITLE
Better way to get germline mutation frequency denominator

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2918]
Currently we are using `12_245_PARTC_CONSENTED` to decide whether a sample was profiled for germline mutations. In order to get that, the list of patients is retrieved first (based on sample IDs), and the clinical data for `12_245_PARTC_CONSENTED` is retrieved.

To simplify the process (and make it less hacky), we will create a sample list for germline profiled samples, then it can be used directly.

**Comment by inodb** [comment]
@jjgao This is perhaps cleaner, but it does result in redundancy in the database (two indicators for the same thing). Or are you also proposing to remove the `12_245_PARTC_CONSENTED` clinical attribute?

**Comment by onursumer** [comment]
Hi @n1zea144, any updates on this one?

**Comment by n1zea144** [comment]
Hi @onursumer This is complete.  Zack must have forgotten to close the ticket.

![image](https://user-images.githubusercontent.com/366003/29190837-95bd2d98-7de9-11e7-951d-91899819a949.png)

**Comment by jjgao** [comment]
Thanks, @n1zea144.

@onursumer the case is `[study_id]_germline`. Please simplify the current frontend code.
