### ISSUE TITLE
pan-cancer histogram: use cbioportal-client.js instead of QueryBuilder/Dao

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#292]
We are phasing out the old architecture of QueryBuilder/Dao and plan to switch to the new API and API client. Features should talk to the data/session manager or client.js rather than talking to the backend directly.

https://github.com/cBioPortal/cbioportal/wiki/The-API-and-API-Client-%5BBeta%5D

**Comment by pieterlukasse** [comment]
I would like to wait with this until we have a more fine grained API in cbioportal-client, including some services that return summary data, as discussed in  https://docs.google.com/document/d/12kIyzs6Gimzolt7Zyqg7X4OASG86utPMoa_LbIkxydo/edit and https://docs.google.com/document/d/14NNneft9PCC3qgmVXVflMkI3jTETYjPVtCVK-77yBzM/edit.
