### ISSUE TITLE
its impossible to read tooltips in genomic tracks

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#2932]
It widens to fill the whole page, and so the tooltip is never readable. 

![image](https://user-images.githubusercontent.com/636232/28988062-164aa4a2-793c-11e7-818b-01c5e1bab586.png)

**Comment by ecerami** [comment]
@adamabeshouse:  can you provide an example URL where you see this issue?  tx

**Comment by adamabeshouse** [comment]
http://www.cbioportal.org/case.do#/patient?studyId=msk_impact_2017&caseId=P-0000291&navCaseIds=P-0000291

**Comment by adamabeshouse** [comment]
but its fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/547
