### ISSUE TITLE
add documentation for civic properties

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#2935]
Currently there's no explanation of `show.civic`. Only some part about oncoprint:

http://cbioportal.readthedocs.io/en/latest/portal.properties-Reference.html?highlight=civic#oncoprint

**Comment by pieterlukasse** [comment]
yes, would be clearer if civic is documented in a separate "civic" section instead of oncoprint section.

**Comment by oplantalech** [comment]
@inodb @pieterlukasse There was a typo in the format, I fixed it.
