### ISSUE TITLE
Save user interactions / sections into session

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2938]
Currently, we only save the query parameters to the session service.

We would like to save state of the page to the session as well. For example, a user may add a new clinical attribute and order by it (currently there is no way for her to save it). The suer should be able to come back to the side with the session ID and load up the same view.

Potentially we can save the whole mobx store.

**Comment by jjgao** [comment]
Here are some related discussions in the @session-service channel.

https://cbioportal.slack.com/archives/C0BE3KF4L/p1502120197641345

JJ Gao [10:56 AM] 
@manda We are thinking of adding more data into the session, e.g. the state (order, filtering, etc) of oncoprint. What do you think would be the best way? Creating new sessions when states change? Or modify the current session? Ideally, we should be able to send the change instead of the whole new session  when states change.


Manda Wilson
[10:58 AM] 
The easiest thing is adding the state to the URL (probably in after the #) and then it would automatically be saved when that user clicks on "bookmark".  I think clicking on "bookmark" already creates a new session anyway.


JJ Gao [11:18 AM] 
@manda it would not be possible to add all the states to the url. And we are going to have more queries with custom case list (direct query from study view). For those queries, sessions are created immediately.


Manda Wilson
[11:21 AM] 
I don't think sessions are created until a user clicks on the bookmark tab.  I would have to double check how it works, but I think it then saves everything in the request, and the session, and everything in the url after the hash.


[11:21] 
Let me check.


Manda Wilson
[11:36 AM] 
I guess I haven't looked at the new code, but in the old code wherever there was this: `addSessionServiceBookmark(window.location.href, $(this).children("#bookmark-result-tab").data('session'));` e.g. portal/src/main/webapp/WEB-INF/jsp/visualize.jsp you would have to first modify the session object before passing it as a parameter to that method.


[11:37] 
The URL hash info is collected automatically here: https://github.com/cBioPortal/cbioportal/blob/rc/portal/src/main/webapp/js/src/cgx_jquery.js#L203
GitHub
cBioPortal/cbioportal
cbioportal - cBioPortal for Cancer Genomics
 


[11:39] 
Then it is added back here: https://github.com/cBioPortal/cbioportal/blob/rc/core/src/main/java/org/mskcc/cbio/portal/util/SessionServiceFilter.java#L80
GitHub
cBioPortal/cbioportal
cbioportal - cBioPortal for Cancer Genomics
 


[11:39] 
So something like that could be done again.


[11:41] 
So to summarize in the url hash example, cgx_query.js knows there is more information that needs collecting, and adds it to the session object.  Then the session service filter knows it needs to add that information back to the URL when a user goes back to that session they saved.


[11:42] 
Everything that was in the user's request parameter map has already been saved in the session.


[11:42] 
I think anything in the Tomcat session and not the request parameter map is not currently stored.


JJ Gao [2:06 PM] 
Thanks @manda. We will need to save more dynamic state in the frontend. For example, a user may enable/disable oncokb annotation in the oncoprint.


Manda Wilson
[2:07 PM] 
Sure,  you should be able to modify the session object that I pointed to above, like I did for the url hash information, and then figure out a way to pass that information back to the front end when they pull the session back up like I do in SessionServiceFilter.java

**Comment by ecerami** [comment]
@jjgao: feature request or refactoring?

**Comment by jjgao** [comment]
@ecerami I think this is an important enhancement that the refactoring effort can enable. We can do this at the final step but we should be mindful of this when refactoring.
