### ISSUE TITLE
make oncoprintjs a node package

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2940]
It'd be good to make the oncoprintjs on node for the new frontend to consume.

@pambot has volunteered to do this.

**Comment by inodb** [comment]
Done in https://github.com/cBioPortal/oncoprintjs/commit/9f8fe54cb3bd1ae0cb179672dfb6bd72a19a6e85 and https://github.com/cBioPortal/oncoprintjs/commit/87094d280a8d6c3de09e38c221432411bb516e22

See: https://www.npmjs.com/package/oncoprintjs

Releasing a new version is now:

```
vi package.json # (update version number to v1.0.2)
git commit -am 'Update version v1.0.2'
gut tag v1.0.2 -m 'New version w really cool features'
git push --tags
```
