### ISSUE TITLE
Add 2 new fields in Sample model, isSequenced and hasSegment

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2944]

**Comment by jjgao** [comment]
@ersinciftci is it also possible to do a similar api change for a study? The study view page needs this as well.

**Comment by jjgao** [comment]
@ersinciftci can we also do the same for study so that we can decide whether the `MUT vs CNA` plots should be generated -- maybe another issue? cc'ing @zhx828

**Comment by ersinciftci** [comment]
@jjgao sorry didn't see this, yeah it can be another issue.
