### ISSUE TITLE
Display "NA" instead of NaN when data is missing in oncoprint heatmap

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2955]
Currently oncoprint heatmap tooltip displays NaN when data is missing:

![image](https://user-images.githubusercontent.com/2900303/29162992-5b391052-7dbb-11e7-9ad4-50402353cc47.png)

The tooltip should display "NA" or "N/A" in this case instead of "NaN". NaN implies a number conversion error, which should not really be the case here, and thus understandably leads to confusion. 

Ideally, the legend will also display an entry for the grey color, similar to what has been done here: https://github.com/thehyve/cbioportal/pull/18

**Comment by adamabeshouse** [comment]
done in refactor
