### ISSUE TITLE
duplicated loading of data in oncoprint

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2956]
when adding 2 heatmap tracks to oncoprint, 4 calls to `geneticprofiledata` are made (see screenshot):

![image](https://user-images.githubusercontent.com/2900303/29163502-fcf8d16a-7dbc-11e7-936c-0a6042eae6eb.png)

Form data 1st call:
```
genetic_profile_ids:luad_tcga_rna_seq_v2_mrna_median_Zscores
genes:OCLN
sample_list_id:luad_tcga_3way_complete
```

Form data 2nd call (exactly the same as 1st call):
```
genetic_profile_ids:luad_tcga_rna_seq_v2_mrna_median_Zscores
genes:OCLN
sample_list_id:luad_tcga_3way_complete
```

etc.

As a general remark: adding heatmap tracks is very slow. Perhaps partly due to doing things twice. A fix to this issue could improve the performance as well :)

**Comment by adamabeshouse** [comment]
fixed in refactor
