### ISSUE TITLE
Study view bugs based on Pieter's feedback

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#296]
- [x] Pie-chart breadcrumb should be removed if unselected sample has been selected on Scatter Plot. (See Scatter Plot, Scenario 1)
- [x] Pie-chart breadcrumb should be removed if selected same has been unselected on Scatter Plot. (See Scatter Plot, Scenario 2)
- [x] If Scatter Plot has been removed, all breadcrumbs should still apply except the one of scatterplot. (See Scatter Plot, Scenario 3)
- [x] Change mousepointer cursor is not changed for the checkbox (See Table, Scenario 1)
- [x] Remove Scatter Plot breadcrumb(or change back to Scatter selection) after deselecting the selected table in MutatedGene/CNA tables when Scatter Plot selection is applied. (See Table, Scenario 2)
- [x] Remove Scatter Plot breadcrumb(or change back to Scatter selection) after removing the selected table in MutatedGene/CNA tables when Scatter Plot selection is applied. (See Table, Scenario 3)
- [x] Table row filtering is not applied after deselecting sample from Scatter Plot (or removing Scatter Plot) (See Table, Scenario 4)
- [x] Table should be reset after selecting samples from Scatter Plot (See Table, Scenario 5)
- [x] Remove table filter after removing table (See Table, Scenario 6)

Most of cases are related to Scatter Plot selection. Should we treat it as special chart and remove other filters if any selection made on Scatter Plot?

Original propose is here [link](https://docs.google.com/document/d/1BhoBxmqD7EJVYj6qwoswIJo_3V7uab8aVbxJBxizOXo/edit#)

**Comment by jjgao** [comment]
@zhx828 could you itemize this issue?

**Comment by zhx828** [comment]
@jjgao I have updated the list. Please take a little look. We may need more discussion on these items. @aderidder Could you take a look and let me know if anything didn't add in here or misunderstood? Thanks.

**Comment by aderidder** [comment]
Hi @zhx828, sure no problem:
For scatterplot scenario 1, does the shift-click on the scatterplot already properly add the item? Or should we add that to the to-do list?
For scatterplot scenario 2, I think the idea was that if you have a filter and deselect an item in the scatterplot, all filters should be removed and a filter/breadcrumb should be added for the scatterplot
Rest seems fine to me

**Comment by jjgao** [comment]
@zhx828 I feeling is that none of them have a high priority but you have to show me in person :)

**Comment by zhx828** [comment]
This issue should be solved in https://github.com/cBioPortal/cbioportal/pull/1405
