### ISSUE TITLE
Cross-cancer page and Query page "Only CNA" option not working

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2962]
Selecting the option "Only CNA" in query page when doing a cross-cancer query still results in a cross cancer view where mutations are shown in the histogram (see screenshot):

![image](https://user-images.githubusercontent.com/2900303/29206024-545c30e6-7e80-11e7-9d6b-db2238fc3f6c.png)

Furthermore, the histogram has *no legend* with information about the colors. 

Reported by user here: https://groups.google.com/forum/#!topic/cbioportal/AXpMP6Kuqls

**Comment by jjgao** [comment]
"Only Mutation" is not working either.

It seems like the selection is not passed to cross-cancer.do.

**Comment by jjgao** [comment]
![image](https://user-images.githubusercontent.com/840895/29291054-4f9a07ee-8110-11e7-9372-e4df75e853d6.png)
