### ISSUE TITLE
Add Deprecation Text to Top of Web API Page

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#2967]
We need to add Deprecation text to the Top of the Web API Page.

Suggested text, all in red or prominent:

Note:  This web API is now deprecated, and will be officially taken down on August 1, 2018.  Please check out our new Beta Web API [w/ link]/

**Comment by jjgao** [comment]
We will do this after we release and commit to the new API.

**Comment by ecerami** [comment]
@jjgao @inodb @alisman:  any objection to me adding the deprecation text to the current web API page?  I think the new API is still too buried.

**Comment by inodb** [comment]
@ecerami yeah would be great! Thanks!

**Comment by ecerami** [comment]
@inodb @jjgao @alisman:  I was thinking something like this.

![image](https://user-images.githubusercontent.com/1009066/75673917-0ccc2300-5c52-11ea-8400-213166933906.png)

**Comment by alisman** [comment]
@ecerami you can use bootstrap styles for the alert message.   <div className="alert alert-info">...</div>

**Comment by inodb** [comment]
there is a deprecation message now: https://docs.cbioportal.org/6.-web-api-and-clients/api-and-api-clients#r-client

See headers for each:

<img width="344" alt="Screen Shot 2020-06-01 at 11 35 57 AM" src="https://user-images.githubusercontent.com/1334004/83425731-1f462c00-a3fc-11ea-980c-2ea192184fb2.png">

<img width="236" alt="Screen Shot 2020-06-01 at 11 36 05 AM" src="https://user-images.githubusercontent.com/1334004/83425727-1f462c00-a3fc-11ea-9b3c-acb0a6f8e7c9.png">
