### ISSUE TITLE
Embed the Swagger API Page into the larger cBioPortal shell

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#2969]
We need to emded this page:  http://www.cbioportal.org/api/swagger-ui.html into the regular cBioPortal shell.

**Comment by ecerami** [comment]
@jjgao @inodb @alisman:  I thought I could also try this one.  Maybe I could just use an iframe?

**Comment by inodb** [comment]
@ecerami I'm not sure how easy this would be actually. There are links to particular endpoints e.g. https://www.cbioportal.org/api/swagger-ui.html#/C._Patients/getAllPatientsUsingGET. I don't think that works with IFrames?

The generated API seems more like a full reference than user friendly API documentation. So maybe it is fine that it's not inside the cBioPortal shell? We could e.g. write new documentation that fits in the cBioPortal shell. Then point to cbioportal.org/api for full reference of all endpoints. At the top top of the reference page we could point to our "user friendly docs". Was thinking to do some general overview of the API and specific examples with Jupyter Notebooks for Python and R

**Comment by ecerami** [comment]
@inodb yeah, sounds good to me.  I will close for now, and we can always revisit later.
