### ISSUE TITLE
oncoprint minimap doesn't move when clinical tracks are added

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2970]
Go here: http://www.cbioportal.org/index.do?session_id=59690649498e5df2e292870c&show_samples=false&&&
Open minimap
Then add a clinical track
Minimap doesn't move down so it ends up covering part of OncoPrint:
![image](https://user-images.githubusercontent.com/10508276/29225622-079fc318-7e9d-11e7-9277-3f5324a13e0c.png)

**Comment by adamabeshouse** [comment]
I'm not sure what the desired behavior here would be - I guess it should stay in the bottom right until the user tries to drag it? because if the user has already moved it around I dont think it should be adjusted by the new track.

**Comment by jjgao** [comment]
@adamabeshouse given other priorities, I just put it in icebox for now.
