### ISSUE TITLE
oncoprint minimap hover text extends over the boundary box

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2972]
When hovering over the minimap button, the text bubble that appears extends over the boundary box but should probably be shifted left so it doesn't do that. 

![image](https://user-images.githubusercontent.com/10508276/29225994-5d5c6d46-7e9e-11e7-9191-f6958b5cc91f.png)

![image](https://user-images.githubusercontent.com/10508276/29225998-63b57638-7e9e-11e7-9eb0-b0ddfd265943.png)

**Comment by jjgao** [comment]
We can delay this until later.
