### ISSUE TITLE
Data not loading from query?

### ISSUE THREAD

**Issue by alexbaras** [cBioPortal/cbioportal#2980]
The results of a query seem to not be properly loading into my browser. 
Query was with nci60 for proliferation gene-set (just as an example)

oncoprint tab
![image](https://user-images.githubusercontent.com/8574243/29288593-4c4357de-8107-11e7-8672-b3ebd99e1427.png)

download tab
![image](https://user-images.githubusercontent.com/8574243/29288673-9ba09508-8107-11e7-99e2-ccd0635c4a74.png)

**Comment by jjgao** [comment]
Hi @alexbaras could you please paste your query url?

**Comment by alexbaras** [comment]
This was occurring independent of the specific query or study I was looking at.

On Aug 14, 2017 3:55 PM, JianJiong Gao <notifications@github.com> wrote:

Hi @alexbaras<https://github.com/alexbaras> could you please paste your query url?

**Comment by alexbaras** [comment]
Results were the same using Firefox and chrome within Ubuntu Linux

On Aug 14, 2017 3:56 PM, Alex Baras <baras@jhmi.edu> wrote:
This was occurring independent of the specific query or study I was looking at.

On Aug 14, 2017 3:55 PM, JianJiong Gao <notifications@github.com> wrote:

Hi @alexbaras<https://github.com/alexbaras> could you please paste your query url?

**Comment by jjgao** [comment]
@alexbaras Thanks. We couldn't reproduce the error. Do you see any error message in the Chrome console?

![image](https://user-images.githubusercontent.com/840895/29323615-738cd966-81af-11e7-9a3e-fe8bbbf092d0.png)

**Comment by alexbaras** [comment]
yes there appears to be an error message


is the embedded screen shot legible?



[cid:88a646b1-facf-4933-bdd0-855656494c0a]

________________________________

**Comment by alexbaras** [comment]
Additional update, this error is specific to chrome/firefox on Linux OS


Chrome on Windows works fine, which you already knew :)


-Alex


________________________________

**Comment by jjgao** [comment]
Thanks, @alexbaras. The screenshot didn't show up. Could you pasted in on github?

https://github.com/cBioPortal/cbioportal/issues/2980

**Comment by alexbaras** [comment]
![image](https://user-images.githubusercontent.com/8574243/29372455-2847775c-8279-11e7-928b-b9e70290c0b7.png)

**Comment by alexbaras** [comment]
![image](https://user-images.githubusercontent.com/8574243/29372537-71c7224c-8279-11e7-8597-3547cfdd5aba.png)

**Comment by jjgao** [comment]
@adamabeshouse does it look like @alexbaras's browser does not have proper WebGL support?

**Comment by adamabeshouse** [comment]
@jjgao I've never seen this before.. some googling shows that it may be a hardware compatibility issue with certain shader language features. I don't think I could debug remotely. Maybe we can look on @onursumer machine tomorrow.

**Comment by alexbaras** [comment]
just for fun

here is the firefox error

this is a linux OS issue, windows and mac for chrome and firefox are fine

![image](https://user-images.githubusercontent.com/8574243/29439894-e0377c52-838e-11e7-95a5-89fcde9a0df0.png)

**Comment by adamabeshouse** [comment]
it might be a linux + hardware issue... we have someone here who runs linux and never had a problem. Are other people you work with having the same issue?

**Comment by alexbaras** [comment]
This is occurring on my laptop (dell precision mobile 7000 series) running up to date ubuntu 16 LTS on chrome browser.

Then I tested on one of my servers (same OS and browser; obviously different hardware) ... and there is no problem.

Therefore, I am closing this issue as it appears to be specific to my laptop?

Thanks for everyone's time looking into this

-Alex

**Comment by alexbaras** [comment]
Brief update (This was a linux chrome issue)
Turns out if I turn off hardware acceleration, the problem went away.

-Alex

**Comment by adamabeshouse** [comment]
great, thanks for the update @alexbaras. Glad it's not a bug on our end 😁
