### ISSUE TITLE
mutual exclusivity tab should show q-values

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#2981]

**Comment by jjgao** [comment]
We could do a simple Bonferroni adjusted p-value, ie. p-value divided by the number of pairs of genes. @ersinciftci @ecerami: Maybe we can squeeze that into the new component?

**Comment by adamabeshouse** [comment]
you mean multiplied ;)

**Comment by jjgao** [comment]
I mean multiplied :)

**Comment by jjgao** [comment]
Column name: Adjust p-value
calculation: p-value times the number of comparison, i.e. p x n x(n-1) / 2.
tooltip: Bonferroni adjusted p-value
