### ISSUE TITLE
patient view next/prev patient buttons get misaligned with long tumor type names

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2989]
When the tumor type name is long the next/prev buttons end up on two rows even though there is actually plenty of space for them to stay together on one row:

http://www.cbioportal.org/genie/case.do#/patient?caseId=GENIE-NKI-KTWZ&navCaseIds=GENIE-MSK-P-0003260%2CGENIE-MSK-P-0004954%2CGENIE-NKI-KTWZ&studyId=genie_public
![image](https://user-images.githubusercontent.com/10508276/29325494-e29c4232-81b5-11e7-914f-dd2f5b7465f9.png)

![image](https://user-images.githubusercontent.com/10508276/29325496-e86e4cc8-81b5-11e7-9912-55554b048977.png)

**Comment by tmazor** [comment]
This is still an issue:
https://genie.cbioportal.org/patient?caseId=GENIE-MSK-P-0003260&studyId=genie_public#navCaseIds=genie_public:GENIE-MSK-P-0003260,genie_public:GENIE-MSK-P-0023752
![image](https://user-images.githubusercontent.com/10508276/76457371-0f93ea00-63af-11ea-8b5e-7a4120fddb5f.png)

**Comment by alisman** [comment]
@tmazor fixed a while back in unrelated PR
