### ISSUE TITLE
add banner to tabs that don't respect OQL

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2990]
The Plots, Mutations and Co-Expression tabs don't respect OQL but all other tabs do.

There are some great suggestions below for longer term solutions, but for now we need a simple notification that alerts the user.

If a user submits a query that includes OQL, those three tabs need a warning on the top that says "This tab does not reflect the OQL specification from your query."

Here's an example of what the plots tab should look like:
![image](https://user-images.githubusercontent.com/10508276/33387571-a34934f2-d4fb-11e7-933c-6ff638ad5990.png)

The Mutations & Co-Expression tabs should similarly have that notification above the content of the tab.

**Comment by tmazor** [comment]
I was describing OQL to a group of users today and based on their feedback, I think it's very important to make clear which tabs do/don't respect OQL. I understand that making all tabs respect OQL is a larger project, but I think we have an obligation to let a user know when the website isn't doing what they think it's doing.

@jjgao @ecerami is this something that we can do in the near term?

@adamabeshouse I think I remember you proposing a way to do this, but I can't remember where that was. Do you remember?

**Comment by adamabeshouse** [comment]
@tmazor hm I actually don't remember making a suggestion on this :D but maybe in the tab text we  could put an indicating icon?

**Comment by jjgao** [comment]
We really have two different types of tabs/analyses:

1. OncoPrint, Mutex, Enrichments, Survival separates the samples into two groups and compare them. (They respect OQL)
2. The other tabs with no comparison functionality in respect to "altered" and "unaltered" samples. (Not sure how they can respect OQL except for Mutations tab).

Just thinking it aloud: maybe we can separate the tabs into "comparative analysis tab" and "general analysis tab". That may actually pave the way for cohort comparison features.

cc'ing @schultzn and @ecerami

**Comment by tmazor** [comment]
@jjgao the Plots & Co-expression tabs both highlight samples with mutations and also don't respect OQL, so those tabs fall into the same boat as the Mutations tab.

@adamabeshouse whoops I guess I'm imagining things - but I like the idea of an indicator icon!

**Comment by adamabeshouse** [comment]
@tmazor @jjgao maybe we can design a OQL filter icon to use wherever we want to indicate it, e.g. in the tab header, in the tooltip for highlighted samples with mutations

something like http://fontawesome.io/icon/filter/

**Comment by schultzn** [comment]
I like the idea of two general categories!

I also think we should have a way to show OQL results on the mutations tab. Maybe by graying out non-selected mutations?

**Comment by tmazor** [comment]
I like all of these ideas! Another thought - we could eventually turn the OQL indicator icon into a button that can be used to toggle OQL on/off.

But in the short term, can we add that indicator icon as a first step? I like the icon that @adamabeshouse suggested as a starting point.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3517

**Comment by tmazor** [comment]
I am so excited to see this! But I thought this warning was only going to appear when the user explicitly includes OQL in their query. If the user doesn't use explicit OQL and just writes gene names with the default settings, then the warning is misleading, since the tab is using those same default settings. (does that make sense?)

**Comment by tmazor** [comment]
Also - this warning needs to be added to the Expression tab in a multi-study query. Sorry, I missed that one in my initial list of pages.

**Comment by jjgao** [comment]
Agreed with Tali. @adamabeshouse please only show the warning when advanced OQL is used.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1335

**Comment by tmazor** [comment]
Looks great! One final piece though - this warning needs to be added to the Expression tab also

**Comment by schultzn** [comment]
What about the mutual exclusivity tab? We should probably make it clear there that only events specified by OQL are included in the comparison. 

Maybe simply add:

This tab reflects the OQL specification from your query.

What do you think?

**Comment by jjgao** [comment]
@schultzn how about other tabs, e.g. Enrichments and Survival? Maybe we should add a banner to every tab to indicate whether or not OQL is reflected?

**Comment by jjgao** [comment]
created another issue - see above.
