### ISSUE TITLE
OQL specification page needs updating

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#2991]
The OQL page (http://www.cbioportal.org/onco_query_lang_desc.jsp) needs to be updated to the new style.

The text should also be updated to reflect that not all tabs respect OQL. It currently says that "all output" respects OQL:
![image](https://user-images.githubusercontent.com/10508276/29327267-97056dce-81bc-11e7-88f7-f22dec1ca33f.png)

This should be updated to list the specific tabs that do or do not listen to OQL.

**Comment by tmazor** [comment]
Actually some of the content on this page is incorrect. For example, the default visualization uses "deep deletion" not "homozygous deletion" and "hemizygous deletion" isn't included by default anymore:
![image](https://user-images.githubusercontent.com/10508276/29477199-658dbae6-8435-11e7-86d6-8687b4387c78.png)

I'm working on tutorial slides for this now. I will also come up with some updated content for this page.

**Comment by jjgao** [comment]
@tmazor you mentioned you were working on a new spec, so I assign it to you :). @adamabeshouse  and I can help review.

**Comment by jjgao** [comment]
@tmazor do you think it'd useful to make it a separate md doc instead of jsp?

**Comment by tmazor** [comment]
@jjgao I'll create a md file and put the updated documentation in there
