### ISSUE TITLE
HGVSg / HGVSc in cBioPortal

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#2996]
Currently the only HGVS annotation in cBioPortal is HGVSp_Short. This is *unofficial* MAF format and outputted from VEP as HGVSp and converted to the short format in vcf2maf. It is one of the most useful columns for cBioPortal, because it describes a mutation's amino acid change.

HGVSc (for coding) is also a useful annotation outputted by VEP and vcf2maf. Especially for splice sites (i.e. c.418-1G>A), which don't have an amino acid change, this is a useful description. Example and description of the format: http://varnomen.hgvs.org/recommendations/DNA/variant/substitution/

It would be nice if a user can view the HGVSc in the Mutation and Patient view. The data is already present in TCGA MAF files on Datahub and in test MAF files, such as in [study_es_0](https://github.com/cBioPortal/cbioportal/blob/master/core/src/test/scripts/test_data/study_es_0/brca_tcga_pub.maf).

**Comment by jjgao** [comment]
Good idea. Maybe we can take this when connecting portal to genome-nexus.

**Comment by tmazor** [comment]
This feature has also been requested by a user: https://groups.google.com/forum/#!topic/cbioportal/th84YhygjFQ

**Comment by tmazor** [comment]
We have another user request for this: https://groups.google.com/forum/#!topic/cbioportal/XDhP9JNpbwU

@jjgao can we prioritize this?

**Comment by jjgao** [comment]
Yes, I think we are ready to do this now.

Maybe @onursumer or @leexgh can help with this?

It might be also a good idea to do the exon number together with this: https://github.com/cBioPortal/cbioportal/issues/5609

**Comment by sandertan** [comment]
Thanks for adding the HGVSc.

Perhaps a future enhancement would be to add the HGVSg from the MAF file.

**Comment by jjgao** [comment]
yes, we'll do HGVSg as well.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao Thanks for taking care of this!

**Comment by inodb** [comment]
fixed hgvsg is now also a column
