### ISSUE TITLE
sharing widget (replacing Bookmark tab)

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3000]
Something like this (inspired by [NYT](https://www.nytimes.com/2017/08/16/business/trumps-council-ceos.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=a-lede-package-region&region=top-news&WT.nav=top-news)):

![image](https://user-images.githubusercontent.com/840895/29385152-af207fc8-82a4-11e7-9003-45360e5fd04b.png)

When clicking on any of the buttons, a session should be created (if session service is available).

Q: do we still need bitly -- maybe for twitter?

**Comment by alisman** [comment]
@Tamba32 If you go to the bookmark tab, you'll see that we are loading a session url and also a shortened version of same url.  See network panel for how we get the url from the server.  We want to allow for easy sharing of this url using an embed widget from a service such as http://www.addthis.com/
Try to customize the buttons so they are monochrome and unobtrusive (as on NYTimes link above)

**Comment by alisman** [comment]
http://www.cbioportal.org/api-legacy/proxy/session-service/main_session
call the above service, first martialling the data it requires from queryStore.

**Comment by jjgao** [comment]
just make an icon for copying to clipboard.
