### ISSUE TITLE
issue with study selector on pancan portal

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3009]
A user reported: "Even though I select studies, it says “0 studies selected” and I can not submit a query. I tried it in  Safari and chrome, emptied cache, restarted computer etc. No help. Also, nothing happens when I click on “select All”."

![image](https://user-images.githubusercontent.com/840895/29430594-fd2ee790-8362-11e7-91f7-bd226748ea89.png)

![image](https://user-images.githubusercontent.com/840895/29430579-edcf9376-8362-11e7-9ceb-ef98aee3f60e.png)

**Comment by jjgao** [comment]
maybe related to #3011

**Comment by jjgao** [comment]
@alisman has this been resolved?

**Comment by alisman** [comment]
@jjgao I can't reproduce this issue.  I have a vague memory of something like this a while back that we fixed.
