### ISSUE TITLE
transcript issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3017]
Reported by [a user](https://groups.google.com/d/msgid/cbioportal/934d885e-f7f5-1c58-1943-049efad43ee2%40jimmy.harvard.edu?utm_medium=email&utm_source=footer):

"
According to the image at the top, which is linked to UniProt, the variants should be listed according to NM_001203247 (Q15910-1 in UniProt).
 
The MSK-IMPACT Clinical Sequencing Cohort seems to list variants according to NM_004456 (Q15910-2 in UniProt).
·         P-0005826-T01-IM5 – I believe p.G660R should be p.G655R, because in NM_001203247 codon 660 is a Lys/K
·         P-0004062-T01-IM5 – I believe p.Y646N should be p.Y641N (and all the other p.Y646 mutants should be p.Y641)
 
It looks like there may be other cohorts with errors, but that just may be for Y646 which is a hotspot; I didn’t look that much in detail.   12-P412 (Ewing Sarcoma cohort) and TCGA-G8-6907-01 (DLBC (TCGA) cohort) are other examples of possible misalignment.
"

**Comment by jjgao** [comment]
I have downloaded the file from [datahub](https://github.com/cBioPortal/datahub/tree/master/public) and the transcript used is ENST00000320356, which is the same as the [msk override isoform](https://github.com/mskcc/vcf2maf/blob/master/data/isoform_overrides_at_mskcc) instead of the public [uniprot override isoform](https://github.com/mskcc/vcf2maf/blob/master/data/isoform_overrides_uniprot) ENST00000460911.

**Comment by ritikakundra** [comment]
Fixed
