### ISSUE TITLE
Gene panel data not loading in sample_profile table

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3027]
Tested with test study `study_es_0`. The order of events:

```
python metaImport.py \
  -s /Users/sander/Data/cbioportal/core/src/test/scripts/test_data/study_es_0/ \
  -html /Users/sander/Desktop/report_study_es_0.html \
  -u http://localhost:8080/cbioportal \
  -v \
  -o
```

 1. The 10 mutations for sample `TCGA-A1-A0SB-01` are added to `mutations`, and when I refresh the DB after this, this sample is added to `sample_profile` with PANEL_ID is `NULL`:
```
Reading data from:  /Users/sander/Desktop/study_es_0/brca_tcga_pub.maf
Recaching...
Finished recaching...
--> profile id:  59
--> profile name:  Mutations
--> genetic alteration type:  MUTATION_EXTENDED
--> OMA Scores Column Number:  32
--> records inserted into `sample_profile` table: 1
--> records inserted into `mutation_event` table: 10
--> records inserted into `mutation` table: 10
--> total number of data entries skipped (see table below):  3
--> total number of samples: 1
--> total number of genes for which one or more mutation events were stored:  10
```

 2. Three events from fusion data are added to `mutation` and 3 samples added to `sample_profile`. Interestingly, when I refresh the DB at this moment, these samples **contain** PANEL_ID values:
```
Reading data from:  /Users/sander/Desktop/study_es_0/data_fusions.txt
Recaching...
Finished recaching...
--> profile id:  59
--> profile name:  Fusions
--> genetic alteration type:  FUSION
--> records inserted into `mutation_event` table: 3
--> records inserted into `mutation` table: 3
--> records inserted into `sample_profile` table: 3
```

 3. The gene panel data is loaded. After refreshing the DB, `sample_profile` is completely empty.
```
Reading data from:  /Users/sander/Desktop/study_es_0/data_gene_panel_matrix.txt
Recaching...
Finished recaching...
Deleting necessary records from sample_profile.
Loading gene panel profile matrix data to database...
Done.
```
**Result:** `sample_profile` does not contain any sample with mutation genetic profile (note: fusion data is currently added to the mutation genetic profile).

I also noticed 2 other issues:
1. `data_gene_panel_matrix.txt` contains `study_es_0_mutations` instead of `mutations`
2. The genes in `gene_panel_example.txt` are **not** in the example MAF. I suggest replacing these with the genes from the MAF (OR11H1 TMEM247 ABLIM1 ADAMTS20 CADM2 DTNB KAT2A MSH3 MYB NPIPB15 OTOR P2RY10 PIEZO1), making it possible to test the functionality.

**Comment by sandertan** [comment]
This issue only affects mutation genetic profiles. CNA genetic profiles are correctly added to `sample_profile` with correct values in `PANEL_ID`.

**Comment by sheridancbio** [comment]
I'm writing up a separate issue with the tracking of genepanel links to samples in the database, but possibly it is related to this reported issue.

However, I have a suspicion that the import using the scripts package python tools may not properly support the import of gene panels (I am not familiar with running imports through the python scripts). The importing method we use is a java based application, and the code for processing the gene panel input files was added to that code. Maybe @zheins would comment on whether the implementation of the gene panel import was intended to also function when using the scripts package for import? @cBioPortal/backend

**Comment by pieterlukasse** [comment]
@sheridancbio there could still be a problem with @sandertan's description here. I asked him to test again to make sure the sequence of steps he reported here are correct. @sandertan will report back here once tested again.

**Comment by sandertan** [comment]
Apologies for the late reply, I was on holiday. I tested this again, pausing after each step (using a `raw_input("Press Enter to continue..."` in the python code)  and inspected the database. There are no mistakes in initial report.

**Comment by sandertan** [comment]
We identified that the meta file for the MAF file was missing the gene_panel property, although the gene_panel_matrix did contain the sample. Apparently the property is mandatory in this case. In the future it would be nice to remove the property, because of this redundancy. And the property is about the MAF file, and can therefor not say anything about samples that are sequenced but have no mutations found. Therefore the gene_panel_matrix is much more useful.

Fix for test data in https://github.com/cBioPortal/cbioportal/pull/3186

**Comment by sandertan** [comment]
I described the specific bug in https://github.com/cBioPortal/cbioportal/issues/3191
