### ISSUE TITLE
ACC TCGA study loads with empty survival plots

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3029]
The first two plots on ACC TCGA study are survival plots saying "No data available"

http://www.cbioportal.org/study?id=acc_tcga#summary
![image](https://user-images.githubusercontent.com/10508276/29579443-e17e9c5c-8740-11e7-9a87-3181698cefa5.png)

**Comment by zhx828** [comment]
@tmazor @jjgao this is not a bug. This study does have OS_MONTHS/OS_STATUS and DFS_MONTHS/DFS_STATUS.(http://www.cbioportal.org/api-legacy/clinicalattributes?study_id=acc_tcga) That's why both survival plots are generated.

**Comment by jjgao** [comment]
Looks like there is some data issue here. @ritikakundra @yichaoS could you look into it?
