### ISSUE TITLE
OQL keyword parsing bug

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3031]
In the current query interface, OQL assumes that any word it doesn't recognize is a mutation code. 

For example, the following are currently considered valid:

EGFR: CERAMI
EGFR: HOTSPOT

**Proposed fix:**

A mutation code either comes from a defined set of keywords (e.g. missense, nonsense, ... ) or it has a number in it (e.g. V600, V600E, ...). 

We can therefore fix the validation code to only allowing inputs that are either

(1) in a list of pre-defined keywords (MUT, CNA, AMP, MISSENSE, EXP, etc) or
(2) have a number in them (V600, R132H, etc).

If an input doesn't have a number and isn't in the list of keywords, then the OQL parser flags it as an invalid input.

**Note:**

Note that this bug also existed prior to refactoring.

**Comment by ecerami** [comment]
Here are some examples that are currently considered valid:

EGFR: CERAMI
EGFR: HOTPSOT

**Comment by ersinciftci** [comment]
@jjgao Is this `In the currently query interface, OQL assumes that any word it doesn't recognize is a mutation code.` an intended feature, should it work that way? I don't see it documented in http://www.cbioportal.org/onco_query_lang_desc.jsp

**Comment by ersinciftci** [comment]
@tmazor If user entered `EGFR: MUT = CERAMI`, and gets nothing as a result, I guess we wouldn't call this a bug (because you specifically mentioned `OQL assumes that any word it doesn't recognize is a mutation code`). So I think the part that makes looks like a bug is that OQL's assumption, so my proposed solution is OQL shouldn't assume it's a mutation code when it doesn't recognize. But if @jjgao wants this feature specifically, then I think this would be considered an enhancement instead of a bug because OQL doesn't claim it validates mutation codes.

**Comment by ersinciftci** [comment]
Just talked to @tmazor , it seems we need OQL's assumption functionality (even though it's not documented). So my suggestion is to add one more constraint to the validation in addition to has a number in them, it should also start with a letter.

**Comment by jjgao** [comment]
@tmazor @ersinciftci @ecerami: I thought about it more and I think adding a constraint to have a number in the string may not work for all scenarios. For example, we have some hacky data such as mutations such as "VIII deletion", or fusions, or "Promoter mutations". I would vote for sticking to the current implementation but in the OQL spec mention that "OQL assumes that any word it doesn't recognize is a mutation code".

**Comment by adamabeshouse** [comment]
maybe we could add that message below the input box if it detects an unrecognized string that will be interpreted as a mutation?

**Comment by jjgao** [comment]
@adamabeshouse good idea. And also update the oql description.

**Comment by adamabeshouse** [comment]
here's what I have running now
![image](https://user-images.githubusercontent.com/636232/30295314-28794256-970e-11e7-80ec-97758e2143c5.png)

thoughts? @jjgao @tmazor @ersinciftci @ecerami
