### ISSUE TITLE
ssl certificate for cbioportal.org is invalid

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#3038]
This issue was reported by @morungos 
Currently these links throw browser warnings that the certificate for these domains are invalid:
https://cbioportal.org
https://www.cbioportal.org

error message:
Your connection is not private

Attackers might be trying to steal your information from www.cbioportal.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
This server could not prove that it is cbioportal.org; its security certificate is from cbioportal.mskcc.org. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by jjgao** [comment]
We don't have https set up for the public portal. We should really do that. Should we ask Joanne again?

**Comment by inodb** [comment]
I have it working on https://k8s.cbioportal.org so if we make the switch for public portal to k8s that would work. But maybe good to have a temp solution as well

**Comment by jjgao** [comment]
@inodb I think we can wait for the amazon/k8s instance.

**Comment by jjgao** [comment]
captured in #4069
