### ISSUE TITLE
Data release issues

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#304]

**Comment by schultzn** [comment]
Change

Cutaneous squamous cell carcinoma (Dana-Farber, Clin Cancer Res 2015)
Target sequencing of 504 cancer-associated genes in 29 CSCC patients

to

Cutaneous Squamous Cell Carcinoma (DFCI, Clin Cancer Res 2015)
Targeted sequencing of 504 cancer-associated genes in 29 cutaneous squamous cell carcinoma samples

**Comment by schultzn** [comment]
Change 

Pediatric Ewing Sarcoma (Dana-Farber, Cancer Discov 2014)
Whole exome sequencing of 96 pediatric Ewing Sarcoma tumors and 11 cell lines; raw data at 

to

Pediatric Ewing Sarcoma (DFCI, Cancer Discov 2014)
Whole exome sequencing of 96 pediatric Ewing Sarcoma tumors and 11 cell lines

**Comment by schultzn** [comment]
Change

Thymic epithelial tumors (NCI, Nat Genet 2014)
Whole exome sequencing (WXS) of 28 thymic epithelial tumors; raw data at the

to

Thymic Epithelial Tumors (NCI, Nat Genet 2014)
Whole exome sequencing of 28 thymic epithelial tumors

**Comment by schultzn** [comment]
Change

Microdissected Pancreatic Cancer Whole Exome Sequencing (UTSW, Nat Commun 2015)
109 micro-dissected pancreatic cancer cases and normal control tissue were subjected to whole-exome sequencing. Microdissection enriches tumor cellularity and enhances mutation calling.

to

Pancreatic Cancer (UTSW, Nat Commun 2015)
Whole exome sequencing of 109 micro-dissected pancreatic cancer cases and normal control tissue.

**Comment by schultzn** [comment]
Change

Multiregion Sequencing of Clear-Cell Renal Cell Carcinoma (IRC, Nat Genet 2014)
Mutation data from multi region exome sequencing (M-seq) of 10 clear cell renal carcinomas(ccRCCs)

to

Multiregion Sequencing of Clear-Cell Renal Cell Carcinoma (IRC, Nat Genet 2014)
Mutation data from multi region exome sequencing of 10 clear cell renal cell carcinomas (ccRCCs)

**Comment by schultzn** [comment]
Primary sites of this study need to be standardized (upper/lower case issues):
http://www.cbioportal.org/beta/study.do?cancer_study_id=es_iocurie_2014

**Comment by schultzn** [comment]
Was this study not supposed to have multiple samples per patient?
http://www.cbioportal.org/beta/study.do?cancer_study_id=ccrcc_irc_2014

**Comment by jjgao** [comment]
Solved all the study name/description issues. Created separate tickets for the last issues.
