### ISSUE TITLE
Patient view bug for study dlbc_tcga

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#3041]
http://www.cbioportal.org/study?id=dlbc_tcga#clinical
Search for sample: TCGA-FA-A6HO-01
Clicking on the sample takes us to the Patient view page but pop up appears with an error message:
<img width="607" alt="screen shot 2017-08-24 at 11 59 52 am" src="https://user-images.githubusercontent.com/1380237/29680617-22a44414-88d3-11e7-9412-a52d8b6b63a5.png">

The bug was identified while investigating user question: https://groups.google.com/forum/#!topic/cbioportal/Qz_cwpJR9rU

**Comment by jjgao** [comment]
http://www.cbioportal.org/case.do#/patient?studyId=dlbc_tcga&sampleId=TCGA-FA-A6HO-01

**Comment by onursumer** [comment]
@jjgao @alisman A quick debug shows that this is related to a failing Civic request. As a quick fix we can just fail silently on any Civic error (by adding an empy `onError` function for civic request in the store).

**Comment by onursumer** [comment]
Silent failing of Civic prevents the popup error message, but we still have the civic loader icon there spinning forever. I think this should be addressed in the Civic annotation renderer...

**Comment by jjgao** [comment]
@oplantalech @pieterlukasse could you look into the civic issue? Thanks.
