### ISSUE TITLE
Gene panel color missing in oncoprint legend

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3047]
With gene panels we now have a distinction between (1) "no alterations in a sequenced sample" and (2) "sample not sequenced". However, there is no item in the legend for (1) and the only entry in the legend that has a similar color is "Truncating mutation (putative passenger)". See screenshot:

![image](https://user-images.githubusercontent.com/2900303/29768265-e5b18f2e-8be5-11e7-8963-35687277ea54.png)

Solution: 
- [x] add legend for (1) 
- [x] perhaps make the color for "sample not sequenced" white and make the color for (1) the lighter grey color?

**Comment by jjgao** [comment]
+1 on adding legend, maybe just "No alterations"

About color, I like the idea of using white for N/S -- it'd be more like missing data. 

I added Niki for his comment.

**Comment by schultzn** [comment]
+1 on legend.

Not sure about colors. I thought @adamabeshouse tried a couple of different combinations and this one worked best? 

Would need to see some examples ....

**Comment by adamabeshouse** [comment]
I think at the time we decided it didn't look good to have white, but we could try it again

**Comment by jjgao** [comment]
@adamabeshouse could you change add the legend.

For the color, if it is easy to do, could you do a quick mockup using white for N/S and put it side by side with the current one? Thanks.

**Comment by adamabeshouse** [comment]
I think it may be confusing to call the gray rectangle "No alterations" because that rectangle color is still there when there is a mutation. What the gray rectangle really shows is no copy number alteration.

**Comment by jjgao** [comment]
@adamabeshouse that's a good point -- but I think it's probably fine. If there is a mutation or other event displayed on top of the gray rectangle, it is obvious that there is an alteration.

**Comment by jjgao** [comment]
@schultzn @pieterlukasse When using OQL, e.g, MUT=V600E, do you think it's OK to put the legend "No alterations", because there maybe other mutations? Technically it should be "No alterations passing OQL filtering", or maybe "No alterations of interest" (which also covers selection profiles).

**Comment by schultzn** [comment]
I don’t think we have to specify that… we would have to change all legends if a user uses OQL in any of the genes, for any of the data types. That could get tricky.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3137

**Comment by adamabeshouse** [comment]
@schultzn @jjgao @pieterlukasse 
![image](https://user-images.githubusercontent.com/636232/30616299-d5549faa-9d5f-11e7-9b45-f928d8e3b003.png)

![image](https://user-images.githubusercontent.com/636232/30616317-e363eb1e-9d5f-11e7-830c-a6fc5fbc4d77.png)

![image](https://user-images.githubusercontent.com/636232/30616330-e9f47b38-9d5f-11e7-8954-0d486962590b.png)

![image](https://user-images.githubusercontent.com/636232/30616355-f746386c-9d5f-11e7-8178-97425ec040c5.png)

![image](https://user-images.githubusercontent.com/636232/30616363-fe2821d6-9d5f-11e7-8f4e-a91b6bf57383.png)

**Comment by jjgao** [comment]
I like it when it's zoomed out, ie. no white space in between (2nd figure) -- I think it's more clear that the data is missing. Not sure about hte 1st figure though -- should there be a light border to indicate it's a sample?

@schultzn @pieterlukasse @ecerami @tmazor : comments?

**Comment by tmazor** [comment]
Overall I like this - I think the white is a more intuitive "no data" color than the light grey was. I agree with JJ's point that it might be beneficial to have a light border when zoomed in like in the first screenshot. I also think the white box for "Not sequenced" in the legend needs an outline to define it.

My other worry is that while this makes a lot of sense in the context of a multi-gene query where different genes have different coverage, I'm a little worried about how it will look if the query is for a single gene that was only covered in a subset of cases. Will there just be a long set of white boxes going off to the right? @adamabeshouse can you add a screenshot of a query just for SPOP or NFKBIZ?

**Comment by adamabeshouse** [comment]
@tmazor 

![image](https://user-images.githubusercontent.com/636232/30759934-2ceb6cc4-9fa6-11e7-8769-57fcff72fbb8.png)

![image](https://user-images.githubusercontent.com/636232/30759937-332a8f3e-9fa6-11e7-826b-5cdb2caec43b.png)

![image](https://user-images.githubusercontent.com/636232/30759945-3fa49336-9fa6-11e7-83f1-4da66031395c.png)

![image](https://user-images.githubusercontent.com/636232/30759954-46fccd4c-9fa6-11e7-975e-0f310b9d74fa.png)

**Comment by tmazor** [comment]
I think I like it - but I can also see how all that white could be confusing for a user.

@jjgao @schultzn @ecerami @pieterlukasse what do you think?

**Comment by adamabeshouse** [comment]
another option, could be to have NA be signified with a thin horizontal center line on a white rectangle, which would have the effect that when they were squashed together it would appear like an unbroken line.

**Comment by tmazor** [comment]
I like that idea @adamabeshouse - could you do a mock-up like that? Thanks!

**Comment by adamabeshouse** [comment]
@tmazor I think it looks pretty cool!

![image](https://user-images.githubusercontent.com/636232/30878823-b052a9ec-a2cb-11e7-8e75-6ce1a8627827.png)

![image](https://user-images.githubusercontent.com/636232/30878836-bbf451c4-a2cb-11e7-9ce8-4137cbb0d7c0.png)

![image](https://user-images.githubusercontent.com/636232/30878852-c5916a78-a2cb-11e7-8d63-d1ccd413dd21.png)

**Comment by tmazor** [comment]
That's awesome @adamabeshouse - I really like it!

@ecerami @schultzn @jjgao @pieterlukasse what do you all think?

**Comment by adamabeshouse** [comment]
here it is lighter to draw less attention to it
![image](https://user-images.githubusercontent.com/636232/30880769-aaad077a-a2d1-11e7-9c1f-792e5ed1f2e5.png)

![image](https://user-images.githubusercontent.com/636232/30880779-b2122374-a2d1-11e7-8470-5ce55e2c4f5f.png)

![image](https://user-images.githubusercontent.com/636232/30880787-b81147be-a2d1-11e7-972f-675c8740fde0.png)

**Comment by jjgao** [comment]
Yes, it looks awesome! Great design @adamabeshouse!

**Comment by adamabeshouse** [comment]
thanks! :) should we use that new convention for other N/A (e.g. in clinical tracks)? Or stick with the light gray for that, the way it is?

**Comment by jjgao** [comment]
Agreed. We should use the new design for clinical data as well.
