### ISSUE TITLE
Incomplete/misleading information in alteration % in oncoprint tracks when using gene panels

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3048]
The % alteration in oncoprint track label is incomplete and/or misleading when combining two or more genes that are not sequenced in exactly the same set of gene panels. 
Example: some panels in the result below only include one of the two genes. In total there are 8,934 samples where at least one of the genes was sequenced (first figure below), but the number of samples where IFNGR1 was sequenced is 8,455, and IFNGR1 is altered in 55 samples (see last figure below). The 0.7% reported for IFNGR1 in the first and second figure is correctly calculated from 55/8,455, but this is not reported anywhere in the first figure (i.e. this is the issue to be solved).

![image](https://user-images.githubusercontent.com/2900303/29768698-9b9c1f24-8be7-11e7-8175-e0006f4e7628.png)

![image](https://user-images.githubusercontent.com/2900303/29768725-b424dcc0-8be7-11e7-9a9b-2c0b3a077624.png)

Solution:
- [ ] add a tooltip for the 0.7% label. When hovering such a label, the user would see the calculation used (in this example 55/8,455).

**Comment by jjgao** [comment]
good idea to add a tooltip.

**Comment by schultzn** [comment]
yes, tooltip is good.. but maybe we need to add an asterisk behind the frequency to make users aware that there is additional information
