### ISSUE TITLE
Mutations tab: loading germline list multiple times

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3051]
http://www.cbioportal.org/index.do?session_id=59a5caa4498e5df2e2949a9b

We are loading the germline sample list for every gene. Can we just load them once?

![image](https://user-images.githubusercontent.com/840895/29842142-f642bf2a-8cd5-11e7-8924-9d1b1c80c565.png)

Can we also capture the error and maybe display some message?

**Comment by adamabeshouse** [comment]
this doesnt appear to be happening anymore
