### ISSUE TITLE
query and download show studies differently

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3065]
Not actually sure if this is a bug or on purpose, but I just noticed that the studies list on the homepage has an additional level of grouping by disease in the query study selection that isn't present in the download study selection:

![image](https://user-images.githubusercontent.com/10508276/29981854-43a3c22a-8f1d-11e7-80b2-8540f378dafd.png)

![image](https://user-images.githubusercontent.com/10508276/29981861-4baa47b4-8f1d-11e7-87a4-91b97ef70baf.png)

**Comment by jjgao** [comment]
It's probably on purpose but not sure who's design that was. In Download Data, one can only select one study, so I don't see it very useful to have many categories -- maybe that's the reason. Anyway, I'll close this. I don't think it's worth the effort the fix this one.
