### ISSUE TITLE
non-MAF variant classification values

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3068]
It is unclear which values for variant classifications are allowed in cBioPortal. According to the current documentation cBioPortal follows the MAF-format, but in the code other classifications are also allowed, such as here:
https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/js/api/cbioportal-datamanager.js#L123 

and here:
https://github.com/cBioPortal/mutation-mapper/blob/master/src/js/util/VepParser.js#L37

Recently @pieterlukasse added validation for the official MAF variant classifications in https://github.com/cBioPortal/cbioportal/commit/75e62937ae2c33531501c13c95356e831c007fc3 . This was necessary because COSMIC counts were not displayed for unrecognized variant classifications.

@jjgao @onursumer @n1zea144 are non-MAF variant classifications (still) supported? It would be nice to document these and put a check in the backend for the allowed values.

**Comment by jjgao** [comment]
I did a query of the public database, below are the values -- we should really clean them up.

```
vIII deletion
Translation_Start_Site
Targeted_Region
stopgain
Splice_Site_SNP
Splice_Site
Splice_Region
splice
Silent
nonsynonymous
Nonstop_Mutation
Nonsense_Mutation
nonframeshift.deletion
nonframeshift-deletion
nonframeshift
non-coding-exon
NA
Missense_Mutation
Missense
In_Frame_Ins
In_Frame_Del
Indel
Fusion
Frame_Shift_Ins
Frame_Shift_Del
frameshift-deletion
frameshift
exon14skip
Exon skipping
coding
5'Flank
```

**Comment by jjgao** [comment]
@ritikakundra @yichaoS maybe we can put this into your cleanup to-do list?

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #302](https://github.com/cBioPortal/datahub/issues/302) via [**ZenHub**](https://www.zenhub.com/)
