### ISSUE TITLE
How to get cancer type summary data

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#3078]
Looking at latest resultsViewPageStore

For summary we need:
Gene -> CancerType -> Alteration

What we have right now in store's filteredAlterations is

Gene -> Alteration

To get the cancer type, we need to use alterations uniqueId to get sample.  With sample, we can look at clinical data of type "CANCER_TYPE_DETAILED" to get cancer type.  However, some samples do not have this clinical data, in which case we have to fall back to cancer type of study that sample belongs to.  The logic just described already exists in the cancer type column definition for the mutation table on the results page.  So, we should really reuse this.

Logic for getting cancer type is in getData '/Users/aaronlisman/WebstormProjects/cbioportal-frontend/src/shared/components/mutationTable/column/CancerTypeColumnFormatterLazyLoaded.tsx'

It might be as simple as just using the store's CancerTypeCache.  See if you can do that.  

Lastly, the type of the alteration (Mut, Amplication, Del, Multiple) can be determined using the alterations molecularProfileId.  Use id to look up molecularProfile in store's collection. Then look at profile's alteration type.  If it's a copy number alteration then we need to determine it's subtype (e.g. amp, del etc) which can be done using the alteration's value property and a dictionary (tbd).

**Comment by jjgao** [comment]
Just wanted to add that the `CANCER_TYPE_DETAILED` can be loaded in four places: oncoprint, mutations tab, plots tab, and cancer type summary. Ideally, it should be loaded in the same way and can be shared.
