### ISSUE TITLE
remoteData returns Immutable, Immutable methods (e.g. reduce) return Immutable

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#3082]
This often causes subtle bugs and it would be preferable if those methods did not return more immutables.

**Comment by jjgao** [comment]
@adamabeshouse should this remain open?

**Comment by adamabeshouse** [comment]
based on how the code looks I believe we ended up just not wrapping the return value in an Immutable, but I think the most preferred option would be to return an immutable object whose methods did not return Immutable. I do think we should keep this open until we find a better solution.
