### ISSUE TITLE
Make sure API changes from #2896 are added to new API

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3086]
In #2896 four new fields were added to the model class `business/src/main/java/org/mskcc/cbio/portal/model/DBMutationData.java` and configured in mapper `business/src/main/resources/org/mskcc/cbio/portal/persistence/ProfileDataMapper.xml`. These changes should be added to the corresponding classes in the new API, according to discussion in #2896. 

It is important to do this before the refactoring of the Oncoprint, so that these fields are also available in the new Oncoprint implementation.

**Comment by jjgao** [comment]
@pieterlukasse seems like the pr is merged. I'm closing this now.
