### ISSUE TITLE
remove `TYPE_OF_CANCER_ID` column of `sample` table

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3088]
The `TYPE_OF_CANCER_ID` data is currently not properly generated. Since we have the `oncotree_code` as sample clinical attribute, it may not necessary to duplicate the data here. I would propose to remove it.

**Comment by jjgao** [comment]
Or maybe we should just remove TYPE_OF_CANCER_ID column? @n1zea144

**Comment by jagnathan** [comment]
https://github.com/jagnathan/cbioportal/commit/3d4c4def658ae683418b876ed23a254c0e2d0da2

Commit of the changes for DB side

**Comment by jjgao** [comment]
Thanks, @jagnathan. Could you add the change to any API code and create an PR?

**Comment by jagnathan** [comment]
PR created https://github.com/cBioPortal/cbioportal/pull/7995/
