### ISSUE TITLE
missing hotspot annotation

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3089]
The EGFR H304Y mutation should be hotspot mutation.

http://www.cbioportal.org/case.do#/patient?caseId=P-0000906&studyId=msk_impact_2017

![image](https://user-images.githubusercontent.com/840895/30226654-d0facae2-94a4-11e7-82fc-9535043b438e.png)

**Comment by onursumer** [comment]
@jjgao EGFR H304 is indeed a hotspot, but we don't have it yet in the public www.cancerhotspots.org website, it is only available in the private mskcc instance.
