### ISSUE TITLE
Portal.properties skin.right_nav.whats_new_blurb not working

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#3096]
skin.right_nav.whats_new_blurb is not confgurable from the portal.properties. UI still displays the default html.

**Comment by inodb** [comment]
@priti88 This is fixed now when using latest hotfix of cbioportal and cbioportal-frontend. Have to discuss how exactly we'd like to more seamless updating of this property as discussed in #3115

**Comment by priti88** [comment]
@inodb I deployed the hotfix branch and it still does not work for me.

**Comment by inodb** [comment]
@priti88 oops missed this. Yes seems there was some diff between dev and prod set up, fixed in this PR: https://github.com/cBioPortal/cbioportal/pull/3244
