### ISSUE TITLE
Cancer type is NA for some samples in MSK Impact 

### ISSUE THREAD

**Issue by JiaoJiao123** [cBioPortal/cbioportal#3099]
In MSK-Impact study, there are around 60 samples that don't have Cancer type assigned. For example "P-0001405-T01-IM3".

**Comment by jjgao** [comment]
That is for msk_impact_2017.

I assume @yichaoS and @ritikakundra are working on this.

**Comment by jjgao** [comment]
Oncotree codes should be added.

http://www.cbioportal.org/case.do#/patient?studyId=msk_impact_2017&caseId=P-0000045&navCaseIds=P-0000045,P-0000668,P-0001083,P-0001179,P-0001195,P-0001345,P-0001405,P-0001458,P-0001686,P-0001779,P-0001849,P-0002047,P-0002198,P-0002219,P-0002267,P-0002377,P-0002411,P-0002422,P-0002736,P-0002787,P-0003374,P-0003615,P-0003703,P-0003706,P-0003747,P-0004199,P-0004604,P-0004871,P-0004881,P-0005135,P-0005812,P-0006098,P-0006121,P-0006132,P-0006307,P-0006384,P-0006454,P-0006611,P-0007293,P-0007575,P-0007605,P-0008185,P-0008524,P-0008860,P-0009328,P-0009435,P-0009588,P-0009867,P-0009917,P-0010050,P-0010109,P-0010111,P-0010241,P-0010266,P-0010459,P-0010902,P-0010957,P-0011029,P-0012035,P-0012226

**Comment by ritikakundra** [comment]
fixed
