### ISSUE TITLE
webworker for data transformation for oncoprint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3104]

**Comment by jjgao** [comment]
Are we still going to do this?

**Comment by jjgao** [comment]
@adamabeshouse should we colse this?

**Comment by adamabeshouse** [comment]
I think at some point we could definitely do this, but not for this release

**Comment by adamabeshouse** [comment]
this might take more work than is worth for us, work refactoring the oncoprint library, because webworkers means we're adding asynchronous stuff and that isnt trivial to do in oncoprint the way its written. should we move to icebox?

**Comment by jjgao** [comment]
yes, ice-boxed.
