### ISSUE TITLE
Add OncoKB gene background information on mouseover of mutations/cna table

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3105]

**Comment by jjgao** [comment]
I think it's now on the oncokb icon. We should probably use a slightly different icon for genes that are included in oncokb.

**Comment by jjgao** [comment]
@zhx828 @inodb any update?

**Comment by jjgao** [comment]
related to #3495

**Comment by jjgao** [comment]
closing this as it'll be covered by #3495.
