### ISSUE TITLE
broken institute logo

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3106]
The right logo is broken. Is it related to #2945?

public portal (should be no logo):
![image](https://user-images.githubusercontent.com/840895/30409262-fc2ca056-98d1-11e7-8ad6-0fc5f55c9dbf.png)

msk portal (msk logo):
![image](https://user-images.githubusercontent.com/840895/30409275-0f5e5c0a-98d2-11e7-99a0-040a46cc9466.png)

**Comment by fedde-s** [comment]
Yes, it might be related. @jjgao, may I ask which release of Tomcat these installations use?

**Comment by fedde-s** [comment]
I see, I can reproduce it by reverting to Tomcat 7.0.x.

**Comment by fedde-s** [comment]
I believe that this is solved now that my patch has been merged into the hotfix development branch.

![Screenshot of the same front page region as the first one in this issue, but without the literal words ‘Institute Logo’](https://user-images.githubusercontent.com/4929431/30473940-4f50d9ec-9a02-11e7-9cd8-bdb3a2be67a5.png)

**Comment by fedde-s** [comment]
As [part of the discussion](https://github.com/cBioPortal/cbioportal/pull/3107#issuecomment-329525587) about the pull request I explained the reasoning behind my choice to use JSTL tags over scriptlets.
