### ISSUE TITLE
Update Dockerfile to work with new base image of tomcat

### ISSUE THREAD

**Issue by als2076** [cBioPortal/cbioportal#3108]
Docker updated the base image of tomcat in hub.docker.com moving from debian jessie to debian stretch.

jessie-backports will no longer work resulting in a broken build.
Edits need to be done on the dockerfile to support stretch-backports instead

**Comment by fedde-s** [comment]
This seems to be in progress in pull request #3109.

**Comment by fedde-s** [comment]
The pull request fixing this was merged to the `hotfix` development branch.
