### ISSUE TITLE
HTML tags in the breadcrumbs if a gene has Mutsig or Gistic result

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#311]
![image](https://cloud.githubusercontent.com/assets/840895/10340109/8c65fb28-6cdc-11e5-8272-b0f6701bb36a.png)

http://www.cbioportal.org/beta/study.do?cancer_study_id=ucec_tcga_pub

**Comment by ecerami** [comment]
the hyve can fix this.  but, I don't see them in the drop down menu for possible assignees....

**Comment by zhx828** [comment]
I will fix this.

**Comment by jjgao** [comment]
@zhx828 Sander can fix this unless you already did.

**Comment by aderidder** [comment]
Hi guys, I'm fixing it at the moment.

2015-10-08 3:38 GMT+02:00 JianJiong Gao <notifications@github.com>:

> @zhx828 <https://github.com/zhx828> Sander can fix this unless you
> already did.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cBioPortal/cbioportal/issues/311#issuecomment-146389834>
> .
>



-- 
E.   sander@thehyve.nl
T.   +31(0)30 700 9713
W.  www.thehyve.nl

the hyve

**Comment by zhx828** [comment]
@aderidder gene is not the unique ID for CNA table. For that table, the unique ID should be gene + altType

**Comment by zhx828** [comment]
I'm also working on separating breadcrumb out of table component into StudyViewInitTable. The component itself shouldn't connect to other components directly.

**Comment by aderidder** [comment]
Ok, I think we may also have to update the breadcrumb text for the CNA
table, as it won't show a distinction either. Shall I wait until you are
finished?

2015-10-08 16:14 GMT+02:00 HongxinZ <notifications@github.com>:

> I'm also working on separating breadcrumb out of table component into
> StudyViewInitTable. The component itself shouldn't connect to other
> components directly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cBioPortal/cbioportal/issues/311#issuecomment-146558552>
> .
>



-- 
E.   sander@thehyve.nl
T.   +31(0)30 700 9713
W.  www.thehyve.nl

the hyve

**Comment by zhx828** [comment]
I will solve this as well in the same pull request.
