### ISSUE TITLE
Change "putative passenger" to "VUS (variant of unknown significance)" in oncoprint legend

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3113]
Oncoprint currently retrieves information from OncoKB and other sources to label some mutations as "putative driver". The rest of the mutations is automatically labelled as "putative passenger". 

**This should change to “VUS (variant of unknown significance)”**, which more accurately reflects the lack of evidence or knowledge about the functional effect of a mutation.

**Comment by pieterlukasse** [comment]
Notify: @adamabeshouse @jjgao @schultzn

**Comment by jjgao** [comment]
@adamabeshouse please change this during refactoring.

**Comment by adamabeshouse** [comment]
that makes the legend kind of cluttered, would it be alright to just say "(unknown significance)"

**Comment by schultzn** [comment]
Sure, that should work…
