### ISSUE TITLE
Create New Component:  Latest Tweets, and add to Home Page

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#3115]
Discussed previously with @tmazor and @jjgao, and also agreed / discussed at today's cBioPortal coordination call.

On the current home page, we have a small "What's New" Section in the right nav bar.

We would like to be able to edit this section without having to rebuild or recompile.  And, ideally the section can take one news item / month that could have 1) paragraph of text;  and 2) optional image / figure.

For example, when we launch the Broad Count Me In Data, we can have a small paragraph describing the project, plus a graphic.  In the future, we might add publications that use cBioPortal, or small user tips, etc.

**Comment by inodb** [comment]
@ecerami are we ok with redeploying (not recompiling)? Only changing the property value and relaunching. Or should this solution read the what's new section from some external source?

**Comment by ecerami** [comment]
@inodb:  Ideally, I think it should be possible to update the news blurb w/o deploying, e.g. similar to how the about page works (I think).

**Comment by inodb** [comment]
@ecerami We've decided to make this a Twitter feed of latest 1/2 tweets on last sprint meeting

**Comment by ecerami** [comment]
Here is the spec I propose:

1.  In front end configuration, we need to add an optional parameter, where we can specify a twitter account.
2.  If a twitter account is specified, then the first 2-3 tweets appear on the home page, in the right nav bar.

**Comment by jjgao** [comment]
http://cytoscape.org/ has embedded tweets on their site.
