### ISSUE TITLE
Genomic profile checkboxes render on single line

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#3116]
I just booted up an instance running the `rc` development branch, and the checkboxes and radio buttons to select genomic profiles on the query page were all jumbled together as inline elements. I presume that part of the solution is to annotate the `<label>` elements with the [`.radio` and `.checkbox` classes](https://getbootstrap.com/docs/3.3/css/#checkboxes-and-radios) recognised by Bootstrap instead of `.undefined`

![Screenshot showing the aforementioned form group](https://user-images.githubusercontent.com/4929431/30490040-274bf77e-9a39-11e7-8dbe-fde527c5d76a.png)

**Comment by fedde-s** [comment]
@adamabeshouse or @alisman, is this a known issue?

**Comment by alisman** [comment]
Yes, there's already a fix for it.  Just hasn't been merged to rc.

**Comment by fedde-s** [comment]
I think the fix has been released long ago now.
