### ISSUE TITLE
Oncoprint heatmap legend renders as plain red block

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#3119]
In the `rc` development branch, the legend for heatmaps in the Oncoprint no longer renders as a gradient from blue to black to red, but as a plain red block all the way from -3 to 3.

![Screenshot showing an Oncoprint heatmap with a plain red block for a legend](https://user-images.githubusercontent.com/4929431/30492063-947ffa9c-9a3f-11e7-8d2f-50c0ba7d9bc7.png)

**Comment by fedde-s** [comment]
@adamabeshouse, do you know what might have caused this?

**Comment by adamabeshouse** [comment]
I haven't made any related changes.. perhaps related to @rnugraha's recent changes? (github wont let me tag him)

**Comment by fedde-s** [comment]
Yes. A `git bisect` shows that the bug was introduced specifically by commit e19e28f8c125937e0ff80eddb2deffe856939f7d.

**Comment by fedde-s** [comment]
I believe that this is being addressed by pull request #3168.
