### ISSUE TITLE
Problem loading patient view if a sample has no _sequenced sample list

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3127]
http://www.cbioportal.org/case.do#/patient?studyId=prad_mskcc_2014&caseId=PCA0300

Why do we need to load the sample list?

**Comment by jjgao** [comment]
BTW, displaying the message below for any kind of js error is confusing -- it's nothing to do with "not finding the sample"

![image](https://user-images.githubusercontent.com/840895/30556765-ff40639e-9c79-11e7-9169-11a245870478.png)

**Comment by onursumer** [comment]
Seems like we need the sequenced sample ids for `Genomic Overview` rendering...

**Comment by fedde-s** [comment]
Possibly related to the discussion on how to structure case list data files in https://github.com/cBioPortal/cbioportal/issues/494

**Comment by jjgao** [comment]
Thanks, @onursumer.

Let's switch to the new fields Ersin added in #3070 for deciding whether there are mutations or seg data for `Genome Overview` so that we don't have to load the whole case list.

**Comment by fedde-s** [comment]
@jjgao: from [this line](https://github.com/cBioPortal/cbioportal/pull/3070/files#diff-8ff982cb7e161da91ec641ea7b769188R144) it looks like those fields are only an alternative way to retrieve that sample list information in the back-end. @ersinciftci, can you comment?

**Comment by ersinciftci** [comment]
@fedde-s sorry I just saw this now. I didn't get what you meant by `only an alternative way to retrieve that sample list`. I think @jjgao suggested to switch to the new fields only for convenience, i.e. 1 less API call.

**Comment by fedde-s** [comment]
Ah, okay. I just meant that that by itself would not fix the issue that something in the frontend breaks when a study does not have a sample list with the `_sequenced` suffix, as it's a ‘view’ on the data (not) loaded from the same case list file.

**Comment by ersinciftci** [comment]
Right, I don't think @jjgao suggested it as a fix to this problem.

**Comment by jjgao** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/639 solve the problem of the pop up window. Let's keep it open until Ersin's API #3070 is used.
