### ISSUE TITLE
Cannot query meso_tcga study

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3145]
Query page gives an error: 

![image](https://user-images.githubusercontent.com/2900303/30637727-7966ac0c-9df9-11e7-97ad-5d50b3a04f8c.png)

Steps to reproduce:
- select Mesothelioma study on query page

**Comment by pieterlukasse** [comment]
@ritikakundra could this be a datahub issue instead? Is this study lacking case lists? The validation script would have blocked this I think.

**Comment by jjgao** [comment]
I think it's lacking _sequenced case list. We should fix the data. But in the frontend, we should also capture the error -- it's probably a good idea to have a warning so that we know there is a data issue but missing a case list shouldn't prevent us from querying it.

**Comment by fedde-s** [comment]
I think it should probably make the assumption that all samples in the study have been sequenced. Alternatively it could assume that only samples that have any mutations have been, but that would cause problems for studies using gene panels rather than whole-exome sequencing.

**Comment by fedde-s** [comment]
Related to the discussion in issue #494.

**Comment by jjgao** [comment]
Actually it's throwing a backend error:

http://www.cbioportal.org/beta/api/studies/meso_tcga/sample-lists?projection=DETAILED

![image](https://user-images.githubusercontent.com/840895/30862248-6134cca8-a29b-11e7-8d6d-c1ad8e20180e.png)

@ersinciftci could you look into it?

**Comment by ritikakundra** [comment]
This is fixed

**Comment by pieterlukasse** [comment]
@ritikakundra is the validator warning in any way that the _sequenced list is missing? If not, could you please open a ticket to fix that?

**Comment by fedde-s** [comment]
RFC37: Redesigning Case Lists? It looks like that would move the information from external case list files to clinical attributes, but still require the same validation (but on the list of clinical attributes instead of the list of case list files).

**Comment by jjgao** [comment]
For the moment, we should have validator to valid that. Should it be a warning or error?
