### ISSUE TITLE
Browser console complains about offset attribute while rendering Oncoprint heatmaps

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#3146]
When enabling a heatmap in the Oncoprint using the code in the **rc** development branch, the browser console fills up with hundreds of error messages about invalid values of an ‘offset’ attribute, starting from `0%%` and going all the way up to `100%%`, multiple times (probably once for each track).

In Firefox ESR the warning text is `Unexpected value 100%% parsing offset attribute`, in Google Chrome it's `Error: <stop> attribute offset: Trailing garbage, "100%%"`. It occurs on a line of **oncoprint-bundle.js** that seems related to SVG elements.

**Comment by fedde-s** [comment]
Using git bisect, I found that the first commit showing this behaviour was e19e28f8c125937e0ff80eddb2deffe856939f7d. @rnugraha, might it be related to issue #3119?

**Comment by jjgao** [comment]
@fedde-s I think it's critical. Who would be the best person to address this?

**Comment by rnugraha** [comment]
I'll look at this

**Comment by fedde-s** [comment]
I don't think this issue still exists. Do reopen or comment if you think I'm mistaken.
