### ISSUE TITLE
No data?

### ISSUE THREAD

**Issue by alexpenson** [cBioPortal/cbioportal#315]
![image](https://cloud.githubusercontent.com/assets/3246599/10348572/c5e2f01a-6d07-11e5-8198-1eb7c124e790.png)

I can't select any studies on the main page...

**Comment by inodb** [comment]
What is the web address?

**Comment by alexpenson** [comment]
https://cbioportal.mskcc.org/beta/#

**Comment by zhx828** [comment]
Please sign up on http://bit.ly/1Ll2xci
