### ISSUE TITLE
Use Entrez ID instead of gene symbols when retrieving CIViC annotations

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#3153]
Currently, when retrieving OncoKB and CIViC annotations, cBioPortal makes requests based on gene symbols. It would be better if these requests were based on Entrez IDs, since gene symbols can change over time and also avoids having issues with special characters that the symbols can contain (such as `/`). However, the downside of this approach is that the annotations will not work in cBioPortal instance based on Ensembl IDs.

What are your thoughts on that? @jjgao @zhx828 @pieterlukasse

**Comment by zhx828** [comment]
@oplantalech OncoKB has switched to entrezGeneId in portal few months ago. And I think it is better to use EntrezGeneId instead of hugo symbol.

**Comment by jjgao** [comment]
For pulling from OncoKB, we plan to switch to genomic coordinates.

Does CIViC supports Ensembl IDs? We are connecting cBioPortal to GenomeNexus which will use Ensembl IDs. It may also make sense to aggregate CIViC data in Genome Nexus as well.

cc'ing @inodb and @onursumer on the discussion as well.

**Comment by oplantalech** [comment]
@jjgao To retrieve genes, CIViC allows `entrez_symbol`, `entrez_id` and `civic_id`.

**Comment by jjgao** [comment]
thanks @oplantalech. `entrez_id` should be used then.

**Comment by pieterlukasse** [comment]
Just noticed that the new Mutation view also relies on `entrez_id` instead of symbol (at least for part of the external calls):
https://mygene.info/v3/gene/4684?fields=uniprot  (apparently to get the uniprot ID for a given entrez id)


This is *good*. Only downside is that the "ensembl workaround" in the gene table is not possible anymore.

**Comment by jjgao** [comment]
also related: https://github.com/cBioPortal/cbioportal/issues/3967

@oplantalech would you be able to help with the switch?

**Comment by jjgao** [comment]
please make sure to filter out fake negative `entrez_id`s.
