### ISSUE TITLE
replace the OQL spec page with the MD file

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3157]
Similar to news.jsp page, we should pull the md file below (master branch) and replace the content in the current onco_query_lang_desc.jsp.

https://github.com/cBioPortal/cbioportal/blob/rc/docs/Onco-Query-Language.md

**Comment by jjgao** [comment]
I marked it critical since the current spec is out of date and the one @tmazor put together is too nice not to put out soon :)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3516

**Comment by tmazor** [comment]
@adamabeshouse I took a look at the screenshot in your PR and some of the formatting didn't translate properly - the section under "OQL Keywords" is supposed to be a table but it doesn't look like one anymore. Maybe the MD -> JSP conversion doesn't support tables?

**Comment by adamabeshouse** [comment]
@tmazor please see discussion on PR
