### ISSUE TITLE
PdbAnnotation API dependency

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#3159]
We cannot completely remove `PdbAnnotation API` yet, because we fetch `PDB header` data from there.

**Comment by jjgao** [comment]
@onursumer is that because we cache the PDB header there? Is performance OK to not use cache?

**Comment by onursumer** [comment]
@jjgao It is a little slow without the cache since we are querying multiple PDB chains for a single gene. Also if we always hit the PDB web service directly, we may end up having problems similar to the ones we have with PFAM web service. Maybe it is better to add another endpoint in genome nexus for this one too.

**Comment by jjgao** [comment]
@onursumer good point.

**Comment by jjgao** [comment]
@onursumer how's going with this one?

**Comment by onursumer** [comment]
I think this is fully integrated into genome nexus by https://github.com/genome-nexus/genome-nexus/pull/97

**Comment by jjgao** [comment]
and we are using the genome-nexus end point in portal too?

**Comment by onursumer** [comment]
@jjgao Looks like we are still using the old endpoint, not genome nexus yet. Do you think it is a good time to switch to genome nexus, or should we do this after releasing 1.11.0?

**Comment by jjgao** [comment]
as discussed, hotfix later.
