### ISSUE TITLE
Functional Impact Column does not work

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3162]
Need to write a function to turn mutation to proper hgvs format for Genome Nexus

**Comment by jjgao** [comment]
There are now many places where we need to turn mutation into proper hgvs format. I remember, @angelicaochoa and @zhx828 were working on implementing that in GenomeNexus? Maybe GenomeNexus should support query by the five genomic coordination columns?

On the other hand, in the cBioPortal, we should have HGVSg/c/p columns.

**Comment by jjgao** [comment]
Any update on this?

**Comment by inodb** [comment]
There is an endpoint for querying by genomic coordinates now, so we prolly just need to update the frontend code for functional impact column to use this

**Comment by jjgao** [comment]
@inodb I looks like we are sending separate genomic changes, but the GN does not return anything.

**Comment by jjgao** [comment]
seems working now. Closing this.
