### ISSUE TITLE
redesign the protein glyphs in oncoprint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3167]
Currently, they are black arrows. They do not work well when zoomed out.

 
![image](https://user-images.githubusercontent.com/840895/30749507-9a9372be-9f81-11e7-9b83-984e887920e6.png)

![image](https://user-images.githubusercontent.com/840895/30749555-c6cf24f4-9f81-11e7-98df-2a06d8b7324f.png)

**Comment by jjgao** [comment]
Maybe do it the same as expression but different colors? e.g. one of the Purple for up and Cyan for down.

https://designguidelines.withgoogle.com/android-wear/style/color.html#color-dark-color-palette-for-wear

**Comment by adamabeshouse** [comment]
what about it don't you think works well? The shape, color?

Im not sure it would be possible to clearly have more than one outline, especially once it gets squished.

**Comment by jjgao** [comment]
I think, when zooming out, triangles do not work as well as rectangles.

**Comment by adamabeshouse** [comment]
hows this?

![image](https://user-images.githubusercontent.com/636232/32289462-2a50249c-bf0d-11e7-8955-cc40e3349676.png)

![image](https://user-images.githubusercontent.com/636232/32289474-34ab501a-bf0d-11e7-80ff-dc53806eed3c.png)

![image](https://user-images.githubusercontent.com/636232/32289494-45041a28-bf0d-11e7-8147-20e8be24e412.png)

**Comment by jjgao** [comment]
Thanks, @adamabeshouse. It's definitely better. Thoughts, @schultzn ?

**Comment by schultzn** [comment]
Looks great - I like it! Nice work.

**Comment by adamabeshouse** [comment]
merged into `rc`
