### ISSUE TITLE
OncoKB ordering of mutations (likely neutral w Level should be above oncogenic w/o Level)

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3171]
if an alteration is “likely neutral” if it has an associated level of evidence, it should shuffle to the top (i.e this ERBB2 mt should be above the CTNNB1 mutation)

![oncokb_screenshot](https://user-images.githubusercontent.com/1334004/35533208-d13479dc-050a-11e8-87cd-5edef946485d.png)

**Comment by jjgao** [comment]
@inodb You mean level should have the priority and therefore level 3 should be before level 4 even if it's neutral?

**Comment by jjgao** [comment]
@zhx828 according to oncokb, it should be likely oncogenic...

http://oncokb.org/#/gene/ERBB2

**Comment by zhx828** [comment]
This seems pretty strange issue to me. The oncogenic alteration should not have a treatment leveled. Please let me know if this issue happens to other alteration. Close for now
