### ISSUE TITLE
cancer types summary: number of cases is inconsistent between y-axis and tooltip

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3177]
When looking at absolute counts on cancer types summary, the number of cases with the alteration in the tooltip is not the same as the height of the bar/y-axis. In the example below, the tooltip says 57 cases are altered but the bar height is ~25

![image](https://user-images.githubusercontent.com/10508276/30814040-07cc3ff2-a1dd-11e7-8e0c-eb4664f9c1e2.png)
http://www.cbioportal.org/beta/index.do?session_id=595d48db498e5df2e29214c8&show_samples=false&

**Comment by alisman** [comment]
@Tamba32 I believe this should now be fixed but please check.
