### ISSUE TITLE
cancer types summary: change y-axis label when set to absolute counts

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3178]
The y-axis label should be "Absolute counts" when the y-axis value is set to "Absolute Counts"

![image](https://user-images.githubusercontent.com/10508276/30814199-7c1ab05a-a1dd-11e7-947d-d104ccc7ee66.png)

**Comment by Tamba32** [comment]
Fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/640
