### ISSUE TITLE
add more index to tables

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3180]
e.g. 

- `STABLE_ID` in `patient`
- `STABLE_ID` in `sample`
- `ATTR_VALUE` in `clinical_patient`
- `ATTR_VALUE` in `clinical_sample`
- `GENE_A` and `GENE_B` in `interaction`

**Comment by jjgao** [comment]
there may be more, but don't worry about tables listed here: https://github.com/cBioPortal/cbioportal/issues/2054

**Comment by ersinciftci** [comment]
Added indexes for 
`STABLE_ID` in `patient`
`STABLE_ID` in `sample`
will add for the others after evaluating the usage patterns.
