### ISSUE TITLE
Importer: Gene panel data as matrix and clinical attribute not imported

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3191]
As described in https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#meta-file-13 gene panels can be assigned to 'genetic profile - sample' using 3 methods:
1. Create a gene panel sample matrix, in which the rows are samples and columns datatypes. The values are the gene panel stable ids. This can also assign a 'genetic profile - sample' to a gene panel when no mutations are found.
2. Add the `gene_panel` field in the metafile, such as in `meta_mutations_extended.txt`. This will **not** assign a 'genetic profile - sample' to a gene panel when no mutations are found.
3. Add a `GENE_PANEL` column to the clinical sample file. This does not support multiple different gene panels per sample, such as one for expression and one for genetic alterations.

So the most useful method is using (1), the gene panel sample matrix. However, when testing I found out that **(1) does not work without (2)**.

A fix should make (1) function independently of (2). It might be better to remove (2) completely. With (2), when querying for a gene, _some_ samples with no mutations are called 'whole exome sequencing', because they are not included in the MAF file.

_Update_: I tested (3) and apparently this is also bugged. The clinical attribute was successfully imported, and viewable in the OncoPrint. However, the gene panel was not showed and all samples were marked as 'Whole-Exome Sequenced'.

**Comment by jjgao** [comment]
@sandertan that's odd, b/c gene panel seems work on public portal: http://www.cbioportal.org/results?session_id=5beee30fe4b06273341189c1

I am adding @n1zea144 and @sheridancbio on this.

**Comment by sandertan** [comment]
@n1zea144 @jjgao I fixed the importer for gene panels in a local branch. I'm currently adding some gene panel data validation. A PR should be ready early next week.

**Comment by sandertan** [comment]
This has been fixed!
