### ISSUE TITLE
Order in Cancer Type Summary

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3193]
From bottom up: Multiple =>  Mutaiton => fusion => CNA => mRNa => protein.

Please also try to use dark gray instead of black for Multiple.

**Comment by alisman** [comment]
@Tamba32 THis refers to the order in which the alteration types appear in the stacked bars.  Can this be accomplished?

**Comment by alisman** [comment]
@jjgao, please order these as desired:
['multiple', 'amplified', 'deleted', 'mutated', 'gain', 'homdel', 'fusion', 'mrnaExpressionUp', 'mrnaExpressionDown', 'protExpressionUp', 'protExpressionDown']

**Comment by jjgao** [comment]
@Tamba32 @alisman let's do:


['multiple', 'mutated',  'fusion', 'amplified', 'gain', 'homdel', 'deleted',  'mrnaExpressionUp', 'mrnaExpressionDown', 'protExpressionUp', 'protExpressionDown']


I assume `deleted` is `hetloss` (cna value of 1), if so, maybe change the label to `hetloss`.

**Comment by jjgao** [comment]
closing this. Let's use the new order here: https://github.com/cBioPortal/cbioportal/issues/3214
