### ISSUE TITLE
Patient view fails when study does not have mutation data 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3203]
Steps to reproduce:

1. Go to http://www.cbioportal.org/case.do#/patient?studyId=prad_mskcc_2014&caseId=PCA0318&navCaseIds=PCA0318,PCA0321,PCA0325,PCA0326,PCA0328,PCA0329,PCA0332,PCA0333,PCA0338,PCA0348,PCA0362,PCA0363,PCA0364,PCA0370,PCA0373,PCA0375,PCA0400,PCA0402

![image](https://user-images.githubusercontent.com/2900303/31015100-ab12b6c0-a51e-11e7-8b01-4a5c90442d9f.png)

This is probably because of the failing call to http://www.cbioportal.org/api/sample-lists/prad_mskcc_2014_sequenced/sample-ids

![image](https://user-images.githubusercontent.com/2900303/31015116-c75ce742-a51e-11e7-9dcd-1e19164d5725.png)

This is a bug and *not* a data problem given this study does not have mutation data but only CNA (and `_sequenced` case list is tied to mutation profile while `_cna` or `_gistic` case lists are related to CNA).

**Comment by pieterlukasse** [comment]
Proposed solution: patient view should only look for `_sequenced` case list if there is any mutation data for this patient.

**Comment by jjgao** [comment]
duplicate with #3127

**Comment by pieterlukasse** [comment]
@jjgao please see my comment on https://github.com/cBioPortal/cbioportal-frontend/pull/639#issuecomment-333125657
