### ISSUE TITLE
Patient View-Clinical Data not displaying all attributes

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#3206]
Couldn't find "American Joint Committee on Cancer Tumor Stage Code" patient attribute on the Patient View - Clinical Clinical Data tab for an IMPACT patient, but if I search for it in the search box it appears.

[Link to patient view on MSK Portal](https://cbioportal.mskcc.org/case.do#/patient?caseId=P-0000751&navCaseIds=P-0000751&studyId=mskimpact&tab=clinicalDataTab)

Per Aaron Lisman, pagination is set to false on the component and there may be a default limit on the table.

**Comment by adamabeshouse** [comment]
Fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/648

But they're not in alphabetical order by attribute.. should they be?

**Comment by jjgao** [comment]
@adamabeshouse yes, alphabetical order would be good.
