### ISSUE TITLE
Cancer Types Summary improvement

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#321]
- [x] %altered was calculated using denominator of the whole dataset. Different denominators (numbers of samples) of different cancer types should be used. 
- [x] switch to %altered as default.
- [x] when switching to frequency, the slide bar should also be based on frequency.

**Comment by jjgao** [comment]
@adamabeshouse will be working on this.

**Comment by pieterlukasse** [comment]
FYI - first part, i.e. : 
-  %altered was calculated using denominator of the whole dataset. Different denominators (numbers of samples) of different cancer types should be used.

is working.

I've made a separate branch for the last two enhancements, i.e.
 -switch to %altered as default.
 -when switching to frequency, the slide bar should also be based on frequency.

but this separate branch would still need some fixing as it is not working yet. 
See https://github.com/thehyve/cbioportal/tree/issue321_enhanc

**Comment by pieterlukasse** [comment]
PR #361 created for the last two enhancements, i.e.
-switch to %altered as default.
-when switching to frequency, the slide bar should also be based on frequency.
