### ISSUE TITLE
Cancer Types Summary Download PNG: needs white background

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3212]
On the Cancer Types Summary tab, the download PNG has a strange grey background - this needs to be white.

![cbioportalcancersummary](https://user-images.githubusercontent.com/11892704/31045974-ebfd77f2-a5bd-11e7-947f-d9f8f6432e09.png)

**Comment by Tamba32** [comment]
@schultzn The background is not grey, it is transparent. The image is a PNG.

**Comment by alisman** [comment]
Should we have a transparent background?  I mean, it does make it easier to incorporate into other settings.

**Comment by schultzn** [comment]
I see. It is probably more useful for our users to have a white background though..

**Comment by Tamba32** [comment]
Fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/646

**Comment by schultzn** [comment]
Agreed - but it looked very funny when I opened it in Preview. Was this something on my end?
