### ISSUE TITLE
Cancer Types Summary tab: change sort order of events

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3214]
Multiple alterations used to be at the bottom, and I still think that’s where they belong.

From top to bottom it should be:
Mutation
Amplification
Deletion
Fusion
Multiple

And the legend on the right should have the same order.

**Comment by jjgao** [comment]
@Tamba32: based on @schultzn's comments, let's change the order of event types to:

Top-down: ['mutated', 'fusion', 'amplified', 'gain', 'homdel', 'hetloss', 'mrnaExpressionUp', 'mrnaExpressionDown', 'protExpressionUp', 'protExpressionDown', 'multiple']

The legend should follow the same order, top-down.

**Comment by Tamba32** [comment]
@jjgao updated

**Comment by Tamba32** [comment]
Fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/646
