### ISSUE TITLE
Beta: About / News / FAQ not loading

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3215]
News

Sat Sep 30 2017 09:04:40 GMT-0400 (EDT)
There was a problem retrieving the page located at: undefined
error, Internal Server Error

**Comment by alisman** [comment]
This was on beta site, correct?  (not production)

**Comment by schultzn** [comment]
Correct.

**Comment by jjgao** [comment]
It may be related to the configuration file. cc'ing @inodb

**Comment by alisman** [comment]
@jjgao this is a configuration issue.  There is no content at the following location:
https://raw.githubusercontent.com/cBioPortal/cbioportal/release-1.8.0/docs/News.md
Probably the settings just need to be updated?

**Comment by inodb** [comment]
@alisman @jjgao yes, ill update docs to point to 1.9.0 branch
