### ISSUE TITLE
Mutation lollipop view hangs when gene has unknown Entrez

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3218]
Mutation lollipop view hangs when gene has unknown Entrez. This could happen for "negative Entrez scenario". 

Steps to reproduce on cbioportal.org (and on /beta): 
- go to study view for MSK Impact study, select Mutations tab: http://www.cbioportal.org/study?id=msk_impact_2017#mutations
- click on the 2nd entry in the table: `CDKN2AP16INK4A` . Link: http://www.cbioportal.org/index.do?Action=Submit&genetic_profile_ids=msk_impact_2017_mutations&case_set_id=msk_impact_2017_all&cancer_study_id=msk_impact_2017&gene_list=CDKN2AP16INK4A&tab_index=tab_visualize&#mutation_details&show_samples=false&

Details: 
- Probably this is hanging due to 404 returned by the new **mygene.info** service that was integrated (see screenshot below). It will of course give 404 for a negative entrez:

![image](https://user-images.githubusercontent.com/2900303/31076254-9cb99262-a779-11e7-821d-2b55941d536b.png)

Desired solution:
- proper error handling for *any* unknown or "not found" entrez gene id:  display the lollipop view on a single domain that is the length of the gene / 3 (like was done before).
- also catch HTTP 500 scenario and display a small error/warning icon (:warning:) in this case

**Comment by pieterlukasse** [comment]
@jjgao also happens on /beta btw.

**Comment by pieterlukasse** [comment]
@oplantalech, @alisman: the CIVIC icon also hangs, but perhaps this is because https://github.com/cBioPortal/cbioportal-frontend/pull/624 is not deployed yet.

**Comment by pieterlukasse** [comment]
@jjgao @alisman : as a general comment for all external services we are integrating: I would recommend reviewing the exception handling scenarios in all cases. Any of these services might fail at any time (including the newly integrated g2s.genomenexus.org). Ideally the UIs won't hang when this happens but give a clear indication about the temporary error in such a case.

**Comment by alisman** [comment]
@pieterlukasse agreed.  we have a global error handler that shows a dialog.  we disabled it a couple weeks ago because it was bring down the patient view unnecessarily.  but we need to bring it back with a more specific treatment of different errors which may or may not be "catastrophic"

**Comment by alisman** [comment]
@onursumer lets discuss how to handle this in UI.  Also, we need a way to egage the global error handler and define an error message for each error (so the dialog can display)

**Comment by pieterlukasse** [comment]
@alisman here is my desired solution for this specific case:
- proper error handling for any unknown or "not found" entrez gene id: display the lollipop view on a single domain that is the length of the gene / 3 (like was done before).
- also catch HTTP 500 scenario and display a small error/warning icon (:warning:) in this case next to the "single domain" lollipop view

**Comment by onursumer** [comment]
@pieterlukasse @alisman Soon we are going to update the way we obtain the domain information: We are switching from `pfam/graphics` API to genome nexus API. It might be a good idea to deal with this issue while redesigning/reimplementing domain rendering.

With the new API, we won't need to query for uniprot id with entrez gene id, because we won't need uniprot id for pfam graphics data any more. But, there will still be unknown genes, i.e. genes with no protein (length) information. And we will still need the `gene length / 3` approach for them.

**Comment by onursumer** [comment]
@pieterlukasse I am just trying to patch a quick fix for now by using the gene length, but looks like we don't have that information in our database for the gene `CDKN2AP16INK4A`. Do you remember how we were getting the gene length previously?

**Comment by onursumer** [comment]
@pieterlukasse My bad, actually we have the length information. Looks like currently we only fetch the minimum info (i.e: `projection=ID`), that's why I was not able to see the length in the result.
