### ISSUE TITLE
OncoKB fails with HTTP 500

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3219]
Reason is still unclear.

Steps to reproduce:
- go to mutation view of gene `HIST1H3B` for MSK Impact study: http://www.cbioportal.org/index.do?Action=Submit&genetic_profile_ids=msk_impact_2017_mutations&case_set_id=msk_impact_2017_all&cancer_study_id=msk_impact_2017&gene_list=HIST1H3B&tab_index=tab_visualize&#mutation_details&show_samples=false&
- Hover over any of the dark grey OncoKB circle icons. It will result in error. See screenshot: 

![image](https://user-images.githubusercontent.com/2900303/31077684-b9502dea-a77f-11e7-8e19-3c836cca7b77.png)

**Comment by pieterlukasse** [comment]
@jjgao also happens on /beta

**Comment by zhx828** [comment]
Issue has been solved in here https://github.com/oncokb/oncokb/commit/173913257e07c10de586b7da72156818d8c70792
