### ISSUE TITLE
cancer type summary: tilt the text a little more

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3222]
Can we match the previous text angle?

previous:
![image](https://user-images.githubusercontent.com/840895/31094351-e326bf3c-a782-11e7-9454-71cf4894a0c2.png)

new:
![image](https://user-images.githubusercontent.com/840895/31094367-ef46c9e2-a782-11e7-8557-a848cad7daa3.png)

**Comment by Tamba32** [comment]
Fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/646
