### ISSUE TITLE
Cancer Types Summary: Missing breakdown by tumor sub-type?

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3224]
When all tumors in the query have the same main cancer type, the cancer types summary tab should show frequencies for each detailed cancer type. That no longer seems to be the case. See these links and the screenshots below.

http://www.cbioportal.org/index.do?session_id=59d3991c498e5df2e2961d1e&show_samples=false&

http://www.cbioportal.org/beta/index.do?session_id=59d3991c498e5df2e2961d1e&show_samples=false&

![image](https://user-images.githubusercontent.com/11892704/31129560-f0370e2a-a822-11e7-9c8d-2d8ef4aa877a.png)
![image](https://user-images.githubusercontent.com/11892704/31129585-01364f7e-a823-11e7-81af-bfa600e96c16.png)

**Comment by alisman** [comment]
@schultzn glad you found this!

**Comment by schultzn** [comment]
I don't think this is fixed yet, or is it?

Don't see it here:
http://www.cbioportal.org/beta/index.do?session_id=59953b66498e5df2e2940f43&show_samples=false&

![image](https://user-images.githubusercontent.com/11892704/31353830-04fcd19e-ad02-11e7-9548-cee27f1ba881.png)

**Comment by alisman** [comment]
![image](https://user-images.githubusercontent.com/186521/31363777-b78d7c24-ad2e-11e7-81d6-2d01357db638.png)

Hi Niki, 
It is fixed for the the initial case that started this ticket, when the query includes only one cancer type.  But I see now this condition can arise from a filter and we don't cover that case.  Will do.
