### ISSUE TITLE
SVG file can be downloaded and opened in browser but not Illustrator

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3225]
... for lollipop.

The following error is given by Illustrator.
![screen shot 2017-10-03 at 3 21 34 pm](https://user-images.githubusercontent.com/5400599/31144367-8e6a5d1a-a84e-11e7-859e-f43393b5d3df.png)

This issue seems to effect all SVG downloading in the portal.

**Comment by alisman** [comment]
Is this true for legacy features as well?

**Comment by zhx828** [comment]
@alisman that's a good question. We got a report from a user using the new lollipop diagram. I tried with study view, it doesn't work there as well. But not sure whether the all other legacy features have the same issue. @onursumer never tried to open it in Illustrator with the old version. So there is no evidence indicating the previous lollipop supports it.

**Comment by jjgao** [comment]
We should try to fix it in the refactored code. If AI cannot open SVG, the downloaded file is not so useful.

**Comment by alisman** [comment]
agreed.

**Comment by alisman** [comment]
@Tamba32 do you have Illustrator so you could test/resolve this?

**Comment by Tamba32** [comment]
@alisman I dont have AI on this computer. I have it on my other computer at home though

**Comment by Tamba32** [comment]
@zhx828 Could you provide more detail about this? I opened my downloaded svg up in illustrator just fine
![image](https://user-images.githubusercontent.com/15708264/31693399-60d53f5e-b36c-11e7-8d06-0c8b1e8748e2.png)

**Comment by zhx828** [comment]
@Tamba32 It works ok now in my AI. But I haven't updated anything in my AI. So seems this is a random issue.

**Comment by adamabeshouse** [comment]
I fixed it around the same time you reported it :D https://github.com/cBioPortal/cbioportal-frontend/pull/667/files

**Comment by jjgao** [comment]
This problem seems to sneak back...

**Comment by adamabeshouse** [comment]
@jjgao only in lollipop?

**Comment by jjgao** [comment]
also in plots, haven't test others.

**Comment by adamabeshouse** [comment]
@jjgao it was the result of the recent change made by @dippindots to add `FreeSans` font to our Victory theme. @dippindots could you try to find a different font that would accomplish the same goal, and make sure you test in illustrator to make sure it can open it.

**Comment by dippindots** [comment]
@adamabeshouse Thanks! I will take a look at it.

**Comment by jjgao** [comment]
Thanks. I guess it may not be easy to make some test out of this?

**Comment by adamabeshouse** [comment]
@jjgao I don't think so since it still does open in SVG and in PDF.

**Comment by jjgao** [comment]
@dippindots I just wanted to make sure this is still on your to-do list? FYI - the svg on comparison page does not work either.

**Comment by dippindots** [comment]
@jjgao It is not on the top of my list, but I can prioritize this.

**Comment by jjgao** [comment]
@dippindots it'd be good to prioritize and see if there is an easy solution.
