### ISSUE TITLE
Overlapping sample label on timeline

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3226]
http://triage.cbioportal.mskcc.org/case.do#/patient?studyId=genie_akt1&caseId=GENIE-MSK-P-0000525&navCaseIds=GENIE-MSK-P-0000525
![screen shot 2017-10-03 at 6 39 22 pm](https://user-images.githubusercontent.com/1334004/31152467-3d2b32c8-a86a-11e7-8c65-e61e9559167a.png)

**Comment by jjgao** [comment]
@inodb is this still a problem?

**Comment by inodb** [comment]
Don't think so - looks fine here: https://genie.cbioportal.org/patient?caseId=GENIE-MSK-P-0000525&studyId=brca_akt1_genie_2019
