### ISSUE TITLE
cancer types summary tab: tooltip location too low on page

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3230]
Sometimes the tooltip appears very low, such that the text extends beyond the lower edge of the page, overlaps the footer text and gets greyed out:

See PTEN & BRAF in this query:
http://www.cbioportal.org/beta/index.do?session_id=59d4f996498e5df2e2962bb8&show_samples=false&

![image](https://user-images.githubusercontent.com/10508276/31183503-c57e3d70-a8f4-11e7-8416-8fcd7dc508ea.png)

![image](https://user-images.githubusercontent.com/10508276/31183634-220e26ea-a8f5-11e7-80a1-2b7fe031847d.png)

**Comment by khzhu** [comment]
@tmazor, it might be a browser issue. Tool tip looks fine from chrome.
<img width="1296" alt="screen shot 2017-10-04 at 11 22 28 am" src="https://user-images.githubusercontent.com/17375786/31184124-8bb54410-a8f6-11e7-8f6c-e6d3c2908405.png">

**Comment by tmazor** [comment]
@khzhu It only happens for me for some genes -- I agree that most look fine. Did you try the example I gave? Among all those genes, I only had that issue with BRAF & PTEN, and I see it in both chrome & safari.

**Comment by khzhu** [comment]
@tmazor , I tried your example from Safari, Firefox and Chrome. All looked fine.
![screen shot 2017-10-04 at 11 35 55 am](https://user-images.githubusercontent.com/17375786/31184844-8574e68a-a8f8-11e7-9898-9720fe3426a8.png)

**Comment by khzhu** [comment]
@tmazor , might be the version of your browser. The proportions in bar chart from your screenshot is not right as well, but not a problem from mines.

**Comment by khzhu** [comment]
I am using Chrome 61.0.3163.100. Firefox 56.0. Safari 10.1.2.

**Comment by khzhu** [comment]
@tmazor , sorry my bad, looked at PTEN and BRAF gene, got the same issue. Remove my comments posted for not confusing the viewer.
