### ISSUE TITLE
Web API: missing FUSION profiles in getGeneticProfiles

### ISSUE THREAD

**Issue by guv** [cBioPortal/cbioportal#3237]
When querying the web API using `cmd=getGeneticProfiles` only one study has a profile with `genetic_alteration_type = FUSION`.
For studies like _laml_tcga_pub_ there is FUSION data in the corresponding data archive but cbioportal does not return a profile with `genetic_alteration_type = FUSION`.

**Comment by jjgao** [comment]
@guv we are currently using mutations profile to store fusions.
