### ISSUE TITLE
Cancer Types Summary: Min % altered cases should be rounded

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3238]
Or why not simply allow a max of 100%?

http://www.cbioportal.org/beta/index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit&show_samples=false&

![image](https://user-images.githubusercontent.com/11892704/31353338-2f1ee5ea-ad00-11e7-8c7c-ab53b3bd3bbc.png)

**Comment by jjgao** [comment]
Maybe it's better to round / ceil it? If we always put 100% as max, most of the slide bar would not be useful if the alteration frequencies are low (e.g. 10%).

**Comment by schultzn** [comment]
I think the default should be rounded to the next 10% value, but a user should be allowed to make the maximum 100%. Can we do that?

**Comment by jjgao** [comment]
@schultzn you mean the max % of y axis? The current slide is used to define the cutoff to filter out bars. Maybe we need another checkbox to toggle that?

**Comment by jjgao** [comment]
One idea: maybe we can add a checkbox `Show unaltered`. When checked, we should a light gray bar and the y-axis will be:

1) 100% when using percentage.
2) all sample counts when using counts.

**Comment by jjgao** [comment]
@Tamba32 @alisman could you fix the number rounding issue for 1.9? We can delay the max option for 1.9.1.

**Comment by schultzn** [comment]
Making the slide range from 0 to 100% might still be simplest...

**Comment by jjgao** [comment]
so making the max editable? I like the idea.

**Comment by jjgao** [comment]
discussed with @alisman. We will round up the number for this release and implement the max option later.
