### ISSUE TITLE
cancer studies y-axis should max out at 100%

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3241]
The y-axis shouldn't go past 100%

http://www.cbioportal.org/beta/index.do?session_id=59d4f996498e5df2e2962bb8&show_samples=false&
![image](https://user-images.githubusercontent.com/10508276/31387734-76e9a75e-ad99-11e7-8321-3a3f750a03eb.png)

**Comment by jjgao** [comment]
But this has not been fixed: http://www.cbioportal.org/index.do?session_id=59d4f996498e5df2e2962bb8&show_samples=false&

**Comment by alisman** [comment]
Hi Tamba, 
So, we still have a problem with this issue.  If we set max to 100% then it will always be 100% even when biggest data point is much smaller.
