### ISSUE TITLE
Non-sequenced genes in Mutual Exclusivity tab

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3242]
http://www.cbioportal.org/genie/index.do?session_id=59dcd679498e5df2e2966c3e&show_samples=false&

A gene that is not sequenced (because it is not on the gene panel), results in `Log Odds Ratio: 3` and `p-value: 1`. It would be nice to hide these rows when one of the genes (NEK7 in example) is not sequenced.

<img width="1023" alt="screen shot 2017-10-10 at 16 24 29" src="https://user-images.githubusercontent.com/9624990/31391754-bdefdc5c-add7-11e7-9532-2c193838a366.png">

**Comment by ersinciftci** [comment]
I think we should show all the queried genes. If the user doesn't want to see a particular gene because it's not on the gene panel, they can remove it from the query.

**Comment by sandertan** [comment]
Another solution is to make the cells of these genes empty or show `Not available`.

But indeed as @ersinciftci said, a new query without these would also solve this.

**Comment by ersinciftci** [comment]
Yeah maybe we can say `Not Sequenced` instead of hiding.

**Comment by jjgao** [comment]
Ideally, we should also exclude N/S cases in either gene for analysis. We would need to modify the input (TRUE or FALSE) to (TRUE or FALSE or NA/NULL). If all samples are NA for a gene, you would not be able to calculate p-values etc.

We would also need to consider sample list b/c one may select cases_all. -- we should handle that in oncoprint as well.

Obviously this is for future improvement.

**Comment by sandertan** [comment]
<img width="720" alt="screenshot 2019-03-06 at 13 59 35" src="https://user-images.githubusercontent.com/9624990/53883054-4571f600-4018-11e9-9153-dd3df1b31ca1.png">

This is still applicable

http://genie.cbioportal.org/results/cancerTypesSummary?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=genie_public&case_set_id=genie_public_sequenced&clinicallist=NUM_SAMPLES_PER_PATIENT&data_priority=0&gene_list=TP53%2520BRAF%2520NEK7&geneset_list=%20&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=genie_public_mutations&show_samples=false&tab_index=tab_visualize

**Comment by dippindots** [comment]
same issue with the https://github.com/cBioPortal/cbioportal/issues/6033
