### ISSUE TITLE
Enrichment tab: Can't add genes to query

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3250]
In the enrichment tab, the button "Add checked genes to query" is not working. It results in an error message.

![screen shot 2017-10-13 at 11 34 50](https://user-images.githubusercontent.com/9624990/31540034-bd8a1a4a-b00a-11e7-9864-212569ad4269.png)
http://www.cbioportal.org/index.do?session_id=595ba299498e5df2e29203d8&show_samples=false&

Also, the spacing between the plot and table could be increased.

**Comment by jjgao** [comment]
@alisman I'll discuss with you on this.

**Comment by inodb** [comment]
Deployed

**Comment by sandertan** [comment]
Hi @inodb thanks for this fix. The issue is solved when querying from the query page.

Unfortunately, when querying from the Study View, adding a gene in the enrichment tab leads to a java.lang.NullPointerException. Can you take a look?

<img width="855" alt="screen shot 2017-11-30 at 15 33 44" src="https://user-images.githubusercontent.com/9624990/33436147-88c57e8a-d5e4-11e7-9cf9-cbcbe7940772.png">

**Comment by inodb** [comment]
@sandertan this seems to be fixed? Could you let me know how to reproduce the bug otherwise? Thanks!

**Comment by sandertan** [comment]
Hi @inodb, yes it appears to be fixed, thanks!
