### ISSUE TITLE
Prevalence based on gene expression without mutations calculated incorrectly

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3251]
In this test case with only mRNA up/down regulation, but no mutations, the prevalence is calculated incorrectly (112%!). 

The prevalence should be calculated by dividing the altered samples by the sum of non-overlapping:
- "samples sequenced for mutations"
- "gene expression samples"

![screen shot 2017-10-13 at 11 42 37](https://user-images.githubusercontent.com/9624990/31542684-51e59fb8-b013-11e7-8537-1330b1fc3710.png)

I guess 'sequenced' samples are supposed to be the samples that are assayed for mutations. Another solution would be to split the mRNA-altered samples from the mutation-altered samples, and base the prevalence purely on mutation-altered samples.

**Comment by adamabeshouse** [comment]
@jjgao what do you think we should do?

**Comment by jjgao** [comment]
@adamabeshouse it's a tricky one. I don't see an easy solution.

We should have the data below:

- samples of each profile
- gene panels of each profile and sample

When the samples of different profiles are different, it is actually impossible to calculate an accurate percentage. One option would be: use the union of samples with tooptip explaining the details.

**Comment by adamabeshouse** [comment]
@jjgao what should we do about this?

**Comment by jjgao** [comment]
@adamabeshouse is it possible to load gene panel per profile and combine them? It's ok to assume that gene panel only apply to mutations and cna data.

**Comment by adamabeshouse** [comment]
thats not going to completely address this https://github.com/cBioPortal/cbioportal/issues/4104 which includes mrna alterations in "unsequenced" samples

**Comment by tmazor** [comment]
Related user reported issue:
https://groups.google.com/forum/#!topic/cbioportal/5b417PeVV3c

Sample without mutation profiling but with copy number/expression/protein show up to the right of samples that have mutation profiling but no alterations:
![image](https://user-images.githubusercontent.com/10508276/39131889-8c390364-46de-11e8-9e69-ab3f740873b9.png)

**Comment by adamabeshouse** [comment]
fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/1110
