### ISSUE TITLE
Wrong coverage info "whole exome sequencing"

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3252]
The default pop-up in oncoprint shows wrong coverage info. It looks like it has a hard-coded default of "whole exome sequencing". 
Example:
1. go to home page and select METABRIC Breast cancer study. The tooltip of mutations profile clearly states "Mutation data from targeted sequencing of 173 genes":
![image](https://user-images.githubusercontent.com/2900303/31605937-f723a050-b267-11e7-9aa9-891638535621.png)
2. Submit a query
3. In oncoprint hover over any sample. It will state "Coverage: whole exome sequencing":
![image](https://user-images.githubusercontent.com/2900303/31606040-42e6c3b4-b268-11e7-8ea2-c6bb0723d89a.png)

**Proposed solution**: the tooltip should *not* show "Coverage: whole exome sequencing" by default but rather show the mutation profile's description by default (as is done in query page). This default is  only overwritten in case any gene panel is configured.

**Comment by jjgao** [comment]
related to https://github.com/cBioPortal/cbioportal/issues/2556.

It's a good idea to use the mutation profile's description by default. @adamabeshouse

**Comment by pieterlukasse** [comment]
@jjgao it is only slightly related to #2556, since there it is about Gene Panels. Here we have an example of a study not configured with gene panels.

**Comment by sandertan** [comment]
Currently, when a sample is not sequenced but is added to study as clinical data, and it is queried, it shows 'Whole exome sequencing' and also the prevalence is calculated based on this (empty) sample. Using the mutation profile's description would not solve this case.

@jjgao is changing the design an option? By making the default box 'light grey/Not Sequenced' and use the case lists to find out which samples are sequenced, this could be solved.

I think this is a use case when for example mutation data did not pass quality control, will be added at a later time, or the sample contains only expression data.

**Comment by adamabeshouse** [comment]
@jjgao do we still want to do this? use the mutation profile description instead of "Whole-Exome Sequencing" everywhere?

**Comment by jjgao** [comment]
@adamabeshouse Maybe not. I just notice some of the profile descriptions are really long. We need to have better meta data for profiles.

@ritikakundra we should have the gene panel data for Metabric.

**Comment by jjgao** [comment]
@sandertan I think your proposal is captured in https://github.com/cBioPortal/cbioportal/issues/2556 and has been fixed.

**Comment by pieterlukasse** [comment]
the original issue does not seem to be present anymore. The tooltip simply displays other information now:

![image](https://user-images.githubusercontent.com/2900303/60015369-9a974d80-9683-11e9-9abc-c45196e03dd4.png)

**Comment by pieterlukasse** [comment]
@jjgao there is a new issue though (small one): the home page states "Select Genomic Profiles" and the tooltip talks about "molecular profiles". Would be nice if the wording could be the same.
