### ISSUE TITLE
Cancer Type Summary: support cancer study

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3265]
When querying for multiple studies, we need to provide an option to switch to use cancer studies in the x-axis. This is critical for the virtual study feature.

**Comment by Tamba32** [comment]
@jjgao When you are querying multiple studies, don't we use a different page & tab than the Results page and Cancer Type Summary tab?  Doesn't multiple studies lead you to this cross-cancer overview display http://www.cbioportal.org/cross_cancer.do?#crosscancer/overview/0/CDKN2A%20MDM2%20MDM4%20TP53/blca_tcga%2Ccellline_ccle_broad ? Isn't this a separate task?
