### ISSUE TITLE
gene name not aligned with oncoprint in svg/pdf

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#327]
![image](https://cloud.githubusercontent.com/assets/840895/10378170/696a3eaa-6dd5-11e5-982e-8d283f0eff1a.png)

**Comment by adamabeshouse** [comment]
Is this HTML, SVG, PDF?

**Comment by jjgao** [comment]
Sorry, svg & pdf

**Comment by jjgao** [comment]
Not a urgent issue.

**Comment by adamabeshouse** [comment]
I think we should "won't fix" this since we're about to reimplement the rendering

**Comment by jjgao** [comment]
Let's keep it here so we can check in the new implementation.

**Comment by adamabeshouse** [comment]
Confirmed working in new implementation
