### ISSUE TITLE
Tweak the survival tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3271]
Can we remove the legend and put the red and blue bars into the table? `p=xxx` can be displayed in the figure with an info icon "Logrank test p-value"

![screen shot 2017-10-19 at 4 15 29 pm](https://user-images.githubusercontent.com/840895/31792072-c5a6aad0-b4e8-11e7-85cd-e42f5a6fc428.png)

**Comment by ersinciftci** [comment]
@jjgao Download PNG option downloads the content of the canvas, so if we remove the legend, it won't show up in the PNG, and `Logrank test p-value` won't show up either. The same will apply when we recreate this chart with an SVG library, downloaded SVG/PDF won't have a legend if we remove it.

**Comment by jjgao** [comment]
@ersinciftci any chance we can make the table into the figure? I am not worry about "Logrank test p-value" not showing up.

Since the web site is more frequently used than download, it's important to keep it clean.

**Comment by ersinciftci** [comment]
@jjgao I don't think we can put the table into the figure
