### ISSUE TITLE
direct link to cancer types summary doesn't work anymore

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3273]
This link used to directly load the Cancer Types Summary tab:
http://www.cbioportal.org/index.do?session_id=59690649498e5df2e292870c&show_samples=false&clinicallist=AGE&#pancancer_study_summary

But if you click it now, it doesn't load any data:
![image](https://user-images.githubusercontent.com/10508276/31794419-490b82c2-b4f0-11e7-8130-347ee80d0989.png)

Direct links to other tabs seem to be working so this is somehow specific to the new Cancer Types Summary tab.

**Comment by jjgao** [comment]
data is loading now, but the direct link to the tab is not working. @alisman

**Comment by jjgao** [comment]
Make sure direct link to every tab works
