### ISSUE TITLE
an ampersand gets added to the end of URLs and breaks them

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3274]
If you right click on a tab and load it in a new window, you get a URL specific to that tab -- for example http://www.cbioportal.org/index.do?session_id=59690649498e5df2e292870c&show_samples=false&clinicallist=AGE&#mutex will go directly to the Mutual Exclusivity tab.

However, during the process of the page loading, an ampersand gets added to the end of the URL (http://www.cbioportal.org/index.do?session_id=59690649498e5df2e292870c&show_samples=false&clinicallist=AGE&#mutex&). This link with the ampersand no longer works as a direct link to Mutual Exclusivity and will default back to loading OncoPrint. So if you click the first link and then reload the page (or wait until after it finished loading to copy the link), you end up at the OncoPrint tab.

Why does that ampersand get added? Can we get rid of it?

**Comment by jjgao** [comment]
@adamabeshouse Could you fix this during oncoprint tab refactoring?

I am also thinking of removing all the status (&show_samples=false&clinicallist=AGE) in the url and put it into the session. Every time the user click on the bookmark/twitter/session icon, a new session should be generated. @Tamba32 @alisman

**Comment by adamabeshouse** [comment]
yes this will be fixed in the refactor. I'm going to handle the URL parameters in a much less hacky way that will fix this.

**Comment by adamabeshouse** [comment]
fixed by refactor, merged into `rc`
