### ISSUE TITLE
Mutation Mapper gets slow after clicking several tabs

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3275]
Mutation mapper gets slow after clicking several tabs (uses a ton of memory). Try for instance this link and click on a few different genes in the mutation mapper:

http://www.cbioportal.org/index.do?session_id=59ea1ed8498e5df2e296fd66

It might be that we are getting to the limits by loading all the different tabs into memory now. Before we reloaded each page. Though before at `1.8.0` I think it was using less memory, so could also be some leak (we should test some older version and see).

**Comment by adamabeshouse** [comment]
@alisman could this have to do with MSKTabs?

**Comment by inodb** [comment]
FYI noticed a similar issue on cancer type summary

**Comment by jjgao** [comment]
do we still have the problem?

**Comment by jjgao** [comment]
@inodb @alisman please verify the issue.

**Comment by inodb** [comment]
@jjgao this seems to have been fixed now, maybe because of what @adamabeshouse mentioned?

**Comment by inodb** [comment]
ok yeah Aaron just confirmed it was indeed cause of the MSK tabs not unmounting
