### ISSUE TITLE
Mutation Mapper table is shown before data is downloaded

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3276]
When clicking on a tab in the mutation mapper it shows the table before the download is done:

![screen shot 2017-10-20 at 12 10 42 pm](https://user-images.githubusercontent.com/1334004/31830948-c66c70ce-b58f-11e7-94c1-99abd3080e28.png)

**Comment by onursumer** [comment]
I think the bug is introduced by this commit: https://github.com/cBioPortal/cbioportal-frontend/commit/37228ec4fcf3e980b8e83b77ef1d0e71b77e0293

Waiting for `this.props.store.mutationData.isPending` should fix it.
