### ISSUE TITLE
enrichments tab "add gene to query" button doesn't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3283]
I get this very nice error message when I try to use the "add checked genes to query" button on the enrichments tab:
![image](https://user-images.githubusercontent.com/10508276/31966999-88d06b96-b8da-11e7-969d-eb7ba283bd6f.png)

Here's an example query:
http://www.cbioportal.org/index.do?session_id=5956356e498e5df2e291e06c&show_samples=false&#enrichementTabDiv

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/cbioportal/issues/3250
