### ISSUE TITLE
Public API clients should only connects to the public client

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3289]
When we release the official API, we will also release public API clients. We should only expose the public (not internal) API endpoints in those clients.

**Comment by inodb** [comment]
If we end up using the swagger generated clients, it's up to the user to point it to the right URL cbioportal.org/api. This is prolly mostly a documentation issue

**Comment by ersinciftci** [comment]
Unassigning myself for now, as I don't know if I'll be the one generating the API clients for R, Python etc., but I agree.
