### ISSUE TITLE
Gene synonym issue from study summary page

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#3297]
If a gene alias exists for a gene symbol, nothing prevents the user from performing a query using the \"old\" symbol which results in an incomplete query (Oncoprint, etc) see example below.  This may be considered a "user" error.

For example, if you search PDL1 in the portal it says synonym:CD274, which is correct, but it returns the following result:

![pastedgraphic-1](https://user-images.githubusercontent.com/366003/32187076-4aacbeb0-bd7a-11e7-967f-00fdf6c525e9.png)

instead of 

![pastedgraphic-2](https://user-images.githubusercontent.com/366003/32187088-4f3d19b6-bd7a-11e7-951b-3f8daee7b90d.png)

**Comment by jjgao** [comment]
How did you get to the first result? By changing the gene symbol in the url?
