### ISSUE TITLE
OncoKB Feedback Button does not work on long URLs

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3298]
example by request

**Comment by zhx828** [comment]
- [ ]  For the long URL in result page, we could generate the patient view URL instead
- [ ]  For patient view page, we can trim off all characters after the # sign

**Comment by inodb** [comment]
@zhx828 we use parts after the `#` sign for routing on `cbioportal-frontend`, so you prolly just want to trim off `navCaseIds=ada,dadada,dada`

**Comment by zhx828** [comment]
This issue has been solved in https://github.com/cBioPortal/cbioportal-frontend/pull/1993
