### ISSUE TITLE
Wiki Page for Authenticated Users via SAML

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#33]
With much help from Ben, I think I now understand how to get SAML working within a new instance of cBioPortal.

I have distilled all my notes from Ben into a new wiki doc:  https://github.com/cBioPortal/cbioportal/wiki/Authenticating-Users-via-SAML

I also made a few tweaks to this page:

https://github.com/cBioPortal/cbioportal/wiki/User-Authorization

Please take a look, and let me know if you would like me to make any revisions.  Once I get feedback, I will close this issue.  Thanks.

**Comment by n1zea144** [comment]
One thing we need to think about - we should separate out institute specific implementation of the user details service interface from the cbioportal repository.  Maybe we should all maintain some cbioportal-private repository which mimics the package/path found in cbioportal where we place custom implementations and we create an appropriate pom.xml in that module.

In fact we are currently reworking some clinical data pipelines where we are going to encounter the same issue - a public interface with private implementations.

Thoughts?

B

**Comment by ecerami** [comment]
Wiki docs on this are complete.  Closing.
