### ISSUE TITLE
Authorization error in private protals

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#3302]
org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver - Resolving exception from handler [public java.util.List<org.mskcc.cbio.portal.model.DBGeneticProfile> org.cbioportal.weblegacy.ApiController.getGeneticProfiles(java.lang.String,java.util.List<java.lang.String>)]: org.springframework.security.access.AccessDeniedException: Access is denied

**Comment by kalletlak** [comment]
probably because of
https://github.com/cBioPortal/cbioportal/blob/master/security/security-spring/src/main/java/org/cbioportal/security/spring/CancerStudyPermissionEvaluator.java#L125

changing `GeneticProfileId` to `MolecularProfileId`

**Comment by ersinciftci** [comment]
@kalletlak that's just a comment line, the actual code checks `"List<MolecularProfileId>".equals(targetType) || "List<GeneticProfileId>".equals(targetType)`, does this issue still exist? @jjgao

**Comment by kalletlak** [comment]
I think it got fixed with https://github.com/cBioPortal/cbioportal/pull/3208. I'll rebase and test it.
