### ISSUE TITLE
Double API calls genome nexus for canonical isoform endpoint

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3308]
This is not in production yet but should be fixed for 1.10.0
![screen shot 2017-11-02 at 12 20 06 pm](https://user-images.githubusercontent.com/1334004/32337477-846fbb7a-bfc8-11e7-825d-bad44602b3fb.png)

**Comment by jjgao** [comment]
@inodb I still see it multiple times in beta. And it is strange that when I click NRAF, the KRAS end point loaded again.

**Comment by jjgao** [comment]
@inodb could you verify this issue?

**Comment by inodb** [comment]
@jjgao I don't see multiple calls now as before, but i do still see the issue you described that it calls the `canonical-transcript` endpoint again for a previous gene when you click on a different tab
