### ISSUE TITLE
API call failing with HTTP 500 where 404 is expected

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3313]
Example: 

http://www.cbioportal.org/api/molecular-profiles/acc_tcga_rna_seq_v2_mrna/molecular-data?sampleListId=wrong_sample_list&entrezGeneId=1&projection=SUMMARY

Notify: @ersinciftci

**Comment by ersinciftci** [comment]
@pieterlukasse Actually it's supposed to return an empty list since sampleListId is not a path variable. Opening a PR that will also fix this now.
