### ISSUE TITLE
Validate presence of gene panel

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3314]
When loading gene panel study data for a gene panel that is not in the database yet, the importer crashes. It would be nice if the validator checks if a study's gene panel is present in the database before loading the study.

**Comment by sandertan** [comment]
We can use http://www.cbioportal.org/api/swagger-ui.html#/Gene_Panels/getAllGenePanelsUsingGET for that

**Comment by pieterlukasse** [comment]
:+1:

**Comment by sandertan** [comment]
Done!
