### ISSUE TITLE
query from cancer study view page is not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3322]
http://www.cbioportal.org/alpha/

Hongxin: could you look into this quickly?

cc'ing @alisman

**Comment by zhx828** [comment]
Query from study view to result page is working;
Query from study view to main page is complaining invalid sample id
The main page is not updated with the latest virtual study branch, the study summary icon should be a pie chart

**Comment by jjgao** [comment]
@zhx828 forgot to mention. Please use `localStorage.heroku = "cbioportal-frontend-pr-728";`

**Comment by zhx828** [comment]
Please use localStorage.heroku = "cbioportal-frontend-1-10-0" instead. The previous instance has been closed. This issue is no longer exist.
