### ISSUE TITLE
Virtual Studies data model and flow

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#3324]
Proposed structure for saving virtual studies

###### back-end data model
```
{
  "id" : "5a031b7dd4c6871d8cfbdd0f",
  "name": "test",
  "created": 1492571415870,
  "studies": [
    {
      "id": "study_1",
      "samples": [
        "sample_11",
        "sample_12"
      ]
    },
    {
      "id": "study_2",
      "samples": [
        "sample_21",
        "sample_22"
      ]
    }
  ],
  "description": "description",
  "filters": {
    "samples": {},
    "patients": {}
  },
  "owner": "user1@gmail.com",
  "users": ["user1@gmail.com","user2@gmail.com"],
  "origin": ["study_1","study_2","virtual_study_1"],
  "version": 1.0
}
```
##### 1.  New Virtual Study
   ```Login --> Select studies --> Apply filters --> Save --> User can see studies in home tree structure```
##### 2.  Delete Virtual Study
   ```Login --> Click delete from tree structure --> update mongodb document by removing userid from users --> update Virtual Studies in home tree structure```
##### 3. Share Virtual Study
   ```Open Virtual Study in Study View page and click save
 --> if filtered then create a new one
 --> else update existing virtual study users list
   ```

**Comment by kalletlak** [comment]
`origin` is to track the parent.
if its a new study the origin would be the `selected studies` else if it is created by applying filters on another virtual study then the new origin would be the `id`

**Comment by jjgao** [comment]
@kalletlak could you add the current format for comparison?

**Comment by jjgao** [comment]
@kalletlak I think we should also put a data model version in it.

**Comment by jjgao** [comment]
from @kalletlak: the current one.

```
{
  "studyName": "Custom Cohort (2017-11-09 20:07:56.112Z)",
  "description": "Cholangiocarcinoma (NCCS): 2 samples / 2 patients\n",
  "userID": "DEFAULT",
  "created": 1510258076112,
  "filters": {
    "samples": {
      "ANATOMICAL_SUBTYPE": [
        "Extrahepatic"
      ]
    },
    "patients": {
      "GENDER": [
        "F"
      ]
    }
  },
  "selectedCases": [
    {
      "studyID": "chol_nccs_2013",
      "samples": [
        "990196",
        "1202"
      ],
      "patients": [
        "990196",
        "1202"
      ]
    }
  ]
}
```

**Comment by kalletlak** [comment]
@jjgao added version to model

**Comment by kalletlak** [comment]
@jjgao @zhx828 should we replace `filters` with the `StudyViewFilter` from the study-view api?

**Comment by zhx828** [comment]
@kalletlak it's a good idea, then we can directly apply the filters to the new study to reproduce. We can then let user decides to save by filters or by currently selected samples.

**Comment by jjgao** [comment]
@kalletlak good idea!
