### ISSUE TITLE
Study is not selected after clicking query button from study view page

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3330]
This is tested from iviz branch.

![nov-08-2017 16-44-02](https://user-images.githubusercontent.com/5400599/32576178-2464d9b4-c4a4-11e7-92d1-d671ccfad112.gif)

**Comment by zhx828** [comment]
Seems this only happens if there is virtual study created

**Comment by inodb** [comment]
@zhx828 If you select multiple studies, they are not selected after clicking query (#3335 doesn't seem to solve this)

**Comment by inodb** [comment]
@zhx828 also clicking the "query this study" button does not seem to work yet for multiple studies?

**Comment by kalletlak** [comment]
Somewhat related #3340

**Comment by kalletlak** [comment]
@zhx828 added comment on #3335
