### ISSUE TITLE
tweaks on the cancer types summary tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3332]
- [x] if there is only one study, select "cancer type" by default
- [x] if there is only one study and one cancer type, select "cancer type detailed"
- [x] solve the "cancer type detailed" issue when there are too many of them
- [x] Use cancer study shortName prop when grouped by study
- [x] fix slider expansion issue

**Comment by inodb** [comment]
@alisman are all these fixed now?

**Comment by jjgao** [comment]
For the issue: `solve the "cancer type detailed" issue when there are too many of them`, @alisman could you add a warning message that only the top 50 were displayed? In the next round, maybe we can add a scroll bar?
