### ISSUE TITLE
option to add gaps between different groups based on clinical attribute

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3336]
I found people like to add a space between different groups when sorting by a clinical attribute. Maybe we can implement that?

![image](https://user-images.githubusercontent.com/840895/32633473-a8a852e2-c575-11e7-9077-56d35a380770.png)

**Comment by adamabeshouse** [comment]
this wouldn't be too hard to implement. what would be a good UI for this?

**Comment by jjgao** [comment]
Maybe add another checkbox under `View`: `Show whitespace between sorted clinical groups`?

![image](https://user-images.githubusercontent.com/840895/32679889-236d9f6c-c636-11e7-9623-6cbc6fe1b556.png)

**Comment by adamabeshouse** [comment]
That's a good idea, so if it's not sorted then there's no effect. That sounds good to me.

**Comment by jjgao** [comment]
yes.

**Comment by adamabeshouse** [comment]
let's leave this until after 1.11?

**Comment by schultzn** [comment]
Love the idea!

**Comment by jjgao** [comment]
@adamabeshouse yes, we can do this later.

**Comment by adamabeshouse** [comment]
one question is what if you are sorting by more than one clinical attribute? would it only be the topmost track? or maybe the bottommost? also im assuming this would only be for categorical data?

**Comment by jjgao** [comment]
Good question. Maybe the bottommost (which basically means all sorted tracks, right?) and see how it looks like?

Yes, only for categorical data.

**Comment by adamabeshouse** [comment]
I think the utility could depend...

Topmost makes sense to me because that most cleanly defines categories. The sort order is determined top to bottom, so if you have it as the bottommost sorted track then the categories will be split up more, which doesnt seem to be the main thrust of this feature.

**Comment by adamabeshouse** [comment]
maybe the best way to do this would be as an option in the clinical track menus? to toggle splitting for a particular track

**Comment by jjgao** [comment]
@adamabeshouse great idea!

**Comment by adamabeshouse** [comment]
@jjgao @schultzn do we still want to do this?

**Comment by schultzn** [comment]
Yes, it would be great.

**Comment by adamabeshouse** [comment]
@schultzn @jjgao 

I have a preliminary implementation:

![image](https://user-images.githubusercontent.com/636232/70100454-cc7fe900-15ff-11ea-8ac7-db472625cc28.png)


![image](https://user-images.githubusercontent.com/636232/70100471-d6095100-15ff-11ea-8eb2-74907953434f.png)


![image](https://user-images.githubusercontent.com/636232/70100483-dd305f00-15ff-11ea-8faa-c2778cbcb334.png)


how do you think the gaps should interact with the zoom? should they zoom or stay the same size?

**Comment by schultzn** [comment]
Looks great!
1 - yes, gaps look big enough
2 - they should probably stay the same size when zooming
3 - when grouping by the track, maybe automatically sort?
4 - a single track is probably enough

**Comment by inodb** [comment]
Hey this is really cool! I was wondering, maybe a separate issue. Would it make sense to add oncoprint to the group comparison page? Then each group could be separated by these gaps. Perhaps additionally have the name of the group as a title above each "gapped part"

**Comment by adamabeshouse** [comment]
do we want the gaps to be reflected in the mini map?

![image](https://user-images.githubusercontent.com/636232/70186869-d9adde00-16ba-11ea-870c-8b0f872f4c19.png)

**Comment by jjgao** [comment]
> do we want the gaps to be reflected in the mini map?

Sorry this question fell between the cracks. I don't think it's very important so I whichever is easy from an implementation perspective.
