### ISSUE TITLE
How to deal with different versions of TCGA studies?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3337]
Now that we have virtual studies, the duplication of samples in our database will be an outstanding issue. For example, one can merge all studies in the public portal now, and a lot of the TCGA samples get duplicated in the merged virtual study.

We have talked about supporting study/profile versioning (e.g. one breast TCGA study with multiple versions and only one version can be selected). I think we should make that a priority as a long-term solution (or come up with a better solution).

For the short term (release 1.10), we should at least put some message on the interface. A few options I can think of:

1. Add a warning message on the study view page if duplicated TCGA provisional studies and published studies are selected.
1. Similarly to results page
1. for 1) and 2), add an quick option to remove duplicated published or provisional study
1. in the query interface, add quick option to select/hide TCGA provisional studies.

@n1zea144 @schultzn @ecerami @Tamba32 @inodb @zhx828 @alisman

**Comment by jjgao** [comment]
@alisman @zhx828 let's work on # 1 & 2 for this release and # 3 & 4 for later.

**Comment by jjgao** [comment]
Based on sample IDs, to display the list of duplicated studies.

**Comment by alisman** [comment]
@jjgao 1. Is this ok placement for the message?  2. Do we want to list the names of the overlapping studies in this alert?  3. Bootstrap has a few different [alert](https://getbootstrap.com/docs/3.3/components/#alerts) levels, is there one you think would make sense? 

![image](https://user-images.githubusercontent.com/186521/32911506-5ac320e2-cada-11e7-88a6-f6909350e26d.png)

**Comment by jjgao** [comment]
@alisman I think this is a good place to place the message. I would made message more obvious -- like a real warning.

The message can be: "You have selected duplicated versions of TCGA studies." It would be good to add two buttons in a new line "Include TCGA provisional studies only" and "Include TCGA published studies only". If there are two published versions selected, pick the new one, e.g. pick brca_tcga_pub2015 over brca_tcga_pub, similar gbm_tcga_pub2013 over gbm_tcga_pub.

**Comment by jjgao** [comment]
nsclc_tcga_broad_2016 also has duplicated samples.

**Comment by alisman** [comment]
So I should hardcode logic for those studies?  Are there any others?

**Comment by jjgao** [comment]
@alisman I am querying the database and see how many of them are duplicated. Maybe we can have a json file of duplicated studies for now? Later we can solve them properly.

**Comment by alisman** [comment]
sounds good

**Comment by jjgao** [comment]
As discussed, we will display the message and highlight the overlapping studies in the query interface.

**Comment by jjgao** [comment]
I logged the data overlapping problem in issue #3395
