### ISSUE TITLE
Study name missing beside 'Modify Query' button

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#3339]
cbioportal beta
![screen shot 2017-11-10 at 11 21 04 am](https://user-images.githubusercontent.com/12956870/32667688-6208fb4a-c609-11e7-909a-67f0261eb535.png)
cbioportal public
![screen shot 2017-11-10 at 11 21 14 am](https://user-images.githubusercontent.com/12956870/32667692-6456f8fc-c609-11e7-8e60-93ad0bcaad14.png)

**Comment by alisman** [comment]
Problem is that it seems iviz changes caused the following event not to be fired: @adamabeshouse  any wisdom?
** $.when(window.QuerySession.getAlteredSamples(), window.QuerySession.getStudyPatientMap(), getCohortName()).then(function(altered_samples, studyPatientMap, studyName) {**

**Comment by adamabeshouse** [comment]
good catch @alisman https://github.com/cBioPortal/cbioportal/pull/3347
