### ISSUE TITLE
how to deal with merging many studies

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3341]
We can now merge up to all studies in the portal into a virtual study. The problem is that when viewing all studies in the study view page, it takes a lot of time to load and render. It may kill the browser too. We would need to find a solution. A few options:

- [x] only allow merging/viewing fewer than 20 (?) studies [short term]
- [ ] display fewer attributes. [long term]
- [ ] improve api performance. [long term]
- [ ] api for mutated genes talbe
- [ ] api for cna genes table
- [ ] api for gene panel data

@zhx828 @schultzn @ecerami @ersinciftci

**Comment by inodb** [comment]
1. is fixed
