### ISSUE TITLE
cbioportal.war not able to deploy to tomcat 8

### ISSUE THREAD

**Issue by wdduncan** [cBioPortal/cbioportal#3348]
I am trying to set up a local instance of cbioportal  using the installation instructions outlined here:
http://cbioportal-inodb.readthedocs.io/en/latest/README.html

I am able to load the database fine. That is, I can run the data load and validator scripts. However, when go to deploy the war file, I am getting errors. There is a lot to print out, but here are some:

Error creating bean with name 'genePanelMapperLegacy' defined in class path resource [applicationContext-business.xml]: Cannot resolve reference to bean 'sqlSessionFactory' while setting bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.

nested exception is javax.naming.NameNotFoundException: Name [jdbc/cbioportal] is not bound in this Context. Unable to find [jdbc].

javax.naming.NameNotFoundException: Name [jdbc/cbioportal] is not bound in this Context. Unable to find [jdbc].

I am using: 
Apache 8.5.23 
OS X 10.12.6
MySQL 5.6.27 Community Server 
cBioportal build 1.9.0

Any ideas?

**Comment by jjgao** [comment]
@wdduncan it looks like you don't have the tomcat context.xml configured.

@pieterlukasse @inodb: I couldn't find it in the instructions. Do we have that?

**Comment by wdduncan** [comment]
Thanks. I fixed the context.xml file.
