### ISSUE TITLE
network view comes up empty

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#3349]
An "Uncaught TypeError" is seen in the console.

**Comment by onursumer** [comment]
![cytoscape_not_a_function](https://user-images.githubusercontent.com/3604198/32807683-ae8f5ce0-c95e-11e7-9122-10ab2077e944.png)


Seems like something is preventing `cytoscape` library to properly plug itself into `jQuery`. I suspect that recently added virtual cohort libraries are causing this problem.

Especially this line looked suspicious to me: https://github.com/cBioPortal/cbioportal/blob/release-1.10.0/portal/src/main/webapp/WEB-INF/jsp/global/js_include.jsp#L114

**Comment by inodb** [comment]
Fixed in cbioportal.org/beta
