### ISSUE TITLE
Null Pointer Exception when query combined studies with genes - beta portal

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3353]
After submitting all samples with KRAS TP53 query, the backend does not respond which leads to empty page. And this is random(maybe study specified). Was doing the query in http://www.cbioportal.org/beta/study?id=5a07544b498e5df2e29811c5#summary

The backend throws the following error:
![screen shot 2017-11-13 at 10 39 36 am](https://user-images.githubusercontent.com/5400599/32734096-fc45c6dc-c85e-11e7-9e6e-e4c0e4152400.png)

**Comment by kalletlak** [comment]
@zhx828 fixed this in https://github.com/cBioPortal/cbioportal/pull/3343
