### ISSUE TITLE
Disable heatmap menu in oncoprint when querying multiple studies? 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3355]
I just combined a few studies with some expression data (expression data in at least one of them), and I get this oncoprint after adding the heatmap:

![image](https://user-images.githubusercontent.com/2900303/32737512-92c2a838-c89a-11e7-915c-e2f729d32600.png)

I was wondering whether we should support expression data related features like this now? Especially the heatmap could be an issue given each study might have a different "normal"  group for the z-score calculation.

**Comment by pieterlukasse** [comment]
Notify: @jjgao @schultzn

**Comment by fedde-s** [comment]
Technically the heatmap does already keep the profiles from different studies strictly separate, even if the menu doesn't clarify which profile is which. The screenshot below shows an Oncoprint with two expression heatmaps, each with data only for the samples of one of the two studies, and a heatmap menu in which the two profiles are indistinguishable by name.

![Screenshot described above](https://user-images.githubusercontent.com/4929431/32738311-c8bc737c-c89c-11e7-9476-357e6f23464c.png)

**Comment by jjgao** [comment]
duplicate with #3356
