### ISSUE TITLE
trouble compiling model file for cbioportal source code

### ISSUE THREAD

**Issue by ashraf123456789** [cBioPortal/cbioportal#3361]
When I attempt to install maven in the cbioportal directory, the portal master is successfully compiled but not the model file: here's the error after running **mvn -DskipTests clean install** in the correct directory:

```ShellSession
$ mvn -DskipTests clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Portal Master
[INFO] model
[INFO] Portal Business Layer
[INFO] persistence
[INFO] persistence-api
[INFO] db-scripts
[INFO] persistence-mybatis
[INFO] security
[INFO] security-spring
[INFO] service
[INFO] Portal Core
[INFO] Portal Web Layer
[INFO] cBioPortal
[INFO] Portal Scripts
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Portal Master 1.9.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ master ---
[INFO] Deleting C:\Users\shaba033\cbioportal\target
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (default) @ master ---
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:prepare-agent (pre-unit-test)                                                                                             @ master ---
[INFO] argLine set to -javaagent:C:\\Users\\shaba033\\.m2\\repository\\org\\jaco                                                                                            co\\org.jacoco.agent\\0.7.6.201602180812\\org.jacoco.agent-0.7.6.201602180812-ru                                                                                            ntime.jar=destfile=C:\\Users\\shaba033\\cbioportal\\target\\coverage-reports\\ja                                                                                            coco-ut.exec
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:report (post-unit-test) @ mast                                                                                            er ---
[INFO] Skipping JaCoCo execution due to missing execution data file:C:\Users\sha                                                                                            ba033\cbioportal\target\coverage-reports\jacoco-ut.exec
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ master ---
[INFO] Installing C:\Users\shaba033\cbioportal\pom.xml to C:\Users\shaba033\.m2\                                                                                            repository\org\mskcc\cbio\master\1.9.0\master-1.9.0.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building model 1.9.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ model ---
[INFO] Deleting C:\Users\shaba033\cbioportal\model\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\shaba033\cbioportal\model\sr                                                                                            c\main\resources
[INFO] skip non existing resourceDirectory C:\Users\shaba033\cbioportal\model\sr                                                                                            c\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5:compile (default-compile) @ model ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 51 source files to C:\Users\shaba033\cbioportal\model\target\cl                                                                                            asses
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Portal Master ...................................... SUCCESS [  2.270 s]
[INFO] model .............................................. FAILURE [  0.662 s]
[INFO] Portal Business Layer .............................. SKIPPED
[INFO] persistence ........................................ SKIPPED
[INFO] persistence-api .................................... SKIPPED
[INFO] db-scripts ......................................... SKIPPED
[INFO] persistence-mybatis ................................ SKIPPED
[INFO] security ........................................... SKIPPED
[INFO] security-spring .................................... SKIPPED
[INFO] service ............................................ SKIPPED
[INFO] Portal Core ........................................ SKIPPED
[INFO] Portal Web Layer ................................... SKIPPED
[INFO] cBioPortal ......................................... SKIPPED
[INFO] Portal Scripts ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.229 s
[INFO] Finished at: 2017-11-13T14:26:32-06:00
[INFO] Final Memory: 19M/211M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.                                                                                            5:compile (default-compile) on project model: Compilation failure -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit                                                                                            ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea                                                                                            d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc                                                                                            eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :model
```

Here's a copy of the POM i tried my best to configure:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>master</artifactId>
        <groupId>org.mskcc.cbio</groupId>
        <version>1.9.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
	<fork>True</fork>
	<execution>/c/Users/shaba033/Downloads/jdk-6u43-windows-x64.exe</execution>

    <artifactId>model</artifactId> 
</project>
```

The file they have on github doesnt run.... I tried to download a JDK 9 version of java but the installer won't even run on my laptop, only JDK 6 does. @fedde-s or anybody is there any chance you can help me out here?

Best.

**Comment by ashraf123456789** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>master</artifactId>
        <groupId>org.mskcc.cbio</groupId>
        <version>1.9.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
	<fork>True</fork>
	<execution>/c/Users/shaba033/Downloads/jdk-6u43-windows-x64.exe</execution>

    <artifactId>model</artifactId> 
</project>

**Comment by fedde-s** [comment]
> I tried to download a JDK 9
> version of java but the installer won't even run on my laptop, only JDK
> 6 does.

I would recommend trying to get a hold of JDK 8 or newer, as the current and future releases of cBioPortal are specifically targeted at those platforms and will not run with older versions. The documentation might still say that JDK 7 is supported, but that is incorrect and [a fix](https://github.com/cBioPortal/cbioportal/pull/3267) will be included in the next release.

If that does not suit your setup, you could consider trying to install [Docker](https://www.docker.com/get-docker#/install_the_platform), the Community Edition will do just fine. This will allow you to run the cBioPortal server in an isolated container that includes all its dependencies, without having to install those globally in your laptop's filesystem. I know of two solutions for running cBioPortal in Docker containers: one described [in the cBioPortal maintenance manual](https://cbioportal.readthedocs.io/en/latest/#docker) and an alternative maintained [at The Hyve](https://github.com/thehyve/cbioportal-docker).

Hope one of the solutions I suggested suits your needs; good luck!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ashraf123456789** [comment]
@fedde-s 

Can you explain what's wrong with this synatx? the naming and networking is giving me huge trouble
PS C:\Users\UserAdmin> docker run -d --restart=always \
>>   --name='cbioDB' \
>>   --net=cbio-net \
>>   -e MYSQL_ROOT_PASSWORD=P@ssword1 \
>>   -e MYSQL_USER=cbio \
>>   -e MYSQL_PASSWORD=P@ssword1 \
>>   -e MYSQL_DATABASE=cbioportal \
>>   -v /<path_to_save_mysql_db>/db_files/:/var/lib/mysql/ \
>>   -v /<path_to_seed_database>/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:ro \
>>   -v C:\Users\UserAdmin\Documents\SavePortalDBfiles.sql.gz:/docker-entrypoint-initdb.d/seed_part1.sql.gz:ro \
>>   -v C:\Users\UserAdmin\Documents\SavePortalDBfiles_only-pdb.sql.gz:/docker-entrypoint-in>itdb.d/seed_part2.sql.gz:ro
 \
>>   mysql
At line:2 char:5
+   --name='cbioDB' \
+     ~
Missing expression after unary operator '--'.
At line:2 char:5
+   --name='cbioDB' \
+     ~~~~~~~~~~~~~
Unexpected token 'name='cbioDB'' in expression or statement.
At line:3 char:5
+   --net=cbio-net \
+     ~
Missing expression after unary operator '--'.
At line:3 char:5
+   --net=cbio-net \
+     ~~~~~~~~~~~~
Unexpected token 'net=cbio-net' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

**Comment by fedde-s** [comment]
>Can you explain what's wrong with this synatx?

Unfortunately, it looks like the Windows command line you're running does not understand the documented commands, which are written in the Unix-based syntax used by many other operating systems. I'm afraid I can't personally help you much further here, as I'm largely unfamiliar with Windows and its command line.

Have you tried contacting the cBioPortal mailing list at <cbioportal@googlegroups.com>? Other members of the cBioPortal community will likely respond to your question if you post it there.

**Comment by ashraf123456789** [comment]
@fedde-s  Thanks for the help! So far I have there's a site running via the Docker server, but with no data sets. cbioDB is running as well....when I try to add a data set I keep getting this....:

shaba033$docker run -it --rm --net cbio-net \
>     -v "$PWD/study-dir:/study:ro" \
>     -v "$HOME/Desktop:/outdir" \
>     cbioportal-image \
>     metaImport.py -u http://cbioportal-container:8080/cbioportal -s /study --html=/outdir/report.html
Starting validation...


INFO: -: Running validation from cBioPortal version 1.9.0
CRITICAL: -: No meta files found in /study. Please make sure the directory is the path to the folder containing the files.
ERROR: -: Cancer type needs to be defined for a study. Verify that you have a study file and have defined the cancer type correctly.
ERROR: -: No valid study file detected

Directory:  /Users/shaba033/Downloads/paac_jhu_2014\ \(1\)/paac_jhu_2014

**Comment by fedde-s** [comment]
Ah, I think I see the problem there: in the second line of that command, `$PWD` refers to the present working directory. The command points the loader at a directory named `study-dir` within that directory. If the study files are right in the current folder, try replacing that line by this one:
```bash
    -v "$PWD:/study:ro" \
```

**Comment by ashraf123456789** [comment]
@fedde-s  I think we are almost there..... when input what you told me i got this. 

shaba033$docker restart cbioportal-container
cbioportal-container
shaba033$cd /Users/shaba033/Downloads/ampca_bcm_2016 
shaba033$docker run -it --rm --net cbio-net     -v "$PWD:/study:ro"     -v "$HOME/Desktop:/outdir"     cbioportal-image     metaImport.py -u http://cbioportal-container:8080/cbioportal -s /study --html=/outdir/report.html
Starting validation...

INFO: -: Running validation from cBioPortal version 1.9.0

INFO: meta_clinical_patient.txt: Validation of meta file complete

INFO: meta_clinical_sample.txt: Validation of meta file complete

INFO: meta_mutations_extended.txt: Validation of meta file complete

INFO: meta_study.txt: Validation of meta file complete

ERROR: -: Cancer type of study is neither known to the portal nor defined in a cancer_type file; value encountered: 'ampca'

INFO: data_clinical_sample.txt: Validation of file complete
INFO: data_clinical_sample.txt: Read 165 lines. Lines with warning: 0. Lines with error: 0

WARNING: data_clinical_patient.txt: Columns DFS_MONTHS and/or DFS_STATUS not found. Disease free analysis feature will not be available for this study.
INFO: data_clinical_patient.txt: Validation of file complete
INFO: data_clinical_patient.txt: Read 165 lines. Lines with warning: 0. Lines with error: 0

WARNING: data_mutations_extended.txt: line 2: Including the SWISSPROT column is recommended to make sure that the UniProt canonical isoform is used when drawing Pfam domains in the mutations view
WARNING: data_mutations_extended.txt: lines [3, 5, 6, (21597 more)]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; values encountered: ['1', '2', '144568', '(10023 more)']
WARNING: data_mutations_extended.txt: lines [3, 5, 6, (21172 more)]: No Amino_Acid_Change or HGVSp_Short value. This mutation record will get a generic "MUTATED" flag
INFO: data_mutations_extended.txt: lines [4, 12, 15, (6902 more)]: Line will not be loaded due to the variant classification filter. Filtered types: [Silent, Intron, 3'UTR, 3'Flank, 5'UTR, 5'Flank, IGR, RNA]; values encountered: ['Silent', 'RNA']
WARNING: data_mutations_extended.txt: lines [214, 681, 1466, (240 more)]: Gene symbol not known to the cBioPortal instance. This record will not be loaded.; values encountered: ['ABHD16B', 'ADGB', 'AP5B1', '(174 more)']
INFO: data_mutations_extended.txt: Validation of file complete
INFO: data_mutations_extended.txt: Read 28750 lines. Lines with warning: 21844. Lines with error: 0

INFO: -: No directory named 'case_lists' found, so assuming no custom case lists.
INFO: -: Validation complete


#######################################################################
One or more errors reported above. Please fix your files accordingly
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!



Unfortunatley nothing still uploaded....should I try updating the seed databases?

**Comment by ashraf123456789** [comment]
resulting in this... .@ 

cbiortal local host: 

 
--
Oops! An error occurred while trying to connect to the database. This could happen if the database does not contain any cancer studies.You may have caught us in the middle of updating data. Please check back later.

**Comment by fedde-s** [comment]
Yes, I believe that would solve it. This particular study, for which the data files were released rather recently, refers to a cancer type that was added in the [new seed db](https://github.com/cBioPortal/datahub/blob/b9662010756188a18051c983b8c445dd033703a9/seedDB/README.md#latest-seed-database) released this week.

**Comment by fedde-s** [comment]
And a reminder: do not forget to restart `cbioportal-container` again after importing studies.

**Comment by ashraf123456789** [comment]
@fedde-s still getting this unfortunatley:

Oops! An error occurred while trying to connect to the database. This could happen if the database does not contain any cancer studies.You may have caught us in the middle of updating data. Please check back later.

what other adjustments can i make? Sorry to bother you this much about it..
