### ISSUE TITLE
Should not make virtual study api call if the session id is null

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3364]
If you go to http://www.cbioportal.org/beta/, in the network tab, there is an API call to http://www.cbioportal.org/beta/api-legacy/proxy/session-service/virtual_cohort/null.

**Comment by zhx828** [comment]
@alisman @adamabeshouse could you help me debug this issue? I can't figure out what causes the issue.

**Comment by kalletlak** [comment]
@zhx828 I have fixed this locally, which would be for next release. I can fix this for you
