### ISSUE TITLE
pathology report sometimes not working on patient view due to github search api rate limit

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3367]
http://www.cbioportal.org/case.do#/patient?caseId=TCGA-BK-A0CC&studyId=ucec_tcga_pub&tab=pathologyReportTab

**Comment by jjgao** [comment]
Looks like it's working one. Anyone did anything? @inodb

**Comment by jjgao** [comment]
It's b/c of rate limit from the github. Can we cache them in the backend?

**Comment by inodb** [comment]
deployed
