### ISSUE TITLE
Oncoprint sorting won't sort if another sorting option is selected

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3374]
Oncoprint sorting won't sort if another sorting option is selected.

Steps to reproduce:
1. query a stuy, e.g. http://www.cbioportal.org/beta/index.do?session_id=599e33e4498e5df2e2945bd4&show_samples=false&&clinicallist=%23%20mutations
2. select sort by case id
3. click on clinical track and sort "A-Z". This will show the sort icon, but the sorting won't happen. 

![image](https://user-images.githubusercontent.com/2900303/32885579-2ff6308c-cabe-11e7-8ac7-2185a6f11939.png)

Desired solution:
- whenever sort "A-Z" is clicked, the sort option is set back to "Sort by data"

**Comment by jjgao** [comment]
good point.

**Comment by adamabeshouse** [comment]
good idea

**Comment by jjgao** [comment]
@adamabeshouse will this be in part of the refactoring?

**Comment by adamabeshouse** [comment]
@jjgao it can be, it isn't currently

**Comment by jjgao** [comment]
@adamabeshouse it's not necessary since it's already there.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/781
