### ISSUE TITLE
mutations tab needs a "by patient" option

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3375]
The mutations tab currently shows all mutations in all samples. In OncoPrint, there is an option to merge all samples from a single patient into a single column. I think the mutations tab needs this feature also. In a study with multiple samples per patient, the frequency of mutations that appear in only a single patient can appear artificially high if that patient has multiple samples.

See screenshots below in which the lollipop plot looks like mutations are recurrent, but each mutation actually is only found in a single patient:

![image](https://user-images.githubusercontent.com/10508276/32896483-1a9bbc8c-cab1-11e7-8ba0-db8934b0facb.png)

![image](https://user-images.githubusercontent.com/10508276/32896430-fdddab14-cab0-11e7-8f6f-bfaf1a1eadea.png)
http://www.cbioportal.org/index.do?session_id=5a0da035498e5df2e298535e&show_samples=false&

**Comment by jjgao** [comment]
Agreed. @onursumer do we have patient IDs?

**Comment by onursumer** [comment]
@jjgao yes, we have `patientId` in our current `Mutation` model. I think it shouldn't be too difficult to merge mutations by `patientId`. 

Should this be the default behavior then: Merge mutations by patient id, and show multiple mutations in a single row (something similar to the patient view implementation)?

**Comment by jjgao** [comment]
@onursumer ideally we should be able to expand a row to see samples. 

 maybe the first step is to count number of patients in the lollipop?

**Comment by jjgao** [comment]
@onursumer Can we do the following?

- add an option to switch between patient and sample, similar to oncoprint.
- when on patients, show number of patients in lollipop, and patient IDs in the table (with same mutations merged)

**Comment by onursumer** [comment]
@jjgao yes we can do this. I don't know how much effort it would require though. We will either need to update some of our column formatters or implement a new mutation table with separate formatters, say `ResultsViewPatientMutationTable`.

**Comment by jjgao** [comment]
@onursumer I guess the difficult part is the merging part? We should be able to have both sample and patient columns easily, right?

Is it similar to patient view page merging mutations from multiple samples? In the patient view, we merge mutations based on mutation identity. Here, we need to merge mutations based on mutation identity and patient id.

**Comment by jjgao** [comment]
@onursumer Maybe we can reuse the logic of patient view in terms of showing/hiding columns?

**Comment by jjgao** [comment]
I think we need to spec the product part more. Moving to to-do list.
