### ISSUE TITLE
case list issue with thca_tcga_pub

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3376]
![image](https://user-images.githubusercontent.com/840895/32896974-6aa11528-cab2-11e7-9779-5b32b2d58684.png)

**Comment by jjgao** [comment]
According to @alisman, it may happen to other studies too.

**Comment by alisman** [comment]
This only seems to happen when a problem study is combined with another one.  For example if both the Papillary Thyroid Cancer Studies are selected at once.  Select either one along and we don't have an issue.   So, it seems like this is related to the virtual study/multi-study changes.

**Comment by alisman** [comment]
Based on what I see in network console when all studies are selected, there are only two studies/molecular profiles for which this happens:

brca_tcga_pub2015_gistic
thca_tcga_pub_gistic

**Comment by jjgao** [comment]
Thanks, @alisman. Could you please check the logic and find out what case lists the frontend is looking for? Maybe in the frontend code, if it cannot find the case list, it should fall back to _all.

**Comment by alisman** [comment]
JJ, the post to the server is below.  Is this what you mean?
![image](https://user-images.githubusercontent.com/186521/32912070-f9f2f984-cadb-11e7-9f5a-65e2a6ee04ec.png)

**Comment by jjgao** [comment]
@alisman Thanks. Strange the case set is 'all' -- there must be some backend code to handle that then.
