### ISSUE TITLE
case list _cnaseq is missing from many studies

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3378]
It's missing from studies e.g. blca_tcga, brca_tcga_pub2015, thca_tcga and more.

We used to auto-generate the case list _cnaseq ("Tumor Samples with sequencing and CNA data") when importing.

**Comment by jjgao** [comment]
It looks like brca_tcga_pub2015 is missing a lot of case lists.

Can we generate (if not exist) the data-related case lists based on case_lists sheet in portal_importer_configuration for all public studies and check them in?

**Comment by jjgao** [comment]
@yichaoS @n1zea144 we may want to have another script to update case lists only. Is that possible?

**Comment by jjgao** [comment]
Another way to address it is to generate them in the API or frontend from either `sample_profile` or `genetic_profile_samples` table.

Maybe it's time to link profile to case list as we discussed earlier. @n1zea144

**Comment by jjgao** [comment]
Did a sql query:

```sql
select `STABLE_ID`, NAME
from sample_list l
where l.`LIST_ID` not in (
 select ll.`LIST_ID`
 from sample_list_list ll
)
```

Here is the list of case list without any samples in the database.
```
brca_tcga_pub2015_sequenced	Sequenced Tumors
brca_tcga_pub2015_rppa	Tumor Samples with RPPA data
gbm_tcga_pub2013_cna	Tumor Samples with CNA data
gbm_tcga_pub2013_rppa	Tumor Samples with RPPA data
prad_tcga_pub_rna_seq_v2_mrna	Tumor Samples with mRNA data (RNA Seq V2)
thca_tcga_pub_sequenced	Sequenced Tumors
thca_tcga_pub_rppa	Tumor Samples with RPPA data
```

**Comment by jjgao** [comment]
I did some more query to find out studies with both mutations and cna data but not _cnaseq case list:

```sql
select cs.`CANCER_STUDY_IDENTIFIER`
from cancer_study cs
where cs.`CANCER_STUDY_ID` in (
 # has mutation profile
 select cs.`CANCER_STUDY_ID`
 from genetic_profile p, cancer_study cs
 where p.`GENETIC_ALTERATION_TYPE`="MUTATION_EXTENDED" and p.`CANCER_STUDY_ID`=cs.`CANCER_STUDY_ID`
) and cs.`CANCER_STUDY_ID` in (
 # and cna profile
 select cs.`CANCER_STUDY_ID`
 from genetic_profile p, cancer_study cs
 where p.`GENETIC_ALTERATION_TYPE`="COPY_NUMBER_ALTERATION" and p.`DATATYPE`='DISCRETE' and p.`CANCER_STUDY_ID`=cs.`CANCER_STUDY_ID`
) and cs.`CANCER_STUDY_ID` not in (
 # but no _cnaseq case list
 select cs.`CANCER_STUDY_ID`
 from sample_list l, cancer_study cs
 where l.`STABLE_ID` like "%_cnaseq" and l.`CANCER_STUDY_ID`=cs.`CANCER_STUDY_ID`
)
order by cs.`CANCER_STUDY_IDENTIFIER`;
```

Here are the studies:
```
acyc_mskcc_2013
blca_mskcc_solit_2012
blca_tcga
brca_tcga_pub2015
coadread_tcga
coadread_tcga_pub
esca_tcga
gbm_tcga_pub2013
hnsc_tcga
kich_tcga
kirp_tcga
lihc_tcga
luad_broad
lusc_tcga
meso_tcga
ov_tcga
ov_tcga_pub
paad_tcga
pcpg_tcga
prad_broad
prad_broad_2013
prad_mich
prad_mskcc
prad_tcga
sarc_mskcc
sarc_tcga
skcm_tcga
stad_tcga
stad_tcga_pub
tgct_tcga
thca_tcga
thca_tcga_pub
thym_tcga
ucec_tcga
ucs_tcga
uvm_tcga
```

**Comment by jjgao** [comment]
Is there any validation code to catch missing case lists? @pieterlukasse

**Comment by angelicaochoa** [comment]
I am going to make a checklist here for resolved cnaseq case lists:

- [ ] blca_tcga	Bladder Urothelial Carcinoma (TCGA, Provisional)
- [ ] brca_tcga_pub2015	Breast Invasive Carcinoma (TCGA, Cell 2015)
- [ ] coadread_tcga	Colorectal Adenocarcinoma (TCGA, Provisional)
- [ ] esca_tcga	Esophageal Carcinoma (TCGA, Provisional)
- [ ] gbm_tcga_pub2013	Glioblastoma (TCGA, Cell 2013)
- [ ] hnsc_tcga	Head and Neck Squamous Cell Carcinoma (TCGA, Provisional)
- [ ] kich_tcga	Kidney Chromophobe (TCGA, Provisional)
- [ ] kirp_tcga	Kidney Renal Papillary Cell Carcinoma (TCGA, Provisional)
- [ ] lihc_tcga	Liver Hepatocellular Carcinoma (TCGA, Provisional)
- [ ] lusc_tcga	Lung Squamous Cell Carcinoma (TCGA, Provisional)
- [ ] meso_tcga	Mesothelioma (TCGA, Provisional)
- [ ] ov_tcga	Ovarian Serous Cystadenocarcinoma (TCGA, Provisional)
- [ ] paad_tcga	Pancreatic Adenocarcinoma (TCGA, Provisional)
- [ ] pcpg_tcga	Pheochromocytoma and Paraganglioma (TCGA, Provisional)
- [ ] prad_tcga	Prostate Adenocarcinoma (TCGA, Provisional)
- [ ] sarc_tcga	Sarcoma (TCGA, Provisional)
- [ ] skcm_tcga	Skin Cutaneous Melanoma (TCGA, Provisional)
- [ ] stad_tcga	Stomach Adenocarcinoma (TCGA, Provisional)
- [ ] stad_tcga_pub	Stomach Adenocarcinoma (TCGA, Nature 2014)
- [ ] tgct_tcga	Testicular Germ Cell Cancer (TCGA, Provisional)
- [ ] thca_tcga	Thyroid Carcinoma (TCGA, Provisional)
- [ ] thca_tcga_pub	Papillary Thyroid Carcinoma (TCGA, Cell 2014)
- [ ] thym_tcga	Thymoma (TCGA, Provisional)
- [ ] ucec_tcga	Uterine Corpus Endometrial Carcinoma (TCGA, Provisional)
- [ ] ucs_tcga	Uterine Carcinosarcoma (TCGA, Provisional)
- [ ] uvm_tcga	Uveal Melanoma (TCGA, Provisional)

**Comment by angelicaochoa** [comment]
@jjgao there are some studies listed above that do not have overlapping sample ids in  `cases_sequenced` and `cases_cna`

* ov_tcga

**Comment by sandertan** [comment]
@jjgao I believe there's currently no validation for missing specific case lists, except for the `_all` case list:
`ERROR: -: No case list found for stable_id 'teststudy_all', consider adding 'add_global_case_list: true' to the study metadata file`

Could we also document the required case lists in [File Formats](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#case-lists) and align it with the default selections on the query page?:

https://github.com/cBioPortal/cbioportal-frontend/blob/b6577560fa2a07e8a6d4b5ea881327283dcccb70/src/shared/components/query/QueryStore.ts#L598

**Comment by jjgao** [comment]
@angelicaochoa re: no overlapping sample ids in `cases_sequenced` and `cases_cna` for `ov_tcga`, there must be something wrong in the case lists. [This query](http://www.cbioportal.org/index.do?session_id=5a1450ca498eb8b3d5606ae5) shows mutations and CNAs on the same samples.

**Comment by jjgao** [comment]
@sandertan: I am thinking of re-implementing case lists: https://docs.google.com/document/d/1aBbkTAFv5nCqBv66BOgwvlt5kymgt0lQ7l_pqaFrupc/edit?usp=sharing

**Comment by angelicaochoa** [comment]
@jjgao missing cnaseq case lists are resolved. The only study that did not actually have overlapping CNA and Mutations samples is `ov_tcga`.

**Comment by jjgao** [comment]
Thanks, @angelicaochoa!

But in this query (http://www.cbioportal.org/index.do?session_id=5a1eb215498eb8b3d560ef6a) (all ov_tcga samples seleted), there are a lot of samples with both mutations and CNAs. Could you double check if  `cases_sequenced` and `cases_cna` were generated correctly?

![image](https://user-images.githubusercontent.com/840895/33376801-187dcb1c-d4dd-11e7-8f04-923bb71ff164.png)

**Comment by jjgao** [comment]
@angelicaochoa I tried two queries, one for sequence tumors (http://www.cbioportal.org/index.do?session_id=5a1eb2af498eb8b3d560ef77), and the other for cna tumors (http://www.cbioportal.org/index.do?session_id=5a1eb2bd498eb8b3d560ef79), and looked at the Download tab. There are a lot of overlapped samples between the two queries.

**Comment by jjgao** [comment]
@angelicaochoa did you have a chance to look into the ovarian study? There are definitely many overlapping samples between the mutations and cna profiles.

**Comment by angelicaochoa** [comment]
@jjgao there might have been an issue where the case list sample IDs were not in standardized formats? that should be addressed now however with the latest datahub updates to the provisional TCGA studies

**Comment by angelicaochoa** [comment]
@yichaoS @ritikakundra were TCGA provisional updated in the public portal yet?

**Comment by angelicaochoa** [comment]
@jjgao There might have been an issue where the TCGA sample IDs were not in the standardized/truncated format but I think this should be resolved in the latest TCGA provisional updates to datahub. 

@yichaoS @ritikakundra can you confirm whether the missing cnaseq case list for `ov_tcga` is resolved?
