### ISSUE TITLE
edits to custom cohort study label

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3379]
When I first browse a custom study, the top of the page lists the full names of the studies:
![image](https://user-images.githubusercontent.com/10508276/32897499-cc4dff42-cab3-11e7-8451-e3cf7c1c6c0b.png)

Once I click the "share" button and load up the custom cohort, the labels on the top get much less descriptive:
![image](https://user-images.githubusercontent.com/10508276/32897520-e12bd15a-cab3-11e7-9dd1-5f97c44edb2f.png)

I think it would help to have the full study names. There also needs to be some punctuation to separate the two studies -- e.g. add a semicolon between "61 patients" and "Glioma (TCGA)"

Or why not keep the same format as on the combined study page - with the plus sign and the list of studies, including links back to the individual study summary pages, and just add the number of samples/patients included in the custom cohort?

**Comment by tmazor** [comment]
If I start by running a query in multiple studies, there is a complete lack of information about which studies I queried at the top:
![image](https://user-images.githubusercontent.com/10508276/32902875-8a7ff404-cac1-11e7-8b10-bb5ec71a435b.png)

Can this also be replaced by the plus sign & the full list of studies?

**Comment by jjgao** [comment]
Good point. The cancer study track should show up int he OncoPrint but it's still good idea to have the same information up there. 

@zhx828 given other issues, I would not worry about this for this release if it takes time. We can do this on later.

**Comment by zhx828** [comment]
@jjgao @tmazor for release 1.10. We are going to show `Selected Studies` instead of `Custom Cohort` for virtual study and show exactly the same studies information like when you just combined the study. # of samples info is no longer available in 1.10 but will be enabled in next release when we enable user authentication and would be able to let them save the virtual study under their account.

**Comment by inodb** [comment]
@zhx828 should we close this?

**Comment by zhx828** [comment]
@inodb we could.
