### ISSUE TITLE
standardize male/female capitalization

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3380]
This is probably already part of the effort to standardize clinical terminology, but I want to particularly highlight the capitalization of Male/Female across studies. If I query all TCGA non-provisional studies, I get these pie charts:
![image](https://user-images.githubusercontent.com/10508276/32903922-3ed55370-cac4-11e7-8b42-beebbcdd93c4.png)

When I convert to charts, it's all a matter of capitalization:
![image](https://user-images.githubusercontent.com/10508276/32903897-2b9ebe4a-cac4-11e7-8d7e-a3bd6058ff29.png)

**Comment by jjgao** [comment]
Yes, we'll work on them once we finish normalize oncotree_code/cancer_type.

**Comment by jjgao** [comment]
we will track the progress here: https://github.com/cBioPortal/datahub/issues/131
