### ISSUE TITLE
Cancer type plot for 2 studies looks lumped together

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3381]
![screen shot 2017-11-16 at 1 49 49 pm](https://user-images.githubusercontent.com/1334004/32909688-2b451028-cad5-11e7-95a9-47f88495d475.png)

Maybe some spacing when very few studies? 

A quick fix could be to show cancer type by default?

**Comment by jjgao** [comment]
@inodb could you add the url?

**Comment by inodb** [comment]
Ill add it once session service starts working again

**Comment by inodb** [comment]
@jjgao @alisman e.g. https://cbioportal.mskcc.org/beta/index.do?session_id=5a0f7d14498eb8b3d5605cbc
