### ISSUE TITLE
fetch gene panel data for studies with the data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3387]
currently we are fetching gene panel data for all studies but we only have gene panel data for a few (maybe only one) studies.

**Comment by zhx828** [comment]
@jjgao currently we don't have such gene panel endpoint yet, I would suggest doing that in next release.

**Comment by jjgao** [comment]
OK. Let's do a hotfix soon once @ersinciftci helps implement an endpoint for this.

**Comment by ersinciftci** [comment]
@jjgao So what kind of an endpoint is needed for this?

**Comment by jjgao** [comment]
@ersinciftci have you done a cross-study gene panel end point already?

**Comment by ersinciftci** [comment]
@jjgao yes, `/gene-panel-data/fetch`, so I think this is done?

**Comment by jjgao** [comment]
I would consider this done. @zhx828 ?

**Comment by zhx828** [comment]
@jjgao @ersinciftci thanks for the new endpoint. It works well with study view.
