### ISSUE TITLE
BETA: Calculate the mutated gene percentage based on unique sample, not unique sample id

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3388]
![screen shot 2017-11-16 at 5 33 52 pm](https://user-images.githubusercontent.com/5400599/32919556-551073f6-caf4-11e7-9627-75a8f909a30d.png)

It may be caused due to same sample id in different studies. (This is combined TCGA studies)

**Comment by kalletlak** [comment]
@zhx828 what's the url/TCGA studies to replicate this error?

**Comment by zhx828** [comment]
@kalletlak I created a virtual study for you http://www.cbioportal.org/beta/study?id=5a0e28b0e4b06e4a2e19bd70
