### ISSUE TITLE
Download tab on cross cancer query empty in firefox

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#339]
All the files on the cross cancer query are empty in Firefox:

For instance: 

http://www.cbioportal.org/index.do?cancer_study_list=sclc_clcgp&cancer_study_id=sclc_clcgp&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=sclc_clcgp_mutations&data_priority=0&case_set_id=sclc_clcgp_all&case_ids=&gene_set_choice=general%3A-pi3k-akt-mtor-signaling-%2817-genes%29&gene_list=PIK3CA+PIK3R1+PIK3R2+PTEN+PDPK1+AKT1+AKT2+FOXO1+FOXO3+MTOR+RICTOR+TSC1+TSC2+RHEB+AKT1S1+RPTOR+MLST8&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit

![screen shot 2015-10-15 at 5 40 08 pm](https://cloud.githubusercontent.com/assets/1334004/10528370/ce4aac22-7363-11e5-9e55-797975ea4c6b.png)

**Comment by jjgao** [comment]
This seems to be fixed.
