### ISSUE TITLE
BETA: co-expression tab disappeared? 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3390]
See for example: 

![image](https://user-images.githubusercontent.com/2900303/32944342-8f0ade66-cb8f-11e7-9138-b83aacf25d6a.png)

The tab "Co-expression" is not there anymore. The same query on cbioportal.org still shows the tab.

**Comment by jjgao** [comment]
@pieterlukasse could you add the query?

**Comment by inodb** [comment]
@jjgao e.g. http://www.cbioportal.org/beta/index.do?session_id=5a0f846a498e5df2e2986a54&show_samples=false& and http://www.cbioportal.org/index.do?session_id=5a0f846a498e5df2e2986a54&show_samples=false&

**Comment by jjgao** [comment]
@inodb could you help look into this one?
