### ISSUE TITLE
Disable Summary Button if more than 20 studies selected

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3393]
Due to the limitation of the new API/legacy API,  we are limiting the number of studies can be combined in study view.

**Comment by jjgao** [comment]
Maybe add a tooltip when disabled. "Only up to 20 studies can be viewed together."

**Comment by inodb** [comment]
This works now on query selector, but on the results page you can still go to the study view by clicking on `Selected Studies`

**Comment by jjgao** [comment]
@zhx828  or @alisman could you disable the link on the results page?
