### ISSUE TITLE
Mutation diagram position issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3396]
In the query below, if you click on the highest position, there are both T1463fs and G1461fs. Why are they mapped to the same position on the diagram?

http://www.cbioportal.org/index.do?session_id=59663cbc498e5df2e29265ca&show_samples=false&

![image](https://user-images.githubusercontent.com/840895/32970773-50d54cde-cbb8-11e7-8d02-17ea8f265da9.png)

**Comment by onursumer** [comment]
@jjgao We use the `proteinPosStart` value when we determine the position of the lollipops. Although protein change values indicate 2 different positions (1461 and 1463) for these mutations, actual `proteinPosStart` values are the same, and it is `1459`, for both mutations. It is surprising though that `proteinPosStart` is neither 1461 nor 1463.

**Comment by jjgao** [comment]
This is strange. We need to look into it more. Could you paste the genome nexus links for the two mutations here?

**Comment by onursumer** [comment]
`T1463Nfs*50`: http://genomenexus.org/annotation/17%3Ag.37687471_37687472insG
`G1461Afs*38`: http://genomenexus.org/annotation/17%3Ag.37687472Gdel

Looks like the canonical transcript for both mutations have the protein start position `1459`. I think the problem, if any, is related to the algorithm that generates the protein change values.

**Comment by jjgao** [comment]
Do you know if protein_start is calculated by vep or us? It should be 1461 based on cDNA.

**Comment by onursumer** [comment]
As far as I know we don't do any calculation for protein start, we are relying on VEP. 

Actually, we are not doing any calculation in genome nexus. We do all the calculations during import phase. I guess this one is currently used for production:  https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/annotator/src/main/java/org/cbioportal/annotator/internal/GenomeNexusImpl.java

**Comment by jjgao** [comment]
So it looks like a bug from VEP. Is there any way to report to them?

**Comment by onursumer** [comment]
Maybe from http://www.ensembl.org/info/about/contact/index.html or https://github.com/Ensembl/ensembl-vep.

**Comment by jjgao** [comment]
Could you submit an issue on their github? Thanks.

**Comment by jjgao** [comment]
VEP will potentially solve this issue next year.

**Comment by jjgao** [comment]
@onursumer they explained it well. Could you add an issue in GenomeNexus and follow up later? I am closing this one here now.
