### ISSUE TITLE
What should be the expected behavior of "Deselect All" button in the study selector?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3399]
Currently, it deselects all of the studies listed below. For example, if I filter the studies by the search box, only the filtered studies will be deselected. 

I find it confusing because I would expect "deselect all" would deselect all previously selected studies (since it is following "xx studies selected" in the header).

Oftentimes, I wanted to select studies in the filtered results and would like to deselect all the previously selected cases. In order to do that, I have to clear my search, then click "deselect all", and then put my search and make my selection.

**Comment by tmazor** [comment]
Agreed! I expect "deselect all" to actually deselect all selected studies, regardless of what studies are currently visible.

I often do exactly what @jjgao described - I select some studies, then search for a new set of studies and I want to deselect everything I previously selected and select the ones I just searched for -- but first I have to clear my search, then deselect all, and then redo my search to select the new set of studies.

**Comment by jjgao** [comment]
@alisman: If no objections from @ecerami or @schultzn or you, let's change the behavior to actually deselect all previously selected studies.

**Comment by jjgao** [comment]
combining this one with https://github.com/cBioPortal/cbioportal/issues/3656.

- [ ] when at least one studies are selected, show "Deselect all"
- [ ] clicking "Deselect all" will deselect all selected studies (including the ones not displayed)
- [ ] when at least one studies display below, show "Select all (xx studies displayed)"
- [ ] add an `x` to reset (similar to the case set selector) when search box is not empty
