### ISSUE TITLE
Wiki Page for Google OAuth2

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#34]
We need to add a wiki page on setting up portal with Google OAuth2.  Assigning to self.

**Comment by jjgao** [comment]
@ecerami has this been done?

**Comment by ecerami** [comment]
no, not done.  @jjgao is there any existing documentation on how this works?

**Comment by pieterlukasse** [comment]
ok, I labeled #540 as 'hyve' as well, since I think it is indirectly related.

**Comment by fedde-s** [comment]
I don't think anyone at The Hyve is currently working on this. It seems to be very straightforward to add Google as an Identity Provider in Keycloak if you know where to find a client token though.

**Comment by jjgao** [comment]
closing this as it's too old.
