### ISSUE TITLE
cancer type summary tab issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3401]
https://cbioportal.mskcc.org/beta/index.do?session_id=5a12f277498eb8b3d5605cce

![image](https://user-images.githubusercontent.com/840895/33025743-c65b1c7e-cddc-11e7-8290-373fdb307ac4.png)

It is working on the currently production site:

https://cbioportal.mskcc.org/index.do?session_id=596d398f498e5df2e292a24b

[update] not working on production either. Need to debug the api.

**Comment by alisman** [comment]
This seems to be a data issue with BRAF.  The reason the production link above works is that it does not includ BRAF.  Following services returns 500 on production:

curl 'https://cbioportal.mskcc.org/api/molecular-profiles/mixedpact_cna/molecular-data/fetch?projection=DETAILED' -H 'Origin: https://cbioportal.mskcc.org' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Referer: https://cbioportal.mskcc.org/index.do?session_id=595aa913498e5df2e291fb24&show_samples=false&' -H 'Cookie: fsr.r=%7B%22d%22%3A90%2C%22i%22%3A%22de358f7-93060357-ea5f-84b8-9460e%22%2C%22e%22%3A1505869820250%7D; ZNPCQ003-31353500=3cbb1e14; _ga=GA1.2.2118131130.1505166059; fsr.s=%7B%22v1%22%3A-1%2C%22v2%22%3A-2%2C%22rid%22%3A%22de35430-94414811-1372-2982-b0b68%22%2C%22ru%22%3A%22https%3A%2F%2Fwww.google.com%2F%22%2C%22r%22%3A%22www.google.com%22%2C%22st%22%3A%22%22%2C%22cp%22%3A%7B%22Find_A_Doctor%22%3A%22N%22%2C%22Find_A_Research%22%3A%22Y%22%2C%22GA_UID%22%3A%222118131130.1505166059%22%7D%2C%22to%22%3A4%2C%22c%22%3A%22https%3A%2F%2Fwww.mskcc.org%2Fresearch-areas%2Flabs%2Fmembers%2Fdebyani-chakravarty-01%22%2C%22pv%22%3A3%2C%22lc%22%3A%7B%22d0%22%3A%7B%22v%22%3A3%2C%22s%22%3Atrue%7D%7D%2C%22cd%22%3A0%2C%22sd%22%3A0%2C%22f%22%3A1510257970691%7D; IPCZQX037c541b96=02006700457d93ffe52fe822541fd2d7a1c5ebb3; _liberty_idp="8ncL4kW0fbCCv1xeVFX2owINvJY="; _saml_idp=aHR0cHM6Ly90ZXN0YWNjZXNzMi5tc2tjYy5vcmcvbmlkcC9zYW1sMi9tZXRhZGF0YQ%3D%3D; JSESSIONID=1DE8502096F3EAF05008FC81ED24D425.ajp13dashi-two5; IPCZQX0352c9c686=0100f500ac12f46af90da258f740c58554394377; __utmt=1; results-tab=null; __utma=90787784.2118131130.1505166059.1507571607.1511192325.11; __utmb=90787784.8.10.1511192325; __utmc=90787784; __utmz=90787784.1511192325.11.5.utmcsr=cbiologin.mskcc.org|utmccn=(referral)|utmcmd=referral|utmcct=/nidp/saml2/idpsend' -H 'Connection: keep-alive' --data-binary '{"entrezGeneIds":[673],"sampleListId":"mixedpact_cnaseq"}' --compressed

**Comment by jjgao** [comment]
Right. I can reproduce it with BRAF on production: https://cbioportal.mskcc.org/index.do?session_id=595aa913498e5df2e291fb24

**Comment by jjgao** [comment]
Here is the error:

![image](https://user-images.githubusercontent.com/840895/33027556-6977c034-cde1-11e7-9b7e-eb193df4207a.png)

**Comment by inodb** [comment]
https://sentry.io/memorial-sloan-kettering/cbioportal-backend/issues/407626664/

**Comment by inodb** [comment]
@jjgao @angelicaochoa so the problem is that, that profile has empty values for `BRAF`, see e.g.:

```
select * from genetic_alteration where genetic_profile_id=14729 and genetic_entity_id=2637;
> ,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, (only last few values shown)
```
Should it be allowed to have N/A values in values of genetic_alteration? I would assume not?

The problem is then when splitting on `,` in backend, java removes empty fields, creating the indexerror:
```
java> "0,51,2132,21,,,,,".split(",")
java.lang.String[] res1 = ["0", "51", "2132", "21"]
```

**Comment by inodb** [comment]
OK talked to @angelicaochoa , we can expect the values to be empty. So we should change the splitting of values to return the proper NA value, such that it can be handled on frontend

**Comment by inodb** [comment]
Actually the issue is only for trailing `,,,,,`, so we are already passing empty strings to the frontend

**Comment by inodb** [comment]
Fix in https://github.com/cBioPortal/cbioportal/pull/3410
