### ISSUE TITLE
gene order not maintained when querying from study view page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3402]

**Comment by zhx828** [comment]
@jjgao I tried to reproduce the issue but works on multiple studies. Could you give me more information?

**Comment by zhx828** [comment]
But I do notice that the gene box in the study view is not listing genes as the order of selection. The order of genes sometimes shifted after few selections.

**Comment by jjgao** [comment]
@zhx828 actually that's the reason. I didn't realize the order was changing when selecting more genes. Could you fix that?

**Comment by zhx828** [comment]
Seems fixed. I will reopen the case if it comes up again.
