### ISSUE TITLE
virtual studies summary page - prioritize charts with data from multiple studies

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3406]
On the study summary page for virtual studies, is there any logic to which charts are shown by default? I think it would make sense to prioritize charts that have data from multiple studies over those with data from only one study.

For example, if I query all TCGA published studies, I get charts at the end that only have data from a single study -- e.g. "Disease stage" or "Transcriptome subtype":
![image](https://user-images.githubusercontent.com/10508276/33034513-1393b3d4-cdf6-11e7-9834-fb5bbcddf784.png)

![image](https://user-images.githubusercontent.com/10508276/33034534-2307c49a-cdf6-11e7-8178-976643fec38a.png)

Why not prioritize charts that have data from multiple studies? I think those are more likely to be meaningful to a user -- the more studies that have data for a particular attribute, the more likely that information can be useful in exploring or stratifying the virtual cohort.

http://www.cbioportal.org/beta/study?id=laml_tcga_pub%2Cblca_tcga_pub%2Cbrca_tcga_pub2015%2Ccoadread_tcga_pub%2Cprad_cpcg_2017%2Cgbm_tcga_pub2013%2Chnsc_tcga_pub%2Ckich_tcga_pub%2Ckirc_tcga_pub%2Cluad_tcga_pub%2Clusc_tcga_pub%2Clgggbm_tcga_pub%2Cov_tcga_pub%2Cnsclc_tcga_broad_2016%2Cthca_tcga_pub%2Cprad_tcga_pub%2Cstad_tcga_pub%2Cstes_tcga_pub%2Cucec_tcga_pub#summary

**Comment by zhx828** [comment]
@tmazor I did put in logic to show the most overlapped attributes first. But it may not necessarily be the case with most available data. Let me actually double check your example.

**Comment by zhx828** [comment]
Thanks @tmazor It actually is a bug, made a fix in here: https://github.com/cBioPortal/iViz/pull/641
