### ISSUE TITLE
another case to flag for duplicate samples

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3407]
The TCGA LGG+GBM study (Cell, 2016) includes samples from the LGG study and from the GBM studies, but it currently isn't flagged as a duplicate:

![image](https://user-images.githubusercontent.com/10508276/33035432-0c165906-cdf9-11e7-8481-68b62fc75df7.png)

**Comment by tmazor** [comment]
I'm not positive about this one, but I would guess that the Pan-Lung study pulls from the Lung Adeno & Lung Squamous Cell studies and therefore these should also be flagged as duplicates:
![image](https://user-images.githubusercontent.com/10508276/33035590-b2d37a12-cdf9-11e7-96a4-77ccaf87bfb9.png)

**Comment by tmazor** [comment]
Again, not positive about the source of the Esophagus-Stomach Cancer cohort, but it probably stems from the Esophageal & Stomach Adenocarcinoma studies:
![image](https://user-images.githubusercontent.com/10508276/33035906-c4602ebe-cdfa-11e7-8674-5687f1e727e7.png)

**Comment by tmazor** [comment]
These 2 prostate studies have some overlap too:
![image](https://user-images.githubusercontent.com/10508276/33036306-f8db57ee-cdfb-11e7-856a-85cbc152f9c5.png)

**Comment by alisman** [comment]
@jjgao Seems like we can't derive these programatically.  Should this hold up release?

**Comment by jjgao** [comment]
There is a lot more overlapping samples, see https://github.com/cBioPortal/cbioportal/issues/3395. We need to find a better way to handle it.

**Comment by jjgao** [comment]
closing this and we will handle it in https://github.com/cBioPortal/cbioportal/issues/3395
