### ISSUE TITLE
tweaks for 1.10.0

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3408]
@alisman 
- [x] "You have selected multiple TCGA studies with overlapping samples, highlighted in red below. Please limit your selection to one TCGA study per cancer type."
- [x] "Too many studies selected for study summary (limit: 20)"
- [x] "Summary" => "View summary"
- [x] Tooltip on single icon => "View study summary"
- [x] Swap "OncoPrint" and "Cancer Type Summary" tab
- [x] Always show oncoprint first

@zhx828 
- [x] "Selected Study" => "Combined Study"
- [x] "Total 9 studies" => "This combined study contains samples from 9 studies"
- [x] move "-" icon to the same position of "+"

**Comment by zhx828** [comment]
@jjgao it was `Combined Study`, but we decided to keep the consistency with the query selector. Should we still change that?
