### ISSUE TITLE
Bitly URL error

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#3422]
http://www.cbioportal.org/api-legacy/proxy/bitly?version=3.0&longUrl=http%3A%2F%2Fwww.cbioportal.org%2Findex.do%3Fsession_id%3D5a139329498eb8b3d5605ef6&history=0&format=json&callback=jQuery20305540635432786616_1511232295728&_=1511232295729

<img width="1109" alt="screen shot 2017-11-20 at 10 07 09 pm" src="https://user-images.githubusercontent.com/12956870/33052940-3462d3a8-ce3f-11e7-85a3-8dd9d53e86ea.png">

**Comment by jjgao** [comment]
bitly is not working: 

![image](https://user-images.githubusercontent.com/840895/33082095-ee375e24-cea9-11e7-828b-e23989a1a240.png)

**Comment by zhx828** [comment]
The server log only has `org.springframework.security.web.FilterChainProxy - /api-legacy/proxy/bitly?version=3.0&longUrl=http%3A%2F%2Flocalhost%3A8080%2Fcbioportal%2Findex.do%3Fsession_id%3D5a14842311d2060f3e0b2411&history=0&format=json&callback=jQuery20308533550521797042_1511295633173&_=1511295633174 has an empty filter list` but seems there are lots of similar logs for other files as well.
