### ISSUE TITLE
Studyview CNA genes table freq mismatch

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#3423]
Example
http://www.cbioportal.org/study?id=5a139acf498eb8b3d5605f7c#summary

http://www.cbioportal.org/study?id=chol_tcga%2Cchol_jhu_2013#summary (Filters : With Mutation Data - YES)

**Comment by zhx828** [comment]
@kalletlak the virtual study above only has 75 samples when saving. But the second example has 76

**Comment by kalletlak** [comment]
try applying Filter : With Mutation Data - YES
