### ISSUE TITLE
EXP OQL not allowed

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3424]
a user just reported that the new site doesn’t allow for queries based on expression - even if only a single study is selected, it thinks that multiple studies are selected and won’t let you submit:

![image](https://user-images.githubusercontent.com/840895/33076500-e084fad4-ce9a-11e7-8216-67da7031cd45.png)

https://groups.google.com/forum/#!topic/cbioportal/kuOiXyKiZHA

**Comment by inodb** [comment]
@jjgao fixed & deployed
