### ISSUE TITLE
mutation mapper isn't working

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3426]
A user reported this issue.

When I try to use MutationMapper using the test data, I get this output:
![image](https://user-images.githubusercontent.com/10508276/33079496-bc39ee4c-cea3-11e7-9cc6-ebc45ac53f8e.png)

**Comment by onursumer** [comment]
This is related to the conflicting jQuery version introduced by `vc-session-vendor.js`.
