### ISSUE TITLE
Add Annotation and Functional Impact into the downloaded txt file

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3427]
Can we split them into multiple columns?

For example:

- Annotation:OncoKB: oncogenic, level_2
- Annotation:CIViC: predictive: 2, prognostic: 2
- Annotation:MyCancerGenome: present
- Annotation:CancerHotspot: yes
- Annotation:3DHotspot: yes

- Functional-Impact:MutationAssesser: impact: medium, score: 3.18
- Functional-Impact:SIFT: impact: deleterious, score: 0.00
- Functional-Impact:Polyphen-2: impact: probably_damaging, score: 1.00

Ideally, each column / resource should specify the way to format the data for download.

**Comment by onursumer** [comment]
- cBioPortal/cbioportal-frontend#771 adds the download functionality for the `Annotation` column. 
- `Functional Impact` is a bit tricky with the current cach & lazy load behavior.
