### ISSUE TITLE
downloads tab is missing links to download tables

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3429]
User reported bug: "Today, the tables which usually I could download as text files in the Download section disappeared, leaving me just with the infos that can be copied and pasted into excel."

I confirmed that those links are gone:
![image](https://user-images.githubusercontent.com/10508276/33084125-22daff46-ceaf-11e7-9de4-1a3b84b429ac.png)

**Comment by jjgao** [comment]
This is the section that is missing:

![image](https://user-images.githubusercontent.com/840895/33086356-4e808c14-ceb5-11e7-98f8-ac1d5c093d42.png)

We removed the section for multiple studies, but it should still be there for single studies.
