### ISSUE TITLE
Page not loading while querying all studies

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#3433]
Example http://www.cbioportal.org/index.do?session_id=5a146656498eb8b3d5606dad

this is making more than 2000 API requests, some of which never completes

**Comment by zhx828** [comment]
This is similar to Study View previous implementation. We need to switch to batch POST.

**Comment by jjgao** [comment]
Number of API requests is now down to 125 in beta: 

http://www.cbioportal.org/beta/index.do?session_id=5a146656498eb8b3d5606dad
