### ISSUE TITLE
Co-Expression tab not loading

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#3439]
Example : http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit&show_samples=false&

<img width="667" alt="screen shot 2017-11-21 at 6 03 53 pm" src="https://user-images.githubusercontent.com/12956870/33101498-7a82e894-cee6-11e7-8f00-0785f944721c.png">

**Comment by jjgao** [comment]
@inodb can you help look into this one?

**Comment by inodb** [comment]
@jjgao ok

**Comment by onursumer** [comment]
Seems like a conflicting jQuery issue. #3435 might have already fixed this...

**Comment by inodb** [comment]
@jjgao @onursumer @kalletlak yes seems to be fixed already. Will deploy soon
