### ISSUE TITLE
Enrichments plot not working

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#3440]
http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit&show_samples=false&

<img width="511" alt="screen shot 2017-11-21 at 6 27 00 pm" src="https://user-images.githubusercontent.com/12956870/33102193-9b2fed5a-cee9-11e7-98b3-a7df1c4105e1.png">

**Comment by onursumer** [comment]
Seems very similar to #3439, and probably fixed by #3435
