### ISSUE TITLE
oncoprint progress bar

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3444]
Can we add a progress bar for oncoprint, especially when loading data from multiple studies, similar to study view.

http://www.cbioportal.org/study?id=5a12fd57498eb8b3d5605cd4

![image](https://user-images.githubusercontent.com/840895/33095088-69f0c390-ced0-11e7-881d-a5934ac29726.png)

**Comment by alisman** [comment]
@jjgao I added a new loading animation to the oncoprint.  It's not a progress bar but better than what we had.  Do you think progress bar would still be an improvement?  If so, not hard to accomplish (fake of course)

**Comment by jjgao** [comment]
@alisman it's probably not necessary. I'm closing this.
