### ISSUE TITLE
Expression tab will not load when _sequenced case list is missing

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3456]
The expression tab (which appears when querying 2 or more studies at the same time in 1.10.1) will hang, apparently due to a 403 error on an `api-legacy` call to retrieve `_sequenced` case lists (this only happens in a portal protected by an authentication). See screenshot below:

![image](https://user-images.githubusercontent.com/2900303/33172181-60f34346-d04f-11e7-87af-a8ec8c85a2c8.png)

A similar problem was also found in #3127 , and perhaps a similar solution can be found (I would vote to remove the call to `api-legacy` anyway). 

Another problem is of course the absence of `_sequenced` in these studies (here `acc_tcga` and `chol_tcga`. But this is a data problem and will be logged separately by @dionnezaal in datahub.

**Comment by jjgao** [comment]
We will probably make sure this will be fixed witht he refactoring effort.

**Comment by pieterlukasse** [comment]
@jjgao could you elaborate a bit on how this would be fixed? Will the new tab not require _sequenced? Where will this flexibility be implemented? In the backend (so no 403 is returned if one of the given case lists is missing)?

**Comment by jjgao** [comment]
I think if _sequence is not available, we should still be able to load the expression data, and `show mutation` button should be hidden.

@alisman could you take care of this in the refactored code?

**Comment by pieterlukasse** [comment]
@SRodenburg can you please retest this issue in a portal with authentication?

**Comment by pieterlukasse** [comment]
@jjgao was there a plan to stop using case lists?

**Comment by jjgao** [comment]
We have fully capture the data in `sample_profile`, but refactoring case lists is still on the back burner.
