### ISSUE TITLE
cBioPortal documentation outdated / "API" broken

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3457]
There is an existing documentation page describing how to integrate with cBioPortal frontend (i.e. let cBioPortal automatically navigate to the study view or to a specific oncoprint result given a set of parameters):
https://github.com/cBioPortal/cbioportal/blob/master/docs/providing-cBioPortal-parameters.md

This functionality is now broken, most probably by the virtual studies feature.  For example, all sample ids now need to be prefixed by their respective study id, like: study_id:sample_id. 

For example, this URL will not work anymore:
http://www.cbioportal.org/index.do?cancer_study_id=acc_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&data_priority=0&case_set_id=-1&case_ids=TCGA-OR-A5LT-01&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=ZFPM1&tab_index=tab_visualize&Action=Submit

This one works:
http://www.cbioportal.org/index.do?cancer_study_id=acc_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&data_priority=0&case_set_id=-1&case_ids=acc_tcga:TCGA-OR-A5LT-01&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=ZFPM1&tab_index=tab_visualize&Action=Submit

**Comment by pieterlukasse** [comment]
@jjgao I think we need a stable set of endpoints for such type of integration.

**Comment by jjgao** [comment]
@pieterlukasse I didn't know we have this doc :).. Yes, we need to update it.

**Comment by jjgao** [comment]
I also think we should have test cases to capture what's defined in this doc.

**Comment by pieterlukasse** [comment]
Thanks @jjgao . Will the frontend team work on this one? I agree we need some automated tests so that CI(travis) fails if anything changes and is not made backwards compatible.

**Comment by jjgao** [comment]
We should still support the old URLs. Could someone in the refactoring team look into this one? @alisman

**Comment by tgreenwood** [comment]
Does anybody know if a workaround exists for multiple cases (samples)? I've tried to add study id to every samples and at the beginning only and it does not work. Any ideas?

**Comment by jjgao** [comment]
@tgreenwood could you please add your url here?

**Comment by tgreenwood** [comment]
I have found solution. We use POST request. To make the request work with custom set of case_ids the samples should be separated by the carriage return and also every sample should have studyId-prefix.

**Comment by pieterlukasse** [comment]
hi @jjgao, any updates on this one? Were the documentation and/or the tests updated?
