### ISSUE TITLE
CCLE study errors / heatmap not working?

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3458]
When querying CCLE study I noticed some problems:

1- the gene panel information seems wrong as there are genes with mutations and "not sequenced"  at the same time !? See screenshot below:
![image](https://user-images.githubusercontent.com/2900303/33208495-129ad8c6-d112-11e7-9263-d4ec091245e0.png)

2- The heatmap option does not seem to be working, although there is expression data (data does show up in the Plots tab for example). See screenshot above

**Comment by jjgao** [comment]
@yichaoS could you look into this and see if the gene panel data are correct?

http://www.cbioportal.org/index.do?session_id=5a0457ae498e5df2e297f575

**Comment by ritikakundra** [comment]
@pieterlukasse @jjgao This has been fixed
http://www.cbioportal.org/index.do?session_id=5a26ea4c498eb8b3d56162ae&show_samples=false&

**Comment by jjgao** [comment]
Thanks, @ritikakundra !
