### ISSUE TITLE
Incorrect labeling/coloring of intronic mutation

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3460]
In the mutation view the Intron is labeled/colored as "Other" but in the OncoPrint it is a (incorrectly) labeled/colored as "Truncating Mutation"

**Mutation View**
![screen shot 2017-11-24 at 13 37 28](https://user-images.githubusercontent.com/9624990/33211318-4b2748c6-d11e-11e7-8a60-7d25d7451b9a.png)

**OncoPrint**
![screen shot 2017-11-24 at 13 37 10](https://user-images.githubusercontent.com/9624990/33211193-b44f635c-d11d-11e7-8575-e1bd37492638.png)

This could also be bugged for other Variant Classifications that belong to the 'Other' category, such as 5'Flank, 3'Flank but I have not tested this.

**Comment by adamabeshouse** [comment]
@jjgao there is no "other" type in the oncoprint, there is only missense, inframe, truncating, fusion, promoter

**Comment by jjgao** [comment]
@sandertan Is this one of your instances?

We do not officially support non-coding mutations. If you want to support that, you may need to change code in many different places: oncoprint, mutations tab, patient view, importer, etc.

**Comment by sandertan** [comment]
@jjgao Yes it’s a custom instance. Many functionality is actually working already (importer, mutation view), but perhaps I should take a better look to see if there are more irregularities. Thanks for the reply, I’ll see if this is a priority for us.
