### ISSUE TITLE
Download tab issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3462]
- [ ] In `Type of Genetic alterations across all cases` section of `Download tab` , a tab is separating `STUDY_ID` and `Case ID`. Let's change it to colon (:). 
- [x] Rename column header `Case ID` to "SAMPLE_ID"
- [x] Change `case` on the tab to `sample` since we always use samples.

https://cbioportal.mskcc.org/index.do?session_id=587f8a7d11d2c4ebd89da9a1

```
STUDY_ID	Case ID	KRAS: MUT FUSION AMP HOMDEL;	NRAS: MUT FUSION AMP HOMDEL;	BRAF: MUT FUSION AMP HOMDEL;
coadread_tcga_pub:TCGA-A6-2670-01			
coadread_tcga_pub:TCGA-A6-2674-01			
```

**Comment by jjgao** [comment]
after #2999, we may not need to fix this one.

**Comment by onursumer** [comment]
@jjgao So far I have added these two tables:

![download_tab_tables](https://user-images.githubusercontent.com/3604198/34690386-f20be030-f486-11e7-9d82-af87ce6b6f56.png)

There are two separate columns for study id and case id, should we combine them? And, also I think we should rename `case id` to `sample id` and `num cases altered` to `num samples altered`, right?

**Comment by jjgao** [comment]
let's have three columns: study_id, patient_id, sample_id
