### ISSUE TITLE
Portal version in Info API

### ISSUE THREAD

**Issue by ersinciftci** [cBioPortal/cbioportal#3464]
http://www.cbioportal.org/api/info returns `{"portalVersion":"${portal.version}","dbVersion":"2.4.0"}`, find out the reason.

**Comment by ersinciftci** [comment]
We need to create a new `maven.properties` to set properties coming from maven.

**Comment by fedde-s** [comment]
We might be able to supply a portal.properties file at runtime once this is released! That would be great, if anything it could greatly simplify the Docker configuration.

**Comment by ersinciftci** [comment]
@fedde-s it's released. So yeah portal.properties doesn't depend on any maven properties anymore, so can be provided at runtime.

**Comment by fedde-s** [comment]
I believe it hasn't been released just yet, unless I've missed a release after v1.11.3; see bug report #3953.

**Comment by ersinciftci** [comment]
@fedde-s Oh you mean that, yeah I fixed it a few weeks ago, not released yet.

**Comment by ersinciftci** [comment]
This was the related issue https://github.com/cBioPortal/cbioportal/issues/3855
