### ISSUE TITLE
multi-study query not loading

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3466]
User reported issue:
I queried on all studies, excluding duplicate studies, entered my gene name, and submitted the query. Such queries were able to display the list of all mutations in the genes previously by selecting the Mutations tab in the previous version of cBioPortal. Now, it is will not load.

Example query:
http://www.cbioportal.org/index.do?session_id=5a15c933498eb8b3d5608591

Screenshot of console:
![image001](https://user-images.githubusercontent.com/10508276/33289901-08594daa-d38f-11e7-9ae8-01b3894a8d55.png)

**Comment by rjattani** [comment]
I have also found that a comprehensive search for all variants in all cancer types looks complete and can yield no mutations (http://www.cbioportal.org/index.do?session_id=5a202fda498eb8b3d5610905):
![image](https://user-images.githubusercontent.com/34137480/33444297-1d696bf6-d5b7-11e7-8a01-9a026dbaecf5.png)

However, if I pick a select few studies for the same gene, it does yield some variants (http://www.cbioportal.org/index.do?session_id=5a202edc498eb8b3d56108e6&show_samples=false&clinicallist=CANCER_STUDY&):
![image](https://user-images.githubusercontent.com/34137480/33444702-3ead15be-d5b8-11e7-9841-ccafd7a11f33.png)

**Comment by jjgao** [comment]
Both seem fixed.
