### ISSUE TITLE
Seed Database not showing up on my local site

### ISSUE THREAD

**Issue by ashraf123456789** [cBioPortal/cbioportal#3470]
Hi...
I have my site up, but with no public data on it. I made a sql database with seed database and schema downloaded, my portal properties file have the right database information, my maven settings file did as well....some help would be nice here.
<img width="905" alt="screen shot 2017-11-28 at 2 55 43 pm" src="https://user-images.githubusercontent.com/33638846/33343856-726e9ec6-d44c-11e7-975b-0d57a3f77935.png">

**Comment by jjgao** [comment]
The seed database does not contain any studies. That's why there are no studies in the interface.

**Comment by ashraf123456789** [comment]
@jjgao is there any steps you used to upload the public studies?

**Comment by jjgao** [comment]
we'll continue the conversation on the user group. https://groups.google.com/forum/#!topic/cbioportal/iCVhj-iWfRI
