### ISSUE TITLE
germline case list error

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3471]
We need to have a better to do this. 
- If a study has no germline case list, we shouldn't try to pull the data.
- If there are no germline mutations, maybe we don't have to add the germline mutations frequency? (we don't really have a germline gene panel data, so it won't be correct anyway, right?) 

![image](https://user-images.githubusercontent.com/840895/33344450-0a7c4f06-d457-11e7-9268-86770016683f.png)

**Comment by onursumer** [comment]
As far as I know, currently only private msk impact studies have this `_germline` sample list.

In order to determine whether a study has a germline sample list id, we can use this endpoint: http://www.cbioportal.org/api/studies/msk_impact_2017/sample-lists

**Comment by onursumer** [comment]
Actually, we are using the `/sample-lists/{sampleListId}/sample-ids` endpoint to check if a certain `germline` sample list exists, but seems like 404 errors show up in the console even if we catch the error in the frontend code: https://stackoverflow.com/questions/7035466/check-if-file-exists-but-prevent-404-error-in-console-from-showing-up

Seems like the only way to get rid of those `404 Not Found` logs is to switch to another endpoint (the one that I pointed above).
