### ISSUE TITLE
Mutations tab has no mutations in the query below

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3474]
http://www.cbioportal.org/index.do?session_id=5a1e2294498eb8b3d560e62c

**Comment by ersinciftci** [comment]
@jjgao `/molecular-profiles/{molecularProfileId}/mutations/fetch` calls return 400 because either sampleIds or sampleListId should be set. But since we have `/mutations/fetch` that supports multiple studies, we should use that one anyway.

**Comment by jjgao** [comment]
not sure how I got this session. I am closing it.
