### ISSUE TITLE
cBioPortal contains different cancer omics data

### ISSUE THREAD

**Issue by mckf111** [cBioPortal/cbioportal#3475]
I am new here, and I really like the UI of it!

After I checked the datasets, I found there are several big data for one cancer type, coming from different papers. However, I am confused that there are a few sets all labeled **TCGA**, including provisional, so which one is actually the data same with TCGA database (or GDC now)?

eg.

* Breast Invasive Carcinoma (TCGA, Cell 2015)
* Breast Invasive Carcinoma (TCGA, Nature 2012)
* Breast Invasive Carcinoma (TCGA, Provisional)

**Comment by jjgao** [comment]
@mckf111 would you please send your question to cbioportal@googlegroups.com? Thanks.
