### ISSUE TITLE
In Fraction of Genome Altered API cutoff must be optional in swagger

### ISSUE THREAD

**Issue by ersinciftci** [cBioPortal/cbioportal#3481]

**Comment by jjgao** [comment]
@ersinciftci I don't know if anyone ever changes the threshold. Maybe we can re-implement it? I would really like to pre-compute FGA.

**Comment by ersinciftci** [comment]
@jjgao There are many things we can and should pre-compute. We can focus on them as part of database schema improvements we are planning with @n1zea144, as it requires schema and importer changes as well.

**Comment by jjgao** [comment]
@ersinciftci sounds good. Please make this one of the items.
