### ISSUE TITLE
Some Datahub links on the Data Sets page are broken

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3484]
The links from the Data Sets page for the following two studies (as reported by a user, maybe there are more?) do not work:
http://www.cbioportal.org/study?id=nepc_wcm_2016#summary
http://www.cbioportal.org/study?id=blca_tcga_pub#summary

The data can be downloaded via the Github web interface directly though..

See the Google Groups requests:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/L8b0awi3w_o/1FcYp2Y2BwAJ

**Comment by jjgao** [comment]
fixed.
