### ISSUE TITLE
Missing genes in pop-up gene panel

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3485]
There are a couple issues with the pop-up of genes contained in a gene panel and possibly with the data on datahub.

- First gene is missing in the pop-up
- Last gene is missing in the pop-up

I also noticed `ABRAXAS1` is missing in the gene panel data files, which I reported in https://github.com/cBioPortal/datahub/issues/127

#### **First gene missing (ABL1):**
<img width="1278" alt="screen shot 2017-12-01 at 10 13 14" src="https://user-images.githubusercontent.com/9624990/33475903-4d613798-d680-11e7-96c1-967cd619ad2e.png">

#### **Last gene missing (YES1):**
<img width="1275" alt="screen shot 2017-12-01 at 10 08 03" src="https://user-images.githubusercontent.com/9624990/33475776-e6db362c-d67f-11e7-9e2a-a7b5e4bcb651.png">

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3492
