### ISSUE TITLE
replace data manager with page store

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3489]
After we fully refactor the page, the frontend data manager will be replaced with the page store. Is it possible to quickly replace the data manager without the full refactoring, ie. connect the unrefactored tab to the store?

**Comment by jjgao** [comment]
I think it should be easy to switch to query parameters (cancer study, case list, sample ids, profile ids, and genes) from the store. But the old tabs are still using the old API (through the data manager?), we cannot remove the data manager before we refactor them.

**Comment by adamabeshouse** [comment]
my thought in the meeting the other day was that we can slightly refactor them to use the new data, and connect them to data in the new store

**Comment by jjgao** [comment]
Let's prioritize the one in the cross-study results page first, ie. Expression tab and Download tab.
