### ISSUE TITLE
Permission Issue on public-portal.log file

### ISSUE THREAD

**Issue by bobml** [cBioPortal/cbioportal#3493]
I know this is more of a Unix Issue than cbioportal but advice would be helpful. The cbioportal commands (validate, import, ...) and data resides in a user directory I created. Whenever I import data into cbioportal via the  ./metaimport.py command I always get the "java.io.FileNotFoundException: /usr/local/tomcat7/logs/public-portal.log (Permission denied)". Now, the import works fine, it just doesn't write to the the log file. Tomcat is owned by root in my case, but I changed the logs directory to be the same group (and writable) as my user that runs the cbioportal scripts. I believe when Tomcat creates a new logfile, its user and group are set to root. I am no a Unix permission expert I am afraid. What I am I doing wrong?

The setting for the directory is seen below where my group is called "cbioportal":
drwxrwxr-x 2 root cbioportal  8192 Dec  1 11:03 logs/

**Comment by jjgao** [comment]
@bobml would you please send your questions to cbioportal@googlegroups.com? Thanks.
