### ISSUE TITLE
cross-study API for pulling molecular data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3496]
When performing a cross-study query now, it can easily generate hundreds of ajax calls. Similarly, for the Mutations tab. That might be one of the reasons that the site is not as smooth as before. 

@ersinciftci can we extend the `molecular-data` end point (or develop a new one) to pull data from multiple molecular profiles?

**Comment by ersinciftci** [comment]
@jjgao will create a `POST /molecular-data/fetch` endpoint. It has been in my todo list for a long time, seems finally the time has come :)

**Comment by ersinciftci** [comment]
https://github.com/cBioPortal/cbioportal/pull/3524
