### ISSUE TITLE
[RC] slow query

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3502]
This query is significantly slower than the old code

new: http://www.cbioportal.org/beta/index.do?session_id=59b0eaca498e5df2e294f635

old: http://www.cbioportal.org/index.do?session_id=59b0eaca498e5df2e294f635

It looks like the new code downloaded 12M CNA data while the old code downloaded 12k CNA data.

**Comment by ersinciftci** [comment]
@jjgao it seems @adamabeshouse forgot to set `entrezGeneIds` in the request filter, so it's getting CNAs for all the genes. It returns 12M CNAs in 43 seconds, not bad :)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/776
