### ISSUE TITLE
[rc] Survival: slight difference of #cases  

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3503]
new: http://www.cbioportal.org/beta/index.do?session_id=59b0eaca498e5df2e294f635&show_samples=false

old: http://www.cbioportal.org/index.do?session_id=59b0eaca498e5df2e294f635&show_samples=false&

**Comment by ersinciftci** [comment]
@jjgao 
```
SELECT count(*) FROM public_test.clinical_patient where INTERNAL_ID IN (select sample.PATIENT_ID from
sample_list_list inner join sample on sample_list_list.SAMPLE_ID = sample.INTERNAL_ID where
sample_list_list.LIST_ID = 3321) and ATTR_ID = 'OS_MONTHS';
```
returns 577, which is the total of my overall survival #total cases. The same query with `OS_STATUS` returns 580, so it means there are 3 patients that has `OS_STATUS` but doesn't have `OS_MONTHS`. I ignore those patients in the calculation but it seems the old code is counting them, not sure what value it uses for nonexistent `OS_MONTHS` though. Does it ring a bell for you?

**Comment by jjgao** [comment]
@ersinciftci thanks. Do you have the sample IDs of the three samples?

**Comment by ersinciftci** [comment]
@jjgao Patient IDs are `TCGA-04-1357`, `TCGA-04-1360` and `TCGA-24-0968`.

**Comment by jjgao** [comment]
Thanks. I think your logic is correct.
