### ISSUE TITLE
Can't upload study files.....

### ISSUE THREAD

**Issue by ashraf123456789** [cBioPortal/cbioportal#3504]
Does anyone know how to deal with this?

Is the issue with the cancer_type.txt file? The metaImport.py? or Tomcat?

shaba033$./metaImport.py -s ../../../test/scripts/test_data/study_es_0/ -u http://localhost:8080/cbioportal -html myReport.html -v
Starting validation...

INFO: -: Running validation from cBioPortal version 1.10.1
DEBUG: -: Requesting cancertypes from portal at 'http://localhost:8080/cbioportal'
DEBUG: -: Requesting genes from portal at 'http://localhost:8080/cbioportal'
DEBUG: -: Requesting genesaliases from portal at 'http://localhost:8080/cbioportal'
DEBUG: -: Requesting genesets from portal at 'http://localhost:8080/cbioportal'

DEBUG: meta_CNA.txt: Starting validation of meta file
INFO: meta_CNA.txt: Validation of meta file complete

DEBUG: meta_patients.txt: Starting validation of meta file
INFO: meta_patients.txt: Validation of meta file complete

DEBUG: meta_log2CNA.txt: Starting validation of meta file
INFO: meta_log2CNA.txt: Validation of meta file complete

DEBUG: meta_samples.txt: Starting validation of meta file
INFO: meta_samples.txt: Validation of meta file complete

DEBUG: meta_methylation_hm27.txt: Starting validation of meta file
INFO: meta_methylation_hm27.txt: Validation of meta file complete

DEBUG: meta_gsva_pvalues.txt: Starting validation of meta file
INFO: meta_gsva_pvalues.txt: Validation of meta file complete

DEBUG: meta_gistic_genes_amp.txt: Starting validation of meta file
INFO: meta_gistic_genes_amp.txt: Validation of meta file complete

DEBUG: meta_gene_panel_matrix.txt: Starting validation of meta file
INFO: meta_gene_panel_matrix.txt: Validation of meta file complete

DEBUG: brca_tcga_meta_cna_hg19_seg.txt: Starting validation of meta file
INFO: brca_tcga_meta_cna_hg19_seg.txt: Validation of meta file complete

DEBUG: -: Retrieving chromosome lengths from 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/hg19.chrom.sizes'

DEBUG: meta_gsva_scores.txt: Starting validation of meta file
INFO: meta_gsva_scores.txt: Validation of meta file complete

DEBUG: meta_fusions.txt: Starting validation of meta file
INFO: meta_fusions.txt: Validation of meta file complete

DEBUG: meta_study.txt: Starting validation of meta file
INFO: meta_study.txt: Validation of meta file complete

DEBUG: meta_expression_median_Zscores.txt: Starting validation of meta file
INFO: meta_expression_median_Zscores.txt: Validation of meta file complete

DEBUG: meta_mutations_extended.txt: Starting validation of meta file
INFO: meta_mutations_extended.txt: Validation of meta file complete

DEBUG: meta_cancer_type.txt: Starting validation of meta file
INFO: meta_cancer_type.txt: Validation of meta file complete

DEBUG: meta_expression_median.txt: Starting validation of meta file
INFO: meta_expression_median.txt: Validation of meta file complete

DEBUG: cancer_type.txt: Starting validation of file
INFO: cancer_type.txt: Validation of file complete
INFO: cancer_type.txt: Read 1 lines. Lines with warning: 0. Lines with error: 0

DEBUG: data_samples.txt: Starting validation of file
INFO: data_samples.txt: Validation of file complete
INFO: data_samples.txt: Read 831 lines. Lines with warning: 0. Lines with error: 0

DEBUG: data_gene_panel_matrix.txt: Starting validation of file
INFO: data_gene_panel_matrix.txt: Validation of file complete
INFO: data_gene_panel_matrix.txt: Read 2 lines. Lines with warning: 0. Lines with error: 0

DEBUG: brca_tcga_data_cna_hg19.seg: Starting validation of file
INFO: brca_tcga_data_cna_hg19.seg: Validation of file complete
INFO: brca_tcga_data_cna_hg19.seg: Read 10 lines. Lines with warning: 0. Lines with error: 0

DEBUG: data_methylation_hm27.txt: Starting validation of file
WARNING: data_methylation_hm27.txt: lines [2, 3, 4, (5 more)]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; values encountered: ['487', '7871', '3232', '(5 more)']
INFO: data_methylation_hm27.txt: Validation of file complete
INFO: data_methylation_hm27.txt: Read 9 lines. Lines with warning: 8. Lines with error: 0

DEBUG: data_gistic_genes_amp.txt: Starting validation of file
WARNING: data_gistic_genes_amp.txt: lines [2, 3, 4, (11 more)]: Gene symbol not known to the cBioPortal instance. This record will not be loaded.; values encountered: ['DDAH1', 'NR2C2', 'CCDC174', '(36 more)']
INFO: data_gistic_genes_amp.txt: Validation of file complete
INFO: data_gistic_genes_amp.txt: Read 15 lines. Lines with warning: 14. Lines with error: 0

DEBUG: data_expression_median_Zscores.txt: Starting validation of file
WARNING: data_expression_median_Zscores.txt: lines [2, 3, 4, (2 more)]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; values encountered: ['6205', '9240', '4313', '(2 more)']
INFO: data_expression_median_Zscores.txt: Validation of file complete
INFO: data_expression_median_Zscores.txt: Read 6 lines. Lines with warning: 5. Lines with error: 0

DEBUG: data_expression_median.txt: Starting validation of file
WARNING: data_expression_median.txt: lines [2, 3, 4, (3 more)]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; values encountered: ['90993', '6205', '9240', '(3 more)']
INFO: data_expression_median.txt: Validation of file complete
INFO: data_expression_median.txt: Read 7 lines. Lines with warning: 6. Lines with error: 0

DEBUG: data_gsva_pvalues.txt: Starting validation of file
INFO: data_gsva_pvalues.txt: Validation of file complete
INFO: data_gsva_pvalues.txt: Read 10 lines. Lines with warning: 0. Lines with error: 0

DEBUG: brca_tcga_pub.maf: Starting validation of file
WARNING: brca_tcga_pub.maf: lines [3, 4, 5, (7 more)]: Gene symbol not known to the cBioPortal instance. This record will not be loaded.; values encountered: ['OR11H1', 'TMEM247', 'ABLIM1', '(7 more)']
INFO: brca_tcga_pub.maf: lines [4, 5, 6, (5 more)]: column 164: Values contained in the column cbp_driver_tiers that will appear in the "Mutation Color" menu of the Oncoprint; values encountered: ['Class 2', 'Class 1', 'Class 4', '(1 more)']
INFO: brca_tcga_pub.maf: lines [7, 9, 14]: Line will not be loaded due to the variant classification filter. Filtered types: [Silent, Intron, 3'UTR, 3'Flank, 5'UTR, 5'Flank, IGR, RNA]; value encountered: 'Silent'
INFO: brca_tcga_pub.maf: Validation of file complete
INFO: brca_tcga_pub.maf: Read 15 lines. Lines with warning: 10. Lines with error: 0

DEBUG: data_CNA.txt: Starting validation of file
WARNING: data_CNA.txt: lines [2, 3, 4, (4 more)]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; values encountered: ['116983', '375790', '55210', '(4 more)']
INFO: data_CNA.txt: Validation of file complete
INFO: data_CNA.txt: Read 8 lines. Lines with warning: 7. Lines with error: 0

DEBUG: data_gsva_scores.txt: Starting validation of file
INFO: data_gsva_scores.txt: Validation of file complete
INFO: data_gsva_scores.txt: Read 10 lines. Lines with warning: 0. Lines with error: 0

DEBUG: data_log2CNA.txt: Starting validation of file
WARNING: data_log2CNA.txt: lines [2, 3, 4, (4 more)]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; values encountered: ['116983', '375790', '55210', '(4 more)']
INFO: data_log2CNA.txt: Validation of file complete
INFO: data_log2CNA.txt: Read 8 lines. Lines with warning: 7. Lines with error: 0

DEBUG: data_patients.txt: Starting validation of file
INFO: data_patients.txt: Validation of file complete
INFO: data_patients.txt: Read 830 lines. Lines with warning: 0. Lines with error: 0

DEBUG: data_fusions.txt: Starting validation of file
WARNING: data_fusions.txt: lines [2, 3, 4]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; values encountered: ['2261', '2064']
INFO: data_fusions.txt: Validation of file complete
INFO: data_fusions.txt: Read 4 lines. Lines with warning: 3. Lines with error: 0

DEBUG: -: Validating case lists

DEBUG: case_lists/cases_custom.txt: Starting validation of meta file
INFO: case_lists/cases_custom.txt: Validation of meta file complete

INFO: -: Validation of case list folder complete
INFO: -: Validation complete

#######################################################################
Warnings. Please fix your files or import with override warning option
#######################################################################

I also ran this.......

shaba033$python2.7 ./cbioportalImporter.py -s ../../../test/scripts/test_data/study_es_0/
Data loading step using: /Users/shaba033/Downloads/cbioportal-master/scripts/target/scripts-1.10.1.jar

Checked DB schema version: (expected: 2.4.0) (found: 2.4.0)
Loading cancer types...
--> Loaded 0 new cancer types.
Done.

Warnings / Errors:
-------------------
0.  Cancer type with id 'brca-es0' already exists. Skipping.; 1x

Warnings / Errors:
-------------------
0.  Cancer type with id 'brca-es0' already exists. Skipping.; 1x
Done.
Total time:  5458 ms

Checking if Cancer study with identifier study_es_0 already exists before removing...
Recaching...
Finished recaching...
Cancer study with identifier study_es_0 found in database, removing...
Recaching...
Finished recaching...
deleted study:
ID: 8
Done.
Total time:  5226 ms

Recaching...
Finished recaching...
Recaching...
Finished recaching...
Loaded the following cancer study:
--> Study ID:  9
--> Name:  Test study es_0
--> Description:  Test study es_0
Done.
Total time:  5091 ms

Recaching...
Finished recaching...
Reading data from:  /Users/shaba033/Downloads/cbioportal-master/core/src/main/scripts/importer/../../../test/scripts/test_data/study_es_0/data_samples.txt
--> total number of lines:  827
--> records inserted into `clinical_sample` table: 506
Total number of sample specific clinical attributes added:  506
Total number of samples processed:  826
Total number of attribute values skipped because of empty value:  320
Done.
Total time:  6122 ms

Reading data from:  /Users/shaba033/Downloads/cbioportal-master/core/src/main/scripts/importer/../../../test/scripts/test_data/study_es_0/data_CNA.txt
Recaching...
Finished recaching...
--> profile id:  8
--> profile name:  Putative copy-number alterations from GISTIC
--> genetic alteration type:  COPY_NUMBER_ALTERATION
--> total number of samples: 778
--> total number of data lines:  7
--> records inserted into `sample_profile` table: 778
--> total number of data entries skipped (see table below):  7
org.mskcc.cbio.portal.dao.DaoException: Something has gone wrong!  I did not save any records to the database!
at org.mskcc.cbio.portal.scripts.ImportTabDelimData.importData(ImportTabDelimData.java:257)
at org.mskcc.cbio.portal.scripts.ImportProfileData.run(ImportProfileData.java:91)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.ImportProfileData.main(ImportProfileData.java:116)

Warnings / Errors:
-------------------
0.  CDC2	983 in config file [resources/gene_symbol_disambiguation.txt]is not valid. You should either update this file or update the `gene` and `gene_alias` tables to fix this.; 1x
1.  Entrez_Id 116983 not found. Record will be skipped for this gene.; 1x
2.  Entrez_Id 2073 not found. Record will be skipped for this gene.; 1x
3.  Entrez_Id 219293 not found. Record will be skipped for this gene.; 1x
4.  Entrez_Id 375790 not found. Record will be skipped for this gene.; 1x
5.  Entrez_Id 54998 not found. Record will be skipped for this gene.; 1x
6.  Entrez_Id 55210 not found. Record will be skipped for this gene.; 1x
7.  Entrez_Id 83858 not found. Record will be skipped for this gene.; 1x
8.  MLL2	8085 in config file [resources/gene_symbol_disambiguation.txt]is not valid. You should either update this file or update the `gene` and `gene_alias` tables to fix this.; 1x

ABORTED!
java.lang.RuntimeException: org.mskcc.cbio.portal.dao.DaoException: Something has gone wrong!  I did not save any records to the database!
at org.mskcc.cbio.portal.scripts.ImportProfileData.run(ImportProfileData.java:96)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.ImportProfileData.main(ImportProfileData.java:116)
Caused by: org.mskcc.cbio.portal.dao.DaoException: Something has gone wrong!  I did not save any records to the database!
at org.mskcc.cbio.portal.scripts.ImportTabDelimData.importData(ImportTabDelimData.java:257)
at org.mskcc.cbio.portal.scripts.ImportProfileData.run(ImportProfileData.java:91)
... 2 more
Traceback (most recent call last):
  File "./cbioportalImporter.py", line 433, in <module>
    main(parsed_args)
  File "./cbioportalImporter.py", line 422, in main
    process_directory(jvm_args, study_directory)
  File "./cbioportalImporter.py", line 296, in process_directory
    import_study_data(jvm_args, meta_filename, data_filename, study_meta_dictionary[meta_filename])
  File "./cbioportalImporter.py", line 131, in import_study_data
    run_java(*args)
  File "/Users/shaba033/Downloads/cbioportal-master/core/src/main/scripts/importer/cbioportal_common.py", line 798, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
RuntimeError: Aborting due to error while executing step.

Can anyone help with his...?

**Comment by sandertan** [comment]
Hi Ashraf,

I replied to your question in our Google Groups:
https://groups.google.com/forum/#!topic/cbioportal/zdnX4AR0UIg

Could you try that solution? If it still isn't working, let me know in the Google Groups thread :)
