### ISSUE TITLE
Missing AF and Cohort for patient view of lgg_ucsf_2014

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3514]
After update to the public amazon database some of the data changed:

http://rawgit.com/cBioPortal/cbioportal/2158ebe35c5fb73c5319972bea44e3760eac2862/test/end-to-end/image-compare/index.html?img1=https://raw.githubusercontent.com/cBioPortal/cbioportal/2158ebe35c5fb73c5319972bea44e3760eac2862/test/end-to-end/screenshots/chrome/patient_view_lgg_ucsf_2014_case_id_P04.png&img2=https://ptpb.pw/xOjE.png&label1=rc&label2=2158ebe3&screenshot_name=test/end-to-end/screenshots/chrome/patient_view_lgg_ucsf_2014_case_id_P04.png

We're missing AF and Cohort for some of the mutations, see also:

http://www.cbioportal.org/case.do#/patient?studyId=lgg_ucsf_2014&caseId=P04

But the data is in the database, check for instance oncoprint of TP53 on the same study (missing Cohort info on patient view):

http://www.cbioportal.org/index.do?session_id=5a1c3394498eb8b3d560c19f&show_samples=false&

**Comment by jjgao** [comment]
looks like the cohort data is back after reimporting?

**Comment by inodb** [comment]
@jjgao correct, AF is still missing for a few I think but that might be fine

**Comment by jjgao** [comment]
Closed for now. Not sure if there is a way to test for this in the backend. @n1zea144

**Comment by inodb** [comment]
@jjgao @n1zea144 One thing is that this wasn't just in this particular study but also in e.g. impact: http://www.cbioportal.org/case.do#/patient?studyId=msk_impact_2017&caseId=P-0000058. The problem is probably more pervasive. I think every mutation should also be in `mutation_count_by_keyword`. Maybe we should just have some sql query to confirm that? Maybe set up a daily cron job that verifies certain mysql queries return the expected result.

**Comment by jjgao** [comment]
@n1zea144 I remember you have some database validation code? Maybe we can add a rule there?
