### ISSUE TITLE
Create drop-down in Mutations Tab for selecting isoform

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3522]
- [x] Get annotation data from genome nexus
- [x] Allow picking transcript through drop down
- [x] ~Maybe add some note that annotations for OncoKB are always based on one transcript~ (disabled OncoKB track) 
- [x] ~Have to figure out what to do with MutationAssessor/Hotspots~ (Disabled Hotspots)
- [ ] What to do with MutationAssessor?

Note:
- we only import NS mutations for canonical isoforms. At some point we'll want to look at least including all NS mutations for all isoforms.

**Comment by jjgao** [comment]
multiple isoforms!!

**Comment by jjgao** [comment]
This is done!
