### ISSUE TITLE
Don't show error that patient doesn't exist when no mutation data

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3526]
When there is no mutation data, we shouldn't show a pop up that the patient doesn't exist if there's still other data available

https://cbioportal.mskcc.org/case.do#/patient?studyId=mixed_pdx_msk&caseId=P-0009874&navCaseIds=P-0009874

**Comment by jjgao** [comment]
@alisman is this done? Where is the pull request?
