### ISSUE TITLE
OncoKB improvement

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#353]
- [x] The feedback form: user can use this to send feedback directly from annotation column. We propose Google form.
- [x] Sort based on oncogenic icon
- [x] Add NCBI link in every gene
- [x] Use light grey as oncogenic icon color for variants not available in OncoKB
- [x] Add clinical summary

**Comment by jjgao** [comment]
@zhx828 what's the status of this ticket? What are the feedbacks from users? Better to write them down explicitly.

**Comment by zhx828** [comment]
@jjgao I updated the list above.
