### ISSUE TITLE
oncoprint - diagnosis age is N/A but data exists

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3531]
![image](https://user-images.githubusercontent.com/10508276/33689280-d5f2346a-daac-11e7-88bc-4c5f27b8c010.png)
http://www.cbioportal.org/beta/index.do?session_id=5a1eef06498eb8b3d560f502&show_samples=true&clinicallist=AGE

Same query on production has ages, so the data does exist:
![image](https://user-images.githubusercontent.com/10508276/33689299-e80a2ab8-daac-11e7-8b3d-9332c8a4d173.png)
http://www.cbioportal.org/index.do?session_id=5a1eef06498eb8b3d560f502&show_samples=false&clinicallist=AGE&

**Comment by tmazor** [comment]
The track populates if I switch to view by patient rather than by sample.

**Comment by adamabeshouse** [comment]
this looks like an issue of creating sample data from patient attribute data, the issue is present for other patient attributes I try. good catch

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/782/files
