### ISSUE TITLE
Weird rendering issue with oncoprint sort Z->a

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#3532]
http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit&show_samples=false&clinicallist=FRACTION_GENOME_ALTERED&

Steps: 
In the clinical track menu, click back and forth between sort a-Z and sort Z-a. You should see the text in the legend become thicker and thinner. It seems to be related to the style `transform: scaleX(-1);` which is applied to the 'ascending' icon to make it into 'descending' for sort Z-a mode. Strangely the thickness seems to go away after clicking elsewhere on the page.

It's not clear whether this is a problem or some browser quirk.

Tagging @fedde-s who I believe implemented that icon.

**Comment by fedde-s** [comment]
Right, I added the icon in pull request #3155.

**Comment by adamabeshouse** [comment]
@fedde-s are you seeing the issue as well

**Comment by fedde-s** [comment]
Not in Firefox or Safari, but I can reproduce it in Chrome, yes.

**Comment by fedde-s** [comment]
And in Chromium, but that's basically the same browser.

**Comment by adamabeshouse** [comment]
okay, then I guess its just a browser issue and since its pretty minor anyway, clicking out gets rid of it, I think we can close this.

**Comment by fedde-s** [comment]
It might be because I failed to include prefixes for browsers that consider the `transform` style experimental, although I'd expect those browsers to just ignore it altogether.
