### ISSUE TITLE
oncoprint pdf download color difference

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3533]
When I download OncoPrint as a PDF, the legend for numeric clinical tracks (e.g. OS (Months) & Total mutations) is black. On the site or if I download as PNG/SVG, the legend is green to match the actual data bars:

PDF
![image](https://user-images.githubusercontent.com/10508276/33722419-e2d19d16-db37-11e7-87fa-4cbba89c3258.png)

PNG
![image](https://user-images.githubusercontent.com/10508276/33722428-ebc7049c-db37-11e7-92fa-4f48c28b5fcf.png)

**Comment by adamabeshouse** [comment]
this probably has to do with someone making a mistake and changing the legend rendering to use an attribute for color thats not compatible with our svg-to-pdf engine. Good catch. I'll look into it

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/oncoprintjs/pull/38
https://github.com/cBioPortal/cbioportal-frontend/pull/783
