### ISSUE TITLE
oncoprint minimap icon

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3534]
The icon on the refactored page to open up minimap is not intuitive to me. When I see that icon, I expect that clicking it will expand the figure or go full screen.
![image](https://user-images.githubusercontent.com/10508276/33722848-16e6e858-db39-11e7-8b21-34d9e77cfad4.png)

Can we change the icon? What about something like the two options below?

![image](https://user-images.githubusercontent.com/10508276/33723345-7651b5c4-db3a-11e7-9e7f-7284af9b5b59.png)

![image](https://user-images.githubusercontent.com/10508276/33723576-10594f1a-db3b-11e7-9fae-2498074c3568.png)

**Comment by adamabeshouse** [comment]
I like the second one, it feels more map-like to me. Maybe even an actual compass icon would be appropriate?

**Comment by jjgao** [comment]
I like the second one too.

**Comment by schultzn** [comment]
Agreed! It looks like you already changed it? I like what is there now:
![image](https://user-images.githubusercontent.com/11892704/33836390-4d565a38-de57-11e7-8932-1611eb23ac04.png)

**Comment by adamabeshouse** [comment]
that is not on the refactored page :)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/800
