### ISSUE TITLE
Gene size on Mutations tab of study view is incorrect for many genes

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3536]
The gene size on the Mutations tab of the study view is incorrect for TP53, TERT, KRAS, probably maybe others.

Where is this data from? Does it include UTRs?

http://www.cbioportal.org/study?id=msk_impact_2017#mutations

![image](https://user-images.githubusercontent.com/11892704/33738167-76a00b62-db66-11e7-836e-9b3f811a5024.png)

**Comment by jjgao** [comment]
@inodb @onursumer maybe now we can get the protein length from GenomeNexus? The current gene length was a hack.

**Comment by zhx828** [comment]
@jjgao do we still need to use the protein length to normalize the genes? Any further instructions?

**Comment by jjgao** [comment]
@zhx828 I think that'd be useful. @inodb @onursumer do we have an api to get length of transcript or protein?

**Comment by onursumer** [comment]
@jjgao it is possible to query `ensembl/transcript` endpoint with transcript id or hugo symbol. But querying with hugo symbol may return more than one transcript with different lengths.

Examples: 
http://genomenexus.org/ensembl/transcript/ENST00000361390
http://genomenexus.org/ensembl/transcript?hugoSymbol=TP53

**Comment by jjgao** [comment]
@onursumer since we use a default transcript per gene on cbioportal, we should be able to pinpoint the transcript.

I am wondering if we should add the canonical transcript into the portal database? Or maybe a service from GN is fine.
