### ISSUE TITLE
R package cgdsr download clinical data error

### ISSUE THREAD

**Issue by nongbaoting** [cBioPortal/cbioportal#3538]
when i used R package cgdsr to download TCGA cancer clinical data，there was an error through to me！

`mycgds = CGDS("http://www.cbioportal.org/public-portal/")
myclinicaldata = getClinicalData(mycgds,'blca_tcga_all')
`
and the errror were：

`
Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  line 284 did not have 91 elements
`

only happened to blca_tcga_all dataset

**Comment by QifengOu** [comment]
could you tell me what's problem about it?
