### ISSUE TITLE
Remove duplicate and empty Genome Nexus query params

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#3540]
Seems like we are sending duplicate and empty queries to genome nexus cache while retrieving data for Functional Impact column. Remove duplicate and empty values before sending the POST request.

**Comment by inodb** [comment]
also check hotspots (same logic)

**Comment by onursumer** [comment]
seems like we are querying hotspots by unique genes: https://github.com/cBioPortal/cbioportal-frontend/blob/b3f30b94b5352fc901c0ed06e93f64d3e9f78b26/src/shared/lib/StoreUtils.ts#L635
