### ISSUE TITLE
virtual studies query fails on beta

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3543]
I get this when I query multiple studies:
![image](https://user-images.githubusercontent.com/10508276/33835989-29e81826-de56-11e7-84cb-aa28639fb578.png)
http://www.cbioportal.org/beta/index.do?session_id=5a2e9657498eb8b3d561c3f3

**Comment by jjgao** [comment]
maybe the same issue: https://github.com/cBioPortal/cbioportal/issues/3500
