### ISSUE TITLE
oncoprint - mutation type shown in legend but not present in data

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3547]
When I run this query on beta, the legend shows "Truncating Mutation (unknown significance)" which implies that there is at least one mutation of that type. 

However, I can't find any mutations like that by eye in the OncoPrint, and when I run the same query on production, it doesn't show up in the legend there.

Beta:
![image](https://user-images.githubusercontent.com/10508276/33836820-8698bef2-de58-11e7-9512-029aa51c1d06.png)
http://www.cbioportal.org/beta/index.do?session_id=5a2e973a498eb8b3d561c404&show_samples=true

Production:
![image](https://user-images.githubusercontent.com/10508276/33836833-8f233868-de58-11e7-9484-23adfd61a43a.png)
http://www.cbioportal.org/index.do?session_id=5a2e97f3498eb8b3d561c40e&show_samples=true&

Can mutation types that do not appear in the OncoPrint be removed from the legend?

**Comment by adamabeshouse** [comment]
if you zoom out there actually is a VUS truncating, in sample TCGA-DU-5874-01 in CIC

**Comment by tmazor** [comment]
Good catch - sorry, I didn't see that one. Follow-up question then - why is that mutation labeled differently in beta than in production? On production, that same mutation is labeled as a putative driver truncating mutation, which is why the legend there doesn't list putative passenger truncating.

![image](https://user-images.githubusercontent.com/10508276/33854681-8ffec2ce-de90-11e7-8233-e3c6c704c51e.png)

**Comment by adamabeshouse** [comment]
@tmazor this may be related to https://github.com/cBioPortal/cbioportal-frontend/pull/797

**Comment by tmazor** [comment]
I'm not sure if that is the reason because other splice site mutations in the same tumor type are being appropriately labeled as oncogenic.

However, I'm not familiar with that "=" in the protein change and I actually think that might be the issue. If I query all studies for CIC mutations, and then filter for splice mutations, there are 2 mutations that don't have an OncoKB logo in the annotation column -- this one, and another one from MSK-IMPACT with an equal sign for the protein change:
![image](https://user-images.githubusercontent.com/10508276/33855481-03f0ad62-de93-11e7-8729-290064c23887.png)
http://www.cbioportal.org/index.do?session_id=5a1fbdcf498eb8b3d5610176

Why are those two mutations annotated differently? And could that explain why OncoKB isn't annotating those as oncogenic?

I'm not sure who might be able to address this? @ritikakundra ?

**Comment by ritikakundra** [comment]
@tmazor @adamabeshouse OncoKb annotation could be due to the weird mutation. This issue was in lgg ucsf too, on re-annotating with genome nexus it got updated. Am doing the MSK-IMPACT one right now. For the provisional, I will have to ask @angelicaochoa

**Comment by ritikakundra** [comment]
@adamabeshouse @tmazor The MSK-IMPACT one is solved:
http://www.cbioportal.org/case.do#/patient?studyId=msk_impact_2017&sampleId=P-0001901-T01-IM3

Provisional will take time.

**Comment by tmazor** [comment]
thanks @ritikakundra!
