### ISSUE TITLE
Download oncoprint issue in  SVG or PNG.

### ISSUE THREAD

**Issue by armeniaj** [cBioPortal/cbioportal#3553]
The bars in the oncoprint from the clinical annotation tab are converted to a flat line when you download the oncoprint either as PNG or SVG. The only clinical attributes that are properly saved as bars are mutation counts or mutation spectrum.

Example:
https://cbioportal.mskcc.org/index.do?session_id=5a2ed498498eb8b3d561c8ef&show_samples=false&clinicallist=AR_SCORE,NEPC_SCORE,NEUROENDOCRINE_FEATURES&

**Comment by armeniaj** [comment]
@adamabeshouse the beta portal does not have the clinical attributes that do not work in the mskcc portal. Below is the link of the issue, can you reproduce it?

https://cbioportal.mskcc.org/index.do?session_id=5a2ed498498eb8b3d561c8ef&show_samples=false&clinicallist=AR_SCORE,NEPC_SCORE,NEUROENDOCRINE_FEATURES,ABI_ENZA_EXPOSURE_STATUS&

**Comment by adamabeshouse** [comment]
@armeniaj I don't have access to that study :(

**Comment by armeniaj** [comment]
@ritikakundra is giving you access.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/804
