### ISSUE TITLE
patient survival status discrepancies

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3555]
I queried all published TCGA studies. There are two clinical attributes relating to survival: "Patient's Vital Status" and "Overall Survival Status". 78 patients (spanning 3 studies) that are alive according to "Patient's Vital Status" are deceased according to "Overall Survival Status":

![image](https://user-images.githubusercontent.com/10508276/33854238-ea598eae-de8e-11e7-90d6-c98eed1a58e7.png)
http://www.cbioportal.org/study?id=5a2eef46498eb8b3d561cb45#summary

@ritikakundra can you check what's happening here? I would expect those two clinical attributes to be consistent with each other.

**Comment by jjgao** [comment]
This is a tricky one. I think it might be related to different time point. `Overall Survival Status` is from the latest follow up data but `Patient's Vital Status` may be from `patient.txt` which is not updated. I think it's probably a good idea to remove `Patient's Vital Status` for TCGA studies.

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #301](https://github.com/cBioPortal/datahub/issues/301) via [**ZenHub**](https://www.zenhub.com/)
