### ISSUE TITLE
NaN in Breast Cancer study (TCGA Cell 2015) causing 

### ISSUE THREAD

**Issue by PichaiRaman** [cBioPortal/cbioportal#3557]
Got this message

```
I am having trouble accessing the EZH2 RNA-seq data for the Breast Invasive Carcinoma dataset (TCGA, Cell, 2015). 
When I check to see which cases are unregulated for EZH2 (EXP>1, for example), it says 0% of the cases are altered, and it will not allow me to download the RNA-seq data, it just says N/A for every patient. 
These searches were previously working and I have the data dowloaded from this study (EZH2 RNA-seq data was available before) and there are many cases wit z-scores greater than 1. 
Do you know how to solve this problem or if others are having the same problem? 
```
I tried it and he is correct. I saw that one of the samples has an NaN value for EZH2 and I think that's causing all samples to have NaN upon Z-scoring.

**Comment by jjgao** [comment]
@ritikakundra could you verify and fix it in the data file? Thanks.

**Comment by ritikakundra** [comment]
@PichaiRaman: Can you tell me where this is coming up?
http://www.cbioportal.org/index.do?session_id=5a552d02498eb8b3d56369a3&show_samples=false&

**Comment by ritikakundra** [comment]
@PichaiRaman Just wanted to follow up on this. Can you send me the link where you are seeing this issue? Thanks!

**Comment by jjgao** [comment]
@ritikakundra here is the query:

http://www.cbioportal.org/index.do?session_id=5acbc04f498eb8b3d56593c7

**Comment by jjgao** [comment]
moved to datahub. Please fix @ritikakundra
