### ISSUE TITLE
oql: support "KRAS:MUT=G12"

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#356]
"KRAS:MUT=G12" should return all mutations on G12 position.

**Comment by adamabeshouse** [comment]
Is there a way we can recognize this type of specification systematically, i.e. with a regular expression?

In other words, is it position-specified if, for example, it matches /^[ACGT][0-9]+$/

How do I get the position of a mutation from the given data:
```
{
	"genetic_profile_id":"brca_tcga_pub_mutations",
	"entrez_gene_id":672,
	"hugo_gene_symbol":"BRCA1",
	"sample_id":"TCGA-BH-A0WA-01",
	"study_id":"brca_tcga_pub",
	"sequencing_center":"genome.wustl.edu",
	"mutation_status":"Somatic",
	"mutation_type":"Splice_Site",
	"validation_status":"Unknown",
	"amino_acid_change":"X1580_splice",
	"functional_impact_score":"NA",
	"xvar_link":"NA",
	"xvar_link_pdb":"NA",
	"xvar_link_msa":"NA",
	"chr":17,
	"start_position":41223256,
	"end_position":41223256,
	"reference_allele":"C",
	"variant_allele":"T",
	"reference_read_count_tumor":"-1",
	"variant_read_count_tumor":"-1",
	"reference_read_count_normal":"-1",
	"variant_read_count_normal":"-1"
}
```

**Comment by inodb** [comment]
By all mutations do you mean only amino acid changes at that specific position or also frameshifts and introduction of a stop codon before the position?

In the former case it's probably easiest to just check if "amino_acid_change" starts with "G12"

**Comment by adamabeshouse** [comment]
@inodb: but what about the one in the example, "X1580_splice"

**Comment by inodb** [comment]
I'm guessing we'll ignore splice site mutations at the moment. But maybe if you query for them specifically with 'BRCA1:MUT=X1580', I don't see why you wouldn't want to display m.

People that are using the oql, probably just want to check how often a certain mutation occurs in other cases.

**Comment by adamabeshouse** [comment]
@jjgao should I just use the rule that @inodb suggested?

**Comment by adamabeshouse** [comment]
todo: pass back protein start & end, check just the position number

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/387
