### ISSUE TITLE
not present genomic overview in patient view

### ISSUE THREAD

**Issue by coonya** [cBioPortal/cbioportal#3565]
![cbio](https://user-images.githubusercontent.com/5857083/33930662-042df5b0-e031-11e7-8e8c-90b233578119.png)

**Comment by jjgao** [comment]
@coonya could you add the link to this page?

**Comment by coonya** [comment]
This is our local server which has restricted connection from outside of hospital.

**Comment by jjgao** [comment]
@coonya it maybe hard for us to debug in this case. Do you see any error message in the console of your browser?

**Comment by coonya** [comment]
I got an error as follows in chrome with MSKCC's Anaplastic Oligodendroglioma and Anaplastic Oligoastrocytomas.
![pic1](https://user-images.githubusercontent.com/5857083/34085614-c74947f4-e3d6-11e7-8e18-4e2e108ad3a9.png)

**Comment by jjgao** [comment]
@coonya You may want to add a case list `[study_id]_sequenced`:

https://cbioportal.readthedocs.io/en/latest/File-Formats.html#case-lists

**Comment by coonya** [comment]
Thank you for your help.
It works well now.
