### ISSUE TITLE
multi-profile support for molecular-profiles

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3569]
Currently, for multi-study query, we are pulling profile data one profile at a time, e.g. http://www.cbioportal.org/beta/api/molecular-profiles/chol_tcga_gistic.

Can we support multiple profiles in `/api/molecular-profiles`? And also change the frontend to pull at once instead of study by study.

We also pull data one study at a time in frontend: e.g. http://www.cbioportal.org/beta/api/molecular-profiles/chol_tcga_gistic

Can we also support multiple studies in the same api `/api/molecular-profiles`?

**Comment by ersinciftci** [comment]
https://github.com/cBioPortal/cbioportal/pull/3580
