### ISSUE TITLE
Add warning for missing mutation and cna case lists

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3577]
Perhaps it's a good idea to give a warning when `_sequenced`, `_cna` or`_cnaseq` are missing while the data is present. These case lists are important for:
- The default case selection on the query page
- The prevalence calculation in the OncoPrint
- The %mutated tables in the Study View.

We can also make it an error because of the importance. A number of public studies might need to be fixed in that case.

Can also validate this for mrna, rppa, methylation etc.

**Comment by jjgao** [comment]
@sandertan is this done?

**Comment by sandertan** [comment]
@jjgao No we've not started on this yet. Is it a priority?

**Comment by jjgao** [comment]
Thanks, @sandertan. Just wanted to keep track.

**Comment by sandertan** [comment]
@jjgao what do you think should be the required case lists?
- _sequenced when mutation data is in study
- _cna when CNA data is in study

These two are required for correct calculation of % mutated in study summary, right?

Are there other case lists for which cBioPortal has specific functionality?

**Comment by jjgao** [comment]
@sandertan I think that would be good! Not sure if `or_cnaseq` is used anywhere - maybe not.
