### ISSUE TITLE
[rc] OncoPrint not rendering for the single-gene multi-study query

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3579]
http://www.cbioportal.org/beta/index.do?session_id=5a32923a498eb8b3d5620e3b

![image](https://user-images.githubusercontent.com/840895/33998552-da0eb596-e0b5-11e7-9f07-59c08bffd69e.png)

**Comment by alisman** [comment]
@adamabeshouse one hint is that when you switch to oncoprint page from cancer type summary (which under this condition is default tab) and THEN resize browser, oncoprint renders.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/813

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3584
