### ISSUE TITLE
Update frontend code for new samples endpoing signature

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#3582]
Samples endpoint can now accept sample lists and the signature of endpoint has been updated.  Endpoint change has been merged to release-1.11.0 branch of portal project so we will need to regnerate client against it. Typescript should then complain.  
We should also pass case lists IF we have them. Check to see they are being properly passed from backend to page to store.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/814
