### ISSUE TITLE
We are not populating some query settings in modify query form

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#3586]
![image](https://user-images.githubusercontent.com/186521/34013352-1f23b0d0-e0e5-11e7-94f0-68d8c7829bdb.png)

Select Data Type Priority
If you click Mutations Only, then submit, that will not be preserved when result opens. 

I think this also true for Genomic Profile settings.  

Also, we need to make sure that on homepage we are aborbing query params from study page (which can send user to query page).

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3589

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/816/files
