### ISSUE TITLE
Oncoprint legend padding issue (is due to study of origin track)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#3592]
@adamabeshouse this issue you found only appears when study of origin track is present.  Looks like maybe that isn't being taken into account when determining absolute offsets?

![image](https://user-images.githubusercontent.com/186521/34017481-f8c3ea7c-e0f3-11e7-8b7e-41ca0c2179ba.png)

**Comment by adamabeshouse** [comment]
Im seeing it even without study of origin track

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/oncoprintjs/releases/tag/v1.0.70
