### ISSUE TITLE
link to patient view from oncoprint loads a blank page

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3594]
Click on any patient ID here:
http://www.cbioportal.org/beta/index.do?session_id=5a333a17498eb8b3d5621a3a&show_samples=false&clinicallist=3%2C1%2C0%2C2%2CAGE

A new window opens but nothing loads:
![image](https://user-images.githubusercontent.com/10508276/34024869-98c09a7c-e11a-11e7-843a-0d0f2e59bf7c.png)

**Comment by jjgao** [comment]
patient page is not working #3600
