### ISSUE TITLE
minimap doesn't have zoom bars

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3595]
![image](https://user-images.githubusercontent.com/10508276/34025000-5cdfbab4-e11b-11e7-87fc-f071d7c42cfb.png)

http://www.cbioportal.org/beta/index.do?session_id=5a333a17498eb8b3d5621a3a&show_samples=false&clinicallist=3%2C1%2C0%2C2%2CAGE

**Comment by adamabeshouse** [comment]
we fixed this @alisman
