### ISSUE TITLE
oncoprint - cluster RNA puts samples with no data first

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3597]
If I add an RNA heatmap to OncoPrint and then click the "cluster heatmap" button, the cluster order puts all samples with no data to the left. Depending on the current zoom of OncoPrint, this can essentially hide the samples offscreen:
![image](https://user-images.githubusercontent.com/10508276/34025173-6e2e4cee-e11c-11e7-8237-e636e4df9de2.png)

Zoomed out, I find the samples with RNA
![image](https://user-images.githubusercontent.com/10508276/34025135-3c2f6f70-e11c-11e7-9cf1-a806bba7dbae.png)

Can the sort order be reversed so that when clustering on RNA, the samples with RNA go to the left?

**Comment by jjgao** [comment]
@pieterlukasse maybe you can help or give some insight?

**Comment by adamabeshouse** [comment]
I can't duplicate this, do you have a link?

**Comment by tmazor** [comment]
@adamabeshouse try this link: http://www.cbioportal.org/beta/index.do?session_id=5a32c40d498eb8b3d5621383&show_samples=false&heatmap_track_groups=lgg_tcga_mrna_median_Zscores%2CIDH1%2CEGFR%2CPTEN

**Comment by adamabeshouse** [comment]
Fixed by https://github.com/cBioPortal/oncoprintjs/pull/44 , will merge updated oncoprint version to cbioportal shortly
