### ISSUE TITLE
oncoprint gets really wide in IE and Firefox

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#360]
Not urgent but we should do some test in IE10 or 11. Onur may have a windows virtual machine for that.

**Comment by leedonghn4** [comment]
can you post pictures

**Comment by onursumer** [comment]
I still have the virtual Windows installed on my local machine. Alternatively, you can use this official VMs provided by Microsoft: https://dev.modern.ie/tools/vms/mac/

**Comment by adamabeshouse** [comment]
I have a VM of windows 8.1 as well and can test

**Comment by jjgao** [comment]
@adamabeshouse since we are going to support IE11 (and of course Firefix), please try to fix it.

**Comment by adamabeshouse** [comment]
tested on IE and firefox (y)
#739
