### ISSUE TITLE
BAM linking

### ISSUE THREAD

**Issue by alexbaras** [cBioPortal/cbioportal#3608]
Is there some documentation I could refer to regarding setting up BAM linking in IGV and/or IGV.js specifically for mutations. I see that IGV.js is already being used for BAM viewing in the context of copy number. I would like to to something like this when linking out for the sample viewer (see below)

![image](https://user-images.githubusercontent.com/8574243/34069651-2a60bed6-e223-11e7-8c9d-0e351ecc438b.png)

**Comment by jjgao** [comment]
@alexbaras unfortunately we no longer support BAM linking with IGV.js.
