### ISSUE TITLE
missing text&button in virtual study oncoprint

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3609]
When I query one study, OncoPrint has a row at the top delineating the case set, numbers of patients, number of samples, and a button to switch between sample/patient view:
![image](https://user-images.githubusercontent.com/10508276/34083489-8da7c2a6-e33f-11e7-9e4d-d5dcc5888e4f.png)
This is important to highlight (with the numbers) that some patients have multiple samples and to make it easy (with the button) to switch between those two views.

But when I query multiple studies, that row doesn't exist:
![image](https://user-images.githubusercontent.com/10508276/34083469-2ec5f104-e33f-11e7-9b2f-1c81472899ad.png)

Can that text be added back to the virtual study OncoPrint?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/824

**Comment by tmazor** [comment]
I don't see the "Case Set: .... " text for virtual studies on beta:
![image](https://user-images.githubusercontent.com/10508276/34791414-e5fff6a4-f612-11e7-91c6-f52c22013e17.png)
http://www.cbioportal.org/beta/index.do?session_id=5a54d826498eb8b3d5636285&show_samples=true&clinicallist=3%2C2%2C0%2CCANCER_TYPE

If I try a different query that includes cases with multiple samples, then I can see that the button appears, but the text still isn't there:
![image](https://user-images.githubusercontent.com/10508276/34791480-1c0f74b8-f613-11e7-8e89-0c1647f9ec74.png)
http://www.cbioportal.org/beta/index.do?session_id=5a566a19498eb8b3d5637fdb&show_samples=false&clinicallist=3

We need to clearly state the numbers of samples & patients in the query like on the old OncoPrint:
![image](https://user-images.githubusercontent.com/10508276/34791617-7493212a-f613-11e7-82eb-9cadad12dc08.png)

@adamabeshouse can that text be added?

**Comment by adamabeshouse** [comment]
@jjgao what should we put here? In the case of a virtual study, there is no case set name.

**Comment by jjgao** [comment]
@adamabeshouse There should be no case IDs, but it's a good idea to display the number of samples. We also want to add the link to study view page back later so we can probably do that together (there should be an issue already, but I couldn't fine it...). 

BTW. could you change "Altered in xxx (xx%) of xxx sequenced cases/patients (xx total)" to "Altered in xxx (xx%) of xxx selected cases/patients (xx total)"

**Comment by adamabeshouse** [comment]
It is sequenced deliberately, the selection may be bigger.

So it should just say "X samples/Y patients." ?

**Comment by jjgao** [comment]
@adamabeshouse I see. So only sequenced samples were counted?

**Comment by adamabeshouse** [comment]
@jjgao In that percentage, yes

**Comment by jjgao** [comment]
@adamabeshouse I misunderstood the issue.

For the case set text above the oncoprint menu, can we revert to the previous version?

In beta it is:
http://www.cbioportal.org/beta/index.do?session_id=5a5cf0e1498eb8b3d563c9ba
![image](https://user-images.githubusercontent.com/840895/34956933-5ec7b2f4-f9f9-11e7-8cc8-3bda7410406a.png)

Previous version:
http://www.cbioportal.org/index.do?session_id=5a5cf0e1498eb8b3d563c9ba
![image](https://user-images.githubusercontent.com/840895/34956941-6651c2ee-f9f9-11e7-866f-f5167613c4d1.png)

**Comment by jjgao** [comment]
moving it back to back log.
