### ISSUE TITLE
links on new OQL page don't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3612]
There are two URLs pointing back to cbioportal in the last section and both need an underscore in between "session" and "id", otherwise they don't work. These links and also the link to the google group at the very end of the page need to be turned into active links also.

**Comment by adamabeshouse** [comment]
this will be fixed when we merge, because the page fetches the documentation markdown page from master. I've confirmed that when the source is changed to the new version, the links work.
