### ISSUE TITLE
enrichments tab "add checked gene to query" doesn't work when using custom case list

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3615]
Complete steps to reproduce:
Go to study page: http://www.cbioportal.org/study?id=lgggbm_tcga_pub#summary
Select IDH1 mutant tumors only.
Query EGFR & TP53: http://www.cbioportal.org/index.do?session_id=5a6f6fd6498eb8b3d56489d4
Then go to Enrichments tab, select a gene, and it fails.

![image](https://user-images.githubusercontent.com/10508276/34083828-6ef2b67c-e344-11e7-90ed-8a761932dd8f.png)

**Comment by alisman** [comment]
@inodb this is broken in production as well.  needs back end debugging to see what's wrong.

**Comment by tmazor** [comment]
any progress on figuring out why this doesn't work?

**Comment by inodb** [comment]
@tmazor this should be fixed in production (cbioportal.org). There's also an automated end to end test that adds a gene to the query using this interface. If it's not working, could you let us know how to reproduce?

**Comment by tmazor** [comment]
Ahhh, I see - when I run a standard query from the homepage and go to the enrichments tab, it works. But if I start with a custom subset of patients (http://www.cbioportal.org/index.do?session_id=5a6f6fd6498eb8b3d56489d4), then it fails:
![image](https://user-images.githubusercontent.com/10508276/35528882-47428ad2-04fd-11e8-8564-51abe255251f.png)

**Comment by inodb** [comment]
Ahh ok good find, thanks @tmazor . I renamed the issue. We didn't test for custom case lists
