### ISSUE TITLE
New beta: Survival test statistics differ between old and new

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3617]
http://www.cbioportal.org/beta/index.do?session_id=5a37c436498eb8b3d562439b
Logrank Test P-Value: 0.0688

http://www.cbioportal.org/index.do?session_id=5a37c41f498eb8b3d5624398
Logrank Test P-Value: 0.0908

**Comment by jjgao** [comment]
@ersinciftci I looked into this more by select samples with os_month. 

http://www.cbioportal.org/beta/index.do?session_id=5a3937c7498eb8b3d5625dee
http://www.cbioportal.org/index.do?session_id=5a3937c7498eb8b3d5625dee

The numbers are still different. But the beta version adds up correctly -- the total cases in the two groups equals to the number of total queried patients, so I think your implementation is correct.
