### ISSUE TITLE
Disparity between prod and beta oncoprint result

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#3621]
How can sequenced cases/patients by higher than total?
"Altered in 360 (40%) of 896 sequenced cases/patients (766 total)"  

![image](https://user-images.githubusercontent.com/186521/34117835-ded799b6-e3ea-11e7-9bb4-ee4d2fb49c15.png)

Also, there's a disparity in percentages between same query on beta and production:
http://www.cbioportal.org/index.do?session_id=5a37efbe498eb8b3d56247b3&show_samples=false&clinicallist=CANCER_STUDY&

![image](https://user-images.githubusercontent.com/186521/34117911-2d8b61dc-e3eb-11e7-90c9-2dd1291b55f3.png)

![image](https://user-images.githubusercontent.com/186521/34117928-3bce31fc-e3eb-11e7-8fc4-9f77e9f57665.png)

**Comment by adamabeshouse** [comment]
closed after discussion in slack suggesting beta version is correct
