### ISSUE TITLE
New beta: Mouse-over in new survival curve is tricky

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3622]
I find it difficult to hover over individual data points in the new survival plots and get the tooltip that includes the patient ID and other. Some data points seem to be hard to "catch".

**Comment by jjgao** [comment]
@schultzn we are thinking of disabling the tooltip and filing a bug to the library for this release and come back to it later. Is that OK?

**Comment by schultzn** [comment]
The tooltips mostly work - so better to keep it in and fix later.

**Comment by ersinciftci** [comment]
Opened an issue in the charting library's repo https://github.com/FormidableLabs/victory/issues/882

**Comment by ersinciftci** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/845 will fix this problem.
