### ISSUE TITLE
Enrichment tab causes error when gene is added to query

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3636]
Steps to reproduce:

- Do a query with some genes, e.g. on BRCA TCGA study
- Go to Enrichments tab. 
- Select one of the genes (by selecting the checkbox)
- Click button "Add checked genes to query". This will result in following error page:

![image](https://user-images.githubusercontent.com/2900303/34251416-50c14d68-e640-11e7-8896-7313c2c5b9e3.png)

**Comment by pieterlukasse** [comment]
Notify: @jjgao

**Comment by jjgao** [comment]
duplicate with #3250
