### ISSUE TITLE
setting priorities for autogenerated charts in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3642]
or any charts that are not associated with clinical attributes.

Maybe we can add a property in the configuration file for now?

**Comment by zhx828** [comment]
@jjgao do we need to follow up on this ticket?

**Comment by jjgao** [comment]
@zhx828 I think so. I am wondering if we can do it per study. E.g. add a configuration file in the study that will be imported into the clinical_attribute_meta table.

This is not a priority though. I think we should keep it here and work on it when see a need.
