### ISSUE TITLE
link to a page as clinical attribute

### ISSUE THREAD

**Issue by patidarr** [cBioPortal/cbioportal#3643]
Hi,

Is it possible to put http address as a clinical attribute? for example I have patient Level QC (a patient have 5-10 samples) as PNG files on a server and I would to open the PNG file from Clinical Data page or any other page where ever the sample/patient level clinical attributes are rendered. 

I actually have many different QC pages (png/pdf and tables in some cases) and I am thinking If I could put them all on a server and can open them from cBIO instance then the PI won't have to go through the folder structure to find the QC.

Same with Bam files, is there a working example of loading bam files in the igvjs (similar to segmented copy numebr loading), 

we have histology slides on all the samples and it would be great if you can point me to instructions on how to link slides to samples.(I think this is done for TCGA samples?)

Thanks,
Rajesh

**Comment by jjgao** [comment]
Hi @patidarr: would you please send your question to cbioportal@googlegroups.com. For your first question, please clarify with an example. Thanks.
