### ISSUE TITLE
remove "Query this study" in the header on study view page?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3649]
It looks like this button is exactly the same as "Query" button below. 

It was different -- previously it would open the query page with the study selected but no sample IDs or genes pre-filled. Maybe the "Query" button is sufficient? 

One change we can make to the query button: if no samples were selected, can we use the default case list (not prefill the sample IDs) in the query page?

![image](https://user-images.githubusercontent.com/840895/34394475-58536750-eb27-11e7-9583-20b88a73197f.png)

**Comment by jjgao** [comment]
@schultzn thoughts?

**Comment by schultzn** [comment]
I agree, that is a good compromise... I used the "query this study" button sometimes.

**Comment by jjgao** [comment]
@zhx828 please prioritize this. Thanks.
