### ISSUE TITLE
Show number of filtered studies in query page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3656]
When I type in "TCGA", I would really like to see how many studies. Currently, you have to select all in order to do that. Can we add the number of studies in the "Study Box" somewhere?

**Comment by tmazor** [comment]
Yes! I agree we need to add this!

Two thoughts on places we could add it:
0 studies selected (0 samples) of XXX studies displayed
or
Select all (XXX studies)

**Comment by jjgao** [comment]
I like "Select all (XXX studies)". 

The first option (0 studies selected (0 samples) of XXX studies) may not work when we have studies selected by not displayed after filtering.

**Comment by jjgao** [comment]
closing this. captured by #3399
