### ISSUE TITLE
Cancer Types Summary customize menu minor issues

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3657]
`Min. # Total Cases` should not be reset when changing `Y Axis Value`.

![](https://media.giphy.com/media/3ohc1dCteKbZYeIV1u/giphy.gif)

Similarly, neither `Min. #(%) Altered Cases` or `Min. # Total Cases` should be reset when changing `Sort X Axis By`.

![](https://media.giphy.com/media/3o752c4zW4NVJTkaZy/giphy.gif)

**Comment by inodb** [comment]
deployed to beta
