### ISSUE TITLE
Clinical attribute for TCGA study incorrectly labelled 

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#3659]
'Initial Weight' has been incorrectly labeled as 'Initial Patient weight' in cBioPortal. 
Example: http://www.cbioportal.org/case.do#/patient?caseId=TCGA-2A-A8VL&studyId=prad_tcga&tab=clinicalDataTab
Data in GDC: https://portal.gdc.cancer.gov/cases/49197847-cc83-4ce1-8397-d09cea4c4928

The weight actually indicates the weight of the sample tissue and not the patient.

Issue was identified by user: https://groups.google.com/forum/#!topic/cbioportal/cl097y7Iqq4

**Comment by jjgao** [comment]
moved to https://github.com/cBioPortal/datahub/issues/145
