### ISSUE TITLE
Show structural variant annotations from OncoKB

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3666]
OncoKB can now show structural variant annotations, but we don't show them yet in cBioPortal.

**Comment by jjgao** [comment]
I don't think that's true: http://www.cbioportal.org/index.do?session_id=59566286498e5df2e291e255&show_samples=false&

We have to make sure this still works.

**Comment by zhx828** [comment]
@inodb @jjgao currently portal is working ok handling structural variants. OncoKB enables most of the portal fusions. The reason we added structural variant support is for differentiating functional, nonfunctional fusions. At this moment, I suppose all fusions in the portal are functional fusions, if this is the case, no changes need to make.
