### ISSUE TITLE
Wrong Mutation Type

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3679]
http://www.cbioportal.org/beta/case.do#/patient?studyId=luad_tcga&caseId=TCGA-86-6562

The ERBB2 mutation should be inframe instead of frameshift.

![image](https://user-images.githubusercontent.com/840895/34728117-010b1092-f527-11e7-8735-7616825452e3.png)

This also happens in the mskimpact clinical cohort here.

**Comment by jjgao** [comment]
By querying the public database, looks like there are many more such cases.

```sql
select *
from mutation_event
where mutation_type="Frame_Shift_Ins"
and protein_change like "%delins%";
```

![image](https://user-images.githubusercontent.com/840895/34729593-230e926e-f52b-11e7-978f-fa7cf42e7833.png)

Maybe something wrong with the logic here: https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/annotator/src/main/java/org/cbioportal/annotator/internal/GenomeNexusImpl.java#L721

**Comment by jjgao** [comment]
@n1zea144 could you put it into your backlog.

- [ ] fix the database (a simple sql query should do the work)
- [ ] fix annotator

**Comment by angelicaochoa** [comment]
@jjgao @sheridancbio @n1zea144 

looks like extra parenthesis is throwing off the `if` statement here:

https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/annotator/src/main/java/org/cbioportal/annotator/internal/GenomeNexusImpl.java#L725

```
if ((variant.equals("frameshift_variant") || (variant.equals("protein_altering_variant") || variant.equals("coding_sequence_variant")) && !inframe)) {
```

should be 

```
if ((variant.equals("frameshift_variant") || variant.equals("protein_altering_variant") || variant.equals("coding_sequence_variant")) &&  && !inframe) {

**Comment by jjgao** [comment]
@angelicaochoa thanks! Could you do a quick and dirty database fix? My sql script above may be useful. Not sure I we should add that into the migration script for other people to fix their data?

**Comment by angelicaochoa** [comment]
@jjgao public database is fixed now. we will push these changes to datahub as well

**Comment by jjgao** [comment]
@angelicaochoa thanks! Please also fix cgds_gdac and maybe other databases.

**Comment by angelicaochoa** [comment]
@jjgao already done :)
