### ISSUE TITLE
OncoPrint: Mutation Color -- cBioPortal and COMSMIC should apply to all types of mutations

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3682]
currently only applied to missense mutations?

**Comment by adamabeshouse** [comment]
thats not true? its missense or inframe for cosmic, anything for cbioportal

**Comment by jjgao** [comment]
@adamabeshouse I moved it to backlog.

**Comment by adamabeshouse** [comment]
is there any conceivable reason for this? I dont understand why we would ever have done this. 

Was there a time when oncokb only applied to missense/inframe, and so we had it like that for consistency?

**Comment by jjgao** [comment]
@adamabeshouse I vaguely remember oncokb only applied to missense (maybe also inframe) long time ago.

**Comment by tmazor** [comment]
@adamabeshouse @jjgao :  Is this issue the reason that when I define putative driver as cBioPortal>=1, there are still truncating mutations of unknown significance?

![image](https://user-images.githubusercontent.com/10508276/37616103-4e1ed3fc-2b85-11e8-8480-dfdf174629d4.png)

**Comment by adamabeshouse** [comment]
@tmazor yes and as of now this change has been merged into `rc` meaning its slated for the next release. should we merge this into this release instead? @alisman @jjgao
