### ISSUE TITLE
Possible issues with study in cbioportal.org

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#369]
I just noticed some apparent inconsistencies while looking at the "Enrichments" tab in cbioportal.org

(1) Go to this example study/query: http://www.cbioportal.org/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_3way_complete&case_ids=&gene_set_choice=prostate-cancer%3A-ar-signaling-%2810-genes%29&gene_list=SOX9+RAN+TNK2+EP300+PXN+NCOA2+AR+NRIP1+NCOR1+NCOR2+ELK4+SLC45A3+IL10+KAT6A+BCORL1+LRRK2+TP53+UHRF1BP1L&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit

(2) In tab "Enrichments" , sub tab "mRNA" there is a column in the table called "Mean of alteration" while the tool tip for this column says: "Mean of expression values in altered or unaltered group" . This is confusing. 
(2b) The profile used is also named "mRNA expression (RNA Seq V2 RSEM) (log)" while this option does not appear in the "Modifiy query" form. There it is mentioned as " mRNA Expression z-Scores (RNA Seq V2 RSEM) "; so z-scores instead of log values.  Is there a hidden profile with log values, or is this a typo in the genetic profile name?

**Comment by jjgao** [comment]
Thanks, Pieter.

(2)"Mean of alteration" is wrong. We will change that.

(2b) We are not using z-score profiles for this analysis because they are just linear transformation of the original data. For RNA seq data, the log form is more normal-like distribution, so we transform the data to log scale on the fly.

**Comment by jjgao** [comment]
@yichaoS, please fix below:

 - [ ] in mRNA table, change "Mean of alteration" to "Mean mRNA expression" and "Standard deviation of alteration" to "Standard deviation of mRNA expression"
 - [ ] in protein table, change "Mean of alteration" to "Mean protein expression" and "Standard deviation of alteration" to "Standard deviation of protein expression"

**Comment by CharlesChuange** [comment]
how to decide the altered criteria of mRNA level ?
thanks
