### ISSUE TITLE
MAF --custom-enst to select UniProt canonical isoforms

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3691]
hi @jjgao and @ckandoth 

In [cBioPortal FileFormats](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#mutation-data) it is described that `--custom-enst` with [this](https://github.com/mskcc/vcf2maf/blob/master/data/isoform_overrides_uniprot) mapping file is required when creating a MAF for cBioPortal. vcf2maf describes this parameter as a `List of custom ENST IDs that override canonical selection`. So it is required to override the "canonical selection", to select the "UniProt canonical isoforms". I was wondering if you could help me understand this better.

1. If `--custom-enst` is not used, which values are included in the MAF?
2. What is the difference between the UniProt canonical isoforms and the canonical values?
3. Is `isoform_overrides_uniprot` a BioMart export? Is it important to update this file regularly or add versioning?

**Comment by jjgao** [comment]
1. If  `--custom-enst` is not used, I think the ensembl canonical isoform will be used.
2. Not sure what you mean by "canonical values".
3. see https://github.com/mskcc/vcf2maf/issues/109

**Comment by ckandoth** [comment]
Thanks @jjgao. @sandertan Ensembl's canonical isoforms are defined [here](https://useast.ensembl.org/Help/Glossary?id=346) and VEP uses that as the top criteria for selecting an isoform to map a variant onto. The other criteria for selecting "one effect per variant" are explained [here](https://useast.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick). Internally at MSK, we prefer [this selection of isoforms](https://github.com/mskcc/vcf2maf/blob/v1.6.15/data/isoform_overrides_at_mskcc) which are manually selected by the clinical sequencing team, and limited to genes in the MSK-IMPACT assay. But the public facing cBioPortal uses uniprot isoforms as explained [here](http://www.uniprot.org/help/canonical_and_isoforms).

**Comment by ckandoth** [comment]
Sorry, I closed the issue accidentally. Reopen if necessary.

**Comment by sandertan** [comment]
Thanks for the clarifications @jjgao and @ckandoth! I'll set a to-do for myself improve our file formats page based on your explanation.

**Comment by sandertan** [comment]
I improved the documentation on creating a MAF file. @jjgao perhaps you could take a look? https://github.com/cBioPortal/cbioportal/pull/3770
