### ISSUE TITLE
Add Variant Type Column to Mutations Table

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3694]
We already pass `variantType` field to the frontend (part of the TCGA MAF spec (https://wiki.nci.nih.gov/display/TCGA/Mutation+Annotation+Format+(MAF)+Specification) ). All that needs to be done is to allow the user to show the column.

User request: https://groups.google.com/forum/#!topic/cbioportal/LpOpb7s5GWY

**Comment by jjgao** [comment]
maybe do it in mutatiomapper first.

**Comment by ecerami** [comment]
@inodb as you say, looks like the variant type is already available within the front-end.  and, therefore this should be a front-end only fix.  And, since it's been long-neglected, I will give it a try!
