### ISSUE TITLE
cancer types summary - add download data button

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3697]
Cancer Types Summary has an option to download PNG but not to download data. Can we add a download data button?

![image](https://user-images.githubusercontent.com/10508276/34789459-56647296-f60c-11e7-836a-70dd86809a6c.png)

**Comment by jjgao** [comment]
@alisman another one when re-refactor the tab.

**Comment by alisman** [comment]
@dippindots @jjgao is there an obvious format for the download data?

**Comment by jjgao** [comment]
I think we can define a general format for stacked bar chart, e.g. a matrix of alteration frequencies of cancer type vs alteration types.

![image](https://user-images.githubusercontent.com/840895/56995599-38810700-6b70-11e9-9299-7b84a4017002.png)

**Comment by alisman** [comment]
@dippindots what's status of this?

**Comment by dippindots** [comment]
@alisman Not started yet, I can work on this next.

**Comment by tmazor** [comment]
This is still an issue

**Comment by jjgao** [comment]
This is captured here: https://github.com/cBioPortal/cbioportal/issues/5314.
