### ISSUE TITLE
oncoprint - add left padding to clinical track hover boxes

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3698]
When I hover over a clinical track, I get a pop-up with a description of the track. When that box happens to overlap with the text above OncoPrint (see screenshot below), I find it hard to read. Can we add a little padding to the left of that box so that there's a bit of white space?

![image](https://user-images.githubusercontent.com/10508276/34789719-57790326-f60d-11e7-9050-2111ec8fd0a1.png)

**Comment by jjgao** [comment]
Maybe @alisman can help improve the style. Not urgent.

**Comment by adamabeshouse** [comment]
duplicate, added to #3728

**Comment by tmazor** [comment]
It looks to me like the tooltips over the OncoPrint content now have left padding, but the tooltips for clinical track names still don't have any left padding:
![image](https://user-images.githubusercontent.com/10508276/35640596-9ede8496-068b-11e8-8cfc-21fc05793193.png)

Can we add padding to the clinical track name tooltips also?
