### ISSUE TITLE
lag in oncoprint when changing mutation color rules

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3699]
If I check/uncheck a box in the Mutation Color menu, OncoPrint goes grey for a second, reloads exactly as it was before, and then after ~2 seconds updates to reflect the new color scheme based on whatever I just checked/unchecked.

(1) This is what I start with
![image](https://user-images.githubusercontent.com/10508276/34790301-65916776-f60f-11e7-8181-e9dfd80f614a.png)

(2) I click "Hide VUS".  This happens too quickly for me to get a screenshot, but OncoPrint briefly changes to the grey "loading" screen

(3) Then OncoPrint reloads looking identical
![image](https://user-images.githubusercontent.com/10508276/34790306-6acd883c-f60f-11e7-82bb-dbcf76d30cb1.png)

(4) After a few seconds, it updates properly
![image](https://user-images.githubusercontent.com/10508276/34790319-6ffbb7de-f60f-11e7-8e62-acc3827a736d.png)

http://www.cbioportal.org/beta/index.do?session_id=5a54d826498eb8b3d5636285&show_samples=true&clinicallist=3%2C2%2C0%2CCANCER_TYPE

**Comment by jjgao** [comment]
@adamabeshouse maybe https://github.com/cBioPortal/cbioportal/issues/3591 will solve the problem?

**Comment by tmazor** [comment]
any updates on this @adamabeshouse @jjgao ?

**Comment by adamabeshouse** [comment]
it seems to be fixed in /beta, yeah?

**Comment by tmazor** [comment]
you're right @adamabeshouse, it is! but it wasn't this morning - it must have been part of the 1.12 update that @inodb deployed today?
