### ISSUE TITLE
oncoprint zooms out after changing mutation colors

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3700]
This may or may not be related to the bug in #3699 

After changing the mutation color (as in #3699), OncoPrint sometimes reloads fully zoomed out
![image](https://user-images.githubusercontent.com/10508276/34790885-3b75631e-f611-11e7-83a9-8c6bfb4be73a.png)

On my computer, I see this happening consistently in Safari but not in Chrome. @ersinciftci tried on his computer and saw this happening in Chrome also.

**Comment by adamabeshouse** [comment]
seems fixed in production
