### ISSUE TITLE
Allow users to show counts in mutual exclusivity analysis

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3704]
Add the columns that show the number of cases where mutations in the gene co-occur. Don't display it by default, but allow the user to click on columns and show the number.

User request: https://groups.google.com/forum/#!topic/cbioportal/cYVB-RawPxc

**Comment by jjgao** [comment]
Another user request: https://mail.google.com/mail/u/0/#inbox/1612b3d2452ff58d

**Comment by jjgao** [comment]
@ersinciftci maybe you can prioritize this one since two users asked in a row? Assuming it's easy.

**Comment by jjgao** [comment]
... and an additional column of q-value too: https://github.com/cBioPortal/cbioportal/issues/2981

**Comment by ersinciftci** [comment]
@jj besides q-value, is it just one new column that will show the co-occurrence count? What should be the name of the column?

**Comment by jjgao** [comment]
@ersinciftci I think there will be four columns, ie. a, b, c, d, corresponding to the 2x2 table in [Fisher's exact test](https://www.wikiwand.com/en/Fisher%27s_exact_test).

![image](https://user-images.githubusercontent.com/840895/35533656-36aca9a0-050c-11e8-82f3-86397da5856f.png)

Maybe we can use a,b,c,d as column name and display the figure above in the mouse over?

**Comment by ersinciftci** [comment]
@jjgao Ah, ok, so you want all the numbers. The columns will be hidden at first, will be shown in the `Columns` dropdown, so they won't see the figure before making those column visible first. Is that ok, or should we name them something like `Neither`, `ANotB`, `BNotA`, `Both`?

**Comment by ersinciftci** [comment]
@jj decided that we should show them by default
