### ISSUE TITLE
header text is different on beta

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3706]
Production:
![image](https://user-images.githubusercontent.com/10508276/34835547-1baf503c-f6c3-11e7-8e50-82cc0ad99049.png)

Beta:
![image](https://user-images.githubusercontent.com/10508276/34835668-79d9703e-f6c3-11e7-8626-bcc4e71dda4f.png)

The number of samples is gone and the percentage has an extra decimal place. Is this done for a reason? I prefer including the number of samples like on production.

The link to the "Combined Study" is also gone, but I think that's on purpose since the study has more than 20 samples?

**Comment by jjgao** [comment]
Good catch. I think we should get the number of altered samples back too.

The "Combined Study" link was removed on purpose. We will bring it back later: https://github.com/cBioPortal/cbioportal/issues/3624

**Comment by jjgao** [comment]
For the text, we should add both the total number and altered number of samples.

- [ ] Change "This combined study contains samples from 32 studies" to "Querying 7958 samples in 32 studies"
- [ ] Change "Gene Set / Pathway is altered in 6.67% of queried samples" to "At least one query genes are altered in 1152 (14.5%) of queried samples".
