### ISSUE TITLE
inconsistent behavior of copy & download from tables

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3708]
On beta, on the Mutual Exclusivity tab (and therefore presumably all tables), clicking the download button downloads all data columns regardless of which are visible but respects the sort order. So if I download once, then change the sort order, then download again, the two downloaded files have the same data in a different order.

However, once I click the copy button once, clicking it again does nothing -- it doesn't re-copy until I reload the page.

As a user, I expect copy & download to do the same thing. Can the copy button act like the download button and re-load the data each time it is clicked?

**Comment by jjgao** [comment]
@tmazor I was thinking of removing the copy functionality. What do you think?

**Comment by tmazor** [comment]
@jjgao that seems fine to me
