### ISSUE TITLE
inconsistent behavior of copy button

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3709]
On beta, the first time I click "copy" on a table, a box appears:
![image](https://user-images.githubusercontent.com/10508276/34837701-a39c3db0-f6c9-11e7-96c1-95b9dbb4e1b0.png)

I have to click the "Copy" button here and then the data is copied.

However, if I click the copy button again, nothing happens. This is presumably related to #3708 in that the data is downloaded into cache once and then copied from there, so the "Download complete" box doesn't need to appear. But as a user, this is very confusing and makes me think that my second copy was unsuccessful, since I don't have the same interface as the first time I copied.

One option is to have that same box appear and make the user click the copy button there again. But that's also adding an unnecessary additional click for the user. Another option might be some sort of visual feedback that the copying was successful? I'm not sure what's best to do here.

**Comment by onursumer** [comment]
I think a visual feedback, something like showing a tooltip saying "Copied!" , is not a bad idea.

**Comment by onursumer** [comment]
@jjgao This one is not fixed yet for the `Mutations` tab, but fixed for the `Download` tab. I'll try to fix it soon for the Mutations tab as well.
