### ISSUE TITLE
removing copy icon from mutations tables

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3713]
There seems to be a few issues related to the copy functionality: https://github.com/cBioPortal/cbioportal/issues/3707, https://github.com/cBioPortal/cbioportal/issues/3708, https://github.com/cBioPortal/cbioportal/issues/3709

I don't see a strong need of copy functionality in mutations and CNA table (and maybe most other tables). Can we remove it from the interface?

![image](https://user-images.githubusercontent.com/840895/34892689-3727291c-f7a8-11e7-83a7-ec90b7fc1d97.png)

**Comment by jjgao** [comment]
Niki mentioned it's still a useful feature, so let's try to keep it. 

@onursumer how much work we need to do to maintain the feature?

**Comment by onursumer** [comment]
@jjgao I already improved copy button functionality. I'll soon open a PR addressing bunch of copy/download issues.

**Comment by jjgao** [comment]
closing this one.
