### ISSUE TITLE
Make pathology pdf reports url configurable

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3716]
- [ ] Currently we show pathology reports with google drive's PDF viewer. This makes it impossible to point to a local PDF server. We could instead use this library from Firefox to display them: https://github.com/mozilla/pdf.js/
- [ ] add a frontend configuration option for changing the datahub URL

User request: https://groups.google.com/forum/#!topic/cbioportal/OGmosOuzBu4

**Comment by jjgao** [comment]
@inodb We could also save the URLs per sample/patient in the database. We would like to attach files per patient, maybe it's better to do it there?

**Comment by inodb** [comment]
@jjgao yes that sounds good. We can maybe get rid of pathology report tab and instead use the files tab.
