### ISSUE TITLE
survival tab labels need to be consistent

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3717]
Currently the y-axis is "Disease/Progression-free survival" while the title is "Disease Free Survival Kaplan-Meier Estimate", the x-axis is "Months Disease Free" and the table below uses "Median Months Disease Free":
![image](https://user-images.githubusercontent.com/10508276/34896719-ec6c0210-f7b8-11e7-9cea-40a0a2d28447.png)

All of those should consistently say either "Disease/Progression Free" or "Disease Free" with the same words, capitalization and lack of a hyphen.

**Comment by tmazor** [comment]
Also, if we're going with "Disease/Progression Free", then the "Number of Cases, Relapsed" column should probably be "Number of Cases, Relapsed/Progressed"

**Comment by DarioS** [comment]
Both Google search results and Nature Journals subjects show that hyphenation and lower-casing of the second word is commonly accepted to be the correct way to write it. You could use either Disease-free or Free of Disease.

![image](https://user-images.githubusercontent.com/631218/34929850-5de7bbe2-fa1a-11e7-8f1e-278cc0386dee.png)

![image](https://user-images.githubusercontent.com/631218/34929857-62e2db18-fa1a-11e7-92bc-8024053d4d55.png)

**Comment by jjgao** [comment]
Let's change header to "Disease/Progression-Free Kaplan-Meier Estimate" and the "Number of Cases, Relapsed" column to "Number of Cases, Relapsed/Progressed"
