### ISSUE TITLE
make text in survival tab tooltip larger

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3718]
The font size in the tooltip seems small to me. Is it truly smaller than other text on the site? If so, can it be made larger?

![image](https://user-images.githubusercontent.com/10508276/34896948-b49bdd8c-f7b9-11e7-9df9-52a6559f2f0c.png)

**Comment by ersinciftci** [comment]
@alisman I tried a few things but can't prevent the line break when I make the font size bigger, can I assign this to you?
