### ISSUE TITLE
new user not getting added

### ISSUE THREAD

**Issue by alexbaras** [cBioPortal/cbioportal#3724]
I am using 1.10.1
I have had saml auth working normally 
I noticed this a while ago (apologies that I cannot place it exactly but it has been an issue for about 1 year)

This 'new' users to the portal's user table are not getting added after successful authentication against our saml server. I can see that it has read in the proper email from the saml server return in that the top right of screen shot below shows the user is logged in, but that record is not present in the portal user table. From that starting point the portal auth table is not really going to be a factor until the user actually exists. 

I did try playing with the always_show_study_group value, but that had no effect.

Any ideas as to what might be going on?

![image](https://user-images.githubusercontent.com/8574243/34904269-777b9bc0-f810-11e7-98c5-5e55e486e19c.png)

**Comment by n1zea144** [comment]
Hi Alex,  Pieter

Alex, I know we had a brief email exchange about this.  I want to add those notes and recruit @pieterlukasse on this issue as he may be able to shed light on the situation.  @pieterlukasse I know that the MSK version of the SAML code was "public" for some time.  In that file we automatically added users to the database after a successful authentication.  That specific code was dropped in the current SAML details service [SAMLUserDetailsServicesImpl.java](https://github.com/cBioPortal/cbioportal/blob/master/security/security-spring/src/main/java/org/cbioportal/security/spring/authentication/saml/SAMLUserDetailsServiceImpl.java#L122) but there is a reference to "always_show_study_group=XXX" in the code/docs [always_show_study_group](http://cbioportal.readthedocs.io/en/latest/User-Authorization.html?highlight=always_show_study_group#configuring-public-studies).  According to Alex, this setting is not working.  Can you help with this?

**Comment by alexbaras** [comment]
Hey guys, any updates on this?

Sorry to bug you on this, but I need to figure out if this is something we need to add back in internally in our instance as I don't want to have to manually be entering users into the user table

Thanks

**Comment by jjgao** [comment]
@alexbaras could you please follow up by email since that would be more efficient. It would also be good to cc cbioportal@googlegroups.com.
