### ISSUE TITLE
convertExpressionZscores.pl error: Expected to find 1 scripts-*.jar, but found: 0 at ../scripts/envSimple.pl line 36

### ISSUE THREAD

**Issue by linkmonica** [cBioPortal/cbioportal#3725]
I tried using script to convert expression values to z-score and got htis error. Please suggest the fix.
I ran on example data mentioned.

Expected to find 1 scripts-*.jar, but found: 0 at ../scripts/envSimple.pl line 36.
Compilation failed in require at ./convertExpressionZscores.pl line 2.

**Comment by jjgao** [comment]
@linkmonica could you please send your question to cbioportal@googlegroups.com? Thanks.
