### ISSUE TITLE
oncopront tooltip tweaks

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3728]
- [x] change "value" to attribute name, e.g. "Cancer Type"
- [x] add "Sample: " or "Patient: " before the sample/patient ID.
- [x] Add left padding as requested in https://github.com/cBioPortal/cbioportal/issues/3698

![image](https://user-images.githubusercontent.com/840895/34955422-46dab4d6-f9f2-11e7-8f9f-819d49e45ef3.png)

**Comment by adamabeshouse** [comment]
For value=>attribute name, should it be the same in case of multiple values? where currently we write "values: Glioma, ... "

**Comment by jjgao** [comment]
@adamabeshouse yes, please combine them.
