### ISSUE TITLE
Oncoprint alteration tracks cannot be sorted by heatmap

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#3740]
See https://github.com/cbioportal/cbioportal-frontend/issues/887

**Comment by fedde-s** [comment]
Right, this would have been a better place for me to report it since it affects the functionality that users of the project as a whole experience. Will consider that in the future.

**Comment by adamabeshouse** [comment]
@fedde-s this just happens to be where we track all issues, no particular logic to it :) yes, in the future an issue here with the `refactoring` tag is how we've been doing it

**Comment by fedde-s** [comment]
Do you mean a fix had been released, @adamabeshouse?

**Comment by adamabeshouse** [comment]
yes, its deployed in /beta and will be generally available soon

**Comment by fedde-s** [comment]
Is the code available yet? I'm wondering if I need to add anything to my PR #898 to make it work for gene set tracks as well.

**Comment by adamabeshouse** [comment]
just got back from vacation, is this resolved? @fedde-s

**Comment by fedde-s** [comment]
Yes! I just checked out `rc`, and it looks like it works now. Thanks for checking up!

**Comment by fedde-s** [comment]
For reference: I see that [this](https://github.com/thehyve/cbioportal-frontend/commit/7a746fb97ee7372bb2f3e682ba933194ac896846#diff-958774fb3f550af60c5435eed1831cd3R55) is the line that fixes it (supported by other lines in the commit).

**Comment by adamabeshouse** [comment]
yep!
