### ISSUE TITLE
Add a timeout when pulling hotspot into oncoprint

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3742]
Show OncoPrint without hotspot info if it takes too much time to get the data

**Comment by jjgao** [comment]
Do we still need to do this? Or should we implement this for all calls to genome nexus?

**Comment by inodb** [comment]
i think this has been handled by using oncokb annotations instead

**Comment by jjgao** [comment]
I see, but we are using Genome Nexus in mutations tab?

**Comment by jjgao** [comment]
logged an issue about switching to genome nexus: https://github.com/cBioPortal/cbioportal/issues/3742
