### ISSUE TITLE
OncoKB feedback button is not working if there are too many navCaseIds

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3754]
The feedback will prefill the form. I think because the url is too long, google form crashed.
![screen shot 2018-01-18 at 2 35 29 pm](https://user-images.githubusercontent.com/5400599/35121008-f78d6bf8-fc67-11e7-9c9e-6b6d3cf12df1.png)

**Comment by jjgao** [comment]
I think we don't need to include navCaseIds
