### ISSUE TITLE
See if there is a way we can use readOnly in MyBatis cache

### ISSUE THREAD

**Issue by ersinciftci** [cBioPortal/cbioportal#3756]
Application performance might possibly benefit using this property, but it causes some problems in security module. We need to find the reason and try to fix.

**Comment by jjgao** [comment]
@n1zea144 @ersinciftci would you still like to explore this?

**Comment by ersinciftci** [comment]
@jjgao I couldn't find a way, maybe @n1zea144 would like to give it a try too.

**Comment by ersinciftci** [comment]
@n1zea144 found a way to do it, so `readOnly` is back now.
