### ISSUE TITLE
Oncoprint is not sorting - CRITICAL

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#3758]
In new release, OncoPrint is no longer sorting correctly.

See:  http://www.cbioportal.org/index.do?case_set_id=gbm_tcga_pub_sequenced&tab_index=tab_visualize&Action=Submit&genetic_profile_ids=gbm_tcga_pub_mutations&genetic_profile_ids=gbm_tcga_pub_cna_rae&case_ids=&Z_SCORE_THRESHOLD=1.0&cancer_study_list=gbm_tcga_pub&cancer_study_id=gbm_tcga_pub&gene_list=TP53+MDM2+MDM4&gene_set_choice=user-defined_list&Action=Submit#summary

![screenshot_2239](https://user-images.githubusercontent.com/1009066/35151898-0f643924-fcee-11e7-9e92-e864b0f15ae3.png)

See MDM2 and MDM4.

@tmazor @jj:  can we also add this check to our new checklist.

**Comment by jjgao** [comment]
I think we need a e2e test on this.

It's also report here about the cause of the issue. @adamabeshouse

**Comment by adamabeshouse** [comment]
This would have been caught quickly by e2e

I made a mistake remembering how oncoprint sorting works. The oncoprint uses sort comparators defined for each track, combines their results to determine the final sort. For each track, there are two tiers of comparator: preferred, and mandatory - preferred determines an ordering between each column that will prevail if none of the below tracks desire a different ordering for those columns; mandatory determines an ordering that is strictly enforced from top to bottom. By adding an alphabetical ordering to the tracks, I forgot to only add that ordering in 'preferred', and so the alphabetical ordering became mandatory, thus any alphabetical ordering in the top track overruled any data-based ordering in the following tracks.

I'm testing the fix now, PR coming shortly.
