### ISSUE TITLE
cross cancer expression plot: not all studies are selected by default

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3764]
Go here:
http://www.cbioportal.org/index.do?session_id=5a62028e498eb8b3d563de6b&show_samples=false&clinicallist=CANCER_STUDY&

Click over to Expression tab.
Click on "Select Studies"
Esophageal Carcinoma & Stomach Adenocarcinoma aren't selected

![image](https://user-images.githubusercontent.com/10508276/35162933-04896e64-fd13-11e7-8202-a91d01a82cd0.png)

**Comment by jjgao** [comment]
@tmazor this was by design. The Stomach data is very different from other data and will screw the plot for most of genes. We should probably add a warning.
