### ISSUE TITLE
mutations tab legend uses two fonts

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3767]
The legend for the lollipop plot uses two fonts.
"Mutation types and corresponding color codes are as follows:"  and the lists of mutation types (e.g. "Nonsense, Nonstop...") are in a different font than the rest of the text.

All of this text should be in the same font.

![image](https://user-images.githubusercontent.com/10508276/35165358-121df578-fd1c-11e7-9940-58483c442ca7.png)

**Comment by agarwalrounak** [comment]
May I please know where can I find the _mutations tab_/_lollipop plot_ 
I am still trying to figure out the structure of the cBioPortal website.

**Comment by agarwalrounak** [comment]
Ok, I can see the lollipop plot at https://www.cbioportal.org/mutation_mapper and the legend by clicking on the legend tab. 
Does `rest of the text` refer to "Mutation diagram circles...mutation type" or the colored headings (e.g. "Missense mutations", "Truncating Mutations" and so on ...)? If it refers to "Mutation diagram circles...mutation type" then from what I see they are of the same font as of now.

**Comment by tmazor** [comment]
@agarwalrounak Indeed, it does appear that the font has been standardized somewhat since I created this issue. However, it still looks to me like the bold & colored text ("Color Codes", "Missense Mutations", "Truncating Mutations", "Inframe Mutation" and "Other Mutations") is in a different font than the rest of the legend. Can you make those use the same font as the rest of the legend/all other text on the page?

**Comment by agarwalrounak** [comment]
Yes, sure! I will send a PR soon.

**Comment by agarwalrounak** [comment]
Opened PR [cbioportal-frontend#2111](https://github.com/cBioPortal/cbioportal-frontend/pull/2111) 
Please review.
