### ISSUE TITLE
new oncoprint: clinical attribute in the url

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3769]
Previously, we put the attribute_id in the url, but in the new code we put the index. I think we should revert to attribute_id because the list of attributes will change over time, especially for project such as mskimpact.

**Comment by jjgao** [comment]
@adamabeshouse I see. Mabye we can have "more meaningful" attribute_id for these special attributes too? e.g. fraction_genome_altered, mutation_count, mutation_spectrum?

**Comment by adamabeshouse** [comment]
sure that makes sense, I'll use snake-case of their display name
