### ISSUE TITLE
Querying all studies failed in mutations tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3785]
http://www.cbioportal.org/index.do?session_id=5a688e67498eb8b3d56434e4

![image](https://user-images.githubusercontent.com/840895/35335513-d2166bc4-00e3-11e8-8bec-a30c1f74d367.png)

Is this data issue? If yes, please let @ritikakundra know.

It should not fail the whole tab for a data problem in one study. Can we still display the data but maybe also show some warning message?

**Comment by inodb** [comment]
@jjgao it seems to work now?

**Comment by inodb** [comment]
@jjgao ah ok this about mutations tab

**Comment by inodb** [comment]
@adamabeshouse @alisman this also doesn't work in beta: http://www.cbioportal.org/beta/index.do?session_id=5a688e67498eb8b3d56434e4&show_samples=false&clinicallist=CANCER_STUDY&

**Comment by alisman** [comment]
@ino the issue above is fixed by existing PR from last night.

**Comment by inodb** [comment]
Seems that there is something wrong with that particular session. If I regenerate the session and query "SPOP KRAS" on all studies it works fine:

http://www.cbioportal.org/index.do?session_id=5a68a8a0498eb8b3d5643748&show_samples=false&clinicallist=CANCER_STUDY&
