### ISSUE TITLE
Oncoprint fails when mutation has no annotation (because hotspot is missing)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#3787]
http://www.cbioportal.org/beta/index.do?cancer_study_id=acc_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=acc_tcga_3way_complete&gene_list=SOX9%2520RAN%2520TNK2%2520EP300%2520PXN%2520NCOA2%2520AR%2520NRIP1%2520NCOR1%2520NCOR2&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=acc_tcga_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=acc_tcga_rna_seq_v2_mrna_median_Zscores

**Comment by adamabeshouse** [comment]
fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/917
