### ISSUE TITLE
Splice Site Hotspots not shown in mutations table

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3789]
We are working on moving this to genome nexus, but just logging this to show splice sites aren't showing up as hotspots.

http://www.cbioportal.org/index.do?session_id=595d61a7498e5df2e2921610&show_samples=false&
MET X1010_splice is a hotspot, but not shown in mutations table
![screen shot 2018-01-24 at 3 05 39 pm](https://user-images.githubusercontent.com/1334004/35354599-789700b0-0118-11e8-875e-425db93ee3c9.png)

**Comment by jjgao** [comment]
I think we made some decision to annotate hotspots for missense and inframe only. Right, @onursumer ?

**Comment by jjgao** [comment]
The problem is still there? Are we annotating splice mutations now?

**Comment by inodb** [comment]
We should fix this

**Comment by inodb** [comment]
or not annotate splice mutations at all i guess

**Comment by jjgao** [comment]
I think we should annotate splice mutations now that we have a separate category for splice hotspots.
