### ISSUE TITLE
New beta: FGA number in the tooltip should be truncated

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3791]
Two significant numbers is enough here.. 

Should this be changed in the database maybe?

![image](https://user-images.githubusercontent.com/11892704/35405639-cb3f074c-01d4-11e8-8e92-f06c16673b1e.png)

**Comment by adamabeshouse** [comment]
no problem, and what about other floating-point tracks, eg heatmaps?

**Comment by schultzn** [comment]
It probably applies to all of them…

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/937

can you confirm these test cases have desired behavior?:

0.1350001351 =>0.14
6.1000032 => 6.10
0 => 0.00
