### ISSUE TITLE
backend OQL legacy bugs

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#3795]
(1) In QueryBuilder.java, in the download data section, geneList is used assuming its just a plain, space- or newline-separated list of genes.

(2) In visualize.jsp, the calculation `if(geneList.length <=1) { computeLogOddsRatio = false; }` has been wrong since GENE_LIST started including OQL.

**Comment by jjgao** [comment]
Hopeful @onursumer will solve the first one when Download tab is refactored.

For the second, maybe we can turn on/off the Mutex tab in frontend?

I really look forward to retire QueryBuilder and all JSPs!!

**Comment by alisman** [comment]
@jj maybe we hide it by default and then let frontend turn it on if there's more than one study?

**Comment by jjgao** [comment]
@alisman ok.

**Comment by adamabeshouse** [comment]
it turns out a bit easier to hide it from frontend, which i think is fine bc we're lazy-rendering the mutex module, so if we hide the tab there's no way to get to it anyway and very little redundant rendering
