### ISSUE TITLE
new line removed in link from cross cancer query to single study query

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#380]
Reported from user:

"And… there is a wee bug: when you click on one of the bars after doing an initial query across multiple datasets, it takes you to a query page for just that dataset. Which is great.
The problem is that the gene list has all the line returns taken out, so that it is one glob that is not recognized: KRASNRASEGFR"

**Comment by adamabeshouse** [comment]
link?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/399
