### ISSUE TITLE
UnitProtKB in Mutation tab: Retrieved from database or MyGeneInfo?

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3802]
@jjgao I noticed when entering an incorrect UniProtKB accession in my data in the SWISSPROT-column (for which the validator fails), this value is imported and saved in the database in the ONCOTATOR_UNIPROT_ACCESSION column. However, when if I query the gene, the UniProtKB name is correctly displayed in the Mutation Tab. This name is retrieved by first querying MyGene.info with the Entrez gene ID to retrieve the **accession** and then querying UniProt to retrieve the **name**.

For a gene which has a correct UniProtKB accession, MyGene.info is also queried to retrieve the UniProtKB accession.

I was wondering if the SWISSPROT data from the database is still used in the Mutation Tab. It would be nice if this mechanism is documented in File-Formats.md.

If the database is not used for the UniProtKB accession, it would mean that if MSK/a user would add their own isoforms in the SWISSPROT column (e.g. during vcf2maf), this data would not be shown in the front end.

#3790 is a PR to change the error to a warning in the Validator.

**Comment by jjgao** [comment]
@sandertan I don't think we are using ONCOTATOR_UNIPROT_ACCESSION  anymore. @onursumer can you confirm?

We are in the middle to switching to GenomeNexus. @inodb @onursumer maybe we should use GenomeNexus instead of MyGene.info?

**Comment by onursumer** [comment]
@jjgao @sandertan we are not using `ONCOTATOR_UNIPROT_ACCESSION` anymore in the mutations tab. As @sandertan pointed out, we query external services.

**Comment by sandertan** [comment]
Thanks for the replies. So will these columns be removed from the database schema in the near future? And will this be aligned with vcf2maf and File-Formats.md?

**Comment by jjgao** [comment]
@sandertan we are going to have a phase to connect to genome-nexus for data and remove many of them from portal.

**Comment by pieterlukasse** [comment]
hi @jjgao, why is the mutation view retrieving uniprot accession when a specific isoform accession is found in the data already? Shouldn't the external service only be used if no isoform preference is found in the data?

**Comment by jjgao** [comment]
@pieterlukasse it's part of the process of switching to genome nexus. We will remove the uniprot data along with many other annotation data from the portal database.

@inodb @onursumer we should switch to genome nexus for uniprot id.

**Comment by pieterlukasse** [comment]
@jjgao but what if an institute has its own cBioPortal and would like a specific set of isoforms to be used by default when querying genomenexus for the VEP annotation? Now the preferred isoform can be stored in this UNIPROT_ACCESSION field...should the institute install its own version of genomenexus in this case?

**Comment by jjgao** [comment]
@pieterlukasse we haven't worked out a solution yet. I don't think we should use the UNIPROT_ACCESSION in the mutations table. If there is a need, the local instance of the portal should probably host an isoform file that can override the default one from genome-nexus. @inodb @onursumer let's keep this in mind when we working on multi-isoform support.

@pieterlukasse do you have a client that has this need?

**Comment by sandertan** [comment]
@jjgao so for now, shall we go ahead with changing the error to a warning for invalid UniProtKB accession in the MAF? 

https://github.com/cBioPortal/cbioportal/pull/3790

**Comment by jjgao** [comment]
@sandertan yes.
