### ISSUE TITLE
Make Public Session Service

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3803]
- [ ] Upgrade http://session-service.herokuapp.com/ to hobby project on heroku
- [ ] Point session.cbioportal.org to the heroku instance
- [ ] Add documentation to the `.EXAMPLE` indicating with comment one can use that session service.
- [ ] Add documentation to deployment that one can use public session service

**Comment by jjgao** [comment]
@inodb second thought: maybe we can just use https://session-service.herokuapp.com/. It's nice that it's already on https.

**Comment by jjgao** [comment]
@inodb let's move this forward w/o https://github.com/cBioPortal/cbioportal/issues/3805.
