### ISSUE TITLE
co-expression tab gene tab control button is too big

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3808]
When running a query with many genes, the button to move right to the next set of gene tabs is much too big. This is a problem on both beta & production.

![image](https://user-images.githubusercontent.com/10508276/35450472-2ba9f1c8-028e-11e8-9bc5-188b41820b07.png)
http://www.cbioportal.org/index.do?session_id=5a6b5a82498eb8b3d564628d&show_samples=false&

![image](https://user-images.githubusercontent.com/10508276/35450521-4b5f7d3a-028e-11e8-8a45-1273585eaa15.png)
http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=lgg_tcga_3way_complete&gene_list=DATATYPES%253A%2520MUT%2520AMP%2520GAIN%2520HOMDEL%2520HETLOSS%2520EXP%253E1%2520EXP%253C-1%250AKRAS%2520HRAS%2520BRAF%2520RAF1%2520MAP3K1%2520MAP3K2%2520MAP3K3%2520MAP3K4%2520MAP3K5%2520MAP2K1%2520MAP2K2%2520MAP2K3%2520MAP2K4%2520MAP2K5%2520MAPK1%2520MAPK3%2520MAPK4%2520MAPK6%2520MAPK7%2520MAPK8%2520MAPK9%2520MAPK12%2520MAPK14%2520DAB2%2520RASSF1%2520RAB25%250ATP53&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=lgg_tcga_rna_seq_v2_mrna_median_Zscores

**Comment by jjgao** [comment]
Let's fix that when we refactor this page.
