### ISSUE TITLE
Some javascript weirdness in tooltip text

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#381]
![image](https://cloud.githubusercontent.com/assets/636232/10804404/bf6e4bde-7d9d-11e5-8c59-48f3ab122161.png)

http://www.cbioportal.org/cross_cancer.do?cancer_study_list=&cancer_study_id=all&data_priority=0&case_ids=&gene_set_choice=user-defined-list&gene_list=KRAS%0D%0ANRAS%0D%0AEGFR&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit#crosscancer/overview/0/KRAS%0ANRAS%0AEGFR/acc_tcga%2Cchol_nccs_2013%2Cchol_nus_2012

**Comment by jjgao** [comment]
@JiaoJiao123 could you help on this soon?

**Comment by JiaoJiao123** [comment]
sure, I will look into that today

**Comment by JiaoJiao123** [comment]
http://dashi-dev.cbio.mskcc.org:8080/crossCancerToolTip_cbioportal//cross_cancer.do?cancer_study_list=&cancer_study_id=all&data_priority=0&case_ids=&gene_set_choice=user-defined-list&gene_list=KRAS%0D%0ANRAS%0D%0AEGFR&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit#crosscancer/overview/0/KRAS%0ANRAS%0AEGFR/acc_tcga%2Cchol_nccs_2013%2Cchol_nus_2012
