### ISSUE TITLE
Virtual-study json: add base url

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3813]
It may be necessary to add the base url into the virtual study json format so that we know which portal instance the virtual study was created in. 

One issue we try to solve is that a user may have access to multiple portal instances. When we load the list of virtual studies in the query page, only the ones created in the same portal instance should be displayed.

But if a user has a virtual study ID, she should also be able to load it up in the study view on any instance that connects to the same session service.

Here is an example:

I created two virtual studies on cbioportal.org (VS_1, VS_2), and one session on cbioportal.org/beta/ (VS_3_BETA). 

When I load up cbioportal.org, only VS_1, VS_2 should be listed in query page. And only VS_3_BETA should be listed on my beta portal.

But I should also be able to load www.cbioportal.org/beta/study?id=VS_1 or www.cbioportal.org/study?id=VS_3_BETA.

Note: there is also a discussion about improving session service, which may be relevant here too.

**Comment by zhx828** [comment]
@jjgao we currently have a field in the session called `source` which is served as similar purpose. But I thought originally you want to show all VS under same domain? If you create VS under cbioportal.org/beta, you can visualize that in cbioportal.org, but not cbioportal.mskcc.org

**Comment by jjgao** [comment]
@zhx828 source would be good enough. I only want to see the list of virtual studies created in the same instance. Are we doing that?

**Comment by zhx828** [comment]
Yes, we are doing that now. @karthik please comment if I’m Wong

**Comment by jjgao** [comment]
Ok. I am closing this as long as we are querying vitual study by both user email / id and source.
