### ISSUE TITLE
missing hotspot annotation for non-oncokb genes

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3815]
Because we are now pulling cancer hotspots info from OncoKB (see https://github.com/cBioPortal/cbioportal/issues/3772) and OncoKB API only returns results for OncoKB genes, we are missing annotation for genes that are in cancerhotspot.org but not included in OncoKB.

The proposed solution will be to use the genomenexus cancerhotspots endpoint.

**Comment by onursumer** [comment]
We can switch to genome nexus API after finalizing this PR: https://github.com/genome-nexus/genome-nexus/pull/134

**Comment by onursumer** [comment]
With https://github.com/cBioPortal/cbioportal-frontend/pull/980/, mutations tab is no longer depending on the Cancer Hotspots web service. But we still need to update Oncoprint to use Genome Nexus data instead of OncoKB data.
