### ISSUE TITLE
Select Patient/Case Set doesn't change when changing Molecular profile when Modifying Query

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#3818]
![11](https://user-images.githubusercontent.com/12956870/35464666-209cae24-02c5-11e8-8132-2483dae36ac2.gif)

**Comment by jjgao** [comment]
This is not an easy one. The user may have selected a case list on purpose for the current session. Not sure if it's a good idea to switch all the time. Maybe we can address this once we have dynamic case list.
