### ISSUE TITLE
Loading Indicator Enrichments Tab

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3820]
the Enrichments tab is missing an indicator that it is loading data … for big cohorts, it looks like it does not load at all

**Comment by jjgao** [comment]
Let's make sure this is fixed in the new Enrichments tab.

**Comment by alisman** [comment]
@jjgao assuming @ersinciftci has addressed this in refactored feature, can we just wait (i.e. close this issue).

**Comment by jjgao** [comment]
@alisman Let's wait for @ersinciftci's new tab, but we should keep it open until we verify it's addressed.
