### ISSUE TITLE
study summary mutation frequency doesn't reset after clearing filters

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3825]
Watch the frequency for mutations below - they don't reset after clearing the filter.

![jan-29-2018 17-46-56](https://user-images.githubusercontent.com/10508276/35538607-7d6bd7de-051c-11e8-9e1a-f1ca780fbf59.gif)

**Comment by kalletlak** [comment]
I think this issues is still there for studies having gene panel data. https://github.com/cBioPortal/cbioportal/issues/2063
