### ISSUE TITLE
Lollipop plot not rendering for NSD3

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3827]
Lollipop plot not rendering for NSD3 - example:
http://bit.ly/2Eo0oSD

**Comment by schultzn** [comment]
![image](https://user-images.githubusercontent.com/11892704/35589801-fb8eb24c-05d2-11e8-9665-0994b9068344.png)

I think the gene symbol changed recently... related?

**Comment by inodb** [comment]
fixed n deployed
