### ISSUE TITLE
mutations tab fails to load when 3d hotspots API isn't reponsive

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3830]
As we did with OncoPrint, we should use a timeout to load the page even when 3D hotspots isn't responding.

**Comment by jjgao** [comment]
@onursumer since 3dhotspots.org is also unstable right now. Maybe it's a good idea to serve the data through GenomeNexus too?

**Comment by onursumer** [comment]
@jjgao Serving 3D hotstpos data through genome nexus sounds like a good idea to me. 

On the other hand, maybe hotspot data shouldn't block the initial loading of the mutation tab at all.

**Comment by jjgao** [comment]
@onursumer agreed.

**Comment by onursumer** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/980/ addresses this issue
