### ISSUE TITLE
mutation assessor predictions don't load

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3831]
Reported by a user: https://groups.google.com/forum/#!topic/cbioportal/FpJxZtuG_Ic

In the functional impact column, the mutation assessor column is always blank:

![image](https://user-images.githubusercontent.com/10508276/35631839-fc29c6e2-0672-11e8-884d-f8d407f48ba5.png)
http://www.cbioportal.org/index.do?session_id=5a1eef06498eb8b3d560f502&show_samples=false&

**Comment by jjgao** [comment]
MA server is down.

**Comment by jjgao** [comment]
@inodb let's remove MA column soon and get it back once it's back online.
