### ISSUE TITLE
Adding incorrect gene breaks Query button in Study Summary

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3835]
I noticed a bug that makes breaks the Query button in the Study Summary. Only refreshing the page restores the functionality.

How to reproduce:
- Go to the Study View (for example, MSK-IMPACT)
- Type `TP53 TRET` in gene box and try to click "Query". TRET is an unexisting symbol.
- The UI will say correctly state `Symbol not found - TRET` and blocks the Query button.
- Click the gene box, manually correct `TRET` to `TERT`.
- The Query button is still blocked.

Tested in 1.11.1 and 1.10.2 with Safari.

**Comment by jjgao** [comment]
In the long run, I think the study page should really use the same gene query component that the query page is using.
