### ISSUE TITLE
Query Panel Lacks Filtering by Assay Type

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3836]
@DarioS commented on [Thu Feb 01 2018](https://github.com/cBioPortal/cbioportal-frontend/issues/950)

The query panel shows a list of 170 studies, but it's not easy to quickly discover which datasets have, for example, RNA-seq data available. I suppose that biologists would choose a dataset based on tissue of origin, but if a machine learning user visits the website looking for some RNA-seq data to test a new statistical method on, they can't do it easily. The data portal of Genomic Data Commons provides such query flexibility.

**Comment by DarioS** [comment]
This still holds true today.
