### ISSUE TITLE
oncoprint genetic alteration legend tweak

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3837]
It looks like alterations are listed in the legend in alphabetical order. Can we instead sort by alteration type and then alphabetically within that? Start with all the mutations (Inframe, Missense, etc), then copy number changes (Amplification, Deep Deletion, Gain, Shallow Deletion), then mRNA down/up, then protein down/up, and then last would be "No alterations"

![image](https://user-images.githubusercontent.com/10508276/35687585-21a3a792-073d-11e8-87e3-6f79833dafdb.png)

Thoughts @schultzn @jjgao @ecerami ?

**Comment by schultzn** [comment]
Good idea. Maybe even sort within copy number by direction, i.e. amp, gain, deep del, shallow del.

**Comment by jjgao** [comment]
@adamabeshouse I think this was introduced when fixing order for clinical tracks. For genetic alteration, please sort per type.
