### ISSUE TITLE
multistudy OQL allows PROT but not EXP

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3838]
If I'm doing a multi-study query and I try to use OQL with EXP, then a warning appears and I can't submit the query:
![image](https://user-images.githubusercontent.com/10508276/35688069-556b7950-073e-11e8-8713-95136bf55fe7.png)

However, if I have an OQL statement including PROT, there is no warning and I am allowed to submit the query:
![image](https://user-images.githubusercontent.com/10508276/35688087-5c694d22-073e-11e8-86da-9a84e040a8e1.png)

We need the same behavior for PROT as we have for EXP.

**Comment by jjgao** [comment]
Good catch. PROT should not be allowed.
