### ISSUE TITLE
Query for mRNA and RPPA data not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#384]
http://bit.ly/1GzjwvV

![image](https://cloud.githubusercontent.com/assets/840895/10832005/1118f990-7e5f-11e5-8a86-347db596d3e5.png)

![image](https://cloud.githubusercontent.com/assets/840895/10831975/fbe0b770-7e5e-11e5-838d-cf3d50ad80c9.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/387
