### ISSUE TITLE
Use the oncoprint add clinical attribute component in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3852]
Some additional charts such as survival, "has mutation data", etc need to added to the list. 

![image](https://user-images.githubusercontent.com/840895/35881039-81dd88a8-0b4d-11e8-8230-4050d3689b9c.png)

cc'ing @pieterlukasse

**Comment by jjgao** [comment]
Let's do it in the new study view.

**Comment by kalletlak** [comment]
New study view is now using this component
