### ISSUE TITLE
 Improving clinical attribute selector by using data availability in samples

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3854]
Improving the functionality of clinical attribute selection by adding the percentage of samples with data in the attribute. 

This end point will be useful: https://github.com/cBioPortal/cbioportal/pull/3354

![image](https://user-images.githubusercontent.com/840895/35881039-81dd88a8-0b4d-11e8-8230-4050d3689b9c.png)

The list of attributes and their availability should be pulled from API once the user clicks on the dropdown #3602.

It should be used in both OncoKB and Study view https://github.com/cBioPortal/cbioportal/issues/3852.

**Comment by jjgao** [comment]
cc'ing @schultzn.

**Comment by pieterlukasse** [comment]
would be nice if the attribute can be disabled in drop-down list if it is not present in any sample (so 0%).

**Comment by jjgao** [comment]
@adamabeshouse could you comment on the status of this?

**Comment by adamabeshouse** [comment]
@jjgao It's awaiting review
