### ISSUE TITLE
OQL not working for fusion

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#386]
e.g. http://bit.ly/1OiTAqV

**Comment by ritikakundra** [comment]
It works if you change query to ERG: MUT FUSION;
On Nov 2, 2015, at 11:18 AM, JianJiong Gao <notifications@github.com<mailto:notifications@github.com>> wrote:


e.g. http://bit.ly/1OiTAqV

—
Reply to this email directly or view it on GitHub<https://github.com/cBioPortal/cbioportal/issues/386>.


=====================================================================

     Please note that this e-mail and any files transmitted from
     Memorial Sloan Kettering Cancer Center may be privileged, confidential,
     and protected from disclosure under applicable law. If the reader of
     this message is not the intended recipient, or an employee or agent
     responsible for delivering this message to the intended recipient,
     you are hereby notified that any reading, dissemination, distribution,
     copying, or other use of this communication or any of its attachments
     is strictly prohibited.  If you have received this communication in
     error, please notify the sender immediately by replying to this message
     and deleting this message, any attachments, and all copies and backups
     from your computer.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/387
