### ISSUE TITLE
Unselected study shows up in Cancer Type Summary tab of cross-cancer query

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3864]
In this query, the MBL SickKids study shows up in the cancer types summary tab, although the study is not selected in the query:
http://www.cbioportal.org/index.do?session_id=5a7dc6c6498eb8b3d564b640

It does not look like the mutations or samples show up in the OncoPrint though, nor in the Mutations tab.

**Comment by schultzn** [comment]
https://groups.google.com/forum/#!topic/cbioportal/1z-JHLcXv5g

**Comment by alisman** [comment]
@schultzn @ritikakundra  looks like this study (brca_igr_2015) has the wrong shortName property in db:
http://www.cbioportal.org/api/studies/brca_igr_2015

**Comment by schultzn** [comment]
@ritikakundra Is this an easy fix?

**Comment by ritikakundra** [comment]
@schultzn Yes, this should be quick to fix. Will schedule it for tonight.

**Comment by schultzn** [comment]
Is there an update on this? The MBL study still shows up in that query. Thanks.
