### ISSUE TITLE
Support multi-study query: Get Significantly Mutated Genes

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3865]
**METHOD**
POST

**Request**
```
[{
  "studyId": "",
  "sampleId": ""
}]
```

**Response:**
```
[{
    "entrezGeneId": 0,
    "hugoGeneSymbol": "string",
    "numberOfMutations": 0,
    "qValue":,
    "relatedSamples": [{
    	"studyId": "",
   	 "sampleId": "”
    }]
}]
```

The new concept introduced here `relatedSamples` is the list of samples(total number should match with `numberOfMutations`) that mutated with this gene in the request samples.

**Comment by ersinciftci** [comment]
Not needed in the new study view
