### ISSUE TITLE
Support multi-study query: Get Significant Copy Number Alteration 

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3867]
**METHOD**
POST

**Request**
```
[{
  "studyId": "",
  "sampleId": ""
}]
```

**Response:**
```
[{
  "cytoband": "",
  "genes": [
      {
        "entrezGeneId": 0,
        "hugoGeneSymbol": "string"
      }
    ]
  “qValue”: ””,
  “amp”: true
  "relatedSamples": [{
    	"studyId": "",
   	 "sampleId": "”
    }]
}]

```

The new concept introduced here `relatedSamples` is the list of samples(total number should match with `numberOfMutations`) that mutated with this gene in the request samples.

**Comment by ersinciftci** [comment]
Not needed in the new study view

**Comment by ersinciftci** [comment]
Actually we will probably need this for the Copy Number Alterations tab in Study View

**Comment by ersinciftci** [comment]
it seems Mutated Genes and Copy Number Alterations tabs is not visible when multiple study selected in study view, I didn't realize that, so no need to add multi-study support to Gistic API for now
