### ISSUE TITLE
Authorization buttons do not always appear in the Google Chrome browser

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#3878]
![image](https://user-images.githubusercontent.com/636232/36126733-cf107750-1027-11e8-86a2-fd2e7c0bd654.png)

**Comment by jjgao** [comment]
@adamabeshouse I couldn't reproduce it...

**Comment by adamabeshouse** [comment]
I reproduce it 100% of the time in chrome :/ what other details about my environment are relevant for debugging this?

**Comment by jjgao** [comment]
@adamabeshouse any js errors?

**Comment by adamabeshouse** [comment]
no, and also no failures in network tab

**Comment by adamabeshouse** [comment]
Some experimentation has showed me that the issue seems to be the "+" sign in the image alt "Google+"

**Comment by jjgao** [comment]
@adamabeshouse is it possible that you have some plugin that interferes with the button? Do you see this happen in other websites with Google log-in?

**Comment by adamabeshouse** [comment]
bingo! it's blocked by the ad block plus plugin. :) 

maybe we can just change the alt name to get around it - like "cBioPortal Google+" or something?

**Comment by jjgao** [comment]
@adamabeshouse could you give it a try?

**Comment by adamabeshouse** [comment]
@jjgao @n1zea144 please see attached PR
