### ISSUE TITLE
enrichments tab: rna & protein tabs don't have "direction/tendency" column

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3881]
For mutations, there is a log ratio column (reflecting the x-axis of the plot on the left), the value of which defines the content of the Direction/Tendency column in the table:
![image](https://user-images.githubusercontent.com/10508276/36172608-66e2768a-10d4-11e8-8b94-3cd5966b9f4e.png)

However, the mRNA & Protein tabs don't include this information in the table. The x-axis of the plot on the left is still a log ratio, but the log ratio doesn't appear in the table and there is no Direction/Tendency column either. 
![image](https://user-images.githubusercontent.com/10508276/36172649-8998eaa6-10d4-11e8-9838-8fc559a33ec2.png)

@jjgao is this intentional? The Direction/Tendency column functions like a summary of all the information, providing the co-occurence/mutual exclusivity summary along with a significance icon if applicable. It seems to me that this same information would be useful for mRNA/Protein, as a place to define if the gene is over/under expressed in the altered sample set along with whether it is significant.

**Comment by tmazor** [comment]
Ok, I just figured out that the green/red arrows in the p/q-value columns indicate if the gene is over/under-expressed in the altered group and that the p/q-values are bolded if significant. So the information is there, but it's not as clear as how that same information is displayed on the mutations/copy number tabs.

I still think we need to add a Direction/Tendency column for clarity & consistency with the other tabs.

**Comment by jjgao** [comment]
@tmazor good idea to add `Direction/Tendency` column.
