### ISSUE TITLE
Some dup variants in the portal are not called hotspot

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3883]
The issue happens for duplication. In the case below, the AKT1 P68_C77dup is annotated in the portal happens on location 78(both proteinStart and proteinEnd are 78). But the cancer hotspot predicts the range 65-77 as a hotspot. According to JJ, the location depends on the caller. It could be 78 or 65. When annotating the variant, cancer hotspot should use both locations to determine whether the variant is a hotspot.

http://www.cbioportal.org/case.do#/patient?sampleId=P-0007009-T01-IM5&studyId=msk_impact_2017

**Comment by jjgao** [comment]
@onursumer Any update on this?

**Comment by onursumer** [comment]
@jjgao If I understood correctly, we need to handle the case differently in genome nexus when the protein change has `dup` keyword in it, and keep the current logic intact for the remaining cases. Is that right?

**Comment by jjgao** [comment]
@onursumer that's correct. @zhx828 do you have the logic implemented in oncokb already?

**Comment by zhx828** [comment]
@jjgao actually oncokb does not have the dup logic. When we see a dup variant coming to the endpoint, we do not use proteinStart and proteinEnd from the input. We annotate the variant on our own which will solve the issue automatically.

**Comment by jjgao** [comment]
@zhx828 could you paste the api call to oncokb? and the one to genome-nexus?

**Comment by onursumer** [comment]
Apparently this issue has already been reported: https://github.com/genome-nexus/genome-nexus/issues/126

**Comment by inodb** [comment]
Fixed in 1.12: http://www.cbioportal.org/beta/case.do#/patient?sampleId=P-0007009-T01-IM5&studyId=msk_impact_2017 by @onursumer
