### ISSUE TITLE
datasets page - add "x" to clear out search box

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3887]
The search box on the Data Sets page should have an "x" to clear the contents of the search box, like what we have for searching datasets in the query tool on the homepage

![image](https://user-images.githubusercontent.com/10508276/36263964-773eedd6-1239-11e8-99d2-441ecb34b384.png)

![image](https://user-images.githubusercontent.com/10508276/36263981-804be802-1239-11e8-8a19-8f87a424bb3d.png)

**Comment by jjgao** [comment]
This should be implemented in the table component we are using - lazy-mobex table

**Comment by tmazor** [comment]
We should still do this

**Comment by alisman** [comment]
@dippindots i think you should use react-select to accomplish this.
