### ISSUE TITLE
some datasets are missing references

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3888]
There are a bunch of studies that sound like they relate to a publication (everything in the list below that isn't a TCGA Provisional study), but don't have a listed reference:

![image](https://user-images.githubusercontent.com/10508276/36264420-ae5c7d3c-123a-11e8-92c8-3009c07a0986.png)

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #168](https://github.com/cBioPortal/datahub/issues/168) via [**ZenHub**](https://www.zenhub.com/)
