### ISSUE TITLE
remove Mutation Counts vs CNA chart when there is no Mutation/CNA data

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3889]
When a study doesn't have Mutation or CNA data, the Mutation Count vs CNA chart is still an option to show on Study View. If you add it, it appears as a completely empty box:
![image](https://user-images.githubusercontent.com/10508276/36264667-53c45ab0-123b-11e8-9a3d-5aff3d3a1622.png)

I think we should remove this chart for any study that doesn't have BOTH mutation & CNA data. Or, if there are reasons I'm not thinking of to keep the plot, then we need to add text that says "Study doesn't have [mutation/CNA] data so graph cannot be generated." rather than showing a completely empty box.

no mutations: http://www.cbioportal.org/study?id=prad_mskcc_2014#summary
no CNA: http://www.cbioportal.org/staging/study?id=lgg_ucsf_2014#summary

@schultzn @jjgao @ecerami can we drop this chart as an option for studies that don't have both mutation & CNA data?

**Comment by jjgao** [comment]
This seems to be fixed. @zhx828 could you link the pr and close it?
