### ISSUE TITLE
Not working if I don't select any studies for query

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#389]
Previously, it'll automatically send all studies for query.

![image](https://cloud.githubusercontent.com/assets/840895/10924505/26bf737e-8255-11e5-9d47-3640b1377fbc.png)

**Comment by jjgao** [comment]
http://www.cbioportal.org/beta/index.do?cancer_study_list=&cancer_study_id=all&data_priority=0&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TP53&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit

**Comment by adamabeshouse** [comment]
@zheins could you look into this? I think this was working before, maybe related to your jstree or query form changes?
