### ISSUE TITLE
mutex tab resets to fewer rows than it started with

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3890]
I expect a reset button to return to the state of the page when it first loaded. On MutEx, the page first loads with 50 rows, but when I hit reset, it shows only 10.

on loading:
![image](https://user-images.githubusercontent.com/10508276/36265632-a510b268-123d-11e8-8d43-b9e70de51582.png)

after reset:
![image](https://user-images.githubusercontent.com/10508276/36265648-aa580280-123d-11e8-994d-e1fa0cc5cd78.png)

http://www.cbioportal.org/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=ADAM10%2520ADAM17%2520APH1A%2520APH1B%2520ARRDC1%2520CIR1%2520CTBP1%2520CTBP2%2520CUL1%2520DLL1%2520DLL3%2520DLL4%2520DTX1%2520DTX2%2520DTX3%2520DTX3L%2520DTX4%2520EP300%2520FBXW7%2520HDAC1%2520HDAC2%2520HES1%2520HES5%2520HEYL%2520ITCH%2520JAG1%2520JAG2%2520KDM5A%2520LFNG%2520MAML1%2520MAML2%2520MAML3%2520MFNG%2520NCOR2%2520NCSTN%2520NOTCH1%2520NOTCH2%2520NOTCH3%2520NOTCH4%2520NRARP%2520NUMB%2520NUMBL%2520PSEN1%2520PSEN2%2520PSENEN%2520RBPJ%2520RBPJL%2520RFNG%2520SNW1%2520SPEN%2520HES2%2520HES4%2520HES7%2520HEY1%2520HEY2&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

**Comment by adamabeshouse** [comment]
I discussed this with @ersinciftci recently, the conclusion is that its an API issue for the LazyMobXTable.

I guess a solution would be: if initialItemsPerPage is specified, and the show more button is set to show, and no itemsPerPageOptions specified, then we should default itemsPerPageOptions to just be [initialItemsPerPage], which would solve this.
