### ISSUE TITLE
plots tab - lock gene shades out gene selector on safari but not chrome

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3891]
In Safari, when Lock Gene is selected, the gene selector is nicely shaded out:
![image](https://user-images.githubusercontent.com/10508276/36266006-83ac9762-123e-11e8-9b74-b4678f08e183.png)

But on Chrome, the gene selector isn't shaded, making it look like it can be clicked even though it can't be:
![image](https://user-images.githubusercontent.com/10508276/36266046-98b6be9e-123e-11e8-93a0-10a997af66b6.png)

**Comment by adamabeshouse** [comment]
I think the new UI will make this problem obsolete - both axes will have a "lock gene" button, and it wont prevent changes, it will just make the other axis always receive the same change
