### ISSUE TITLE
plots tab - weird response to color by copy number

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3892]
On the plots tab, if I view data colored by mutation types, everything looks normal:
![image](https://user-images.githubusercontent.com/10508276/36266192-e848934c-123e-11e8-9f33-39a522e1555e.png)

But if I change to view by copy-number, then the coloring isn't successful and I get a long list of unlabeled black dots in the legend:
![image](https://user-images.githubusercontent.com/10508276/36266220-fb7ee484-123e-11e8-8b3c-652727034b17.png)

http://www.cbioportal.org/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=ADAM10%2520ADAM17%2520APH1A%2520APH1B%2520ARRDC1%2520CIR1%2520CTBP1%2520CTBP2%2520CUL1%2520DLL1%2520DLL3%2520DLL4%2520DTX1%2520DTX2%2520DTX3%2520DTX3L%2520DTX4%2520EP300%2520FBXW7%2520HDAC1%2520HDAC2%2520HES1%2520HES5%2520HEYL%2520ITCH%2520JAG1%2520JAG2%2520KDM5A%2520LFNG%2520MAML1%2520MAML2%2520MAML3%2520MFNG%2520NCOR2%2520NCSTN%2520NOTCH1%2520NOTCH2%2520NOTCH3%2520NOTCH4%2520NRARP%2520NUMB%2520NUMBL%2520PSEN1%2520PSEN2%2520PSENEN%2520RBPJ%2520RBPJL%2520RFNG%2520SNW1%2520SPEN%2520HES2%2520HES4%2520HES7%2520HEY1%2520HEY2&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

**Comment by adamabeshouse** [comment]
Im going to label this wontfix since we're going to refactor the plots tab completely anyway

**Comment by adamabeshouse** [comment]
theres no chance this issue will still be there in new code, closing issue no need to check up on it in refactoring
