### ISSUE TITLE
In Safari, OncoPrint data downloaded to filename "unknown.dms" 

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3898]
While Chrome downloads tabular data from OncoPrint correctly as `PATIENT_DATA_oncoprint.tsv`, Safari (11.0.3) downloads the file as `unknown.dms`. The contents of the file are fine. This also occurs when downloading PDF, SVG, Patient Order and PNG.

Similar to https://apple.stackexchange.com/questions/303200/safari-downloads-files-via-ftp-as-unknown-dms (no solution).

**Comment by sandertan** [comment]
Currently, I can't download at all from OncoPrint when using Safari http://www.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=acc_tcga&case_set_id=acc_tcga_cnaseq&data_priority=0&gene_list=TP53&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=acc_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&tab_index=tab_visualize

Also, the PDF download doesn't work in Chrome. @jjgao

**Comment by adamabeshouse** [comment]
@sandertan I'm no longer the `unknown.dms` issue, maybe since updating my OS to 10.12.6. Are you still seeing it?

Here's a PR for the pdf download issue https://github.com/cBioPortal/cbioportal-frontend/pull/2211

**Comment by Sjoerd-van-Hagen** [comment]
@adamabeshouse Fedde could not reproduce the issue so I think this is fixed.
