### ISSUE TITLE
"Request-URI Too Large" when querying all studies

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#390]
I thought the cancer studies ids were after the hash symbol?

![image](https://cloud.githubusercontent.com/assets/840895/10924583/98ce1222-8255-11e5-9e99-af64b723484b.png)

**Comment by adamabeshouse** [comment]
they are; something must have changed

**Comment by jjgao** [comment]
Looks like the cross cancer query also goes to index.do now.

**Comment by adamabeshouse** [comment]
@zheins could your changes be behind this?
