### ISSUE TITLE
staging: mutations tab fails to load

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3900]
Go here:
http://www.cbioportal.org/staging/index.do?session_id=5a61ffea498eb8b3d563de36&show_samples=false&

Go to the mutations tab. PIK3CA & PTEN load fine. IGF2 won't load.
![image](https://user-images.githubusercontent.com/10508276/36446851-8feefda6-1650-11e8-8764-37f5195248e8.png)

I think this fails because IGF2 has no mutations.

**Comment by inodb** [comment]
@tmazor seems to be fixed now

**Comment by tmazor** [comment]
agreed - looks good to me
