### ISSUE TITLE
survival tab: make "no data" text smaller and more informative

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3902]
The "no data available" text on the Survival tab is much larger than equivalent text on other tabs
![image](https://user-images.githubusercontent.com/10508276/36447680-0e7203ec-1653-11e8-9a34-03c3dd7e0e9d.png)

![image](https://user-images.githubusercontent.com/10508276/36447689-15db25be-1653-11e8-85c0-7fec51cc0b01.png)

More importantly, the text should explain why the plots aren't available.
If there are no patients in the "altered" group, say: No patients have an alteration in the queried gene(s), therefore comparative survival analysis cannot be performed.
If there are no patients in the "unaltered" group, say: All patients have an alteration in the queried gene(s), therefore comparative survival analysis cannot be performed.
If there is no OS data, say: Survival data is not available for this study.

Example query where all patients have alteration:
http://www.cbioportal.org/index.do?cancer_study_id=lgg_ucsf_2014&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=lgg_ucsf_2014_sequenced&gene_list=IDH1&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_ucsf_2014_mutations

Example query where no patients have alteration:
http://www.cbioportal.org/index.do?cancer_study_id=lgg_ucsf_2014&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=lgg_ucsf_2014_sequenced&gene_list=FUBP1&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_ucsf_2014_mutations

Example query in study without survival data:
http://www.cbioportal.org/index.do?session_id=5a8c8705498eb8b3d564d8c6

**Comment by jjgao** [comment]
Should we just hide the tab if the corresponding analysis cannot be performed?

**Comment by tmazor** [comment]
I think it depends on why we can't perform the analysis. If there is no outcome data for a study, then I'm find with hiding the tab. But if the analysis can't be performed because all or none of the patients have an alteration, then I think we should still show the tab with an explanation.

**Comment by jjgao** [comment]
@tmazor good point.

@ersinciftci could you make the changes as @tmazor suggested?

**Comment by ersinciftci** [comment]
@jjgao @tmazor hiding the tab is tricky for survival until we have the single page application, because the tabs themselves are still part of the JSP, but JSP doesn't know if the study has survival data or not. It was easy for mutex because JSP knows the queried genes.

**Comment by jjgao** [comment]
looks like it's fixed.
