### ISSUE TITLE
OQL doesn't complain if appropriate data type isn't selected under genomic profiles

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3903]
OQL with EXP complains if expression isn't selected in molecular profiles. This is a good thing.
![image](https://user-images.githubusercontent.com/10508276/36448412-91231a22-1655-11e8-89ac-c7909b7e35d4.png)

However, no other data type acts like this. All of the scenarios below should similarly provide a warning and prevent the user from submitting the query:
![image](https://user-images.githubusercontent.com/10508276/36448433-a0907004-1655-11e8-8980-4d6750790dad.png)

![image](https://user-images.githubusercontent.com/10508276/36448446-aa949ac6-1655-11e8-9868-2ae9cf345eca.png)

![image](https://user-images.githubusercontent.com/10508276/36448454-b3132582-1655-11e8-9d88-891587ba9354.png)

Also, that error for expression should say "Genomic Profile", not "Molecular Profile"

**Comment by alisman** [comment]
@jjgao @tmazor would it at all make sense to just shut off the profile selector as soon as we detect someone has typed qualifiers directly into the oql?  Just looking for a possible simplification

**Comment by adamabeshouse** [comment]
@alisman another idea: we could auto-select a profile in that case?

**Comment by alisman** [comment]
I mean, if these are alternative methods to do the same thing, maybe it's simpler to be exclusive about them.   It could avoid confusion to mix and match.   I would not expect that things I type into that box automatically toggle a selection up above.   On the other hand, maybe it's too much to expect them to type all qualifiers into the field?   Definately need product input on this.

**Comment by adamabeshouse** [comment]
the only issue with hiding it is there could be more than one option for mrna profile

**Comment by tmazor** [comment]
@alisman I don't think we can turn off the profile selector when a user starts typing OQL because a user could want to query genomic profiles that aren't explicitly called out -- for example, I could type
EGFR: AMP MUT
CDKN2A
That would only select mutation & copy number profiles. But I might want to also select mRNA and use the default OQL applied to CDKN2A. So I think we need to maintain user control of the profile selection.

We could consider auto-selecting a profile if OQL is added, but then we run into questions like @adamabeshouse pointed out, for example, which mRNA profile to select if there are multiple. And I agree, it's not the most intuitive to have some in the gene box change a setting above.

That said, I do agree that it would be great to simplify this process. I just don't happen to have a good idea for how to do it...
