### ISSUE TITLE
KMT2B shows up as N/S in oncoprint when queried with other genes

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3909]
Querying both KMT2B and KM2TD shows KMT2B as N/S
http://www.cbioportal.org/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=msk_impact_2017_cnaseq&gene_list=KMT2B%250AKMT2D&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna

Querying just KMT2B works fine:
http://www.cbioportal.org/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=msk_impact_2017_cnaseq&gene_list=KMT2B&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna

Some problem with aliases and gene panels as reported by @ritikakundra

**Comment by inodb** [comment]
@adamabeshouse do you have any clue?

**Comment by adamabeshouse** [comment]
weird.. I'll look into it

**Comment by inodb** [comment]
Thanks!

**Comment by adamabeshouse** [comment]
I'm not sure exactly what's going on but I see that it is in fact fixed in `rc`
