### ISSUE TITLE
In Downloads, show only gene names instead of OQL line by default

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#3911]
Suggestion from @schultzn :

Any more thoughts on the suggestion to remove the OQL details?

I don’t think most of our users will know what OQL Line means (as most of them don’t actually use OQL). It might be best to show OQL only when users actually used OQL, otherwise show gene symbols only?

**Comment by onursumer** [comment]
How about adding a separate (initially visible) gene symbol column, and hiding the OQL line column by default? In that case, downloaded file will include both columns though.

**Comment by jjgao** [comment]
@onursumer sounds good to me.

**Comment by onursumer** [comment]
addressed by an update in cBioPortal/cbioportal-frontend#923
