### ISSUE TITLE
OncoPrint: "sort by case list order" not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3921]
e.g. after check "sort by case list order", the sample order is different from the one in the query.

http://www.cbioportal.org/index.do?session_id=5a970249498eb8b3d564f999

**Comment by jjgao** [comment]
2 users reported this today. Please prioritize.

**Comment by schultzn** [comment]
@adamabeshouse Will this be fixed soon? A user just asked about it.

**Comment by ecerami** [comment]
FYI:  This was reported again last night by another user:  "OncoPrint",sort by case id and sort by case list order get the same result,I think you should fix it."

**Comment by adamabeshouse** [comment]
fix has been merged to master branches of both frontend and backend, should be deployed shortly

**Comment by adamabeshouse** [comment]
fixed
