### ISSUE TITLE
Oncoprint doesn't load

### ISSUE THREAD

**Issue by adefelicibus** [cBioPortal/cbioportal#3925]
Hi,

I've updated a local version of cbioportal from 1.7.3 to 1.11.4 and now Oncoprint doesn't load. I've got the error below:
![image](https://user-images.githubusercontent.com/5203073/36912888-f6f0ca10-1e26-11e8-8957-d478f995ec9f.png)

I've updated the code and migrated the database. 
Is there anything else to do?

Thanks

**Comment by adefelicibus** [comment]
@pieterlukasse Can you help me?

**Comment by jjgao** [comment]
@adefelicibus did you migrate you database too?

https://cbioportal.readthedocs.io/en/latest/Updating-your-cBioPortal-installation.html

**Comment by adefelicibus** [comment]
Hi @jjgao , Yes, I've migrated the database too.
I'm using cbioportal version 1.11.4 and db-schema 2.5.0. Also, after the update, I was able to upload a new study on cbiportal with no error about the db-schema.

**Comment by adefelicibus** [comment]
@pieterlukasse I dit it, but with no success. I've tried a different browser and also a new installation. I will try to use the docker image with a new database, maybe there is something wrong in my database.

**Comment by pieterlukasse** [comment]
@adefelicibus yes, that would be good. We recently updated our docker files to 1.11.3: https://github.com/thehyve/cbioportal-docker
