### ISSUE TITLE
After adding certain chart in study view, mutation counts all been set to NA

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3926]
Open study: http://www.cbioportal.org/study?id=acc_tcga#summary
Add chart `Specimen Freezing Means`
Then mutation count all set to NA

**Comment by kalletlak** [comment]
@zhx828 overriding group ndx data is removing special charts data
https://github.com/cBioPortal/iViz/blob/master/app/scripts/main.js#L160
