### ISSUE TITLE
Mutex tab does not recognize ; as separator for genes

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3928]
From user:

What happens is if I use the Pan-Lung dataset and type: "KRAS SPRED1" the mutual exclusivity button shows up.  However, if I type "KRAS;SPRED1" then the mutual exclusivity button does not show up.

http://www.cbioportal.org/index.do?session_id=5a9e1c07498eb8b3d5650f25

https://groups.google.com/d/msgid/cbioportal/9f682e93-45f8-40e3-95ac-2d1bbe9a6e0f%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by jjgao** [comment]
@ersinciftci why Mutex is different?

**Comment by ersinciftci** [comment]
@jjgao I think the logic that hides the Mutex tab is in 2 places, both in JSP and frontend, the one in the JSP might be parsing the genes itself since there is no store or anything. I'll check it.

**Comment by jjgao** [comment]
@ersinciftci I see. In that case, maybe we could remove the logic in jsp?

**Comment by ersinciftci** [comment]
@jjgao The tabs are still part of the JSP, so we need to keep the part in JSP for now. I guess the logic in the new frontend is just for tests. I found the problem in jsp:
`String[] geneList = URLDecoder.decode((String) request.getAttribute(QueryBuilder.GENE_LIST), "UTF-8").split("( )|(\\n)");`

So will fix it for now.
