### ISSUE TITLE
OQL test cases

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#393]
We need to write test cases to support OQL:

http://www.cbioportal.org/onco_query_lang_desc.jsp

**Comment by adamabeshouse** [comment]
I've already written some tests for OQL but it would definitely be good to have a more complete TDD-style testing framework to put things in.

**Comment by adamabeshouse** [comment]
OQL is tested, going to close this because a more general testing strategy doesn't need to focus on this in particular.
