### ISSUE TITLE
beta - cancer types summary - genes should be in order of query

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3934]
Genes are listed alphabetically but should be in the same order as the query

![image](https://user-images.githubusercontent.com/10508276/37123860-bd20cba8-2233-11e8-9991-9265baa63ce8.png)
http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=IDH1%2520TP53%2520EGFR%2520CDKN2A&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

**Comment by inodb** [comment]
deployed to beta
