### ISSUE TITLE
beta - cancer types summary - filters reset when x/y-axis settings change

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3936]
If I filter with by Min # Altered Cases or Min # Total Cases, and then change the x-axis sorting, the min # resets to 0. Changing the sorting shouldn't reset those filters:

![mar-07-2018 18-26-35](https://user-images.githubusercontent.com/10508276/37124171-245f5ce8-2235-11e8-92a8-5456c13938e9.gif)

Filters should also be retained for changing the Y axis value between Absolute Counts and Alteration Frequency

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/cbioportal/issues/3657
