### ISSUE TITLE
beta - cancer types summary - tooltip sometimes is too low

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3938]
If I hold my mouse over a relatively short bar, or over a low component of a stacked bar, then the tooltip shows up over the axis label rather than over the bar:

![image](https://user-images.githubusercontent.com/10508276/37124623-144a782c-2237-11e8-9e7e-7fd3df616558.png)

http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=IDH1%2520TP53%2520EGFR%2520CDKN2A&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

**Comment by inodb** [comment]
deployed to beta
