### ISSUE TITLE
[Beta] suggestions to cancer type summary

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3942]
From @schultzn:

In the cancer type summary tab, please change the x-axis sort option from “X-axis values” to “Alphabetically”.

![image](https://user-images.githubusercontent.com/840895/37159815-bea8f890-22bc-11e8-811e-fe03cc59588d.png)

Also, it may be better to swap min % altered cases and min # total cases, as users are more likely to modify the latter?

![image](https://user-images.githubusercontent.com/840895/37159840-ce24a102-22bc-11e8-8741-52fe927c9832.png)

**Comment by inodb** [comment]
deployed to beta
