### ISSUE TITLE
[beta] cancer type summary: SVG cannot be opened by AI 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3944]
From @schultzn : "in the Cancer Types Summary tab, I noticed that the SVG file can’t be loaded by Adobe Illustrator … see the error message I get below. "

![image](https://user-images.githubusercontent.com/840895/37160019-41ef98f8-22bd-11e8-8105-1dd046899b97.png)

**Comment by jjgao** [comment]
is it the same reason as https://github.com/cBioPortal/cbioportal/issues/1541 and #3225?

**Comment by schultzn** [comment]
I noticed that despite this error message the SVG actually loads… it would just be nice if that error message could disappear.

**Comment by alisman** [comment]
Seems like this is probably an issue with font of Victory chart's theme.  Only way to test this is to change it and see if problem persists.  I can do this when I'm in the office tomorrow.

**Comment by inodb** [comment]
deployed to beta
