### ISSUE TITLE
[beta] cancerhotspots ajax error

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3946]
When opening mutations tab: http://www.cbioportal.org/beta/index.do?session_id=5a982262498eb8b3d564fd89

![image](https://user-images.githubusercontent.com/840895/37161501-d906c5d8-22c0-11e8-8cbc-df2193652491.png)

![image](https://user-images.githubusercontent.com/840895/37161484-cdec0974-22c0-11e8-8d9f-6086bbace3fb.png)

**Comment by inodb** [comment]
Fixed. This was an old problem - proxy isn't working for genome nexus for whatever reason so need to use https
