### ISSUE TITLE
[beta] downloads tab - percent sign is cut off

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3948]
This is minor, but when 100% of sample have an alteration, the percent sign is cut off:
![image](https://user-images.githubusercontent.com/10508276/37163988-248a7b70-22c7-11e8-88ab-64b77b9d91ef.png)

http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_ucsf_2014&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_ucsf_2014_sequenced&gene_list=IDH1%2520TP53%2520ATRX%2520CIC&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_ucsf_2014_mutations&show_samples=false

**Comment by onursumer** [comment]
@tmazor I cannot reproduce this bug neither in Chrome nor Firefox. On what browser (and OS) does this happen?

**Comment by tmazor** [comment]
@onursumer I see it in Chrome (Version 64.0.3282.186 (Official Build) (64-bit)) and Safari (Version 11.0.3 (12604.5.6.1.1)) and Firefox (58.0.2 (64-bit)). I'm on Mac OS 10.12.6

**Comment by onursumer** [comment]
Tested on Windows with the latest Chrome, and Firefox. Same problem there, too. Looks like only on Ubuntu it works properly :)
