### ISSUE TITLE
Cancer Types Summary: Incorrect frequencies when sorting alphabetically

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3954]
Try this:
http://bit.ly/2F2iF7K

Then sort by x-axis...   all frequencies are wrong.

See this user report:
https://groups.google.com/forum/#!topic/cbioportal/wgq0bsJdCiA

Luckily, this seems to have been fixed during refactoring!

**Comment by alisman** [comment]
wow.  so, you tested the new one and it's ok?  i guess we should get it out.

**Comment by jjgao** [comment]
closing this since it's fixed in beta.
