### ISSUE TITLE
Can we show only the top mutated genes in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3955]
The Mutated Genes table currently shows cBioPortal cancer genes with 1 or more mutations, as well as any gene with 2 or more mutations. This has caused some confusion since not all mutated genes can be found in the table.

The question is whether it's useful to show so many genes. Can we show only the top, say 100, mutated genes? If not, what's the use cases to show less frequently mutated genes? 

Similarly to CNA Genes table -- which is worse b/c we only show cancer genes.

![image](https://user-images.githubusercontent.com/840895/37219208-c5203f74-2390-11e8-8f30-7cf97dc73c62.png)

**Comment by schultzn** [comment]
I really like the ability to search for specific genes in the table, even if they are low frequency... can we keep that somehow?

**Comment by jjgao** [comment]
@schultzn maybe we can have the complete list in the Mutated Genes tab? Or do you think it is important to support interactive analysis between low frequently mutated genes with other charts?

**Comment by schultzn** [comment]
I don’t really want to lose the functionality… I never go to the Mutated Genes tab.

Why are you trying to remove the low frequency genes? To save loading time or to make changes to the visualization?

Let’s discuss in person maybe?

**Comment by jjgao** [comment]
@schultzn the big problem is we are not showing all mutated genes, i.e. we are not showing a gene if it's only mutated once and is not a cancer gene. In the case of CNA genes, we only show cancer genes. There have a few users asking about the "discrepancy" between the Mutated Genes table and the results page.

Maybe we should just try to show all mutated genes and CNA genes. @zhx828 @ersinciftci maybe we can try to have some backend support for pagination and filtering?

**Comment by zhx828** [comment]
@jjgao the issue will be real-time filtering. It will have delay everytime user filters the table.

**Comment by ersinciftci** [comment]
The new study view APIs returns all mutated and CNA genes, so I'm closing this issue for now. We can re-open if we don't like the performance.

**Comment by schultzn** [comment]
It would still be nice to search for genes and retrieve the frequency of alterations.. maybe we can show only the top 10 at first, but then quickly compute the other frequencies when a user searches for genes?

**Comment by jjgao** [comment]
I like @schultzn's idea.

@ersinciftci @zhx828 How difficult is it to do pagination and query? For query, you may want to match genes that start with the user input once they have typed two characters.

**Comment by ersinciftci** [comment]
@jjgao do we need pagination? I can just add an optional filter parameter to the endpoint, if it's empty, return top 100 genes, if user enters a filter, return top 100 genes that matches with the filter?

**Comment by zhx828** [comment]
@ersinciftci we also need to support sorting. @jjgao  I need to discuss with Aaron how this can be done. Do we need to make sure when user scrolling the table? The table will fetch the data continuously?

**Comment by zhx828** [comment]
@jjgao just checked with the library. It would actually be easier than I thought. Let's discuss during the stand up meeting today.

**Comment by ersinciftci** [comment]
Seems like https://github.com/cBioPortal/cbioportal/pull/4773 fixed this performance problem, both tables load instantly now on cbioportal.org/rc.

**Comment by ersinciftci** [comment]
Seems like https://github.com/cBioPortal/cbioportal/pull/5322 solved this, http://www.cbioportal.org/beta/study?id=msk_impact_2017 both mutated and cna genes take around 2 seconds for single study queries and http://www.cbioportal.org/beta/study?id=acc_tcga%2Cmsk_impact_2017 around 5 seconds for multi-study. So closing the ticket.
