### ISSUE TITLE
Results page does not reflect changes to frontend OQL parser

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#3959]
When adjusting the OQL parser to support new syntaxes, the query page reflects this just fine. However, clicking the Submit button to open the results view parses the query again using a *different* OQL parser, outdated duplicate code fetched from `<cBioPortal root URI>/js/lib/oql/oql-parser.js?20180312-1513`.

**Comment by fedde-s** [comment]
@pieterlukasse, I believe I just heard you say that you'd want to look into this.

**Comment by fedde-s** [comment]
The parser was called by the `genes()` function in an outdated duplicate of `oqlfilter.js`, from a jQuery callback. Might  [`visualise.jsp`](https://github.com/cBioPortal/cbioportal/blob/debcdc50dfdf01afed86552245bc1d922b4a893a/portal/src/main/webapp/WEB-INF/jsp/visualize.jsp#L498) be the caller?

**Comment by jjgao** [comment]
@adamabeshouse could you comment?

**Comment by adamabeshouse** [comment]
@fedde-s I see the issue here. This will go away once we refactor the plots tab. If we want to fix it before then it will be pretty simple, we just need to expose the corresponding function to the window from the frontend application. What do you think we should do @alisman

**Comment by alisman** [comment]
@adamabeshouse, yes, lets expose it.    maybe we should just get rid of legacy parser to be sure it's gone.

**Comment by jjgao** [comment]
@alisman @adamabeshouse it's a good idea to remove the legacy parser code.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3963
https://github.com/cBioPortal/cbioportal-frontend/pull/1020

**Comment by adamabeshouse** [comment]
fixed in rc

**Comment by fedde-s** [comment]
I can confirm; I've rebased the commits that extend the OQL syntax, and they now go through to the results view 👍

**Comment by fedde-s** [comment]
@adamabeshouse, all tabs respect the new parser now, except for the Enrichments tab. Has that been missed, or is it waiting for refactoring?

**Comment by fedde-s** [comment]
Related to https://github.com/cBioPortal/cbioportal/issues/3986.

**Comment by fedde-s** [comment]
I see that it's being addressed in that issue already, will close this one again.
