### ISSUE TITLE
geneids null value JSP error

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3960]
Lots of these errors when `genesetIds` is null:
```
Mar 08, 2018 10:03:00 AM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet jsp threw exception
java.lang.NullPointerException
        at org.apache.jsp.WEB_002dINF.jsp.global.server_005fvars_jsp._jspService(server_005fvars_jsp.java:78)
```
All other values in `server_vars` are cast to string from getAttributes. This is not done for the `getParameter` from `geneSetIds`. Not sure if that's the error but possibly.

**Comment by fedde-s** [comment]
What view were you rendering when this occurred? A results view that didn't include a gene set score profile?

**Comment by jjgao** [comment]
@inodb @alisman how close are we to getting rid of the jsp pages?

**Comment by jjgao** [comment]
@inodb does this error have any effect on the page?

**Comment by inodb** [comment]
@fedde-s @jjgao i haven't been able to figure out yet when this error occurs, but i see it in the public tomcat logs at `11:44:23`

**Comment by fedde-s** [comment]
I haven't reproduced it either, but I imagine it might be a backwards incompatibility in the coupling between frontend and backend somewhere.

**Comment by jjgao** [comment]
I put it into icebox for now since we are going to get rid of the jsp pages.

**Comment by fedde-s** [comment]
Is anyone still running in to this at all? I'd made a note on my backlog, but haven't heard anyone complain about it for about five months now. Re-open or define a new issue if you do have more info.
