### ISSUE TITLE
1.12 study view: Loading mutation and CNA frequencies takes forever on first load

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3961]
This seems to be a new issue - the tables take a long time to load, and the progress bar is stuck at 100% for a while

![image](https://user-images.githubusercontent.com/11892704/37294254-cdde5666-25eb-11e8-8d19-a0124ad1c333.png)

**Comment by jjgao** [comment]
It seems that it happens only when the study is loaded for the first time? The subsequent loading seems very fast. Adding @zhx828 and @ersinciftci on this.

**Comment by zhx828** [comment]
@schultzn @jjgao this is not an issue. Both tables are waiting for gene panel API to response. The progress bar does not have that undercover. 
There are two steps here: 
- [ ] Adjust the progress bar to have gene panel. 
- [ ] Switch to new gene panel endpoint.

**Comment by zhx828** [comment]
This is not a new issue introduced in 1.12. It has been there for a while. I'm currently working on the fixes mentioned above, but it is not necessary to be introduced in 1.12. It could be a hotfix on 1.12.1.
