### ISSUE TITLE
Gene panel improvement: user reported

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#3965]
Gene panel coverage for samples which were not profiled defaults to WES. We want to add the functionality to display them as "Not sequenced".
https://groups.google.com/forum/#!topic/cbioportal/mTVmgGe9-hI

**Comment by jjgao** [comment]
For example, in this query, two samples don't have sequencing data:

http://bit.ly/2Drk467

![image](https://user-images.githubusercontent.com/840895/37411095-5f0b7e24-2778-11e8-9c36-d6635be355b5.png)

@ersinciftci do you know if you considered this in https://github.com/cBioPortal/cbioportal/pull/3793?

**Comment by adamabeshouse** [comment]
strange, it seems like the relevant changes (https://github.com/cBioPortal/cbioportal-frontend/blob/rc/src/pages/resultsView/ResultsViewPageStoreUtils.ts#L92) are not present in master... but we must have released since those changes were merged. @alisman @inodb  ?

**Comment by adamabeshouse** [comment]
This is either a data or API issue, because the data coming back says it's WXS
![image](https://user-images.githubusercontent.com/636232/38059783-d3ebbd2e-32b5-11e8-9bc9-7896ae3189fc.png)
@ersinciftci

**Comment by jjgao** [comment]
@ersinciftci please look into this. `TCGA-OR-A5LM` is not in the `_sequenced` sample list.

**Comment by inodb** [comment]
Fixed in master: http://cbioportal.herokuapp.com/index.do?cancer_study_id=acc_tcga&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=acc_tcga_all&gene_list=EGFR&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=acc_tcga_gistic

**Comment by inodb** [comment]
deployed to production

**Comment by inodb** [comment]
![screen shot 2018-04-03 at 3 00 44 pm](https://user-images.githubusercontent.com/1334004/38269900-d3efdbea-374f-11e8-8aeb-f6e780fb46a6.png)
