### ISSUE TITLE
withdrawn hugo symbol MIR-3676/3676 causes civic to return 404

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3967]
CIViC loads for the mutations, but not for copy number for this patient:
http://www.cbioportal.org/case.do#/patient?studyId=lgg_tcga&caseId=TCGA-DU-5853
![image](https://user-images.githubusercontent.com/10508276/37363241-cad8cacc-26cd-11e8-8dd8-b54fde883d0a.png)

I tried a few other patients from this study (selected at random) and they all load the CIViC annotation just fine, so I'm not sure what's happening with this one.

**Comment by inodb** [comment]
prolly one of the genes fails or the parameters are too long. will have a look

**Comment by inodb** [comment]
yes, so all these genes fail:
```
LSP1:failure
C11ORF21:failure
KCNQ1DN:failure
C11ORF40:failure
C11ORF42:failure
C11ORF16:failure
C11ORF58:failure
MIR-3676%2F3676:failure
SOX1-OT:failure
LINC00404:failure
```
That is any sample that has these mutations will return 404

**Comment by inodb** [comment]
I put a proposed solution here that we could implement on our end: https://github.com/griffithlab/civic-server/issues/420. Just verifying with civic what they think

**Comment by jjgao** [comment]
@pieterlukasse could you guys help with this one?

**Comment by inodb** [comment]
FYI @pieterlukasse @oplantalech they got back to me on the civic-server issue tracker: https://github.com/griffithlab/civic-server/issues/420

**Comment by inodb** [comment]
Ok - so issues is actually that one of the genes queried is this one: `MIR-3676%2F3676`

**Comment by inodb** [comment]
So I think this is actually a data issue - this seems to be an incorrect hugo symbol. There's only two copy number events that use this. The symbol was withdrawn: https://www.ncbi.nlm.nih.gov/gene/100500892. Should we just remove this copy number event from the data @jjgao @ritikakundra ?

**Comment by jjgao** [comment]
@inodb I am not sure if the error was due to that. Is the error due to the slash in the miRNA symbol?

BTW,  we have some special code for miRNA -- none of them are valid hugo symbols.

**Comment by inodb** [comment]
@jjgao yes

**Comment by inodb** [comment]
Ok so decided to not remove this, but instead hope that civic changes their endpoint to handle encoded `/` (see same issue griffithlab/civic-server#420)

**Comment by jjgao** [comment]
If they cannot do that. We should skip genes with special characters such as /.

**Comment by inodb** [comment]
seems like they won't - so yeah we might have to do that instead

**Comment by jjgao** [comment]
Entrez gene IDs would be better since they are more stable. We should filter out our fake negative entrez ID before sending to them.

**Comment by jjgao** [comment]
Let's query by entrez: civicdb.org/api/genes/673,7157?identifier_type=entrez_id

It's also good to use entrez anyway since civic and cbioportal may not be using the same version of symbols.
