### ISSUE TITLE
[beta] cancer types summary - change color for shallow deletion

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3968]
Can we use the same light blue color for Shallow Deletion here as on OncoPrint?

Cancer Types Summary uses black:
![image](https://user-images.githubusercontent.com/10508276/37363710-fcefc546-26ce-11e8-920e-e3148658491c.png)

OncoPrint uses light blue, which nicely coordinates with dark blue for Deep Deletion:
![image](https://user-images.githubusercontent.com/10508276/37363733-09fad596-26cf-11e8-9cbc-6d9bf0f07a2f.png)

**Comment by jjgao** [comment]
@ersinciftci an example: http://www.cbioportal.org/beta/index.do?session_id=5aaac300498eb8b3d56539ba

**Comment by tmazor** [comment]
Deep deletion on cancer types summary is now the same light blue as shallow deletion on oncoprint. Shallow deletion on cancer types summary is still black.

The colors on cancer types summary should be:
Shallow deletion = light blue
Deep deletion = dark blue

Current beta cancer types summary:
![image](https://user-images.githubusercontent.com/10508276/37616504-88a24dfa-2b86-11e8-969d-b4fddceb8edc.png)

Desired colors (from oncoprint):
![image](https://user-images.githubusercontent.com/10508276/37616492-7b1cfda6-2b86-11e8-9341-3ae5f5098418.png)
![image](https://user-images.githubusercontent.com/10508276/37616494-7f400b4e-2b86-11e8-97d7-eb223d77deee.png)

query: http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=EGFR%253A%2520AMP%2520GAIN%2520MUT%250ACDKN2A%253A%2520HETLOSS%2520HOMDEL%2520MUT%250AIDH1%253AMUT%253DR132C&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

**Comment by inodb** [comment]
seems to be fixed for real this time
