### ISSUE TITLE
[beta] Modify Query: js/api error

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3970]
When clicking Modify Query, there is a js error. The site seems working fine though.

![image](https://user-images.githubusercontent.com/840895/37404359-0367d9e2-2768-11e8-841c-51ebae2a0500.png)

![image](https://user-images.githubusercontent.com/840895/37404395-222b6c5e-2768-11e8-860e-53d3a9bf0c1f.png)

**Comment by ersinciftci** [comment]
It's Gene Sets API, so assigning to @pieterlukasse
