### ISSUE TITLE
3D structure view not working on mutations tab

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3976]
This seems to be an existing issue.. 3D structure button is always greyed out. 

![image](https://user-images.githubusercontent.com/11892704/37465333-3f790b3a-2831-11e8-917d-cb5c4bbf7d8e.png)

**Comment by inodb** [comment]
Thanks for reporting - looks like ssl certificate of g2s expired 2 days ago

**Comment by jjgao** [comment]
Juexin fixed it. We will try to find a way to auto-renew the certificate.
