### ISSUE TITLE
can still get the to the crosscancer.do page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#3977]
See e.g.:

http://www.cbioportal.org/cross_cancer.do?gene_list=C2&Action=Submit&cancer_study_list=&cancer_study_id=all#crosscancer/overview/0/C2/all,paac_jhu_2014,all_stjude_2016,laml_tcga_pub,laml_tcga,acyc_fmi_2014,acyc_mda_2015,acyc_mskcc_2013,acyc_sanger_2013,acbc_mskcc_2015,acc_tcga,ampca_bcm_2016,blca_mskcc_solit_2014,blca_mskcc_solit_2012,blca_plasmacytoid_mskcc_2016,blca_bgi,blca_dfarber_mskcc_2014,blca_tcga_pub,blca_tcga,lgg_tcga,brca_metabric,brca_bccrc,brca_broad,brca_sanger,brca_tcga_pub2015,brca_tcga_pub,brca_tcga,brca_bccrc_xenograft_2014,cellline_ccle_broad,cesc_tcga,chol_nccs_2013,chol_nus_2012,chol_tcga,lcll_broad_2013,cll_iuopa_2015,ccrcc_utokyo_2013,coadread_dfci_2016,coadread_genentech,coadread_tcga_pub,coadread_tcga,coadread_mskcc,ctcl_columbia_2015,cscc_dfarber_2015,pact_jhu_2011,desm_broad_2015,dlbc_broad_2012,esca_broad,esca_tcga,escc_icgc,escc_ucla_2014,es_iocurie_2014,gbc_shanghai_2014,egc_tmucih_2015,nsclc_unito_2016,prad_cpcg_2017,gct_msk_2016,gbm_tcga_pub2013,gbm_tcga_pub,gbm_tcga,hnsc_broad,hnsc_jhu,hnsc_tcga_pub,hnsc_tcga,liad_inserm_fr_2014,hcc_inserm_fr_2015,all_stjude_2013,all_stjude_2015,panet_shanghai_2013,chol_jhu_2013,kich_tcga_pub,kich_tcga,kirc_bgi,kirc_tcga_pub,kirc_tcga,kirp_tcga,lihc_amc_prv,lihc_riken,lihc_tcga,lgg_ucsf_2014,luad_broad,luad_mskcc_2015,luad_tcga_pub,luad_tcga,luad_tsp,lusc_tcga_pub,lusc_tcga,dlbc_tcga,msk_impact_2017,lung_msk_2017,prad_mskcc_2017,mpnst_mskcc,plmeso_nyu_2015,mcl_idibips_2013,mbl_broad_2012,mbl_icgc,mbl_pcgp,mbl_sickkids_2016,skcm_broad_dfarber,lgggbm_tcga_pub,meso_tcga,prad_su2c_2015,mm_broad,ccrcc_irc_2014,brca_igr_2015,mds_tokyo_2011,cellline_nci60,odg_msk_2017,npc_nusingapore,nbl_amc_2012,nbl_ucologne_2015,nepc_wcm_2016,skcm_vanderbilt_mskcc_2015,hnsc_mdanderson_2013,ov_tcga_pub,ov_tcga,mel_tsam_liang_2017,nsclc_tcga_broad_2016,paad_icgc,paad_qcmg_uq_2016,paad_tcga,paad_utsw_2015,panet_jhu_2011,thca_tcga_pub,es_dfarber_broad_2014,pcpg_tcga,thyroid_mskcc_2016,pcnsl_mayo_2015,prad_broad_2013,prad_broad,prad_fhcrc,prad_mskcc,prad_tcga_pub,prad_tcga,prad_mskcc_2014,prad_mskcc_cheny1_organoids_2014,prad_mich,hnc_mskcc_2016,nccrcc_genentech_2014,rms_nih_2014,summit_2018,sarc_mskcc,sarc_tcga,skcm_broad,skcm_tcga,skcm_yale,scco_mskcc,sclc_clcgp,sclc_jhu,sclc_ucologne_2015,stad_pfizer_uhongkong,stad_tcga_pub,stad_tcga,stad_utokyo,stad_uhongkong,stes_tcga_pub,egc_msk_2017,urcc_mskcc_2016,crc_msk_2018,utuc_mskcc_2013,tgct_tcga,brca_mbcproject_wagle_2017,tet_nci_2014,thym_tcga,thca_tcga,ucs_jhu_2014,ucs_tcga,ucec_tcga_pub,ucec_tcga,uvm_tcga,panet_arcnet_2017,skcm_ucla_2016,past_dkfz_heidelberg_2013

Not sure if this is a feature or a bug. We should prolly rewrite the url if we want backwards compatibility

**Comment by jjgao** [comment]
If the parameters are compatible and it's simply a redirection, let's redirect the url. Otherwise, it's OK to drop the support for cross_cancer.do.

**Comment by jjgao** [comment]
From Google Analytics, there is still very little traffic to the page 457 visits (0.33%) last month, so I think it's ok to drop it.

**Comment by jjgao** [comment]
Let's drop the mapping.
