### ISSUE TITLE
ln?q=EGFR:MUT rediction

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3979]
http://cbioportal.org/ln?q=EGFR:MUT is still redirecting to cross_cancer.do? Please change it to index.do.

**Comment by alisman** [comment]
@inodb can you take this?

**Comment by jjgao** [comment]
I guess it has not been pushed out?

**Comment by inodb** [comment]
@jjgao this is live now - note that it does take quite a while before something appears on the page but hopefully that'll be solved once we switch to single page app
