### ISSUE TITLE
TERT promoter mutations are annotated as truncating in OncoPrints

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3982]
TERT promoter mutations should be shown with a separate color.

See this user report:
https://groups.google.com/forum/#!topic/cbioportal/_23sVHiEqXs

**Comment by adamabeshouse** [comment]
this is probably a data issue... i'll look into it

**Comment by adamabeshouse** [comment]
oops! big oversight.. fixing now

**Comment by adamabeshouse** [comment]
fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/1036

**Comment by schultzn** [comment]
Thank you!

**Comment by adamabeshouse** [comment]
fixed in master

**Comment by inodb** [comment]
@adamabeshouse fyi good to close this after deployment so we won't forget to email the user. Maybe we can automate this at some point

**Comment by adamabeshouse** [comment]
good point @inodb
