### ISSUE TITLE
[beta] oncoprint doesn't show if a gene is not sequenced

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3988]
Production:
![image](https://user-images.githubusercontent.com/10508276/37601240-e47d17b2-2b5f-11e8-829a-e3099964bdc9.png)
http://www.cbioportal.org/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=msk_impact_2017_all&gene_list=ALK%2520SOS1&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna

Beta:
![image](https://user-images.githubusercontent.com/10508276/37601247-ec1f3950-2b5f-11e8-8677-4020dff2d964.png)
http://www.cbioportal.org/beta/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=msk_impact_2017_all&gene_list=ALK%2520SOS1&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna

**Comment by adamabeshouse** [comment]
Fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/1045
