### ISSUE TITLE
[production] oncoprint doesn't show "not sequenced" if the only gene queried is not sequenced

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3990]
If I query SOS1 & another gene in MSK-IMPACT, then SOS1 correctly appears as not sequenced in all samples:
![image](https://user-images.githubusercontent.com/10508276/37601812-580d38c8-2b61-11e8-9e85-b721fd2a5512.png)

But if I query SOS1 alone, it shows up labeled as whole exome sequencing and 0% altered:
![image](https://user-images.githubusercontent.com/10508276/37601776-3ff602ec-2b61-11e8-98de-b20fe55d5901.png)

**Comment by adamabeshouse** [comment]
Fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/1045
