### ISSUE TITLE
truncated oncoprint expression legend

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3994]
http://www.cbioportal.org/beta/index.do?session_id=5a61ffea498eb8b3d563de36&show_samples=false&

![image](https://user-images.githubusercontent.com/840895/37616056-240ed594-2b85-11e8-8d60-3a63051ea9da.png)

**Comment by adamabeshouse** [comment]
Fixed by new oncoprint version https://github.com/cBioPortal/cbioportal-frontend/pull/1046
