### ISSUE TITLE
Using cbioportal.war

### ISSUE THREAD

**Issue by vingorius** [cBioPortal/cbioportal#4]
When using cbioportal.war from bitbucket.

i followed all needed step as i know.

there's error about type_of_cancers is null.

but i insert sample brca_study data successfully.
and i can select it with jndi.

below is snapshot of firefox & firebug.

give me any tiny hint whatever you can suppose.

thanks.

![screenshot_20150421161147](https://cloud.githubusercontent.com/assets/5274928/7247168/5a0aff40-e841-11e4-9346-5f035eecc83e.png)

**Comment by vingorius** [comment]
I found what' wrong.
After insert the sample data named 'brca-example-study.tar.gz' , 
It's cancer_study's type_of_cancer_id is lowercase on database.
After changing it uppercase, there' s no error.
Thanks.

**Comment by n1zea144** [comment]
Thanks for reporting this.
B
