### ISSUE TITLE
oncoprint won't load for a specific query

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4007]
I don't understand what's going on, but this specific query refuses to load the actual OncoPrint:
![image](https://user-images.githubusercontent.com/10508276/37685056-7364a626-2c68-11e8-8e13-39ce7377ae04.png)

http://www.cbioportal.org/index.do?cancer_study_id=gbm_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=gbm_tcga_cnaseq&gene_list=CDKN2A%2520CDK4%2520RB1&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=gbm_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=gbm_tcga_gistic

also reported by:
https://groups.google.com/forum/#!topic/cbioportal/Gx95-mQv0hU

**Comment by adamabeshouse** [comment]
error also present in beta.. looks possibly related to a failing oncokb query @zhx828 , but anyway the oncoprint shouldnt fail

**Comment by zhx828** [comment]
Thanks, @tmazor @adamabeshouse . Will solve the issue soon.

**Comment by tmazor** [comment]
Looks like this is specifically a problem with RB1. I just tried several studies and OncoPrint fails to load in all of them if RB1 is included in the query.
@zhx828 @adamabeshouse

**Comment by zhx828** [comment]
It's weird and I couldn't reproduce the issue locally, so I restarted the OncoKB instance, it works now. I will keep an eye on the issue.
