### ISSUE TITLE
Querying RB1 is failing on oncokb endpoint

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4014]
http://www.cbioportal.org/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=msk_impact_2017_cnaseq&gene_list=RB1&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna

**Comment by zhx828** [comment]
This issue is related https://github.com/cBioPortal/cbioportal/issues/4007

**Comment by inodb** [comment]
duplicate of #4007 indeed
