### ISSUE TITLE
does gzipping has a big overhead?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4018]

**Comment by jjgao** [comment]
@ersinciftci do we have an answer to this?

**Comment by ersinciftci** [comment]
@jjgao not yet, I'll read more about it, though https://developers.google.com/blogger/docs/3.0/performance#gzip states that
`
An easy and convenient way to reduce the bandwidth needed for each request is to enable gzip compression. Although this requires additional CPU time to uncompress the results, the trade-off with network costs usually makes it very worthwhile.
`
