### ISSUE TITLE
Extra filter for pancancer summary view

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#402]
There is currently no way to require a minimum number of samples for a tumor type to appear. In the example below, leukemia shows up as having 33% mutations in AKT1 - but the sample size is so small (n = 3) so that this number is not reliable. 

Would be nice to be able to also specify a minimum number of samples in a group - like in the mockup below.
When switching to absolute counts, the two sliders could be called: “Min. # altered samples” and “Min. # total samples”.

<img width="1058" alt="pastedgraphic-7" src="https://cloud.githubusercontent.com/assets/2900303/11000256/f4a497a4-84a0-11e5-8808-c3e5f8faa0f5.png">

**Comment by ecerami** [comment]
@schultzn:  this was a great idea.  it's much more usable now, in terms of being able to create useful plots.  just tested against sander's latest code.
