### ISSUE TITLE
SEO: how to make google to index patient view again?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4024]
https://www.oho.com/blog/explained-60-seconds-hash-symbols-urls-and-seo

Looks like search TCGA sample IDs on Google won't show up cBioPortal links any longer. I think we should do this optimization soon. 

We should also try to optimize search engine results for searches such as "EGFR lung cancer" or "BRAF V600E", "TCGA breast"

**Comment by alisman** [comment]
Hi @jjgao I've done some more search now and verified us with the Google Webmaster toolkit.  Here are some steps we need to take:
1. Create and upload a sitemap to the GWT that lists studies and patients (there may be too many patients but we could also have a page that lists them call on our site)
2. Add meta and description tags on patient page which are set dynamically
3. Google has [deprecated](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) the old #! ajax crawling scheme.  They will now render all URLS.  It's fuzzy how long they wait.  The best info I could get is that they use "heuristics" to determine when page is loaded. ~5 secs someone said. 
4. We should ultimately switch away from using # fragments to HTML5 history based routing in new sites.
5. The Google Webmaster Toolkit will allow us to debug all of this and actually see whether Google is indexing our pages.

**Comment by jjgao** [comment]
@alisman great! Thanks.

For # 1, maybe we can generate a dynamic page from database? We should have google to index studies, patients, samples, and genes.

For # 3, not sure why our patient view pages are not indexed now?

For # 4, is there still a reason not to use #?

**Comment by jjgao** [comment]
@alisman is this done?

**Comment by jjgao** [comment]
@alisman I tried to search a couple of TCGA patients. Google doesn't return cBioPortal link on this...

**Comment by jjgao** [comment]
It seems hard to fully fix this after a few tries and now that we have quick search, let's close this for now.
