### ISSUE TITLE
mutations tab fails to load lollipop & cancer hotspots

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4028]
![image](https://user-images.githubusercontent.com/10508276/37911074-17aca508-30dd-11e8-8f5f-de04724c24d3.png)
http://www.cbioportal.org/index.do?session_id=5a1eef06498eb8b3d560f502&show_samples=false&

**Comment by inodb** [comment]
@jjgao yeah just noticed ssl seems to be down :(

**Comment by inodb** [comment]
@tmazor @jj	 restarted the tomcat - not sure why ssl stopped working. Is ok again now
