### ISSUE TITLE
getCanonicalMutationType

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4030]
@adamabeshouse should getCanonicalMutationType provide for mutation type value which does NOT exist in the list?  I.e. return "other" if 
canonicalType[mutationType.toLowerCase()] is undefined.

I ask because I think it makes more sense here than in feature code.

**Comment by adamabeshouse** [comment]
yeah, I think we also need to do some renaming. related: https://github.com/cBioPortal/cbioportal/issues/2779
