### ISSUE TITLE
gene-panel-data/fetch request has an unnecessary object layer

### ISSUE THREAD

**Issue by ersinciftci** [cBioPortal/cbioportal#4034]
After the latest changes, `GenePanelMultipleStudyFilter` has only a list in it now, so we can just use that list in the controller directly.

**Comment by ersinciftci** [comment]
@adamabeshouse @zhx828 this would require frontend changes too, so need to do it in sync. not urgent though.

**Comment by adamabeshouse** [comment]
:+1:

**Comment by zhx828** [comment]
🆗

**Comment by jjgao** [comment]
@adamabeshouse @zhx828 do you know what @ersinciftci is talking about here?

**Comment by adamabeshouse** [comment]
it appears to be done already
