### ISSUE TITLE
Unable to download Oncoprint from chrome

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#4038]
and PDF format in any browser

**Comment by jjgao** [comment]
@kalletlak I couldn't reproduce it? Is it on the production portal?

**Comment by adamabeshouse** [comment]
I can't reproduce this, but could it have to do with an ad blocker or popup blocker you have installed, preventing the download action?

**Comment by jjgao** [comment]
@kalletlak I am closing this since we cannot reproduce it.
