### ISSUE TITLE
Customize the width of OncoPrint attribute/gene name column

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4041]
I was wondering if it would be possible to make the width of the clinical attribute/gene name column in OncoPrint customizable. 

Names of clinical tracks can be pretty long and I understand that it's perhaps best to not display their full length by default. A solution could be to make this customizable, perhaps with a slider that can be dragged to increase/decrease the width of this column.

For specific images, possible for use in presentations, posters or publications, it could be pretty useful to see the full name of long attributes and genes.

![screen shot 2018-03-29 at 15 12 00](https://user-images.githubusercontent.com/9624990/38090797-fc8e7196-3363-11e8-9259-e872c00554a8.png)

**Comment by jjgao** [comment]
Good point. But you could get the full name in svg or pdf download :)
