### ISSUE TITLE
Problems with cBioPortal in IE11

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4046]
When using [cbioportal.org](http://www.cbioportal.org/) (currently on 1.12.1-SNAPSHOT) with IE11 I found the following 2 issues:

1- Patient view does not always work. E.g. select http://www.cbioportal.org/study?id=brca_tcga and then click on icon to view the selected patients. The error below appears:

![image](https://user-images.githubusercontent.com/2900303/38137532-7108a23c-3425-11e8-9e0f-4551a3fba2bd.png)

2- Study view does not work anymore when filtering. E.g. select http://www.cbioportal.org/study?id=coadread_tcga#summary and then filter "with mutation data = YES" by clicking on the pie chart. The study view will try to filter, but the horizontal progress bars will loop indefinitely. See screenshot below.  

![image](https://user-images.githubusercontent.com/2900303/38137555-9733b3c0-3425-11e8-9780-98ae838c2037.png)

**Comment by jjgao** [comment]
Since we have a small IE11 user base and the review feature is more useful for reviewing a small set of patients, it is a rare use case that an IE 11 user reviewing many patients. I don't think it's a critical issue.

**Comment by alisman** [comment]
@zhx828 We are going to show this message for Edge as well because it turns out Edge truncates the patient list.  Better than IE but still not completely working.
