### ISSUE TITLE
In IE 11, we cannot send large patient/sample ID sets to patient page (from study page)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4049]
IE truncates the URL at some point.  Lets figure out what threshold is and just an alert saying IE can't handle this, use another browser. This needs to be done in study view code.

**Comment by zhx828** [comment]
According to https://blogs.msdn.microsoft.com/ieinternals/2014/08/13/url-length-limits/, it's 2083.

**Comment by zhx828** [comment]
@alisman @jjgao I tested windows 10 Edge16. It has the similar issue. Instead of not showing anything in IE11, the Edge cuts off the. Should we apply the same rule for Edge?

**Comment by zhx828** [comment]
![screen shot 2018-04-09 at 1 25 37 pm](https://user-images.githubusercontent.com/5400599/38512770-243c9a9e-3bfa-11e8-8739-7e367ebc740c.png)
![screen shot 2018-04-09 at 1 26 20 pm](https://user-images.githubusercontent.com/5400599/38512771-24471064-3bfa-11e8-9a92-67ab3baac1e9.png)

**Comment by zhx828** [comment]
@jjgao @alisman Are you ok with the warning messages above?
