### ISSUE TITLE
Oncoprint: add clinical attribute drop down hidden in footer

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#405]
http://bit.ly/1MHARiu

![image](https://cloud.githubusercontent.com/assets/840895/11045961/75271dc6-86f8-11e5-81c0-aada2e22a024.png)

**Comment by adamabeshouse** [comment]
I'm not sure why this would have started happening. Did anyone recently change something related to the layout (@zheins did you mention something related to layout of the query page)? Or can someone with better knowledge of CSS possibly weigh in (@zhx828)?

**Comment by jjgao** [comment]
This may be related: https://github.com/cBioPortal/cbioportal/pull/370

**Comment by adamabeshouse** [comment]
@jjgao basically no doubt that's the issue :stuck_out_tongue:

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/419/
