### ISSUE TITLE
error related to OncoKB when loading OncoPrint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4054]
http://www.cbioportal.org/index.do?session_id=5a5d5992498eb8b3d563cea1

![image](https://user-images.githubusercontent.com/840895/38213156-36018e86-368e-11e8-8286-7e196156e6b7.png)

**Comment by zhx828** [comment]
@jjgao I refreshed the cache, the query is working now. BRAF keeps going off... I'm looking into the issue.
