### ISSUE TITLE
[beta] Virtual Study button

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4062]
The virtual study button is a little too predominant. Maybe we should design an icon? Maybe a basket icon?

Currently: 
![image](https://user-images.githubusercontent.com/840895/38271547-bf70af6e-3754-11e8-8064-7b74a471b610.png)

One option (`fa-shopping-basket`):
![image](https://user-images.githubusercontent.com/840895/38272184-8130e32a-3756-11e8-800f-93654e6c502d.png)

Thoughts?

**Comment by kalletlak** [comment]
looks good. but not sure if its user-friendly.

**Comment by jjgao** [comment]
Maybe something like this one would work? Can we try? @kalletlak @zhx828 

![image](https://user-images.githubusercontent.com/840895/38517240-43bc13ba-3c07-11e8-9f01-e71bd7eb8228.png)

**Comment by zhx828** [comment]
@jjgao @schultzn @ecerami @kalletlak 
![screen shot 2018-04-12 at 12 39 16 pm](https://user-images.githubusercontent.com/5400599/38691345-9b239ecc-3e4e-11e8-9b22-5d08602a74d6.png)
![screen shot 2018-04-12 at 12 39 41 pm](https://user-images.githubusercontent.com/5400599/38691346-9b313244-3e4e-11e8-93c8-d5dafd8bb315.png)
![screen shot 2018-04-12 at 12 39 50 pm](https://user-images.githubusercontent.com/5400599/38691347-9b45dff0-3e4e-11e8-967e-fd8e5fc1157a.png)

**Comment by zhx828** [comment]
What about a cart icon with saving
![screen shot 2018-04-12 at 12 46 41 pm](https://user-images.githubusercontent.com/5400599/38691776-c9cff706-3e4f-11e8-8513-7adc9f447d17.png)
 indicator in it:

**Comment by zhx828** [comment]
New basket icon. Idea comes from basket trail(from JJ).
![screen shot 2018-04-12 at 4 40 49 pm](https://user-images.githubusercontent.com/5400599/38704391-2842d0b4-3e74-11e8-8419-aece80f74d82.png)

**Comment by zhx828** [comment]
With arrow icon instead
<img width="419" alt="screen shot 2018-04-16 at 11 12 26 am" src="https://user-images.githubusercontent.com/5400599/38817860-4543b46c-4167-11e8-8c4a-06b732781fa3.png">

**Comment by zhx828** [comment]
<img width="414" alt="screen shot 2018-04-16 at 10 45 59 pm" src="https://user-images.githubusercontent.com/5400599/38846036-43cbf3a4-41c8-11e8-801a-3b3f1a060709.png">
<img width="416" alt="screen shot 2018-04-16 at 10 46 17 pm" src="https://user-images.githubusercontent.com/5400599/38846037-43db2112-41c8-11e8-9193-38efeb31c7c8.png">
<img width="417" alt="screen shot 2018-04-16 at 10 46 39 pm" src="https://user-images.githubusercontent.com/5400599/38846038-43e65186-41c8-11e8-95d6-aa92d6accbf5.png">
<img width="417" alt="screen shot 2018-04-16 at 10 46 59 pm" src="https://user-images.githubusercontent.com/5400599/38846039-43f33fe0-41c8-11e8-8a7a-91e650399184.png">
