### ISSUE TITLE
Add a optional warning to all pages

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4065]
MSK users sometimes put internal urls in their publications. e.g.

http://ascopubs.org/doi/full/10.1200/JCO.2017.75.3384

![image](https://user-images.githubusercontent.com/840895/38285686-64a7c988-378f-11e8-98f9-959401de61a4.png)

We need to be able to add a warning and ask them not to do that. 

- [ ] add a new property in frontend or backend: `study_view_warning`
- [ ] append the warning at the end of the description of a study 
- [ ] add a warning for all our private portal: "Please do NOT include the URL to this study or any other pages on this portal in your publication. If you need to make a study for your publication in the public cBioPortal, please contact cbioportal@cbio.mskcc.org."

**Comment by jjgao** [comment]
this is still happening. But maybe the message I put above is a bit too long.

thoughts, @schultzn ?

**Comment by schultzn** [comment]
How about just "Study URL is temporary - do NOT include in publications."

**Comment by inodb** [comment]
This applies to all studies in MSKCC/triage portals right? If so, maybe we can make it more general i.e. allow to add some blurb to the description of all studies in a portal. For example a `skin.study_view.blurb`. Similar to `skin.blurb`: https://docs.cbioportal.org/2.3-customization/portal.properties-reference#control-the-content-of-specific-sections.

**Comment by jjgao** [comment]
@inodb sounds good. Yes, to all studies.

**Comment by inodb** [comment]
we should do this

**Comment by Leowisd** [comment]
![image](https://user-images.githubusercontent.com/32425638/88334859-fce3d700-ccf7-11ea-9478-1ec3ad7b2547.png)

**Comment by Leowisd** [comment]
![image](https://user-images.githubusercontent.com/32425638/89047863-a4729200-d314-11ea-8003-fb4a6c5818a2.png)
![image](https://user-images.githubusercontent.com/32425638/89047899-afc5bd80-d314-11ea-8b2d-6bcee558c026.png)
![image](https://user-images.githubusercontent.com/32425638/89047926-bb18e900-d314-11ea-9205-612459473528.png)

**Comment by jjgao** [comment]
Thanks, @Leowisd. It looks good!

For the last one, could you add "transferred to the public cBioPortal"?

Is this message configurable? e.g. we should have a message in the private portal too.

@schultzn @n1zea144 comments?

**Comment by Leowisd** [comment]
Okay.

**Comment by alisman** [comment]
- [ ] Alert at top should read/appear as follows:
![image](https://user-images.githubusercontent.com/186521/89220711-13afe680-d5a0-11ea-9eb8-cf0a571a8e46.png)
- [ ] The UI/text in the modal should be changed as follows:

```When adding a link to this cBioPortal cohort in a manuscript, **I will not link to the internal MSK portal (cbioportal.mskcc.org)**, but will instead link to this study on the public cBioPortal (cbioportal.org). Contact cbioportal@cbio.mskcc.org with any questions about getting the data transferred to the public cBioPortal.```

**Comment by Leowisd** [comment]
Got it

**Comment by Leowisd** [comment]
![image](https://user-images.githubusercontent.com/32425638/89222301-70a89e00-d59a-11ea-9c27-f80549ed5527.png)
![image](https://user-images.githubusercontent.com/32425638/89222337-7d2cf680-d59a-11ea-86bc-93531129599a.png)

**Comment by alisman** [comment]
@Leowisd we only want to do this when
``` ["triage-portal","mskcc-portal"].includes(AppConfig.serverConfig.app_name)```
