### ISSUE TITLE
Oncoprint cell mouseover disappears before it can be clicked

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#4066]
On the public /beta portal and the current `rc` branch, when I hover the mouse over an Oncoprint cell, the tooltip disappears very quickly and often can't even be seen at all. It seems impossible to move the mouse onto the tooltip to click the patient ID link inside.

**Comment by fedde-s** [comment]
The first commit on which I was able to reproduce the bug is this one:

```
commit ea34ebffc67029e5f8df50f3860af1be9013e765
Author: Ino de Bruijn <ino@ino.pm>
Date:   Tue Apr 3 13:33:06 2018 -0400

    update frontend to rc 8144b5126276dd9ea97b76c0090756bf4ac11b45
```

Which is also included in the `release-1.13.0` branch.

**Comment by adamabeshouse** [comment]
its actually in production too

**Comment by fedde-s** [comment]
Ah, yes, you're right. I guess I couldn't reproduce it in master yesterday due to #4067, which has since been fixed.

**Comment by adamabeshouse** [comment]
fix in `master`

**Comment by fedde-s** [comment]
I see no change in `master` yet.

**Comment by inodb** [comment]
Fixed in production - will include in 1.12.1 release

**Comment by fedde-s** [comment]
I can confirm that commit a2c4654cb5d3583fc8b2ebb92a326a7285fc65b1 in @inodb's `update-frontend` branch would fix this issue in the setup in which I previously reproduced it.

**Comment by fedde-s** [comment]
However, the issue does still exist in the `master` branch.

**Comment by inodb** [comment]
merged to master
