### ISSUE TITLE
Oncoprint not appearing in current master; gene panel request error

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#4067]
When I run the current master branch (8784f73b0b73207b84aa4f926a1e9a4a63d8a359) and open the results view, no Oncoprint appears. Instead, the backend throws a NullPointerException and sends a HTTP 500 Internal Server Error as the response to a post request for `api/gene-panel-data/fetch`.

**Comment by fedde-s** [comment]
The bug seems to have been introduced by this commit:

```
commit 48bffceb7eb65c2fd905a67b7c30dea3836e5018
Author: Ersin Ciftci <arseniusthegreat@gmail.com>
Date:   Mon Apr 2 11:11:31 2018 -0400

    Gene panel improvement

    Fixes #3965
```

**Comment by fedde-s** [comment]
@ersinciftci, are you aware of this?

**Comment by ersinciftci** [comment]
@jjgao it seems @fedde-s 's local DB is missing the `_sequenced` list (I thought it was enforced somehow), should I assume all samples are sequenced if the study doesn't have `_sequenced` list?
