### ISSUE TITLE
Move Public Portal to AWS

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4069]
- [x] Create API secret key for session service
- [x] Make k8s deployment of cbioportal on AWS (http://test.cbioportal.review, https://github.com/cBioPortal/cbioportal/pull/4035) use heroku session service
- [x] support https on aws
- [x] point frontend of one of the servers (dashi2) to the api of k8s instance.
- [x] point both (dashi,dashi2) to the api of k8s instance
- [x] figure out why replicas go down so much (https://snapshot.raintank.io/dashboard/snapshot/2aGdDE724RYTQ7SKnk1a3glV9l9RouGB?orgId=2)
- [x] figure out where to point dns record of www.cbioportal.org. We could either point it to a backend on k8s. Or we could point it to e.g. frontend on netlify, fix redirects there and make sure that they use the api on k8s. Advantage of latter is that it's more likely that the static assets are always reachable. So we could for instance give a notification that the API is down and point people to status notification channels instead of showing a blank page

**Comment by jjgao** [comment]
related to #4217
