### ISSUE TITLE
switching between sample and patient mode causes double flash

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#4073]

**Comment by adamabeshouse** [comment]
problem still present :( looks different now, but switch to sample looks fine, then switch back to patient theres an immediate flash, then another one after a delay
http://www.cbioportal.org/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=msk_impact_2017_cnaseq&gene_list=KRAS%2520NRAS%2520BRAF&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&show_samples=false

**Comment by jjgao** [comment]
@adamabeshouse I'm can live with this one if it's not easy to solve.
