### ISSUE TITLE
add selection criteria into the default virtual study description

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4080]

**Comment by zhx828** [comment]
@jjgao Does this look good?
```
13 samples from 1 study (2018-4-9)

Sex: Male
Diagnosis Age: 30< ~ <=70
Mutation Count 80< ~ <=140
```

**Comment by jjgao** [comment]
Maybe, we can also list the studies?

**Comment by zhx828** [comment]
@jjgao 
```
13 samples from 1 study (2018-4-9)

Filters:
Sex: Male
Diagnosis Age: 30< ~ <=70
Mutation Count 80< ~ <=140

Relevant Study:
Adrenocortical Carcinoma (TCGA, Provisional)
```

**Comment by jjgao** [comment]
@zhx828 

```
13 samples from 2 studies (2018-4-9):
- Adrenocortical Carcinoma (TCGA, Provisional) (10 samples)
- Adrenocortical Carcinoma (MSK, 2018) (3 samples)

Filters:
- Sex: Male
- Diagnosis Age: 30< ~ <=70
- Mutation Count 80< ~ <=140
```

**Comment by zhx828** [comment]
![screen shot 2018-04-10 at 7 09 06 pm](https://user-images.githubusercontent.com/5400599/38588218-bc5cd660-3cf2-11e8-922f-6e95bcecc82b.png)
@jjgao @kalletlak this is the default description when the above filters applied. For the scatter plot, it is tricky since it contains all selected samples. So for now, I don't include them in the description. What do you think?
![screen shot 2018-04-10 at 7 09 01 pm](https://user-images.githubusercontent.com/5400599/38588223-c06f1b8c-3cf2-11e8-96ff-48583554a5ce.png)

**Comment by jjgao** [comment]
@zhx828 for `CNA Genes` and `Mutated Genes`, I guess you used `;` to indicate different selections? Maybe you can break them into two lines so between lines it's always `AND` relationship.  In fact, I think it would be useful to do that in the Selection criteria head in the page as well, but maybe that's a separate pull request.

For scatter plot, is it possible to break it into two selections (MUT and CNA).

How do you handle custom selection?

**Comment by zhx828** [comment]
@jjgao For the scatter plot, we don't have the range info yet. I can take a look how complicated it will be to have them in. Looks like I missed the custom selection part. How do you want the filter to be?

**Comment by jjgao** [comment]
@zhx828 In that case, don't worry about scatter plot -- maybe just list as `MUT vs CNA: xx samples` if you know the number of samples. For custom selection, maybe also list as `-Select by IDs: xx samples`.

Do you think you can break multiple selections of `Mutated Genes` and `CNA Genes` into multiple lines?

**Comment by zhx828** [comment]
@jjgao I even suggest using separate lines for pie chart filters.
![screen shot 2018-04-11 at 5 38 02 pm](https://user-images.githubusercontent.com/5400599/38644625-2c3e7986-3daf-11e8-8e1b-662f4b2389b7.png)

**Comment by jjgao** [comment]
@zhx828 I think pie chart should be on one line since it OR logic.

Should we spell out the logic? e.g. 

-CNA Genes: ((TERT AMP) OR (RICTOR-AMP)) AND (SDHA-AMP)

or maybe it's better just:

-CNA Genes: TERT AMP, RICTOR AMP
-CNA Genes: SDHA AMP
