### ISSUE TITLE
Study View: Survival plot exclude NA is not working

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4094]
Seems like this is an issue for specific study.

**Comment by jjgao** [comment]
@zhx828 this seems like a critical issue. Maybe @kalletlak can help while you are gone?

**Comment by zhx828** [comment]
I can revisit the issue. Last time I checked, it only applied to the study
Ritika brought up

**Comment by kalletlak** [comment]
@jjgao @zhx828 there is another issue. survival curve shows cases even with excluding case with NA data. This happens when the Samples per Patient > 1. In this case once sample has NA data and other is not NA. But overall considers that patient has non NA data.
