### ISSUE TITLE
Unresponsive error on internal portal when querying all studies

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4099]
Query e.g. `ABL1 AMER1 AR ATM ATXN2` for all studies on cbioportal.mskcc.org

This is what Sarah saw:
![image](https://user-images.githubusercontent.com/1334004/38695525-854b4b34-3e5a-11e8-81d3-27c84beac635.png)

I'm getting empty oncoprint:

![screen shot 2018-04-12 at 2 05 49 pm](https://user-images.githubusercontent.com/1334004/38695566-aab4689c-3e5a-11e8-844c-3a258732e460.png)

**Comment by jjgao** [comment]
Is it b/c there are too many samples? If so, maybe we shouldn't worry about it yet. 

I don't see the Page Unresponsive popup, but it took forever to load the data.
