### ISSUE TITLE
Number of samples differs between patient view and sample view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4100]
http://triage.cbioportal.mskcc.org/study?id=brain_pdx_msk_2018#summary

If I look for patient `P-0002181` I see only two samples in study view whereas there are 8 on patient view

**Comment by zhx828** [comment]
These 6 missing samples are not included in the `brain_pdx_msk_2018_all` sample list. @inodb is assuming these samples do not have any genomic data but clinical data. But they should be in the `brain_pdx_msk_2018_all` sample list.

**Comment by ritikakundra** [comment]
@angelicaochoa I added a caselist for all samples, still now showing all samples in summary page.

**Comment by angelicaochoa** [comment]
@jjgao @inodb this issue looks like it's been resolved. 
<img width="1150" alt="screen shot 2018-04-19 at 8 59 02 pm" src="https://user-images.githubusercontent.com/15623749/39025363-88a843da-4414-11e8-9007-ffc73c43fa79.png">
