### ISSUE TITLE
Importer bug? (expected: ${db.version}) (found: 2.6.0)

### ISSUE THREAD

**Issue by messersc** [cBioPortal/cbioportal#4120]
After enabling authentication, I had to switch the importer from querying localhost for info on the portal to using the `--jar flag`.

My command looks like this:
```
~/cbioportal/core/src/main/scripts/importer/metaImport.py -n -v -o -jar $(ls $CATALINA_HOME/webapps/cbioportal/WEB-INF/lib/*.jar | tr '\n' ':') -s /tmp/work/upload/
```

Apparently, this worked back in the 1.4 days, but now it breaks with the following error message:

```
Checked DB schema version: (expected: ${db.version}) (found: 2.6.0)
Error, probably due to this version of the portal being out of sync with the database. Run the database migration script located at PORTAL_HOME/core/src/main/scripts/migrate_db.py before continuing.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
Traceback (most recent call last):
  File "/root/cbioportal/core/src/main/scripts/importer/metaImport.py", line 118, in <module>
    cbioportalImporter.main(args)
  File "/root/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 419, in main
    check_version(jvm_args)
  File "/root/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 152, in check_version
    run_java(*args)
  File "/root/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 799, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
RuntimeError: Aborting due to error while executing step.
```

I get that maven should replace these placeholders with the actual version, but somehow this does not work here. 

Is there a better way to import studies?

Or do I need to configure something else to get this working?

Thanks,
Clemens

**Comment by jjgao** [comment]
@messersc strange. MVN should replace with the actual version. 

@pieterlukasse do you guys have the problem?

**Comment by jjgao** [comment]
closing. Please feel free to reopen if the problem persists.

**Comment by messersc** [comment]
Hi @jjgao,

the problem is still there for me on `rc`. I can't re-open the ticket, but apparently I am the only one with this problem?

Will try to find a work-around.

Thanks,
Clemens

**Comment by messersc** [comment]
Turns out I was using the wrong `jar` path.

The correct command is 

` ~/cbioportal/core/src/main/scripts/importer/metaImport.py -n -v -o -jar $(ls $PORTAL_HOME/scripts/target/scripts-1.13.0-SNAPSHOT.jar | tr '\n' ':') -s /tmp/work/upload/`

Clemens
