### ISSUE TITLE
discussion: not to use CancerHotspots annotation in OncoPrint by default

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4133]
Currently both OncoKB and CancerHotspots are used to annotate OncoPrint by default. For performance reason, can we NOT use CancerHotspots by default? All the hotspots in OncoKB genes would be covered by `predicted oncogenic`. We would lose annotation for non-OncoKB gene hotspots by default.

![image](https://user-images.githubusercontent.com/840895/39307663-74d0c842-4931-11e8-979c-14c648052b54.png)

**Comment by fedde-s** [comment]
I feel like I have too little experience with the actual use-case of the CancerHotspots annotation to comment on what the best approach would be. What did bother me today was that the Oncoprint tab occasionally displayed nothing beyond a big non-interactive grey rectangle saying ‘Downloading Oncoprint data…’ for over half a minute on end with no information at all that any data had already been downloaded, making me think that no Oncoprint was going to appear.

**Comment by fedde-s** [comment]
On the plus side, it looks like [the documentation for server administrators](https://github.com/cBioPortal/cbioportal/blob/v1.12.1/docs/portal.properties-Reference.md#automatic-selection-of-oncokb-annotations) already lists a simple option that can be flipped to turn it off by default, if that's appropriate!

**Comment by jjgao** [comment]
@fedde-s Thanks for pointed out the documentation. Let's wait for @schultzn's comment.

**Comment by adamabeshouse** [comment]
what should we do about this? now we can do hotspot and oncokb separately, hotspot is through genome nexus

**Comment by jjgao** [comment]
@adamabeshouse this has changed quite a lot. Loading cancer hotspots does not seems like a bottleneck any more. Let's keep them so that they can show up in the tooltip.
