### ISSUE TITLE
Remove table pdb* creation from scripts 

### ISSUE THREAD

**Issue by abushoy** [cBioPortal/cbioportal#4137]
Please remove pdb* tables from the script https://github.com/cBioPortal/cbioportal/blob/master/db-scripts/src/main/resources/cgds.sql, they are not used by the application?

**Comment by pieterlukasse** [comment]
+1 for cleaning this up. Notify @jjgao , @n1zea144

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/cbioportal/issues/2054
