### ISSUE TITLE
JS error in getPatientSampleIdMap 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#414]
http://bit.ly/1M2db8v

![image](https://cloud.githubusercontent.com/assets/840895/11065431/647301ae-8791-11e5-8d7b-d69eb744d6bd.png)

![image](https://cloud.githubusercontent.com/assets/840895/11065436/6cce3a4e-8791-11e5-97f4-df6615455486.png)

**Comment by zheins** [comment]
@jjgao, how do you get this error? I'm not able to reproduce it. I also didn't change any code surrounding the old PatientSampleMap - this comes from the QueryBuilder directly and is not parsed by my code. Basically those IDs just get passed through the back end to the front end, mapped through the same code as before. Is this a data issue with a sample not having a patient reference?

**Comment by zheins** [comment]
@chenh4 corrected the data causing the issue.
