### ISSUE TITLE
Still allow to choose genomic profiles for VS if it only contains one physical study

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4140]
The behaviors for querying subset of one physical study should be the same with querying VS 
 with same subset

Current Query VS: 
![screen shot 2018-04-27 at 4 02 44 pm](https://user-images.githubusercontent.com/5400599/39382740-826d7b22-4a34-11e8-8671-bc71cbf1c923.png)

Current Query Subset Without Saving to VS:
![screen shot 2018-04-27 at 4 02 50 pm](https://user-images.githubusercontent.com/5400599/39382745-83c46828-4a34-11e8-8833-e8a979ee0bb0.png)

**Comment by kalletlak** [comment]
It's not easy to just show genomic profile without case-sets. Lets discuss this in the meeting.

**Comment by jjgao** [comment]
@kalletlak Good point about case set. Not sure how to solve it...

**Comment by kalletlak** [comment]
Seems Done. Closing it for now.
