### ISSUE TITLE
SV: Pie Chart

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4156]
- [x] Remove `Reset` button
- [x] Support multi-selection
Tooltip after hovering over the chart (Enhanced Fixed data table, - [ ] study-view-summary version)
- [x] Checkbox in tooltip to select pie slices
- [ ] ~~Hover category color rectangle, the pie slice is highlighted~~
- [ ] ~~Hover category color rectangle, an arc will be added beside of pie slice~~
- [x] Download
	- [x] DATA
	- [x] SVG
	- [x] PDF

**Comment by kalletlak** [comment]
@zhx828 existing Enhanced Fixed data table or the new one?

**Comment by zhx828** [comment]
@kalletlak probably the new one in the frontend repo.
