### ISSUE TITLE
SV: Tables

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4158]
- [x] Calculate frequency based on gene panel info (this is done at backend)
- [x] Show # of profiled samples in the header
- [x] Mutated Genes table: MutSig icon in Gene column
- [x] CNA Genes table: Gistic icon in Gene column
- [x] Download
	- [x] DATA
- [x] Use react-virtualized populate table
	- [x] Clinical Table
	- [x] Mutated Genes Table
	- [x] CNA Genes Table
- [x] Shorten the text and give tooltip.
- [x] ~~Use [react-virtualized](https://github.com/bvaughn/react-virtualized), co-exist with simple table.~~
	- [x] Possibility co-exist with the current SimpleTable and change very minimum of the data
	- [x] ~~Click even on the table row, CoExpression tab [example]~~(http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit)
	- [x] Special sorting... this seems not affected since the sorting is done in lazyMobxTable
	- [x] ~~Auto-adjust the column width~~
- [x] https://github.com/cBioPortal/cbioportal/issues/4167
- [x] Color the CNA column
- [x] Highlight the rows
- [x] Support multi-selection in the MutatedGenes, CNA Genes table. For instance: `{MYC or TP53} and {ALK or FOXM1}`
- [x] The tables' API should not be triggered when tables are removed from the page
- [x] The legend rectangle is squashed when the label is too long http://www.cbioportal.org/rc/newstudy?id=lung_msk_2017 SO comments
	![screen shot 2018-09-04 at 5 04 05 pm](https://user-images.githubusercontent.com/5400599/45057816-a407e880-b064-11e8-9881-aaacb187f597.png)
- [x] The search does not work for clinical attribute table

**Comment by kalletlak** [comment]
@zhx828 any specific reason for two different type of tables?

**Comment by zhx828** [comment]
@kalletlak most the components are the same, but there are customized features for different usecase. So two branches are created.
