### ISSUE TITLE
SV: Survival Plot

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4159]
- [x] Support more than two curves with color option(maybe shape as well?)
    how to reproduce: go to study http://www.cbioportal.org/study?id=lgg_tcga#summary . Hover over bar chart and click on the survival icon on the chart header. The survival ploy will show multiple curves.
- [x] Tooltip showing the current curves, and option to exclude/include NA nodes
- [x] Exclude/include NA nodes on the selected attribute, default exclude
- [x] Hover category color rectangle, the curve is highlighted putting off for now
- [x] Down-sampling to improve performance
- [x] Add log rank p-value textbox if theres two curves

**Comment by adamabeshouse** [comment]
@zhx828 what do you mean by toggling include/exclude NA nodes? where would this toggling take place, a checkbox somewhere?
