### ISSUE TITLE
SV: Scatter Plot

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4160]
- [x] ~~Scatter plot by clinical attribute (it is missing in current production)
	Not tied with mutation count/CNA~~
- [x] Select samples by using the brush
- [x] Shift-click on multi-region selection
- [x] Show scatter plot with multiple groups by coloring the node after clicking the survival icon
- [x] Tooltip when hover over the dot
- [x] Downsampling
- [x] Download
	- [x] DATA
	- [x] SVG
	- [x] PDF
- [x] Issue: on selection scatter plot selects unselected samples instead of selected sample when there are already filters on other charts
- [x] Density plot

**Comment by kalletlak** [comment]
@zhx828 are we going to use Plotly scatter or Victory scatter?

**Comment by zhx828** [comment]
@kalletlak we are going to do down sampling to check on the performance. Need to discuss the performance again after that.
