### ISSUE TITLE
Fusion with gene not in gene panel

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4165]
Try e.g. TTN which is not copy number or mutation profiled in mskimpact: http://bit.ly/2rbBQHs

Mouseover mentions:
```
Fusion: TTN-<OTHER_GENE> fusion
Not profiled in selected molecular profiles.
```
Should this mention that the other gene was profiled?

**Comment by jjgao** [comment]
Maybe in the tooltip we can say in this case:

"Gene panel: MSK-IMPACTxxx. TTN is not part of the panel, but it is a partner of this fusion."

![image](https://user-images.githubusercontent.com/840895/39501794-d5d0a434-4d8a-11e8-9b13-2786f2d9e4bb.png)

BTW, @adamabeshouse for samples with a gene-panel, it's a good idea to show the gene panel name even if a gene is not in this panel. The tooltip could be `Gene panel: MSK-IMPACTxxx. TTN is not part of the panel.`

cc'ing @schultzn

**Comment by schultzn** [comment]
If the gene is not part of the panel, should we remove / not import the variant?

**Comment by jjgao** [comment]
@schultzn that sounds like a better solution. It would also solve the double counting issue.

@n1zea144 @angelicaochoa Maybe we could use the gene panel as the white list and not duplicate fusions for non-panel genes in the pipeline?

**Comment by n1zea144** [comment]
@jjgao I prefer to make this change in the scripts package of core as this seems like a fix that other studies can benefit from.  The gene panel data is also more accessible during import.

**Comment by adamabeshouse** [comment]
@jjgao in https://github.com/cBioPortal/cbioportal-frontend/pull/1167 for samples with a gene panel but the hovered gene is not in the panel, i have the gene panel id link in red in the tooltip, as opposed to blue. is that clear enough?

**Comment by jjgao** [comment]
@adamabeshouse Thanks. I think we will try to fix it in the data.

**Comment by jjgao** [comment]
Thanks, @n1zea144. It's a good idea to fix it during import. Could you add it to you backlog?

**Comment by n1zea144** [comment]
@jjgao Here is the fix:  [PR-4227](https://github.com/cBioPortal/cbioportal/pull/4227)

**Comment by jjgao** [comment]
@n1zea144 TTN fusion is still present in the result: http://bit.ly/2rbBQHs. Could you check if your fix is in place?

**Comment by n1zea144** [comment]
@jjgao I believe its because the code is not integrated into MSK importers.  I will follow-up ASAP.

**Comment by jjgao** [comment]
@n1zea144 thanks!

**Comment by n1zea144** [comment]
@jjgao This is fixed now.

![image](https://user-images.githubusercontent.com/366003/44587319-9eff8b00-a780-11e8-8288-87548ca3f3f6.png)

**Comment by jjgao** [comment]
Thanks, @n1zea144 !

**Comment by jjgao** [comment]
@n1zea144 was the fix only integrated for the mskimpact study? I think it would be good to apply this to all studies with gene panel in all portals (public, genie, bic studies, etc). 

- apply the fix to all portals
- write a migration script to fix the data
