### ISSUE TITLE
not profiled message is unclear for patient with multiple samples

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4179]
This patient has 2 samples, one of which is profiled and the other is not. But the tooltip doesn't show that at all - so it mostly looks like the tooltip is contradicting itself.

![image](https://user-images.githubusercontent.com/10508276/39707844-87ee89fe-51e3-11e8-92b7-741d45aae359.png)

Can we add text to the tooltip to make this more clear -- for example:
Sample 1 is profiled in .....
Sample 2 is not profile in ....

**Comment by jjgao** [comment]
@tmazor maybe it's OK if we only show the warning when none of the samples in a patient are profiled?

**Comment by tmazor** [comment]
@jjgao that seems reasonable and probably more consistent with how oncoprint is representing the data anyway. sounds good to me!

**Comment by adamabeshouse** [comment]
that works!

**Comment by adamabeshouse** [comment]
PR: https://github.com/cBioPortal/cbioportal-frontend/pull/1150
