### ISSUE TITLE
beta - a virtual study derived from another virtual study needs a more complete default description

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4181]
I really like how the default virtual study description explains how the study was generated. However, once a virtual study is saved, if I go to study view, all of that information is lost.

Take this example: I create Virtual Study A. I then create Virtual Study B which is a subset of Virtual Study A. The description for Virtual Study A clearly states how that study was created. The description for Virtual Study B describes how it was created from Virtual Study A, but doesn't reference Virtual Study A or how Virtual Study A was generated. If someone just views Virtual Study B, there is no real context for how that study was created.

I would appreciate some continuity of the description -- either Virtual Study B should import the description text from Virtual Study A and build on that OR it should reference that it derived from Virtual Study A.

Thoughts? @jjgao @schultzn

**Comment by jjgao** [comment]
@zhx828 Maybe we can try to add the virtual study to the study list instead of physical study?

Then you can append/down the virtual study description at the end of the description?

**Comment by zhx828** [comment]
Thanks @tmazor @schultzn and @jjgao. Will do.

**Comment by zhx828** [comment]
@tmazor @schultzn @jjgao After testing few rounds, I realize the VS description would easily get expanded too long if you build VS based on VS several rounds. What do you think I list all studies with descriptions that this study derived from?
![screen shot 2018-05-07 at 9 23 35 pm](https://user-images.githubusercontent.com/5400599/39732975-66985ab8-523e-11e8-84f4-e0b9dd9f26c2.png)

**Comment by tmazor** [comment]
I appreciate that this text could very easily get very long, but if I make a VS from a VS, I very quickly lose the information about which the original study was. Having the link-out to the previous VS is helpful, but I don't want to have to click through several previous VS to remember what I did/where I started.

Since the previous VS is already shown as a closed box that can be expanded, could we actually nest the previous VS within that box also? By which I mean: let's say I make VS1, then from that make VS2, then from that make VS3.

Here's what it looks like when I expand the VS3 study description:
![image](https://user-images.githubusercontent.com/10508276/39869651-6aa922a0-542c-11e8-9bdc-d3e8957dab29.png)

What if the text that says "VS1" could actually be expanded to show the full VS1 description:
![image](https://user-images.githubusercontent.com/10508276/39869658-7214cd64-542c-11e8-852b-435ea68389de.png)

I don't know how often someone is going to go this many virtual studies deep, but it seems potentially useful. @schultzn  what do you think?

**Comment by schultzn** [comment]
I agree with Tali. It would be great to preserve the full history - especially since prior virtual studies can be deleted, which would mean that all that information is lost. 

Niki.

**Comment by kalletlak** [comment]
May be something like this?
![screen shot 2018-05-10 at 10 03 29 am](https://user-images.githubusercontent.com/12956870/39873660-8f86b972-5439-11e8-8304-d8a1b5e717f7.png)

https://jsfiddle.net/pnqzspoe/3726/

**Comment by jjgao** [comment]
@kalletlak's mockup looks great!
