### ISSUE TITLE
downloads tab should indicate not profiled

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4183]
The second sample for this patient is not profiled:
![image](https://user-images.githubusercontent.com/10508276/39720282-d102d962-5209-11e8-9f21-3748488f1318.png)

That should be made clear in the download tab as well, but currently isn't. This sample looks the same as another sample which is profiled but lacks any mutations/CNAs:
![image](https://user-images.githubusercontent.com/10508276/39720243-b1854c0a-5209-11e8-8cc4-0e65b2a54492.png)
![image](https://user-images.githubusercontent.com/10508276/39720409-3c7cb2e4-520a-11e8-9f88-ed58665225ee.png)

**Comment by jjgao** [comment]
Gaofei Zhao [11:55 AM]
@product Onur and I discussed about how to fix issue 4183: https://github.com/cBioPortal/cbioportal/issues/4183. We proposed one solution which shows in this screenshot. Can I ask your opinions about this?

![image](https://user-images.githubusercontent.com/840895/48431485-d3f7fa00-e73f-11e8-9e98-d02dc9c7bd7d.png)

**Comment by jjgao** [comment]
@dippindots @onursumer maybe we should use different columns for different profile type and put `no alteration` and `not profiled`. 

@tali thoughts?

**Comment by tmazor** [comment]
Definitely agree we should use "Not Profiled" rather than "NP", that will be much clearer to a user. Writing "No alteration" rather than leaving those cells blank is probably also a good idea since that makes everything explicit. So yes, I agree, good plan!

**Comment by jjgao** [comment]
Thanks, @tmazor!

@dippindots @onursumer please go head and implement or make a mock-up.

- [ ] separate columm for each profile, e.g. `IDH1 MUT`, `IDH1 CNA` 
- [ ] support `no alteration` and `not profiled`.

**Comment by dippindots** [comment]
@jjgao @tmazor 
I finished the demo version of the proposal based on new requirements. Here is the screenshot of the new table.
![image](https://user-images.githubusercontent.com/15748980/48517440-5366f580-e834-11e8-81e2-330d94ee21c7.png)

Does it match your requirements?

**Comment by jjgao** [comment]
Thanks, @dippindots.

@tmazor should we use gray color for `no alteration`? Or bold any alterations?

**Comment by alisman** [comment]
@dippindots seems consensus is that we should always show all columns
