### ISSUE TITLE
Singe Study View case list drop down with default

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4188]
For one of our PDX collaborators it would be useful to show the study view without PDX samples. We would like to add a dropdown for all case lists. For their use case it would be useful to not use `_all` case list as the default but one that only has non-pdx samples

**Comment by jjgao** [comment]
- [ ] support default case list for study view, e.g. `cases_study_view_default` or a better name @zhx828
- [ ] Curarate `cases_study_view_default`, `cases_patient_samples`, `cases_patient_samples_for_pdx_models` (the patient samples used to derive pdx), `case_pdx_samples` @ritikakundra 
- [ ] Support dropdown manu to select different case list in study view @zhx828

**Comment by jjgao** [comment]
@zhx828 maybe we can do the first one soon? @ritikakundra can you do the second one? I think that will address most of their use cases.

**Comment by jjgao** [comment]
We could also support switching to user-defined group - let's keep that in mind when design this.

**Comment by zhx828** [comment]
@jjgao should we implement this soon with the `WIth CNA/ With Mutation`?

**Comment by jjgao** [comment]
@zhx828 let's not worry about it for now. I think it requires some more designing...

**Comment by jjgao** [comment]
@zhx828 thinking it more, it's a great idea to add it to the `WIth CNA/ With Mutation` section. We could have a drop-down component to list all case lists and allow users to select multiple case lists. 

This is also related to the [Redesigning case lists](https://docs.google.com/document/d/1aBbkTAFv5nCqBv66BOgwvlt5kymgt0lQ7l_pqaFrupc/edit) RFC.

**Comment by jjgao** [comment]
Now that we have a "genomic profile samples count" table (https://github.com/cBioPortal/cbioportal-frontend/pull/3090), let's make another table "Case lists".
