### ISSUE TITLE
Refactored Expression tab: use styles close to other tabs

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4197]
Can we use stypes close to other tabs? And please feel free to be creative :)

- [x] further reduce the white space between studies in Expression tab -- should be able to fit all 33 pancancer studies in the screen (just like we do now)
- [x] is it possible to link out the patient view in the tooltip?
- [x] the mutation status does not seem right (http://bit.ly/2Knv88p) -- too many truncating (black) mutations for EGFR
- [x] X-axis label issue: http://bit.ly/2Knv88p

![image](https://user-images.githubusercontent.com/840895/40024664-0e6f065c-579d-11e8-8f94-4e8cbc1619dd.png)

- [x] for switching genes, can we use the same style (button) as Cancer Type Summary and Mutations tab.
- [x] Change "Sort by" to a dropdown menu with two options: Alphabetically, and Median expression
- [x] The current filters line looks more like filters being used. Maybe remove `Filters:` and add three buttons: `Selected TCGA Provisional Studies (10)`, `Selected TCGA PanCancer Atlas Studies (20)`, `Custom`
- [x] If no TCGA provisional studies were select, `Selected TCGA Provisional Studies (10)` should not be displayed. The same for `Selected TCGA PanCancer Atlas Studies (20)`.

**Comment by alisman** [comment]
@jjgao I have a question abou #2.  Should it be tabs or buttons (relates to presevagtion of settings on gene by gene basis). Lets discuss tomorrow.
