### ISSUE TITLE
mutations tab - grey out gene names when no mutations present

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4201]
On the Cancer Types Summary tab, the gene name appears in grey where there are no alterations. Can we do the same on the Mutations tab?

Example: RBL1 and RBL2 in these screenshots:

![image](https://user-images.githubusercontent.com/10508276/39871220-240c8444-5432-11e8-805b-49416b7e9fa5.png)

![image](https://user-images.githubusercontent.com/10508276/39871227-2b420f04-5432-11e8-8b28-691b01013aad.png)

**Comment by tmazor** [comment]
Let's also do this for the co-expression tab when a gene has no data for a particular dataset - e.g. most genes when RPPA data is selected:
![image](https://user-images.githubusercontent.com/10508276/41247445-fc235648-6d7b-11e8-8d5c-e02f62e11551.png)

**Comment by adamabeshouse** [comment]
for both mutations and coexpression, since we load this data lazily, we wont be able to show that until after the tab has already been clicked. is it still useful?

**Comment by alisman** [comment]
@tmazor what adam says does seem to compromise the utility of it.  what you think?   we could of course preload all that data just for the sake of providing the indicator, but we actually worked pretty hard to avoid loading all data up front when we don't have to so ...

**Comment by adamabeshouse** [comment]
This is not an uncommon type of situation... maybe we could add a projection to the mutations endpoint, "EXISTS", or "LENGTH", which just returns whether there exist results for that query, or the length of the would-be return value? Would this be too slow on the database side anyway, even though we'd save on download time?

**Comment by alisman** [comment]
I think we should not worry about this for 1.14.0.  We can discuss with @jjgao at planning meeting tomorrow.

**Comment by tmazor** [comment]
Agreed - this is not necessary for 1.14 and also not worth pre-loading all data to address.

**Comment by jjgao** [comment]
Maybe we should use the data (# mutated samples) from OncoPrint for this since the data is already loaded? If MUT OQL is used, it won't work well, but that's a rare use case. 

Or maybe we should do it once we syncronize oql/oncoprint with Mutations tab?

**Comment by adamabeshouse** [comment]
@jjgao in order to calculate the number of mutated samples we need to load all the mutation data, and if you go straight to the mutations tab you can avoid this.

**Comment by jjgao** [comment]
@tmazor This seems complicated in implementation. Are you ok if we hold this off since we have other priorities?

**Comment by tmazor** [comment]
absolutely @jjgao - i don't think this is an urgent need at all

**Comment by jjgao** [comment]
Thanks, @tmazor. I've moved this to icebox.

**Comment by jjgao** [comment]
@adamabeshouse maybe we can do this now since we are using the oncoprint (oql) data to filter mutations?

If a user opens mutations tab directly, it's ok to render all of them as blue.

**Comment by adamabeshouse** [comment]
@jjgao somewhere along the way, we are no longer loading mutations gene-by-gene. So we can either restore the functionality to do this gene-by-gene, then find a way to do it, or just do it this way where all data is loaded up front no matter what. What do you think?

**Comment by jjgao** [comment]
@adamabeshouse are we loading more data than oncoprint when loading all genes in mutations tab? If not, it's ok to load them all.

**Comment by jjgao** [comment]
@adamabeshouse so we are not loading any additional data for mutations tab if the oncoprint data is loaded?

How about other tab? Are we still lazy loading them?

**Comment by adamabeshouse** [comment]
@jjgao thats right, the oncoprint uses the same mutation data as the mutations tab.

Which tabs are you talking about? I've touched a few tabs and I think we are using lazy loading in most places.

**Comment by jjgao** [comment]
Great. Thanks.
