### ISSUE TITLE
Alternate methods for data import?

### ISSUE THREAD

**Issue by ashraf123456789** [cBioPortal/cbioportal#4209]
Hello,

I work in a department where we deployed a local instance of cbioportal to multiple users using a common server. We have access to the instance via http link. But at the moment data import will be a problem via terminal/command line due to authorization issues with the server. Is there a GUI available in the instance where we can upload the data without direct access to the server?

**Comment by jjgao** [comment]
We don't have a GUI for uploading data to the server. One option I could think of is using a GUI (installed on the server) to update the database directly, e.g. https://www.phpmyadmin.net/. You can then import data in a local computer and update to the server.
