### ISSUE TITLE
moving session service

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4217]
- [x] decide where to move: Amazon or Heroku?
- [x] set up a session service on cloud
- [ ] create one collection per production portal
- [x] create api key (we went for basic auth)
- [ ] point to the cloud session service for all portals except public, public genie, and mskcc portals.
- [x] move current sessions / virtual studies to the corresponding collections on cloud (manual process)
- [x] point to the cloud session service for public, public genie, and mskcc portals.

**Comment by jjgao** [comment]
@inodb please update this if needed.

**Comment by inodb** [comment]
@jjgao 	updated - 

One question: we don't have the single collection per production portal. I believe we currently use the `source` field of the collection to indicate which portal the session came from. One sets this source by changing the URL to the api, e.g.:
`/api/sessions/portal_name`. Should this be changed?

**Comment by jjgao** [comment]
@inodb I think it's good idea to have separate collections for different portals. Maybe we can start to separate them as we move the portals to AWS? We can still make the session service url configurable (maybe the same way).

**Comment by inodb** [comment]
@jjgao i think it will complicate the move, cause it'll require code changes and data migrations. We have multiple collections atm:

``
main_session
virtual_cohort
virtual_study
```

We could e.g. prefix them with the name of the portal to get separate collections. But we also discussed moving session service into cBioPortal, so not sure if it's worth the effort. Since it's not essential to the move it might be better to separate this out to a different issue

**Comment by inodb** [comment]
we're using the aws session service now for all portals
