### ISSUE TITLE
why are we loading all virtual studies in the study view?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4218]
... even if I only open a physical study.

![image](https://user-images.githubusercontent.com/840895/39945365-38ee8fea-5538-11e8-971a-1b7e13db9ddd.png)

**Comment by zhx828** [comment]
@jjgao we are loading all virtual studies created by this particular user. This is one of the services needed for giving details where this VS derived from. We could make multiple API calls for particular VSs, but think this is more efficient.

**Comment by jjgao** [comment]
@zhx828 this happens in the study view page. The virtual studies are not displayed in the page...

**Comment by kalletlak** [comment]
@jjgao @zhx828 this is fixed in new study view page. closing it for now
