### ISSUE TITLE
.seg file downloaded from CN segments appears to be broken

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4220]
@schultzn reported this. Maybe it is the ” at the beginning of the file.

![image](https://user-images.githubusercontent.com/840895/39946033-a3b543e4-553a-11e8-8562-031c7b534152.png)

**Comment by onursumer** [comment]
Actually the entire string is wrapped with `"`, and also there are special escape characters like `\n`,`\t` in it. For now a quick fix is to perform an `unquote` and `unescape` before downloading. I'll take care of this.
