### ISSUE TITLE
end point for sample_profile data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4225]
- [ ] Clean up [code](https://github.com/cBioPortal/cbioportal/blob/master/service/src/main/java/org/cbioportal/service/impl/GenePanelServiceImpl.java) and remove logic around "_sequenced" case list
- [ ] separate the `gene-panel-data` (the `1st` and `last` below) to a new endpoint of `is_profiled`. The other three gene-panels meta endpoints can remain.

![image](https://user-images.githubusercontent.com/840895/46354142-eacd0c00-c62b-11e8-9ada-7834368d28ef.png)

- [ ] there are a couple data points in the `sample` endpoints that are related to data availability. I think we should move these data here.
![image](https://user-images.githubusercontent.com/840895/84302336-21f30080-ab23-11ea-8930-a5765b21f92a.png)

==== previous note ===
@ersinciftci once #4109 is closed, you can remove code to look for data in _sequenced case list for the gene panel end point. Maybe we should also redesign the end points and have a specific one for sample_profile data?

**Comment by pieterlukasse** [comment]
@jjgao are these still the current plans? Apparently `_sequenced` is still an issue when missing.

**Comment by jjgao** [comment]
Yes, #4109 can probably be closed now -- need to verify, and then @ersinciftci can remove the hacky code.

**Comment by ersinciftci** [comment]
@jjgao #4109 is closed, so I'll remove the hacky code in gene panel data.

**Comment by ersinciftci** [comment]
@jjgao Actually, according to my code comments, the hacky code was awaiting for https://github.com/cBioPortal/datahub/issues/200 to be fixed, and it's still open.

**Comment by jjgao** [comment]
@ersinciftci https://github.com/cBioPortal/datahub/issues/200 was fixed. Please remove the hacky code. Please also remove code that is using `_sequenced` and use data from `sample_profile` directly.

Maybe we should also separate the `gene-panel-data` (the 1st and last below) to a new endpoint of `is_profiled` or something? The other three gene-panels meta endpoints can remain.

![image](https://user-images.githubusercontent.com/840895/46354142-eacd0c00-c62b-11e8-9ada-7834368d28ef.png)

**Comment by jjgao** [comment]
Looks like the hacky code were removed: https://github.com/cBioPortal/cbioportal/commit/27253b856f14d1e65918ed5c3e84a262bd6b049c#diff-204c4ae53f8d0f19a485eb9e9d831867

I have updated the description of the issue above.

**Comment by jjgao** [comment]
We should still do it.
