### ISSUE TITLE
The warning message shouldn't be shown if the Internet is slow

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4228]
This issue ususlly happends when the internet is slow and the query selector hasn't gotten the full list of physical studies.

![screen shot 2018-05-15 at 4 56 13 pm](https://user-images.githubusercontent.com/5400599/40083169-528495f4-5861-11e8-9f70-f795be1b74f5.png)

**Comment by jjgao** [comment]
maybe the message should be shown after the data is loaded?

**Comment by alisman** [comment]
This has been fixed
