### ISSUE TITLE
RNA data should consistently be shown after log2 transformation

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4234]
RNA data is currently inconsistently stored in the database and shown in the front end - sometimes the data has been log2 transformed and sometimes it hasn't. We should consistently show log2 transformed data.

This could be achieved through either:
1) standardization of the data in the database
2) modification of front end code everywhere RNA data is utilized to log2 transform any data which is not already transformed

I think option 1 is probably the optimal approach, but I don't really know about the relative difficulty/time frame for these two approaches.

Thoughts? @schultzn @jjgao @ritikakundra

**Comment by schultzn** [comment]
Hmm… I like being able to see the actual normalized counts and being able to switch back and forth.  Would that still be possible with your proposed changes?

Also, how would this affect the Agilent array data, which is a ratio from a two-color array? These arrays were used in the TCGA pilot studies.

Niki.

**Comment by jjgao** [comment]
The 3rd option is to add options to the API to transform the data (log and z-score) and frontend can switch between the options.

I think we should only support log transformation for RNASeq data, not microarray data.
