### ISSUE TITLE
FUSION data not filtered out in OQL

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4237]
See examples below.

STK11: HOMDEL MUT

![image](https://user-images.githubusercontent.com/2900303/40181588-bedb2dd8-59e9-11e8-89d0-817f5880f4d1.png)

STK11: HOMDEL FUSION

![image](https://user-images.githubusercontent.com/2900303/40181558-aa465dac-59e9-11e8-9506-e01f643d757d.png)

Query links:

http://www.cbioportal.org/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=msk_impact_2017_Non-Small_Cell_Lung_Cancer&gene_list=STK11%253A%2520HOMDEL%2520MUT&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna

http://www.cbioportal.org/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=msk_impact_2017_Non-Small_Cell_Lung_Cancer&gene_list=STK11%253A%2520HOMDEL%2520FUSION&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna

**Comment by sandertan** [comment]
Specifically, in the current implementation `FUSION` falls under `TRUNC`:

`STK11: MUT=TRUNC` in http://bit.ly/2rKEvav

Also, the section regarding this can also be improved in the [documentation](https://github.com/cBioPortal/cbioportal/blob/master/docs/Onco-Query-Language.md#oql-keywords) , as it is unclear whether FUSION falls under MUT or not.

**Comment by jjgao** [comment]
@adamabeshouse when querying MUT, let's filter fusion out if possible.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1184
