### ISSUE TITLE
In expression tab scatter fix calculation of cap values

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4238]
it seems to me it should be `(expressionValue < EXPRESSION_CAP) ? Math.log2(EXPRESSION_CAP) : Math.log2(expressionValue)`, in other words `Math.log2(Math.max(expressionValue, EXPRESSION_CAP))`

**Comment by jjgao** [comment]
@alisman is this done?

**Comment by alisman** [comment]
@jjgao yes
