### ISSUE TITLE
new co-exp tab: Download Full Results button missing

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4239]
![image](https://user-images.githubusercontent.com/840895/40244495-feba1b60-5a90-11e8-9953-b882285c741a.png)

**Comment by adamabeshouse** [comment]
i thought that replaced by the download button in the table 
![image](https://user-images.githubusercontent.com/636232/40254416-652f4652-5ab1-11e8-9b3c-71207d0ec76f.png)

**Comment by adamabeshouse** [comment]
oh I see

**Comment by jjgao** [comment]
I think it's related to https://github.com/cBioPortal/cbioportal/issues/4244. Maybe we can just display all genes without filtering?

**Comment by adamabeshouse** [comment]
that would definitely make things easier

**Comment by jjgao** [comment]
As discussed, let's give it a try and see how it performs.

**Comment by adamabeshouse** [comment]
showing all data, in rc
