### ISSUE TITLE
new co-exp: when logged, change the axis label

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4242]
... append `(log10)`

**Comment by adamabeshouse** [comment]
is it better to un-log the ticks? I was about to do that. Or would you want both? (i think that would be confusing)

**Comment by jjgao** [comment]
@adamabeshouse: @alisman and I discussed -- we thought having the logged value for the tick mark is fine.

**Comment by adamabeshouse** [comment]
i had already just changed it to show unlogged tick values :D

**Comment by adamabeshouse** [comment]
unlogged, no (log10) is in rc

**Comment by jjgao** [comment]
will test this in beta and decide.
