### ISSUE TITLE
new co-exp: is it possible to list all genes with either measure above 0.3

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4244]
Is it too expensive to calculate Spearman correlations for all genes?

![image](https://user-images.githubusercontent.com/840895/40245939-08c8f870-5a95-11e8-9a0c-25f550ac3747.png)

**Comment by jjgao** [comment]
@ersinciftci maybe we can try to return data for all genes?

**Comment by ersinciftci** [comment]
@jjgao frontends sends the threshold to the API, if it sends 0, then every gene will be returned.

**Comment by adamabeshouse** [comment]
showing all data, in rc
