### ISSUE TITLE
In expression tab, handle case of multipe mutations per sample

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4245]
In expression tab, we tag data points with mutation type of the sample.  But sample may have multiple mutations.  @adamabeshouse, JJ says we have same problem in oncoprint and should use the same prioritization logic to determine which mutation type to show.  Can you advise? Can this be shared?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/shared/components/oncoprint/DataUtils.ts#L34 is where the render priority is (the suffix `_rec` means tagged as a putative driver)
