### ISSUE TITLE
Co-Expression plot issue

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#4247]
There is an error in rendering of Co-Expression plot. 
Example :
<img width="1220" alt="screen shot 2018-05-21 at 12 51 15 pm" src="https://user-images.githubusercontent.com/1380237/40323226-bc0d6d34-5d02-11e8-8053-45bbb24ff933.png">

Issue reported by user:
https://groups.google.com/forum/#!topic/cbioportal/X51e5p_dO8c

**Comment by jjgao** [comment]
We are refactoring co-expression tab and it seems working in the new tab. Let's report back to the user once we release the new one.

**Comment by aeyesilkanal** [comment]
Hi! I am the user who reported this bug. Thanks for taking care of it. I was just wondering, when are you planning on releasing the new version?

**Comment by adamabeshouse** [comment]
@aeyesilkanal thanks for reporting the bug. We just merged it into our release candidate branch, so it will be deployed in our next release, which will probably be within a couple of weeks.

**Comment by jjgao** [comment]
fixed in beta. Will release this week.
