### ISSUE TITLE
Enrichments: p-value or q-value

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4254]
Now that we switched to q-value, I see two problems:

1. with so many tests (20k), it's very difficult to reach significance. (this is probably a right signal to send)
2. many q-values are the same even the p-values are different. Should we still use p-value in the vocano plot (we don't need to significant line -- we could render the significant dots differently).

![image](https://user-images.githubusercontent.com/840895/40331421-525abef2-5d1e-11e8-8810-083d2c9eb45a.png)

![image](https://user-images.githubusercontent.com/840895/40331463-77471cc4-5d1e-11e8-986d-2be047ef0274.png)

Steps to reproduce:
1. Open cbioportal.org
2. in console: localStorage.heroku = “cbioportal-frontend-pr-1186”
3. open http://bit.ly/2lDTjHy
4. navigate to Enrichments tab of some query
5. in console: renderEnrichmentsTab($(“#enrichments-tab-tabs”).empty()[0])

**Comment by jjgao** [comment]
@tmazor any thoughts on this?

**Comment by ersinciftci** [comment]
I like the current small tooltip in volcano plot, this proposed tooltip would cover most of the plot when visible.
