### ISSUE TITLE
new enrichments: tabs not working as expected

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4255]
When clicking on Copy-number or mRNA, instead of switch to the new results, the tables are appended under the Mutations table.

![image](https://user-images.githubusercontent.com/840895/40332130-eb48a8c0-5d20-11e8-9f2d-c81c35238640.png)

**Comment by ersinciftci** [comment]
Weird, works normal on my local, might be related to the way you test it with @alisman 's script `renderEnrichmentsTab($(“#enrichments-tab-tabs”).empty()[0])`[0])`.

**Comment by ersinciftci** [comment]
Other stuff looks out of place in your screenshot too, not sure why.

**Comment by ersinciftci** [comment]
I don't think beta has this problem, so closing it.
