### ISSUE TITLE
Display name of clinical variables in plots tab

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#4256]
There is a bug in how the Plots tab displays the name of the clinical variables. If I have two studies in an instance with different display names for clinical variables, e.g. `OS_STATUS` and `DFS_STATUS` are `OS Status` and `DFS Status` in study 1, and `Test` and `Test` in study 2; and then I query ONLY study 1, I see two `Test` instead of `OS Status` and `DFS Status`.

**Comment by oplantalech** [comment]
@jjgao Can you take a look at it?

**Comment by pieterlukasse** [comment]
Basically the Plots tab is listing the study variables with the first description it can find in the DB, regardless of the study. I think you will be able to find this issue ocurring in all studies on cbioportal.org if you look closely. See for example TCGA Breast Cancer (Provisional): 

Clinical attributes matching query `days` in Plots tab:

![image](https://user-images.githubusercontent.com/2900303/40384359-90cc2a14-5e03-11e8-81f2-5cf72cb82b5f.png)

Clinical attributes matching query `days` in Oncoprint tab:

![image](https://user-images.githubusercontent.com/2900303/40384567-307112fa-5e04-11e8-90d0-6f19c9445bdc.png)

**Comment by adamabeshouse** [comment]
This code was written assuming that clinical attributes w the same clinical attribute id are going to have the same display name, and we choose one arbitrarily so as to not have duplicate entries. I'm not sure what would be best here because I don't think I understand the data properly..

**Comment by pieterlukasse** [comment]
Perhaps the previous example can still be explained by differences of attributes with data vs attributes with no data (so plots tab does not display attributes for which no data is found in any sample). Then the example below is a bit better:

Clinical attributes matching query `.` in Oncoprint tab:
![image](https://user-images.githubusercontent.com/2900303/40387454-1b997972-5e0d-11e8-8683-802fab3e8fbe.png)

Clinical attributes matching query `.` in Plots tab:
![image](https://user-images.githubusercontent.com/2900303/40387480-333cfa68-5e0d-11e8-92fc-2a8abe03cee8.png)

**Comment by pieterlukasse** [comment]
@adamabeshouse the desired solution would be for the plots tab to take the description that was specified for this attribute in the study, just as the oncoprint is probably doing. The approach you describe could be applied for multi-study queries, but for a single study query it might lead to confusion when mismatches occur. 

If the UI or other parts of the code are to rely on the assumption that the same attribute name leads to the same description, then I think we should enforce this at data loading and in the data model. But I believe this is (ironically) something we stepped away from some time ago in the data model.

**Comment by pieterlukasse** [comment]
The main problem with the current implementation is that one poorly curated study loaded into the db of a local cBioPortal installation can mess up the plots tab for all other studies in this same portal.

**Comment by jjgao** [comment]
* Attribute meta data was not study-specific -- that's probably the reason for this bug.
* Agreed with @pieterlukasse, we should use study-specific information now.
* We don't have Plots tab in multi-study view.
* @adamabeshouse is working on refactoring the tab.

@pieterlukasse @oplantalech would you have time to look into this issue?
