### ISSUE TITLE
"www.cbioportal.org/ln?q=EGFR:MUT" redirects to old cross cancer page.

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#4262]
www.cbioportal.org/ln?q=EGFR:MUT redirects to old cross cancer page.

User reported: https://groups.google.com/forum/#!topic/cbioportal/p4Bre3-F_L0

**Comment by jjgao** [comment]
fixed in https://github.com/cBioPortal/cbioportal/issues/3979. Will push out soon.
