### ISSUE TITLE
Gene list page is outdated

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4263]
The cancer gene list that is linked out from the Study view is outdated. See
http://www.cbioportal.org/cancer_gene_list.jsp
and:
https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/resources/cbio_cancer_genes.txt

**Comment by jjgao** [comment]
@pieterlukasse we plan to switch to oncokb cancer genes, but it's keeping falling between the cracks.

https://github.com/cBioPortal/cbioportal/issues/2902

@zhx828 let's do it soon once you are back.

**Comment by jjgao** [comment]
also added @kalletlak to this...

**Comment by jjgao** [comment]
closing this. Tracking in #2902.
