### ISSUE TITLE
oncokb.api.url property is being ignored

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#4266]
I have set the oncokb.api.url in my portal.properties file but the application is using the public url.

**Comment by jjgao** [comment]
@onursumer could you help look into this?

**Comment by onursumer** [comment]
Seems like we are always using the public api url even if `oncokb.api.url` exist: https://github.com/cBioPortal/cbioportal/blob/b06c8828d5843c93e1736bbeb164801155da0e46/portal/src/main/webapp/WEB-INF/jsp/global/frontend_config.jsp#L12

**Comment by onursumer** [comment]
Apparently we have two separate properties in `portal.properties` for OncoKB URL: `oncokb.api.url` and `oncokb.public_api.url`. 

@jjgao Is it safe to ignore `oncokb.public_api.url` value if `oncokb.api.url` value exists?

**Comment by onursumer** [comment]
@priti88 for now, instead of `oncokb.api.url` can you try setting `oncokb.public_api.url` and see if it works?

**Comment by priti88** [comment]
it doesn't work.   
<img width="1428" alt="screen shot 2018-05-24 at 11 09 53 am" src="https://user-images.githubusercontent.com/1380237/40494507-04a8450e-5f43-11e8-865e-616d589e2082.png">

**Comment by priti88** [comment]
Actually, it calls our oncokb instance now, so that part works. But, oncokb returns error. I will look into the error.
Thanks

**Comment by jjgao** [comment]
https://github.com/cBioPortal/cbioportal/issues/4277

**Comment by arnaudceol** [comment]
@priti88 we have the exact same issue, did you solve it?

http://localhost:8080/oncokb/api/v1/genes is working, but if I set oncokb.public_api.url=localhost:8080/oncokb/api/v1/ , it make a query to http://localhost:8080/cbioportal/proxy/localhost:8080/oncokb/api/v1/genes which returns org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.client.HttpClientErrorException: 404 null

**Comment by arnaudceol** [comment]
Ok, I figured it out. I'm working with containers (docker-compose), so I had to use `oncokb.public_api.url=oncokb:8080/oncokb/api/v1/` , where oncokb is the name of the container.
