### ISSUE TITLE
keycloak link is outdated

### ISSUE THREAD

**Issue by naismith15** [cBioPortal/cbioportal#4268]
the link to the keycloak installation instruction mentioned [here](https://github.com/cBioPortal/cbioportal/blob/master/docs/Authenticating-and-Authorizing-Users-via-keycloak.md) are outdated.

the new link is:
https://www.keycloak.org/docs/latest/server_installation/index.html

**Comment by khzhu** [comment]
@jjgao , no problems, I will update the link tomorrow.
