### ISSUE TITLE
Navigating back to OncoPrint renders black box in Safari

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4269]
To reproduce: 
1. Query with Safari 11.1 
2. Navigate from OncoPrint to a different tab
3. Navigate back to OncoPrint
<img width="1237" alt="screen shot 2018-05-24 at 15 13 41" src="https://user-images.githubusercontent.com/9624990/40488062-264e5b08-5f66-11e8-880b-2f79e9d4e585.png">

When switching tabs again, OncoPrint becomes completely white

<img width="1222" alt="screen shot 2018-05-24 at 15 21 52" src="https://user-images.githubusercontent.com/9624990/40488115-4431d2a8-5f66-11e8-9087-16ad6f4e54b5.png">

Tested on cbioportal.org and cbioportal.org/beta

**Comment by adamabeshouse** [comment]
strange.. i cant reproduce in safari 9.1.3
any console errors?

**Comment by adamabeshouse** [comment]
seems potentially related to this https://bugs.webkit.org/show_bug.cgi?id=181317

**Comment by adamabeshouse** [comment]
we might need to turn on antialiasing in safari, which will make the oncoprint less crisp, edges a little fuzzier https://bugs.webkit.org/show_bug.cgi?id=181007 @jjgao

**Comment by jjgao** [comment]
I have moved this one to icebox for now for the following reasons:

- it seems to be a difficult bug
- we have about 5% of users using Safari 11 or above
- the oncoprint tab is working initially
- only a fraction of users will go to another tab and come back to oncoprint
- while this is annoying, a user can reload the page to fix it
- maybe it's Sarari browser bug that will be solved later

Let's wait until someone complains about it.

**Comment by sandertan** [comment]
This doesn't happen anymore :)
