### ISSUE TITLE
Error in survival chart in latest rc

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4271]
If you run latest rc frontend against cbioportal.org/rc/
Go to survival chart, hover over data point, there is a run time error when creating tooltip.  Must be some data change.

**Comment by ersinciftci** [comment]
I just tested with latest rc backend and rc frontend on my local, didn't get any error.

**Comment by alisman** [comment]
Problem resolved when i reinstalled npm and ran npm build. no idea!
