### ISSUE TITLE
Why do we have  oncokb.public_api.url and oncokb.api.url ?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4277]

**Comment by jjgao** [comment]
@zhx828 @alisman could you comment what's the current logic of handling various oncokb properties?

**Comment by alisman** [comment]
@jjgao @zhx828 currently, in release-1.19.0, we are only using oncokb.public_api.url.  I find no reference to the other one.  It is not returned in our app configuration service.  @zhx828 can we do away with it?

**Comment by zhx828** [comment]
@alisman I believe that was a legacy settings. Now we only use one url, in this case oncokb.public_api.url. I haven't got a chance to clean up the properties file at the backend yet.
