### ISSUE TITLE
Tab style on enrichments

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4280]
@jjgao @inodb @ersinciftci  Should we use the "pill" tab style for these secondary tabs?  Just as we do for genes?   Or perhaps introduce another tab style to keep it separate? Lets discuss.

![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/4a77a749-c8c6-4091-8518-7c1c5f467cdb)

**Comment by jjgao** [comment]
@alisman Maybe we can use the "pill" tab but use a different color?

**Comment by ersinciftci** [comment]
I think pill is more appropriate for cases that changing the selection doesn't change the UI layout, like gene selection. I think in here it should look more like actual tabs.

**Comment by jjgao** [comment]
@ersinciftci agreed. @alisman could you help improve the style, reduce white space etc?

**Comment by ersinciftci** [comment]
@jjgao I talked to @alisman , will try to reduce the empty spaces to make it smaller.

**Comment by ersinciftci** [comment]
Does this look good?
<img width="1520" alt="screen shot 2018-06-04 at 10 56 32 am" src="https://user-images.githubusercontent.com/3595704/40924723-00d7ac70-67e6-11e8-94ca-d26a1dd6ab82.png">

**Comment by alisman** [comment]
I would also reduce the font size a tad.  I think we can revisit style when
we do single page app because it will look different with those tabs above.

**Comment by ersinciftci** [comment]
How about this?
<img width="1274" alt="screen shot 2018-06-04 at 11 13 58 am" src="https://user-images.githubusercontent.com/3595704/40925759-6d4f9f00-67e8-11e8-97fa-2f46997993f1.png">

**Comment by jjgao** [comment]
@ersinciftci Thanks. It looks good to me.

I thought the space between the main tab and sub-tab was a little too much but it is similar to other tabs, so I am fine with it.

@alisman agreed that we should improve styles once we use the whole screen.
