### ISSUE TITLE
1.14 beta Enrichments tab: Query genes should not appear in the enrichments test

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4285]
KRAS and NRAS should not appear as significantly co-altered genes - try the first example query to see what I mean.

![image](https://user-images.githubusercontent.com/11892704/40698097-65f03432-639b-11e8-9cf0-a3dd6683b5ac.png)

**Comment by ersinciftci** [comment]
@schultzn it was a feature requested by @jjgao

**Comment by schultzn** [comment]
I see. I found it very confusing - but happy to discuss with @jjgao.

**Comment by jjgao** [comment]
I found it confusing too. Maybe we should remove the query genes. @tmazor @ersinciftci thoughts?

**Comment by tmazor** [comment]
I also find it confusing. Let's remove the query genes.

**Comment by jjgao** [comment]
Should we keep the query genes for the types of data that were not queried? e.g. if the user querried for mutation and copy number, should we keep the query genes for mrna and protein? @schultzn @tmazor

**Comment by schultzn** [comment]
Sounds like a good idea. But does this introduce additional logic that has to be built in? How complex is that?

**Comment by jjgao** [comment]
@schultzn we should be able to know which types of profiles are used in the query and for those type, we can remove the query genes. @ersinciftci is that right?

**Comment by ersinciftci** [comment]
I'll need to change the APIs for this, I need to send the query genes to backend because q-value calculation happens in the backend, and having query genes in the calculation or not changes the q-value for other genes. So I'll either send the query genes or an empty gene list to APIs, depending on if the profile is queried or not.

**Comment by ersinciftci** [comment]
@jjgao If a study has 2 mRNA profiles, and the user selects only mRNAProfile1 in the query page, and then opens the mRNA enrichments and changes the dropdown to mRNAProfile2, will I not show the query genes because the user queried at least one mRNA profile, even though it was a different profile?

**Comment by ersinciftci** [comment]
@jjgao I opened the PR assuming my last comment is correct, let me know if it's not.
