### ISSUE TITLE
1.14 beta Enrichments tab: Sub-tab headers look a little big

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4287]
The Mutations / Copy-number / mRNA tab headers look bigger than most other control elements in cBioPortal:

![image](https://user-images.githubusercontent.com/11892704/40698213-f71427a2-639b-11e8-9b13-824b45022b41.png)

**Comment by ersinciftci** [comment]
We can merge this issue with https://github.com/cBioPortal/cbioportal/issues/4280

**Comment by alisman** [comment]
duplicate of #4280
