### ISSUE TITLE
1.14 beta co-expression tab: Axis labels in log scale

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4288]
When applying log scale, the scaling of the axes is strange - it looks like the numbers don't get converted to log scale, but the axis scaling changes. That may be fine, but the tick marks should be evenly spaced integers. 

Also, the y-axis label overlaps the axis numbers.

![image](https://user-images.githubusercontent.com/11892704/40698418-e098e4d0-639c-11e8-8768-ae0d8a624b95.png)

**Comment by jjgao** [comment]
It's very hard to have integer tick marks that are evenly spaced after log.

@adamabeshouse let's use logged tick marks? Please also add (log10) in axis label after doing that.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1210

**Comment by adamabeshouse** [comment]
merged into rc
