### ISSUE TITLE
1.14 beta co-expression tab: Move plot down?

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4289]
Would this look better if the sentence about the selected gene was on one line above the table and the graph, and the table and graph were top aligned?

![image](https://user-images.githubusercontent.com/11892704/40698552-952946ba-639d-11e8-95fc-daf88136eb0f.png)

**Comment by alisman** [comment]
@schultzn i agree.  
Maybe we don't need "table" but just "Genese with highest expression correlation"
The instructions ("Click on a row ...") should perhaps be in a lighter color.  @adamabeshouse try 
.text-muted and <small>

**Comment by adamabeshouse** [comment]
@schultzn @alisman That sounds fine to me. @alisman I think you trailed off there

**Comment by adamabeshouse** [comment]
got it, thanks

**Comment by adamabeshouse** [comment]
how does this look? 
![image](https://user-images.githubusercontent.com/636232/40751887-20793174-643b-11e8-8649-0b426a23c63a.png)

**Comment by schultzn** [comment]
Better!

Maybe the line “click on a row ...” could be moved above the graph somewhere and be rephrased slightly to “click on a row in the table on the left to ...”?

**Comment by adamabeshouse** [comment]
That seems weird to me.. but I'll do it if you want to 😛

**Comment by schultzn** [comment]
It would just be to save a little more space - see the mockup below.

Another way to save some space would be to shorten the correlation column headers to just Pearson and Spearman.

**Comment by schultzn** [comment]
It does not look like my mockup came through when responding via email client. Trying again.

PastedGraphic-1.png

**Comment by schultzn** [comment]
and again ...

![image](https://user-images.githubusercontent.com/11892704/40801451-f56d1db4-64e0-11e8-8893-10111338f899.png)

**Comment by adamabeshouse** [comment]
@schultzn after talking to @jjgao and @alisman we decided that those two lines were maybe unnecessary, heres the new proposal:

![image](https://user-images.githubusercontent.com/636232/40803715-4d4ac544-64e7-11e8-814c-50b1fec96082.png)

**Comment by schultzn** [comment]
That looks great!

**Comment by adamabeshouse** [comment]
changes now in the PR https://github.com/cBioPortal/cbioportal-frontend/pull/1210

**Comment by adamabeshouse** [comment]
merged into rc
