### ISSUE TITLE
Study view javascript cache not updated after new release

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#429]
Both Niki and Ethan had this problem. @zhx828 could you check on this? The LoadJS.js file has no version append -- is that the cause?

![image](https://cloud.githubusercontent.com/assets/840895/11077480/69c2434e-87ce-11e5-8c12-f4e8d55e4621.png)

**Comment by ecerami** [comment]
thanks.  the problem went away after clearing cache.  but, most users won't know to do this.


Sent from mobile phone.  Please excuse typos.

-------- Original message --------

**Comment by zhx828** [comment]
@jjgao It shouldn't be the LoadingJS. It has been changed and it's reading the appVersion global variable. Could you tell me what't the issue?

**Comment by zhx828** [comment]
This issue has been solved in https://github.com/cBioPortal/cbioportal/pull/1405
