### ISSUE TITLE
1.14 beta co-expression tab: cytoband filter only supports one cytoband

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4290]
The new cytoband filter is great, but should a user be able to filter by multiple cytobands, e.g. "-1p -11p"?

![image](https://user-images.githubusercontent.com/11892704/40698606-cf5c8194-639d-11e8-82b9-43d39064fe0c.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1213/commits

it now does logical OR on all the "positive" (no minus sign) queries, then combines that with logical AND on all the "negative" queries. so you could say "3p 11p -11p15.4 -11p15.3" and get all results for 3p or 11p, excluding 11p15.4 and 11p15.3

**Comment by schultzn** [comment]
Awesome - thanks!!
