### ISSUE TITLE
Add Total mutation "clinical attribute" to Plots tab

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4291]
Currently "Total mutations" is a "clinical attribute" in the onconprint. See screenshot below:

![image](https://user-images.githubusercontent.com/2900303/40709877-7e289eca-63f7-11e8-9574-56f8e2cd4ef0.png)

It would be good to also list this "clinical attribute" in the new Plots tab, so that both oncoprint and the plots tab are aligned on the list of clinical attributes they present.

**Comment by pieterlukasse** [comment]
hi @adamabeshouse , I discussed this with @jjgao and he thought it would be a good idea to add this to the new Plots tab that you are working on.

**Comment by adamabeshouse** [comment]
@pieterlukasse is this the same issue we were discussing with Sjoerd in slack? regarding this RFC https://docs.google.com/document/d/1BvMxEi6MDAnLJu9GS8ZQ0liExSKmmbAPyfywpLAgNSA/edit#

**Comment by pieterlukasse** [comment]
@adamabeshouse not the same issue. Actually I would like to assign this one to @oplantalech and log a new one for the one you mentioned, and perhaps assign to you?

**Comment by pieterlukasse** [comment]
@adamabeshouse : I logged a new ticket for the RFC one you mentioned: https://github.com/cBioPortal/cbioportal/issues/4332

**Comment by jjgao** [comment]
@pieterlukasse would you also be able to add `Fraction of Genome Altered`?

**Comment by pieterlukasse** [comment]
both mutation count and Fraction of Genome altered are there now :tada:
