### ISSUE TITLE
'PubMed' in Study Summary should be hidden when not available

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4292]
For example, for PanCancer Atlas no PubMed IDs are available (perhaps this is an other issue). On the Query page this is correctly greyed out, but on the Study Summary page the text is still present and active

<img width="754" alt="screen shot 2018-05-30 at 14 03 16" src="https://user-images.githubusercontent.com/9624990/40719605-60ae2546-6414-11e8-82d1-3f3bde010d3f.png">

It links to a "page not found".

<img width="771" alt="screen shot 2018-05-30 at 14 03 26" src="https://user-images.githubusercontent.com/9624990/40719327-9aacef58-6413-11e8-858c-5d264e373a8a.png">

**Comment by jjgao** [comment]
@kalletlak could you help to fix this one on master?
