### ISSUE TITLE
1.14 beta co-expression dataset tooltips updates

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4294]
I like the additional of a tooltip for the dataset selector, but I have a few tweaks:

The oncotree code should be in all capitals ("digf" in screenshot below):
![image](https://user-images.githubusercontent.com/10508276/40724897-24a1211c-63f0-11e8-961f-071e738cb621.png)

The RPPA tooltip should also list the number of genes/samples like the mRNA tooltip does:
![image](https://user-images.githubusercontent.com/10508276/40724956-45731b48-63f0-11e8-9b48-fdaa282562d0.png)

Actually, could we put the number of samples into the dropdown? So for a study with multiple mRNA datasets, it's easier to pick the one with the most samples? Not everyone will know to use the tooltip to find that information.

**Comment by adamabeshouse** [comment]
@tmazor I'm just putting the description from the database. Do we want to make these changes on the frontend or data-side?

**Comment by jjgao** [comment]
@tmazor which study is this? is `difg` in the case list name? If so, we need to fix the data.

@adamabeshouse is it easy to get the number of samples? It should be the number of profiled and selected samples.

**Comment by adamabeshouse** [comment]
Sure. so what should the message be - should I disregard the description that comes back from the database, or add onto it? Do I need to detect whether the description already mentions it, or just add the information no matter what?

**Comment by jjgao** [comment]
@adamabeshouse you can still use the description for the tooltip. For the dropdown, maybe add a number to each profile, e.g. `mRNA expression (RNA Seq V2 RSEM) (xxx samples)`

**Comment by tmazor** [comment]
@jjgao that screenshot is from the lgg_tcga study

**Comment by adamabeshouse** [comment]
theres a UI issue - that number depends on which genes are selected

**Comment by adamabeshouse** [comment]
I implemented it to do based on any gene, if any gene is profiled for a sample then its considered profiled for the count.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1213/commits
