### ISSUE TITLE
1.14 beta coexpression - table sometimes doesn't filter

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4295]
Go to the coexpression tab for this query:
http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=IDH1%2520EGFR%2520PTEN&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

Change to the microarray expression dataset and try to to filter the table - it won't filter.

There are a bunch of errors in the console and from talking to @ersinciftci it sounds like this is something he encountered on the Enrichments tab already.

**Comment by adamabeshouse** [comment]
ah okay, thanks @ersinciftci

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1210

**Comment by adamabeshouse** [comment]
merged into rc
