### ISSUE TITLE
1.14 beta coexpression - copy doesn't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4296]
When I click the copy button, the "Copied!" tooltip appears, but it doesn't actually copy anything.

**Comment by adamabeshouse** [comment]
apparently this is because its taking too long to copy, the browser won't dump the result into the clipboard. i dont think its worth working out, ill just hide the copy button

**Comment by jjgao** [comment]
ok.

**Comment by adamabeshouse** [comment]
merged into rc
