### ISSUE TITLE
1.14 beta coexpression - axis labels need more digits

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4297]
This plot has "2k", "3k" and "4k" appearing multiple times on both the x and y axis:
![image](https://user-images.githubusercontent.com/10508276/40726271-63f38ef6-63f3-11e8-8d88-13bb8d4358f5.png)

http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=IDH1%2520EGFR%2520PTEN&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1214
