### ISSUE TITLE
1.14 beta coexpression - axis labels should specify the data being plotted

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4298]
The old coexpression plot axis labels included the specific data being shown (e.g. "mRNA expression (RNA Seq V2 RSEM)") and included "(log2)" when log-scale was applied.

The new coexpression axis labels list the gene name & cytoband (which is great!) but not the actual data being plotted. Can we add a description of the specific data being plotted, like in the old version?

**Comment by adamabeshouse** [comment]
We decided to do this to use the space for cytoband, because the data is the same on both axes, and specified by the title of the plot.

**Comment by jjgao** [comment]
@adamabeshouse maybe instead of "mRNA co-expression", you can put the profile name? It can be useful when people are using the figure outside the portal.

**Comment by adamabeshouse** [comment]
that makes sense

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1210

**Comment by adamabeshouse** [comment]
merged into rc
