### ISSUE TITLE
1.14 beta coexpression - filtering by cytoband filters out partial matches also

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4299]
If I use the filter box to exclude alterations on 7p ("-7p"), then as far as I can tell, that also removes anything on 17p.

Is there a way that we can implement this filtering to be a little smarter so it doesn't filter out more than I want?

**Comment by adamabeshouse** [comment]
we can change the cytoband search to do a match only from start of string.. that actually makes more sense in general I think. what do you think? @tmazor @jjgao  that would solve this problem

**Comment by jjgao** [comment]
@adamabeshouse maybe instead of "mRNA co-expression", you can put the profile name? It can be useful when people are using the figure outside the portal.

**Comment by jjgao** [comment]
@adamabeshouse good idea.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1210

**Comment by tmazor** [comment]
@adamabeshouse sounds good to me too

**Comment by adamabeshouse** [comment]
merged into rc
