### ISSUE TITLE
PUBMED link shows up in studies with no references.

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#4302]
Even though the meta_study is empty for a pmid, studies will still show the pubmed link which leads to https://www.ncbi.nlm.nih.gov/pubmed/undefined.
https://cbioportal.mskcc.org/study?id=mixed_pdx_aacf#summary

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/cbioportal/issues/4292
