### ISSUE TITLE
1.14 beta coexpression - info button should be black

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4303]
The little info button is black in other places on the site (e.g. mutations tab) but blue here. Let's make it black for consistency.
![image](https://user-images.githubusercontent.com/10508276/40737827-d80636ba-640f-11e8-9d67-16b6daa5e4b7.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1210

**Comment by adamabeshouse** [comment]
merged into rc
