### ISSUE TITLE
1.14 beta enrichments - mutual exclusivity/co-occurence colors

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4304]
The old site used red/green colors in the log ratio column which were consistent with the colors of the label axes on the volcano plot. Let's use the same blue/red in this column that we are using for the axis labels in the volcano plot (rather than the green that is currently in place)

Also, it looks like we swapped the colors - on the old site red was mutual exclusivity and now red is co-occurence. To the extent that colors have meaning, it makes more sense to me to use red for mutual exclusivity/negative numbers and blue for co-occurence/positive numbers. Can we make that change or is there a reason to do it this way?

**Comment by jjgao** [comment]
@tmazor @ersinciftci I would propose to remove the color, ie. use black.

**Comment by tmazor** [comment]
@jjgao @ersinciftci that's fine with me

**Comment by ersinciftci** [comment]
@jjgao @tmazor remove the color from where? log ratio column or volcano plot or both?

**Comment by jjgao** [comment]
@ersinciftci just log ratio column

**Comment by jjgao** [comment]
actually both... agreed @tmazor ?
