### ISSUE TITLE
1.14 beta enrichments - adjust column widths

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4307]
I think it looks funny when the p/q-value columns are so narrow that the text runs over into a second line. This seems to happen when the "significant" tag makes the "tendency" column very wide.
![image](https://user-images.githubusercontent.com/10508276/40741557-d92310b8-6419-11e8-9b72-e6d86b62d623.png)

Can we make it so the "significant" tag is always on a second line
(like this: ![image](https://user-images.githubusercontent.com/10508276/40741597-ee3b8fe8-6419-11e8-9a3f-a30c90715df8.png) )
so then the "tendency" column can be narrower and the other columns can be wider.

**Comment by jjgao** [comment]
Good point. Since usually not many rows will have the Significant label, let's put `significant` in separate row under `co-occurrence`/`mutex`?
