### ISSUE TITLE
enrichments tab - new tooltips

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4311]
I find that the tooltips on the "Percentage of alteration in altered group" and "Percentage of alteration in unaltered group" columns are not as clear as they could be.

Let's replace the tooltip text for those columns with:
Number (percentage) of samples that have alterations in the query gene(s) that also have alterations in the listed gene.
Number (percentage) of samples that do not have alterations in the query gene(s) that do have alterations in the listed gene.

Also, the column content is really the number, not the percentage, so I think we should change the column headers to be:
Samples with alteration in altered group
Samples with alteration in unaltered group

@jjgao @schultzn do those sound ok to you?

**Comment by schultzn** [comment]
I like these proposals!

**Comment by jjgao** [comment]
@tmazor sounds good! 👍

**Comment by tmazor** [comment]
As long as we're changing these tooltips, let's actually make them specific to the data in the table. Here are tooltips for each of the different tables on the page:

Mutations:
Number (percentage) of samples that have alterations in the query gene(s) that also have a mutation in the listed gene.
Number (percentage) of samples that do not have alterations in the query gene(s) that have a mutation in the listed gene.

Deep deletions:
Number (percentage) of samples that have alterations in the query gene(s) that also have a deep deletion in the listed gene.
Number (percentage) of samples that do not have alterations in the query gene(s) that have a deep deletion in the listed gene.

Amplifications:
Number (percentage) of samples that have alterations in the query gene(s) that also have an amplification in the listed gene.
Number (percentage) of samples that do not have alterations in the query gene(s) that have an amplification in the listed gene.

mRNA/Protein:
Mean expression of the listed gene in samples that have alterations in the query gene(s).
Mean expression of the listed gene in samples that do not have alterations in the query gene(s).
Standard deviation of expression of the listed gene in samples that have alterations in the query gene(s).
Standard deviation of expression of the listed gene in samples that do not have alterations in the query gene(s).
