### ISSUE TITLE
1.14 beta enrichments - change text for copy number subtab tables

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4312]
I think the text for the copy-number subtab is out of order -- the difference between the two tables is Deep Deletion vs Amplification but that's hidden at the end of a long line of text in parentheses:
![image](https://user-images.githubusercontent.com/10508276/40744659-492cb39c-6423-11e8-8798-319b3c2bc61f.png)

Let's use this text instead:
Deep Deletion (putative copy-number alterations from GISTIC)
Amplification (putative copy-number alterations from GISTIC)

**Comment by ersinciftci** [comment]
`Putative copy-number alterations from GISTIC` is the name of the molecular profile, not sure if it's a good idea to put it in parentheses. We don't put the name of the molecular profiles in parentheses in Mutation, mRNA and Protein tabs. Maybe `Deep Deletion - Putative copy-number alterations from GISTIC` or `Deep Deletion: Putative copy-number alterations from GISTIC`?

**Comment by tmazor** [comment]
@ersinciftci let's use:
Deep Deletion - Putative copy number alterations from GISTIC
