### ISSUE TITLE
why so many rows with q-value of 0.64 in the query below?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4313]
http://www.cbioportal.org/beta/index.do?session_id=58c01624498e5df2e29105bb

![image](https://user-images.githubusercontent.com/840895/40331463-77471cc4-5d1e-11e8-986d-2be047ef0274.png)

**Comment by ersinciftci** [comment]
Same in the current old page http://www.cbioportal.org/index.do?session_id=58c01624498e5df2e29105bb

**Comment by jjgao** [comment]
hmmm... just curious how it was calculated?

**Comment by ersinciftci** [comment]
Benjamini–Hochberg false discovery rate

**Comment by jjgao** [comment]
@ersinciftci I see. Maybe we should use the same one for Mutex then?

**Comment by ersinciftci** [comment]
Mutex is just `pValue * totalCount`, so you will almost always see `1`s as q-value if we use it.

**Comment by ersinciftci** [comment]
@jjgao ah, you mean change the Mutex tab to use Benjamini–Hochberg?

**Comment by jjgao** [comment]
@ersinciftci yes. I mean using Benjamini–Hochberg for Mutex. https://github.com/cBioPortal/cbioportal/issues/4335
