### ISSUE TITLE
Plots tab missing mutation overlay when sample ids are not UPPERCASE

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4318]
When sample ids are *not* UPPERCASE, then plots tab misbehaves and does not annotate the points with their respective mutation status. 

Steps to reproduce:

1. go to http://www.cbioportal.org/index.do?session_id=5b07d63d498eb8b3d5664b69&show_samples=true . Notice there are a number of samples with mutations (screenshot below)
![image](https://user-images.githubusercontent.com/2900303/40772390-1ec18ff4-64c0-11e8-81f3-a7f79e7ef60f.png)
2. Go to Plots tab and select "Clinical Attribute" for the vertical axis (see screenshot). Select "MedR Time to Metastatic Diagnosis (Calculated Days)" for example. All samples are plotted as "Not mutated" as shown in screenshot below.
 
![image](https://user-images.githubusercontent.com/2900303/40772526-79e2920c-64c0-11e8-9fd9-a5da272ae177.png)

**Comment by pieterlukasse** [comment]
Next to the *"The Metastatic Breast Cancer Project (Provisional, April 2018)"*, the study *"Pan-Lung Cancer (TCGA, Nat Genet 2016)"* has the same problem, as shown in screenshot below:

![image](https://user-images.githubusercontent.com/2900303/40772636-d59f1052-64c0-11e8-9b15-ecd69a44f32b.png)

**Comment by pieterlukasse** [comment]
Notify: @jjgao, @adamabeshouse

**Comment by jjgao** [comment]
@adamabeshouse let's address this in the refactored code -- hopefully it's already done :)

**Comment by adamabeshouse** [comment]
i wouldnt expect this bug to be present in the new code :)

**Comment by pieterlukasse** [comment]
@adamabeshouse Ok, I will wait for the new code to be on /beta and test it there.

**Comment by adamabeshouse** [comment]
seems to be fixed now
