### ISSUE TITLE
enrichments plots formatting

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4325]
On the enrichments tab, the volcano plot & box plot have different formatting: the colors/transparency are different & the box plot has a line around each dot which the volcano doesn't have.

Is this something that bothers anyone else or it is just me?

If it's not just me, I'm not sure what the optimal solution is, but I'm curious if there are any simple tweaks we could make to make them look more consistent. I wonder if removing the line on the box plot dots would be enough?

@schultzn @jjgao @alisman any opinions on this?

![image](https://user-images.githubusercontent.com/10508276/40788518-4771aea4-64be-11e8-88cf-d50c22a2cdd6.png)

**Comment by alisman** [comment]
@tmazor 100% agree we should strive for consistency.   We'll work on this.

**Comment by ersinciftci** [comment]
FYI, I just made it look like the current page, I didn't put any personal preference in it, so I'm ok with any style :)

**Comment by jjgao** [comment]
Good idea to make them consistent.

**Comment by jjgao** [comment]
I think with the color change, we can close this. Please feel free to re-open it if needed.
