### ISSUE TITLE
1.14 beta coexpression - legend is truncated when gene name is long

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4327]
![image](https://user-images.githubusercontent.com/10508276/40789260-fff11d7e-64bf-11e8-82d6-61d62be3d645.png)

http://www.cbioportal.org/beta/index.do?session_id=5b100ad2498eb8b3d5665f8b

**Comment by adamabeshouse** [comment]
how does this look to you? 
![image](https://user-images.githubusercontent.com/636232/40811792-b2721508-6500-11e8-928d-cd03f166dc99.png)

**Comment by tmazor** [comment]
looks good to me @adamabeshouse

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1214
