### ISSUE TITLE
1.14 beta coexpression - query genes appear in two rows rather than one row with arrows

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4329]
New coexpression tab:
![image](https://user-images.githubusercontent.com/10508276/40789649-eb9cf068-64c0-11e8-8a77-dad3d2ac4fd2.png)

Mutations tab:
![image](https://user-images.githubusercontent.com/10508276/40789637-e4b6ffb4-64c0-11e8-8b5a-7eafe5cab11b.png)

**Comment by tmazor** [comment]
Also the CN Segments tab:
![image](https://user-images.githubusercontent.com/10508276/40789867-7649c786-64c1-11e8-8ace-9370e17a8556.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1213
