### ISSUE TITLE
1.14 beta enrichments - protein table extends over the page border

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4330]
The table extends too far to the right:
![image](https://user-images.githubusercontent.com/10508276/40790018-c8dd2dc6-64c1-11e8-979a-7a4c490dd970.png)

http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=RB1%2520RBL1%2520RBL2%2520CCNA1%2520CCNB1%2520CDK1%2520CCNE1%2520CDK2%2520CDC25A%2520CCND1%2520CDK4%2520CDK6%2520CCND2%2520CDKN2A%2520CDKN2B%2520MYC%2520CDKN1A%2520CDKN1B%2520E2F1%2520E2F2%2520E2F3%2520E2F4%2520E2F5%2520E2F6%2520E2F7%2520E2F8%2520SRC%2520JAK1%2520JAK2%2520STAT1%2520STAT2%2520STAT3%2520STAT5A%2520STAT5B&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

**Comment by ersinciftci** [comment]
@jjgao this is because of long hugo symbols with underscore, like `ERBB3_PY1289`. @tmazor proposed to replace underscores with spaces in hugo symbols so the line would break to the next line, wouldn't take up much space. Sounds good to you?

**Comment by ersinciftci** [comment]
Actually even that didn't fully fix the problem, so @tmazor proposed to shorten the headers for mRNA and Protein like in the screenshot. Looks good to you @jjgao ?

<img width="959" alt="screen shot 2018-06-01 at 11 37 44 am" src="https://user-images.githubusercontent.com/3595704/40849556-3d038d3e-6590-11e8-8efc-5fe2c35a6b98.png">

**Comment by jjgao** [comment]
@ersinciftci `ERBB3_PY1289` is actually a support "gene symbol" that you can use for the query, so I would not mess around that.

OK to shorten the headers. Maybe we can use something like &#956;<sub>1</sub>, &#963;<sub>1</sub>, &#956;<sub>2</sub>, &#963;<sub>2</sub> with tooltip?

**Comment by tmazor** [comment]
I generally would prefer to use words rather than symbols, but I can't come up with any other plan to make the columns narrow enough to fit - so I guess I agree, let's use sigma & mu.

**Comment by ersinciftci** [comment]
While we are at it, should I change `Percentage of alteration` column names in Mutation/CNA to `% of alteration`?

**Comment by ersinciftci** [comment]
While we are at it, should I change `Percentage of alteration` columns in Mutation/CNA to `% of alteration`?

**Comment by tmazor** [comment]
I actually requested a name change to those columns in another issue which removes the word "percentage". I think the issue with the new tooltip text also has the new column names.
