### ISSUE TITLE
CNA data on study view never finishes loading

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4331]
As reported by: https://groups.google.com/forum/#!msg/cbioportal/Y6ghwpI_PIs/bwrq725AAQAJ

The CNA table for Prostate Adenocarcinoma CNA study (MSKCC, PNAS 2014) never finishes loading:

http://www.cbioportal.org/study?id=prad_mskcc_2014#summary

http://www.cbioportal.org/study?id=prad_mskcc_2014#summary

Not sure if this is related (has a PR submitted but not reviewed/merged):

https://github.com/cBioPortal/cbioportal/issues/2406

**Comment by jjgao** [comment]
@kalletlak could you take a look when you have a chance?

**Comment by jjgao** [comment]
@kalletlak Thanks.

@ersinciftci could you look into this? prad_mskcc_2014 has no mutations profile.

**Comment by jjgao** [comment]
@kalletlak @zhx828 @ersinciftci in the new study view, when we handle gene panels, maybe we can try to improve it. Ideally, we don't have to request gene panel data for studies without gene panels.

**Comment by ersinciftci** [comment]
@jjgao I'll check. In the new study view the frontend doesn't call gene panels endpoint, backend calculates the frequencies.
