### ISSUE TITLE
Add Mutations profile to Plots tab

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4332]
Requirements are specified in [RFC 31_c](https://docs.google.com/document/d/1BvMxEi6MDAnLJu9GS8ZQ0liExSKmmbAPyfywpLAgNSA). Basically, it means adding the mutations profile data in a similar way to what we have now for CNA data in the Plots tab. One of the mockup screenshots from the RFC is shown below:

![image](https://user-images.githubusercontent.com/2900303/40790064-3191faa4-64f4-11e8-9541-f746cfb600ae.png)

**Comment by schultzn** [comment]
Good idea. Will this then also expand to box plots where you can show numerical values in relation to mutation status for a given gene, so a two box box-plot, one for "mutated", one for "not mutated"?

**Comment by pieterlukasse** [comment]
@schultzn yes, the box plot should also be there, but I was thinking of a box plot with one box per mutation status instead of only "mutated" and "not mutated". Or do you think the variant classification is not really relevant in this plot?

**Comment by schultzn** [comment]
It would be nice to have the variant classification as an option - I am sure users will want the ability to combine all mutations.

**Comment by jjgao** [comment]
@pieterlukasse maybe we can split into two attributes: `mutation by type` and `mutant vs wildtype`?

**Comment by jjgao** [comment]
Discussed this with @pieterlukasse. 

One option: add the following options (another dropdown below `profile name`) when a mutation profile is selected:

`Mutations by type`: missense, inframe, truncating, wild-type, (not sequenced?)
`Mutated vs wildtype`: mutated, wild-type, (not sequenced?)
`Fusions`: fused (?), not fused

Also thinking of support `altered` vs `not altered`. Maybe we can add another option in the `Profile Type` drop-down called "Queried alteration"?

@schultzn let's discuss this in person.

**Comment by Sjoerd-van-Hagen** [comment]
@adamabeshouse how is it going?

**Comment by adamabeshouse** [comment]
@jjgao noone has discussed this with me :D

**Comment by Sjoerd-van-Hagen** [comment]
@adamabeshouse good to know... you are working on the plots tab, right?

@jjgao I think @pieterlukasse  discussed this with you right? We would to the mutation count and fraction genome altered and then Adam would work on the mutation type?

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen yes.

@adamabeshouse please work on this after we roll out 1.15.

**Comment by adamabeshouse** [comment]
ok i added it to 1.16

**Comment by jjgao** [comment]
Reviving this. @adamabeshouse could you do the followings?

- `Data Type` dropdown: `Clinical Attribute`, `Mutation`, `Copy Number`, `mRNA`, `Protein`, `Methylation` (hide when not available)
- When `Mutation` is selected, the next dropdowns are `Mutation Data Profile`, `Mutation Count by`, and `Gene`
- `Mutation Data Profile` will usually have only one profile which should be automatically selected
- `Mutation Count by` will have the following items: `Mutation Type`, `Mutated vs Wild-type`. (Treat fusion as one type of mutations for now.)
- `Gene` dropdown will remain the same.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen @pieterlukasse Please comment if you would like to make changes to the design above.

**Comment by pieterlukasse** [comment]
@jjgao thanks, this is good. One small remark I have is only for  `Mutation Data profile`: afaik there is always only one profile, so perhaps this box can be removed in this case.

**Comment by adamabeshouse** [comment]
@pieterlukasse @jjgao lets omit the box and use that selector for `Mutation Count By`

**Comment by adamabeshouse** [comment]
@pieterlukasse @jjgao what order should we put the mutation types in?

**Comment by adamabeshouse** [comment]
@pieterlukasse @jjgao for choosing mutation type, should we use the same priority algorithm as the oncoprint?

**Comment by pieterlukasse** [comment]
@adamabeshouse I would say, the same algorithm used to color the samples in the plots tab.

**Comment by pieterlukasse** [comment]
did some tests now on cbioportal.org and it looks great! Thanks @adamabeshouse, @jjgao and @schultzn
