### ISSUE TITLE
use Benjamini–Hochberg for Mutex q-value

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4335]
Currently, in Mutex we are using Bonferroni adjusted p-Value and in Enrichment we are using Benjamini–Hochberg q-value. Let's change Mutex to use Benjamini–Hochberg.

**Comment by ersinciftci** [comment]
Any reason we call it adjusted p-Value in Mutex, instead of q-value?

**Comment by jjgao** [comment]
@ersinciftci let's fix this since we have two tabs using Benjamini–Hochberg now.
