### ISSUE TITLE
multi-study query interface: populate case set selection based on sample lists in studies

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4337]
- `_all` => `All`
- `_sequenced` => `Cases with mutations data`
- `_cna` => `Cases with copy number alterations data`
- `_cnaseq` => `Cases with both mutataions and copy number alterations data`

Maybe the case list IDs should be sent over to the results page? For existing sessions w/o case lists, we can use the current logic, or always select `_all`.

Is it also possible to get the number of samples for each? For multiple phisical studies, you can add them up, but for virtual studies, you need to intersect with the one in the vs.

![image](https://user-images.githubusercontent.com/840895/40805679-096f05aa-64ed-11e8-9d20-918fe3ac48ea.png)

**Comment by kalletlak** [comment]
closed via https://github.com/cBioPortal/cbioportal/pull/4341
