### ISSUE TITLE
Replace black by white in color scheme for expression in OncoPrint's heatmap

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4344]
Recently @fedde-s used a beautiful color map for the gene set scores in OncoPrint's heatmap. Using the expand function, it's possible to view the expression of individual genes as well. Compared to the colors for gene set scores, the colors for expression values are less nice. I think that if black is replaced by white, the heatmap will look much nicer. Perhaps black was once used to distinguish between missing values and 0. Currently, missing values have a distinguishable line in it, making this less an issue.

We can the RdBu color scheme from http://colorbrewer2.org for this, just like the PiYG scheme Fedde used for gene set scores. 

### Current colors
<img width="1172" alt="screen shot 2018-06-06 at 09 43 15" src="https://user-images.githubusercontent.com/9624990/41023977-334f3bda-696e-11e8-8749-8f0952266ccb.png">

### Proposed gene expression color scheme
<img width="1085" alt="screen shot 2018-06-06 at 09 27 25" src="https://user-images.githubusercontent.com/9624990/41023172-e7387100-696b-11e8-9df7-b4df6d0bea9b.png">

**Comment by jjgao** [comment]
I like the proposal, but I am not a heatmap guy :)

@schultzn @tmazor any comments?

**Comment by schultzn** [comment]
Sounds like a good idea. Any chance we can support multiple and allow users to choose?

**Comment by tmazor** [comment]
Sounds good to me

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao who will have some time to implement this?

**Comment by jjgao** [comment]
I think replacing the schema with another one should be really easy to do. Adding an option for different schema may require some more work. 

@adamabeshouse thoughts?

**Comment by adamabeshouse** [comment]
@jjgao you were correct - it would be very easy to replace the color scheme. it would be more work, but possible, to allow the user to choose, for example in an oncoprint track menu

**Comment by jjgao** [comment]
Thanks, @adamabeshouse. Let's keep it on the backburner for the moment.

**Comment by Sjoerd-van-Hagen** [comment]
We may have a chance to work on this. How about we use the same color scheme as for the generic assay data? @jjgao

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen it would be great if you can find some bandwidth. Would you allow the user to choose a schema?

**Comment by Sjoerd-van-Hagen** [comment]
No, that is not part of the plan but we may work on the heat map, and then it should be a small effort to change the colors.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen sounds good. Thanks
