### ISSUE TITLE
Deploying a cbioportal instance outside of a local host

### ISSUE THREAD

**Issue by ashraf123456789** [cBioPortal/cbioportal#4349]
Hello,

We are trying to deploy a cbioportal instance in a private server where multiple scientists can have access to. We are able to deploy the homepage, but import has be an issue. What we did so far:

1. Set up cBioPortal locally and created the war file
2. Deployed the war file on a linux server
3. cbioportal instance is up and running on linux
4. Copied the "importer" to some path on the server ( my home directory )
5. Error -- 
Expected to find 1 scripts-*.jar, but found: 0

Do we need to copy master folder ?  set up portal_home??

**Comment by n1zea144** [comment]
The scripts jar file is created after building the code.  It can be found in $PORTAL_HOME/scripts/target, e.g., scripts-1.11.1-SNAPSHOT.jar.  Can you verify that it exists and yes, make sure that the PORTAL_HOME shell variable has been defined.  

This page has more info:
http://cbioportal.readthedocs.io/en/latest/Using-the-metaImport-script.html <http://cbioportal.readthedocs.io/en/latest/Using-the-metaImport-script.html>

Let us know if you have any further questions.

Benjamin

**Comment by nhuff** [comment]
Where do the import scripts get their Database connection information from?  Are they hard coded at build time?  The import scripts always seem to be trying to connect to mysql on localhost, but none of the config files have that as the jdbc url.

**Comment by jjgao** [comment]
@nhuff could you please send your questions to cbioportal@googlegroups.com? We will pick up user questions more promptly there. Thanks.
