### ISSUE TITLE
1.14 beta coexpression - table buttons should be consistent with other tabs

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4356]
The buttons under the table look like this:
![image](https://user-images.githubusercontent.com/10508276/41246639-a8d07176-6d79-11e8-9e94-9b5edfb0f3c1.png)

The button in the middle should be blue to match the arrows. Also, it looks like a button but doesn't actually do anything. On other pages, that is actually a "show more" button. For example, on the mutations tab:
![image](https://user-images.githubusercontent.com/10508276/41246729-f428975c-6d79-11e8-8ced-028cbbbd3f60.png)

Is there a reason not to have "show more" here?

**Comment by adamabeshouse** [comment]
@tmazor I think we just didn't consider using 'Show More' in this case. It would be easy enough to set up. The button in the middle isn't blue because it's not clickable, its just a display.

**Comment by tmazor** [comment]
Gotcha - let's change it to "Show More" so it fits with other tables on the site.
