### ISSUE TITLE
run Mutex test in OncoPrinter tool

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4363]
See user request: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/cbioportal/wL7wd445Png

**Comment by adamabeshouse** [comment]
report scores for every pair of tracks?

**Comment by jjgao** [comment]
@adamabeshouse yes. Maybe @dippindots can help with this later once he finishes https://github.com/cBioPortal/cbioportal/issues/4514. Ideally the same mutex components can be used here?
