### ISSUE TITLE
For internal portal, show OncoKB therapy description instead of references only

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4365]

**Comment by zhx828** [comment]
@jjgao this is how's gonna look like for private portal.
![screen shot 2019-02-07 at 6 04 03 pm](https://user-images.githubusercontent.com/5400599/52448783-fad98880-2b02-11e9-9ac1-325d261f8122.png)

But we have issues for most of L4 and R2. We only have PMIDs in the description.
![screen shot 2019-02-07 at 6 04 20 pm](https://user-images.githubusercontent.com/5400599/52448787-fdd47900-2b02-11e9-8233-7441739a7ac2.png)

**Comment by jjgao** [comment]
Looks good!

For L4 and R2, can we at least make them into a sentence in the curation interface, e.g. "This assertion is supported by (PMIDs:...)."?

**Comment by zhx828** [comment]
@jjgao Should I use the same icon or change to information icon when the description is available? 

![screen shot 2019-02-07 at 6 22 51 pm](https://user-images.githubusercontent.com/5400599/52449466-789e9380-2b05-11e9-8790-442403f017f8.png)

![screen shot 2019-02-07 at 6 23 00 pm](https://user-images.githubusercontent.com/5400599/52449457-72a8b280-2b05-11e9-8a24-a829d4b8ed0c.png)

**Comment by jjgao** [comment]
I think the same icon is fine as we will always have some citations...
