### ISSUE TITLE
support a list of sample ids as a parameter for legacy network.do 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4369]
@ersinciftci Could you look into the code and see if we can support sample IDs as a parameter? Currently it only support case_set_id and case_set_key. Since we don't want to support case_set_key in the new frontend repo, it would be necessary to post all sample IDs.

**Comment by alisman** [comment]
@ersinciftci did we do this?

**Comment by ersinciftci** [comment]
not yet, maybe @onursumer can look at it as I won't be working on portal until Monday.

**Comment by jjgao** [comment]
@onursumer please prioritize this one since this is required for this release.
