### ISSUE TITLE
add warning if tcga pan cancer study is selected together with other tcga studies (same cancer type)

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4373]
![image](https://user-images.githubusercontent.com/840895/41499147-90e82954-7149-11e8-989d-b38e5f8e27e8.png)

**Comment by alisman** [comment]
@jjgao is screenshot you posted a mock of what the "warning" state should look like?  i.e. non-pan in red with alert when corresponding pancan is selected.

**Comment by alisman** [comment]
@jjgao we have an existing warning system (currently disabled) which shows if a studies public and provisional version are seleceted at same time.   detection of this condition is based purely on study id convention.   we can do same thing with pan can yes?   and do we still want to the old "overlapping" study warning disabled?
