### ISSUE TITLE
[enrichments] log before t test for RNA seq data

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4374]
The old enrichments tab notes that the data has been log-ed:
![image](https://user-images.githubusercontent.com/10508276/41562278-21cd49be-731a-11e8-9267-281a8f99af21.png)
and
![image](https://user-images.githubusercontent.com/10508276/41562284-276c28c2-731a-11e8-9e05-672ebb120805.png)

On beta, neither of those "(log)" notations are present. Let's add those back but additionally specify that the data is log2 transformed, since users will wonder if it's log2 or log10 (see: https://groups.google.com/forum/#!topic/cbioportal/EICtfJTspGk)

**Comment by tmazor** [comment]
Ersin & I got to talking and I’m worried there is a larger problem in some of the calculations on the enrichments tab - this problem exists on the current production and was re-implemented in the new tab. RNA data is sometimes in the database as log values and sometimes not log values. When data in the database is log values, then the enrichments tab calculates the mean of those logs. When data in the database in not log values, then the enrichments tab takes the mean of the un-log-ed values and then takes the log of that mean. Taking the log of a mean is not the same as taking the mean of log values (https://stats.stackexchange.com/a/250213). What is the preferred behavior here @jj? Given that this is a larger issue, I don’t think this needs to hold up 1.14 but we need to standardize the math and then add some clarification to the page (via tooltips or something) once we do. We can also ignore this issue until we fix this.

**Comment by jjgao** [comment]
@tali @ersin that’s a good point. In principle, it’s better log transform the rna seq data (to make it more normal-like distribution) for t test. Let’s create an issue and follow up on that.

When doing log transformation, we need to handle negative data: #4186

**Comment by jjgao** [comment]
@ersinciftci the problem is that some of the non-logged rnaseqv2 data contains some negative values: https://gist.github.com/inodb/26e77fb017d6b7b639a0d17d58b79728#file-mrna_distribution_cbioportal-ipynb

**Comment by tmazor** [comment]
Ok, @ersinciftci & I talked some more and I think we have this figured out. My explanation from this morning is wrong & based on some confusion -- we are applying log & mean in the appropriate order. Instead, what we have is a minor disconnect between backend and frontend logic.

Thanks to @jjgao 's explanation on slack, I now understand that in the database RNA-seq data is not log transformed while microarray data is log2 transformed. The backend for the enrichments tab checks to see if the dataset is RNA-seq, and if it is, it applies a log2 transformation on the data. So the front end is always getting log transformed data. However, the front end doesn't know this.

The "mean in altered" and "mean in unaltered" columns show the mean of the data returned from the backend -- so this is always the mean of already log transformed data. The disconnect appears in the log ratio column. Here, the front end checks to see if the molecularProfileDatatype is LOG_VALUE or LOG2_VALUE. If it is, then the values in that column are the difference of the means. If it isn't, then the values in that column are the log2 transformed difference of means. What this means is that the log ratio column for microarray data (which is stored in the database as log-transformed) is (mean altered - mean unaltered) whereas the log ratio column for RNA-seq data is log2(mean altered / mean unaltered) even though the RNA-seq data has also already been log transformed in the backend.

Here is what I think we need to do to fix this and make things more clear:
1) change the logic for the log ratio column to always take the difference of the means since the data is already log transformed
2) change the backend to report log10(RNA-seq) rather than log2(RNA-seq) for consistency with co-expressions tab and easier interpretation
3) add text on the enrichments tab that specifies if data is log2 or log10 transformed (either with tooltips or in the table header)
4) add text on the coexpression tab that makes clear that microarray data is already log2 transformed (and keep the existing text that makes clear RNA-seq data gets log10 transformed)
5) we need a way to deal with pancan expression data which can have negative values in the not-log-transformed data (I don't have a solution for this one but don't want it getting lost in this long thread)

**Comment by jjgao** [comment]
Thanks, @tmazor @ersinciftci, for figuring this out. I know it is confusing.

@ersinciftci could you handle the first two items soon? 

For # 3&4, we will have to change the text for microarray-based expression data, so I would not worry about it for now. I am also rethinking the log2 vs log10 decision and saw this post (https://www.researchgate.net/post/Why_do_we_usually_use_Log2_when_normalizing_the_expression_of_genes). Maybe we should revert back to log2 in Expression and Co-Expression.

We will need to find a solution for # 5 too. I don't understand where the negative data come from. FYI - There is some information about the RNAseq data we are using here (https://www.biostars.org/p/106127/). One option would be reset all numbers that are less than a small number (e.g. 0.001) before log transformation -- that's what we did in Expression.

**Comment by ersinciftci** [comment]
@jjgao in the backend, we log if the profile id has `rna_seq` in it. In the frontend when calculating the log ratio we log again if `(molecularProfileDatatype === LOG_VALUE || molecularProfileDatatype === LOG2_VALUE || hasNegativeValue)` is false.

**Comment by jjgao** [comment]
@ersinciftci I see. Let's get rid of the frontend logic (# 1). 

@alisman @adamabeshouse could you comment on how we deal with negative and small numbers when doing log transformation for the expression and co-expression tab?

**Comment by adamabeshouse** [comment]
@jjgao in coexpression, the log argument has a minimum possible value: 
```
private logScale(x:number) {
        return Math.log10(Math.max(x, MIN_LOG_ARGUMENT));
}
```

negative values are not handled explicitly, in the code log is only allowed to be turned on if the profile contains the string "rna_seq" and does not contain the string "zscore", in other words positive data.

**Comment by jjgao** [comment]
@alisman what's the min value you used in Expression?

**Comment by ersinciftci** [comment]
#1 is on production now.

**Comment by jjgao** [comment]
We found out that the negative data was due to the batch correction. 

"
RNA Data Batch Correction

The expression data for mRNA and miRNA were batch-corrected to adjust for platform differences between the GAII and HiSeq Illumina sequencers. For mRNA, additional adjustments were made for different sequencing centers (The University of North Carolina [UNC] and British Columbia Cancer Agency [BCCA]) and a plate effect observed in PRAD. For the mRNA data, first batch 312 and 320 PRAD were adjusted to remove batch effects. UNC GA samples (UCEC, COAD, READ) were adjusted to the UNC HiSeq data. Genes with mostly zero reads or with residual batch effects (∼10% of genes) were removed from the adjusted samples and replaced with NAs. A similar adjustment was made for BCCA GAII-sequenced samples (LAML, STAD, ESCA) to HiSeq. Genes were adjusted using a novel algorithm called EB++; a variant of the Empirical Bayes / ComBat algorithm with training and testing features added.
"

**Comment by jjgao** [comment]
@ersinciftci I was reading through this thread and got confused. Do we have any logic in the frontend to determine whether a profile has been logged?

**Comment by ersinciftci** [comment]
@jjgao I don't think we do anymore, backend has all the logic and frontend assumes it's all logged.

**Comment by jjgao** [comment]
@ersinciftci thanks! thought you were on vacation :)
