### ISSUE TITLE
digitalslidearchive call not working / tissue tab hanging

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4375]
Steps to reproduce:

Try this URL:

http://www.cbioportal.org/case.do#/patient?caseId=TCGA-BL-A0C8&studyId=blca_tcga_pub&tab=tissueImageTab

The call to http://www.cbioportal.org/proxy/cancer.digitalslidearchive.net/local_php/get_slide_list_from_db_groupid_not_needed.php?slide_name_filter=TCGA-BL-A0C8
will hang.

**Comment by pieterlukasse** [comment]
Notify: @jjgao

**Comment by jjgao** [comment]
I am reaching out to cdsa.

**Comment by pieterlukasse** [comment]
@jjgao it looks like it is still hanging.

**Comment by jjgao** [comment]
@pieterlukasse they are still working on it...

**Comment by schultzn** [comment]
Now 404 Not Found. Is this the same issue?

It looks like they updated the Cancer Digital Slide Archive website.

http://cancer.digitalslidearchive.net/

**Comment by jjgao** [comment]
They have changed their API and will send us the new API format.

**Comment by jjgao** [comment]
Update

There is a working instance of CGSA now: https://docs.google.com/document/d/1J8SZKz8t6DnOzMnyOKdsRx4R7H1kba-uKRp4Q1R-1tY/edit?ts=5ba543ea

API to determine whether a patient has images: https://api.digitalslidearchive.org/api/v1/tcga/image?caseName=TCGA-02-0006&

The direct page to a patient:
https://cancer.digitalslidearchive.org/index.html?cohort=gbm&patientId=TCGA-02-0015&

We will need to get to the patient page without the cohort parameter though. I have emailed them about it.

**Comment by jjgao** [comment]
It's working now. 

https://api.digitalslidearchive.org/api/v1/tcga/image?caseName=TCGA-02-0015
https://cancer.digitalslidearchive.org/index.html?patientId=TCGA-02-0015

@alisman could you work on this soon and renable the image tab?
