### ISSUE TITLE
[Enrichments] making the header more compact for expression and protein

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4378]
@tmazor @ersinciftci the tables in Expression and Protein are really long. Maybe we can make the header a little more compact?

currently
![image](https://user-images.githubusercontent.com/840895/41616074-02a5bb1e-73cb-11e8-905d-af8aa617ff14.png)

proposed:

Altered	&nbsp;&nbsp; Unaltered
group	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; group

 &#956;<sub>1</sub> &nbsp;&nbsp; &#963;<sub>1</sub>	&nbsp;&nbsp;&nbsp;&nbsp; &#956;<sub>2</sub> &nbsp;&nbsp; &#963;<sub>2</sub>

**Comment by tmazor** [comment]
looks good to me!

**Comment by ersinciftci** [comment]
@jjgao not sure, I'm assigning @alisman too, he would know better.
