### ISSUE TITLE
paad_qcmg_uq_2016 has RNA-seq data but co-expression and enrichments/RNA tabs don't appear

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4380]
This study has RNA-seq data -- I can query it and it appears in the oncoprint, but none of the RNA-specific tabs (co-expression or enrichments/RNA) appear:
![image](https://user-images.githubusercontent.com/10508276/41617917-b641e540-73cf-11e8-9f68-6ce36ed1535f.png)
![image](https://user-images.githubusercontent.com/10508276/41617924-bb1f9e54-73cf-11e8-8922-ac7da0c7488c.png)

http://www.cbioportal.org/beta/index.do?cancer_study_id=paad_qcmg_uq_2016&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=paad_qcmg_uq_2016_all&gene_list=KRAS%2520TP53%2520EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=paad_qcmg_uq_2016_mutations&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=paad_qcmg_uq_2016_rna_seq_v2_mrna_median_Zscores&show_samples=false&clinicallist=PROFILED_IN_paad_qcmg_uq_2016_mutations%2CPROFILED_IN_paad_qcmg_uq_2016_rna_seq_v2_mrna_median_Zscores

**Comment by jjgao** [comment]
It's data issue. I am moving it to datahub.

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #243](https://github.com/cBioPortal/datahub/issues/243) via [**ZenHub**](https://www.zenhub.com/)
