### ISSUE TITLE
Query page shows wrong number of genes depending on sets of genes configuration 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4385]
Steps to reproduce:
1. go to https://cbioportal.thehyve.net/cbioportal
2. scroll to the bottom of the "Enter Genes" select box (see screenshot below):
![image](https://user-images.githubusercontent.com/2900303/41713397-499c2ffc-754d-11e8-8912-0ac2d31d009c.png)
3. notice that "Test 1" and "Test 2" are the same OQL query but report different number of genes in the select box. The only difference is that one of them has `;` as separator. 

This is the respective json configuration:
```
{
        "id": "Test 1",
        "genes": ["TP53:MUT; TP53:HOMDEL;"]
}, {
        "id": "Test 2",
        "genes": ["TP53:MUT", "\\nTP53:HOMDEL"]
}
```
The frontend seems to count the length of the list and report this as the number of genes, instead of analyzing the OQL itself to report the number of unique genes. 

Desired solution:
- let the frontend analyze the OQL itself and report the number of unique genes based on that.
Alternative solution: 
- clearly document how to influence the count by using different json configuration as shown above.

**Comment by pieterlukasse** [comment]
Another bug in this part is: when the configuration is as follows: 
```
{
        "id": "Test 3",
        "genes": ["TP53:MUT;", "TP53:HOMDEL;"]
}
```
the item cannot be selected from the select box (not possible to click on it). You can also find this on our server https://cbioportal.thehyve.net/cbioportal .

**Comment by alisman** [comment]
@jjgao @inodb it seems the existing configuration schema (array of genes) is not really appropriate (as @pieterlukasse explains above).   Ideally, we would change schema so that user could pass oql and we parse it.   Do we need to be backward compatible at this point or could we change it?

**Comment by jjgao** [comment]
@pieterlukasse as you know, the current list only support gene list not oql, so I would not call it a bug :)

But I think it's a good idea to support OQL for this list. Maybe we can change the data to:

```
{
	"id": "q1",
	"name": "TP53 pathway oncogenic alterations",
	"oql": "TP53: MUT HOMDEL; CDKN2A: MUT HOMDEL; MDM2: MUT AMP; MDM4: MUT AMP;"
}
```

@pieterlukasse do you think you can help with this?

**Comment by pieterlukasse** [comment]
hi @jjgao, @alisman,  any updates?

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen I am wondering if anyone at Hyve would be interested in taking this?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao I might have a client that would like to have this fixed but it would take some time to set that up.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen we can wait. thanks.
