### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ashraf123456789** [cBioPortal/cbioportal#4388]
Hello,

I received this error when running an import: 

Checked DB schema version: (expected: 2.4.0) (found: -1)
Error, probably due to this version of the portal being out of sync with the database. Run the database migration script located at PORTAL_HOME/core/src/main/scripts/migrate_db.py before continuing.

This is from an external server rather than a localhost. I only added the core,src, and script. We needed to limit the file size of the master folder due to space.

Please let me know what you think. Thank you!

Best,

-Ashraf

**Comment by jjgao** [comment]
@ashraf123456789 could you please send your question to cbioportal@googlegroups.com? Thanks.
