### ISSUE TITLE
validateStudies.py crashes for skcm_tcga_pan_can_atlas_2018

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4391]
This issue was reported in the Datahub channel and refers to an issue found on CircleCI when validating the SKCM TCGA PanCancer study (`skcm_tcga_pan_can_atlas_2018`) 

DataHub PR with the problematic study:
https://github.com/cBioPortal/datahub/pull/239

CircleCI error:
https://circleci.com/gh/cBioPortal/datahub/279?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I reproduced this issue locally when using the same wrapper to validate multiple studies, [`validateStudies.py`](https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/scripts/importer/validateStudies.py). The study data for`skcm_tcga_pan_can_atlas_2018` can be found here: https://github.com/cBioPortal/datahub/tree/eb96197c4750ce04c09cfcb12d3806a343663588/public/skcm_tcga_pan_can_atlas_2018

Strangely enough, when validating using validateData.py on this study, there is no crash. Most likely this has something to do with how the logger is controlled in `validateStudies.py`.

**Comment by fedde-s** [comment]
I can't find the validateStudies.py script in cBioPortal v1.13.2. Is it to be introduced in v1.14.0?

**Comment by fedde-s** [comment]
The issue isn't just present in the master branch, it has indeed been released in v1.14.0.

**Comment by fedde-s** [comment]
Pull request #4453 should fix it.

**Comment by sandertan** [comment]
Thanks for the fix!
