### ISSUE TITLE
Create auto-generated sitemap and submit to Google webmaster console

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4394]
I have created dynamically generated sitemaps (actually a whole set of sitemaps) which will list:
1. Link for every study summary page
2. Link for every patient in every study

We could also do every sample in every patient.  

This is a lot of links, but if we want to be able to search on IDs and have portal show up, this is surrest way.

**Comment by jjgao** [comment]
Thanks, @alisman. 

Is there a way to submit meta data too, e.g. study name?

I am also thinking about creating links to genes and frequent mutations. But that can go later.
