### ISSUE TITLE
Set X-frame options on network.htm serve from cbioportal.mskcc.org

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4400]
Right now network tab cannot be loaded into iframe because of X-FrameOptions header set to same origin (i.e. don't show me in an iframe).  We need to remove that header.

http://www.cbioportal.org/beta/index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit

**Comment by inodb** [comment]
@alisman I think this is working now:

Added the following to `webapps/frontend/WEB-INF/web.xml` 
```
<filter>
  <filter-name>httpHeaderSecurity</filter-name>
  <filter-class>org.apache.catalina.filters.HttpHeaderSecurityFilter</filter-class>
  <async-supported>true</async-supported>
  <init-param>
    <param-name>antiClickJackingEnabled</param-name>
    <param-value>false</param-value>
  </init-param>
  <!--<init-param>
    <param-name>antiClickJackingOption</param-name>
    <param-value>DENY</param-value>
  </init-param>-->
</filter>
<filter-mapping>
  <filter-name>httpHeaderSecurity</filter-name>
  <url-pattern>/*network.htm</url-pattern>
</filter-mapping>
```

Was able to include the `network.htm` now in an iframe

**Comment by inodb** [comment]
feel free to re-open if it's not working for u

**Comment by zhanxw** [comment]
Where can I find this file `webapps/frontend/WEB-INF/web.xml`?

I tried to edit `portal/src/main/webapp/WEB-INF/web.xml` instead, packaged it `mvn -DskipTests install`, and deployed it, but the response header still failed:

```
> curl -sD - -o /dev/null 'http://localhost:8080/reactapp/network/network.htm?1.0&apiHost=%2F%2Fqbrc2.swmed.edu%2F#%7B%22gene_list%22%3A%22SOX9%20RAN%20TNK2%20EP300%20PXN%20NCOA2%20AR%20NRIP1%20NCOR1%20NCOR2%22%2C%22genetic_profile_ids%22%3A%22acc_tcga_pan_can_atlas_2018_mutations%20acc_tcga_pan_can_atlas_2018_gistic%22%2C%22cancer_study_id%22%3A%22acc_tcga_pan_can_atlas_2018%22%2C%22Z_SCORE_THRESHOLD%22%3A2%2C%22xdebug%22%3A%220%22%2C%22netsrc%22%3A%22cgds%22%2C%22linkers%22%3A%2250%22%2C%22netsize%22%3A%22large%22%2C%22diffusion%...%20TCGA-OR-A5L8-01%20TCGA-OR-A5L9-01%20TCGA-OR-A5LA-01%20TCGA-OR-A5LB-01%20TCGA-OR-A5LC-01%20TCGA-OR-A5LD-01%20TCGA-OR-A5LE-01%20TCGA-OR-A5LF-01%20TCGA-OR-A5LG-01%20TCGA-OR-A5LH-01%20TCGA-OR-A5LI-01%20TCGA-OR-A5LJ-01%20TCGA-OR-A5LK-01%20TCGA-OR-A5LL-01%20TCGA-OR-A5LM-01%20TCGA-OR-A5LN-01%20TCGA-OR-A5LO-01%20TCGA-OR-A5LP-01%20TCGA-OR-A5LR-01%20TCGA-OR-A5LS-01%20TCGA-OR-A5LT-01%20TCGA-OU-A5PI-01%20TCGA-P6-A5OH-01%20TCGA-PA-A5YG-01%20TCGA-PK-A5H9-01%20TCGA-PK-A5HA-01%20TCGA-PK-A5HB-01%20TCGA-PK-A5HC-01%22%7D'
HTTP/1.1 200
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: total-count,sample-count
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Accept-Ranges: bytes
ETag: W/"96155-1562103946000"
Last-Modified: Tue, 02 Jul 2019 21:45:46 GMT
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
Content-Type: text/html
Content-Length: 96155
Date: Thu, 29 Aug 2019 10:30:35 GMT
```


It seems webapp-runner does not pick up the settings.
Do  you have suggestions?

**Comment by zhanxw** [comment]
I found it is related to the settings in portal/src/main/webapp/WEB-INF/web.xml:
Comment the lines below will make it work. 


     <filter>
         <filter-name>springSecurityFilterChain</filter-name>
         <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
     </filter>

     <filter-mapping>
       <filter-name>springSecurityFilterChain</filter-name>
       <url-pattern>/*</url-pattern>
     </filter-mapping>

Is that a better to way to solve this problem?
