### ISSUE TITLE
categories of mutations in different tabs

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4404]
Currently, Expression and Plots tab uses sub-categories for truncating mutations, while oncoprint render truncating mutations in the same way. Since the Plots tab rendering was designed before we separated mutation types in OncoPrint, maybe it's time to make them consistant? How about:

- [ ] switch to the OncoPrint colors for Expression and Plots tabs
- [ ] add fusions
- [ ] add copy number alterations as different borders (similar to https://github.com/cBioPortal/cbioportal/issues/4006)
- [ ] ~~support putative drivers vs VUS in Expression and Plots tabs (?)~~
- [ ] ~~do we want to support an option to show the current detailed mutation types? If so, should we do it in oncoprint too?~~

Expression and Plots tab:
![image](https://user-images.githubusercontent.com/840895/41884559-fe18f556-78c1-11e8-8611-62d9d20818c8.png)

OncoPrint:
![image](https://user-images.githubusercontent.com/840895/41884662-556e8848-78c2-11e8-9b20-9dedd72b8056.png)

to: @schultzn @tmazor @ecerami 

cc: @adamabeshouse @alisman

**Comment by jjgao** [comment]
@schultzn liked the idea.

@adamabeshouse could you mock it up for Plots tab, e.g this query: http://www.cbioportal.org/index.do?session_id=5b32ab0f498eb8b3d566bb6d#plots

![image](https://user-images.githubusercontent.com/840895/41939355-84516f4e-7963-11e8-9f2e-44422efcebca.png)

**Comment by adamabeshouse** [comment]
@jjgao so you're saying reduce plots to only show the types of mutations available in oncoprint?

**Comment by schultzn** [comment]
Yes, same categories and same colors.

**Comment by adamabeshouse** [comment]
@schultzn and what about shapes, all circle? or different shapes?

**Comment by jjgao** [comment]
all circle. @adamabeshouse

**Comment by adamabeshouse** [comment]
@jjgao @schultzn realizing that we havent included promoter in the mutation rendering priority system. where should we put it? currently its truncating more important than inframe more important than missense

**Comment by adamabeshouse** [comment]
and how should fusions factor in here? in the oncoprint they're outside the mutation priority system bc its a different symbol.

**Comment by schultzn** [comment]
You can give promoter mutations the highest priority.

Fusions would be nice to include..

**Comment by adamabeshouse** [comment]
What priority should fusions receive?

**Comment by schultzn** [comment]
Let’s give them the highest priority… thanks!

**Comment by adamabeshouse** [comment]
so ive got fusion > promoter > truncating > missense > inframe ?

**Comment by schultzn** [comment]
How about
 fusion > promoter > truncating > inframe > missense ?

**Comment by adamabeshouse** [comment]
oops yeah

**Comment by jjgao** [comment]
@adamabeshouse for oncoprint, we can do truncating > inframe > missense > other (including promoter). Current implementation of have both fusions and mutations is good.

for Plots and Expression tab, let's put fusion above mutations.

**Comment by schultzn** [comment]
We only have promoter mutations for the TERT gene - and here, they should be above all other mutations (no other mutations are known to be functional).

**Comment by jjgao** [comment]
@adamabeshouse do you also use oncokb to prioritize in OncoPrint? If so, I would put all other mutations on the bottom. But because tert promoter mutations are oncogenic so they will be above missense... (Niki: I don't think it's a good idea to put non-coding mutations above coding mutations in general in our code. I understand currently we only have tert, but in case we import more non-coding mutations later.)

**Comment by adamabeshouse** [comment]
@jjgao we use VUS annotation to prioritize in oncoprint, yeah. but as of now we're not using VUS annotation in plots/expression

**Comment by jjgao** [comment]
@adamabeshouse maybe we should do that too since the data is already loaded in OncoPrint? It can also be useful to look at the differences between driver events and VUSs. The only caveat is that the Driver menu is only in OncoPrint.

@schultzn thoughts?
