### ISSUE TITLE
Tissue Image Tab is broken

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#4409]
It takes about 2-3 minutes for the `Tissue Image` to show up, and then after another 2-3 minutes, it eventually ends up with an error message next to a (forever) loading animation:

![tissue_image_tab](https://user-images.githubusercontent.com/3604198/42050549-499d13ba-7ad7-11e8-84ce-97eb6bb66501.png)

An example: http://www.cbioportal.org/case.do#/patient?sampleId=TCGA-EW-A1PC-01&studyId=brca_tcga

And, here is the failing service call: http://www.cbioportal.org/proxy/cancer.digitalslidearchive.net/local_php/get_slide_list_from_db_groupid_not_needed.php?slide_name_filter=TCGA-EW-A1PC

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/cbioportal/issues/4375
