### ISSUE TITLE
support whole genome view in CN Segment tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4411]
Currently we only support single-chr view. We should support whole genome view too. We may need to wait for igv.js to implement that first.

**Comment by onursumer** [comment]
@jjgao @JiaoJiao123 Didn't we already add support for this in the GSoC project?

**Comment by jjgao** [comment]
Maybe, but I don't think we push it out.

**Comment by jjgao** [comment]
related to: https://github.com/cBioPortal/cbioportal/issues/4670

**Comment by onursumer** [comment]
New version of igv supports whole genome view, so cBioPortal/cbioportal-frontend/pull/1713 also fixes this issue
