### ISSUE TITLE
copynumbersegments api-legacy endpoint returns all segments instead of requested chromosome

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4412]
http://www.cbioportal.org/api-legacy/copynumbersegments?cancerStudyId=prad_tcga_pan_can_atlas_2018&chromosome=7&sampleIds=TCGA-2A-A8VL-01,TCGA-2A-A8VO-01

**Comment by onursumer** [comment]
@jjgao Looks like the query parameter is `chromosomes`, not `chromosome`. So this one works as desired: http://www.cbioportal.org/api-legacy/copynumbersegments?cancerStudyId=prad_tcga_pan_can_atlas_2018&chromosomes=7&sampleIds=TCGA-2A-A8VL-01,TCGA-2A-A8VO-01

**Comment by onursumer** [comment]
The API is fine. Updated the issue as a `refactoring` bug, since we need to fix this in the frontend.
