### ISSUE TITLE
Update documentation to replace retired wiki.nci.nih.gov references

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4416]
I've been in contact with NCI and it appears wiki.nci.nih.gov has been retired. This wiki is mentioned a number of times in our documentation, mainly because it has a complete description of the MAF format. 

The new resource for this is https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/. However, some critical information on the MAF format is absent, for example, what the allowed values are, and what the restrictions are within the format. 

I contacted GDC to ask for an update on their documentation, and they responded they will look at the information on the old website. When this is updated, we should update all wiki.nci.nih.gov references and refer to the new GDC documentation.

An archived version of the MAF Format Specifications can be found at:
https://web.archive.org/web/20111028213114/https://wiki.nci.nih.gov/display/TCGA/Mutation+Annotation+Format+(MAF)+Specification

**Comment by jjgao** [comment]
@sandertan have you heard anything from GDC?

**Comment by sandertan** [comment]
No update yet. Emailed the document with legacy documentation on the format to JJ, Cyriac, Pieter and Sjoerd.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao can we assign this to someone in your ETL team?

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen I'll take this :)

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen just realized that it was tag with validator. Would it make sense to assign to anyone who is taking over validator? Are you going to have a validator person at Hyve?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao the validator may need to be updated but we would first need to have the new MAF documentation to know that.

I am in the process of hiring someone to take over the validator and all data related cBioPortal work.
