### ISSUE TITLE
[1.15.0] Plots: displaying CNA vs mRNA by default if available

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4426]
Old:
http://www.cbioportal.org/beta/index.do?session_id=5b32ab0f498eb8b3d566bb6d#plots
![image](https://user-images.githubusercontent.com/840895/42242121-cfc97e5e-7eda-11e8-821c-e04a36534e3f.png)

New:
http://www.cbioportal.org/index.do?session_id=5b32ab0f498eb8b3d566bb6d#plots
![image](https://user-images.githubusercontent.com/840895/42242110-c9a0c4a6-7eda-11e8-962c-e7951a823189.png)

**Comment by adamabeshouse** [comment]
cool. is that the only rule?

**Comment by jjgao** [comment]
@adamabeshouse AFAIK.
