### ISSUE TITLE
[1.5.0] Plots: mutation colors

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4427]
Can we use the exact the same colors as OncoPrint? 

e.g. black for truncating, gray for Not mutated, etc

**Comment by adamabeshouse** [comment]
I'm using the passenger colors, I should use the driver colors instead?

**Comment by jjgao** [comment]
@adamabeshouse yes, unless we use VUS annotation.

**Comment by adamabeshouse** [comment]
lets consider this duplicate/obsolete https://github.com/cBioPortal/cbioportal/issues/4428
