### ISSUE TITLE
[1.15.0] Plots: driver vs vus?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4428]
Is it possible to have driver vs vus colors in plots tab as well?

**Comment by adamabeshouse** [comment]
yes but let's talk about the UI

**Comment by jjgao** [comment]
@adamabeshouse you mean how to select/deselect oncokb, etc?

**Comment by adamabeshouse** [comment]
right yeah

**Comment by jjgao** [comment]
@adamabeshouse I think we can keep the configuration in the oncoprint for now, so Plots would use what's defined in oncoprint. Would that work?

**Comment by adamabeshouse** [comment]
sure, that would be fine
