### ISSUE TITLE
[1.15.0] Plots: adding Mutations and CNA colors at the same time

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4429]
Can we do the followings?

- [x] add both mutations (fill) and CNA status (border) at the same time
- [x] Gray border if not CN altered
- [x] Change "View" to "Coloring by"
- [x] Change "Mutation Type" to "Mutations"
- [x] Change "Copy Number" to "Copy Number Alteration"
- [x] use checkboxes instead of radio boxes for Mutation and Copy Number Alteration
- [x] by default, both should be checked

**Comment by adamabeshouse** [comment]
I'm not so sure the border will be visible enough but I can try

**Comment by jjgao** [comment]
You can try to thicken it. 

We also proposed that here: https://github.com/cBioPortal/cbioportal/issues/4006
