### ISSUE TITLE
New Plots: Profile list based on data availability

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4431]
We used to populate the profile list based on data availability for the selected gene and samples. We are not doing that for the new interface. I think we have discussed that but couldn't remember the exact reason to do that? @adamabeshouse could you comment?

Old
http://www.cbioportal.org/index.do?session_id=5b32ab0f498eb8b3d566bb6d#plots
![image](https://user-images.githubusercontent.com/840895/42243077-1ea0c0ca-7ede-11e8-8124-4f0c1bfe93b2.png)

new: 
http://www.cbioportal.org/beta/index.do?session_id=5b32ab0f498eb8b3d566bb6d#plots
![image](https://user-images.githubusercontent.com/840895/42243082-250f3a22-7ede-11e8-8463-bc4412cac649.png)

**Comment by adamabeshouse** [comment]
to do that we would have to prefetch all the data right?

**Comment by jjgao** [comment]
@adamabeshouse good point. In this case, you would also need gene as a parameter. Could you write down your proposed endpoint?

**Comment by adamabeshouse** [comment]
I think @ersinciftci would be better to pin down the details since he is familiar with the conventions, but basically it would be input: profile, genes, samples, output: number of samples with data for the profile and genes. what do you think @jjgao @ersinciftci ?

**Comment by adamabeshouse** [comment]
oh wait, would gene panel be sufficient for this?

**Comment by jjgao** [comment]
@adamabeshouse I think so, but it may be not so different from just pull the data -- the number of data points would be the same I think.

**Comment by adamabeshouse** [comment]
you're right. but if we load the oncoprint anyway then it would be the same. but it would cost more time if we load straight to the tab. i remember now we had this conversation..

**Comment by adamabeshouse** [comment]
my idea is that the new API method would just be a different "projection", so now we have DETAILED, SUMMARY, ID, and others, so I propose a new projection something like COUNT

**Comment by jjgao** [comment]
@adamabeshouse I think it's a good idea to use projection. 

Maybe the gene-panel endpoint can serve only gene-panel meta data. And we can have profiled (or profile-coverage, or a better name) to serve whether a sample is profiled (for a gene in a profile)? It will combine data from sample-profile and gene-panel-list tables.

There is another complication: the NA values should be excluded -- are we handling that in the current gene-panel-data endpoint?

@ersinciftci

**Comment by ersinciftci** [comment]
If you guys are talking about the number of samples that has a non-NA value in `genetic_alteration` table for a profile, then it's related to Molecular Data API, Gene Panel or Gene Panel Data APIs don't use `genetic_alteration` table, they use `sample_profile` and `gene_panel` tables, so they don't deal with `NA` values.

**Comment by adamabeshouse** [comment]
ah okay, in that case theres no getting around adding an endpoint. what do you think of the new projection @ersinciftci ?

**Comment by ersinciftci** [comment]
Molecular Data API currently has a `META` projection that returns the total count, so if you call /molecular-profiles/{molecularProfileId}/molecular-data/fetch for a profile with `META` projection, you will get the total number of gene+sample couples that has non-NA data in the response headers, and since only one gene can be selected in that screen, it will give you the sample count, and it seems like that's what you want. So seems like no API change is needed.

**Comment by adamabeshouse** [comment]
oh okay, great!

**Comment by ersinciftci** [comment]
Actually `META` projection had a bug and was counting `NA` values as well, opened a PR to fix it https://github.com/cBioPortal/cbioportal/pull/4459

**Comment by adamabeshouse** [comment]
@ersinciftci not done yet

**Comment by ersinciftci** [comment]
yeah it closes automatically when something is merged to `master`

**Comment by jjgao** [comment]
we decided not to list profiles based on data availability
