### ISSUE TITLE
Plots: should we list Clinical Attributes as a Profile Type to simplify the interface?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4432]
We could

- [ ] remove the two radio boxes to select Molecular Profile or Clinical Attribute
- [ ] Move Profile Type to the first one
- [ ] Add Clinical data into the Profile Type drop-down
- [ ] Move Gene selection to the last one

Just a thought. Comments? @schultzn @tmazor @adamabeshouse 

Current one:

![image](https://user-images.githubusercontent.com/840895/42243843-a6e20ac8-7ee0-11e8-91df-381f429ae53a.png)

**Comment by adamabeshouse** [comment]
Makes perfect sense to me

**Comment by schultzn** [comment]
That might work… so gene selection would move down to the last step?

**Comment by jjgao** [comment]
@schultzn yes.

@adamabeshouse could you give it a try?

**Comment by pieterlukasse** [comment]
@jjgao sounds good. One thought: maybe rename "Profile type" to something more generic like "Data type"? "Clinical data" is not something I would look for in a "Profile type" drop down.

**Comment by jjgao** [comment]
@pieterlukasse I was thinking of that too, but should we also change `Profile Name`?
