### ISSUE TITLE
Save a shared virtual study

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4437]
After opening a shared virtual study without change anything, the title and description should be populated based on the shared VS when the current user tried to save it.

**Comment by inodb** [comment]
not sure if this is an issue yet, @zhx828 	?

**Comment by zhx828** [comment]
@inodb it's still an issue. I will schedule a fix soon.

**Comment by zhx828** [comment]
@jjgao What about the origin? Should it be the shared VS or the origin of the shred VS?

**Comment by jjgao** [comment]
@zhx828 I think we can just copy the title and description into the text area as the default value. Other things should follow the same process.
