### ISSUE TITLE
How to delete a study from the database?

### ISSUE THREAD

**Issue by messersc** [cBioPortal/cbioportal#4443]
I only found this http://cbioportal.readthedocs.io/en/latest/Importer-Tool.html#remove-cancer-study, but it says these instructions are outdated.

Is there a way to remove a cancer study from the database currently?

Thanks,
Clemens

**Comment by jjgao** [comment]
Hi @messersc would you please send the question to our user support group cbioportal@googlegroups.com? Thanks.

**Comment by messersc** [comment]
The solution can be found here: https://groups.google.com/d/topic/cbioportal/2-jl_wOR0aw/discussion
