### ISSUE TITLE
issue with borderedChart css class

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#4444]
![image](https://user-images.githubusercontent.com/636232/42527661-46120ede-8447-11e8-8f95-ceaf9f70e90d.png)

![image](https://user-images.githubusercontent.com/636232/42527667-4d91eea4-8447-11e8-83ff-fdb7bff5a92a.png)

it seems like the border is calculated to only contain the part thats initially visible, without scrolling (see how it cuts off due to scroll width, on the right)

**Comment by jjgao** [comment]
@adamabeshouse has this been fixed?

**Comment by adamabeshouse** [comment]
it's been fixed by the custom scrollbar
