### ISSUE TITLE
oncotree_code inconsistency

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4445]
Oncotree_code in the clinical data and our database are no longer up to date. We should migrate them to the latest version. CANCER_TYPE and CANCER_TYPE_DETAILED should also be update.

**Comment by ritikakundra** [comment]
@jjgao Do you have a way to find those studies?

**Comment by jjgao** [comment]
We can write a script to look for outdated oncotree code in clinical data table. I could do that next week. But maybe @yichaoS can help on this? @yichaoS please share your sql query code here if you can do.

**Comment by jjgao** [comment]
And this is also impacting internal data. Maybe we need some code in the pipeline to convert old oncotree codes to new ones. @n1zea144 @sheridancbio

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #264](https://github.com/cBioPortal/datahub/issues/264) via [**ZenHub**](https://www.zenhub.com/)
