### ISSUE TITLE
Patient clinical attributes not shown in all patient samples

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#4451]
As you can see in the screenshot for study lgg_ucsf_2014 in cbioportal.org, patient attributes like "Gender" are only displayed in one of the samples of the patient, but not in all: 
![example](https://user-images.githubusercontent.com/20278013/42685560-8ff709b6-8693-11e8-9c07-d4276e5ef1e6.png)

**Comment by inodb** [comment]
I think gender is a patient attribute. I don't see it on the patient view for the samples. @zhx828 do you know why it shows up this way?

Is there some logic on the frontend that assigns the gender to one sample?

**Comment by zhx828** [comment]
@inodb the patterns looks like only the first sample got the gender info. Yeah, the clinical table will map all patient clinical data to sample level. I can take a look at the issue.

**Comment by kalletlak** [comment]
@zhx828 I was running into errors when there is only one sample in the study. My fix in https://github.com/cBioPortal/iViz/pull/739 even fixes this

**Comment by zhx828** [comment]
@kalletlak I doubt it will because the logic of mapping P to S data is in cbioportal, separated out from iviz project. Let me take a look.

**Comment by zhx828** [comment]
@kalletlak looks good. It does solve the issue. I will send the pull request to portal.
