### ISSUE TITLE
allow log scale for certain clinical attributes in plots tab

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#4456]

**Comment by adamabeshouse** [comment]
@inodb @jjgao how do we decide which clinical attributes can have log scale? is it just total mutations?

**Comment by jjgao** [comment]
@adamabeshouse maybe we can add a log option (toggle on/off, by default off) for any number attributes. 

You can also do that for negative numbers:

![image](https://user-images.githubusercontent.com/840895/42777441-1e39f9c4-8908-11e8-8979-5d84160acb84.png)

https://community.tableau.com/thread/105453

**Comment by zhx828** [comment]
@onursumer study view bar chart may need this too, not critical yet.

**Comment by jjgao** [comment]
@zhx828 @onursumer it was an example to show how to do log transformation for negative data, but yeah it can be useful in study view page.

**Comment by jjgao** [comment]
@adamabeshouse you are right... I couldn't think of a general solution. Let's do some more research.

**Comment by adamabeshouse** [comment]
for now we could hardcode it in for total mutations?

**Comment by jjgao** [comment]
@adamabeshouse ok. Maybe make it an option.
