### ISSUE TITLE
Custom News.md linking

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#4457]
I have a properties file setup to access a custom md file for news:

skin.documentation.baseurl=https://raw.githubusercontent.com/cBioPortal/cbioportal/genie-documentation/docs/
skin.documentation.markdown=true
skin.documentation.skin.news=genie-news.md
...

The content is not showing up - after investigation into the chrome debugger/network tab, it looks like skin.documentation.skin.news property is ignored and the code is hardcoded to go to News.md.

![image](https://user-images.githubusercontent.com/366003/42776779-11a814f4-8906-11e8-92a1-ae45520e654b.png)

**Comment by jjgao** [comment]
@alisman has this been solved in the SPA?

**Comment by alisman** [comment]
@jjgao yes this has been solved.
