### ISSUE TITLE
Tooltips on crowded Survival or Expression charts are not working properly

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4471]
When you hover over a point in a crowded area, we should be able to enter tooltip without triggering tooltip for adjacent points.  This really hard problem I think. @jjgao maybe we introduce clicking behavior?  i.e. click on point brings up tooltip directly under the mouse so that user can click on links?  We need to find some relatively simple and universal solution.

**Comment by adamabeshouse** [comment]
@jjgao @alisman well a faster reason why its broken in survival, and more difficult than in other tabs, is that the tooltip is misaligned, so its difficult to move the mouse while remaining inside the tooltip. if we realign the tooltip, do you think it would be usable enough? eg see plots tab
