### ISSUE TITLE
Login button and login window need more and better descriptions

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4474]
The new login button is great. 

A couple of suggestions to improve:
 - [x] Show a tooltip over the login button that says: "Optional login via Google allows you to save cohorts" or something similar
 - [x] in the login window, change: 
Login to Portal:
Welcome to cBioPortal - log in to save your virtual studies.
    to
    Login to cBioPortal:
    Welcome to cBioPortal - log in with your Google account to store your virtual 
    studies. This will allow you to access your studies from any computer. Login is 
    optional and not required to access any of the other features of cBioPortal.

**Comment by inodb** [comment]
- The tooltip is done with `title`.
- Text has been updated

Created a new issue for potentially changing popup to tooltip:

https://github.com/cBioPortal/cbioportal/issues/4528
