### ISSUE TITLE
beta - cancer types summary - bar overlaps y-axis

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4478]
![image](https://user-images.githubusercontent.com/10508276/43008227-768d0e60-8c08-11e8-9ae6-29616c7c7a2c.png)

http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=TP53%2520EGFR%2520PDGFRA%2520PTEN%2520CIC&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic&show_samples=false&clinicallist=MUTATION_COUNT%2CFRACTION_GENOME_ALTERED%2CNO_CONTEXT_MUTATION_SIGNATURE%2CINFORMED_CONSENT_VERIFIED%2CDFS_STATUS

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/cbioportal/issues/4466
