### ISSUE TITLE
beta - plots - missing box in box plot

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4479]
Oligoastrocytoma has data points but no box is drawn:
![image](https://user-images.githubusercontent.com/10508276/43008466-2d47208c-8c09-11e8-9be9-7dd28ffe2319.png)

Similarly, Gain & Amplification are missing boxes in this plot:
![image](https://user-images.githubusercontent.com/10508276/43008585-7b80710e-8c09-11e8-976b-8c5dbe35f7ee.png)

http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=TP53%2520EGFR%2520PDGFRA%2520PTEN%2520CIC&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic&show_samples=false&clinicallist=MUTATION_COUNT%2CFRACTION_GENOME_ALTERED%2CNO_CONTEXT_MUTATION_SIGNATURE%2CINFORMED_CONSENT_VERIFIED%2CDFS_STATUS

**Comment by adamabeshouse** [comment]
for some reason the data is rendering in the wrong order, the boxes and the points are not correctly aligned
