### ISSUE TITLE
plots - profile descriptions

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4482]
The profile descriptions for mRNA & copy number contain the total number of samples. However, the data shows in the plots tab will only be the number of samples contained in the query, which may not be the same number. It is confusing for a user to see multiple different sample counts.

I know we covered this conversation in the Co-Expression tab, but I wanted to highlight that the same issue exists on the plots tab and that it also impacts the description of copy number alterations:
![image](https://user-images.githubusercontent.com/10508276/43009574-0ae94c60-8c0c-11e8-8c89-c4f3e349707f.png)

![image](https://user-images.githubusercontent.com/10508276/43009613-27a35256-8c0c-11e8-9ab9-399abf9c859e.png)

My query contains just 283 samples:
![image](https://user-images.githubusercontent.com/10508276/43009647-39735a6c-8c0c-11e8-8369-7f4478d7808b.png)

**Comment by adamabeshouse** [comment]
let me know how you want to handle this

**Comment by tmazor** [comment]
@adamabeshouse let's do the same thing we did for co-expression: remove the profile description and add the number of samples to the dropdown for each profile.

**Comment by adamabeshouse** [comment]
done in https://github.com/cBioPortal/cbioportal-frontend/pull/1296#discussion_r205213507
