### ISSUE TITLE
beta - plots - highlighted samples are hard to find

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4483]
If I search for a case or a mutation, the dot representing any samples that matches those searches get slightly larger. I'm finding it hard to identify those samples because the size difference is minimal:
![image](https://user-images.githubusercontent.com/10508276/43014402-134e94d8-8c1a-11e8-9273-a0df24d72618.png)

On production, there is a huge size difference:
![image](https://user-images.githubusercontent.com/10508276/43014435-2271e316-8c1a-11e8-91d2-883e7bee08e2.png)

I don't think we necessarily need to make the dots as large as on production, but I do think they need to be larger than they currently are on beta. Can we try an in-between size?

**Comment by adamabeshouse** [comment]
what if we also change the shape? right now its all circles, so we could increase the size *and* change the shape to star?

**Comment by jjgao** [comment]
@adamabeshouse Let's try to increase the size and see if it works better.

ps. @schultzn also brought up this issue.

**Comment by schultzn** [comment]
We can also slightly reduce the default size of the dots.

**Comment by adamabeshouse** [comment]
@schultzn that I dont think we can do because of wanting to display both mutation color and CNA border

**Comment by adamabeshouse** [comment]
Fixed here: https://github.com/cBioPortal/cbioportal-frontend/pull/1305 I increased the size, and also resorted the data to put highlighted dots on top in z-index
