### ISSUE TITLE
beta - plots - if plot is wide, legend gets cut-off

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4485]
Specifically, the (i) symbol (about driver annotation settings) disappears when the plot is wide:
![image](https://user-images.githubusercontent.com/10508276/43014647-dd5c565c-8c1a-11e8-8c08-7ec5cb7706e3.png)

http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=TP53%2520EGFR%2520PDGFRA%2520PTEN%2520CIC&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic&show_samples=false&clinicallist=MUTATION_COUNT%2CFRACTION_GENOME_ALTERED%2CNO_CONTEXT_MUTATION_SIGNATURE%2CINFORMED_CONSENT_VERIFIED%2CDFS_STATUS

**Comment by adamabeshouse** [comment]
its still there but its scrolled off to the right. its related to this https://github.com/cBioPortal/cbioportal/issues/4444

@alisman what do you think?

**Comment by tmazor** [comment]
Scrollbar is great!
