### ISSUE TITLE
legacy genetic_profile_ids param in url 

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4486]
The old site supports a url parameter genetic_profile_ids.   The way I know this is that there is a sample query with this parameter.  As far as I can tell, there is not way to produce such a query with the interface, which now enumerates profiles like so:

genetic_profile_ids_PROFILE_MUTATION_EXTENDED,
genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION,
genetic_profile_ids_PROFILE_MRNA_EXPRESSION,
genetic_profile_ids_PROFILE_PROTEIN_EXPRESSION

Is there a way to produce a query with the single param genetic_profile_ids and if NOT, do we still need to support it in new site?

**Comment by jjgao** [comment]
For the new URL in SPA, let's use `genetic_profile_id`. After we do that, is it possible to have a script to map the old URLs to the new format so that we support old sessions and bookmarked urls? @alisman
