### ISSUE TITLE
beta - plots - missing color control when plotting clinical + molecular

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4487]
When one axis is a clinical attribute and the other axis is a molecular profile, the ability to control sample coloring disappears and samples are colored according to mutations but not copy number. The same controls that exist when the plot is two molecular profiles should apply in this scenario also.

![image](https://user-images.githubusercontent.com/10508276/43015142-aec52024-8c1c-11e8-928d-620010d32133.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1305

**Comment by jjgao** [comment]
@adamabeshouse I moved it back to backlog.
