### ISSUE TITLE
"ln" url shorthand for all studies

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4488]
http://www.cbioportal.org/beta/ln?q=BRAF:MUT=V600E

Do we need to support this shorthand in new site?

**Comment by jjgao** [comment]
@alisman yes, but we should probably use the "good" default set of studies instead of all: https://github.com/cBioPortal/cbioportal/issues/3395

**Comment by jjgao** [comment]
We can probably redirect this url so we don't need a SPA for it.

**Comment by alisman** [comment]
@jjgao looks to me like this works now.    do you have the list of "good" studies?

**Comment by jjgao** [comment]
@alisman not yet. It'll be handled by this one: https://github.com/cBioPortal/cbioportal/issues/3395.
