### ISSUE TITLE
beta - plots - support multiple search values?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4489]
The search utility labels include "(s)" which could be interpreted to allow for searching for multiple case IDs/mutations at once:
![image](https://user-images.githubusercontent.com/10508276/43015278-389d67e8-8c1d-11e8-8aaa-f659dafc255c.png)

Is the search feature supposed to work for multiple values?

If so, we need some explanation/description of how to do it (I can write this if someone tells me how to do it - I tried comma & space separate values but neither worked)

If not, can we change those labels to say:
"Search for a case"
"Search for a mutation"

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1305
