### ISSUE TITLE
Can't get authentication to work

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#449]
I would like to enable authentication on our instance of cbioportal.
I've followed the wiki page https://github.com/cBioPortal/cbioportal/wiki/Authenticating-Users-via-SAML.
When I go to /cbioportal I get

    HTTP Status 500 - An Authentication object was not found in the SecurityContext
    exception
    org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
    org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:339)
    org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:198)
    org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:60)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	com.sun.proxy.$Proxy43.getCancerStudies(Unknown Source)

When I go to cbioportal/login.jsp it works and I see the button Sign in with MSK but when I click it cbioportal/login?idp=[my identity] gives me a 404.

Is there something missing?

**Comment by ecerami** [comment]
Very hard for us to debug this with the information given.  Are you using a SAML endpoint within your institution?  Have you followed all the steps on the wiki page?

**Comment by n1zea144** [comment]
Yeah, for starters we would need to see how you have set some of your portal.properties properties.  For example, do you have authenticate=saml ?

**Comment by j-hudecek** [comment]
Yeah I deleted everything and started again and got it resolved. Thanks anyway
