### ISSUE TITLE
beta - plots - sample tooltip spacing

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4490]
There is a space before the comma when there are two mutations:
![image](https://user-images.githubusercontent.com/10508276/43015968-35aef3ba-8c1f-11e8-88a4-f01db06e4bcb.png)

I assume it happens for all samples with 2 mutations, but it's particularly noticeable when the OncoKB/hotspots icons aren't there.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1305
