### ISSUE TITLE
beta - networks - right clicking edges fails

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4491]
If I right-click on an edge then a new window opens with 404 not found:
![image](https://user-images.githubusercontent.com/10508276/43018123-93514caa-8c26-11e8-8d91-e7717998c4ed.png)

**Comment by jjgao** [comment]
@alisman can we disable this functionality?

**Comment by tmazor** [comment]
This is still happening.

Also if the solution is to remove this functionality, please delete the text on the page that says to do this:
![image](https://user-images.githubusercontent.com/10508276/43469020-46827f80-94b3-11e8-90e3-c5f8cf2d63cd.png)

**Comment by alisman** [comment]
@tmazor sorry, we just didn't properly deploy this part.  it's up now.  please check again.

**Comment by jjgao** [comment]
@alisman is it possible to disable to right-click functionality too?

**Comment by jjgao** [comment]
but it still opens the SBGNViz.js page for me...

**Comment by jjgao** [comment]
It's fixed after clearing cache.

**Comment by tmazor** [comment]
Works for me now too!
