### ISSUE TITLE
incorrect clinical annotation 

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#4492]
the patient TCGA-BW-A5NP is from Liver Hepatocellular Carcinoma (TCGA, Provisional) study
> Dear Sir or Madam,
We are using TCGA data for hepatocellular carcinoma from cBioportal. We noticed something seems strange regarding patient clinical data.
For patient TCGA-BW-A5NP, the overall survival is 0 while the disease free survival is about 3.5 months.  Is there something we misunderstand?
Thank you.
Jingjing

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #272](https://github.com/cBioPortal/datahub/issues/272) via [**ZenHub**](https://www.zenhub.com/)
