### ISSUE TITLE
OncoPrint tooltip needs to indicate the altered gene in merged tracks

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4493]
In a merged OncoPrint track, the tooltip should indicate which gene is altered. 

We can consider to always show the gene symbol to make things simpler?

![image](https://user-images.githubusercontent.com/11892704/43079607-8fd7b834-8e5b-11e8-91d9-37316e9629ce.png)

**Comment by jjgao** [comment]
@fedde-s would you be able to help with this?

**Comment by schultzn** [comment]
I think the point is not having to expand the track - the tooltip should show which gene the mutations was found in.

**Comment by fedde-s** [comment]
Would that be only the most ‘significant’ alteration of a type, that determines the colour, or possibly a list of several genes that are all amplified? Currently the tooltips show all alterations relevant to a square, just like a single-gene square that displays alterations for all of a patient's samples.

**Comment by fedde-s** [comment]
The question I just asked might be a separate issue. Prepending the gene to each alteration is a pretty clear requirement. And by “always show the gene symbol,” do you mean being consistent and doing that for single-gene tracks as well?

**Comment by jjgao** [comment]
@fedde-s I think it'd be important to have the gene displayed. We missed it when reviewing it initially. Can you still help?

**Comment by adamabeshouse** [comment]
@jjgao @schultzn  it should be a very simple change. the tooltip generating function has access to the full mutation object which includes the gene. it wont take more than a few minutes of work, if you just want to show the gene for every mutation in the list (and we should also do this for other alterations, i.e. mrna, prot, cna). it would probably make sense only to show it in merged tracks, right?

**Comment by fedde-s** [comment]
Nice! I didn't remember the code well enough off the top of my head to know whether it would be trivial or slightly awkward. But indeed, the question still stands. Consistently for all tooltips, only for merged tracks, or consistently within Oncoprints that contain at least one merged track. The last one is probably the trickiest to implement.

**Comment by jjgao** [comment]
It may be ok to always include gene symbol in the tooltip. @schultzn?

**Comment by schultzn** [comment]
Yes, I think so!

**Comment by fedde-s** [comment]
Could you make the PR, @adamabeshouse? I'm a bit busy at the moment, and you seem to recall exactly which line of code to change :)

**Comment by jjgao** [comment]
@adamabeshouse thanks for the fix. Please also apply this to other data types, CNA, mRNA, protein. 

![image](https://user-images.githubusercontent.com/840895/43784013-198a261c-9a31-11e8-8361-c3eaa847a73d.png)

Please also add a space after comma (,).

![image](https://user-images.githubusercontent.com/840895/43784120-5f4b7a84-9a31-11e8-9cd5-148ed165dca7.png)
