### ISSUE TITLE
beta - expression - box of boxplot looks misaligned

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4496]
The box for the AML expression in the screenshot below looks misaligned. The samples are almost all >0, the whiskers are visible at ~-0.5 and 5.5, but the box is drawn from 1 to -6.
![image](https://user-images.githubusercontent.com/10508276/43083944-a332a74a-8e65-11e8-92f7-105b961a6025.png)

Every other box looks to be in an appropriate place so I'm not sure what's happening here. I see the same issue on production also:
![image](https://user-images.githubusercontent.com/10508276/43084107-03ef775c-8e66-11e8-9993-8230e3f3c8b6.png)

http://www.cbioportal.org/beta/index.do?session_id=5b55e8c6498eb8b3d56710f3

**Comment by alisman** [comment]
@jjgao the reason for this is that there are many data points where expression=0 in that study.   The box bottom represents the lower quartile, and lower quartile is zero.  We are capping the expression value at 0.01, and log10(.01) is -6.xx.  

In the old version of the plot, you can see that there are a number of data points on that line, but with our new seeded random # jitter calculation, the points with equal value are getting put in essentially the same place.  This might be a rounding issue.  

Anyway, seems like this is just the same old issue of how we handle zero values.

**Comment by jjgao** [comment]
I am thinking that we should probably exclude 0 for calculating the box...

Why the samples with 0 only have one dot?

**Comment by alisman** [comment]
@jjgao See note above. I'm pretty sure it has to do with the new jitter calculation.  The dots with same value end up in same place (could be rounding) and so perhaps Victory has an optimization to hide overlapping?

**Comment by jjgao** [comment]
@alisman I see - the random seed was based on value only. Maybe we can add a sample-related attribute to the seed, e.g. the index of the sample in the data array?

Alternatively we don't have to fix random seed in production.

**Comment by jjgao** [comment]
@alisman I remember we had some discussion earlier about not using 0s for calculating boxes but decided not to do that. Do you remember the reason?

**Comment by alisman** [comment]
@jjgao i can't remember exactly what we decided, but now it just seems weird to me to show a box which is not reflective of the scatter data on top of it, no?   just as you noticed here (though for different reason).   in this case, there was another problem which obscured the truth: seeded jitter calculation seems to place all points with equal value on top of each other.  so you didn't see a whole slew of the zero points down at bottom of box which would have made sense of the box plot.   anyhow,

**Comment by jjgao** [comment]
@alisman there are two reasons that we should consider remove 0s for calculating the boxes.

1. The artificial cap we choose for 0s affects the box.
2. When expression is 0, we don't really know whether the gene the not expressed or not covered.

**Comment by alisman** [comment]
@jjgao ok, this is deployed.  we no longer take 0 values into account
