### ISSUE TITLE
Adding add_global_case_list:true in metaStudy.txt assigns case_list category to 'other' instead of 'all_cases_in_study'

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#4502]
https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/scripts/AddCaseList.java#L58

**Comment by sandertan** [comment]
Hi @kalletlak. @rnugraha informed me of the issue. Indeed, a solution for future studies would be to change the `case_list_category` to `all_cases_in_study` when using the `add_global_case_list:true`-option. However, all studies that are currently loaded with the old importer, will suffer from the bug. It would mean that all these studies have to be reloaded.

In your PR, #4341 , could you use the stable ID (ending with `_all`) to retrieve the all-case list?

**Comment by kalletlak** [comment]
@sandertan I could, but this even affected the fronted. Currently the counts in the Case Set selection in query pages is based on category. example(when case_list category is `other`)

![screen shot 2018-07-23 at 12 33 59 pm](https://user-images.githubusercontent.com/12956870/43090199-b87a1bd8-8e74-11e8-9bdd-b6365e58bb43.png)


Not sure if we want these hacks even in frontend. @jjgao @alisman thoughts?

**Comment by fedde-s** [comment]
I feel that time I discussed this with others in the community, the consensus was that the `case_list_category` has been deprecated for a long time, and any (legacy) code that uses it instead of the suffixes is broken. After all, it's never been clearly documented for data curators.

**Comment by fedde-s** [comment]
For that reason, I think making the loader explicitly generate it will only cause more confusion and bugs.

**Comment by jjgao** [comment]
@kalletlak could you check if case_list_category is being used in any other places. If not, let's stick to suffix for now.

**Comment by sandertan** [comment]
@kalletlak @jjgao We received a report from a client about a bug in 1.14.0 that sometimes displays this message:
<img width="990" alt="screen shot 2018-08-02 at 12 06 41" src="https://user-images.githubusercontent.com/9624990/43578018-d94c2140-964d-11e8-872d-87401f5bbe74.png">

This is a patient with only clinical data. Case lists were generated with `add_global_case_list: true`. Unfortunately, the message didn't show up all the time so I haven't been able to pinpoint the exact source of the issue. When I reloaded this data with a manual `all_cases_in_study`case list and `add_global_case_list: false`, I haven't been able to reproduce the bug.

So perhaps a missing `all_cases_in_study` is related to this bug in the patient view as well.

**Comment by kalletlak** [comment]
@jjgao seems like its used only in query selection. I'll update and create PR

**Comment by jjgao** [comment]
@kalletlak ok. thanks

**Comment by fedde-s** [comment]
Now to solve the root cause and point future developers at which field to use, might it make sense to add a deprecation comment in the file format documentation, the Java data structure that defines case list categories or the API endpoint that returns them?

**Comment by jjgao** [comment]
Thanks, @fedde-s.

@ersinciftci it may be a good idea to remove `category` from the endpoint for now.
