### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4507]
Currently:

Home page:
- /
 - /index.do

Results page:
- /index.do?
 - cancer_study_id
 - ...

LN page:
- /ln?
 - ...

Patient view:
- case.do?
 - ...

Study view:
- study?
 - ...

Proposed:

**Comment by alisman** [comment]
@jj I'll fill this early next week when I'm through with 1.15.0 stuff

**Comment by jjgao** [comment]
@alisman no hurries.

**Comment by jjgao** [comment]
@alisman could you fill this?

**Comment by alisman** [comment]
Study page: /study
Results page: /results/:tab
Patient: /patient

Old routes are rerouted as appropriate:
ln, index.do, case.do, etc.
