### ISSUE TITLE
Verify that legacy patient links redirect properly to new HTML5 links

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4510]
@inodb i'm give this to you just to get a different set of eyes on it.  

- [x] Legacy patient links work
  - [x] nav case ids
- [x] Legacy sample links works
- [x] Legacy cohort links work
- [x] Check links to patient page from other areas of app
  - [x] study view (top button, clinical data tab)
  - [x] oncoprint (mouseover tooltip)
  - [x] mutations tab (first column)
  - [x] plots tab (mouseover tooltip)

**Comment by inodb** [comment]
@alisman all seems to work - i just updated some urls in prs to backend and frontend, but they work anyway cause of the rewrite.
