### ISSUE TITLE
Study archive download stalls

### ISSUE THREAD

**Issue by guv** [cBioPortal/cbioportal#4513]
I tried to download the study archive for `hnsc_tcga_pan_can_atlas_2018` from the [download link](http://download.cbioportal.org/hnsc_tcga_pan_can_atlas_2018.tar.gz).
After 109/140 MB the download stalls and does not continue again.

**Comment by jjgao** [comment]
@guv thanks for the contacting us. Is it a one-time glitch or are you experiencing this constantly?

**Comment by jjgao** [comment]
Actually I am closing this and please contact cbioportal@googlegroups.com if the problem persists.

**Comment by guv** [comment]
Yes, this is reproducible for larger downloads (>100MB). Though, the time when it happens (measured in completion percentage) varies.

**Comment by jjgao** [comment]
@guv thanks, I can reproduce it now. We will look into this.

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #273](https://github.com/cBioPortal/datahub/issues/273) via [**ZenHub**](https://www.zenhub.com/)
