### ISSUE TITLE
testing pair of tracks instead of genes in Mutex tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4514]
For example, in [this query](http://www.cbioportal.org/index.do?session_id=5b592dcf498eb8b3d5671c60),

```
["RAS" KRAS NRAS HRAS]
["RAF" BRAF RAF1 ARAF]
```

Mutex tab is still testing gene pairs, but it would be interesting to test Mutex between RAS and RAF groups.

Another example, in [this query](http://www.cbioportal.org/index.do?session_id=5b592e8a498eb8b3d5671c62),

```
EGFR:MUT;
EGFR:AMP;
```

Mutex is missing because only one gene is queried, but it would be interesting to test EGFR MUT vs AMP.

So, instead of testing gene paris, can we test track pairs?

cc'ing @cBioPortal/product

**Comment by schultzn** [comment]
+1

**Comment by tmazor** [comment]
Great idea!
