### ISSUE TITLE
OncoPrint: option to only show clinical legends for altered samples

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4515]
We received a feature request:

When querying MSK-IMPACT study and showing cancer type clinical attribute track, there are too many different cancer types. It would be useful only show the legend for the cancer types that contain altered samples.

Can we add an option "Only for altered samples" under View -> "Show legends for clinical tracks"? By default, this option is turned off.

**Comment by adamabeshouse** [comment]
this will take an oncoprintjs library change but its definitely possible

**Comment by jjgao** [comment]
@adamabeshouse if it's easy to do, could you prioritize this one once 1.15 is done?

**Comment by adamabeshouse** [comment]
sure
