### ISSUE TITLE
Special characters not allowed in patient/sample names

### ISSUE THREAD

**Issue by patidarr** [cBioPortal/cbioportal#4516]
I have ~ in the patient and sample names, it used to work till v 1.12 but not anymore, any chance the restriction could be lifted? 

Thanks,
Rajesh

**Comment by jjgao** [comment]
@patidarr we decided to normalize IDs (https://github.com/cBioPortal/datahub/issues/192) due to issues related to special characters. Please fellow the new format. Sorry for the inconvenience.
