### ISSUE TITLE
Seeded jitter calculation produces same value for data points with equal values

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4522]
Seems like we need to make seed unique for each datapoint?  E.g. take sampleId into calculation?  Let know if you have ideas.  Right now, it seems that if datapoints have same value, they end up stacked on top of each other.

export function calculateJitter(boxWidth: number, seed:number){
    return (getRandomNumber(seed) - getRandomNumber(seed+1)) * 0.30;
}

**Comment by adamabeshouse** [comment]
very good point

**Comment by adamabeshouse** [comment]
actually it would be better to determine that based on sample id altogether rather than based on the numerical data value

**Comment by alisman** [comment]
@adamabeshouse what about

String.prototype.hashCode = function() {
  var hash = 0, i, chr;
  if (this.length === 0) return hash;
  for (i = 0; i < this.length; i++) {
    chr   = this.charCodeAt(i);
    hash  = ((hash << 5) - hash) + chr;
    hash |= 0; // Convert to 32bit integer
  }
  return hash;
};

**Comment by adamabeshouse** [comment]
that works! whered you get that from?
