### ISSUE TITLE
OncoKB Card only shows the first treatment for this sample

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4524]
This KIT	V654A has three treatments 1 2A, 2 2B
https://cbioportal.mskcc.org/patient?sampleId=P-0023777-T01-IM6&studyId=mskimpact

**Comment by jjgao** [comment]
@zhx828 any update?

**Comment by zhx828** [comment]
@jjgao this was designed to ignore all 2B treatments when level 1/2A detected.

**Comment by jjgao** [comment]
@zhx828 then we should close it?

**Comment by jjgao** [comment]
But I thought we were only ignoring lower levels when the drugs are the same and otherwise displaying all levels on portal?

**Comment by zhx828** [comment]
Seems not the logic in the frontend. I can do a deep look and update the
logic if need.

**Comment by jjgao** [comment]
@zhx828 let's find out what was decided first? If it's too long ago, we could have a discussion with the group first.

**Comment by zhx828** [comment]
Sounds good. Will put it on trello for next week.

**Comment by jjgao** [comment]
We have both Level 1 & 3B in this patient:

http://www.cbioportal.org/patient?sampleId=P-0009912-T01-IM5&studyId=msk_impact_2017

![image](https://user-images.githubusercontent.com/840895/52459351-8cacba00-2b32-11e9-98a6-9ab6ffad7483.png)

I don't know why we should not show Level 1 & 2B together... I think we should change the logic.

**Comment by zhx828** [comment]
Yeah... It's a bit odd when I saw the logic today as well. Let's discuss.
