### ISSUE TITLE
different color for "Not mutated" in Plots and Expression

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4530]
@schultzn commented that when there are not many mutations, the plot looks too grayish. Maybe we can try to use some different color. The blue we used originally might not work since it's too close to green and the copy number blue. @adamabeshouse could you try another light color? Please feel free to add screenshots here for discussion.

![image](https://user-images.githubusercontent.com/840895/43410623-83940cf4-93f5-11e8-9be1-7995bdfe8e6d.png)

**Comment by adamabeshouse** [comment]
How about if we just increase the stroke opacity to differentiate the blob

![image](https://user-images.githubusercontent.com/636232/43412308-d965b13c-93fa-11e8-9644-809958d5032a.png)

**Comment by jjgao** [comment]
@adamabeshouse and I came up with one color. @adamabeshouse could you add a screenshot here for comparison?

**Comment by adamabeshouse** [comment]
![image](https://user-images.githubusercontent.com/636232/43486134-060ef54a-94e1-11e8-9eff-e5fa2b7650a6.png)

![image](https://user-images.githubusercontent.com/636232/43486146-0c2a2580-94e1-11e8-8352-0a411a27f146.png)

![image](https://user-images.githubusercontent.com/636232/43486157-15546fda-94e1-11e8-9405-8d53a81477bc.png)

![image](https://user-images.githubusercontent.com/636232/43486164-1b496f26-94e1-11e8-9395-a68eb96697e4.png)

**Comment by jjgao** [comment]
Thanks, @adamabeshouse 

@tmazor @schultzn any comments about the colors (gray vs light blue)?

**Comment by schultzn** [comment]
I like the one below. I don't think we need to color code the dots when we already have copy-number categories.

![image](https://user-images.githubusercontent.com/11892704/43509712-6565d918-9541-11e8-93cb-28d2c62cb948.png)

**Comment by jjgao** [comment]
@schultzn thanks.

@adamabeshouse could you disable coloring by copy number alterations when discrete copy number data is plotted?

**Comment by adamabeshouse** [comment]
sure

**Comment by tmazor** [comment]
that light blue looks good to me too
