### ISSUE TITLE
optional log in: is it possible to stay logged in betweens sessions?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4531]
just similar to Gmail...

**Comment by jjgao** [comment]
@zhx828 do we need to change the tomcat start script?

**Comment by zhx828** [comment]
@jjgao yes, but only when we deploy the optional login. @inodb I will remind you again when we decide to release optional login. Then you could update our deployment script by adding `-Dtomcat.session.timeout=43200` This is a 30 days timeout.
