### ISSUE TITLE
strange issues for optional login

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4533]
sometimes I logged in the study view page and than click to frontpage and see that I am not logged in. I couldn't reproduce it consistently.

**Comment by zhx828** [comment]
@jjgao I have difficulty to reproduce the issue. Could you give us more details including the browser, version?

**Comment by jjgao** [comment]
@zhx828 don't worry about this for now. I think if you can fix https://github.com/cBioPortal/cbioportal/issues/4531, this one should not be a problem.
