### ISSUE TITLE
On plots tab, is lock the right icon for the gene select list sync?  

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4534]
Maybe link would be better?  

![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/7e48fe2f-d365-478a-9493-4ef23f666344)

**Comment by adamabeshouse** [comment]
I like that idea @jjgao 
How about `Same gene (KRAS)`

**Comment by jjgao** [comment]
@adamabeshouse better!

**Comment by tmazor** [comment]
I like this too!
