### ISSUE TITLE
beta - plots - svg download cuts off legend

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4537]
The PDF download seems ok, but SVG cuts off the legend

![image](https://user-images.githubusercontent.com/10508276/43470102-c5b97356-94b5-11e8-8e68-b7ef51b5f8f2.png)

**Comment by tmazor** [comment]
This might be related to #4550 - some of the text here (including the legend) is larger than other text, which could be why it's getting cutoff

**Comment by adamabeshouse** [comment]
@tmazor that seems to be the issue. I'll mark this as a duplicate
