### ISSUE TITLE
beta - plots - change order of data options

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4538]
I like the change to include clinical attributes & genomic elements under one dropdown. However, the order feels awkward to me now. How about moving Gene to the bottom so the order becomes:
Data Type
Clinical Attribute / Genomic Profile selection
Gene

![image](https://user-images.githubusercontent.com/10508276/43470528-cb659b44-94b6-11e8-9975-90789cf7e6bf.png)
![image](https://user-images.githubusercontent.com/10508276/43470544-cf8c3aac-94b6-11e8-9c24-d0047f37e37b.png)
![image](https://user-images.githubusercontent.com/10508276/43470556-d61866c0-94b6-11e8-9453-9644bc6c111c.png)

**Comment by alisman** [comment]
@jjgao can you confirm this change?

**Comment by jjgao** [comment]
Agreed. Gene should be the last one. Niki also requested that: https://github.com/cBioPortal/cbioportal/issues/4432

**Comment by jjgao** [comment]
I think we can also high the Gene selector when selecting Clinical Attribute as Data Type. @adamabeshouse

**Comment by adamabeshouse** [comment]
this should affect the text used here as well https://github.com/cBioPortal/cbioportal/issues/4534

**Comment by adamabeshouse** [comment]
the semantic issue with this is that the gene selected determines which data type and profiles are available. thoughts @tmazor @jjgao ?

**Comment by jjgao** [comment]
@adamabeshouse that's a good point. One option would be to display the number of samples with data for the gene and then we can display all profiles including the ones with 0 samples with data.

**Comment by adamabeshouse** [comment]
it could still be confusing eg if you have a profile selected then you change the gene then that profile no longer has data so we auto-select a different profile. it makes more sense to have gene on top since the flow of info really does come from the gene.

**Comment by jjgao** [comment]
@adamabeshouse we don't have perfect solution here. Having Gene on top is also confusion because Clinical data does not depend on gene. (maybe that's reason had clinical data and genomic data separate in the fist place.)

I am wondering if we move gene between data type and profile? (Is data type also determined by gene?)

![image](https://user-images.githubusercontent.com/840895/43496720-e5888a8a-950c-11e8-89f9-e363589985b7.png)

**Comment by jjgao** [comment]
commented in #4480 too. "This is getting too complex. Maybe we should not be too smart about changing the dropdown menu items and simply show a message on the right that we don't have data in xx profile for xx gene?" This will avoid the auto-selection issue @adamabeshouse mentioned...

**Comment by adamabeshouse** [comment]
@jjgao data type also depends on gene, available data types depends on available profiles.

i have a message set up that does that, it just says "no data to plot". We can go back to that and that way put "Gene" on the bottom. what do you think?

**Comment by adamabeshouse** [comment]
as discussed in person, we're not going to filter options by data availability anymore. that will make it unproblematic to move the gene selector to the bottom

**Comment by tmazor** [comment]
I like it! Maybe this gets us back into the too complex realm but when the horizontal axis is a clinical attribute, the vertical axis ideally would say just the gene name and not "same gene":
![image](https://user-images.githubusercontent.com/10508276/43656809-c3327f06-9721-11e8-9e6f-67ee2884ed49.png)

**Comment by adamabeshouse** [comment]
@tmazor I thought of that but then does that mean we should have two options in the menu at that time, both with the same gene?

**Comment by tmazor** [comment]
I think ideally the "Same gene" option would disappear from the menu and the selection would move to be just the gene name.

**Comment by adamabeshouse** [comment]
@tmazor I guess thats fine. if they change the gene then thats where itll sit when the horizontal axis is restored. if not then it'll restore to 'Same gene' when the horizontal axis is restored.

**Comment by tmazor** [comment]
that sounds good to me @adamabeshouse
