### ISSUE TITLE
beta - plots - add search functionality to clinical attributes

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4539]
The old plots tab had search functionality for the list of clinical attributes - we need that feature on the refactored version also

**Comment by adamabeshouse** [comment]
@alisman adding "searchable" or "isSearchable" to ReactSelect isnt working. any insight as to why that is? i cant figure any difference in usage from CaseSetSelector where there is search

**Comment by tmazor** [comment]
This is great! One small thing which might just be me, but... can we make the text in the box grey when the dropdown is opened? I think it might make it slightly more intuitive that it's searchable and you can type over the text.
![image](https://user-images.githubusercontent.com/10508276/43656694-549cc100-9721-11e8-8981-61ebcdf01d83.png)

**Comment by adamabeshouse** [comment]
@tmazor its not just you, @alisman and I were talking about the same thing. Not ideal style choice by ReactSelect.

**Comment by tmazor** [comment]
That looks so much better now!
