### ISSUE TITLE
beta - expression - pdf download fails

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4541]
Once when I clicked the PDF button it downloaded something but the file was 0 bytes. Now when I click the button nothing happens.

SVG & PNG downloads seem just fine.

**Comment by alisman** [comment]
@jjgao i think we agreed a while ago that PDF download is redundant.   i've opened up a PR that does away with PDF download here.  we can merge upon confirmation

**Comment by jjgao** [comment]
@alisman as discussed, let's try to restore PDF options for tab. It's OK if we delay this until after 1.15.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/issues/4541 duplicate
