### ISSUE TITLE
beta - some downloads have different fonts/sizes

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4550]
PDF looks like the image on the website:
![image](https://user-images.githubusercontent.com/10508276/43476181-e80dfc3c-94c5-11e8-8dd1-3a7f41235d83.png)

But SVG & PNG have different fonts (and maybe different text size - I can't tell since the font also changes):
![image](https://user-images.githubusercontent.com/10508276/43476208-f5bb2a4e-94c5-11e8-9dce-8cbf5ffd47e4.png)

**Comment by tmazor** [comment]
On co-expresion, the PDF looks normal but the SVG has inconsistent text - note how the axis names are much smaller text than everything else:
![image](https://user-images.githubusercontent.com/10508276/43476377-7595f37a-94c6-11e8-9924-b8332c22d286.png)

On enrichments, both SVG & PNG have the numbers along the axes in a larger font size than everything else:
![image](https://user-images.githubusercontent.com/10508276/43476433-92726794-94c6-11e8-84b5-643099690879.png)

**Comment by tmazor** [comment]
Also - is there a reason that some plots can be downloaded as PNG/SVG/PDF and others only as PDF/SVG or SVG/PNG? Can we just offer all three options everywhere?

**Comment by jjgao** [comment]
@tmazor I am taking this off of 1.15 since the issue is already there for Mutations tab, but we will look into this.

@alisman Let's always have PNG, SGV, PDF, Data. https://github.com/cBioPortal/cbioportal/issues/4555

please investigate if the font issue can be fixed. If it is not easy to fix, I don't think it's a high priority (@tmazor please comment if you think otherwise).

**Comment by tmazor** [comment]
@jjgao this is actually new to Mutations tab on beta. Downloading from Mutations tab on production looks just like the image on the site no matter the format.

**Comment by adamabeshouse** [comment]
When looking at the downloaded svg vs the one in the browser, for some reason the downloaded svg has dropped the 'font-size' style in the downloaded version, while keeping the other styles (as far as I can tell). I'll look into it. @alisman does this ring any bell for you?
