### ISSUE TITLE
Tweaks to plots tab box plot styles

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4556]
1 - increase spacing between boxes slightly
2 - add median line for categories with just one sample (maybe not necessary)
3 - reduce empty space at the right of the plot slightly

![image](https://user-images.githubusercontent.com/186521/43534548-a4eee626-9585-11e8-8869-de8284ccd7e1.png)

**Comment by jjgao** [comment]
@adamabeshouse while you are on this, could you also tilt the x-axis label a little more?

**Comment by adamabeshouse** [comment]
@jjgao I had it to match cancer type summary. let me know how you would like it

**Comment by jjgao** [comment]
@adamabeshouse I logged the label angle issue: https://github.com/cBioPortal/cbioportal/issues/4578
