### ISSUE TITLE
hide/disable coloring by copy number alterations when discrete copy number data is plotted

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4559]
see discussion https://github.com/cBioPortal/cbioportal/issues/4530#issuecomment-409490791

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1337

**Comment by tmazor** [comment]
If copy number is plotted against a clinical attribute, then the copy number coloring returns:
![image](https://user-images.githubusercontent.com/10508276/43720807-1a4b44d2-995f-11e8-9d73-700c8ace8102.png)
http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=EGFR%2520PDGFRA%2520TP53&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic
