### ISSUE TITLE
Beta -- View 3D Structure is not work in MutationMapper

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4561]

**Comment by jjgao** [comment]
It affects Mutations tab too!

**Comment by jjgao** [comment]
I am closing this. @inodb could you create an issue about your dirty fix (all functionality seem working!) and @onursumer can take a look later. Thanks.

**Comment by inodb** [comment]
@jjgao ok: https://github.com/cBioPortal/cbioportal/issues/4573
