### ISSUE TITLE
is there a way to reorder endpoints in swagger-ui.html

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4570]
currently it's alphabetical. Ideally we should order them in a way that reflect the data, e.g. https://github.com/cBioPortal/cbioportal/blob/jjgao-patch-api-doc/docs/cBioPortal-Web-API.md. Is that possible?

**Comment by ersinciftci** [comment]
@jjgao it seems like https://springfox.github.io/springfox/javadoc/current/springfox/documentation/swagger/web/TagsSorter.html supports only alphabetical sorting for now. I tried a few different things but it seems like it's not possible. Closing it for now.

**Comment by jjgao** [comment]
@ersinciftci maybe we can add a prefix then? E.g. `A. `, `B. `

**Comment by ersinciftci** [comment]
@jjgao hmm yeah good idea, or `1.`, `2.`. I'll give it a try

**Comment by jjgao** [comment]
@ersinciftci if using `1.`, `2.`, please make sure `10.` goes after `9.` :)

**Comment by ersinciftci** [comment]
@jjgao yeah I was thinking about that too :)

**Comment by alisman** [comment]
@ersinciftci what's status of this?
