### ISSUE TITLE
August 6th News: color of Total Mutations and Fraction Genome Altered

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4579]
Should we show Total Mutations and Fraction Genome Altered in regular black font? Not sure why it is red.

I also suggest some small tweaks to the News items, see below: 

- The eighth phase of the cBioPortal architectural upgrade is now complete: The Plots, Expression, Network, and Bookmarks tabs, and therefore all analysis tabs on the Results page, have been moved to the new architecture.
- Updated the MutationMapper tool, now connecting to Genome Nexus for annotating mutations on the fly.
- "Total Mutations" and "Fraction Genome Altered" are now available in the Plots tab for visualization and analysis.

![image](https://user-images.githubusercontent.com/11892704/43674043-41295e74-979b-11e8-84a7-ea9c196a99a0.png)

**Comment by jjgao** [comment]
updated.
