### ISSUE TITLE
move legend to top in Plots tab?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4581]
I don't quite like the scrollbar on top in the plots tab. For example, one common use case of the plots tab (and other visualizations in the portal) is that people would just take screenshots and paste in slides. With scrollbar, we cannot do a screenshot of the full figure.

Can we move the legend to the top similar to Expression tab? Alternatively, we could also reduce the size of the plot.

![image](https://user-images.githubusercontent.com/840895/43680353-cc661e1c-9806-11e8-9577-dd9900c294d8.png)

http://www.cbioportal.org/beta/index.do?session_id=5b66124b498eb8b3d5673e99#plots

**Comment by alisman** [comment]
@jjgao @adamabeshouse we can certainly try to compress things.  Unless there is a hard limit to the # of items on x axis though, we can't gaurantee that things will fit in user's browser.  Same situation for Cancer Type Summary tab where there's no limit on study # or type #.  So I think there has to be scrolling.   When me move to SPA, we won't have fixed width so will be able to rely on window's scroll bar.  But I agree that for now, we can just compress the width as we have done with Expression tab.

**Comment by jjgao** [comment]
@alisman it's ok to use a scrollbar if there are many items on x-axis. But since CNA vs mRNA is the default plot, we should at least be able to fit 5 items on axis + legend.

**Comment by alisman** [comment]
agreed, we should tune it so scroll bar is only necessary in extreme cases.  @adamabeshouse

**Comment by adamabeshouse** [comment]
The only way to do this is decrease the box size or move the legend. let me know what you think

**Comment by alisman** [comment]
If it's true that there can be great variability in length of x axis, then I think we should do both.  Cancer type summary has two different box widths.  When we reach a certain threshold, we switch to skinnier.

**Comment by jjgao** [comment]
@adamabeshouse I think it's ok to reduce the box size a little.

**Comment by adamabeshouse** [comment]
@alisman @jjgao should we move the legend to the top for scatterplot as well? and in coexpression tab too?

**Comment by alisman** [comment]
@adamabeshouse I think wherever a chart has no fixed width, we should probably have legend at top.  @jjgao agree?

**Comment by jjgao** [comment]
@alisman agreed. But maybe we can do that after the release if it take a bit time?
