### ISSUE TITLE
oncoprint - pdf download - expression heatmap legend is missing

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4584]
Not sure if this is related to #4550 , but the expression heatmap legend is missing in the PDF download. SVG & PNG downloads are fine.

![image](https://user-images.githubusercontent.com/10508276/43724508-26d3a20e-9968-11e8-9365-49fe5b03b8ff.png)

**Comment by alisman** [comment]
@tmazor is this true in current production as well?

**Comment by tmazor** [comment]
Yes this is on production.

But also, it's slightly more complicated than I realized. If there are no clinical tracks, then the PDF includes the expression heatmap legend. It's only when I add a clinical track that the expression heatmap legend disappears.

**Comment by adamabeshouse** [comment]
im almost sure this has to do with the pdf converter not handling svg gradient elements properly. ill double check

**Comment by jjgao** [comment]
Maybe it's time to look for a js version of svg2pdf again?

**Comment by adamabeshouse** [comment]
@jjgao maybe that is the answer to our pdf woes in general. but for this particular issue i just published a workaround in the oncoprintjs library that seems to work. @tmazor could you check it out? `localStorage.heroku='cbioportal-frontend-pr-1359'`

**Comment by tmazor** [comment]
Yup, that's fixed the problem - PDF download now includes the heatmap legend!
