### ISSUE TITLE
coexpression - pancan atlas missing log2 option

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4586]
PanCan Atlas studies have two mRNA expression studies. When the "batch normalized" one is selected, co-expression has an option to log scale the plot. When the other one is selected, there is no log option:
![image](https://user-images.githubusercontent.com/10508276/43725640-17b2dc6a-996b-11e8-8136-7f21f2c892a0.png)
<br>
![image](https://user-images.githubusercontent.com/10508276/43725651-1cfbd79e-996b-11e8-8058-1273de486056.png)

I'm not sure if this is a data issue or a front end issue?

**Comment by jjgao** [comment]
It may be related to this: https://github.com/cBioPortal/datahub/pull/239

**Comment by adamabeshouse** [comment]
this is the logic we're using in coexpression tab to determine whether log scale checkbox will show

```
@computed get showLogScaleControls() {
        const profileId = this.props.molecularProfile.molecularProfileId.toLowerCase();
        return (
            (profileId.indexOf("rna_seq") > -1) &&
            (profileId.indexOf("zscore") === -1)
        );
    }
```

**Comment by adamabeshouse** [comment]
same thing in plots tab, written differently
```!(/zscore/i.test(axisSelection.dataSourceId)) &&
        /rna_seq/i.test(axisSelection.dataSourceId)```

**Comment by jjgao** [comment]
The profile ID is `acc_tcga_pan_can_atlas_2018_mrna`. Let's wait for @yichaoS to fix the data.

**Comment by adamabeshouse** [comment]
okay, so i'll take myself off this issue

**Comment by jjgao** [comment]
this has been fixed. Only one expression profile exist now.
