### ISSUE TITLE
Cancer Types Summary should default to show cancer types with >=1 alteration

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#459]
We have many cancer types within our system now.

When we load the Cancer Types Summary tab, we end up with many "empty" cancer types (see below):

![screenshot_348](https://cloud.githubusercontent.com/assets/1009066/11143985/42356ed2-89c7-11e5-9e95-34e6a928ec00.png)

Would like to suggest that by default, we only include cancer types with >=1 alteration, to clean up the initial view.  Adding @schultzn to see if he agrees.

**Comment by schultzn** [comment]
Yes, I agree. Don’t we already do this in the cross-cancer queries? 

N

**Comment by aderidder** [comment]
Hi,
We're looking into this at the moment. For the absolute counts it is no problem, as we can set the initial number of altered samples to 1. 
However, what would you like for "Alteration Frequency"? We can set it to a default of 1% and if the maximum is smaller than 1%, set it to 0?

**Comment by ecerami** [comment]
as discussed at today's call with the hyve, +1 to @aderidder suggestion.
