### ISSUE TITLE
IndexOutOfBoundsException on gene panel endpoint

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4590]
The following study's gene pane endpoint is failing with indexOutOfBounds Exception
https://cbioportal.mskcc.org/beta/study?id=acyc_jhu_unpub%2Cacyc_sanger_2013%2Cacbc_mskcc_2015%2Cacyc_sanger_unpub%2Cacyc_mda_2015%2Cacyc_mskcc_2013#summary

https://sentry.io/memorial-sloan-kettering/cbioportal-backend/issues/634196330/?referrer=slack

**Comment by jjgao** [comment]
@zhx828 has this been fixed in the new study view?

**Comment by zhx828** [comment]
@jjgao the gene panel is totally handled at the server side now
