### ISSUE TITLE
add banner to tab that reflect OQL too

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4595]
When OQL is used, let's add banner to all tabs.

- [ ] for tabs that respect OQL, add `This tab reflects the OQL specification from your query.` with green text. Already fixed in https://github.com/cBioPortal/cbioportal/issues/2990 except for the color.
- [ ] for tabs that do not respect OQL, add `This tab does not reflects the OQL specification from your query.` with red (?) color.

@adamabeshouse could you paste a few examples of different colors?

**Comment by adamabeshouse** [comment]
![image](https://user-images.githubusercontent.com/636232/43804487-2eba4632-9a6a-11e8-86ef-ab80fce4c681.png)

**Comment by jjgao** [comment]
@adamabeshouse I like the colors!

**Comment by adamabeshouse** [comment]
@jjgao I'm a little worried red is too alarming.. I was playing with bootstrap alerts. what do you think of this?

![image](https://user-images.githubusercontent.com/636232/43807205-5fa5a7fe-9a75-11e8-9608-48414d47ee4f.png)


![image](https://user-images.githubusercontent.com/636232/43807194-4e48f81c-9a75-11e8-9540-b6f40e7bf597.png)

**Comment by adamabeshouse** [comment]
here it is thinner 
![image](https://user-images.githubusercontent.com/636232/43807328-ef5e2114-9a75-11e8-9063-729fea25e600.png)

![image](https://user-images.githubusercontent.com/636232/43807336-f5c5958c-9a75-11e8-8a68-e3a85d843822.png)

**Comment by adamabeshouse** [comment]
@jjgao so every other tab that we havent already added the 'no' banner to will get a 'yes' banner? are there any excluded, besides network, CN segments, download?

**Comment by jjgao** [comment]
@adamabeshouse I think the blue version is too quiet. Maybe change the warning icon to yellow?

**Comment by jjgao** [comment]
@adamabeshouse could you list all tabs here and the current yes/no banner assignments?

**Comment by adamabeshouse** [comment]
Oncoprint - YES
Cancer Types Summary - YES
Mutual Exclusivity - YES
Plots - NO
Mutations - NO
Co-Expression - NO
Enrichments - YES
Survival - YES
Network - N/A
CN Segments - N/A
Download - YES
Bookmark - N/A
Expression - NO

**Comment by adamabeshouse** [comment]
![image](https://user-images.githubusercontent.com/636232/43859126-c8998836-9b1d-11e8-8aa9-8d79ab947a03.png)

what do people think of this for the warning?

**Comment by jjgao** [comment]
I think yellow is too obvious. I like blue more. @schultzn @tmazor thoughts?

**Comment by tmazor** [comment]
I also prefer blue over yellow
