### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#460]
We received a request a while back, asking us to enable CORS support.

See: https://groups.google.com/forum/#!searchin/cbioportal/almeida/cbioportal/DHpzlqxNVsM/XmxyQKbb3kUJ

I happened to bump into Jonas Almeida at the Google Summer of Code conference, and he asked whether this was in the works.

Has anyone started this already?

**Comment by jjgao** [comment]
It is already supported.

**Comment by jonasalmeida** [comment]
just checked - $.get('http://www.cbioportal.org/webservice.do?cmd=getCaseLists&cancer_study_id=gbm_tcga').then(function(x){console.log(x)}) - it's all good indeed :+1: . Thank you Ethan :-) !
