### ISSUE TITLE
LDAP Authentication no longer working

### ISSUE THREAD

**Issue by alexsigaras** [cBioPortal/cbioportal#4600]
## Versions
Latest version working: 1.13.2
Versions tested but not working: 1.14.0, 1.14.1, 1.15.0

## Problem Definition
When upgrading to the latest cBioPortal versions, the LDAP authentication has stopped working throwing a redirection error for POST /cbioportal/j_spring_security_check.

LDAP configuration is made by changing portal.properties without any additional files or custom configuration

## How to replicate
Simply deploy with a portal.properties file configured for LDAP. Example below

## Example LDAP Configuration

```
## configuration for the LDAP access
ldap.user_search_base=ou=people,o={LDAP_O_DOMAIN}
ldap.url=ldaps://{LDAP_LINK}:636
ldap.manager.dn=
ldap.manager.password=
## The following attributes for are good for ActiveDirectory, for OpenLDAP use "uid" for username
# ldap.attributes.username=sAMAccountName
ldap.attributes.username=uid
ldap.attributes.last_name=sn
ldap.attributes.given_name=givenName
ldap.attributes.email=mail
```

**Comment by alexsigaras** [comment]
@inodb could you help me bring this to the attention of someone from the team that would know more how to help?

Thanks

**Comment by inodb** [comment]
Sure! @pieterlukasse @n1zea144 any clue about this one?

**Comment by alexsigaras** [comment]
Following up on this. I've also noticed that Google Plus auth is also problematic as well since 1.13.2.
Although login works the api throws errors when checking for hugo gene symbols or doesn't render study summaries.

Should we open this as a separate issue?

**Comment by messersc** [comment]
Looks like this is the same problem: https://groups.google.com/forum/#!topic/cbioportal/Wtdy0Q0_Uws

We're on keycloak by now, so I cannot comment further.

**Comment by jjgao** [comment]
@alexsigaras would you have the bandwidth to look into the ldap issue? The ldap support was not implemented by us and we don't have ldap authentication in our private portals. Another option would be switching to keycloak.
