### ISSUE TITLE
Allow multiple PMIDs

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#4601]
As discussed with @jjgao , the PMID field in meta_study.txt for pancan studies now contains multiple IDs, and the meta_study.txt looks like this screenshot below: 
![screen shot 2018-08-07 at 6 47 50 pm](https://user-images.githubusercontent.com/5973438/43806547-672ff324-9a72-11e8-9db5-1e755ebcbc34.png)

Therefore, the PUBMED icon in query form 
![screen shot 2018-08-07 at 6 52 59 pm](https://user-images.githubusercontent.com/5973438/43806750-4606f26e-9a73-11e8-931b-3ff263549c84.png)
 and the PUBMED link in study summary page
![screen shot 2018-08-07 at 6 52 10 pm](https://user-images.githubusercontent.com/5973438/43806756-4d465ede-9a73-11e8-9102-2c8d3548d302.png)
 need to interpret it currently and link to URL formatted with multiple PMIDs such as: https://www.ncbi.nlm.nih.gov/pubmed/27158780,22802077,26804919

A few things might need to be adjusted/checked
- [ ] Correct URL embedded with the PUBMED icon in query form
- [ ] Correct URL embedded with the PUBMED hyperlink in study summary page
- [ ] Adjust the size PMID field in database schema (now only allow 20 char) 
- [ ] validator change: https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/scripts/importer/cbioportal_common.py#L726

**Comment by jjgao** [comment]
Thanks, @yichaoS. Please remove the space after comma (,) in meta file.

Do you know if validator needs to change?

**Comment by sandertan** [comment]
The validator currently checks the length of PMID value (max 20 chars).

**Comment by sandertan** [comment]
@yichaoS is there a PR to update the DB schema? What should the validator check?

**Comment by yichaoS** [comment]
@sandertan The DB schema needs to change. It is listed one of the checklist items. I guess the validator just need to change the length check of PMID field. @jjgao I suggest the length in DB schema change to 100.

**Comment by jjgao** [comment]
@yichaoS 100 sounds good.

**Comment by sandertan** [comment]
@yichaoS I think it's appropriate to modify the documentation, validator, importer and database schema in one PR. The value in the validator code that needs to be changed can be found over here:
https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/scripts/importer/cbioportal_common.py#L726

**Comment by yichaoS** [comment]
@sandertan Added the validator change to the checklist. @jjgao what documents need to be changed?

**Comment by jjgao** [comment]
@yichaoS not sure if we need to change any documents.

**Comment by jjgao** [comment]
@n1zea144 @sheridancbio could you help on this one? It's it's mostly database schema change.

**Comment by sheridancbio** [comment]
@jjgao ok, I will put together a PR for this. Let's do 255 characters though .. so we don't need to increase it again when we make a study that references 11 papers.

**Comment by jjgao** [comment]
@jjgao good idea.

**Comment by sheridancbio** [comment]
Actually, I see there are already fields for lists of PMIDs in tables interaction and drug_interaction, and these are both sized varchar(1024), so I will stick with that standard.

**Comment by jjgao** [comment]
@sheridancbio I think 255 would be sufficient -- I cannot image we associate 100 papers with one study, but I don't feel strongly about it. As for the field name, are you going to change it to pmids in the files and API endpoints too (it would become a big pull request)?  I think it's ok to use `pmid` to minimize the effort.

**Comment by sheridancbio** [comment]
I was just thinking about that @jjgao ... if this field is going to hold a list of pubmed ids now, I think would be best to model that in the API. The model for cancer_study should return a list of strings for PMID rather than a comma separated string that needs to be parsed by the frontend / other clients. That would be cleaner and more semantically correct. We could separate this into two steps though ... first migrate the database table, and then (when convenient) migrate the api. But maybe it is best to do it in one release so we are not delivering comma separated lists in the api output for any length of time.

**Comment by jjgao** [comment]
@sheridancbio it's not necessary to separate them into separate IDs. In the frontend, we are going to use it as one string, e.g. https://www.ncbi.nlm.nih.gov/pubmed/27158780,22802077,26804919.
