### ISSUE TITLE
OQL page has weird characters

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4602]
![image](https://user-images.githubusercontent.com/10508276/43837764-87c675c0-9ae7-11e8-9d45-a1912ed33964.png)

**Comment by adamabeshouse** [comment]
ugh we've been having this problem before. I thought we were done with this. it has something to do with the markdown converter

**Comment by adamabeshouse** [comment]
it seems to be related to using backticks inside tables, the showdown library seems to have an issue with backticks next to pipes which are supposed to indicate the column boundaries.

**Comment by adamabeshouse** [comment]
applying this transformation to the fetched page fixes the bug (it inserts a space between pipes | and backticks ` to fix parsing), but it inserts an annoying space

.replace(/\|\s*`/g, "|&nbsp;`");

![image](https://user-images.githubusercontent.com/636232/44059228-a8e8c970-9f1e-11e8-93a5-f16d0a3f3379.png)

**Comment by adamabeshouse** [comment]
with @alisman's help now we have 

`.replace(/|\s*/g, "|&#8203;");` which inserts a "zero-width" space. PR incoming

**Comment by jjgao** [comment]
@inodb could you deploy the change?

**Comment by inodb** [comment]
@jjgao deployed (might need to do a hard refresh to see it)
