### ISSUE TITLE
Coexpression (and enrichment?) API(s) too slow

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#4606]
The coexpression API is very slow, even on a small study (like http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit#coexp). The enrichments API is not too fast either. 

Would it be possible to optimize this?

Maybe multithreading would improve this significantly.

**Comment by jjgao** [comment]
After discussing more with @adamabeshouse, we think the current performance is acceptable, so I am moving this one to icebox for now.
