### ISSUE TITLE
add pdf download mutation mapper

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4609]
As requested by:

https://groups.google.com/forum/#!topic/cbioportal/8XGdviTwV8U

Currently only svg and png are supported at:

http://www.cbioportal.org/mutation_mapper.jsp

**Comment by jjgao** [comment]
https://github.com/cBioPortal/cbioportal/issues/4610

**Comment by inodb** [comment]
fixed for mutation mapper
