### ISSUE TITLE
add PDF download option to all chars

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4610]
We should have PDF, SVG, PNG, and data.

- [x] oncoprint
- [ ] cancer type summary
- [ ] mutations
- [ ] plots
- [ ] expression
- [ ] co-expression
- [ ] enrichments
- [ ] survival
- [ ] timeline in patient view
- [ ] study view charts (as part of refactoring effort)

It may be a good idea to look for a frontend svg2pdf lib.

**Comment by alisman** [comment]
@jjgao do all charts need data download?

**Comment by jjgao** [comment]
@alisman let's not worry about data for this round.

**Comment by adamabeshouse** [comment]
@alisman whats up with this?

**Comment by alisman** [comment]
@dippindots you could look for a client side pdf library and see how it does with our charts

**Comment by alisman** [comment]
@jjgao 
1. Just to confirm: we will continue to use existing PDF generation 
2. All charts (with exception of timeline in patient view, which currently has no download options) have SVG, PNG, PDF download.  Few if any have data download.  I think the data download needs further specification.
So, the actionable items here right now seem like: adding PDF/PNG/SVG download to timeline on patient view.  
Lets discuss data download.

**Comment by jjgao** [comment]
@alisman @dippindots 

1. yes
2. ok to add PDF/PNG/SVG to plots.

For data, is there any js lib to do json to tsv?

https://codebeautify.org/json-to-tsv-converter

**Comment by alisman** [comment]
@jjgao shall we close this ticket and open a new one for data download?  can you prioritize that?

**Comment by jjgao** [comment]
data download logged here: https://github.com/cBioPortal/cbioportal/issues/5314
