### ISSUE TITLE
Add TGF-β pathway gene list

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4613]
"General: TGF-β Pathway":["TGFB1","TGFB2","TGFB3","TGFBR1","TGFBR2","TGFBR3","BMP2","BMP3","BMP4","BMP5","BMP6","BMP7","GDF2","BMP10","BMP15","BMPR1A","BMPR1B","BMPR2","ACVR1","ACVR1B","ACVR1C","ACVR2A","ACVR2B","ACVRL1","Nodal","GDF1","GDF11","INHA","INHBA","INHBB","INHBC","INHBE","SMAD2","SMAD3","SMAD1","SMAD5","SMAD4","SMAD9","SMAD6","SMAD7","SPTBN1","TGFBRAP1","ZFYVE9"]

**Comment by jjgao** [comment]
Will we be able to support non-ascii characters?

**Comment by alisman** [comment]
@jjgao this is done.  non-ascii char looks fine.

**Comment by jjgao** [comment]
@alisman great. Thank you!
