### ISSUE TITLE
study view - copy number table fails to load

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4617]
This doesn't happen every time, but I have seen it several times in the past few days now. The mutated genes or copy number tables sometimes fail to load:
![image](https://user-images.githubusercontent.com/10508276/43964300-8267b61c-9c8a-11e8-8c28-4adbd9b8d0b4.png)
http://www.cbioportal.org/study?id=paad_icgc%2Cpaad_qcmg_uq_2016%2Cpaad_tcga_pan_can_atlas_2018%2Cpaad_utsw_2015#summary
![image](https://user-images.githubusercontent.com/10508276/43964541-0aabaad8-9c8b-11e8-9483-f5e4a25b5fdd.png)

**Comment by zhx828** [comment]
@tmazor this is a feature we implemented recently when necessary data for the table does not get loaded properly. https://github.com/cBioPortal/cbioportal/commit/441bdf478c675becec65dfd16ee393dc709910a1

Looks like the gene panel endpoint is failing for this particular case. @ersinciftci @onursumer could one of you take a look?

**Comment by jjgao** [comment]
@onursumer could you look into this soon? I think it's because two studies with cna data and two w/o and the backend code cannot handle that.
