### ISSUE TITLE
Replace FAQ 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4622]
@tmazor has put together an updated version:

https://docs.google.com/document/d/1S-mkN2Gr8f-hQ2WES3VzgDskr7UBDa9w25xjgAFlESE/edit?usp=sharing

Can we link to this doc directly on our site?

**Comment by alisman** [comment]
@jjgao  we could do an embed such that this doc would show up in an iframe.  Would that work?   If so, we need to first make the doc available on web to all.

**Comment by jjgao** [comment]
It's published:

```
<iframe src="https://docs.google.com/document/d/e/2PACX-1vSWTtIJZF2tuBimihr8ke-d00DpKh7fydFIQb5xYpE_bMYM9hZyY9OP1Vz1Ts0ow7ob-3h2S19cuB5O/pub?embedded=true"></iframe>
```

**Comment by inodb** [comment]
I think it's slightly confusing to have some pages be pulled as markdown and some through google docs. Isn't it better to update this file: https://github.com/cBioPortal/cbioportal/blob/master/docs/FAQ.md ?

**Comment by jjgao** [comment]
@inodb good point. We used Google Docs b/c it's easy to edit and work together. But maybe now that we have done with the editing, it's better to move to markdown. Hopefully, the future edit will be incremental.

And the published Google doc doesn't look so good...

https://docs.google.com/document/d/e/2PACX-1vSWTtIJZF2tuBimihr8ke-d00DpKh7fydFIQb5xYpE_bMYM9hZyY9OP1Vz1Ts0ow7ob-3h2S19cuB5O/pub?embedded=true

@tmazor @ecerami @schultzn should we move it to markdown on github?

**Comment by jjgao** [comment]
We will transfer the google doc to markdown: https://github.com/cBioPortal/cbioportal/pull/4809
