### ISSUE TITLE
switch to genome nexus for hotspot annotation

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4626]
for 

- [x] oncoprint
- [ ] Oncoprinter
- [x] mutations tab
- [x] MutaitonMapper
- [x] patient view
- [ ] anywhere else

**Comment by adamabeshouse** [comment]
whats up with this?

**Comment by jjgao** [comment]
Thanks, @adamabeshouse.

@zhx828 could you prioritize this one?

**Comment by jjgao** [comment]
Thanks, @zhx828 . Please test thoroughly and keep @inodb in the loop.

**Comment by zhx828** [comment]
@jjgao will do.
