### ISSUE TITLE
Add Mutation Count and Fraction Genome Altered as clinical data

### ISSUE THREAD

**Issue by ersinciftci** [cBioPortal/cbioportal#4631]

**Comment by jjgao** [comment]
backend changes:
- [ ] import script (mutation count)
- [ ] import script (GFA)
- [ ] migration sql
- [ ] remove `mutation_count` and `fraction_genome_altered` tables
- [ ] remove api endpoints
- [ ] anything else?

frontend changes:
- [ ] study view
- [ ] patient view
- [ ] oncoprint
- [ ] plots tab
- [ ] mutations tab
- [ ] anywhere else?

**Comment by jjgao** [comment]
cc'ing @cBioPortal/frontend
