### ISSUE TITLE
Confirm that oncoprint interaction with url params still works with SPA

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4632]
http://cbioportal-frontend-pr-1236.herokuapp.com/results?cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list

**Comment by adamabeshouse** [comment]
this is covered by end-to-end tests @alisman

**Comment by adamabeshouse** [comment]
confirmed
