### ISSUE TITLE
Support patient level enrichment analysis

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#4637]
Currently, enrichment tab allows only sample level analysis. This can bias the results if a study has longitudinal data. Can we add a drop-down in the enrichments tab to allow users to pick if they want the analysis at patient level or sample level?
Enrichments API currently supports patient-level analysis.

**Comment by jjgao** [comment]
I think this would be a nice feature. A few things we need to consider:

1. How to deal with samples that belong to the same patient but in different groups? 
2. Which expression value to pick for mRNA? 
3. For mutations and CNAs, are we going to just combine everything on the patient level?

**Comment by priti88** [comment]
Thanks @jjgao 
1) Do you mean different cancer types?
2) This feature might not make sense for mRNA and we can ignore it?
3) Currently, that is how @ersinciftci does the analysis for the API

**Comment by jjgao** [comment]
@priti88 

1. e.g. a patient as two samples s1 and s2. S1 has a mutation in tp53 and S2 does not. Now a user query tp53 and therefore s1 belongs to altered group and s2 belongs to unaltered group. How would we deal with this patient? Maybe exclude it?

**Comment by priti88** [comment]
I see. In my hack, I include the patient in the altered set. If the patient has TP53 in any 1 of the sample, they will be counted as altered

**Comment by jjgao** [comment]
@priti88 I see, so you basically merge all mutations/cnas to patient level and then treat patients in the same way as we treat samples. That could work.

Since we also have a setting in OncoPrint to show data on patient or sample level. Maybe we should make it a global setting.

Another one we need to add to global setting is Driver vs VUS colors in OncoPrint and Plots.

cc'ing @alisman

**Comment by priti88** [comment]
@jjgao Would this also enable doing enrichment/mutual exclusivity analysis based on just drivers? Maybe a different discussion.

**Comment by jjgao** [comment]
@priti88 it could be. Let's keep it separate: https://github.com/cBioPortal/cbioportal/issues/4646 https://github.com/cBioPortal/cbioportal/issues/4647

**Comment by jjgao** [comment]
@priti88 we will tackle #4646 first and then this one, so it'll take some time. ok?

**Comment by priti88** [comment]
@jjgao sounds good. Thank you

**Comment by jjgao** [comment]
@adamabeshouse let's see if we can support this request in this round.

**Comment by adamabeshouse** [comment]
@jjgao so take the setting from the oncoprint for now?

**Comment by jjgao** [comment]
@adamabeshouse that might work... Maybe it should be a global setting?

Do we need to do any API change since we will compare patients not samples for each gene?

**Comment by ersinciftci** [comment]
Enrichment APIs already have `enrichmentType` property that can be `SAMPLE` or `PATIENT`.

**Comment by adamabeshouse** [comment]
@jjgao if we want to enable this for group comparison (where theres no oncoprint) we'll need to add some UI for it in the enrichments tabs. could just be a checkbox/toggled button?

**Comment by jjgao** [comment]
@adamabeshouse I think it's probably time to design the global settings menu.

**Comment by tmazor** [comment]
@adamabeshouse @jjgao has there been any progress on this?

**Comment by adamabeshouse** [comment]
@tmazor we briefly started talking about the global settings menu, but we're putting it off until group comparison is done

**Comment by tmazor** [comment]
Gotcha - thanks for the update @adamabeshouse !

**Comment by jjgao** [comment]
@adamabeshouse but maybe we could/should do this for the comparison page?

**Comment by adamabeshouse** [comment]
sure, we're about to finish the issues anyway. I can start that tomorrow or the next day.

**Comment by jjgao** [comment]
@adamabeshouse maybe we can implement this option for comparison page? I think we can prioritize implementing this for the Mutations and Copy-number tabs locally since it's easy to merge mutation and copy number events on the patiennt level.

**Comment by adamabeshouse** [comment]
@jjgao @kalletlak looks like its not working for the copy number endpoint, only for mutation endpoint

**Comment by jjgao** [comment]
@kalletlak could you help with this?

I am wondering how we can handle CNA in case there are conflicts?

**Comment by tmazor** [comment]
@adamabeshouse @kalletlak is this done?

**Comment by adamabeshouse** [comment]
no the frontend isnt done

**Comment by tmazor** [comment]
gotcha - i got confused when this closed :)

**Comment by adamabeshouse** [comment]
yeah im not sure how that happened. some automatic github thing I guess 😛

**Comment by kalletlak** [comment]
Implemented in https://github.com/cBioPortal/cbioportal-frontend/pull/2534. closing
