### ISSUE TITLE
review configuration properties spreadsheet

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4638]
https://docs.google.com/spreadsheets/d/1eC0-mU-kdmiInmi1LZRj_-L-oZofmTNOzBYBMr12eUE/edit?usp=sharing

This is a list of all properties read from portal.properties in GlobalProperties.java.   

We need to determine if the are:
1. defunct (no reference in legacy codebase via getter)
2. relevant to frontend 

We then need to make sure that relevant properties are being passed to SPA by new config service and are properly heeded in codebase.

**Comment by inodb** [comment]
@alisman Nice! Looks like it's missing all lowercase properties in `GlobalProperties`, e.g.:
`showCivic`, `showGenomeNexus`, `sessionServiceUrl`, `skinAuthorizationMessage`

**Comment by jjgao** [comment]
@alisman any additional work we need to do on this?
