### ISSUE TITLE
Within OncoPrint Add Clinical Track List is truncated

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#464]
1.  Create an OncoPrint.
2.  Within the OncoPrint, click +

The list of clinical attributes is cut-off.  See below.

![screenshot_363](https://cloud.githubusercontent.com/assets/1009066/11155617/9c45e472-8a14-11e5-94c3-a718db353b3b.png)

This does not occur in production on cbioportal.org.  It only seems to occur on our DFCI instance and my local instance.  We are running latest code from master.  I tried rc branch too, and I see the same problem.

Not sure who can fix this.  Assigning to @jjgao to delegate further.

**Comment by adamabeshouse** [comment]
Are you fully pulled? I think we fixed this with https://github.com/cBioPortal/cbioportal/issues/405

**Comment by ecerami** [comment]
wow, great.  I just pulled the hotfix branch, and it's fixed.

how are we doing this now:

hotfix --> rc --> master?

**Comment by jjgao** [comment]
@ecerami : hotfix --> master --> rc after release. 

rc branch cannot be merged to master before all new features in rc can be released. hotfixes should not depend on that.
