### ISSUE TITLE
Oncoprint: color by COSMIC issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4642]
For the query below, all truncating mutations are colored as Driver by COSMIC, but none of them occur frequently in COSMIC.

http://www.cbioportal.org/index.do?session_id=5b732b30498eb8b3d5675fe8

![image](https://user-images.githubusercontent.com/840895/44113803-495cdd84-9fd7-11e8-91db-fb262f89eb77.png)

![image](https://user-images.githubusercontent.com/840895/44113898-9189ce64-9fd7-11e8-8f22-f022b4896119.png)

**Comment by adamabeshouse** [comment]
@jjgao this is because they all have the search keyword "EGFR truncating", and are tallied up by keyword, not by protein change. should we instead tally the counts only by protein change?

**Comment by jjgao** [comment]
@adamabeshouse I see. We should use the same logic as in the table. Are we matching by protein change in the table?

**Comment by jjgao** [comment]
it's by position for truncating mutations.
