### ISSUE TITLE
oncoprint clinical selector - if only disabled search results, theres some exception

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#4643]
(1) Go to http://www.cbioportal.org/index.do?cancer_study_id=acc_tcga&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=acc_tcga_cnaseq&gene_list=KRAS%2520NRAS%2520BRAF&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=acc_tcga_gistic

(2) Open the clinical selector, try to search for "Von" so that the only result is the disabled option for Von Hippel-Lindau

At this point, you'll see an exception in the console, and you won't be able to type past "v".

**Comment by rnugraha** [comment]
@adamabeshouse what kind of exception? I didn't see it.

<img width="1555" alt="schermafbeelding 2018-08-15 om 07 09 42" src="https://user-images.githubusercontent.com/2835281/44132485-4bacee5c-a05a-11e8-9572-a50dbdeae121.png">

**Comment by adamabeshouse** [comment]
@rnugraha sorry I dont think it will be visible right now, it will be visible on our next hotfix deploy. it would be visible if you use local frontend using `master`

**Comment by adamabeshouse** [comment]
@rnugraha I'm seeing the issue in production now. do you see it?

**Comment by jjgao** [comment]
@rnugraha would you have time to fix this soon? Hopefully it's an easy bug.

**Comment by Sjoerd-van-Hagen** [comment]
How was this introduced? It was not there before.

**Comment by adamabeshouse** [comment]
@Sjoerd-van-Hagen it's been there since some changes made to react-select-checked, since around August 14 :)

**Comment by Sjoerd-van-Hagen** [comment]
@adamabeshouse right, it was recently brought to my attention then. We will have a look to see if it is an easy fix but we are really busy atm so it is hard to say when we will have time to fix it.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen thanks for looking into this. It's a critical issue in production so my goal is to fix it ASAP. Please keep us posted.

**Comment by rnugraha** [comment]
I will look into it. It's a very strange bug.

**Comment by rnugraha** [comment]
Hi all. 

I just released new version of [react-select-checked](https://github.com/thehyve/react-select-checked). This issue should be fixed in the latest version of react-select-checked (v.0.1.11). Could you upgrade your dependencies and let us know for any further issues.

User should be able to filter disabled options now.

![schermafbeelding 2018-11-22 om 15 33 39](https://user-images.githubusercontent.com/2835281/48909345-4ddd6100-ee6d-11e8-96a3-14c07ba87a34.png)
![schermafbeelding 2018-11-22 om 15 33 50](https://user-images.githubusercontent.com/2835281/48909348-503fbb00-ee6d-11e8-8674-b65a10cc2d8a.png)

**Comment by rnugraha** [comment]
@adamabeshouse @jjgao  I added one use case, for disabled options. Please use v0.1.12 instead.

![schermafbeelding 2018-11-23 om 12 37 17](https://user-images.githubusercontent.com/2835281/48941743-129a6b00-ef1d-11e8-88bb-7fa8d4f3a4eb.png)

**Comment by adamabeshouse** [comment]
thanks @rnugraha it seems to be working great

**Comment by rnugraha** [comment]
Good to hear @adamabeshouse. Could you pls close this issue if you think everything is as expected? Cheers.

**Comment by adamabeshouse** [comment]
yes, I will when the PR is closed :+1:
