### ISSUE TITLE
results page global settings

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4646]
We now have settings that affect multiple tabs. The first one is the `driver vs vus` setting that affects both OncoPrint, Plots, and Expression (currently in OncoPrint menu). We are discussing about have another one `Show patients vs samples` for both OncoPrint and Enrichments in #4637. Let's make a global settings/menu to include both after we have SPA.

**Comment by adamabeshouse** [comment]
should we start thinking about this?

**Comment by jjgao** [comment]
@adamabeshouse I think it's a good idea. How about we start with a settings icon next to the link icon? (or is there a better place?)

**Comment by adamabeshouse** [comment]
I think I'd prefer to see it next to Modify Query. Thoughts? @jjgao @alisman

**Comment by jjgao** [comment]
Good idea. (wondering if we should just make it part of Modify Query?) I am also thinking of saving the global setting to local storage...

**Comment by adamabeshouse** [comment]
whats the plan for this? what should we put into this menu?

**Comment by jjgao** [comment]
@adamabeshouse I am thinking of doing #6300 first.

**Comment by adamabeshouse** [comment]
lets just go straight to #6300, this implementation is close but is there a point in making two changes to our UI?

**Comment by jjgao** [comment]
@adamabeshouse good point. Let's go #6300 straight. It's not urgent to have the global settings button yet.

**Comment by adamabeshouse** [comment]
sounds good. then i'll close this

**Comment by jjgao** [comment]
Reopened this b/c we will close #6300.

**Comment by jjgao** [comment]
@adamabeshouse I can think of the two below but I might have missed some. 

- driver vs vus 
- Show patients vs samples 

What did you include in your previous implementation?

**Comment by adamabeshouse** [comment]
oh wait no actually it also had driver annotation settings, and show/hide germline mutations. should we just do that?
![image](https://user-images.githubusercontent.com/636232/67969352-7de5c600-fbdf-11e9-8dbd-68dca71e4c69.png)
https://github.com/cBioPortal/cbioportal-frontend/pull/2213

**Comment by jjgao** [comment]
@adamabeshouse as discussed on slack, let's not include sample vs patient in this round. The individual tab can have their own settings on that.

I think bboth "Annotate data" and "Filter data" can be global. I am wondering there are better section titles?

adding @schultzn and @tmazor @alisman @cBioPortal/product

**Comment by Sjoerd-van-Hagen** [comment]
Do all of these settings influence all of the results tabs? If not, we may want to warn the user about this.

**Comment by tmazor** [comment]
This is exciting! I agree in terms of the sections to include. I do think patient-vs-sample should be included also, but sounds like you discussed including that, just at a later date?

For the filter data, if I deselect one of those, it hides the color on OncoPrint, but it also counts those samples as un-altered on the other tabs, right? We should also adjust the wording for those to make that more clear. Maybe instead of "Show VUS" and "Show germline" it could say "Include VUS/germline" ?

**Comment by adamabeshouse** [comment]
@Sjoerd-van-Hagen theres a warning in the form of the tooltip on the (i) icon hovers, as you can see in the screenshot. do you think that's enough?

**Comment by Sjoerd-van-Hagen** [comment]
@adamabeshouse I think it is enough for this screen but when the navigates to the other tabs he/she may forget. I guess this may be similar to when you put some more complicated OQL, and you would see either
"The results below do not reflect the OQL specification from your query."
or
"The results below reflect the OQL specification from your query."
depending on where you are.

Are there any tabs where the driver/passenger has influence on what is displayed but is not influenced by this setting? Any potential for confusion? Perhaps this is not applicable as it is for the OQL example.

**Comment by adamabeshouse** [comment]
When germline or VUS filtering is active, theres a user warning that looks like the OQL warning you mentioned. Is that enough?

**Comment by Sjoerd-van-Hagen** [comment]
Yes, that should be enough indeed.

**Comment by jjgao** [comment]
> I do think patient-vs-sample should be included also, but sounds like you discussed including that, just at a later date?

@tmazor I think it's ok to add the patient-vs-sample setting. @adamabeshouse let's do that. (I wasn't sure if it should be set globally, ie across the tabs.)

**Comment by tmazor** [comment]
Ok! I would just add that we should make sure to add appropriate warnings to tabs if needed (same as we already have for OQL, germline filtering, etc)

**Comment by adamabeshouse** [comment]
@tmazor which other warnings do you have in mind?

**Comment by adamabeshouse** [comment]
@tmazor @jjgao so then should we keep the enrichments tab dropdown for selecting sample/patient mode?

**Comment by tmazor** [comment]
@adamabeshouse I was thinking about adding warnings for which tabs will/won't respect the sample-vs-patient setting.

Which tabs would actually listen to that setting? Is this list correct?
OncoPrint & Enrichments can do sample or patient level
Survival is only patient level
All other tabs are only sample level??

If it's really just those two tabs, maybe it does make more sense to not include the patient-vs-sample setting in the global menu. Sorry for being indecisive about this.

**Comment by jjgao** [comment]
@tmazor let's leave patient-vs-sample out for now and add it later if we have a stronger reason?

**Comment by adamabeshouse** [comment]
@tmazor @jjgao does that also mean that we will decouple the sample/patient setting in the oncoprint from enrichments?
