### ISSUE TITLE
What exactly do the little up/down arrows do in the OncoPrint add clinical track?

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#465]
What exactly do the little up/down arrows and the blue text labeled "Add a Clinical Track" do in the OncoPrint add clinical track?  They don't seem to do anything.

**Comment by ecerami** [comment]
Tried to add a gif movie, but it wasn't very good :(

**Comment by adamabeshouse** [comment]
weird...I'm not seeing this on my end. But if it's appearing AFAIK it's an unintended consequence of the chozen library.

How did you make that gif movie??

**Comment by ecerami** [comment]
GifGrabber for the mac.

**Comment by ecerami** [comment]
what are the up/down arrows supposed to do?

**Comment by jjgao** [comment]
I am not seeing the arrows either. @ecerami could you do a screenshot? What is your browser?

**Comment by ecerami** [comment]
@jjgao:  you can see the arrows in the first 2 seconds of this clip:  http://www.gfycat.com/ObedientFrigidAlbacoretuna

But, I just tried to grab a screenshot based on latest code.  And, now I don't see the arrows either.  Very strange, but closing for now...
