### ISSUE TITLE
2 CNA case list suffixes for selecting CNA profiled samples

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4651]
There are currently two suffixes used for selecting CNA profiled samples: `_acgh` and `_cna`:

## _acgh
- Used on Query page for selecting the CNA case list when only CNA genetic profile is selected:
https://github.com/cBioPortal/cbioportal/blob/399e1e70d7d5b7601c97c39905f90a2118240cc1/portal/src/main/webapp/js/src/dynamicQuery.js#L505
https://github.com/cBioPortal/cbioportal-frontend/blob/090546ff443214e716ab484273beca20dd625d4f/src/pages/resultsView/network/files/dynamicQuery.js#L505
https://github.com/cBioPortal/cbioportal-frontend/blob/090546ff443214e716ab484273beca20dd625d4f/src/pages/resultsView/network/files/dynamicQuery.js#L505
- Because this was used here, I documented this in File-Formats: https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#case-list-stable-id-suffixes

## _cna
- All studies on datahub that I checked had `_cna` as profile for CNA samples:
https://github.com/cBioPortal/datahub/blob/master/public/acc_tcga_pan_can_atlas_2018/case_lists/cases_cna.txt
- I suspect this one is used on the study view to select CNA samples for CNA table:
https://github.com/cBioPortal/cbioportal/blob/399e1e70d7d5b7601c97c39905f90a2118240cc1/portal/src/main/webapp/js/src/dashboard/model/StudyViewProxy.js#L231
- Used on the datasets page:
https://github.com/cBioPortal/cbioportal/blob/641ace484a24f896d0bbcbb5bf5cacf2416852bc/core/src/main/java/org/mskcc/cbio/portal/util/DataSetsUtil.java#L128
- Also some other parts of the code use this, but I'm not familiar with the functionality of those.

## Proposed solution
Can we use `_cna` everywhere, and document this in File-Formats? This looks like the easiest fix, and is in my opinion the most appropriate name.

**Comment by sandertan** [comment]
@jjgao I made a PR in front end repo, but I'm not sure if I should also fix this in the legacy code in back end repo.

https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/js/src/dynamicQuery.js

**Comment by jjgao** [comment]
Thanks, @sandertan. Don't worry about the legacy code.
