### ISSUE TITLE
CNSegments tab uses legacy api

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4669]
http://www.cbioportal.org/beta/api-legacy/copynumbersegments

**Comment by jjgao** [comment]
@alisman we can try to switch to new version of IGV and they will be able to support our new API.

**Comment by jjgao** [comment]
logged here: https://github.com/cBioPortal/cbioportal/issues/4670

**Comment by alisman** [comment]
@jjgao lets discuss this one tomorrow

**Comment by onursumer** [comment]
switched to the new API with https://github.com/cBioPortal/cbioportal-frontend/pull/1713

**Comment by alisman** [comment]
this will be fixed
