### ISSUE TITLE
Should we lazy load the the network data after the network tab is clicked?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#467]
Currently we load the network data after the page is loaded. If the user does open the network tab, it's a waste of bandwidth. Should we load the data after the network tab is clicked?

**Comment by alisman** [comment]
this may have been result of change that I made.  I'll look.

**Comment by jjgao** [comment]
@alisman it's a really old ticket. I think lazy load would be good since the tab is rarely used.
