### ISSUE TITLE
calls to oncokb fail for CDKN2A-isoform gene names

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4672]
If I query for CDKN2A isoform gene names (CDKN2AP14ARF and CDKN2AP16INK4A), the OncoKB annotations don't load -- see below, where the same mutations are called drivers in the CDKN2A track but passengers in the isoform tracks. The mutations table also fails to load OncoKB annotations.

![image](https://user-images.githubusercontent.com/10508276/44356163-8c353f80-a47c-11e8-9491-6a87a501ba89.png)

http://www.cbioportal.org/index.do?session_id=5b7af99e498eb8b3d56773c9

**Comment by schultzn** [comment]
Yes, I think we should.

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #321](https://github.com/cBioPortal/datahub/issues/321) via [**ZenHub**](https://www.zenhub.com/)
