### ISSUE TITLE
MYD88 mutations are being reporting in Non-canonical transcript (1 study only)

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#4679]
Reported by user:

In this study (and only this study):  "Primary Central Nervous System Lymphoma (Mayo Clinic, Clin Cancer Res 2015)", MYD88 mutations are being reported based on transcript:  ENST00000417037.

*But*, all other studies are using the default UniProt https://raw.githubusercontent.com/mskcc/vcf2maf/master/data/isoform_overrides_uniprot transcript, e.g. ENST00000396334.

This results in a non-standard L273P mutation, versus the commonly report L265P mutation.

Is is possible that this specific study is not being pre-processed by our standard pipeline?

**Comment by ecerami** [comment]
Discussed with @ritikakundra and assigning to her to resolve.

**Comment by ritikakundra** [comment]
Data files on datahub (https://github.com/cBioPortal/datahub/tree/master/public/pcnsl_mayo_2015) look correct. Going to reimport to see if that solves this issue

**Comment by jjgao** [comment]
cc'ing @inodb here: maybe it's another case that is related to genome nexus.

**Comment by jjgao** [comment]
@ritikakundra if it's the same tomorrow, please notify @inodb .

**Comment by ritikakundra** [comment]
Re-import on triage shows the correct annotations

**Comment by ecerami** [comment]
Awesome!  thanks @ritikakundra!!

**Comment by ecerami** [comment]
Ethan reported status back to user.
