### ISSUE TITLE
OncoPrint Tooltips are sometimes persisent, blocking out + button and sort options, etc.

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#468]
Admittedly, this is a small thing, but would be nice to fix.

When you mouse over an individual case within the Oncoprint, the tool tip with the mutation and sample ID is sometimes persistent.

Because of this, if the tooltip can sometimes obscure the + and sort by options, and you cannot click these buttons.  The only way around is to mouse over another column to get rid of the tooltip.

**Comment by adamabeshouse** [comment]
Fixed in new oncoprint
