### ISSUE TITLE
Mutation Mapper, Protein Change Data is Not Working

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#4685]
Reported by user, and confirmed by Ethan.

The Mutation Mapper tool under Visualize Your Data is not plotting the data using the example 'Protein Change' data at the website, or our personal data.  The tool works fine on the Genomic Changes and Genomic and Protein Changes datasets.

I noticed this yesterday. Everything was fine before Monday.

**Comment by inodb** [comment]
good catch - ill take this

**Comment by ecerami** [comment]
great.  tx @inodb!

**Comment by ecerami** [comment]
wow, thanks @inodb.  17 hours from user reporting to fixing! 🥇

**Comment by ecerami** [comment]
Confirmed that bug is fixed in production...  http://www.cbioportal.org/mutation_mapper.jsp
