### ISSUE TITLE
extend documentation on mutation mapper tool input

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4687]
I believe it works like this now.

- When using genomic changes input it shows all annotations
- When using protein change input, only oncoKB and mycancergenome

Question about how combined input should work:

- When using both protein change and genomic changes input, it's not clear what the current logic does. It seems it will annotate hotspot with the information from the genomic position, but will display the protein change inputted by the user. For oncokb and mycancergenome it will use the inputted protein change to annotate.

- Also it's unknown what transcript was used for those annotations that only have the protein changes. The filter to only show mutations on the displayed transcript id wouldn't work

**Comment by jjgao** [comment]
Supporting protein change from the user is tricky -- maybe we shouldn't worry too much about annotation. I think in the long run OncoKB should also be based on genomic location.
