### ISSUE TITLE
Oncoprint reports two different percentages

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#469]
The Oncoprint currently reports two different percentages, usually a difference of 1%.

For example: http://bit.ly/1N4ipXR

![screenshot_364](https://cloud.githubusercontent.com/assets/1009066/11167121/86c02950-8b22-11e5-823f-408d9cb970f5.png)

In the above, the header says 18%, the row says 17%.

**Comment by adamabeshouse** [comment]
ah ok this is almost definitely because of different rounding strategies...will look into

**Comment by adamabeshouse** [comment]
#480
