### ISSUE TITLE
Missing button for custom study

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4698]
In the following examples I queried two studies to make a virtual study, and opened the expression tab. Both expression profiles are RNA Seq V2. 

When querying two 2 TCGA studies, there are 2 study buttons under "Select Studies". Where are the button texts coming from? Are they parsed from the parentheses in the study names? 

<img width="663" alt="screen shot 2018-08-23 at 12 14 42" src="https://user-images.githubusercontent.com/9624990/44520162-6b185d00-a6cf-11e8-9f75-7af71c052079.png">

When using a custom study, "Select Studies" is missing a button for the custom study. My guess is that this is because the custom study does not have parentheses in the name.

<img width="641" alt="screen shot 2018-08-23 at 12 15 25" src="https://user-images.githubusercontent.com/9624990/44519998-f513f600-a6ce-11e8-8724-6c29432d56ae.png">

1. Can we add button(s) for non-TCGA studies? 
2. Also, can we document this feature? Where is button text coming from? 

https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#meta-file

**Comment by jjgao** [comment]
The two TCGA buttons are hard coded. Custom list is for selecting any studies.
