### ISSUE TITLE
Can we apply style of scatter points via the victory template?

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4699]
E.g. is easy enough to make coexpression chart points look like the new ones 
![image](https://user-images.githubusercontent.com/186521/44534771-8894f900-a6c6-11e8-8b59-6abe98da2daf.png)

**Comment by adamabeshouse** [comment]
after talking with @alisman the change we would make is to make the dots in coexp tab the same size, for uniformity, because applying the same styles on theme-level doesn't make sense
