### ISSUE TITLE
Timeline shows the same event with different color for different patients

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#4706]
Timeline currently shows the same event type (and subtype) with different colors across different patients. The crucial difference seems to be the number of event types.

For example XRT is orange here
www.cbioportal.org/patient?caseId=P07&studyId=lgg_ucsf_2014

and green here
http://www.cbioportal.org/patient?caseId=P04&studyId=lgg_ucsf_2014

The server could assign a global order on event types across all patients and color would be determined by this global order. 
Or client code could hash together event type and subtype and modulo it by the number of colors so that there is a deterministic mapping between event type and color - this wouldn't guarantee unique colors but it would be easier to implement.

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/cbioportal/issues/6952
