### ISSUE TITLE
mRNA z-score metadata missing in Patient view and Oncoprint

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4709]
The various UIs do not have a standard text for the tool-tips of the mRNA expression z-scores shown in different places. See examples below.

Patient view - value is labeled as "mRNA z-score" and a hard-coded title is given "mRNA level of the gene in this tumor" and `%` is used to indicate percentile(?): 
![image](https://user-images.githubusercontent.com/2900303/44590909-89a85200-a7bc-11e8-9e5d-5158a6d71d6c.png)

Heatmap in oncoprint - value is labeled as "MRNA" and no further explanation is given. "z-scores" is only mentioned in the menu when adding the heatmap:
![image](https://user-images.githubusercontent.com/2900303/44591209-6c27b800-a7bd-11e8-8e09-4e318192b15b.png)

Homepage - tooltip shows documentation text as configured in the metadata of the genomic profile. 
![image](https://user-images.githubusercontent.com/2900303/44591262-88c3f000-a7bd-11e8-8d84-f104073ec857.png)

**Desired solution**: 
 - use another symbol for percentile (maybe _P_?) in Patient view, or no symbol at all
 - just as in the homepage, the metadata of the genomic profile should be used in the Patient View and Oncoprint (see mockups below)
- the tooltip for the values in the oncoprint should be made the same as the one in the Patient View.

![image](https://user-images.githubusercontent.com/2900303/44591595-70080a00-a7be-11e8-9cc4-8bcb8b4d6139.png)

![image](https://user-images.githubusercontent.com/2900303/44591974-6cc14e00-a7bf-11e8-8704-de284569d3c2.png)

**Comment by jjgao** [comment]
@pieterlukasse good points. Agreed with the last two solutions. Not sure about the first one. Related to https://github.com/cBioPortal/cbioportal/issues/4713 also.
