### ISSUE TITLE
seems like deep deletions are missing on plots tab

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4710]
For this PR, merge master to rc:

https://github.com/cBioPortal/cbioportal-frontend/pull/1409/files?short_path=9a8eaad#diff-9a8eaad85de523b9b05aa730dfbcae66

it seems there are no deep deletions anymore for `tests/screenshots/reference/plots_tab_clinical_vs_molecular_element_chrome_1600x1000.png`

not sure if that is expected @adamabeshouse ? Seems like it might be an error

**Comment by adamabeshouse** [comment]
I see your concern and Im confused too but it seems like there must have been some kind of data change or something, because when I look in the network response, there in fact are no deep deletions. So Im really not sure.

**Comment by adamabeshouse** [comment]
@jjgao @ritikakundra @yichaoS does this make any sense? did data recently change to reassign deep deletions to amplifications in brca_tcga?

**Comment by inodb** [comment]
@adamabeshouse it's weird cause there are deep deletions on master right? 

http://www.cbioportal.org/index.do?cancer_study_id=brca_tcga&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=brca_tcga_cnaseq&gene_list=TP53%252520MDM2&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic#plots

**Comment by inodb** [comment]
@adamabeshouse ah no i guess they are missing there as well: https://github.com/cBioPortal/cbioportal-frontend/blob/master/end-to-end-tests/screenshots/reference/plots_tab_clinical_vs_molecular_element_chrome_1600x1000.png

But only since 5 days ago?

**Comment by inodb** [comment]
@adamabeshouse looks like they've only gone missing for MDM2

**Comment by adamabeshouse** [comment]
at @inodb 's suggestion, by exploring an older version of `master`, before those changes that changed the screenshots, Ive found that there was a bug before and it seems the chart for MDM2 was colored using TP53 data. so the new screenshot is correct, and theres no data issue.
