### ISSUE TITLE
[rc] mutation count values differ and axis label changed

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4712]
See: https://13917-66571349-gh.circle-artifacts.com/0/imageCompare.html

- [x] Counts on the y axis are wrong (see patient view)
- [ ] from `Total mutations` on y axis of plots tab to `Mutation Count`

**Comment by jjgao** [comment]
The reference screenshot seems to have the correct number of mutations (you can go to the patient view to find out). @ersinciftci could you investigate?

**Comment by ersinciftci** [comment]
@jjgao it's changed because `Total mutations` was hardcoded in the frontend, but now it's coming as clinical data and the attribute's name is `Mutation Count`, so it shows the attribute's name, just like all other clinical data in the dropdown.

**Comment by inodb** [comment]
@ersinciftci the counts are really different as well as JJ mentioned - im going to change the title of this issue

**Comment by inodb** [comment]
Closing, cause counts are correct now. Label change is fine I assume?
