### ISSUE TITLE
Confusing mRNA Expression column in Patient View

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4713]
The current implementation of the mRNA Expression column in Patient View mixes up two different statistics in the same visualization, leading to wrong interpretation of one or both statistics (or just leading to plain confusion and an inability to make any interpretation at all). 

Screenshot of the current feature:
![image](https://user-images.githubusercontent.com/2900303/44662910-5c071700-aa0f-11e8-903f-ccfb360deb19.png)

While the z-score (if populated correctly in the data files before uploading to cBioPortal) is derived from a comparison to a reference population, the percentile displayed in the patient view is just a comparison of the z-scores to the other z-scores for this same gene in the same genetic profile/study (see [code here](https://github.com/cBioPortal/cbioportal/blob/master/service/src/main/java/org/cbioportal/service/impl/MrnaPercentileServiceImpl.java#L33)). In other words,  the z-score and the percentile are comparing the expression value found for the gene to two very different groups. This means it is perfectly possible to have for example, in the same patient view, a gene with z-score=`-3.0` and percentile=`90` while another gene has z-score=`-3.0` and percentile=`5`. 

Desired solution:
- remove the percentile part and just show the z-score. The slider could stay, but let it range between -3 and 3 (the same range of values we have for the heatmap in the oncoprint).

**Comment by pieterlukasse** [comment]
notify: @jjgao

**Comment by jjgao** [comment]
Another option is: using the original mRNA (instead of z-scores) profile and still showing percentiles. The issue with z-scores is that they are oftentimes not very meaningful since the original data (e.g. rnaseq) does not follow normal-like distribution.

**Comment by pieterlukasse** [comment]
@jjgao if the main use case for this specific visualization is to give the user an impression of how the expression of the gene for the current sample relates to the expression of the same gene in the other (tumor) samples of the study, then I agree with your alternative. However, if the main use case is to give the user an impression of how the expression of the gene for the current sample relates to the expression of the same gene in the **reference normal samples** of the study, then I think the alternative is not appropriate and we need to go for the z-score solution.

using the original mRNA and still show percentiles would be good if the

**Comment by jjgao** [comment]
@pieterlukasse that's a good point. The current design was for comparing to other samples. And currently we don't have z-scores calculated with reference normal samples.
