### ISSUE TITLE
[testing expression sample coloring] mobx error

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4716]
Go here: http://www.cbioportal.org/index.do?session_id=5b84611d498eb8b3d5678e93
Click on Expression and then IDH1. There is a mobx error in the console

**Comment by jjgao** [comment]
If SPA would solve it, I think it's ok to wait.

**Comment by alisman** [comment]
I can confirm that this is fixed in spa:
http://www.cbioportal.org/alpha/results?session_id=5b84611d498eb8b3d5678e93
