### ISSUE TITLE
[testing expression sample coloring] y-axis no longer starts at 0

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4720]
On production, the y-axis always goes to 0. The new version uses a y-axis scaled to the data. Was there a reason for this change?
![image](https://user-images.githubusercontent.com/10508276/44685121-aa6ce380-aa18-11e8-931b-dc4e5a741fa7.png)
![image](https://user-images.githubusercontent.com/10508276/44685126-ae006a80-aa18-11e8-96eb-f477402058e0.png)

**Comment by adamabeshouse** [comment]
no reason. should we keep it as before?

**Comment by adamabeshouse** [comment]
@tmazor @alisman thoughts?

**Comment by jjgao** [comment]
@adamabeshouse let's keep it as before.
