### ISSUE TITLE
oncoprint images configurable with absolute path?

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4723]
Oncoprint loads some images right now.   Could we make the library configurable so it would accept an absolute path for these images?  I can explain why this is necessary.

**Comment by adamabeshouse** [comment]
@alisman right now it doesnt accept the image paths as a parameter. would that be necessary?

**Comment by adamabeshouse** [comment]
instead, used webpack in oncoprintjs to use data urls instead of relative paths
