### ISSUE TITLE
"download data" component fails

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4739]
User reported bug: https://groups.google.com/forum/#!topic/cbioportal/vnOkiXE3tEI

Doing this:
![image](https://user-images.githubusercontent.com/10508276/44913153-85b78b00-acfa-11e8-8254-5603db093bed.png)

Produces this:
![image](https://user-images.githubusercontent.com/10508276/44913147-7df7e680-acfa-11e8-84c3-82f26bf14e7a.png)

**Comment by jjgao** [comment]
@onursumer maybe you can help with this one? Let's fix it soon.

**Comment by inodb** [comment]
Would it be ok to change it to go directly to the download tab? Doesn't feel super intuitive to just download the mutation data imo

**Comment by alisman** [comment]
@jjgao determined yesterday that we DO need to retain that functionality.  maybe not everything is available on download page?

**Comment by inodb** [comment]
This has been fixed and deployed
