### ISSUE TITLE
Network view comes up empty

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#474]
Sometimes (when the network tab is clicked too quickly? or on your first try?) the network view comes up empty!

**Comment by jjgao** [comment]
We had a hand-on workshop this afternoon. A few users had this issue -- empty network view.

**Comment by ugurdogrusoz** [comment]
I confirmed that this was fixed in a local deployment. I'll check again once a beta deployment is available.
