### ISSUE TITLE
Improve performance of study view

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#475]
Tasks:
- profile study view to find bottlenecks: profile frontend and backend code, including DB queries.

Goals:
- report with main bottlenecks identified
- bottlenecks solved or addressed in specific new issues (add reference to these issues)

**Comment by pieterlukasse** [comment]
@aderidder : @zhx828 started an [RFC document (RFC14)](https://docs.google.com/document/d/19xaYBvciCCYjY1j244Dl1wCpiQn6f0r4DzmKajdWE04/edit) for this.

**Comment by zhx828** [comment]
ScatterPlot Optimization SHA: d8b6573943bd28d9c1b32ff4d4238f294ec42d86

**Comment by zhx828** [comment]
Help needed on the Table.js initDataTable function. Looks like most of time has spend on redrawing the dataTable. I couldn't find any better solution for this except using other library.

You might want to use my branch to do the further improvement. (https://github.com/zhx828/cbioportal/tree/study-view)

**Comment by zhx828** [comment]
Help also needed on drawPlots function in StudyView ScatterPlot(https://github.com/zhx828/cbioportal/blob/study-view/portal/src/main/webapp/js/src/study-view/component/ScatterPlots.js). This is more like d3 performance issue. May need to find a better method.

**Comment by pieterlukasse** [comment]
Hi @zhx828 , thanks for sharing the improvements. For your information, @aderidder and I are also looking at ways to improve some bottlenecks. We have worked on improving performance related to:
- qtips in query form case lists
- qtips and timeout in query results page: Plots view, Enrichment tab, 
- improvements in query results page to ensure each tab only gets loaded when clicked

We are also planning to improve some parts of Study view like the Datatables .

**Comment by zhx828** [comment]
@pieterlukasse Should I send a pull request including about all my edits and maybe later you can merge with yours. Then we can discuss about the next common goal?
