### ISSUE TITLE
Expression too colorful...

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4755]
The Expression plot is really colorful with both mutations and CNAs. Turning on only one of them seems fine. Should we only turn on mutations only or CNAs only by default?

http://www.cbioportal.org/index.do?session_id=5b903556498eb8b3d567b494

![image](https://user-images.githubusercontent.com/840895/45117804-9c0f7d80-b124-11e8-8f40-ddebea20b3a0.png)

![image](https://user-images.githubusercontent.com/840895/45118226-ee04d300-b125-11e8-931b-144c75744eef.png)

@cBioPortal/product

**Comment by schultzn** [comment]
I agree, showing only mutations might be a better default.

We should probably also start drawing dots with more transparency, so that users get a better idea of the density of the data points. This is especially important in the mutations vs CNA plot on the study view.
