### ISSUE TITLE
Improve performance of query page

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#476]
The query page itself can be very slow when having large studies (>5K samples) with many case lists (>100 case lists). When  clicking on such a study in the query page, it can take seconds before the respective drop-down with case lists is rendered. 

Screenshot below shows an example of the query page, a study selected and the drop-down with case lists. 

Tasks:

- profile query page to find bottlenecks: profile frontend and backend code, including DB queries.

Goals:

- report with main bottlenecks identified
- bottlenecks solved or addressed in specific new issues (add reference to these issues)

![image](https://cloud.githubusercontent.com/assets/2900303/11187410/8b59b570-8c86-11e5-97d1-1059e2f71e8a.png)

**Comment by ecerami** [comment]
We currently have 672 case lists within one study, and this may be a significant factor in the slow-down on our end.

**Comment by pieterlukasse** [comment]
Profiling test: test it with 672 case lists, avg size of 100 cases

**Comment by pieterlukasse** [comment]
solved via #653
