### ISSUE TITLE
The oncoprint does not show any inforamtion from the study view linkout

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4768]
The linkout is to index.do. In the new implementation, the index.do will be redirected to results page. There are two issues here:
1. The mutations tab is no longer selected by default
2. The oncoprint does not show any TP53 mutations

Reproduce:
New: http://www.cbioportal.org/alpha/study?id=acc_tcga_pan_can_atlas_2018#mutations
Production: http://www.cbioportal.org/study?id=acc_tcga_pan_can_atlas_2018#mutations

Click on the TP53 gene linkout

**Comment by alisman** [comment]
lets discuss

**Comment by adamabeshouse** [comment]
the oncoprint issue is: default oql not going through to the query for some reason
