### ISSUE TITLE
validator should not allow MUTATION_COUNT and FRACTION_GENOME_ALTERED

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4769]
We removed `fraction_genome_altered` and `mutation_count` tables and instead created auto populated clinical atttributes MUTATION_COUNT and FRACTION_GENOME_ALTERED. There should be an error raised in the clinical data validator when this value is used. We should probably also update the docs to indicate there are computed clinical attributes

**Comment by fedde-s** [comment]
It looks like a PR was merged to address this bug. Reopen if I misread.
