### ISSUE TITLE
Keycloak / spring security SAML workflow fails (only in Chrome)

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4770]
Login and redirect to cBioPortal homepage works fine in Firefox, but fails in Chrome with 403 error back from tomcat. 

Should be reproducible with docker setup: https://github.com/thehyve/cbioportal-docker and https://github.com/thehyve/cbioportal-docker/blob/master/docs/using-keycloak.md

Firefox screenshots: 

![image](https://user-images.githubusercontent.com/2900303/45349451-9ba63500-b5b1-11e8-98f6-385dffa72dea.png)
![image 1](https://user-images.githubusercontent.com/2900303/45349469-a52f9d00-b5b1-11e8-9485-2c17aa8c9a0e.png)

Chrome result after login page:
![image 2](https://user-images.githubusercontent.com/2900303/45349513-c09aa800-b5b1-11e8-890c-94f8b1662412.png)

**Comment by pieterlukasse** [comment]
Also fails for 1.16.0 and 1.15.0 in the same way (Chrome only). 

However, we have a deployment based on v1.15.0 https://github.com/thehyve/cbioportal/commit/d96c6acfeae21ce427705ea4769c39f84306fb90 and a frontend based on https://github.com/thehyve/cbioportal-frontend/commit/a3db711e7f94534b58e2915e94bd91e08396028c (+ some minor frontend changes on top) which is working fine for Chrome.

**Comment by pieterlukasse** [comment]
Could it be related to CSRF or other security implementation differences in Chrome vs Firefox? Perhaps because my test is with self-signed certificates on localhost? One test to do is: deploy same release on a real server with valid certificates. @inodb : why was CSRF protection disabled here https://github.com/cBioPortal/cbioportal/blob/rc/security/security-spring/src/main/resources/applicationContext-security.xml#L60 ?

**Comment by pieterlukasse** [comment]
Other possible checks: check for differences in the headers of the request/response of call to `/cbioportal/saml/SSO` URL. E.g. what is the `Referrer Policy`, `Remote Address`, `Access-Control-Allow-Origin`, etc?

**Comment by inodb** [comment]
@pieterlukasse i think @n1zea144 disabled csrf protection for now when we moved to spring security v5 to limit the scope of the changes required to make the upgrade

**Comment by pieterlukasse** [comment]
New results: it does not seem to be related to self-signed certificates. Just tested on http and the same behavior is observed. Versions tested here Keycloak 3.1.0.Final , cBioPortal Version 1.15.1-SNAPSHOT.

Different versions of Keycloak, cBioPortal, with or without https all show same behavior: works in Firefox, not in Chrome. Next test: try with old version of Chrome(or Chromium?)

**Comment by c4cam** [comment]
Hi, is this issue resolved? Just encountered the same problem after upgrading my Keycloak.

**Comment by inodb** [comment]
@c4cam the fix from pr #4878 should have fixed it afaik. That fix is in version v1.17.1.  We don't have keycloak set up here for testing, so please let us know if this fix isn't working for you - Thanks!

**Comment by c4cam** [comment]
Nice! Will give it a go now.

**Comment by c4cam** [comment]
Thanks, it works! Super duper 👍
