### ISSUE TITLE
Several config settings require changing source code folders

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#4774]
As recognised by the [Twelve-Factor App](https://12factor.net/) methodology, it's good practice to [separate deployment-specific configuration from code](https://12factor.net/config) for flexibility and ease of deployment. cBioPortal documents at least 8 config files in ways that do involve changing files in source code directories:

- The `skin.right_logo` and `skin.tag_line_image` properties documented [in this table](https://github.com/cBioPortal/cbioportal/blob/v1.16.0/docs/Customizing-your-instance-of-cBioPortal.md#cbioskins-properties) are paths inside the `portal/src/main/webapp/images` source folder, and require placing files there. Would it be feasible to have the backend access these file from an absolute path at runtime, rather than compiling them into the WAR?
- The news, FAQ and about pages, documented [here](https://github.com/cBioPortal/cbioportal/blob/v1.16.0/docs/Customizing-your-instance-of-cBioPortal.md#creating-your-own-local-newsabout-or-faq-page), do have an option to access their files from a separate web service, but otherwise only recognise paths within `portal/src/main/webapp/content`, similar to the images above. Again, would it be feasible to serve files without compiling them along with the source code?
- The styling of clinical attributes in the patient view [is also documented](https://github.com/cBioPortal/cbioportal/blob/v1.16.0/docs/Customizing-your-instance-of-cBioPortal.md#custom-styling-of-the-patient-views-clinical-data) as configurable, but doing so explicitly involves forking a version-controlled source code file in place.
- The [Keycloak integration guide](https://github.com/cBioPortal/cbioportal/blob/v1.16.0/docs/Authenticating-and-Authorizing-Users-via-keycloak.md#export-configuration-for-cbioportal) documents placing a SAML certificate and a (private) key in the `src/main/resources` folder and having properties access them via the Java classpath.

I feel like improving this should be doable, given that [at least one other configurable file](https://github.com/cBioPortal/cbioportal/blob/v1.16.0/docs/portal.properties-Reference.md#gene-sets-used-for-gene-querying) is accessed via a full path starting with `file:/`, listed in the central configuration.

**Comment by fedde-s** [comment]
I do not aim to make every single line of `portal.properties` an environment variable any time soon, as it does allow changing all settings in one non-version-controlled place so far, even if it's a bit Java-centric. Changing it might take a lot of work, and annoy everyone who's running a cBioPortal server somewhere.

I *am* working on something that I hope will allow `portal.properties` to be swapped out at runtime by simply pointing an environment variable to it.

**Comment by jjgao** [comment]
cc'ing @alisman on this as he has been working on separating frontend properties from backend ones.

**Comment by fedde-s** [comment]
I've addressed the `portal.properties` issue in https://github.com/cBioPortal/cbioportal/pull/4787, as discussed in the `#cloud` channel on Slack over the past months.

**Comment by alisman** [comment]
@fedde-s Yes I can make sure that skin properties allow for absolute paths as you say.

**Comment by fedde-s** [comment]
Nice! I think that would really help simplify the Docker setup, once the pull request I linked is integrated.
