### ISSUE TITLE
SV: moving configs.json

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4778]
We need to find a way to define the custom [configs.json](https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/js/src/dashboard/resources/configs.json)

**Comment by fedde-s** [comment]
If it's configuration likely to sometimes vary between different people's installations or even deployments of the same institute, I hope it can be kept out of the `src/` folders, but settable from the same place as all other configuration.  I tried to express general aim in issue https://github.com/cBioPortal/cbioportal/issues/4774.

The Twelve-Factor App methodology I linked there suggests environment variables as that one central place, and I'm hoping that I can get the location of our central `portal.properties` file fully configurable at runtime via the `$PORTAL_HOME` variable soon.

**Comment by fedde-s** [comment]
If it is indeed such a setting, this will affect containerisation/cloud deployment and it might be useful to notify people working on that.

**Comment by jjgao** [comment]
@alisman would this be part of the SPA effort?

**Comment by fedde-s** [comment]
This sounds more like a feature or enhancement than a refactoring.
