### ISSUE TITLE
Automated validation of internal URLs in markdown files

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4782]
It would be nice if URLs in our markdown files that link to other internal markdown files/sections are automatically checked in a weekly run and perhaps on commit.

Cases of broken URLs in our documentation:
- Modification of filename / removal of a markdown file, which causes the URL in another file that refers to this file to be broken.
- Modification of title in a markdown file, which causes the URL in table of contents to break.
- External web-locations might be down permanently. For example the MAF format at NIH NCI Wiki is not available anymore (#4416). Checking these might be trickier, as these can be down temporarily.

Perhaps this can be automated (and integrated in CircleCI) with a tool like:
- https://github.com/tcort/markdown-link-check
- https://github.com/remarkjs/remark-validate-links

**Comment by fedde-s** [comment]
It might be simpler and more robust to check it on the CI server when someone pushes to a branch or makes a pull request, instead of wiring commit hooks into people's local git checkouts.
