### ISSUE TITLE
Refactor addGenesAndSubmit to work with SPA (QueryStore)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4783]

**Comment by alisman** [comment]
Let me know if you need help with this.   Work should be don

**Comment by adamabeshouse** [comment]
Im confused lol

**Comment by alisman** [comment]
![image](https://user-images.githubusercontent.com/186521/46370883-d5b8a300-c654-11e8-8f76-fb1ca8118a6c.png)

This button needs to be integrated with new architecture.  I guess it should submit a new query

**Comment by jjgao** [comment]
In the new architecture, ideally the new genes should be added to the query instead of submitting a new query.

**Comment by adamabeshouse** [comment]
we decided to go back to oncoprint

**Comment by jjgao** [comment]
Base on discussion today (https://github.com/cBioPortal/cbioportal/issues/4937), we would like to mimic the current functionality due to technical reason. We will discuss again on this once https://github.com/cBioPortal/cbioportal/issues/4937 is addressed.
