### ISSUE TITLE
Virtual studies listed as normal studies in query selector when tree setting is non-nested

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4788]
When going to e.g. www.cbioportal.org/genie one can see other virtual studies listed at the same level as other studies, because there is no nesting. I guess this can also be solved by having separate session services for each portal.

**Comment by jjgao** [comment]
There are two issues here:

1. we are displaying virtual studies across portals for the same user. Using a separate collection for each portal would solve the problem. Currently, we are all using `xxx/sessions/msk_portal/`. Let's create separate collections. @inodb Can you work on that? I think it would also make migration later easier.

2. when we don't show the tree structure, all virtual studies are listed in the same section as the main studies. Maybe we should always list the virtual studies under it's section no matter how many levels of the three we decide to show.

![image](https://user-images.githubusercontent.com/840895/45449066-27978a00-b6a2-11e8-8ca5-66e7e3b19d6c.png)

**Comment by jjgao** [comment]
closing this since they are separately logged.
