### ISSUE TITLE
co-expression: use scientific notation for p/q-values

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4790]
Currently:

![image](https://user-images.githubusercontent.com/840895/45448027-59f3b800-b69f-11e8-9043-3881e2a457c3.png)

Let's change it to scientific notation, similar to Enrichments.

![image](https://user-images.githubusercontent.com/840895/45448129-99ba9f80-b69f-11e8-9ada-853e486897a5.png)

**Comment by inodb** [comment]
@jjgao send a PR for this since it was p simple. Do we need the formatting with conditional bold text as well?

**Comment by inodb** [comment]
@jjgao also i noticed enrichments sorts everything by asc q-value by default, should that be same for co-expression?

**Comment by zhx828** [comment]
@jjgao @inodb we probably should standardize exponential fraction digits. In the study view, I'm setting it to three.
