### ISSUE TITLE
use separate session service collections for different portals

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4791]
we are displaying virtual studies across portals for the same user. Using a separate collection for each portal would solve the problem. Currently, we are all using xxx/sessions/msk_portal/. Let's create separate collections. @inodb Can you work on that? I think it would also make migration later easier.

**Comment by jjgao** [comment]
@inodb found this issue logged early :)

**Comment by jjgao** [comment]
@inodb should this be closed?

**Comment by inodb** [comment]
yes
