### ISSUE TITLE
hide chart if only one value in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4795]
I remember we used to hide chart if the value of all samples for an attribute is the same. Can we re-enable that?

For example, in this study: http://www.cbioportal.org/study?id=ampca_bcm_2016, `With Mutation Data`, `With CNA Data` (note all `no` here), and `# of Samples Per Patient` should be hidden. 

![image](https://user-images.githubusercontent.com/840895/45453669-726bce80-b6af-11e8-8b20-b33baff08524.png)

It's ok to do that in the new study view.

**Comment by zhx828** [comment]
@kalletlak JJ and I had a discussion the other day. For these charts, at this moment, we don't have a plan to support them in the clinical data table yet. We need to manually add in the front-end.
