### ISSUE TITLE
co-expression tab: add volcano plot (on top of the current scatter plot) of spearman correlation (x-axis) vs q value (y-axis).

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4798]
Moved issue from https://github.com/cBioPortal/cbioportal/issues/4248 to separate issue, so we can schedule it for a different release. See that issue for discussions.

From there by JJ:

I think we can use the same layout (and the same component?) as `enrichments` tab. We can move the current scatter plot to left too (replacing the box plot in the screenshot below; maybe moving the legend under the plot).

![image](https://user-images.githubusercontent.com/840895/45440116-6e2cba80-b689-11e8-93c2-bf047ab925ba.png)

**Comment by adamabeshouse** [comment]
@jjgao but the coexpression table does not have as many columns. And this would shrink the scatter plot a lot, is that okay? Our scater plot shows more info than the expression boxplot - it also has mutation info. And there is the log scale selector checkbox as well.

What about shrinking the coexp tables height, and putting the volcano plot below it, while keeping the scatter plot the same size and location?

**Comment by jjgao** [comment]
@adamabeshouse I think we should keep the same positions as Enrichments. It's ok to make the plots bigger than the ones in Enrichments.
