### ISSUE TITLE
are we missing MUTATION_COUNT attribute for sequenced samples without mutations

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4799]
https://github.com/cbioportal/cbioportal/blob/rc/core/src/main/java/org/mskcc/cbio/portal/dao/DaoMutation.java#L141

**Comment by ersinciftci** [comment]
@jjgao do you know if they were missing from the `mutation_count` table before? Because the query is very similar to the old one inserting to `mutation_count`.

**Comment by jjgao** [comment]
@ersinciftci they were probably also missing before. I think we should fix it. Maybe a follow up pr?

**Comment by jjgao** [comment]
Just checked. We are missing them in the `mutation_count` table.

**Comment by jjgao** [comment]
duplicate #4895
