### ISSUE TITLE
Mutation Mapper doesn't produce frameshift variants

### ISSUE THREAD

**Issue by stublakemore** [cBioPortal/cbioportal#4806]
Hi,

I've been using the online version of cBioPortal Mutation Mapper to produce Lolliplots of my mutation data for the last year or so, but after a break using the website, it seems the graphs no longer produce any form of indels. The format of my tables have not altered in the mean time, and the Mutation Mapper with the same table still plots SNVs, splice variants and stop mutations, without producing any sort of error message regarding the indels. 

Could it be that the Mutation Mapper has received an update in the last few months? If so, is this the right platform to ask whether anyone responsible for the code could take a look? 

Many thanks in advance!

**Comment by jjgao** [comment]
@stublakemore would you please share some of your data here so we can debug? Thanks.

**Comment by stublakemore** [comment]
Hey @jjgao ,

Thanks for getting in touch. Yeah sure. Attached are two images, both created using the same table (also attached). 
List of mutations:
[BIRC3_Mutations.txt](https://github.com/cBioPortal/cbioportal/files/2389884/BIRC3_Mutations.txt)

New image not producing indels:
[BIRC3_lollipop_new.svg.pdf](https://github.com/cBioPortal/cbioportal/files/2389886/BIRC3_lollipop_new.svg.pdf)

Old image with indels produced:
![image](https://user-images.githubusercontent.com/43299208/45644136-35437a00-babd-11e8-8570-6cd99a3db408.png)

Many thanks!

**Comment by onursumer** [comment]
Hi @stublakemore,

Thanks for the details.

I did a quick debug and seems like a recently added `filterMutationsByTranscriptId` function is the culprit. Seems like most of the transcripts are classified as non-canonical, and therefore filtered out. I am not sure at this moment if this is a bug or the desired behavior of this new functionality. We need to do a further analysis to see what's going wrong.

**Comment by stublakemore** [comment]
Hi @onursumer,

Ah I see. Thanks for taking a look. Hopefully (for me) it's not a new desired behaviour, since I need to make 2 more graphs to finish a figure for a paper I'd like to submit soon!

Many thanks,

Stuart

**Comment by stublakemore** [comment]
Hi @inodb ,

Thank you so much! That's done the job. It did take about 20 refresh attempts for it to work, but it worked and definitely included all the mutations. 

Thanks again for such a quick and helpful response to my problem.
