### ISSUE TITLE
Download tab (homepage) not working when selecting all studies

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#4808]
I get a NullPointerException:

![image](https://user-images.githubusercontent.com/2900303/45619386-5e421b80-ba79-11e8-80ad-15a155b4c2e3.png)

Steps to reproduce:
1. select all studies in Query tab. Wait for the case list to build up. 
2. select some of the genes (I selected "Glioblastoma: TP53 Pathway (4 genes)")
3. go to the "DOWNLOAD DATA" tab and click Download button

**Comment by jjgao** [comment]
`DOWNLOAD DATA` form only support one study. After going through the steps @pieterlukasse listed above, the `cancer_study_id` parameter is incorrect in the url.

![image](https://user-images.githubusercontent.com/840895/45634714-1f0fcc80-ba71-11e8-9916-c321064007cd.png)

**Comment by jjgao** [comment]
Actually, you don't have to select all studies, select 2 studies would do the trick.
