### ISSUE TITLE
Add HTML report output to generic validation script

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#481]
Add an option to let the generic validation script for staging files (#479) produce a HTML report at the end. For now the report should just contain the same messages as what is sent to stdout during validation, but this can be improved later with extra styling options such as collapsing the messages per file or file type.

**Comment by pieterlukasse** [comment]
This is the simple layout presented today by @fedde-s 

![image](https://cloud.githubusercontent.com/assets/2900303/11477963/aca87e28-978a-11e5-8257-634f82eeb08e.png)

Extra actions to work on:
[ ] Add color code legend
[ ] Send to @priti88 for testing [this branch](https://github.com/thehyve/cbioportal/tree/SimpleHtmlValidationReport) before the hackathon
[ ] Test current solution during hackathon
[ ] The Load part also needs to generate a similar HTML report. This can be logged as an extra requirement related to #528

**Comment by fedde-s** [comment]
I merged the prototype branch into [the main branch in which I was working](https://github.com/thehyve/cbioportal/tree/issue479_ImproveImportDataValidation) on issue #479 after positive feedback on the screenshot from the person who had requested the feature, at commit thehyve/cbioportal@e08bf05

**Comment by pieterlukasse** [comment]
Is done, but I will keep this issue open until we make the PR to rc

**Comment by fedde-s** [comment]
Moreover, the layout of the report was changed completely based on a template provided by @priti88  during the first hackathon. Messages are now grouped into separate tables for each file, which are only displayed after clicking on the colour-coded filename header.

**Comment by pieterlukasse** [comment]
closing it now to focus on remaining topics. Will refer to this in pr.
