### ISSUE TITLE
Text outside box when multiple panels in 1 patient

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4810]
'example_gene_panel_stable_id2' is rendered outside the text box. Perhaps it would be better to render this on a new line.

This patient contains 2 samples, each sequenced using a different gene panel.

<img width="501" alt="screen shot 2018-09-17 at 17 13 27" src="https://user-images.githubusercontent.com/9624990/45632203-0ae1c480-ba9d-11e8-964b-26958365635c.png">

**Comment by sandertan** [comment]
@adamabeshouse did you fix this in PR 1822?

**Comment by adamabeshouse** [comment]
@sandertan no, I just referenced it because someone else brought up the same issue.

**Comment by adamabeshouse** [comment]
oh okay, then I will unassign @Sjoerd-van-Hagen

**Comment by sandertan** [comment]
@adamabeshouse Ah ok, sorry for the confusion. I was assigning @Sjoerd-van-Hagen to track some issues, but indeed if he's not working on them, perhaps best to unassign.
