### ISSUE TITLE
enforce one mutation profile per study

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4811]
We assume there is only one mutation profile per study in many places, e.g. study view, patient view, mutation_count clinical data, but we don't enforce that. Should we start to put constraint so that only on mutation profile can exist for a study?

- [x] add a rule in validator
- [ ] add an sql trigger when adding a profile

@ersinciftci @sandertan @pieterlukasse @n1zea144 @sheridancbio @inodb

**Comment by sandertan** [comment]
Hi @jjgao , I think it is already enforced by the validator, because there's only one documented stable id for mutations (`mutations`).

```
DEBUG: meta_mutations_extended2.txt: Starting validation of meta file
INFO: meta_mutations_extended2.txt: Validation of meta file complete

DEBUG: meta_mutations_extended.txt: Starting validation of meta file
INFO: meta_mutations_extended.txt: Validation of meta file complete
ERROR: meta_mutations_extended.txt: stable_id repeated. It should be unique across all files in a study; value encountered: 'mutations'
```

**Comment by jjgao** [comment]
@sandertan great. Thanks!
