### ISSUE TITLE
DOWNLOAD DATA is not work in SPA

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4816]

**Comment by jjgao** [comment]
@alisman since we are getting rid of QueryBuilder/index.do, I think we should reimplement the DOWNLOAD DATA functionality. We will need to pull data based on the form from the API. Hopefully they are the same ones as QUERY form. We will also need to reformat the data for downloading.

**Comment by alisman** [comment]
@jjgao for time being, i made a new route that points to Query builder.  This works.  When you do want to do the project you describe?

**Comment by jjgao** [comment]
we'll remove querybuilder later: https://github.com/cBioPortal/cbioportal/issues/4837

**Comment by jjgao** [comment]
logged about removing QueryBuilding in https://github.com/cBioPortal/cbioportal/issues/5189
