### ISSUE TITLE
hide tabs based on data availability

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4822]
- [x] Hide `Mutual Exclusivity` when querying only one gene
- [ ] Hide `Co-expression` when there is no mRNA or protein data
- [ ] Hide `Survival` when there is no survival data
- [ ] Hide `CN Segments` when there is no segments data

**Comment by alisman** [comment]
@jjgao unless there's some flag or heuristic, I don't think we know whether there's expression data, survival data or segment data until we load it (lazily).  I.e. someone lands on oncoprint after query submission --> do we load survival data just to determine whether to show survival tab?    Let me know if there is some rule that don't mind baking into the site.

**Comment by alisman** [comment]
(I will do Mutex right now)

**Comment by jjgao** [comment]
@alisman I think we will need to call api to get whether the data exists. How it was done in the current portal?

**Comment by jjgao** [comment]
We will need to extend the study API to add more information. Materialized views (https://github.com/cBioPortal/cbioportal/issues/4794) might be useful here.
