### ISSUE TITLE
Cancer Types Summary: making menu more compact

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4823]
@schultzn commented that he almost always set a `Min. # Total Cases` when using the tab. But the functionality is hidden. You would have to click `Customize`. Let's redesign it after SPA.

- [x] always show the options
- [ ] Redesign the layout and make them more compact

![image](https://user-images.githubusercontent.com/840895/45643489-3490f080-ba89-11e8-872d-d401f8b1392d.png)

**Comment by jjgao** [comment]
@alisman thanks for the quick action on this. Can we also try to make the menu more compact

**Comment by adamabeshouse** [comment]
use table layout, move labels down
