### ISSUE TITLE
optimize loading time for mutated genes and CNA genes

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4826]
There have been a few tries, e.g. https://github.com/cBioPortal/cbioportal/issues/4803.  let's keep improving it.

![image](https://user-images.githubusercontent.com/840895/45645541-c2bba580-ba8e-11e8-87a5-ec8fe5311cb5.png)

**Comment by zhx828** [comment]
@ersinciftci are you still working on this ticket? If no, should we move it to 1.19.x?

**Comment by jjgao** [comment]
These two tables, esp CNA table, are still slow comparing to other charts. It'd be great if we can further improve them.

**Comment by zhx828** [comment]
@ersinciftci @jjgao i possible, could we do in 1.19.0? The current production is faster in msk_impact_2017

Current production: http://www.cbioportal.org/study?id=msk_impact_2017
mutations.json(loading 570 genes): 2.11s + gene panel:3s
cna.json(loading 784 gene-alteration): 2.27s + gene panel:3s

Beta study view: http://www.cbioportal.org/beta/study?id=msk_impact_2017
mutated-genes(loading 1168 genes): 11.73s
cna-genes(loading 784 gene-alteration): 20.54s

**Comment by ersinciftci** [comment]
@jjgao @zhx828 For genie http://www.cbioportal.org/genie-beta/study?id=genie_private they both take 3 seconds, and there are 1397 mutated genes and 1433 CNA genes for around 60.000 samples. So it feels like there might be something else going on, maybe some memory related problems with the beta server? or MySQL cache size or something?

**Comment by ersinciftci** [comment]
And I remember that for msk_impact_2017 on beta, before we did any performance improvements, cna-genes used to take around 13 seconds. So 20 seconds doesn't make any sense. And I found this conversation on slack from 2 months ago :)
```
Ersin Ciftci [2 months ago]
not sure why but cna-genes and mutated-genes works much faster on http://www.cbioportal.org/beta/ :slightly_smiling_face:

Hongxin Zhang [2 months ago]
haha yeah seems server has a pretty good mood today
```

**Comment by jjgao** [comment]
It might be b/c of caching that genie is loaded fast. (we use caching on private portals but not on public portal.)

It is strange that the current production is much faster than beta. We should improve it before release.

**Comment by jjgao** [comment]
@ersinciftci it wasn't turned off for genie-beta in the configuration. I think the cache is on. Is that right, @zhx828 @inodb?

**Comment by jjgao** [comment]
And for public portal production and beta, they are both not cached, but the performance of the two tables are different. So in any case, we should improve that.

**Comment by ersinciftci** [comment]
@jjgao I just checked what is done differently, as far as I can see the biggest difference is the old API caches all the samples and patients in the systems in a Map, so stable_id -> internal_id conversion doesn't happen in the SQL, they convert it before sending to DB, so the SQL is a bit simpler. So I will try that and see. 

And as for caching on `genie-beta`, we did most of the performance testing there, I hope the caching was not on :) But I still thing there is something weird going on with `beta` server, because I remember some days mutated and cna genes tables were really fast, and we were surprised because it wasn't a day that we changed something in those APIs, it was just random.

**Comment by jjgao** [comment]
@ersinciftci I remember that too, but maybe it was fast on `gene-beta`.

@n1zea144 and I would like to do a redis-based caching (not in memory). Once we have that, we can turn caching back on.

**Comment by jjgao** [comment]
@ersinciftci do you have an example sql?

**Comment by ersinciftci** [comment]
@jjgao They still have some mybatis syntax but basically:
The new API
```
SELECT
mutation.ENTREZ_GENE_ID AS entrezGeneId,
gene.HUGO_GENE_SYMBOL AS hugoGeneSymbol,
COUNT(*) AS totalCount,
COUNT(DISTINCT(mutation.SAMPLE_ID)) AS countByEntity
FROM mutation
INNER JOIN genetic_profile ON mutation.GENETIC_PROFILE_ID = genetic_profile.GENETIC_PROFILE_ID
INNER JOIN sample ON mutation.SAMPLE_ID = sample.INTERNAL_ID
INNER JOIN gene ON mutation.ENTREZ_GENE_ID = gene.ENTREZ_GENE_ID
WHERE

mutation.SAMPLE_ID IN (
SELECT sample.INTERNAL_ID from sample
INNER JOIN patient ON sample.PATIENT_ID = patient.INTERNAL_ID
INNER JOIN genetic_profile ON patient.CANCER_STUDY_ID = genetic_profile.CANCER_STUDY_ID
WHERE 
    genetic_profile.STABLE_ID = #{molecularProfileIds[0]} AND
    sample.STABLE_ID IN
    <foreach item="item" collection="sampleIds" open="(" separator="," close=")">
        #{item}
    </foreach>)

GROUP BY mutation.ENTREZ_GENE_ID
```
The old API
```
select
mutation.ENTREZ_GENE_ID as entrezGeneId,
GROUP_CONCAT(mutation.SAMPLE_ID) as concatenatedSampleIds,
count(*) as count,
count(*)/`LENGTH` as count_per_nt

from mutation, gene

where mutation.ENTREZ_GENE_ID = gene.ENTREZ_GENE_ID
and GENETIC_PROFILE_ID = #{geneticProfileId}

    and mutation.SAMPLE_ID in
    <foreach item="item" collection="sampleIds" open="(" separator="," close=")">
        #{item}
    </foreach>

group by mutation.ENTREZ_GENE_ID
having count(*) >= #{thresholdRecurrence}
order by count_per_nt desc
LIMIT 0, #{thresholdNumGenes}
```

**Comment by jjgao** [comment]
thanks @ersinciftci

**Comment by ersinciftci** [comment]
Fixed by https://github.com/cBioPortal/cbioportal/pull/5322
