### ISSUE TITLE
MDACC compendium heatmaps tab missing from Study page (since v1.10.0)

### ISSUE THREAD

**Issue by ChrisWakefield** [cBioPortal/cbioportal#4833]
Changes to dashboard.jsp introduced after v1.9.1 removed this feature.  I'd like to submit PR to add it back.  I notice the implementation style used within the jsp has completely changed, so hopefully it's not about to be redone yet again (?), but I do see many references to refactoring in the issues list.  Is now a good time?  (#1613)

**Comment by jjgao** [comment]
@ChrisWakefield sorry we accidentally dropped it. We will add it back in next release.

**Comment by ChrisWakefield** [comment]
@jjgao @zhx828 Thanks for your quick reply!  
I don't understand whether I need to do anything.  Do you want me to submit a pull request?  Or is your group changing & refactoring things on your end such that you must be the ones to do it?  (The old lines of code don't appear that they would work dropped into the new-style rewrite of that .jsp).

**Comment by zhx828** [comment]
@ChrisWakefield at this moment, we are very close to finishing the study view refactoring. I will implement the feature and tag you to review if you have time.

**Comment by ChrisWakefield** [comment]
@zhx828 I will make time, as I would like to review it and I'm happy to help out.  Thank you!

**Comment by zhx828** [comment]
@ChrisWakefield  could you review the above pr?

**Comment by ChrisWakefield** [comment]
@zhx828 Sorry, what PR ?  Is it deployed somewhere?  (I looked for something like "deployed to cbioportal-pr-#### on Jun 28".)

In the commit, I see you using the "/dyce?app=..." URLs, but what I had originally supplied (in the portal.properties.EXAMPLE file) was:
"//bioinformatics.mdanderson.org/participant2maps?participant=" and
"//bioinformatics.mdanderson.org/study2url?studyid=", wasn't it?
(Yes, they currently redirect to the URL that you used, but I'm working to get that corrected on our end to use the above webservice api.  It should stop doing the redirect within the next few days.)

Other than that, I don't see anything in the commit that concerns me, but I also can't see that it works.

**Comment by zhx828** [comment]
@ChrisWakefield ah, ok, I will change the URL. Thought it has been changed to the new `dyce` link while I was testing.

If you go to our rc portal(http://www.cbioportal.org/rc/) and set the following in your browser console `localStorage.heroku = 'cbioportal-frontend-pr-1471'`, it will take you to the PR.
Then you can access any studies with heatmap info, here is an example for Bladder Urothelial Carcinoma (TCGA, Nature 2014) http://www.cbioportal.org/rc/newstudy?id=blca_tcga_pub&tab=mdaccHeatmap

**Comment by ChrisWakefield** [comment]
@zhx828 @jjgao I suspect some here may like for it to be labeled "NG-CHM". 
Don't get me wrong - if you want to use the long name, that's ok too.

**Comment by jjgao** [comment]
I think it's better to use a common name for the tab, e.g. Heatmaps. It's clear that it is linked to NG-CHM once it's open. Would you be ok with that, @ChrisWakefield ?

**Comment by ChrisWakefield** [comment]
@jjgao @zhx828 I agree, "Heatmaps" will be fine, and that's what we decided before.

**Comment by zhx828** [comment]
@jjgao @ChrisWakefield thank you both.

**Comment by ChrisWakefield** [comment]
@zhx828 Was this already merged in?  Or is there a PR for it to be merged?

**Comment by zhx828** [comment]
@ChrisWakefield this has been merged to rc branch(https://github.com/cBioPortal/cbioportal-frontend/pull/1471)

**Comment by zhx828** [comment]
@ChrisWakefield is the http no longer supported? The browser will redirect http call to https, but if you curl the link `http://bioinformatics.mdanderson.org/study2url?studyid=brca_tcga_pub`, it no longer returns any info.

**Comment by ChrisWakefield** [comment]
@zhx828 http is now automatically redirected to https (at the router).  You'll see this if you add the -v option to curl.  Please also refer back to the Sep 28 message above (though that says it will send 301, and instead we see 302).  

curl -v http://bioinformatics.mdanderson.org/study2url?studyid=brca_tcga_pub
*   Trying 143.111.2.220...
* TCP_NODELAY set
* Connected to bioinformatics.mdanderson.org (143.111.2.220) port 80 (#0)
> GET /study2url?studyid=brca_tcga_pub HTTP/1.1
> Host: bioinformatics.mdanderson.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Found
< Location: https://bioinformatics.mdanderson.org/study2url?studyid=brca_tcga_pub
< Server: BigIP
* HTTP/1.0 connection set to keep alive!
< Connection: Keep-Alive
< Content-Length: 0
< 
* Curl_http_done: called premature == 0
* Connection #0 to host bioinformatics.mdanderson.org left intact

You need the -L option to make curl follow redirects.  I think this is what you expected to see:

curl -L http://bioinformatics.mdanderson.org/study2url?studyid=brca_tcga_pub
{"getRequestType":"withParameters","jobStatusText":"job completed","jobStatus":"completed","requestKey":"313386703","jobCompleted":true,"fileContent":"[\"view=0&p0DiseaseInput=brca\"]\n"}

**Comment by zhx828** [comment]
@ChrisWakefield awesome, we will just point all calls to https. Thanks for the information.

**Comment by ChrisWakefield** [comment]
@zhx828 Thank you!
I remember this seemed to work in the rc branch even with http (redirected in the browser).  Are you now changing the mechanism?

**Comment by zhx828** [comment]
@ChrisWakefield No sure what changed, but since http/https portal instances can access https service, it's find to update to that.
