### ISSUE TITLE
Making Mut vs GFA plots more like a density plot

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4835]
Discussion copied from slack.

Adam Abeshouse [3:45 PM]
Hi all, so I'm looking at adjusting the SV scatter plot to show density with opacity. The way I have it is that I set an opacity-per-sample, and dots that contain multiple samples just have the number multiplied by that opacity (maximum opacity is 1). I also thought it would make sense to change the opacity-per-sample depending on how many points are in the plot, so the formula I'm using for that is f(n) = 1/n^a, where a is set so that f(10000) = 0.1 (opacity per sample is 0.1 with 10000 points) (edited)
hongxin asked me to give screenshots with and without each of opacity and size. here they are:
msk_impact_2017: opacity and size modulation
![image](https://user-images.githubusercontent.com/840895/45727008-db5fb480-bb8f-11e8-952a-ae58ba9db839.png)

acc_tcga: opacity and size modulation
![image](https://user-images.githubusercontent.com/840895/45727025-e3b7ef80-bb8f-11e8-97b7-6625625a76e0.png)

msk_impact_2017: only size modulation
![image](https://user-images.githubusercontent.com/840895/45727034-eca8c100-bb8f-11e8-969a-79382a0da08f.png)

acc_tcga: only size modulation
![image](https://user-images.githubusercontent.com/840895/45727044-f3cfcf00-bb8f-11e8-9934-f428a2fa58ef.png)

msk_impact_2017: only opacity modulation
![image](https://user-images.githubusercontent.com/840895/45727050-fb8f7380-bb8f-11e8-94c9-4dbb4a7f8610.png)

acc_tcga: only opacity modulation
![image](https://user-images.githubusercontent.com/840895/45727057-021deb00-bb90-11e8-8753-cf8a6d561358.png)

msk_impact_2017: neither
![image](https://user-images.githubusercontent.com/840895/45727064-0b0ebc80-bb90-11e8-9645-53fa94e14974.png)

acc_tcga: neither
![image](https://user-images.githubusercontent.com/840895/45727071-1530bb00-bb90-11e8-9744-620e68f9c615.png)

Adam Abeshouse [4:07 PM]
personally I think only opacity modulation looks best

JJ Gao [10:05 PM]
Thanks, @adam! I like opacity modulation too.
I am wondering if we can differentiate more for the dense area in order to make it reflect the density.
![image](https://user-images.githubusercontent.com/840895/45727083-24176d80-bb90-11e8-99ca-a90dc94a6c49.png)

**Comment by adamabeshouse** [comment]
@jjgao I forgot to show in screenshots, but the plot can also have multiple colors differentiating different groups. So we couldnt have a global color scheme that way

**Comment by schultzn** [comment]
I vote for an approach that does not use any pale colors but instead shows the density, as shown in the example by JJ above.

**Comment by jjgao** [comment]
@adamabeshouse let's try not to use opancity or size, and try to use the colors similar to this.

![image](https://user-images.githubusercontent.com/840895/45727083-24176d80-bb90-11e8-99ca-a90dc94a6c49.png)

**Comment by zhx828** [comment]
@jjgao @schultzn the density is only applied when there is no selection to the study? Otherwise, we will have different colors for selected/unselected groups.

**Comment by jjgao** [comment]
@zhx828 let's not sure any unselected samples in this plot.

**Comment by schultzn** [comment]
I think what JJ tried to say is: In this plot, always only show selected samples (or all samples, when no selection has been made yet). In other words, do not show the non-selected samples anymore.

**Comment by adamabeshouse** [comment]
@schultzn @jjgao two things:

1) Does that mean we no longer want this plot to be interactive? Right now you can drag to select a rectangle of points to set the selection.

2) What about the functionality of showing the groups, in different colors? Eg the one above from impact was generated by the smoking clinical attribute.

**Comment by jjgao** [comment]
@adamabeshouse 

1. It'll still be interactive, ie. you can still select points, but only points that have been selected (or all).

2. We will show the groups/colors for the selected samples.

3. Good point. I am wondering if we should try to make non-overlapping points? Or even go further to do a density plot?

**Comment by adamabeshouse** [comment]
After talking in standup, we decided to try a plot that forgoes the group coloring feature, and just focus on density plot for the selected samples.

**Comment by adamabeshouse** [comment]
@jjgao @schultzn 
I dont think this is what we want

![image](https://user-images.githubusercontent.com/636232/45904710-d1ba9480-bdbb-11e8-84b2-774b048e2d7b.png)

![image](https://user-images.githubusercontent.com/636232/45904741-e6972800-bdbb-11e8-90e3-430208fa6ee4.png)


I'm going to try hashing the samples into a grid, and then color the dots by the count in their grid rectangle, which will give a more intuitive sense of the overall plot density.

**Comment by adamabeshouse** [comment]
here it is with darkened background color for visibility
![image](https://user-images.githubusercontent.com/636232/45904829-34139500-bdbc-11e8-9c0e-a6d72d4104b3.png)

![image](https://user-images.githubusercontent.com/636232/45904847-44c40b00-bdbc-11e8-812c-e7faf0efa8db.png)

**Comment by adamabeshouse** [comment]
I think this *looks* much better, but it could be confusing because some of the dots that are colored very high end up actually only having one sample, just because they're in a high density area. What do you think?

I'm computing counts based on a grid where each axis is divided up into 100 bins.

![image](https://user-images.githubusercontent.com/636232/45905368-1fd09780-bdbe-11e8-8bd4-ecefcedc5969.png)

![image](https://user-images.githubusercontent.com/636232/45905375-27903c00-bdbe-11e8-8c83-1828d217e9c4.png)

**Comment by zhx828** [comment]
The proposal of the density plot has almost been finalized. Here are some discussions about the legend of the plot.
In the initial thought, Adam suggested to list the threshold which used to determine the color:
![image 1](https://user-images.githubusercontent.com/5400599/46619437-1b131f80-caf0-11e8-846d-142d7a73bcce.png)
Then later JJ suggested to put in as a continuous legend, then we have:
![image 2](https://user-images.githubusercontent.com/5400599/46619513-43028300-caf0-11e8-8c7b-85ff44f42b53.png)
![image 3](https://user-images.githubusercontent.com/5400599/46619547-557cbc80-caf0-11e8-89a7-28e99980ae89.png)
![image 4](https://user-images.githubusercontent.com/5400599/46619551-5877ad00-caf0-11e8-94ea-f6ca55c50255.png)
![image 5](https://user-images.githubusercontent.com/5400599/46619556-5b729d80-caf0-11e8-85b7-3f60c363a826.png)

**Comment by adamabeshouse** [comment]
@zhx828 Im working on an actual gradient component but having some trouble with Victory

**Comment by zhx828** [comment]
The feature has been supported in new study view.  http://www.cbioportal.org/beta/newstudy?id=msk_impact_2017
Added in https://github.com/cBioPortal/cbioportal-frontend/pull/1505

**Comment by schultzn** [comment]
Nice!

When there is only a single case (count = 1), can you remove the ~ sign, since we know the exact value in those cases?

Niki.
