### ISSUE TITLE
Plots tab: using stacked bar chart for discrete vs discrete

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4844]
Currently, we display a table for discrete vs discrete. It's not very easy to digest especially when there are many categories. Let's support stacked bar chart (similar to Cancer Type Summary) and display that as a default. The current table can be an option that user can switch to.

**Comment by adamabeshouse** [comment]
@jjgao you mean any discrete data, not just discrete CNA right?

**Comment by jjgao** [comment]
@adamabeshouse yes.

**Comment by adamabeshouse** [comment]
@jjgao any preference whether the stacked bar is for the y axis or the x axis? or should that be a user setting? my instinct is y-axis (i.e. vertical bars)

**Comment by jjgao** [comment]
@adamabeshouse let's do vertical bars. The user already has the option to swap attributes -- that's probably enough.

**Comment by adamabeshouse** [comment]
in `master`
