### ISSUE TITLE
Cohort column for UNCALLED mutations on patient view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4848]
This should always show the keyword counts from the `_mutations` profile, never the one from `_mutations_uncalled`. I think right now it might be using the first mutation passed to the cell

- [ ] fix frontend code to show always `_mutations` profile's mutation count by keyword, instead of the one from `_mutations_uncalled` profile
- [ ] remove `_mutations_uncalled` profiles from `mutation_count_by_keywords` table. It's possible that the backend code breaks when there's no such count available (the mutations model returned by the api includes it for each mutation).

**Comment by jjgao** [comment]
We might want to remove `_mutations_uncalled` in the `mutatio_count_by_keywords` table.
