### ISSUE TITLE
Don't offer bookmark if we don't have session service or bitly

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4862]

**Comment by fedde-s** [comment]
While at it, consider reviewing [the config docs](https://github.com/cBioPortal/cbioportal/blob/v1.17.0/docs/portal.properties-Reference.md) and maybe [the example config file](https://github.com/cBioPortal/cbioportal/blob/v1.17.0/src/main/resources/portal.properties.EXAMPLE) to see whether they're clear on what a deployer should do if they don't want to enable these services.

**Comment by alisman** [comment]
@jjgao turns out the bitly documentation differs from the portal.props example file.   In docs it's "bitly.api.key" wherease in example file it's "bitly.access.token"  
I can support both if necessary

**Comment by jjgao** [comment]
hmm... is api key different from access token?

**Comment by fedde-s** [comment]
For reference: from what I can find, the bookmark tab has been replaced by [sharing widgets](https://github.com/cBioPortal/cbioportal/issues/3000) in the top-right corner of the results page for 1.18, even if there are no references to the pull request in which those were built and reviewed. I presume that hiding them when not available was taken into account when building them.
