### ISSUE TITLE
cancer type summary: improve plot when all data is filtered out

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4873]
If I filter by number/percent of cases while looking at data in one way (e.g. by cancer type) and then switch to another (e.g. cancer type detailed) where no bar fits the filter criteria, then I get this sad looking tiny box:

![image](https://user-images.githubusercontent.com/10508276/46023696-278c8680-c0b3-11e8-95e8-065a3c45a564.png)
http://www.cbioportal.org/index.do?session_id=5a1eef06498eb8b3d560f502&show_samples=false&

Let's show an actual empty plot in this scenario.

**Comment by alisman** [comment]
@dippindots instead of chart, lets show an alert with message, "There is no data". 
 
You should use Boostrap 3's alert markup.  Let me know if you have questions
