### ISSUE TITLE
spa: long gene lists appear on two lines the second time a tab is viewed

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4875]
The first time I click on a tab, the genes appear on one row with an arrow to view the rest:
![image](https://user-images.githubusercontent.com/10508276/46024761-76d3b680-c0b5-11e8-91d8-1d1b12475a59.png)

If I click to another tab and click back, then the genes appear on two rows:
![image](https://user-images.githubusercontent.com/10508276/46024786-805d1e80-c0b5-11e8-81c8-71686af7cd52.png)

This seems to happen reliably on other tabs that list out genes like this also (mutations, expression)

http://www.cbioportal.org/alpha/results/cancerTypesSummaryTab?session_id=5baa5038498eb8b3d5680727

**Comment by onursumer** [comment]
@alisman currently, I can only reproduce this on the `expression` tab (on beta portal), other tabs seems fine to me.

**Comment by onursumer** [comment]
Seems like the problem stems from page recalculation on a window resize event. For some tabs, resize event is triggered when switched back and forth from a tab, and paging calculation cannot be performed properly for some reason.

Disabling recalculation on resize events fixes the problem, but it also makes the tabs paging unresponsive to the window resize events (which I think we can tolerate at this point).
