### ISSUE TITLE
Select genes for query in the study page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#488]
It should be possible to select genes from the CNA and mutation tables in the study view and add these genes to the query, together with the selected samples.

**Comment by pieterlukasse** [comment]
Screenshot of solution now on TEST server:

![image](https://cloud.githubusercontent.com/assets/2900303/11207106/729aafca-8d13-11e5-9934-bb354aa744be.png)

**Comment by ecerami** [comment]
I think this is looking great.  @schultzn @jjgao @zhx828:  any final thoughts?  Please post to the issue directly.  thanks.

**Comment by schultzn** [comment]
Agreed, it looks great and everything seems to be working fine!

**Comment by zhx828** [comment]
I tested couple times too. It works great.

**Comment by pieterlukasse** [comment]
:+1:
