### ISSUE TITLE
issues with MUT vs FGA plot

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4881]
Empty plot in [msk_impact_2017](http://www.cbioportal.org/study?id=msk_impact_2017)

y-axis mutation number too high for acc_tcga_pan_can_atlas_2018

http://www.cbioportal.org/study?id=acc_tcga_pan_can_atlas_2018

![image](https://user-images.githubusercontent.com/840895/46156894-8a635680-c248-11e8-9064-3d82ead00b6f.png)

**Comment by jjgao** [comment]
I am reopening it. I think we should do a db migration to migrate them to `number`s. @ersinciftci could you help with that? Could you also change the import script to set them as number attributes?

**Comment by ersinciftci** [comment]
@jjgao I don't think we can migrate them to numbers, as they are in `clinical_sample` table now and the `ATTR_VALUE` can't be number as some of other clinical data are string values.

**Comment by jjgao** [comment]
Sorry I wasn't clear. I was talking about the meta for clinical attribute. I thought STRING was used, but it looks like NUMBER was used. Closing this.
