### ISSUE TITLE
create tests for MUTATION_UNCALLED

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4882]
This is only used internally, but we ran into two bugs after releasing:

- MUTATION_UNCALLED weren't being import as MUTATION data but CNA/RPPA instead
- The endpoint for fetching mutations did not return any uncalled mutations, because it wasn't considered a valid mutation profile

**Comment by jjgao** [comment]
@inodb I missed this one. I think we should fix this soon.

**Comment by jjgao** [comment]
@inodb is this still an issue?

**Comment by jjgao** [comment]
@inodb do we need to keep this open?

**Comment by adamabeshouse** [comment]
can we discuss this more? I don't really know what to do

**Comment by adamabeshouse** [comment]
can we close? @alisman @inodb @jjgao
