### ISSUE TITLE
mutation mapper tool not working in SPA

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4904]
- [x] The tools page looks different (missing images for mutation mapper and oncoprint). Harder to find them
- [x] The mutation mapper isn't working: http://www.cbioportal.org/beta/s/mutation_mapper.jsp
- [ ] We might want to support the old URLs e.g. forward http://www.cbioportal.org/tools.jsp -> http://www.cbioportal.org/beta/s/visualize

**Comment by onursumer** [comment]
@alisman @inodb http://www.cbioportal.org/beta/s/mutation_mapper.jsp doesn't work but http://www.cbioportal.org/beta/mutation_mapper does. 

A quick fix is to update the broken link in the http://www.cbioportal.org/beta/s/visualize page. I guess then we can safely retire `mutation_mapper.jsp`

**Comment by onursumer** [comment]
@inodb @alisman seems like the tools page under SPA is using an older version, not the latest `visualize.jsp`. Updating `Visualize.tsx` with the latest `visualize.jsp` should fix this problem.

**Comment by onursumer** [comment]
@inodb @alisman @adamabeshouse I guess we still need to refer to `oncoprinter.jsp` since we don't have the `tsx` version of the standalone `Oncoprinter`, right?

**Comment by adamabeshouse** [comment]
@onursumer yeah I never finished the oncoprinter
