### ISSUE TITLE
mutation mapper getMutationAligner.json optimization

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4909]
getMutationAlginer.json is called every time when switching transcript in the new mutation mapper tool dropdown. We could save that result

**Comment by jjgao** [comment]
@inodb are we call getMutationAlginer.json when hovering the domain or when the page the open? We should do the former if possible.

**Comment by jjgao** [comment]
Let's delay the data load until hovering on the domain and potentially save it so that we don't have to fetch again after switching transcripts.
