### ISSUE TITLE
Should we show uncalled mutations for a single sample?

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4910]
Right now we only show uncalled mutations on the patient view. It is a little confusing tho that when looking at a single sample, those mutations don't show up

Raised by @ritikakundra

**Comment by jjgao** [comment]
@inodb I don't think we should show a mutation unless there is a called mutation in at least one sample. Otherwise, it'd be confusing too.

**Comment by inodb** [comment]
right - so only show those uncalled mutations that are in at least one sample of the same patient?

**Comment by jjgao** [comment]
yes, and I think that sample (with the called mutation) should be shown on the page...

**Comment by jjgao** [comment]
I think the current implementation is ok.
