### ISSUE TITLE
incorrect sample collection days

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#4911]
for samples from [SKCM](http://www.cbioportal.org/study?id=skcm_tcga#clinical) and [PAAD](http://www.cbioportal.org/study?id=paad_tcga#clinical), "days to sample collection" annotations are incorrect, since days are larger than the overall survival of the patient.

> I am using TCGA data (SKCM and PAAD) for publications. I just have a really important question about the overall surivival. For SKCM and PAAD tumors the "days to sample collection" column makes not much sense to me because the values are larger than the overall survival of the patient.
For SKCM I substracted "Submitted.tumor.dx.days.to" from the overall survival in an attempt to correct for the days to sample collection. This parameter does not exist for PAAD unfortunately. Is this correct? Or is there no need to do this correction?

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #382](https://github.com/cBioPortal/datahub/issues/382) via [**ZenHub**](https://www.zenhub.com/)
