### ISSUE TITLE
Spring contexts and GlobalProperties use separate logic to read portal.properties

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#4916]
The logic on which configuration files override which for the  is duplicated between at least three files: `GlobalProperties.java` (used for most customisation, and since PR #4787 also database credentials), `applicationContext-business.xml` (used for a few of the integrations with other web services and some details of caching and database integration) and `applicationContext-security.xml` (used for auth config). The logic isn't identical between the three, and this has already bitten me in #4905.

Apart from the bug referenced above, I believe that the Spring config in the `applicationContext-*.xml` files refer to the compiled-in file copied from `portal.properties.EXAMPLE` whenever a property is not specified in the runtime `$PORTAL_HOME/portal.properties`, whereas non-Spring configuration in `GlobalProperties.java` only refers to the baked-in file if no runtime file was supplied. This is difficult to document and maintain.

**Comment by jjgao** [comment]
@fedde-s @alisman : Maybe we should list and review the different configuration files and how they are being used?

**Comment by fedde-s** [comment]
@alisman: the issue I reported was about a need to refactor to avoid growing some technical debt across modules of the backend, written in Java and in Spring XML. Could you explain how that's now about the frontend? Or was that a misclick?

**Comment by fedde-s** [comment]
@jjgao: I think that ensuring that the various configuration files are clearly documented is better handled as a separate issue; more closely related to #4774. I reported this issue here just to keep track of some technical debt in how the logic to locate `portal.properties` is implemented.

**Comment by alisman** [comment]
I don't think this ticket is frontend related.   We do of course use portal.properties for frontend configuration properties but it doesn't sound like that's what's at issue.
