### ISSUE TITLE
cBioPortal breaks for multi/virtual study query if the studies are missing case_list_category=all_cases_in_study

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#4919]
If the case_list_category=all_cases_in_study is required for multi-study query or virtual study query then we need to: 
1) update the documentation (https://cbioportal.readthedocs.io/en/latest/File-Formats.html#case-lists).
2) fix the importer when "add_global_case_list" attribute in Study metadata is used. Currently, the importer sets case_list_category as "Other".

This error can be replicated by importing test study (study_es_0) twice with different cancer study identifier.

**Comment by jjgao** [comment]
@priti88 this was logged here: https://github.com/cBioPortal/cbioportal/issues/4502. I think @kalletlak has fixed the issue. Are you using the latest code?

**Comment by priti88** [comment]
@jjgao yes we used the latest code.

**Comment by jjgao** [comment]
@kalletlak are we still using `case_list_category` in query page?

**Comment by kalletlak** [comment]
@jjgao not in the front-end. Just figured out that we are still using it in the banck-end. I'll fix and send a pr

**Comment by jjgao** [comment]
@kalletlak thanks! Can we not hide it in the API too? cc'ing @ersinciftci

**Comment by kalletlak** [comment]
@jjgao `case_list_category` would be useful to identify other categories i.e. whether `sequenced` or `cna`

**Comment by ersinciftci** [comment]
@jjgao it's not hidden

**Comment by ersinciftci** [comment]
@jjgao did you mean `Can we hide it in API too`?

**Comment by jjgao** [comment]
@ersinciftci sorry I mean hide it in API.
