### ISSUE TITLE
lcll_broad_2013 is missing mutation count

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4923]
Mutation count is NA for all samples
![image](https://user-images.githubusercontent.com/10508276/46434805-b1c39300-c722-11e8-9c53-0fd4344ca43b.png)

http://www.cbioportal.org/study?id=lcll_broad_2013#summary

**Comment by jjgao** [comment]
@inodb @ersinciftci Mutation_count is still haunting us. ergh.

It looks like that 16 new studies with mutation data have no Mutation_Count data in `clinical_sample` table (although Mutation_Count attributes were created in `clinical_attribute_meta` table).

Could you look into that?

CANCER_STUDY_ID | CANCER_STUDY_IDENTIFIER
-- | --
1351 | ampca_bcm_2016
1352 | cellline_nci60
1353 | dlbc_tcga_pan_can_atlas_2018
1354 | mixed_pipseq_2017
1355 | mrt_bcgsc_2016
1356 | mixed_allen_2018
1357 | dlbcl_duke_2017
1358 | bfn_duke_nus_2015
1359 | uccc_nih_2017
1360 | mm_broad
1361 | ctcl_columbia_2015
1362 | all_stjude_2013
1363 | lcll_broad_2013
1364 | dlbc_broad_2012
1365 | breast_msk_2018
1368 | angs_project_painter_2018

Query:
```sql
select *
from cancer_study cs
join genetic_profile gp on gp.cancer_study_id=cs.cancer_study_id and gp.genetic_alteration_type="MUTATION_EXTENDED"
where cs.cancer_study_id not in (
 select p.cancer_study_id
 from clinical_sample cls, sample s, patient p
 where cls.attr_id="MUTATION_COUNT" and cls.internal_id=s.internal_id and s.patient_id=p.internal_id
);
```

**Comment by inodb** [comment]
@jjgao:	@sheridancbio is actually running the migration right now. It is fixed on my local after running: https://github.com/cBioPortal/cbioportal/pull/4907

**Comment by inodb** [comment]
we might have to reimport those studies

**Comment by jjgao** [comment]
@inodb thanks. Please run the sql above and close this issue once all fixed.
