### ISSUE TITLE
make style consistent for "no data" messages

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4924]
![image](https://user-images.githubusercontent.com/10508276/46435034-5e9e1000-c723-11e8-8e70-077acd978c89.png)

![image](https://user-images.githubusercontent.com/10508276/46435036-62ca2d80-c723-11e8-921a-281513b15d33.png)

![image](https://user-images.githubusercontent.com/10508276/46435057-6e1d5900-c723-11e8-9580-79164a5e9be3.png)

Survival on beta has an error but looks like this on production:
![image](https://user-images.githubusercontent.com/10508276/46435110-8beabe00-c723-11e8-9c49-df09013347b9.png)

Let's have consistent text size and consistently use or not use the blue box and for CN Segments how about a message that there is no CN data rather than loading an empty IGV?

**Comment by jjgao** [comment]
I still think we should not display all tabs and just to let users to that there is no data when they open them. Maybe we should have an API to let frontend know if data exists? cc'ing @ersinciftci
