### ISSUE TITLE
study view: colors for "sex" chart aren't the same as other pie charts

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4927]
Is there a reason we're using different shades of red and blue for "sex" than for all other pie charts? Can we use the same colors?

![image](https://user-images.githubusercontent.com/10508276/46435572-a5403a00-c724-11e8-955c-fd17fbd60000.png)

**Comment by zhx828** [comment]
@tmazor this is a feature to color reserved clinical value, in this case, female and male. We haven't decided on the color yet, just temporarily leave as dark blue and dark red.

**Comment by jjgao** [comment]
@cBioPortal/product what colors should we use for sex?

**Comment by tmazor** [comment]
I'm fine with using the same red/blue colors that are used in all the other charts. There are already a lot of colors on this page and I don't think this requires new ones.

That said - I'm very excited we have assigned colors for certain values! That's a great new feature!

**Comment by zhx828** [comment]
Sure thing.
