### ISSUE TITLE
add chart doesn't work for lgg_ucsf_2014

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4929]
Clicking on "Add Chart" does nothing. It is possible that the study loads with all charts visible, but even if I close some charts, the "Add Chart" still does nothing.

http://www.cbioportal.org/beta/newstudy?id=lgg_ucsf_2014

**Comment by kalletlak** [comment]
Seems like an api issue `/api/sample-counts/fetch`. @ersinciftci could you take a look at it

**Comment by ersinciftci** [comment]
https://github.com/cBioPortal/cbioportal/pull/4942 should fix the API to solve https://github.com/cBioPortal/cbioportal/issues/4931, but not sure why Add Chart is related to this API

**Comment by ersinciftci** [comment]
@kalletlak but this API is about how many samples are mutation and CNA profiled, wouldn't it make more sense to use the result of the `/filtered-samples` API for the percentage purpose?

**Comment by jjgao** [comment]
@kalletlak but the "Adding clinical track" dropdown in OncoPrint works fine for the same study. Are we using the same component?

**Comment by kalletlak** [comment]
@ersinciftci its required for this.
![screen shot 2018-10-05 at 2 56 51 pm](https://user-images.githubusercontent.com/12956870/46554640-ed8b6380-c8ae-11e8-8137-de323fc19f40.png)

filtered-samples count woudn't be same as samples with mutation and/or CNA data

**Comment by jjgao** [comment]
@ersinciftci looks like it's sql issue...

![image](https://user-images.githubusercontent.com/840895/46555649-fb8eb380-c8b1-11e8-9231-9aba125e11ec.png)
