### ISSUE TITLE
Add volcano plot to Enrichments tab

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#493]
Add a volcano plot next to the Mutations table in the Enrichments>Mutations tab. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/2900303/11207716/18b18a66-8d17-11e5-9f52-7a8173037a88.png)

**Comment by pieterlukasse** [comment]
The solution is available on the [TEST](http://cbioportal-test.thehyve.net/cbioportal) server

**Comment by pieterlukasse** [comment]
@schultzn made some comments:  To make the plot a little clearer, can you please do a couple of different things:

1 - Indicate on the x-axis, which range indicates mutually exclusive alterations (left, negative log ratios), and which indicates co-occurrence (right, positive values).
2 - Add an additional label to the y-axes: Significance
3 - Show the gene symbols and maybe even percentages in each group upon mouse-over on the points in the graph
4 - Add a label to the graph

**Comment by pieterlukasse** [comment]
@schultzn : Here are my replies + some questions:
1- Ok, I've made a sketch for this in the [google drawing](https://docs.google.com/drawings/d/1Y0i45yRv1b8A9pNqjdKHgzXejBwHl_99p4RXuXnzP8M/edit?usp=sharing)
Please check this. Feel free to make changes in this drawing document. 
2- This one I also added to the drawing. Please let me know if this is what you want. 
3- Ok, I will add the gene symbols and the percentages in each group. 
4- I guess with this you mean a title for the plot? Any suggestions for a good title? I can think of long titles only. Something like: "p-value vs alteration ratio for genes in altered and unaltered groups".

**Comment by pieterlukasse** [comment]
@schultzn , @ecerami : Furthermore, I have added an extra Euler diagram below the scatterplot to help the user interpret the values he sees for a specific gene. This appears when a user selects one of the genes in the table. See example in screenshot below (not yet on TEST server). With this, the user quickly gets an idea of the group sizes and how much variation the selected gene shows in both groups. 

Please let me know your comments on this extra diagram. Will this be helpful? Now it is just a prototype, but if you think this extra diagram is useful, I can add it to the upcoming PR as well. 

![image](https://cloud.githubusercontent.com/assets/2900303/11207862/1035da8a-8d18-11e5-9a2e-d961b1df1d06.png)

**Comment by ecerami** [comment]
I like @schultzn suggestions above, especially the axis labeling suggestions.  

Still thinking about the Euler diagram...

**Comment by ecerami** [comment]
Here's another idea...  Our most common visualization technique for visualizing co-occurrence v. mutual exclusivity is OncoPrints.  So, perhaps when a user clicks on a node in the volcano plot or a gene in the table, they get a very condensed, slightly modified Oncoprint.

In this case, Line 1 of the Oncoprint would either list:  1) single gene, if the user only entered in one gene or 2)  "Query Gene";  Line 2 would show the target gene, e.g. ACACA in the above.

To make the functionality of enrichments more obvious, we could also auto-select the top ranked gene, and display the condensed OncoPrint.

@pieterlukasse @schultzn @jjgao:  what do you think?

**Comment by pieterlukasse** [comment]
@ecerami so we show the oncoprint plot again here, now with the extra gene selected? This is already covered by "Add checked genes to query" button on top of the table. Or do you mean adding only 1 lane to represent all query genes in a condensed form? Can you maybe add a sketch of your proposal?

**Comment by ecerami** [comment]
yes, the idea is to embed a mini-oncoprint rather than a venn diagram, since OncoPrints are the primary "meme" we use for visualizing co-occurrence and mutual exclusivity.

Something like this:  (data is made up)

![screenshot_374](https://cloud.githubusercontent.com/assets/1009066/11226461/16fa3ee8-8d4e-11e5-8008-641b56641616.png)

would rather get feedback from @jjgao @schultzn and if @pieterlukasse thinks this is a lot of work, probably not worth it.

**Comment by jjgao** [comment]
@ecerami: it's a very cool idea, but I also think it's a lot of work to do it right, e.g. query genes merged into one track, "right" zoom out level when there are a lot of samples, etc. Maybe we should stage it?

**Comment by schultzn** [comment]
I agree that this would be much better than the Euler diagram (which I don’t understand at first glance), but it is probably a lot of work. So I agree with JJ that we should maybe add this later?

N

**Comment by pieterlukasse** [comment]
@ecerami @jjgao @schultzn : we can do a compact version of the oncoprint that does not include separate boxes for each of the samples. See screenshot below. This should be easy to do as it is just representing the same information as the Euler plot, but in a oncoprint format. 

![untitled drawing](https://cloud.githubusercontent.com/assets/2900303/11241035/9ce29164-8df7-11e5-9f57-8d92788ee2be.png)

**Comment by ecerami** [comment]
I second @pieterlukasse suggestion.  This is easier than my original suggestion, but keeps with the visual of Oncoprints that users are used to.

**Comment by adamabeshouse** [comment]
That should be relatively easy to implement with the new oncoprint.

**Comment by schultzn** [comment]
I like it too!

**Comment by jjgao** [comment]
Sounds good. @pieterlukasse can we try to reuse oncoprint.js code as @adamabeshouse suggested? It may be a good opportunity to further modularize the oncoprint code.

**Comment by ecerami** [comment]
@pieterlukasse's suggestion is actually much simpler than the regular oncoprints, e.g. it's just two rectangles;  no discrete mouse-overs, etc.  So, may be overkill to use oncoprint.js.  just my two cents.

**Comment by adamabeshouse** [comment]
It may be easier than you think to use oncoprint.js - I think it would be overkill to write new code instead of using it. I'd be happy to help with this. You basically just point the code at a container and add rules - should be only a few lines.

**Comment by pieterlukasse** [comment]
The advantage of this solution is that it is just a few rectangles, independent of the number of samples. The code will be very limited in this case as well. It will require only a few parameters: the total number of A=all samples, the % of  B=samples where queried genes are altered, the % of samples where clicked gene is altered in B (this comes from enrichment table), the % of samples where clicked gene is altered in A-B (this also comes from enrichment table). 

The rectangles are: 2 grey rectangles and 3 red rectangles, as shown in figure below


![untitled drawing](https://cloud.githubusercontent.com/assets/2900303/11266131/7d433646-8ea2-11e5-9bcc-351fca6f6b45.png)

**Comment by schultzn** [comment]
I like the simple rectangle solution - that way there also won't be any issues with scaling, such as oncoprints that are too large because there are too many samples.

**Comment by adamabeshouse** [comment]
That's true, good point, it would be a bit more complicated/potentially slow with oncoprint.js

**Comment by aderidder** [comment]
Here's a screenshot of the scatterplot with the axis and labels:
![image](https://cloud.githubusercontent.com/assets/9414840/11810587/7e550900-a32f-11e5-8729-a62813293a62.png)

Interested in hearing your thoughts

**Comment by schultzn** [comment]
Looks great. To be consistent with the rest of the site, can you change “exclusion” to “exclusivity”?

Niki.

**Comment by aderidder** [comment]
Hi everyone,

We had some major performance issues when dragging to select points with the scatterplot. We tried to fix these, but in the end we created a new version which uses plotly. It currently looks like this: 

![image](https://cloud.githubusercontent.com/assets/9414840/11992326/beeb2fe8-aa24-11e5-84d7-1d51a8edac0e.png)

The performance is way better and it when you drag-select the points, the plot also zooms in, which is a nice plotly feature I think. What do you think of this screenshot? 

Thanks,
Sander

**Comment by schultzn** [comment]
Looks good Sander!

Can you add an “r” to co-occurrence though?

Thanks.

Niki.

**Comment by aderidder** [comment]
Hi Niki,

Yes, no problem.

Sander

**Comment by pieterlukasse** [comment]
merged via #753
