### ISSUE TITLE
check box in study view table has moved

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4930]
Is this on purpose? The check box used to be attached to the frequency column but is now in the "#" column:

![image](https://user-images.githubusercontent.com/10508276/46436248-66ab7f00-c726-11e8-9ba9-987cef75b0b4.png)

![image](https://user-images.githubusercontent.com/10508276/46436253-6ad79c80-c726-11e8-844c-d7ee0ec5b2c1.png)

**Comment by zhx828** [comment]
@tmazor  it's actually always in the # column, just in the previous implementation, the checkbox is right align, looks like in the Freq column.

**Comment by jjgao** [comment]
I think it's clear in the new way that it's for selecting samples. Closing this. @tmazor please reopen if you think otherwise.
