### ISSUE TITLE
mutated genes table doesn't always show sample number

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4931]
lgg_ucsf_2014 in new study view is missing sample number:
![image](https://user-images.githubusercontent.com/10508276/46436449-d3bf1480-c726-11e8-9b18-e8b389346713.png)

msk_impact_2017 new study view has sample numbers
![image](https://user-images.githubusercontent.com/10508276/46436470-db7eb900-c726-11e8-8b22-626740ac0e15.png)

ucsf_lgg_2014 old study view has sample numbers
![image](https://user-images.githubusercontent.com/10508276/46436481-e33e5d80-c726-11e8-8c35-ed4ea481edbc.png)

**Comment by zhx828** [comment]
@ersinciftci could you take a look this ticket? In study http://www.cbioportal.org/beta/newstudy?id=lgg_ucsf_2014, sample-counts endpoint is giving 500.
