### ISSUE TITLE
Remove category from Sample List API

### ISSUE THREAD

**Issue by ersinciftci** [cBioPortal/cbioportal#4933]
As requested in https://github.com/cBioPortal/cbioportal/issues/4919

![image](https://user-images.githubusercontent.com/840895/67502537-ff73ac00-f653-11e9-8c8c-d42a2fae6602.png)

**Comment by jjgao** [comment]
We should still do it.

**Comment by inodb** [comment]
gonna focus on docs first for public release of API, so removing the sprint milestone for now

**Comment by jagnathan** [comment]
this issue also involves db changes. 
table `sample_list`  has column `CATEGORY` varchar(255) NOT NULL

**Comment by inodb** [comment]
@jagnathan nice find - let's try to release this one then in the same set of migrations as the others (https://github.com/cBioPortal/cbioportal/pull/8352)

**Comment by inodb** [comment]
Let's confirm whether and how it is used in the frontend

**Comment by kalletlak** [comment]
Category is used at couple of places which needs to be refactored if it is removed
1. Results page - sorting by case list order and 
2. Query page - showing case list sample counts

**Comment by inodb** [comment]
Categories are defined here: https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#case-list-categories

**Comment by inodb** [comment]
We looked into this but we might revamp caselists anyway, so not worth investing too much time

**Comment by jagnathan** [comment]
the enumeration for sample list category is defined in the file core/src/main/java/org/mskcc/cbio/portal/model/SampleListCategory.java

This is the same list mentioned in the docs as case list categories above.
