### ISSUE TITLE
discussion about tab/component-specific states

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4937]
@alisman @adamabeshouse I am capturing the discussion about tab-specific states here. Please fill in if anything is wrong or missing. Please also do some research and see if there is an existing (better) solution.

- tab/component-specific states should not destroy after unmounted (tabs/components should be able to register to the global state registry/store). We may also want to save states into session in the future.
- a component should only listen to states that affect the component, e.g. the query state and component-specific state. (In the future, we may want to support listening to other component's state changes)
- when data/state change affects a component, that component should be unmounted. (this is our version of lazy rendering)
- when mounting a component, the component-specific state should be applied.

**Comment by adamabeshouse** [comment]
I feel like this discussion is too vague/abstract. Is there a specific task/fix we have in mind when discussing this?

**Comment by jjgao** [comment]
let's discuss in person.

**Comment by adamabeshouse** [comment]
can we close this?
