### ISSUE TITLE
SPA: merged gene tracks do not work

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#4938]
For more information on merged gene tracks: http://www.cbioportal.org/onco_query_lang_desc.jsp

**Comment by adamabeshouse** [comment]
its weird because I was able to replicate this once, but then every time since then I haven't been able to replicate. can you give step by step?

**Comment by jjgao** [comment]
Do we have screenshot tests for merged gene tracks feature?

**Comment by adamabeshouse** [comment]
no, thats a good idea

**Comment by oplantalech** [comment]
Ok, so the merged gene tracks don't work when the query contains genesets. If the query contains only genes, then merged gene tracks work. So I guess the bug is in the genesets. I'll close this issue.
