### ISSUE TITLE
API for calculating density plot of two numeric attributes

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4941]
We are switching to density plot for the `Mut vs CNA` plot (https://github.com/cBioPortal/cbioportal/issues/4835). Currently, all sample level data are retrieved from API and binned on frontend. But the density plot is actually a 2D histogram and can be calculated in the backend. It'll reduce the data size dramatically for large dataset.

@ersinciftci @adamabeshouse it would be great if you can work together and move the calculation code to the backend. To generalize it, the backend should be able to calculate densities for any two numeric attributes.

**Comment by adamabeshouse** [comment]
@ersinciftci we'll also need to be able to query by range of FGA and mutation count, for the draw-to-select feature
