### ISSUE TITLE
SV: Add range chart to bar chart

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4948]
Allow user to see the data distribution base on the range selected.

Similar concept: http://dc-js.github.io/dc.js/examples/range-series.html, https://dc-js.github.io/dc.js/

![screen shot 2018-10-05 at 3 23 24 pm](https://user-images.githubusercontent.com/5400599/46559596-d3598180-c8be-11e8-879a-c2393bf38139.png)
![screen shot 2018-10-05 at 4 49 32 pm](https://user-images.githubusercontent.com/5400599/46559680-0ef44b80-c8bf-11e8-825f-85321e000fbe.png)

**Comment by jjgao** [comment]
There could be two purposes of the range chart:

1. zoom / pan the view of the chart
2. selection of samples in a range

Maybe we should just do # 1?

Also, ideally, the range chart can be minimal.

**Comment by jjgao** [comment]
Let's design it the same way for density plot and maybe also survival plot (https://github.com/cBioPortal/cbioportal/issues/2176).
