### ISSUE TITLE
Change results summary from "Gene Set / Pathway is altered in ..."

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4953]
Maybe this is a good opportunity to change the results summary from "Gene Set / Pathway is altered in ..." to "Gene set is altered in ...". There is no need to use the term pathway here, and it may just be confusing sometimes. 

@jjgao What do you think?

**Comment by jjgao** [comment]
@schultzn I suggested to @alisman that we can probably just remove this summary sentence as it is also in the oncoprint tab (without pathway etc). What do you think?

**Comment by schultzn** [comment]
This is now related to my other proposal to move the toolbar for the oncoprint. I think having the summary above the top is useful (e.g., for enrichments, survival). I vote to keep it there.

**Comment by jjgao** [comment]
@alisman: let's keep the summary and do something similar to https://github.com/cBioPortal/cbioportal/issues/3000. Please also change the text as suggested by @schultzn.

I think we can remove the summary from OncoPrint as proposed in https://github.com/cBioPortal/cbioportal/issues/4976.

**Comment by jjgao** [comment]
I am closing this one and will capture it in #4976.
