### ISSUE TITLE
Beta: Lollipop plots not showing

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4954]
This is the mutations tab for the first example query:

![image](https://user-images.githubusercontent.com/11892704/46576072-06b81100-c990-11e8-973e-0681fe02839d.png)

http://www.cbioportal.org/beta/results/mutationsTab?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_ids=&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations

**Comment by jjgao** [comment]
@alisman it seems like a configuration issue of genome nexus url.

![image](https://user-images.githubusercontent.com/840895/46614429-d41f2d00-cae3-11e8-9733-b9f5f701e674.png)
