### ISSUE TITLE
SV: MDACC heatmap tab key needs to be heatmaps

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#4958]
Also in the patient view, probably the url should be called `heatmapsTab` instead of `heatMapReportTab`

**Comment by jjgao** [comment]
@zhx828 do we still have the heatmap in patient view?

**Comment by zhx828** [comment]
@jjgao yes we do. http://www.cbioportal.org/beta/patient/heatMapReportTab?caseId=TCGA-BL-A0C8&studyId=blca_tcga_pub

**Comment by jjgao** [comment]
Thanks, @zhx828.

I think we should probably remove it as it's not useful in the patient view page. @schultzn would you agree?

**Comment by schultzn** [comment]
Yes, probably ok to remove it.

**Comment by zhx828** [comment]
@alisman I can fix together with study view.
