### ISSUE TITLE
change text in oncoprint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4961]
change "sequenced cases/patients" to "queried cases/patients"

![image](https://user-images.githubusercontent.com/840895/46612939-df705980-cadf-11e8-98b9-1ba48bdea495.png)

**Comment by adamabeshouse** [comment]
@jjgao you mean when # sequenced = # queried, right?

**Comment by adamabeshouse** [comment]
obsolete w compact oncoprint
