### ISSUE TITLE
Set gzip configuration as default for Docker Image

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#497]
Set default for `WEBAPP_OPTS` in https://github.com/cBioPortal/cbioportal/blob/master/docker/web/Dockerfile to be 

```
-AmaxHttpHeaderSize=16384 -AconnectionTimeout=20000 --enable-compression
```
Similar to https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/blob/master/cbioportal/cbioportal_spring_boot.yaml

For the default web + data image: https://github.com/cBioPortal/cbioportal/blob/master/docker/web-and-data/Dockerfile. We should add it to the documentation: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker#step-6-run-the-cbioportal-web-server. Currently we don't mention compression at all

**Comment by ecerami** [comment]
I can do this one.

**Comment by pieterlukasse** [comment]
I believe @jjgao also had a scenario where some extra configuration is needed in case you have an extra Apache web-server. @jjgao : maybe this is also good to document?

**Comment by pieterlukasse** [comment]
apparently not yet in the wiki...?

**Comment by pieterlukasse** [comment]
@sheridancbio : could you maybe take care of this one?

**Comment by pieterlukasse** [comment]
@inodb: our Docker setup takes care of this here: https://github.com/thehyve/cbioportal-docker/blob/master/catalina_server.xml.patch#L7
How is this done in the recent one you made using webapp runner (https://github.com/cBioPortal/cbioportal/blob/master/docker/web/Dockerfile#L28)?

**Comment by inodb** [comment]
@pieterlukasse good point - these are command line arguments to webapp-runner:

https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/blob/master/cbioportal/cbioportal_spring_boot.yaml#L117-L134

Should probably be the default for the image

**Comment by pieterlukasse** [comment]
Thanks @inodb. I agree it should be the default. Feel free to close this issue once the image is adjusted.

**Comment by inodb** [comment]
we should still update this

**Comment by inodb** [comment]
Could finally close this :) - the tricky part was that web-and-data docker image did not have a default run command. Since we combine both data import and web in the image, it didn't really make sense to have a default for that one. Now with the new docker-compose setup we could add the default there instead
