### ISSUE TITLE
Enhancement to cbioportalImporter.py : option to deleteCancerStudyByCascade()

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#4975]
There are two methods of deleting cancer studies in the portal core:
DaoCancerStudy.deleteCancerStudy() : executes over a dozen operations removing related data across multiple tables for a designated study
DaoCancerStudy.deleteCancerStudyByCascade() : executes a single operation removal of the record for the designated study from the cancer_study table ... and relies on the delete cascade feature of foreign key constraints.

Because we allow deployers to deploy to databases that do not support foreign key constraints, we cannot make the cascade function the method for removing cancer studies with cbioportalImporter.py, but we could add an optional argument which allowed a user who knew that their database supported FKC to request the cascade method, which may be more efficient.

Alternatively we might be able to detect whether the database supports foreign key constraints and cascades ... either by database queries or using a test operation to probe capabilities.

In any case, if we allow the use of DaoCancerStudy.deleteCancerStudyByCascade(), it would also be wise to follow this operation with the "cleanup orphan records" function call DaoCancerStudy.purgeUnreferencedRecordsAfterDeletionOfStudy()

**Comment by sheridancbio** [comment]
cc: @fedde-s @kalletlak

**Comment by kalletlak** [comment]
@fedde-s @sheridancbio any updates on this?

**Comment by fedde-s** [comment]
As for me, I don't plan to work on it any time soon. As for peope in my office who may be running into it or working with adjacent code: @SRodenburg, @oplantalech or @pvannierop, do any of you think that potentially making study removal more performant/robust would fit something you're working on?

**Comment by jjgao** [comment]
@sheridancbio is there any plan on the pipeline team to work on this?

**Comment by sheridancbio** [comment]
@jjgao this in not on the roadmap currently. I think there are too many other priorities in progress for this to be taken up. cc: @n1zea144
