### ISSUE TITLE
More compact OncoPrint tab

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4976]
I propose to slightly redesign the OncoPrint tab. Two options below. Thoughts?

Option 2 is probably better, as the case list and alteration frequency is already shown above the tab.

But if we go with option 2, where would information about multiple samples per patient go?

![image](https://user-images.githubusercontent.com/11892704/46689905-f3df4f80-cbce-11e8-82c0-821cfb69b3d8.png)

![image](https://user-images.githubusercontent.com/11892704/46689721-82070600-cbce-11e8-9281-3589f0630e67.png)

![image](https://user-images.githubusercontent.com/11892704/46689734-88957d80-cbce-11e8-9055-c5de4eacada3.png)

**Comment by schultzn** [comment]
Adding option 3

![image](https://user-images.githubusercontent.com/11892704/46690430-45d4a500-cbd0-11e8-816c-91211955d98e.png)

**Comment by jjgao** [comment]
I like option two better too. We have the the `show patient/sample` option under View menu -- would that be sufficient?

![image](https://user-images.githubusercontent.com/840895/46708865-c914eb80-cc0e-11e8-899c-2a4c25c2c17d.png)

**Comment by schultzn** [comment]
I think that is too hidden.

**Comment by schultzn** [comment]
I think we should find a way to indicate to the user when multiple samples from a single patient were merged.

**Comment by jjgao** [comment]
@schultzn maybe we can have a clinical track to indicate the number of samples per patient when multiple samples from a single patient were merged? We can then have a submenu of that track to expand to samples?

**Comment by adamabeshouse** [comment]
@jjgao @schultzn what about adding this information to the portal header?
![image](https://user-images.githubusercontent.com/636232/46756923-a1696600-cc96-11e8-90c7-c3b8a07ff0e9.png)

**Comment by adamabeshouse** [comment]
if people need to know specifically which patients have more than one sample, then a clinical track would make sense, but otherwise it seems overly complicated if all they need to know is that some columns contain more than one sample.

**Comment by jjgao** [comment]
To summarize:

- option 2
![image](https://user-images.githubusercontent.com/11892704/46689734-88957d80-cbce-11e8-9055-c5de4eacada3.png)
- adding number of patients into header
![image](https://user-images.githubusercontent.com/636232/46756923-a1696600-cc96-11e8-90c7-c3b8a07ff0e9.png)
- modify the the header "Gene Set / Pathway is altered in ..." to "Queried gene(s) is/are altered in ..." (switch based on 1 gene or multiple genes)
- add "# samples" clinical attribute track and allow expanding to samples in the track menu

ok, @schultzn

**Comment by schultzn** [comment]
I like it! OK!

**Comment by tmazor** [comment]
I'm a little late to this one but I like this plan also!

However, I think we're going to be missing one thing. The % altered in the header is always at the sample level:
![image](https://user-images.githubusercontent.com/10508276/46762952-7a1a9500-cca6-11e8-99f5-9578af972520.png)

But the % altered in the Oncoprint can be % samples or % patients depending on what is being viewed:
![image](https://user-images.githubusercontent.com/10508276/46762982-8bfc3800-cca6-11e8-99fd-4bc145199217.png)
vs
![image](https://user-images.githubusercontent.com/10508276/46762996-94547300-cca6-11e8-88d1-42ffc2700e90.png)

Perhaps we add that to the header? Maybe something like: "Queried gene(s) is/are altered in X (Y%) of queried samples and Z (W%) of queried patients"

**Comment by jjgao** [comment]
@tmazor good point. 

When there is just one sample for every patient, we can do: "Queried gene(s) is/are altered in X (Y%) of queried samples/samples"

**Comment by adamabeshouse** [comment]
do we want the num samples track to start at 0 or the minimum?

this is starting at 0 (in other words, most have 1)
![image](https://user-images.githubusercontent.com/636232/47823841-75467f80-dd40-11e8-8ec2-cca8a5a0f2af.png)

sorted
![image](https://user-images.githubusercontent.com/636232/47823851-8099ab00-dd40-11e8-9c0e-42739b9f75e2.png)


this is starting at the data minimum, so that its blank space if at 1

![image](https://user-images.githubusercontent.com/636232/47823879-a2932d80-dd40-11e8-9d55-523050e61472.png)

sorted
![image](https://user-images.githubusercontent.com/636232/47823892-b0e14980-dd40-11e8-91a6-d5f678ea5196.png)

**Comment by jjgao** [comment]
@adamabeshouse I think starting at 0 makes sense.

**Comment by jjgao** [comment]
@schultzn we are now always showing the oncoprint menu as it's not so neat or useful to hide it and leave a blank space. Please comment if you'd like to hide it.

**Comment by schultzn** [comment]
Yes, looks good.
