### ISSUE TITLE
Change download source to datahub instead of msk storage

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#4978]
Instead of maintaining two sources of our data for download (msk storage and datahub), we've been considering (@jjgao @ritikakundra @n1zea144) to allow downloading directly from github. @inodb brought up this solution for directly downloading and zipping from github (example): https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/cBioPortal/datahub/tree/master/public/acc_tcga. 

So the idea is to swap all the URL behind our downloading links (study summary page and "data set" tab) into using DownGit in the form of https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/cBioPortal/datahub/tree/master/public/STUDY_ID

*However there's concern about the limit we have for github downloading (1TB), so we'll have to experiment for ~1 month and see this limit would become an issue.

**Comment by jjgao** [comment]
Is there a way to find out the list of available studies on datahub?
