### ISSUE TITLE
adding filters in url of study view page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4983]
e.g. 
http://www.cbioportal.org/beta/newstudy?id=msk_impact_2017&filters=CANCER_TYPE:Pancreatic Cancer;Sex=Male

or learn from GDC.

**Comment by jjgao** [comment]
We decided to add the json data into the url for the first iteration just the same as what GDC does.

**Comment by zhx828** [comment]
For example this url will work

http://www.cbioportal.org/beta/newstudy?id=lgg_tcga&filters={"clinicalDataEqualityFilters":[{"attributeId":"CANCER_TYPE_DETAILED","clinicalDataType":"SAMPLE","values":["Oligoastrocytoma","Astrocytoma"]},{"attributeId":"CANCER_TYPE","clinicalDataType":"SAMPLE","values":["Glioma"]}],"clinicalDataIntervalFilters":[{"attributeId":"AGE","clinicalDataType":"PATIENT","values":[{"end":30,"start":25}]}],"mutatedGenes":[{"entrezGeneIds":[3417,546,7157]}],"cnaGenes":[{"alterations":[{"entrezGeneId":215,"alteration":2},{"entrezGeneId":175,"alteration":-2},{"entrezGeneId":10944,"alteration":-2},{"entrezGeneId":55553,"alteration":-2}]}],"studyIds":["lgg_tcga"]}

**Comment by zhx828** [comment]
@jjgao in the first release, how do you want to generate the URL?

**Comment by jjgao** [comment]
@zhx828 you mean change the url when selecting?

**Comment by jjgao** [comment]
Ideally, if we can simplify the json...

{
"CANCER_TYPE_DETAILED":["Oli..."],
"SAMPLE_TYPE":["..."],
"AGE":[{"start":25,"end":30}],
"@mutatedGenes#":[...],
"@cnaGenes#":[...],
"@studyIds#":["..."]
}

**Comment by jjgao** [comment]
@zhx828 is the implementation already done if we decide not to change the format?

We will need to document it.

**Comment by zhx828** [comment]
@jjgao the implementation of the current filter in the URL is done. But the new format you posted above hasn't been supported yet.

**Comment by jjgao** [comment]
@ersinciftci do you think the simplified json format above is something that is technically possible?

**Comment by jjgao** [comment]
alternatively, we could do:

```json
{
  "clinicalPatient":
  {
	"AGE":[{"start":25,"end":30}],,
	...
  },
  "clinicalSample":
  {
	"CANCER_TYPE_DETAILED":["Oli..."],
	"SAMPLE_TYPE":["..."],
	...
  },
  "mutatedGenes":{
	profileId: 1111,
	entrezGeneIds: [...]
  },
  "cnaGenes":{
	profileId: 1112,
	entrezGeneIds: [...]
  },
  "studyIds":["..."]
}
```

Later we may add other filtered, e.g. filter based on expression data.

**Comment by jjgao** [comment]
Ok. Updated. It's actually not simplified much comparing to the original one. But I think it's good to organize by the data categories (patient or sample) instead of the attribute data type (numerical or string). @ersinciftci is it possible to make the change before we make the first release?

The `mutatedGenes` and `cnaGenes` are the same, except I added `profileId` (I think we need that right?). I think we should

**Comment by jjgao** [comment]
@jjgao @zhx828 @kalletlak sorry I think I misunderstood how it works right now. I thought the whole json was sent to the backend to filter to the sample? If not, we can do it in the frontend.

**Comment by jjgao** [comment]
@zhx828 let's prioritize this. I am thinking that maybe we shouldn't use the json directly and instead, come up with a human-readable format for the url.

**Comment by onursumer** [comment]
- [ ] remove the `clinicalDataType`: Decide the data type on backend
- [ ] support hugo symbols in addition to `entrezGeneIds`: Map hugo symbol to entrezGeneId on backend
- [ ] unify `clinicalDataEqualityFilters` and `clinicalDataIntervalFilters` into `clinicalDataFilters`

**Comment by jjgao** [comment]
@zhx828 could you prioritize this one?

**Comment by alisman** [comment]
@kalletlak, @jjgao and i decided that the best way to do this is to encode json in url hash (e.g. results/?blah#{json}.   When json gets long, we offer a url shortening button.

**Comment by kalletlak** [comment]
@alisman you mean json of complete StudyViewFIlter object?

**Comment by n1zea144** [comment]
@jjgao I'm looking at [PR6585](https://github.com/cBioPortal/cbioportal/pull/6585) which is a supporting PR for this effort.  I wonder why GraphQL was not considered (and maybe should still be) as a means to filter/query.

**Comment by jjgao** [comment]
@n1zea144 I think PR #6585 is just change some of the format of the currant API. The decision of using JSON based REST api was during the refactoring effort. 

We can consider GraphQL implementation if needed, but it probably should be implemented as separate effort across the API. (But I am not sure if there is a reason to prioritize that though.)

**Comment by kalletlak** [comment]
@jjgao @zhx828 here is what we discussed today

- [ ] Replace `mutationCountVsCNASelection` filter with individual clinical data filters.
This requires following changes

    **Frontend**
    - [ ] sync selections on `Mutation Count vs Fraction of Genome Altered`, `Mutation Count` and `Fraction Genome Altered` charts

     **Backend**
     - [ ] Update `/clinical-data-bin-counts` api to support continuous(if values doesn't fall under defined bins return just 3 bins) filter range

- [ ] Combine and replace filters on `Mutated Genes`, `CNA Genes` and `Fusion Genes` with limited OQL support
new filter format looks something like
	```
	"geneFilters": [{
		"molecularProfileIds": ["string"],
		"values": ["string"]
	}]
	```
    possible for values `["ALK"]`, `["ALK: MUT"]`, `["ALK: AMP"]`, `["ALK: HOMDEL"]`, `["ALK: FUSION"]`

**Comment by jjgao** [comment]
Thanks, @kalletlak! @adamabeshouse @zhx828 and I discussed about oql support and thought one option is utilize the frontend oql parser and and the parsed oql-json data to backend, while still using the oql in the url. We should evaluate the pros annd cons.

**Comment by kalletlak** [comment]
@cBioPortal/product here is the test url for testing these updates
https://cbioportal-feature-sv-u-o2unal.herokuapp.com/
