### ISSUE TITLE
Full study names not always visible on the main query page

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4984]
When a study name is too long, it is truncated with "...". The full study name is not show when hovering over it with the mouse. There also seems to be available space to show more characters.

Not sure who to assign this to.

![image](https://user-images.githubusercontent.com/11892704/46755714-cd371c80-cc93-11e8-837c-783f7bde8986.png)

**Comment by alisman** [comment]
@schultzn I think we've improve the situation here.  It's still not perfect.  It's difficult probleem
