### ISSUE TITLE
How to automate the process of testing pull request?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#499]
Currently, we have to checkout the pull request locally and build a war file from it, deploy to our server and test it. Can we automate the process?

Can we use travis to do that? For example, travis can deploy to Heroku (http://docs.travis-ci.com/user/deployment/heroku/). We would need to set up a public test database.

Ideally, different wars are used for different pull requests (named by PR id?) and closed when PRs are closed.

**Comment by jjgao** [comment]
Ino has find the solution using Heroku. A few more items to follow up with Heroku:

 - [ ] build war of pull requests from folks
 - [ ] put the link to war in the "Merge Pull" section

**Comment by inodb** [comment]
They told me they are working on both these items
