### ISSUE TITLE
METABRIC: Samples in which no mutations were found are considered as not profiled

### ISSUE THREAD

**Issue by clfougner** [cBioPortal/cbioportal#5000]
When viewing the most frequently mutated genes in the METABRIC dataset (http://www.cbioportal.org/study?id=brca_metabric#summary) under the "Mutated genes" card, the "Freq" value (that is, the percentage of tumors carrying mutations in the given gene) is inaccurate.

This is because only 173 genes were sequenced in this study, and not all sequenced tumors carried mutations in one of the sequenced genes. The sequence data is saved in a single file with mutation data from all samples, with one row per mutation. The consequence of this is that those tumors in which no mutations were found are not found in the data itself. All sequenced tumors are however listed in the first line of the file.

Examples of tumors with no mutations include MB-5325, MB-5255 and MB-0907. If you search the mutations file, you will see these sample names listed in the first row, but they are not found in the data rows.

Consequently, the value currently given for the number of samples profiled is in fact the number of samples profiled and in which at least one mutation was found. The denominator for the calculation of the Freq value is therefore too low, thereby inflating the the percentage of tumors carrying the mutation. 

For example, 218 claudin-low tumors were sequenced, however when only viewing those tumors, the number of tumors profiled is listed as 182. The frequency of Tp53 mutations, for example, is therefore listed as 104 / 182 = 57.14%, when the real frequency is 104 / 218 = 47.71%.

**Comment by jjgao** [comment]
@clfougner Thank you for bringing this to our attention.

@ritikakundra we have some issues with the case lists, which causes this issue.

In [data_mutations_extended.txt](https://github.com/cBioPortal/datahub/blob/master/public/brca_metabric/data_mutations_extended.txt), the first line `sequences_samples` indicate all 2509 samples were sequenced. But in [cases_sequenced.txt](https://github.com/cBioPortal/datahub/blob/master/public/brca_metabric/case_lists/cases_sequenced.txt), there are only 2369 samples. Please correct this.

[cases_cnaseq.txt](https://github.com/cBioPortal/datahub/blob/master/public/brca_metabric/case_lists/cases_cnaseq.txt) should also be corrected.

I am wonder if [cases_cna.txt](https://github.com/cBioPortal/datahub/blob/master/public/brca_metabric/case_lists/cases_cna.txt) is correct. Please double check.

@n1zea144 I am wondering if it is a systematic issue.

**Comment by jjgao** [comment]
@pieterlukasse @sandertan maybe it's possible to check if the case_sequenced.txt has the right samples if data_mutations_extended.txt has a "#sequenced_samples" line?

**Comment by ritikakundra** [comment]
@jjgao We used our case-lists script to create this and from what I understand, it does use the seq_sample header to create the case_list if specified. Am not sure why this skipped. Fixing it now

**Comment by jjgao** [comment]
fixed in https://github.com/cBioPortal/datahub/pull/394.

Thanks, @ritikakundra ! Could you schedule it for update to the portal?

**Comment by sandertan** [comment]
@jjgao "#Sequenced_Samples: " looks like a nice way to add the sequenced samples to a MAF file. In addition to adding this rule to the validator, shall we document in File-Formats that if this attribute is added, the sample list should be the same as in `cases_sequenced.txt`?

In the future we could even use this as the source for the _sequenced case list, and deprecate `cases_sequenced.txt`.

**Comment by jjgao** [comment]
@sandertan good point. We can do that as part of the plan to switch to case lists that link to profiles. https://docs.google.com/document/d/1aBbkTAFv5nCqBv66BOgwvlt5kymgt0lQ7l_pqaFrupc/edit
