### ISSUE TITLE
Setting up attributes in Clinical Tabs According to Priority

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#5002]
Discussed this with @jjgao 

The clinical attributes in the Clinical Tab, as well as the clinical tab in patient view, be ordered on the basis of set priorities rather than alphabetically.

**Comment by zhx828** [comment]
@jjgao @ritikakundra this has been implemented in the new study view. I'm looking at the patient view, but wouldn't it weird if you sort by Attribute, but the table is not sorted alphabetically but by priority?

**Comment by zhx828** [comment]
@jjgao @ritikakundra never mind. I'm going to sort by priority by default. It should not affect other columns sorting.
