### ISSUE TITLE
Query with sample list fails in SPA

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#5006]
http://www.cbioportal.org/index.do?cancer_study_id=all&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=1&case_set_id=w_cna&gene_list=CDKN2A%2520CDKN2B%2520CDKN2C%2520CDK4%2520CDK6%2520CCND2%2520RB1&geneset_list=%20&tab_index=tab_visualize&Action=Submit&cancer_study_list=acyc_fmi_2014%2Cacyc_mda_2015%2Cacyc_mskcc_2013%2Cacyc_sanger_2013&show_samples=false&clinicallist=CANCER_STUDY

**Comment by alisman** [comment]
This occurs on query with multiple studies.  Samples specification is messed up.    studyId has concatenated list
![image](https://user-images.githubusercontent.com/186521/46897486-e46f3900-ce50-11e8-817e-4b00995d288a.png)

**Comment by jjgao** [comment]
@alisman currently we reply on convention of the case lists, studyId_sequenced, _cna, _cnaseq. Do we have the case lists in the frontend?

**Comment by jjgao** [comment]
@kalletlak please chime in if you have any comments.

**Comment by kalletlak** [comment]
@jjgao not exactly. we are currently using case list category. 
`w_mut -> all_cases_with_mutation_data -> which corresponds to <studyId>_sequenced`
`w_cna -> all_cases_with_cna_data -> which corresponds to <studyId>_cna`
`w_mut_cna -> all_cases_with_mutation_and_cna_data -> which corresponds to <studyId>_cnaseq`
