### ISSUE TITLE
Validator fails with python2

### ISSUE THREAD

**Issue by thomasyu888** [cBioPortal/cbioportal#5007]
I know python2 is being deprecated eventually, but I think we should make the validator python2 friendly as well. (I personally use python3, but some collaborators still use python2)
```
python2 validateData.py -h
  File "validateData.py", line 2559
    ) from e
         ^
SyntaxError: invalid syntax
```

**Comment by jjgao** [comment]
@fedde-s @pieterlukasse do you think we should try to support python2 at all?

**Comment by jjgao** [comment]
@fedde-s agreed. I am closing this one.
