### ISSUE TITLE
New cBioPortal Instance for Cell-line cohorts

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#5014]
We are updating CCLE cohort with new datasets and also hoping to get more cell line cohorts. Maybe it's a good idea to discuss to have a cell line portal and not integrate it with non-cell line portal.

**Comment by jjgao** [comment]
I think it's good to have the cell line data together with tumor data so that they can be compared, as long as we don't put them into the default set.

**Comment by ritikakundra** [comment]
hmm, I am actually not sure why this was created. I believe this was based on the outcome of a meeting.
