### ISSUE TITLE
performance - new study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5015]
- [x] sql potential improvement (single study vs multiple) #4802
- [ ] filtering improvement (ideally only do filtering once for all ajax calls)
- [x] reduce ajax call by combining all unfiltered pie charts in one call and the same with filtered pie chars. And the same with bar charts.
- [x] scatter plot imporvement (hide it for genie, and support density plot)
- [ ] max simultaneous calls
- [ ] cache (mybatis or custom), e.g. cache by filtering criteria for getting the list of samples (session-based, user-based, global?)

**Comment by zhx828** [comment]
@jjgao @ersinciftci @n1zea144 is this done?

**Comment by jjgao** [comment]
I have removed this from 1.19.0, but let's keep it open - there is still room to improve.
