### ISSUE TITLE
sv: survival plots & mutation vs cna plots should be blue by default, not red

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5016]
On old study view, these plots appear in blue:
![image](https://user-images.githubusercontent.com/10508276/47029366-5f7a6d00-d139-11e8-8100-f8fd29e9ef5b.png)

And then when you make a selection, the selected samples appear in red and the rest in blue:
![image](https://user-images.githubusercontent.com/10508276/47029390-6dc88900-d139-11e8-8f5b-c15c885b22b1.png)

But in the new study view, these plots are red to start:
![image](https://user-images.githubusercontent.com/10508276/47029433-889afd80-d139-11e8-8958-a9b67a82150f.png)

Let's revert to blue as the default color for these plots.

**Comment by jjgao** [comment]
We'll change the scatter plot to a density plot and unselected samples will not be shown.

@zhx828 please change the color for survival plots.
