### ISSUE TITLE
Oncoprint clinical attribute coloring NO/YES

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5026]
Seems like `No` can sometimes be red when there's No/Unknown/Yes/No data. See screenshot `blca_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png`

in

https://github.com/cBioPortal/cbioportal-frontend/pull/1571/files?short_path=f3fb37c#diff-f3fb37cc3c2a5d8173a826ae8be3aa99

I guess this is just based on some sorting, but perhaps we want to assign the colors for yes/no/no data in some default way

**Comment by jjgao** [comment]
We should use the same colors as in study view.

**Comment by adamabeshouse** [comment]
right now colors are not specified for anything, defaults always chosen for clinical tracks (besides mutation spectrum). but it wouldn't be hard to do so. where do we get the colors from though?

**Comment by jjgao** [comment]
@zhx828 @adamabeshouse ideally we should use the same code for choosing colors for study view and oncoprint.

**Comment by zhx828** [comment]
@adamabeshouse the color is defined currently under `StudyViewConfig.ts`. Aaron and I had a discussion moving it uner /srv/config. You can start to use it if you want. I can fix that when I do moving.

**Comment by sandertan** [comment]
This would be nice to have! Could you also assign fixed colors for other common used values? Such as:
- Positive/Negative (case insensitive)
- True/False (case insensitive)
- No data
- Unknown
- Other

I got most of these from querying BRCA TCGA (Prov) and adding all clinical data as tracks.

**Comment by adamabeshouse** [comment]
sure, just let me know what the colors should be. we already have True #66AA00 and False #666666
