### ISSUE TITLE
Cancer type summary chart cutting off labels

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#5031]
![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/c088741a-c125-4858-a654-15c8c7e0658e)

**Comment by adamabeshouse** [comment]
http://www.cbioportal.org/beta/results/cancerTypesSummary?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=coadread_tcga_pub&case_set_id=coadread_tcga_pub_nonhypermut_all&data_priority=0&gene_list=KRAS%2520NRAS%2520BRAF&geneset_list=%20&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&tab_index=tab_visualize
