### ISSUE TITLE
If show_oncokb=false, we still request oncokb data

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#5036]
We don't show annotations on patient page, but we still make requests to oncokb endpoints.  @jjgao this is wrong yes?

I also found, we still show oncokb data in oncoprint and on mutations tab.  So i general it would seem aren't respecting this variable properly.

Maybe we can fix this as follow up @jjgao

**Comment by jjgao** [comment]
@alisman we should fix it. If show_oncokb=false, we should not load oncokb the data or show anywhere.

**Comment by alisman** [comment]
@jjgao i think this is not an new issue so perhaps we can defer to 1.19.0

**Comment by jjgao** [comment]
@alisman ok. I think we should fix it in master.
