### ISSUE TITLE
RC: custom logo broken

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#5041]
In RC the image of the custom logo (top right) does not work. Might be related with: https://github.com/cBioPortal/cbioportal/issues/5035

**Comment by alisman** [comment]
@oplantalech can you send us the configuration you are using for that property?

**Comment by alisman** [comment]
This should be fixed.    It works on MSKCC portal where the right logo is configured to "msk_logo_transparent_black.png"     
it's relative to the root/images directory of instance.

**Comment by oplantalech** [comment]
Yes, it is working. Thanks @alisman for taking a look at this. I'm closing this issue.
