### ISSUE TITLE
Change columns shown by default for mutations in patient view

### ISSUE THREAD

**Issue by messersc** [cBioPortal/cbioportal#5043]
Hi,

a collaborator of us asked if it would be possible to change the default columns a patient's mutation table to always show some columns like chromosome, position and the number of reads supporting the variant in the tumor. Mainly this is to save some clicks, otherwise you need to add these columns every time you change to another patient.

I thought I'd look for places which control this and here are the changes I made, which apparently do not change anything - I'm not fluent in js.

```diff
--- a/portal/src/main/webapp/WEB-INF/jsp/patient_view/mutations.jsp
+++ b/portal/src/main/webapp/WEB-INF/jsp/patient_view/mutations.jsp
@@ -237,7 +237,6 @@
                     },
                     {// chr
                         "aTargets": [ mutTableIndices["chr"] ],
-                        "bVisible": false,
                         "sClass": "right-align-td",
                         "mDataProp": function(source,type,value) {
                             if (type==='set') {
@@ -251,7 +250,7 @@
                     },
                     {// start
                         "aTargets": [ mutTableIndices["start"] ],
-                        "bVisible": false,
+                        "bVisible": true,
                         "sClass": "right-align-td",
                         "mDataProp": function(source,type,value) {
                             if (type==='set') {

```

It would be nice if someone could point me into the right direction. 

Further, wouldn't it be desirable to expose this option in the portal.properties as a setting?

Thanks!
Clemens

**Comment by jjgao** [comment]
@messersc thanks for the feature request. This might be a feature that should be user-specific instead of instance-specific, as different users might want to see different columns. One option would be using cookie/local storage to remember the selection.

The frontend code are now here: https://github.com/cBioPortal/cbioportal-frontend
