### ISSUE TITLE
Bug in fetch molecular data endpoint

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#5044]
When the `/molecular-data/fetch` endpoint is called with an empty `molecularProfileIds` list, the endpoint returns a nullpointer exception instead of a 404.

You can test it in cbioportal.org with these parameters:
```
{
  "entrezGeneIds": [
    1442
  ],
  "molecularProfileIds": [
  ]
}
```

**Comment by ersinciftci** [comment]
https://github.com/cBioPortal/cbioportal/pull/5045 adds a size constraint, so it will return 400 and say 
```
{
  "message": "molecularProfileIds size must be between 1 and 10000000"
}
```
