### ISSUE TITLE
sort by allele freq not working properly on patient view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5047]
NaN values show up high in the list http://www.cbioportal.org/patient?studyId=lgg_ucsf_2014&tab=summaryTab&caseId=P04

DM for genie-private link

**Comment by jjgao** [comment]
@alisman I just assign this to you but please delegate.

**Comment by dippindots** [comment]
@jjgao Should we keep the NaN rows at the bottom all the times? Or do we want to place them at the top when we are sorting from low to high?

**Comment by jjgao** [comment]
@dippindots good question. Maybe place them at the bottom all the time.
