### ISSUE TITLE
We should replace the term "Sequenced Tumors" in case lists

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5048]
The term sequenced tumors is misleading. To be consistent with what we use in the study view, we should rename these lists to:

"Tumors with mutation data"
and
"Tumors with mutation and CNA data"

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #444](https://github.com/cBioPortal/datahub/issues/444) via [**ZenHub**](https://www.zenhub.com/)
