### ISSUE TITLE
evaluate plotly.js

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#505]
Let's use this as a discussion thread for evaluation of plotly.js.

https://plot.ly/javascript/open-source-announcement/
https://github.com/plotly/plotly.js

 - [x] Evaluate plotly.js for plots @yichaoS
 - [ ] Evaluate plotly.js for study view @zhx828  
 - [ ] Does their WebGL impl use GPU? @leedonghn4 
 - [ ] Evaluate data format compatibility

**Comment by leedonghn4** [comment]
I have not found the GPU code now

**Comment by yichaoS** [comment]
http://dashi-dev.cbio.mskcc.org:8080/plotly-cc-plots/

**Comment by yichaoS** [comment]
Problems: 
- No hyperlink in mouse-over (tmp solution: click on dots)
- missing SVG & PDF download
- can't hover axis titles for full study name (tmp solution: included in qtip)
- glitch when switching genes and sorting
