### ISSUE TITLE
oncokb issue in patient view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5060]
http://www.cbioportal.org/patient?studyId=skcm_tcga&sampleId=TCGA-FW-A3R5-06

![image](https://user-images.githubusercontent.com/840895/47310510-6277d080-d605-11e8-84aa-85760cd66e8c.png)

cancer type if wrong ("in null").

And should it be level 2B instald level 1?

**Comment by alisman** [comment]
@zhx828 this is a database issue?  is it being dealt with? can we close?

**Comment by zhx828** [comment]
@alisman This is a data issue, but should still be handled in the frontend. If the sample does not have tumor type, then the query should use the study tumor type unless it is a mixed. I think Gaofei is working on this ticket? We discussed about this ticket last week.

**Comment by zhx828** [comment]
ccing @dippindots
