### ISSUE TITLE
OQL does not carry through to the mutation tab

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#507]
If you search for specific mutations, e.g.  BRAF: MUT = V600, the OQL is respected within the OncoPrint.  But, it's not respected within the mutation tab, e.g. you get all mutations for BRAF, not just V600.

@schultzn @jjgao:  Is this a bug or a specific feature?

**Comment by onursumer** [comment]
Mutation tab gets the mutation data through a separate servlet (MutationDataServlet). Currently it does not support OQL parameters, it only works with a list of genes.

We can either add OQL support to the servlet or filter the mutations wrt OQL on the client side.
