### ISSUE TITLE
spa: icons on homepage aren't working

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5070]
The Github logo is just a box (also the frontend version is wrong but I think that's already been flagged):
![image](https://user-images.githubusercontent.com/10508276/47328187-16954d80-d63e-11e8-8fe4-64fd9fff00ac.png)

The twitter logo in the sidebar is also a box:
![image](https://user-images.githubusercontent.com/10508276/47328178-1006d600-d63e-11e8-8ba5-a7b2f9e9c2d9.png)

The studies list also has problems:
![image](https://user-images.githubusercontent.com/10508276/47328286-958a8600-d63e-11e8-9c61-ece648c0f44c.png)

![image](https://user-images.githubusercontent.com/10508276/47328407-05007580-d63f-11e8-8ff1-8e206b60a527.png)

**Comment by inodb** [comment]
@alisman thanks - ill try to add them
