### ISSUE TITLE
spa: enrichments tab add gene to query button doesn't add gene to modify query interface

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5076]
If I use the enrichments tab "add gene to query" button to add a gene to a query, it works correctly and brings me back to OncoPrint with the new gene added. However, if I then use the modify query button, the newly added gene does not appear in the gene box.

**Comment by adamabeshouse** [comment]
note to self: this is because QueryStore/Query form not reactive to URL changes
