### ISSUE TITLE
enrichments: error when changing mrna profile

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5080]
On production & on beta - when I change from the RNA-seq to microarray data on the enrichments tab, the page fails to load and an error appears in the console:

![image](https://user-images.githubusercontent.com/10508276/47386127-e26f6a80-d6d9-11e8-8a0c-0a8dd38ad37a.png)

http://www.cbioportal.org/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=EGFR%2520IDH1%2520CDKN2A%2520TP53%2520ATRX%2520CIC%2520PDGFRA%2520PTEN&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

**Comment by ersinciftci** [comment]
The fix is merged but it seems @adamabeshouse has an open frontend PR to handle these kind of errors better in the future, so keeping the issue open until it's merged.
