### ISSUE TITLE
beta plots - allow color by copy number when viewing mutation data

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5082]
Right now when one of the data types is Mutations, then there is no option to color the samples by copy number. Let's add that.

![image](https://user-images.githubusercontent.com/10508276/47386742-70982080-d6db-11e8-9279-25400c361549.png)

**Comment by adamabeshouse** [comment]
@jjgao told me to do this

**Comment by adamabeshouse** [comment]
@jjgao copy number and mutation view are both checked by default from the start. which would you like:
(1) make copy number unchecked by default
(2) uncheck copy number when we go to a mutation profile

**Comment by adamabeshouse** [comment]
@jjgao and when we change back to another profile? should we restore the previous setting? it feels a bit confusing. maybe we should just uncheck it by default?

**Comment by jjgao** [comment]
hmm... good point. Could you add some screenshots with both mutation and copy number checked? Ideally with both driver and vus.

**Comment by adamabeshouse** [comment]
![image](https://user-images.githubusercontent.com/636232/47464148-58e19a80-d7b6-11e8-93df-8d6b8f844d32.png)

![image](https://user-images.githubusercontent.com/636232/47464158-65fe8980-d7b6-11e8-9f9a-e5a35da8cbf7.png)

**Comment by jjgao** [comment]
@tmazor @schultzn what do you think? Should we not show CNA by default in all plots? I find it's difficult to digest when having both mutation and cna overlaid.

**Comment by tmazor** [comment]
agreed!

**Comment by jjgao** [comment]
@adamabeshouse Let's always show the CNA option (as long as there is CNA data) and uncheck it by default.
