### ISSUE TITLE
search function not work in CN segment for genes that are not on the same chromosome

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5086]
for example, in [this query](http://www.cbioportal.org/beta/results/cnSegments?session_id=5ba11ce6498eb8b3d567e7ed), if you search TP53 in CN Segments tab, no segment data will be loaded

![image](https://user-images.githubusercontent.com/840895/47404156-3bf78980-d71a-11e8-98a0-388a1ef26548.png)

Let's fix it after we switch to the new IGV.js: https://github.com/cBioPortal/cbioportal/issues/4669

**Comment by onursumer** [comment]
cBioPortal/cbioportal-frontend/pull/1713 should also fix this issue since we are now fetching the segment data for the whole genome.

**Comment by jjgao** [comment]
@onursumer we should fetch only the necessary chromosomes as discussed.

**Comment by onursumer** [comment]
@jjgao in that case built-in igv browser search functionality won't load additional data for other chromosomes. We will need to somehow detect the search event within the igv browser and load the data for every new search. 

Or maybe we start downloading the whole genome data as soon as the page loads, and the search will be fully functional when the whole genome data finish loading.

**Comment by jjgao** [comment]
@onursumer maybe we can discuss with Jim and see what's the best option here. Not a priority. Let's do this later.

**Comment by inodb** [comment]
this seems to have been addressed so im going to close it - you now click on whole genome and search for tp53 there. Everywhere else search is disabled
