### ISSUE TITLE
SPA R/Matlab page example usage boxes need formatting fix

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5089]
Production:
![image](https://user-images.githubusercontent.com/10508276/47430829-6f610500-d768-11e8-806b-dbc57c516197.png)

SPA:
![image](https://user-images.githubusercontent.com/10508276/47430836-738d2280-d768-11e8-86ae-1d6b39670c73.png)

**Comment by tmazor** [comment]
The same problems exists on on the Web API page

**Comment by inodb** [comment]
fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/1613

**Comment by inodb** [comment]
Re: web API page, im not sure we should keep that. Maybe we should just point that button to www.cbioportal.org/api

**Comment by inodb** [comment]
@jjgao 	☝️

**Comment by jjgao** [comment]
@inodb we should still keep the old one until we release the new one.

**Comment by inodb** [comment]
fixed webapi in: https://github.com/cBioPortal/cbioportal-frontend/pull/1615
