### ISSUE TITLE
SNAPSHOT jar missing

### ISSUE THREAD

**Issue by tylerizatt** [cBioPortal/cbioportal#509]
I am installing cbioportal locally and have followed all the steps from the wiki.  I was able to compile and install it with the "mvn -DskipTests clean install", with no errors (BUILD SUCCESS).  However when I went to look for - $PORTAL_HOME/core/target/core-1.0-SNAPSHOT.jar- it was missing. 
I see "core-0.1.1.jar" and "original-core-0.1.1.jar".

Relevant information
**lsb_release -a**

LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.5 (Final)
Release:	6.5
Codename:	Final

**java -version**
java version "1.7.0_45"
OpenJDK Runtime Environment (rhel-2.4.3.4.el6_5-x86_64 u45-b15)
OpenJDK 64-Bit Server VM (build 24.45-b08, mixed mode)

**mvn -version**
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
Maven home: /mongo/cbioportal/resources/apache-maven-3.3.3
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /mongo/cbioportal/resources/jdk1.8.0_65/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-431.3.1.el6.x86_64", arch: "amd64", family: "unix"

**Comment by j-hudecek** [comment]
I've just renamed core-0.1.1.jar to core-1.0-SNAPSHOT.jar and that seems to work

**Comment by jjgao** [comment]
This should have been solved in the latest code in master branch (v1.0.1).
