### ISSUE TITLE
update instructions for "linking to us"?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5090]
We have this section at the bottom of the Web API page:
![image](https://user-images.githubusercontent.com/10508276/47430932-bc44db80-d768-11e8-920f-1d0cbc1c9084.png)

Are these instructions still valid? I have a feeling that the format of our links has changed.

**Comment by alisman** [comment]
lets discuss this at standup

**Comment by jjgao** [comment]
@alisman we should still support this. It seems working if you remove `/s` in the url.

![image](https://user-images.githubusercontent.com/840895/47441864-223c5d80-d77f-11e8-8a15-64a4ae5b2a07.png)

**Comment by alisman** [comment]
@jjgao you're right!  it's using the LinkOut servlet to redirect url.    We could accomplish this in the frontend although it's certainly cleaner the way it is.  If that's important, lets schedule for later.  I'll fix the /s/ issue right now

**Comment by jjgao** [comment]
Thanks. Good idea to clean it up. I think we can do that as part of the URL clean-up effort (https://github.com/cBioPortal/cbioportal/issues/4353).

http://www.cbioportal.org/beta/ln?q=TP53:MUT seems not working though. It is b/c it's too long?

**Comment by alisman** [comment]
@jjgao the reason it doesn't work is that data_priority param is missing.  I'm thinking the legacy app figured it out based on the MUT in the oql.  Lets discuss a solution

**Comment by jjgao** [comment]
@alisman could you set data_priority=0 if missing?

**Comment by jjgao** [comment]
I would really love to get rid of data_priority soon :)
