### ISSUE TITLE
SPA oncoprinter page is still jsp

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5093]
I thought all jsp pages were gone now?

**Comment by tmazor** [comment]
I just realized the OncoPrinter link goes back to production and doesn't stay on beta. Maybe that's why?

**Comment by alisman** [comment]
@jjgao @adamabeshouse i think we just missed this one.   @adamabeshouse how much work involved to redo this?

**Comment by alisman** [comment]
@adamabeshouse We need to migrate this to new architecture and oncoprint
