### ISSUE TITLE
SPA: sharing a link

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5099]
I think we should always generate a session link instead of having the full query link for sharing.

![image](https://user-images.githubusercontent.com/840895/47444517-9af1e880-d784-11e8-9cb9-0f2903b85aed.png)

**Comment by alisman** [comment]
@jjgao can you try again?  i do get a session link.  i wonder if this was failure of session service

**Comment by jjgao** [comment]
It seems working now.
