### ISSUE TITLE
Configuration file portal.properties.EXAMPLE broken

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#5104]
The are a number of URL parameters that do not seem to be used anymore since they have been made hard-coded values in places like https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/shared/api/urls.ts and https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/pages/patientView/PatientViewPage.tsx

See 
https://github.com/cBioPortal/cbioportal/blob/master/src/main/resources/portal.properties.EXAMPLE#L125

I think most, and perhaps all, URLs should be configurable. E.g. hard coding genome nexus location like [here](https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/shared/api/urls.ts#L114) is not helpful for others trying to have local installations of cBioPortal and its dependencies like genomenexus. The same argument also applies for other URLs. Session service, oncokb, digital slides, should all remain configurable.

Desired solution:
- make the urls configurable again

**Comment by pieterlukasse** [comment]
Notify: @jjgao @alisman

**Comment by alisman** [comment]
@pieterlukasse i will tag this 1.18.1 and will follow up in next few days
