### ISSUE TITLE
Segment track depending on sequenced case list

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#5105]
In an instance with only clinical and segment data, it is currently not possible to show the Segment track in the Patient view, because there is a dependency on the "sequenced" case-list. I guess this dependency exist because of the Mutation ("MUT") track. But when there is not Mutation data, it does not make sense that this case list should be present.

## Public study that has this issue:
http://www.cbioportal.org/patient?studyId=prad_mskcc_2014&caseId=PCA0300

## TCGA test study without _sequenced case list
![screenshot 2018-10-25 at 14 07 10](https://user-images.githubusercontent.com/9624990/47499196-a7973f00-d85f-11e8-9226-f94a68fd7517.png)

## TCGA test study with _sequenced case list (but no mutation data)
![screenshot 2018-10-25 at 14 03 27](https://user-images.githubusercontent.com/9624990/47499233-b978e200-d85f-11e8-8786-a35204f7442d.png)

**Comment by pieterlukasse** [comment]
Notify: @alisman @jjgao

**Comment by jjgao** [comment]
Thanks, @sandertan. Would you like to give it a try to fix this?

**Comment by pieterlukasse** [comment]
@jjgao we found another bug that is potentially related https://github.com/cBioPortal/cbioportal/issues/5243. Maybe @zhx828 can see if he can fix both at once if they are indeed related?

**Comment by jjgao** [comment]
We will also reimplement the Genomic Overview with igv.js https://github.com/cBioPortal/cbioportal/issues/4390. Hopefully this issue will be fixed once that's done.
