### ISSUE TITLE
how to indicate there are more samples to the right in oncoprint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5107]
Since there is no visibal horizontal scrollbar in chrome, it is not obvious that there are more samples to the right. How can we can tell the user there are more samples?

![image](https://user-images.githubusercontent.com/840895/47519240-1a51eb80-d85b-11e8-9531-5edd09288592.png)

Showing the minimap would make it obvious but I guess it's too heavy.

Any thoughts? @adamabeshouse @alisman @cBioPortal/product

**Comment by adamabeshouse** [comment]
I actually think showing minimap is probably the cleanest way to do it.. I think having an arrow or other indicator would just add clutter and more things to learn about the oncoprint. The minimap shows it in an obvious way without adding more

**Comment by schultzn** [comment]
What if the OncoPrint has a lot of genes so that is pushed the mini map below the bottom of the screen?

Did we ever figure out why the scroll bar does not show up? Didn’t we determine that this was related to a Apple Cinema Display being plugged into a MacBook?

**Comment by adamabeshouse** [comment]
@schultzn theres a max height for oncoprint, and a vertical scrollbar shows up

**Comment by alisman** [comment]
@schultzn @jjgao scrollbar visibility is actually a [system setting ](https://www.google.com/search?q=macos+always+show+scrollbars&rlz=1C5CHFA_enUS710US710&oq=macos+scrollbars+show&aqs=chrome.4.69i57j0l4.10408j0j7&sourceid=chrome&ie=UTF-8)(at least on Mac)

**Comment by jjgao** [comment]
@alisman @adamabeshouse I am wondering if this can solve it? https://stackoverflow.com/questions/7492062/css-overflow-scroll-always-show-vertical-scroll-bar

**Comment by adamabeshouse** [comment]
I cant replicate the original error on my machine, can someone who can test it with the new PR: https://cbioportal-frontend-pr-1788.herokuapp.com/

**Comment by jjgao** [comment]
scrollbar show up in the pr.

![image](https://user-images.githubusercontent.com/840895/49475062-43638580-f7e4-11e8-8c03-96d6a4246a10.png)

Is it possible to make it less predomiment, e.g. thinner and maybe lighter?

**Comment by adamabeshouse** [comment]
lmao... yeah

**Comment by adamabeshouse** [comment]
lmao... yeah

**Comment by adamabeshouse** [comment]
@jjgao update pushed

**Comment by jjgao** [comment]
@adamabeshouse it looks still the same...
