### ISSUE TITLE
SPA: clicking changes URL but doesn't change the page

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5114]
I can't reproduce this, but in results view, I got to a state where I could click on other tabs and the URL would change but the site didn't actually navigate to the other tab. There were many errors in the console:

First this one appears ~20 times:
![image](https://user-images.githubusercontent.com/10508276/47533112-7bd88100-d880-11e8-8b51-6d97bdb1f88d.png)

Then this appears, and the second of these repeats a few times:
![image 1](https://user-images.githubusercontent.com/10508276/47533121-84c95280-d880-11e8-8c37-03d5295a5fa0.png)

It ends with these messages:
![image 2](https://user-images.githubusercontent.com/10508276/47533134-94e13200-d880-11e8-9b15-f4c5de4d7d0e.png)

**Comment by adamabeshouse** [comment]
@tmazor can we close this? have you seen this issue recently?

**Comment by tmazor** [comment]
No, I haven't seen this since reporting it. I think we can close this.
