### ISSUE TITLE
SPA: cancer types summary extends beyond width of the page

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5115]
In a very wide cancer types summary plot, the plot extends past the width of the screen. In a query that also has many genes, this means the gene list also extends past the width of the screen and some gene names are hidden unless you scroll.

The plot should scroll if it is wider than the current screen width, like in the current production implementation.

![image](https://user-images.githubusercontent.com/10508276/47533506-f786fd80-d881-11e8-95c0-ad4bc96d24a9.png)

http://www.cbioportal.org/beta/results/cancerTypesSummary?session_id=5bd240d0498eb8b3d5688318

**Comment by jjgao** [comment]
Not sure if this is a bug or feature since we are now using the full screen. 

It's definitely a problem that the gene list extends past the screen. @alisman is there a way to address that?

**Comment by alisman** [comment]
yes, we have a way of addressing this but it involves horizontal scrolling

**Comment by tmazor** [comment]
This also leads to the the header content extending off the page:
![image](https://user-images.githubusercontent.com/10508276/48803455-fb226e80-ecdf-11e8-8661-9666f23b44dc.png)
