### ISSUE TITLE
study view permanently converts gene names in query box to "AND xx MORE"

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5116]
I know this was reported before but I thought it had been fixed? I can't find the issue. In any case - the query box permanently encodes " AND x MORE" as genes and then the query can't be run (or if you time it right, you can run the query and get the funny oncoprint below) 

![image](https://user-images.githubusercontent.com/10508276/47534049-edfe9500-d883-11e8-807c-9109805da56e.png)

![image](https://user-images.githubusercontent.com/10508276/47534012-d8896b00-d883-11e8-8877-ceabaa9ebe2a.png)

This seems to happen reproducibly if I type some of the gene names, but not if I only click on the gene names from the mutations/cna tables.

**Comment by jjgao** [comment]
@Tamba32 since this will be fixed in the new study view (we'll use the same component as in the query page) and this issue does not happen often, I think we should just wait for 1.19 (hopefully very soon).

**Comment by alisman** [comment]
@jjgao does this still happen in new study view?

**Comment by jjgao** [comment]
I don't think so. Closing now.
