### ISSUE TITLE
footer tweaks

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5117]
- add version number under the logo
- move API Docs under INFO

![image](https://user-images.githubusercontent.com/840895/47570845-22fefc00-d905-11e8-82e0-ff1586e4663f.png)

cc'ing @schultzn

**Comment by inodb** [comment]
@jjgao 	@schultzn 	specifying a version has become a little more complex, so Im not sure how useful it is to the user without knowing the details. We have both backend and frontend version. They don't always have an official tag

We could do e.g. this to show all the details

1.
![screen shot 2018-10-26 at 10 20 12 am](https://user-images.githubusercontent.com/1334004/47572452-fea51e80-d908-11e8-93f0-0cef4dc14597.png)

or

2.
![screen shot 2018-10-26 at 10 29 15 am](https://user-images.githubusercontent.com/1334004/47572883-0913e800-d90a-11e8-9fa1-dbada3b7a220.png)


Or keep it as it was and only list the backend pom version as we currently do with v1.17.1 and v1.17.1-SNAPSHOT

3.
![screen shot 2018-10-26 at 10 30 23 am](https://user-images.githubusercontent.com/1334004/47572960-319be200-d90a-11e8-8a32-5bfb2ca56058.png)

4.
Or list api and UI, but when u click on it actually takes you to the right commit on github
![screen shot 2018-10-26 at 10 33 28 am](https://user-images.githubusercontent.com/1334004/47573175-a7a04900-d90a-11e8-9545-280b4c55c7c2.png)



For developers we already know that we should go to to www.cbioportal.org/api/info to get the backend version and check `window.FRONTEND_COMMIT` to see frontend version.

**Comment by schultzn** [comment]
Thanks. Less is more, as it is easier to parse by our users. So just the simple version number might be best. Do we have to show the “snapshot” string?

**Comment by inodb** [comment]
@schultzn `-SNAPSHOT` is not necessary, will remove that

**Comment by jjgao** [comment]
@inodb is it possible to add the date of release?

**Comment by inodb** [comment]
@jjgao 	i can prolly add the date of the commit (frontend/backend or both, what do you think?). Or the `app.version` from maven. That's the time of the build.

**Comment by jjgao** [comment]
@inodb maybe the latest of frontend/backend?
