### ISSUE TITLE
Query produces 400 error

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#5121]
http://www.cbioportal.org/beta/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=cellline_nci60%2Cacc_tcga_pan_can_atlas_2018%2Campca_bcm_2016&case_set_id=w_cna&data_priority=0&gene_list=TP53%2520MDM2%2520MDM4%2520CDKN2A%2520CDKN2B%2520TP53BP1&geneset_list=%20&tab_index=tab_visualize&show_samples=false&clinicallist=CANCER_STUDY%2CPROFILED_IN_MUTATION_EXTENDED

**Comment by jjgao** [comment]
Strange.. Why do we have this error. The page seems working.

**Comment by alisman** [comment]
@jjgao This query is has case set category (cases with cna) set.  One of the studies does not have a corresponding sample list for that category.  We aren't handling this condition well so we end up submitting a call to mutations with zero samples.  That produces this 400.  But because there can be no mutations for no samples, the results are not affected.  I will correct this so that no call is made when there are no samples.

**Comment by alisman** [comment]
FYI, it's actually a 400 error (bad request) not a 404 as I have in title.
