### ISSUE TITLE
Mutation Count vs. CNA plot never finishes loading

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#5123]
The plot seems to get stuck at 90%.  IHere is an example with [acc_tcga](https://cbioportal.mskcc.org/study?id=acc_tcga#summary), but I've seen it with other cohorts too.

![image](https://user-images.githubusercontent.com/366003/47588573-9c621300-d934-11e8-96dc-77e7961bc6d2.png)

**Comment by jjgao** [comment]
I couldn't reproduce it now. Since we are working on the new study view, let's test it in the new page.
