### ISSUE TITLE
Missing release Notes link on News Page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5127]
Used to be in top right corner:
![screen shot 2018-10-26 at 6 09 17 pm](https://user-images.githubusercontent.com/1334004/47594656-5d3ebc80-d94a-11e8-8b07-ed0f41c5f024.png)

https://github.com/cBioPortal/cbioportal/releases

**Comment by alisman** [comment]
@Luke-Sikina please add link to release notes on news page.  On News.tsx, you'll see we just render a <StaticContent> component which pulls in news markdown from remote source.  You can Just insert the link above it and us some css hackery to put it in top right, inline with the page title (News)
