### ISSUE TITLE
Network tab: issue with download

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5130]
reported by [a user](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/Uzsh98OgAOU/8ulLDnrIAAAJ)

"When I select GraphML or SIF for  downloading, I obtain this message: 
```
<!--messages begin:
Error loading network. Please report this to <span class="mailme" title="Contact us">cbioportal at googlegroups dot com</span>!
java.lang.NullPointerException
messages end-->
<graphml></graphml>
```
"

http://www.cbioportal.org/index.do?session_id=5bd305a5498eb8b3d56884f7&show_samples=false&clinicallist=PROFILED_IN_ucec_tcga_pan_can_atlas_2018_mrna_U133_Zscores

**Comment by jjgao** [comment]
@alisman I see. We can fix the backend link. Mabye @onursumer can help?

**Comment by alisman** [comment]
@jjgao I actually don't think it can be handled in backend because it needs to initiate a post (not a GET) to handle custom case lists.    So, really need to be done on frontend.   Not too nasty.

**Comment by jjgao** [comment]
@alisman oh, I see. Please make change in the frontend then.
