### ISSUE TITLE
Support driver in OQL 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5136]
e.g. `EGFR: driver`

- [ ] support driver in oql
- [ ] oql documentaiton

**Comment by adamabeshouse** [comment]
how does this work - this matches all drivers? or would it combine w other mutation modifiers, like missense

**Comment by jjgao** [comment]
Good question. Thoughts, @schultzn @tmazor ?

**Comment by jjgao** [comment]
@adamabeshouse 

since everything in the OQL is OR logic. Maybe we should do that too? ie.  `MISSENSE DRIVER` means union of missense and drivers of any type.

I remember you have implemented AND/OR logic. What would it look like if we use that? 

Can we also apply drivers to CNA and fusions?

**Comment by adamabeshouse** [comment]
i did implement AND/OR but that was a while ago I think it may be in old project. I can try to track it down.

An idea I just thought of is to use . to chain together, its more readable than the words "AND" and "OR". So it could be like

EGFR: MISSENSE.DRIVER INFRAME.GERMLINE which would get driver missense and germline frame mutations. or MISSENSE.DRIVER.GERMLINE. what do you think?

**Comment by jjgao** [comment]
@adamabeshouse I think it's a great idea! 

@tmazor @schultzn what do you think?

**Comment by schultzn** [comment]
I like the idea!

**Comment by jjgao** [comment]
@tmazor Good point -- not sure what's the best option here.

Maybe it's OK to allow the user to define them after the query is submitted? We should remember the "driver" sources in the query state @adamabeshouse. 

We are thinking about adding a global (instead of oncoprint-specific) setting for results page to set "driver" sources.

**Comment by adamabeshouse** [comment]
ill start with this one https://github.com/cBioPortal/cbioportal/issues/5137 bc it will establish a lot of the related code while avoiding the issue of defining drivers, so we can have some time to talk about that
