### ISSUE TITLE
query from filtered study view doesn't work properly

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5140]
If I'm on study view and filter down to a subset of samples and then submit the query (example: go to MSK-IMPACT study page, select NSCLC, then run query for EGFR) - the results view loads with only mutation data and no copy number data. If I then click on Modify Query, I see this:
![image](https://user-images.githubusercontent.com/10508276/47680458-3926e980-db9d-11e8-9b70-9588a8a622fa.png)

I can check off "copy number" and re-submit but nothing happens. Also note that the sample list is essentially blank, but it should be the custom sample list from study view.

**Comment by zhx828** [comment]
@jjgao study view only uses gistic profile to query CNA data. But seems like MSK IMPACT study does not have gistic profile anymore.

**Comment by ritikakundra** [comment]
@zhx828 This cohort never had a gistic file, only data_CNA.txt, and segment file

**Comment by zhx828** [comment]
@ritikakundra thanks for the confirmation.

**Comment by alisman** [comment]
@tali @jjgao I just deployed fix for retaining the custom case list id when user click modify query.

**Comment by alisman** [comment]
@tmazor yes, we're still figuring that out.  will be fixed today

**Comment by alisman** [comment]
@tmazor @jjgao this bug should now be fixed.

**Comment by tmazor** [comment]
looks good to me!
