### ISSUE TITLE
Temporarily hidden tabs conundrum

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#5150]
If you go to following link (coexpression tab), you will first see oncoprint tab selected (and rendering).  Soon after that, it switches to coexpression tab (targetted in url).  Oncoprint is loaded/rendered even though hidden.  I assume this is because we don't yet know whether to show coexpression tab and it isn't in collection, so we default to oncoprint.    Maybe solution for this would be, we always show a tab if we are routed to it, even if it's hidden condition is met.  

I don't think this is a super urgent/serious issue and we shouldn't complicate thing too much.  Let me know your thoughts.

http://www.cbioportal.org/results/coexpression?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_ids=&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations

**Comment by adamabeshouse** [comment]
ohhh interesting. right, so right now, I have it that if the info to determine whether to hide the tab isn't loaded yet, then it defaults to hidden. seems like if we just by default show, until we determine it needs to be hidden, it would fix this issue. or maybe thats confusing UX and we should show the tab no matter what if its in the route?

**Comment by jjgao** [comment]
"we always show a tab if we are routed to it, even if it's hidden condition is met." That makes sense.

**Comment by alisman** [comment]
yeah, i don't think we show it if it's pending.  we hide it while pending UNLESS it's routed

**Comment by jjgao** [comment]
sounds good. We may need to add some error message just in case a tab is routed and there is no data.
