### ISSUE TITLE
FACETS integration

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5158]
We should document the FACETS field. https://github.com/cBioPortal/cbioportal/pull/5152/files    

Variable | sample attribute | mutation attribute | Meaning
-- | -- | -- | --
dipLogR | ? | ? | ?
cellularFraction | n | y | fraction of cell that carry the mutation?
totalCopyNumber | n | y | total CN of the gene
minorCopyNumber | n | y | CN of the minor allele
cellularFractionEm |   |   | ?
totalCopyNumberEm |   |   | ?
minorCopyNumberEm |   |   | ?
purity | y | n | sample purity
ploidy |   |   | ?
ccfMCopies |   |   |  
ccfMCopiesLower |   |   |  
ccfMCopiesUpper |   |   |  
ccfMCopiesProb95 |   |   |  
ccfMCopiesProb90 |   |   |  
ccfMCopiesEm |   |   |  
ccfMCopiesLowerEm |   |   |  
ccfMCopiesUpperEm |   |   |  
ccfMCopiesProb95Em |   |   |  
ccfMCopiesProb90Em |   |   |  

cc'ing @schultzn @ersinciftci

**Comment by sheridancbio** [comment]
@jjgao We have recently added code to allow fields in the MAF in the form "namespae_id:attribute_id" and we document the following ASCN fields briefly here:
https://github.com/cBioPortal/cbioportal/blob/rc/docs/File-Formats.md

42. **ASCN.ASCN_METHOD (Optional)**: Method used to obtain ASCN data e.g "FACETS"
43. **ASCN.CCF_M_COPIES (Optional)**: Cancer-cell fraction if mutation exists on major allele.
44. **ASCN.CCF_M_COPIES_UPPER (Optional)**: Upper error for CCF estimate.
45. **ASCN.MUTANT_COPIES (Optional)**:i Estimated number of copies harboring mutant allele.
46. **ASCN.CLONAL (Optional)**: "True" or "False" whether mutation is clonal.
47. **ASCN.TOTAL_COPY_NUMBER (Optional)**: Total copy number of the gene
48. **ASCN.MINOR_COPY_NUMBER (Optional)**: Copy number of the minor allele
49. **ASCN.ASCN_INTEGER_COPY_NUMER (Optional)**: Absolute integer copy-number estimate.

Does this seem adequate to close this issue? (we see that formatting needs to be smoothed out)
