### ISSUE TITLE
oncokb calls are slow for large query

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5167]
For example, loading oncokb annotation took 2 minutes consistently (even after reloading a few times).

http://www.cbioportal.org/results?session_id=5bda5a3d498eb8b3d56897d2

There might be room to improve on the oncokb api side, but it may make sense to cache the genomic-level annotation in genome nexus.

**Comment by zhx828** [comment]
For things need to do:
- [ ] For oncoprint, we should only get Oncogenic evidence
- [ ] For mutations tab, we should fetch oncokb service by gene, not all genes together in one call
- [ ] OncoKB performance improvement

**Comment by jjgao** [comment]
> For mutations tab, we should fetch oncokb service by gene, not all genes together in one call

@zhx828 @onursumer: how hard is it to do the above?

**Comment by zhx828** [comment]
@jjgao Onur and I haven't really done any further analysis whether it requires extensive work. But as far as we know, it can be done now since the oncoprint is using a separate store. It's not really a priority yet, but probably better do it before implementing the Dx/Px.

**Comment by onursumer** [comment]
For some reason we still keep `oncoKbData` in `ResultsViewPageStore` and `MutationMapperToolStore`. Moving it under `MutationMapperStore` should improve the performance.
