### ISSUE TITLE
Exception in the result's page

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5168]
This error happens pretty randomly. I was tracing why one of the e2e tests randomly failed in my PR. Does this ring any bell? 

The test is to https://cbioportal.mskcc.org/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=msk_impact_2017_cnaseq&gene_list=AKR1C1%2520AKR1C2%2520AKR1C4&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna

Then page redirects to https://cbioportal.mskcc.org/results?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=msk_impact_2017_cnaseq&gene_list=AKR1C1%252520AKR1C2%252520AKR1C4&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna

![screen shot 2018-11-01 at 9 53 19 am](https://user-images.githubusercontent.com/5400599/47855913-3229f200-ddbc-11e8-8193-c9bf26706b7a.png)

**Comment by adamabeshouse** [comment]
looks like an error with URI encoding

**Comment by adamabeshouse** [comment]
does the e2e test use a hardcoded URL link? which one is it?

**Comment by zhx828** [comment]
@adamabeshouse   this one 
```
The test is to https://cbioportal.mskcc.org/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=msk_impact_2017_cnaseq&gene_list=AKR1C1%2520AKR1C2%2520AKR1C4&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna

**Comment by alisman** [comment]
@adamabeshouse it's an oql parser issue. you can see some detail in this screenshot

![image](https://user-images.githubusercontent.com/186521/47878487-c87a0a00-ddf4-11e8-972d-1a429f99e250.png)

**Comment by adamabeshouse** [comment]
@alisman @zhx828 if you copy a link from webstorm, it URL encodes it more than what is actually in the e2e test. you have to right click on the selection and click "copy as plain text" to avoid this

this is basically a case of malformed URL created by user error/modification, so I don't think we need to handle it. although we could handle this particular error heuristically just by iterating URIDecode until there are no percent signs in the OQL. @alisman what do you think we should do?

**Comment by alisman** [comment]
I don't think we need to address this
