### ISSUE TITLE
Clean up database schema

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#517]
- [x] change patient_list to sample_list
 - [x] change patient_list_list to sample_list_list
 - [x] fix Java code naming
 - [x] remove micro_rna and micro_rna_alteration
 - [x] remove mutation_frequency
 - [x] change field name within patient_list_list
 - [x] create version table in database
 - [x] migration script - account for versioning
 - [x] seed database
 - [ ] ER diagram for documentation

**Comment by jjgao** [comment]
@zheins let's try to finish it.

**Comment by morungos** [comment]
Might be worth looking at sqitch: https://github.com/theory/sqitch (although it's Perl so you'll probably all hate it)

**Comment by pieterlukasse** [comment]
@jjgao : I would love to review this

**Comment by zheins** [comment]
PR #700 addresses some of the immediate concerns. We have it merged in our development environment.

Aside from changing some of the names of classes and db tables to be consistent with our naming conventions, there is a python script which takes a sql script as input to update the database. The script is executed based on the version found in stored in an information table and the version assigned to the statements.

```sql
##version: 1.0.0
CREATE TABLE info (DB_SCHEMA_VERSION VARCHAR(8));
INSERT INTO info VALUES ("1.0.0");

##version: 1.1.0
CREATE TABLE sample_list LIKE patient_list;
INSERT sample_list SELECT * FROM patient_list;
...
```

**Comment by jjgao** [comment]
@pieterlukasse: sure, please review #700. No need to ask :) Thanks.

**Comment by pieterlukasse** [comment]
@zheins regarding the seed DB (in https://github.com/cBioPortal/cbioportal/wiki/Import-the-Seed-Database) can you please let me know where I can find the respective test seed DB file so that I can review this as well?

**Comment by jjgao** [comment]
I am closing this one. Please log remaining issues in another one.

**Comment by pieterlukasse** [comment]
@jjgao : Ok, I moved the diagram part to #1041
