### ISSUE TITLE
Civic api does not accept gene names with / or . chars in them (404s)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#5172]
https://civicdb.org/api/genes/MIR4469,MIR548O2,MIR4519,MIR3975,MIR4637,MIR3974,MIR4529,MIR4758,MIR4659A,MIR4660,MIR4532,MIR3591,MIR4533,MIR4743,MIR4659B,MIR4744,MIR5095,LINC00659,PYCARD-AS1,DSG2-AS1,GS1-24F4.2,PCAT1,MIR5583-2,MIR5011,MIR5583-1,MIR5194,NRG1-IT1,TMEM265,RNU6-78P,LZTS1-AS1,DENND5B-AS1,NRG1-IT3,LINC-ROR,LINC01544,OVCH1-AS1,LINC01910,LINC00681,OGFR-AS1,CCAT2,PRNCR1,LINC01929,LINC01416,LOC101927322,LINC01927,DSCAS,LINC01029,DSG1-AS1,LINC01477,LINC01478,LOC101928048,LAMA5-AS1,LINC01917,ARNTL2-AS1,LOC101929172,LINC02149,CTD-2350J17.1,LINC02150,LOC101929524,LINC01726,LINC01727,MIR6841,MIR6842,MIR6843,MIR6876,MIR7160,MIR486-2,MIR8055,MIR8057,MIR8078,LOC102723376,BMP7-AS1,LINC01919?identifier_type=entrez_symbol

**Comment by alisman** [comment]
@jjgao whenever we submit a gene with . or / we get a 404 and what's worse, their 404 does't have CORS headers on it, so we can't really catch the failure.  What should we do?   Strip out offending gene names?

**Comment by jjgao** [comment]
@alisman as discussed, let's switch to entrez_gene_id. https://github.com/cBioPortal/cbioportal/issues/3153
