### ISSUE TITLE
virtual study is not selected when clicking query after a VS is created

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5179]
![image](https://user-images.githubusercontent.com/840895/47935341-6d0d5200-deb0-11e8-971c-3cb22c7401d4.png)

somehow for virtual study the url is as follows:

http://www.cbioportal.org/?cancer_study_id=5bdc9f43498eb8b3d5689cc9

**Comment by dippindots** [comment]
@jjgao Just want to confirm what do we want. When we click the "query" button, the page will redirect to the home page, and the visual study will be selected. And about the URL, do we want to keep it as "http://www.cbioportal.org/?cancer_study_id=5bdc9f43498eb8b3d5689cc9" or just "http://www.cbioportal.org/"?

**Comment by jjgao** [comment]
just http://www.cbioportal.org is fine.

**Comment by dippindots** [comment]
@jjgao Ok thanks! Will do.

**Comment by kalletlak** [comment]
@jjgao @alisman should we just do https://www.cbioportal.org/results?cancer_study_id=5bdc9f43498eb8b3d5689cc9

**Comment by alisman** [comment]
@kalletlak that one shows the list of sample ids and selected physical studies but i think what we want is to have the actual virtual study selected.

**Comment by kalletlak** [comment]
@alisman if its a shared virtual study then physical studies would be selected. if its a saved virtual study then actual virtual study would be selected
