### ISSUE TITLE
no warning message when opening a link to a sample that does not exist 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5182]
http://www.cbioportal.org/patient?studyId=ucec_tcga_pub&caseId=not-a-sample

**Comment by AndrewCveklNYUClass** [comment]
Hey JJ, when I click on the link, is the bug that the load icon keeps going and nothing shows up?

**Comment by jjgao** [comment]
@AndrewCveklNYUClass yes. There should be message to indicate the study and/or sample do not exist or are not accessible by the user.

**Comment by ZakiaSalod** [comment]
Hi there,
Is this item still available to be worked on?
Or, is any of you currently working on it? Kindly let me know. Thanks.

**Comment by alisman** [comment]
@ZakiaSalod you would we welcome to try to fix this. thanks

**Comment by alisman** [comment]
duplicate #5357
