### ISSUE TITLE
# of cases not shown in query summary line

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5184]
http://www.cbioportal.org/results?Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=coadread_tcga_pub_3way_complete&gene_list=KRAS%2520NRAS%2520BRAF&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&cancer_study_list=coadread_tcga_pub

![image](https://user-images.githubusercontent.com/11892704/48020993-5f043f00-e105-11e8-85b8-c2596047bef7.png)

**Comment by jjgao** [comment]
This will be fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/1667

**Comment by alisman** [comment]
Duplicate. Fixed
