### ISSUE TITLE
study view density plot: can we  remove the ~ sign when there is only 1 sample

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5194]
requested by @schultzn https://github.com/cBioPortal/cbioportal/issues/4835

@adamabeshouse @zhx828 I guess it may not be that easy since we are not loading sample level data for the plot. (do we even have the sample IDs in this plot or do we have to query?)

![image](https://user-images.githubusercontent.com/840895/48073903-b4942680-e1ad-11e8-80ba-2b1729d0ab1b.png)

**Comment by schultzn** [comment]
Wouldn’t it be as simple as: IF COUNT = 1, do not display “~”?

**Comment by jjgao** [comment]
@schultzn The number would not be correct by just removing ~ b/c this is a binned plot. For example, the actually values for the sample above are 198 mutations and 0.145 FGA.

**Comment by jjgao** [comment]
This can be confusing. Maybe we should display the range too? We can ask the backend API to return the `max` and `min` and display them. If a dot has only one sample, then `max=min` and we can display the exact value.

**Comment by schultzn** [comment]
What would happen in studies with just a few samples? Shouldn’t we be able to show the exact values there?

**Comment by adamabeshouse** [comment]
@schultzn we still need the additional info @jjgao mentioned - the API sends back the bin coordinates, which are related to the endpoints of the data range, not related to the contents of the bin.

**Comment by schultzn** [comment]
Ok, I understand. I didn’t anticipate that this would be a problem. 
Ok to leave as is then.

Two other quick suggestions on fixes:
1 - tooltip cut off if a point is too far to the right
2 - after selecting samples, can the other ones still be shown but greyed out?

**Comment by adamabeshouse** [comment]
@schultzn remember that the dots in the plot are bins, not individual samples. so what do you mean by still having them there - have grayed out bins where any dots are? also, we are zooming the y axis (mutation count) according to the new domain - would we not zoom in this case?

**Comment by schultzn** [comment]
Something like this? In this example, the samples near the top are selected, the rest are not.

**Comment by adamabeshouse** [comment]
@schultzn image wasnt attached

**Comment by schultzn** [comment]
![image](https://user-images.githubusercontent.com/11892704/48099853-00b38b00-e1ef-11e8-8d09-ed4b79e335c7.png)

**Comment by adamabeshouse** [comment]
did you do that by hand??? yeah that looks nice. I spoke to @jjgao and it'll mainly take some API changes

**Comment by jjgao** [comment]
@adamabeshouse We only need to display the gray ones if we are using the density plot for selection, similar to barchart.

@ersinciftci would you please modify the API to support features above?

- [ ] add unselected dots to the output
- [ ] add min and max values (the actual values in sample) to the output

**Comment by schultzn** [comment]
Photoshop… not all that well done - as you can see I also made the grid disappear.

**Comment by ersinciftci** [comment]
@jjgao if we are going to keep the unselecred dots, it means the frontend will call the API just once at the first load, then no need to call the API again, since we are not zooming in based on selection anymore. Basically just like the old Mutation Count vs FGA plot.

I can add min and max to every bin but it sounds like a bit overkill since they will be only useful when min = max. Let's see if we can find a better way after I come back.

**Comment by jjgao** [comment]
@ersinciftci if we use another chart to select samples, we are still going to hide unselected samples. We only show the gray dots that are not selected directly through the density plot. This is very similar to bar charts. 

![image](https://user-images.githubusercontent.com/840895/48108959-8a754f80-e213-11e8-8cc0-3866e2ade59a.png)

**Comment by ersinciftci** [comment]
@jjgao @adamabeshouse If the frontend doesn't send `mutationCountVsCNASelection` field in the filter when calling `/clinical-data-density-plot/fetch`, the unselected bins would still be visible, so I think still no need to change the API for that one.

**Comment by ersinciftci** [comment]
Just for the record, we discussed this during the planning meeting, there was some confusion about how the filter applies to bins, but now on the same page that no API change is needed for showing the unselected bins.

**Comment by ersinciftci** [comment]
@jjgao I just realized that you wanted `min` and `max` values to display them for every bin, not only 1-sample bins. So we will use the bin coordinates only for drawing the chart, and will use min-max values in the tooltip. That sounds good to me, let me see how it affects the performance of the API, shouldn't affect much in terms if big O notation.

**Comment by ersinciftci** [comment]
Merged the PR, so the new bin object looks like:
```
[
  {
    "binX": 0,
    "binY": 0,
    "count": 0,
    "maxX": 0,
    "maxY": 0,
    "minX": 0,
    "minY": 0
  }
]
```
max-min fields won't be present if the count is 0.

**Comment by jjgao** [comment]
@adamabeshouse let's use one color for gray.

**Comment by adamabeshouse** [comment]
@jjgao ah okay
