### ISSUE TITLE
support dragging in bar chart

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5201]
We used to support dragging in barchart in [study view](https://www.cbioportal.org/study?id=msk_impact_2017). It'd be nice to get it back. 

Similar to what [DC](https://dc-js.github.io/dc.js/) supports:

![img](https://media.giphy.com/media/1wr0ZRz9aJ4c3xCA5k/giphy.gif)

@schultzn this may not be easy to implement so we are not prioritizing it for now unless you think it's necessary.

**Comment by coderrsid** [comment]
@jjgao Can i get more description on this?

**Comment by jjgao** [comment]
@coderrsid I have updated the description. I labeled this one as `good first issue` somehow, but it may be a hard one to solve. Please feel free to give a try if you like.
