### ISSUE TITLE
tooltip on oncokb logo in oncoprint should be words, not code

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5209]
Let's make the OncoKB tooltip more like the Cancer Hotspots tooltip:

![image](https://user-images.githubusercontent.com/10508276/48140785-7ebb7480-e277-11e8-992f-dc6b8683f3d8.png)

![image](https://user-images.githubusercontent.com/10508276/48140741-63e90000-e277-11e8-85ac-35ad36319c66.png)

http://www.cbioportal.org/results?session_id=5be30401e4b0f26b31591203

**Comment by adamabeshouse** [comment]
oops, that is a bug in the string building
