### ISSUE TITLE
show status of progress in results tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5210]
e.g.

- Loading genomic data
- Annotating with OncoKB and Cancer Hotspots
- Rendering

**Comment by adamabeshouse** [comment]
just in oncoprint?

**Comment by jjgao** [comment]
@adamabeshouse I think we should show it in all tabs, but we can start with oncoprint since it's usually the first one.

**Comment by adamabeshouse** [comment]
@jjgao got it

**Comment by adamabeshouse** [comment]
@jjgao what should we show if oncokb/hotspots turned off?

**Comment by alisman** [comment]
@adamabeshouse I have a PR with messaging option in LoadingIndicator.

**Comment by jjgao** [comment]
@adamabeshouse @alisman The status bar in OncoPrint looks great! Can we generalize it and put it in all tabs?

- [ ] change "Loading genomic data" to "Loading data" (since we use the same message when we have clinical data too)
- [ ] adding one more line before "Loading data": "Querying xxx samples for xx genes"
- [ ] When the query is big (e.g. #genes x #samples > 10k), show something like (above "Loading data"): "This is a large query. It may take some time. Please hang on..." @tmazor @schultzn please help me with the language.

![image](https://user-images.githubusercontent.com/840895/48857252-6cb4f800-ed86-11e8-9ba3-d845933d3d70.png)

**Comment by adamabeshouse** [comment]
What about "Loading genomic and clinical data"? I think its more satisfying to see more specifically what's happening.

I don't get the difference between Loading data and Querying

**Comment by schultzn** [comment]
+1 on loading genomic and clinical data

The idea about the “querying” line is to indicate to the user how large the query is (number of samples x number of genes). We would like to to use this to give the user an idea of how long it could take.

We could have:

Querying 3 genes in 27 samples - this should be quick
Querying 30 genes in 2700 samples - this might take a minute
And so forth … not sure what the right messages and thresholds would be.

**Comment by adamabeshouse** [comment]
Oh i see, so it's like an info message, it's not a loading item like the others.

**Comment by jjgao** [comment]
@adamabeshouse that's right.
