### ISSUE TITLE
oncoprint seems to wait for genome nexus annotations

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5211]
There was a brief down time for genome nexus this morning, the oncoprint didn't render. Would be good to still render oncoprint when there's an error with the genome nexus or oncokb service

**Comment by jjgao** [comment]
@inodb I think that's a good idea.

**Comment by jjgao** [comment]
Same with OncoKB.

**Comment by adamabeshouse** [comment]
we are already doing it for oncokb but I forgot to add this ability when we switched to using genome nexus for hotspots :+1:

**Comment by alisman** [comment]
@inodb can you verify and close?
