### ISSUE TITLE
Adding OncoKB and CancerHotspots annotation into cBioPortal database

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5213]
We would like to do this for two reasons:

1. OncoKB and CancerHotspots annotation has become a bottleneck when loading oncoprint for big queries #5167
2. Supporting OncoKB analysis in study view #5212

A high-level to-do list:
- [ ] extend database scheme to add OncoKB and CancerHotspots annotation
- [ ] change import pipeline to add annotation
- [ ] set up a process and scripts to update annotation when there is new OncoKB or CancerHotspots releases
  - the scripts could be used for importing too
- [ ] documentation of the process so that others can use it
- [ ] modify frontend code 

Questions:
- What data to add?
  - To address # 1, we could add information about whether an alteration is Oncogenic or a hotspot into our database.
  - For # 2, we may need additional information such as oncokb levels. (would on-the-fly loading of levels for oncogenic events fast enough? If so, maybe we don't have to save them in cBioPortal?)
- Where to add annotation?
  - For mutations, we could add it to either `mutation_event` or `mutation` table
    - note: level data has to add to `mutation` table since it's cancer type specific
  - For CNAs, cna_event?
  - How about fusions? Currently we are modeled as mutations but we will separate them into the `structural_variant` table.
  - Or should we separate them and have a `variant_annotation` table? Maybe cleaner?
  - Should we consider re-using the `DRIVER_FILTER/TIERS` columns?

cc'ing @pieterlukasse @schultzn

**Comment by zhx828** [comment]
I think we like to keep this open.

**Comment by jjgao** [comment]
This is being implemented based on [RFC56](https://docs.google.com/document/d/1TLRIOurdRK1HE7nDPqk6d4zhfjpgchBd9tU6PQpbwxw/edit).
