### ISSUE TITLE
bad links in documentation

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5214]
The "Import Gene Panels" page has links to other pages within the documentation, but those links are wrong.

Go here: https://cbioportal.readthedocs.io/en/latest/Import-Gene-Panels.html
Click on "File Format" under #2.
It brings you to: https://cbioportal.readthedocs.io/File-Formats.html#gene-panel-data
But the correct link is: https://cbioportal.readthedocs.io/en/latest/File-Formats.html#gene-panel-data

"Loading a Sample Study" under #3 has the same issue.

**Comment by inodb** [comment]
Seems to be a known issue with the docs parser: https://github.com/rtfd/recommonmark/issues/8 . Looks like someone wrote a hacky fix, might be worth trying.

**Comment by inodb** [comment]
moved to gitbook instead
