### ISSUE TITLE
CN Segments tab on study view page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5221]
View segments data in study view could be useful. Once we finish #4670 and #4410, it should be easy to do it with igv.js.

One difference on the study view is that we may want to update the sample list based on selection.

@onursumer it would be good to keep this in mind when you develop the component.

![image](https://user-images.githubusercontent.com/840895/42052201-1870ab6c-7adc-11e8-9ec9-7dbdcb8e1e6c.png)

cc'ing @cBioPortal/product

**Comment by schultzn** [comment]
Agree, that would be nice. The sample list should be synchronized with the selections made on the main study view page.
