### ISSUE TITLE
OncoPrint: zoomed out->multiple samples in one pixel->show all in tooltip

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5226]
When zooming out and having multiple samples in one pixel, it seems that we only able to display one sample in the tooltip. 

Should we display all samples here or maybe just display the number of samples instead?

@adamabeshouse it's not a priority. Let me know if it's a hard issue.

cc'ing @cBioPortal/product

**Comment by adamabeshouse** [comment]
Im not sure if number of samples would be very useful, because it would be the same number of samples for every pixel, theres no density difference. But showing all the samples in the tooltip maybe? I dont think it would be too much work.

**Comment by jjgao** [comment]
@adamabeshouse let's show all samples then.

**Comment by adamabeshouse** [comment]
I implemented it but I'm not sure it looks very good..

![image](https://user-images.githubusercontent.com/636232/51268956-3ca56200-198f-11e9-916e-3c22b54f367a.png)

**Comment by jjgao** [comment]
@adamabeshouse maybe we can combine them? e.g.

Mutation: KRAS G12D (xx samples), KRAS G12E (xx samples)
Gene Panels: IMPACT410 (xx samples), IMPACT467 (xx samples)
View these patient [link to patient view page with navIds]
