### ISSUE TITLE
Merge tool should copy MAFs to dest not merge MAFs

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#524]
When studies A and B are merged, respective MAFs should be copied over to dest directory, not merged.  Any annotations (VEP) should be stripped from sources MAFs to ensure both files are re-annotated using same version of annotation tool.

**Comment by zheins** [comment]
Just to be clear, when handling MAFs from two studies, no merge file should be generated and only the originals stripped of VEP annotations should be copied to the destination director. Is this correct?

**Comment by n1zea144** [comment]
Yes, correct.  Moving issue to pipelines tracker.
