### ISSUE TITLE
making it obvious that a gene can be selected on study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5241]
Chris suggested that the current functionality of selecting a gene is not obvious. Maybe we can change the text in the gene input box and also add an info icon in the header of gene column. We could also add a selection icon before the gene symbol (if we can find a good icon).

**Comment by zhx828** [comment]
This is solved in https://github.com/cBioPortal/cbioportal-frontend/pull/1824/files
