### ISSUE TITLE
Co-exp & Enrichments: move the Data Set dropdown

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5257]
Can we move the Data Set drop down under the gene tabs? Maybe above the scatter plot section?

Similarly for Enrichments, move it above the table on the right side.

Can we also change "Data Set" to "Profile"?

![image](https://user-images.githubusercontent.com/840895/48582263-05b0c280-e8f2-11e8-9f57-7b88bce700bd.png)

![image](https://user-images.githubusercontent.com/840895/48582400-6b9d4a00-e8f2-11e8-9874-3edebaa1c123.png)

http://bit.ly/2TfYXwO

**Comment by alisman** [comment]
@jjgao 
In coexpression tab, the Profile dropdown is now "sticky."   As is the show mutations checkbox.  Stays the same as you switch genes.  But the correlation chooser is not.  Is this desirable?


http://cbioportal-frontend-pr-1747.herokuapp.com/results/coexpression?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_ids=&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations

**Comment by jjgao** [comment]
@alisman yes, that's desirable.
