### ISSUE TITLE
Bookmark, Twitter and email links very slow

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5267]
It takes a good 10-30 seconds for the bookmark, email and Twitter links to result in the desired action after the click, at least in my Chrome browser.

**Comment by jjgao** [comment]
The session service seems very slow at the moment.

**Comment by jjgao** [comment]
@inodb I remember we had a checksum in the json. Maybe we can use that to query. If we worry about checksum collision, we can then compare the json once it's loaded out.

**Comment by inodb** [comment]
@jjgao 	there is a unique constraint on source,type and checksum so querying by those now: https://github.com/cBioPortal/session-service/pull/18
