### ISSUE TITLE
Missing clinical tracks in Study Summary

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#5269]
When I query BRCA TCGA (Prov) I can only add 31 out of 112 clinical profiles to the study summary page.

### Study Summary of brca_tcga
![screenshot 2018-11-19 at 12 39 58](https://user-images.githubusercontent.com/9624990/48706872-d950bb00-ebfd-11e8-841f-7b6a585b7a33.png)

### OncoPrint of brca_tcga
![screenshot 2018-11-19 at 12 40 26](https://user-images.githubusercontent.com/9624990/48706878-dfdf3280-ebfd-11e8-9281-4924acce51eb.png)

**Comment by zhx828** [comment]
@sandertan this is now fixed.
