### ISSUE TITLE
Decide on system to gather usage statistics

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#527]
It would be nice to decide on a system to gather usage statistics for cBioPortal. This can help simplify some of the UIs. Yesterday we were pointed to this by a big pharma company that already uses cBioPortal for some time now, but thinks the UI is getting overly complicated at some points. They feel we just keep adding tabs for new features without assessing whether some of the existing tabs may also be removed. But we can only do this if we know the usage statistics...

Knowing which parts can be retired is also potentially beneficial for the overall performance improvement efforts (see #475 , #477 )

**Comment by pieterlukasse** [comment]
@ecerami, @schultzn any thoughts on this?

**Comment by ecerami** [comment]
+1 for having a better system for gathering usage stats.  We currently use google analytics for the public site, but this is not good at gathering stats on tabs or what goes on side of tab, etc.  We also can't use google analytics on our DFCI instance, because of "data leakage" to google.  So, would be great to have an internal system that we could use as well.

**Comment by jjgao** [comment]
This is very good point. There was some discuss a while back and we never prioritize it.

You can actually push any events to Google Analytics. 

For example, below is some simple JQuery code that produces Analytics Events on link clicks (from Augustin Luna); it keeps track of the current page URL and the clicked URL. 

```javascript
<script src='http://code.jquery.com/jquery-latest.min.js'
type='text/javascript'></script>
<script type='text/javascript'>
$(function() {
  $("a").on('click',function(e){
    var url = $(this).attr("href");
    console.log('Link: ' + url);
    _gaq.push(['_trackEvent', 'Outbound Links', window.location.href, url, 0]);
  });
});
</script>
```

For the DFCI instance, would it be OK if we only send general information such as which tab is clicked, and which gene is queried, without any patient ID etc. Once we have the session manager service, we don't have to encode patient ID, study ID, etc in the URL.

**Comment by ecerami** [comment]
I don't think we can use google analytics at all.  really hard to prevent data leakage.

**Comment by qwangmsk** [comment]
I am not a Portal developer, but I happen to think about something related to this issue recently. Some Portal users are experts in this field. Their use of the Portal, e.g. which mutation of a patient they choose to click first, on which page they spend most of their time, conveys extremely important information, from which maybe it is doable to infer which piece of data is more relevant than others to a specific tumor/patient. So for usage data, don't limit our use for the purpose of UI only. We should also aim to provide data relevant to future users (properly ordered, highlighted, correlated), through mining of usage information (maybe) to be collected.

**Comment by qwangmsk** [comment]
But probably it is not the right time yet to collect usage information in a comprehensive way. it may be more practical to address the immediate need to improve UI.

**Comment by jjgao** [comment]
We are working on improving the tracking to understand the usage of UI elements.
