### ISSUE TITLE
SV: add commas to number of samples/patients

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5270]
Let's add commas when the number of patients/samples extends to 4 digits

![image](https://user-images.githubusercontent.com/10508276/48717292-178eb000-ebe7-11e8-98ba-313f234fb460.png)

**Comment by zhx828** [comment]
@tmazor should we add for all places in study view, also in the mutated genes/cna genes tables?

**Comment by tmazor** [comment]
yes that would be great @zhx828 !

**Comment by zhx828** [comment]
@tmazor this is now updated. Please let me know if you want to make any adjustment http://www.cbioportal.org/beta/study?id=msk_impact_2017

**Comment by tmazor** [comment]
This looks great! The only other place I'm noticing is the legend on the mutations vs cna density plot - can you also add the comma there?
![image](https://user-images.githubusercontent.com/10508276/48797760-0e7a0d80-ecd1-11e8-8fe0-974f1898099f.png)

**Comment by zhx828** [comment]
@tmazor all done
