### ISSUE TITLE
SV: density plot tooltip updates

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5271]
I think the tooltip will be clearer with the following 2 updates:
1) Change "count" to "number of samples"
2) Show the min/max of # of mutations/fraction altered rather than "~xx"

For example:
Number of samples: 6
Number of mutations: 50-60
Fraction of copy number altered genome: 0.02-0.07

![image](https://user-images.githubusercontent.com/10508276/48717417-5f153c00-ebe7-11e8-9353-b3545df759f5.png)

@schultzn do you like this?

**Comment by schultzn** [comment]
+1
