### ISSUE TITLE
SV: gene names from CNA table show up as entrez gene IDs

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5272]
This is fun - gene symbols sometimes appear as entrez gene IDs when used as a filter. See example below. The first time I select a gene to filter in the CNA table, it appears as an entrez gene ID. If I add a gene from the mutations table, both genes appear as hugo symbols. If I then clear that and select the same CNA gene, it appears as a hugo symbol, but any other gene from the CNA table appears as an entrez gene. If I refresh the page, then this memory is lost and all the genes from the CNA table appear as entrez gene IDs again.

![nov-19-2018 11-00-28](https://user-images.githubusercontent.com/10508276/48719084-a224de80-ebea-11e8-8574-c827959099a5.gif)

**Comment by zhx828** [comment]
@tmazor this is now fixed.
