### ISSUE TITLE
SV: mutsig & gistic labels are offset

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5275]
The "M" for mutsig is a bit low and the "G" for gistic is a bit high. Can they both appear at the same high relative to the text, and ideally at the center of the row?

![image](https://user-images.githubusercontent.com/10508276/48719969-b4a01780-ebec-11e8-83b4-5eb613ceb9bc.png)

**Comment by zhx828** [comment]
@tmazor I tweaked the style a bit. They should look the same and center aligned now. http://www.cbioportal.org/beta/study?id=lgg_tcga

**Comment by tmazor** [comment]
looks good!
