### ISSUE TITLE
SV: mutations & CNA table tooltips

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5277]
Let's have more informative tooltips for these tables:

Gene: Gene
\# Mut: Total number of mutations
#: Number of samples with one or more mutations
Freq: Percentage of samples with one or more mutations

Gene: Gene
Cytoband: Cytoband
CNA: Copy number alteration, only amplifications and deep deletions are shown
#: Number of samples with the listed copy number alteration
Freq: Percentage of samples with the listed copy number alteration

**Comment by zhx828** [comment]
@tmazor this is now updated, just wondering whether we also need some tooltips for the clinical table(after converting pie chart, also the table in the pie chart tooltip)
