### ISSUE TITLE
buttons in study view vs results view

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5284]
Both study view & results view have 3 buttons in the upper right corner of the screen, in the same style. The problem is that these 3 buttons are completely different from each other, and I worry that this will be confusing to users who get used to one set of buttons and then suddenly find a different set of buttons.

I don't have a proposed solution at the moment, but I wanted to raise this issue and see what others think.

@schultzn @jjgao @alisman do you have any thoughts on this?

study view: 
![image](https://user-images.githubusercontent.com/10508276/48723322-4cedca80-ebf4-11e8-8099-6e45e8606b8d.png)

results view:
![image](https://user-images.githubusercontent.com/10508276/48723325-5119e800-ebf4-11e8-94ad-89455175511c.png)

**Comment by zhx828** [comment]
@tmazor  we are planning to add a share button(v1.19.1), not sure this will affect anything.
<img width="1266" alt="screen shot 2018-11-20 at 12 39 31 am" src="https://user-images.githubusercontent.com/5400599/48753670-dd5ff580-ec5c-11e8-9799-4ac1a2a9c4da.png">

And potentially add all these buttons?(Maybe too many)
<img width="1256" alt="screen shot 2018-11-20 at 12 42 43 am" src="https://user-images.githubusercontent.com/5400599/48753767-362f8e00-ec5d-11e8-9608-5d3650f06aca.png">

**Comment by alisman** [comment]
We got rid of the twitter and email buttons.   We will add a link button to the study view which should then "normalize" the button experience.
