### ISSUE TITLE
Node inspector not working in Network view

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#5285]
When you click on a node to show details (alteration values), you get nothing (it keeps saying "loading"):
<img width="1177" alt="screenshot 2018-11-19 at 20 48 16" src="https://user-images.githubusercontent.com/3874988/48725442-46377580-ec3d-11e8-99a0-fc6b8a1357aa.png">

**Comment by jjgao** [comment]
@ugurdogrusoz I think we should do a proper isolation of the network tab from the code base and maybe make it more like a library (similar to oncoprint.js). Do you think you would have resource to do that?

**Comment by ugurdogrusoz** [comment]
@jjgao this sounds like a good idea. I am not sure about the work involved for this but we don't have any resources at the moment unless it is more or less trivial. Might have some in the Spring though. @onursumer can you comment on the amount of work needed for this?

**Comment by jjgao** [comment]
@ugurdogrusoz thanks. It's not urgent.
