### ISSUE TITLE
New study view: Spacing in tables could be slightly better

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5290]
The spacing in tables used to be better... it looks like the font was just slightly smaller, which was more aesthetically pleasing. Also, the search box seems a little big now.

![image](https://user-images.githubusercontent.com/11892704/48751816-5ad33800-ec54-11e8-8341-6f292a091224.png)

**Comment by zhx828** [comment]
@schultzn this is now updated
