### ISSUE TITLE
Oncoprint clinical attribute coloring

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#5296]
From @sandertan 's comment https://github.com/cBioPortal/cbioportal/issues/5026#issuecomment-440245228

Also looping @jjgao in, to decide what the colors should be

**Comment by jjgao** [comment]
coping @sandertan's comments here:

This would be nice to have! Could you also assign fixed colors for other common used values? Such as:
- Positive/Negative (case insensitive)
- True/False (case insensitive)
- No data
- Unknown
- Other

I got most of these from querying BRCA TCGA (Prov) and adding all clinical data as tracks.

**Comment by jjgao** [comment]
We should have some color util code to handle colors the same way for everywhere, e.g. oncoprint and study view.

Can we list the special values we have assigned or plan to assign colors?

- Yes vs No
- True #66AA00 and False #666666
- No data, Unknown, NA, N/A should have the same color
- ...

**Comment by sandertan** [comment]
It would be nice if True/Yes/Positive all are the same color and the same goes for False/No/Negative. 

Also
- DiseaseFree vs Recurred/Progressed
- WITH TUMOR vs TUMOR FREE
- Male vs Female

could be added to those sets.

**Comment by zhx828** [comment]
@adamabeshouse I believe this ticket is done?

**Comment by adamabeshouse** [comment]
@zhx828 we haven't done every category mentioned here

**Comment by zhx828** [comment]
@adamabeshouse , I will revisit the study view to make sure all the colors are defined. Then you can import.

**Comment by Sjoerd-van-Hagen** [comment]
@zhx828 @adamabeshouse what is the status of this one?

**Comment by zhx828** [comment]
@sandertan @Sjoerd-van-Hagen here are the colors we defined so far. Please let me know if you want to add/update any one of them.
TRUE/YES/POSITIVE :  `#109618`
FALSE/NO/NEGATIVE : `#DC3912`
MALE: `#2986E2`
FEMALE: `#DC3912`

**Comment by adamabeshouse** [comment]
according to previous comments, we also need
No Data
Unknown
Other
DiseaseFree
Recurred/Progressed
WITH TUMOR
TUMOR FREE

**Comment by zhx828** [comment]
@adamabeshouse I need the color definition for them as well. By just looking at the name, I'm not super sure what color I should assign.
No Data Unknown Other will use the FALSE color?
Could you give me some more info about rest four?

**Comment by adamabeshouse** [comment]
no I have no idea what the colors should be. Im' just saying those are what we need

**Comment by zhx828** [comment]
@adamabeshouse cool, thanks. I will wait for @sandertan  and @Sjoerd-van-Hagen

**Comment by zhx828** [comment]
@jjgao what do you think?

**Comment by Sjoerd-van-Hagen** [comment]
_No Data Unknown Other_ should be a neutral color like gray. Not the same as false/negative.
_DiseaseFree TUMOR FREE_ I would use the same as yes/positive
_Recurred/Progressed WITH TUMOR_ I would use the same as false, no negative
I would change the color for female not to be the same as all the bad things...

**Comment by adamabeshouse** [comment]
good ideas. for no data, unknown, other, maybe we can use oncoprint default grey? @Sjoerd-van-Hagen @zhx828

**Comment by zhx828** [comment]
@adamabeshouse in study view we have a default NA color `#CCCCCC`

**Comment by zhx828** [comment]
In StudyViewConfig.js

**Comment by sandertan** [comment]
Good suggestions! Perhaps make give [Other / Unknown ] a different color than [ NA / No data]. Like in OncoPrint: a mutation not found is grey, but no data because gene is not profiled (on gene panel), it's white.

**Comment by jjgao** [comment]
agreed with @sandertan that other should have a different color, but maybe unknown could be the same with NA?

**Comment by zhx828** [comment]
@jjgao @Sjoerd-van-Hagen @adamabeshouse the colors will be updated to: 
true/yes/positive/diseasefree/tumorfree: `#109618`
false/no/negative/recurred-progressed/withtumor: `#DC3912`
female: `#E0699E`
male: `#2986E2`
unknown/other: `#A9A9A9`
na: `#D3D3D3`

Please let me know whether you wanna make any changes

**Comment by jjgao** [comment]
should unknown and na have the same color?

**Comment by sandertan** [comment]
Nice colors!

**Comment by zhx828** [comment]
@jjgao yeah, it makes more sense to me unknown is the same as NA. I can change that.

**Comment by Sjoerd-van-Hagen** [comment]
Nice work!

This is regardless of the attribute name, right? 

I think maybe the positive and negative should have different colors. Testing positive for a disease is usually not good. On the other hand if deceased is yes or true, that is also not good. Maybe a bit too hard to take those scenarios into account. Neutral colors could be better. Green suggests good, red bad.

**Comment by zhx828** [comment]
@Sjoerd-van-Hagen this is regardless of the attribute name.
The meaning of positive is arbitrary among attributes. I think I would do a quick stats of current data usage to see what fits the best.

**Comment by Sjoerd-van-Hagen** [comment]
But there will always be situations in which it will be the other way around, regardless of which decision we make now. With neutral colors we won't have that problem.

What do you think? @schultzn @jjgao

**Comment by schultzn** [comment]
I don't have a strong opinion on the colors for positive vs negative. Any suggestions for a better color scheme?

**Comment by Sjoerd-van-Hagen** [comment]
Let's leave it as it is and see how people respond then. It is not a big deal.

**Comment by zhx828** [comment]
@jjgao I don't think the color should be this way, at least should be reversed? https://www.cbioportal.org/study/summary?id=mbn_mdacc_2013

<img width="547" alt="Screen Shot 2019-06-02 at 9 27 49 PM" src="https://user-images.githubusercontent.com/5400599/58770511-5d0c3c80-857d-11e9-823b-32799676c4f5.png">

**Comment by Sjoerd-van-Hagen** [comment]
@zhx828 Yes, that would be better imo.

**Comment by jjgao** [comment]
@zheins agreed.

**Comment by zhx828** [comment]
@Sjoerd-van-Hagen @jjgao standard green/red? 

<img width="551" alt="Screen Shot 2019-06-03 at 4 11 56 PM" src="https://user-images.githubusercontent.com/5400599/58831275-57b0ff80-861a-11e9-9f31-7c816aef158f.png">

**Comment by jjgao** [comment]
@zhx828 looks good.

**Comment by zhx828** [comment]
@jjgao @schultzn @Sjoerd-van-Hagen just got some feedback from Aaron about the green/red combination especially in the following screenshots. The combination is not really friendly to color weakness/blindness users, especially when we start to apply the color in oncoprint. Should we reconsider the color for YES/POSITIVE?

## After applying green/red
![oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_initial_patient_order_element_chrome_1600x1000](https://user-images.githubusercontent.com/5400599/59460888-1e347d00-8dee-11e9-9ab3-7e0bca61ca2b.png)

## Before
![oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_initial_patient_order_element_chrome_1600x1000](https://user-images.githubusercontent.com/5400599/59461028-74092500-8dee-11e9-9c00-ae6a782a1b78.png)

**Comment by jjgao** [comment]
@zhx828 I think it's ok to use blue (living) and red (deceased).

**Comment by Sjoerd-van-Hagen** [comment]
When in doubt use: http://colorbrewer2.org/#type=qualitative&scheme=Dark2&n=3

Check the box for 'colorblind safe'

**Comment by zhx828** [comment]
It will look like this in production based on @Sjoerd-van-Hagen recommendation.
![Screen Shot 2019-06-14 at 10 28 20 AM](https://user-images.githubusercontent.com/5400599/59516417-4b853780-8e8f-11e9-8e87-1c5d16f57289.png)
![Screen Shot 2019-06-14 at 10 28 45 AM](https://user-images.githubusercontent.com/5400599/59516418-4b853780-8e8f-11e9-990c-d4d3df4984ce.png)

**Comment by Sjoerd-van-Hagen** [comment]
Nice! The 8% of the men and 0.5% of the women who are colorblind will be happy.
