### ISSUE TITLE
compact oncoprint: tooltip text updates

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5298]
Let's change the tooltip text to say:
\# Samples per Patient
Number of queried samples for each patient.

![image](https://user-images.githubusercontent.com/10508276/48800672-754ef500-ecd8-11e8-8162-7805190f0337.png)

![image](https://user-images.githubusercontent.com/10508276/48800683-7b44d600-ecd8-11e8-9a23-ce36830d35e3.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1667/commits/e7d6429cef23038fb2d42564119a8396a52e8d60
