### ISSUE TITLE
enrichments: confusing "no calculation" message

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5300]
The enrichments tab can't show a calculation if all samples are altered, or if no samples are altered. However, we need to show a different message in those 2 scenarios.

I ran a query with alterations in all samples, but got this message:
![image](https://user-images.githubusercontent.com/10508276/48801409-52254500-ecda-11e8-9c0e-86de966c1a2d.png)

The message should be "All queried samples are altered, therefore this calculation can not be performed."

In the case of samples without alteration, the existing message should be updated to read: "No queried samples are altered, therefore this calculation can not be performed."

To test this, query ucsf_lgg_2014 with IDH1 (all samples will be altered) or EGFR (no samples will be altered)

**Comment by dippindots** [comment]
@tmazor Thanks for the perfect example and detailed explanation!
