### ISSUE TITLE
compact oncoprint: left header for combined study is different than for single study

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5301]
1) The text on the first line is much bigger for the combined study
2) The genes included in the query aren't included for the combined study

![image](https://user-images.githubusercontent.com/10508276/48802267-bf39da00-ecdc-11e8-9724-cc89bceef826.png)

vs

![image](https://user-images.githubusercontent.com/10508276/48802275-c6f97e80-ecdc-11e8-944f-112c479543c6.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1667/commits/b2e8e1d771d3ad197b5618fc48929f2345fbd0f4
