### ISSUE TITLE
compact oncoprint: add patients to header when #samples=#patients

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5304]
![image](https://user-images.githubusercontent.com/10508276/48802763-2c9a3a80-ecde-11e8-977b-460a1343f5d2.png)

Can the header be updated on both the left & right sides to say "samples/patients"?
I think it's clearer if we are explicit that those 2 numbers are the same.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1667/commits/b84db01bd3ece8a3e8e33cd51d98cf02d0557256
