### ISSUE TITLE
Gene "Not profiled in selected molecular profiles." only based on mutation profile

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#5308]
In the following example, the study contains:
- mutation data that is sequenced on a panel
- discrete CNA data that is sequenced with whole exome seq

In the first screenshot:
- Of the 4 genes, only OR11H1 is on the panel
- Of the queried samples, only the first sample is in the gene panel matrix file. 
- Both the mutation and discrete CNA profile are selected.
- The white boxes for BRCA2, TP53 and ACAP3 should be grey, because the CNA profile is also selected.

<img width="482" alt="screenshot 2018-11-21 at 13 53 59" src="https://user-images.githubusercontent.com/9624990/48842601-f370d180-ed94-11e8-81b1-cc50ecd5991b.png">

In the second screenshot:
- When only selecting the discrete CNA profile, the boxes are still white for "not profiled". 
- I think this means that "not profiled" is only based on the mutation profile, instead of the selected profiles.

<img width="499" alt="screenshot 2018-11-21 at 13 57 06" src="https://user-images.githubusercontent.com/9624990/48842984-1059d480-ed96-11e8-84d0-5bdc59b092c3.png">

**Comment by jjgao** [comment]
@sandertan as discussed, it'd be good if you can find examples on the public portal.

**Comment by jjgao** [comment]
@sandertan alternatively, if you have the link to your test site, it would also work.

**Comment by sandertan** [comment]
@jjgao I used the study used by the validator system tests, `cbioportal/core/src/test/scripts/test_data/study_es_0/` to reproduce this error. I can try to setup a test server & database later this week.

**Comment by adamabeshouse** [comment]
this is probably a backend issue relating to assumptions made of data form in the gene panel API. i think @ersinciftci should be in here
