### ISSUE TITLE
When does the "Profiled in" track appear in OncoPrint?

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#5309]
The "Profiled in" track is a great addition to the OncoPrint to get a quick overview of the profiled samples in specific datatypes. I was wondering when this track appears. Is it depending on whether a subset of the samples is not profiled?

For example, this query showed me the "Profiled in" track for CNA but not for mutations.

<img width="711" alt="screenshot 2018-11-21 at 15 50 34" src="https://user-images.githubusercontent.com/9624990/48848857-58342800-eda5-11e8-8383-435c32ec2803.png">

Perhaps it would be nice to make it possible to be able to check/uncheck these tracks, for all queried profiles.

<img width="642" alt="screenshot 2018-11-21 at 16 00 16" src="https://user-images.githubusercontent.com/9624990/48849538-d80ec200-eda6-11e8-84f1-77f83b5a6a45.png">

I'm also confused why my local installation says that none of the samples are profiled on CNA, while the CNA case list looks good. Perhaps this has to do with the data_gene_matrix.txt. I'm looking into that now.

**Comment by jjgao** [comment]
Good idea to enable the option to select/deselect them just like other attributes.

**Comment by adamabeshouse** [comment]
@jjgao this is a possibility, its just that the track doesnt exist at all unless at least one sample is not profiled

**Comment by jjgao** [comment]
@adamabeshouse but in [this query](http://www.cbioportal.org/results?session_id=5bf5a859e4b0627334119046), I cannot turn them back on if I remove them...

I guess it's b/c of the 0%, but the 0% is wrong.

![image](https://user-images.githubusercontent.com/840895/48862363-28305900-ed94-11e8-848e-c5c7322cbdbc.png)

**Comment by adamabeshouse** [comment]
ah okay
