### ISSUE TITLE
update TCGA to Firehose 2015_08_21

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#531]

**Comment by fedde-s** [comment]
Is this only about loading new data into the public portal, or about updating cBioPortal/cbioportal-pipelines@d917780 to changes in the data format and layout?

**Comment by zheins** [comment]
@fedde-s this is only about loading the data into the public portal.

**Comment by pieterlukasse** [comment]
Hi @jjgao , @n1zea144 : do you have any updates on this one? This is perhaps also relevant for our new version of the TCGA staging files generated at #839. I heard from a client (@awernibi) that there is an important fix made Jan-2016 for one of the studies, so we might want to consider this version instead?

**Comment by jjgao** [comment]
Firehose 2015_08_21 has been released.
