### ISSUE TITLE
SV: Seems the gene frequency is not really matched with the current production

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5311]

**Comment by ersinciftci** [comment]
For Mutated and CNA Genes tables? They look same to me.

**Comment by ersinciftci** [comment]
Nevermind, CNA Genes look different for `acc_tcga`. Mutated genes look same though, and both mutated and cna genes look same for `msk_impact_2017`. I'll look into it, since it comes from the API.

**Comment by ersinciftci** [comment]
Found out why, because in the new study view, we show all the genes in CNA table, not only the cancer genes, so it looks different, but it's not actually. Closing the issue.
