### ISSUE TITLE
Compact OncoPrint: Show unaltered columns not working correctly

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5315]
Many columns are hidden, but not all, for some reason.

http://cbioportal-frontend-pr-1667.herokuapp.com/results?Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=msk_impact_2017_cnaseq&gene_list=BRAF%253A%2520V600%250AKRAS%250AEGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&cancer_study_list=msk_impact_2017

![image](https://user-images.githubusercontent.com/11892704/48860728-b6561080-ed8f-11e8-9598-32028071ef05.png)

**Comment by adamabeshouse** [comment]
not sure why but I can't reproduce this in your link

**Comment by jjgao** [comment]
@schultzn I cannot reproduce it either... strange.

**Comment by jjgao** [comment]
@alisman cannot reproduce it either.

@schultzn can you see this error in production as well?

**Comment by adamabeshouse** [comment]
seems like maybe the issue is just that it was taking a very long time, maybe even errored out. in any case, I just made a fix that hopefully should reduce this issue. https://github.com/cBioPortal/cbioportal-frontend/pull/1753
