### ISSUE TITLE
Tooltip too small for profile description

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#5320]
The profile description contains a very long word, perhaps that's causing issues with the box size.

<img width="951" alt="screenshot 2018-11-23 at 10 53 46" src="https://user-images.githubusercontent.com/9624990/48937632-0a3b3380-ef0f-11e8-88ba-871c76e79dab.png">

**Comment by coderrsid** [comment]
@sandertan I have fixed this issue and combined it with another fix.
Please review https://github.com/cBioPortal/cbioportal-frontend/pull/2099

**Comment by sandertan** [comment]
@coderrsid Thanks for the update. However, I'm not active in this project anymore, and also not a front-end developer, so perhaps someone else can review this fix.
