### ISSUE TITLE
ESR1-intragenic is annotated as oncogenic

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5324]
We should not link intregenic SVs to fusion annotations. Linking them to deletion is probably appropriate. 

https://cbioportal.mskcc.org/patient?studyId=mskimpact&sampleId=P-0035290-T01-IM6

![image](https://user-images.githubusercontent.com/840895/49041022-197de380-f192-11e8-8576-d40bd5ee5cf8.png)

http://oncokb.org/#/gene/ESR1/alteration/Fusions

**Comment by zhx828** [comment]
@jjgao I can update this to Deletion in OncoKB. But portal also annotates this variant on Mutation Type as Fusion.

**Comment by zhx828** [comment]
@jjgao this issue is now solved and deployed.
