### ISSUE TITLE
Network tab download options result in NullPointerException if opened in separate browser tab

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#5327]
Steps to reproduce:
1. go to http://www.cbioportal.org/results/network?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=brca_metabric&case_set_id=brca_metabric_cnaseq&data_priority=0&gene_list=ROR1%250ASORT1%250AFMOD&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_metabric_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_metabric_mutations&tab_index=tab_visualize
2. Select GraphML link and click "Open in new tab":
![image](https://user-images.githubusercontent.com/2900303/49084592-31b43800-f250-11e8-912f-2813f7611a19.png)
3. The new tab will open with URL http://www.cbioportal.org/network.do?gene_list=ROR1%20SORT1%20FMOD&genetic_profile_ids=brca_metabric_mutations%20brca_metabric_cna&cancer_study_id=brca_metabric&case_set_id=null&Z_SCORE_THRESHOLD=2&netsrc=cgds&msgoff=t&download=on and display the error below:
```
<!--messages begin:
Error loading network. Please report this to <span class="mailme" title="Contact us">cbioportal@googlegroups.com</span>!
java.lang.NullPointerException
messages end-->
<graphml></graphml>
```

**Comment by jjgao** [comment]
@pieterlukasse there is not an easy solution to fix this. Please click the link directly to download. 

@alisman maybe we can make the two links into buttons so that right click is disabled?

**Comment by pieterlukasse** [comment]
related to https://github.com/cBioPortal/cbioportal/issues/5130?

**Comment by jjgao** [comment]
@pieterlukasse yes, the same problem.

**Comment by pieterlukasse** [comment]
@alisman @jjgao, here a quick update on this one: apparently the download link is not working at all anymore. See screenshot below (it tries to fetch something from /beta via http):

![image](https://user-images.githubusercontent.com/2900303/60196627-dd9d2080-983d-11e9-9171-ea005b6717a7.png)

**Comment by alisman** [comment]
looking

**Comment by alisman** [comment]
Thanks for finding this Pieter,

PR made:

https://github.com/cBioPortal/cbioportal-frontend/pull/2504/files

**Comment by pieterlukasse** [comment]
thanks for the fix @alisman . 
The original issue of this ticket still exists though. I get this when opening the link in a new tab:
```
<!--messages begin:
Error loading network. Please report this to <span class="mailme" title="Contact us">cbioportal@googlegroups.com</span>!
java.lang.NullPointerException
messages end-->
<graphml></graphml>
```

**Comment by alisman** [comment]
Open in new tab is now fixed.
