### ISSUE TITLE
Display missing study ids in session on results page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5328]
- [ ] When querying an old session that includes missing studies e.g.

    http://www.cbioportal.org/results/cancerTypesSummary?session_id=5bd240d0498eb8b3d5688318

    It should show some warning which study ids are missing.

- [ ] If the session only includes missing studies another message should appear and probably none of the tabs should be initialized

- [ ] ResultsViewPageStoreUtils and ResultsViewPageHelpers have some overlap, maybe we should just merge them?

**Comment by alisman** [comment]
@jjgao in case where session or url has studies which are missing, do we want to attempt to show results and just have a warning?  
my preference would just be to have total error state (show no data).  otherwise, we have to handle case where there are samples in custom list which correspond to missing studies, etc.

**Comment by jjgao** [comment]
@alisman I think we should attempt to show results and show warning about the missing studies/samples.

It is not unusual that a sample and sometimes study is dropped or renamed from time to time. If I query for all curated 155 studies and saved a session, that session would very likely contain some dropped samples/studies. A session with a few missing samples/studies is still useful. It would be frustrating if we only show an error message without the results or a way to fix the error.

**Comment by jjgao** [comment]
Maybe we can discuss the issue with the custom list and see if we can find a good solution?

**Comment by alisman** [comment]
@jjgao we now show a warning message and the populated query form for invalid studyIds.  Do you think this is sufficient or should we follow through with showing results but with a warning and perhaps a link to modify query. 

![image](https://user-images.githubusercontent.com/186521/62875081-5eca4d00-bcf0-11e9-89ad-c6f36f5aad28.png)

**Comment by jjgao** [comment]
@alisman this is good enough. But when I try to submit, it still gives me the same error message. I was expecting I would be able to submit the query without the two studies.

**Comment by alisman** [comment]
@jjgao ah.  that's not good.  i will figure it out

**Comment by alisman** [comment]
@dippindots 
If when I see this error message, I check another study in list, the page will submit, but only if I select another study.  I should be able to submit without making any selection.  Clearly the invalid studyIds are being resubmitted.  Lets filter out the invalid studyIds on submission.
