### ISSUE TITLE
SV: changes to which charts appear by default?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5332]
On new study view for MSK-IMPACT, the survival chart doesn't appear by default.

We now are always showing the "Cancer Studies" chart, which is not meaningful when looking at a single study.

Are there reasons for these changes?

**Comment by jjgao** [comment]
We decided not to show survival chart for pancan studies (similiar to genie).

We should not show `Cancer Studies` chart when there is only one study -- we should apply the same rule that hide a chart if there is only one value.

**Comment by tmazor** [comment]
Oh not showing survival for pancan studies makes lots of sense - I like that change :)

Yes, let's hide the "Cancer Studies" chart when there is only one study.

**Comment by zhx828** [comment]
@tmazor  this one is now updated. http://www.cbioportal.org/beta/newstudy?id=lgg_tcga
