### ISSUE TITLE
SV: update text when filtering from barcharts

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5333]
![image](https://user-images.githubusercontent.com/10508276/49103055-602e1500-f248-11e8-950c-8dfdb0e01aeb.png)

When I filter from a barchart, e.g. Diagnosis Age, the label at the top says "20 < ~ < 60". This is confusing. I find the tilde very confusing, since that generally refers to an approximate, and should be replaced by "x". Or, even better, let's use the same text as when filtering on the Mutations vs CNA plot: "20 < Diagnosis Age < 60"

**Comment by jjgao** [comment]
I like the idea to use `20 < Diagnosis Age < 60`.

For Mutation Count vs FGA, is it possible to split it into two filters, i.e. `7 < Mutation Count < 71` and `0.06 < FGA < 0.38`? @zhx828

**Comment by zhx828** [comment]
@tmazor  this one is now updated. http://www.cbioportal.org/beta/newstudy?id=lgg_tcga
