### ISSUE TITLE
SV: survival chart NA toggle should only be present when relevant

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5335]
Currently the "exclude patients with NA" toggle is always present in the tooltip for the survival chart. However, this is confusing when (1) no filter is applied or (2) a filter is applied that doesn't have any NA values - in both scenarios, that toggle does nothing.

Can we update the tooltip to only show the NA toggle when it is relevant - ie when a filter has been applied for which some samples are NA?

Or, if that's too complicated, can we at least not show it when no filter is applied?

**Comment by ersinciftci** [comment]
Or we can disable it with an explanatory tooltip instead of hiding it.

**Comment by ersinciftci** [comment]
I just realized that it would mean a tooltip in a tooltip, so maybe we can just disable without a tooltip :)

**Comment by zhx828** [comment]
@tmazor @ersinciftci this issue is now fixed.
