### ISSUE TITLE
query from new study view leads to error in results view header

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5336]
Below are screenshots of the header of results view when running a query from study view.

The missing number of samples I presume will be fixed when compact oncoprint gets included in beta. But the name of the study is also missing, and I'm not sure if that one is related or not.

Query in all samples: 
![image](https://user-images.githubusercontent.com/10508276/49104117-332f3180-f24b-11e8-8d3b-4d02b3760486.png)

Query in subset of samples:
![image](https://user-images.githubusercontent.com/10508276/49104135-39bda900-f24b-11e8-9a3c-4a2b7d251c84.png)

Query on production: 
![image](https://user-images.githubusercontent.com/10508276/49104153-46420180-f24b-11e8-9268-1a9c44d4d046.png)

**Comment by adamabeshouse** [comment]
I'll merge master to rc and see if that fixes it

**Comment by adamabeshouse** [comment]
yes, it does
