### ISSUE TITLE
Empty getOrderedSampleList

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#534]
We recently imported the complete tcga brca provisional. Included in this is a file called data_RNA_Seq_v2_expression_median_normals and with it a meta_RNA_Seq_v2_expression_median_normals. The meta contains generic_alteration_type: MRNA_EXPRESSION_NORMALS

It seems that importing this file has caused the Plots and Co-expression tabs to crash. We traced the problem to DaoGeneticProfileSamples.java, where the getOrderedSampleList results in an empty sample list for this set. Verifying this in the database shows that indeed there are no samples associated.

The validator should prevent this from happening.

**Comment by fedde-s** [comment]
Not all data types use the `genetic_profile_samples` and `genetic_alteration` tables (which respectively hold what are effectively the header and rows of a csv, stored in an unfortunate non-relational way), but these mRNA expression z-scores should most definitely use it. I’ll have to look into it when I get to implementing validation of this field.

**Comment by pieterlukasse** [comment]
NORMALS is not supported any more.
