### ISSUE TITLE
Alternative Patient / Sample name functionality

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#5347]
@jjgao I was wondering whether PATIENT_DISPLAY_NAME  and SAMPLE_DISPLAY_NAME functionality is working as expected. I assumed they have specific functionality such as alternative naming in the front-end. But currently using PATIENT_DISPLAY_NAME and SAMPLE_DISPLAY_NAME in clinical data does not show any specific functionality. 

Current documentation:
SAMPLE_DISPLAY_NAME: displayed in addition to the ID
PATIENT_DISPLAY_NAME: displayed in addition to the ID
https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-sample-columns

Example in public portal:
http://www.cbioportal.org/patient?studyId=blca_plasmacytoid_mskcc_2016&caseId=DS-sig-002

**Comment by jjgao** [comment]
Actually, I am not sure. @ritikakundra @n1zea144 are you aware of PATIENT_DISPLAY_NAME and SAMPLE_DISPLAY_NAME?

**Comment by inodb** [comment]
@sandertan 	looks like a bug: https://github.com/cBioPortal/cbioportal-frontend/blob/ad8769543e3642f3d15715305d47b7924043c146/src/pages/patientView/patientHeader/style/clinicalAttributes.scss#L57-L61. There's no `display: inline` on those attributes.

**Comment by sandertan** [comment]
Fixed by Ino!
