### ISSUE TITLE
gene panel API returns "API not implemented yet"

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5356]
Using the swagger page to test:
/molecular-profiles/{molecularProfileId}/gene-panel-data/fetch

I get "Requested API is not implemented yet":
![image](https://user-images.githubusercontent.com/10508276/49395007-52bed200-f703-11e8-93b2-458a2c74bc04.png)

**Comment by lemccarthy** [comment]
Hey @tmazor can you confirm you can replicate this bug? I have tried it both locally and on live and I don't see it.

**Comment by tmazor** [comment]
I agree, looks like it's working now - closing the issue
