### ISSUE TITLE
make OQL link more obvious (and less scary)

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5361]
When I run training sessions I always demo OQL, and I frequently hear from existing users that they had no idea OQL existed and that they are super excited to use it going forward.

One thing that I think would help is to change the text for the link -- calling it "Advanced" may scare people away from clicking on it. How about calling the link "Refine your query with OQL"? Or something along those lines.

In addition, perhaps the text can be larger? Or made more obvious in some other way? @alisman any ideas?

**Comment by jjgao** [comment]
@tmazor good point. Calling it a language is also intimidating. I like "Refine your query with OQL"!

**Comment by alisman** [comment]
@tmazor @jjgao 

is this prominent enough?

![image](https://user-images.githubusercontent.com/186521/50118181-ef619380-021c-11e9-85c4-8802584841cb.png)

**Comment by alisman** [comment]
I also kind of think the text box itself needs to say in the label that it accepts oql.   A way to inject sample queries?

**Comment by jjgao** [comment]
@alisman good idea.
