### ISSUE TITLE
OQL syntax error doesn't move the cursor

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5362]
If I submit this:
![image](https://user-images.githubusercontent.com/10508276/49406491-bfe25f80-f723-11e8-9d1f-a5ba005899d2.png)

The cursor just appears at the beginning of the text box - it doesn't move to the location of the syntax error:
![image](https://user-images.githubusercontent.com/10508276/49406526-ccff4e80-f723-11e8-9b0c-e9fda677d86d.png)

**Comment by adamabeshouse** [comment]
reassigning to @kalletlak because he'd be more familiar with this code

**Comment by kalletlak** [comment]
@tmazor seems working to me. Could you check it again

**Comment by tmazor** [comment]
@kalletlak you are correct. I think @adamabeshouse fixed this while he was adding all the new OQL functionality. I will close this.
