### ISSUE TITLE
SV beta - # samples per patient shouldn't be recalculated after filtering

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5383]
The # of samples per patient is a patient level attribute that should not be affected by any filters that are applied, but that doesn't seem to be true on beta.

In tcga_lgg there are 16 patients with 2 samples. 
![image](https://user-images.githubusercontent.com/10508276/49535561-79f7d980-f892-11e8-8b62-023aa61c4044.png)

If I select those 16 patients, then the sample type chart shows me 16 primary and 14 recurrent samples (which is all the recurrent samples in the study)
![image](https://user-images.githubusercontent.com/10508276/49535610-8f6d0380-f892-11e8-8b71-ff40e8a5160d.png)

If I instead apply a filter to just view the 14 recurrent samples, then the # of samples per patient shows me that all 14 patients have 1 sample
![image](https://user-images.githubusercontent.com/10508276/49535636-a3186a00-f892-11e8-8363-c6ec0dd77427.png)
But based on the previous plots, I know that all 14 recurrent samples come from patients with 2 samples.

On production, this is done correctly.

Also on production, I see that there are 2 samples with N/A for sample type, and these account for the other 2 patients with 2 samples per patient. Those N/A samples are missing on beta.

This is probably the reason for #5382

**Comment by ersinciftci** [comment]
This is one related to API, will look at it.

**Comment by ersinciftci** [comment]
We will most likely fix this by adding a new patient clinical attribute called `SAMPLE_COUNT`.

**Comment by jjgao** [comment]
- calculate SAMPLE_COUNT (for each patient) after a sample clinical data file is imported
- override SAMPLE_COUNT for a patient if the data already exists
