### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5389]
I propose to keep footer only on the front/query page and other static pages, but remove it from the results page, study view, and patient view. The reason is that removing it will make it easier for us to utilize the whole space.

All the links will be available in the new header that @inodb designed. (@inodb do we have an issue for that? If not, could you create one?)

@schultzn @tmazor: objections or comments?

**Comment by inodb** [comment]
@jjgao https://github.com/cBioPortal/cbioportal/issues/5649

**Comment by alisman** [comment]
@jjgao i think we should consider just restoring the footer on all pages.  There is some valuable info in there (help, email contact, app version) that is most pertinent to users who are actually using the app (on various result pages).    I don't see what the drawback is to footer (except for that issue we ran into with the bottom oriented add button).

**Comment by jjgao** [comment]
@alisman I think we can capture the user links in the header. I think footer is useful for information website (mskcc.org). I am not sure an application website needs footer in every page. At least I don't miss it.

**Comment by schultzn** [comment]
Hmm… I am torn. Maybe we can remove the footers once we have a really good reason for it? Do we have something working yet that does not work with a footer?

**Comment by jjgao** [comment]
@alisman: @schultzn and I discussed on this. I think it's good to move things to header (#5649) and keep it clean, but I don't feel strongly about it. @schultzn doesn't feel strongly about this either. So @alisman maybe you can make a decision on this?

**Comment by alisman** [comment]
ok, if the decision is mine, i decide we should have a footer on every page.  if in the future we have a feature which conflicts with it, we can easily remove it.

**Comment by schultzn** [comment]
Sounds good!
