### ISSUE TITLE
study view beta: pie chart labels need adjustment

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5399]
Some labels on pie charts look wonky. I think in general they may be improved by putting the labels a bit father from the center where the slices are wider and the text may fit more easily, but there are also issue with spacing within a slice, or putting labels on slices that are probably too small to fit text.

These screenshots come from acc_tcga_pan_can_atlas_2018
![image](https://user-images.githubusercontent.com/10508276/49595729-a10fe300-f946-11e8-939c-a39611905436.png)
"5" covers 2 of the pie slices

![image](https://user-images.githubusercontent.com/10508276/49595762-b4bb4980-f946-11e8-8f3d-2b770307c5e4.png)
"10" overlaps the grey pie slice also

![image](https://user-images.githubusercontent.com/10508276/49595808-d7e5f900-f946-11e8-9955-cf9530825431.png)
"11" and "9" are both awkwardly close to the edge of the slices, and "21" could be more centered within its slice.

msk_impact_2017
![image](https://user-images.githubusercontent.com/10508276/49595940-301cfb00-f947-11e8-8a2c-e49c9435094b.png)
The red slice seems large enough that it should maybe have a label.

lgg_tcga
![image](https://user-images.githubusercontent.com/10508276/49596019-6195c680-f947-11e8-9d37-74dc8aa4259c.png)
"112" and "130" are so close to each other that it looks like one very long number.

![image](https://user-images.githubusercontent.com/10508276/49596032-68243e00-f947-11e8-9103-c9dc33907789.png)
"126" is hugging the edge of the slice, but there's plenty of room for it to be centered within the slice instead.

**Comment by zhx828** [comment]
@tmazor this is a tricky one. I will try to solve it before the release, but do you think it has to be done before the release?

**Comment by zhx828** [comment]
@tmazor this issue is now addressed. http://www.cbioportal.org/beta/study?id=acc_tcga_pan_can_atlas_2018
