### ISSUE TITLE
Tooltip for segmented copy-number in patient gets clipped

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5406]
![image](https://user-images.githubusercontent.com/11892704/49609590-f90c1100-f969-11e8-863a-cf85083bcf34.png)

**Comment by jjgao** [comment]
Maybe we should just wait for @onursumer's IGV.js integration for this?

**Comment by schultzn** [comment]
Yes, probably a good idea.

Would like to see that implementation - my first impression based on tomorrow’s slides was that it took up a little too much space.

**Comment by jjgao** [comment]
@schultzn agreed. We need to make it more compact in patient view.
