### ISSUE TITLE
missing mRNA profile from genomic profiles checklist

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#5416]
METABRIC study has mRNA expression data. However, users can not select the mRNA profile since it is not included in the genomic profiles checklist on query page.
![screen shot 2018-12-08 at 11 53 48 pm](https://user-images.githubusercontent.com/17375786/49693639-beab9b00-fb46-11e8-92d6-d111ba15403b.png)
![screen shot 2018-12-08 at 11 54 44 pm](https://user-images.githubusercontent.com/17375786/49693644-ca975d00-fb46-11e8-9c1f-8a9c73e639d1.png)

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/datahub/issues/485
