### ISSUE TITLE
Importer crashes when gene panel data is not yet loaded

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#5417]
If you follow documentation here https://github.com/cBioPortal/cbioportal/blob/master/docs/Load-Sample-Cancer-Study.md, then the data loading works fine. The problem however, is that the validation script does not enforce this order. 

Steps to reproduce:
- load new seed DB
- try to load study_es_0 with metaImport. Data loading step will crash. @pvannierop has more details.

Desired solution:
- validation script should give an ERROR when necessary gene panel data is missing.

**Comment by pieterlukasse** [comment]
@sandertan have you perhaps worked on this one? I couldn't find any issues or PRs

**Comment by pvannierop** [comment]
This is the stacktrace of the Exception:

> Reading data from:  /study/brca_tcga_pub.maf
> Recaching...
> Finished recaching...
> --> profile id:  24
> --> profile name:  Mutations
> --> genetic alteration type:  MUTATION_EXTENDED
> --> OMA Scores Column Number:  32
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> at java.util.ArrayList.rangeCheck(ArrayList.java:657)
> at java.util.ArrayList.get(ArrayList.java:433)
> at org.mskcc.cbio.portal.util.GeneticProfileUtil.getGenePanelId(GeneticProfileUtil.java:91)
> at org.mskcc.cbio.portal.scripts.ImportExtendedMutationData.addSampleProfileRecord(ImportExtendedMutationData.java:586)
> at org.mskcc.cbio.portal.scripts.ImportExtendedMutationData.importData(ImportExtendedMutationData.java:425)
> at org.mskcc.cbio.portal.scripts.ImportProfileData.run(ImportProfileData.java:86)
> at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
> at org.mskcc.cbio.portal.scripts.ImportProfileData.main(ImportProfileData.java:124)
>
