### ISSUE TITLE
cbioportal column in mutations tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#542]
We should reuse some of the code in PancanMutationHistogram.js. But there are a lot of code in PancanMutationHistogram.js for displaying a thumbnail per row. We are not using them any more. We should clean up the code.
- [ ] a servlet to pull mutation frequency (Adam should have some implementation already)
- [ ] only pull study specific data when mouse over and displaying the histogram
- [ ] mutations tab and patiant view should use the same PancanMutationHistogram.js.

**Comment by alisman** [comment]
@jjgao this seems more like a project than a ticket.  not sure how to label this vzv this morning's discussion

**Comment by jjgao** [comment]
@alisman this was an old one.
