### ISSUE TITLE
SV: Show tooltip when mouse over the bar

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5425]
Add a tooltip when hover over each bar in the study view bar chart indicating how many samples in this group and what the range is. You can follow the .

Forgive my simple mockup. But it should be similar as the one in density plot ![Screen Shot 2019-03-11 at 10 29 40 AM](https://user-images.githubusercontent.com/5400599/54131918-b1be7200-43e9-11e9-9bc6-6502a2a18b48.png)

![Screen Shot 2019-03-11 at 10 38 51 AM](https://user-images.githubusercontent.com/5400599/54132034-e4686a80-43e9-11e9-8ec9-f209b848f337.png)

**Comment by coderrsid** [comment]
@zhx828 can you provide more detailed description of this issue, i'll like to work on this. Add links and screenshots too please?

**Comment by zhx828** [comment]
@coderrsid I updated the description.

**Comment by Parth910** [comment]
@zhx828  can I work on this Issue?

**Comment by zhx828** [comment]
Sure thing. Thanks.

**Comment by Parth910** [comment]
so , where i can send pull request for this issue? In frontEnd Repository or somewhere else?

**Comment by zhx828** [comment]
Please send PR to https://github.com/cBioPortal/cbioportal-frontend master
branch.

**Comment by Parth910** [comment]
Ok Thanks.

**Comment by zhx828** [comment]
@Parth910 do you still have the fix available? I saw there were two attempts but all closed.

**Comment by Luke-Sikina** [comment]
Closing this. The code is merged into master and deployed on cbioportal.org.
PR: https://github.com/cBioPortal/cbioportal-frontend/pull/2724
