### ISSUE TITLE
'á' (UTF-8) not correctly displayed

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#5428]
@jjgao @alisman I noticed that 'á' is not correctly displayed on the query page in a custom instance. My `portal.properties` is saved as UTF-8.

![screenshot 2018-12-12 at 11 55 55](https://user-images.githubusercontent.com/9624990/49865518-740b7680-fe05-11e8-85f9-1cccab956d28.png)

```
# web page cosmetics
skin.title=cBioPortál

# setting controlling the blurb
skin.blurb=This is a test to see if á is correctly displayed.
```

**Comment by sandertan** [comment]
@jjgao It's currently not critical. I'll try look into this at a later time.

**Comment by alisman** [comment]
@sandertan when you are in dev server mode (localhost:3000), the config reaches the page via a service (see screenshot).  can you look at the response of the service to see if the character is corrupted in the response?  

![image](https://user-images.githubusercontent.com/186521/49960074-4e51a080-fedd-11e8-948e-5b4a46312000.png)

**Comment by alisman** [comment]
config_service.jsp is the endpoint.

**Comment by sandertan** [comment]
@alisman Thanks for the explanation on running it in DEV mode. It seems that it's already corrupted in the response:

<img width="1138" alt="screenshot 2018-12-14 at 16 10 47" src="https://user-images.githubusercontent.com/9624990/50010887-e1143d00-ffba-11e8-8d1e-8768239a4b13.png">

**Comment by alisman** [comment]
@sandertan woud you mind looking at the jsp that produces this file? You might know better than me how it can be fixed/debugged at there.

portal/src/main/webapp/WEB-INF/jsp/global/frontend_config.jsp

**Comment by sandertan** [comment]
@alisman I'll look at it next week. I don't know how to set a debugger here, so I need some help from the Oleguer.

**Comment by lemccarthy** [comment]
Hey everyone, .properties files use the Latin-1 encoding, and so any characters outside of that set need to use their unicode escape sequences. Try using `\u00C1` instead of that á. When I do that I get this:

[Image](https://imgur.com/bJBIsbL)

To avoid doing this manually, you can use this: https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/native2ascii.html

And if the project upgrades its Java version to Java 9 or up, UTF-8 properties files will be natively supported.

**Comment by alisman** [comment]
thanks @lemccarthy!  @Sjoerd-van-Hagen i'll let you decide whether to close this or not.

**Comment by Sjoerd-van-Hagen** [comment]
Wow. I assumed everything would be UTF-8 in Java. Silly.
