### ISSUE TITLE
Wrong sample counts in Data Sets overview

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#543]
When there are multiple datasets of the same type (same genetic_profile.datatype) in a study, then the sample counts in the Data Sets overview UI  (see screenshot) are possibly not correct.   

![image](https://cloud.githubusercontent.com/assets/2900303/11499474/a5debb24-9826-11e5-8310-4501603d1f03.png)

**Comment by pieterlukasse** [comment]
overlaps with #244  and #249

**Comment by pieterlukasse** [comment]
Actually, dataset counts are problematic in general since they are currently relying on data administrators to correctly set the stable_id of case lists as (not yet completely) documented here: https://github.com/cBioPortal/cbioportal/blob/rc/docs/File-Formats.md#case-lists

**Comment by pieterlukasse** [comment]
@paulcwvandijk is this still an actual issue in your recent experience?

**Comment by paulcwvandijk** [comment]
@pieterlukasse I haven't come across this problem yet. I will re-open this issue if such a situation arises

**Comment by pieterlukasse** [comment]
@jjgao what about 

Glioblastoma (TCGA, Nature 2008)	
TCGA, Nature 2008	206	91	206	0

why does it report 0 samples for RNA-Seq? From the heatmap it looks like it has data:

![image](https://user-images.githubusercontent.com/2900303/60167925-5aaba400-9804-11e9-8b6e-f9ed2556a614.png)

**Comment by jjgao** [comment]
that's microarray data, not rnaseq.
