### ISSUE TITLE
Missing profile description in the Plots tab

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#5436]
In the old Plots tab view, I think there was a "?"-icon on each axis. When hovering over the item, you would see the description of that profile. In the new Plots tab, this icon is missing and there is no alternative.

<img width="1186" alt="screenshot 2018-12-13 at 16 01 30" src="https://user-images.githubusercontent.com/9624990/49946991-6c74cc00-fef0-11e8-8499-d80510e4c841.png">

**Comment by jjgao** [comment]
We can show the info icon next to the Profile dropdown. If we do that, we should do it in other places, such as Co-expression and Enrichments. 

@adamabeshouse I remember we had the icon in other tabs. Did we remove it b/c the description was confusing?

**Comment by jjgao** [comment]
found it: https://github.com/cBioPortal/cbioportal/issues/4482

We will not add it back until https://github.com/cBioPortal/datahub/issues/238 is fixed.

**Comment by sandertan** [comment]
@jjgao Any plans on adding this back now? :)

**Comment by jjgao** [comment]
We can turn it back on now. @adamabeshouse
