### ISSUE TITLE
Study view: Number of samples incorrect in various pie charts

### ISSUE THREAD

**Issue by paulcwvandijk** [cBioPortal/cbioportal#5437]
Steps to reproduce:
Go to url: http://www.cbioportal.org/beta/study?id=brca_tcga

Look at Pie Chart "Sample Type"

Look at sample and patient size at the header

Total of both (1,105 vs 1,108) don't add up to same amount.

![screenshot 2018-12-13 at 16 06 48](https://user-images.githubusercontent.com/44695112/49947393-70edb480-fef1-11e8-8fe9-69daeea0672c.png)
![screenshot 2018-12-13 at 16 09 25](https://user-images.githubusercontent.com/44695112/49947411-7c40e000-fef1-11e8-98c0-eaade59bbe33.png)

- Desired solution: Numbers should match

**Comment by pieterlukasse** [comment]
notify: @jjgao @zhx828

**Comment by ersinciftci** [comment]
The reason is, this query:
```
SELECT * FROM public_test.sample inner join patient on sample.PATIENT_ID = patient.INTERNAL_ID 
inner join cancer_study on cancer_study.CANCER_STUDY_ID = patient.CANCER_STUDY_ID
where cancer_study.CANCER_STUDY_IDENTIFIER = 'brca_tcga';
```
returns 1108 patients but this query:
```
SELECT * FROM public_test.sample_list_list inner join sample_list on sample_list_list.LIST_ID = sample_list.LIST_ID where sample_list.STABLE_ID = 'brca_tcga_all';
```
return 1105. So `brca_tcga_all` list doesn't have all the samples in `brca_tcga` for some reason. Seems like a data issue.

**Comment by jjgao** [comment]
@ersinciftci @zhx828 instead of loading all samples, should we load a list, by default case_all? Frontend can pass this list to backend.

**Comment by ersinciftci** [comment]
I think short term solution can be calling the `/filtered-samples/fetch` endpoint instead of `/samples/fetch` in the first page load (it's better to do that in terms of consistency anyways, we already call `/filtered-samples/fetch` for every subsequent filter). We can talk about getting rid of the case lists concept after the release.

**Comment by pieterlukasse** [comment]
Getting rid of case lists could prove difficult,  since they are used to keep track of what has been sequenced for example. But perhaps this has been mostly made redundant by the gene panel implementation...not sure.

**Comment by pieterlukasse** [comment]
If case lists remain, there should be a validation rule that checks that _all contains at least all samples used in other files (it should be allowed to contain more, but not less). @sandertan

**Comment by ersinciftci** [comment]
I think `sample_profile` table already has the information of what has been sequenced.

**Comment by pieterlukasse** [comment]
@ersinciftci looking at the code, `sample_profile` only seems to be filled when there is gene panel data or if the MAF file contains a special header row with a list of samples (which is actually legacy stuff and something not documented as far as I can see in https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#mutation-data). Looking at datahub, I also don't see this extra row in the MAF file of all studies (see https://media.githubusercontent.com/media/cBioPortal/datahub/master/public/brca_tcga/data_mutations_extended.txt for example). In fact, I expect `sample_profile` table will actually be empty for this specific `brca_tcga` study, given it also has no gene panel data (see https://github.com/cBioPortal/datahub/tree/master/public/brca_tcga).

**Comment by jjgao** [comment]
`sample_profile` should be filled for all profiles. It'll be used to populate the profile-related case lists on the fly: https://docs.google.com/document/d/1aBbkTAFv5nCqBv66BOgwvlt5kymgt0lQ7l_pqaFrupc/edit#h

**Comment by jjgao** [comment]
I checked with database, brca_tcga_mutations has 981 samples in `sample_profile`

**Comment by pieterlukasse** [comment]
hm..apparently there is also `addSampleProfile` in the deprecated class ImportDataUtil...

**Comment by jjgao** [comment]
hmm.. there are 982 (somehow nto 981) samples in the MAF. I guess some of the samples may not have any mutations and when we converted the data from firehose, we created the cases_sequenced list, but didn't add the `#sequenced_samples:` header...

**Comment by pieterlukasse** [comment]
I think the case lists should remain as a file format, but they could be removed from the DB schema, meaning we should use only `sample_profile` table for queries. The case list tables could be dropped. But the data loading code needs to be adjusted to fill the `sample_profile` table.

**Comment by zhx828** [comment]
@pieterlukasse @ersinciftci @jjgao @paulcwvandijk hi guys this is now fixed on production.
