### ISSUE TITLE
Study view: x-axis value labels in Survival plots too dense

### ISSUE THREAD

**Issue by paulcwvandijk** [cBioPortal/cbioportal#5438]
Steps to reproduce:
Go to study view: http://www.cbioportal.org/beta/study?id=brca_tcga
Look at Survival plots

![screenshot 2018-12-13 at 16 24 03](https://user-images.githubusercontent.com/44695112/49948331-8663de00-fef3-11e8-82d8-0e95858545b4.png)

- desired solution: only major tick mark labels (?)

**Comment by jjgao** [comment]
@zhx828 we should also rotate the text for survival and density plot, or use fewer ticks.
