### ISSUE TITLE
If Mutated/CNA Genes table are disabled, the data fetching for them should not be triggered

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5443]

**Comment by alisman** [comment]
@zhx828 @adamabeshouse i think that accomplishing this will require destroying the promises which sit in the clinicalDataCountPromises collection.   Right now they sit there and react even if the chart which requires them has been "deleted".  So we need to have a way of discarding them from the collection and calling a destroy method on them.   Right now mobxPromise doesn't have a way of disposing.  I'm pretty sure it needs it.

**Comment by adamabeshouse** [comment]
mobxpromise doesnt need to dispose, it doesnt have reactions

**Comment by adamabeshouse** [comment]
there seems to be something specific about mutated and cna genes table because other charts ive checked, other mobxpromises, dont seem to have the same problem. I believe this indicates this isn't a mobxpromise bug

**Comment by adamabeshouse** [comment]
oh okay here we go lol

in MutatedGenesTable
```
reaction(() => this.props.promise.result, () => {
            this.updateCellMargin();
        }, {fireImmediately: true});
```
