### ISSUE TITLE
Study view: Change "no" to red in pie charts

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5448]
Green vs red seems to be most commonly used for yes vs no

**Comment by zhx828** [comment]
@cBioPortal/product could you confirm this is the color scheme for Yes/No,  Positive/Negative
![screen shot 2018-12-14 at 11 34 10 am](https://user-images.githubusercontent.com/5400599/50015704-33426780-ff95-11e8-9dc8-755c528618a4.png)

Or the green we always use in the study view? The only downside of using this green is in other chart we will have expectation that green represents Yes even it does not.
![screen shot 2018-12-14 at 11 38 11 am](https://user-images.githubusercontent.com/5400599/50015705-33426780-ff95-11e8-8afe-7db5ee7a4ac5.png)
