### ISSUE TITLE
Study view: change position of add chart icons

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5450]
JJ will explain in person

Goal is to reduce mouse travel distance

**Comment by zhx828** [comment]
- [ ] Move the plus icon next to Select **/sample box
- [ ] Using same style as the buttons above
- [ ] When the button is clicked, a tooltip will be shown with three tabs showing to replace the current `Select clinical data`, `Select genomic data`, `Add Custom Charts` buttons

cc @cBioPortal/product  please take a look this ticket and update anything if you want to. This is the mock up I have base on the conversation with JJ:

![dec-13-2018 19-33-59](https://user-images.githubusercontent.com/5400599/49975958-24fd3880-ff0e-11e8-8bfe-416aeae9c01a.gif)

**Comment by schultzn** [comment]
Nice!

One more: move search box above the table to allow for quicker interaction (less mouse movement).

**Comment by zhx828** [comment]
@schultzn just one concern: we may already have the expectation at the bottom since all other tables have search at the bottom left.

**Comment by zhx828** [comment]
@schultzn sure, I will update the component.
