### ISSUE TITLE
sv: layout of charts includes gaps

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5453]
When I load this combined study (http://www.cbioportal.org/beta/study?id=lgg_tcga%2Cgbm_tcga), the starting layout includes gaps at the bottom. The Disease Free chart can move to the left and that would leave room for the Overall Survival plot to fit next to it.
![image](https://user-images.githubusercontent.com/10508276/50023749-25e5a700-ffae-11e8-9937-5d3add4c89ea.png)

If I then move "Disease Free Status" to the right, everything gets pushed down rather than re-arranging:
![image](https://user-images.githubusercontent.com/10508276/50023758-2da54b80-ffae-11e8-976a-d1e8a65eb5d2.png)

**Comment by zhx828** [comment]
@tmazor this is the design from the library we are using. I can take a look whether there is a way to fix that. But probably will fix in 1.19.x
