### ISSUE TITLE
SV: Two survival plot tooltips are visible at the same time

### ISSUE THREAD

**Issue by ersinciftci** [cBioPortal/cbioportal#5455]
<img width="1680" alt="screen shot 2018-12-12 at 2 10 03 pm" src="https://user-images.githubusercontent.com/3595704/50025000-254f0f80-ffb2-11e8-9fb7-f396354c2bbb.png">
So maybe we can add the same amount of delay  with the pie chart tooltips to them.

**Comment by alisman** [comment]
@ersinciftci i can't reproduce this.  any trick?

**Comment by ersinciftci** [comment]
Seems like this is fixed.
