### ISSUE TITLE
logo for private portals is faded and tiny

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5462]
Private portals like GENIE or DFCI can include a logo in the upper right corner, but the icon is tiny and appears faded. Can this be made bigger & easier to see?

![image](https://user-images.githubusercontent.com/10508276/50109562-31cba600-0206-11e9-8b6a-5582468fbe4f.png)

**Comment by tmazor** [comment]
Yes, I believe so

**Comment by alisman** [comment]
@jjgao @tmazor 
Right now there is a 50% opacity on the logo, which accounts for the fading.  I will change that to 100%.  
The size though is tricker.  Is it reasonable to require that the logo not be larger than the portal logo?  The AACR logo has three seperate lines of text which is going to require a pretty big size to be legible.  Ideally the institution would crop of the logo to the right size.

**Comment by tmazor** [comment]
@alisman  I think it's reasonable to require that the logo not be taller than the portal logo so as to not mess with the overall height of that header bar (wider should be ok though). I think that, combined with the 100% opacity, will help a lot in terms of legibility.
