### ISSUE TITLE
TCGA provisional datasets have a patient_weight field which is not actually patient weight

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5467]
I suspect this is sample weight in mg, rather than patient weight in kg, but that should be confirmed against the original data source.

lgg_tcga
![image](https://user-images.githubusercontent.com/10508276/50121177-e7f2b800-0225-11e9-9c46-0ef634596be6.png)

chol_tcga
![image](https://user-images.githubusercontent.com/10508276/50121238-1a9cb080-0226-11e9-8acb-fbc66fd3087d.png)

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #505](https://github.com/cBioPortal/datahub/issues/505) via [**ZenHub**](https://www.zenhub.com/)
