### ISSUE TITLE
sv: un-necessary re-rendering when adding charts

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5472]
When I add a chart, all of the existing data re-renders, as does this bar:
![image](https://user-images.githubusercontent.com/10508276/50121863-28ebcc00-0228-11e9-8e07-b02fa7622d28.png)

There aren't any new filters being applied, so other charts & that "selected" bar shouldn't re-render.

This also applies when viewing the clinical data table - I understand that the table may need to re-render with the new column, but the "selected" bar doesn't need to.

**Comment by jjgao** [comment]
looks like this has been fixed.
