### ISSUE TITLE
Error when loading four small cell lung cancer studies

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5478]
This url returns error 
http://www.cbioportal.org/study?id=sclc_clcgp%2Csclc_jhu%2Csclc_ucologne_2015%2Csclc_cancercell_gardner_2017
Error: 500

**Comment by adamabeshouse** [comment]
I cant see the bug for this one either :D what are the steps to reproduce it?

**Comment by adamabeshouse** [comment]
cant repro

**Comment by zhx828** [comment]
This is caused by the 500 error code. Need to handle the error code on the promise level. It is related to https://github.com/cBioPortal/cbioportal/issues/5488.

**Comment by jjgao** [comment]
Can we keep this open since the error is still happening.

**Comment by zhx828** [comment]
This is now fixed on production.
