### ISSUE TITLE
Add Chart (Add all) does not work for this study

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5479]
https://cbioportal.mskcc.org/study?id=mskraindance

**Comment by adamabeshouse** [comment]
it seems to work for me?

**Comment by zhx828** [comment]
This is caused by the 500 error code. The endpoint seems working properly now. Need to handle the error code on the promise level. It may be related to https://github.com/cBioPortal/cbioportal/issues/5484. But definitely not the add chart issue.  Closing for now.

**Comment by jjgao** [comment]
Select "Overall Survival" does not work for me.
