### ISSUE TITLE
Filters are still applicable from one study to another

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5480]
- If you go to this link http://www.cbioportal.org/study?id=prad_mskcc_2017%2Cprad_mskcc%2Cprad_p1000%2Cprad_mskcc_2014%2Cprad_mskcc_cheny1_organoids_2014
- then select anything 
- click on the plus icon next to Combined study
- Select any hyperlink to study
- bomb... the filter is still there

@jjgao LOL no sure whether this should be a feature?

**Comment by jjgao** [comment]
@zhx828 I think we should open a new tab for these links.
