### ISSUE TITLE
Data issue for Prostate Adenocarcinoma (MSKCC, Cancer Cell 2010)

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5481]
This study returns 216 samples, but has 234 count for prostate cancer cases under Cancer Type

http://www.cbioportal.org/study?id=prad_mskcc

**Comment by jjgao** [comment]
@zhx828 how is this possible?

**Comment by zhx828** [comment]
@ersinciftci will do. Sorry to bother you during the vacation.

**Comment by ersinciftci** [comment]
@zhx828 No worries :)

**Comment by zhx828** [comment]
@ersinciftci @jjgao this is now fixed on production.
