### ISSUE TITLE
Custom Group issue

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5484]
- paste a list of ids
- click on the add chart
- and remove some ids from the list
- then click on the add chart again

**Comment by adamabeshouse** [comment]
cannot reproduce

**Comment by zhx828** [comment]
This is potentially caused by the 500 error code while interacting with the page. It may be related to https://github.com/cBioPortal/cbioportal/issues/5484. But definitely not the custom group chart issue.  Closing for now.
