### ISSUE TITLE
error on study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5489]
1. http://www.cbioportal.org/study?id=lung_msk_2017
2. Add Chart
3. Select All(30)

![image](https://user-images.githubusercontent.com/840895/50240048-c9113480-0391-11e9-8f2f-9a84fedad54c.png)

**Comment by schultzn** [comment]
The following chart appears to be the reason for the error:
Number Treatment Lines Prior To Receiving...

**Comment by zhx828** [comment]
@schultzn @jjgao we are working on it, will update the system tonight.
