### ISSUE TITLE
problems with OQL error submission in modify query interface

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5496]
On the homepage, if I type invalid OQL, I can click the Submit button to see the location of the OQL error.

The same option is available through the Modify Query interface. However, if I click submit there, it closes the modify query interface and when I open it up again, the previous query is still there -- so the bad OQL is lost and as a user I'm just confused about what happened.

I did this at first by accident -- I didn't realize my OQL was bad, I didn't notice the warning text, and since the Submit button was clickable, I just clicked and expected to see an updated OncoPrint but instead saw the exact same OncoPrint I had started with.

We need properly enable OQL checking within the modify query interface: the modify query interface needs to stay open and the "bad" OQL needs to remain there after clicking Submit so the user can fix it.

**Comment by adamabeshouse** [comment]
merged in `master`
