### ISSUE TITLE
Study Summary: Selecting a 10K patient list takes time to load

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#5498]
Tried selecting 10k patients in the portal for MSK-IMPACT and it took 20-30 seconds for the summary to read those patients and enable me to click the add chart button.

**Comment by jjgao** [comment]
@zhx828 maybe there is room to improve in the frontend code? using hashmap might help if you are not using it.

**Comment by zhx828** [comment]
@jjgao I'm already using it. I will take a look which other parts I can improve.

**Comment by zhx828** [comment]
@ritikakundra @jjgao so I misunderstanding the meaning of this ticket. Are you saying after selecting 10k samples, the portal is slow to generate all charts? Or pasting sample ids into that box is slow before clicking on `add chart button`?

**Comment by jjgao** [comment]
@zhx828 it's slow to generate the chart after you click "Add Chart". But I found that if you click "Use current select samples/patients" and click "Add Chart", it's not slow.

**Comment by adamabeshouse** [comment]
should be fixed in `master` now

**Comment by jjgao** [comment]
@ritikakundra please verify.
