### ISSUE TITLE
propagate filtering from oncoprint to other tabs

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5499]
When filtering changes in oncoprint, we should propagate the change to other relevant tabs, e.g. `Mutual Exclusivity`, `Mutations`, `Enrichments`, `Survival`.

Changes include

- Anything in the Filter menu, Show VUS, Show Germline
- Change of sources for driver when not showing VUS or DRIVER is used in OQL

**Comment by adamabeshouse** [comment]
This is now done except for two oversights:

(1) No tab respects "dont show germline"
(2) Mutations tab only respects driver filtering if there is a non-trivial mutation spec in OQL
