### ISSUE TITLE
SV: Pie chart filtering doesn't work when you click on the number in the slice

### ISSUE THREAD

**Issue by ersinciftci** [cBioPortal/cbioportal#5500]
<img width="195" alt="screen shot 2018-12-19 at 4 46 57 pm" src="https://user-images.githubusercontent.com/3595704/50250029-bc9ad500-03ad-11e9-8ae0-3a824fc12bd0.png">
If I click on anywhere on those two numbers, the filtering doesn't happen. So those labels should also catch mouse click events.

**Comment by zhx828** [comment]
Issue has been solved in https://github.com/cBioPortal/cbioportal-frontend/pull/1860

**Comment by zhx828** [comment]
@ersinciftci this issue has been solved.
