### ISSUE TITLE
EllipsisTextTooltip is not working in AddChartButton

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5505]
I found the issue before the release, but didn't not get a chance to solve yet.
The quick dig in, seems like `this.el.scrollWidth` is 0 in AddChartButton

- Go to http://www.cbioportal.org/study?id=lgg_tcga
- Click on Add Chart
- Hover any row with long text
- You don't see the tooltip

**Comment by coderrsid** [comment]
Please remove this issue from bugs cause this is resolved.
