### ISSUE TITLE
gene tracks cannot be expanded

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5514]
If I click "expand" on a gene track, the page reloads but the OncoPrint never appears:
![image](https://user-images.githubusercontent.com/10508276/50315748-f2a98900-0481-11e9-88a7-d869410f1ee9.png)

http://www.cbioportal.org/results/oncoprint?session_id=5c1c206de4b09ccddade4ba7

**Comment by adamabeshouse** [comment]
fixed in `master`
