### ISSUE TITLE
oncoprint add clinical track text disappears after adding

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5518]
The menu to add a clinical track normally has text saying "Add clinical tracks..."

If I open the menu and click a track, that text remains. But if I search to select a track, then the text goes away.
![dec-21-2018 13-31-00](https://user-images.githubusercontent.com/10508276/50357676-cb57c800-0524-11e9-86fe-1e714e95854b.gif)

**Comment by adamabeshouse** [comment]
paging @rnugraha @fedde-s

**Comment by adamabeshouse** [comment]
this is actually an issue with the react-select-checked component, which I'm not sure if we're going to take ownership of or not, or ask the hyve to maintain it. @alisman

**Comment by rnugraha** [comment]
@adamabeshouse One tricky thing about the usage of react-select-checked in the Oncoprint is: after selecting an item (or more), it refreshes/reloads the whole component including the react-select-checked. 

Therefore it reset the state to the initial state. This eventually creates a lot of issues. Most of the issues actually won't happen if it's not being refreshed. Maybe we need to think about how to mitigate this.

The library is open-source. You can always create PR if you have fixes. If you 're interested to be maintainer, contact us in #slack to talk about this further.

**Comment by alisman** [comment]
@rnugraha i think we need to resist forking libraries like this and also creating libraries (like json-to-table for example).  There is a maintenance cost that I don't think is entirely justified.  Better just to make this a component in our project unless there is a really strong, known need to reuse it elsewhere.   Also, react-select 2.0, which I am using for the quick search, makes customizing react-select much easier than in 1.x.  I think accomplishing the checkbox thing would be a cinch in 2.0.

**Comment by rnugraha** [comment]
@alisman I think the opposite. Making them as a separate library will make them loosely coupled from the main application and easier to maintain. As for react-select 2.0 if you think so we would be happy to help as well as we are open if you want to take the ownership to continue the development.

**Comment by pieterlukasse** [comment]
@alisman just discussed it internally here, also with @rnugraha . Please feel free to go ahead and move it to the cBioPortal frontend code repo :+1: . Hopefully this will make maintenance easier.

**Comment by jjgao** [comment]
@oleguer @pieter would you be able to help with this? Or should we just incorporate the code in the main frontend repo?

**Comment by adamabeshouse** [comment]
now using `react-select 2.0` which doesnt have this problem
