### ISSUE TITLE
Overlay a Mutation Signature on OncoPrint

### ISSUE THREAD

**Issue by DarioS** [cBioPortal/cbioportal#5520]
It would be beneficial to be able to choose a particular mutation type and add a symbol such as a vertical bar to the OncoPrint wherever it occurs. For example, being able to plot presence of C to A mutations in genes, a [somatic signature of tobacco smoking](http://science.sciencemag.org/content/354/6312/618), might be useful to head and neck cancer researchers. Someone researching melanoma might be interested in C to T mutations, [indicative of ultraviolet light](https://www.jidsponline.org/article/S1087-0024(15)30226-4/). There are a few other signatures. Perhaps it would look like

![image](https://user-images.githubusercontent.com/631218/50379923-8b235180-06ac-11e9-9ac1-d2f6886ef409.png)

**Comment by jjgao** [comment]
Hi @DarioS,

Thank you for the feature request. Visualization of mutational signatures is an area we would like to improve.

Currently, we have NT changes visualized in OncoPrint:

![image](https://user-images.githubusercontent.com/840895/50451938-1860e300-0905-11e9-9ea4-fc4200d9785e.png)

We also plan to integrate mutational signatures per sample:

https://github.com/cBioPortal/GSoC/issues/40

For your feature request, would the above be sufficient? If not, would you please explain in more details? Thanks!

**Comment by DarioS** [comment]
It would solve my analysis issue once it's released in a future version.

**Comment by jjgao** [comment]
Thanks again. Closing this for now.
