### ISSUE TITLE
save frontend states into session

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5525]
We have discussed saving frontend states into session and URL. We can start with OncoPrint. 

In general, there are two sets of states we would like to save to the session.

1. core states that are essential, ie. currently the query parameters
2. optional states

For the core states in a session, we commit to them and should be backward compatible. For optional states, if we cannot understand them, we can ignore them (e.g., if we decide to drop an optional state in a new version of oncoprint).

We could start with having all non-query parameters as optional states. one simple option would be save all states into session. Another option would be save important ones, e.g. the list of clinical attributes, sorting parameters, zooming levels, etc.

- [ ] define the UI states in a json (or yaml?)
- [ ] add the state json to url, e.g. `#states=...`
- [ ] UI change will trigger url change
- [ ] click on the link icon will generate a new session with the state

notifying @cBioPortal/product

**Comment by adamabeshouse** [comment]
Should we update the single session as each change is made, or make a new session? I think it would be unsettling to make a new session for every change, and see the hash change with every little thing you do. On the other hand, for sharing a session, you might not want someone to get your session with all the changes you made. What do you think?

**Comment by adamabeshouse** [comment]
How do these sound for starters?

For the oncoprint, we have:

- [ ] clinical tracks
- [ ] heatmap tracks
- [ ] everything that is represented by a menu, i.e. sort configuration, mutation coloring, various view options, zoom level, minimap state
- [ ] mutation coloring configuration

**Comment by jjgao** [comment]
@adamabeshouse: @alisman and I discussed long time ago and I remember we were thinking of generating a new session only when the user clicks the "link" icon.

**Comment by adamabeshouse** [comment]
@jjgao so we'd be updating the session throughout, and then when you click link it would create a session with your current state? Is that unexpected, would people want to generate a link to the state they encountered when they came into the page?

**Comment by jjgao** [comment]
@adamabeshouse not sure if I understand the question. People will still be able to generate a link when they open the session... I think at the moment when they would like to generate a link (for sharing or booking marking), it makes more sense to save the state.

**Comment by adamabeshouse** [comment]
@jjgao I think my confusion is/was, I think its intuitive to copy paste a link from the browser address bar. It would be nice if the same link in the link window was also put into the address bar. should we do that?

**Comment by jjgao** [comment]
@adamabeshouse I think that makes sense: when a user clicks the link icon, we also update the url? (maybe the browser back/forward button can allow go between the links?)

@alisman what do you think?

**Comment by jjgao** [comment]
There is some discussion about coding states into URL in #2212, which made me think of adding state into url as json format.

- [ ] define the UI states in a json
- [ ] add the state json to url, e.g. `#state=...`
- [ ] UI change will trigger url change
- [ ] click on the link icon will generate a new session with the state

**Comment by jjgao** [comment]
@adamabeshouse @alisman what do you think? Maybe we can also use the same approach for comparison page?

**Comment by Sjoerd-van-Hagen** [comment]
We could actually use the same JSON format for defining defaults in the portal properties (but allow users to supply them as YAML). This way the code and documentation to parse from URL, session service and portal properties can be the same.

**Comment by adamabeshouse** [comment]
man that could get long and ugly. is it important for it to be easily readable by the user? if not maybe we can base64 encode json in the URL

**Comment by jjgao** [comment]
@adamabeshouse I think it should be readable (not necessary easily) so that people can customize the URL for links.

**Comment by adamabeshouse** [comment]
@jjgao what do you mean customize? you mean hand-change parameters?

**Comment by jjgao** [comment]
@adamabeshouse yes, or assemble a url by themselves.

**Comment by adamabeshouse** [comment]
but is it really preferable to have giant json encoded parameter strings? how often is that really done vs building a state within the app then linking to it?

**Comment by jjgao** [comment]
@adamabeshouse I think we should just support a selected core set of states instead of adding everything in the store. As whether we should use json or yaml or another format, it's up to discussion.

Here are some requirements I can think of - it's repeating what's up there:

* A core set of states should be supported and documented
* A non-core set of states can be passed in, but if the application can ignore them if they have changed
* The states can be encoded in the request (GET or POST)
* The states can be saved with the session

**Comment by alisman** [comment]
Just wanted to float the idea of both having a "session" stored by session service, and then also so url parameters in which a user can deep link particular view parameters (e.g. sorting, maybe even group on/off).  This way we don't want to update the persistant sessions every time the user makes a small change.  So, it would look something like this:

comparison/?sessionId=xxxxx&hiddenGroups=group1,group2&sortSomething=up

**Comment by jjgao** [comment]
@alisman yes, good idea. (I proposed that above too :)

I guess we are more comfortable with &-delimited parameters in the url? If so, let's move forward with that.

**Comment by alisman** [comment]
@jjgao sorry for repeating you!  so, when a user first clicks "compare," do we create a session?  if not how do we store the spec?  could be localstorage or url hash or even js memory.  we just have to decide if user needs to be able to refresh (devs want to refresh!)   
then, once user gets to comparison session, what are the actions which would result in a new session (as opposed to just altered url params?).   once new groups are "saved" that would obviously need to do it.  are there any other things?

**Comment by jjgao** [comment]
@alisman this ticket was originally for the Results page, but it can apply to Comparison page too.

Session service will be required, so we will always create a session for Comparision page. A new session will be created when the user click the link icon. (@adamabeshouse I think we don't need to save concept with parameters in url)

**Comment by adamabeshouse** [comment]
@jjgao I think I am confused about the final list of tasks for this. Could you please summarize/consolidate? Is this still a priority?

**Comment by jjgao** [comment]
@adamabeshouse let me think it over.

**Comment by jjgao** [comment]
@adamabeshouse let's discuss this.

**Comment by alisman** [comment]
worth noting that with URLWrapper, we can now distinguish between core
params that should be in session and those that should not

**Comment by alisman** [comment]
@jjgao core "query" params are (as before) stored in session (when session is necessary).  "Non-query" params e.g. heatmap selection or sorting, are stored in URL.   
This also works on group comparison page.
