### ISSUE TITLE
change up/down-regulation to high/low

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5529]
mRNA and protein up/down-regulation is confusing as it indicates that the gene is dysregulated in the sample (discussed in #5528). 

![image](https://user-images.githubusercontent.com/840895/50489453-bcb25a80-09d5-11e9-980a-bcd7a01d9aa5.png)

Let's change them to high/low in the following tabs: OncoPrint, Cancer Types Summary, and Download. 

@schultzn

**Comment by jjgao** [comment]
@schultzn ok if we start to change to "mRNA high" and "mRNA low"?

**Comment by schultzn** [comment]
Yes. Similar for protein?

**Comment by dippindots** [comment]
@jjgao Ok, I will do this week!
