### ISSUE TITLE
example links

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5532]
- [All TCGA Pan-Cancer](http://www.cbioportal.org/study?id=laml_tcga_pan_can_atlas_2018%2Cacc_tcga_pan_can_atlas_2018%2Cblca_tcga_pan_can_atlas_2018%2Clgg_tcga_pan_can_atlas_2018%2Cbrca_tcga_pan_can_atlas_2018%2Ccesc_tcga_pan_can_atlas_2018%2Cchol_tcga_pan_can_atlas_2018%2Ccoadread_tcga_pan_can_atlas_2018%2Cdlbc_tcga_pan_can_atlas_2018%2Cesca_tcga_pan_can_atlas_2018%2Cgbm_tcga_pan_can_atlas_2018%2Chnsc_tcga_pan_can_atlas_2018%2Ckich_tcga_pan_can_atlas_2018%2Ckirc_tcga_pan_can_atlas_2018%2Ckirp_tcga_pan_can_atlas_2018%2Clihc_tcga_pan_can_atlas_2018%2Cluad_tcga_pan_can_atlas_2018%2Clusc_tcga_pan_can_atlas_2018%2Cmeso_tcga_pan_can_atlas_2018%2Cov_tcga_pan_can_atlas_2018%2Cpaad_tcga_pan_can_atlas_2018%2Cpcpg_tcga_pan_can_atlas_2018%2Cprad_tcga_pan_can_atlas_2018%2Csarc_tcga_pan_can_atlas_2018%2Cskcm_tcga_pan_can_atlas_2018%2Cstad_tcga_pan_can_atlas_2018%2Ctgct_tcga_pan_can_atlas_2018%2Cthym_tcga_pan_can_atlas_2018%2Cthca_tcga_pan_can_atlas_2018%2Cucs_tcga_pan_can_atlas_2018%2Cucec_tcga_pan_can_atlas_2018%2Cuvm_tcga_pan_can_atlas_2018)
- [MSK-IMPACT clinical cohort, Zehir et al. 2017](http://www.cbioportal.org/study?id=msk_impact_2017)
- [Histone mutations across cancer types](https://www.cbioportal.org/study?id=5c26a970e4b05228701f9fa9)

**Comment by jjgao** [comment]
@inodb let's hold off adding the oncohistone links since the paper of the dataset is still being finalized.

**Comment by jjgao** [comment]
The oncohistone paper will be out on 3/20 Wed. @inodb could you schedule this for the same day?

**Comment by inodb** [comment]
Sure

**Comment by inodb** [comment]
@jjgao 	it seems like the histone session isn't working anymore http://www.cbioportal.org/results/oncoprint?session_id=5c38ba56e4b09ccddade62ee . Do we need a session id for this one?
