### ISSUE TITLE
virtual study not work

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5533]
It was a virtual study I previously saved in public portal.

http://www.cbioportal.org/study?id=5b5e3272498eb8b3d5672653

![image](https://user-images.githubusercontent.com/840895/50519560-81716380-0a89-11e9-889b-fcf01ea4c746.png)

**Comment by zhx828** [comment]
@jjgao this issue is now fixed and deployed.

**Comment by jjgao** [comment]
It was because of renaming of study, the coad and rect tcga pancan study were merged into one.
