### ISSUE TITLE
SV should give user option when some sample are not available in the virtual study

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5534]
Often time, after user created the virtual study, some samples maybe removed, updated from origin studies. In current implementation, we only say they are no longer available anymore. But it would be nice to give an option to update the study.

There are two solutions here:
1. Allow user remove all unavailable samples
2. Apply original filters on selected studies and update the sample list

**Comment by jjgao** [comment]
We may want to provide both options.

1. If studies do not exist, warn user: "We were not able to find the studies xxx and yyy. It is possible that they were removed or renamed, or that you don't have access to them" and give the option to remove the study from the virtual study _if they are the owner_ of the VS.
2. If samples are updated, let user know "xx smaples were missing and yy new samples meet the filtering criteria." and "Click to update"  _if they are the owner_ of the VS.

Also be mindful that for a shared virtual study, we may not want to allow update if it's not a owner. Alternatively, we could always create new virtual studies. Let's discuss more before we implement. cc'ing @kalletlak too.
