### ISSUE TITLE
custom selection only work for the first study

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5535]
1. http://www.cbioportal.org/study?id=chol_nccs_2013%2Cchol_nus_2012
2. Custom Selection (or Add Chart -> Custom Groups):
```
chol_nccs_2013:1202
chol_nus_2012:B085
```
3. only one sample is selected
![image](https://user-images.githubusercontent.com/840895/50525100-631a6080-0aa7-11e9-83a0-ed3e2ae03c51.png)

**Comment by zhx828** [comment]
@jjgao this issue is solved and deployed.
