### ISSUE TITLE
Add icons to the Results View tabs

### ISSUE THREAD

**Issue by ersinciftci** [cBioPortal/cbioportal#5536]
Something like:
<img width="1670" alt="screen shot 2018-12-28 at 5 12 25 pm" src="https://user-images.githubusercontent.com/3595704/50530089-873a6980-0ac8-11e9-8698-29727911c214.png">

Needs to be discussed further. These are the icons in font family that we are using:
https://fontawesome.com/v4.7.0/icons/

**Comment by jjgao** [comment]
notifying @cBioPortal/product @cBioPortal/frontend

**Comment by adamabeshouse** [comment]
To me, it feels a little cluttered, but I do like it. Maybe we can reduce the icon opacity?
