### ISSUE TITLE
Connection pool config block does not show up in GitBook manual

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#5540]
The section on [setting up the database connection pool](https://docs.cbioportal.org/2.1-deployment/deploying#set-up-the-database-connection-pool) doesn't show any of the XML tags you can see there [on GitHub](https://github.com/cBioPortal/cbioportal/blob/v1.18.1/docs/Deploying.md#set-up-the-database-connection-pool); only the ellipses show up.

I suspect that GitBook does not recognise the [indented code block](https://spec.commonmark.org/0.28/#indented-code-blocks) syntax there, and instead interprets it as an [HTML block](https://spec.commonmark.org/0.28/#html-blocks) to be parsed by the browser. If that's the case, it should be easy to fix using a [fenced code block](https://spec.commonmark.org/0.28/#fenced-code-blocks), and it might be worth checking whether the other indented code blocks in the deployment steps show any issues.

**Comment by inodb** [comment]
hmm looks like this is still an issue?

**Comment by inodb** [comment]
still an issue

**Comment by fedde-s** [comment]
@inodb, in the current version, I no longer see a section about Tomcat config on the page I originally linked at all. Have those docs moved to a different location (and should I edit the issue summary), or is deploying with Tomcat just no longer documented?

**Comment by fedde-s** [comment]
A quick skim of the commit history tells me that the docs that this issue was about disappeared in commit [`2fa5d60`](https://github.com/cBioPortal/cbioportal/commit/2fa5d60c3e9a41a465955153a77ffa6b6c49207b#diff-6739856a39f19565ba4fc51883602195) (release v3.0.0), and before that, the issue might have been fixed in f343178d078918ffd643aedb8f849f2faae3716d (release v2.2.1). Is that correct?
