### ISSUE TITLE
define the data structure of a custom group

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5541]
the data structure of a custom group could be very similar to virtual study). A custom group should have it's own document in mongodb with a field linking to its parent study. 

Note a custom group will always belong to one study or virtual study.

**Comment by jjgao** [comment]
@kalletlak could you add a mock data for the current virtual study and we can start from there?

**Comment by kalletlak** [comment]
This is how it looks in mongoDB. And seems like filter object is outdated, need to replace it with new StudyView filter object
```
{
  "id": "xyz",
  "data": {
    "name": "test",
    "description": "test",
    "studies": [
      {
        "id": "study_1",
        "samples": [
          "sample_1",
          "sample_2"
        ]
      },
      {
        "id": "study_2",
        "samples": [
          "sample_1",
          "sample_2"
        ]
      }
    ],
    "filters": {
      "patients": {},
      "samples": {}
    },
    "owner": "xxx",
    "origin": [
      "study_1",
      "study_2"
    ],
    "created": 1546969195937,
    "users": [],
    "version": 1
  },
  "source": "localhost",
  "type": "virtual_study"
}
```

**Comment by kalletlak** [comment]
@jjgao I have couple of questions

1. does user needs to be logged in to save group (I mean is this feature only for authenticated portal)?
2. about `Note a custom group will always belong to one study or virtual study.`, what if user tries to query multiple studies( without saving it as a virtual study) and save a new group -> to which study is this group mapped to?

**Comment by jjgao** [comment]
> 1. does user needs to be logged in to save group (I mean is this feature only for authenticated portal)?

Yes

> 2. about Note a custom group will always belong to one study or virtual study., what if user tries to query multiple studies( without saving it as a virtual study) and save a new group -> to which study is this group mapped to?

I don't have a good solution for that. I could think of three options when multiple studies/virtual studies are present:

1. Allow associate a custom group with multiple studies. 
2. Allow saving groups but only temporarily (not saving to session service) -- it won't load up next time the the same studies are opened.
3. Don't give the option for saving groups at all.

# 1 can be confusing. For example, a group can be saved for studies A&B. When we open A or B, we will not see it. When we open A and B and C, should we list it? Or do we only list it when when opening A&B?

# 2 may also be confusing. If I spent time creating the groups and next time it's gone, it's frustrating.

**Comment by jjgao** [comment]
@kalletlak could you also add an example file for a query session?

**Comment by kalletlak** [comment]
query session objects can contain any fields(no validation)
here are couple of examples
1. for single-study query
```
{
  "id": "xyx",
  "data": {
    "Action": "Submit",
    "genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION": "blca_tcga_pub_gistic",
    "Z_SCORE_THRESHOLD": "2.0",
    "genetic_profile_ids_PROFILE_MRNA_EXPRESSION": "blca_tcga_pub_rna_seq_v2_mrna_median_Zscores",
    "tab_index": "tab_visualize",
    "data_priority": "0",
    "case_set_id": "blca_tcga_pub_3way_complete",
    "gene_list": "ALK%20MYC%20TP53",
    "RPPA_SCORE_THRESHOLD": "2.0",
    "cancer_study_list": "blca_tcga_pub",
    "geneset_list": " ",
    "genetic_profile_ids_PROFILE_MUTATION_EXTENDED": "blca_tcga_pub_mutations"
  },
  "source": "localhost",
  "type": "main_session"
}
```
2. for multi-study query
```
{
  "id": "xyz",
  "data": {
    "Action": "Submit",
    "show_samples": "false",
    "Z_SCORE_THRESHOLD": "2.0",
    "clinicallist": "CANCER_STUDY,PROFILED_IN_COPY_NUMBER_ALTERATION,PROFILED_IN_MUTATION_EXTENDED",
    "tab_index": "tab_visualize",
    "data_priority": "0",
    "case_set_id": "all",
    "gene_list": "ALK%20MYC%20TP53",
    "RPPA_SCORE_THRESHOLD": "2.0",
    "cancer_study_list": "blca_tcga_pub,blca_dfarber_mskcc_2014",
    "geneset_list": " "
  },
  "source": "localhost",
  "type": "main_session"
}
```

**Comment by jjgao** [comment]
I think the virtual study format is exact what we need here too. Comments?

```json
{
  "id": "xyz",
  "data": {
    "name": "test",
    "description": "test", // not sure if we need this
    "studies": [ // physical studies
      {
        "id": "study_1",
        "samples": [
          "sample_1",
          "sample_2"
        ]
      },
      {
        "id": "study_2",
        "samples": [
          "sample_1",
          "sample_2"
        ]
      }
    ],
    "filters": {
      "patients": {},
      "samples": {}
    },
    "owner": "xxx",
    "origin": [ // studies in which the custom group was created, initially only one should be allowed
      "study_1",
      "study_2"
    ],
    "created": 1546969195937,
    "users": [],
    "version": 1
  },
  "source": "localhost",
  "type": "custom_group"
}
```
