### ISSUE TITLE
support custom groups in session service

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5542]
data model defined in #5541

- [x] save
- [x] load by study ID and user email
- [x] update (name, sample list)

**Comment by jjgao** [comment]
@kalletlak maybe you can help with this one since you are familiar with session service?

**Comment by kalletlak** [comment]
@jjgao sure!
btw should we allow saving group for unauthenticated or non-logged users

**Comment by jjgao** [comment]
@kalletlak good question. My instinction is that we should not save groups if a user is not logged in -- the same reason as virtual study. That would mean only logged in users can create groups.
