### ISSUE TITLE
custom group management

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5544]
- [x] UI for managing the custom groups
  - `Select` Button will select all samples in the selected groups in the study view page
  - `Compare` button will lead to the Comparison page
  - `Delete` button will delete the groups and a restore button should show once.
- [x] Only groups matching the study and user email will be listed

![image](https://user-images.githubusercontent.com/840895/50664920-c5c69d00-0f7c-11e9-9852-5821b2215004.png)

Similar to virtual study, a restore button should show after deletion just once.
![image](https://user-images.githubusercontent.com/840895/51955851-617be980-2413-11e9-947f-f0e1a5d757cf.png)

**Comment by adamabeshouse** [comment]
@jjgao does that hamburger icon above the scrollbar mean anything?

**Comment by jjgao** [comment]
@adamabeshouse that doesn't mean anything. I was thinking of having a settings icon for all chart. Please ignore it.

I also updated the requirement for delete above.

**Comment by jjgao** [comment]
From @kalletlak for `delete`:

"actually we do not delete anything that’s stored into session-service. we just remove access for the user to that particular virtual study. we could do the same even for group"

**Comment by adamabeshouse** [comment]
As discussed in Slack with @jjgao, we will allow group Restore after Delete until the panel is closed.
