### ISSUE TITLE
Comparison page framework

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5551]
The framework of Comparison page could be similar to Results page.

We can have a display the Study with the groups on top and comparison tabs below. #5579

Let's use `/comparison` as the url.

**Comment by jjgao** [comment]
@kalletlak @adamabeshouse @alisman : I made a mock up for this.

![image](https://user-images.githubusercontent.com/840895/51342776-c07c4e80-1a62-11e9-808e-25761fb3ad6c.png)

**Comment by jjgao** [comment]
@adamabeshouse that should be an option for the user -- the checkbox after the group selection. By default, it should be selected, b/c when comparing groups, usually, we don't want to compare the same samples :)

For Overlapping tab, we should always use all the samples and thus the note down there when the checkbox is checked.

**Comment by adamabeshouse** [comment]
@jjgao 
ah, I see, thanks!

also, what should be the interface for selecting the two enrichment profiles? should it be inside the enrichment tabs? should they persist across enrichment tabs, or be selected separately for each one?

**Comment by jjgao** [comment]
@adamabeshouse let's do it on the page level. 

In this design, the groups can be toggled. @alisman may be able to come up with a better design for selecting groups.
![image](https://user-images.githubusercontent.com/840895/51351211-3c34c600-1a78-11e9-8232-467df3397781.png)

If there are two groups, Enrichments can be performed. Otherwise (1 group, or >2 groups selected), we should still show the tabs if data is available, but render them differently and show tooltip that "Mutations enrichments analysis is only available when comparing two groups".
