### ISSUE TITLE
Survival tab in Comparison page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5553]
We should reused the component in Results and Study View.

**Comment by kalletlak** [comment]
@jjgao How should we deal with groups with overlapping samples in survival plots?

**Comment by jjgao** [comment]
As discussed, we will handle overlapping samples on the page level, ie. the page will only decide whether to send non-overlapping groups (by default, we should do that). The survival component can take the groups of samples (overlapping or not), and pull data, and visualize.

The same for other tab.
