### ISSUE TITLE
Copy-Number tab in Comparison page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5556]
We will only display results in this tab when there are two groups to compare. We can still display the tab with a different style and some information to explain.

- [x] use the same component as Enrichments/Copy-number tab in Results page
- [ ] support this tab when querying multiple physical studies

**Comment by alisman** [comment]
@jjgao i think the second checkbox of this is followup?

**Comment by jjgao** [comment]
yes: https://github.com/cBioPortal/cbioportal/issues/5680
