### ISSUE TITLE
whole slide viewer clinical attribute (msk)

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#5560]
We've recently introduced a whole slide viewer (computational pathology slide viewer) url for msk-impact samples.  We are working with the CVR team to clean some of the data, but there are samples with valid URLs:
[P-0035379-cbioportal](https://cbioportal.mskcc.org/patient?studyId=mskimpact&caseId=P-0035379#navCaseIds=mskimpact:P-0035379)
[P-0035379-whole-slide-viewer](https://slides-res.mskcc.org/viewer?ids=1163404.svs@annotation=off)

![image](https://user-images.githubusercontent.com/366003/51046670-b35bed00-1594-11e9-8961-d2fa949a7508.png)

Front-end development to link/embed the whole slide viewer can proceed.

**Comment by jjgao** [comment]
@alisman please prioritize this one.

**Comment by jjgao** [comment]
@dippindots please add it as an i-frame to patient view similar to http://www.cbioportal.org/patient?studyId=ucec_tcga_pub&caseId=TCGA-BK-A0CC. We only need it for the mskimpact study on the msk portal.

**Comment by jjgao** [comment]
@n1zea144 @angelicaochoa : @dippindots is almost done with the frontend part. We have a small issue. For patients with multiple samples and multiple slides, we will need to need to change the URL to have all the IDs. We are wondering if it makes sense to change the attribute to path_slide_ids instead of url and we can assemble the url in the frontend?

**Comment by angelicaochoa** [comment]
@jjgao I would be fine with that. I'll wait for @n1zea144 to comment

**Comment by jjgao** [comment]
@angelicaochoa thanks, let's wait for @n1zea144's comment.

**Comment by jjgao** [comment]
@n1zea144 will add an additional MSK_SLIDE_ID attribute. Once we have that, @dippindots please change your code. Then we can delete the current attribute.
