### ISSUE TITLE
study view - combined study view shows blank charts

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5565]
Go to http://www.cbioportal.org/study?id=brca_mbcproject_wagle_2017%2Cbrca_tcga_pan_can_atlas_2018

Click the plus sign to view the studies that are present. Click on the TCGA study. It will open in the same page. Then click the back button. Scroll down, and there are now many empty plots, which represent the charts that were visible in the TCGA study view but were not shown in the original combined study.

Bottom of study view upon first load:
![image](https://user-images.githubusercontent.com/10508276/50793062-f6684880-1294-11e9-9537-db3cf58f8a32.png)

Bottom of study view after clicking on TCGA and then going back:
![image](https://user-images.githubusercontent.com/10508276/50793093-113abd00-1295-11e9-9b3d-3964e7c704d3.png)

**Comment by zhx828** [comment]
@tmazor @jjgao just cross referencing another issue related to this. If we open a new tab when click on the study link, this issue will go away.
Questions here:
- Should I open a new tab? @tmazor please see discussion here https://github.com/cBioPortal/cbioportal/issues/5480
- If yes, do I still need to fix this issue?
