### ISSUE TITLE
study view - chart priority in combined study

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5567]
Combined/virtual studies appear to respect the priority of specific charts from each study. While overall I think this is reasonable, I think we should consider some additional metrics, including data availability.

Go here: http://www.cbioportal.org/study?id=5c33c0a1e4b09ccddade5b4f

The majority of visible charts are N/A for ~95% of samples. These charts all come from the MBC project which has assigned them a high priority. Looking at other charts under "Add Chart", there are many charts with higher data availability that would be more appropriate to see (e.g. Sample Type).

Perhaps this conversation has already been had, but I wonder if there is some combination of availability + priority that we can use to improve the loading of charts in combined studies?

@jjgao @schultzn @zhx828 @alisman

**Comment by zhx828** [comment]
@tmazor we did have the conversation, and it was exactly you want to implement. But for bigger studies, the data availability cannot be retrieved in a desired amount of time. So we decided to only calculate the availability when user tries to add a new chart.

**Comment by jjgao** [comment]
@zhx828 I am wondering if we should reorganize charts once we load up all data?

**Comment by zhx828** [comment]
@jjgao I think depends on whether user has looked at charts yet. If will create confusion when we reshuffling the charts. Or we could add a button to allow user reshuffles the charts. Or automatically reshuffling but give a message if did so.

**Comment by jjgao** [comment]
@zhx828 I usually don't do anything before all the data are loaded. Maybe we can have another step to reshuffle the data once they are loaded. We can actually tell the user we are doing that in the message. 

@tmazor what do you think?

**Comment by zhx828** [comment]
@jjgao @tmazor quick note here, we are not loading data availability by default in the initial loading. Only after user clicks the `Add Chart` button

**Comment by jjgao** [comment]
Ideally, we further improve the performance of "data availibility" api and then we can take that into consideration too. Maybe that should be the way to go.

cc'ing @ersinciftci @n1zea144

**Comment by ersinciftci** [comment]
Not sure if there is much wiggle room in the data availability API, I already rewrote it in an optimized way and now MSK-IMPACT takes around 1 sec and Genie takes 5 secs.

**Comment by jjgao** [comment]
It may require some fundamental change to db or caching. @n1zea144 and I are thinking of caching all json results from api (buying a lot of disk space).

**Comment by zhx828** [comment]
@jjgao for the next step, we could do the following?

### The way of sorting clinical attributes
#### For single study
1. Sort by Priority
2. Sort by Clinical Attribute Display Name

#### For multi-studies
1. Sort by study view frontend defined default priorities (the priority defined in the backend for each study will be ignore)
2. Sort by data availability
3. Sort by Clinical Attribute Display Name

**Comment by jjgao** [comment]
@zhx828 I think sort by data availability can be used for single study as well. But is it practical to do that now?

**Comment by zhx828** [comment]
@jjgao it definitely brings some delay, MSK internal average 2.5s, Genie average: 3.5s. It's not really preferred at the moment for bigger studies, but we could draw a line base on number of clinical attributes * number of samples. But small studies are definitely doable.

**Comment by jjgao** [comment]
@zhx828 for large study (msk impact), maybe 2.5s is fine as it won't impact subsequent selections. Let's discuss.

**Comment by tmazor** [comment]
This is still an issue

**Comment by jjgao** [comment]
@zhx828 @kalletlak let's try the proposal @zhx828 had above. But given that we have many other tasks and this one may needs some research and exploration, let's delay it one more time.
