### ISSUE TITLE
define the input for the comparison page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5574]
In the most generic form, it can be a list of groups of samples. The data format of a "group of sample" can be a simplified version of as [custom group](https://github.com/cBioPortal/cbioportal/issues/5541), e.g.

```json
[
{
 "name": "group name",
 "studies": 
 [
  {
   "id":"study_id1",
   "samples":
   ["s1", "s2", ...]
  }, 
  {
   "id":"study_id2",
   "samples":
   ["s10", "s20", ...]
  }, 
  ...
 ]
},
...
]
```

In the future, we can also support filters to define groups of samples.

**Comment by jjgao** [comment]
@adamabeshouse could you paste an example format you are using?

**Comment by adamabeshouse** [comment]
@jjgao the representation Im using is

```
export type SampleGroup = {
    id:string,
    name?:string,
    sampleIdentifiers:SampleIdentifier[],
    color?: string;
    legendText?: string;
};
```

**Comment by jjgao** [comment]
Thanks, @adamabeshouse. 

Two discussion points:
- should use the same structure for custom group and the input to comparison page?
- In any case what would be the data structure(s)?

Maybe we should have a call on this since it's so fundamental? @adamabeshouse @kalletlak @alisman

**Comment by jjgao** [comment]
We decided to use a list of groups as input defined in https://github.com/cBioPortal/cbioportal/issues/5541
