### ISSUE TITLE
save comparison sessions into session service

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5578]
Similar to query sessions, we should save a comparison session (#5574) to session service. 

http://cbioportal.org/comparison?session_id=xxxxdkdkekkk

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2077

**Comment by kalletlak** [comment]
@adamabeshouse its implemented right, should we close this?
