### ISSUE TITLE
genie samples are mislabeled as "not profiled in mutations"

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5583]
I don't know if this is a data issue or an OncoPrint issue, but something is definitely wrong:

Go to this link, zoom in, and take a look at the first case in the OncoPrint:
http://www.cbioportal.org/genie/results/oncoprint?clinicallist=NUM_SAMPLES_PER_PATIENT%2CPROFILED_IN_genie_public_cna&session_id=5c36516be4b09ccddade5f14&show_samples=true

Hover over SOS1 for the first sample - it says "Not Profiled in Somatic Mutations". However, this sample was profiled for somatic mutations (click on the patient link or just notice the fusion called in EGFR), but SOS1 isn't on the gene panel that the sample was profiled with.
![image](https://user-images.githubusercontent.com/10508276/50925479-70790880-1420-11e9-8782-58830888a1cb.png)

This sample (and many others) should be appearing as not profiled. Why are they appearing as if they were profiled for copy number but not mutations?

**Comment by ritikakundra** [comment]
@tmazor: In 4.1 the CNA profiling in the matrix file was not part of the file coming in from SAGE. Therefore it was using WXS as default and stating it is profiled in CNA. But Sage has now added the CNA profiling data in the matrix file so with 5.0 update, this will be rectified.

**Comment by tmazor** [comment]
Thanks for the explanation @ritikakundra. When will the 5.0 update be released? Is it possible to update this sooner? Until that point, we're showing incorrect data to our users.

**Comment by tmazor** [comment]
@jjgao @schultzn do you know when the next GENIE data will be released? I'm concerned about the consequences of not having correct gene panel data for CNAs in the current public release.

**Comment by ritikakundra** [comment]
@tmazor 5.0 is out now. Can you check your link again? (I think its fixed now)

**Comment by tmazor** [comment]
yup, it is fixed now! thanks @ritikakundra
