### ISSUE TITLE
why the origin of virtual study is the list of studies?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5587]
wy do we need it if we already encoded them in the `studies` field?

![image](https://user-images.githubusercontent.com/840895/50844405-a80c8580-1338-11e9-8eea-a666a5305830.png)

**Comment by jjgao** [comment]
What do we store in orgin for query sessions?

**Comment by kalletlak** [comment]
`studies` represent physical studies in that virtual study. We need origin to track on how a virtual study is created(if its created from another virtual study)

**Comment by jjgao** [comment]
@kalletlak I see. I was confused and thought was was meant to be the Origin in the html request header.
