### ISSUE TITLE
Study view gene query box: can we eliminate the automatically added semi-colons?

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5590]
This applies only when a user selects genes from the tables.

This looks nice:
![image](https://user-images.githubusercontent.com/11892704/50944034-d1263680-145c-11e9-9a0c-40c64c887fe7.png)

But once you want to edit it and click into the box, it converts to one gene per row with a semi-colon.

![image](https://user-images.githubusercontent.com/11892704/50944087-06cb1f80-145d-11e9-9443-991f7f9ec96d.png)

Can we simply add genes in a single row? That would make it much easier to add a few genes from the tables and then add some more by hand.

**Comment by zhx828** [comment]
@schultzn @jjgao I can change to one line separate by space. But base on our design, after validating the query fragment, we always attach a semicolon afterward. Is it ok showing as `APC; TP53; BRAF:600E;`?

**Comment by schultzn** [comment]
But we don’t do that on the main query page, do we?

**Comment by zhx828** [comment]
@schultzn the box is inline with the query box in the query page. Just consulted with @adamabeshouse : that semicolon is essential when you have a mutation for the gene. So we can do here is to remove the semicolon when there is no mutation attached. The query will look like `APC TP53 BRAF:V600E; EGFR`

**Comment by adamabeshouse** [comment]
not just mutation but any alteration - if you have the form `GENE:` with the colon, you'll need a semicolon to do another gene on the same line

**Comment by schultzn** [comment]
Thanks!

**Comment by zhx828** [comment]
@schultzn this issue is fixed and deployed.
