### ISSUE TITLE
Graph ML comments are out of date

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#5595]
If I navigate to:  http://www.cbioportal.org/results/network?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=gbm_tcga&case_set_id=gbm_tcga_cnaseq&data_priority=0&gene_list=EGFR&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=gbm_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=gbm_tcga_mutations&tab_index=tab_visualize

and click the network tab, I can then click the GraphML link.

The GraphML document that is generated has some comments at the beginning, e.g. 

This entire comment is out of date and should be deleted.

**Comment by jjgao** [comment]
@alisman not high priority if tricky to fix.

**Comment by alisman** [comment]
Network tab will be taken down 11/1. Closing this issue.
