### ISSUE TITLE
profiled in mutations/copy number tracks don't always appear

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5599]
Start in a combined study like this one: http://www.cbioportal.org/study?id=paad_icgc,paad_qcmg_uq_2016,paad_tcga_pan_can_atlas_2018

Run a query from study view, and there will be a "Profile in..." track:
![image](https://user-images.githubusercontent.com/10508276/51053248-28382280-15a7-11e9-9cf3-b205377db0ea.png)

Return to study view and apply a filter (e.g. TP53 mutations) and then run a query. There is no "Profiled in" track, even though there should be:
![image](https://user-images.githubusercontent.com/10508276/51053397-86650580-15a7-11e9-9134-dfeb0f4829f6.png)

**Comment by adamabeshouse** [comment]
merged to `master`
