### ISSUE TITLE
some filters break study view

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5600]
Go here: http://www.cbioportal.org/study?id=paad_icgc,paad_qcmg_uq_2016,paad_tcga_pan_can_atlas_2018

Select Sex = Male

Watch the page fail to reload and go blank.

This only happens for certain filters. Filtering for Person Gender = Male works but Person Gender = NA fails.

**Comment by zhx828** [comment]
In this case, study `paad_tcga_pan_can_atlas_2018` has CNA data but not the rest of two.
`paad_tcga_pan_can_atlas_2018` uses `Person Gender`
`paad_icgc,paad_qcmg_uq_2016` `paad_tcga_pan_can_atlas_2018` use `Sex`

So when you chose `Male` from `Sex` attribute, the page wants to load CNA data but not available.

I will schedule a fix. @tmazor @jjgao I will show `0 w/ CNA data` on the top.

**Comment by zhx828** [comment]
@tmazor @jjgao the issue has been fixed and deployed, but fount another backend related issue(https://github.com/cBioPortal/cbioportal/issues/5603)
