### ISSUE TITLE
API 500 in study view

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5603]
After fixing issue(https://github.com/cBioPortal/cbioportal/issues/5600), I notice the `api/cna-genes/fetch` returns 500 after selecting `Male`

Reproduce:
- Go here: http://www.cbioportal.org/study?id=paad_icgc,paad_qcmg_uq_2016,paad_tcga_pan_can_atlas_2018
- Select Sex = Male
- Take a look the Network

**Comment by jjgao** [comment]
@zhx828 is it creating issues for frontend? Do we need to fix it soon?

**Comment by zhx828** [comment]
@jjgao we need to fix it soon. The CNA table does not get any information.

**Comment by jjgao** [comment]
@ersinciftci do you think you'll have time to handle this?

**Comment by ersinciftci** [comment]
@jjgao I'll try to look at it tomorrow
