### ISSUE TITLE
Tags endpoint called for each study on homepage

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5606]
The `/tags` endpoint is called for each study on the homepage: www.cbioportal.org/beta . Seems a little heavy? Not sure if this was on purpose?

CC: @oplantalech @alisman @ersinciftci

**Comment by oplantalech** [comment]
It is done on purpose. The endpoint is only being called once you hover the "i" icon and the tooltip needs to be displayed: https://github.com/cBioPortal/cbioportal-frontend/pull/1709/files#diff-5c2cfb79ecda2a8ec518e588e2491ff4R46

**Comment by alisman** [comment]
@oplantalech it would seem Ino is right:
![image](https://user-images.githubusercontent.com/186521/51259964-34432c00-197b-11e9-85e8-ccb46224d91d.png)
Tags endpoint gets called three times without any interaction with the icons at all.

**Comment by oplantalech** [comment]
@alisman @inodb That's interesting. According to the code I wrote, the endpoint should only be called when hovering the tooltip... It is not called anywhere else

**Comment by jjgao** [comment]
@oplantalech why can't we just return the tag data together with the study meta data? It's useful for search too.

**Comment by jjgao** [comment]
@oplantalech @pieterlukasse I added a follow-up ticket for searching tags: https://github.com/cBioPortal/cbioportal/issues/5684
