### ISSUE TITLE
Text cropping of labels in study-overview pie chart qtip

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#561]
Longer labels are cropped, see attached image from a colleague. Is there a reason to crop them? What are we saving the screen space for?
![clinical_sum statistics_name_abbrev](https://cloud.githubusercontent.com/assets/5654699/11626538/d868a728-9ce3-11e5-8f93-3b51b50275e9.png)

**Comment by zhx828** [comment]
We are trying to make the study view more clean and organized. We can of course make the table wider, but the name of each category is not unpredictable, we still need a limit for the width.

**Comment by zhx828** [comment]
@j-hudecek what do you think? Any updates on this issue?

**Comment by j-hudecek** [comment]
My point was that since it's a popup there isn't a limit on how big the table should be. You can't really rely on being able to see anything else because it can be placed in any position in relation to the original pie chart. It's hardcoded to width 300. Is it possible to make it grow with the text to say max-width 500?
