### ISSUE TITLE
skml_tcga has NA for z-scores of some genes

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5615]
In skml_tcga, EIF2A, AHNAK and DDX3Y are all "NA" for z-scores, even though all 3 genes have expression data.

This issue was flagged by a user: https://groups.google.com/forum/#!topic/cbioportal/RPEBkuhIgus

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #534](https://github.com/cBioPortal/datahub/issues/534) via [**ZenHub**](https://www.zenhub.com/)
