### ISSUE TITLE
Adding clinical data on GENIE is slow

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5617]
From Chrome Network, I can see that we are only loading the clinical data for the selected clinical attribute. Is that right? @adamabeshouse 

If so, I guess it is b/c the backend API to load clinical data is slow?

BTW, maybe we can change the message when only loading clinical data?

![image](https://user-images.githubusercontent.com/840895/51269100-986feb00-198f-11e9-8f83-1bdcdf568ec9.png)

**Comment by adamabeshouse** [comment]
@jjgao yes, it does look like we're just loading data for the selected attribute. I guess the API is slow for that many samples. I'll make a change to just say clinical data if that's all thats loading

**Comment by jjgao** [comment]
Thanks, @adamabeshouse.

@ersinciftci do you think there is any obvious way to further improve the performance of the clinical API?

Also adding @n1zea144 to this.

**Comment by ersinciftci** [comment]
@jjgao Unfortunately I don't see an obvious way. And it's not something we can pre-calculate either.
