### ISSUE TITLE
add gene columns to sample matrix

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5618]
With recent updates to the downloads tab, we have made it more complicated for a user to determine if a gene is altered (by any type of alteration) in a particular sample. Let's add that information to the sample matrix.

We can add columns to the sample matrix that summarize the alteration status of each gene -- so one column per queried gene, with 0 or 1 to indicate if the sample has any alteration in that particular gene.

This stems from a user request: https://groups.google.com/forum/#!topic/cbioportal/jvYFOglkKas

**Comment by jjgao** [comment]
It maybe a good idea to add additional columns, one gene per column in this file:

![image](https://user-images.githubusercontent.com/840895/51283705-0f6caa00-19b7-11e9-8823-8f4dc0d993f9.png)

@dippindots it's not urgent.
