### ISSUE TITLE
support single filter parameters for study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5621]
http://www.cbioportal.org/beta/newstudy?id=msk_impact_2017#filterAttributeId=CANCER_TYPE&filterValues=Pancreatic Cancer;Breast Cancer

Q: what if there is a `;` in the value?

**Comment by jjgao** [comment]
This is a simple solution to support one filter. Multiple filters will be supported in #4983.

**Comment by zhx828** [comment]
@jjgao ';' would not allowed to use in the case you mentioned. This is designed for a quick filter, I don't think we should consider too much here. If there is special character, then probably #4983 is a better solution to go.

**Comment by zhx828** [comment]
@jjgao for continuous data, this will be the format `http://www.cbioportal.org/study?id=nsclc_tcga_broad_2016&filterAttributeId=AGE&filterValues=60-65,70-75`

And we only support clinical data for now?

**Comment by jjgao** [comment]
@zhx828 sounds good.

**Comment by zhx828** [comment]
@jjgao I just noticed in the example you posted, `filterValues:Pancreatic Cancer;Breast Cancer`, different value you want to use semicolon over comma? Also it should be `=` instead of `colon`?

I have a working instance here http://cbioportal-frontend-pr-1935.herokuapp.com/study?id=msk_impact_2017&filterAttributeId=CANCER_TYPE&filterValues=Pancreatic%20Cancer,Breast%20Cancer

**Comment by jjgao** [comment]
@zhx828 it should be `=` instead of `:` -- just corrected it. Do you have a preference for `;` vs `,`? Do we have any other url support list and what are they using?

**Comment by zhx828** [comment]
@jjgao we use comma for multi-studies. It seems pretty standard way to do. We have similar in patient view `navCaseIds`

**Comment by jjgao** [comment]
@zhx828 sounds good!

**Comment by zhx828** [comment]
@jjgao should we give some messages when the filterAttributeId is not available in this study?
