### ISSUE TITLE
download study files button missing in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5622]
Please add it back: "Download study files" (after the study name?)

The link should be the same as in [datasets page](http://www.cbioportal.org/datasets): http://download.cbioportal.org/paac_jhu_2014.tar.gz

Please note that it's not necessary that every study has a file so you would need to test first. Please use the same code (ideally not duplicate the code) as Datasets page to decide the logic.

**Comment by zhx828** [comment]
@jjgao keep the same style as in DataSets page?

![screen shot 2019-01-17 at 2 03 04 pm](https://user-images.githubusercontent.com/5400599/51341992-a7729e00-1a60-11e9-9db5-46f2d069de4f.png)

**Comment by zhx828** [comment]
@jjgao should we also add a tooltip for the new download button? Differentiate the download on the right.

**Comment by jjgao** [comment]
Thanks, @zhx828 . Yes, tooltip: "Download all clinical and genomic data of this study"

**Comment by jjgao** [comment]
@zhx828 looks great. Thanks!
