### ISSUE TITLE
Study view: filter duplicate IDs in select sample / patient box

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5627]
Can we support filtering of duplicate sample or patient IDs in lists pasted into the Custom Selection box?

![image](https://user-images.githubusercontent.com/11892704/51400108-90da4e80-1b15-11e9-8afe-fb25c91d946f.png)

**Comment by zhx828** [comment]
@schultzn I will do some mockup.

**Comment by schultzn** [comment]
It could be as simple as an automated removal of any duplicates and a message underneath saying "x duplicate IDs were removed”

**Comment by zhx828** [comment]
@jjgao @schultzn similar to this for the Add Custom Groups, do we allow the same id in different groups?

**Comment by schultzn** [comment]
That would make sense - if a user enters the same ID twice in the same group, one should be removed.

**Comment by zhx828** [comment]
@schultzn this is the mockup when duplicates exist
![screen shot 2019-01-23 at 12 59 13 pm](https://user-images.githubusercontent.com/5400599/51630446-3297dc00-1f18-11e9-8f5e-740355825d01.png)

**Comment by schultzn** [comment]
I think this looks good!
