### ISSUE TITLE
Make Plots tab layout slightly more compact vertically

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5633]
Can we think about making the Plots tab slightly more compact vertically so that it fits on a 13" laptop screen?

![image](https://user-images.githubusercontent.com/11892704/51445671-f6753900-1cd5-11e9-9fc8-be2b16b9f448.png)

**Comment by jjgao** [comment]
Maybe we can remove some white space?  @adamabeshouse

**Comment by adamabeshouse** [comment]
which elements would we want to be in the frame? I think we would have to shrink the plot a bit

**Comment by schultzn** [comment]
Ideally, everything should in view. If you just remove some white space and reduce font sizes a but, that might be all that is needed. And any way you can move the "Color samples by" options into the actual plot, or closer to it?

![image](https://user-images.githubusercontent.com/11892704/52128382-d4978280-2602-11e9-9189-4c66fc871696.png)

**Comment by coderrsid** [comment]
Can you provide the immediate link for the query? Layout can be fixed.

**Comment by jjgao** [comment]
@coderrsid here is the link: https://www.cbioportal.org/results/plots?session_id=5ba11ce6498eb8b3d567e7ed

**Comment by coderrsid** [comment]
@jjgao So we want the layout to be like as said by @schultzn ?

**Comment by coderrsid** [comment]
@schultzn what do you mean by " And any way you can move the "Color samples by" options into the actual plot, or closer to it? "

**Comment by schultzn** [comment]
Take a look at my mockup - The “Color Samples By” options are currently on the bottom left - in my mockup, I moved it further to the right and up so that it is not hidden below the edge of the screen.

**Comment by coderrsid** [comment]
@schultzn So this design should only be for 13 or less inch screen or for all size screens?

**Comment by schultzn** [comment]
I am not sure I understand your question. The page should be designed so that most plots fit on a 13 inch laptop screen.

**Comment by coderrsid** [comment]
Okay @schultzn,
I made some changes and tried to make it as small as i could and decreased the font-size, the button-size and made the colouring-options to be positioned near to plot. Please tell me if you want more changes.
<img width="1440" alt="screenshot 2019-03-08 at 12 16 48 am" src="https://user-images.githubusercontent.com/35633575/53981021-ca076600-4137-11e9-9665-fd99cf3409c3.png">
<img width="1440" alt="screenshot 2019-03-08 at 12 17 05 am" src="https://user-images.githubusercontent.com/35633575/53981022-ca076600-4137-11e9-9c7f-28fae20f946c.png">

**Comment by jjgao** [comment]
@coderrsid thanks for working on this. Could you send a pull request and we can test from there?

In case you are not aware, you can use Chrome Dev Tools to mimic a 13" mac screen.

![image](https://user-images.githubusercontent.com/840895/53981667-08be0180-40e1-11e9-9ec0-3076ba34aac6.png)

**Comment by coderrsid** [comment]
@jigao Thanks. But i am using a 13 inch mac book

**Comment by coderrsid** [comment]
I'll make the PR. then everyone can understand easily. Please check.

**Comment by coderrsid** [comment]
Can anyone guide me that after i made changes, i have to test myself or only you guys will?

**Comment by jjgao** [comment]
> @Jigao Thanks. But i am using a 13 inch mac book

that would be perfect :)

> Can anyone guide me that after i made changes, i have to test myself or only you guys will?

You should test first and then we will once your pull request is ready for reviewing.

**Comment by coderrsid** [comment]
@jjgao i have made the pull request please review it and tell me if i have to rectify anything in that.

**Comment by alisman** [comment]
@schultzn can we close this?

**Comment by schultzn** [comment]
Yes!
