### ISSUE TITLE
custom case list not work for virtual study

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5634]
In [this query](http://bit.ly/2FFXrk5), I selected a few samples from the virtual study for querying, but the result contained all samples.

![image](https://user-images.githubusercontent.com/840895/51481554-21a56a00-1d62-11e9-83ca-b1286a85095d.png)

![image](https://user-images.githubusercontent.com/840895/51481571-2a963b80-1d62-11e9-9944-241323646259.png)

**Comment by alisman** [comment]
@dippindots please confirm that this is still an issue first (and fix if is!)

**Comment by dippindots** [comment]
@jjgao We do not support the custom list on query page for virtual study right now, but we think the virtual study is already done the custom case selection when creating the virtual study. Also, if users go to study view page, they can select the case and create a new virtual study by doing so. Do we really need to support here?

**Comment by jjgao** [comment]
We have two options:

1. Removing the whole Case Set section. Currently, this dropdown is ignored completely in the query above.

![image](https://user-images.githubusercontent.com/840895/60364867-3cd17100-99b5-11e9-86c0-29ac3eda1f07.png)

2. Keep the section, then it should not be ignored.

I am leaning towards # 2. LMK if it's too complex.

@alisman @dippindots
