### ISSUE TITLE
Clicking node in network tab doesn't do anything

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#5636]
I'm running 2.0.1
When I click a node in the network graph a request gets fired to `http://server/cbioportal//bioGeneQuery.do` (note the two slashes). It fails with error 500 and tomcat spits out 

	Jan 22 04:16:10 localhost.localdomain server[1978]: SEVERE: Servlet.service() for servlet [bioGeneQuery] in context with path [/cbioportal] threw exception
	Jan 22 04:16:10 localhost.localdomain server[1978]: org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:248)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:194)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:440)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	Jan 22 04:16:10 localhost.localdomain server[1978]: at java.lang.Thread.run(Thread.java:748)

the effect is similar to  #5285 but instead of loading I just see gene selection on `genes_tab`

**Comment by jjgao** [comment]
@j-hudecek it seems working on our public portal. We currently don't have the bandwidth to work on Network tab if the production work. We decided to move the Network tab into a separate standalone project at a certain point.
