### ISSUE TITLE
No error for wrong gene name entered for oncoprint heatmap track

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5639]
@pvannierop commented on [Tue Jan 22 2019](https://github.com/cBioPortal/cbioportal-frontend/issues/1942)

Steps to reproduce:
1. Go to Oncoprint tab
2. Click heatmap button
3. Enter "WRONGGENENAME" in the input field
4. Press "Add genes to heatmap"

Problem:
User is not informed that a unknown gene identifier was entered

Desired behavior:
When entering a list of genes the user is presented with the entries that could not be mapped to a gene in a popup.

**Comment by jjgao** [comment]
The save gene validator used in Query page could be used.

**Comment by adamabeshouse** [comment]
this issue is already fixed - the same gene validation box is used as is used in the query form
