### ISSUE TITLE
Sorting CNVs by Cytoband

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5646]
@tjpugh commented on [Mon Apr 16 2018](https://github.com/cBioPortal/cbioportal-frontend/issues/1093)

In the patient view, the CNV table has a Cytoband column with data that can be ordered by clicking on the header. Unfortunately, sorting is currently set to alphanumeric which means that chromosome 10 comes before 1, 2, 3, etc. There could also be subtle sorting problems due to the ordering of p and q arms and cytobands. The correct ordering should follow karyotypic cytobands as ordered in the UCSC cytoBand table:
https://genome.ucsc.edu/cgi-bin/hgTables?clade=mammal&org=Human&db=hg19&hgta_group=map&hgta_track=cytoBand

---

@jjgao commented on [Thu Apr 19 2018](https://github.com/cBioPortal/cbioportal-frontend/issues/1093#issuecomment-382851238)

This should also apply to Co-Expression tab.

**Comment by ZakiaSalod** [comment]
Hi @jjgao , I have forked this repository into my Github.
I cloned it on my computer. Have it opened now on IntelliJ Idea IDE.
I'm trying to find the location of where I need to make this change of sorting the Cytoband column.
I had also simulated from the Front-end side, of where the location of the Cytoband column is, of which the sort-order needs to be changed : here:
https://www.cbioportal.org/patient?studyId=ucec_tcga_pub&caseId=TCGA-BK-A0CC
However, am having some difficulty finding the exact file/location from the source-code side from the IntelliJ Idea side.
Please help - generalized help will be appreciated.
Thanks.

**Comment by ZakiaSalod** [comment]
@jjgao : what is "results.coexpression"?

**Comment by ZakiaSalod** [comment]
@adamabeshouse  : could you perhaps assist with the above please?

**Comment by adamabeshouse** [comment]
HI @ZakiaSalod, how can I help?

**Comment by ZakiaSalod** [comment]
Hi @adamabeshouse : thanks for this - I will re-look at this again. Thanks. I really do appreciate it!
Am excited to be working on the cBioPortal code-base.

**Comment by ZakiaSalod** [comment]
@adamabeshouse : can you give me general guidelines on how you figured out where the change needs to be made so that I can be mindful of this in future as well.
I had been looking for the file of where this change needs to be made the other day, but I wasn't sure about it, hence decided to ask. P.S. Its my first time looking at the cBioPortal code-base. Really appreciate the help!

**Comment by adamabeshouse** [comment]
@ZakiaSalod The best way I can think is to install a React devtools plugin to your browser (I know chrome has one) that allows you to inspect React components on the page. Then click on the component in question, find out its name, then search for that file in the code, and go from there. Unfortunately I can't think of anything more specific than that - it will always depend on the task and the code.

Thanks for your interest and help!
