### ISSUE TITLE
MDACC compendium heatmaps tab missing from Patient page (regression?)

### ISSUE THREAD

**Issue by ChrisWakefield** [cBioPortal/cbioportal#5648]
http://www.cbioportal.org/patient?studyId=brca_tcga_pub&caseId=TCGA-A1-A0SD
used to have a Heatmaps tab that would iframe our "Compendium" containing links to NGCHM with that patient id selected.  Did recent frontend changes drop it?

The link above still has the configuration to access the index, but the code that actually places the tab and decides whether to make it visible is missing (?).  I expect to see the browser send a GET to https://bioinformatics.mdanderson.org/participant2maps?participant=TCGA-A1-A0SD

**Comment by jjgao** [comment]
@ChrisWakefield we have decided to remove the tab in the patient view page as heatmaps make more sense in a cohort than for a single patient. The support in the study view still remains.

**Comment by ChrisWakefield** [comment]
@jjgao JJ, I agree that a single-patient heatmap would not make sense.  What this tab was for was show all heatmaps in our compendium that contained that patient ID, and allow users to navigate to a particular platform & study that highlights how that patient relates in that cohort.  (ie. where in the heatmap relative to others, and what grouping, etc.)  I think this still makes sense.

**Comment by jjgao** [comment]
@ChrisWakefield we would really like to simplify the patient view page and thought the use case of the heatmaps tab was a little complex and different from other features on the page. And we didn't see much usage of the tab in patient view from our users after it was released. The use case of the tab in the study view page aligns perfectly with the study view.

**Comment by jjgao** [comment]
@ChrisWakefield ... and apologized that we forgot to check with you first.

**Comment by zhx828** [comment]
@ChrisWakefield I noticed today, the study heatmap does not show any content except the page is not availble. Is this a temporary issue?  http://www.cbioportal.org/study?id=brca_tcga_pub&tab=heatmaps

The URL we use is https://bioinformatics.mdanderson.org/TCGA/NGCHMPortal/?view=0&p0DiseaseInput=brca

![screen shot 2019-02-07 at 4 43 10 pm](https://user-images.githubusercontent.com/5400599/52444822-7b928780-2af7-11e9-924a-189035422c84.png)

**Comment by jjgao** [comment]
created another one: https://github.com/cBioPortal/cbioportal/issues/5714 and closing this.
