### ISSUE TITLE
support multiple reference genomes, 2nd push

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5652]
https://docs.google.com/document/d/1oIA6aTn8HJq0uztetFq8WKyB13Xi70o1oepOpvTIjt8/edit

- [x] remove cytoband from gene table
  - [x] db migration
- [x] add REFERENCE_GENOME_ID into cancer_study
  - [x] db migration
  - [x] if no REFERENCE_GENOME_ID in study meta, assume it's 37
- [x] don't add cytoband into cna_event
- [x] for API endpoints using cytoband, break into two sql queries and get cytoband into the api
- [x] for mutations, use CHR in mutation_event table instead of parsing from cytoband
- [ ] disable "View Summary" and "Submit" when studies with different reference genomes
- [x] ensure one species per portal installation
  - database constraint?

validator for reference_genome: 
- [x] reference_genome_id in segment data meta file should match the study genome build
- [x] field NCBI_Build (if filled) in MAF file should match the study genome build
- [ ] validate mutation_event.chr from referernce_genome_gene table?
  - I am not sure if this is necessary...

![multiple_genome_build_support](https://user-images.githubusercontent.com/17375786/51698901-73a3f500-1fd9-11e9-8d3a-ca89b2298563.png)

cc'ing @pieterlukasse @n1zea144

**Comment by pieterlukasse** [comment]
@khzhu: input data validation rules (for the validateData.py):
- [ ] `reference_genome_id` in segment data meta file should match the study genome build
- [ ] field `NCBI_Build` (if filled) in MAF file should match the study genome build

**Comment by khzhu** [comment]
@pieterlukasse , you will still need to supply the reference genome build when query gene annotations (chr, cytoband) from genomenexus, right?

**Comment by khzhu** [comment]
[reference_genome_build_support.pdf](https://github.com/cBioPortal/cbioportal/files/2792886/reference_genome_build_support.pdf)

**Comment by khzhu** [comment]
schema diagram updated.
![reference_genome_build_support](https://user-images.githubusercontent.com/17375786/51697661-61748780-1fd6-11e9-9e70-baf1ee36a67d.png)

**Comment by khzhu** [comment]
![referenece_genome_build_support](https://user-images.githubusercontent.com/17375786/51698625-b6b19880-1fd8-11e9-896e-8c74d1c22ef8.png)

**Comment by jjgao** [comment]
> @jjgao maybe a totally different solution, but with less impact on DB: what if we get all gene "annotation" data like cytoband and chromosome from an external service like genomenexus? Then we don't need the reference_genome* tables.

@pieterlukasse good thinking and genome nexus would be the natural place to host such data, but maybe we should keep it simple for this round so that we can get it done? (we are not supporting different reference genomes yet in genome nexus.)

**Comment by jjgao** [comment]
I updated the list in the main issue description.

@khzhu I don't we should _populate_ mutation_event.chr from referernce_genome_gene table. It should be from MAF. _validating_ would be fine, not sure if necessary.

**Comment by khzhu** [comment]
@jjgao , I agree with you, no check is really needed. What do you think, @pieterlukasse?

**Comment by pieterlukasse** [comment]
@khzhu I think the check is important, so that wrong data can be flagged early. So if MAF reports a mutation about a specific gene and chr is filled, the check of whether the chr is correct for this gene should be done (I expect this to be easy if the right data is pulled in at validateData.py - I think now it is still pulling from gene api...so you might have to change gene api to get the chr from the new table).

@jjgao regarding genomenexus: @sandertan has been working on hg38 support. @inodb can also tell a bit more about this I guess. This brings me to another point: the mutation view should be using different genomenexus endpoints depending on the build version. E.g. if the data is hg19, then requests should go to something like hg19.genomenexus.org while if it is hg38, it should go to hg38.genomenexus.org. Maybe not important now, but will be soon once you add "VEP" on the fly features to mutation view to support multiple transcripts, right?

**Comment by pieterlukasse** [comment]
@khzhu One comment I have after discussing with @sandertan. Please do *not* add new requirements to the meta file formats. So, do *not* add a new field to the `meta_study.txt` to indicate the build for this study. Rather, let the importer infer it from the build information that is present in the MAF file and/or the meta file for segment data. In this way, users don't need to change their staging files to add something that is already there anyway.

**Comment by khzhu** [comment]
@pieterlukasse, there is one problem with this approach. Please note cancer study is always the first data to be loaded into the DB. This makes the cancer study identifier available to the genetic profile table before any mutations can be loaded into the DB.

**Comment by khzhu** [comment]
@pieterlukasse , 
regarding your comments on chr validation. I do not think the validator script currently uses any APIs, but I agree totally with you, we should go with that route. thanks!

**Comment by jjgao** [comment]
@pieterlukasse I agree that we should connect to genome nexus properly ultimately, but I worry that if we add genome nexus (and cbioportal frontend) into this round, it'll end up the same as the last time. We are not pulling many data from GN yet, so maybe a temporary solution is not to pull from GN for studies if its reference genome is not hg19.

It would be good to define the remaining work in another issue though.

**Comment by jjgao** [comment]
@khzhu any update on this?

**Comment by khzhu** [comment]
@jjgao ,the code was done while a ago, will need to rebase to the latest rc, and set up a test database (due to the change in schema) before pushing the PR back to Github for a review. 
Working on a mysql cluster on Microsoft Azure cloud, can be used for CI testing once done.

**Comment by khzhu** [comment]
Hi @jjgao @pieterlukasse  , do you want **length** (exonic length) to be removed from the **_gene_** table too?

**Comment by jjgao** [comment]
@khzhu I think we can try to remove the length. I don't think it's being used anywhere now, but I might have missed some. Could you give it a try?

We wanted to use protein_length later: https://github.com/cBioPortal/cbioportal/issues/3536.

**Comment by khzhu** [comment]
I do not think the field is in use, since all recorded as 0. I will know for sure once I dropped it.

**Comment by khzhu** [comment]
Please find updated schema diagram. 
![support-multiple-genomes-2nd-5652](https://user-images.githubusercontent.com/17375786/54882632-5ef5a900-4e32-11e9-8798-43d5840be825.png)

**Comment by jjgao** [comment]
Thanks, @khzhu . Could you check the checkboxes above for the ones you completed in the pr?

**Comment by khzhu** [comment]
Will do, thanks @jjgao !

**Comment by khzhu** [comment]
@jj @pieterlukasse @n1zea144 @sheridancbio @onursumer ,
db schema diagram updated and is final.
![support-multiple-genomes-5652-revised](https://user-images.githubusercontent.com/17375786/55636611-32765100-5791-11e9-841f-9e8dc7b27d99.png)

**Comment by khzhu** [comment]
@jjgao @n1zea144 @sheridancbio , frontend/backend all passed CI. Thanks again for all the help!

**Comment by jjgao** [comment]
@khzhu can we close this now? or are there unfinished work?

**Comment by khzhu** [comment]
no, it was done. thank you!
