### ISSUE TITLE
Support multiple studies/profiles for Mutations and CNAs in Enrichments API

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5655]
Current, both [Mutation](http://www.cbioportal.org/beta/api/swagger-ui.html#/Mutation_Enrichments) and [Copy Number](http://www.cbioportal.org/beta/api/swagger-ui.html#/Copy_Number_Enrichments) Enrichments endpoints (both are internal) only support one `molecularProfileId`. We would like to support multiple profile IDs so that Enrichments analysis can be performed when multiple studies are selected. Below is a list for Mutations, but the same should apply for CNA.

- [ ] Add a new endpoint: `POST /mutation-enrichments/fetch` with the following input parameters (similar to the [Mutations endpoint](http://www.cbioportal.org/api/swagger-ui.html#/Mutations/fetchMutationsInMultipleMolecularProfilesUsingPOST))
  - `molecularProfileIds` (@ersinciftci or should we use `molecularProfileFilter`?)
  - `enrichmentType` - the same was the current endpoint
  - `enrichmentGroups` 
```json
[
{
"groupName": "string",
"identifiers": [ // similar to http://www.cbioportal.org/api/swagger-ui.html#/Clinical_Data/fetchClinicalDataUsingPOST
    {
      "studyId": "string",
      "entityId": "string" // sample or patient based on `enrichmentType`
    }
  ]
}
]
```
  - (optional) Can we also rename `enrichmentFilter` in the current endpoint to `enrichmentGroups` since it's not about filter anymore?

**Comment by adamabeshouse** [comment]
I think it should look approximately the same as the current one except that alteredIds and unalteredIds should take a list of {sampleId, molecularProfileId} or {patientId, molecularProfileId} objects, and scratch the separate molecularProfileIds input.

**Comment by ersinciftci** [comment]
We should create a new filter class called `EnrichmentMultipleStudyFilter.java` and it should do what @adamabeshouse suggested. Not sure what `enrichmentGroups` is, if it's just about querying multiple studies/profiles, I don't think we need `enrichmentGroups`.

**Comment by jjgao** [comment]
@ersinciftci thanks, but it's not filter. The parameter is actually to define two groups of samples for comparison.

**Comment by ersinciftci** [comment]
@jjgao is this issue about cohort comparison or just showing the enrichments tab in multi-study queries? Or by `two groups of samples` do you mean altered and unaltered samples?

**Comment by jjgao** [comment]
@ersinciftci it's going to be used in the cohort comparison page (and also Enrichments tab). Altered and unaltered samples are two groups (with special group names).

**Comment by adamabeshouse** [comment]
@jjgao I think your issue is just the terminology, because I think the functionality doesn't have to do w altered/unaltered those just happen to be two names. But I would agree it would be better to name them more generally.

**Comment by jjgao** [comment]
@adamabeshouse yes, just terminology.

**Comment by adamabeshouse** [comment]
@jjgao how would it work for more groups? it would return the pairwise enrichments?

**Comment by jjgao** [comment]
@adamabeshouse pairwise would be one way to do it. I think it is also possible to test for multiple groups. But let's not go there yet.

**Comment by ersinciftci** [comment]
@jjgao Yes

**Comment by jjgao** [comment]
@ersinciftci thanks. What do you do if there are patient IDs that are included in both groups.

**Comment by adamabeshouse** [comment]
@ersinciftci for group comparison we are doing enrichments for any two groups, not specifically altered vs unaltered. its possible for there to be overlap

**Comment by sheridancbio** [comment]
@adamabeshouse @jjgao @cBioPortal/backend 
@angelicaochoa and I are proposing a change to the internal API schema for endpoints:
- api/molecular-profiles/{molecularProfileId}/copy-number-enrichments/fetch
- api/molecular-profiles/{molecularProfileId}/mutation-enrichments/fetch

The change adds a specification of a genetic-profile-id for each individual sample listed in either of the two comparison groups passed as arguments to the request. The schema of the output/response has been expanded to report the count of samples for each group which were profiled for each record.

The path parameter _{molecularProfileId}_ has been dropped in both endpoints, which become:
- api/molecular-profiles/copy-number-enrichments/fetch
- api/molecular-profiles/mutation-enrichments/fetch

New Body Schema argument (for both endpoints):
```
{ 
    "set1":[
        {
            "geneticProfile":string (stable ID, i.e., "brca_tcga_mutations"),
            "entityId":string (sample or patient stable ID)
        }, 
        ...
    ],
    "set2":[
        {
            "geneticProfile":string (stable ID, i.e., "brca_tcga_mutations"),
            "entityId":string (sample or patient stable ID)
        }, 
        ...
    ]
}
```
Old Schema:
```
{
  "alteredIds": [
    "string"
  ],
  "unalteredIds": [
    "string"
  ]
}
```
The query parameter _enrichmentType_ functions the same : it will determine the interpretation of the entityType values passed in for set1 and set2. We suggest considering changing the name of this parameter to _entityType_. (Please give feedback)

CopyNumberEnrichment also has a query parameter named _copyNumberEventType_, and this is unchanged.

In the Result Schema, we add two fields : _profiledInSet1Count_ and _profiledInSet2Count_, which report the number of samples in which the entrezGeneId was profiled for (i.e. part of the gene panel). We have also renamed _alteredCount_ to _alteredInSet1Count_ and renamed _unalteredCount_ to _alteredInSet2Count_.

New Result Schema:
```
[
  {
    "alteredInSet1Count": 0,
    "alteredInSet2Count": 0,
    "cytoband": "string",
    "entrezGeneId": 0,
    "hugoGeneSymbol": "string",
    "logRatio": "string",
    "profiledInSet1Count": 0,
    "profiledInSet2Count": 0,
    "pValue": 0
  }
]
```
Old Result Schema:
```
[
  {
    "alteredCount": 0,
    "cytoband": "string",
    "entrezGeneId": 0,
    "hugoGeneSymbol": "string",
    "logRatio": "string",
    "pValue": 0,
    "unalteredCount": 0
  }
]
```

**Comment by ersinciftci** [comment]
@sheridancbio it should be `api/copy-number-enrichments/fetch` and `api/mutation-enrichments/fetch` after dropping molecularProfileId from the URL, at least that's how all the other endpoints are designed. Because `/molecular-profiles` is there to specify that the ID comes after it is a molecular profile ID, so we wouldn't need that anymore.

**Comment by sheridancbio** [comment]
Thank you @ersinciftci .... updating now
