### ISSUE TITLE
plots tab - bar chart problems

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5657]
Something has gone wrong with this plot:
![image](https://user-images.githubusercontent.com/10508276/51840630-8de01a80-22da-11e9-892d-21b3dd4f6130.png)

The spacing between entries on the x-axis is very large (the other values are off the screen) and the bars themselves are too wide.

To replicate, go here & change the vertical axis to Cancer Type:
http://www.cbioportal.org/results/plots?session_id=5c4f0931e4b05228701fcd9e

**Comment by adamabeshouse** [comment]
thanks, yes, this has been reported https://github.com/cBioPortal/cbioportal/issues/5626
