### ISSUE TITLE
improvement of table in download tab

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5659]
- [ ] Looking for all different rows for data for a gene (a gene may present in multiple rows)
- [ ] Add links to study, sample, and patient
- [ ] Change colors of `no alteration` and `not profiled` to gray and add a strikethrough to ~~not profiled~~
- [ ] Add columns for each gene that combines all alterations (hidden by default but included in download.
- [ ] Change UP/Down to High/Low #5529

-- origginal reported issue --
Genetic Alterations table on Download tab does not always show all events

Example:
http://bit.ly/2WqAiaj

Some samples are clearly labeled as altered, but the alterations do not show up. I think it has to do with OQL, possible with non-exact OQL matches, e.g. K601 (without the resulting amino acid), and possible only in certain combinations. I can't quite figure out the logic.

![image](https://user-images.githubusercontent.com/11892704/51857446-466c8500-2300-11e9-9cd7-f92ae28125bb.png)

**Comment by schultzn** [comment]
Just to clarify: The overall alteration status of the sample is correct. It is just that the qualifying alterations are not listed.

**Comment by jjgao** [comment]
It looks like the issue happens when a gene is queried in different lines. 

I created a simpler version of @schultzn's query here: http://bit.ly/2WqQUyM

"BRAF:V600; BRAF:V601;" were queried, but in Download tab, only V600 is present.

![image](https://user-images.githubusercontent.com/840895/51861121-6785a380-2309-11e9-81c5-e993dc4fe67b.png)

BTW, is it possible to show the OQL when it is used?

![image](https://user-images.githubusercontent.com/840895/51861179-8ab05300-2309-11e9-9252-d0eb11a656cf.png)

**Comment by schultzn** [comment]
And while we are fixing the table, can we / should we add links to sample and patient IDs?

**Comment by jjgao** [comment]
while we are on this. Maybe we can discuss the colors? (I think I may have missed the final discussion for the final decision.) I think we should use less predominant colors for `no alteration` and `not profiled` (e.g. gray) and maybe a strikethrough for `not profiled` (similar to oncoprint). Thoughts? @schultzn @tmazor @alisman

**Comment by schultzn** [comment]
Good idea. And one more: We should add the term "germline" behind germline mutations.

**Comment by schultzn** [comment]
And another one:

When downloading the TSV, the column headers show the full OQL query instead of the individual subsets.

In addition to fixing the headers, maybe we can add an extra column in the download that combines all alterations for a gene in a single column (like we used to have), then have additional columns with individual alteration types? I am doing a quick analysis / extraction right now, and having the old format would be really helpful.

**Comment by jjgao** [comment]
@schultzn it was actually requested by a user as well. I would add a hidden column per gene and include them download.

@dippindots here is a summary of things to improve:

- [ ] Looking for all different rows for data for a gene (a gene may present in multiple rows)
- [ ] Add links to study, sample, and patient
- [ ] Change colors of `no alteration` and `not profiled` to gray and add a strikethrough to ~~not profiled~~
- [ ] Add columns for each gene that combines all alterations (hidden by default but included in download.
