### ISSUE TITLE
Mutation mapper not working / unclear error messages

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#5661]
Mutation mapper does not seem to be working as documented. E.g.

The following input starts the process, but returns a "Critical error":
```
Sample_ID	Cancer_Type	Chromosome	Start_Position	End_position	Reference_Allele	Variant_Allele
328_Cellline	Gastrointestinal Cancer	1	51760373	51760373	T	C
328_Cellline	Gastrointestinal Cancer	1	65171074	65171074	C	T
328_Cellline	Gastrointestinal Cancer	1	69107714	69107714	T	C
328_Cellline	Gastrointestinal Cancer	1	69107725	69107725	C	A
328_Cellline	Gastrointestinal Cancer	1	69107749	69107749	A	G
328_Cellline	Gastrointestinal Cancer	1	65161058	65161058	G	A
328_Cellline	Gastrointestinal Cancer	1	65166232	65166232	G	A
```
![image](https://user-images.githubusercontent.com/2900303/51903630-f7385a00-23bc-11e9-8613-463b306dde56.png)
```
Error processing the input. Please review your input and try again.
```
Another issue with this page occurs when the lines have the wrong number of columns (e.g. replace the tabs above by spaces). The user will not be informed about the problem, but only gets this error:
```
Error processing the input. Please review your input and try again.
```

**Troubleshooting**: interestingly, there seems to be only 1 row in the input data I pasted above that is causing the "critical annotation error", namely:
```
328_Cellline	Gastrointestinal Cancer	1	69107714	69107714	T	C
```
All other rows result in the following message (if I paste them just above the "Genomic changes" example data):

![image](https://user-images.githubusercontent.com/2900303/51904456-fe606780-23be-11e9-8796-ecfc2317feb0.png)

Could the underlying issue be related to hg19 vs hg38 coordinates?

**Comment by pieterlukasse** [comment]
@inodb, @onursumer , was this solved?

**Comment by inodb** [comment]
@pieterlukasse 	looks like it wasn't, sorry for the delay - we'll look into it

**Comment by inodb** [comment]
it's a bit tricky to provide more detailed feedback about why the mutations are failing b/c the current annotation model in genome nexus doesn't provide a way to retrieve error messages from external services (e.g. VEP) in the response. We'll first have to fix that. I assume this is indeed b/c of hg38 coordinates
