### ISSUE TITLE
stacked bar chart - long legend goes off screen

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5662]
When the legend is long, it gets cutoff:
![image](https://user-images.githubusercontent.com/10508276/51932090-6bc6c500-23cc-11e9-994b-04d995a578a7.png)

To replicate, the query is EGFR in MSK-IMPACT

**Comment by adamabeshouse** [comment]
duplicate https://github.com/cBioPortal/cbioportal/issues/5569

**Comment by adamabeshouse** [comment]
note to self: put legend on bottom if more than 15 items
