### ISSUE TITLE
plots tab - extra clinical attributes?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5663]
In MSK-IMPACT study, there are options to plot "Mutation spectrum" and "# Samples per Patient" but neither of these seem to have any data:
![image](https://user-images.githubusercontent.com/10508276/51932776-dcbaac80-23cd-11e9-8052-a5d29a7c24bf.png)

Neither of these exist as tracks in study view.

Should these not be appearing here?

Note that there are two tracks listed in the clinical attribute dropdown: "# Samples per Patient" and "Number of Samples Per Patient". This is only a problem with the former.

Also note that this problem exists on production already.

**Comment by jjgao** [comment]
I don't think we have a way to show mutation spectrum here.

**Comment by adamabeshouse** [comment]
youre right @jjgao this is probably because there is data available, which puts it in the list, but its data type is not plottable, which means no plot is shown. ill confirm when i get in. we’ll just filter that out of the list.
