### ISSUE TITLE
query altered samples in Download

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5665]
updated:

- [ ] change "Sample affected" to "Altered samples"
- [ ] Add "Query" after "Download" to query the altered samples with the same genes.
- [ ] Add a new line "Unaltered samples: ..." with the same options.

===
I am thinking of adding a query button after the `samples affected...` line. It would query the altered samples with the same genes. (BTW, we should change `samples affected` to `Altered samples`.)

It may be also useful to go to study view (and patient view) for these samples.

http://bit.ly/2sRi7gs

![image](https://user-images.githubusercontent.com/840895/51959112-f6391400-2420-11e9-8ec0-865ad32994ef.png)

@cBioPortal/product @dippindots

**Comment by tmazor** [comment]
Nice idea!

If we're going to do this, what about also adding a way to query/go to study view for the unaltered samples?

**Comment by jjgao** [comment]
@tmazor good point, so adding another line "Unaltered samples..." with the same options.

**Comment by jjgao** [comment]
@dippindots I added a checklist above. Please work on it when you have time. Not urgent.

**Comment by tmazor** [comment]
Exciting!! So glad this is happening @dippindots !

First, what happened to adding a link to study view for the altered/unaltered samples?

Second, while I love the idea of these Query buttons, I'm not sure about this specific implementation. Right now you essentially can run a query in which either 100% of samples are altered or 0% of samples are altered. What about allowing the user to define the gene list when they click the Query button? I realize this can always be done by modifying the query after running it, but it might be nice to make this explicit. @jjgao what do you think?

Third, it looks like the unaltered list doesn't take gene panels into account. For example, query ACVR1 in MSK-IMPACT and then query the unaltered samples -- there are ~3000 samples that are not profiled for ACVR1 which are included in this query. I realize this can get more complicated for multi-gene queries, and maybe it requires the outcome of #6051 to decide how to deal with this, but I do think it's important to consider.

Finally, one semi-related request: can we also update the text in this download table? I think this wording is more clear:
Altered samples: List of samples with alterations
Unaltered samples: List of samples without any alteration
Sample matrix: List of all samples where 1=altered and 0=unaltered

**Comment by jjgao** [comment]
@tmazor It may be tricky to handle all these scenarios in the Download tab. Maybe we should only add the link to study view of these samples and let the user start query from there?

**Comment by jjgao** [comment]
Or we could address "Modify Genes" for now and leave gene panel for later when we have a solution for #6051?

I think it's a good idea to modify genes. One simple option would be: instead of submitting the query directly, we could just open "Modify Query" interface and change the querying sample list (and highlight and put some text to tell the user it's changed). Then we can leave the user to modify the genes if needed?

**Comment by dippindots** [comment]
Thanks for your comments, @jjgao @tmazor. 

Could you confirm that we want to make the following change:
- [ ] Update download tab texts(Altered samples, Unaltered samples, and Sample matrix)
- [ ] When the user clicked the "Query" button. Open "Modify Query" interface and change the querying sample list
- [ ]  Show a highlight alert "altered/ unaltered samples has been added" to tell the user it's changed.

Something may need discussion:
- Do we need to consider gene panels, or just consider genes?
- Do we also want to add a link to the study view page?

Please feel free to leave comments and edit this list, thanks!

**Comment by jjgao** [comment]
Thanks, @dippindots. 

> Do we need to consider gene panels, or just consider genes?

I would postpone this until we have a solution for #6051 

> Do we also want to add a link to the study view page?

Yes, we need.

**Comment by tmazor** [comment]
Thanks for the summary @dippindots - I agree with all of the above. Nice idea @jjgao about jumping straight to modify query!

**Comment by dippindots** [comment]
Hi @jjgao @tmazor , @alisman gave me some advice on how to implement the button(go to study view with selected samples). But there are many ways can accomplish this so we may want to get some advice from the production side.

**Problem description:** 
Our study view page doesn't support the custom samples (we need to use `custom selection` to add a filter for the custom samples);

**Solutions:** 
1. Virtual Study: When the user clicks the button, create a virtual study and go to the virtual study view page.
2. Pre-filter support: When the user clicks the button, we go to study view page and add a filter for them.

**Other Concerns:**
1. Do we want to open a new tab or redirect the current tab

**Comment by jjgao** [comment]
@dippindots Solution #-1 creating a virtual study sounds good. Let's open a new tab.
