### ISSUE TITLE
cbioportal software markdown page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5667]
Create new page listing cBioPortal Software and Acknowledge service providers (e.g. Netlify, Slack, Travis, CircleCI, Heroku)

**Comment by ecerami** [comment]
Hi @inodb I think I am going to take a break from the e-2-e testing :)

And, will try this one next.  Have you already started on this?

Are there others we should acknowledge on this page?  Also, I am assuming we should link to this new page from the footer?

**Comment by inodb** [comment]
@ecerami Thanks! That would be great! I haven't started on it

Just the acknowledgement section would already be great. Can't think of of other services to acknowledge atm. Potentially we could extend it to list other open source projects

I hadn't fully thought out yet what else to put on the cBioPortal Software page. Maybe the target audience is other developers looking to contribute and/or those trying to understand the software powering cBioPortal.org. I did write the [architecture docs](https://docs.cbioportal.org/2.1-deployment/architecture-overview) which might have some overlap with that idea. Could potentially link to those docs

A link in the footer would be good, prolly in the `DEV` column. A related issue is this one on redesigning the header to be more similar to the footer: https://github.com/cBioPortal/cbioportal/issues/5649

**Comment by ecerami** [comment]
ok, I will start something tomorrow.  will probably share the content as a google doc to gather some initial feedback.

**Comment by ecerami** [comment]
@inodb @jj @alisman @pieterlukasse:  Here is a google doc draft content for this issue:  https://docs.google.com/document/d/1pZFt1cjlwNmP70SxcaUM2jUbhW1stACjjD9EicqoVvM/edit?usp=sharing.  Please add any major open source libs or service providers we use.  I can then convert to Markdown and integrate.  tx.
