### ISSUE TITLE
render data tables in study view without waiting for the web service data

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#567]
Currently data table instances wait for the data which is not actually used by the table itself.

**Comment by zhx828** [comment]
Hi @aderidder @pieterlukasse  I will be on vacation for next month. Since you are working some small changes related to the tables in Study View, would you mind taking over this issue?

**Comment by pieterlukasse** [comment]
@zhx828 : sorry for the late reply. For the next weeks I am unfortunately too busy with some other issues and @aderidder will also be leaving for a holiday. There is a chance that we can help with this during our next project with @ecerami , so I will add a `hyve` for the time being. There is also a chance we will have to give it back to you ;)

**Comment by zhx828** [comment]
@pieterlukasse No problem. I can work on this project after two weeks if hyve doesn't pick it up at that point. :)

**Comment by jjgao** [comment]
@zhx828 any update?

**Comment by zhx828** [comment]
@jjgao it's on my list, but not on priority list.

**Comment by jjgao** [comment]
@zhx828 OK.

**Comment by zhx828** [comment]
This issue should be solved in https://github.com/cBioPortal/cbioportal/pull/1405
