### ISSUE TITLE
for mutation mapper tracks show level of oncokb in tooltip

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5672]
![screen shot 2019-02-01 at 2 26 34 pm](https://user-images.githubusercontent.com/1334004/52144843-65835380-262d-11e9-9e88-56e93046a71b.png)

**Comment by jjgao** [comment]
Highest level? ... since the same variant may have different levels.

**Comment by onursumer** [comment]
@jjgao or should we list all levels separated by commas? That's actually current implementation for the `Implication` and `Effect` columns. The implementation allows displaying of multiple comma separated values.

**Comment by jjgao** [comment]
@onursumer sounds good. Then maybe add tumor types and one line per level, e.g.

`Level 1 (Melanoma, Non-Small Cell Lung Cancer, and 6 other cancer types)`
`Level 2B (Breast cancer)`
`Leven 3A (Colorectal cancer)`
