### ISSUE TITLE
Mutation burden plot

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5676]
**Background**: 

Different cancers have different mutation burdens. One nice way to visualize them is the so-called hamburger plot. In the figure below as discribed in [this paper](http://www.nature.com/nature/journal/v499/n7457/full/nature12213.html#f1), "each dot corresponds to a tumour–normal pair, with vertical position indicating the total frequency of somatic mutations in the exome. Tumour types are ordered by their median somatic mutation frequency. The bottom panel shows the relative proportions of the six different possible base-pair substitutions, as indicated in the legend on the left."

![image](https://user-images.githubusercontent.com/840895/30937878-280d66b8-a3a6-11e7-966a-a6a1289f6279.png)

**Goal**: 
Visualizing mutation burdens in OncoPrint and the study view page of cBioPortal

**Approach**: 
- The three types of data (mutation burdens, Mutation spectrum, and Cancer Type) are already visualized in OncoPrint. E.g. open [this link](http://bit.ly/2RtEgeI) and add the three attributes. If we order by Mutation Count and Mutation spectrum, we kind get a similar plot.

![image](https://user-images.githubusercontent.com/840895/52147297-43d99a80-2634-11e9-869c-ad3e9b5d3a4b.png)

- In order to make it more like the one in the paper, we can:
  - support custom height so we can increase the track height of Mutation Count
  - plot dots instead of lines for Mutation Count
  - add median line
- We can add the plot (without genes) into study view page.

**Need skills**: 
* Javascript
* ReactJS

**Possible mentors**:

**Comment by jjgao** [comment]
Moving the issue here. Looks like we pretty much have the feature in oncoprint already. We just need to improve the visualization a little.

**Comment by schultzn** [comment]
But shouldn't this be a study view feature?
