### ISSUE TITLE
How validator deal with MT mutations

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5690]
In [this line](https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/scripts/importer/validateData.py#L2628), chrM was skipped. I didn't look into the code. What's the logic here?

And we usually have `MT` as the chr number.

**Comment by sandertan** [comment]
@fedde-s Can you remember why this logic was added 3 years ago?

**Comment by fedde-s** [comment]
No, I'm not sure. Skipping it from the list of valid chromosomes here disallows the mitochondrial chromosome in segment-wise copy number data files, even though [the docs for data curators](https://github.com/cBioPortal/cbioportal/blob/v2.0.1/docs/File-Formats.md#segmented-data) do not mention that restriction.

Should data about the mitochondrial chromosome be valid in .seg files?

**Comment by fedde-s** [comment]
If it should stay disallowed, it may make sense to add another sentence about that to the comment and the data curation docs.

**Comment by fedde-s** [comment]
And for reference if we are going to adjust the code, [this](https://github.com/cBioPortal/cbioportal/blame/v2.0.1/core/src/test/scripts/unit_tests_validate_data.py#L1749) is the unit test covering the behaviour.

**Comment by jjgao** [comment]
@fedde-s is the code for segment file? I don't think we had a discussion about that. I thought it was for mutations.

**Comment by fedde-s** [comment]
@jjgao:
> is the code for segment file?

Yes, the block of code linked in the issue description is specifically about which chromosomes are supported in segment files.

**Comment by jjgao** [comment]
@fedde-s maybe we can remove this line? ... unless you see a rational.

**Comment by fedde-s** [comment]
Are people interested in visualising the CNA landscape across the mitochondrial chromosome in the graph on the patient view page?

If so, we should probably decide on the name/code of the chromosome, make sure the rest of the data loading pipeline handles it correctly, and validate it accordingly.

On the other hand, if nobody has run into problems with the current status, I can only imagine it keeping the database clean and preventing disappointment when the data in the file isn't being visualised after the effort of loading it.

**Comment by jjgao** [comment]
@fedde-s that's a good point. closing now.
