### ISSUE TITLE
PFAM annotation

### ISSUE THREAD

**Issue by zbozoky** [cBioPortal/cbioportal#5691]
Hi,

I am wondering what PFAM version is used to generate domain boundaries on lollipop plots. Domain boundaries on c-bioportal don't always match domain boundaries on PFAM, which is version 32.0 (https://pfam.xfam.org/about).  

Thanks,
Zoltan

**Comment by inodb** [comment]
Hi @zbozoky - the PFAM data comes from Genome Nexus (https://www.genomenexus.org).

Our latest PFAM data dump was from February 2018, so it's from before the v32 release (that one is from April):

https://github.com/genome-nexus/genome-nexus-importer/releases/tag/v0.1

I created an issue to update PFAM info:

https://github.com/genome-nexus/genome-nexus-importer/issues/26

Thanks for letting us know!
