### ISSUE TITLE
Oncoprint "Sort by case list order" isn't working 

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#5694]
https://groups.google.com/d/msg/cbioportal/PZrNpBS_GuM/gGXAsmOuEAAJ

**Comment by adamabeshouse** [comment]
we have a test for this, and I manually went in to test it and I'm not seeing an error. I asked the user for more info.

**Comment by adamabeshouse** [comment]
nevermind, I just reproduced it.

**Comment by adamabeshouse** [comment]
nevermind, I can only reproduce it sporadically. the details from the user would help.

**Comment by jjgao** [comment]
@kalletlak could you reproduce it? If so, maybe paste the query url. If not, maybe ask the user for the query.

**Comment by adamabeshouse** [comment]
this should fix it. a very strange bug caused by using both the @autobind decorator and binding the method using .bind in the constructor.

https://github.com/cBioPortal/cbioportal-frontend/pull/1989

**Comment by rgescudero** [comment]
here is the query address

http://www.cbioportal.org/results/oncoprint?session_id=5c5c9eb3e4b0f6ce58b5debd

if a want to sort by case list order, and nothing happen

Can you help?

Thanks

Ramon

**Comment by kalletlak** [comment]
@rgescudero thanks!
@adamabeshouse its very random.
seems working fine when the above link is opened and update the sort. but if you try to click modify query button and submit then the sort buttons doesn't work

**Comment by adamabeshouse** [comment]
@kalletlak great, that is consistent with the bug that we fixed. and indeed when i test it with the new pull request, it succeeds. so we'll be merging the fix soon. we'll let you know when it is deployed @rgescudero thanks!

**Comment by rgescudero** [comment]
Ok, thanks

**Comment by adamabeshouse** [comment]
Hi @rgescudero, we've deployed the bug fix and it seems the problem is fixed. Could you please confirm?

Thanks,
Adam

**Comment by rgescudero** [comment]
As far as I can see, it seems that now is OK.

Thanks a lot

Ramon
