### ISSUE TITLE
Patient view exception when there is no clinical patient or sample data

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#570]
Test case: http://www.cbioportal.org/case.do?sample_id=CHOL01&cancer_study_id=chol_jhu_2013

![screen shot 2015-12-09 at 10 16 26 am](https://cloud.githubusercontent.com/assets/5400599/11689031/f02716d0-9e5d-11e5-9dfe-e8b718c84fcc.png)

**Comment by jjgao** [comment]
@inodb could you look into this.

**Comment by jjgao** [comment]
another one

**Comment by inodb** [comment]
Looks like those samples don't have any clinical information in the db. I'll send out a PR that will make the page work without it, but the data should prolly be updated as well.

**Comment by inodb** [comment]
@ritikakundra

**Comment by ritikakundra** [comment]
The TCGA acc is empty in overrides. Where is the path of this study on dashi-dev? gdac-portal in staging just has uvm and tgtc.

**Comment by chenh4** [comment]
I added a data_clinical file to the chol_jhu_2013 study in Triage, and the clinical information there is still keep loading. Will try to import into MSK portal to see if there is any difference.

**Comment by zheins** [comment]
I noticed this happened with the Illumina data as well. If the clinical data file has blanks and not NA for unpopulated fields it creates these issues.

**Comment by chenh4** [comment]
Blanks and not NA for unpopulated fields are just checked. Ino, are the SAMPLE_DISPLAY_NAME and PATIENT_DISPLAY_NAME in the code the same as the clinical attributes we use for clinical file?

**Comment by inodb** [comment]
Yes
