### ISSUE TITLE
CN segments tab: remember zoom

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5700]
Not sure if this is possible but... currently, the IGV zoom resets whenever a filter is added or cleared. Ideally, I would like the IGV viewer to remember the zoom when filters are added/removed.

**Comment by tmazor** [comment]
This would still be a nice feature to add

**Comment by adamabeshouse** [comment]
@tmazor can you elaborate, what do you mean by "filter added or cleared?

**Comment by onursumer** [comment]
@adamabeshouse This happens in the study view page.

To reproduce:

1. Go to https://www.cbioportal.org/study/cnSegments?id=ov_tcga_pub
2. Zoom into the Genomics Viewer, e.g. by clicking on a chromosome number
3. Go to the summary page
4. Filter samples by a chart/table
5. Go back to the CN segments tab

Current behavior: Genomics Viewer resets its zoom level to the default (whole genome)
Desired behavior: Keep the previously user selected zoom level

Hope this helps!
