### ISSUE TITLE
CN segments: 3-frame translate doesn't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5701]
If I select "Three-frame Translate" in the upper track, the track gets taller to allow room for the translation, but nothing appears.

**Comment by onursumer** [comment]
Seems like an IGV library bug to me. If this is critical, we should let them know.

**Comment by jjgao** [comment]
Let's move forward without this one, but @onursumer please report it to igv.

**Comment by tmazor** [comment]
This appears to be fixed
