### ISSUE TITLE
StudyView API's are not secured for private portal

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#5702]
For private instances, user can still get data for StudyView API's(http://www.cbioportal.org/api/swagger-ui.html#/Study_View) even if he doesn't have access to studies

**Comment by jjgao** [comment]
@kalletlak could you help fix this? Any other APIs that are not secured?

**Comment by kalletlak** [comment]
@jjgao looks like this is the only one missing it. opened pr to fix it.
