### ISSUE TITLE
Allele Freq columns are empty for downloaded data from Mutations tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5704]
note: they can be calculated from reads

Allele Freq (T) = [Variant Reads] / [Variant Reads + Ref Reads]

Allele Freq (N) = [Variant Reads (N)] / [Variant Reads (N) + Ref Reads (N)]

**Comment by dippindots** [comment]
This issue described the same issue and has been solved in the #5407
