### ISSUE TITLE
mutations tab annotation tracks should always be load-able 

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5705]
Go to this query: http://bit.ly/2RJPrji
Go to CDKN2A
The Cancer Hotspots track is unselectable.

My guess is that this is because neither of the 2 mutations in CDKN2A are in Cancer Hotspots.

First, can someone confirm that my guess is correct?

Second, if my guess is correct, I think it is preferable to be able to load the track no matter what, and it just won't have any dots on it.

**Comment by onursumer** [comment]
@tmazor your guess is correct, if there is no data available, the track is disabled.
