### ISSUE TITLE
rename log2cna to linear cna for firehose CNA data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#571]
For Firehose study, we only need to change our config sheet. I've done
that -- renamed log2 to linear and changed description. We would need
to change checked in files for TCGA projects as well. Ritika, could
you do that for all TCGA checked published studies and override
studies?

* Rename data_log2CNA.txt to data_linear_CNA.txt, and similarly the meta file.
* Change the meta file content

**Comment by fedde-s** [comment]
Sounds good. @zheins and @priti88 might have to check if the changes in the meta file would have any impact on the work they have been doing with regards to the full-study data loading script during the hackathon (overlapping #528 and #479), particularly anything that may use existing fields to ease the conversion to the new meta file (and filename) conventions.

**Comment by ritikakundra** [comment]
Renamed all TCGA and one celline to data_linear_CNA.txt and meta_linear_CNA.txt
Metafile content has also been updated based on the config file data.

**Comment by ritikakundra** [comment]
Can I close this?

**Comment by jjgao** [comment]
@ritikakundra let's keep it here until we fixed the database.
