### ISSUE TITLE
Multiple filters causes incorrect selection of sample

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#5710]
If you add multiple filters the sample selection freezes after a while and does not change on further filtering.
![screen shot 2019-02-07 at 5 28 05 pm](https://user-images.githubusercontent.com/12007862/52447091-c7e0c600-2afd-11e9-88dc-03466456e45c.png)

**Comment by zhx828** [comment]
@onursumer could you take a look this ticket? https://cbioportal.mskcc.org/study?id=brain_pdx_msk_2018  
`https://cbioportal.mskcc.org/api/filtered-samples/fetch` returns 47 samples, but it should really return 40.
![msk cbioportal](https://user-images.githubusercontent.com/5400599/52491699-b21edf80-2b95-11e9-8cca-200c30d29669.png)
