### ISSUE TITLE
Adding a display name to allow users to visualize on their choice of ID

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#5711]
In addition to SAMPLE_ID, adding a new field called DISPLAY_NAME which if populated for a sample, will use that value over SAMPLE_ID for visualization purposes.

**Comment by jjgao** [comment]
This will just be for patient view page. If there is a display_name, it should be used in the place of sample_id on the page.

@dippindots maybe you can help with this?

**Comment by jjgao** [comment]
At the same time, @ritikakundra maybe you can start to add the display_name so that we have some data to test?

**Comment by dippindots** [comment]
@jjgao @ritikakundra Yes, I can help with this one by the early of next week.

**Comment by dippindots** [comment]
@jjgao @ritikakundra 
I found two places have SAMPLE_ID. Do we want to replace them both with the DISPLAY_NAME? And do I missing somewhere else?
![image](https://user-images.githubusercontent.com/15748980/52676610-b2eaa500-2ef8-11e9-8b07-905a078a08e8.png)
![image](https://user-images.githubusercontent.com/15748980/52676643-cf86dd00-2ef8-11e9-9e2a-a52399597ee3.png)

**Comment by jjgao** [comment]
And also in mouse over of various placed. Maybe we don't have to change them including the ones in the Clinical tab, but it would be good to add Display_name as the first row by default.

https://www.cbioportal.org/patient?studyId=lgg_ucsf_2014&caseId=P04#/patient?caseId=P04&studyId=lgg_ucsf_2014

So I am suggesting just changing to display name in the header and make it in the first row in various tables. @ritikakundra maybe that would be sufficient?

I assume we may have a display name for patient as well? @ritikakundra

**Comment by jjgao** [comment]
Maybe we should have both display name and id, ie `display_name (id)`? Otherwise it might be confusing when it's different from the url.

**Comment by dippindots** [comment]
@jjgao @ritikakundra I have done a draft of this ticket using dummy data. 
Here is the screenshot, do you think it is what we want?
![image](https://user-images.githubusercontent.com/15748980/52871571-582f9400-3118-11e9-93b9-c827e374b867.png)

**Comment by ritikakundra** [comment]
Sorry for the delay in my response. 
So I am suggesting just changing to display name in the header and make it in the first row in various tables. @ritikakundra maybe that would be sufficient?: YES

I assume we may have a display name for the patient as well? @ritikakundra: YES

I do like the idea of showing both IDs for everyone to keep track of their respective IDs.

Are we also showing it in the clinical tab?

**Comment by dippindots** [comment]
@ritikakundra I am showing it in the clinical tab right now. If we don't need it in the clinical tab, that would be much easier.

**Comment by jjgao** [comment]
@dippindots I think we should use `DISPLAY_NAME (ID)` instead of `ID (DISPLAY_NAME)`.

**Comment by dippindots** [comment]
@jjgao Yes, thanks! Just updated.

**Comment by dippindots** [comment]
@jjgao @ritikakundra Should we have some real data to test? Or I can test more cases with dummy data.

**Comment by ritikakundra** [comment]
@dippindots: I will be adding real data soon. We can test on that

**Comment by dippindots** [comment]
@ritikakundra Thanks for your help!
