### ISSUE TITLE
MDACC compendium heatmaps not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5714]
@ChrisWakefield I noticed today, the study heatmap does not show any content except the page is not availble. Is this a temporary issue?  http://www.cbioportal.org/study?id=brca_tcga_pub&tab=heatmaps

The URL we use is https://bioinformatics.mdanderson.org/TCGA/NGCHMPortal/?view=0&p0DiseaseInput=brca

![screen shot 2019-02-07 at 4 43 10 pm](https://user-images.githubusercontent.com/5400599/52444822-7b928780-2af7-11e9-924a-189035422c84.png)

**Comment by ChrisWakefield** [comment]
I was away last week, so I'm just now seeing this.  We changed some infrastructure with the web site the week before, and I assume it's related to that.  Looking into it now.

**Comment by ChrisWakefield** [comment]
@jjgao @zhx828 There were two problems.  The one with the 404 has been fixed.
Now, it works correctly if I use https://cbioportal.org as the base of my request.  If I use http:// , the request to us gets redirected (302) to https: , but then the browser complains about CORS issues (even though we include the header).  Our correspondence back in https://github.com/cBioPortal/cbioportal/issues/4833 says you were going to use the https protocol (although I had quoted the url as "//bioinformatics.mdanderson.org")

**Comment by zhx828** [comment]
@inodb what do you think about this? Why the https heatmap link will get a CORS warning? Because of the redirect?

**Comment by ChrisWakefield** [comment]
@jjgao @zhx828 Attempting to close this issue.  Please see PR #5948.  Since the PR really only changes the EXAMPLE properties file, can someone on cbioportal.org please make the same changes to their config (only adding "https:" to the URLs)?  Once that's done, there's no reason not to close this.

**Comment by zhx828** [comment]
@ChrisWakefield I will follow up. Sorry about the delay.

**Comment by ChrisWakefield** [comment]
@zhx828 I realize now that the code that needs changing is over in cbioportal-frontend, and the PR mentioned above won't help anything (already closed it).  I will submit a new PR to frontend.
