### ISSUE TITLE
Option to use cancer genes to filter genes on study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5716]
For both Mutated Genes and CNA Genes table, add a toggle option to show only Cancer Genes (the OncoKB list), on by default.

@zhx828 maybe do some mockup first.

**Comment by jjgao** [comment]
@zhx828 could you prioritize this one? Maybe @dippindots can help?

**Comment by zhx828** [comment]
@jjgao I notice in the ticket https://github.com/cbioportal/cbioportal/issues/5213 we also want to filter the table by oncogenicity. Should we do the mockup together?

**Comment by jjgao** [comment]
@zhx828 let's not worry about oncogenicity for now -- it'll be harder b/c we will have to annotate all mutations. In this one we just need to filter based on the oncokb cancer gene list.

**Comment by jjgao** [comment]
@zhx828 maybe just add a filter icon before the download icon would do the trick?

**Comment by zhx828** [comment]
After discussing with JJ, we are going to use the realtime oncokb cancer gene list to filter the genes.

**Comment by zhx828** [comment]
@schultzn JJ and I had some discussion about this ticket. We would love to add a oncokb column in the table to indicate whether the gene is from oncokb cancer gene list, and sort the table by oncokb column. Then you would also have some links out to oncokb gene page.
Filtering the table by oncokb cancer gene list would miss some genes that highly mutated in subset of the study.
What do you think? I will post a mock up later.

**Comment by schultzn** [comment]
Should it be a column, and do we have room for that? Or a simple check box at the top of the table?

**Comment by zhx828** [comment]
@schultzn I would vote for a column and it will only be a column with symbols, it should take very minimum of the space. Will send a mock up shortly.

**Comment by schultzn** [comment]
Ok… a column and a checkbox?

And this will only be to indicate whether a gene is a TSG or OG? Or in general in OncoKB - maybe that is better.

And what about step 2: Filter table for oncogenic mutations only, to get driver alteration frequencies. :-)

**Comment by zhx828** [comment]
@schultzn I'm going to include all genes in oncokb cancer gene list
for the step 2, we don't have the capacity to do that yet, but JJ and I are in discussion and hopefully one of the GSOC student can take that and bring in the full OncoKB analysis into study view page.

**Comment by jjgao** [comment]
We may not need a checkbox as long as it is sorted by OncoKB by default. This may reduce some confusion as people may search for their genes (non-cancer genes) and they would have to figure out they need to do one more step to bring them in. (we had a number of users asking about missing genes in the mutated genes table previously when we had the filter)

**Comment by zhx828** [comment]
@jjgao @schultzn what do you think?
![screen shot 2019-03-07 at 6 54 24 pm](https://user-images.githubusercontent.com/5400599/53997506-77fc1b80-410a-11e9-8dc5-f323d04317d3.png)

**Comment by schultzn** [comment]
It's a good start - but maybe a little too large / in your face?

I like the size of the MutSig icon. 

![image](https://user-images.githubusercontent.com/11892704/54004544-e9949380-4123-11e9-9dc5-16df715e535f.png)

**Comment by schultzn** [comment]
It's close... so maybe just a little smaller?

**Comment by zhx828** [comment]
@schultzn what about this one? 
![screen shot 2019-03-08 at 9 46 17 am](https://user-images.githubusercontent.com/5400599/54035316-1928b780-4187-11e9-8065-f256c39496d5.png)

**Comment by zhx828** [comment]
@jjgao @schultzn  I was going to add the oncokb gene page link out but just realize not all of cancer genes have been curated. So you will have link out that actually goes to main page(because oncokb redirect the unknown gene request to main page). Is this expected?

**Comment by jjgao** [comment]
@zhx828 maybe for OncoKB curated genes, link to the gene page. For other genes, link to the cancer genes page?

**Comment by zhx828** [comment]
@jjgao sounds good. @schultzn @jjgao what do you think about the design though?

**Comment by schultzn** [comment]
Looks good - not 100% sure about the header using the same (but larger) symbol, but I don’t have a better idea.

**Comment by zhx828** [comment]
@schultzn :  @jjgao suggested to use black in the header. What do you think?
<img width="404" alt="Screen Shot 2019-03-11 at 3 01 36 PM" src="https://user-images.githubusercontent.com/5400599/54150359-a3368180-440e-11e9-931b-293e75d26f2b.png">

**Comment by schultzn** [comment]
Nice!

**Comment by zhx828** [comment]
@schultzn @jjgao I have a running instance here including the feature. Could you take a look and give me some suggestions? Thanks. https://cbioportal-frontend-pr-2109.herokuapp.com/study?id=cellline_nci60

**Comment by schultzn** [comment]
It looks good - but I still think it is too many blue circles. 

Also, what if others want to use a different list of cancer genes? Can we revisit the option of having a simple checkbox in the header of the table? Maybe we can get together and brainstorm briefly?




It looks so much better in this view:

**Comment by schultzn** [comment]
Attachments don't make it through when responding via email. Sorry. 

This looks good:
![image](https://user-images.githubusercontent.com/11892704/54169798-933c9300-444a-11e9-95e9-8bb29e50673e.png)

**Comment by schultzn** [comment]
Not this (the default):

![image](https://user-images.githubusercontent.com/11892704/54169813-a8b1bd00-444a-11e9-979e-f750ef5dc644.png)

**Comment by zhx828** [comment]
@schultzn yeah, but for msk studies, probably all of the genes will have the icon. :(

**Comment by jjgao** [comment]
@zhx828 @schultzn should we try different icons/colors for TSG and oncogenes?

**Comment by zhx828** [comment]
@jjgao @schultzn I use O and T for oncogene and tumor suppressor. If no gene type specified, I use oncokb icon. let's discuss at Thursday meeting.

<img width="408" alt="Screen Shot 2019-03-12 at 4 22 22 PM" src="https://user-images.githubusercontent.com/5400599/54233300-0eea1e80-44e3-11e9-9a04-0a8088b97859.png">

**Comment by schultzn** [comment]
Sorry, didn’t have enough time today. It would be great if we could brainstorm a little before you go any further.

I still think the following would work better:
- By default, show only cancer genes
 - If the study has genes that are not cancer genes, add an option in the header to “show all genes”
 - When all genes are shown, add the new column with a symbol for cancer genes. If the source of the information is OncoKB, show the OncoKB icon - but allow others to change it.

What do you think?

**Comment by jjgao** [comment]
@zhx828 : @schultzn and I had a discussion and thought of the followings:

- no separate column for oncokb
- no checkbox
- use a different style for cancer genes, e.g. bold
- hovering a bold gene would display e.g.: "TP53 is included in the [OncoKB Cancer Genes List] (link) as a tumor suppressor gene [link out icon to the gene page]"
- when click Gene column to sort, sort by cancer genes first, then frequency, then gene name (A tooltip on Gene header: "Click to sort by cancer genes first")
- when click Freq for sorting, sort by Freq first; similarly for any other columns

**Comment by zhx828** [comment]
Sounds good.

**Comment by zhx828** [comment]
@schultzn @jjgao 
In current production, we use the bold style to emphasize the gene is selected. I would propose to change that style by adding a checkbox instead. Bold gene name will be a indication of the cancer gene.

![Screen Shot 2019-03-14 at 11 24 55 AM](https://user-images.githubusercontent.com/5400599/54369174-d6b21f80-464b-11e9-97c2-992cdb20a54c.png)

**Comment by schultzn** [comment]
Good idea!

**Comment by tmazor** [comment]
I'm a bit worried that having 2 checkboxes with different meanings (add to query vs apply filter) is going to be confusing.

This also changes the meaning of bold in these tables, which could also be confusing for users.

I know I'm jumping into this conversation late, and I don't immediately have any better suggestions, but can we think some more about this?

**Comment by schultzn** [comment]
Yes, let’s definitely think about it so more.

Changing the meaning of bold might be ok though - users can quickly get used to it, I think.

**Comment by jjgao** [comment]
I was also a little worried about changing the meanings of bold but I think it's just b/c I am used to it and I will probably adjust quickly.

I think a selection icon is actually a more intuitive way to indicate the gene is selected for query, but I agree that the current icon could cause confusion. Maybe a query (e.g. magnifier) would work better?

**Comment by schultzn** [comment]
I like Hongxin’s proposal to add a checkbox, but only show a checked checkbox after a user clicks on a gene. I think users will get used to this change very quickly, even if we don’t use bold for cancer genes.

**Comment by zhx828** [comment]
@tmazor @schultzn @jjgao I have the latest instance running here https://cbioportal-frontend-pr-2109.herokuapp.com/study?id=lgg_tcga, please take a look and let me know what you think.

**Comment by jjgao** [comment]
Maybe instead of a linkout icon just put the link on the gene name?

![image](https://user-images.githubusercontent.com/840895/54706362-1c239080-4b15-11e9-96a4-cf67ed363af0.png)

**Comment by zhx828** [comment]
On both ATRX in the example?

**Comment by jjgao** [comment]
@zhx828 no just the one in "ATRX is...".

Maybe we should remove "Click ..." and when hovered over, maybe we should just display a checkbox for people to check? We can also remove the blue box.

**Comment by zhx828** [comment]
@jjgao I could remove the blue box. But personally I don't like to add a check box when hover because you need to do the following in order to click on the gene 
- hover gene name
- move mouse to the check box
- Click on the checkbox

You can also miss the checkbox if you accidentally moved the mouse else where.

**Comment by jjgao** [comment]
@zhx828 good point, but maybe you can show the checkbox when hovering on the `<td>` instead of the gene name? In general I think it's better to use intuitive/conventional UI elements without hover-over text explanation.

**Comment by zhx828** [comment]
![Apr-15-2019 11-09-06](https://user-images.githubusercontent.com/5400599/56143806-36fbf000-5f6f-11e9-9e5c-cd320f689d95.gif)

Hi @schultzn @jjgao @cBioPortal/product I have the latest design of this table running here https://filter-cancer-gene-list.herokuapp.com/study?id=lgg_tcga. If you could take a look and give me some feedbacks, that would be awesome. Thanks!

**Comment by Sjoerd-van-Hagen** [comment]
Why is this limited to oncokb? We also have civic, hotspots and custom driver annotations.

**Comment by zhx828** [comment]
@Sjoerd-van-Hagen this is not for annotation. This is implementation for cancer gene filtering. At the moment, we are using OncoKB Cancer Gene List(https://oncokb.org/cancerGenes). But the implementation can be change to other source if needed.

**Comment by Sjoerd-van-Hagen** [comment]
But those are strongly related. If something is marked as a driver  it should be in the list when applying the filter. If it is not marked it should be filtered out. That is the idea, right?

**Comment by zhx828** [comment]
@Sjoerd-van-Hagen actually OncoKB Cancer Gene List is generated not based on annotation team but rather base on different gene panels. As you can see in here(https://oncokb.org/cancerGenes) we consider six different gene panels. The purpose of this feature is filtering out noise genes. I'm sure @schultzn  can give more information. Again, this should be a general implementation for cancer genes. If you have any suggestion of other cancer gene list, we would love to discuss it.

**Comment by schultzn** [comment]
I agree that this could be linked to any cancer gene list - and we discussed this a lot internally. We could also use the Cancer Gene Census, or any other list. We just need one icon to represent that list so that a user can easily toggle. We can also discuss this on the next call.

**Comment by Sjoerd-van-Hagen** [comment]
I see.

If we would like to generalize this in the future we should go for a generic filtering icon I think.

**Comment by schultzn** [comment]
I agree - but good look finding a federal “cancer genes” icon. :-)

**Comment by Sjoerd-van-Hagen** [comment]
I don't know about a federal icon, but I was thinking to just pick the funnel type icon: https://www.google.com/search?tbm=isch&q=filter+icon&chips=q:filter+icon,g_1:transparent:XCW-_vHaJFk%3D&usg=AI4_-kQ8GmMz4jcKtx7t0N9WzWBhOrd8uA&sa=X&ved=0ahUKEwjVhIOLidPhAhVmUN8KHbrADbQQ4lYIJygA&biw=1920&bih=931&dpr=2#imgrc=9tisrLIVLRLEcM:

**Comment by schultzn** [comment]
But it would be nice to somehow indicate that the user is filtering by cancer genes..

**Comment by Sjoerd-van-Hagen** [comment]
How about using the filter icon which, when clicked, shows a drop down menu with the sort options?

**Comment by schultzn** [comment]
That might work -  but I think the goal was to design something that only requires a single click.

**Comment by Sjoerd-van-Hagen** [comment]
For now that works but when we want to generalize in the future we will likely need more clicks (two).

**Comment by zhx828** [comment]
@schultzn @jjgao @Sjoerd-van-Hagen do we have a conclusion yet?

**Comment by jjgao** [comment]
@zhx828 based on the discussion above, we can go ahead with the oncokb icon, I think.

**Comment by Sjoerd-van-Hagen** [comment]
I am fine with it but have a personal preference for a filter icon. Mainly because it is a filter. A hover over could show 'filter by oncokb cancer genes. That would still be one click but it is clear that a filter is set, and can be extended in the future. @schultzn what do you think?

**Comment by schultzn** [comment]
How about a cancer ribbon instead of the OncoKB icon?

**Comment by Sjoerd-van-Hagen** [comment]
I would like to make explicit that the list is filtered and the user is not seeing all the genes. How would you do that with the ribbon?

**Comment by schultzn** [comment]
The same as with the OncoKB symbol - there will be two versions, one to indicate “selected”, the other to indicate “not selected”.

**Comment by Sjoerd-van-Hagen** [comment]
I think I would still prefer the funnel symbol that is typically used to signify filters, but have no strong objections to using the ribbon.

**Comment by jjgao** [comment]
@schultzn and I had some discussion and agreed that we can use a filter icon with a tooltip as @Sjoerd-van-Hagen suggested.

tooltip:
- "Filtered by OncoKB Cancer Gene List. Click to show all genes."
- "Showing all genes. Click to filter by OncoKB Cancer Gene List"

**Comment by zhx828** [comment]
Thank you everyone.

**Comment by zhx828** [comment]
@schultzn @jjgao @Sjoerd-van-Hagen  the interface will be the following. I will send out a testing interface soon.

## After filtering
<img width="428" alt="Screen Shot 2019-05-15 at 10 32 48 PM" src="https://user-images.githubusercontent.com/5400599/57822252-69ad2a00-7761-11e9-948b-ba45872fc86f.png">

## Before filtering
<img width="431" alt="Screen Shot 2019-05-15 at 10 32 56 PM" src="https://user-images.githubusercontent.com/5400599/57822254-6a45c080-7761-11e9-81de-2841459294ad.png">

**Comment by zhx828** [comment]
@schultzn @jjgao @Sjoerd-van-Hagen here is the testing instance https://cbioportal-frontend-pr-2109.herokuapp.com/study/summary?id=acc_tcga

**Comment by Sjoerd-van-Hagen** [comment]
The filter should be disabled by default imo.

For instance, in the example, MUC16 has a higher number of mutated samples than MUC4 but is not shown by default, even though it is associated with ovarian cancer (enough to spend money on trying to create a drug for it that targets this gene (OREGOVOMAB)) where CA-125 is also used as a biomarker, and has a very high occurrence in melanoma. I think people would like to see MUC-16 in this list.

In any case, I think by enabling this filter by default we are forcing our opinion, on what the cancer genes are, a bit too much.

**Comment by Sjoerd-van-Hagen** [comment]
Wait, disregard the last comment. There seems to be a bug. If I follow the link I see the icon is enabled and the text says it is filtered, but it is actually not. The behaviour of the switch mirrored.

**Comment by schultzn** [comment]
We can debate whether enabling or disabling is the best route - I am ok with disabling, but would personally always enable it right away. :-)

While CA125 is an ovarian cancer biomarker, MUC16, which encodes it, is one of the largest genes in the genome and notorious for its high background mutation rate. So the high frequency of mutations is very misleading for those who don’t know…

**Comment by jjgao** [comment]
@zhx828 maybe this setting can be saved into local storage so that people can have their own preference?

**Comment by Sjoerd-van-Hagen** [comment]
I think we really need to have user preferences at some point. Or perhaps advanced and beginner modes or something. So many bells and whistles...

Problem is then that the solution space for the inputs will become even larger, which will make testing more difficult.

**Comment by Sjoerd-van-Hagen** [comment]
> Wait, disregard the last comment. There seems to be a bug. If I follow the link I see the icon is enabled and the text says it is filtered, but it is actually not. The behaviour of the switch mirrored.

Before it is hidden by the more recent posts. @zhx828

**Comment by zhx828** [comment]
@Sjoerd-van-Hagen I don's see the issue though. Could you give me more info which gene is showing up which should not be?

**Comment by Sjoerd-van-Hagen** [comment]
Ah, my mistake. I somehow assumed that the genes with the small icon behind it were in the OncoKB list but it is just a coincidence that if I click the filter the top genes all have the icon...

@schultzn I now see that MUC16 is actually in the list too...

**Comment by jjgao** [comment]
@zhx828 anything left for this?

**Comment by zhx828** [comment]
@jjgao nope. Just need to verify everything looks good. Then I will schedule the release.

**Comment by jjgao** [comment]
@zhx828 thanks, please prioritize.

**Comment by zhx828** [comment]
@jjgao could you take a final look at this feature? https://cbioportal-frontend-pr-2109.herokuapp.com/study/summary?id=lgg_tcga

**Comment by jjgao** [comment]
@zhx828 It looks great! Thanks.

**Comment by zhx828** [comment]
@jjgao @schultzn @Sjoerd-van-Hagen this feature is not released.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen @schultzn should we try to remember user's preference in local storage / cookie?

**Comment by Sjoerd-van-Hagen** [comment]
If it is not too much effort and you are willing to do that, I would say yes.

**Comment by Sjoerd-van-Hagen** [comment]
It is probably not so much a bug in the menu itself but in the way it is used.

**Comment by zhx828** [comment]
@jjgao @Sjoerd-van-Hagen created an issue https://github.com/cBioPortal/cbioportal/issues/6274
