### ISSUE TITLE
0% should be displayed instead of 'N/P' on oncoPrint when any genes of interest is not tested in selected molecular profiles

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#5719]
Hi cBioPortal team,
can you please investigate why 'N/P's showed up as opposed to "0%"s when the genes of interest are not tested in selected molecular profiles?
> We are having trouble showing a gene as "N/P" as opposed to the "0%" we are getting in our local instance (v2.0.1).
>We downloaded the blca_mskcc_solit_2014 study as a sample to look at.
>When ran on your server, the OncoPrint screen shows "N/P" (Not Profiled).  When we run a search for the same genes, it says "0%".  So we're trying to figure out what is wrong with our configuration.
Attached are screenshots showing the differences in the 2 instances.
![np-from-oncoprint](https://user-images.githubusercontent.com/17375786/52507942-02f7fd80-2bc1-11e9-9710-60066839a75c.png)

**Comment by jjgao** [comment]
@khzhu is it from a user? It's probably that they haven't import the gene panel data properly.

**Comment by khzhu** [comment]
no, the screenshot I took from cbioportal.org this afternoon.

**Comment by khzhu** [comment]
![screen shot 2019-02-08 at 2 44 50 pm](https://user-images.githubusercontent.com/17375786/52509788-756bdc00-2bc7-11e9-9e9c-a37ab0af87bc.png)
![screen shot 2019-02-08 at 2 45 33 pm](https://user-images.githubusercontent.com/17375786/52509793-7b61bd00-2bc7-11e9-81f5-83cfc71016af.png)

**Comment by khzhu** [comment]
@jjgao , attached two from the user.
