### ISSUE TITLE
Heatmap menu not working when invalid gene is filled in

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#5720]
Steps to reproduce:
1. submit this query http://www.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=brca_tcga&case_set_id=brca_tcga_cnaseq&data_priority=0&gene_list=SOX9%2520RAN%2520TNK2%2520EP300%2520PXN%2520NCOA2%2520AR%2520NRIP1%2520NCOR1%2520NCOR2&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&tab_index=tab_visualize
2. Click "Add heatmap" with SOX9 and TEST (see screenshot below)
![image](https://user-images.githubusercontent.com/2900303/52557645-5308d700-2df0-11e9-8ea2-66ee46dbb401.png)
3. No heatmap will be rendered. Also not after removing the invalid gene id

**Comment by adamabeshouse** [comment]
good catch, I'm surprised we didn't see this earlier. we should reuse the component from the study view which validates genes.

**Comment by adamabeshouse** [comment]
lets do this after https://github.com/cBioPortal/cbioportal-frontend/pull/1994 is merged
