### ISSUE TITLE
issue with importing gene panel data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5721]
A user reported [here](https://groups.google.com/forum/#!msg/cbioportal/81x2PSSrBN4/jrid41KOAAAJ):

- Both the gene_panel and gene_matrix files were imported
- But in the database, only gene panel for mutations existed
- In oncoprint, it seemed that gene panel for CNA got picked up but not for mutations (see screenshots below)
- The user has tried both blca_mskcc_solit_2014 and msk_impact_2017

On user's instance:
![image](https://user-images.githubusercontent.com/840895/52579067-75e8ba80-2df3-11e9-8bad-8d76b424920c.png)

It should be (on our production):
![image](https://user-images.githubusercontent.com/840895/52579074-797c4180-2df3-11e9-8705-95ac0758a347.png)

**Comment by jjgao** [comment]
More update from user:

Ran a test today.  Loaded your entire public download of the cbioportal database into our instance.  Stated tomcat and looked at the msk impact 2017 study without any issues, including querying of a non-profiled gene (E2F1) which showed ‘N/P’ (example below (1)).

Loaded our study and it still shows 0%.  (example below (2).

I then reloaded the msk_impact_2017 study:

[cportal@cbioportal importer]$ ./metaImport.py -n -s /home/cportal/PortalStudies/msk_impact_2017 -o

Your query again shows only the mutation entries in the sample_profile query you asked us to run.  Before running the import, the cna notations for them were present.  After reloading the CNA Genes Panel failed to load the ‘Infininte or NaN’ error.  Querying for E2F1 now shows 0%.

It appears to me that there is something not working properly in the metaImport.py script.

**Comment by tmazor** [comment]
@priti88 has noticed with our instance that you have to manually import the gene matrix after cbioportalImporter.py finishes.

**Comment by priti88** [comment]
@jjgao cbioportalImporter.py log says it imported the gene matrix data, but I have to import it again manually for it to work.

**Comment by jjgao** [comment]
https://github.com/cBioPortal/cbioportal/pull/5602 should fix it.
