### ISSUE TITLE
problem importing the seed DB

### ISSUE THREAD

**Issue by grugna** [cBioPortal/cbioportal#5729]
I am following the instruction step by step ( https://docs.cbioportal.org/2.1-deployment/import-the-seed-database ) but after I unzip the file at the GitHub page containing the seed I can't run this command `mysql --user=cbio_user --password=somepassword cbioportal < cgds.sql` since there is no cads.sql file. And I I try to load the unzipped one `mysql --user=cbio_user --password=password cbioportal < ~/Downloads/seed-cbioportal_hg19_v2.7.2.sql` I get `Table 'cbioportal.authorities' doesn't exist`.
I followed all the steps in the pre-build and building from source section, what am I doing wrong?

**Comment by dddfff22** [comment]
https://raw.githubusercontent.com/cBioPortal/cbioportal/v2.0.0/db-scripts/src/main/resources/cgds.sql 
first create new file, and copy page and paste in new file, and rename file cgds.sql.
