### ISSUE TITLE
replace PDF button to Print button (keep SVG button)

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5738]
Currently PDF was converted by our backend from the SVG. The SVG-to-PDF converter we are using (Batik) is buggy. We have spend quite a lot of time to make it work but keep bumping into new issues, e.g., [the latest issue](https://github.com/cBioPortal/cbioportal-frontend/pull/1835#issuecomment-461174004). We can spend more time to fix/update it or replace it with a Javascript one. But now I am considering another option. Can we change the PDF button to a Print button, which will open a print window ([window.print()](https://stackoverflow.com/questions/242182/how-can-i-pop-up-a-print-dialog-box-using-javascript)) of the SVG for print and the user can save them to PDF? 

@cBioPortal/product @alisman do you think that would be ok?

**Comment by schultzn** [comment]
I have always loved the SVG download function - the SVGs were always easy to edit in Illustrator, without having to release endless clipping masks or removing duplicates of the same shapes, which often seems to happen with PDF downloads. But would your print option take care of all these issues?

**Comment by alisman** [comment]
@jjgao @schultzn 
To see how this would look:

1. go to a page with a visualization
2. bookmark this js and run it (or just run it browser console)

javascript:(function()%7Bwindow.el%20%3D%20%24(%22.VictoryContainer%3Avisible%22).remove()%24(%22body%22).empty().append(window.el)%3Bwindow.print()%7D)()

you should be prompted to print and you can then output to PDF and see what happens

**Comment by jjgao** [comment]
@schultzn the print option will not take care of these issues. But if a user knows to use Illustrator, hopefully they'll just pick SVG.

**Comment by jjgao** [comment]
@schultzn @tmazor OK we move forward?

**Comment by schultzn** [comment]
I am confused - I thought the proposal was to no longer allow support the SVG download. But maybe I misunderstood, and the conversion to PDF was the issue. If that is the case, then sure, printing to PDF will solve that. Is that a feature in Windows though?

**Comment by jjgao** [comment]
The SVG button will still be there (exact the same way).

The proposal is to replace the PDF button with a Print button. (Currently the PDF is converted from SVG and that's not easy to maintain.)

The print() function should work on most browsers, but print to pdf may not be supported by all browsers. It should hopefully work on all OS for the same browser but we should test.

**Comment by jjgao** [comment]
@dippindots maybe you can help with this one?

**Comment by dippindots** [comment]
@jjgao Sure, I will try to change some pdf button to window.print() function and make a pr for testing. I will post the link at here then.

**Comment by dippindots** [comment]
@cBioPortal/product The pdf download has been replaced with window.print() function. You can use this link for testing:https://cbioportal-frontend-pr-2071.herokuapp.com/. Thanks!

**Comment by tmazor** [comment]
@dippindots it doesn't work for me.

In study view for MSK-IMPACT, I tried to download the Number of Samples Per Patient chart to PDF, but when I click "PDF" nothing happens.

In Chrome and Firefox, clicking TSV or SVG does successfully download files. However, in Safari, I get errors when I click on TSV or SVG:
![image](https://user-images.githubusercontent.com/10508276/53442724-ee48a180-39d7-11e9-802e-bfcd00256025.png)

**Comment by dippindots** [comment]
@tmazor sorry I didn't noticed that the download in study view page is different. In the result view, the chart pdf download is replaced, I will take another look to the study view. Sorry about that.

**Comment by tmazor** [comment]
I tried a query with KRAS in MSK-IMPACT:
- on OncoPrint, the PDF download complains: "Oncoprint too big to download as PDF - please download as SVG."
- on Cancer Types Summary/Plots, the download to PDF option appears to work, in that it opens a new window with the plot in the background and the print screen in the foreground. But from there, my success varies by browser:
Chrome: From the chrome print screen, I selected "Print using system dialog", and from there the PDF save option. But the file that gets saved is empty (0 bytes).
Firefox: The print screen that appears is the system print option, I select the PDF save option, and it saves a PDF correctly.
Safari: The print screen that appears is the system print option, I select the PDF save option, and it saves a PDF. However, the plot I tested with is very wide (cancer types summary) and this PDF does't include the full image.

**Comment by dippindots** [comment]
@tmazor Thanks for your feedback, I will search for the solution and then update my pr.

**Comment by dippindots** [comment]
@cBioPortal/product After a search for the solution and discussion. The window.print() function do have its limitation: 
1. The different browser may handle the print event in a different way
2. It cannot handle a very large SVG. A very wide SVG (cancer types summary) doesn't include the full image.

@alisman and I were thinking if we want to generate pdf on front-end, we can consider using a front-end library or a web service to replace our back-end service. Thanks!

**Comment by alisman** [comment]
@cBioPortal/product just want to clarify: when we use browser's print to create PDF, at least in chrome, the browser print UI offers the user limited ability to set width of PDF.  this is because it's oriented toward printing to paper.   we are also subject to different browsers's print interface.  if this is a problem, then we should investigate frontend PDF generation or a 3rd party svg2PDF api type service.

**Comment by jjgao** [comment]
Thanks, @dippindots @alisman. 

Maybe we can try a frontend svg2pdf converter, e.g. https://github.com/yWorks/svg2pdf.js/tree/master?
