### ISSUE TITLE
ln?q=TP53:MUT is not working any more

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5742]
Is it b/c the URL is too long?

https://www.cbioportal.org/ln?q=TP53:MUT

two solutions:

1) we only expand it to TCGA Pancancer Studies
2) use post

**Comment by alisman** [comment]
@jjgao out of curiousity, when did you test the ln request?  b/c there was a big outtage at around 11:30

**Comment by jjgao** [comment]
Right before I created this issue (12:08) so it should be after 11:30.

**Comment by jjgao** [comment]
Now a user is asking: https://groups.google.com/forum/#!topic/cbioportal/Q4e3B9duxu0

**Comment by jjgao** [comment]
It maybe related to the nginx limit. (we recently switched to nginx when moving to aws)

**Comment by jjgao** [comment]
another related one: https://groups.google.com/d/msg/cbioportal/2eiP2TiNy_E/1kInmbhzBwAJ

**Comment by jjgao** [comment]
another user: https://groups.google.com/d/msg/cbioportal/zEvkMQX5zcE/GnppOGhGBwAJ

**Comment by jjgao** [comment]
I logged the long url bug here: https://github.com/cBioPortal/cbioportal/issues/5836

**Comment by inodb** [comment]
this is solved n deployed
