### ISSUE TITLE
cbioportal login doesn't persist to OQL page

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5745]
Log in on the homepage. Click on the link to the OQL page. It opens in a new window and loses the fact that I am logged in:
<img width="1429" alt="untitled" src="https://user-images.githubusercontent.com/10508276/52824259-e9a1f600-3085-11e9-80ba-c3729b921602.png">

**Comment by jjgao** [comment]
This is strange. And if you click to the home page from the oql page, you are still not logged in. Only if you refresh the page, you'd be logged in.

**Comment by tmazor** [comment]
This is still an issue
