### ISSUE TITLE
If running cBioPortal on a non-default port, the bookmark widget does not specify the port

### ISSUE THREAD

**Issue by marriott-er** [cBioPortal/cbioportal#5750]
Found by @tmazor .  I hardcoded it as a workaround in a local deployment, but thought I'd file an issue for the record.

Behavior:
![image](https://user-images.githubusercontent.com/43185833/52877588-700f1400-3128-11e9-8054-d4d8673a27c0.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/43185833/52877628-8f0da600-3128-11e9-8343-eda84b781f2e.png)

(two different pages but these are the screenshots I have.)

Reproduce:
Query a study, click the link icon in the top right 
![image](https://user-images.githubusercontent.com/43185833/52877761-f4619700-3128-11e9-83a0-6a04e3d9c45d.png)

Dialog box that pops up has the correct URI but without the port.

**Comment by tmazor** [comment]
@Luke-Sikina do you know if this is still hard-coded in our instance or if it is fixed?

**Comment by Luke-Sikina** [comment]
@tmazor still hardcoded.

**Comment by alisman** [comment]
@Luke-Sikina based on what i see, we are reading directly from window.location.href, which ought to include the port.  i also checked locally (localhost:3000) and it has the port.  can you double check this hasn't been fixed?

**Comment by Luke-Sikina** [comment]
@alisman This is my fault, not cbioportal's. The bug was happening because the cbioportal was running behind a proxy and nginx wasn't properly telling cbioportal what port it was running on. Closing.
