### ISSUE TITLE
download tab improvements

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5751]
I think there are a few things we can improve about the Download tab:

1) If I query "IDH1: MUT", the table at the bottom has columns for IDH1 CNA and IDH1 fusion. These columns are only ever filled with "no alteration" or "not profiled", but really there's no reason for the columns to exist if the data type wasn't queried.
--> I propose we remove columns for any gene+datatype that isn't queried.

2) If I download or copy the table at the bottom, there is no record of any OQL applied to the query. On the website, I can see the OQL in a tooltip on the column name. But once downloaded/copied, that information is lost.
--> Any OQL applied should appear in the copied/downloaded version of the table

3) At the top of the page, we include a banner saying that OQL is applied to this page. However, that's only partially true. The CNA and Mutations downloadable data files at the top of the page include all alterations, regardless of OQL. Everything else on the page does appear to reflect OQL.
--> We need to make clear that these 2 files include all alterations and ignore OQL.

@jjgao @schultzn thoughts?

**Comment by jjgao** [comment]
All good point!

**Comment by schultzn** [comment]
Agreed!

**Comment by jjgao** [comment]
There are other problems. For example, when querying `TP53: TRUNC`, samples without truncating mutations will be shown as "No alteration" but they may have missense mutations. And "No alteration" in fusion column is incorrect for most of the times (they are not profiled usually).

To fully address this, we are thinking of 1) changing the columns from one column per gene/profile to per track; and 2) adding OQL to header when OQL is used in query.

**Comment by dippindots** [comment]
@jjgao The reason why we separate the columns by alterations is: we want to differentiate each alteration is "not profiled" or is "no alteration". Because we may have a OQL has a gene mutation but "not profiled" in mRNA. Now we merge them together, I am not sure how should I show the related information.
![image](https://user-images.githubusercontent.com/15748980/54307817-f5101080-45a2-11e9-9ac4-466b6935007c.png)

**Comment by jjgao** [comment]
discussed with @dippindots in person: we will use exact what OncoPrint is displaying per track.

**Comment by jjgao** [comment]
@dippindots any reason this was moved from Review back to Backlog?

**Comment by dippindots** [comment]
@jjgao My previous implementation is not very generic, so I closed that pr and will try to come up a generic way to implement this which can also use for other tabs.

**Comment by alisman** [comment]
@tmazor could you do a final check on this:
https://cbioportal-frontend-pr-2575.herokuapp.com/

**Comment by tmazor** [comment]
Looks much better!

However, we do still have columns for data types that are not queried. They are hidden on the site, which helps, but they are still an option to view and they are part of the downloaded table. Can we remove those? @dippindots @alisman

**Comment by dippindots** [comment]
@tmazor Thanks! I will remove those unnecessary columns.

**Comment by tmazor** [comment]
Looks good @dippindots !

One final request - let me know how feasible this would be:
I understand the desire to have a single column reflecting the full track information, and then individual columns for each data type. However, I still worry that the individual column names could be confusing since they don't explicitly reference the OQL. So - can the column names for the individual data types include the relevant piece of OQL?

So for example, if I query "EGFR: MUT=T790M AMP", can the column called "EGFR MUT" instead be called "EGFR: MUT=T790M" and the "EGFR CNA" column would be "EGFR: AMP"
