### ISSUE TITLE
remove email link in Testimonials section

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5754]
We haven't received any testimonials, only questions. Let's remove it.

![image](https://user-images.githubusercontent.com/840895/52883764-0c8de200-313a-11e9-944e-e132268b02df.png)

**Comment by khzhu** [comment]
done, will send remove email link PR on Monday.

**Comment by agarwalrounak** [comment]
@jjgao Can I take up this issue?

**Comment by jjgao** [comment]
@agarwalrounak sorry, there is already a pull request -- see above.

**Comment by agarwalrounak** [comment]
I guess this issue can be closed now given that [cBioPortal/cbioportal-frontend#2112](https://github.com/cBioPortal/cbioportal-frontend/pull/2112) is merged.

**Comment by jjgao** [comment]
@agarwalrounak yes, thanks for the reminder.
