### ISSUE TITLE
Comparison: Frequency scatter plot

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5756]
I think this one belongs to the Mutations and Copy-number enrichments tab. Maybe we can allow user to switch between Vocano Plot and this one?

![image](https://user-images.githubusercontent.com/840895/52888928-b45fdb80-314b-11e9-920c-bc7e57176ed4.png)

@cBioPortal/product

**Comment by schultzn** [comment]
+1

**Comment by tmazor** [comment]
agree!

**Comment by jjgao** [comment]
@adamabeshouse for tooltip, maybe we can extend the current tooltip to include the frequencies.

![image](https://user-images.githubusercontent.com/840895/53376193-89377200-392b-11e9-9df7-193add4fb5b3.png)

The same colors as volcano plot can be used, ie. blue for significant dots and gray for insignificant ones.

**Comment by adamabeshouse** [comment]
do you want the dots to change size based on q value? personally I think no, because the significance is already captured by the blue/white coloring. and for borderline cases of significance, modulating the size won't even capture it anyway bc we'll never have enough size gradation to make those changes visible (circle sizes are considered bad for precisely comparing quantities)

**Comment by jjgao** [comment]
discussed on slack. @adamabeshouse will make some screenshots.

**Comment by jjgao** [comment]
@adamabeshouse here is an example: https://www.cbioportal.org/results/enrichments?session_id=5c747fd4e4b0f6ce58b5f2fd

**Comment by adamabeshouse** [comment]
modulating size between 1 and 5 for q values 0.2-0.01. Anything less significant is clamped to size 1, anything more is clamped to size 5.

![image](https://user-images.githubusercontent.com/636232/53378320-32359b00-3933-11e9-8676-8bb069557286.png)

And here it is with same size everywhere
![image](https://user-images.githubusercontent.com/636232/53378390-66a95700-3933-11e9-8e5f-2d89ead0120e.png)

**Comment by jjgao** [comment]
hmm... Not sure if I like the first one... 

Should we increase the opacity? And maybe the line can be lighter? And I think the axes don't have to be always 100%?

**Comment by adamabeshouse** [comment]
I agree, I don't think the size modulation adds anything. The idea of "more significant" is already a bit statistically dicey AFAIK.

**Comment by adamabeshouse** [comment]
@jjgao 

![image](https://user-images.githubusercontent.com/636232/53448249-f0652d00-39e4-11e9-984c-aee95bf3fd35.png)

**Comment by jjgao** [comment]
@adamabeshouse I like the one with higher opacity. 

I guess the reason to pick a low opacity is that overlapping dots can be seen?
