### ISSUE TITLE
White screen after refreshing results of query from study view

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#5758]
When I deploy v2.0.1 according to the [documented deployment steps](https://github.com/cBioPortal/cbioportal/blob/master/docs/System-Requirements.md), open an Oncoprint for a few dozen patients selected in the study summary view, and refresh the results view page, I see a blank page, and several exceptions in the browser console.

I believe it might be related to the `?session_id=pending` parameter in the URL.

**Comment by fedde-s** [comment]
@jjgao or @zhx828, do you know whether this bug is caused by the study view or some other page along the way? If I click the ‘back’ button (trying to get away from the blank page), I see a URL ending in `/results/legacy_submission`.

**Comment by fedde-s** [comment]
Did some recent release introduce an undocumented requirement to deploy a session service?

**Comment by jjgao** [comment]
@fedde-s could you reproduce it on https://cbioportal.herokuapp.com?

**Comment by fedde-s** [comment]
I'm not sure how, I've never done that. Do you know (or have) docs on where to start?

**Comment by zhx828** [comment]
@fedde-s I'm not aware of the issue. And could not reproduce the issue in the public portal. @adamabeshouse do you know anything about this? `?session_id=pending`

**Comment by adamabeshouse** [comment]
I know that `session_id=pending` is something @alisman set up as a temporary thing in the URL while the actual session gets saved and an id exists to put into the URL.

**Comment by fedde-s** [comment]
@zhx828:
> could not reproduce the issue in the public portal

I think that's probably because the public portal is integrated with a session service, which is optional (barely even mentioned) according to the documentation for setting up a custom installation.

**Comment by pieterlukasse** [comment]
@jjgao I think we probably need to make a decision regarding session service, i.e. whether it is a *required* dependency or not.
- If it is to remain optional, then we would need some regression tests in place to make sure this scenario keeps working. 
- If it is to be made mandatory, then we need some documentation updates, and perhaps add it to the release notes of the last release. Better exception handling will also be needed to avoid blank pages like Fedde described. 
Please let me know which solution you think is better to pursue.

**Comment by jjgao** [comment]
@pieterlukasse I was thinking about that too. I think it's probably time to make session service mandatory.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao Will you(r team) take care of the updates of the documentations, release notes and exception handling? We will need to install this for all our clients when they next update.

**Comment by jjgao** [comment]
Create a ticket for the discussion: https://github.com/cBioPortal/cbioportal/issues/5773.

Our team can take a lead on this, but I think we should get some feedback from the community first. @Sjoerd-van-Hagen

**Comment by alisman** [comment]
Hi all, the app should be capable of functioning without session service (with limitation on url length).   So, the failure @fedde-s describes is either a bug or misconfiguration (perhaps stemming from lack of documentation or inappropriate example config).  I will investigate this today.   @fedde-s could you post here the portal.properties file you are using?

**Comment by fedde-s** [comment]
Only a few lines different from the common example file: https://github.com/thehyve/cbioportal-docker/blob/v2.0.1-iss5758/portal.properties#L184

**Comment by fedde-s** [comment]
Side-note: I'm hoping to get that difference down even further at some point in the process of integrating our dockerisation solutions, and limit the config file to options for which the defaults don't apply as demonstrated [in the end-to-end tests](https://github.com/cBioPortal/cbioportal/blob/v2.0.1/test/end-to-end/runtime-config/portal.properties).

**Comment by alisman** [comment]
yeah, the empty assignment might be the problem.  i see that is what is in the EXAMPLE file.  i will confirm that frontend interprets that inappropriately as ON.    you could also try commenting out at that line, which may fix the problem.

**Comment by fedde-s** [comment]
For anyone reading along: @alisman made PR https://github.com/cBioPortal/cbioportal/pull/5796 to address this.

**Comment by alisman** [comment]
@fedde-s when you get a blank screen (b/c server fails with too long URL) do you see what http response code is?

**Comment by fedde-s** [comment]
500 (Internal Server Error) on a POST request to `/api-legacy/proxy/session/main_session`.

**Comment by fedde-s** [comment]
Without your fix in @5796, the portal doesn't put too much data into the URL. Instead, it tries to use the session service, which works initially as long as you don't try to refresh.

**Comment by inodb** [comment]
we decided to make session service a requirement

**Comment by fedde-s** [comment]
Yep, that resolved this, several releases ago already :+1:
