### ISSUE TITLE
Swagger API default scheme is http

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5760]
When browsing the API here:

https://www.cbioportal.org/api

It lists http as the default scheme, which gives errors on public portal when clicking on execute. We should maybe only show the https scheme when browsing over https, and http when browsing over http

**Comment by jjgao** [comment]
@Luke-Sikina maybe you can help fix this?

**Comment by Luke-Sikina** [comment]
I don't think this can be done right now. I put a question in SpringFox's glitter, but from what I can tell, `Docket.properties` is a HashSet, which blows away any ordering on the submitted list. There are a few outcomes here:
1. I am wrong, someone in the chat tells me what to do. I do it, it works, we rejoice.
2. I am right, but they are fine with me submitting a PR. I do that, we upgrade when its released. We rejoice several months from now.
3. I am right, but they have a good reason for it being a HashSet. We suffer.

**Comment by jjgao** [comment]
@Luke-Sikina maybe at least submit this issue to them?

**Comment by Luke-Sikina** [comment]
@jjgao Honestly, if I don't get a reply soon on their chat, I'm just going to put up a PR. It's a pretty small change, and a similar one went through recently.
