### ISSUE TITLE
Genome Nexus annotation issue for long deletions

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5761]
Somehow the allele_string reported can be longer than the given input:

https://www.genomenexus.org/beta/annotation/genomic/3,41266016,41266403,GCTGATTTGATGGAGTTGGACATGGCCATGGAACCAGACAGAAAAGCGGCTGTTAGTCACTGGCAGCAACAGTCTTACCTGGACTCTGGAATCCATTCTGGTGCCACTACCACAGCTCCTTCTCTGAGTGGTAAAGGCAATCCTGAGGAAGAGGATGTGGATACCTCCCAAGTCCTGTATGAGTGGGAACAGGGATTTTCTCAGTCCTTCACTCAAGAACAAGTAGCTGGTAAGAGTATTATTTTTCATTGCCTT,-?fields=annotation_summary,mutation_assessor&isoformOverrideSource=uniprot

The allele string given is 255 characters but the result allele_string is 388. When using the GenomeNexusCache this gives a lot of missing data, because the key used for the fetched data is different from the key for querying.

**Comment by jjgao** [comment]
@inodb should this be moved to GN repo?
