### ISSUE TITLE
MutSig button not loading data

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#5768]
User reported bug: https://groups.google.com/forum/#!topic/cbioportal/oSHk0fWNrxg

**Comment by jjgao** [comment]
The MUTSIG and GISTIC buttons are not working in query page.

@schultzn @tmazor should we consider removing the two button to simplify the page? They only show up in TCGA provisional studies, and the users would still be able to select MUTSIG or GISTIC genes in study view?

**Comment by schultzn** [comment]
I never use these buttons - I guess we can see what happens if we drop them?

**Comment by jjgao** [comment]
@dippindots could you help with this? Please hide the two button for now. We can clean up the code later if no one complains about them.

![image](https://user-images.githubusercontent.com/840895/53259268-ac002700-369c-11e9-857e-992ce8c801c0.png)

**Comment by dippindots** [comment]
@jjgao Sure, I will do this today.
