### ISSUE TITLE
session service requirement

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5771]
We are using the session service for saving and loading:

1. virtual studies
2. custom groups
3. query sessions
4. comparison sessions

For # 1 & 2, we always want to use session service, virtual studies or custom groups features will only be supported when there is a session service. We also require that the user is logged in for # 2.

For # 3 & 4, when session service is available, we save the query and comparison sessions to session service. Otherwise, we will support query and comparison but they'll not be saved.

ps. there is a discussion about making sessions service mandatory: #5773

**Comment by adamabeshouse** [comment]
Further specs discussed in Slack with @jjgao and @kalletlak:

(1) samples/patients in a group are defined by the `studies` attribute of the `VirtualStudyData` object. `filters` are there for other purposes, but the contents of the group are actually defined by `studies`.

(2) We store groups in a comparison session by value, not by reference. So if you open a comparison session, C, for 3 groups, then update those groups, or the studies change, C will remain unchanged - it has copies of the groups at that time.
