### ISSUE TITLE
Minor typo on File-Formats.md

### ISSUE THREAD

**Issue by MrsLaviniaG** [cBioPortal/cbioportal#5772]
Hi,

I believe the sentence: 

_As of March 2016, the clinical file is split into a patient file and a clinical file. The sample file is required, whereas the patient file is optional._ 

should actually be:

_As of March 2016, the clinical file is split into a patient file and a **sample** file. The sample file is required, whereas the patient file is optional._ 

thanks.
(just trying to make things crystal clear for a newbie).

**Comment by jjgao** [comment]
@MrsLaviniaG thank you. We'll fix it soon.
