### ISSUE TITLE
Making session service mandatory

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5773]
Currently, cBioPortal can be installed w/o session service. As session service is becoming an integral part of the cBioPortal (see #5771), we should consider making it mandatory.

- [x] 1. Documentation on how to set up session service
- [ ] 2. Exception handling
  - What should we do when session service is (temporary) unavailable? 
  - One simple option would be disabling all related features #5771
- [ ] ~~3. Should we consider integrating session service as part of the cBioPortal API?~~
- [ ] ~~4. Should we provide a public session service for others to use?~~

cc'ing @cBioPortal/product @pieterlukasse @Sjoerd-van-Hagen @kalletlak @priti88 @inodb @alisman @n1zea144 @sheridancbio

**Comment by pieterlukasse** [comment]
Maybe it makes sense to have it as part of cbioportal core. It is probably simple and small enough to integrate it there. This would mean we will not need to complicate the cBioPortal installation. What do you think @jjgao? Or is there a good reason for keeping this as a separate service?

**Comment by jjgao** [comment]
@pieterlukasse I think that may be a good idea. We can still keep the data in the mongo database (to avoid a full refactoring), and integrate the Java code or even just include the session service as a library and expose it in the web API.

@n1zea144 @mandawilson @inodb @kalletlak thoughts?

**Comment by jjgao** [comment]
I have add this to the comparison feature epic. Let's do # 1&2 for this round.

@inodb I am wondering if you can help with # 1. Or maybe there is a better person?

@kalletlak and @adamabeshouse could you take care of # 2.

We can consider # 3&4 later.

**Comment by inodb** [comment]
@jjgao 	I can help with that - would be nice if whoever integrates the session-service can provide at least some basic documentation on how to use it. I can help test and improve it. Maybe help with providing a docker solution. 

It might also be nice if there's a way to run session service with in memory mongo db for development.

**Comment by jjgao** [comment]
> whoever integrates the session-service can provide at least some basic documentation on how to use it

@kalletlak maybe you can work with @inodb on this?

I also talked to @n1zea144. We agreed that we should not work on its integration with cBioPortal code base for this round.

**Comment by kalletlak** [comment]
@jjgao sure.

@inodb session-service is well documented at https://github.com/cBioPortal/session-service/blob/master/README.md, we can start with that.

**Comment by adamabeshouse** [comment]
this is done for cohort comparison, we just show an error message if the request to the session service fails

**Comment by fedde-s** [comment]
Unless I misunderstand, the session service has been made mandatory a long time ago. The deployment documentation includes the instruction to deploy it, both [with](https://github.com/cBioPortal/cbioportal/blob/v3.2.8/docs/docker/README.md#step-5---run-session-service-containers) and [without](https://github.com/cBioPortal/cbioportal/blob/v3.2.8/docs/Deploying.md#run-cbioportal-session-service) Docker.
