### ISSUE TITLE
handling missing cases in custom groups

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5777]
Sometimes, samples or even a study get removed or renamed. In case that samples in a custom group are missing, we should handle that when load it to the page. Option is to display a warning icon in the custom groups pannel after the group with mouse-over message such as "The following samples cannot be found in our database. They might be removed or updated since this group was created." with a list of sample IDs.

**Comment by adamabeshouse** [comment]
should we still include those samples in the count that we display next to the group name?

**Comment by jjgao** [comment]
I think we should not include them in the count.

**Comment by adamabeshouse** [comment]
that makes sense to me
