### ISSUE TITLE
Handling missing samples in comparison sessions

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5778]
Sometimes, samples or even a study get removed or renamed. In case that samples used in a comparison are missing, we should handle that when loading the session. 

We can display a message on the page: "xx samples cannot be found in our database. They might be removed or updated since this group was created." The user should be able to expand the message and see the list of samples and their groups.

**Comment by adamabeshouse** [comment]
should we include those samples in the count that we show next to the group name?

**Comment by jjgao** [comment]
@adamabeshouse I think so.

**Comment by adamabeshouse** [comment]
that makes sense to me
