### ISSUE TITLE
PDF download broken on public portal

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5785]
`SVGtoPDFConverter is throwing exception - root cause is that libpng16.so.16 cannot be found.`

We prolly need to change the docker image to contain this library

**Comment by jjgao** [comment]
we are thinking of replacing the pdf button with a print button. https://github.com/cBioPortal/cbioportal/issues/5738

**Comment by inodb** [comment]
moved PDF download to frontend
