### ISSUE TITLE
biogenequery throwing exceptions on public portal

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5786]
```
SEVERE: Servlet.service() for servlet [bioGeneQuery] in context with path [] threw exception
```

Spring security thinks its a denormalized URL. No errors on msk-tomcat so potentially related to requests coming from AWS

as reported by @n1zea144

**Comment by jjgao** [comment]
What's our solution here? Disable biogene in portal?

**Comment by jjgao** [comment]
@n1zea144 or is it possible to make biogene api work for outside traffic?

**Comment by jjgao** [comment]
closing this since we will retire network tab: https://github.com/cBioPortal/cbioportal/issues/6610
