### ISSUE TITLE
Example queries not loading in search box on public portal

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#5788]
This is because when a property is present in portal.properties but assigned to empty string, we get "" instead of null.   We could fix this by automatically resolving empty string to null, but this seems dangerous to change behavior that way. 

Question is what should default be for other portals?

**Comment by alisman** [comment]
I propose to actually configure our examples properly and just not show any examples when there is either null or empty value.   This should be ok b/c the portal.properties_EXAMPLE file has an example configured.  So if it's empty, it's likely a deployer meant to kill this entirely
@inodb @jjgao what do you think of this logic?

**Comment by jjgao** [comment]
@alisman I think that sounds fine.

**Comment by alisman** [comment]
@jjgao sorry i let this go.  my feeling is that we would have to go back to
