### ISSUE TITLE
Specimen in timeline invisible

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#579]
We are experimenting with timeline data. We've imported this Specimen timeline datafile:

    PATIENT_ID	START_DATE	STOP_DATE	EVENT_TYPE	SPECIMEN_REFERENCE_NUMBER	SPECIMEN_SITE	SPECIMEN_TYPE	SOURCE
    XM-3P1C	0	0	SPECIMEN	XM-3P1C20201	lever	FFPE	NKI

However it doesn't show up on the timeline. When looking around, it actually has an svg node but it is a rectangle instead of a circle and its X coordinate is applied twice so it is cropped. I've included a screenshot of it being invisible (not very helpful I know) and the svg node inside a g transform

![specimen](https://cloud.githubusercontent.com/assets/5654699/11719853/e6fc51b0-9f5c-11e5-8898-e3638a457a7a.png)

**Comment by inodb** [comment]
I believe you should leave out the STOP_DATE for that point (remove the `0`) in the data. Circles are drawn for data points that only have a START_DATE but no STOP_DATE.

**Comment by j-hudecek** [comment]
Thanks that solved it
