### ISSUE TITLE
sample page doesn't have clinical data tab

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5790]
Patient view has a clinical data tab for patients, but not for samples.

This is confusing, in particular because most links from results view go directly to the sample page rather than the patient page -- so when a user clicks on a sample ID in results view, the page that loads doesn't have a clinical data tab.

I can't remember if we used to have this and so this is a bug report, or if this is a feature request, but can we show the clinical data tab in sample view?

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/cbioportal/issues/3280. Will prioritize.
