### ISSUE TITLE
Plotting clinical attribute vs rna expression doesn't work anymore

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5793]
As reported by:

https://groups.google.com/forum/#!topic/cbioportal/4GtlgN0eKI0

See e.g.:

https://www.cbioportal.org/results/plots?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=ov_tcga&case_set_id=ov_tcga_cnaseq&clinicallist=CLINICAL_STAGE&data_priority=0&gene_list=STAT3&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=ov_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ov_tcga_mutations&show_samples=false&tab_index=tab_visualize

Not sure if this is a bug or a data issue

**Comment by adamabeshouse** [comment]
this is a user misunderstanding, there is no issue here. They just chose a different clinical attribute in plots which doesnt actually have data.

**Comment by inodb** [comment]
I see, thanks @adamabeshouse ! This is more clearly indicated in the oncoprint. Maybe we should have a similar thing for the plots tab? Indicating what percentage of the cases has that clinical attribute and don't allow it to be selected?

**Comment by adamabeshouse** [comment]
we used to have that but we took it out, I can't honestly remember why though. It does seem like something we should do. @jjgao ?
