### ISSUE TITLE
Handle the case in study view when session service is not available

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5798]
We have some ongoing discussions(#5771 ) about making session mandatory. But before having that, we need to make sure the study view works properly when session is not available.

@jjgao  should we disable all features related to session service in study view in this scenario?

**Comment by jjgao** [comment]
@zhx828 I think it's a good idea to disable if not available. What are the features?

**Comment by zhx828** [comment]
@jjgao just the session service at the moment. Do you want to remove the button, or just disable it?

**Comment by jjgao** [comment]
just disable it.

**Comment by jjgao** [comment]
session service is required now.
