### ISSUE TITLE
Integrating the Comparison component into Results page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5802]
Once the Comparison component is finished, we should replace the current `Enrichments` tab with the Comparison tab. `Survival` tab can be merged to `Comparison` or stay as is.

**Comment by adamabeshouse** [comment]
@jjgao just confirming we still want to do it like this?

**Comment by jjgao** [comment]
I think so. I think the Overlapping and Clinical tabs are useful in the results page as well. Also, it's a good idea to use only one concept.

I am not sure about whether Survival should be merged to the Comparison tab though.

Adding @cBioPortal/product

**Comment by adamabeshouse** [comment]
how would overlapping work, with just altered/unaltered?

**Comment by jjgao** [comment]
@adamabeshouse there may be overlapping patients.
