### ISSUE TITLE
Comparison tab in Results: allow group samples by gene/track

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5804]
By default, we group the samples by altered and unaltered. We can also group the samples by altered in each track. Then we will have multiple groups.

This will enable us to do one very useful use case to study co-mutations: Comparing "Gene A & Gene B", "Gene A only", and "Gene B only". #5803 will be required for this use case too.

- [ ] fixing e2e tests

**Comment by adamabeshouse** [comment]
I love this idea.. whats the UI you envision for this?

**Comment by jjgao** [comment]
@adamabeshouse Here is a quick design - needs to be refined.

It could be a dropdown `Group by` with three options:
A.`Alterations in any genes`
B. `Alterations per gene`
C. `Alterations per OncoPrint gene track` 

- The dropdown should only be shown when there are multiple genes or tracks.
- A should be the default.
- B should only be listed when there are multiple genes
- C should only be listed when there are multiple tracks and at least one gene duplicated in two or more tracks.

The group names will change based on the selection.

**Comment by jjgao** [comment]
This one is about enrichments and survival. Adding Comparison to Results page is another one: https://github.com/cBioPortal/cbioportal/issues/5802

@adamabeshouse I am not sure which one we should do first. Thoughts?

**Comment by adamabeshouse** [comment]
@jjgao just for enrichments and survival is a lot easier. If we just want that feature and the whole comaparison is not a priority, then we should just do that. what do you think?

**Comment by adamabeshouse** [comment]
@jjgao also where do we put this dropdown? in global settings?

**Comment by jjgao** [comment]
> I think we should start with enrichments and survival as a first step, since we're going to be using the same groups for the comparison tab, right?

that's right.

> one question I have for the comparison tab is is do we still want to allow creating new groups in the overlap subtab? i think what we should do with that is if they do that, then we open a full comparison session in a new browser tab.

I think allowing open a full comparison session is a good idea!

> also where do we put this dropdown? in global settings?

I think the dropdown should be within the tab. The Enrichments and Survival tabs can use the same state for the drop downs?

**Comment by adamabeshouse** [comment]
@jjgao getting started on this now. 
a couple of questions:

1) you mention in the original post that we need to be able to treat the overlapping group as a separate group. is that still true? if so, whats the UI for that? are we bringing back the "create group from overlap" functionality? or a different, similar results-view specific functionality?

2) how do these group definitions interact with not-profiled?

**Comment by adamabeshouse** [comment]
@jjgao revised the feature to omit the groups by gene, so now it's just altered vs unaltered and altered by oncoprint track.

Also, we're adding the ability to add a created group to the study view, the same way as in group comparison

**Comment by adamabeshouse** [comment]
after discussion with @jjgao we're going to collapse all groups after the first 5

**Comment by adamabeshouse** [comment]
after further discussion with @alisman we changed the collapse threshold to 40 - the screen can definitely comfortable accomodate it
