### ISSUE TITLE
Quick Search: move title text to the left

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5811]
Another suggestion by Niki: move the text to the left, on a wide screen the text is kinda far to the right.
![pastedgraphic-8](https://user-images.githubusercontent.com/1334004/53758454-c5b72080-3e8b-11e9-8043-5908f015ecf8.png)

**Comment by alisman** [comment]
@ino @niki 
I think we should leave the text where it is.  When it's left aligned, it's too bunched up and difficult to tell that it applies to what's below.   @niki if you feel strongly about it, i can change it.

**Comment by jjgao** [comment]
@alisman : could you paste a mock-up when it's left aligned?

**Comment by dippindots** [comment]
![image](https://user-images.githubusercontent.com/15748980/54940855-f413a300-4f01-11e9-9ba6-0edc56ef1e57.png)

@jjgao This is the screenshot when it's left aligned. You can also test it out at https://cbioportal-frontend-pr-2126.herokuapp.com/.

**Comment by jjgao** [comment]
hmm... I agree with @alisman -- it looks cluttered. Maybe we could make a section more like a section? e.g. different background?

**Comment by alisman** [comment]
@jjgao the problem with a different background is, different sections need dedicated background colors. otherwise they need to be alternating, and would be unstable (depending on result set).  we could try adding more padding or putting the label below the dotted line.  i can mock this up later today.

**Comment by jjgao** [comment]
@alisman another idea: instead of displaying a header line, should just just display the message in the line with gene (or study, or sample) when hovered over?
