### ISSUE TITLE
settings.xml sample file from "pre-build-steps" page of docs does not render correctly on doc site

### ISSUE THREAD

**Issue by brettvanderwerff** [cBioPortal/cbioportal#5812]
Just a heads up that the part where it says "A sample file is shown below:" on the following doc page: 

https://docs.cbioportal.org/2.1-deployment/pre-build-steps

has markdown that does not render correctly. It renders correctly on github:

https://github.com/cBioPortal/cbioportal/blob/master/docs/Pre-Build-Steps.md

but not the docsite at: 

https://docs.cbioportal.org/2.1-deployment/pre-build-steps

I tested this on chrome and firefox with the same bad rendering on both browsers

**Comment by jjgao** [comment]
@brettvanderwerff thanks. We'll fix it soon.
