### ISSUE TITLE
"Custom selection" button in Study View only allows to select one Study ID / Patient ID

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#5813]
Currently (version 2.1.0), the "Custom Selection" button in the study view only allows to filter by one study ID or one patient ID, but not for multiple. If you try to add multiple IDs separated by spaces, validation of the IDs fail:
![study_view_bug](https://user-images.githubusercontent.com/20278013/53721527-b9b76880-3e63-11e9-9f09-02f0411bfc5c.png)

**Comment by zhx828** [comment]
@oplantalech we no longer supports space as separator because of the custom groups feature. Please list multiple cases in separate lines.

**Comment by jjgao** [comment]
hopefully it'll be more clear once we restore the example. https://github.com/cBioPortal/cbioportal/issues/5769
