### ISSUE TITLE
Update how study view sort the clinical attribute 

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5815]
The current way of study view calculates which chart should be prioritized is the following

1. Check the priority from data
2. Use a regular expression to match clinical attribute as preselected when the priority is the same
3. Check which data group the clinical attribute belongs to (patient/sample) and use the threshold `clinicalChartsPerGroup` to cap them. 
4. by name

- [x] We are proposing to remove the step 2, 3. We will give default priorities for the clinical attributes meet the Regex match.
- [ ] Update study view README

**Comment by zhx828** [comment]
The `chartMetaComparator ` needs to be updated.

**Comment by zhx828** [comment]
@jjgao after review the Regex in study view,  the following default priorities will be added on top of the current list which you can find here https://github.com/cBioPortal/cbioportal/blob/master/docs/Study-View.md
The original Regex `/(os_survival)|(dfs_survival)|(mut_cnt_vs_cna)|(mutated_genes)|(cna_details)|(^age)|(gender)|(sex)|(os_status)|(os_months)|(dfs_status)|(dfs_months)|(race)|(ethnicity)|(sample_type)|(histology)|(tumor_type)|(subtype)|(tumor_site)|(mutation_count)|(copy_number_alterations)|(.*(site|grade|stage).*)/i`

"PATIENT_RACE": 8,
"PATIENT_ETHNICITY": 8,
"SAMPLE_SAMPLE_TYPE": 8,
"PATIENT_HISTOLOGY": 8,
"SAMPLE_TUMOR_TYPE": 8,
"PATIENT_SUBTYPE": 8,
"PATIENT_TUMOR_SITE": 8

I will not include any blur match, such as `(.*(site|grade|stage).*)` for a more stable sorting result.

As you may realize, the clinical attributes are currently separated in to PATIENT/SAMPLE groups. These default priorities are set particularly for one group only. I realize this may not be the prefer way since the sample clinical attribute can be assigned to patient or sample in different studies. Should I make the adjustment removing the group restriction?

**Comment by jjgao** [comment]
Thanks, @zhx828. I think it's ok to remove the group restriction.
