### ISSUE TITLE
Allow user defines bar chart bins

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5819]

**Comment by jjgao** [comment]
@zhx828 would you have time to work on this soon?

**Comment by jjgao** [comment]
It would be good to do some mockup or brainstorm first.

**Comment by zhx828** [comment]
@jjgao just had a discussion with Onur. It may turn out to be easier than we thought. I will prioritize the ticket.

**Comment by zhx828** [comment]
@jjgao  When a user particularly wants to modify the range of the filter, we think it makes sense just group all samples into three groups(numbers), one for defined ranges, one for any samples before the start of the range, one for the rest. 
For instance, if user selects 10-20, the following bar chart will be rendered
![Screen Shot 2019-06-25 at 10 52 17 AM](https://user-images.githubusercontent.com/5400599/60108915-6c734580-9737-11e9-8f25-14e129655a6a.png)

**Comment by zhx828** [comment]
And we also want to support multiple selections?

**Comment by jjgao** [comment]
> @jjgao When a user particularly wants to modify the range of the filter, we think it makes sense just group all samples into three groups(numbers), one for defined ranges, one for any samples before the start of the range, one for the rest.

@zhx828 I think your proposed solution is fine. We should also be able to support one side selection and in that case, there are going to be two groups?

> And we also want to support multiple selections?
Not sure if I understand. I don't think we need to support selection of unconnected data (a.g. age<18 or 30<age<40) if that's what you are asking.

**Comment by zhx828** [comment]
@jjgao I have the Custom Bins running here, could you take a look? Any feedback would be appreciated. Thanks! https://cbioportal-frontend-pr-2518.herokuapp.com/study/summary?id=acc_tcga_pan_can_atlas_2018

**Comment by jjgao** [comment]
- I don't think the settings icon is intuitive. We need a binning icon. The tooltip should also change to "Custom bins"
- make the window bigger
- after change the bins, the whole page refresh. is it possible to only refresh the barchart in question?

**Comment by zhx828** [comment]
@jjgao 
> I don't think the settings icon is intuitive. We need a binning icon. The tooltip should also change to "Custom bins"

I was hoping to introduce the setting icon for later usage including changing the bar filter. But maybe a bit over kill for this pr?

> after change the bins, the whole page refresh. is it possible to only refresh the barchart in question?

This is an overall issue of the study view, similar to the [log issue](https://github.com/cBioPortal/cbioportal/issues/5468). Should we solve the log issue before releasing the feature?

**Comment by jjgao** [comment]
@zhx828 for the icon, it's confusing to have both setting and hamburger icons. Maybe we can add "Customize bins" under the hamburger icon? I don't expect this function to be frequently used so it's perfect to hide it by default. And maybe we don't need an icon in that case? Also related to discussion here: https://github.com/cBioPortal/cbioportal/issues/6356

For the refreshing issue, let's solve it in a separate PR later.

**Comment by zhx828** [comment]
@jjgao could you take another look of this mockup? If it looks good, I will send it to do code review. Thanks. https://cbioportal-frontend-pr-2518.herokuapp.com/study/summary?id=acc_tcga_pan_can_atlas_2018

**Comment by jjgao** [comment]
@zhx828 looks great! Thanks.

**Comment by jjgao** [comment]
@zhx828 https://github.com/cBioPortal/cbioportal/issues/5468 has been fixed.
