### ISSUE TITLE
remove the limit of 50 studies for study view?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5830]
Maybe we can remove the limit on this now? We need to do some performance evaluation first.

![image](https://user-images.githubusercontent.com/840895/53815217-3ebb8400-3f2f-11e9-9481-963ce9d165ff.png)

**Comment by alisman** [comment]
@jjgao @inodb @n1zea144, I did a test of study view with 150 studies on master.cbioportal.org.  This instance uses the production db.  It looks very much like it crashed the database and brought down the entire portal for a minute or so.   So I don't think we should remove this limit with further investigation by backend team.

**Comment by jjgao** [comment]
@alisman Thanks. Let's hold off then.

**Comment by alisman** [comment]
@zhx828 @kalletlak want to get you input on whether this is practical.

**Comment by zhx828** [comment]
@alisman with the recent added Ehcache, it would definitely help to increase the limit. In terms of completely removing the limit, I'm skeptical on that. We should do more testing and monitor the memory/cpu usage. There is no easy way to select all studies now, but they can still do it if they manage to use the url. So on the safe said, a limit should still in place especially considering the MSK portal has more than 1000 studies.

**Comment by kalletlak** [comment]
May be Limit the number of attributes that should be visible by default and can be added until api performance is improved.
