### ISSUE TITLE
war file does not deploy

### ISSUE THREAD

**Issue by bprentice77** [cBioPortal/cbioportal#5838]
I am unable to deploy the cbioportal.war on tomcat. I've followed the instructions at https://docs.cbioportal.org/2.1-deployment/

Server version:        Apache Tomcat/8.5.37
Server built:          Dec 12 2018 12:07:02 UTC
Server number:         8.5.37.0
OS Name:               Linux
OS Version:            4.15.0-45-generic
Architecture:          amd64
Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
JVM Version:           1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12
JVM Vendor:            Oracle Corporation
CATALINA_BASE:         /usr/share/tomcat
CATALINA_HOME:         /usr/share/tomcat

``` org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'genePanelMapperLegacy' defined in class path resource [applicationContext-business.xml]: Cannot resolve reference to bean 'sqlSessionFactory' while setting bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [applicationContext-business.xml]: Cannot resolve reference to bean 'businessDataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'businessDataSource' defined in class path resource [applicationContext-business.xml]: Invocation of init method failed; nested exception is javax.naming.NamingException: Cannot create resource instance```

**Comment by bprentice77** [comment]
I should also note, the cBioPortal version is 2.1.0, and the "Set up Database Connection Pool" heading under the "Deploying the Web Application" section does looks incomplete...

https://docs.cbioportal.org/2.1-deployment/deploying

**Comment by kalletlak** [comment]
@bprentice77 I think its unable to find the resource. Somehow it's not properly formatted in https://docs.cbioportal.org/2.1-deployment/deploying. Please check https://github.com/cBioPortal/cbioportal/blob/master/docs/Deploying.md#set-up-the-database-connection-pool

try updating context.xml appropriately and restart tomcat.

**Comment by bprentice77** [comment]
@kalletlak I actually already had my context.xml set up exactly how the guide you are referencing specifies. I've double checked permissions and ownership, but I cannot determine why it cannot resolve the reference to 'sqlSessionFactory'. Everything seems to be defined in the context files.

**Comment by khzhu** [comment]
@bprentice77 , 
which authentication method did you use? I got the same errors when I had a JVM option 
**-Dauthenticate=saml** 
in my setenv file. And, worked just fine when I turned authentication off by setting
**-Dauthenticate=false.** 
I was trying to deploy a copy of cbioportal 2.1.0 war to a centos7 VM.

**Comment by bprentice77** [comment]
@khzhu I am using the JVM option "-Dauthenticate=false". Attached is my cbioportal.log.
[cbioportal.log](https://github.com/cBioPortal/cbioportal/files/2938563/cbioportal.log)

**Comment by khzhu** [comment]
I spot this error.
> 2019-03-06 22:16:55 [localhost-startStop-1] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'dbconnector:jndi' in any property source
which version mysql were you using?

**Comment by bprentice77** [comment]
5.7.25-0ubuntu0.18.04.2

**Comment by pieterlukasse** [comment]
hi @bprentice77, I know this is not a direct answer to your issue, but perhaps you can compare the steps you have been following with the steps found in the `Dockerfile` here https://github.com/thehyve/cbioportal-docker/tree/cbiov2.0.1 (this is a slightly older version as well, 2.0.1 - not sure if your issue is 2.1 specific)?

**Comment by bprentice77** [comment]
Hey @pieterlukasse, thank you for that suggestion. I reviewed the Dockerfile, and noticed on line 48, there is a CATALINA_OPTS flag for "-Ddbconnector=dbcp". I added that to my sentenv.sh and now the webapp deploys succesfully! Thank you everyone for your suggestions!

**Comment by jjgao** [comment]
@bprentice77 great you figured it out.

@pieterlukasse @khzhu @kalletlak thanks for the help. Is there anything we should do in our code base? cc'ing @n1zea144

**Comment by kalletlak** [comment]
`-Ddbconnector=dbcp` is not mandatory. If it's not specified, it should fallback to default value `jndi`. Not sure why it's throwing an error.
