### ISSUE TITLE
virtual study of 1 sample doesn't load charts

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5845]
If I create a virtual study with just one sample, then when study view loads none of the clinical attributes appear, even though there is data for them.

![image](https://user-images.githubusercontent.com/10508276/54040848-4fb8ff00-4194-11e9-8dde-cc4b2963cad6.png)

Examples:
https://www.cbioportal.org/study?id=5c829300e4b046111fee1dd8
https://www.cbioportal.org/study?id=5c829616e4b046111fee1ddd

**Comment by jjgao** [comment]
@tmazor this is a good one -- it's b/c we only show charts with more than 1 pies. But in this one, we should remove that rule.

**Comment by zhx828** [comment]
@tmazor @jjgao this is now fixed in production.
