### ISSUE TITLE
study view - decimal bins for integer values

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5846]
When the maximum value of the data in a histogram is low, then bins are created with decimal limits, which looks silly for a variable that only has integer values -- e.g. mutation count:
![image](https://user-images.githubusercontent.com/10508276/54040895-6cedcd80-4194-11e9-868d-b93fb0b0671d.png)
https://www.cbioportal.org/study?id=5c829380e4b046111fee1dda

Can histograms only use integer bins when all the underlying data is integers?

**Comment by zhx828** [comment]
@onursumer this is a backend issue. Do you think this one is easy to fix?

**Comment by onursumer** [comment]
I think we have the same problem with the year data as well. Not sure how much effort it would take to fix this though.

**Comment by tmazor** [comment]
looks like this is fixed
