### ISSUE TITLE
Error during building from source stage.

### ISSUE THREAD

**Issue by lokeshrana9999** [cBioPortal/cbioportal#5847]
[WARNING] 
[INFO] Scanning for projects...
Downloading from jitpack.io: https://jitpack.io/com/github/cbioportal/maven-external-version/maven-external-version-plugin/f09c2b9608744881111f24e55d55a91e54e6cb5f/maven-external-version-plugin-f09c2b9608744881111f24e55d55a91e54e6cb5f.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/github/cbioportal/maven-external-version/maven-external-version-plugin/f09c2b9608744881111f24e55d55a91e54e6cb5f/maven-external-version-plugin-f09c2b9608744881111f24e55d55a91e54e6cb5f.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.github.cbioportal.maven-external-version:maven-external-version-plugin:f09c2b9608744881111f24e55d55a91e54e6cb5f or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.github.cbioportal.maven-external-version:maven-external-version-plugin:jar:f09c2b9608744881111f24e55d55a91e54e6cb5f @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.mskcc.cbio:master:0-unknown-version-SNAPSHOT (/home/loki/Documents/cbioportal/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin com.github.cbioportal.maven-external-version:maven-external-version-plugin:f09c2b9608744881111f24e55d55a91e54e6cb5f or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.github.cbioportal.maven-external-version:maven-external-version-plugin:jar:f09c2b9608744881111f24e55d55a91e54e6cb5f: Could not transfer artifact com.github.cbioportal.maven-external-version:maven-external-version-plugin:pom:f09c2b9608744881111f24e55d55a91e54e6cb5f from/to jitpack.io (https://jitpack.io): Network is unreachable (connect failed) -> [Help 2]

**Comment by inodb** [comment]
@lokeshrana9999 this seems like some network error where the dependencies aren't being downloaded from jitpack. Maybe there was some network outage, could you try again?

**Comment by lokeshrana9999** [comment]
> @lokeshrana9999 this seems like some network error where the dependencies aren't being downloaded from jitpack. Maybe there was some network outage, could you try again?

Thank you @inodb, it was an issue of version compatibility bw java and maven. I just ran a successful install.

**Comment by inodb** [comment]
Glad to hear you solved the issue
