### ISSUE TITLE
Are we really doing log2 in mRNA Enrichments?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5848]
[A user](https://groups.google.com/d/msg/cbioportal/DHTND1Hcbu8/cuC16p8MCgAJ) reported this.

Initially I thought it was because the original values were logged that we only substract the two mean values, but it looks like even for RNAseq v2 non-log2 values, we just do a substractio, e.g. http://bit.ly/2NQWc2F

![image](https://user-images.githubusercontent.com/840895/54059359-d8509300-41c6-11e9-8708-a4118a2f49ce.png)

**Comment by adamabeshouse** [comment]
yeah, thats exactly what's happening. is there a way to detect whether the dataset is already in log form?

**Comment by jjgao** [comment]
@ersinciftci will look into this on Monday.

**Comment by jjgao** [comment]
We should probably define them (whether log or not) properly in the profile meta data. I remember I had an issue created for that but couldn't locate it.

**Comment by ersinciftci** [comment]
@jjgao This is what backend is doing:

```
private double[] getAlterationValues(List<GeneMolecularData> molecularDataList, String molecularProfileId) {
        
    if (molecularProfileId.contains(RNA_SEQ)) {
        return molecularDataList.stream().mapToDouble(g -> Math.log(Double.parseDouble(g.getValue())) / LOG2)
            .toArray();
    } else {
        return molecularDataList.stream().mapToDouble(g -> Double.parseDouble(g.getValue())).toArray();
    }
}
```

So backend always returns values in log2, and frontend just does a subtraction because it's already logged. This was done as part of #1 bullet point in this comment https://github.com/cBioPortal/cbioportal/issues/4374#issuecomment-398541038

**Comment by ersinciftci** [comment]
So answer to `but it looks like even for RNAseq v2 non-log2 values, we just do a subtraction` is: Backend converts those RNAseq v2 non-log2 values to log2 values, that's why it's still just a subtraction.

**Comment by adamabeshouse** [comment]
@jjgao @ersinciftci would people expect non-logged values when they're querying a non-log profile?

**Comment by ersinciftci** [comment]
I think the problem is that we were not sure about log2 vs log10 at that time (then decided to do log2), so #4 in https://github.com/cBioPortal/cbioportal/issues/4374#issuecomment-398541038 got somehow ignored. It was about making clear if the data is already log2ed or if we transformed it to log2.

**Comment by adamabeshouse** [comment]
yeah, im lost..

**Comment by ersinciftci** [comment]
So my take on this issue is; it works correctly, we just need to make it more clear to the user.

**Comment by adamabeshouse** [comment]
ah, okay

**Comment by jjgao** [comment]
I think the mouse over message should indicate they are already logged.

**Comment by adamabeshouse** [comment]
Wait so is \mu the log of the average, or the average of the log values?

**Comment by jjgao** [comment]
It should be average of log (logged values are more normal-like). @ersinciftci correct me if I am wrong.

**Comment by ersinciftci** [comment]
@adamabeshouse @jjgao The first paragraph of the same comment also explains this https://github.com/cBioPortal/cbioportal/issues/4374#issuecomment-398541038

**Comment by ersinciftci** [comment]
So both mean and standard deviation is applied after the log (so in the same order with @jjgao 's suggestion).

**Comment by adamabeshouse** [comment]
So then I find the phrase "Log ratio" very confusing, isn't it? Since the word log doesnt appear in description of mean or stddev. It's unclear to me what's happening, by looking at the table.

**Comment by jjgao** [comment]
I think we use log ratio just to indicate it's `log(X/Y)` or `log(X)-log(Y)`, but maybe it's inappropriate?
