### ISSUE TITLE
Performance issues in OncoprintSVGRenderer.prototype.clipAndPositionCells ?

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#585]
The method OncoprintSVGRenderer.prototype.clipAndPositionCells is one of the bottlenecks in rendering and is called multiple times during rendering: once during addTrack and once during setTrackData. Maybe this can be combined in 1 call? 

Furthermore, the number of iterations in this function seems to grow *exponentially* with the number of tracks. See screenshot below for an example of how many iterations are found in both inner loops of this function vs number of genes in the query: 

![image](https://cloud.githubusercontent.com/assets/2900303/11780641/a50036f0-a263-11e5-9bd9-786c7f2a4f29.png)

**Comment by adamabeshouse** [comment]
Sidenote: I think the growth is probably actually quadratic but either way you're right

**Comment by adamabeshouse** [comment]
Sidenote: I think the growth is actually probably quadratic? But either way you're right, this needs to be improved.

**Comment by pieterlukasse** [comment]
Yes. I think your remark and conclusion are both correct; )

**Comment by adamabeshouse** [comment]
Issue fixed in new oncoprint.
