### ISSUE TITLE
study view mutations/CNA tables should include denominator

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5851]
I vaguely remember seeing this conversation once before but can't find an issue about it so I'm making a new one...

The mutations & CNA frequency tables in study view can look very confusing in a study like GENIE that has many different gene panels -- genes that are frequently mutated but are only sequenced in a few samples show up with frequencies that look completely wrong given the number of alterations (see ZFHX4 and MUC16 below)

We could make this much clearer by including the denominator used to calculate each frequency. So let's add that.

![image](https://user-images.githubusercontent.com/10508276/54135448-314f3f80-43f0-11e9-9a15-60e95eb94aa8.png)

**Comment by zhx828** [comment]
@tmazor I agree this is very confusion. Where should we include that information? When mouse over the frequency? Should we also mention which panel these samples from?

**Comment by tmazor** [comment]
@zhx828 I think a tooltip that includes the denominator & gene panel name would be great. Can that same information also be included as additional columns when someone downloads the table?

**Comment by zhx828** [comment]
@tmazor sure thing.
