### ISSUE TITLE
redirects not working for tools page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5852]
- [ ] http://www.cbioportal.org/tools.jsp
- [ ] http://www.cbioportal.org/visualize_your_data.jsp

As reported by Rounak, a potential GSoC student:

A quick Google search of `cbioportal lollipop plot` gives the first two links as http://www.cbioportal.org/tools.jsp and http://www.cbioportal.org/visualize_your_data.jsp but neither of the pages exists.

**Comment by abhinavsagar** [comment]
Is anybody working on it?
If not I am taking on it.
Please inform me if you are working for the same.

**Comment by inodb** [comment]
@abhinavsagar nobody's working on it atm. Would be great if you could fix it. The fix is probably similar as the one in this PR: https://github.com/cBioPortal/cbioportal-frontend/pull/1931/files

**Comment by jjgao** [comment]
I am closing this. These links seem no long exist in google search.
