### ISSUE TITLE
Summary view filtering bug

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#5853]
Grouping of samples in the pie chart is not case sensitive, but if we apply filter then the code does exact string match.
Example: Local Recurrence = 11 samples, If I apply the filter only 10 samples get selected because one of the sample had a typo: 'Local recurrence' (R is in lower case).

**Comment by zhx828** [comment]
@jjgao this is the issue Adam and I saw last week. Basically this is a mysql group by issue. Since the pie chart gets the category from data directly. Should we make the frontend case insensitive?

**Comment by jjgao** [comment]
Yes, please make frontend case insensitive.

**Comment by zhx828** [comment]
@onursumer this is related to backend as well. Probably I should start to take a look?

**Comment by khzhu** [comment]
@zhx828 , which study in public portal should I use to reproduce the error? Thanks!

**Comment by khzhu** [comment]
Hi @priti88 , I am looking at the issue. Could you please let me know how to reproduce the issue? For instance, which study you were looking at, the type of chart used for grouping/filtering samples? Thanks!

**Comment by zhx828** [comment]
@khzhu I'm trying to reproduce the issue. But seems the all public studies with `Local Recurrence` all have been fixed. But one thing you can do is making the study view filtering insensitive. For instance, http://www.cbioportal.org/study?id=lgg_tcga&filterAttributeId=ONCOTREE_CODE&filterValues=OSAT works but not http://www.cbioportal.org/study?id=lgg_tcga&filterAttributeId=ONCOTREE_CODE&filterValues=osat We want to make it case insensitive.

**Comment by khzhu** [comment]
I see, thanks @zhx828 , will do some debugging.

**Comment by khzhu** [comment]
Hi @zhx828 , after some debugging, I would say it is no longer an issue. First of all, the backend queries the clinical data by clinical attributes Ids and sample Ids only. And, there isn't any filters applied to the clinical attribute values being pulled out from the database. The frontend, on the other hand, does a filter only on a user selected option from the Oncotree pie chart. 
![Screen Shot 2019-04-29 at 3 37 30 PM](https://user-images.githubusercontent.com/17375786/56922299-d5bb3d00-6a95-11e9-88d5-5a3180904e97.png)

The request URL no longer has **_filterValues_** appended to the query string which also eliminates any chances the query string to be modified.
![Screen Shot 2019-04-29 at 3 37 51 PM](https://user-images.githubusercontent.com/17375786/56922196-9c82cd00-6a95-11e9-84b4-5884698a4687.png)

**Comment by priti88** [comment]
@khzhu I don't think we can use the public data to debug this. You might have to to create some fake data and upload the study to your local instance to verify if this works.

**Comment by priti88** [comment]
I would recommend using any tcga study and changing the values for one of the clinical field. Example: make it all lower case or upper case.

**Comment by khzhu** [comment]
@priti88 , no worries, please. I was debugging using my local develop instance with the same public dataset downloaded.

**Comment by jjgao** [comment]
@khzhu any update on this?

**Comment by khzhu** [comment]
@jjgao , I do not think this is a problem any more. Repaste my comments on April 29. 

>
after some debugging, I would say this is no longer an issue. First of all, the backend queries the clinical data by clinical attributes Ids and sample Ids only. And, there isn't any filters applied to the clinical attribute values being pulled out from the database. The frontend, on the other hand, is filtering based on the user selection on the Oncotree pie chart. **_filterAttributeId_**=ONCOTREE_CODE&**_filterValues_**=OAST no longer being appended to the URL query string so that the user will not be able by any chance to alter the filterValues.

**Comment by jjgao** [comment]
@khzhu I don't think I got it.

So when we have both `Local Recurrence` and `Local recurrence`, is our API pull both samples out when we query for `Local Recurrence`, ie. case insensitive? @khzhu @zhx828

**Comment by khzhu** [comment]
@jjgao , the API will only return those **_Local Recurrence_** samples. Is that a desirable behavior? If we have both **_Local Recurrence_** and **_Local recurrence_** samples, then we would have two different sample types listed on the pie chart. So, If we want to treat "Local Recurrence" and "Local recurrence" as one sample type, then we should do the mapping before importing/loading into the database.
Could you please show me how do you enter submit your query, since I cannot see any places you can enter your search text other than either select a sample list from the dropdown box or select a pie chart.

**Comment by jjgao** [comment]
@khzhu I think one option is to make the web api case insensitive.

For example, currently this link works: https://www.cbioportal.org/study/summary?filterAttributeId=SEX&filterValues=Male&id=msk_impact_2017

but not this: https://www.cbioportal.org/study/summary?filterAttributeId=SEX&filterValues=MALE&id=msk_impact_2017

**Comment by jjgao** [comment]
Another reason we should make filter case insensitive is b/c the API for counting (pie chart) is case insensitive.

**Comment by khzhu** [comment]
@jjgao , here are sql queries for counting clinical attributes, seems are case sensitive though.
```
    <select id="getClinicalAttributeCountsBySampleIds" resultType="org.cbioportal.model.ClinicalAttributeCount">
        SELECT count(*) as count,
        clinical_sample.ATTR_ID as attrId
        FROM clinical_sample
        <include refid="joinSample"/>
        <include refid="whereSample"/>
        GROUP BY clinical_sample.ATTR_ID

        UNION

        SELECT count(*) as count,
        clinical_patient.ATTR_ID as attrId
        FROM clinical_patient
        <include refid="joinPatient"/>
        <include refid="whereSample"/>
        GROUP BY clinical_patient.ATTR_ID
    </select>

    <select id="getClinicalAttributeCountsBySampleListId" resultType="org.cbioportal.model.ClinicalAttributeCount">
        SELECT count(*) as count,
        clinical_sample.ATTR_ID as attrId
        FROM clinical_sample
        <include refid="joinSample"/>
        <include refid="whereBySampleListId"/>
        GROUP BY clinical_sample.ATTR_ID

        UNION

        SELECT count(*) as count,
        clinical_patient.ATTR_ID as attrId
        FROM clinical_patient
        <include refid="joinPatient"/>
        <include refid="whereBySampleListId"/>
        GROUP BY clinical_patient.ATTR_ID
    </select>

```

**Comment by jjgao** [comment]
@khzhu "group by" is case insensitive :)

https://stackoverflow.com/questions/10952696/how-to-do-a-case-sensitive-group-by

**Comment by khzhu** [comment]
@jjgao , but all queries are based on clinicalAttribute IDs sent from the view not text (clinical attributes)
```
<select id="getClinicalAttribute" resultType="org.cbioportal.model.ClinicalAttribute">
        SELECT
        <include refid="select">
            <property name="prefix" value=""/>
        </include>
        FROM clinical_attribute_meta
        INNER JOIN cancer_study ON clinical_attribute_meta.CANCER_STUDY_ID = cancer_study.CANCER_STUDY_ID
        WHERE clinical_attribute_meta.ATTR_ID = #{clinicalAttributeId}
        AND cancer_study.CANCER_STUDY_IDENTIFIER = #{studyId}
    </select>
```

**Comment by jjgao** [comment]
@khzhu what is the query when you click a slice on the pie?

**Comment by khzhu** [comment]
Hi @JJ, @Hongxing, finally got the bug fixed 🙂 . Can give a quick demo tomorrow at our standup.

**Comment by inodb** [comment]
There is still an issue that on the frontend that attribute values are not case insensitive. There are PRs that fixed other parts of this issue e.g. this frontend PR fixed case insensitive attribute ids: https://github.com/cBioPortal/cbioportal-frontend/pull/2716 & other related backend fixes: https://github.com/cBioPortal/cbioportal-frontend/pull/2716.

But this still needs to be fixed:

See MALE in URL

https://www.cbioportal.org/study/summary?filterAttributeId=SEX&filterValues=MALE&id=acc_tcga_pan_can_atlas_2018

![Screen Shot 2020-01-17 at 12 35 21 PM](https://user-images.githubusercontent.com/1334004/72633161-dea2b600-3925-11ea-860a-defbca5ec51e.png)


vs

Male in URL

https://www.cbioportal.org/study/summary?filterAttributeId=SEX&filterValues=Male&id=acc_tcga_pan_can_atlas_2018

![Screen Shot 2020-01-17 at 12 36 04 PM](https://user-images.githubusercontent.com/1334004/72633190-f37f4980-3925-11ea-80f3-bbe310849d14.png)
