### ISSUE TITLE
Compilation failure during MVN

### ISSUE THREAD

**Issue by sgspaddy** [cBioPortal/cbioportal#5854]
Get the following error messages when I was trying to compile the latest version. Appreciate your help

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project core: Compilation failure: Compilation failure:
[ERROR] /usr/local/etc/cbioportal/core/src/test/java/org/mskcc/cbio/portal/servlet/NullHttpServletRequest.java:[63,8] **org.mskcc.cbio.portal.servlet.NullHttpServletRequest is not abstract and does not override abstract method <T>upgrade(java.lang.Class<T>) in javax.servlet.http.HttpServletRequest**
[ERROR] /usr/local/etc/cbioportal/core/src/test/java/org/mskcc/cbio/portal/servlet/NullHttpServletResponse.java:[89,20] org.mskcc.cbio.portal.servlet.NullHttpServletResponse.NullServletOutputStream is not abstract and does not override abstract method setWriteListener(javax.servlet.WriteListener) in javax.servlet.ServletOutputStream
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

**Comment by jjgao** [comment]
@sgspaddy what version of Java are you using?

**Comment by sgspaddy** [comment]
@jjgao Thank you for taking care for this issue, the versions are:

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

=================================================================

Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T14:33:14-04:00)
Maven home: /opt/apache-maven-3.5.4
Java version: 1.8.0_144, vendor: Oracle Corporation, runtime: /usr/java/jdk1.8.0_144/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-642.11.1.el6.x86_64", arch: "amd64", family: "unix"
==================================================================

Python 3.4.5 (default, Jun  1 2017, 13:52:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux
Type "help", "copyright", "credits" or "license" for more information.
==================================================================

mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
==================================================================

**Comment by sgspaddy** [comment]
@jjgao Thank you for taking care tare of this issue. The versions are:

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
===================================================================

Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T14:33:14-04:00)
Maven home: /opt/apache-maven-3.5.4
Java version: 1.8.0_144, vendor: Oracle Corporation, runtime: /usr/java/jdk1.8.0_144/jre
Default locale: en_US, platform encoding: UTF-8
===================================================================

Python 3.4.5 (default, Jun  1 2017, 13:52:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux
Type "help", "copyright", "credits" or "license" for more information.
===================================================================

**Comment by n1zea144** [comment]
Strange that we are only seeing this now.  @sgspaddy Can you rerun maven with the -X switch and provide us with the output?

**Comment by sgspaddy** [comment]
Hi @n1zea144,

Thank you for your help. Please find attached output 


[output.txt](https://github.com/cBioPortal/cbioportal/files/2966993/output.txt)

**Comment by wengm** [comment]
@jjgao and @n1zea144 
How this is solved?

**Comment by jjgao** [comment]
@wengm do you still have the issue with the latest code?

**Comment by wengm** [comment]
@jjgao No anymore. Mine was my mistake.
