### ISSUE TITLE
genie example queries don't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5856]
None of the 4 example queries on the genie public or private sites work.

The first three show a blank page with errors in the console.

The last shows a page with this error:
![image](https://user-images.githubusercontent.com/10508276/54207377-6cb14300-44b0-11e9-92ff-c17fb4c17cc1.png)

**Comment by jjgao** [comment]
@sheridancbio or @inodb could you fix the example links. I think it's in properties file.

**Comment by alisman** [comment]
Fixed.  Just needed to update study name gene --> gene_public/private  hardcoded into configuration property
