### ISSUE TITLE
Link redirects to markdown instead of rendered doc

### ISSUE THREAD

**Issue by agarwalrounak** [cBioPortal/cbioportal#5859]
In https://docs.cbioportal.org/5.2-datasets/downloads#study-staging-files, `validator and importer` redirects to [Data-Loading.md](https://github.com/cBioPortal/cbioportal/blob/master/docs/Data-Loading.md). Instead, it should redirect to https://docs.cbioportal.org/5.1-data-loading/data-loading 

Similarly, In https://docs.cbioportal.org/2.1-deployment/load-sample-cancer-study#set-the-portal_home-environment-variable, `the previous step` redirects to [Deployment.md](https://github.com/cBioPortal/cbioportal/tree/c52f9891f04a4d7cd7d8c2983dd496ef75f2150c/docs/Deployment.md) which is a broken link and should have been [Deploying.md](https://github.com/cBioPortal/cbioportal/blob/c52f9891f04a4d7cd7d8c2983dd496ef75f2150c/docs/Deploying.md) but here too there is already a rendered doc for it https://docs.cbioportal.org/2.1-deployment/deploying

**Comment by agarwalrounak** [comment]
Once the issue is approved, I can start working on it.

**Comment by agarwalrounak** [comment]
@onursumer @jjgao Any thoughts on this?

**Comment by jjgao** [comment]
@agarwalrounak good catch. thank you! Please feel free to send us a pull request to fix this.
