### ISSUE TITLE
Performance issues due to early setting of qtip in Oncoprint rendering

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#586]
qtips are being added during Oncoprint rendering and tests show that performance can easily be improved by 15% by delaying this until items are hovered. 

Currently in a query with 50 genes and 482 samples, the function QTIP = $.fn.qtip = function(options, notation, newValue) in jquery.qtip.min.js is called 3570 times during rendering!

**Comment by adamabeshouse** [comment]
this won't be an issue in the new oncoprint
