### ISSUE TITLE
cBioportal frontend environment is only compatible for node version 8.12.0.

### ISSUE THREAD

**Issue by Parth910** [cBioPortal/cbioportal#5861]
If we have other versions of Node which is greater than 8.12.0. we are not able to compile project.

Can we upgrade the project such that it is compatible with node version >= 8.12.0. ?

**Comment by jjgao** [comment]
@alisman @cBioPortal/frontend comments?

**Comment by alisman** [comment]
Short answer: you can use NVM (node version manager) to solve this.  Allows you to have multiple node versions and use them simultaneously for different projects as necessary.

The node version is somewhat dictated to us by the different remote env/platforms we use as part of build/deployment.   It might be possible to upgrade, but it will be a chore to constantly keep it in sync and would force everyone to always be upgrading their local node version unecessarily.  So unless there's a strong reason to upgrade, I want to keep it locked for the time being.  NVM was created to solve this specific problem.

**Comment by Parth910** [comment]
I already used NVM for development. but I want to know why we are not upgrading version. Now I got it. Thanks for Reason @jjgao @alisman.
