### ISSUE TITLE
allele frequency rounding factor

### ISSUE THREAD

**Issue by patidarr** [cBioPortal/cbioportal#5864]
Hi,

Currently the allele frequency is rounded to 2 digits after the decimal but I am planning on uploading a ctDNA project samples to our local instance and in most cases the VAF comes as 0.00, is there a setting I can change round it upto 4 digits after decimal? so that I see a line in patient view when multiple samples are ran from a patient?

Thanks,
Rajesh

**Comment by jjgao** [comment]
@patidarr good point.

**Comment by coderrsid** [comment]
Hey @jigao @patidarr  Can you provide more description with screenshots

**Comment by patidarr** [comment]
<img width="1377" alt="Screen Shot 2019-03-15 at 12 40 32 PM" src="https://user-images.githubusercontent.com/4172322/54447427-c8cdce80-471f-11e9-93ce-4ab5d8ff2402.png">
<img width="1391" alt="Screen Shot 2019-03-15 at 12 41 11 PM" src="https://user-images.githubusercontent.com/4172322/54447428-c8cdce80-471f-11e9-941c-dc6971bc7dc1.png">

Here are some examples.

What I think:
Not only we need to change the rounding factor, but if there is a possibility to change the scale of bar graph so that these AF bar become visible (when multiple samples from same patient), (mayb log scale)
or project specific settings to show scale VAF bars from 0 to X AF?

Thanks a lot,
Rajesh

**Comment by coderrsid** [comment]
Thanks @patidarr. I'll look after this issue for sure.

**Comment by coderrsid** [comment]
@patidarr can you provide the link of you sent screenshots?

**Comment by patidarr** [comment]
@coderrsid, sorry this is on a instance inside the firewall.

**Comment by coderrsid** [comment]
@jjgao  Can you provide some link of this query, i can't find allele frequency.

**Comment by jjgao** [comment]
@coderrsid here are two examples: 
- https://www.cbioportal.org/patient?studyId=ucec_tcga_pub&caseId=TCGA-BK-A0CC
- https://www.cbioportal.org/results/mutations?session_id=5c8fa291e4b0d20a239993c3

Note that the frequencies in the public portal are usually high (>0.03)

**Comment by coderrsid** [comment]
So @jjgao , How can i test the changes i did?

**Comment by MehulGoel1** [comment]
I think changing this value to 4 might work. Or as @jjgao said most frequencies are usually high (>0.03), we can add a condition if(frequency<0.01) frequency.toFixed(4)

![screenshot (1)](https://user-images.githubusercontent.com/35894429/54872304-f97cca80-4de7-11e9-8934-bab7de66ee47.png)

**Comment by coderrsid** [comment]
Thanks @MehulGoel1

**Comment by coderrsid** [comment]
But the problem is the database of cbioportal doesn't has allele frequency less than 0.01. So i don't know how to test my results.

**Comment by patidarr** [comment]
@jjgao, is this issue fixed? I am still on v2.1.0 but would migrating to latest version solve it?

Thanks,
@patidarr
