### ISSUE TITLE
add link on tutorial page to google drive folder

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5865]
In order to allow users to easily download the tutorial slides, let's add a link to the google drive folder where the slides live: https://drive.google.com/drive/u/0/folders/0B9KTQJAGhFhhRi1qaTdUWmpLQTA

**Comment by ayushns9** [comment]
I would like to work on this issue.

**Comment by ayushns9** [comment]
@dippindots I've added the PR! Please review: https://github.com/cBioPortal/cbioportal-frontend/pull/2129

**Comment by ayushns9** [comment]
I've added the pull request! Please review: https://github.com/cBioPortal/cbioportal-frontend/pull/2129
