### ISSUE TITLE
Issue importing sample study

### ISSUE THREAD

**Issue by figalj** [cBioPortal/cbioportal#5867]
I have cbioportal up and running and have imported the seed database without issues.  Trying to run the following: ./metaImport.py -s ../../../test/scripts/test_data/study_es_0/ -u http://localhost:8080/cbioportal -v -o

I get the following error:
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
Traceback (most recent call last):
  File "./metaImport.py", line 118, in <module>
    cbioportalImporter.main(args)
  File "/var/webapps/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 423, in main
    process_directory(jvm_args, study_directory)
  File "/var/webapps/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 276, in process_directory
    import_cancer_type(jvm_args, data_filename)
  File "/var/webapps/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 54, in import_cancer_type
    run_java(*args)
  File "/var/webapps/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 798, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
RuntimeError: Aborting due to error while executing step.

If I scroll up, I see a sql error: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'cbioportalcbioportal'

I'm not sure why it is trying to hit the database called cbioportalcbioportal, the database is actually named cbioportal.  I checked the portal.properties file and the database is named correctly.  Any ideas why it is calling the DB name twice?

**Comment by jjgao** [comment]
@fedde-s @pieterlukasse any insights?

**Comment by fedde-s** [comment]
The Python part of the traceback suggest that the step it was executing at the time was [the Java class to add a cancer type](https://github.com/cBioPortal/cbioportal/blob/v2.1.0/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportTypesOfCancers.java#L48). By that point, the importer should have already succesfully connected to the database to [check the schema version](https://github.com/cBioPortal/cbioportal/blob/v2.1.0/core/src/main/scripts/importer/cbioportalImporter.py#L447).

**Comment by fedde-s** [comment]
I imagine it might be a difference between how the two commands connect to the database. @figalj, which release of the cBioPortal code are you running? The difference in logic [changed](https://github.com/cBioPortal/cbioportal/commit/c8621f0769d6deede4b58075ea989f2546741504) as of v1.18.0.

**Comment by figalj** [comment]
The version of the app is 1.10.1.  I believe the DB version is 2.4

**Comment by fedde-s** [comment]
In that case I expect that it might have something to do with the value of the [`db.connection_string`](https://github.com/cBioPortal/cbioportal/blob/v1.10.1/src/main/resources/portal.properties.EXAMPLE#L12) setting in your portal.properties file--try comparing it to the `db.host` setting in the same file. Note that, with software versions older than v1.18.0, you have to [rebuild the Java code](https://github.com/cBioPortal/cbioportal/blob/v1.10.1/docs/Build-from-Source.md#building-with-maven) whenever you change any configuration.
