### ISSUE TITLE
MySql Version 

### ISSUE THREAD

**Issue by sgspaddy** [cBioPortal/cbioportal#5874]
Hi Cbioportal Team,

As IT security requirement, we are forced to use Mysql 8.x version instead of 5.x. We got the following error message regarding version conflicts.:

Is there any way that we can locate the file and change the SQL query on our local instance?

20-Mar-2019 08:20:03.393 SEVERE [https-jsse-nio-443-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [api] in context with path [/cbioportal] threw exception [Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException:
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank,
        mut_sig.NumBasesCovered AS numBasesCovered,
        mut_sig.NumMut' at line 7
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank,
        mut_sig.NumBasesCovered AS numBasesCovered,
        mut_sig.NumMut' at line 7
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank,
        mut_sig.NumBasesCovered AS numBasesCovered,
        mut_sig.NumMut' at line 7] with root cause
 com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank,
        mut_sig.NumBasesCovered AS numBasesCovered,
        mut_sig.NumMut' at line 7

**Comment by khzhu** [comment]
@sgspaddy, mysql8 does not allow to use any reserved keywords such as rank, group as identifiers without quoting. In org/cbioportal/persistence/mybatis/SignificantlyMutatedGeneMapper.xml file 
rank was used without a quote. So, change 
>mut_sig.RANK AS rank,

to

> mut_sig.`RANK` AS `rank`,

will solve the issue. Hope this helps!

**Comment by sgspaddy** [comment]
@khzhu
Thank you. We are trying to modify the query but we couldn’t find the xml file in our local cbioportal. Could you please help us locate the xml files?

**Comment by khzhu** [comment]
@sgspaddy , you will have to build your war file and re-deploy it to the site. Please check this document (https://github.com/cBioPortal/cbioportal/blob/master/docs/Deploying.md) for more details.

**Comment by sgspaddy** [comment]
@khzhu  Thank you, Kelsey. We have successfully updated the query at our local instance. Thanks!

**Comment by khzhu** [comment]
@sgspaddy , glad it worked out. Thanks for the updates!

**Comment by jjgao** [comment]
@khzhu maybe we should fix it in our scheme?

**Comment by khzhu** [comment]
that is a good idea. should I start a PR for this?

**Comment by jjgao** [comment]
@khzhu yes, please.

**Comment by khzhu** [comment]
Hi @jjgao , checked the latest master branch, someone already made the correction. No PR needed any more.
![Screen Shot 2019-03-23 at 6 06 24 PM](https://user-images.githubusercontent.com/17375786/54872188-9c0c5d80-4d96-11e9-9ee5-07006172b0c5.png)

**Comment by jjgao** [comment]
thanks. Closing this.
