### ISSUE TITLE
structure alignment is not displayed when switching to another gene

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5878]
steps to reproduce:
- open https://www.cbioportal.org/results/mutations?session_id=5ba11ce6498eb8b3d567e7ed
- click "view 3d structures"
- switch to BRAF

issue: 3d structure is displayed but not the alignment is not

![image](https://user-images.githubusercontent.com/840895/54749737-e8477a00-4bab-11e9-881b-e99c7baf6346.png)

**Comment by onursumer** [comment]
@jjgao I couldn't reproduce this one, but I suspect that it might be related to some `async` reload behavior of the alignment panel. We might be doing something wrong here: https://github.com/cBioPortal/cbioportal-frontend/blob/fe501529d6951ce98c812a61e5255b2f813d2925/src/shared/components/proteinChainPanel/ProteinChainPanel.tsx#L210

**Comment by MehulGoel1** [comment]
![image](https://user-images.githubusercontent.com/35894429/54872162-e7019180-4de5-11e9-84b3-4ca592893e94.png)
I think the annotation is actually present, it is just in a very small part, so requires some looking. I may have got it wrong and assuming something else annotation.

**Comment by jjgao** [comment]
strange. now it showed up. Closing.

**Comment by onursumer** [comment]
Confirmed that this bug exists (thanks to @inodb). This occasionally causes some e2e tests fail, reopening for further investigation.

**Comment by inodb** [comment]
still an issue
