### ISSUE TITLE
Remove invokeOldDataManagers method

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#588]
invokeOldDataManagers() in oncoprint-analysis-setup.js is still called. Perhaps this can now be removed.

**Comment by pieterlukasse** [comment]
@adamabeshouse : can this be closed? Or is it still present?

**Comment by jjgao** [comment]
@adamabeshouse update?

**Comment by adamabeshouse** [comment]
It cannot yet be closed. PortalDataCollManager, which is what is invoked, interacts with other tabs in ways I need to look into and replace. Should this be a priority?

**Comment by jjgao** [comment]
@adamabeshouse not a priority. Just to keep track.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1416
