### ISSUE TITLE
Overall survival curve, custom visualization ? 

### ISSUE THREAD

**Issue by kcourtet** [cBioPortal/cbioportal#5883]
Hi ! I have a question about the Overall Survival curve visualization : for a combined study query, is it possible to get one curve per studies instead of an unique global one ?

Something like this :
![image](https://user-images.githubusercontent.com/36259702/54829216-3648a480-4cb6-11e9-9725-3c6abc028726.png)

**Comment by jjgao** [comment]
Hi @kcourtet: could you send the question to cbioportal@googlegroups.com? (please let us know if you asking about the survival curve when you query genes or on the study view page?) 

thanks
