### ISSUE TITLE
svg to pdf - legend sometimes broken

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#5886]
After merging #2094:

https://cbioportal.org/results/oncoprint?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_ids=&case_set_id=coadread_tcga_pub_nonhypermut&clinicallist=CANCER_TYPE_DETAILED%2CMUTATION_COUNT%2CNO_CONTEXT_MUTATION_SIGNATURE&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&heatmap_track_groups=coadread_tcga_pub_rna_seq_mrna_median_Zscores%2CKRAS%2CNRAS%2CBRAF&show_samples=false

Download pdf and you'll see the legend is spaced weirdly, thus some tracks get pushed off

**Comment by dippindots** [comment]
This issue has been solved in https://github.com/cBioPortal/cbioportal-frontend/pull/2094.

**Comment by adamabeshouse** [comment]
@dippindots i found the bug with your PR, it was not existing before

**Comment by alisman** [comment]
@adamabeshouse this is fixed, right?

**Comment by adamabeshouse** [comment]
ah, yeah it is. but now I just found another more minor error - the gradient seems broken
@alisman @dippindots 

![image](https://user-images.githubusercontent.com/636232/55422159-02d50800-5549-11e9-8918-f0514895f5c2.png)

**Comment by dippindots** [comment]
@adamabeshouse Yes, it is a bug. I just reported this bug to the svg2pdf library repo. Let's see whether they have already had a solution to this issue.
