### ISSUE TITLE
Can pathology report url configurable?

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#5888]
Currently Pathology Report tab in Patient view looks for files in just `cBioPortal/datahub` repo 

cbioportal-frontend/src/pages/patientView/pathologyReport/PathologyReport.tsx
```let resp: any = await request.get(`//api.github.com/search/code?q=${this.patientId}+extension:pdf+in:path+repo:cBioPortal/datahub`);```

Is it possible to make the complete url configurable?

**Comment by inodb** [comment]
There is an RFC for this in the works: https://docs.google.com/document/d/1_Re7ThLGYcyzvpEH9eMrdi-vbOx_He5Txkgt_L0onGA/edit#
