### ISSUE TITLE
SV: Save and reuse UI state for logged in users

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#5892]
- [x] Save study view state (chart order, visible charts and chart type for this round) for log'ed users
- [x] Use the latest study view state (for particular user and study list) in visualizing page
- [x] Save custom chart

**Comment by kalletlak** [comment]
@zhx828 @jjgao which model should we go with?

1. this is based directly on objects/types present in StudyViewPageStore. with this we can directly set the local variables
```
    {
        visibleCharts?: {[id:string]:boolean},
        chartTypes?: { [id: string]: ChartType },
        chartDimensions?: { [id: string]: ChartDimension },
        customCharts?: {
            id: string,
            name: string,
            groups: NewChart
        }[],
        layout?:  ReactGridLayout.Layout[]
    }
```

2. A cleaner version with all properties of a chart together. with this there is some overhead in converting/setting it to/from the local variables
```
   {
        id: string,
        name?:string,
        visible?:boolean,
        chartType?:ChartType,
        dimension?: ChartDimension,
        groups?: NewChart //used when it is custom chart
        layout?:  ReactGridLayout.Layout
    }[]
```

**Comment by jjgao** [comment]
I like 2 but it probably make sense to go with 1 -- the same as what we have in store. Unless we change the store?

**Comment by kalletlak** [comment]
Model 1 has redundant data. I considered 2 in all my implementations since its much cleaner, no redundant data and validation can be done easily. there is very little overhead in transformation between those models.

**Comment by jjgao** [comment]
@kalletlak could you prioritize this one?
