### ISSUE TITLE
study view: colors change when filters are applied

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5893]
Go to: https://www.cbioportal.org/study?id=hcc_mskimpact_2018&tab=summary

Add chart for HBV

Look at Race chart -- note that "White" is blue and "Asian" is red.

Filter to "Yes" for HBV.

Now look at the Race chart again: "White" is now orange and "Asian" is blue.

This is very confusing to a user. Colors need to be consistent after filters are applied.

**Comment by jjgao** [comment]
I guess the color is assign currently based on the order of Freq. I guess we need to hash the colors based on value. We may need some backend support on this...

**Comment by zhx828** [comment]
@jjgao also the reserved values? These reserved colors also used in oncoprint. They need to be added in the endpoints for oncoprint as well.

**Comment by jjgao** [comment]
@zhx828 I don't understand. For the reserved values (Yes, No, etc), do we have fixed colors? If so, they are fine. 

The problem is that the colors of non-reserved values keep changing and the problem becomes more obvious when the colors change after selecting a subset of samples as shown in @tmazor's example.

**Comment by zhx828** [comment]
@jjgao if you move the logic of assigning colors. Then the reserved colors for reserved values should be moved to backend as well. The logics should stay together.

**Comment by jjgao** [comment]
@zhx828 I see your point.

Do you think it's possible to remember the colors of values without filtering and apply the same colors after filtering? One challenge might be when the user loads a new chart after filtering?

**Comment by zhx828** [comment]
@zhx828 even for the latter scenario. I can remember the colors too.  Basically have a cache variables to remember the colors for one particular chart. Just need some confirmation from product team what side where this should be done(frontend or backend).

**Comment by jjgao** [comment]
@zhx828 let's do it in the frontend and remember the colors (that sounds much easier technically). It's ok that different colors are used in different studies or even different sessions, but at least the same session should stick to the same colors.

**Comment by zhx828** [comment]
@jjgao thanks, will do.

**Comment by tmazor** [comment]
This is still an issue
