### ISSUE TITLE
study view survival tooltip is impossible to click

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5895]
There is a checkbox that appears in the survival plot tooltip:

![image](https://user-images.githubusercontent.com/10508276/55021975-0d832080-4fd0-11e9-96a4-c2f361a077f2.png)

I can't get my mouse into the tooltip to click it - the tooltip closes as soon as my mouse approaches it.

**Comment by brettvanderwerff** [comment]
@tmazor @zhx828 I am not sure who to tag, but if someone wants to assign me I can open a PR. I have replicated this issue and I think I have a fix for this.

**Comment by zhx828** [comment]
@brettvanderwerff thanks, please feel free to send a pr.

**Comment by brettvanderwerff** [comment]
@zhx828 No problem, I opened PR 2193 on the frontend repo to try and resolve this

https://github.com/cBioPortal/cbioportal-frontend/pull/2193
