### ISSUE TITLE
Comparison: using upset for overlap analysis when there are 4 or more groups

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5898]
http://caleydo.org/tools/upset/

Maybe just use this one instead of the full feature:

![image](https://user-images.githubusercontent.com/840895/55032548-7924b800-4fe7-11e9-9924-47b7ea456209.png)

Not sure if we can use [their code](https://github.com/VCG/upset), but may be we can implement it if necessary?

**Comment by kalletlak** [comment]
Done in https://github.com/cBioPortal/cbioportal-frontend/pull/2219
