### ISSUE TITLE
Mutation Count vs FGA density API broken in rc

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#5899]
The API seems to be returning empty for coadread_tcga_pub, msk_impact_2017, probably others

![image](https://user-images.githubusercontent.com/636232/55034647-5052f180-4fec-11e9-8cc7-aa1e0b214892.png)

**Comment by jjgao** [comment]
@adamabeshouse is there any update to the related endpoints in RC?

**Comment by kalletlak** [comment]
Fixed in https://github.com/cBioPortal/cbioportal/pull/5954
