### ISSUE TITLE
cBioPortal SAML implementation - is it federation ready?

### ISSUE THREAD

**Issue by vipints** [cBioPortal/cbioportal#5901]
Dear cBioPortal team, 

At ETH Zurich, we are deploying a cBioPortal instance which can be accessed by multiple organizations. I thought of configuring SAML authentication for this instance. 

I am following the [documentation](https://cbioportal.readthedocs.io/en/latest/Authenticating-Users-via-SAML.html#) about the cBioPortal SAML implementation. Is it restricted to a *single IdP*? 

Thanks! 
Vipin

**Comment by jjgao** [comment]
Vipin, keycloak is probably what you are looking for: https://github.com/cBioPortal/cbioportal/blob/master/docs/Authenticating-and-Authorizing-Users-via-keycloak.md

If you need more info, please email cbioportal@googlegroups.com.
