### ISSUE TITLE
SV: Custom chart pie-to-table conversion doesn't set dimensions correctly

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#5903]
![Screen Shot 2019-03-27 at 12 45 47 PM](https://user-images.githubusercontent.com/12956870/55095292-497cbb00-508e-11e9-80e9-f71be04d63f9.png)
![Screen Shot 2019-03-27 at 12 45 53 PM](https://user-images.githubusercontent.com/12956870/55095293-497cbb00-508e-11e9-98af-6e9ab929ea81.png)

**Comment by zhx828** [comment]
@kalletlak I do need to get the steps reproducing the issue. I think I solved this issue before.

**Comment by kalletlak** [comment]
1. Add a new custom chart
2. Convert pie chart to table
