### ISSUE TITLE
Error encountered while checking out master using git

### ISSUE THREAD

**Issue by lakhujanivijay** [cBioPortal/cbioportal#5907]
Hi,

I am trying to install local cbioportal database on my pc so I am following the instructions provided at [this](https://docs.cbioportal.org/2.1-deployment/system-requirements) and [this](https://docs.cbioportal.org/2.1-deployment/pre-build-steps) link:

This command works fine:

```
(cbioportal) bioinfo@bioinfo-pc:~$ git clone https://github.com/cBioPortal/cbioportal.git
Cloning into 'cbioportal'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 204104 (delta 24), reused 9 (delta 0), pack-reused 204039
Receiving objects: 100% (204104/204104), 216.20 MiB | 2.23 MiB/s, done.
Resolving deltas: 100% (123795/123795), done.
```
However, when I run this, I get an error

```
(cbioportal) bioinfo@bioinfo-pc:~$ git checkout master
fatal: not a git repository (or any of the parent directories): .git
```

Could you please help? I am on ubuntu 16.04 LTS edition.

**Comment by jjgao** [comment]
@lakhujanivijay you would need to cd into the folder cbioportal.
