### ISSUE TITLE
Pending Session

### ISSUE THREAD

**Issue by 1231231312321132** [cBioPortal/cbioportal#5910]
I have recently experienced a problem when querying a set of genes (about 300 genes) against few clinical studies. The website just redirects to the main page and I get a webpage link: https://www.cbioportal.org/results/oncoprint?session_id=5c9cb165e4b0d20a23999eb8

Do I just have to access this session id at a later time so that it is complete?

However, when I do the same process with another set of genes, the website continues further with the analysis.

Why is that?

**Comment by jjgao** [comment]
@dippindots could you help look into this?

**Comment by dippindots** [comment]
@jjgao Sure, I will take a look today!

**Comment by alisman** [comment]
@dippindots looks like session service cannot handle that may genes?  surprising but possible.

**Comment by dippindots** [comment]
@alisman In this issue, the problem is we got "InvalidGenes" error. Seems like this "MIA2" gene has been added twice when we fetch the data from our API. Maybe this is a data related issue?

**Comment by alisman** [comment]
@jjgao @n1zea144 see @dippindots response.  is this possible?

**Comment by jjgao** [comment]
why no error was shown in frontend? Could you try to reproduce it with a small set of genes? @dippindots @alisman

**Comment by dippindots** [comment]
@jjgao we can try this [link](http://www.cbioportal.org/results/cancerTypesSummary?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=luad_broad%2Cluad_mskcc_2015%2Cluad_tcga_pub%2Cluad_tcga_pan_can_atlas_2018%2Cluad_tcga%2Cluad_tsp%2Clusc_tcga_pub%2Clusc_tcga_pan_can_atlas_2018%2Clusc_tcga%2Clung_msk_2017%2Cnsclc_pd1_msk_2018%2Cnsclc_unito_2016%2Cnsclc_tcga_broad_2016&case_set_id=all&data_priority=0&gene_list=MIA2&geneset_list=%20&tab_index=tab_visualize): This query only contains `MIA2` gene, but we will get this error in the frontend(the `MIA2` gene will be returned twice when after the API call). 
![image](https://user-images.githubusercontent.com/15748980/55972905-6a2e3e80-5c52-11e9-98e9-28d7b0cf4b23.png)

**Comment by dippindots** [comment]
This is an issue related to https://github.com/cBioPortal/datahub/issues/540.

**Comment by jjgao** [comment]
@alisman we will fix the issue (duplicated gene symbols) with https://github.com/cBioPortal/cbioportal/issues/5910.

**Comment by alisman** [comment]
@jjgao it's my understanding that a single hugo can legitimately map to multiple entrez, no?

**Comment by jjgao** [comment]
@alisman that's a data bug that we need to fix. A single hugo should only map to one entrez once that's fixed.

**Comment by alisman** [comment]
@dippindots we need to change validation api to catch this condition (2 genes with same hugo symbol)

**Comment by jjgao** [comment]
looks like it's fixed.
