### ISSUE TITLE
stad_tcga_pub has mRNA data but doesn't list mRNA as a genomic profile

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5915]
There are samples with mRNA data, and expression data is visible in the Plots tab, but mRNA isn't an available genomic profile for querying:

![image](https://user-images.githubusercontent.com/10508276/55236923-5bce3480-5207-11e9-80b6-fe95a3bed77c.png)

**Comment by yichaoS** [comment]
The data file for the RNA exp v2 exp zscore file somehow was missing. We added them back and now the profile is showing up (see screenshot). 

![Screen Shot 2019-04-02 at 11 30 10 AM](https://user-images.githubusercontent.com/5973438/55415234-acf96380-553a-11e9-80d7-c0645b560c98.png)
