### ISSUE TITLE
Mouse over popup on the wrong survival plot

### ISSUE THREAD

**Issue by Sjoerd-van-Hagen** [cBioPortal/cbioportal#5920]
When looking at the survival tab in the results page. If I hover over the samples in the bottom survival plot, the pop-up actually appears on the top plot. It seems to be in the right location, just the wrong plot so I expect this to be an easy fix for someone familiar with the code.

Link to reproduce: https://www.cbioportal.org/results/survival?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=acc_tcga&case_set_id=acc_tcga_cnaseq&data_priority=0&gene_list=TP53&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=acc_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&tab_index=tab_visualize

**Comment by Sjoerd-van-Hagen** [comment]
Fixed?

**Comment by adamabeshouse** [comment]
yep, see attached pull request

**Comment by Sjoerd-van-Hagen** [comment]
You mean the one that is attached to issue #5933 ? Looks like that is a different issue altogether.

**Comment by adamabeshouse** [comment]
No, the pull request that addresses this is attached on github. Can you see it? It should indicate it here on this page.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2214

**Comment by Sjoerd-van-Hagen** [comment]
I do not see any link pointing from here to the PR.

Does not matter. Thanks for fixing this.
