### ISSUE TITLE
Query results page crashes - MSK Impact query for specific set of genes

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#5925]
See this URL:

https://www.cbioportal.org/results/oncoprint?session_id=5c9f8e23e4b0d20a2399a138&show_samples=false&clinicallist=NUM_SAMPLES_PER_PATIENT

![image](https://user-images.githubusercontent.com/2900303/55467138-f613eb00-5600-11e9-9730-f5683b13f64e.png)

See also https://groups.google.com/forum/#!topic/cbioportal/kcphBgnMGvo

**Comment by pieterlukasse** [comment]
Notify: @alisman @inodb

**Comment by pieterlukasse** [comment]
Is this one also related https://mail.google.com/mail/u/0/#label/cbio+forum/FMfcgxwBWTFWlHcXHDZVBFVsKVrkNMhR ?

**Comment by alisman** [comment]
@pieterlukasse @jjgao, the query has >500 genes.  the browser is throwing a OUT OF MEMORY exception.   
1. Do we know that such a query ever worked? (if so, it's possible that a new feature we introduced made it impossible to support)  
2. Should we support that many genes?   If not, we should enforce a limit.

**Comment by jjgao** [comment]
We used to allow up to 100 genes, but the limit was dropped during refactoring.

@cBioPortal/product does anyone have a use case for using >100 genes?

**Comment by ecerami** [comment]
I vote to go back to the 100 gene limit.

**Comment by 1231231312321132** [comment]
I have done up to 250 genes.

**Comment by tmazor** [comment]
I think a 100 gene limit is reasonable

**Comment by Sjoerd-van-Hagen** [comment]
Agree with the limit of 100.

--

Sjoerd van Hagen

E.   sjoerd@thehyve.nl

T.   +31(0)30 700 9713

W.  www.thehyve.nl

**Comment by alisman** [comment]
Ok, I have created a ticket to impose this limit.  Should be done this week.  
https://github.com/cBioPortal/cbioportal/issues/5932

**Comment by 1231231312321132** [comment]
Why such a low limit?

Why not allow user a higher limit?

**Comment by pieterlukasse** [comment]
@1231231312321132 the differential expression (aka enrichment) analysis done in cBioPortal includes all genes (e.g. do a 1 gene query and then go to "Enrichments">mRNA tab - see screenshot below)

![image](https://user-images.githubusercontent.com/2900303/55634915-c52de480-57bf-11e9-8420-7795f2d256eb.png)

The limit in this page is mainly about how many genes you would like to see in the Oncoprint tab, and how many genes you want to use to split the sample set into 2 groups ("altered" vs "unaltered" groups) for other plots like the survival plot. Makes sense? If not, maybe you can explain a bit more about your specific use case?

**Comment by jjgao** [comment]
@1231231312321132 please let us know if you have any other use cases that require >100 genes.

**Comment by 1231231312321132** [comment]
My intended use was for the survival plots and see how many of my differentially expressed genes are altered against a set of clinical studies (total of 500 genes). I've managed to get up to 200 genes at once working. Not sure why creating a higher limit would pose a problem, but it would be lovely if the limit is adjusted higher.

**Comment by jjgao** [comment]
@1231231312321132 Thanks for the explanation!

The problem is that when querying hundreds of genes, the browser may not be able to hold so much data. It also creates a burden for our server.

Querying 200 genes for survival analysis is probably a rare use case. We have to make hard decisions to better use our resources for more common use cases.

**Comment by jjgao** [comment]
@1231231312321132 please feel free to elaborate with an example (e.g a query), and maybe we can find a workaround.

**Comment by Sjoerd-van-Hagen** [comment]
@1231231312321132 note that you can deploy your own instance of cBioPortal and set the limit to whatever you like. We need to take other users into account who may work with a slower machine than yours, and as JJ mentioned this also impacts the server performance.

**Comment by 1231231312321132** [comment]
Fair enough

**Comment by pieterlukasse** [comment]
the portal now displays a clear error message:
<img width="909" alt="Screen Shot 2019-06-07 at 22 37 31" src="https://user-images.githubusercontent.com/2900303/59132236-f1f3a900-8974-11e9-81b1-5cc52e1f5c08.png">
