### ISSUE TITLE
Customized column name

### ISSUE THREAD

**Issue by sgspaddy** [cBioPortal/cbioportal#5931]
Hi Cbioportal Team,

Is there any possible that we could customize the column name in mutation tables? 
Ex: Change 'Variant Reads (N)' to 'Variant Reads (Normal)' ?

Thanks

**Comment by jjgao** [comment]
@sgspaddy you would have to do it in the code. I like the idea of changing 'Variant Reads (N)' to 'Variant Reads (Normal)'. Do you have any other column names to change?

**Comment by sgspaddy** [comment]
@jjgao Thank you for your replying. it will be great if we could also change 'Ref Reads (N)' to 'Ref Reads (Normal)'

**Comment by jjgao** [comment]
Change column names:

- 'Variant Reads (N)' to 'Variant Reads (Normal)'
- 'Ref Reads (N)' to 'Ref Reads (Normal)'

**Comment by sgspaddy** [comment]
yes, could we do that?

**Comment by dippindots** [comment]
@sgspaddy Yes, will do today.
