### ISSUE TITLE
Survival tooltip arrow is mis-aligned

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#5933]
![image](https://user-images.githubusercontent.com/186521/55573634-75c0b900-56d8-11e9-8287-c27458b5582c.png)

**Comment by brettvanderwerff** [comment]
@alisman I'll take a look at this and open a PR if I have a solution. I also want to document that this is somewhat connected to issue  #5920. I think #5920 is a heavier lift and I would like to try and solve this issue (#5933) by itself first. Thank you!

**Comment by brettvanderwerff** [comment]
@alisman I think @adamabeshouse beat me to the punch on this one. Should I close this issue?

https://github.com/cBioPortal/cbioportal-frontend/pull/2214

**Comment by alisman** [comment]
Tnaks @brettvanderwerff, I'll close it.
