### ISSUE TITLE
Missing maven dependency in pom.xml

### ISSUE THREAD

**Issue by c4cam** [cBioPortal/cbioportal#5934]
Hi,
Could you help me out please? I seem to be running into problems building cBioPortal due to a missing dependency (I think)?

Thanks so much for any advice/assistance you can provide.

Cheers,
Calvin

https://repo.maven.apache.org/maven2/com/github/cbioportal/maven-external-version/external-version-strategies/f09c2b9608744881111f24e55d55a91e54e6cb5f/external-version-strategies-f09c2b9608744881111f24e55d55a91e54e6cb5f.pom

https://github.com/cBioPortal/cbioportal/blob/master/pom.xml#L49

**Comment by alisman** [comment]
@c4cam did you figure this out?

**Comment by c4cam** [comment]
Yah, I dunno what I did though! It's building now again ;)
