### ISSUE TITLE
Error in gene table on cbioportal.org?

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#5936]
Why do we have a double entry for MIR21? See also here:

http://www.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=acbc_mskcc_2015%2Cbrca_metabric%2Cbreast_msk_2018%2Cbfn_duke_nus_2015%2Cbrca_bccrc%2Cbrca_broad%2Cbrca_sanger%2Cbrca_tcga_pub2015%2Cbrca_tcga_pub%2Cbrca_tcga_pan_can_atlas_2018%2Cbrca_tcga%2Cbrca_bccrc_xenograft_2014%2Cbrca_igr_2015%2Cbrca_mbcproject_wagle_2017&case_set_id=all&clinicallist=CANCER_STUDY%2CNUM_SAMPLES_PER_PATIENT%2CPROFILED_IN_COPY_NUMBER_ALTERATION%2CPROFILED_IN_MUTATION_EXTENDED&data_priority=0&gene_list=MIR-21%252F21*%250AMIR-21%252F21&geneset_list=%20&show_samples=false&tab_index=tab_visualize

![image](https://user-images.githubusercontent.com/2900303/55636143-88afb800-57c2-11e9-92c2-6e7aacc7e0f7.png)

What is the difference between both?

**Comment by pieterlukasse** [comment]
notify @sheridancbio , @ritikakundra

**Comment by ersinciftci** [comment]
Not sure if a hugo symbol ending with asterisk has a special meaning, but
```
SELECT * FROM public_test.gene where HUGO_GENE_SYMBOL like '%*';
```
returns 205 genes, and they all have a corresponding gene without the asterisk at the end in the table as well.

**Comment by jjgao** [comment]
https://www.cbioportal.org/faq#how-can-i-query-micrornas-in-the-portal

**Comment by jjgao** [comment]
@pieterlukasse it's a hack. We should do it properly when we have the bandwidth.

**Comment by yichaoS** [comment]
@pieterlukasse @ersinciftci The * indicates a different version of mature sequence for this miRNA. For precursor hsa-mir-21 there is two mature forms: hsa-miR-21 and hsa-miR-21* (Please see here: http://www.mirbase.org/cgi-bin/mirna_entry.pl?acc=hsa-mir-21). In portal we represent them in combined format, this one for example, as mir-21/21* and mir-21/21.  
When importing, if the miRNA record appears in CNA data, we duplicate the miRNA record for each difference mature forms, but if the miRNA records is in expression, we don't duplicate.

**Comment by yichaoS** [comment]
@jj how can we do it properly?
