### ISSUE TITLE
study view: add gene panel name to mutations/cna tooltip

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5937]
We're adding a tooltip to the Mutations & CNA tables with the denominator for the frequency (#5851). Let's also add a list of which gene panels those samples were sequenced on, ideally with each panel name as a link to a pop-up with the genes on that panel (like in OncoPrint).

**Comment by jjgao** [comment]
just thinking it loud.

Another useful feature would be allowing users to select samples that are profiled for a set of genes.

It would be useful to have a gene vs panel matrix...

**Comment by tmazor** [comment]
@jjgao I agree, a matrix like that would be a useful feature. But also, what about adding a pie chart to study view with the gene panels - we have this for GENIE, but I think not for any other study - could we make this automatically for all studies?

**Comment by jjgao** [comment]
@tmazor it may not be easy to do -- a sample may have different gene panels for different profiles. Maybe we should just curate the clinical attribute gene_panel? What are the studies that are missing the gene_panel attribute?

**Comment by tmazor** [comment]
@jjgao is the clinical attribute gene_panel derived from the data in the data_gene_matrix.txt file during upload? i think that would work well - we could have a mutations gene panel chart and a CNA gene panel chart.

**Comment by jjgao** [comment]
@tmazor I don't think the gene_panel data was derived from data_gene_matrix.txt, but that would work. Having two gene panel charts may work well too.

**Comment by tmazor** [comment]
The original issue for this ticket has been completed, but there is a proposal in the comments that I think we should still do. I will close this issue and make a new one for the gene panel charts described in the comments here.
