### ISSUE TITLE
Error upgrading to 2.20 - with SAML - org.cbioportal.persistence.mybatis.PatientMapper.select

### ISSUE THREAD

**Issue by c4cam** [cBioPortal/cbioportal#5940]
I'm getting a weird error upgrading cbioportal to version 2.2.0

If I turn on my SAML authentication I get this error:
SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
 org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyViewFilterApplier' defined in URL [jar:file:/usr/local/tomcat/webapps/cbioportal/WEB-INF/lib/web-2.2.0-SNAPSHOT.jar!/org/cbioportal/web/util/StudyViewFilterApplier.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sampleServiceImpl': Unsatisfied dependency expressed through field 'studyService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyServiceImpl': Unsatisfied dependency expressed through field 'cancerTypeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is org.apache.ibatis.builder.IncompleteElementException:

Could not find SQL statement to include with refid 'org.cbioportal.persistence.mybatis.PatientMapper.select'

**Comment by jjgao** [comment]
@khzhu is this the same issue? https://github.com/cBioPortal/cbioportal/issues/5816

**Comment by khzhu** [comment]
HI @jjgao , I think so. Rob and myself are looking into the issue.

**Comment by c4cam** [comment]
also, you're right - i tried rolling back to 2.0.1 and it works ok
