### ISSUE TITLE
allow clinical data in oncoprinter

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5941]
maybe a separate input box?

**Comment by adamabeshouse** [comment]
whats the input format?

**Comment by jjgao** [comment]
a matrix file of samples vs attributes?

**Comment by adamabeshouse** [comment]
`SAMPLE ID      ATTRIBUTE NAME      ATTRIBUTE VALUE`?

**Comment by jjgao** [comment]
@adamabeshouse that would work. Or we could go simply by:


SAMPLE_ID | CANCER_TYPE | AGE
-- | -- | --
S1 | COLORECTAL CANCER | 66
S2 | BREAST CANCER | 76

**Comment by adamabeshouse** [comment]
@jjgao that's a better idea :+1:

**Comment by adamabeshouse** [comment]
@jjgao just realized thats not going to work because that would only allow a single clinical track, right?

**Comment by jjgao** [comment]
@adamabeshouse not sure if I follow, but the format above will support multiple attributes - one attribute per column.

**Comment by adamabeshouse** [comment]
right, sorry i got confused for a second.
