### ISSUE TITLE
Move regression equation to the right

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5942]
Can we move the equation to the right in the legend, e.g. have a red line and followed by equation and R-square?

![image](https://user-images.githubusercontent.com/840895/55736930-4b317180-59f2-11e9-9e17-35021a186a90.png)

**Comment by alisman** [comment]
@Luke-Sikina to reproduce this, go [here](https://www.cbioportal.org/results/coexpression?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_ids=&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations) and in the top right of the chart, click "show regression line" checkbox.

**Comment by alisman** [comment]
@Luke-Sikina we use the library VictoryJS for our charts.  Victory is pretty good for this kind of customization.
