### ISSUE TITLE
Patient search fails on private portal

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#5944]
@jjgao @kalletlak can you think of any reason this endpoint (used by quicksearch) returns 501 error on public portal?

https://cbioportal.mskcc.org/api/patients?keyword=EG&projection=DETAILED&pageSize=3&sortBy=patientId

**Comment by kalletlak** [comment]
@alisman seems working fine on public portal https://www.cbioportal.org/api/patients?keyword=EG&projection=DETAILED&pageSize=3&sortBy=patientId. do you mean private mskcc portal?

**Comment by alisman** [comment]
@kalletlak oops. yes, i meant private portal.

**Comment by kalletlak** [comment]
@alisman that pr should fix the issue
