### ISSUE TITLE
adding visit statistics to study view page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5953]
Is it possible to pull the visit statistics from GA and display on study view the following information:

- total number of uses of the study data
- when mouse over
  - visits to the study view page
  - visits to Query/results page that utilizing the study
  - visits to patient view of the study
  - time the study data was downloaded

Tasks:

- [ ] Determine if GA allows public access to reporting api
- [ ] Get events data for access to study and results page
- [ ] Create component on study page that displays count of above

**Comment by alisman** [comment]
@jjgao i figured out how to get data from GA.   we need to start tracking download of study data.  could you list all the various places that can happen?  i.e. download tab, charts, etc.  or should we just track at webserice.do?

**Comment by alisman** [comment]
@jjgao maybe i could start with visits to study view, queries, then add patient and download later

**Comment by jjgao** [comment]
Starting with visits to study view, queries sounds good.

If you haven't track Download button, please add it to GA. Need to track API or webservice.do for now.

**Comment by alisman** [comment]
`    var VIEW_ID = '34065145';

    // Query the API and print the results to the page.
    function queryReports() {
        gapi.client.request({
            path: '/v4/reports:batchGet',
            root: 'https://analyticsreporting.googleapis.com/',
            method: 'POST',
            body: {
                reportRequests: [
                    {
                        viewId: VIEW_ID,
                        dateRanges: [
                            // {
                            //     startDate: '7daysAgo',
                            //     endDate: 'today'
                            // }

                            {"startDate":"2019-04-01", "endDate": "2019-04-08" }
                        ],

                        "dimensionFilterClauses": [
                            {
                                "filters": [
                                    {
                                        "dimensionName": "ga:eventAction",
                                        "operator": "EXACT",
                                        "expressions": ["query"]
                                    }
                                ]
                            },
                            {
                                "filters": [
                                    {
                                        "dimensionName": "ga:eventLabel",
                                        "operator": "EXACT",
                                        "expressions": ["brca_metabric,"]
                                    }
                                ]
                            }
                        ],

                        metrics: [
                            {
                                expression: 'ga:uniqueEvents'
                            },
                            {
                                expression: 'ga:totalEvents'
                            }

                        ]
                    }
                ]
            }
        }).then(displayResults, console.error.bind(console));`
