### ISSUE TITLE
change gene quick search to the default tab (cancer types summary) instead of Mutations tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5958]
The Gene Quick Search is pointing to Mutations tab. I think we should change it to the default tab (cancer types summary for cross cancer). Any objections, @cBioPortal/product?

![image](https://user-images.githubusercontent.com/840895/55972910-6dc1c580-5c52-11e9-9cbc-e63fdbbdaac3.png)

**Comment by jjgao** [comment]
One problem is that Mutations tab is slower than Cancer Types Summary tab for large query.

**Comment by ecerami** [comment]
I support the change.

**Comment by Sjoerd-van-Hagen** [comment]
I am also in favor.

**Comment by Sjoerd-van-Hagen** [comment]
I am also in favor.

**Comment by coderrsid** [comment]
I can work on this @jjgao and make this route go to cancer types summary

**Comment by schultzn** [comment]
+1

**Comment by jjgao** [comment]
@coderrsid that'd be great. Thanks.

notifying @alisman as well.

**Comment by coderrsid** [comment]
@jjgao Check the PR please.
