### ISSUE TITLE
'0' zero sample count on Query Builder (study selector)

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#5961]
After getting imported, some studies are labelled as having zero samples despite the data existing in the database.  Further more, this incorrect label only appears in the study selector widget of the Query Builder page.  Elsewhere on this page, the correct number of samples is displayed.

![image](https://user-images.githubusercontent.com/366003/56047770-28fe6300-5d14-11e9-8276-334e1add0da9.png)

**Comment by dippindots** [comment]
@n1zea144 @alisman Quick looked at this ticket, it is because the incorrect label is using the `allSampleCount` of each study as the samples count value. I think this might because of the `allSampleCount` mismatch with the actual count. We can make a quick fix by counting the sample list. But I think it is still a data problem we need to fix.

**Comment by alisman** [comment]
@dippindots @n1zea144 it does seem we should fix allSampleCount because it's used elsewhere in project.  Would be super wasteful to load all samples just to count them.

**Comment by dippindots** [comment]
@n1zea144 I found out we simply count the matched samples in our database for each study: [StudyMapper](https://github.com/cBioPortal/cbioportal/blob/master/persistence/persistence-mybatis/src/main/resources/org/cbioportal/persistence/mybatis/StudyMapper.xml#L76). Seems it is right, one thing may cause the mismatch is `STABLE_ID` and `CONCAT(cancer_study.CANCER_STUDY_IDENTIFIER,'_all')` mismatch. We may want to check if the sample of our database has the correct `STABLE_ID`. Could I ask for your input?

**Comment by jjgao** [comment]
@n1zea144 @sheridancbio somehow this study is `set_oa_gct` but the case id is `pi_8a_d6_set_oa_gct_all`. I think we should fix the data.

**Comment by n1zea144** [comment]
Hi @dippindots @alisman @jjgao Sorry for not following up sooner.  We did go back to roslin and ask them to update the data.  I'll remind them and also close this ticket.
