### ISSUE TITLE
Use prettier to format TypeScript code 

### ISSUE THREAD

**Issue by lemccarthy** [cBioPortal/cbioportal#5963]
Currently, the frontend codebase for cBioPortal has no unified formatting settings. Unified formatting settings are important for consistent style across multiple authors and make it easier to maintain a large code base. I recommend we use prettier (https://github.com/prettier/prettier) to format our frontend code. Most IDEs have an extension for it, and it can be configured to run on save, or set up to run as a pre-commit hook. This way individual contributors can style their code the way they want to without affecting the style of the project.

**Comment by jjgao** [comment]
Doing this at one shot may create too many conflicts with active pull requests. If we decide to do this, we need to come up with a strategy.
