### ISSUE TITLE
oncoprint pdf download has weird file name

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#5964]
I think it's due to the svg2pdf library. Is it possible to change it?

![image](https://user-images.githubusercontent.com/636232/56064466-1b5ed280-5d40-11e9-8f75-7f56d8688ec1.png)

**Comment by dippindots** [comment]
@adamabeshouse That's weird, I will take a look. Could you give me the link you are using so that I can reproduce it? Also, just want to make sure, are you using Chrome?

**Comment by adamabeshouse** [comment]
@dippindots 
https://www.cbioportal.org/results/oncoprint?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_ids=&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations

yes, I'm using chrome
