### ISSUE TITLE
Hyperlink to Gene panels for mutation data is broken

### ISSUE THREAD

**Issue by lakhujanivijay** [cBioPortal/cbioportal#5965]
Hi again!

I am looking at [this](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#mutation-data) link to import mutation data into cBioPotal. Under this section, at "Meta File" -> point#9, the [link to gene panel data](https://github.com/cBioPortal/cbioportal/blob/master/docs/gene-panels-for-mutation-data) is broken.

Could you please update the link for us?

**Comment by dippindots** [comment]
@lakhujanivijay Thanks for reporting this bug to us, the documentation has been updated. Sorry about any inconvenience for you.

**Comment by lakhujanivijay** [comment]
@dippindots Thanks for the response. Strange though, I still cannot access it. I am looking at an incorrect link? Can you please share the URL of the correct link?

Highly appreciating the  attention.

**Comment by lakhujanivijay** [comment]
Hi again, 

Is this fixed?

**Comment by dippindots** [comment]
@lakhujanivijay Hi, sorry for the late response. For this issue: it is not an external link, just redirect to the other section([gene panel data](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#gene-panels-for-mutation-data)). Thanks for pointing out another broken redirection, looking at it.
