### ISSUE TITLE
 enhance methylation data visualization

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#5966]
Current POETIC study separates gene promoter and gene body measurements as two separate data sets. In POETIC, these are both measured by WGSBS and array. 

- [x] Consider new colour scheme to make methylation data distinct from copy number data (keep red/blue for copy number, use orange/green for unmethylated/methylated). Taken from http://colorbrewer2.org diverging 4-colour spectral scheme:
![Screen Shot 2019-04-13 at 10 00 09 AM](https://user-images.githubusercontent.com/17375786/56080741-f5ced900-5dd2-11e9-8f80-7fa0766d6c11.png)
- [ ] Docs need to be updated to support this: https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#meta-file-7

**Comment by khzhu** [comment]
![Image from iOS](https://user-images.githubusercontent.com/17375786/56080954-755da780-5dd5-11e9-805f-1682be7aa65e.png)

**Comment by jjgao** [comment]
adding @schultzn @ao508

**Comment by khzhu** [comment]
Trevor mentioned Niki has a R script that can be used to classify three methylation groups: promoters, gene bodies, other. Would @schultzn or @ao508 please share it with us?
I've adjusted the importer script to load three types of methylation data, and enhanced methylation data visualization (please see attached).
![Screen Shot 2019-04-14 at 5 52 17 PM](https://user-images.githubusercontent.com/17375786/56159262-3aed3980-5f92-11e9-84d9-d2b601d5cf34.png)

**Comment by schultzn** [comment]
We don’t have a script to separate the probes - we revived the separated data from a collaborator.
