### ISSUE TITLE
Validation '@AssertTrue' not working on api's on rc branch

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#5967]
Example

```curl -X POST "http://test.cbioportal.org/rc/api/clinical-attributes/counts/fetch" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"sampleIdentifiers\": [ { \"sampleId\": \"TCGA-OR-A5J3-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J4-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J5-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J6-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J2-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J9-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J7-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J8-01\", \"studyId\": \"acc_tcga\" } ], \"sampleListId\": \"acc_tcga_sequenced\"}"```

should throw 400 error. but instead its returning results

Seems like an issue wherever `@AssertTrue` is used

**Comment by sheridancbio** [comment]
Could you explain more about this @kalletlak ?  Is the filter argument that is being passed up invalid? Where is the error?

**Comment by kalletlak** [comment]
@sheridancbio main error is validations are skipped.
Example, in main instance
```curl -X POST "https://www.cbioportal.org/api/clinical-attributes/counts/fetch" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"sampleIdentifiers\": [ { \"sampleId\": \"TCGA-OR-A5J3-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J4-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J5-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J6-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J2-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J9-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J7-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J8-01\", \"studyId\": \"acc_tcga\" } ], \"sampleListId\": \"acc_tcga_sequenced\"}"```

throws `{"message":"eitherSampleListIdOrSampleIdsPresent must be true"}` which is expected and correct

but if you try to query 
```curl -X POST "http://test.cbioportal.org/rc/api/clinical-attributes/counts/fetch" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"sampleIdentifiers\": [ { \"sampleId\": \"TCGA-OR-A5J3-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J4-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J5-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J6-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J2-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J9-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J7-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J8-01\", \"studyId\": \"acc_tcga\" } ], \"sampleListId\": \"acc_tcga_sequenced\"}"```
or
```curl -X POST "http://test.cbioportal.org/beta/api/clinical-attributes/counts/fetch" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"sampleIdentifiers\": [ { \"sampleId\": \"TCGA-OR-A5J3-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J4-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J5-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J6-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J2-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J9-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J7-01\", \"studyId\": \"acc_tcga\" }, { \"sampleId\": \"TCGA-OR-A5J8-01\", \"studyId\": \"acc_tcga\" } ], \"sampleListId\": \"acc_tcga_sequenced\"}"```

returns result instead of error message
