### ISSUE TITLE
Compress bar charts (vertically) to optimize for 13inch lap screen

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#5970]
![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/e3296e41-e62c-4ae7-9c63-0e3c2ce03aab)

I think this may be true for all of our bar charts, but it does seem like we waste a lot of space vertically.

**Comment by adamabeshouse** [comment]
paging @kalletlak who wrote this component

**Comment by coderrsid** [comment]
Can you provide me direct link for the above query i wanna test it myself. maybe i'll be able to fix this issue.

**Comment by kalletlak** [comment]
@coderrsid thanks, but the vertical height of bars is already fixed. anyways here is link http://test.cbioportal.org/rc/comparison/clinical?sessionId=5cb76053e4b0ab4137873e7d, you might not see the changes as the latest code needs to be deployed yet.

This is how it looks
<img width="1671" alt="Screen Shot 2019-04-17 at 1 34 44 PM" src="https://user-images.githubusercontent.com/12956870/56308735-fbe7f100-6115-11e9-9db9-288ae361523d.png">

**Comment by kalletlak** [comment]
@adamabeshouse @alisman I think there is still a problem with vertical height of the table because of the clinical attribute name which gets wrapped if its too long. should we worry about it?

**Comment by adamabeshouse** [comment]
We could shorten it with `...` and show full title on tooltip. Thoughts @jjgao @schultzn ?

**Comment by alisman** [comment]
@kalletlak i don't think the table height needs to be constrained.  i mean, it would be nice to truncate them (with shortcut) but what do you mean "problem" with vertical height?

**Comment by adamabeshouse** [comment]
@alisman the problem is we'd like the page to fit on a 13" screen

**Comment by schultzn** [comment]
The table can probably be longer -  but the graph should fit.
