### ISSUE TITLE
wrong order of portal.properties in web application context files

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#5982]
The order should be 
```
                <value>classpath:portal.properties</value>
                <value>file:///${PORTAL_HOME}/portal.properties</value>
```
but is now the other way around in files like `applicationContext-web.xml`. See
https://github.com/cBioPortal/cbioportal/blob/master/web/src/main/resources/applicationContext-web.xml#L21

I.e. the classpath entry should be the default one, since this is the one built here https://github.com/cBioPortal/cbioportal/blob/master/pom.xml#L101
(`          <!-- copy portal.properties.EXAMPLE and log4j.properties.EXAMPLE if they don't exist -->`)
The entry `<value>file:///${PORTAL_HOME}/portal.properties</value>` can then be used to overwrite default properties at runtime.

Expected solution: removal of the portal.properties entries in these context xml files (where possible), or change of inclusion order. Example of PRs and places where the correct order is already followed:
- https://github.com/cBioPortal/cbioportal/pull/4917/files#diff-21441032f087e541ccd00007d827e66eR21
- https://github.com/cBioPortal/cbioportal/pull/4787/files#diff-634267913d77530c3faabaa8c50a846fR20
- https://github.com/cBioPortal/cbioportal/pull/4787/files#diff-634267913d77530c3faabaa8c50a846fR20

**Comment by pieterlukasse** [comment]
notify @inodb, @fedde-s

**Comment by fedde-s** [comment]
There may be two more issues with these lines of code:
- other parts of the portal do not look at the portal.properties file compiled into the classpath at all if `$PORTAL_HOME/portal.properties` exists at runtime: they would use the defaults listed in the code if a property is not listed in the runtime configuration file, even if another value happens to be listed in the build-time portal.properties file
- I don't think the placeholder `${PORTAL_HOME}` is replaced by its runtime value here in the first place, as this is one of the bean constructor arguments of the class responsible for replacing such placeholders.

**Comment by pieterlukasse** [comment]
@fedde-s right, so `file:///${PORTAL_HOME}/portal.properties` should be `file:///#{systemEnvironment['PORTAL_HOME']}/portal.properties` in files such as `applicationContext-web.xml`

Regarding the classpath ("default") one: thinking more about it, I actually think we should try to get rid of this. In other words: a runtime portal.properties should be mandatory, and there should be _no_ default file based on portal.properties.EXAMPLE backed in by maven. Wondering what @inodb thinks of this approach. @inodb ?
