### ISSUE TITLE
Tutorials are (sometimes) not accessible behind corporate firewalls

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5989]
Tutorials are now in google drive, and this is (sometimes) not accessible behind corporate firewalls. Would be great if a download link can be provided next to the iframes that now host the google docs.

cc: @pieterlukasse

**Comment by pieterlukasse** [comment]
👍

**Comment by nabeelmerchant1** [comment]
@tmazor Just a very minor fix. Click here should be underlined.

![image](https://user-images.githubusercontent.com/40885903/56841321-82cf6300-68a6-11e9-8345-25915b875744.png)

**Comment by tmazor** [comment]
@inodb @alisman I've just uploaded PDFs to GitHub. Could one of you update the tutorial page to link to those?

**Comment by alisman** [comment]
https://github.com/cBioPortal/cbioportal/issues/6333
will do
