### ISSUE TITLE
Keep scroll position when switching tab on results page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#5998]
As reported by @schultzn : 

When on small screen and clicking on a tab the page scrolls to the tab. Would be better to keep the scroll position

**Comment by coderrsid** [comment]
@inodb how smaller screen are you talking about? Can you give us an example through a video or gif or ss?

**Comment by neelesh17** [comment]
Is this issue still open?And if it is could i work on it.

**Comment by alisman** [comment]
@neelesh17 it seems this has been fixed already.  thanks very much for your offer
