### ISSUE TITLE
Cohort comparison: Frequencies of mutated genes and copy-number altered genes

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5999]
The frequencies for mutated genes and copy-number altered genes seems are no longer calculated correctly, they all show up as <0.1%

![image](https://user-images.githubusercontent.com/11892704/56526029-c7ab7080-6519-11e9-8a0b-7ac0f58a4eec.png)

**Comment by kalletlak** [comment]
should be fixed once backend is redeployed to latest code

**Comment by kalletlak** [comment]
fixed after redeploying
