### ISSUE TITLE
Predefined study selection does not work on Firefox

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6]
If you click on one of the predefined study selections, such as "tcga" on http://www.cbioportal.org/
you get a popup with [object Object] in firefox 37.0.2. No problems in in chrome, neither in safari.

**Comment by adamabeshouse** [comment]
The problem was doing <a href='javascript:X'>..</a>
Solved by doing, instead, <a href='javascript:void(0)' onclick='X'>...</a>
