### ISSUE TITLE
Cohort comparison: axis label cut off

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6002]
http://test.cbioportal.org/beta/comparison/clinical?sessionId=5cbe1704e4b0ab4137873e8b

![image](https://user-images.githubusercontent.com/11892704/56529629-0c85d600-651f-11e9-943e-ae6f7ce550c5.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2243
