### ISSUE TITLE
New tracking for file download

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6003]
We want to track the # of times data is downloaded for a given study.  It could be downloaded in different places on the site.  Come up with a good plan to track this with google analytics.  Could be backend or frontend!

This is a sub issue:
https://github.com/cBioPortal/cbioportal/issues/5953

**Comment by nabeelmerchant1** [comment]
1.For the backed a new database tab could be created for all studies which would track each time the download button is clicked. When button is clicked you can increment the counter and serve the file.

2.  Either way we could also use google analytics

Another suggestion could be to also track the number of time a study or genes have been viewed.

Example : <a href="http://www.example.com/files/map.pdf" onClick="javascript: _gaq.push(['_trackPageview', '/downloads/map']);">

**Comment by dippindots** [comment]
Close since it has been solved by pr#2245.
