### ISSUE TITLE
MKSTabs anchor elements should have href defined to allow open in new tab

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6004]
When you right click the nav tabs:
![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/8014301c-1cfa-403b-8919-3bc8b4ade12c)

we should be able to open them in a new window.  Look into setting href attribute on them to allow for this.

**Comment by coderrsid** [comment]
@alisman. Can i work on this?

**Comment by dippindots** [comment]
@coderrsid Yes, thanks for your help! You can find the related code in MSKTabs.tsx.

**Comment by coderrsid** [comment]
Sure.

**Comment by nabeelmerchant1** [comment]
We might kill 2 birds with one stone with an alternative option

1.New window tab in to enable JSReact for Navigation Tabs

Example: 
<td onClick={()=> window.open("someLink", "_blank")}>text</td>

and

1. A regular link can be used to be styled as a cell for study data

Example :
<a style={{display: "table-cell"}} href="someLink" target="_blank">text</a>

**Comment by dippindots** [comment]
Hi @coderrsid, any news for this ticket? Are you still working on it?

**Comment by alisman** [comment]
@adamabeshouse i think we have to introduce a mode for this in which tabId is appended to url.  let me know your thoughts
