### ISSUE TITLE
Evaluate session service architecture

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6005]
With session service becoming more and more an integral part of cBioPortal, we should re-evaluate its architecture.

Questions to answer:

- Should we combine session service with cbioportal repo?
  - is there any performance benefit to having sessions in the mysql database versus pulling sample lists from session service and then querying them in the mysql database? 
  - do cbioportal maintainers find it more complicate to install both mysql and mongo database?
  - why did we choose the current design?
- What is the scope of session service? The name implies it stores sessions, but it's storing both sessions and user data like virtual studies, groups, study view customizations.
- Should session service by a requirement for running cBioPortal?
  - maybe localStorage goes a long way?
- How do we test the system?

CC: @mandawilson @n1zea144 @kalletlak @alisman @adamabeshouse

**Comment by adamabeshouse** [comment]
From a development POV of a session service consumer, I think it's better to require session service because otherwise we would have to maintain two parallel systems: using session service, and using localStorage.

**Comment by jjgao** [comment]
> Should we combine session service with cbioportal repo?

It may be a good idea to do that ultimately, but definitely not this round v3.0.0. We should evaluate the options.

> What is the scope of session service?

see https://github.com/cBioPortal/cbioportal/issues/5771

> Should session service by a requirement for running cBioPortal?

Agreed and we have decided to make sessions service a requirement https://github.com/cBioPortal/cbioportal/issues/5773. 

We also decide not to use local storage b/c user data cannot be maintained between computers.

> How do we test the system?

??

**Comment by inodb** [comment]
Thanks @jjgao ! 

Regarding testing session service. We currently have no tests of session service standalone. I made an issue of what I think should be doable:

https://github.com/cBioPortal/session-service/issues/23

There's also a known issue with testing review apps. You could still use the localStorage trick to test, but one can't use the review app directly to log in. Maybe not that big of a deal

**Comment by jjgao** [comment]
@inodb I am going to close this one. Please create separate issues if still relevant, e.g. testing.
