### ISSUE TITLE
Cohort comparison: Clinical data error message for overlapping samples

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6009]
The current error message is: "We can only show clinical plots when groups have overlapping samples. Please exclude them by changing dropdown option to 'Exclude overlapping samples'"

We should change this to:
"We can only show clinical plots when groups do not have overlapping samples. Please exclude them by selecting 'Exclude overlapping samples' in the dropdown menu above."

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2254/files

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2243
