### ISSUE TITLE
Cohort comparison: Survival analysis should not show up when there are overlapping patients

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6010]
Survival analysis should not show up when there are overlapping patients - we should have an error message similar to the one from the clinical data tab.

**Comment by kalletlak** [comment]
@schultzn @adamabeshouse @alisman @jjgao we do not have `exclude overlapping patients` in the dropdown. should we add it as a new option or change `exclude overlapping samples` to  `exclude overlapping samples and patients`

**Comment by schultzn** [comment]
I think you can just change it to:
exclude overlapping samples and patients

**Comment by kalletlak** [comment]
@schultzn if we exclude overlapping patients, then samples with same patient in different groups will be excluded. do we want that?

**Comment by schultzn** [comment]
Good question. Probably not. Maybe exclude the patients in the clinical and survival tab but keep the samples in the genomic comparisons?

**Comment by dippindots** [comment]
@schultzn After discussed with @kalletlak , we proposed to do the following things:

1. keep the option text: `exclude overlapping samples`
2. add a warning on survival and clinical tab to inform that the overlapping patients are excluded by default
3. change the data fetching method only for these two tabs

is that ok?

**Comment by adamabeshouse** [comment]
@dippindots @kalletlak It definitely makes sense to me to just exclude and show a warning message considering the plot is not even possible when there is not exclusion. So I think it's a great decision.

**Comment by schultzn** [comment]
Sounds good! Thanks.
