### ISSUE TITLE
Revisit loader positioning 

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6011]
On a 13 screen, for Impact, the loader appears near bottom of screen

**Comment by adamabeshouse** [comment]
You mean for oncoprint right?

**Comment by alisman** [comment]
yes.  lets discuss monday

**Comment by adamabeshouse** [comment]
can we close this? @alisman

**Comment by jjgao** [comment]
It seems fine to me... @alisman  please reopen if it is still a problem.
