### ISSUE TITLE
Standalone Installer for cBioPortal and other MSKCC Projects 

### ISSUE THREAD

**Issue by nabeelmerchant1** [cBioPortal/cbioportal#6013]
**Feature Title**: Standalone Installer 

**Problem :** 
Several potential users and contributors of cBioPortal, OncoKB & Genome Nexus are facing numerous problems in creating/deploying a local instance for several mskcc projects and their components into their machine/Operating Systems.  

It can take several days for new/experienced users and contributors to read through and install the several software packages required in the documentation and FAQs to deploy, contribute and extract data for projects . 

**Solution**
Creating a standalone installer can considerably  bring down the time taken to deploy and contribute to mskcc projects for users and developers.

_Operating Systems : Windows, OSX, Linux, Unix other operating systems._

![image](https://user-images.githubusercontent.com/40885903/56664642-e0568a80-66c1-11e9-8f87-c8cb2e74aa31.png)

**Approach** : ( to be further elaborated )

Possible collaborators : @inodb, @zhx828, @jjgao

**Comment by jjgao** [comment]
I am not sure about this. Maybe we should just improve our documentation and simplify the deployment process?

**Comment by nabeelmerchant1** [comment]
@jjgao Ino had also suggested the same. Currently implementing  a plan to simplify the documentation and deployment procedure.
