### ISSUE TITLE
SV: Cancer Studies chart not showing correctly

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#6014]
1. Cancer Studies Chart showing as pie chart by default even if it has more than 20 values. example https://www.cbioportal.org/study?id=chol_msk_2018%2Cchol_nccs_2013%2Cchol_nus_2012%2Cchol_tcga%2Cgbc_msk_2018%2Cgbc_shanghai_2014%2Cchol_jhu_2013%2Cblca_mskcc_solit_2014%2Cblca_mskcc_solit_2012%2Cblca_plasmacytoid_mskcc_2016%2Cblca_tcga_pub_2017%2Cblca_bgi%2Cblca_dfarber_mskcc_2014%2Cblca_tcga%2Cblca_nmibc_2017%2Cutuc_mskcc_2015%2Cblca_cornell_2016%2Ccoadread_dfci_2016%2Ccoadread_genentech%2Ccoadread_tcga%2Ccoadread_mskcc%2Ccrc_msk_2017
![Screen Shot 2019-04-24 at 1 11 22 PM](https://user-images.githubusercontent.com/12956870/56679221-8d191380-6692-11e9-8a3c-883c2c85a89a.png)
2. Then when converting this chart to table, dimensions are not getting updated
![Screen Shot 2019-04-24 at 1 14 05 PM](https://user-images.githubusercontent.com/12956870/56679352-db2e1700-6692-11e9-8240-4e53a71d02d4.png)

3. Next when other charts are filtered its somehow converted back to pie chart

4. Next if you delete a chart then the dimensions of the pie chart are updated, same as table
![Screen Shot 2019-04-24 at 1 18 09 PM](https://user-images.githubusercontent.com/12956870/56679643-9060cf00-6693-11e9-982a-35a9f0d47b8c.png)

**Comment by nabeelmerchant1** [comment]
All the pie charts have problems related to this similar nature.

![image](https://user-images.githubusercontent.com/40885903/56699402-b5465800-670e-11e9-8888-2a4702c10393.png)

**Comment by nabeelmerchant1** [comment]
Most of the other pie chart studies have a problem similar to this nature.

![image](https://user-images.githubusercontent.com/40885903/56700462-c9d91f00-6713-11e9-98c1-83be9727cbcf.png)

**Comment by kalletlak** [comment]
@nabeelmerchant1 not sure what you are pointing exactly at. do you count(number) on the slices?

**Comment by nabeelmerchant1** [comment]
@kalletlak I have noticed the React Pie Charts with Index / Data Labels placed Inside are not showing properly. The values do show when you place the cursor over the color coded segments.

**Comment by kalletlak** [comment]
@nabeelmerchant1 looks like a different bug. Feel free to create a new ticket when you are done documenting. Closing this ticket for now. Thanks!
