### ISSUE TITLE
3d structure of tp53 not showing up

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6016]
Might be a problem with multiple genes

**Comment by jjgao** [comment]
@onursumer any update?

**Comment by onursumer** [comment]
@jjgao @inodb Looks like we rank `5XZC` as the highest PDB structure to load. However, 3Dmol cannot download any structure for this PDB: http://3dmol.csb.pitt.edu/viewer.html?pdb=5XZC.

**Comment by onursumer** [comment]
NGL has no problem loading it: https://www.rcsb.org/3d-view/5XZC/1, maybe we should switch to NGL :)

**Comment by onursumer** [comment]
Opened a ticket at 3dmol.js issue tracker: https://github.com/3dmol/3Dmol.js/issues/415

**Comment by inodb** [comment]
@onursumer 

- might be an option. Im not too familiar with either. If the general consensus is that NGL works better these days it could be worth switching. Does seem like it could potentially cause other issues
- how does the current ranking of PDB structures work? What is it based on?

**Comment by onursumer** [comment]
@inodb ranking is based on the `identity` value and the alignment length returned by `g2s` service. Here you can find the full sort metric: https://github.com/cBioPortal/cbioportal-frontend/blob/9c5b2e874d5d08a9a46a10521c2b5d8918dea6d8/src/shared/components/mutationMapper/MutationMapperStore.ts#L371

**Comment by inodb** [comment]
@onursumer Thanks! If there's no quick response to the 3d mol issue tracker bug: maybe a temporary fix could be to have a list of ignored structures?

**Comment by onursumer** [comment]
@inodb that may work, but detecting empty structures might be tricky/hacky. The only indication is this webGL warning message in the console: `[.WebGL-0x3c66aae86000]RENDER WARNING: Render count or primcount is 0.`

**Comment by inodb** [comment]
@onursumer good point - i thought maybe we only hardcode the TP53 structure 5XZC. Then add more if any other broken ones are reported. Until we find a proper fix. But yeah let's see if it's an easy fix on their end
