### ISSUE TITLE
How to define altered only samples with alterations in all query genes

### ISSUE THREAD

**Issue by fbrundu** [cBioPortal/cbioportal#6018]
Hi all,
I'd like to query multiple genes and plot survival between two sets of samples:
1. The samples with alterations in each one of the queried genes
2. The remaining samples

At the moment, the survival curve is computed between the set of samples with at least one query gene mutated and the remaining samples. Is there a way to obtain the former or more complex behaviors?

Thanks

**Comment by nabeelmerchant1** [comment]
@fbrundu Are you perhaps looking for something like this

![image](https://user-images.githubusercontent.com/40885903/56746050-e49fa800-6794-11e9-8282-2412b456c3bb.png)

**Comment by fbrundu** [comment]
@nabeelmerchant1 actually, this should be the current behavior. In this case the red line contains samples with at least one query gene altered. I would like the red line to have only samples with one alteration in ALL query genes (more strict subset).

**Comment by nabeelmerchant1** [comment]
This process is quite simple. 

You could use the oco query language to custom create the particular survival chart here https://www.cbioportal.org/oql  - on OQL modifiers. 

1. On the main cBioPortal webpage : https://www.cbioportal.org ( on the **select studies** panel - you should select the relevant studies which includes your targeted gene set )

2.  After selecting  your study you should notice  a drop down menu for query open up if you scroll down. 

3. You could then view the user defined list of genes, copy and paste the relevant genes that pop up .

4. After copy and pasting your gene hit the submit query button.

**Comment by nabeelmerchant1** [comment]
@fbrundu Please let us know if this has resolved your problem.

**Comment by fbrundu** [comment]
@nabeelmerchant1 
Thanks.
No, the problem is different: I am able to produce plots with at least one gene altered vs no alteration. My objective is to compare samples with alterations ON EACH query gene vs samples with no alterations, or a smaller subset of query genes altered.

**Comment by tmazor** [comment]
Hi @fbrundu - Great question! However, this GitHub repo is really meant for technical issues. We prefer to answer questions like this through our google group, so that the answer can be a resource for future users searching those archives. Would you mind sending this question there (cbioportal@googlegroups.com) and I'll help you to do this through that forum.
