### ISSUE TITLE
cgdsr R package failed some unit tests

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#6019]
I am trying to using the cgdsr package but am getting the following error when I test the CGDS endpoint:
> test(mycgds)
getCancerStudies...  OK
getCaseLists (1/2) ...  OK
getCaseLists (2/2) ...  OK
getGeneticProfiles (1/2) ...  OK
getGeneticProfiles (2/2) ...  OK
getClinicalData (1/1) ...  FAILED!
getProfileData (1/6) ...  FAILED!
getProfileData (2/6) ...  FAILED!
getProfileData (3/6) ...  FAILED!
getProfileData (4/6) ...  FAILED!
getProfileData (5/6) ...  OK
getProfileData (6/6) ...  OK

**Comment by nabeelmerchant1** [comment]
Does this occur after executing this command ?

setRepositories(ind=1:6)
options(repos="http://cran.rstudio.com/")
if(!require(devtools)) { install.packages("devtools") }
library(devtools) 

install_github("cBioPortal/cgdsr")

**Comment by kvaldez** [comment]
Yes, the error occurs with the github version as well.

**Comment by nabeelmerchant1** [comment]
Please let us know which command did you use to retrieve cgdsr package.

**Comment by kvaldez** [comment]
Sure thing, I used 

`mycgds = CGDS("http://www.cbioportal.org/")
test(mycgds)`

**Comment by nabeelmerchant1** [comment]
@khzhu Is your R Version 2.12 or higher ?

**Comment by khzhu** [comment]
Here is my R version.
> version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.3                         
year           2019                        
month          03                          
day            11                          
svn rev        76217                       
language       R                           
version.string R version 3.5.3 (2019-03-11)
nickname       Great Truth

**Comment by khzhu** [comment]
which version were you using, @kvaldez ?

**Comment by kvaldez** [comment]
> version
>                _                           
> platform       x86_64-apple-darwin15.6.0   
> arch           x86_64                      
> os             darwin15.6.0                
> system         x86_64, darwin15.6.0        
> status                                     
> major          3                           
> minor          5.1                         
> year           2018                        
> month          07                          
> day            02                          
> svn rev        74947                       
> language       R                           
> version.string R version 3.5.1 (2018-07-02)
> nickname       Feather Spray

**Comment by nabeelmerchant1** [comment]
@ritikakundra I guess we are facing some server side issues.
