### ISSUE TITLE
Cohort comparison: End axis in stacked bar charts at 100%

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6020]
Can the axis end at 100% in stacked bar chart? We currently show the last tick there but extend the axis a little further.

![image](https://user-images.githubusercontent.com/11892704/56805539-5e687d80-67f7-11e9-8971-065fdc889f03.png)

**Comment by dippindots** [comment]
@schultzn Just want to confirm that do we want all stacked bar chart stop at the end of the axis? Or we just want to do this for the percent stacked bar chart. Thanks!

**Comment by alisman** [comment]
@schultzn @dippindots i guess with absolute values, you might want to end on a tick value?  But that would usually require padding that axis.

**Comment by schultzn** [comment]
Agree with @alisman
