### ISSUE TITLE
Cohort comparison: Divide axes of volcano and scatter plots

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6023]
We need to add gaps (or padding) below the zeros of the axes to avoid having dots on the actual axis. 

![image](https://user-images.githubusercontent.com/11892704/56836750-2177a780-6846-11e9-9c3f-884061595711.png)

We have it implemented on the Plots tab:
![image](https://user-images.githubusercontent.com/11892704/56836871-803d2100-6846-11e9-9550-076b549f73e2.png)

**Comment by alisman** [comment]
@adamabeshouse did you handle this?

**Comment by adamabeshouse** [comment]
no Ive been putting it off because I gave it a shot and it's one of those situations where victory just makes things way harder than they need to be
