### ISSUE TITLE
Save group feature is not clear

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6024]
I am trying to create a group consisting of overlapping patients... 

The first step is intuitive, but I am not sure what the second step (save) is supposed to do.

Also, my saved group does not get saved as a group when I go back to the study view - that would be desirable (users could use the venn diagrams to identify and save interesting groups and then use them in subsequent queries from the study view).

**Comment by adamabeshouse** [comment]
The idea is that the original session (i.e. the URL/session id) remains unchanged when you create these groups. When you click save, then it creates a new session which includes these new groups. I guess that's not useful/intuitive?

We can allow saving the group back to the study view but it will require them to be logged in. I guess there's not really an issue with that.

**Comment by jjgao** [comment]
I think it's a good idea to save back to the study view when the user is logged in.

The second step (save states) is new to our web site. We will have the same need when saving states in results page. If it's not intuitive, we should try to find a better way to do it.

**Comment by adamabeshouse** [comment]
we had a long conversation about it yesterday and decided that among all the conflicting needs the current solution is good, except with maybe more explanatory UI for the buttons. and for saving back to study we were going to add a checkbox for that in the "Create Group" box

**Comment by jjgao** [comment]
@adamabeshouse sounds good.
