### ISSUE TITLE
group comparison testing

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#6025]
screenshots/e2e
- [x] Overlap tab
   - [x] venn diagram @dippindots  
   - [x] upset @kalletlak 
   - [x] upset create group, use venn tests as template @adamabeshouse 
- [x] Clinical data @kalletlak 
- [x] Survival @kalletlak 
- [x] Enrichments @adamabeshouse 
  - [x] Gene selection and bar chart e2e test @kalletlak 

unit
- [x] OverlapUtils  @adamabeshouse 
- [x] GroupComparisonUtils @adamabeshouse 
- [x] overlapComputations @adamabeshouse 
- [x] quartiles @adamabeshouse

**Comment by adamabeshouse** [comment]
unit tests done here https://github.com/cBioPortal/cbioportal-frontend/pull/2309

**Comment by paulcwvandijk** [comment]
When selecting studies with overlapping patient+sample IDs I would expect this to be shown in the Venn diagram. When doing this:
<img width="733" alt="TCGA studies with overlapping patients samples" src="https://user-images.githubusercontent.com/44695112/57623941-256b2f80-7591-11e9-8e83-0ec539d01322.png">

Creating groups:
<img width="380" alt="creating groups" src="https://user-images.githubusercontent.com/44695112/57623713-a0801600-7590-11e9-96a7-815f283fa5df.png">

This results in:
<img width="1046" alt="Venn overlapping but not overlapping" src="https://user-images.githubusercontent.com/44695112/57623756-b8f03080-7590-11e9-9591-72673c8c8cd9.png">

Is this intended behaviour or a bug?

**Comment by adamabeshouse** [comment]
I'll move this discussion to a new issue:

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2429

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2431

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2478
