### ISSUE TITLE
"Jump to the first selected cancer study" seems not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#603]
http://www.cbioportal.org/beta/

There is a JS error when clicking "Modify Query" -- not sure if related.

**Comment by JiaoJiao123** [comment]
Ok I will double check

**Comment by JiaoJiao123** [comment]
Hi JJ, could you try this link?
http://dashi-dev.cbio.mskcc.org:8080/Jiao_cbioportal/index.do
I tested it and it's working fine to me.
