### ISSUE TITLE
Charts above table in Mutations and Copy-Number tabs of group comparison

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6030]
Can we do something like this for mutations and CNA tabs? This would be similar to the Mutations tab in results. It would be nice if the charts change as a user searches the table below. We can later add the bar chart here as well.

Expression is trickier, since we only have one graph. We can think of adding additional graphs later.

![image](https://user-images.githubusercontent.com/11892704/56975605-29359580-6b3f-11e9-9eaa-eaac71d1d906.png)

**Comment by jjgao** [comment]
Once we have the bar plot as defined in #6030, we can have it as one of the plots too.
