### ISSUE TITLE
mutex doesn't respect gene panels

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6033]
As best I can tell, MutEx doesn't respect gene panels.

Take this example: http://bit.ly/2XXIA9M

In the OncoPrint we can see clearly that there are:
2 samples with ACVR1 alterations
4 samples with KRAS alterations that are also profiled for ACVR1
5 sample with KRAS alterations that are NOT profiled for ACVR1
5 samples without KRAS alterations that are NOT profiled for ACVR1

Click over to the MutEx tab. Here we say:
B not A = 9
Neither = 5

I don't think it's correct to include samples in this calculation that weren't profiled for one of these genes. I think that those numbers should be:
B not A = 4
Neither = 0

Right? Or am I misunderstanding something here? @schultzn @jjgao

**Comment by jjgao** [comment]
@tmazor I think you are right. We never considered gene panel when calculating mutex.

@dippindots it should be easy to fix. If the sample has no date for a gene in all queried profiles, the sample should be excluded when calculating pairs that include the gene.

**Comment by tmazor** [comment]
@jjgao @schultzn Actually, this is a much bigger issue: what about every other tab? At first glance, OncoPrint, Plots & Download might be the only tabs that acknowledge a sample as not profiled. For some tabs it may not matter (e.g. Mutations might be fine as is), but for many tabs this could significantly impact the analysis.

For example: http://bit.ly/2UVaVeI
- The cancer types summary alteration frequency ignores gene panels and include all samples in the denominator.
- The survival tabs includes not-profiled samples in the unaltered group. I assume the enrichments tab does also, although I haven't confirmed this.

This might require some larger discussion to determine all the places on the site where gene panels matter, but I think it's important that we consistently use gene panels across all tabs.

**Comment by jjgao** [comment]
@tmazor other tabs would be more difficult to do when querying 2 or more genes. Maybe we should add some warning to start?

**Comment by tmazor** [comment]
@jjgao agree! let's add a warning to the other tabs, and then let's think about how to deal with this for multi-gene queries. I'll make issues for both of those and leave this one as just a fix to MutEx.

**Comment by dippindots** [comment]
Hi @tmazor @jjgao I want to confirm that for the merged group oql, if we have some samples are not profiled in one gene but profiled in other genes, should we exclude these samples? In this sample [link](http://www.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=msk_impact_2017&case_ids=msk_impact_2017%3AP-0000192-T02-IM3%2Bmsk_impact_2017%3AP-0000766-T01-IM3%2Bmsk_impact_2017%3AP-0001824-T01-IM3%2Bmsk_impact_2017%3AP-0002143-T01-IM3%2Bmsk_impact_2017%3AP-0002213-T01-IM3%2Bmsk_impact_2017%3AP-0006583-T01-IM5%2Bmsk_impact_2017%3AP-0007426-T01-IM5%2Bmsk_impact_2017%3AP-0008182-T01-IM5%2Bmsk_impact_2017%3AP-0009596-T01-IM5%2Bmsk_impact_2017%3AP-0009611-T01-IM5%2Bmsk_impact_2017%3AP-0010761-T01-IM5%2Bmsk_impact_2017%3AP-0000114-T01-IM3%2Bmsk_impact_2017%3AP-0000114-T02-IM3%2Bmsk_impact_2017%3AP-0000127-T01-IM3%2Bmsk_impact_2017%3AP-0000127-T02-IM3%2Bmsk_impact_2017%3AP-0000147-T01-IM3&case_set_id=-1&data_priority=0&gene_list=%255B%2522TEST%2522%2520ACVR1%2520EGFR%255D%250AKRAS&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&tab_index=tab_visualize&show_samples=false&clinicallist=NUM_SAMPLES_PER_PATIENT), seems like oncoprint are not excluding these samples?

**Comment by jjgao** [comment]
@dippindots If the sample has no date for a gene in all queried profiles, the sample should be excluded when calculating pairs that include that gene. For example, in [this query](http://bit.ly/2ZTUNOv), only the first 6 samples will be used for calculating ACVR1-KRAS and ACVR1-EGFR, but all 14 samples will be used for calculating KRAS-EGFR.

![image](https://user-images.githubusercontent.com/840895/57153852-54b9b980-6da5-11e9-9803-c9ac9c13ada3.png)

**Comment by dippindots** [comment]
Thanks @jjgao! Yes, this is my implementation now, but for gene groups:  http://bit.ly/2VDxwkD. If you expand the `TEST` group, you can see some of the samples are not profiled, but for the whole group, the alteration rate is 2/14 which means we think all the samples are profiled. Should we follow the same rules for mutex?
![image](https://user-images.githubusercontent.com/15748980/57154604-52585f00-6da7-11e9-810e-e160eb90e0db.png)

**Comment by jjgao** [comment]
@dippindots yes, you can follow the same logic, ie. a sample should be excluded only if it's not profiled in all genes.

**Comment by alisman** [comment]
@tmazor could you test the fix here: https://cbioportal-frontend-pr-2288.herokuapp.com/

**Comment by tmazor** [comment]
Looks good overall, but I think we need to figure out how to deal with the scenario where no samples are profiled for one of the query genes, e.g. https://cbioportal-frontend-pr-2288.herokuapp.com/results/oncoprint?session_id=5d013db4e4b0ab413787508e

ACVR1 isn't profiled in any queried samples, but the MutEx page still runs a calculation:
![image](https://user-images.githubusercontent.com/10508276/59374757-8dd93800-8d1a-11e9-9ce2-75962d487711.png)

Instead the Log Odds / p-value / q-value / Tendency columns should probably be blank or have some sort of "samples not profiled for gene" message.

**Comment by alisman** [comment]
@tmazor @jjgao, while we're at it, seems like maybe we should even raise a flag if some percentage of samples are not profiled in a certain gene?   it seems wrong to treat any significant portion of samples that are not profiled as negative.

**Comment by jjgao** [comment]
@dippindots @tmazor: I think we should exclude genes that are not profiled in any samples. We can add a message: "ACVR1 is not profiled in any queried samples and therefore excluded in this analysis."

@alisman this issue is about excluding "not profiled" samples and not treat them as negative.

**Comment by tmazor** [comment]
@jjgao that sounds good to me

**Comment by dippindots** [comment]
@jjgao @tmazor Thanks for your comments, I will update this pr to add the warning message.

**Comment by dippindots** [comment]
@tmazor @jjgao This pr has been updated, could you help to test it one more time? Thanks! https://cbioportal-frontend-pr-2288.herokuapp.com/

**Comment by tmazor** [comment]
Look better @dippindots ! I found one edge case that isn't accounted for, and also I'd like to update the warning text:

If I run a query with two genes that are not profiled in any of the queried samples, clicking on the MutEx tab breaks the site. The page goes blank and this error appears in the console:
![image](https://user-images.githubusercontent.com/10508276/59456023-669a6d80-8de3-11e9-8970-7f8a60573909.png)
https://cbioportal-frontend-pr-2288.herokuapp.com/results/oncoprint?session_id=5d028ea1e4b0ab41378754a0


Also, please modify the warning text that appears when genes are not profiled:

One gene:
"[gene] is not profiled in any queried samples and therefore is excluded from this analysis."

Multiple genes:
"[gene], [gene] and [gene] are not profiled in any queried samples and therefore are excluded from this analysis."
