### ISSUE TITLE
The hyperlink to "Gene Panel Matrix file" under Fusion data is broken

### ISSUE THREAD

**Issue by lakhujanivijay** [cBioPortal/cbioportal#6035]
The hyperlink to "[Gene Panel Matrix file](https://github.com/cBioPortal/cbioportal/blob/master/docs/gene-panel-matrix-file)" under [Fusion data](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#gene-panels-for-fusion-data) is broken.

Similar Issue: https://github.com/cBioPortal/cbioportal/issues/5965

**Comment by dippindots** [comment]
Hi @lakhujanivijay, this link has been fixed to redirect to the right position "[Gene panel Matrix file](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#gene-panel-matrix-file)". If you have other questions regarding this, please let me know!
