### ISSUE TITLE
annotation tracks should download with lollipop plot

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6044]
If annotation tracks are added, and I download the lollipop plot, those tracks should be in the downloaded image also. Currently the downloaded image is just the lollipop plot.

**Comment by tmazor** [comment]
We should still do this

**Comment by inodb** [comment]
We should still do this

**Comment by adamabeshouse** [comment]
We *will* still do this 👊

**Comment by adamabeshouse** [comment]
@onursumer I think this might be better done by you because it could be involved with the details of your implementation of the annotation tracks, copying them into an svg at their positions

**Comment by Luke-Sikina** [comment]
From standup: always show expanded plot in PDF
