### ISSUE TITLE
add warning to results view tabs that don't respect gene panels

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6049]
Only some tabs on results view respect gene panels. We need to provide a warning to users on the tabs that don't.

The tabs that need warnings are:
Cancer Type Summary
Survival
Enrichments (I think?)

Tabs that respect gene panels are:
OncoPrint
MutEx (once #6033 is fixed)
Plots
Download
Co-expression

Tabs where I think it doesn't matter:
Mutations
CN Segments

@jjgao can you confirm my lists above?

The warning text could be:
The results below do not reflect gene panel data. Samples which were not profiled for the queried gene(s) are included in the analysis below.

We should only display this message when there are "not profiled" samples in any of the query genes.

**Comment by jjgao** [comment]
@tmazor Thanks for the list. I think co-expression should be moved to the last category. Others look good.

We should only display the message when there are "not profiled" samples in any of the query genes.

**Comment by adamabeshouse** [comment]
Co-expression definitely shows not profiled when youre displaying mutations

**Comment by jjgao** [comment]
@adamabeshouse that's true. Forgot about the plot in the coexp tab.

**Comment by tmazor** [comment]
Thanks @adamabeshouse! I will update the list.

**Comment by tmazor** [comment]
@jjgao agree about only showing this when it is relevant - I've added your comment to my original one ot keep everything together

**Comment by tmazor** [comment]
@jjgao can we prioritize this one? I think it's important to be clear about this.

**Comment by jjgao** [comment]
@tmazor prioritized :) @adamabeshouse please work on this soon.
