### ISSUE TITLE
plan to add gene panel to all results view tabs

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6051]
Currently only some tabs incorporate gene panel data (see #6049).

We need to come up with a plan for how to properly include gene panels on all other tabs (cancer type summary, survival & enrichments).

For a single gene query, I think there is a relatively simple solution: sample that were not profiled for that gene should be excluded from the analysis.

However, with queries for multiple genes this can get more complicated. My initial proposal would be to only include samples that are profiled for ALL queried genes. We could perhaps include a toggle to allow users to include all samples (or maybe all samples profiled for at least one queried gene?)

@cBioPortal/product what are your thoughts?

**Comment by Sjoerd-van-Hagen** [comment]
I think it makes sense. My only concern is that we cannot keep adding toggles and switches. I think at some point we need to have an advanced user mode that allows you to do things that are 'dangerous', while the 'normal' mode only allows things that are safe. In that mode you would always ignore samples that are not profiled.

**Comment by jjgao** [comment]
There are more tabs using gene panel data now, e.g. mutex and enrichments.

I like @tmazor's idea to add an option to exclude any samples that are not profiled in all query genes. Maybe we can add it to the global setting once that's implemented.

**Comment by jjgao** [comment]
Option to exclude samples is logged in https://github.com/cBioPortal/cbioportal/issues/7441. Closing this one.
