### ISSUE TITLE
Cannot find  skin.custom_header_tabs in portal.properties file.

### ISSUE THREAD

**Issue by lakhujanivijay** [cBioPortal/cbioportal#6052]
Hi

I want to add `Pathology Report` and `Tissue Image` tab into local cbioportal instance; just as shown [here](http://www.cbioportal.org/patient/pathologyReport?caseId=TCGA-D5-6530&studyId=coadread_tcga)

I looked at the [documentation](https://docs.cbioportal.org/2.3-customization/customizing-your-instance-of-cbioportal) and I can see that it is possible by modifying `portal.properties` file , however, I cannot find `skin.custom_header_tabs` in `portal.properties` file.

Should I add that manually? Can you please help?

Regards
Vijay

**Comment by jjgao** [comment]
I don't think the tabs in patient view are configurable. @alisman @inodb could you confirm?

@lakhujanivijay is this for your own local samples? Where are the path reports and tissue images stored?

**Comment by inodb** [comment]
@jjgao @lakhujanivijay This is is indeed not supported currently. The pathology report and tissue images are hardcoded for TCGA.

We are planning to allow adding any type of PDF to a patient in a specific "Files" tab which might work for your use case? Could you elaborate a bit on your use case? Thanks!

**Comment by lakhujanivijay** [comment]
Hi @inodb and @jjgao 

Thanks for your response. We wanted to add few documents associated with our samples. 

> adding any type of PDF to a patient in a specific "Files" tab
This should work for us. Is this has been already implemented?

**Comment by jjgao** [comment]
@lakhujanivijay not yet. We just supported link out to any URLs. Would that be helpful?
