### ISSUE TITLE
Simplify authentication documentation

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#6053]
Authentication documentation is currently unnecessarily complicated at
https://docs.cbioportal.org/2.2-authorization-and-authentication/authenticating-and-authorizing-users-via-keycloak#modifying-configuration
and 
https://docs.cbioportal.org/2.2-authorization-and-authentication/authenticating-and-authorizing-users-via-keycloak#doing-a-test-run
since it assumes the configuration still needs to be baked in by mvn step. 

It also relies on `-D` options being set in CATALINA_OPTS, while this should really be taken from portal.properties (perhaps a different issue).

Desired solution:
- remove mvn step from documentation
- test and document solution using `saml.idp.metadata.location=file:///client-tailored-saml-idp-metadata.xml` instead of `classpath:/client-tailored-saml-idp-metadata.xml`
- remove all `-D` parts (could be a separate PR)

**Comment by lakhujanivijay** [comment]
Thanks @pieterlukasse for that

**Comment by nabeelmerchant1** [comment]
@pieterlukasse We should ideally pass this to GSDOC

**Comment by pieterlukasse** [comment]
@nabeelmerchant1 did we get a GSDOC project?

**Comment by jjgao** [comment]
Our Google Season of Docs application was turned by Google, unfortunately.

**Comment by nabeelmerchant1** [comment]
@jjgao @pieterlukasse  Willing to work on this even though the organisation didn't get selected. I have put multiple proposals forward working on several documentation issues with MSKCC open projects. Will be updating my proposal to include this issue to.  Will be sending my proposal out shortly.
