### ISSUE TITLE
change oql text banner 

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6059]
1. ![Screen Shot 2020-06-22 at 3.40.38 PM.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/4044bb9c-2bf0-48ad-80c0-8812ad8c2fe9)

2. ![Screen Shot 2020-06-22 at 3.40.43 PM.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/0d2cf306-9f4f-4298-8ad0-f3ecdce1f129)

4. ![Screen Shot 2020-06-22 at 3.43.43 PM.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/0bbdb99c-1d22-4177-93b9-f873a2211a85)

5. ![Screen Shot 2020-06-22 at 3.43.50 PM.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/916560a1-7f18-4e61-8c45-cb7b4319cca7)

5. ![Screen Shot 2020-06-22 at 3.40.49 PM.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/023c9d69-99c1-4efe-a0eb-41f57f99bd18)

1+3. The results below are filtered by the OQL specification from your query
2+4. The results below **are not filtered** by the OQL specification from your query 
5. Your OQL specification does not affect the results below, because it includes all mutations in this gene.

See discussions on https://github.com/cBioPortal/cbioportal-frontend/pull/3286

**Comment by mrswagbhinav** [comment]
I want to help out. Did you want them to both be styled the same?

**Comment by inodb** [comment]
@mrswagbhinav 	yes that would be great !

**Comment by inodb** [comment]
still an issue

**Comment by inodb** [comment]
still a good first issue

**Comment by inodb** [comment]
Jag will look at this

**Comment by jagnathan** [comment]
Updated the message to reflect the new sentence. please see attached image.
<img width="943" alt="6059 - Updated text message" src="https://user-images.githubusercontent.com/37613906/86027309-8ad0e880-b9fe-11ea-941e-a6e056e630fb.png">
