### ISSUE TITLE
Most of the core tests are not working

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#606]
There seem to be quite some Exceptions raised in the latest master branch test https://travis-ci.org/cBioPortal/cbioportal/builds/95919781. Travis however still says the test was successful. Any idea @cataphract ?

**Comment by cataphract** [comment]
Apparently maven is still deeming the build successful. The most obvious cause would be something like `maven.test.failure.ignore` set to true. Maybe running maven with `-X` gives a clue.

**Comment by inodb** [comment]
Thanks for the reply. It is indeed because the failure results are ignored: https://github.com/cBioPortal/cbioportal/blob/master/core/pom.xml#L347. Basically the tests aren't working at all, so changing the title of this.

**Comment by ecerami** [comment]
@inodb:  is this still open, e.g. travis is reporting all green, but unit tests are failing?

**Comment by inodb** [comment]
@ecerami yup, the unit tests are still failing. The only test we currently have is the E2E test that takes a screenshot of the study view and the patient view.

**Comment by ecerami** [comment]
@inodb:  that's just crazy!  thought we had fixed this months ago.  am going to assign this to @ersinciftci as his first big task.

**Comment by inodb** [comment]
Great! Yeah it would be wonderful if we can get this fixed. Good luck @ersinciftci! As a side note, I've been told a bunch of the unit tests are pretty pointless. I'm guessing the data model has changed as well, so feel free to deprecate tests that are no longer useful. Ideally if you have the time, we would also be able to get some test coverage stats so we can get a better idea of what's untested. Maybe code climate https://docs.codeclimate.com/docs/setting-up-test-coverage or coveralls https://github.com/trautonen/coveralls-maven-plugin

**Comment by Sjoerd-van-Hagen** [comment]
If Maven is set to ignore the failed tests, they are also ignored by the CI. If you run the unit tests directly, say from your IDE, they will not be ignored and thus may fail.

What needs to be done is update the pom so the failed tests are not ignored. Failing tests can be labeled with @Ignore if necessary. They will then be ignored both by jUnit and Maven, and therefore also by Travis.

**Comment by morungos** [comment]
I've run JaCoCo for test coverage before, and I'm starting to backport some of my changes -- I can add this into the mix if anyone wants. It works OK, and JaCoCo is free and isn't dependent on external services. FYI, the coverage was around 20% when I last ran it

**Comment by inodb** [comment]
@morungos Yes :+1:, I think JaCoCo would be nice! Coveralls supports JaCoCo output format (https://github.com/trautonen/coveralls-maven-plugin), so we can still choose to use their CI service, without being locked into it

**Comment by morungos** [comment]
I've previously added JaCoCo to Maven in the tracker I built, the pom is at: https://github.com/pughlab/tracker/blob/develop/pom.xml for reference. That's a decent place to start.

**Comment by n1zea144** [comment]
If I recall, one fundamental problem was that we couldn't get transactions to work properly so that seeding/rollback between tests was not happening.  I think looking there is a good place to start.

**Comment by ersinciftci** [comment]
Solved.
