### ISSUE TITLE
Icon elements not showing in PlotsTab 

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#6069]
In rc branch there seems to be a problem with buttons/icons that use font awesome icons. The information hover-over icons for datasources are not showing in PlotsTab. Same for the download icon in the plots.

![Screenshot from 2019-05-08 09-21-00](https://user-images.githubusercontent.com/745885/57362935-2e6a9400-7180-11e9-9836-03dd929eb75a.png)

**Comment by alisman** [comment]
fixed by https://github.com/cBioPortal/cbioportal/pull/6055
