### ISSUE TITLE
Patient view e2e failure

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6079]
Please diagnose problem with this:

new sorted patient order correct - 1

https://circleci.com/gh/cBioPortal/cbioportal-frontend/35399

**Comment by dippindots** [comment]
@alisman This is a data related issue. Those oncoprint tests have been turned into screenshot tests in @adamabeshouse 's pr: https://github.com/cBioPortal/cbioportal-frontend/pull/2295. So that will be easier to debug.
