### ISSUE TITLE
Oncoprint issues

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#609]
- [x] fusions should be ordered before other mutations
![image](https://cloud.githubusercontent.com/assets/840895/11831311/7535a20c-a37b-11e5-932d-bf8e94dc9cbf.png)
 - [x] when "show all mutations with the same color," fusions should still show with different color and glyph
 - [x] treat "Targeted_Region" separately -- use the same color as in frame for now

**Comment by jjgao** [comment]
@schultzn should fusions ordered before or after mutations?

**Comment by schultzn** [comment]
I would put them before mutations.

**Comment by adamabeshouse** [comment]
Can you please elaborate on the desired behavior regarding 'Targeted_Region'?
