### ISSUE TITLE
MutationMapper not mapping for gene PLCG2

### ISSUE THREAD

**Issue by ao508** [cBioPortal/cbioportal#6090]
See cbioportal discussion here: https://groups.google.com/forum/#!topic/cbioportal/WrljLR2bMhM

**Comment by jjgao** [comment]
The user reported for PLCG2, MutationMapper tool was not able to show the mutation diagram for [their data]()(https://github.com/cBioPortal/cbioportal/files/3174448/Mutation_Mapper_Romain.xlsx).

After some digging we found that the canonical trascript ID (ENST00000564138) is only correct for [grch38](https://useast.ensembl.org/Homo_sapiens/Transcript/Summary?g=ENSG00000197943;r=16:81779291-81962685;t=ENST00000564138) but not for [grch37](https://grch37.ensembl.org/Homo_sapiens/Transcript/Summary?g=ENSG00000260682;r=16:81779291-81962685;t=ENST00000564138). Somehow, Ensembl use the same ID for two different genes.

We will need to change the canonical transcript ID to [ENST00000359376](http://grch37.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000197943;r=16:81772702-81991899;t=ENST00000359376) for grch37.

Ideally we want to keep the transcript ID of ENST00000564138 for grch38 if possible.

**Comment by inodb** [comment]
Mutation mapper part is fixed - but other issues of https://github.com/genome-nexus/genome-nexus/issues/272 still need to be addressed
