### ISSUE TITLE
issue when handling samples shared between studies

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#6096]
https://github.com/cBioPortal/cbioportal/issues/6025#issuecomment-491815688

![image](https://user-images.githubusercontent.com/636232/57649837-361ea400-7597-11e9-9475-ad0379becf1c.png)

this is a case we had not considered... we identify samples by study id + sample id. 

@jjgao @alisman please advise?

**Comment by jjgao** [comment]
We will not be able to handle this in this round since we are importing the samples in different studies as different samples. We have some plan to model study versions. We could do the venn diagram once we finish that.
