### ISSUE TITLE
Remove Cancer Study ID from Single Studies

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#6098]
Remove the cancer study ID column in the clinical tab (maybe from all tabs) from single studies since those are not helpful except in studies like a virtual cohort.

**Comment by jjgao** [comment]
![image](https://user-images.githubusercontent.com/840895/57730780-34241600-7667-11e9-954f-2eb20f5a9216.png)

**Comment by jjgao** [comment]
@zhx828 please prioritize this if it's easy.

**Comment by zhx828** [comment]
@ritikakundra @jjgao will do
