### ISSUE TITLE
-Ddat.method has no default value

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6099]
Running without adding `-Ddat.method` gives runtime error:

```
SEVERE: Exception sending context initialized event to listener instance]of class [org.springframework.web.context.ContextLoaderListener]
java.lang.IllegalArgumentException: Could not resolve placeholder 'dat.method' in value "${dat.method}"
```

**Comment by inodb** [comment]
Lol github doesn't understand `"needs to be fixed"` vs `"fixed"`

**Comment by ao508** [comment]
@n1zea144 @inodb when you ran this, did your properties contain `dat.method` with no value set for it or did `dat.method` not exist at all in your properties
