### ISSUE TITLE
Allow user uses custom selection for CN Segments tab

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6101]
Niki suggested to add this feature to allow filtering the segments

**Comment by jjgao** [comment]
That'd be a great feature. I am wondering if igv.js supports that. @onursumer

**Comment by zhx828** [comment]
@jjgao it's already supported. So if you select some samples in the summary tab and go to segments tab, it will only show selected samples info. I'm going to just enable the Custom Selection for Segments tab.

**Comment by jjgao** [comment]
ah, I misunderstood. I thought it was about select samples in the igv view -- that would be really cool.

**Comment by zhx828** [comment]
They might have the feature though lol @onur?
