### ISSUE TITLE
support mRNA and Protein tab with >2 groups

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6105]
Before we come up with some plot, we can display the table of results with the same table format as outlined here: https://github.com/cBioPortal/cbioportal/issues/5990#issuecomment-490094061

**Comment by alisman** [comment]
should we wait for optimization or finish and then optimize? talk to @n1zea144

**Comment by kalletlak** [comment]
@jjgao what should be the y for gene bar plot in mRNA and protein enrichment tabs

**Comment by jjgao** [comment]
per Slack discussion, we will not have a bar plot for mrnna and protein tabs.
