### ISSUE TITLE
missing gnomAD data

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6113]
BRCA1 E23Vfs*17 is a highly recurrent germline variant which is present in gnomAD (https://gnomad.broadinstitute.org/variant/17-41276044-ACT-A) but has no gnomAD frequency in this query:

https://cbioportal-frontend-pr-2064.herokuapp.com/results/mutations?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=ov_tcga_pub&case_set_id=ov_tcga_pub_cna_seq&data_priority=0&gene_list=BRCA1&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=ov_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ov_tcga_pub_mutations&tab_index=tab_visualize

**Comment by jjgao** [comment]
This is strange. Maybe after all, myvariantinfo won't work? @leexgh please investigate.

**Comment by leexgh** [comment]
@inodb i can't find it on myVariantInfo, could you check please?

**Comment by inodb** [comment]
@tmazor yikes - excellent catch.

It is in VEP:

http://grch37.rest.ensembl.org/vep/human/hgvs/chr17:g.41276045_41276046delCT?content-type=application/json

but not in myvariant.info:

http://myvariant.info/v1/variant/chr17:g.41276045_41276046delCT

@leexgh could you report to the myvariant.info issue tracker that this variant is missing from their gnomad data? Maybe it's an easy fix for them

https://github.com/biothings/myvariant.info/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by jjgao** [comment]
I am wondering if this is not just one of the many. Can we check all brca1 and brca2 variants in gnomad and see how many are missing i myvariant.info?

**Comment by leexgh** [comment]
I report the issue to myVariantInfo (https://github.com/biothings/myvariant.info/issues/75)

**Comment by tmazor** [comment]
I second @jjgao 's concern that this could be indicative of a large problem of missing data. Might be worth checking a few other genes also (in addition to BRCA1/2).

**Comment by leexgh** [comment]
@tmazor @jjgao @inodb the myVariantInfo team replays me with this:

Hi Xiang,

We have this variant in MyVariant.info. You could access it by: http://myvariant.info/v1/variant/chr17:g.41276045_41276046del. We normally remove the deleted nucleotides when representing a variant in HGVS id.

**Comment by jjgao** [comment]
Thanks, @leexgh. Let's use change it on our end when calling myvariant then. 

@leexgh @inodb : please make sure we code them correctly for other mutation types.

**Comment by leexgh** [comment]
@jjgao Sure I'm working on it

**Comment by jjgao** [comment]
@leexgh is this solved?

**Comment by leexgh** [comment]
@jjgao yes it's done, maybe we can close this issue?
