### ISSUE TITLE
Need info icon on Survival Analysis tab to indicate survival data source

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6115]
Next to "Overall Survival Kaplan-Meier Estimate", add an info icon which upon mouse-over shows the description of the OS_MONTHS (or OS_STATUS?) field, e.g. "Overall survival since time of diagnosis" or "Overall survival since time of sequencing".

Need the same for DFS.

![image](https://user-images.githubusercontent.com/11892704/57876987-af5f0680-77e4-11e9-9e3c-98007b000623.png)

**Comment by jjgao** [comment]
I don't think we are curating the information. @ritikakundra please correct me if I am wrong.

One option is to curate it in the description of OS_STATUS clinical attribute per study. @ritikakundra: can we do that?

Once the data is curated, we can make them into the frontend. @dippindots can probably help with that.

**Comment by ritikakundra** [comment]
@jjgao  @schultzn: most of our OS is from date of initial dx. But for some cases we might have PIs send us a different time 0. For public, we can go check publications for confirmation. 

We can add overrides for each study for OS_STATUS (hopefully there wont be many different timepoint 0s). Just need to find a better way of maintaining it.

**Comment by schultzn** [comment]
Can't we just use the description for OS_MONTHS? We can customize that whenever needed.

![image](https://user-images.githubusercontent.com/11892704/57948233-16e18880-78af-11e9-9f54-1593e9ae564c.png)

**Comment by ritikakundra** [comment]
@schultzn @n1zea144 : Ya i just updated os_montsh for impact to: Overall survival in months since date of sequencing. If patient died before sequencing overall survival in months is set to ‘0’. If patient is alive and last contact date is before date of sequencing, overall survival in months is set to ‘NA’

**Comment by jjgao** [comment]
@dippindots please help the frontend when you have a chance.

**Comment by dippindots** [comment]
@jjgao Ok! Will do soon.

**Comment by alisman** [comment]
@schultzn @jjgao in working on this we realized that in group comparison, there can be samples from multiple studies in the same curve.  When we fetch the meta data for the clinical data (survival time), we have to fetch for all studies.  We were going to list them all in this tooltip, but then it occured to us that if these are meaningfully different, doesn't it call into question the whole idea of putting them in the same chart?  Shouldn't we at least warn user that they might be comparing apples and oranges?

**Comment by schultzn** [comment]
Maybe that is a good idea. Maybe an info or alert icon somewhere that explains that the survival data on patients from different cohorts may have been defined by different criteria.

**Comment by alisman** [comment]
@schultzn so new plan is, when we detect more than one description (among descriptions for all represented studies) we show an alert message saying so.   Otherwise, we show the info icon? Could we just put the description text in the title?  Seems like it's important enough to warrant display without user interaction?

**Comment by schultzn** [comment]
Sounds good. We can maybe evolve that feature over time once we see all the use cases.

**Comment by alisman** [comment]
Gaofei, can you make the "differing criteria" a link tag with href="javascript:void(0)" so that it will appear link a link.  Thanks
![image](https://user-images.githubusercontent.com/186521/58964570-23a21f80-877d-11e9-9ed8-1d5d136c3073.png)

**Comment by jjgao** [comment]
@dippindots @alisman can this be closed?

**Comment by dippindots** [comment]
@jjgao Yes, it is merged and ok to close.
