### ISSUE TITLE
Orientation of vertical and horizontal axis labels in PlotsTab 

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#6119]
The change in orientation of the vertical and horizontal axis labels in PlotsTab does not improve readability nor aesthetic appeal. At least the 90deg. clock-wise rotation should be a 90deg. counter clock-wise rotation. It may also good to consider reverting to a horizontal orientation of the text.
![Screenshot from 2019-05-20 13-10-18](https://user-images.githubusercontent.com/745885/58017492-aaf65e80-7b00-11e9-8ff7-c283b0096a2a.png)

**Comment by jjgao** [comment]
I think I agree with @pvannierop. The current production looks better. Not sure when this change was merged into rc. Is it for reducing the height of the menu?


![image](https://user-images.githubusercontent.com/840895/58124119-70152900-7bdb-11e9-8729-54c457bd98aa.png)

**Comment by alisman** [comment]
This was specifically requested by @schultzn in order to condense the layout so that controls below could be seen on 13inch screen.   We all agree that the text should at least read bottom to top and it's possible that can be achieved.

**Comment by alisman** [comment]
@adamabeshouse lets hold off until we get agreement from everyone.

**Comment by schultzn** [comment]
Yes, it was an idea to save space, as the controls below the horizontal and vertical controls often fall below the fold. Was supposed to run bottom to top.
