### ISSUE TITLE
Mutations tab completely rerenders after table data load

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#6122]
https://www.cbioportal.org/results/mutations?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=msk_impact_2017&case_set_id=msk_impact_2017_cnaseq&clinicallist=NUM_SAMPLES_PER_PATIENT&data_priority=0&gene_list=TP53&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&show_samples=false&tab_index=tab_visualize

Initially the table displays "there are no results", and then the whole tab rerenders. Ideally only the table should rerender.

**Comment by jjgao** [comment]
this seems fixed.
