### ISSUE TITLE
"Color Sample By" section not placed correctly

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6127]
Move it under the legend.

https://beta.cbioportal.org/results/plots?session_id=5ba11ce6498eb8b3d567e7ed

![image](https://user-images.githubusercontent.com/840895/58124639-b28b3580-7bdc-11e9-85d2-12fcf29ef9b0.png)

**Comment by alisman** [comment]
@jjgao it's problematic to put it below legend b/c legend is of variable length.   this might fit at top of chart.  would that be alright?

**Comment by dippindots** [comment]
@jjgao Like what we did in the co-expression tab:
![image](https://user-images.githubusercontent.com/15748980/58133442-d2792400-7bf1-11e9-8aad-bba62fb428a0.png)

**Comment by jjgao** [comment]
That may work as long as we don't push the plots out of a 13" screen.
