### ISSUE TITLE
comparison gene barplot tweaks

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6129]
- [x] Remove x-axis label "Genes"
- [x] Add an way to allow user to specify the nubmer of genes to show, e.g.
- [x] Change the options to:
  - Genes with highest frequency in any group
  - Genes with highest average frequency
  - Genes with most significant p-values 
- [x] Show the current selection before "Select Genes" button so that one would know how the genes are selected
- [x] in comparison page when there are more than 2 groups, if showing 100 genes, the page is too wide -- it will be set to the width of the chart.

**Comment by alisman** [comment]
@jjgao @schultzn i think the gene # selector needs to be it's own UI element (not inside of dropdown).   like, next to dropdown.  what do you think?

**Comment by kalletlak** [comment]
true. it is hard to maintain sync between dropdown, number of genes and gene inputs box

**Comment by schultzn** [comment]
Not sure.

I just had another thought: It is confusing that you can make a selection and are then able to modify the gene list. Would it be better to have a fourth option: Custom Gene List?

**Comment by schultzn** [comment]
I see we have that.. sorry…

**Comment by jjgao** [comment]
@alisman agreed - gene # selector needs to be it's own UI element (not inside of dropdown)
