### ISSUE TITLE
handling gene panels for enrichments analysis

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6130]
- [x] Backend: for each row, only samples for which the gene is profiled should be included as the denominator
- [x] API: return the denominators for each group
- [x] Frontend: Visualize the denominators

**Comment by jjgao** [comment]
as discussed, profiled samples per gene should be used.

**Comment by adamabeshouse** [comment]
@jjgao what visualization do you have in mind for the denominators (by which you mean the number profiled, right?)

**Comment by jjgao** [comment]
We could use it in the tooltip of `(A)`, `(B)`, ... columns. Also it should be reflected in the Co-occurrence pattern, e.g. the NA cases can have a white background with a strikethrough just like oncoprint.

![image](https://user-images.githubusercontent.com/840895/64370573-b789be80-cfec-11e9-960d-89eca57f79a6.png)

**Comment by kalletlak** [comment]
@jjgao is this part of release-3.1.0?
and @adamabeshouse are you going to take care of frontend changes?

**Comment by adamabeshouse** [comment]
@kalletlak yes, just let me know when the API is merged

**Comment by kalletlak** [comment]
Frontend still needs to be implemented. @adamabeshouse API changes are merged.
