### ISSUE TITLE
New default for # of cancer types in Cancer Type Summary tab

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6132]
I propose to make the minimum # of cases 10 for the Cancer Type Summary tab. This should apply to Cancer Study, Cancer Type, and Cancer Type Detailed

![image](https://user-images.githubusercontent.com/11892704/58190262-1fa8d480-7c8a-11e9-8094-a95934bb4cad.png)

**Comment by dippindots** [comment]
@schultzn If the # of cases less than 10, do we want to show a warning alert rather than show those content?

**Comment by jjgao** [comment]
@dippindots I think you just need to set the `Min. # of Total Cases` to 10, and the bars with <10 samples will become hidden.

![image](https://user-images.githubusercontent.com/840895/58203862-1a0eb700-7ca9-11e9-95fb-83b1aae2a86a.png)

I am wondering if we should highlight the input box when it's greater than 0, e.g. make the border blue?

**Comment by schultzn** [comment]
Yes, good idea…

**Comment by alisman** [comment]
@dippindots There's some confusion above.  I think what we want is for the range to still be be 0 to xx, but the default SETTING to be 10.  So, then a user can come along and take it down to whatever they want.   I think what @schultzn doesn't like is that by default, we include types which are less than 10 and are really not significant.    

So, the following would be the initial state of the UI:
![image](https://user-images.githubusercontent.com/186521/58488807-0b585200-8138-11e9-9b3e-2bc8d32a7819.png)

**Comment by alisman** [comment]
@jjgao @schultzn can you confirm the above is desired?

**Comment by schultzn** [comment]
yes, exactly that!

**Comment by alisman** [comment]
@dippindots, per conversation with JJ, we will include an info alert with this messaging:
![image](https://user-images.githubusercontent.com/186521/58492571-2d090780-813f-11e9-8f9c-192cd9177718.png)

**Comment by dippindots** [comment]
Thanks @alisman. I will make the change soon.
