### ISSUE TITLE
Show VUS Filter in OncoPrint Mutations menu should trigger filter warning

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6133]
The Show VUS Filter in the OncoPrint Mutations menu does not revert to default after modifying a query, while the germline filter does.

We should make it consistent for these two settings.

It might be best to keep both filter settings as last set by the user, but we should add a warning message in the header of the page that filtering has occurred. This warning message should show up right after the selection, even before a query is modified.

![image](https://user-images.githubusercontent.com/11892704/58190897-74991a80-7c8b-11e9-83b4-a0cf5da643ee.png)

**Comment by alisman** [comment]
@adamabeshouse lets discuss

**Comment by schultzn** [comment]
I also just noticed that the VUS filter propagates to the mutations tab. Is that intended? Does it also apply to other tabs? If so, we definitely need the filter info message.

**Comment by jjgao** [comment]
@adamabeshouse @alisman please prioritize this one.

**Comment by alisman** [comment]
@jjgao @schultzn, adam and I discussed this one.  As far as showing current filtering in a header message, one question is the "sign" of the filters.   Right now we show VUS by default.  So the header message would have to read "_**Hiding**_ VUS".    Alternatively, we could change the checkbox to read "hide VUS ..." and have it unchecked by default.   What do you guys think?  

![image](https://user-images.githubusercontent.com/186521/59632343-01fb4d80-9118-11e9-8e8f-ed6cc1dc57ff.png)

**Comment by adamabeshouse** [comment]
To add to that, there's also a question of what we should show in the alert - just filtering, of germline/VUS, or also annotating?

**Comment by schultzn** [comment]
I like his:

"hide VUS ..." and have it unchecked by default.

**Comment by jjgao** [comment]
@adamabeshouse @alisman and I had a discussion on the filter settings and will do the followings (I added a couple more based on discussion here):

- [ ] keep both filter settings after resubmission (I think we should keep as much state as possible)
- [ ] both filter should propagate to other tabs
- [ ] a message should be displayed in all tabs if any of the filters are effective - at least 1 event is filtered out (similar to the OQL message), e.g. "Germline mutations are now shown."
- [ ] in Mutations tab, allow removing each filter (similar to oql)
- [ ] change "Show VUS..." to "Hide VUS" unchecked by default
- [ ] change "Show germline mutations" to "Hide germline mutations" unchecked by default

anything else?

**Comment by alisman** [comment]
@adamabeshouse i'm not wild about the info icon.  maybe a filter icon?  also:
1. can we put the setting in the url?  forgot what we decided on
2. Can we make it clearable from the alert message?

**Comment by adamabeshouse** [comment]
filter icon is a good idea. 

we're not currently putting it in the URL, can it wait for a different PR?

yes we can :+1:
