### ISSUE TITLE
Adding a new cancer type: type of cancer ID is not validated

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#6136]
Currently, it is possible to load a study with a new cancer type that contains an ID with spaces (e.g. `other breast cancers`). The validation step does not raise any warnings or errors and the loader allows to load a study with spaces in the cancer type ID. However, the study then breaks the cBioPortal instance.

Therefore, if a study with contains a wrong format of type of cancer ID is attempted to be loaded:
- The validator should throw an error.
- The loader should throw an error to prevent this study to be loaded.

**Comment by SRodenburg** [comment]
Can this be closed, or do you want to test further? @oplantalech

**Comment by oplantalech** [comment]
@SRodenburg let's close this issue. If I encounter the problem again, I will raise a new issue
