### ISSUE TITLE
group comparison: extra period in loading message

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6145]
![image](https://user-images.githubusercontent.com/10508276/58334876-64f60f00-7e0e-11e9-85f7-8426c75286e3.png)

Looks like there are 2 periods after "sex"

Also, as long as this message is getting updated, can "Do not close the window you came from." be one line rather than having "from" all by itself on a second line?

**Comment by alisman** [comment]
@adamabeshouse i think we can get rid of that "do not close the window you came from" message.  It is very strange.  It's highly unlikely that someone would do that anyway.  Like, switch back to old window, close it, then return to the new one?  Seems unlikely.

**Comment by adamabeshouse** [comment]
@alisman I do it all the time :p
