### ISSUE TITLE
group comparison: issue with adding new group from overlap page

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6146]
Create a new group on the Overlap page, then a warning box appears at the top of the page. This is good.

However, if I click "Save to new comparison session", there is no clear visual indication that anything has happened. I do see that the URL updates to a new session, but this is not obvious unless a user is paying super close attention.

I would expect the warning box to disappear at this point, because that warning no longer is true, and that would serve as a visual indication to the user that something has changed.

**Comment by alisman** [comment]
@tmazor @adamabeshouse i agree that the warning should disappear and this would be good confirmation

**Comment by jjgao** [comment]
@alisman @adamabeshouse this remind me that we also discussed about adding parameters to the url: https://github.com/cBioPortal/cbioportal/issues/5525#issuecomment-489733778. I guess we can do it with a follow up? Or is it easy enough that we should do it now?

**Comment by adamabeshouse** [comment]
which url parameters are you proposing @jjgao , I don't see the relevance

I can't repro this issue - I do see the warning disappear. Can you give a link and which steps to follow to reproduce this?

**Comment by jjgao** [comment]
@adamabeshouse let's keep the url change a separate discussion: https://github.com/cBioPortal/cbioportal/issues/6165

**Comment by tmazor** [comment]
@adamabeshouse I can't replicate it anymore either... either someone already fixed it or there was just something weird happening when I tested on Friday. Either way, it's fine now!
