### ISSUE TITLE
group comparison: overlap tab with overlapping patients

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6149]
In this session, I created groups based on sex, and then made new groups of male & female from the Overlap tab:
https://beta.cbioportal.org/comparison/overlap?sessionId=5ce8030ce4b0ab41378740f4

Every case is included in 2 groups, so all cases overlap. I find the way that this is dealt with slightly confusing.

With all 4 groups selected, I don't even see the tab headers, I just see text telling me that all cases are overlapping.

If I unselect "C. male", then all the tabs appear, and the overlap tab shows me all the cases, including the ones that are overlapping between A. Female and D. female.

So why can't I see the overlap tab when all 4 groups are selected?

**Comment by alisman** [comment]
@jjgao @adamabeshouse it does seem we could do a better job in explaining the situation.  @adamabeshouse i'm guessing the reason we don't show the overlap is because then we would have to disable everything?

**Comment by adamabeshouse** [comment]
@alisman actually I think it is possible to show the overlap tab. I think we should show an informative message in every tab instead of hiding them as we do.. it would be confusing. I'll do that

**Comment by jjgao** [comment]
I think:

- We should show all samples (including the overlapping samples) in the `Overlap` tab, even if "Exclude overlapping samples and patients" are selected
- Hopefully, by doing that, we will always show the other tabs (some could be in gray)?
- When a group is a subset of another group, we are excluding it from analysis - that's good. But we should better explain it. E.g. in [this session](https://beta.cbioportal.org/comparison/mutations?sessionId=5ce864c4e4b0ab41378741a9), we should state that "Group D is a subset of Group C and therefore have been excluded from analysis."
- When two groups are partially overlapping, we should state "xx samples overlapping between group A&C have been excluded from analysis"
- When two groups are identical, we should pick the first group and treat the second one as a subset of the first group.

**Comment by jjgao** [comment]
@adamabeshouse please modify according to the language @Tamba32 proposed https://github.com/cBioPortal/cbioportal/issues/6150

**Comment by alisman** [comment]
i'm pretty sure it was @tmazor not @Tamba32 !

**Comment by jjgao** [comment]
yes, I should start to search @tmazor's last name :)

**Comment by adamabeshouse** [comment]
after discussion with @jjgao we decided that for handling the case of one group being a subset of the other, we're going to do the following:

if a group A is completely covered by other groups B1,...,Bn, then we will just exclude A from the analysis completely, show some indicator of this with tooltip in the group selector interface, and also not exclude A's samples from B1,...,Bn analysis, as once A is excluded it doesn't seem to have a point to exclude its samples from the analysis, haunting the analysis from the grave.
