### ISSUE TITLE
Legend links from Help broken in Network view

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#615]
If you click on any of the legend links (gene, drug, and interaction legends) on the Help page in the Network view, they won't pop up the corresponding legend window!

**Comment by istemi-bahceci** [comment]
This should be fixed now. I've made a pull request to hotfix branch: https://github.com/cBioPortal/cbioportal/pull/635

**Comment by ugurdogrusoz** [comment]
I verified this in a local deployment.
