### ISSUE TITLE
group comparison: update overlap inclusion/exclusion warning messages

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6150]
The message currently says: "Overlapping 249 patients have been excluded from analysis."

Let's change that slightly to:
- [x] 249 overlapping patients are excluded from this analysis.

Or:
Overlapping patients (n=249) and samples (n=0) are excluded from this analysis.

On the survival tab, can we change the overlap included text from:
Overlapping patients are graphed in multiple-group curves below.
to:
- [x] Overlapping patients (n=249) are plotted as distinct groups below.

On the other tabs, can we change the the overlap inclusion message from:
Your selected groups overlap in 2447 samples and 2384 patients.
to:
- [x] The selected groups contain 2447 overlapping samples and 2384 overlapping patients.

**Comment by alisman** [comment]
@jjgao can you confirm this messaging change and assign to @adamabeshouse

**Comment by jjgao** [comment]
yes, please modify. "samples (n=0)" may be confusing, so maybe just use the first option.
