### ISSUE TITLE
group comparison: alignment issue on rna & protein tabs

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6151]
![image](https://user-images.githubusercontent.com/10508276/58340316-8c9ea480-7e19-11e9-881f-98350e446be6.png)

https://beta.cbioportal.org/comparison/mrna?sessionId=5ce810d4e4b0ab4137874102

The same alignment weirdness happens on the Protein tab also.

**Comment by alisman** [comment]
@dippindots this is a strange layout issue. please see if you can figure it out!
