### ISSUE TITLE
group comparison: legend overlap

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6152]
![image](https://user-images.githubusercontent.com/10508276/58340624-45fd7a00-7e1a-11e9-9692-850c10c6f01d.png)

In the legend, the end of the B. Black or African American text overlaps the color box for the C. NA text

https://beta.cbioportal.org/comparison/cna?sessionId=5ce810d4e4b0ab4137874102

**Comment by kalletlak** [comment]
Looks like an issue with `<VictoryLegend>` @adamabeshouse any idea of how to fix it?
