### ISSUE TITLE
group comparison: make plot larger to accommodate legend

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6153]
![image](https://user-images.githubusercontent.com/10508276/58340750-8b21ac00-7e1a-11e9-8e67-726166110a35.png)

This one is minor, but when there are multiple groups selected, there's just one plot shown for mutations/CNA, so when there is a long group name, can the plot be made wider so the whole legend text is visible? I know I can scroll to see it, but there's also just so much white space to the right of the plot.

https://beta.cbioportal.org/comparison/mutations?sessionId=5ce810d4e4b0ab4137874102

**Comment by jjgao** [comment]
And maybe we should truncating the name if it's too long...

**Comment by kalletlak** [comment]
looks like sometimes legend is not visible

![Screen Shot 2019-05-28 at 11 55 44 AM](https://user-images.githubusercontent.com/12956870/58492803-a6085f00-813f-11e9-89e1-e96c45432278.png)
