### ISSUE TITLE
group comparison: overlap tab color scheme

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6155]
The grey used to denote a group is the same grey used as the default color in the overlap diagram:
![image](https://user-images.githubusercontent.com/10508276/58341499-5d3d6700-7e1c-11e9-8dbc-81cf7b903eba.png)

It's impossible to find which circles correspond to the NA group because both are grey.

**Comment by kalletlak** [comment]
@tmazor @jjgao @alisman how about this?
![Screen Shot 2019-05-28 at 11 29 54 AM](https://user-images.githubusercontent.com/12956870/58490918-03021600-813c-11e9-8e06-1c18f4a08936.png)

**Comment by tmazor** [comment]
@kalletlak looks good to me!
