### ISSUE TITLE
group comparison: change text color of variable used to create groups?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6158]
![image](https://user-images.githubusercontent.com/10508276/58343603-7268c480-7e21-11e9-94f7-fd1307dc14bf.png)

This is a very minor issue.

I appreciate that "First Pathologic Diagnosis..." is colored to highlight it. But it's colored blue, and every other text that is blue is a clickable link or button. Can we highlight the text in some other way so it looks less like a link?

**Comment by adamabeshouse** [comment]
how about bold and italic?

![image](https://user-images.githubusercontent.com/636232/58352430-815b7100-7e39-11e9-8b70-409bff2db7aa.png)
