### ISSUE TITLE
group comparison: mrna/protein tooltip update

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6160]
The tooltip for "Enriched in" for mRNA/protein tabs says:
![image](https://user-images.githubusercontent.com/10508276/58349296-e494d580-7e30-11e9-85ba-e96243c61333.png)

Can we change it to say that <=0 is "Enriched in [other group name]", the same way the Mutations & Copy-Number tabs do:
![image](https://user-images.githubusercontent.com/10508276/58349347-ffffe080-7e30-11e9-8b34-eebc29851ba6.png)

**Comment by jjgao** [comment]
Not sure if we can use `enriched` for mRNA. Maybe we should just say Higher expression in...?

**Comment by tmazor** [comment]
That makes sense to me - how about:
>0: Higher expression in A. Tumor resection
<=0: Higher expression in B. Incisional Biopsy

**Comment by tmazor** [comment]
@jjgao we still use "Enriched in" for the column header. Should that also be changed to "Higher expression in" ?

**Comment by jjgao** [comment]
@tmazor I think that makes sense.
