### ISSUE TITLE
group comparison: update google authentication text

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6161]
![image](https://user-images.githubusercontent.com/10508276/58351879-034a9a80-7e38-11e9-9338-5854c59e5ce8.png)

Login is not just for virtual studies anymore! Let's update this text!

**Comment by kalletlak** [comment]
@jjgao its a property setting. @inodb could you update `authorization_message` property

**Comment by inodb** [comment]
@tmazor Good point! What should the text be?


How about:

```
Welcome to cBioPortal - sign in with your Google account to store your virtual studies and groups. This will allow you to access them from any computer. Login is optional and not required to access any of the other features of cBioPortal.
```

?

**Comment by tmazor** [comment]
sounds good to me @inodb !

**Comment by jjgao** [comment]
@inodb @tmazor Maybe add links to the tutorials of virtual studies and custom groups?

**Comment by inodb** [comment]
@jjgao good idea - i can update it once the tutorial for group comparison is there (I think @alisman has a PR)

**Comment by tmazor** [comment]
One small change: can it say "This will allow you to access your studies and groups from any computer." (add "and groups" to the existing text)

![image](https://user-images.githubusercontent.com/10508276/58963688-9f02d180-877b-11e9-8406-df17dd7da5ce.png)

**Comment by jjgao** [comment]
@inodb please update and close this issue (last issue in 3.0.0 :))
