### ISSUE TITLE
group comparison: upset only for samples but not patients?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6162]
There's a sample intersection, but no patient intersection plot:
![image](https://user-images.githubusercontent.com/10508276/58355575-cf28a700-7e42-11e9-902e-aff4cf541774.png)

https://beta.cbioportal.org/comparison?sessionId=5ce856d5e4b0ab4137874182

**Comment by kalletlak** [comment]
@jjgao @tmazor how about this?
![Screen Shot 2019-05-28 at 11 30 06 AM](https://user-images.githubusercontent.com/12956870/58491006-2af17980-813c-11e9-987f-7b99ee1634dd.png)

**Comment by tmazor** [comment]
@kalletlak looks good! will the two plots be on top of each other like this? or can we make them side-by-side like the venn diagrams are?

**Comment by kalletlak** [comment]
@tmazor number of bars could grow a lot if they’re lot of groups and intersections between them

**Comment by tmazor** [comment]
good point @kalletlak. can we do side-by-side if the plots are small enough to fit that way? and then on top of each other if they are big? or would that be very complicated to encode?
