### ISSUE TITLE
group comparison: move new group popup?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6163]
If I decide to make a new group from a selection in the Overlap tab, the "group name" pop-up blocks the text telling me what I clicked on. Can we keep that text visible while entering the group name?

![image](https://user-images.githubusercontent.com/10508276/58356968-0bf69d00-7e47-11e9-85b2-5b6555b05554.png)

**Comment by adamabeshouse** [comment]
yes, Ill just pop it up
