### ISSUE TITLE
allow user to delete a group on comparison page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6164]
Can we allow the user to delete a group on comparison page. After deletion, the user should be able to save it as a new session.

**Comment by adamabeshouse** [comment]
now that we have dragging maybe we can show a trash can that they can drag it to, to save UI space? or we can just keep it simple and add little x's to the group buttons?

**Comment by adamabeshouse** [comment]
@jjgao @alisman at this point we have warnings/banners for unsaved order, unsaved new groups, unsaved deleted groups. each has its own save and reset buttons. is it getting too much? should we consolidate them? or is it okay to have them separate?

**Comment by jjgao** [comment]
@adamabeshouse I think we should consolidate. We definitely don't need multiple Save and Reset buttons.

**Comment by alisman** [comment]
@adamabeshouse i think we should just do this in 3.1.0, no?
