### ISSUE TITLE
Need more colors with better contrast for 3+ groups in group comparison

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6168]
It is very hard to see the difference in color here:

https://beta.cbioportal.org/comparison/survival?sessionId=5cec2948e4b0ab41378741c6

Can color brewer help?
http://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=7

![image](https://user-images.githubusercontent.com/11892704/58434545-3b491c00-808a-11e9-9c61-ad30bd93432d.png)

**Comment by adamabeshouse** [comment]
so in general if we allow N groups then we have at most 2^N curves, so if we have a maximum of 5, as started to be discussed, then we'd need 32 distinguishable colors. I'm not sure it's entirely possible. but we can definitely choose a smaller set of more easily distinguishable colors.

**Comment by adamabeshouse** [comment]
the way it's done now is to have each curve be the color obtained by mixing together all the colors of the groups in the curve. I see that's not really useful here.

**Comment by alisman** [comment]
what about:

1. highlighting the legend items when you hover over a curve
AND/OR
2. putting the group name in the tooltip 

I realize his wouldn't help in exported chart.

**Comment by adamabeshouse** [comment]
oh, yeah Im surprised the group isnt already in the tooltip
