### ISSUE TITLE
Need some way to indicate orderability/draggability of groups

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6171]
Convention would be to use the "move cursor", but we also use these things as clickeable buttons.   Maybe we add an instruction or a "move icon" after the checkbox (or after the name)

**Comment by Sjoerd-van-Hagen** [comment]
I think it is also not very clear that the user can click to select/deselect the groups. Perhaps by replacing the little check mark with an actual checkbox that could be resolved.

**Comment by jjgao** [comment]
Maybe we can do something similar to Gmail: when hovering, display a few dots to indicate draggability?

![image](https://user-images.githubusercontent.com/840895/58513121-c3075700-816c-11e9-89b3-6e09cb505933.png)
