### ISSUE TITLE
maximum 5 groups in a comparison

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#6173]
when tons of groups, only show 5, then have a link that says "75 more..", opens a modal where you can select with checkboxes up to 5 groups to have in the workspace

**Comment by adamabeshouse** [comment]
@jjgao @alisman how do we handle the situation of clicking on a pie chart with more than 5 categories? do we need a new interface to select which ones will make it through to the comparison page?

**Comment by schultzn** [comment]
Maybe grey out the VS button and ask users to manually store the groups they want to compare?

**Comment by jjgao** [comment]
Or we can still send all groups over to the comparison page. On the comparison page, we can select the first 5 groups by default. And the user would have the option to change.

**Comment by schultzn** [comment]
That might work too

**Comment by adamabeshouse** [comment]
@schultzn I remember you had originally said the block of 80 groups for eg impact cancer type detailed was one of the reasons you wanted to cap the # groups. so if we send them all over we'll still see that. is that okay?

@jjgao

**Comment by alisman** [comment]
@adamabeshouse seems like we need to impose a limit on horizontal extend of group buttons either way because they impinge on the dropdown to the right.    maybe we put them in a scroll:auto div to deal with this situation.
