### ISSUE TITLE
In study view table chart, items should be DE-selectable by clicking on checkbox

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6175]
![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/056e66fe-ef99-471f-811d-fca28a4db5f6)

Discussed this with @jjgao.  Since it's possible to deselect a term that's part of the filter tokens, it should also be possible to do so at the checkbox level.

**Comment by kalletlak** [comment]
Closing it for now as there is no easy solution.
