### ISSUE TITLE
documentation missing on db.use_ssl

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#6180]
`db.use_ssl` was introduced in https://github.com/cBioPortal/cbioportal/commit/60e1d41db3acaaf8fa7138be1173e4496e6a03d3, without supporting documentation. Would be good to have some explanation of what this does and how to get it working. E.g. should the DB certificate be added to the tomcat keystore?

**Comment by pieterlukasse** [comment]
Notify @averyniceday

**Comment by ao508** [comment]
Following up on this with @averyniceday @sheridancbio

**Comment by sheridancbio** [comment]
A card for this is in the backlog for the backend pipelines team cc : @n1zea144

**Comment by inodb** [comment]
this is document now indeed: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker#usage-instructions
