### ISSUE TITLE
group comparison: save session resets group selections

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6182]
I add new groups on the Overlap tab, I click "save to new session", and when the page reloads, all groups are selected.

Is it possible to remember which groups were originally selected and retain that after that page reloads?

**Comment by adamabeshouse** [comment]
lets address this together with https://github.com/cBioPortal/cbioportal/issues/6165

**Comment by alisman** [comment]
@jjgao we could accomplish this with url params.  or @kalletlak suggested we just not include inactive groups in new session.  would that be too aggressive (@tali)?

**Comment by tmazor** [comment]
@alisman I think we need to include unselected groups in the new session.

My actions when I logged this issue are (I think) something many users will do: I deselected several groups in order to have a simple venn diagram from which I could define a new group. I then wanted to compare that new group to some of the other groups which I had deselected.

**Comment by adamabeshouse** [comment]
I think the best way to handle this is store it in the url. I don't think it makes sense to save this to a new session, and we've already decided we're never changing sessions once theyve been created.

**Comment by jjgao** [comment]
@alisman @kalletlak I think it may make sense to keep the inactive groups in the session. Using url params makes sense to me. @tmazor what do you think?

Deleting a group will be handled here: https://github.com/cBioPortal/cbioportal/issues/6164

**Comment by tmazor** [comment]
I agree -- let's keep inactive groups in the session. Recording the selection status of each group as a URL parameter makes sense to me.

**Comment by jjgao** [comment]
closing this one. We should not reload the page after saving as logged in #6236
