### ISSUE TITLE
group comparison page forgets that I am logged in

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6185]
If I am logged in on study view, and then run a comparison, the group comparison page loads with the Login button visible. It's like it forgets that I'm logged in?

**Comment by tmazor** [comment]
In fact, I believe it is actually logged out. If I create a new group when the Login button is visible, it doesn't get saved back to the study view page.

If I login, and then create a new group, then it does save the new group back to study view.

**Comment by tmazor** [comment]
This is still happening. While the URL is https://beta.cbioportal.org/loading/comparison?phase=creating_session, I can briefly see the header which shows that I am still logged in. But then it reloads to the comparison session URL and when that loads I am logged out.

**Comment by kalletlak** [comment]
Looks like backend changes are not deployed. @inodb @alisman could you check if the latest(3.0.0) backend is deployed to beta?

**Comment by kalletlak** [comment]
@tmazor its should be working now

**Comment by tmazor** [comment]
Yes it is! Thanks @kalletlak !
