### ISSUE TITLE
faq headers are lost

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6186]
The highest level headers in the FAQ hierarchy appear in the TOC at the top, but not on the page below.

This is particularly an issue for the last entry in the TOC (what if I have other questions?):
![image](https://user-images.githubusercontent.com/10508276/58586020-286c4e00-8228-11e9-818b-10179205f29b.png)

The text for the answer to this gets lost in the answer to the previous question, because the question itself never appears on the page:
![image](https://user-images.githubusercontent.com/10508276/58586013-21454000-8228-11e9-9a56-14525dcd0105.png)

**Comment by ecerami** [comment]
Related to this bug, looks like the higher-level headings, e.g. General Questions, Data Questions, etc. are not clickable.

**Comment by ecerami** [comment]
Will try to fix this one!  may need help... :-)

**Comment by ecerami** [comment]
Ok, I think I understand what's causing this.  The FAQ page actually contains the h1 headings, e.g. General Questions, Data Questions.  But, by default our style sheet hides h1 tags.  That's so we don't end up with two headings at the top of the page.  So, the h1 text is hidden and the links to these sections don't work.

I think we can fix this by simply modifying the markdown page and not changing any code.  To fix, we just need to change all the h1 tags to h2, all the h2 tags to h3, etc.  I will try.
