### ISSUE TITLE
OncoPrint tooltip sometimes not wide enough to show all text

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6187]
Example - cancer type detailed protrudes out of the tooltip box:
![image](https://user-images.githubusercontent.com/11892704/58587040-666a7180-822a-11e9-80ae-74b747577e44.png)

**Comment by adamabeshouse** [comment]
I feel like someone from the hyve fixed this, right @Sjoerd-van-Hagen ?

**Comment by Sjoerd-van-Hagen** [comment]
Yes, @pvannierop has fixed it.

**Comment by Sjoerd-van-Hagen** [comment]
If it indeed is the same issues as this one: https://github.com/cBioPortal/cbioportal/issues/6530
