### ISSUE TITLE
Normalize Reference Information for Genes

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6189]
Currently we have a gene to transcript mapping in cBioPortal and there is one in Genome Nexus (https://github.com/genome-nexus/genome-nexus-importer/blob/master/data/grch37_ensembl92/export/ensembl_biomart_canonical_transcripts_per_hgnc.txt). We should try to have a single one.

- [ ] Check if the Genome Nexus mappings work for cBioPortal
- [ ] Check if the Genome Nexus mappings work for OncoKB
- [ ] regenerate the cbioportal seed database
- [ ] normalize oncokb genes

Further discussion:

- When importing MAF into cBioPortal we use the Entrez ID. Is it possible that sometimes entrez ids get imported that don't have an associated hugo symbol? This would make it impossible to query the data
- cBioPortal doesn't really have a gene to ensembl transcript mapping, but rather gene to entrez id where entrez id represents a particular transcript (?)
- datahub now uses some JSON dump from cBioPortal to validate the mutation file. This differs from live cBioPortal
- Should we use hugo symbol in cBioPortal over Entrez Id?

Check:

- [ ] Is it correct that most of our data has an entrez id? And how is this computed if it doesn't exist?
- [ ] How many MAF files don't have genomic location information?

CC @sheridancbio @n1zea144 	@zhx828 @jjgao

**Comment by jjgao** [comment]
Thanks, @inodb.

Just copied all the columns below and let's discuss which ones to keep or add.


hgnc_symbol | A1BG
-- | --
ensembl_canonical_gene | ENSG00000121410
ensembl_canonical_transcript | ENST00000263100
genome_nexus_canonical_transcript | ENST00000263100
uniprot_canonical_transcript | ENST00000263100
mskcc_canonical_transcript | ENST00000263100
hgnc_id | HGNC:5
approved_name | alpha-1-B glycoprotein
locus_group | protein-coding gene
locus_type | gene with protein product
status | Approved
chromosome | 19q13.43
location_sortable | 19q13.43
synonyms |  
alias_name |  
previous_symbols |  
prev_name |  
gene_family | Immunoglobulin like domain containing
gene_family_id | 594
date_approved_reserved | 6/30/89
date_symbol_changed |  
date_name_changed |  
date_modified | 7/13/15
entrez_gene_id | 1
vega_id | OTTHUMG00000183507
ucsc_id | uc002qsd.5
accession_numbers |  
refseq_ids | NM_130786
ccds_id | CCDS12976
uniprot_id | P04217
pubmed_id | 2591067
mgd_id | MGI:2152878
rgd_id | RGD:69417
lsdb |  
cosmic | A1BG
omim_id | 138670
mirbase |  
homeodb |  
snornabase |  
bioparadigms_slc |  
orphanet |  
pseudogene.org |  
horde_id |  
merops | I43.950
imgt |  
iuphar |  
kznf_gene_catalog |  
mamit-trnadb |  
cd |  
lncrnadb |  
enzyme_id |  
intermediate_filament_db |  
rna_central_ids |

**Comment by jjgao** [comment]
I looked at our cbioportal database, I think the data above covers everything we need. (We don't have length, but I think we can remove the LENGTH COLUMN in the GENE table now - it was previously used in the Mutated Genes tab).

@n1zea144 could someone in your group also take a look, e.g. check all genes in the current portal database are covered.

@zhx828 could you check if all genes in oncokb are covered?

**Comment by zhx828** [comment]
@inodb @jjgao I think due to recent gene updates in portal, some genes in OncoKB are no longer match with GN and portal. I will need to update the genes in the next release. 
 https://docs.google.com/spreadsheets/d/1mqmH1ccKWli7te7L8v0lIQh6uWbnSf2gu07l76RL-gI/edit?usp=sharing

**Comment by n1zea144** [comment]
I will ask one of the curators (probably @rmadupuri) to take a look at gene coverage.

**Comment by zhx828** [comment]
These two genes in GN use different uniport isoforms comparing to the [vcf2mac uniport file](https://raw.githubusercontent.com/mskcc/vcf2maf/master/data/isoform_overrides_uniprot)

gene | isoform
-- | --
HIST1H2BO | ENST00000616182
ARID3B | ENST00000622429

**Comment by jjgao** [comment]
@inodb @zhx828 @n1zea144 @rmadupuri please prioritize this one. This will fix a couple of existing issues, e.g. #5910 and cBioPortal/datahub#540 and will give us a clean start to re-import all studies.

**Comment by rmadupuri** [comment]
Hi @jjgao, the following genes in database did not have matches in GN. Divided them to 4 sheets.
https://docs.google.com/spreadsheets/d/1JCx12E86TGbMydRuzwFSUVgJ2HwlGAvKFViDfgaEK2U/edit?usp=sharing

1. 76 Protein coding genes (Sheet 1)
2. 1820 genes of other types (ncRNA, pseudo, rRNA, scRNA, tRNA, biological-region) (Sheet 2)
3. 24,925 genes whose name starts with LOC.. (Sheet 3) (not sure if needed)
4. 373 miRNA genes (Sheet 4)

The above miRNA's might have been covered in GN but its not easy to compare since the portal has negative entrez ids and GN has positive ids.

**Comment by jjgao** [comment]
I looked a few protein-coding genes:

- GAGE3 was withdrawn: https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:4100
- FAM240C is a placeholder symbol (not sure what that means): https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:54200
- ZNF765-ZNF761 does not seem to have a hugo symbol: https://www.ncbi.nlm.nih.gov/gene/110116772
- LITAFD seems regular: https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:53927

We should do a more systematic analysis. Before doing that, I am wondering if you can help to add a couple of more columns in the spreadsheet so that we know how much data are there for each gene in the public portal? @rmadupuri 
- # of mutations of each gene in `mutation_event` table
- # of rows of each gene in `genetic_alteration` table

**Comment by jjgao** [comment]
related issue https://github.com/cBioPortal/cbioportal/issues/6432

**Comment by jjgao** [comment]
Once we switch, it is also an opportunity to switch to `previous symbols` instead of `synonyms` and hopefully remove manny ambiguity, e.g. mll2. We maybe able too remove this file too: https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/resources/gene_symbol_disambiguation.txt.

**Comment by n1zea144** [comment]
Hi @jjgao - @inodb and I met yesterday to discuss this effort and we have some thoughts about this that I will outline in a google doc / rfc.  I'll link back once I have a draft.

**Comment by n1zea144** [comment]
@jjgao Per our discussion, we will revisit the utility of Entrez, or Ensembl id's in a later effort.  With that, we can build out the roadmap of work to be done on this issue.  cc: @inodb

**Comment by inodb** [comment]
still an issue

**Comment by jjgao** [comment]
@inodb what's the status on this? Should we turn it into an epic?

**Comment by ritikakundra** [comment]
@inodb @jjgao This is now part of our scrum planning (been for 2 weeks). We have been working on finding the best source for our gene table and whatever utilization leads to what kind of data loss.

**Comment by jjgao** [comment]
@inodb @yichaoS can this be closed?

**Comment by jjgao** [comment]
Closing this. Please create new issues if needed.
