### ISSUE TITLE
group comparison: show all tabs when deselect all groups

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6195]
If I deselect all groups, I see just 2 tabs:
![image](https://user-images.githubusercontent.com/10508276/58712433-83b85080-838e-11e9-8e04-8b4e7a9b54f9.png)

If I select just one group, all tabs are visible, even though most are disabled:
![image](https://user-images.githubusercontent.com/10508276/58712454-8fa41280-838e-11e9-96c0-159b4280eea3.png)

Can we show all tabs when no groups are selected? It's confusing that tabs disappear when I click the "Deselect all" button.

**Comment by alisman** [comment]
@adamabeshouse i think we already planned to address this, right?  lets chat when you get in, someone else could take this

**Comment by adamabeshouse** [comment]
@tmazor theres a bit of a subtlety here that makes this hard

We decide whether to show survival and the enrichments tabs based on whether the selected groups have data for it. So technically we really don't know whether we can show those tabs until we know which groups are selected. I think that for a single study there are ways we could get around it, and special cases for multiple study, but for a general session involving multiple studies we really don't know until we know which groups are selected. 

So we have a couple of options, both of which seem off to me:
(1) Show the tab regardless of whether there is survival data, mutation profiles, mrna profiles, etc
(2) Keep as-is with hiding the tabs when there's no available profiles/data, but show the tabs when no groups selected, then hide it again when a group becomes selected.

So in the end I think the only option is really to keep them hidden until more groups are selected.

**Comment by tmazor** [comment]
@adamabeshouse thanks for the explanation.

I think overall my preference would be to always show all tabs for which any group has data. Then selecting or de-selecting groups would not change which tabs are visible, it would just change which are greyed out. We can then show an appropriate message on those tabs for which is there is no data telling the user to select different groups. Does that seem reasonable?

**Comment by adamabeshouse** [comment]
yeah, that sounds like a good idea to me @tmazor

**Comment by jjgao** [comment]
@adamabeshouse thanks for the explanation.

Give the technical complexity, it may not worth the effort. Should we just keep it as is? @tmazor

**Comment by adamabeshouse** [comment]
I would vote do it for 3.1 but not 3.0

**Comment by tmazor** [comment]
I think it's important to do, but I'm fine with pushing it back to 3.1 @jjgao @adamabeshouse

**Comment by adamabeshouse** [comment]
we'll just save which tabs have existed, and show those greyed out
