### ISSUE TITLE
group comparison: order NA as the last group

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6196]
This is a very minor one...

It looks like groups are ordered alphabetically by default? I think that's reasonable, but can we add an exception to put NA as the last group?

![image](https://user-images.githubusercontent.com/10508276/58712656-fa554e00-838e-11e9-908c-924e20f12031.png)

https://beta.cbioportal.org/comparison?sessionId=5ce8164be4b0ab4137874107

**Comment by alisman** [comment]
@adamabeshouse i think we could push this to 3.1.0 if necessary
