### ISSUE TITLE
group comparison: legends on Survival tab are cutoff

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6198]
The legends for the group-combination lines are cutoff:

![image](https://user-images.githubusercontent.com/10508276/58716284-b23a2980-8396-11e9-8a7d-5bf485f02d88.png)

https://beta.cbioportal.org/comparison/survival?sessionId=5cf13d70e4b0ab4137874293

**Comment by alisman** [comment]
@jjgao is this a useful chart?  should we go ahead and handle the width issue?

**Comment by jjgao** [comment]
For interactions, should we just do `A & B only`, `A & C only`, etc? I think we should also change "(A) CDKN2AB del" to "(A) CDKN2AB del only".

**Comment by adamabeshouse** [comment]
@jjgao thats a great way to improve the overlap tooltips actually. I will make that change
