### ISSUE TITLE
group comparison: overlap tab typo

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6199]
The patient intersection plot is labeled samples:
![image](https://user-images.githubusercontent.com/10508276/58716807-dba78500-8397-11e9-82c2-03c48913cdc1.png)
https://beta.cbioportal.org/comparison/overlap?sessionId=5cee9a53e4b0ab4137874211

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2386
