### ISSUE TITLE
group comparison: upset plot shows different data now

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6200]
This is a screenshot from a few days ago (#6183) 

![image](https://user-images.githubusercontent.com/10508276/58717190-a8b1c100-8398-11e9-9b2f-9ee8e14e7140.png)

This is the same data today:
![image](https://user-images.githubusercontent.com/10508276/58717207-b23b2900-8398-11e9-8ad1-c6d403fc88bf.png)
https://beta.cbioportal.org/comparison/overlap?sessionId=5cf14a3ce4b0ab4137874295

The plot is much smaller now. Has there been a change to how we show the overlap?

**Comment by alisman** [comment]
@tmazor yes, we did change how we handle overlap.  i'm not the best person to articulate it exactly so I will get someone else to do so.

**Comment by adamabeshouse** [comment]
@tmazor 
lets say the session is groups A,B,C

previously, the bar corresponding to groups A and B would have all samples in A and B, regardless of whether they're in C

now, the bar corresponding to groups A and B would have all samples in A and B that are also NOT in C

so the numbers have changed

**Comment by tmazor** [comment]
Gotcha! Thanks @adamabeshouse, that makes sense!
