### ISSUE TITLE
Create group from Upset diagram

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6201]
The user should be able to select a bar and create a group, similar to Venn diagram

**Comment by tmazor** [comment]
Agree! I was going to make this same issue :)  I would just add that the user should be able to select multiple bars, just like with the Venn diagram.

**Comment by adamabeshouse** [comment]
where should we put it when the samples and patients upsets are stacked vertically?

**Comment by jjgao** [comment]
@adamabeshouse can we add it under the plot, the same as venn diagram?

BTW, maybe it's better to hide the button before selection? And also swap the position of button and text?

![image](https://user-images.githubusercontent.com/840895/58732697-45d42000-83c0-11e9-82a4-ad5f19264fc7.png)

**Comment by tmazor** [comment]
I would argue for keeping the button because it is an indication to the user that they can create a group. Otherwise that functionality might be too hidden?

**Comment by jjgao** [comment]
@tmazor good point. Then let's keep it as is.

**Comment by tmazor** [comment]
Swapping the button and text might make sense though. Although then we would need to revert the change that @adamabeshouse made to make the new group pop-up not block the text... (sorry @adamabeshouse!)

**Comment by jjgao** [comment]
@tmazor not sure if we should swap the button and text if we always show the button but not the text. There would be too much space between the plot and button when nothing is selected.

**Comment by tmazor** [comment]
Oh good point - I wasn't thinking about that. Ok let's leave it as is.

**Comment by adamabeshouse** [comment]
my favorite outcome!

**Comment by jjgao** [comment]
> where should we put it when the samples and patients upsets are stacked vertically?

@adamabeshouse Let's implement the button under each chart?
