### ISSUE TITLE
Add "Most enriched in" column in Mutations and Copy-number when there 3 or more groups

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6203]
Currently, we only have the `Enriched in` when there are two groups. When there are 3 or more groups, can we add a column `Most enriched in`?

**Comment by kalletlak** [comment]
@jjgao what should the tooltip be for the column be?

currently we have
<img width="281" alt="Screen Shot 2019-05-31 at 2 06 08 PM" src="https://user-images.githubusercontent.com/12956870/58725482-41ead280-83ad-11e9-9a39-2f5cc77a0732.png">

<img width="293" alt="Screen Shot 2019-05-31 at 2 06 35 PM" src="https://user-images.githubusercontent.com/12956870/58725509-55963900-83ad-11e9-959e-bdd1ac6e4cf6.png">

**Comment by jjgao** [comment]
"The group with the highest alteration frequency"
