### ISSUE TITLE
Comparison page: color code CNA in Alteration column in Copy-number tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6204]
... similar to patient view

![image](https://user-images.githubusercontent.com/840895/58721073-f0891600-83a1-11e9-81fb-bf467e2e9d4f.png)

https://www.cbioportal.org/patient?caseId=TCGA-DI-A1NN&studyId=ucec_tcga_pub

Currently on Comparison page:
![image](https://user-images.githubusercontent.com/840895/58721197-4d84cc00-83a2-11e9-9e52-096cf9db8d3b.png)

**Comment by adamabeshouse** [comment]
should it say DeepDel as well?

**Comment by jjgao** [comment]
@adamabeshouse yes.
