### ISSUE TITLE
use groups colors in comparison page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6205]
Overlap tab
- [x] Venn diagrams
- [x] Upset diagrams: first try - https://github.com/cBioPortal/cbioportal-frontend/pull/2382

Survival tab
- [x] Survival curves

Clinical tab
~- [ ] axis label of the plot (optional) -- no worries if too hard to do~ - skipping according to https://github.com/cBioPortal/cbioportal-frontend/pull/2526#issuecomment-509885427

Mutations and Copy-number columns
- [x] barplot #6202
- [x] `Enriched in` column
- [x] mini-oncoprint #6206

mRNA and Protein
- [x] `Enriched in` column

**Comment by adamabeshouse** [comment]
CC @alisman
