### ISSUE TITLE
group comparison: add color to co-occurrence pattern plot

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6206]
I find the co-occurrence pattern mini-oncoprint to be hard to understand.

1) Can the upper bar be colored the same colors as the groups list in the header? I think that will help a lot with the interpretation of the plot.

2) Let's add a tooltip:
Upper row: Samples colored according to group.
Lower row: Samples with [a mutation (mutations tab); the listed alteration (copy-number tab)] in the listed gene are highlighted.

**Comment by jjgao** [comment]
Good idea!

**Comment by alisman** [comment]
@adamabeshouse JJ wants the lower bar in the MiniOncoprint to reflect the color of the alteration type (mutation, copy number del or amp)

**Comment by alisman** [comment]
@jjgao @tmazor, I've take care of the colors per this ticket, however there are two outstanding changes unfinished:  
1. the tooltip. Tali, there is already a tooltip.  Should we combine the explanatory and data content?
2. @jjgao you asked for the color of the bottom bar to reflect alteration type color from oncoprint.  Adam and I feel this would really make the whole thing ever harder to understand.  

In fact, Ino and Adam (and I guess me) feel like we still haven't gotten this quite right.  Maybe solicit more opinions for potential 3.1.0 changes?

**Comment by tmazor** [comment]
@alisman I don't see a tooltip on the "Co-occurence Pattern" column header - or at least I can't get it to appear.

**Comment by tmazor** [comment]
@alisman oh do you mean there is a tooltip for each mini-oncoprint? That one is good, but I wanted to add a tooltip to the column name.

**Comment by jjgao** [comment]
@alisman I get your point, let's not worry about # 2.

**Comment by jjgao** [comment]
tooltip issue: https://github.com/cBioPortal/cbioportal/issues/6251

**Comment by alisman** [comment]
@tmazor ok, column header.  got it
