### ISSUE TITLE
group comparison: add tutorial slides

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6207]
Making an issue so we don't forget about this. I still need to finalize the tutorial slides, but I think we want to have this added to the Tutorials page together with the group comparison release.

**Comment by jjgao** [comment]
@tmazor maybe we can already include it while you are still finalizing it?

**Comment by tmazor** [comment]
haha yes, great point.

Link to the tutorial is: https://docs.google.com/presentation/d/1P2boDph8IfpvjxoxDj_496CLHGtshzJnbbZhszPsmf4/edit#slide=id.p
