### ISSUE TITLE
functional impact tooltip doesn't have definitions for mutation assessor

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6208]
The tooltip nicely defines how SIFT and PolyPhen predictions are color-coded, but Mutation Assessor isn't included:

![image](https://user-images.githubusercontent.com/10508276/58729077-6c8d5900-83b6-11e9-9741-31755404660b.png)

**Comment by tmazor** [comment]
This is still an issue

**Comment by inodb** [comment]
I think @leexgh might have looked at this?

**Comment by leexgh** [comment]
@tmazor it works fine for me
![image](https://user-images.githubusercontent.com/16869603/77272037-96d23f00-6c86-11ea-8907-9d0464429e6a.png)
Could you send me the link you queried?

**Comment by inodb** [comment]
We should fix this, I think we should show all legends when mousing over. It's somehow only showing two at a time:

<img width="564" alt="Screen Shot 2020-06-22 at 12 47 11 PM" src="https://user-images.githubusercontent.com/1334004/85313766-851b5600-b486-11ea-955b-111f4fe69de8.png">
<img width="564" alt="Screen Shot 2020-06-22 at 12 47 06 PM" src="https://user-images.githubusercontent.com/1334004/85313767-85b3ec80-b486-11ea-95ad-46b5b3a239fa.png">
<img width="496" alt="Screen Shot 2020-06-22 at 12 47 02 PM" src="https://user-images.githubusercontent.com/1334004/85313768-85b3ec80-b486-11ea-8988-b7da273fb2b9.png">

**Comment by leexgh** [comment]
@inodb i see, so the mutationAssessor legend is missing. I'll fix it soon

**Comment by leexgh** [comment]
Mutation Assessor is down again, we'll remove it until it's back.
