### ISSUE TITLE
Group comparison tracking

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6209]
Comparison page and tabs will be tracked as per usual by ga page events.

Fire GA events for the following interactions:

Create custom group
Create custom comparison session
Create comparison session from chart
Open group management popover

**Comment by jjgao** [comment]
On Comparison page:

- tab visits
- number of groups in session
- the studies (if virtual study, break them into real studies)

**Comment by jjgao** [comment]
Some of the interactions may be worth capturing so that we know whether they are used, e.g. "Create Group from selected diagram" clicked and Exclude/Include selection,

**Comment by jjgao** [comment]
Some discussion from Slack.

Aaron Lisman [12:18 PM]
JJ, working on tracking.  when someone does a comparison from a virtual study, how important is it to know the underlying physical studies?

Aaron Lisman [12:24 PM]
actually, i just figured out a pretty easy way

JJ Gao [1:07 PM]
ok. It’s important to track the physical studies.

Aaron Lisman [1:40 PM]
ok.  figured out away to do it pretty simply.  now, we can track these only when we create session, or every time session is viewed
any opinion on that?

JJ Gao [1:41 PM]
I think we should try when a session is created or viewed - that’s the number of times that a study is used.

Aaron Lisman [1:42 PM]
ok, so "when a session is used"  either at creation or subsequent access

JJ Gao [1:44 PM]
Yes
Just to be clear, we should track the number of uses of each physical studies for comparison (not number of uses of comparison sessions). (edited) 

Aaron Lisman [1:47 PM]
i see, so we're not counting sessions (or maybe that in addition) but "uses of certain physical study in a comparison"
if there's five phys studies in a single session
that's five events
i mean, we could also derive that in report
lets talk about this one after meeting
just want to make sure we get it right

JJ Gao [1:48 PM]
I don’t think it’s useful to count per session, just like we are not counting Results sessions.
