### ISSUE TITLE
style group names and ordinals everywhere in group comparison page

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#6218]
we want `(<strong>{group.ordinal}</strong) {group.name}`

- [x] chart ticks
- [x] chart legend
~- [ ] enrichments table header~ leave as-is for now
~- [ ] enrichments table "most enriched" column~ leave as-is for now

**Comment by jjgao** [comment]
related: https://github.com/cBioPortal/cbioportal/issues/6205

**Comment by adamabeshouse** [comment]
for chart ticks and legend, we can use the strategy implemented in https://github.com/cBioPortal/cbioportal-frontend/pull/2499 for the upset ticks

**Comment by adamabeshouse** [comment]
use React.FunctionComponent for the types of the label components
