### ISSUE TITLE
group comparison: update text for "limit 20 groups" message

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6221]
Current text:
Group comparisons are limited to 20. Click OK to create a comparison of the 20 largest groups. Or, you can click to select fewer groups in this chart to compare.

Other options:
Group comparisons are limited to 20 groups. Click OK to compare the 20 largest groups in this chart. Or, select up to 20 specific groups in the chart to compare.

Group comparisons are limited to 20 groups. Click OK to compare the 20 largest groups in this chart. Or, filter to the specific groups of interest and then click the compare button.

Thoughts? @schultzn @jjgao @alisman @adamabeshouse

**Comment by adamabeshouse** [comment]
I like the first one. If I was a user Id be confused by more abstract terms like "filter", and clarified by a the concrete term of "select"

**Comment by adamabeshouse** [comment]
integrated into https://github.com/cBioPortal/cbioportal-frontend/pull/2399
