### ISSUE TITLE
group comparison: updates to text in group labels

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6222]
I'm not sure what the right solution to this is, but here's the issue.

Looking at the buttons for each of these groups, the text is essentially split 50/50 between the group name and the parenthetical with the number of samples/patients. The problem is that the words "samples" and "patients" take up a whole lot of space and are repetitive across all the groups, whereas the group name is more informative but is often truncated.

Is there a reasonable way that we can abbreviate/limit how much space it devoted to "(xx samples/yy patients)" so that we can see more of the group name?

Some options include:
- eliminate the words "sample" and "patient" entirely, and just show the numbers, and define those numbers in a tooltip
e.g. button says "(A) Bladder Cancer (423/406)" and tooltip says "(A) Bladder Cancer (423 samples/406 patients).

- use "s" and "p" instead of "sample" and "patient"
e.g. button says "(A) Bladder Cancer (423 s/406 p)" 

- write out "samples" and "patients" for the first group and then hide/abbreviate those words for all subsequent groups
e.g. "(A) Bladder Cancer (423 samples/406 patients)" and then "(B) Breast Cancer (1324/1234)"

I do worry that some of these options might be confusing, especially for new users.

Any other ideas? @cBioPortal/product @alisman @adamabeshouse 

![image](https://user-images.githubusercontent.com/10508276/58907604-927b6c00-86dc-11e9-86da-9b287d70a0bd.png)

**Comment by adamabeshouse** [comment]
just had what I (humbly) think is a great idea - show "s/p" and then on mouseover the button expand the text out

**Comment by jjgao** [comment]
Good point. I like the last option the best but I think any of them would work.

**Comment by Sjoerd-van-Hagen** [comment]
With the third option the name of the first study will still be abbreviated. The s and p in the second option will not mean anything to the user unless they already suspect that it is sample and patient. 

I like the first option best. Perhaps we can do better if we can find a good icon for sample? That would be really nice because we can use it consistently across the portal so users will learn what it means.

**Comment by Sjoerd-van-Hagen** [comment]
Perhaps for the patient we can use a 'person' icon with a colored, irregular spot to denote the tumor. Sample would then just be that spot, in the same color and shape. They will be next to each other so people will probably understand, especially if we use them consistently in the whole portal.

In the same fashion, perhaps we can use icons for many other things as well. For instance, now we have colors for different sample types, we could also use icons there. ICGC uses icons for tissue type, and there are some icon sets around cancer treatment which could be nice on the patient timeline: https://www.shutterstock.com/search/chemotherapy+icons

The cBioPortal audience is large enough to set a standard for these icons.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen good idea about have icons consistently across the portal, but I am not sure having icons in the button here would look good - it could be.

Before we can decide on icons, maybe we can go with option 1? @tmazor @Sjoerd-van-Hagen @adamabeshouse
