### ISSUE TITLE
This clinical tab causes error page

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6228]
https://cbioportal.mskcc.org/beta/comparison/clinical?sessionId=5cf7dd9ce4b0ab413787434a

**Comment by kalletlak** [comment]
@zhx828 could you give more information about it. I Don't have access to mskcc portal

**Comment by zhx828** [comment]
@kalletlak It's the `api/clinical-data-enrichments/fetch` endpoint returns 500. You probably just need to handle the error.

**Comment by kalletlak** [comment]
Looks like data is string(example `<18` or `>60`) for some attributes of NUMBER datatype. which throws an error while converting them to number when calculating Kruskal-wallis test.

@jjgao how should we handle such special cases?

possible options
1. ignore(filter) such data before doing Kruskal-wallis test
2. update study change datatype to STRING
3. ignore attribute (don't show it in table)

**Comment by alisman** [comment]
@kalletlak lets at least handle this error in the sub tag so that the whole comparison session isn't destroyed.  this is easy enough to do by adding an error handler to the mobxpromise and showing a message in the tab

**Comment by alisman** [comment]
@zhx828 can you tell how prevalent this is?  i actually remember this coming up before

**Comment by zhx828** [comment]
@alisman @kalletlak  this happens not really frequently but mainly requested by the GENIE community. Some institutions would not want to release the actual age especially for pediatric patient. We need to handle the case in the group comparison. I suggest to ignore the enrichment analysis for clinical attribute that does no qualify the data requirement. So in the GENIE case, we would not perform statistical test, and shows `Analysis unavailable` when user clicks on age.

**Comment by jjgao** [comment]
@kalletlak let do option 1 "ignore(filter) such data before doing Kruskal-wallis test".

Let's not block the 3.0 release but please prioritize the fix.

**Comment by adamabeshouse** [comment]
@alisman In addition to adding an error screen for the clinical tab, we also need to take off the code in AppStore.ts that makes the error screen come up on every unhandled error. Any server error from a client that results in Promise.reject will be an unhandled error.

**Comment by adamabeshouse** [comment]
line 26: siteErrors.push(...)

**Comment by jjgao** [comment]
hmm. still not work...
![image](https://user-images.githubusercontent.com/840895/59200764-f7184a00-8b66-11e9-8107-73dbd2ad4349.png)

**Comment by zhx828** [comment]
@jjgao the issue has been addressed in production portal if you look at this link with same session id https://cbioportal.mskcc.org/comparison/clinical?sessionId=5cf7dd9ce4b0ab413787434a The beta portal is not up to date.
