### ISSUE TITLE
Filter option broken for clinical tracks selection component

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#6231]
Steps to reproduce:

1. go to http://www.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=brca_tcga&case_set_id=brca_tcga_cnaseq&data_priority=0&gene_list=SOX9%2520RAN%2520TNK2%2520EP300%2520PXN%2520NCOA2%2520AR%2520NRIP1%2520NCOR1%2520NCOR2&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&tab_index=tab_visualize

2. Click "Add clinical tracks"

3. Filter on IHC. The list will become shorter, but the count on the "Add all" button will remain on 138 (see screenshot below)

![image](https://user-images.githubusercontent.com/2900303/59026467-c37fac00-8856-11e9-9370-94d5111db2db.png)

Desired solution:
 - the "Add all" button should show the correct count of matching items. Clicking the button should result in only the filtered items being added as clinical tracks.

**Comment by pieterlukasse** [comment]
notify @jjgao, @alisman

**Comment by adamabeshouse** [comment]
fixed by new component
