### ISSUE TITLE
Selection of gene in volcano plot for mini onco print broken

### ISSUE THREAD

**Issue by paulcwvandijk** [cBioPortal/cbioportal#6233]
Steps to reproduce:

go to https://www.cbioportal.org/results/enrichments?Action=Submit&cancer_study_list=msk_impact_2017&case_set_id=msk_impact_2017_all&gene_list=TP53&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&tab_index=tab_visualize&show_samples=false&clinicallist=NUM_SAMPLES_PER_PATIENT

The instruction in the mini bar chart (mini oncoprint) next to "None selected" says "Select gene in table or volcano plot". 

This works as expected when selecting a gene in the table in the enrichment tab
Selecting a gene based on a datapoint in the volcano plot does NOT work.

Desired solution:

-  The instruction is limited to "Select gene in table" 
or
- clicking a dot/gene in the volcano plot results in a bar for that gene  

![mini oncoprint](https://user-images.githubusercontent.com/44695112/59029686-3c830180-885f-11e9-8a5d-99622f2a3707.png)

**Comment by paulcwvandijk** [comment]
notify @jjgao, @alisman

**Comment by alisman** [comment]
thanks @paulcwvandijk.  We are replacing this feature in release-3.0.0, which should be released this week.  so i think we should just leave this be.  (the mini oncoprint will now appear in each row the gene table and won't require user interaction to see)
