### ISSUE TITLE
update labels on enrichments tab

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6237]
![image](https://user-images.githubusercontent.com/10508276/59044752-b1990b80-884c-11e9-8072-f9c72cb47c1d.png)

The frequency plot is confusingly labeled on the enrichments tab. Both the tooltip & axis labels refer to "Alteration Frequency in Co-occurence/Mututal Exclusivity". However, what is being plotted is the "Alteration Frequency in Altered/Unaltered group".

Let's update the tooltip text & axis labels on the Mutations & Copy-number tabs.

**Comment by kalletlak** [comment]
even dropdown contains Co-occurence, Mututal Exclusivity. should we even change this?
![Screen Shot 2019-06-06 at 12 12 47 PM](https://user-images.githubusercontent.com/12956870/59048770-8dd9c380-8854-11e9-9147-c96af9d21226.png)
