### ISSUE TITLE
When in pie chart tooltip, show column name in table

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6255]
![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/f3981836-8468-49a8-ac00-5e043d6a5f3f)

The first column in this table used to have header "Sex."   We took that away because it was redundant when table was shown as top level chart. But when the table is shown inside tooltip, one can see we need the column name.

**Comment by zhx828** [comment]
@dippindots just want to give you a heads-up, there are some minor changes introduced in this pr https://github.com/cBioPortal/cbioportal-frontend/pull/2109/files are related to this ticket.  Let me know when you finished the fix, it may create conflict in yours if mine is merged first.

**Comment by dippindots** [comment]
@zhx828 Thanks! It is just a one-line fix, and fortunately, we don't have overlap!
