### ISSUE TITLE
Error while importing gene panel data from study_es_0 study

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#6261]
https://groups.google.com/forum/#!topic/cbioportal/07Qwl_LYTvI

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen would anyone from your team help with this?

**Comment by Sjoerd-van-Hagen** [comment]
@pvannierop can you have a look?

**Comment by jjgao** [comment]
Thanks

**Comment by pvannierop** [comment]
Issue was resolved by the google group thread started.
