### ISSUE TITLE
Oncoprint Mutation Representation When RNA-seq Available

### ISSUE THREAD

**Issue by DarioS** [cBioPortal/cbioportal#6262]
Many data sets hosted by cBioPortal have both exome sequencing and RNA sequencing available. If a gene is not transcribed, its mutation might still be described as missense because the data types are treated independently. Could there be a new category of annotation, Not Expressed that represents mutations differently for unexpressed genes (a category such as missense would not be shown for such a gene)?

**Comment by jjgao** [comment]
@DarioS it's a good idea but we don't actually have such data (whether a mutation is expressed). In order to do that, we would need to build a pipeline to generate the data. Please let us know if you know that such dataset is already available somewhere.
