### ISSUE TITLE
A earlier session is no longer working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6265]
reported by [a user](https://groups.google.com/forum/#!msg/cbioportal/1murYSTdY-g/-25ufVQOBgAJ)

http://bit.ly/2WgIFYK

**Comment by alisman** [comment]
@ritikakundra @jjgao the name of the study "all_phase2_target_2018_pub" appears to have changed.  We get the following 404 response:
{"message":"Study not found: all_phase2_target_2018_pub"}
(We need to handle this better. )

**Comment by ritikakundra** [comment]
@alisman waiting for this to be merged https://github.com/cBioPortal/cbioportal/pull/6271 and then we will import this back in

**Comment by jjgao** [comment]
@alisman we should handle the case when a study or sample does not exist any more in the frontend.

**Comment by alisman** [comment]
@jjgao if we have an invalid study ID in query, my preference would be to NOT show any results and show a message citing the invalid IDs.  User would have to correct URL.  Is this reasonable?

**Comment by jjgao** [comment]
@alisman Maybe we can show the error message and also the Query interface so that the user can correct the query in the interface (not URL)?

**Comment by alisman** [comment]
study name was fixed
