### ISSUE TITLE
Add chart menu in study view hiding the add chart button preventing user from closing the menu

### ISSUE THREAD

**Issue by Sjoerd-van-Hagen** [cBioPortal/cbioportal#6272]
- Select a small study, I used https://www.cbioportal.org/study/summary?id=mixed_pipseq_2017
- Open the Add chart menu
- Make a selection that creates bread crumbs, for instance click on a pie slice

Now the appearance of the breadcrumbs will push the 'add chart' button behind the 'add chart' menu and you cannot close the menu any more.

The same can actually be achieved from within the menu by clicking the 'custom data' tab and then the 'Use selected samples/patients and then hit 'add chart'

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao @zhx828

**Comment by zhx828** [comment]
@Sjoerd-van-Hagen I will fix.

**Comment by Sjoerd-van-Hagen** [comment]
@zhx828 Thanks!
