### ISSUE TITLE
Remember user preference whether filter the tables in SV by cancer gene list

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6274]

**Comment by zhx828** [comment]
@kalletlak this is will be part of the user customization.

**Comment by jjgao** [comment]
@zhx828 are you planning to make it a global setting or cancer study specific setting?

**Comment by zhx828** [comment]
I thinks this should be global? But up for discussion.

**Comment by jjgao** [comment]
I think this should be global too. Do we have a global setting for user? If not yet, I think it's ok to save it to local storage since it's not a critical parameter.
