### ISSUE TITLE
pull mrna, protein, continuous cna, and methylation data in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6278]
- [x] add a new tab "Gene level" (next to Genomics tab) in the "Add Chart" dialog
- [x] UI for pulling data for a single gene and a single profile (mrna, protein, continuous cna, and methylation data)
- [x] display the data in bar plot
- [x] support group comparison, similar to other bar plot
- [x] save the chart in user-specific data so that it'll load up next time

**Comment by zhx828** [comment]
BREAST-TCGA-PROVISIONAL(brca_tcga) has methylation, protein data
how to handle cross study page, multiple profile, same type? Give dropdown for each study to select the profile(select one by default)

**Comment by alisman** [comment]
@kalletlak, we decided to assign this ticket solely to you (@dippindots  will focus elsewhere).

**Comment by jjgao** [comment]
@kalletlak for multiple studies, we can group the profiles based on profile name, similar to what @dippindots did in the Download tab. http://bit.ly/32GITID

**Comment by tmazor** [comment]
I love that we are adding these other data types to study view! But if we do this, I think it's also important to add the ability to easily filter to samples with a particular data type. We have this as quick filters for mutation & CNA already, and we used to have this as pie charts with yes/no. This might be too much for quick filters, so perhaps it would be better to go back to having pie charts for each data type.

**Comment by jjgao** [comment]
@tmazor maybe instead of creating a pie chart per profile, we can do it in one table? I logged [here](https://github.com/cBioPortal/cbioportal/issues/6771) and let's discuss there. Let's do another pull request for that and release this separately?

**Comment by tmazor** [comment]
Sounds good - selecting samples based on profiles can definitely can be a separate task/PR
