### ISSUE TITLE
adding custom groups into oncoprint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6279]
It would be useful to support adding custom groups to oncoprint. Maybe we can just add the custom groups into the clinical data menu with a prefix, e.g. "Custom Group: "?

**Comment by adamabeshouse** [comment]
and the clinical track value would be in group/not in group?

**Comment by alisman** [comment]
@adamabeshouse i test this.  As @jjgao suggested, I think we need a prefix before group name is possible.  Otherwise, it's card to understand what these items are.  
![image](https://user-images.githubusercontent.com/186521/59710008-13a32a80-91d6-11e9-856f-991f22039b70.png)
