### ISSUE TITLE
Info icon error for virtual studies when auth enabled

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6285]
As reported by @marriott-er 

The info icon of virtual studies shows an error on hover for authenticated portals 

![image (8)](https://user-images.githubusercontent.com/1334004/59707806-63cbbe00-91d1-11e9-8d92-920de1847258.png)

There's a 403: Forbidden at the /api/studies/study_id/tags endpoint

**Comment by inodb** [comment]
@oplantalech do you have an idea? The study tags wouldn't exist for a virtual study

**Comment by oplantalech** [comment]
@inodb my guess is that the endpoint only accepts `study_id` and not the id of the virtual study. This needs to be fixed. I will try to prioritize this.

**Comment by inodb** [comment]
Thanks @oplantalech
