### ISSUE TITLE
feature request: highlight multiple mutations in the same sample in mutation view

### ISSUE THREAD

**Issue by ndfriedman** [cBioPortal/cbioportal#6293]
When you query a gene in cbio portal and then click the mutations tab, then sort by patient ID, it would be quite helpful if then patient name were shaded to highlight cases that have two or more mutations.
Ie in the image below, the two lines for patient 448 would be both shaded dark gray to highlight that they have multiple mutations in the same gene in the same case
<img width="454" alt="Screen Shot 2019-06-19 at 6 03 54 PM" src="https://user-images.githubusercontent.com/19807496/59804566-b6ce6f80-92bc-11e9-8331-b6dd2c4a77e4.png">

**Comment by jjgao** [comment]
@ndfriedman thanks for the feature request. Instead of shading the patient name, maybe we can add some information, e.g. an icon or the text "multiple", in the Protein Change column?

![image](https://user-images.githubusercontent.com/840895/59805139-6eb04c80-92be-11e9-9c51-6d150260040e.png)

**Comment by ndfriedman** [comment]
yeah that would be another good solution, as long as it pops off the page

**Comment by jjgao** [comment]
@onursumer this seems like an easy task?

**Comment by onursumer** [comment]
@jjgao Implementing the logic shouldn't be too difficult, but is the protein change column the best place to indicate this?

**Comment by jjgao** [comment]
@onursumer It seems intuitive to me to add it to the protein change, but maybe there is a better place. Any suggestions?

**Comment by Luke-Sikina** [comment]
Adding a tooltip when you mouse over the `multiple` that says "This sample has multiple mutations".

**Comment by jjgao** [comment]
@Luke-Sikina would you have bandwidth to finish this PR?
