### ISSUE TITLE
expression tab appears for studies without expression data

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6294]
Let's hide the Expression tab for queries where no studies have expression data -- similar to how we hide Co-Expression in a single-study query without expression data.

![image](https://user-images.githubusercontent.com/10508276/59859935-b204cc80-934b-11e9-86df-d0ab667b2d2e.png)

https://www.cbioportal.org/results/expression?session_id=5d0ba114e4b0ab4137876b19

**Comment by alisman** [comment]
@jjgao @tmazor, in process of handling this ticket, i noticed that we show expression tab for a multi-study query when only a single study has expression data.    why is it that we don't show it when there's only one study in the query?

**Comment by jjgao** [comment]
@alisman and  I had a discussion and we will always show the expression tab when there is data.

**Comment by alisman** [comment]
This is now merged
