### ISSUE TITLE
allow sharing session with group tracks in oncoprint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6296]
As commented [here](https://github.com/cBioPortal/cbioportal-frontend/pull/2466#issuecomment-503634103), if I share a session including "in group" tracks with another person, that person will be able to render the "in group" tracks.

https://www.cbioportal.org/results/oncoprint?clinicallist=NUM_SAMPLES_PER_PATIENT%2CIN_COMPARISON_GROUP_Non-Small%20Cell%20Lung%20Cancer&session_id=5d0a6174e4b0ab4137876774&show_samples=false

![image](https://user-images.githubusercontent.com/840895/59783148-7f949a00-928d-11e9-8a9b-d3a73edb49a4.png)

I think it was due to authentication, ie. only the user who created the groups is allowed to access it. Let's 

- [x] allow read access to any group by group UID for anyone
- [x] change the id in clinicallist to group UID

@adamabeshouse would you need @kalletlak's help on the 1st item?

**Comment by adamabeshouse** [comment]
@jjgao I already did the first item in my PR. and yes Im not familiar with the backend. it will still take some frontend changes once thats implemented

**Comment by kalletlak** [comment]
@adamabeshouse you can always pull ID. example https://www.cbioportal.org/api-legacy/proxy/session/group/5ce4119fe4b0ab4137874072
