### ISSUE TITLE
Cancer types summary misleading 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#6301]
See https://www.cbioportal.org/results/cancerTypesSummary?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=paac_jhu_2014%2Cblca_bgi%2Cbrca_tcga&case_set_id=all&clinicallist=CANCER_STUDY%2CNUM_SAMPLES_PER_PATIENT%2CPROFILED_IN_COPY_NUMBER_ALTERATION&data_priority=2&gene_list=SOX9%2520RAN%2520TNK2%2520EP300%2520PXN%2520NCOA2%2520AR%2520NRIP1%2520NCOR1%2520NCOR2&geneset_list=%20&show_samples=false&tab_index=tab_visualize

The studies "Bladder" and "PAAC" will be listed in the histogram as if they have no alterations for the selected gene, while in reality there is no CNA data for these studies.

**Comment by pieterlukasse** [comment]
notify @jjgao

**Comment by jjgao** [comment]
Good catch. At least we should add a note (under the plot), e.g.

Missing mutations data: study a
Missing copy number alterations data: study a, studyb

**Comment by alisman** [comment]
I think the alert at the top of this screenshot was an attempt to address this in a general way.  Is this insufficient? 

![image](https://user-images.githubusercontent.com/186521/59884420-4724b700-9386-11e9-8db3-dd9fb8db79e5.png)

**Comment by jjgao** [comment]
I think it's not specific. We should say "Bladder (BGI 2013) and PAAC (JHU) has no CNA data". And a message on top is not noticeable enough in this case.

I remember we had tracks per study to indicate whether mutations and cna data exist. Maybe we need that back...

**Comment by pieterlukasse** [comment]
The current message also only talks about "profiled for some ...genes" while this is about a study not having a CNA profile at all. The current message does not cover this well.

**Comment by pieterlukasse** [comment]
The UI @jjgao is referring to can be seen here https://github.com/cBioPortal/cbioportal/issues/1514...although only partly since in this issue it is not working completely.

**Comment by alisman** [comment]
Putting this here for record
![image](https://user-images.githubusercontent.com/186521/59930652-47b65f80-9411-11e9-9c87-6704a81471a1.png)

**Comment by alisman** [comment]
@jjgao it seems like bringing back tracks is safest best. 
I think track labels should say "Has mutation data" and we should figure out how best to call attention to the negative case.

**Comment by alisman** [comment]
@kalletlak lets bring back the "tracks" on cancer type summary (implement them in Victory).

**Comment by kalletlak** [comment]
@jjgao @alisman do we want to support all data types or is it just `Mutation Data` and `CNA data` as. shown in above image?
And do we also want to show `Cancer type`?

**Comment by alisman** [comment]
@kalletlak not sure what you mean "show Cancer Type"?  you did get me to thinking about what happens when user chooses to group by cancer type (maybe that's what you meant?).   In this case, it possible that a some of the studies in a single bucket would have profiles and others not, so the "tracks" approach doesn't work.  @jjgao @pieterlukasse do you remember how the old feature handled this?  any input? 
As for tracks for other data types, I will defer to @jjgao on that

**Comment by pieterlukasse** [comment]
@alisman good question....I'm not sure. Anyway, I think the exact same banner could be shown. It just makes it clear that some studies are not contributing to the plot because they don't have the selected profile data.

**Comment by alisman** [comment]
@pieterlukasse we discussed this issue yesterday.  @kalletlak, add any detail i'm missing but the solution, when cancer type is selected, is to adjust the denominator so that un profiled samples do not count as unaltered.

**Comment by jjgao** [comment]
@kalletlak @alisman and I had a call. We will recalculate the denominator based on whether a sample is profiled as well as the gene panel information. When the denominator is 0, we will indicate that.
