### ISSUE TITLE
Add link to NG-CHM Compendium on Heatmap tab

### ISSUE THREAD

**Issue by ChrisWakefield** [cBioPortal/cbioportal#6306]
(Based on conversation with Rehan Akbani and Niki Schultz:)
insert a fourth button in the Heatmap drop-down. Clicking on the button would show a disclaimer that the user is linking out to an external website and their gene and sample selections may not be the only ones represented in the map. Once the user acknowledges the disclaimer, NG-CHM would open up (perhaps in a new browser tab).

**Comment by ChrisWakefield** [comment]
You can assign this to me.

**Comment by ChrisWakefield** [comment]
Here I am months later.
@jjgao @zhx828 Is there (what is) a preferred way to display a modal confirmation dialog?  Recall that I am to show a disclaimer message before opening the NGCHM.

I've found some existing use of <Modal ...> and been trying to get that to do what I need, but I'm trying to avoid creating whole new files and new classes just for this.  It seems like it should be simple, but my inexperience with the react-js stack, etc is leaving me puzzled.

**Comment by jjgao** [comment]
adding @alisman to this and see he has suggestions.

**Comment by ChrisWakefield** [comment]
@jjgao @zhx828 @alisman Thanks.  I think I've found a solution that should be ok.  It did require more head-banging.

**Comment by ChrisWakefield** [comment]
@jjgao or @zhx828 @alisman 

I'm attempting to test my changes against the rc branch (export BRANCH_ENV=rc).
Even though everything works with the same changes applied to master, I'm getting this error from rc.cbioportal.org well before getting to any of my code:

{"req":{"method":"GET","url":"https://rc.cbioportal.org/api/studies/blca_tcga_pub/molecular-profiles","headers":{"accept":"application/json"}},"xhr":{},"text":"<!doctype html><html lang=\"en\"><head><title>HTTP Status 500 – Internal Server Error</title>
...
that eventually gets to:
bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column &#39;genetic_profile.GENERIC_ASSAY_TYPE&#39;
...

Any suggestions?  Do something different? Wait?  Submit PR anyway?
Thanks, Chris
