### ISSUE TITLE
Gene length issues

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#6307]
The last seed DB in #13 seems to have longer gene LENGTH values for some of the genes. At least, longer than would be expected if processing on the the "GENCODE Basic" transcripts. 

The cause is likely to be due to processing of Gencode v25 "Comprehensive gene annotation" file instead of the "Basic gene annotation" file from http://www.gencodegenes.org/releases/25lift37.html. See also http://www.ensembl.org/Help/Glossary?id=500

One example of "Basic gene annotation" length difference from what is now in our seed DB:
- gene `AARS` is now reported with length  4,498 in the seed DB while the "GENCODE Basic" transcript length is 3,477 (see http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000090861;r=16:70252295-70289543)

Discussion: by using the "Comprehensive gene annotation" file, we are introducing an unfavorable bias towards genes where there are more non-validated entries. These genes end up with a longer length that is partly built up by very uncertain "transcripts". The longer length will result in a lower  `#mutations/bp` rate in cBioPortal, affecting some of the views in the portal (like the study view). 

Questions: if we use the "Basic gene annotation" file, will this result in more genes not having the LENGTH info in the DB? Or do all genes in GENCODE have at least a "Basic" transcript that can be used for the length?

**Comment by jjgao** [comment]
logged in #6308
