### ISSUE TITLE
remove LENGTH in gene table

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6308]
- [x] Verify that it is no longer used in frontend? (it was used in Mutated Genes tab of study view)
- [x] Remove LENGTH in gene table
- [x] Remove it from API
- [x] Remove it from import code

**Comment by inodb** [comment]
I checked all references for `length` field of the `Gene` model in the frontend. Doesn't seem to be in use

**Comment by pieterlukasse** [comment]
@inodb , @jjgao one scenario I can think of: what happens when the gene does not have pfam info but we want the lollipop view in mutation mapper? What is the length of the "protein model" in this case?

**Comment by pieterlukasse** [comment]
Maybe also add a checkbox to remove it from backend / import scripts like /cbioportal/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportGeneData.java. Quite some complex code there to get the length right.

**Comment by jjgao** [comment]
@pieterlukasse I think we should fix the protein length data in genome nexus (e.g. https://github.com/cBioPortal/cbioportal/issues/1378). Gene length is not reliable anyway.

Good point about the import scripts.

**Comment by Sjoerd-van-Hagen** [comment]
@inodb I don't think this has to be in 3.1, does it?
