### ISSUE TITLE
'Three dots' icons of oncoprint vary in size depending on heatmap tracks [backlog]

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#6313]
The 'three dots' icons to the right of track names in oncoprint are 17x17px or 24x24px depending on whether there are or are not heatmap tracks present, respectively.
![Screenshot from 2019-06-22 13-46-57](https://user-images.githubusercontent.com/745885/59963541-9a1c7c80-94f4-11e9-9feb-8b1fda114040.png)
![Screenshot from 2019-06-22 13-50-02](https://user-images.githubusercontent.com/745885/59963545-abfe1f80-94f4-11e9-98d9-439eb692feea.png)

No biggie, but can be placed on the backlog.

**Comment by jjgao** [comment]
I was thinking of only showing the three dots when hovering a line/track. That way, the interface will be cleaner and it'll make the issue documented here less obvious.

**Comment by jjgao** [comment]
@adamabeshouse is it possible to how the three dots when hovering a track? Could this be a good first issue?

**Comment by adamabeshouse** [comment]
good first issue, quite easy @jjgao

**Comment by jjgao** [comment]
Ok, let's hide these dots by default and show them when hovering over.
