### ISSUE TITLE
Some attribute is 0% freq before filtering

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6315]
Two issues:

-  `Initial Patient Weight` duplicated
- One of them is 0%

https://www.cbioportal.org/study/summary?id=laml_tcga_pub%2Csarc_tcga_pub%2Cblca_tcga_pub_2017%2Cblca_tcga_pub%2Cbrca_tcga_pub2015%2Cbrca_tcga_pub%2Ccoadread_tcga_pub%2Cstes_tcga_pub%2Cgbm_tcga_pub2013%2Cgbm_tcga_pub%2Chnsc_tcga_pub%2Ckich_tcga_pub%2Ckirc_tcga_pub%2Cluad_tcga_pub%2Clusc_tcga_pub%2Clgggbm_tcga_pub%2Cov_tcga_pub%2Cthca_tcga_pub%2Cpcpg_tcga_pub%2Cprad_cpcg_2017%2Cprad_tcga_pub%2Cstad_tcga_pub%2Cucec_tcga_pub

![image](https://user-images.githubusercontent.com/840895/60026989-9ca0e280-966a-11e9-8ee8-a9b5f3fa5c10.png)

**Comment by jjgao** [comment]
The first issue is solved. The second still stands for `Specimen Current Weight`

![image](https://user-images.githubusercontent.com/840895/76637859-dcbe3300-6521-11ea-8ca3-8472d992d92f.png)

**Comment by kalletlak** [comment]
@jjgao looks like none of the queried studies have data for `Specimen Current Weight`. Two studies(`blca_tcga_pub_2017` and `kich_tcga_pub`) have this attribute meta defined but no data.

**Comment by jjgao** [comment]
Thanks, @kalletlak. I created an issue on datahub: https://github.com/cBioPortal/datahub/issues/1154
