### ISSUE TITLE
Merged gene track in OncoPrint not shown

### ISSUE THREAD

**Issue by paulcwvandijk** [cBioPortal/cbioportal#6319]
When  creating a merged gene track in OncoPrint with OQL in the public portal and you click "add genes" the result is not shown in OncoPrint (see screenshot):
http://bit.ly/2X6nslv

![Screenshot 2019-06-25 at 12 37 09](https://user-images.githubusercontent.com/44695112/60092115-7a7c9280-9746-11e9-8bc7-1f904ebf19d4.png)

Desired solution:
- Oncoprint should show the merged gene track like expected and as has been documented at https://www.cbioportal.org/oql

**Comment by paulcwvandijk** [comment]
@jjgao @adamabeshouse

**Comment by adamabeshouse** [comment]
AFAIK we don’t currently support that for heatmap tracks

**Comment by jjgao** [comment]
Maybe we should just extract the genes for the heatmap tracks.

**Comment by adamabeshouse** [comment]
yeah that makes sense
