### ISSUE TITLE
Mouse Support no longer working for Mutations tab / table

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6326]
We are relying on Genome Nexus to draw the lollipop on the mutations tab. Various annotations are also coming from Genome Nexus, which are all human based.

To support using cBioPortal for mouse genomes we'll have to set add some documentation to set up a mouse instance of genome nexus:

https://github.com/genome-nexus/genome-nexus-importer/issues/22

**Comment by pieterlukasse** [comment]
CC @Sjoerd-van-Hagen , @oplantalech

**Comment by pieterlukasse** [comment]
@inodb was @sandertan 's work to support hg38 already merged? This would be a similar effort, right?

**Comment by inodb** [comment]
@pieterlukasse 	yes @sandertan 's excellent work on hg38 has been merged ✅  - supporting mm10 would be a similar effort. That would fix the lollipop plots

I guess annotations for oncokb, hotspots and most other annotations coming through genome nexus won't work. The VEP annotations might work if you would run a local VEP with mouse genome: https://github.com/genome-nexus/genome-nexus-vep

**Comment by Sjoerd-van-Hagen** [comment]
I think this would be a nice job for @SRodenburg !

**Comment by SRodenburg** [comment]
Can be closed
