### ISSUE TITLE
Legend items on cancer type summary are not well spaced

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6329]
![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/5c981f3c-f60e-4e48-89c4-1733c812040d)

See how the dot for last legend item is actually closer to preceding text?  Lets see if we can improve this.
@adamabeshouse can you advise @dippindots.  Maybe your new component would help?

https://www.cbioportal.org/results/cancerTypesSummary?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=coadread_tcga_pub&case_set_id=coadread_tcga_pub_nonhypermut&clinicallist=PROFILED_IN_coadread_tcga_pub_rna_seq_mrna_median_Zscores&data_priority=0&gene_list=KRAS%2520NRAS%2520BRAF&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=coadread_tcga_pub_rna_seq_mrna_median_Zscores&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&show_samples=false&tab_index=tab_visualize

**Comment by alisman** [comment]
This own is even worse:

https://cbioportal.org/results/cancerTypesSummary?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=.1&cancer_study_list=coadread_tcga_pub&case_set_id=coadread_tcga_pub_nonhypermut&clinicallist=PROFILED_IN_coadread_tcga_pub_rna_seq_mrna_median_Zscores&data_priority=0&gene_list=KRAS%2520NRAS%2520BRAF&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=coadread_tcga_pub_rna_seq_mrna_median_Zscores&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&show_samples=false&tab_index=tab_visualize

**Comment by adamabeshouse** [comment]
luckily this is something victory does handle :D https://formidable.com/open-source/victory/docs/victory-legend/#gutter

**Comment by dippindots** [comment]
Oh, that's perfect, thanks @adamabeshouse !

**Comment by dippindots** [comment]
@alisman @adamabeshouse There is a ticket in victory's repo describes the same issue: https://github.com/FormidableLabs/victory/issues/864. Seems like it is not their priority issue and it is not easy to fix. Should we just add more space between the legend items for now?

**Comment by adamabeshouse** [comment]
so gutter isnt doing the trick?

**Comment by dippindots** [comment]
@adamabeshouse actually every legend has a default gutter value as 10; But the length of the item is not correct, so the gutter cannot help with that, can only increase the space between two items.

**Comment by adamabeshouse** [comment]
oh i see
