### ISSUE TITLE
Add tutorial slide urls to github (in addition to gdrive)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6333]

**Comment by alisman** [comment]
@tmazor what are the urls for the slides on github?

**Comment by tmazor** [comment]
@alisman i just added you the PR -- it's still open. can you approve?
https://github.com/cBioPortal/cbioportal/pull/6332

**Comment by tmazor** [comment]
I'd like to keep the embedded tutorial slides still pointing to google slides, because those are easier to keep up to date. Can we just add this as a second link at the top of the page, next to the link to the google drive folder?

**Comment by tmazor** [comment]
Let's change:
View tutorial slides below or download slides here (link to google drive folder).

To:
View tutorial slides below or download from google drive (existing link to google drive folder) or GitHub (link to new folder).

**Comment by alisman** [comment]
@dippindots you can use the config property "skin_documentation_baseurl".  tutorials are inside "docs/tutorials" folder at that root.

**Comment by tmazor** [comment]
@dippindots one small request - can you also add an underline to the words that are links? because the text is already blue, the links don't really stand out, and I think an underline might help. thanks!

**Comment by inodb** [comment]
Maybe good to have a link below each slidedeck as well? So a link that links directly to that particular tutorial. The link at the top is a little hidden imo

**Comment by tmazor** [comment]
good idea @inodb  -- let's do that!

**Comment by dippindots** [comment]
Thanks @tmazor @inodb ! All good ideas! I will do that.
