### ISSUE TITLE
group comparison header extends wider than browser window

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6343]
When the data on group comparison tabs extends wider than the screen, the header also extends and goes off screen.

See clinical or mutations or copy-number in this session:
https://www.cbioportal.org/comparison/mutations?sessionId=5cf6aa24e4b0ab4137874305

The header should remain fixed to the width of the screen and the figures/tables below should scroll separately.

**Comment by Dharmesh-Poddar** [comment]
@tmazor  can I work on it?

**Comment by jjgao** [comment]
@Dharmesh-Poddar sure, thanks for volunteering!

**Comment by tmazor** [comment]
Looks fixed!
