### ISSUE TITLE
tweaks to list of groups

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6344]
Two thoughts to perhaps improve the layout of the list of groups.

- Move "Select All | Deselect All" to directly follow the last group, rather than appearing as a separate column of text. This would leave more horizontal space for the group names, which would enable...

- Allow group names to be longer before truncation. We gained back lots of space by removing the words "patient" and "sample", so let's take advantage of that by allowing group names to be longer before they get truncated.

![image](https://user-images.githubusercontent.com/10508276/60459062-270ab880-9c0e-11e9-8001-fc0281cb162f.png)
https://www.cbioportal.org/comparison/overlap?sessionId=5cf6aa24e4b0ab4137874305

**Comment by jjgao** [comment]
related to https://github.com/cBioPortal/cbioportal/issues/6222

**Comment by Dharmesh-Poddar** [comment]
@jjgao @tmazor can I work on it?

**Comment by jjgao** [comment]
@Dharmesh-Poddar sure. Thanks.

Let's also move the "Exclude..." dropdown to the right of the same row as the study name "MSK-IMPACT..." so that we have more space for the groups.

**Comment by adamabeshouse** [comment]
Thanks for your interest @Dharmesh-Poddar , since this issue is an internal priority we're going to take it, but we encourage you to contribute on other issues.
