### ISSUE TITLE
change the login button

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6352]
Currently:
![image](https://user-images.githubusercontent.com/840895/60612442-9f03ea80-9d96-11e9-9727-a9da4533d422.png)

Desired:
![image](https://user-images.githubusercontent.com/840895/60612455-a4613500-9d96-11e9-86c0-08c32554ad6b.png)

... only if it's easy to do.

**Comment by Dharmesh-Poddar** [comment]
@jjgao can I work on it

**Comment by jjgao** [comment]
@Dharmesh-Poddar yes, I assigned this to you :)

**Comment by Dharmesh-Poddar** [comment]
@jjgao is there any community channel(like gitter) for cbioportal to discuss issues?

**Comment by jjgao** [comment]
@Dharmesh-Poddar we use slack: https://slack.cbioportal.org/

**Comment by Dharmesh-Poddar** [comment]
Thanks @jjgao  for the response..

**Comment by inodb** [comment]
still an issue

**Comment by jjgao** [comment]
I am closing this.
