### ISSUE TITLE
ClinVar column tweaks

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6353]
- [x] Change the head from "ClinVar ID" to "ClinVar"
- [x] Instead of displaying the ID, is it possible to display "Interpretation"?
https://www.ncbi.nlm.nih.gov/clinvar/variation/163380/
![image](https://user-images.githubusercontent.com/840895/60351019-d8051f00-9992-11e9-836c-36da8944bfdc.png)
- [x] make it available in patient view

cc'ing @inodb

**Comment by inodb** [comment]
@jjgao: for the interpretation one caveat is that ClinVar is not cancer specific. Is that an issue you think?

**Comment by jjgao** [comment]
@inodb I think that's fine and the interpretation is still useful.

Maybe it's better to keep it in a separate column (instead of adding to Annotation) because of that.

**Comment by Unberath** [comment]
The ClinVar column could be added to the patient view mutation table as well.
Or is there a reason why the column was only added to the results view?

**Comment by jjgao** [comment]
@Unberath good catch. It should be available in the patient view.

**Comment by leexgh** [comment]
@jjgao @Unberath I will work on it

**Comment by inodb** [comment]
@Unberath it is enabled on the patient view now as well. Thanks for fixing that @leexgh !

**Comment by leexgh** [comment]
This is done. 
![image](https://user-images.githubusercontent.com/16869603/122264501-9b939c00-cea5-11eb-8088-dfe95fe69c52.png)
