### ISSUE TITLE
should we reconsider the hamburger icon?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6356]
I find it confusing to duplicate the actions in icon and dropdown of the hamburger icons.

![image](https://user-images.githubusercontent.com/840895/60625618-54926600-9db6-11e9-9afd-5a04c18ced2c.png)

I think I have seen other website doing this but only list additional items in the hamburger. Maybe we should do the same, ie. having infrequently used items in the hamburger only, e.g. for [this](https://github.com/cBioPortal/cbioportal/issues/5819)? When there is no item, we could just hide it.

@adamabeshouse @tmazor @schultzn

**Comment by schultzn** [comment]
Good idea… I agree.

**Comment by adamabeshouse** [comment]
how about using a question mark icon instead?

**Comment by zhx828** [comment]
I have a running instance to elaborate JJ's suggestion, the hamburger icon is removed for pie chart but kept for bar chart to include the Custom bins feature.
https://cbioportal-frontend-pr-2518.herokuapp.com/study/summary?id=acc_tcga_pan_can_atlas_2018

**Comment by adamabeshouse** [comment]
how about we run a google analytics experiment to settle it once and for all?

**Comment by jjgao** [comment]
@zhx828 thanks for the implementation.

@adamabeshouse I don't think we need a Help icon since we already have a tooltip on each icon. I am also not sure if running analytics would help -- say if we found 50% (or even more) users uses the hamburger icon, does that mean it's a good choice? I think providing two entries for each of the options in a small interface is confusing. Annd I think the user can be trained if we provide only one option. I would prefer the hamburger icon onnly over the current solution for simplicity but I get Niki's point about two clicks. Since we don't have so many icons after all and we can move future non-critical icons into the hamburger icon, I would vote for not duplicate the items.

@cBioPortal/product any comments?

**Comment by adamabeshouse** [comment]
if we found users overwhelmingly prefer the hamburger then we would keep it there. Also its not two clicks its one click, the menu opens on rollover.

**Comment by tmazor** [comment]
I agree that its confusing to have buttons shown twice.

I think I also prefer the hamburger menu over individual buttons in general, although I wonder how well that will work for something like the download button, which currently brings up a menu of its own. That said, I don't feel super strongly about the hamburger menu vs individual buttons as the ultimate solution. I would also be fine with using the hamburger menu for some buttons and keeping others outside the menu. But I definitely strongly support not duplicating any buttons.

**Comment by jjgao** [comment]
Let's try to see how it look like when we have all in the dropdown. @adamabeshouse @zhx828 could you mock it up. Maybe @zhx828 can modify it in your PR? For download, is it possible to have a submenu for the different options?

**Comment by jjgao** [comment]
Actually, let's leave `info`, `reset filter`, and `close` buttons and try to move all others into the dropdown? @zhx828

**Comment by zhx828** [comment]
@jjgao will do in my pr.

**Comment by zhx828** [comment]
@jjgao @adamabeshouse @tmazor @schultzn I have updated the instance base on JJ's suggestion. Now only info/reset/delete icons are in the header, the rest icons are moved to hamburger icon. The download also has a submenu but the functionality hasn't been implemented yet. Please take a look and give us some feedbacks. https://cbioportal-frontend-pr-2518.herokuapp.com/study/summary?id=acc_tcga_pan_can_atlas_2018

**Comment by adamabeshouse** [comment]
@zhx828 i think it looks great!

**Comment by tmazor** [comment]
I like it!

@zhx828 one thing I noticed is that the download menu always opens to the right, which doesn't really work for charts on the right side of the window.

**Comment by zhx828** [comment]
@tmazor yeah, I noticed too. There are few more things need to be considered when the actual implementation is done. I didn't do any of that just in case we want to change the prototype.

**Comment by schultzn** [comment]
I like it this way. Thanks!

**Comment by zhx828** [comment]
@jjgao @tmazor @schultzn @adamabeshouse this is now deployed in production.
