### ISSUE TITLE
Download of the pie chart should list the categories and frequency instead of the full clinical data

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6357]

**Comment by jjgao** [comment]
@zhx828 I don't know if I agree. I think downloading the full clinical data for an attribute is useful too (it may be more useful). Maybe we could provide both options: `summary data` and `full data`?

**Comment by zhx828** [comment]
I think Niki's argue is that we keep the consistency. We do only download
the summary data for mutated genes table. But let me know how you think.
Offer both options are easy to do as well.

**Comment by jjgao** [comment]
I think we should offer both options. I have used it a couple of time. It's convenient.

@schultzn do you think that'd be ok?

(for mutated genes, let's only provide summary data.)

**Comment by schultzn** [comment]
Both is fine!
