### ISSUE TITLE
making all treatments available in Plots tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6366]
change the implementation of  treatment data in Plots tab so that it does not depend on oncoprint tab, ie. making all treatments available in Plots tab.

**Comment by Sjoerd-van-Hagen** [comment]
The current behaviour is consistent with genesets and genes where also not the whole list is shown but only the genesets and genes that were selected earlier. We should change the behaviour for all of them, and of course you would need some search box instead of the dropdown we have now.

We should not implement this for 3.1.0.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen In general I agree. I think Plots tab really belongs to study view instead of the query/results page. That's a direction we will explore.

That said, for the Pltos tab in the result page, I would compare the response data with clinical data (all clinical attributes are available in Plots tab). The query/results page is centered around querying genes and other data types currently supplementing that. I think it's ok not to allow querying all genes in Plots tab.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao I think we agree. My main point is that we should release 3.1 as soon as possible by focusing on fixing bugs and postponing improvements to a later time.

When I was testing the waterfall plot I found that adding a gene is a bit of a pain, because if you do this, the plots tab gets reinitiated and you have to make the same selections again. This is not really a problem of the gene not appearing in the dropdown but more of the mechanism for adding it via the modify query button. My suspicion is that this might actually be quite tricky to resolve.

For the treatments it actually works better. I can just go to the oncoprint, add a treatment track and use it in the plots tab without losing the settings I put before.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen agreed. We are thinking of changing the Modify Query interface and make it a left panel for a more interactive interface, which will allow users to add to remove genes easily. We will do some mockup and get back to the community for feedback.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao so you want to use the same menu as is used in the oncoprint to select the treatments, correct? Otherwise it does not make sense because the list will be to long to use a simple drowndown menu.

**Comment by jjgao** [comment]
> @jjgao so you want to use the same menu as is used in the oncoprint to select the treatments, correct?

I think that makes sense.

**Comment by Sjoerd-van-Hagen** [comment]
And then use that to populate the dropdown? Because you may be interested in looking at multiple treatments, which have a common target maybe, but you can only plot them one at a time.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen I think having two steps is not ideal. Maybe it's ok to have this drop of the long list and allow them select one treatment only as long as the user can search?

![image](https://user-images.githubusercontent.com/840895/67958673-ecba2380-fbcd-11e9-9446-3efd27daf28f.png)

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen just brainstorming...

- how about we list the ones selected by the oncoprint first? That way, we don't loss any of the current functionality but also able to search for all drugs.
- we can also remember the previous user search, ie. if BRAF was search, the same search term will be there by default in the same session.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao That would improve things but I think it is still a bit more clunky than using the dropdown with an extra button to do a full search to add items to the dropdown. I also feel that keeping the current dropdown in place makes it more uniform across the different data types. The '...'-button is just an additional element in that case.

Maybe we should involve the product team in this?

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen if we prioritize the drugs that are in the oncoprint as well as the drugs the user searched, I am not sure it would be clunkier than the '...'-button. I just don't like the idea to have two step for selecting one drug. It maybe a good idea to add others to this conversation...

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao I still don't like it. You would get the prioritized drugs on top, then the rest will be sorted alphabetically, which is to me is not user-friendly. 

If you select only one drug, that drug would be the only on in the dropdown, so automatically selected, so it would be only one step. If you select multiple drugs, this allows you to cycle through them in the drop down, as you would do now. To me, this seems quite efficient. As an added bonus, I expect less work is required compared to having this component + the prioritization.

@cBioPortal/product what are  your thoughts on this?

**Comment by tmazor** [comment]
I think @jjgao 's suggestions make a lot of sense. This presentation would be similar to how, for example, the font menu in google docs works: recently used fonts appear at the top and the rest are in alphabetical order below. I think this is a fairly intuitive way to present a list of options.

If we do this, we could also apply it to the clinical tracks list - if any clinical attribute is added to oncoprint, it can appear at the top of the list of clinical options.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen any more thoughts on this?

**Comment by Sjoerd-van-Hagen** [comment]
Let's revisit when we have the resources to work on this, unless you want to take it on @jjgao ?

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen we can take this.

@alisman @dippindots since we are working on a solution for generic assay, we can use this one to prototype. 

@alisman do we have an issue for adding generic assay profile into Plots tab?
