### ISSUE TITLE
hrrs configuration crashes with properties.EXAMPLE

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6368]
- [ ] Would be good to have the default for hrrs be:

    `hrrs.enable.logging=false`

    it should work when all these properties are missing from the properties file:

    ```
    hrrs.logging.filepath=
    hrrs.enable.logging=
    ```
    
    This is useful for people deploying a new version of the portal. They won't have to update their properties file

- [ ] In the EXAMPLE properties file good to mention what hrrs is. Mention that it is for debugging and probably good to comment out by default? The EXAMPLE file is included automatically as the default properties file when no properties file is given so better to not assign any values there

**Comment by pvannierop** [comment]
As I stated in my duplicate issue report there is also this issue:

>2. When setting hrrs.enable.logging=false the property hrrs.logging.filepath is still required. The implementation better not require hrrs.logging.filepath to be set, when not logging.
