### ISSUE TITLE
Get rid of cancer study short names

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6375]
Currently the short names are used only in Cancer Type Summary and Expression tabs, but they are not consistently curated. Also, we are not using the short names in other places. Should we switch to the full names (use ... if too long) and get rid of the short name? This will reduce some burden for curation... @cBioPortal/product 

- [ ] remove from db
- [ ] remove from api
- [x] remove from src/pages/resultsView/ResultsViewPageStoreUtils.ts
- [x] src/pages/resultsView/expression/ExpressionWrapper.tsx
- [x] src/shared/cache/ClinicalDataCache.ts
- [x] change to full name in Cancer Type Summary and Expression tabs
  - use ... if too long and hovering to show the full name ; New rules: use ... before the parenthesis.
- [ ] Notify Curation team after changing backend changes

For @cBioPortal/curation, once this is done, we can get rid of the short name field.

**Comment by jjgao** [comment]
@cBioPortal/product any objections?

**Comment by Sjoerd-van-Hagen** [comment]
I think this is fine. I assume with the ... you can hover over it and see the full name anyways, right?

**Comment by jjgao** [comment]
@jagnathan maybe you can help with this when you have a chance? I can explain some more details.

**Comment by jagnathan** [comment]
Sure @jjgao. Sounds good.

**Comment by jagnathan** [comment]
Will work on it in Jan.

**Comment by jjgao** [comment]
Thanks, @jagnathan . I assign the first milestone next year. Happy to fill you in more details before you work on it.

**Comment by jagnathan** [comment]
/cbioportal-frontend/packages/cbioportal-utils/src/model/MyCancerGenome.ts has references to cancer type. 

ExtendedSample interface has cancerType has one of the properties.

**Comment by jagnathan** [comment]
Expression tab has been removed. Now it is shown in Plots tab.

**Comment by jagnathan** [comment]
Instead of using Cancer study short name from `SHORT_NAME` varchar(64) NOT NULL in table  `cancer_study`, to use `DESCRIPTION` varchar(1024) NOT NULL.

If the length of DESCRIPTION is too long,  use  "..."

**Comment by jagnathan** [comment]
<img width="346" alt="Cancer Study Full name" src="https://user-images.githubusercontent.com/37613906/103937067-3ec1d780-50f6-11eb-9db1-c20cd53342b3.png">

**Comment by jagnathan** [comment]
UI changes with full name instead of short name. Will make changes in the backend and frontend to remove short name completely.

**Comment by jagnathan** [comment]
Using ... for long names in charts and showing a tooltip is complex as per Aaron.

**Comment by jagnathan** [comment]
If the length of NAME is too long ., > 50 characters,  use  "..." No tool tip will be shown.

**Comment by jagnathan** [comment]
According to JJ, let’s not count the part in parenthesis, so in this case, for Ampullary Carcinoma (Baylor College of Medicine, Cell Reports 2016), only count “Ampullary Carcinoma”. If this part is >50 we shorten it. And we alway append the parenthesis part back.

Also, let’s only shorten for x/y-axis labels but not for legend of oncoprint or plots.

**Comment by jagnathan** [comment]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/37613906/104794894-ba67f800-5778-11eb-9c89-d1102e2b95f4.png">

**Comment by jagnathan** [comment]
https://github.com/cBioPortal/cbioportal/pull/8322

Backend change PR into rc branch.

**Comment by jagnathan** [comment]
to do:  notify Curation team after backend changes are merged.
