### ISSUE TITLE
Update deployment document

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6382]
Base on the experience we got from a GSoC project, cBioPortal deployment does not work in java 12 and not mysql 8.

javax.annotation was removed from java 11.
you will run into mysql connector issue in mysql 8.

We should update our document to reflect that until we full support higher version.

**Comment by sheridancbio** [comment]
Issue added to backend pipeline scrum backlog candidates cc: @n1zea144

**Comment by inodb** [comment]
Since we're recommending people to use docker install now i think it's fine to close this
