### ISSUE TITLE
rendering markdown for clinical attributes

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6383]
@PichaiRaman requested that we support linkout for any URLs in the Clinical Data tab on Study View. To generalize it, it would be good to support markdown. Let's do it for both Study View and Patient View.

cc'ing @alisman

**Comment by alisman** [comment]
@PichaiRaman @jjgao could we see an example of existing data that has urls in it?

**Comment by jjgao** [comment]
@alisman we don't have that on public portal. I thinnk we may have to build this feature first and data will come.

**Comment by jjgao** [comment]
I am wondering if we can "customize" markdown so that we can embed some more meta data, e.g. whether the url should be rendered as an i-frame. If we can do that, then we can provide a general solution for i-frame tabs (we can remove some of our code for msk slide viewer).

**Comment by alisman** [comment]
Lets discuss live, b/c i'm still not totally understanding

**Comment by jjgao** [comment]
Here are a few examples:

- `[example](https://example.com)` -> [example](https://example.com)
- `https://example.com` -> https://example.com
- `[example|i-frame](https://example.com)` -> this will generate a new tab named example to iframe https://example.com

**Comment by jjgao** [comment]
superseded by https://github.com/cBioPortal/cbioportal/issues/7239
