### ISSUE TITLE
oncoprint clinical track tooltip extends offscreen

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6393]
![image](https://user-images.githubusercontent.com/10508276/61408310-be7a3780-a8ad-11e9-8c06-b8407c0a0f54.png)

To replicate, add "International Classification of Diseases for On..." in this session:
https://www.cbioportal.org/results/oncoprint?session_id=5d2f80d9e4b0ab413787bf78

**Comment by adamabeshouse** [comment]
there are still issues with tooltip placement when scrolling down the page
