### ISSUE TITLE
oncoprint add clinical track menu doesn't have tooltips for truncated names

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6394]
Variable names can be truncated in the Add Clinical Track menu, but there is no way to see the full name. Let's show the complete name on hover. See example below where two tracks are indistinguishable based on the text that is shown.

![image](https://user-images.githubusercontent.com/10508276/61408435-013c0f80-a8ae-11e9-9c0a-04eef582af0b.png)
https://www.cbioportal.org/results/oncoprint?session_id=5d2f80d9e4b0ab413787bf78

**Comment by adamabeshouse** [comment]
@alisman I gave this one some work and I'm stumped. I think it needs your CSS expertise. could you give it a shot?

**Comment by dippindots** [comment]
@adamabeshouse Seems like this issue has already been fixed?
![image](https://user-images.githubusercontent.com/15748980/66087353-2ce1a400-e545-11e9-81b6-54b9651cab58.png)

**Comment by adamabeshouse** [comment]
@tmazor can you confirm its working on your end as well?

**Comment by tmazor** [comment]
yes it's working for me @adamabeshouse
