### ISSUE TITLE
group comparison mutations tab shows an error

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6395]
Some group comparison sessions are loading fine, so this isn't a universal issue, but I don't know how widespread it is.

![image](https://user-images.githubusercontent.com/10508276/61409075-722ff700-a8af-11e9-96c6-9afde0702c37.png)

![image](https://user-images.githubusercontent.com/10508276/61409089-7c51f580-a8af-11e9-88a8-7dc70a209fbd.png)

https://www.cbioportal.org/comparison/mutations?sessionId=5d26299ce4b0ab413787aa79

**Comment by alisman** [comment]
@kalletlak this CURL returns 500.  NumberFormatException.  Can you take a look?

curl 'https://www.cbioportal.org/api/mutation-enrichments/fetch?enrichmentType=SAMPLE' -H 'origin: https://www.cbioportal.org' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'referer: https://www.cbioportal.org/comparison/mutations?sessionId=5d26299ce4b0ab413787aa79' -H 'authority: www.cbioportal.org' -H 'cookie: _ga=GA1.2.1764028159.1557761784; mp_96b84420a1a32e448f73e7b9ffccebdb_mixpanel=%7B%22distinct_id%22%3A%20%2216ab1d6770f3af-0a7842b0ab7e5a-37607603-1aeaa0-16ab1d67710b0f%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Fgithub.com%2FcBioPortal%2Fcbioportal%22%2C%22%24initial_referring_domain%22%3A%20%22github.com%22%7D; mp_a37bac8664a332481726ae49603f9f63_mixpanel=%7B%22distinct_id%22%3A%20%22fc475e52-7243-4961-acd4-23e53d287e76%22%7D; _gid=GA1.2.271449033.1563204184; results-tab=null; JSESSIONID=79858637B175E72BD767FDFD32982C8A; _gat=1' --data-binary '[{"name":"(A) Methylated","molecularProfileCaseIdentifiers":[{"caseId":"P01_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P02_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P05_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P05_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P06_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P09_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P09_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P10_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P10_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P11_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P11_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P16_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P16_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P17_Pri_A","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P17_Pri_B","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P17_Pri_C","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P18_Pri_A","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P18_Pri_B","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P18_Pri_C","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P18_Pri_D","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P18_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P21_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P21_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P24_Rec2","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P25_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P25_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P26_Pri_A","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P26_Pri_B","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P26_Rec1_A","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P26_Rec1_B","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P27_Pri_A","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P27_Pri_B","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P27_Rec1_A","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P27_Rec1_B","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P28_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P28_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P29_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P29_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"}]},{"name":"(B) Unknown","molecularProfileCaseIdentifiers":[{"caseId":"P04_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P04_Rec1","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P04_Rec2","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P04_Rec3","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P07_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P07_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P08_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P08_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P12_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P12_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P15_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P15_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"}]},{"name":"(C) Unmethylated","molecularProfileCaseIdentifiers":[{"caseId":"P01_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P02_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P06_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P13_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P13_Rec","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P17_Rec1_A","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P17_Rec1_B","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P17_Rec1_C","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P17_Rec1_D","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P24_Pri","molecularProfileId":"lgg_ucsf_2014_mutations"},{"caseId":"P24_Rec1","molecularProfileId":"lgg_ucsf_2014_mutations"}]}]' --compressed

**Comment by jjgao** [comment]
Karthik Kalletla [3:21 PM]
@jj regarding https://github.com/cBioPortal/cbioportal/issues/6395. looks like all samples are altered. this is throwing error while calculating p-values. should I ignore genes where either all cases are altered or unaltered?

**Comment by jjgao** [comment]
@kalletlak is it possible to return na for these genes?
