### ISSUE TITLE
JS error message when clicking "Modify Query"

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#640]
![image](https://cloud.githubusercontent.com/assets/840895/11915024/b61e3b78-a662-11e5-8c89-fc6a43d0673d.png)

**Comment by adamabeshouse** [comment]
I've encountered this error before but now I can't replicate it. Has it been fixed?

**Comment by adamabeshouse** [comment]
Can no longer replicate in chrome, firefox, or safari.
