### ISSUE TITLE
Improve the current patient view to incorporate cfDNA

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6401]
cfDNA provides an approach for real-time noninvasive monitoring of treatment response and cancer progression. For example, MSK-ACCESS has received New York State approval as a clinical assay. There is a need to visualize cfDNA data (which are oftentimes put side-by-side with tumor sequencing data. We have been using cBioPortal to show cfDNA data, but there are a few challenges.

1. There may be many samples over time
2. The allele frequencies mutations detected in cfDNA are usually very small and therefore the current bar plot from 0-1 does not work well, esp when placing together with mutations from tumors
3. There is no visualization over time for cfDNA data.

We have done some prototyping work two years ago in [a GSoC project](https://github.com/cBioPortal/GSoC/issues/3). The prototype is documented [here](https://pambot.github.io/posts/gsoc2017-cbioportal). I think it's time to implement some of them in production.

- Provides an alterantive view of the mutations data
  - a heatmap of allele frequencies (transposed oncoprint) similar to the ones in the [prototype](https://pambot.github.io/posts/gsoc2017-cbioportal)
  - a line chart of allele frequencies; user can select samples to plot
  - by default still show Mutations table, but provide option to the others
- Provide option to plot allele frequencies as log scale
- Should we separate allele frequencies from cfDNA and tumors?
- How to add cfDNA to timeline?

Here is [an example patient](https://cbioportal.mskcc.org/patient?caseId=p_DH_akt_09&studyId=mixed_cbe_solitd_MSK_cfDNA_IMPACT)

@schultzn @alisman @n1zea144

**Comment by jjgao** [comment]
logged separately for the heatmap view: https://github.com/cBioPortal/cbioportal/issues/6402

**Comment by n1zea144** [comment]
Re: adding cfDNA to timeline - is that beyond specimen collection events?

**Comment by jjgao** [comment]
> Re: adding cfDNA to timeline - is that beyond specimen collection events?

and also displaying cfDNA levels in timeline fashion - not necessarily in the current timeline.
