### ISSUE TITLE
Adding oncoprint-like heatmap in patient view for multi-samples

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6402]
It was prototyped early in [one of the GSoC project](https://pambot.github.io/posts/gsoc2017-cbioportal). 

![image](https://user-images.githubusercontent.com/840895/61502332-8d7b2f00-a9a1-11e9-8ec0-0675ef19f288.png)

We can implement it as an alternative visualization of the mutations table.

**Comment by adamabeshouse** [comment]
duplicate https://github.com/cBioPortal/cbioportal/issues/6401
