### ISSUE TITLE
Combined Study link in Result page always open all samples in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6403]
Link to the Combined Study does not open the queried samples but open all samples in the study.

http://bit.ly/30MEaE9

![image](https://user-images.githubusercontent.com/840895/61505722-c4efd880-a9ad-11e9-9b06-ff2dd49cd952.png)

If not all samples were selected for query, we should only open the selected samples. An easy solution may be create a virtual study and open the virtual study? Alternatively, we can post the sample IDs to the study view and let the study view to handle it.

**Comment by alisman** [comment]
@dippindots @zhx828  i think we should solve this in the same was as we handle cohorts on patient view. list of ids are put in the url hash.

**Comment by kalletlak** [comment]
@jjgao how about when querying single study with cases subset(user defined cases or it can be any case list) except `All Samples`? do we want same behavior even for this?

**Comment by jjgao** [comment]
@kalletlak yes, we do. I think the link to study view should alway open exactly the same set of samples in the query.
