### ISSUE TITLE
queried cases with Mutations and CNAs data but oncoprint indicates some of them are not profiled for muations

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6405]
In [this query](https://www.cbioportal.org/results/oncoprint?session_id=5d31d922e4b0ab413787c596), I selected cases with Mutations and CNAs data as the case list, why are there 4 samples that are not profiled for mutations?

![image](https://user-images.githubusercontent.com/840895/61544459-83921400-aa13-11e9-9f22-c872ce12df8c.png)

**Comment by kalletlak** [comment]
@jjgao looks like selected case list is `Cases with copy number alterations data`

**Comment by adamabeshouse** [comment]
yes and when I select cases with mutations and cna, it seems like everything is profiled.

**Comment by jjgao** [comment]
sorry, my mistake.
