### ISSUE TITLE
minor issue with oncoprint progress message

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6407]
Can we make Canncer Hotspots in the same line?

![image](https://user-images.githubusercontent.com/840895/61580926-83fadf80-aae5-11e9-9d5f-ca56346373e4.png)

**Comment by jjgao** [comment]
I mean can we move "Annotating with OncoKB and Cancer Hotspots" into the same line? :)

![image](https://user-images.githubusercontent.com/840895/61664066-03341300-aca0-11e9-8662-b9118f3fb609.png)

**Comment by adamabeshouse** [comment]
oh lol, yes 😄

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2564
