### ISSUE TITLE
issue with co-expression

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6409]
reported by [a user](https://groups.google.com/forum/#!msg/cbioportal/3gpkOqKTvbQ/slV2M8zKDgAJ), the query below does not return any co-expression data, but expression data for these samples exist.

https://www.cbioportal.org/results/coexpression?session_id=5d3528e0e4b0ab413787c9b6

**Comment by adamabeshouse** [comment]
looks like server issue. also if I change one of the profiles it causes a 500 server error

**Comment by jjgao** [comment]
adding @n1zea144 to this.

**Comment by jjgao** [comment]
@n1zea144 will look into this.

**Comment by kalletlak** [comment]
@jjgao looks like there is no expression for queried gene `IGF2BP2`

**Comment by jjgao** [comment]
@kalletlak if you look at the Plots tab, there are expression data for IGF2BP2...

**Comment by kalletlak** [comment]
@jjgao yeah, seems like an issue whenever sampleId's are passed to the api
