### ISSUE TITLE
unclear group comparison overlap message

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#6414]
from @jjgao: 

@adamabeshouse quick question: for [this query](https://cbioportal-frontend-pr-2534.herokuapp.com/comparison/overlap?sessionId=5cf89323e4b0ab413787436c) with overlapping patients but no overlapping samples, whencomparing samples for Mutations, are all samples included? When switching to patients, are the overlapping patients excluded?

I find the message below confusing...

![image](https://user-images.githubusercontent.com/840895/61665103-2cee3980-aca2-11e9-8af1-4c63fb212876.png)

**Comment by jjgao** [comment]
@adamabeshouse is this fixed? I still see the same message on production.

**Comment by adamabeshouse** [comment]
oh I thought that after further discussion it was actually correct and the problem was the tab analysis wasn't in agreement.

It's correct because all analyses are done on either sample level or patient level, never together. So the message still is correct. Should it be phrased in a better way?

**Comment by jjgao** [comment]
I think the message itself is confusing. We should rephrase it.

**Comment by adamabeshouse** [comment]
any ideas?

**Comment by tmazor** [comment]
How about:

Overlapping samples (10) are excluded from sample-level analysis on other tabs.
Overlapping patients (2) are excluded from patient-level analysis on other tabs.

We could show just one of those sentences if only samples or patients are overlapping, or both sentences if both are overlapping.

@jjgao is that more clear?

**Comment by adamabeshouse** [comment]
that sounds good to me. should we show a message for 0 or just omit it?

**Comment by tmazor** [comment]
I would vote to omit the message for 0

**Comment by adamabeshouse** [comment]
what about in "include mode", where the message just explains what the overlap is? should we keep the format as-is now?

**Comment by tmazor** [comment]
I think we can probably update those as well. How about a similar set of sentences, and once again only show the applicable sentence(s). @adamabeshouse @jjgao ?

Overlapping samples (10) are included in sample-level analysis on all tabs.
Overlapping patients (2) are included in patient-level analysis on all tabs.

**Comment by adamabeshouse** [comment]
sounds good. how do you want to phrase it for a message about "this" tab?

**Comment by tmazor** [comment]
ohhh like the clinical tab screenshot above? How about:

Overlapping samples (10) are included in this sample-level analysis.
Overlapping patients (2) are included in this patient-level analysis.

We can just show the sentence that's relevant depending on if the analysis on the tab is sample or patient level. Although I guess clinical tab maybe needs both sentences?

Although I'm realizing now that what I cut out from these warning messages is the phrase "the selected groups", which was a nice subtle reminder to the user that they can always de-select groups.

Should we adjust all of these statements to start with:
The selected groups contain 10 overlapping samples which are included/excluded...
The selected groups contain 2 overlapping patients which are included/excluded...

@jjgao @schultzn @adamabeshouse anyone feel strongly about including "the selected groups" in these warning messages?

**Comment by adamabeshouse** [comment]
@tmazor keep in mind also that when a group is excluded, theres extra text that comes up ("between ... "):

![image](https://user-images.githubusercontent.com/636232/62901034-be911a00-bd29-11e9-84ed-bfc290732d94.png)

**Comment by tmazor** [comment]
ahhh so many messages!

I think the first message ("Primary is completely...") is fine.

In general, I think the confusing part about these messages is when we lump patients & samples together. So the message in your screenshot seems fine to me because it's only about patients. 

![image](https://user-images.githubusercontent.com/10508276/62975775-2b1f1e00-bde9-11e9-8f98-a833c3cc5017.png)

In the case where we mention both samples & patients, maybe that can be rephrased to:
 
Samples (256) and patients (256) that overlap between (A) EGFR amp, (C) IDH1 mutant, and (D) TP53 mutant are excluded from sample- and patient-level analyses respectively.

I guess for consistency we can use that same sentence structure but include only samples or patients when only one is relevant.

Does that make sense?

**Comment by adamabeshouse** [comment]
So combine them into one sentence only when we have the "between..." part?

**Comment by tmazor** [comment]
I think so? I slightly prefer having separate sentences in general, but it just feels too long/redundant to do that when we list out the group names. I don't feel super strongly though - we could combine all those other 2 sentence options into a single sentence of this structure if you prefer.

**Comment by adamabeshouse** [comment]
I think we should stick with separate sentences. Clinical is the only tab that has both sample and patient analysis, and maybe we could even only show a warning based on whether the currently selected attribute is sample or patient. That would probably be clearer, actually.

So the only tab that would show both sentences is overlap, and I think it's fine there. Phew!

**Comment by tmazor** [comment]
Great! Except, I think we probably should show both sample & patient messages on clinical, because regardless of which attribute is selected, the table is always visible with both sample & patient attributes.

**Comment by adamabeshouse** [comment]
sounds good!
