### ISSUE TITLE
Variant allele frequency rounding issue?

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#6418]
We've recently released MSK-ACCESS (cfDNA) data into the portal. Unlike existing clinical bioinformatic assays, very low VAF mutations will be reported with ACCESS.  Currently, some ACCESS samples are appearing with an Allele Freq of 0.00 which we think is due to a rounding down of the quotient Variant Reads / Ref Reads [P-0036946](https://cbioportal.mskcc.org/patient?studyId=mskimpact&caseId=P-0036946#navCaseIds=mskimpact:P-0036946) (see capture below).

Can we update the code not to round down when the VAF computed is 0.00?  In the case of ACCESS data, rounding to the 1/1000s would be sufficient. 

![image](https://user-images.githubusercontent.com/366003/61810799-0d741f80-ae0e-11e9-85e4-99323ffe2db3.png)

**Comment by jjgao** [comment]
It was logged #5864 and there was a merge pull request https://github.com/cBioPortal/cbioportal-frontend/pull/2155. @alisman would you please check why this was fixed?

**Comment by onursumer** [comment]
@jjgao Because the fix is attempted in the wrong legacy file: `src/pages/resultsView/network/files/mutationMapper.js`. 

This legacy file is only included because we have the legacy network tab in a separate iframe. I am not sure if the network tab uses the legacy mutation mapper at all.

**Comment by jjgao** [comment]
got it. How come the code was merge! Could you take of this? @onursumer

**Comment by onursumer** [comment]
@jjgao apparently, it's been approved by multiple reviewers and then merged. Yet another reason to retire the network tab as soon as possible :)

I'll apply the fix to the correct file and open a PR.

**Comment by jjgao** [comment]
thanks, @onursumer
