### ISSUE TITLE
Erron on co-expression service

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6424]
Following request returns 500 error.  Error occurs if you go to  https://bit.ly/2JSyzqf
and change the right side molecular profile dropdown.

curl 'https://www.cbioportal.org/api/molecular-profiles/co-expressions/fetch?molecularProfileIdA=kirc_tcga_pub_mrna&molecularProfileIdB=kirc_tcga_pub_rna_seq_v2_mrna&threshold=0' -H 'origin: https://www.cbioportal.org' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'referer: https://www.cbioportal.org/results/coexpression?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=kirc_tcga_pub&case_set_id=kirc_tcga_pub_treated&clinicallist=PROFILED_IN_kirc_tcga_pub_rna_seq_v2_mrna_median_Zscores&data_priority=0&gene_list=PART1&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=kirc_tcga_pub_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=kirc_tcga_pub_rna_seq_v2_mrna_median_Zscores&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=kirc_tcga_pub_mutations&show_samples=false&tab_index=tab_visualize' -H 'authority: www.cbioportal.org' -H 'cookie: _ga=GA1.2.1764028159.1557761784; mp_96b84420a1a32e448f73e7b9ffccebdb_mixpanel=%7B%22distinct_id%22%3A%20%2216ab1d6770f3af-0a7842b0ab7e5a-37607603-1aeaa0-16ab1d67710b0f%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Fgithub.com%2FcBioPortal%2Fcbioportal%22%2C%22%24initial_referring_domain%22%3A%20%22github.com%22%7D; mp_a37bac8664a332481726ae49603f9f63_mixpanel=%7B%22distinct_id%22%3A%20%22fc475e52-7243-4961-acd4-23e53d287e76%22%7D; results-tab=null; _gid=GA1.2.642140968.1563891605; JSESSIONID=C0E9B42AA249A041ED0B8815E25C67A8; _gat=1' --data-binary '{"sampleListId":"kirc_tcga_pub_treated","entrezGeneId":25859}' --compressed

**Comment by alisman** [comment]
@kalletlak turns out the error occurs whenever the the profileIds A and B are different.  If they are the same, which is true on coexpression tab by default, request succeeds.

**Comment by n1zea144** [comment]
Should be fixed with this PR:

[PR-6426](https://github.com/cBioPortal/cbioportal/pull/6426)
