### ISSUE TITLE
co-expression tab fails for user-defined sample set

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6455]
User reported bug: https://groups.google.com/forum/#!topic/cbioportal/wOdcVXdbLbs

Co-expression tab shows no data when a query is run on a user-defined sample set.

The plots tab shows that these samples do have expression data, and co-expression works when querying the whole study.

Examples:
https://www.cbioportal.org/results/coexpression?session_id=5d3fa77be4b0ae75b0adb011
https://www.cbioportal.org/results/coexpression?session_id=5ca3c1b1e4b046111fee355f

**Comment by kalletlak** [comment]
@tmazor fixed in https://github.com/cBioPortal/cbioportal/pull/6411.
Latest master needs to be deployed to public instance

**Comment by jjgao** [comment]
duplicate with #6409

**Comment by alisman** [comment]
@tmazor @jjgao 6411 deployed today.  i verified on the links above.  please test and close.

**Comment by jjgao** [comment]
@alisman Thanks. it's fixed. Somehow the coexpression tab seems very slow...

**Comment by jjgao** [comment]
the slowness might be due to my slow internet at home today -- will test tomorrow.

**Comment by tmazor** [comment]
Agreed, looks like this is fixed. Co-expression seems slow for me too, but also could be due to my internet right now. @jjgao I'm going to close this issue but if you are still seeing slowness on a good internet connection can you open a new issue about that?

**Comment by jjgao** [comment]
It still feels slow. I created an issue: https://github.com/cBioPortal/cbioportal/issues/6467
