### ISSUE TITLE
Please investigate/fix this test

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6460]
https://circleci.com/gh/cBioPortal/cbioportal-frontend/43716?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by leexgh** [comment]
see fix here: https://github.com/cBioPortal/cbioportal-frontend/pull/2574

**Comment by jjgao** [comment]
@leexgh it would be good if you can link issues in pull request (with Zennhub) so that issues can be closed automatically when the pr is merged.

**Comment by leexgh** [comment]
@jjgao no problem, this issue was open after my fix PR had been merged, so I didn't have a chance to link them before

**Comment by jjgao** [comment]
Got it. Thanks for the explanation! Is this fixed now?

**Comment by leexgh** [comment]
@jjgao yes it's fixed
