### ISSUE TITLE
performance issue for genie

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6461]
GENIE study view is slow. Query is also kind of slow. I am wondering if it’s due to all the gene panels in genie. The implementation on gene panels are not optimized.

**Comment by sheridancbio** [comment]
@jjgao wasn't this issue addressed with the rollout of cbioportal release 3.1.0?  We had a PR which essentially duplicated work which was part of the release branch we believe.

**Comment by n1zea144** [comment]
Closed issue - this was resolve in PR by Hongxin/Kelsey which treats sv differently than mutattions on the study view.
