### ISSUE TITLE
IGV viwever fails to load the selected locus

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#6466]
The error seems to be related to CORS settings on the IGV web service:
```
Access to XMLHttpRequest at 'https://portals.broadinstitute.org/webservices/igv/locus?genome=hg19&name=PIK3CA' from origin 'https://www.cbioportal.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by jjgao** [comment]
@onursumer maybe contact Jim?

**Comment by onursumer** [comment]
This works fine now. Probably the IGV service was temporarily down. 

Maybe we should add a screenshot test for the CN Segments tab, so that we can catch service errors earlier.

**Comment by jjgao** [comment]
@onursumer ok, let's close this for now unless this happens again.
