### ISSUE TITLE
co-expression is slow?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6467]
The co-expression seems slower than before. I am wondering if we can find a way to test?

**Comment by n1zea144** [comment]
Its pretty clear that fetching gene information provides a great deal of overhead when processing coexpression requests.  I think we should reconsider this issue after discussing this one - 

[PR-6456](https://github.com/cBioPortal/cbioportal/pull/6456)

**Comment by tmazor** [comment]
any progress on this? this is a major barrier to using the coexpression tab these days.

**Comment by jjgao** [comment]
@tmazor it's acting bad that we have removed the tab and now the server is back to normal (sweating). We hope to fix it shortly.

**Comment by tmazor** [comment]
ok! good luck!
