### ISSUE TITLE
"Can't create table data_access_tokens (errno: 150)" cannot migrate DB from 2.7.3 to 2.9.0

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#6468]
I would like to upgrade our private instance from v2.7.3 to v2.9.0 (for v3.0.3) but when running the db migration script I get the following error:

     $ python3.6 cbioportal/core/src/main/scripts/migrate_db.py -p  cbioportal/src/main/resources/portal.properties --sql cbioportal/db-scripts/src/main/resources/migration.sql
     ...
     Executing statement: CREATE TABLE `data_access_tokens` ( `TOKEN` varchar(50) NOT NULL, `USERNAME` varchar(128) NOT NULL, `EXPIRATION` datetime NOT NULL, `CREATION` datetime, PRIMARY KEY (`TOKEN`), FOREIGN KEY (`USERNAME`) REFERENCES `users` (`EMAIL`) ON DELETE CASCADE );
     (1005, "Can't create table 'cbioportal.data_access_tokens' (errno: 150)")

**Comment by mandawilson** [comment]
Hi @j-hudecek.  Can you login to MySQL and check what the default storage engine is, as well as what your users table storage engine is?  E.G.
```
mysql> show variables like 'default_storage_engine';
+------------------------+--------+
| Variable_name          | Value  |
+------------------------+--------+
| default_storage_engine | InnoDB |
+------------------------+--------+
1 row in set (0.01 sec)

mysql> show create table users;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                            |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| users | CREATE TABLE `users` (
  `EMAIL` varchar(128) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `ENABLED` tinyint(1) NOT NULL,
  PRIMARY KEY (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)```

**Comment by j-hudecek** [comment]
Default is InnoDB but the table was on MyISAM for some reason. Also it used latin1 instead of utf8 like users, but running

    ALTER TABLE users ENGINE = InnoDB;
    ALTER TABLE data_access_tokens CONVERT TO CHARACTER SET utf8;

fixed it and I could add the constraint. Thanks, Manda

**Comment by mandawilson** [comment]
Excellent!  MySQL < 5.5.5 had MyISAM as the default storage engine, but for versions >= 5.5.5 InnoDB is the default storage engine.  Some cBioPortal databases set up on older MySQL versions that have been upgraded to >= 5.5.5 sometimes do have a mix of MyISAM and InnoDB tables, which as you saw is not a very good idea or just plain doesn't work.  We spent some time changing all of our tables to InnoDB.
