### ISSUE TITLE
Fix checkbox misalignment issue

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6473]
![Screen Shot 2019-08-05 at 1 42 24 PM](https://user-images.githubusercontent.com/5400599/62483938-ef4fdd00-b786-11e9-9c08-401ef14d464a.png)

@adamabeshouse maybe the top alignment is intentional? You can test on genie portal.
Feel free to reassign it to me since I'm fixing some other issues on study view

**Comment by adamabeshouse** [comment]
@zhx828 is this after your 'block' fix? that would cause it

**Comment by zhx828** [comment]
@adamabeshouse nope. The block element has a flex parent. The issue is already in production.

**Comment by adamabeshouse** [comment]
ohh okay. should be a quick fix, put the checkbox in the same flex as the text. it's definitely not intentional
