### ISSUE TITLE
Results view should give error message when molecular-profile is not available

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6474]
Currently when the call to `https://cbioportal.mskcc.org/api/molecular-profiles/{molecularProfile}/molecular-data/fetch` is failing(404), the page shows a loading bar. 

Suggestion: Give an error message instead.

https://cbioportal.mskcc.org/results/plots?Action=Submit&cancer_study_list=crc_jga_msk_2019&case_set_id=crc_jga_msk_2019_all&clinicallist=NUM_SAMPLES_PER_PATIENT&gene_list=TP53&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=crc_jga_msk_2019_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=crc_jga_msk_2019_mutations&show_samples=false&tab_index=tab_visualize

**Comment by jjgao** [comment]
@alisman this falls in the same category of issues related to error handling.
