### ISSUE TITLE
release-3.1.0: cytoband not appearing in group comparison enrichments tabs

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#6479]
![image](https://user-images.githubusercontent.com/636232/62577305-a8d4ae00-b86c-11e9-971c-89840075b94b.png)

maybe fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/2180?

**Comment by khzhu** [comment]
@adamabeshouse @jjgao , all fixed. The changes have been merged into **_enrichments-merge-lock_**.
