### ISSUE TITLE
add save for hidden custom charts & delete functionality in study view

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6482]
As of https://github.com/cBioPortal/cbioportal-frontend/pull/2174, custom charts that are visible in study view will be saved for logged in users.

Custom charts that are currently hidden should also be saved. Since custom charts will then be permanently saved for a user, we should also add the ability to delete a custom chart.

**Comment by jjgao** [comment]
Maybe we can add the functionality in the Custom Data sub-menu? Once custom data is submitted, it will be listed in a table with the option to delete?
