### ISSUE TITLE
Why cBioportal can be accessed after machine restart ?

### ISSUE THREAD

**Issue by lakhujanivijay** [cBioPortal/cbioportal#6487]
Hi,

I have installed cBioPortal using docker and it is working fine till the time I restart my machine. Every time I do that, I can no longer access the local instance.  Is it something related with mounting volumes using docker; like it is being unmounted on restart. Any guesses ?

**Comment by kalletlak** [comment]
duplicate of https://github.com/cBioPortal/cbioportal/issues/6488
