### ISSUE TITLE
Why cBioportal cannot be accessed after machine restart ?

### ISSUE THREAD

**Issue by lakhujanivijay** [cBioPortal/cbioportal#6488]
Hi,

I have installed cBioPortal using docker and it is working fine till the time I restart my machine. Every time I do that, I can no longer access the local instance.  Is it something related with mounting volumes using docker; like it is being unmounted on restart. Any guesses ?

**Comment by kalletlak** [comment]
@lakhujanivijay looks like an existing issue with docker.
What version of docker and machine are you using? 
And what command did you use to run the application?

**Comment by lakhujanivijay** [comment]
Hi @kalletlak 

My docker version is:
```
docker version
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54
 Built:             Wed Mar 27 18:34:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```
-----

It has to be noted that after running the following steps, I can have the access cBioportal again.

```
docker run -d --restart=always \
    --name='cbioDB' \
    --net=cbio-net \
    -e MYSQL_ROOT_PASSWORD=P@ssword1 \
    -e MYSQL_USER=cbio \
    -e MYSQL_PASSWORD=P@ssword1 \
    -e MYSQL_DATABASE=cbioportal \
    -v $PWD'/cbioportal_database_files/':/var/lib/mysql/ \
    -v $PWD'/cgds.sql':/docker-entrypoint-initdb.d/cgds.sql:ro \
    -v $PWD'/seed-cbioportal_hg19_v2.7.3.sql.gz':/docker-entrypoint-initdb.d/seed_part1.sql.gz:ro \
    mysql:5.7
```
and 

```
docker run -d --restart=always \
    --name=cbioportal-container \
    --net=cbio-net \
    -v $PWD'/portal.properties':/cbioportal/portal.properties:ro \
    -e CATALINA_OPTS='-Xms2g -Xmx4g' \
    -p 8081:8080 \
    thehyve/cbioportal:v2.0.1-iss5758
```
and then re-started the containers

**Comment by inodb** [comment]
@lakhujanivijay 

Do you see anything in the logs after restarting your machine ?

And do you see things running when running `docker ps`?

**Comment by lakhujanivijay** [comment]
hi @inodb 

where do i find the logs? also, the containers remain in `running status` when i do `docker ps`

**Comment by lakhujanivijay** [comment]
hi @inodb

is there any update on this one ?

**Comment by lakhujanivijay** [comment]
@xpivarc I observed that when I restart the machine , my hard disk name changes every time. for e.g.

if right now it is:
`/media/bioinfo/primary8`

after machine restart it becomes
`/media/bioinfo/primary9`

again if I restart, it will be
`/media/bioinfo/primary10` and so on! I don't understand what's going on.

**Comment by xpivarc** [comment]
@lakhujanivijay That will be the problem. As far I know "/media/..." are used for removable media. So that`s probably cause of the changing name (don`t use it). And another good practice IMHO is not to use $PWD, just use relative paths.
