### ISSUE TITLE
Feature request for Download tab: Cases not affected

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6496]
Can we add a new option on the download tab:
"Cases not affected: Only samples without alterations that match the query are included"

![image](https://user-images.githubusercontent.com/11892704/62894734-53404b80-bd1b-11e9-9c62-8d3b70b578d2.png)

**Comment by dippindots** [comment]
@jjgao Is it has been solved by this merged pr already? 
![image](https://user-images.githubusercontent.com/15748980/63202655-c669fa80-c058-11e9-818d-298d05f8c40d.png)
We have `Altered samples` and `Unaltered samples` options now.

**Comment by schultzn** [comment]
Thanks!

One small change that needs to be made: "Visual Study" needs to be renamed to "Virtual Study" in the altered and unaltered samples selection options.

**Comment by dippindots** [comment]
@schultzn Sorry I thought I corrected all these typos in the pr, created a pr to fix that.

**Comment by dippindots** [comment]
The feature and fix are merged to the website now, so closed this issue.
