### ISSUE TITLE
Bring back the survival plot in study view

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6499]
Per requested by production team and few other users but with following updates:
- [x] Show both survival plots for all studies, OS and DFS when available
- [x] Only one curve showing the currently selected samples

**Comment by zhx828** [comment]
@cBioPortal/product I have an instance running here to bring back the survival plot. There are few things have been updated if you could take a look https://cbioportal-frontend-pr-2608.herokuapp.com/study/summary?id=acc_tcga_pan_can_atlas_2018

- [ ] Survival plot is always shown for single tumor type study and will be available through adding charts for mix studies.
- [ ] There will be only one curve shown in the survival indicating `All patients` when no selection made or `Selected patients` when the study is filtered
- [ ] The `Exclude NA` in the tooltip is complicated removed since there is no comparison happening in the chart.

Please take a look and let me know if there is any changes need to be made. Thanks.

**Comment by schultzn** [comment]
Looks great!
