### ISSUE TITLE
treatment data is not always showing up on heatmap

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6500]
Try e.g.:

https://beta.cbioportal.org/results/oncoprint?session_id=5d5305bbe4b0d777deb04b71

Then add IC50 to heatmap

Somehow it does sometimes show up when changing the case list to only include cases with treatment data

**Comment by Sjoerd-van-Hagen** [comment]
This one should now be fixed by @pvannierop and @adamabeshouse . Let us know if it still occurs.

**Comment by adamabeshouse** [comment]
I dont even see IC50 in the treatments list

**Comment by inodb** [comment]
@adamabeshouse check the dropdown for `Area under the curve`, 	it's a measurement rather than a treatment

![Screen Shot 2019-09-03 at 10 27 39 AM](https://user-images.githubusercontent.com/1334004/64182027-874bef80-ce35-11e9-9a99-2f3cf2a6aa8c.png)

**Comment by adamabeshouse** [comment]
oh I see
