### ISSUE TITLE
Rename Treatment to Treatment Response in UI

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6501]
Good to be more explicit about the name. It's treatment response data

**Comment by pvannierop** [comment]
I have updated the menu label as per your suggestion. Fix is in [cbioportal-frontend PR #2638](https://github.com/cBioPortal/cbioportal-frontend/pull/2638).

**Comment by inodb** [comment]
Thanks @pvannierop 	! There is also `Treatment` in the Heatmap menu of oncoprint. Probably good to change that to `Treatment Response` as well. I think the `search for treatments..` is fine. But the button should prolly say `Add Treatment Response to heatmap`

**Comment by pvannierop** [comment]
I have done as suggested. Fix is in [cbioportal-frontend PR #2661](https://github.com/cBioPortal/cbioportal-frontend/pull/2661).

**Comment by pvannierop** [comment]
Code change has been accepted. I close this issue.
