### ISSUE TITLE
Oncoprint treatment_list parameter in URL does not show treatments

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6503]
E.g. 
https://beta.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=mixed_broad_ccle_2018&case_set_id=mixed_broad_ccle_2018_cnaseq&clinicallist=MUTATION_COUNT&data_priority=0&gene_list=TP53%2520PIK3CA&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=mixed_broad_ccle_2018_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=mixed_broad_ccle_2018_mutations&heatmap_track_groups=mixed_broad_ccle_2018_CCLE_drug_treatment_AUC%2C1%2C3&show_samples=false&tab_index=tab_visualize&treatment_list=1%3B3

does not show treatments

**Comment by pvannierop** [comment]
Has been fixed.
