### ISSUE TITLE
 NETWORK gives different results for same queried genes

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#6512]
>error can be reproduced as the following:
Ovary/Fallopian Tube was selected for Select Studies, then the Ovarian Serous Cystadenocarcinoma (TCGA, Nature 2011) dataset was chosen for analysis. For the section labeled Select Genomic Profiles, the mRNA Expression was selected, and finally its profile mRNA expression Z-scores (all genes). For the section Select Patient/Case Set, the Samples with mRNA data (Agilent microarray) (489) option was chosen from the dropdown menu. At the end, genes NOTCH2, NOTCH3, and MAML1 were selected to submit the query. Based on the three core genes, a signaling network was created to provide the 50 most frequently altered neighboring genes.  However, each time it gives me different network image results.
also
```
Uncaught DOMException: Failed to execute 'addColorStop' on 'CanvasGradient': The provided value (1) is outside the range (0.0, 1.0).
    at CanvasRenderer.CRp.drawNode (https://frontend.cbioportal.org/reactapp/network/files/cytoscape.renderer.canvas.portal-renderer.js:164:25)
    at drawElements (https://frontend.cbioportal.org/reactapp/network/files/cytoscape.js:19269:17)
    at drawToContext (https://frontend.cbioportal.org/reactapp/network/files/cytoscape.js:19325:9)
```

**Comment by jjgao** [comment]
network tab will be removed soon.
