### ISSUE TITLE
Can we remove the numbers from the treatment data?

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6524]
It seems that in the UI the drug numbers are used in:

- the oncoprint heatmap dropdown to indicate which one has been selected
- the plots tab on the x and/or y axis

I guess this was done b/c the drug name can be too long? Maybe better to list the drug name with `...` when it is too long?

**Comment by pvannierop** [comment]
No, this is a behavior determined by the study. I will update CCLE 2018 study data so that the stable ids of the drugs are the actual names of the compounds.

**Comment by pvannierop** [comment]
@inodb I have updated the CCLE 2018 study to not have numbers used for the stable_id (see screenshots below).

### Treatment selection menu
![Screenshot from 2019-08-29 10-36-50](https://user-images.githubusercontent.com/745885/63924728-0eb9ed00-ca49-11e9-8abf-b94a7579a2b6.png)

### Treatment response heatmap tracks
![Screenshot from 2019-08-29 10-38-17](https://user-images.githubusercontent.com/745885/63924777-298c6180-ca49-11e9-89a7-a1e41c4dc089.png)
