### ISSUE TITLE
plots tab `ordered samples` axis label?

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6526]
Maybe good to have some label on the ordered samples label? Not sure what it should be `Sample #` or something maybe?

**Comment by jjgao** [comment]
Maybe `Sample`?

**Comment by Sjoerd-van-Hagen** [comment]
Does that not suggest that it is ordered on sample id?

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen not to me, but not sure if it's just me.

**Comment by Sjoerd-van-Hagen** [comment]
I would put something like 'Ordered by IC50'.

**Comment by jjgao** [comment]
Or maybe we don't need a label? There is usually no x-axis labels in waterfall plot.

**Comment by Sjoerd-van-Hagen** [comment]
I don't think we do. The user picked ordered from the drop down, and it is pretty obvious that it is sorted.

**Comment by jjgao** [comment]
@inodb maybe we can leave it out?

**Comment by Sjoerd-van-Hagen** [comment]
@inodb let's close this one. We can reconsider when users find it unclear.

**Comment by pvannierop** [comment]
I am closing this issue. When can revisit when needed.
