### ISSUE TITLE
Indicate that study has treatment response data on data sets page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6527]
Currently it is hard to figure out which studies have treatment data

**Comment by Sjoerd-van-Hagen** [comment]
Let's not include this in the 3.1.0 release.

**Comment by jjgao** [comment]
I don't think we should do that unless we have response data in multiple studies. Otherwise we'll just have an almost empty column.

**Comment by jjgao** [comment]
@inodb is there a ticket about adding a case list or attribute to indicate whether a sample has response data?
