### ISSUE TITLE
Treatment tooltip: Sample ID can extend past the tooltip boundary

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6530]
![image](https://user-images.githubusercontent.com/11892704/63562930-53b3c000-c52d-11e9-9147-bdf27d69d9cc.png)

**Comment by pvannierop** [comment]
@schultzn @inodb I have updated the css of the oncoprint tooltip to accomodate long sample names.

# Before
![Screenshot from 2019-08-26 16-54-49](https://user-images.githubusercontent.com/745885/63700583-7a227580-c823-11e9-847b-1290627bfcdb.png)

# After
![Screenshot from 2019-08-26 16-51-39](https://user-images.githubusercontent.com/745885/63700580-78f14880-c823-11e9-869d-8591f9c6d8da.png)

**Comment by pvannierop** [comment]
Fix for this issue has been merged. I am closing this issue.
