### ISSUE TITLE
Treatments: Not clear which treatment track is shown

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6531]
There are 3 choices for treatment heatmaps in CCLE: AUC, IC50, and z-score of ln-transformed IC50. It is not clear to me which one is selected, nothing seems to change and the legend at the bottom always states "IC50".

![image](https://user-images.githubusercontent.com/11892704/63563032-b7d68400-c52d-11e9-839b-3c3c80134840.png)

**Comment by pvannierop** [comment]
@schultzn We agree. However, this behavior is not related to the treatment feature. Also for molecular profiles it is unclear which profile is represented in a particular oncoprint track group. I propose to remove this from the 3.1.0 milestone and create a new issue for the 3.1.1 milestone.

**Comment by jjgao** [comment]
This seems fixed...

**Comment by pvannierop** [comment]
@jjgao I do not think so. Or mabe I misunderstood the problem. As I understood it Niki pointed out that it is not clear to which treatment profile a heatmap track group belongs. Only gene names are show for each heatmap track group.

**Comment by jjgao** [comment]
This is a problem of all heatmaps. I have just created another issue for this: https://github.com/cBioPortal/cbioportal/issues/6747
