### ISSUE TITLE
Treatment waterfall plot: Log does not work for AUC

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6533]
![image](https://user-images.githubusercontent.com/11892704/63564013-56181900-c531-11e9-994b-db9345691e4c.png)

**Comment by pvannierop** [comment]
@schultzn @alisman @adamabeshouse @inodb This issue is fixed in [cbioportal-frontend PR #2631](https://github.com/cBioPortal/cbioportal-frontend/pull/2631).
