### ISSUE TITLE
Use new CheckedSelect component for treatment dropdown in Oncoprint

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6534]
@pvannierop we decided to do away with react-checked-select.  We have a new component ReactChecked which handles this using react-select.  You can see an example of it being used: src/pages/resultsView/enrichments/ExpressionEnrichmentsContainer.tsx.  

Could you switch to this component for the treatment dropdown in OncoprintControls.tsx?   Right now this is causing a conflict with master because we've removed react-checked-select.   Thanks!

--Aaron

**Comment by Sjoerd-van-Hagen** [comment]
Isn't this exactly why such a change needs to be applied to RC first? That way we would have noticed it immediately when rebasing.

@inodb thoughts?

**Comment by pvannierop** [comment]
@alisman @Sjoerd-van-Hagen @Sjoerd-van-Hagen decided to keep the react-select-checked dependency for release 3.1.0 using a forked version that has a different exported name to prevent name collisions. For update 3.1.1 @pvannierop will update the treatment selection menu to the new react-select-checked.
