### ISSUE TITLE
Issue with PDF download of oncoprinter with large sample count

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6535]
User reports:
I entered my own data into the oncoprinter application and it spit out the data I desired, but when I go to save it to a pdf, it create a pdf that appears completely blank because the image are so small. Have other people had this issue before? I tried to save it as one of the other file options and they did not work either. Do you have any suggestions?

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/amq5mDz7Dh4/2y7Uk0gjDwAJ

**Comment by adamabeshouse** [comment]
interesting. hard to test without example, ive never run into it myself.

@khzhu can you paste here the fake data you generated so we can try to fix this?

**Comment by khzhu** [comment]
Hi @adamabeshouse , here is the file.
[oncoprint_sample_test.txt](https://github.com/cBioPortal/cbioportal/files/3580541/oncoprint_sample_test.txt)

**Comment by jjgao** [comment]
I am not sure if OncoPrinter is so useful when there are two many genes. @adamabeshouse we could consider add a limit on the number of genes if it's nto easy to support too many genes.

**Comment by adamabeshouse** [comment]
I don't think theres a bug, it's just incredibly slow because huge file, as indicated over e-mail. I added a warning when there's a huge oncoprinter.
