### ISSUE TITLE
update "saved layout" text

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6542]
![image](https://user-images.githubusercontent.com/10508276/63970500-4e48ff00-ca72-11e9-9ed1-188c79f82caf.png)

There's a typo: "You" should be "Your"

It's not immediately clear to me what clicking "Yes" or "No" will do. How about dropping "Undo?" and changing the "Yes" "No" button text to say:
"Keep Saved Layout"
"Revert to Previous Layout"

**Comment by alisman** [comment]
@Luke-Sikina please make this a PR to release-3.1.0 branch, thanks
