### ISSUE TITLE
when should "save layout" text appear?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6543]
![image](https://user-images.githubusercontent.com/10508276/63970807-09719800-ca73-11e9-8ada-2f68e4fd4d09.png)

As best I can tell, this text only appears when I go to study view while not logged in, and then log in while on study view.

If I log in from the homepage, and then click on study view, I don't see this message. I find this un-intuitive. I think the message should appear anytime I click through to study view.

Also, the message appears even for studies that I have not previously viewed/altered the layout for. Ideally, the message only appears when a layout that is not the default loads.

**Comment by tmazor** [comment]
Ahhh... I just realized why this works the way it does.

While not logged in on study view, I might have altered the layout. If I then log in, the layout changes to the saved layout (or back to the default layout if no layout is previously saved), but clicking "Yes" reverts back to whatever I had done prior to logging in. This is very useful.

Forget my original comment - I think this functionality is good, however, I would suggest that the text should only appear if the layout on screen is different from the saved (or default when nothing is saved) layout.

A separate point which we can consider is if we want to add a "Revert to Default Layout" button somewhere. I'm not sure how useful it will be, but it's something to consider.

**Comment by kalletlak** [comment]
@tmazor that message only appears if the user tries to login in study-view page and the current layout is different from saved layout (not from default layout)

@jjgao @zhx828 any suggestion on where to add `Revert to Default Layout` button?

**Comment by jjgao** [comment]
Maybe the message is not clear. @tmazor any suggestions to improve the text?

I couldn't think of a good place to put the `Revert to Default Layout` button. Maybe in `Add Chart` menu?

**Comment by tmazor** [comment]
@jjgao i proposed updated text in another issue: #6542 

The Add Chart menu could work for a "revert" button! I can't really think of anywhere else that makes much sense.

**Comment by jjgao** [comment]
Sounds good! Thanks, @tmazor 

How about having a "Default" button at the up-right corner? We can add a tooltip to it: "Revert to the default list and order of the selected clinical and genomic attributes/charts."

 When a user clicks it, there should be a confirmation dialog: "Are you sure you want to override the list and order of the selected charts with the default setting? This is irreversible."

![image](https://user-images.githubusercontent.com/840895/64353416-b85e2880-cfcb-11e9-96b1-5a9c917bf610.png)

**Comment by kalletlak** [comment]
@jjgao @tmazor user will lose all the custom data charts that were created. is that ok?

@jjgao is this feature for release-3.1.0?

**Comment by jjgao** [comment]
@kalletlak that's ok as long as we ask them to confirm.

Let's do it in the master branch.

**Comment by alisman** [comment]
@jjgao I don't think it's intuitive that the default button be inside the "add chart" dropdown.  Also, I think button text should be "Reset charts"  
![image](https://user-images.githubusercontent.com/186521/65270218-b080a700-dae8-11e9-90e9-5c9040f5969a.png)

**Comment by jjgao** [comment]
@alisman Changing text to "Reset charts" sounds good, but I don't think it deserves to be on the page upfront (it may be even distractive). 

If you think about "+ Add Chart", it is really actually "Charts Management" and I think the button belongs there. (Maybe we should change Add Chart to Charts?)

**Comment by kalletlak** [comment]
@jjgao should this button be available even for clinical tab?

**Comment by jjgao** [comment]
@kalletlak let's not worry about the clinical data tab.
