### ISSUE TITLE
when plots tab is wide, it extends off screen and takes part of the header & plot with it

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6544]
![image](https://user-images.githubusercontent.com/10508276/63972440-c1ed0b00-ca76-11e9-9b26-9e0cd1144cf6.png)

When plots tab is wider than window, the "Queried in..." text & bookmark query button move offscreen. There should be a horizontal scroll for this plot so that the header, the download button in the upper right of the plot, and the gene selection/other controls above the plot all stay on screen.

**Comment by pvannierop** [comment]
Fix is in [cbioportal-frontend PR #2662](https://github.com/cBioPortal/cbioportal-frontend/pull/2662)

**Comment by Sjoerd-van-Hagen** [comment]
@tmazor can you check if this is working correctly and close the issue if it is?

**Comment by tmazor** [comment]
Looks good to me!
