### ISSUE TITLE
"CNA type" should be "Copy Number Alteration"

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6545]
Text for treatment response plots:
![image](https://user-images.githubusercontent.com/10508276/63973408-b26ec180-ca78-11e9-924c-095d904f203f.png)

Text on production:
![image](https://user-images.githubusercontent.com/10508276/63973415-b7337580-ca78-11e9-93f1-77a48639f080.png)

Did we change this on purpose? I think "Copy Number Alteration" is much clearer than "CNA Type"

**Comment by pvannierop** [comment]
@tmazor Thank you for this issue report. Fix for this is proposed in [cbioportal-frontend PR #2662](https://github.com/cBioPortal/cbioportal-frontend/pull/2662)

**Comment by Sjoerd-van-Hagen** [comment]
This was fixed.
