### ISSUE TITLE
Germline mutation rates mismatch for some queries

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#6546]
Germline mutation rate reported in the Mutation Mapper tab doesn't match the one in the Oncoprint tab.

Example: https://cbioportal.mskcc.org/results/mutations?session_id=5d680a7ce4b0ab413787e5f4

This is most likely related to the fact that we rely on germline consented samples for `msk-impact` studies: https://github.com/cBioPortal/cbioportal-frontend/blob/4e4230483e563c18bd11670b618df2f6ef9176ae/src/pages/resultsView/mutation/MutationRateSummary.tsx#L59

**Comment by inodb** [comment]
To add to this:

oncoprint does not have the concept of germline/somatic mutation rate. Only overall mutation rate
