### ISSUE TITLE
"add to query" button on enrichments tab doesn't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6548]
If I select a gene on the enrichments tab and click "add checked genes to query", the page  freezes and essentially crashes.

It does appear to update the URL, so if I copy that URL and load it in a new window, it loads the revised query with the gene added.

**Comment by Sjoerd-van-Hagen** [comment]
@tmazor can you add some more details? I tried this and it worked.

**Comment by tmazor** [comment]
Go here: https://beta.cbioportal.org/results/enrichments?session_id=5d7101dfe4b058f36688a5a8
Check the box next to CIC
Click "Add checked genes to query"
Nothing happens. The page gets stuck like this:
![image](https://user-images.githubusercontent.com/10508276/64342546-be96d980-cfb8-11e9-886f-d06623bf12b5.png)
The URL does change, and if I copy the URL to a new window, it loads the updated query including CIC.
However this original window remains frozen and eventually crashes entirely:
![image](https://user-images.githubusercontent.com/10508276/64342670-03227500-cfb9-11e9-8ec6-cf4fbf9f513c.png)

**Comment by Sjoerd-van-Hagen** [comment]
Now I can reproduce the issue. When I used a different study it did not occur.
