### ISSUE TITLE
update text on plots tab when no treatments selected

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6549]
![image](https://user-images.githubusercontent.com/10508276/64047190-1efec480-cb3c-11e9-96c0-15e622f3d64b.png)

I think this text would be clearer:
To visualize treatment response data, you must first visit the OncoPrint tab and use the "Heatmap" menu to add treatment response tracks to the OncoPrint. Any treatments added to the OncoPrint will then be available on this tab for visualization.

**Comment by pvannierop** [comment]
The message was updated to your proposed content. The fix is proposed in [cbioportal-frontend PR #2676](https://github.com/cBioPortal/cbioportal-frontend/pull/2676).

**Comment by Sjoerd-van-Hagen** [comment]
PR was merged.
