### ISSUE TITLE
plots - after search, tooltips are misplaced

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6551]
When I search for a mutation, a red cross appears next to samples that match, but when I hover over the red cross, the tooltip appears in the middle of nowhere:

![image](https://user-images.githubusercontent.com/10508276/64047955-38a10b80-cb3e-11e9-8ace-f5c225b67d39.png)

https://beta.cbioportal.org/results/plots?session_id=5d697d3ce4b0d777deb063ea

**Comment by pvannierop** [comment]
The fix for this issue has been submitted in [cbioportal-frontend PR #2667](https://github.com/cBioPortal/cbioportal-frontend/pull/2667).

**Comment by Sjoerd-van-Hagen** [comment]
Fixed and released @tmazor
