### ISSUE TITLE
Color of CNA diploid in waterfall plot

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6553]
We usually use gray for no data, so can we consider swapping colors to indicate diploid in the waterfall plots?

![image](https://user-images.githubusercontent.com/11892704/64049744-db0fbd80-cb43-11e9-8046-f54be21725ab.png)

**Comment by ngocnn1104** [comment]
I have looked for other plots and it seems that we have been using color gray for Diploid, so the example you presented is actually correct and consistent with the general styles. Please provide other cases you can find where Diploid is indicated with a different color.

![plot1](https://user-images.githubusercontent.com/31291004/64690781-7df40000-d491-11e9-9378-c7947335de8d.png)

![plot2](https://user-images.githubusercontent.com/31291004/64690701-4f762500-d491-11e9-8fb5-5f8bbcd8e9b2.png)

**Comment by pvannierop** [comment]
@schultzn If there is still a desire to change the color of the CNA diploid value, I propose to attach this to a different milestone. I remove this issue from the 3.1.0 milestome.

**Comment by schultzn** [comment]
Ok... it looks like the other plots do not have a color for "not profiled". We should probably revisit this for all plots.
