### ISSUE TITLE
x-frame-option for the network tab

### ISSUE THREAD

**Issue by zhanxw** [cBioPortal/cbioportal#6555]
This issue is about how to config cbioportal within the spring framework.
The same phenomenon was previously discussed (https://github.com/cBioPortal/cbioportal/issues/4400),
but after I followed the instruction there, the iframe response header still had  `x-frame-option` to be `deny`.

Here is my setting for `portal/src/main/webapp/WEB-INF/web.xml`:

<filter>
     <filter-name>springSecurityFilterChain</filter-name>
     <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
 </filter>

 <filter-mapping>
   <filter-name>springSecurityFilterChain</filter-name>
   <url-pattern>/*</url-pattern>
 </filter-mapping>

 
 <filter>
     <filter-name>httpHeaderSecurity</filter-name>
     <filter-class>org.apache.catalina.filters.HttpHeaderSecurityFilter</filter-class>
     <async-supported>true</async-supported>
     <init-param>
       <param-name>antiClickJackingOption</param-name>
       <param-value>SAMEORIGIN</param-value>
     </init-param>
 </filter>

**Comment by alisman** [comment]
@zhanxw We are going to retire the network tab in about 1 month due to obsolete data.  For this reason it may not make sense to invest time understanding this.  @jjgao ?

**Comment by jjgao** [comment]
@zhanxw we will replace it with a pathway view.

**Comment by zhanxw** [comment]
Thank you. I look forward to the new version.
