### ISSUE TITLE
DRY up ProfileDataMapper.xml SQL

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#656]
https://github.com/adamabeshouse/cbioportal/commit/f2179df85b5195f6134d9e02bb776e6e75141e35#commitcomment-15068273

**Comment by jjgao** [comment]
@adamabeshouse update?

**Comment by adamabeshouse** [comment]
No update yet.

**Comment by adamabeshouse** [comment]
New API deprecates this implementation.
