### ISSUE TITLE
Mismatched mutation count?

### ISSUE THREAD

**Issue by zhanxw** [cBioPortal/cbioportal#6562]
Hello, 

In https://www.cbioportal.org/study/clinicalData?id=acc_tcga_pan_can_atlas_2018 , 
the mutation count for sample TCGA-OR-A5J1-01 is 24.

but in page https://www.cbioportal.org/patient?sampleId=TCGA-OR-A5J1-01&studyId=acc_tcga_pan_can_atlas_2018 , 
mutation , it reported 64 mutations for the same sample.

Why these two numbers are different?

**Comment by jjgao** [comment]
@sheridancbio could you help look into this? Please also check if it occurs to other samples.

**Comment by n1zea144** [comment]
@jjgao Looks like mutation count does not take into account reported Fusions.  How do you want to proceed?

**Comment by jjgao** [comment]
@n1zea144 I see. Fusions should not be counted as mutations and we will separate the fusions into a fusion table.

**Comment by zhanxw** [comment]
Hello, I still find discrepancy on cBioportal 3.0.1 hosted on my server. Please see the screenshot:
https://imgur.com/gallery/zhjUKLX

The reported mutation count for this sample is 1.
But this sample has 18 mutations including 4 missense mutations. 
Can you please resolve the discrepancy? Thanks.

**Comment by zhanxw** [comment]
I checked the `clinical_sample` in MySQL database, and the MUTATION_COUNT is 1, and that is incorrect.

I doubt the study import script/program has some problem. 
Can you point out where the relevant codes to calculate MUTATION_COUNT?

**Comment by jjgao** [comment]
@zhanxw the code is here: https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/dao/DaoMutation.java#L134

**Comment by zhanxw** [comment]
I guess that the reason is that I did not provide enough mutation information (chromosome name, position et al). I will report back if I found solutions. Thanks!
