### ISSUE TITLE
Rename the tables patient_list and patient_list_list to sample_list and sample_list_list

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#657]
It's quite unclear at the moment because these tables actually refer to sample id lists, not patient id lists. But because the elements of the lists are referred to by internal id, there's no way of knowing that it refers to sample ids, not patient ids. So this is actually very confusing right now.

**Comment by jjgao** [comment]
It is log in this issue: https://github.com/cBioPortal/cbioportal/issues/517.
