### ISSUE TITLE
Change Heatmap Button based on available data

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6570]
Heatmap button on oncoprint shows up when there is:

- Treatment Response (Tx Response)
- mRNA Expression (mRNA)
- Methylation (Methylation)
or
- Gene sets (?) (GSVA)

Let's change the button text based on available data, e.g.:

`mRNA Heatmap`

or 

`Tx Response Heatmap`

If multiple use `/`, e.g.:

`mRNA / Tx Response Heatmaps`

See the text above in parenthesis, e.g. `(Tx Response)`, for what to put in the text of the button

**Comment by pvannierop** [comment]
@inodb I propose to add this to the 3.1.1 milestone.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen I am wondering if you have the bandwidth for this?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao Yes, we can do this.

**Comment by jjgao** [comment]
We have number bubble now but still don't know about the available data. Should we have tabs for different types?

![image](https://user-images.githubusercontent.com/840895/71311145-e8023680-23ea-11ea-8427-65af29f7c1c9.png)

I am moving this to watch-list as it does not seem like a priority.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao That is what I suggested in one of the other discussion around this. There is plenty of room in the button-bar for adding more buttons, esp now some of this has been moved to the 'global' config button.

**Comment by jjgao** [comment]
Not sure if we should open that discussion again - we spend so much time last time :)

Maybe we can just add a few tab under the "Add Heatmap Tracks" dropdown?

**Comment by jjgao** [comment]
I'd like to close this issue for now. @inodb @Sjoerd-van-Hagen please feel free to re-open or open a new one if needed.
