### ISSUE TITLE
How to change the right logo on cbioportal which has been installed using docker?

### ISSUE THREAD

**Issue by lakhujanivijay** [cBioPortal/cbioportal#6573]
Hi 

I am wondering how to I change the right hand side logo on my local cbioportal instance installed using docker ?

Right now, I am able to change the logo using an already available image (oncokb.png) but as soon as I put a new image, it does not work. Here is what I did to get the oncokb image logo on the right hand side of the cbioportal instance:

1. `docker exec -it cbioportal-container bash`

2. got to the images folder
`root@113f04533e68:/cbioportal# cd portal/images/`

3. do `ls`
```root@113f04533e68:/cbioportal/portal/images# ls
cancer-hotspots.svg  cbioportal_icon.png  down.png  driver.png	driver_tiers.png  menudots.svg	
oncokb-oncogenic-1.svg	oncokb.png
```
4. update `portal.properties` file as follows
`skin.right_logo=oncokb.png`

4. restart the container
`docker restart cbioportal-container`

If I do this, I can see the oncokb image on cbioportal instance

<a href="https://imgbb.com/"><img src="https://i.ibb.co/JvRcYd4/onck.png" alt="onck" border="0"></a>

**Comment by lakhujanivijay** [comment]
Hi @xpivarc That was informative however can you help me with more details as to how to use volume in that case such that I can have the logo permanently set up?

**Comment by xpivarc** [comment]
@lakhujanivijay simplest way (but also depends on your "startup process") is to add " -v /<path_to_image>:/<where_to_mount_in_container> " to your docker run command.

**Comment by jjgao** [comment]
@lakhujanivijay I am closing this. Please comment if you have additional questions.

**Comment by lakhujanivijay** [comment]
Hi 

Unfortunately, I am still not able to change the right logo. can someone please help?

**Comment by inodb** [comment]
Hi @lakhujanivijay !

You can mount files in the `/cbioportal-webapp` folder which has the contents of the extracted war:

https://github.com/cBioPortal/cbioportal/blob/master/docker/web-and-data/Dockerfile#L54

e.g. after following these steps:

https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended

you can do something like this:

```
docker run -d -v ~/Downloads/dna_logo.png:/cbioportal-webapp/images/dna_logo.png --restart=always     --name=cbioportal-container     --net=cbio-net -e JAVA_OPTS='
        -Xms2g                                                                        
        -Xmx4g                                                                                                                     
        -Dskin.right_logo=dna_logo.png     
        -Dauthenticate=noauthsessionservice                                                                                                                                                               
        -Dsession.service.url=http://cbio-session-service:5000/api/sessions/my_portal/                                             
    '     -p 8081:8080     cbioportal/cbioportal:latest     /bin/sh -c 'java ${JAVA_OPTS} -jar webapp-runner.jar /cbioportal-webapp' 
```

Does that help?
