### ISSUE TITLE
Step 4 of Docker install assumes db-scripts is in container when it is not

### ISSUE THREAD

**Issue by Luke-Sikina** [cBioPortal/cbioportal#6574]
## Steps to Reproduce
I was using the [documentation](https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker) to install the cBioportal. I got to step 4 successfully and ran this: 
```bash
docker run --rm -it --net cbio-net \
    -v /home/luke/code/cbioportal-properties/portal.properties:/cbioportal/portal.properties:ro \
    cbioportal/cbioportal:3.0.1 \
    migrate_db.py -p /cbioportal/portal.properties -s /cbioportal/db-scripts/src/main/resources/migration.sql
```
I expected this to migrate the database. Instead, it reported this error: 

> sql file /cbioportal/db-scripts/src/main/resources/migration.sql cannot be found

## Confirmation
I stepped into the container using this command:
```bash
docker run --rm -it --net cbio-net \
    -v /home/luke/code/cbioportal-properties/portal.properties:/cbioportal/portal.properties:ro \
    cbioportal/cbioportal:3.0.1 \
    /bin/bash
```
and confirmed that the file was in fact not in the container. Furthermore, the `/cbioportal/db-scripts/` directory does not exist.

## Cause
This happens because the 3.0.1 container does not copy db-scripts. This issue was fixed in 3.0.6. Amending the command to reference a newer allows the script to run.

**Comment by pvannierop** [comment]
This is the same issue as reported in #6558.
