### ISSUE TITLE
Keep the state after Modify Query

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6579]
Currently, most states got lost. Can we try to keep as much as possible?

**Comment by alisman** [comment]
@jjgao there is further question about whether to keep state in url so it is persisted across page loads (and shareable).   Shall we just keep ALL state in url?   And fur ther, do we want to add subtabs for genes into the path.  e.g. results/cancerTypesSummary/TP53

**Comment by jjgao** [comment]
@alisman I don't think we need to keep all states in the url, e.g. search term in the mutations table is not necessary to be persisted across page loads.

Maybe we should have a separate discussion about what to save in the url?

**Comment by jjgao** [comment]
fixed in the gigantic url wrapper pr.
