### ISSUE TITLE
tweaking study view 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#658]
The Query, View, and Download buttons look a bit awkward. I'd propose to do the following.

 - [x] remove both View and Download buttons
 - [x] make the number of selected samples a button -- the same function as the view button
 - [x] add a small download icon to the right of (or inside?) the selected samples button -- the same download icon as used in individual charts
 - [x] Don't treat one sample differently, ie. when selecting only one sample, display a button with 1 sample.

![image](https://cloud.githubusercontent.com/assets/840895/11966639/f058613c-a8ca-11e5-96a5-b2a8ea4c7446.png)

**Comment by pieterlukasse** [comment]
nice

**Comment by zhx828** [comment]
The download icon looks a little weird.
