### ISSUE TITLE
Expression tab in pan-cancer query should only show TCGA studies

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6595]
![image](https://user-images.githubusercontent.com/11892704/64821052-d99cb700-d57f-11e9-8019-8e596fafff68.png)

**Comment by jjgao** [comment]
@alisman If pancan studies are selected, let's only show the pancan ones by default.

**Comment by alisman** [comment]
@jjgao how do studies which are TCGA, but NOT PanCan Atlas fit in?   Which category?

**Comment by schultzn** [comment]
I think this tab should only ever show TCGA PanCancer Atlas studies, none of the other TCGA studies, or any other studies. 


That is an easy decision to make for the public portal. But in certain local instances with uniformly processed mRNA data from other sources, some people might want to change that behavior. 

Maybe we should discuss this in more detail in person?

**Comment by jjgao** [comment]
Initially we were only showing TCGA studies, but later there was a request to make it available for immunogenomcis studies (immunotherapy portal).

I think we should give the user option to select non-pancan studies, but by default only display PanCan studies if at least one PanCan study is selected.

**Comment by alisman** [comment]
Do regular TCGA studies (non pancan) get treated just like all other non-pancan studies?

**Comment by jjgao** [comment]
> @jjgao Do regular TCGA studies (non pancan) get treated just like all other non-pancan studies?

yes.

> And for other instances (where I assume we can't make any assumptions about study ids, we should probably just show all studies with expression data, yes?

I think we can have the same logic for all insances of portals. If they don't have any pancan studies in their databbase, all selected studies with expression data should be shown.

(if no pancan studies are selected, we should just show all studies in the tab.)

**Comment by jjgao** [comment]
@alisman: had some discuss with @schultzn - let's not make any change and fix the data. the pancreas study should probably have V1 rna seq profile.

**Comment by jjgao** [comment]
Filed issue on datahub: https://github.com/cBioPortal/datahub/issues/830
