### ISSUE TITLE
Improve styling prev/next case in patient view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#66]
Change prev and next case buttons to be more in line with the rest of the patient view styling
![screen shot 2015-06-04 at 11 23 00 am](https://cloud.githubusercontent.com/assets/1334004/7987538/23b100d8-0aac-11e5-96fa-cd4659973fe8.png)

**Comment by inodb** [comment]
Couple of ideas
![screen shot 2015-06-11 at 11 54 17 am](https://cloud.githubusercontent.com/assets/1334004/8111579/b013efb6-1030-11e5-9dee-c308a87bbcfb.png)
![screen shot 2015-06-11 at 11 41 30 am](https://cloud.githubusercontent.com/assets/1334004/8111580/b014d476-1030-11e5-8310-7d783f6afd2f.png)
![screen shot 2015-06-11 at 11 25 32 am](https://cloud.githubusercontent.com/assets/1334004/8111581/b01dc626-1030-11e5-883a-1cee572ba4d7.png)
![screen shot 2015-06-11 at 11 09 09 am](https://cloud.githubusercontent.com/assets/1334004/8111647/f28c9b7c-1030-11e5-90e9-0c6a9f71d3fb.png)

**Comment by jjgao** [comment]
this one looks good to me:

https://cloud.githubusercontent.com/assets/1334004/8111580/b014d476-1030-11e5-8310-7d783f6afd2f.png

**Comment by inodb** [comment]
Thanks. I made some larger screenshots.

![screen shot 2015-06-11 at 12 03 33 pm](https://cloud.githubusercontent.com/assets/1334004/8111824/ef79b50e-1031-11e5-8ce9-e77315b2b98a.png)

![screen shot 2015-06-11 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/1334004/8111825/ef7a76f6-1031-11e5-8eae-cc5b525a03f2.png)

![screen shot 2015-06-11 at 12 03 06 pm](https://cloud.githubusercontent.com/assets/1334004/8111826/ef7ba526-1031-11e5-8a7b-115ac27c95b3.png)

![screen shot 2015-06-11 at 12 02 45 pm](https://cloud.githubusercontent.com/assets/1334004/8111829/ef80cace-1031-11e5-8a7b-8670f5605fdf.png)

![screen shot 2015-06-11 at 12 02 25 pm](https://cloud.githubusercontent.com/assets/1334004/8111827/ef7f9dd4-1031-11e5-87ff-d1510f319261.png)

![screen shot 2015-06-11 at 12 01 50 pm](https://cloud.githubusercontent.com/assets/1334004/8111828/ef8042d4-1031-11e5-9546-c249bbd152fc.png)

The patients with a lot of samples don't look super neat but it might be ok 

![screen shot 2015-06-11 at 12 12 37 pm](https://cloud.githubusercontent.com/assets/1334004/8112023/3416758e-1033-11e5-8670-de71def89406.png)

![screen shot 2015-06-11 at 12 12 00 pm](https://cloud.githubusercontent.com/assets/1334004/8112024/389866da-1033-11e5-909a-76af0f3a031c.png)
