### ISSUE TITLE
Study view: Is it possible to display the number of sample early?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6607]
Sometimes, I just want to click the View button but I have to wait for all data to be loaded.

![image](https://user-images.githubusercontent.com/840895/64972707-bfacee00-d877-11e9-858c-be3f68c98c3c.png)

**Comment by alisman** [comment]
@jjgao just want to confirm that you mean the "View Selected Cases" button, correct?

**Comment by jjgao** [comment]
Yes, and also the numbers of samples if possible.

**Comment by jjgao** [comment]
@alisman @Luke-Sikina I am reopening this. I think we are displaying it too early now. Can we hide it before the numbers are ready?

![image](https://user-images.githubusercontent.com/840895/66083135-b2f7ed80-e539-11e9-83f9-868c6539653f.png)

**Comment by alisman** [comment]
@jjgao yes, we have a PR to fix this already.  should be merged very shortly.

**Comment by Luke-Sikina** [comment]
Fixed with: https://github.com/cBioPortal/cbioportal-frontend/pull/2748
