### ISSUE TITLE
retire Network tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6610]
With PathwayMapper feature coming (https://cbio-pm.herokuapp.com/), maybe it's time to retire the current Network view? ... because:

- The data is really old (7 years old!) and we don't have a pipeline to update the data.
- The code is old and will be expensive to refactor and maintain.
- We can point users who like to current Network veiw to PCViz (http://www.pathwaycommons.org/pcviz/) which can load the pathway commons data and add cbioportal single study data on top.

@cBioPortal/product @ugurdogrusoz

**Comment by schultzn** [comment]
Sounds good. Should we start giving users a warning, maybe by adding a message on the Network tab in the 3.1 release? That way they can get used to going to PCViz instead.

**Comment by Sjoerd-van-Hagen** [comment]
+1 for replacing the old network view and +1 for giving the user proper warning.

**Comment by jjgao** [comment]
@alisman could you add a warning in Network tab for the 3.1.0 release?
