### ISSUE TITLE
Highlighting errors in gene query in study view causes unintended deltions

### ISSUE THREAD

**Issue by Luke-Sikina** [cBioPortal/cbioportal#6620]
# Reproduction
1. Go to: https://www.cbioportal.org/study/summary?id=msk_impact_2017
2. Focus on the gene query text area at the far right
3. Type "BRAF:" and then pause for at least 1 second
4. Continue typing a valid OQL query, like " MUT"
5. Note that you ended up typing "BRAF MUT" instead of "BRAF: MUT"

# Problem
When you pause for more than half a second after typing a colon, the colon will become highlighted because it is invalid OQL. This causes you to delete the colon when you resume typing, resulting in a different query than what you intended.

**Comment by jjgao** [comment]
@Luke-Sikina good catch. Instead of using selection to highlight, I am wondering if we could use something similar to spell check? Maybe there is a custom spellcheck library we can use?

(this is a minor issue and let's fix it only if it does not require much time.)

**Comment by tmazor** [comment]
This is only a problem on study view, but is not a problem on the homepage. The two gene boxes have slightly different behavior. On the home page, you are told to click "Submit" to get the error highlighted. On study view, this highlighting happens automatically, which is what causes the issue Luke identified.

@jjgao can we just make the study view gene box work the same way as the homepage gene box?

**Comment by Luke-Sikina** [comment]
@tmazor Front a code standpoint, this is easier than it was now that the homepage gene box and the study view gene box use the same component.

**Comment by jjgao** [comment]
@Luke-Sikina please feel free to fix it if it's a very quick fix. Another option to fix it when we do https://github.com/cBioPortal/cbioportal/issues/6781.
