### ISSUE TITLE
Error when switching between patients in patient cohort

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6621]
Click next/prev patient buttons and you will see error in console

https://bit.ly/2MuciPl

**Comment by dippindots** [comment]
@alisman Is this the correct URL? I haven't seen the `next/prev patient buttons`...

**Comment by onursumer** [comment]
@dippindots seems not. this should be an issue on the patient view page.

**Comment by alisman** [comment]
![image](https://user-images.githubusercontent.com/186521/66594466-3a131a00-eb67-11e9-9999-60ab8e308844.png)
