### ISSUE TITLE
New CheckedSelect component does not adhere to cBioPortal style

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#6622]
While incorporating the CheckedSelect component in the OncoPrint tab treatment selection menu we found that the CheckedSelect does not style consistent with other select menu's in cBioPortal (see screenshot below). There are several problems:

1. The there is a blue background color for currently selected items. This blue color is not constitent with cBioPortal blue. I propose to not assign a background color for CheckedSelect since the checkbox provides feedback on selection to the user.
2. The arrow at the right side of the select box is of a different style than that of other select menu's used in cBioPortal.
3. There is a divider line next to the rightside arrow that is absent in other select menu's used in cBioPortal.
4. The old style checkmarks for selected list items were more clear, in our opinion. 

# Screenshot old react-select-checked
![image](https://user-images.githubusercontent.com/745885/65241734-9a70e780-dae4-11e9-9fe2-3ad5c689e76d.png)

# Screenshot new CheckedSelect
![image](https://user-images.githubusercontent.com/745885/65241756-ac528a80-dae4-11e9-952e-5f8114acc61c.png)

**Comment by jjgao** [comment]
notifying @alisman
