### ISSUE TITLE
treatment data gets 403 error on mskcc authenticated portal

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6623]
Not sure if this issue is for any authenticated portal or just mskcc. Fix here for erroneous treatment response (oncoprint controls wouldn't show): https://github.com/cBioPortal/cbioportal-frontend/pull/2719.

**Comment by inodb** [comment]
@pvannierop have you by any chance seen this when using an authenticated portal? Or is this limited to our mskcc portal auth?

**Comment by pvannierop** [comment]
@ino No we see it also on other authenticated portals. I have to investigate why this happens. @n1zea144 Obviously fetch of treatments works on a public portal. Would you be able to provide a clue on why an endpoint might deny access when authentication is used? AFAIK all end points are open; it's only at the level of visible studies that there is a limit. Is that correct? I think that what goes wrong is the retrieval of treatments based on study_id. Any background information on this would help me identify the problem.

**Comment by n1zea144** [comment]
@pvannierop After some thought, yes.  You need to update [CancerStudyExtractorInterceptor](https://github.com/cBioPortal/cbioportal/blob/master/web/src/main/java/org/cbioportal/web/util/InvolvedCancerStudyExtractorInterceptor.java) to process fetch requests for treatment data.

**Comment by sheridancbio** [comment]
We are not sure how to handle permissions when the filter contains only treatmentIds ... how can we know which samples the user has access to?

**Comment by sheridancbio** [comment]
We now are thinking that querying /api/treatments/fetch and supplying a TreatmentFilter containing only TreatmentIds may only be returning meta information about the treatments themselves rather than any sample data. But we are not sure. For now the endpoint will reject all calls that provide only TreatmentId arguments ... but we can probably allow such calls to pass through and always be responded to.

**Comment by pvannierop** [comment]
@sheridancbio 
>We now are thinking that querying /api/treatments/fetch and supplying a TreatmentFilter containing only TreatmentIds may only be returning meta information about the treatments themselves rather than any sample data. But we are not sure. For now the endpoint will reject all calls that provide only TreatmentId arguments ... but we can probably allow such calls to pass through and always be responded to.

Treatments are like genes. Treatments are not tied to a sample or study. When treatments are fetched by the treatmentId, this is allowed.

**Comment by sheridancbio** [comment]
will do ... we were thinking that would be appropriate as we understood the endpoint better.

**Comment by pvannierop** [comment]
@sheridancbio Thank you very much for your assistance.
