### ISSUE TITLE
missing oncoprint menu on msk portal

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6624]
https://cbioportal.mskcc.org/results/oncoprint?session_id=5d83951ee4b0616a4480aa3e

![image](https://user-images.githubusercontent.com/840895/65255075-41488a00-dacb-11e9-9e61-f773d26f6f5a.png)

**Comment by alisman** [comment]
@jjgao this is now fixed.  it was due to permissions problem with new treatment service.  the temporary fix ignores this error.

**Comment by jjgao** [comment]
thanks, @alisman . Could you open another ticket to fix it properly?

**Comment by jjgao** [comment]
I saw it: https://github.com/cBioPortal/cbioportal/issues/6623.

**Comment by pvannierop** [comment]
@n1zea144 Obviously fetch of treatments works on a public portal. Would you be able to provide a clue on why an endpoint might deny access when authentication is used? AFAIK all end points are open.
