### ISSUE TITLE
Download tab: Somatic vs germline information is missing from downloads

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6625]
We should include in the downloads information about germline vs somatic - our default could be somatic, in which case we don't add the information, but we would label germline variants as "germline"

**Comment by inodb** [comment]
@dippindots do u know if this is fixed?

**Comment by dippindots** [comment]
@inodb It hasn't been fixed yet, any suggestions on how to show the differences information?

**Comment by jjgao** [comment]
In [this example](http://bit.ly/33qWQvL), we could display it in the similar as in mutations tab. In the downloaded file, append ` [germline]`.

![image](https://user-images.githubusercontent.com/840895/76636419-64ef0900-651f-11ea-95fa-7ab29f68f877.png)

**Comment by inodb** [comment]
I think ☝️would work

To add some context: we are using quite a lot of different formats

E.g. the oncoprinter is using a different input format for how to indicate germline: https://www.cbioportal.org/oncoprinter. The output in downloads tab doesn't work as the input for oncoprinter, but that's a separate issue

Would be nice to fix https://github.com/cBioPortal/cbioportal/issues/3973, so we can just add a Mutation_Status column. That's the input to cBioPortal

**Comment by jjgao** [comment]
unstale

**Comment by adamabeshouse** [comment]
@jjgao @inodb which approach should I take? add a column, or just add [germline] to the protein change code?

**Comment by jjgao** [comment]
@adamabeshouse Not sure how we can add a column since they may be both germline and somatic mutations in the same gene and same sample. I think add [germline] is ok. Please add to both `Type of Genetic Alterations Across All Samples` table and downloadable file. Thanks

**Comment by jjgao** [comment]
@adamabeshouse for txt download, maybe fix https://github.com/cBioPortal/cbioportal/issues/3972 too?
