### ISSUE TITLE
SAML response error 

### ISSUE THREAD

**Issue by timchu90** [cBioPortal/cbioportal#6627]
Hi,

We're having an issue with keycloak authentication in our local cbioportal instance. 
We previously had it working but when we moved domains the SAML responses keep referring to the old domain. 
As a result, even if a user successfully logs into cbioportal, they get sent to https://[cbioportal-host]/login.jsp?login_error=true
How is the SAML response generated? How does it decide which hostname to use?
Any suggestions on a problem like this? 

Thanks,
Tim

**Comment by jjgao** [comment]
@timchu90 thanks for contacting us. Also saw your question on Google Groups. We will answer there.

**Comment by khzhu** [comment]
@timchu90 ,
to answer your questions:
1. please read this [document](https://www.keycloak.org/docs/6.0/server_admin/#saml-bindings). It explains how saml response is generated. 
2. **_Valid Redirect URIs_** defines URL pattern for Keycloak to use upon a successful authentication. 
3. did you set both **_Force POST Binding_** and **_Front Channel Logout_** to OFF and **_Force Name ID Format_** to ON? and modify the portal.properties have 
```
# global logout (as opposed to local logout):
saml.logout.local=false
saml.logout.url=/
```

**Comment by timchu90** [comment]
Thanks for your help, we managed to trace down the issue to Tomcat. Enabling SSL to Tomcat fixed that problem.

**Comment by jjgao** [comment]
@timchu90 if you think there is anything that the documentation can be improved, we welcome pull requests :)
