### ISSUE TITLE
Plots tab does not load

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#6629]
The plot tab keeps loading for studies in the triage and MSK portals. And it looks like its looking for treatment data even though it's not there. It works in the public portal:
![Screen Shot 2019-09-20 at 1 35 05 PM](https://user-images.githubusercontent.com/12007862/65346760-7b895880-dbab-11e9-9efd-71eb50fc7a0f.png)

**Comment by n1zea144** [comment]
@pvannierop Maybe this may be related to issue [6623](https://github.com/cBioPortal/cbioportal/issues/6623), but why would a fetch for treatment info be executed if the study does not contain treatment info?

**Comment by jjgao** [comment]
@pvannierop would you have time to help with this? We need to fix it soon. Thanks.

**Comment by jjgao** [comment]
It looks like @sheridancbio has started working on this. https://github.com/cBioPortal/cbioportal/pull/6630

**Comment by n1zea144** [comment]
Yeah, working on a PR now, but we are not sure what is suppose to happen when treatment ids are passed via the request instead of cancer study ids:
[fetchTreatments](https://beta.cbioportal.org/api/swagger-ui.html#/Treatments/fetchTreatmentsUsingPOST)

**Comment by pvannierop** [comment]
I refer to my comment in the primary issue --> https://github.com/cBioPortal/cbioportal/issues/6623#issuecomment-534036295

**Comment by sheridancbio** [comment]
The issue related to the treatment endpoints have been fixed and merged. There are additional fixes to other API PreAuthorize tag use problems in the works. (#6656)  When these are merged and authenticated portals are built and tested we may be able to close this issue.
