### ISSUE TITLE
reference genome genes endpoint is a bottleneck

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6635]
This endpoint shows up in monitoring as a performance drain on db. 

https://www.cbioportal.org/api/reference-genome-genes/hg19

It returns all ~143,000 genes in public portal.   Is it necessary to return all of them or could we instead return just genes which are queried?

@jjgao @inodb

**Comment by jjgao** [comment]
We discussed about caching the data in frontend.

**Comment by jjgao** [comment]
- [ ] add `last_updated_genes` into [info table](https://github.com/cBioPortal/cbioportal/blob/master/db-scripts/src/main/resources/cgds.sql#L844)
- [ ] increase the database schema version
- [ ] update [migration.sql](https://github.com/cBioPortal/cbioportal/blob/master/db-scripts/src/main/resources/migration.sql)
- [ ] add to the [import gene script](https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportGeneData.java#L163)
- [ ] add to `info` api
- [ ] cache all gene reference info in frontend
- [ ] check timestamp and sync data, e.g. when opening the site
- [ ] using the cached data in frontend
- [ ] remove all other connection to the gene data in other api/babckend

**Comment by n1zea144** [comment]
@Luke-Sikina @jjgao The persistence methods to support the ref-genome gene info were not being cached by EhCache.  I would hold off caching data in the front-end until we get the memory spikes resolved in the backend and EhCache working.  That seems a better place to cache ref gene information.

**Comment by jjgao** [comment]
@n1zea144 Since the gene and reference genome information data are not changing frequently, we think it may make sense to cache them in the frontend. As discussed, this data will replace data from API, e.g. for co-expression.

**Comment by jjgao** [comment]
@Luke-Sikina found that we could use sql to get the time of last update to a table so that it's not necessary to modify the info table.

```sql
SELECT UPDATE_TIME
FROM   information_schema.tables
WHERE  TABLE_SCHEMA = 'dbname'
   AND TABLE_NAME = 'tabname'
```
