### ISSUE TITLE
add "one sided" to MutEx fisher exact tooltip

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6638]
Change tooltip text to:
Derived from one-sided Fisher Exact Test

**Comment by dippindots** [comment]
@tmazor Should we update the tooltip on enrichment tab also? 
![image](https://user-images.githubusercontent.com/15748980/65790433-a2a4d480-e12d-11e9-9a24-745883db9e6c.png)

**Comment by tmazor** [comment]
@dippindots if it's a one-sided test on enrichments also, then yes, we should definitely update.
