### ISSUE TITLE
Visualization issue with Waterfall plot when axes are swapped

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6640]
Bars overlap the axis

https://beta.cbioportal.org/results/plots?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=mixed_broad_ccle_2018&case_set_id=mixed_broad_ccle_2018_cnaseq&data_priority=0&gene_list=BRAF&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=mixed_broad_ccle_2018_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=mixed_broad_ccle_2018_mutations&heatmap_track_groups=mixed_broad_ccle_2018_CCLE_drug_treatment_IC50%2CAfatinib-1%2CPLX-4720-1&show_samples=false&tab_index=tab_visualize&treatment_list=Afatinib-1%3BPLX-4720-1

![image](https://user-images.githubusercontent.com/11892704/65639451-28057900-dfb6-11e9-899f-b3bc1f4874c1.png)

**Comment by ngocnn1104** [comment]
This issue will be fixed by pending PR [#2753](https://github.com/cBioPortal/cbioportal-frontend/pull/2753).
