### ISSUE TITLE
link in file format documentation doesn't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6642]
In the second paragraph of the Clinical Data section (https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#clinical-data), there's a link to bring you a bit further down the page to the section on custom columns. However, that link doesn't work:
https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#custom-columns-in-clinical-data

**Comment by jjgao** [comment]
@tmazor I assigned this to you :) Please feel free to reassign.

**Comment by tmazor** [comment]
I can't figure this one out... @alisman can you help?

**Comment by alisman** [comment]
This looks like a markdown problem. The target title has no id corresponding to the links (custom-columns-in-clinical-data).   We need to figure out if the markup is missing.

**Comment by jjgao** [comment]
@alisman the md file is here: https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md

**Comment by inodb** [comment]
@alisman https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md
