### ISSUE TITLE
copy number alterations not showing up in oncoprint that are on study view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6647]
See e.g. CCND1 in study view: https://www.cbioportal.org/study/summary?id=breast_msk_2018. 

<img width="400" alt="Screen Shot 2019-09-26 at 3 56 25 PM" src="https://user-images.githubusercontent.com/1334004/65720590-4763db00-e076-11e9-8a24-acba9c0bb5f9.png">

Then query for CCND1 in the same study. You'll notice no CNAs are shown:

<img width="1369" alt="Screen Shot 2019-09-26 at 3 56 48 PM" src="https://user-images.githubusercontent.com/1334004/65720603-4b8ff880-e076-11e9-97a7-ecaf037db913.png">

**Comment by inodb** [comment]
@adamabeshouse @zhx828 assigned u to this for now, but feel free to reassign

**Comment by adamabeshouse** [comment]
the molecular data API is returning empty array, no CNA in it. Something's going on in the backend
@kalletlak ?

**Comment by kalletlak** [comment]
@adamabeshouse @jjgao @inodb looks like data loading issue. somehow this data is missing in `genetic_alteration` table. Similarly gene data which is present in `genetic_alteration` is missing in `sample_cna_event`. Example gene `CCT5` which show alterations in oncoprint is missing in CNA table in study view

**Comment by kalletlak** [comment]
@inodb re-importing study might fix this error

**Comment by jjgao** [comment]
@ritikakundra @yichaoS @rmadupuri would you please schedule a re-import of the study?

**Comment by ritikakundra** [comment]
@jjgao @kalletlak reimport did the trick, CCND1 is now 19% altered (majorly amp):
http://www.cbioportal.org/results/oncoprint?Action=Submit&cancer_study_list=breast_msk_2018&case_set_id=breast_msk_2018_all&gene_list=CCND1&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=breast_msk_2018_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=breast_msk_2018_mutations&tab_index=tab_visualize&show_samples=false&clinicallist=NUM_SAMPLES_PER_PATIENT

**Comment by kalletlak** [comment]
@jjgao @ritikakundra @yichaoS @rmadupuri here are remaining studies which have similar issue
```
urcc_mskcc_2016
egc_msk_2017
nsclc_pd1_msk_2018
lung_msk_2017
ucec_msk_2018
```

@jjgao @inodb noticed one more thing, there are some records in `genetic_alteration` and `sample_cna_event` which are not mapped to any `genetic_profile`. here are some of them GENETIC_PROFILE_ID -> 6902, 7286, 7300

**Comment by ritikakundra** [comment]
Scheduled these for import

**Comment by jjgao** [comment]
@kalletlak could you please post the sql query you made? @ritikakundra do we have database tests? If so, we can add Karthik's script.

**Comment by ritikakundra** [comment]
@kalletlak Is CCND1 for:
urcc_mskcc_2016
egc_msk_2017
nsclc_pd1_msk_2018
lung_msk_2017
ucec_msk_2018


And second: Why do these genes go missing?

**Comment by kalletlak** [comment]
@ritikakundra No, in general. I was looking for Studies which has records in CNA table in study view but doesn't show-up in oncoprint for same genes.

Not sure why those are not added into genetic_alteration table.
