### ISSUE TITLE
OncoPrint takes too long to render for large sample sets

### ISSUE THREAD

**Issue by Luke-Sikina** [cBioPortal/cbioportal#6657]
# Problem
For large data sets, the OncoPrint tab can take minutes to load, if it loads at all. During this time it consumes a lot of CPU resources and memory.

# Example
Link: https://www.cbioportal.org/results/oncoprint?clinicallist=CANCER_STUDY%2CNUM_SAMPLES_PER_PATIENT%2CPROFILED_IN_COPY_NUMBER_ALTERATION%2CPROFILED_IN_MUTATION_EXTENDED&session_id=5d9268aae4b0656ac4cf2938&show_samples=false
Number of samples: `79010`
Number of genes queried: `5`
Load time: `~4.5 minutes`
Max heap size: `1.5 Gb`

# Investigation Thusfar
## Dividing oncoprint into logical segments
- In order to better understand what is under performing, break up the process into its parts
- Parts:
    - Data load
    - Data processing in cBioportal code
    - Processing in OncoprintJS
    - Rendering
## Measuring performance in each of those parts
- Challenges
    - Parts overlap, making timing a single part difficult
    - Anonymous functions make it harder to map profiler output to lines of code
- Strategies
    - Leverage front end request memoization to isolate networking
        - Requests under a certain size are memoized
        - This information is retained as long as you don’t refresh the page
        - This allows us to measure performance with and without the network requests by performing a query on a sample set, then returning to the homepage and repeating the process
        - Limitations
            - Responses for GENIE were too large and did not get cached
    - Reduce pipelining to isolate cBio logic from OncoprintJS logic
        - Code tweaks to ensure that the OncoprintJS library isn’t called until the data is loaded and processed _branch?_
    - Ignore problems, forge ahead with profiling
        - This can still provide some useful information
- Findings
    - Waiting for network requests is a significant component of overall time
        - Ex
            - Studies: `msk_impact_2017`
            - Query: `BRAF NRAS KRAS ERBB2 EGFR`
            - Uncached: `~12 seconds`
            - Cached: `~6 seconds`
        - Better example: Aaron’s spreadsheet, which I don’t have
        - Caveat: we only know this for medium sized datasets. For large datasets, the requests aren’t cached
    - We spend a lot of time trimming strings for `parseFloat` and `parseInt`
        - Same example as above: 10.7% of CPU time on the cached load was spent running `l.trim`
        - There are some parameter values that are typed as percentage strings or numbers that are, in practice, always percentage strings. Switching these values to numbers and assuming they are always percentage values could remedy this
        - Doing this without static type checking would be rough. Maybe wait until after the library is in typescript
## Discussion
- Are we at the point where we can no longer offer the current level of granularity in Oncoprint for large datasets?
- Are we delivering the data in an optimal fashion? Are there formats other than JSON that we should investigate using
- What is our goal? OncoPrint needs to scale, but by how much? What would be a realistic target for sample size and query size that would allow us to support people's use cases for the foreseeable future. 
## Potential Next Steps
- Typescript Oncoprint
- Changed stringly typed dimensions to only accept percentages

**Comment by adamabeshouse** [comment]
as a first step I'm going to try to address the frontend side - I suspect that there may be too many react renders being called. I'll report back on whether this helps

**Comment by adamabeshouse** [comment]
good news - just making sure that the oncoprint doenst keep rerendering seems to have improved it a lot. genie now renders in under a minute.

https://github.com/cBioPortal/cbioportal-frontend/pull/2853

I also updated the oncoprintjs version, I cant remember if I made any performance upgrades recently but I may have, anyway it doesnt hurt to update.

**Comment by adamabeshouse** [comment]
I'm gonna work on switching to percent numbers now

**Comment by adamabeshouse** [comment]
WOW! switching to percent numbers cut the render time to 15s!!!! good catch @Luke-Sikina
