### ISSUE TITLE
Reuse radio buttons component on plots tab for all plots

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6668]
On the plots tab when displaying clinical attributes, we should reuse the treatment component radio buttons:

![image](https://user-images.githubusercontent.com/1334004/64047438-cbd94180-cb3c-11e9-8c9e-90b6831e0de8.png)

Currently it's unclear what gene the dots are colored by:

![image](https://user-images.githubusercontent.com/1334004/64047551-1d81cc00-cb3d-11e9-92cb-bf450ff7c184.png)

Let's also apply it to all other plots.

**Comment by Sjoerd-van-Hagen** [comment]
It is colored based on all query genes, right?

**Comment by inodb** [comment]
Another thing I guess here is that it's using checkboxes vs radio buttons. Maybe it makes sense to make treatment use this component? Or we can unify the component in some other way perhaps that allows for both use cases?

**Comment by inodb** [comment]
Clearing the milestone until we've agreed on the spec

**Comment by Sjoerd-van-Hagen** [comment]
> Another thing I guess here is that it's using checkboxes vs radio buttons. Maybe it makes sense to make treatment use this component? Or we can unify the component in some other way perhaps that allows for both use cases?

With the waterfall plot using both the border and inside coloring would not work, unless you have a very small number of samples. This is why we color either by mutated or cna, not both.

**Comment by jjgao** [comment]
For plots other than waterfall, we only overlay the currently selected gene(s). I think it could be useful to allow users to select a different gene.

The checkbox vs radio box, I am leaning towards keeping it consistent.

Maybe we can reuse the waterfall options (including the gene dropdown and radio buttons) and add a new radio button `both` for non-waterfall plots?

**Comment by tmazor** [comment]
I agree about having consistency of checkbox vs radio, and I think a third radio button for "both" makes sense.

Can we also add an option of "Same gene (xxx)", like what we have for the Vertical Axis Gene selector? I think that should be the default and a user can always choose to change it to another gene.

I got a bit lost above... what's the question about coloring samples by two genes?

**Comment by jjgao** [comment]
> I got a bit lost above... what's the question about coloring samples by two genes?

@tmazor when there are different genes for x/y axes, the coloring is based on the two genes.

**Comment by tmazor** [comment]
ohhh thanks @jjgao that makes sense  - in that case, yes, I agree it's ok to only color by one gene

**Comment by jjgao** [comment]
@inodb @Sjoerd-van-Hagen I added the milestones back. Who should take this?

**Comment by Sjoerd-van-Hagen** [comment]
We can put it on our backlog but if you would like to do this short term it is better if you can take it up.

**Comment by jjgao** [comment]
Thanks, @Sjoerd-van-Hagen . I assign it to you :)

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao PR created.
