### ISSUE TITLE
Discussion of gene panel tab mockup for Patient View 

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#6670]
For RFC45 there is the need for a UI component that displays information on a gene panel. I would like to get feedback on the mockup that I have created for this new component. Features of this component:
- Is shown as a new tab in Patient View when gene panel link is clicked in Summary tab.
- Shows name of gene panel, the number of genes in the panel and an interactive multicolumn table that can be filtered based on a query.
- The table holds HUGO gene symbols concatenated with the Entrez Gene Id.
- The filter does a whole text search on each cell and covers gene symbol and entrez id. The filter allows for partial word matches.
- Data can be downloaded or copied to clipboard in tab-separated format. The gene symbol and entrez id are exported as two separate columns.

# Mockup
![image](https://user-images.githubusercontent.com/745885/66055113-5692cf00-e535-11e9-8269-284f5935c715.png)

**Comment by jjgao** [comment]
@pvannierop thanks for the mockup.

I don't think if we should have a `Gene panel` tab in the patient view. Another option is to implement a Gene Panel page for display information about a panel. In different places (patient view, study view, oncoprint, and maybe more) that refer to gene panels, we can than have a link to the gene panel page to open another window (or tooltip).

For the table, maybe we can have symbol and entrez IDs in separate columns?

cc'ing @cBioPortal/product

**Comment by jjgao** [comment]
BTW, I don't think we should have an RFC45 label. Instead, it may be better to use Zenhub to create an epic for RFC45 and assign the issues to the epic.

**Comment by tmazor** [comment]
I agree with @jjgao  - I think that rather than a tab in patient view, it would be better to come up with a standardized gene panel page that can be linked to (as a pop-up or modal or ...) from all of the many places where we refer to gene panels.

Also, I believe this would be the only place in the UI that we show entrez gene IDs - is there a reason that is necessary here? I would vote to simplify and just show hugo symbols, since that is what is used elsewhere on the site.

**Comment by jjgao** [comment]
Good idea to just show gene symbols. There was some discussion about moving away from entrez gene IDs anyway.

**Comment by pvannierop** [comment]
I appreciate that most users will know the HUGO symbol. However, I personally think relying on HUGO symbols only, is bad practice in light of the unstable/inconsistent reference (name changes over time, etc.) these indicators provide.

**Comment by pvannierop** [comment]
This is the modal mockup.

![image](https://user-images.githubusercontent.com/745885/66109478-082d1100-e5c5-11e9-8e34-3d59ffc19e7c.png)

**Comment by jjgao** [comment]
@pvannierop 

ZenHub is free for public repos on GitHub: https://www.zenhub.com/pricing

About hugo vs entrez, I got your point, but I think it should be a separate decision for exposing the entrez IDs. I don't think we should only expose it here but not anywhere else. Maybe we can table it and further discussion but not expose it for this round?

I also don't like modal dialog, maybe we can have a new page for this?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao what is wrong with the modal dialog? A separate page will be more clunky I think.

**Comment by jjgao** [comment]
A modal dialog will be blocking and cannot be opened separately. But I don't feel strongly about it as long as we do it consistently across the site.

Why a separate page is clunky?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao in a single page app opening a separate page feels a bit 'off' to me.

What is the use case for showing the gene panel information? Imo, the user would want to check on a particular gene quickly and close it again. I do not think someone would go and look at all the genes in the panel. Perhaps the user is looking at the mutations in a patient and is thinking something like: wait, is there no mutation in gene X or is it not sequenced? He opens the gene panel dialog, checks for gene X and closes it. With the search box this is a matter of seconds.

To me that is a use case to be handled by a quick popup not a separate page.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen thanks for the explanation. 

I was thinking of the gene panel page more as an informational page for the user to study the gene list.

@tmazor @schultzn since you have requested this page for a couple of times, how/when would you use it?

**Comment by Sjoerd-van-Hagen** [comment]
@tmazor @schultzn can you give some input on this?

Would you like to have a separate gene panel page? Would you want to go there instead of seeing a quick popup, or would it better to have both?

**Comment by schultzn** [comment]
Sorry for the delay.

I think both would be useful. In addition to a popup, it would be nice to have a centralized page that lists all gene panels used in a given instance of cBioPortal. The table could have the following entries:
 - Name of list
 - any meta data fields we have for the list
 - number of genes
 - number of samples using this gene list
 - number of studies that contain samples with this gene list

Clicking on a gene list name would then take the user to a new page that shows all genes in the list.

Does this make sense?

Niki.

**Comment by Sjoerd-van-Hagen** [comment]
It does make sense.

We will implement the modal popup as we planned, and perhaps improve it a bit.

For the gene panel page, I suggest we make a design. It would not be part of the current project we are running but I can try to float it with the sponsor to see if we can do it in a follow up project.
