### ISSUE TITLE
Documentation for updating the frontend commons

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6675]
We recently had a genome nexus API update but for multiple devs it was unclear how to update the API clients in the frontend commons library. Maybe a few lines in the `README.md` suffice

See: https://github.com/cBioPortal/cbioportal-frontend/pull/2752

**Comment by ao508** [comment]
@inodb Is this still unresolved?

**Comment by onursumer** [comment]
`cbiopotal-frontend-commons` is now a proper npm module, with its own `package.json` (https://github.com/cBioPortal/cbioportal-frontend/tree/master/packages/cbioportal-frontend-commons)

For more details see `Workspaces` section of the readme (https://github.com/cBioPortal/cbioportal-frontend#cbioportal-frontend).
