### ISSUE TITLE
Plots tab: RPPA data missing

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6679]
In [this query](http://bit.ly/2pIuLQG), the RPPA data exists in OncoPrint, but not in Plots tab. It happens to other studies as well.

**Comment by jjgao** [comment]
The rppa data is working in another query: https://www.cbioportal.org/results/plots?session_id=5d9e257ce4b0656ac4cf36e2

**Comment by adamabeshouse** [comment]
im not seeing a problem, theres just no protein alterations for kras. if you change the gene to nras you'll see the plot.

**Comment by jjgao** [comment]
ah, I see. Sorry.
