### ISSUE TITLE
Oncoprint result difference

### ISSUE THREAD

**Issue by AswathyPaul** [cBioPortal/cbioportal#6696]
I had accessed cBioPortal a month ago looking for expression of genes (mRNA Expression z-Scores (RNA Seq V2 RSEM)) in different cancer such as Breast Invasive Carcinoma (TCGA, Provisional), Ovarian Serous Cystadenocarcinoma (TCGA, Provisional) and endometrial. But when was were cross verifying the expression once again today I found the result was different. The change was for breast and ovarian but not for Uterine Corpus Endometrial Carcinoma (TCGA, Provisional). So I doubt whether there was any calculation update for Z score, then why the update was not reflected in every cancer. 

Thank you in advance

**Comment by jjgao** [comment]
@AswathyPaul we have been recalculating all z-scores. We decided to use all samples instead of just the diploid samples as the reference population. We haven't finished updating all studies yet. Please let us know (cbioportal@googlegroups.com) if you have any questions or concerns.
