### ISSUE TITLE
plots - treatment data - samples are not properly colored by copy number alteration

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6697]
http://bit.ly/2AZO7D8

Note here that samples with an amplification called are labeled as not profiled for copy number:
![image](https://user-images.githubusercontent.com/10508276/66657066-3043f200-ec0d-11e9-9d02-3d14debf58ab.png)

The same data when plotted with mRNA instead of treatment correctly colors samples by copy number:
![image](https://user-images.githubusercontent.com/10508276/66657088-39cd5a00-ec0d-11e9-8587-ba70c479a144.png)

**Comment by Sjoerd-van-Hagen** [comment]
@pvannierop can you have a look at this. Interestingly, it only occurs with treatment on the horizontal axis, which is why I did not notice this before.

**Comment by pvannierop** [comment]
@tmazor We have put this issue on our todo-list.
