### ISSUE TITLE
plots - horizontal scrolling is very difficult

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6698]
On other tabs, e.g. OncoPrint, I can just have my mouse anywhere over the plot and scroll horizontally.

On a waterfall plot (which will often be wider than the screen), I have to use a very narrow scrollbar above the plot to scroll. This is less intuitive and much harder to use.

Let's use the same scrolling mechanisms on plots as we have used on OncoPrint and elsewhere.

![image](https://user-images.githubusercontent.com/10508276/66657449-da237e80-ec0d-11e9-9bab-ba8d41cb4d85.png)
http://bit.ly/2AZO7D8

**Comment by jjgao** [comment]
And why the scroll bar is on the top.

cc'ing @alisman as well.

**Comment by pvannierop** [comment]
@tmazor @jjgao This behavior is default to cBioPortal (implementd by @alisman in [PR #1345](https://github.com/cBioPortal/cbioportal-frontend/pull/1345)) and not modified by me.

**Comment by jjgao** [comment]
@pvannierop got it. Thanks. I assign this to @alisman

**Comment by tmazor** [comment]
This is still an issue

**Comment by pieterlukasse** [comment]
I think there should be no scrolling at all, but rather shrink/scale back the plot so that it fits the screen.

**Comment by alisman** [comment]
@pieterlukasse i know for certain there some charts where we cannot compress further without losing data to resolution.   I would wager that would happen for the waterfall under question given that the individual lines seem to be pixel width.

**Comment by pieterlukasse** [comment]
@alisman maybe it is OK to lose some data to resolution in this case? If there is a zoom option, then user could see more details.

**Comment by jjgao** [comment]
I like the idea of zooming out. We have a solution for that in OncoPrint for zooming out using canvas, but that's a much bigger project. Since this only affects a small fraction of plots, I don't think we should prioritize it. Can we just fix the scrolling bar for now?

**Comment by alisman** [comment]
One of the reasons I made the fake scrollbar was that I felt that with native bar at bottom, it was not easy to see that there is more data to the right.  There is no way to get scrollbar at top natively.  @jjgao @tmazor do you guys think this is a problem?

![image](https://user-images.githubusercontent.com/186521/93826171-aed64b80-fc34-11ea-95ab-e99ab65b0c71.png)

**Comment by alisman** [comment]
We could use this trick to get the native bar at top.

http://jsfiddle.net/TBnqw/1/
