### ISSUE TITLE
co-expression is too slow

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6702]
Co-expression tab has become un-usably slow.

This query, with just 283 samples, takes 2 minutes to load: http://bit.ly/31n4tSi

I know we've talked about this and there were some theories about how to improve on this, but we need to get those fixes deployed soon.

**Comment by jjgao** [comment]
duplicated with https://github.com/cBioPortal/cbioportal/issues/6467.

**Comment by jjgao** [comment]
@n1zea144 it'd be great if we can prioritize this one.
