### ISSUE TITLE
ResultsViewPage not showing tabs after update of incorrect gene symbols

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#6706]
I came across this problem with component logic in ResultsViewPage the user enters an incorrect gene symbol via the URL. To recreate this behavior:

# Reproduction
1. Go to cbioportal with this url that contains an invalid gene symbol __RB__: https://www.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=mixed_pipseq_2017&case_set_id=mixed_pipseq_2017_sequenced&clinicallist=NUM_SAMPLES_PER_PATIENT&data_priority=0&gene_list=RB&geneset_list=%20&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=mixed_pipseq_2017_mutations&show_samples=false&tab_index=tab_visualize

This opens a QueryContainer that indicates that the gene name should be corrected.

2.  Correct the gene name to __RB1__

3. Press _Submit Query_.

This re-opens the QueryContainer. __<--- problem__

3. Press 'back' on the browser.

4. Press  Press _Submit Query_.

This opens the oncoprint. __<--alternation__

5. Press 'back' on the browser.

6. Press  Press _Submit Query_.

This opens the QueryContainer.__<--alternation__

...etc.

So, the navigation problem is the reopening of the QueryContainer where the oncoprint tab should have been opened (see __<-- problem__).

# Desired behavior
The user is taken immediately to the oncoprint tab after step 3.

# Analysis of problem
The incorrect display of the QueryContainer appears to stem from the incorrect value of the     `@observable showTabs = true;` in ResultsViewPage parent component. After pressing _Submit Query_ in step 3. the value of this var is false and the oncoprint tab does not show accordingly. The alternation behavior (see __<--alternation__) is somehow caused by repeated calls to the `onToggleQueryFormVisiblity` callback passed to QuerySummary component when going back and forth.

# Solution
The logic that controls the state of the `showTabs` var should be updated to be compatible with incorrect gene names passed in via the url.

**Comment by alisman** [comment]
@dippindots could you write an e2e test for this?

**Comment by dippindots** [comment]
@alisman Sure!
