### ISSUE TITLE
fusion tables

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6709]
The new fusion tables in study view are a great addition, but I suspect that they are currently misleading.

I visited study view for a random sampling of studies, and most have an empty fusion table:
![image](https://user-images.githubusercontent.com/10508276/66836384-3862a100-ef2f-11e9-97b2-48c6a2badaef.png)
https://www.cbioportal.org/study/summary?id=cesc_tcga

I suspect that for many of these studies, it is not that there are truly no fusions, but rather that fusions weren't called. If true, this is very misleading because the table clearly says "XXX profiled samples".

How are these tables being populated? Do they depend on a case list that doesn't exist yet?

In the meantime, perhaps we can hide these tables by default so they are less obvious/misleading to our users? @schultzn @jjgao  thoughts?

**Comment by zhx828** [comment]
Just quick note on this. We don't have a case list for fusion yet. There is an structural variant effort undergoing which is supposed to address the issue. We should find a temporary solution for tcga studies.

**Comment by zhx828** [comment]
@tmazor @schultzn The frontend team discussed the issue during the weekly meeting. We are going to modify one API to record whether the study has fusion. If yes, then the table will show up. I will keep you posted when that's available.

**Comment by khzhu** [comment]
@zhx828 , which existing API to modify. I am not sure if we have one already.

**Comment by zhx828** [comment]
@khzhu  you could modify the `/sample-counts/` under `StudyViewController` to include `numberOfFusionProfiledSamples/numberOfFusionUnprofiledSamples` in the `MolecularProfileSampleCount` model. The api call in the study view to this endpoint is before all charts are rendered, so you can include fusion table only if the `numberOfFusionProfiledSamples` is bigger than 0.

**Comment by khzhu** [comment]
@zhx828 , I see. Sounds like a good plan. I will get the API modified. Thanks!

**Comment by khzhu** [comment]
@zhx828 , the problem now is we can not get Fusion sample Ids from the molecularProfileService, since Fusion is not a type of genetic profiling.

**Comment by jjgao** [comment]
@khzhu I guess we need to query the data to see if there are any fusions, you can do a `limit 1` or `exists` for performance: https://stackoverflow.com/questions/10598935/select-exists-vs-limit-1

**Comment by khzhu** [comment]
Hi @jj, we will need a new web service endpoint then.

**Comment by khzhu** [comment]
@jjgao @zhx828 , what do you think this plan?

- [ ] 1. add a new fusion case list
- [ ] 2. add a new flag **_fusionPresent_** to sample model
- [ ] 3. add a new property **numberOfFusionProfiledSamples** in MolecularProfileSampleCount
- [ ] 4. count number of Fusion Profiled in Samples if sample is marked as **fusionPresent**.

**Comment by tmazor** [comment]
@khzhu @zhx828 @jjgao What's the status of hiding the Fusion table for studies without fusion data?

**Comment by khzhu** [comment]
the fixing will be included in release 3.2.0, @tmazor .
