### ISSUE TITLE
screenshot of plots tab mutations changed on rc

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6710]
This might have been an intentional change:

https://github.com/cBioPortal/cbioportal-frontend/pull/2790/commits/3ab754b466276c353599bd18ebf4d403fcd17b2e?short_path=401ab1c#diff-401ab1c2bf57eec42cd5ea1b2969c4a8

**Comment by jjgao** [comment]
@inodb what's the difference?
