### ISSUE TITLE
Treatments: Select treatments that match search term

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6717]
Can we change the button here to allow the user to select all treatments that match the search term? I thought we had that in the first version, but I might be wrong.

![image](https://user-images.githubusercontent.com/11892704/67100826-685baf80-f18e-11e9-88f2-4be2c5172266.png)

**Comment by pvannierop** [comment]
@schultzn We have put this issue on our to do list.

**Comment by n1zea144** [comment]
This came up in a parallel conversation, I would suggest we only show treatments in this list that are available in the chosen molecular profile.  This will be easier to implement once we have the generic assay code in place.

**Comment by ngocnn1104** [comment]
This issue is fixed by pending PR [#2807](https://github.com/cBioPortal/cbioportal-frontend/pull/2807).

**Comment by Sjoerd-van-Hagen** [comment]
@schultzn PR was merged and is in the new release.
