### ISSUE TITLE
Custom bins should be remembered for user preference

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6721]
The custom bins is currently not saved in the session, but we should.

**Comment by jjgao** [comment]
Should we also have a "default bins" option in the "custom bin" menu so that one can reset it?

**Comment by kalletlak** [comment]
@zhx828 @jjgao how about the log-scale option. should we remember even this?

**Comment by zhx828** [comment]
I think so. Every chart should have a setting object to record all relevant features.
