### ISSUE TITLE
issues with plots tab gene selection memory

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6723]
Go here:  http://bit.ly/2J2E0BY

- Click over to plots tab. The default plot is Copy Number (KRAS) vs mRNA (same gene = KRAS).
- Change copy number gene to EGFR. mRNA changes to "same gene=EGFR". This is fine.
- Change copy number to clinical. mRNA reverts back to KRAS. This is confusing - the gene should remain EGFR.
- Swap axes. Now mRNA is showing EGFR again. This is even more confusing. Swapping axes should not change any data.
- Swap axes again and change clinical back to copy number. Now the copy number gene is KRAS while the mRNA gene is still EGFR. Confusing again - why is my plot showing 2 different genes when I never selected that?

These issues are highlighted by the new plots examples. Go here: http://bit.ly/2BnOxnd
Change the gene on the mRNA-CNA plot to EGFR. Click on "mRNA vs Dx" and you are suddenly looking at KRAS instead of EGFR. This is also more dangerous because I suspect that a user clicking through the examples won't be paying as much attention to the horizontal/vertical axis content and may not even realize the gene has been changed.

**Comment by jjgao** [comment]
@tmazor good catch. @Luke-Sikina could you make sure a selected gene should not change unless a user decides to?
