### ISSUE TITLE
plots tab - remember profile for each data type

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6724]
If I change the profile for a datatype, it would be good for that to be remembered.

For example, go to plots tab here: http://bit.ly/31sZX3i
Change mRNA from RNA-seq to microarray. Click on Mut vs Dx, and then on mRNA vs mut type. The mRNA profile will be changed back to RNA-seq.

It would be much better to have the plots remember the last selected profile for a given data type.

**Comment by alisman** [comment]
@tmazor could you verify that the above PR solves the issues you raised?   U can use this:

https://cbioportal-frontend-pr-2804.herokuapp.com/

**Comment by tmazor** [comment]
Awesome! Looks like this and #6723 are fixed.
