### ISSUE TITLE
Documentation on multiple reference genomes

### ISSUE THREAD

**Issue by a-nayden** [cBioPortal/cbioportal#6729]
Hello,

I'm the author of [this question](https://groups.google.com/forum/#!topic/cbioportal/FCAQDS7H-4Q).

Is it possible to add some documentation on how to reconfigure a cBioPortal instance so both human and mouse data can be uploaded. [This one](https://github.com/cBioPortal/cbioportal/blob/master/docs/Import-reference-genome.md) does not seem to be relevant.

Thank you,
Anastasia

**Comment by khzhu** [comment]
hi @a-nayden ,
to answer your questions:

> if it is possible to reconfigure the existing instance so human and mouse data can be imported to the DB and shown in the UI. 

yes, is possible.

> Could you spot the document (if any) where I can read about the procedure please? I've tried this one https://github.com/cBioPortal/cbioportal/blob/master/docs/Import-reference-genome.md 

you might want to go through the document on [how updating gene and gene alias tables](https://docs.cbioportal.org/3.-cbioportal-maintenance/updating-gene-and-gene_alias-tables) to load genes from other species such as mouse

> but can't see corresponding perl file and suspect that is to upgrage reference_genome table.

those perl scripts can be found at
```
<cbioportal_source_folder>/core/src/main/scripts
```

> Could you also give us some clarifications on how it is supposed to work? 

here is how it works. 
1. assume all reference genomes already loaded into the reference_genome table. if not use importReferenceGenome.pl script to add any new reference genomes to the portal database
2. next, follow [how update gene and gene alias tables](https://docs.cbioportal.org/3.-cbioportal-maintenance/updating-gene-and-gene_alias-tables) to import all genes from the new reference genome to the database if you have not done so.
3. once you complete step 1 & 2, you can now follow this [document](https://docs.cbioportal.org/5.1-data-loading/data-loading/using-the-metaimport-script) to load any datasets of a given reference genome into the portal database. You can also overwrite default genome values using the following options:
```
  -species SPECIES, --species SPECIES
                        species information (default: assumed human)
  -ucsc UCSC_BUILD_NAME, --ucsc_build_name UCSC_BUILD_NAME
                        UCSC reference genome assembly name (default: assumed
                        hg19)
  -ncbi NCBI_BUILD_NUMBER, --ncbi_build_number NCBI_BUILD_NUMBER
                        NCBI reference genome build number (default: assumed
                        37 for UCSC reference genome build hg19)
```

> Should we import a mouse DB seed and is there a safe way to do so as our db is already 2.11.0 and contains some human data we'd like to keep? 

you should not use any seed database, **_that would overwrite what you already had_**. Instead use import scripts to populate the reference genome or reference genome genes.

> Is there some specific configuration for portal.properties file? 

you can use portal.properties file to give default genome values, for instance.
```
# species and genomic information
species=human
ncbi.build=37
ucsc.build=hg19
```

**Comment by jjgao** [comment]
Thanks, @khzhu! Would it be useful to have some of your answers in the documentation?

**Comment by jjgao** [comment]
@khzhu could you please add your text to documentation since more users are asking?

**Comment by khzhu** [comment]
will update the document, thanks, @jjgao!
