### ISSUE TITLE
Refactor oncoprint sort mode in ResultsViewOncoprint.tsx

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6735]
https://github.com/cBioPortal/cbioportal-frontend/pull/2726

In my URLWrapper branch, we need to make oncoprint sort mode driven by URL.   It seems a bit messy how it's handled now so this may require a little refactoring.   

As you probably already understand, the basic flow is 
1. Mutation to a setting is always done via urlWrapper.updateRoute
2. Application state must then derive from urlWrapper.   

It seems like sortConfig should be the @computed source of truth for the app?

**Comment by adamabeshouse** [comment]
https://github.com/alisman/cbioportal-frontend/pull/25
