### ISSUE TITLE
treatment_list url parameter lost when going from Oncoprint to Plots Tab

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#6737]
# Current behavior
Selecting a treatment response profile in oncoprint sets the _treatment_list_ url parameter. Navigation to Plots Tab updates the url to be handled by session service. 
```
https://www.cbioportal.org/results/plots?session_id=5da82b12e4b0656ac4cf4226
```
Because the  the _treatment_list_ parameter is not available for Plots Tab this components gives an error that notify the user has not selected treatments in oncoprint even though the treatments were added in this component (see movie below).

# Desired behavior
By selecting a treatment response profile in oncoprint the _treatment_list_ url parameter is set.  When navigating to Plots Tab the _treatment_list_ parameter persisted and is interpreted by the Plots Tab component and is used to populate the axis menu's for treatment entries.

# Analysis
The update to handle the URL by session service seems incompatible with the way the treatments axis menu is populated.  

![Peek 2019-10-24 10-27](https://user-images.githubusercontent.com/745885/67467416-fa5d2f80-f648-11e9-8ac1-ae66b99248d7.gif)

**Comment by adamabeshouse** [comment]
@alisman lets address this with URLWrapper work

**Comment by alisman** [comment]
@adamabeshouse i agree.    i wonder if it only happens when URL length is near threshold for conversion to session.

**Comment by alisman** [comment]
@pvannierop this is now fixed in the following PR.  You can see here: 

https://cbioportal-f-urlwrapper-uk1qmc.herokuapp.com/results/oncoprint?session_id=5da82b12e4b0656ac4cf4226

All oncoprint sorting options are now read from/written to URL.  

PR is not quite ready for review.  But we're close.   I will assign it to so you can have a look.

**Comment by Sjoerd-van-Hagen** [comment]
@alisman any updates on this?

**Comment by alisman** [comment]
@Sjoerd-van-Hagen there are some complications that have come up with my fix.  i will consider merging @pvannierop fix temporarily

**Comment by Sjoerd-van-Hagen** [comment]
@alisman thanks for the update.

**Comment by pvannierop** [comment]
This issue is fixed with PR https://github.com/cBioPortal/cbioportal-frontend/pull/2726.
