### ISSUE TITLE
Fusion tab crashes on mixed structural variant types

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#6741]
The Fusion tab of the results page appears to operate in two modes ... an enhanced visualization mode which renders exon structure diagrams to show fused transcripts, and a basic mode which renders a pie chart with a textual list of fused gene pairings.

Two levels of detail are permitted for the structural variant file format, one which requires exon numbers and transcript ids for site1 and site2 ... and one which does not. The problem occurs when some records are imported with the enhanced level of detail and some records are imported with the non-enhanced level. The frontend page was tested with two fusion records involving a common site1 gene. One was in the enhanced format and one was not. Either record alone would be successfully rendered, but the fusion page would crash when both events were present in the database for the test study.

We would like the frontend to be able to render a mixture of both record detail levels. cc: @n1zea144

**Comment by jjgao** [comment]
This seems like a frontend issue. Maybe @khzhu can help resolve?

**Comment by khzhu** [comment]
Hi @jj @sheridancbio , I will take a look at next week.

**Comment by khzhu** [comment]
Hi @sheridancbio , which dataset can be used to reproduce the error? msk_impact_2017? thanks!

**Comment by n1zea144** [comment]
Hi @khzhu Yes!  but we haven't checked in the file with the mixed records types.  @sheridancbio is working on the file now, he can give you a copy before it goes into datahub.

**Comment by khzhu** [comment]
hi @jjgao, you mentioned the pie chart on the fusion tab will be removed at some point in the future. Is that still a plan? 

The Pie chart (right side) and the location of exome/transcript structure (left side) are currently rendered from two different react components and use the same structure variants. 
Pie chart only needs fusions and their partner genes while the locations of exome structure need the sites of exomes/transcripts. To prevent crash, we can add some logics in the frontend for not displaying the locations if no exome/transcripts present. 

If we really want to solve the problem, then we should modify the import script to import only those records with the enhanced level of detail.

**Comment by jjgao** [comment]
> hi @jjgao, you mentioned the pie chart on the fusion tab will be removed at some point in the future. Is that still a plan?

Sorry I couldn't recall the exact conversation on this. I think the pie chart can be implemented in a better way, e.g. a bar chart next to the left pannel. But let's not worry about that for the moment.

>  To prevent crash, we can add some logics in the frontend for not displaying the locations if no exome/transcripts present.

Let's add some logic here.

Thanks, @khzhu

**Comment by khzhu** [comment]
thanks, @jjgao! 
will only add some logic for not displaying locations if no exome/transcripts present.

**Comment by n1zea144** [comment]
Hi @khzhu I wanted to share with you the data file from our published msk-2017-impact study that was used to fix bugs in the import process and should be used to complete this issue.  You can find the file on [datahub](https://github.com/cBioPortal/datahub/blob/master/public/msk_impact_2017/data_SV.txt).

**Comment by khzhu** [comment]
perfect, thank you, @n1zea144!

**Comment by n1zea144** [comment]
Hi @khzhu What is the status of this issue?  Do you think we will be able to release the fusion visualization soon using the msk-2017-impact data?

**Comment by khzhu** [comment]
Hi @n1zea144 , I am working on it today and planning to get the code done by Monday.

**Comment by khzhu** [comment]
sorry accidentally close the ticket. reopened.

**Comment by khzhu** [comment]
Hi @jjgao @n1zea144 @sheridancbio ,
I've successfully merged the hyve implementation on the fusion tab into the cbioportal codebase. The fusion visualization using msk-2017-impact data worked well (please see the attached screenshot). 
I will send two PRs (backend and frontend) over with a few minor adjustments for the review on Monday. I also set up a demo on Azure (https://dev.cbioportal.ca) if any of you are interested in taking a look.
We can release the fusion visualization using the msk-2017-impact data some time next week.
Cheers!
<img width="1416" alt="Screen Shot 2019-11-23 at 11 25 16 AM" src="https://user-images.githubusercontent.com/17375786/69484189-497fb700-0de5-11ea-9247-badf269a2101.png">
