### ISSUE TITLE
plots: include driver categorization as option

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6742]
When plotting mutations on plots, we currently have options to group by mutation type or mutated vs. wild type. It would be great to add an option that includes driver status -- so rather than just mutated vs wild type, we could have a grouping with 3 categories:
Mutated (driver)
Mutated (vus)
Wild type

**Comment by jjgao** [comment]
good idea

**Comment by tmazor** [comment]
I think we should still do this

**Comment by jjgao** [comment]
@adamabeshouse please feel free to work on this when you have the bandwidth.
