### ISSUE TITLE
remove mutation mapper dependency on getMutationAligner.json

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6743]
To make react-mutation-mapper more standalone

**Comment by jjgao** [comment]
@onursumer since you are working on https://github.com/cBioPortal/cbioportal/issues/4909, I am wondering if this one can also be taken care of?

**Comment by onursumer** [comment]
@jjgao we can move the logic to frontend and get rid of `getMutationAligner.json`, but we still need to use the backend proxy since mutation aligner endpoint is not https.

**Comment by jjgao** [comment]
hmm... in that case, should we close this issue? @inodb

**Comment by onursumer** [comment]
I think it is still a valid issue, we don't really need `getMutationAligner.json`, we can replace it with the proxy. And, hopefully at some point we can directly connect to an https endpoint.

**Comment by jjgao** [comment]
@onursumer thanks. Please make sure the site is functional in case mutation aligner is not accessible.
