### ISSUE TITLE
property to turn on/off GSVA features

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6749]
Can we have a setting in portal.properties or frontend config to turn on GSVA features (off by default)? Hiding the GSVA component in Query page might be enough.

That way, we can set show_profile_in_analysis_tab to true so that we will be able to use the data for screenshot tests and at the same time they will not show up in the public portal.

**Comment by Sjoerd-van-Hagen** [comment]
As discussed with JJ, we will add a configuration option to hide the GSVA in the query page. This way we can load data for GSVA for testing purposes and have a portal that shows the GSVA, while cbioportal.org does not.

**Comment by jjgao** [comment]
notifying @alisman

**Comment by ngocnn1104** [comment]
Hi @jjgao, just to clarify, do you want to turn on GSVA in test mode and turn it off in production mode?

**Comment by ngocnn1104** [comment]
@Sjoerd-van-Hagen ok, so that option should be `false` by default, `true` in test mode and when deploying to different clients we would manually change the default value to either `true` or `false` based on request?

**Comment by Sjoerd-van-Hagen** [comment]
False by default in both production and test mode, and we can set it for individual front ends.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao this can be closed, right?

**Comment by alisman** [comment]
Hi guys, I'm confused here.  We do not have any "frontend" configuration.  All configuration is piped in from portal.properties and so is specific to a backend instance.  There are some defaults for these which are stored in frontend codebase.  Perhaps we need to a short conversation to figure out what needs to be accomplished.

**Comment by jjgao** [comment]
@alisman could you check this implementation? https://github.com/cBioPortal/cbioportal-frontend/pull/2823/files

**Comment by alisman** [comment]
@jjgao yes this implementation is correct.   it's off by default.  we can "hack" it open for tests (as ngocnn1104 has done with browser.execute.   for any particular instance of cbioportal, we can turn it on by setting in portal.properties.
