### ISSUE TITLE
hide Annotation column if no annotations

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#675]
Hi the Annotation column if no annotations in mutations table, and copy number table in Mutations tab and patient view.

**Comment by zhx828** [comment]
@jjgao This is only doable if the table knows whether OncoKB annotation(or other future annotations which will be added in realtime) is available. Table initialization is before realtime annotation coming in. @onursumer is there a way to hide column after initialization? What about the Show/Hide dropdown feature? How to manually trigger it?

**Comment by zhx828** [comment]
@jjgao I've discussed with @onursumer. There are two options for this.
1. Hide the annotation column at first, if there is any data available, then toggle on the annotation column. 
Pro: dataTable doesn't have any dependency, will be initialized once the server side data returned. 
Con: Toggle on the annotation column will redraw the dataTable. For large table(e.g., above 1000 rows) it will freeze the page for couple seconds
2. Send a request to OncoKB(and all other client-side depend annotation sources) to check whether there are data available, then initialize the table.
Pro: dataTable won't be redrawn
Con: The page will depend on the request, and only will be drawn after getting the responses from resources(e.g., OncoKB)

**Comment by zhx828** [comment]
This has been proved that not possible in current DataTable.js Close for now

**Comment by jjgao** [comment]
Let's keep this issue open for future fixes.
