### ISSUE TITLE
Mutsig and Gistic tooltips

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6752]
The tooltips of MutSig and GISTIC icons are not very informative - see below.

Let's add some description:

- MutSig: [gene] is detected as a significantly mutated gene (q=xxx) in [study] by MutSig.
- GISTIC: [gene] is detected as a significantly copy number altered gene (q=xxx) in [study] by GISTIC.

![image](https://user-images.githubusercontent.com/840895/67704295-336c0b80-f98b-11e9-9925-5009e59eed24.png)

![image](https://user-images.githubusercontent.com/840895/67704310-3c5cdd00-f98b-11e9-945e-c8b47d422937.png)

![image](https://user-images.githubusercontent.com/840895/67704336-48489f00-f98b-11e9-9a99-db67450fab29.png)

https://www.cbioportal.org/patient?studyId=ucec_tcga_pub&caseId=TCGA-BK-A0CC
https://www.cbioportal.org/study/summary?id=ucec_tcga_pub

**Comment by ecerami** [comment]
Is anyone working on this?  I thought I would try to tackle, as it's hopefully not too hard.  let me know.

**Comment by dippindots** [comment]
@ecerami I think no one is working on this currently, please feel free to take it!

**Comment by ecerami** [comment]
ok thanks @dippindots.  will try!

**Comment by dippindots** [comment]
@ecerami Thank you!

**Comment by ecerami** [comment]
@jjgao for GISTIC, I was thinking of adding the following text:

Copy number alteration is statistically significant
as determined by the GISTIC algorithm.

The GISTIC algorithm identifies likely driver copy number
alterations by evaluating the frequency and amplitude of
observed CNA events within the entire study.

**Comment by ecerami** [comment]
Related to this bug, when you hover over G or M, you get a cross hair cursor;  it should be a pointer.

**Comment by ecerami** [comment]
And MutSig text like so:

Mutation is statistically significant, as determined by
the MutSig algorithm.

The MutSig algorithm identifies likely driver mutations
by evaluating the frequency of observed mutations within
the entire study.

**Comment by jjgao** [comment]
Thanks, @ecerami! 

I am wondering if we should mention "driver" here. We use a different definition of driver when we query (basically oncokb drivers).

@cBioPortal/product

**Comment by schultzn** [comment]
How about the following modifications @ecerami @jjgao:

Gene is statistically significantly recurrently mutated in this cohort, as determined by
the MutSig algorithm. Note that not all mutations in this genes are necessarily driver mutations.

The MutSig algorithm identifies likely driver genes
by evaluating the frequency of observed mutations within
the entire study. 

---

Gene is is statistically significantly copy-number altered in this cohort
as determined by the GISTIC algorithm.

The GISTIC algorithm identifies likely driver genes by evaluating the frequency and amplitude of
observed CNA events within the entire study.

**Comment by ecerami** [comment]
@jjgao @schultzn:  I was trying to avoid too many "ly"s, e.g. "statistically significantly recurrently".

So, that's how I settled on the current text:  "Candidate driver gene, as determined by the XXX."

Is there a reason you don't like "candidate driver gene"?  e.g. isn't the purpose of MutSig and GISTIC to identify such candidates?

**Comment by schultzn** [comment]
I agree with the "lys", but it is just more precise. 

But I like "candidate driver gene, as ...". So how abou the following (would avoid "Mutation is statistically significant", which I did not like)? @ecerami 

"Candidate driver gene, as determined by the MutSig algorithm. MutSig identifies likely driver genes by evaluating the frequency of observed mutations within the entire study. Note that not all mutations in this genes are necessarily driver mutations."

"Candidate driver gene, as determined by the GISTIC algorithm. GISTIC identifies likely driver genes by evaluating the frequency and amplitude of observed CNA events within the entire study."

**Comment by tmazor** [comment]
How about these @ecerami @schultzn @jjgao ?

Gene is mutated significantly more often than expected by chance in this cohort, as determined by the MutSig algorithm. The MutSig algorithm identifies candidate driver genes by evaluating the frequency of observed mutations within the entire study.

Note that not all mutations in this gene are necessarily functional/driver events.
-----
Gene is amplified/deleted significantly more often than expected by chance in this cohort, as determined by the GISTIC algorithm. The GISTIC algorithm identifies candidate driver genes by evaluating the frequency and amplitude of observed CNA events within the entire study.

**Comment by ecerami** [comment]
tx @schultzn @jjgao and @tmazor.  Unless I hear objections, I will go with the last suggestion by @tmazor.  thanks again!

**Comment by ecerami** [comment]
actually I liked the merging of @schultzn and @tmazor best.  So ended up with:

Candidate driver gene, as determined by the MutSig algorithm.

MutSig identifies likely driver genes by evaluating the
frequency of observed mutations within the entire study.

Note that not all mutations in this gene are necessarily
functional/driver events.
