### ISSUE TITLE
Group comparison: Need numbers in tooltips on clinical tab

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6756]
For some comparisons, especially when there are a lot of samples plotted in a box plot, it is hard to interpret a difference without seeing averages. Can we add tooltips to each category in the boxplot that would summarize the cohort, including average, min, max, etc.?

![image](https://user-images.githubusercontent.com/11892704/67804455-5f5bbf80-fa65-11e9-84f9-7c10155b5701.png)

**Comment by jjgao** [comment]
and the values of the whiskers (median, 75%, 25%) in the box plots?
