### ISSUE TITLE
Adding mutations, CNA, SV gene charts to study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6759]
https://github.com/cBioPortal/cbioportal/issues/6278 addresses pulling gene-level continuous data into study view. Let's also support categorical data, ie. mutations, discrete CNAs, and SVs. A pie chart will be displayed.

The slices for CNAs:
- Amplification
- Gain
- Diploid
- Shallow deletion
- Deep deletion

The slices for mutations (option 1):
- Mutated (the samples with one or more mutations in the gene)
- Not mutated (the samples without mutations in the gene)
- Not profiled (the samples that were not profiled)

The slices for mutations (option 2):
- mutation types and driver vs vus as defined in oncoprint
- Not mutated (the samples without mutations in the gene)
- Not profiled (the samples that were not profiled)

The slices for mutations (option 3):
- number of mutations in the gene
- Not mutated (the samples without mutations in the gene)
- Not profiled (the samples that were not profiled)

The slices for SVs (option 1):
- Has SVs
- No SVs
- Not profiled

The slices for SVs (option 2):
- SV types
- No SVs
- Not profiled

The slices for SVs (option 3) https://github.com/cBioPortal/cbioportal/issues/9678:
- Different fusion partners (one partner per slice)
- No partner (?)
- No SVs
- Not profiled

@cBioPortal/product

**Comment by Sjoerd-van-Hagen** [comment]
I like how this allows for easy construction of patients that are mutated for one gene and wildtype for another. You can now only do that via the group comparison view.

**Comment by Sjoerd-van-Hagen** [comment]
Regarding the options for the mutations, I think option 3 is not that useful. Option 1 and 2 could be combined in one pie chart but it is probably better to have separate ones. You could also separate option two in two pie charts, one for driver vs vus, the other one for the types. This will not allow you to do certain combinations though (driver of type X and vus of type Y), but you would get fewer slices, making it a bit easier to use maybe.

**Comment by tmazor** [comment]
I actually think option 3 can be useful - it's a very specific question, but I can certainly imagine, for example, looking up a tumor suppressor to see how many samples have two mutations vs one mutation. I don't think there's any way to do this right now on the site.

In terms of options 1 & 2, we could combine those into one user-controlled plot. By default we plot as option 1, and then in the menu for that chart there can be options to also include mutations type and/or driver-vs-vus.

If we're adding driver-vs-vus functionality, then I think we also need to think about bringing over the driver definition controls from results view. Perhaps that global settings menu in results view can also exist in study view?

**Comment by schultzn** [comment]
I agree with Tali on #3 - definitely very useful and we are looking at that kind of data more and more.

And 1 & 2 are both useful but could be combined...

**Comment by jjgao** [comment]
Thanks, all great points! I think all three options can be combined into one chart and the user can switch between them.

**Comment by jjgao** [comment]
@kalletlak It may not be strageforward to do driver-vs-vus for this yet. If that's the case we can leave it out for now. Once Hongxin has the implementation for oncokb integration in the study view page, we can revisit that.

**Comment by tmazor** [comment]
I think we are still planning to do this?

**Comment by jjgao** [comment]
@kalletlak: @Luke-Sikina is interested in working on this. Please give him some pointers. Thanks.

**Comment by kalletlak** [comment]
@jjgao Sure. @Luke-Sikina thanks!

**Comment by tmazor** [comment]
@cBioPortal/product this is the ticket we talked about this morning - let's see if we can work on it soon
