### ISSUE TITLE
db update script not adding gene.CYTOBAND

### ISSUE THREAD

**Issue by alexbaras** [cBioPortal/cbioportal#6763]
it would appear that when we tried to update the db, it did not add the gene.CYTOBAND column

this is using most recent stable release

thanks

**Comment by khzhu** [comment]
@alexbaras , 
which version of the database are you using? 
**_cytoband_** column was dropped from the gene table in schema 2.11.0. Now, we record **_cytoband_** in the reference_genome_gene table for supporting multiple reference genomes, for instance, having hg19 and hg38 datasets co-exist in the same database. 
If your schema is < 2.11.0, please follow this [document](https://docs.cbioportal.org/3.-cbioportal-maintenance/updating-your-cbioportal-installation) to get your database schema updated.

**Comment by alexbaras** [comment]
i just tried to import into a new database right off the github site and got this error

abaras1@atlas:~$ mysql --user=cbio_user --password=********* --host=ares.pathology.jhmi.edu cbioportal_2.7.3 < seed-cbioportal_hg19_v2.7.3.sql 

**ERROR 1054 (42S22) at line 275: Unknown column 'CYTOBAND' in 'field list'**

**Comment by khzhu** [comment]
we do not have 2.11 seed database at the moment.
here are steps you have to do:
1. download 2.7.3 schema from [here](https://raw.githubusercontent.com/cBioPortal/cbioportal/v2.0.0/db-scripts/src/main/resources/cgds.sql) 
2. restore database from seed [database](https://github.com/cBioPortal/datahub/raw/master/seedDB/seed-cbioportal_hg19_v2.7.3.sql.gz)
3. migrate your database schema to the latest using migration script.

**Comment by alexbaras** [comment]
i cannot perform step 2 above with current release, that is the error I showed you previously

**Comment by alexbaras** [comment]
it would appear that the issue was that the schema at <cbioportal>/db-scripts/src/main/resources/cgds.sql is not the same as step #1 above. should they be?

**Comment by khzhu** [comment]
@alexbaras , you can not use the one from your repo, since it is the latest schema of 2.11.0. 
Please download 2.7.3 schema from [here](https://raw.githubusercontent.com/cBioPortal/cbioportal/v2.0.0/db-scripts/src/main/resources/cgds.sql) to complete step 2.
