### ISSUE TITLE
oncoprint gradient shows up as solid block in pdf download

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#6765]
we've encountered this before...

https://github.com/cBioPortal/cbioportal/issues/3119

@fedde-s @rnugraha can you help, what could possibly be the issue now?

**Comment by Sjoerd-van-Hagen** [comment]
Hi @adamabeshouse,

I remember we encountered this before, I think it was Riza who did, as Fedde does not remember. Fedde is also not working on cBioPortal at the moment. Hopefully @rnugraha remembers, but he just started his new job so I am not sure if he can look into this.

My vague recollection is, that when Riza encountered this, he reported it to the maintainers of the library that does the conversion. Apparently, they fixed it.

My suggestion to move forward in case Riza does not respond, is to try and go back to a version of the library that did work, and based on that report this to the maintainers.

**Comment by jjgao** [comment]
@adamabeshouse are we using the frontend sgv2pdf.js for oncoprint?

https://github.com/cBioPortal/cbioportal-frontend/pull/2094

**Comment by adamabeshouse** [comment]
@jjgao yes, it is svg2pdf

**Comment by adamabeshouse** [comment]
@dippindots you're familiar with svg2pdf right? maybe you can take a look?

**Comment by dippindots** [comment]
@adamabeshouse Sure, I can take a look at this.

**Comment by dippindots** [comment]
Hey @adamabeshouse. I noticed that I have encountered this problem before, and fixed that https://github.com/cBioPortal/cbioportal/issues/5886#issuecomment-479151999. I am wondering that if we changed the way to render the gradient in `<rect>` recently?

**Comment by adamabeshouse** [comment]
@dippindots I think the bug has maybe existed ever since then but we forgot about it. so it is just an issue with the svg2pdf library?

**Comment by adamabeshouse** [comment]
@dippindots looks like they merged your PR and released it :) but we never updated the version of svg2pdf in our codebase? i will make a PR now to update

**Comment by dippindots** [comment]
Thanks @adamabeshouse! I see, I will try to update the library, seems they changed something after the version we are using, may take some time to figure out.

**Comment by adamabeshouse** [comment]
yes, I encountered the same issue. looks like importing doesnt work the way it used to with jsdpf-yworks somehow
