### ISSUE TITLE
svg2pdf throws error and fails on certain victory chart

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#6767]
https://www.cbioportal.org/patient/genomicEvolution?caseId=P04&studyId=lgg_ucsf_2014

https://cbioportal-f-pv-mutatio-c012sw.herokuapp.com/patient/genomicEvolution?caseId=P04&studyId=lgg_ucsf_2014

![image](https://user-images.githubusercontent.com/636232/68045728-983ba480-fcb0-11e9-9555-04057e17656d.png)

![image](https://user-images.githubusercontent.com/840895/68132364-91997100-feec-11e9-987e-5380f38ce13e.png)

**Comment by adamabeshouse** [comment]
CC @tmazor

**Comment by jjgao** [comment]
@adamabeshouse it may be helpful to get @dippindots's insight on this?

**Comment by dippindots** [comment]
@adamabeshouse at the first glance I found out that if we comment out this part the download is working: https://github.com/cBioPortal/cbioportal-frontend/pull/2573/files#diff-2cb47553498caf40902d5f04dbb75e5aR632-R650, I am going to take a look what's going on here.

**Comment by adamabeshouse** [comment]
thanks @dippindots. for some reason the github link isnt working, can you say which file/line you're talking about?

**Comment by dippindots** [comment]
@adamabeshouse I found this would work, try to filter the lineData before the map (`this.data.lineData.filter((dataForSingleLine) => dataForSingleLine && dataForSingleLine.length > 1)`) on line `632` in file `VAFLineChart.tsx`. could you test it?

**Comment by adamabeshouse** [comment]
it worked!! thanks @dippindots
