### ISSUE TITLE
Error showing message for non existing page

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6768]
https://www.cbioportal.org/results/network

Expected behavior:
We see the 404 Page Does Not Exist route (routes.tsx)

Actual behavior:
If you go this page, you'll see a blank page and an error message in console.  

![image](https://user-images.githubusercontent.com/186521/68057646-e9599180-fccc-11e9-896e-8c1d558522d7.png)

**Comment by Luke-Sikina** [comment]
From talking to Aaron
Fix actual error
Make better 404 page in frontend (add head and footer)
Legitimate pageloads shouldn't 404

**Comment by alisman** [comment]
@n1zea144 i think that problem is a frontend issue specific to network page (used to exist, now doesn't).   other non-existant pages work fine on rc ```https://rc.cbioportal.org/results/donkey```
so this issue is separate
