### ISSUE TITLE
data availability of all profiles in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6771]
Currently we only have mutation and CNA, but we should also support other profiles. Maybe we can implement this as a table with the following columns?

- Profile name
- \# (number of samples with data)
- Freq (freq of samples with data)

For the data above, we need to develop a new end point to get the data from sample_profile table.

Should we also consider adding non-profile data into this? e.g.
- segment data
- timeline data

What's left:
- [ ] deploy as part of v3.1.11

@cBioPortal/product

**Comment by tmazor** [comment]
@jjgao I like this idea for how to do this! And I think adding those other data types to this would be awesome!

I think we should also consider adding things like segments & timeline data to the Data Sets page too.

**Comment by kalletlak** [comment]
@jjgao we do already have an endpoint to fetch sample counts `/api/sample-counts/fetch`. which currently returns 
```
numberOfMutationProfiledSamples
numberOfMutationUnprofiledSamples
numberOfCNAProfiledSamples
numberOfCNAUnprofiledSamples
numberOfCNSegmentSamples
```

We can update this to return counts for other profiles.

**Comment by jjgao** [comment]
@tmazor I was thinking of adding the table to study view. Sorry it wasn't clear.

**Comment by jjgao** [comment]
@kalletlak great. We can expand that API.

**Comment by kalletlak** [comment]
@jjgao @tmazor I remember some studies having multiple mutation or copy number profiles. What should be the logic when there are more than one profile of same type?

**Comment by jjgao** [comment]
@kalletlak it should be one profile (instead of profile type) per row. Profile name should be used.

**Comment by kalletlak** [comment]
@jjgao ok. What should it be from multi-study query? group them by profile type?

**Comment by jjgao** [comment]
> What should it be from multi-study query? group them by profile type?

Good question. In `Download` tab of study view and `Gene level` tab of Add Chart in Study view, are we grouping by profile ID or name? I think we should do it in the same way here.

**Comment by kalletlak** [comment]
Ok. we grouping by profile name.

**Comment by kalletlak** [comment]
@jjgao looks like there are different profile name for mutation data for some studies. Here are the distinct names currently in the public database
```
Mutations
Somatic mutations
Whole-exome sequencing
Mutations called from Research Pipeline
Mutations (MSK-IMPACT)
Mutation data from MSK-IMPACT
Mutations from whole exome sequencing
Whole exome sequencing
Mutation data from MSK-IMPACT sequencing of 86 patients with HER2- and HER3-mutant cancers
Bladder Cancer, Plasmacytoid Variant (MSKCC, Nat Gen 2016)
```
In case of multi-study it would be shown as separate records. Its the same even with other datatypes

**Comment by jjgao** [comment]
@kalletlak 

1. Maybe we should merge based on profile IDs? @dippindots I remember there was a reason you chose merging by name instead of id in download tab?

2. I think we should do it for all profiles, e.g. one may want to find all samples with methylation data

3. I would propose to remove the checkboxes and pie charts once this is done.

**Comment by dippindots** [comment]
I remember the reason I merging profiles by name instead of id in download tab is: The profile with the same suffix of id can holds different type of data (data may computed based on different criteria), while the profile name described the actual type of data.

**Comment by jjgao** [comment]
> The profile with the same suffix of id can holds different type of data (data may computed based on different criteria)

@dippindots I am wondering if you can find an example... It's probably for expression data.

**Comment by dippindots** [comment]
@jjgao  I was wrong about my last comment, the reason we decided to group by profile name was `different profile name are using across different profiles`. If we can find a solution for this, I think group (merge) profiles by `profile id` is a great idea.

**Comment by jjgao** [comment]
@dippindots thanks. Maybe we can pick the profile name that is used by the majority of the selected studies? If there is a tie, just randomly pick one?

We should probably clean them up in the data...

**Comment by dippindots** [comment]
@jjgao That's a good idea! I also created an issue to log the data difference issue here: https://github.com/cBioPortal/cbioportal/issues/7196

**Comment by kalletlak** [comment]
@jjgao since we are going to have a table, should we remove these selection options
![Screen Shot 2020-02-24 at 11 22 29 AM](https://user-images.githubusercontent.com/12956870/75170417-1573a500-56f8-11ea-9096-0d7ac10304b4.png)

CC: @zhx828 @cBioPortal/product
