### ISSUE TITLE
improve warning text when VUS/germline are excluded

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6777]
I think we need to edit the warning text on Enrichments & Survival & Download when VUS (or germline) are excluded. The current text is:
469 mutations and copy number alterations of unknown significance are excluded from analysis.
It’s just not clear to me what "excluded from analysis" means.

Maybe we can add another sentence that says something like “Samples with alterations of unknown significance are considered unaltered.”

**Comment by tmazor** [comment]
We should still do this

**Comment by adamabeshouse** [comment]
@tmazor nitpick with your suggestion - a sample with a driver as well as a VUS alteration would not be considered unaltered.

**Comment by tmazor** [comment]
Great point @adamabeshouse !

How about this:
469 mutations and copy number alterations of unknown significance (or: germline mutations) do not count as alterations for this analysis.

**Comment by adamabeshouse** [comment]
I like it!
