### ISSUE TITLE
Issue with query

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6819]
Reported by [a user](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/DoWWYn_s-4k/_Z3c2-e4BgAJ)

Querying the genes below in "Ovarian Serous Cystadenocarcinoma (TCGA, PanCancer Atlas)" was not successful.

```
C9ORF24
PRSS8
CDHR3
AQP1
CRYGB
DNMT3L
PIK3R3
CLDN15
ESPN
ALDH1A2
FBXL22
CALB2
UNC45B
SLC7A11
ZIC3
OSGIN1
SLC7A5
EDEM2
ANPEP
FAM83G
CYP11B1
CAMK2B
SLC1A1
STARD5
GADD45B
PDZK1IP1
EZR
ELF3
UPK3B
AVPR1A
KRT8
SC5D
STC2
WWC1
F11R
CA9
AARD
ARHGEF4
CHRNB1
MYBPC2
UNC79
RGS7
MAPKAPK3
EPPIN
AQP5
PROK2
GOT1
GPT2
BRINP2
SLC2A3
SPHK1
LGALS7
ADAMTS4
CYP4F8
SCX
KCTD14
REC8
KRT18
CLDN3
MMD2
KRT7
FBP2
CES1
DEFB119
CLDN11
HDC
IL17RE
MRAP
TMEM184A
KLK3
BMERB1
DYNLRB2
ACAN
CFAP161
GSTA3
GNG13
FCMR
NEFH
CFI
ALAS1
ADORA1
DEFB123
CELA3B
FXYD4
UPK1A
TMEM114
KLK1
DPEP1
AHSG
SLC13A4
KRT23
CYP2F1
MIA
AGT
SLC5A4
CST9
CA12
PTGDS
ATP12A
ABCB1
COX6A2
SPINK8
ADH7
```

**Comment by alisman** [comment]
@jjgao this is the old duplicate huge gene symbols issue.   We need to handle this better in frontend.  I guess we could just run uniq on the genes response to eliminate this problem in frontend?

**Comment by alisman** [comment]
this returns more genes that were submitted

curl 'https://www.cbioportal.org/api/genes/fetch?geneIdType=HUGO_GENE_SYMBOL' -H 'authority: www.cbioportal.org' -H 'accept: application/json' -H 'origin: https://localhost:3000' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36' -H 'content-type: application/json' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-mode: cors' -H 'referer: https://localhost:3000/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=ov_tcga_pan_can_atlas_2018&case_set_id=ov_tcga_pan_can_atlas_2018_cnaseq&data_priority=0&gene_list=C9ORF24%250APRSS8%250ACDHR3%250AAQP1%250ACRYGB%250ADNMT3L%250APIK3R3%250ACLDN15%250AESPN%250AALDH1A2%250AFBXL22%250ACALB2%250AUNC45B%250ASLC7A11%250AZIC3%250AOSGIN1%250ASLC7A5%250AEDEM2%250AANPEP%250AFAM83G%250ACYP11B1%250ACAMK2B%250ASLC1A1%250ASTARD5%250AGADD45B%250APDZK1IP1%250AEZR%250AELF3%250AUPK3B%250AAVPR1A%250AKRT8%250ASC5D%250ASTC2%250AWWC1%250AF11R%250ACA9%250AAARD%250AARHGEF4%250ACHRNB1%250AMYBPC2%250AUNC79%250ARGS7%250AMAPKAPK3%250AEPPIN%250AAQP5%250APROK2%250AGOT1%250AGPT2%250ABRINP2%250ASLC2A3%250ASPHK1%250ALGALS7%250AADAMTS4%250ACYP4F8%250ASCX%250AKCTD14%250AREC8%250AKRT18%250ACLDN3%250AMMD2%250AKRT7%250AFBP2%250ACES1%250ADEFB119%250ACLDN11%250AHDC%250AIL17RE%250AMRAP%250ATMEM184A%250AKLK3%250ABMERB1%250ADYNLRB2%250AACAN%250ACFAP161%250AGSTA3%250AGNG13%250AFCMR%250ANEFH%250ACFI%250AALAS1%250AADORA1%250ADEFB123%250ACELA3B%250AFXYD4%250AUPK1A%250ATMEM114%250AKLK1%250ADPEP1%250AAHSG%250ASLC13A4%250AKRT23%250ACYP2F1%250AMIA%250AAGT%250ASLC5A4%250ACST9%250ACA12%250APTGDS%250AATP12A%250AABCB1%250ACOX6A2%250ASPINK8%250AADH7&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=ov_tcga_pan_can_atlas_2018_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ov_tcga_pan_can_atlas_2018_mutations&tab_index=tab_visualize' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' --data-binary '["C9ORF24","PRSS8","CDHR3","AQP1","CRYGB","DNMT3L","PIK3R3","CLDN15","ESPN","ALDH1A2","FBXL22","CALB2","UNC45B","SLC7A11","ZIC3","OSGIN1","SLC7A5","EDEM2","ANPEP","FAM83G","CYP11B1","CAMK2B","SLC1A1","STARD5","GADD45B","PDZK1IP1","EZR","ELF3","UPK3B","AVPR1A","KRT8","SC5D","STC2","WWC1","F11R","CA9","AARD","ARHGEF4","CHRNB1","MYBPC2","UNC79","RGS7","MAPKAPK3","EPPIN","AQP5","PROK2","GOT1","GPT2","BRINP2","SLC2A3","SPHK1","LGALS7","ADAMTS4","CYP4F8","SCX","KCTD14","REC8","KRT18","CLDN3","MMD2","KRT7","FBP2","CES1","DEFB119","CLDN11","HDC","IL17RE","MRAP","TMEM184A","KLK3","BMERB1","DYNLRB2","ACAN","CFAP161","GSTA3","GNG13","FCMR","NEFH","CFI","ALAS1","ADORA1","DEFB123","CELA3B","FXYD4","UPK1A","TMEM114","KLK1","DPEP1","AHSG","SLC13A4","KRT23","CYP2F1","MIA","AGT","SLC5A4","CST9","CA12","PTGDS","ATP12A","ABCB1","COX6A2","SPINK8","ADH7"]' --compressed

**Comment by alisman** [comment]
@jjgao i guess the problem is that if run uniq on response based on hugo sybmol, we will be omitting particular entrez gene arbitrarily

**Comment by jjgao** [comment]
>  i guess the problem is that if run uniq on response based on hugo sybmol, we will be omitting particular entrez gene arbitrarily

I think that's fine, but another problem is when oql is used a gene symbol may be duplicated, e.g.

```
EGFR
EGFR: MUT
EGFR: AMP
```

**Comment by uurzua** [comment]
thanks for analyzing this issue; just to let you know that I got the same error for a smaller list (derived from the original) in which there are no gene symbol repeats 

http://www.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=ov_tcga_pan_can_atlas_2018&case_set_id=ov_tcga_pan_can_atlas_2018_cnaseq&data_priority=0&gene_list=CLDN3%2520MMD2%2520KRT7%2520FBP2%2520CES1&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=ov_tcga_pan_can_atlas_2018_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ov_tcga_pan_can_atlas_2018_mutations&tab_index=tab_visualize

**Comment by alisman** [comment]
Hi,

Yes the problem is that there are certain hugo symbols that correspond to
multiple entrez entries in our database.  I will come up with a final
decision today on how to proceed and put a fix in.

JJ, lets discuss in a bit.

--Aaron

**Comment by alisman** [comment]
@kalletlak the problem here is that for whatever reason, a single hugo gene symbol sometimes corresponds to multiple entrez ids.  @jj and i decided that for the time being the portal should simple regard these hugo symbols as invalid and not allow submission.  so the validation service needs to be adapted to consider them invalid.

**Comment by alisman** [comment]
@kalletlak since users maybe still be able to reach results page with these genes (via other systems), lets show an error page when we detect the condition.  you can see in store where we have the following code throw new Error(ErrorMessages.InvalidGenes);
lets instead handle this with an <ErrorScreen> in view
