### ISSUE TITLE
Keycloak No Longer Exposes IDPSSODescriptor config

### ISSUE THREAD

**Issue by Luke-Sikina** [cBioPortal/cbioportal#6820]
The documentation for setting up cBioportal with Keycloak read as follows:

> Next, navigate to the Installation tab for the same client.
> Select SAML Metadata IDPSSODescriptor as the Format Option and click the Download button.

This format option is not exposed any more. I found a solution [here](https://stackoverflow.com/questions/33542812/keycloak-idp-saml-2-export-of-xml-metdata-to-an-sp). You can still find the xml at `http://{KEYCLOAK-URL}/auth/realms/{REALM-NAME}/protocol/saml/descriptor`, but I'm not sure if we want to recommend something that keycloak seems to want to hide.

![Screenshot from 2019-11-14 12-34-45](https://user-images.githubusercontent.com/20069833/68881548-4ac12d80-06db-11ea-94b6-0fce0e8fdfe6.png)

**Comment by pieterlukasse** [comment]
@Luke-Sikina this looks like either a bug in keycloak or the wrong screen in keycloak. The list you show contains SPSOO.... which I would not expect to be an export option in case Keycloak is the IDP. It could be an option in case Keycloak is a SP for a central IDP, or if one is trying to register a new SP in Keycloak by importing a file.

**Comment by khzhu** [comment]
which version of Keycloak are you using? PM is using version 4.8 and the **SAML Metadata IDPSSODescriptor** is still available from the dropdown menu (please see attached).
<img width="1435" alt="Screen Shot 2019-11-18 at 5 50 35 PM" src="https://user-images.githubusercontent.com/17375786/69102053-4f654900-0a2f-11ea-9a6f-173da269c123.png">

**Comment by Luke-Sikina** [comment]
@khzhu I talked to Pim about this. The conclusion I've come to is that our documentation silently supports keycloak 4.8 without outright saying that it does. I found this issue on 7.0.1.

I sent an email to keycloak asking them about this. It may be that I'm just doing something wrong. It may also be that they are going to deprecate IDPSSODescriptor. I'll update this ticket once I hear back from them.

**Comment by krnbr** [comment]
hi guys any news/ update on this one?

**Comment by vikas027** [comment]
hey @Luke-Sikina , Did you find a solution for the same? It looks `IDPSSODescriptor` has been removed in this [PR](https://github.com/keycloak/keycloak/pull/5944) but not sure what is the alternative.

**Comment by krnbr** [comment]
@vikas027 , @jjgao & @Luke-Sikina 

this will be the format for the descriptor url for keycloak

http(s)://<your_host_domain>/auth/realms/<your-realm-name>/protocol/saml/descriptor

**Comment by vikas027** [comment]
Thanks, @krnbr . I figured it out yesterday from another resource. Additionally, to make things work in AWS, I had to replace 

```xml
<EntityDescriptor entityID="https://<your_host_domain>/auth/realms/<your-realm-name>">
```
with

```xml
<EntityDescriptor entityID="https://<your_host_domain>/auth/realms/<your-realm-name>"
        xmlns="urn:oasis:names:tc:SAML:2.0:metadata"
        xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

**Comment by inodb** [comment]
still an issue CC @j-hudecek

**Comment by fdamstra** [comment]
This is still an issue in Keycloak v14. The correct file is generated as part of the "Generate Auth Mellon" files, but it would be really nice if we could just display it directly for copy and paste purposes.

**Comment by fdamstra** [comment]
If you're affected, you might try commenting on this issue at keycloak: https://issues.redhat.com/browse/KEYCLOAK-18822
