### ISSUE TITLE
Treatment data validation

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#6826]
The validation of `treatment` data has been removed when migrating to `generic_assay` data. Maybe we should bring back the validation just for the file which `generic_assay_type` is `TREATMENT_RESPONSE`.

CC: @pvannierop @n1zea144 @inodb 

validation should be added:
1. multiple files validations (all files should include the same columns and same entities)
https://github.com/cBioPortal/cbioportal/pull/6818#discussion_r346649928
2. validation tests
https://github.com/cBioPortal/cbioportal/pull/6818#discussion_r346649820

**Comment by n1zea144** [comment]
Yes, we should - as previously mentioned, I think we should avoid putting validation code into the backend codebase (specifically, the core-scripts package) as we want to do away with that.  We should bring back what was in the python validator and keep as much out of java as possible.

**Comment by dippindots** [comment]
per discussion, we don't add validation back for now.
