### ISSUE TITLE
Gene API: Gene with multiple entrez Ids thows error

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#6835]
Example https://www.cbioportal.org/api/genes/MMD2

![Screen Shot 2019-11-18 at 3 29 35 PM](https://user-images.githubusercontent.com/12956870/69091419-3f8e3a80-0a18-11ea-9a70-11bfdeacdc33.png)

**Comment by jjgao** [comment]
Should we return something similar to invalid gene but with a different message?

https://www.cbioportal.org/api/genes/NOT-A-GENE

![image](https://user-images.githubusercontent.com/840895/69195025-aaaf3e00-0af8-11ea-8241-62de141719b6.png)

```json
{
"message": "Gene data error: multiple Entrez gene IDs for MMD2"
}
```

**Comment by kalletlak** [comment]
@jjgao how should we handle them in other gene api's? especially for

1. `/genes`
2. `/genes/fetch`

**Comment by jjgao** [comment]
@kalletlak for let's not return the genes with mutliple entrez gene IDs? ... similar to unknown gene symbols.

`curl -X POST "https://www.cbioportal.org/api/genes/fetch?geneIdType=HUGO_GENE_SYMBOL&projection=SUMMARY" -H "accept: application/json" -H "Content-Type: application/json" -d "[ \"NOT-A-GENE\",\"TP53\"]"`
