### ISSUE TITLE
PRAMEF11 issues

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6850]
User reported issue: https://groups.google.com/forum/#!topic/cbioportal/_cJX8QTfLVg

There are some issues with the PRAMEF11 gene in hnsc_tcga. I also checked luad_tcga_pan_can_atlas_2018 and see similar issues, so I suspect these issues span all/many studies.

Go to this query: https://www.cbioportal.org/results/mutations?session_id=5dd8334fe4b0f7d2de786a01

There are several issues:
1) The mutations tab doesn't list IDs for RefSeq or CCDS.
2) The lollipop plot only shows 4 mutations but there are 14 in the table.
3) Click on the Ensembl link for the gene. Open up the Transcript table and click on the UniProt link - this brings you to the UniProt entry for PRAMEF27, suggesting that the Ensembl transcript is for a different gene.
4) The first two listed mutations are C84S and H82R. Look at the protein sequence in UniProt for both PRAMEF27 (as linked from the Ensembl transcript) or PRAMEF11 (as linked from the UniProt link on the mutations tab) -- neither protein sequence has C84 or H82. What transcript/protein sequence are these mutations called against?

**Comment by ritikakundra** [comment]
@jjgao Is this data related? We don't add CCDS and RefSeq IDs in mAF. The lollipop plot looks weird for this study, there are not domains, etc mentioned

**Comment by jjgao** [comment]
@onursumer could you help look into this?

**Comment by onursumer** [comment]
@jjgao @ritikakundra I think this is related to the way we pick the canonical transcript for this gene in genome nexus.

@inodb do you think this is easy to fix?

**Comment by jjgao** [comment]
moved to https://github.com/genome-nexus/genome-nexus/issues/388

**Comment by jjgao** [comment]
captured in GN.
