### ISSUE TITLE
oncoprint: render both fusion and mutation on the same sample

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#686]
We should be able to render both.

**Comment by adamabeshouse** [comment]
Right now fusions trump other mutations when all mutations are desired to be shown - should they be considered a separate category of alteration? I.e. instead of "is there a fusion, or truncating, or inframe, or missense", "is there a fusion or not; is there a truncating, or inframe, or missense"

**Comment by jjgao** [comment]
Yes, they should be considered separately. Treating Fusion as one type of mutation was a hack. Fusion should be considered differently from mutations, similar to CNA. So fusion and mutations should be able to displayed simultaneously. For multiple mutations, we only need to display the worst effect.

**Comment by adamabeshouse** [comment]
Okay cool, so from now on the oncoprint data will look like { 'cna': 'AMP', 'mut': 'INFRAME', 'fusion': false | true }

**Comment by adamabeshouse** [comment]
How should it be displayed in the tooltip? @jjgao @schultzn

**Comment by jjgao** [comment]
@adamabeshouse: the value of fusion should be the one from the "Amino acid change", e.g. "tmprss-erg fusion." You can display this value in the tooltip.

```
{ 
  'cna': 'AMP',
  'mut': <inframe mutation amino acid change> 
  'mut_type': 'INFRAME', 
  'fusion':<the fusion value> 
}
```

**Comment by adamabeshouse** [comment]
so display <fusion value>,<inframe value>

**Comment by jjgao** [comment]
Just display <fusion value>.

**Comment by jjgao** [comment]
@adamabeshouse what's the status of this?

**Comment by adamabeshouse** [comment]
I was under the impression this would be released with, or soon after, the new oncoprint.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1533
