### ISSUE TITLE
Linking OncoKB annotation to MSI, TMB

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6862]
- [x] add msi_status to the sample header
- [x] add oncokb icon next to it

**Comment by jjgao** [comment]
@zhx828 is this issue about showing OncoKB data for MSI cases? What's the implementation plan? Initially I thought we could link OncoKB to annotate clinical attribute directly on patient view.

**Comment by zhx828** [comment]
@jjgao yeah I misunderstood earlier.

**Comment by jjgao** [comment]
I updated the title and description.
