### ISSUE TITLE
Text Box Instructions Seem Incorrect

### ISSUE THREAD

**Issue by DarioS** [cBioPortal/cbioportal#6865]
I don't see any gene symbols to click anywhere.

![image](https://user-images.githubusercontent.com/631218/69684558-2e76b500-110d-11ea-8131-d40510c88f83.png)

Since there are no gene symbols on the table shown on the Clinical Data tab, what form would the query take then? For example, how to subset to Subtype = HNSC_HPV- ?

**Comment by jjgao** [comment]
@DarioS please check out [our tutorial](https://www.cbioportal.org/tutorials) on how to use the study view page. If you have any additional questions, please contact cbioportal@googlegroups.com.
