### ISSUE TITLE
Change Referrer policy

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#6866]
We're running a private cbioportal instance with potentially confidential mutation data. When opening a patient view page cbioportal sets `Referrer Policy:no-referrer-when-downgrade` which means that the complete referrer (including the sample/patient ID) is included in every HTTPS request to every external service. 

For example GenomeNexus receives this way the sample name and for each mutation the position and nucleotide change. We would like to limit that.

Is it possible to change the referrer policy to `origin-when-cross-origin` or `same-origin`?

**Comment by jjgao** [comment]
@j-hudecek would you please send us a pull request on this?
