### ISSUE TITLE
columns missing from https://www.cbioportal.org/mutation_mapper

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6868]
- hgvsc
- gnomad
- clinvar

Would it be possible to make some constant variable that indicates the same columns for all mutation tables of:

- mutations tab
- patient view
- https://www.cbioportal.org/mutation_mapper

Another solution like change the base mutation mapper class to include all columns when genome nexus is enabled could work as well

**Comment by leexgh** [comment]
@inodb do we need Exon and dbSNP in mutation mapper table?

**Comment by inodb** [comment]
@leexgh yes
