### ISSUE TITLE
adding more studies to the priority list

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6869]
currently:
![image](https://user-images.githubusercontent.com/840895/69740353-3e8b9600-1107-11ea-9f4e-21659f562964.png)

@alisman:
- `PanCancer Studies`
	- MSK IMPACT Clinical Sequencing Cohort
	- metastatic_solid_tumors_mich_2017
	- MMS mixed solid tumors
	- metastatic solid cancers
	- SUMMIT
	- TMB & immunotherapy 
	- tumors with TRK fusions
	- (REMOVE `Pan-Lung cancer` and `mixed_pipseq_2017`)

- Add a new category `Pediatric Cancer Studies` before `Cell lines`
	- pptc_2019
	- mixed_pipseq_2017
	- pediatric_dkfz_2017
	- mbl_pcgp
	- all_phase2_target_2018_pub
	- rt_target_2018_pub
	- wt_target_2018_pub
	- aml_target_2018_pub
	- nbl_target_2018_pub
	- es_dfarber_broad_2014

@ritikakundra @rmadupuri  could you fix the tumor types for these two studies under other?
- Move "Hypodiploid ALL" in "Other" to "Myeloid"
- Move "Recurrent & metastatic head & neck" to "Head & Neck"

**Comment by Sjoerd-van-Hagen** [comment]
I think it is odd that the Pan-Lung Cancer one is under PanCancer, since it is only lung.

What would be the reason to put pediatric on top? Because it is a new category?

Can't we just have:
New (everything that was recently added or had a mayor update)
Popular (everything that is accessed a lot)
Pan cancer
and then the rest split by cancer type / organ.

**Comment by jjgao** [comment]
> I think it is odd that the Pan-Lung Cancer one is under PanCancer, since it is only lung.

Good point. Not sure how it got into the list... I updated the to-do list to exclude it.

> What would be the reason to put pediatric on top? Because it is a new category?

Pediatric studies are not very visible and not easy to find. Creating a list will be useful for pediatric cancer researchers.

> Can't we just have:
New (everything that was recently added or had a mayor update)
Popular (everything that is accessed a lot)
Pan cancer
and then the rest split by cancer type / organ.

"New" and "Popular" is a good idea but we would need to implement some non-trivial process to support that. I don't think we have the bandwidth to handle that currently.

**Comment by jjgao** [comment]
@ritikakundra @rmadupuri could you check if the pediatric list is complete?

**Comment by tmazor** [comment]
I like the idea of highlighting pediatric studies.

In terms of pan-cancer studies, I just took a look at the "Other" section, and there are a bunch of other studies that sound like pan-cancer studies:
- MMS mixed solid tumors
- metastatic solid cancers
- SUMMIT
- TMB & immunotherapy 
- tumors with TRK fusions
Shouldn't we put all of these under the pan-cancer header?

There are also some studies under "Other" that sound like they might belong under a specific cancer type:
- Hypodiploid ALL
- Recurrent & metastatic head & neck

I suspect people rarely browse through the "Other" section, so I think as much as possible we should put studies either under a specific cancer type or highlighted as pan-cancer/pediatric/cell lines.

**Comment by jjgao** [comment]
Good idea! @tmazor 

@alisman this seems like an straightforward one to me. Maybe we can squeeze this one into one of the next couple of sprints?

**Comment by jjgao** [comment]
@tmazor @alisman @ritikakundra to-do list above updated.

**Comment by tmazor** [comment]
@alisman @ritikakundra @jjgao any update on doing this one?

**Comment by jjgao** [comment]
@tmazor I added this to our next sprint.

@ritikakundra I move data curation related work to https://github.com/cBioPortal/cbioportal/issues/6869

**Comment by inodb** [comment]
Updated:

![Screen Shot 2020-05-26 at 9.54.02 AM.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/d36f3282-014c-4f06-bded-02bea3419fc8)

**Comment by ritikakundra** [comment]
@inodb @jjgao These are additional pediatric studies I found:
https://www.cbioportal.org/study/summary?id=es_iocurie_2014
https://www.cbioportal.org/study/summary?id=all_stjude_2015
https://www.cbioportal.org/study/summary?id=all_stjude_2016

Maybe as curators, we can use the term Pediatric as a starting part of the title?

**Comment by inodb** [comment]
@ritikakundra i can add those, what order should they be in? Date of publication (newest at the top)?

**Comment by ritikakundra** [comment]
@inodb What about descending order of publication dates?

**Comment by ritikakundra** [comment]
@inodb yes, that works

**Comment by ritikakundra** [comment]
And we will start using Pediatric Tumor Type as the title for pediatric studies for easy access to the study list.

**Comment by inodb** [comment]
opened a new issue to add those studies: https://github.com/cBioPortal/cbioportal/issues/7543

**Comment by inodb** [comment]
Sounds like a good idea to add Pediatric as the title 👍
