### ISSUE TITLE
x-axis in survival plot shifted in a public TCGA study

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6871]
https://www.cbioportal.org/study/summary?id=stes_tcga_pub

![image](https://user-images.githubusercontent.com/11892704/69881616-965b0600-129b-11ea-88c1-1efa05eae1d0.png)

**Comment by jjgao** [comment]
somehow I still see the same

![image](https://user-images.githubusercontent.com/840895/71696865-2e10b000-2d84-11ea-8544-b1554a66cebc.png)

**Comment by inodb** [comment]
wasn't deployed yet - fixed
