### ISSUE TITLE
Gene panel information icon in patient view is too prominent

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6874]
I am sorry if I missed discussions about this, but I found the info icon on the gene panel a bit too prominent... my eye is drawn to it, although summary information about number of mutations found and FGA are more important. Can we find tone the icon down a little, maybe by simply using a fainter color or no fill color at all?

![image](https://user-images.githubusercontent.com/11892704/69918820-7c105c00-1444-11ea-81c5-87a1778349d4.png)

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen do you think your team can help with this?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao it should be easy enough for you to fix, right?

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen we can take this.

@alisman could you help improve this?

**Comment by alisman** [comment]
![image](https://user-images.githubusercontent.com/186521/69987376-66b33480-150d-11ea-8f92-be582f3fbe6e.png)
@schultzn how does this look (bottom two rows)

**Comment by schultzn** [comment]
Maybe draw a thin outline around P1 / P2?

**Comment by alisman** [comment]
@adamabeshouse, per @schultzn suggestion, try drawing a thing outline in same color as text?

**Comment by adamabeshouse** [comment]
how does it look?
![image](https://user-images.githubusercontent.com/636232/70188021-9bfe8480-16bd-11ea-8a09-06e5ca5677d0.png)

**Comment by Sjoerd-van-Hagen** [comment]
Looks good. Can you add just a bit of space between the panel icon and the percentage before it? Perhaps a slight background color would be nice too.

**Comment by schultzn** [comment]
I agree with Sjoerd!

**Comment by adamabeshouse** [comment]
@Sjoerd-van-Hagen @schultzn @alisman 
![image](https://user-images.githubusercontent.com/636232/70264488-83967480-1766-11ea-8e1d-0bf765a4cd15.png)

thoughts?

**Comment by Sjoerd-van-Hagen** [comment]
Nice.

I think that WGS/WES had a different color. Did you change that as well?

**Comment by adamabeshouse** [comment]
is that in the screenshot? no, I only changed the icon.

**Comment by Sjoerd-van-Hagen** [comment]
I am not sure if it has a different color, and since I do not know of any studies that have mixed WGS and panel data, I also cannot check.

Let's just say it is fine for now. If it bothers Niki at some point we can fix it then :-)

**Comment by adamabeshouse** [comment]
@Sjoerd-van-Hagen oh, I understand what you're asking. no I didn't change the fill, only the fill opacity (which now Im glad I did because I wasnt even aware the fill could be different :D)

**Comment by Sjoerd-van-Hagen** [comment]
In that case, perfect!

**Comment by schultzn** [comment]
Agreed - thank you!
