### ISSUE TITLE
Oncoprint control toolbar improvements

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6880]
To bring more attention to heatmap tracks, we want to add little counter bubbles to the control buttons.  Also, change button text from "Heatmap" to "Add Heatmap Tracks".   

@schultzn just to confirm, the number for heatmap tracks corresponds to # of profiles listed in dropdowns.  

![image](https://user-images.githubusercontent.com/186521/70085940-418ef680-15df-11ea-9743-d5eb82f7342e.png)

**Comment by schultzn** [comment]
Yes, correct.

**Comment by alisman** [comment]
https://cbioportal.slack.com/files/U23R2QVQA/FR8E78469/image.png

@Luke-Sikina , the css for the bubbles is here

**Comment by Luke-Sikina** [comment]
> https://cbioportal.slack.com/files/U23R2QVQA/FR8E78469/image.png
> 
> @Luke-Sikina , the css for the bubbles is here

@alisman That page 404s

**Comment by alisman** [comment]
![image](https://user-images.githubusercontent.com/186521/70176905-47e8a580-16a7-11ea-8b36-8b4e9865627e.png)
@Luke-Sikina
