### ISSUE TITLE
change default behavior of gene panel filter in patient view

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6890]
The new filter to include genes profiled by any or all samples is great.

However, I think the default behavior should be to show all genes. The user can then chose to filter to just the genes profiled in all samples if they want. But currently we essentially hide those genes, and a user could easily not notice that they are filtered out. So I think it's better to show all and let the user actively select the filter.

For this patient, 3 genes are just hidden by default, including a likely loss-of-function mutation in a known tumor suppressor:
![image](https://user-images.githubusercontent.com/10508276/70341074-1b0bce00-1820-11ea-8242-b4063055c461.png)

![image](https://user-images.githubusercontent.com/10508276/70341110-3971c980-1820-11ea-9db0-215bcc2c1d06.png)

https://www.cbioportal.org/patient?studyId=msk_impact_2017&caseId=P-0000377#navCaseIds=msk_impact_2017:P-0000377

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao this can be set in portal properties!

**Comment by Sjoerd-van-Hagen** [comment]
@alisman ^

**Comment by alisman** [comment]
Ok, will look for property

**Comment by alisman** [comment]
# setting controlling the default setting for filtering genes in patient view
skin.patientview.filter_genes_profiled_all_samples=true

**Comment by alisman** [comment]
@Sjoerd-van-Hagen @jjgao @tmazor I am updating this property on public portal right now.  Does everyone agree we should reverse the default for ALL portals though?

**Comment by tmazor** [comment]
yes, i think all portals should default to "show all"  @alisman

**Comment by jjgao** [comment]
Maybe we don't even need this property and always show all genes?

**Comment by Sjoerd-van-Hagen** [comment]
We do need this property, which is why we implemented it.

**Comment by Sjoerd-van-Hagen** [comment]
@alisman I think you may be misreading the property's intention. 'filter genes profiled (in) all samples' means that the genes are shown that are profiled in all samples, so setting it to true should remove all the genes that are not profiled in all samples. Setting true means filtering out genes, setting false means keeping them all. If it works differently, that may be a bug.

I suppose this confusion means we should rename this property.

@pvannierop can you confirm that I am correct?

**Comment by alisman** [comment]
@Sjoerd-van-Hagen @pvannierop @jj i think what happened here is that in the portal.properties.EXAMPLE file, the example was set to true.    We actually use this examples file as a default (overridden by kubernetes configuration).

**Comment by Sjoerd-van-Hagen** [comment]
So it looked like it was set to false but was set to true? Perhaps set it to false in the EXAMPLE file as well?

**Comment by alisman** [comment]
@Sjoerd-van-Hagen yes my PR 6944 sets it to false in example file.

**Comment by alisman** [comment]
I'm wondering whether it makes sense to always leave new properties undefined or commented out in EXAMPLE file.  That way we can control the default behavior with frontend.  The idea is that most of the time these properties should really NOT be managed by individual installers.  When we include them in portal.properties, we lose control.  @inodb ?

**Comment by inodb** [comment]
Yeah commented out makes sense i think for most props that we don't really want people to change unless they know what they're doing.

For reference, although the file is called `EXAMPLE` it really is defaults as well. The order of property assignment is like this for Docker if you don't have your own properties file:

- defaults in portal.properties.EXAMPLE
- defaults in GlobalProperties.java
- defaults in frontend
