### ISSUE TITLE
issue with "not profiled" annotation in patient view

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6891]
It is possible for a gene to have an event called, even though it is not part of the gene panel. I suspect this will most often be the case for fusion partners, but it can also arise for other reasons.

The problem is that if the gene is profiled, the event is not marked as being present in any sample.

![image](https://user-images.githubusercontent.com/10508276/70341489-067c0580-1821-11ea-81ad-24b5982c3f3d.png)
https://www.cbioportal.org/patient?studyId=msk_impact_2017&caseId=P-0000377#navCaseIds=msk_impact_2017:P-0000377

Clearly those two 2 fusions were called in at least one sample, because otherwise they wouldn't be listed. But it is now impossible to know where they were called.

We need to show the sample number anytime an event is called, even if the gene wasn't profiled in that sample. Perhaps the sample number can be slightly transparent, or in some other way indicate that it wasn't profiled?

FWIW, we do this nicely in OncoPrint. If I query just this same patient, I get this:

![image](https://user-images.githubusercontent.com/10508276/70341666-75595e80-1821-11ea-88ff-c6ae0b321ab3.png)
http://bit.ly/2qxm0K4

**Comment by Sjoerd-van-Hagen** [comment]
@tmazor @jjgao this should be fixed when the fusions are not loaded as mutations any more. I assume that they will also be shown separately in the patient view when that happens?

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen yes, this will be fixed in the proper fusion implementation. But I think we should put some code in here to show the sample number when we see mutation/cna in the sample regardless of whether the gene is in the panel.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao I am not necessarily against doing that but I would prefer that we simply prevent incorrect data from entering the system in the first place. Having mutations in a gene that is not profiled should raise an alarm and prompt the data loader to have a look, don't you think?

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen I completely agree that data should be fixed. I think ideally the logic should be implemented in the validator. But I also think that given noisy data, we should try our best to visualize it in the frontend. The current implementation would be confusing (the user would not know which samples carry the mutation) when the data is incomplete like above.

**Comment by onursumer** [comment]
@jjgao do we still want to show sample numbers with regular colors and opacity for `not profiled` genes, or do we prefer something different, like reduced opacity or different color?

**Comment by onursumer** [comment]
@jjgao how about showing the sample icon as is with an additional tooltip text to indicate that the gene is not profiled? (see screenshot below)

![not_profiled_sample_with_tooltip](https://user-images.githubusercontent.com/3604198/71599691-e981dc00-2b19-11ea-9a7b-ee1c506f8077.png)

**Comment by alisman** [comment]
@tmazor if you use 2963 (bookmarklet) you can test Onur's fix for this issue

**Comment by alisman** [comment]
@jjgao @onursumer @tali thinking more about this, i think the question is, does the fact that we have a read for any sample really mean that it is profiled for all samples?  what's more likely/accurate for those other samples: to infer that it is profiled or that it's not?

**Comment by tmazor** [comment]
@alisman I think we should continue to use gene panel data to determine if a gene is profiled or not. As @jjgao said above, the data from sequencing assays can be noisy, and sometimes things will get called in genes that were not on the panel. I think our current implementation is correct.

@onursumer your PR looks good to me!
