### ISSUE TITLE
Show altered vs unaltered group in oncoprint

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6893]
People often ask what the altered vs unaltered group in the survival tab is. Would it help to show a track of altered vs unaltered in oncoprint? Alternatively with the new whitespace padding we could add a title instead of a track?

**Comment by jjgao** [comment]
Good idea. Not sure if adding titles would work since we can sort by clinical data.

**Comment by adamabeshouse** [comment]
unstale
