### ISSUE TITLE
genomic profile selection isn't working

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6894]
User reported: https://groups.google.com/forum/#!topic/cbioportal/Eicgjo91Luk

When submitting a query in a single study, the genomic profile selector works.
When submitting a query in multiple studies, the genomic profile selector is ignored.
When modifying a query (single or multiple studies), the genomic profile selector is ignored.

**Comment by alisman** [comment]
@adamabeshouse after first attempt to fix this, problem was solved for combine queries but not for single study queries.  so you can see the bug on production by making a single study query, then modifying it and trying to change the genomic profile.  In short, you can't change it.  The old one always survives.
