### ISSUE TITLE
Test to see if property is documented

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6905]
Can we add a simple test in bash that

1. Gets all properties here: https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/config_service.jsp
2. Greps all of those in the reference docs here: https://github.com/cBioPortal/cbioportal/blob/master/docs/portal.properties-Reference.md

We'll probably find some that are missing when we introduce those tests. If we don't want to document some of those we should maybe add a section experimental or warning internal use only

**Comment by jjgao** [comment]
Good idea.
