### ISSUE TITLE
Do not show full study description when it's too long

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6911]
From Niki: `it would be nice to just show one line and give the user the option to expand the description…`

**Comment by zhx828** [comment]
We still need to do this.

**Comment by zhx828** [comment]
@cBioPortal/product do we still need this?

**Comment by jjgao** [comment]
@schultzn Do you think we still do it? The MSK IMPACT internal cohort has a really long description but I don't think we should shorten it on the frontend....

**Comment by jjgao** [comment]
Closing this. Please reopen if still relevant.
