### ISSUE TITLE
Some columns cleared in patient tsv download

### ISSUE THREAD

**Issue by Luke-Sikina** [cBioPortal/cbioportal#6915]
# Overview
## Expected
When I download a tsv from the patient view, the data in the tsv should match the data I see in the corresponding columns on the page itself.

## Actual
Annotation, Cytoband, mRNA Expr., and Cohor appear as columns in the TSV, but have no data.

# How to Reproduce
1. Go to [this patient](https://www.cbioportal.org/patient?sampleId=OVSAHO_OVARY&studyId=ccle_broad_2019)
1. Keep the default columns for the CNA TSV (Gene, CNA, Annotation, Cytoband, mRNA, Cohort)
1. Click the download TSV button
1. Observe that the resulting TSV has column headers for Annotation, Cytoband, mRNA Expr., and Cohort
1. Observe that the result TSV does not have data for those columns

**Comment by alisman** [comment]
@adamabeshouse please investigate.  this may be solved by a PR that @Luke-Sikina and @jtquach1 did to remove columns which do not have have download callbacks defined.  But it's also possible that these columns SHOULD have download functions defined.
