### ISSUE TITLE
both /health and /api/health endpoints exist (should be only /api/health)

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6916]
Not sure if this was on purpose, but prolly makes sense to only have one of `/health` and `/api/health`? `/api/health` currently doesn't work on auth portals, only `/health`. I'm open to either, but maybe having only `/api/health` makes more sense? Since all the other `/something` paths are routes to pages? CC: @pvannierop @averyniceday  

See:

https://www.cbioportal.org/health

https://www.cbioportal.org/api/health

**Comment by sheridancbio** [comment]
re-opened for the follow-up effort to drop the "/health" mapping and make sure kubernetes liveness probe uses /api/health

**Comment by inodb** [comment]
For some reason even though https://github.com/cBioPortal/cbioportal/pull/6920 is in v3.1.9 `/api/health` still 401s. You can see with:

```
while true; do kubectl port-forward  svc/cbioportal-backend-genie-private 9090:80; done
```
And opening http://localhost:9090/api/health

For whatever reason http://localhost:9090/health still works fine
