### ISSUE TITLE
missing p/q-values in group comparison mutations tab

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6918]
Why doesn't TP53 have a p/q value? Is it "too" significant? If so, then it should appear in the "Genes with most significant p-value" plot but it currently doesn't.

![image](https://user-images.githubusercontent.com/10508276/70817964-b2cd6700-1da0-11ea-9c1d-c9e222196faa.png)

https://www.cbioportal.org/comparison/mutations?sessionId=5df3c369e4b04836b8ae30bf

**Comment by jjgao** [comment]
@kalletlak could you look into this?

**Comment by tmazor** [comment]
Thanks @kalletlak for fixing the p/q-values in the table. However, if I change the graph on the top to "Genes with the most significant p-value", TP53 still doesn't appear, even though it is the most significant gene.
