### ISSUE TITLE
Error loading Mutations plot in Chrome (Error creating WebGL context.)

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#692]
![capture](https://cloud.githubusercontent.com/assets/12956870/12027490/30df9eea-ad95-11e5-8e14-88676f652e28.PNG)

**Comment by leedonghn4** [comment]
did you include webGl

**Comment by leedonghn4** [comment]
did you include webGL libraries?

**Comment by kalletlak** [comment]
I didn't include any webGL libraries. This problem is in chrome, but is working fine in firefox. Here is my branch https://github.com/kalletlak/cbioportal/tree/tvn-plot

**Comment by leedonghn4** [comment]
sorry! I can not look into your branch. can you specify where did you use
wbnGL?

**Comment by kalletlak** [comment]
I haven't added any libraries. I am just using latest cbioportal master code.

**Comment by leedonghn4** [comment]
Hi, karthik

    ok. I will look into it tomorrow.

sincerely,
Dong Li

**Comment by jjgao** [comment]
@kalletlak could you check if you can use the 3d viewer on the public site?

http://bit.ly/1HrZBrX#mutation_details

**Comment by kalletlak** [comment]
@jjgao its getting loaded in Firefox but not in Chrome(complete mutation plot is not getting loaded)

**Comment by leedonghn4** [comment]
I checked on my cellphone. It also works on chrome.

**Comment by kalletlak** [comment]
I think its because of browser version, I am running it on older chrome version. Checked in updated browser, Its working good. Thanks for the help.

**Comment by leedonghn4** [comment]
no problem!
