### ISSUE TITLE
500 error on sample counts service in study view

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6926]
curl 'https://www.cbioportal.org/api/sample-counts/fetch' -H 'authority: www.cbioportal.org' -H 'accept: application/json' -H 'origin: https://www.cbioportal.org' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36' -H 'content-type: application/json' -H 'sec-fetch-site: same-origin' -H 'sec-fetch-mode: cors' -H 'referer: https://www.cbioportal.org/study/summary?id=coadread_tcga' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'cookie: _ga=GA1.2.1764028159.1557761784; mp_96b84420a1a32e448f73e7b9ffccebdb_mixpanel=%7B%22distinct_id%22%3A%20%2216ab1d6770f3af-0a7842b0ab7e5a-37607603-1aeaa0-16ab1d67710b0f%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Fgithub.com%2FcBioPortal%2Fcbioportal%22%2C%22%24initial_referring_domain%22%3A%20%22github.com%22%7D; mp_a37bac8664a332481726ae49603f9f63_mixpanel=%7B%22distinct_id%22%3A%20%22fc475e52-7243-4961-acd4-23e53d287e76%22%7D; results-tab=null; JSESSIONID=C829C06C961E0CB2309615D5C484297B; _gid=GA1.2.1968383365.1576509665; amplitude_id_fef1e872c952688acd962d30aa545b9ecbioportal.org=eyJkZXZpY2VJZCI6ImY5YWE0MDJkLWZkYmQtNGMwMS05Mzg2LWM1NDk2Y2U3YzA3MlIiLCJ1c2VySWQiOm51bGwsIm9wdE91dCI6ZmFsc2UsInNlc3Npb25JZCI6MTU3NjUxMDc5NTIxMiwibGFzdEV2ZW50VGltZSI6MTU3NjUxMDc5NTIxMiwiZXZlbnRJZCI6MCwiaWRlbnRpZnlJZCI6MSwic2VxdWVuY2VOdW1iZXIiOjF9; _gat=1' --data-binary '{"sampleIdentifiers":[{"sampleId":"TCGA-A6-2674-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-A6-2677-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-A6-2678-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-A6-2683-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3514-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3517-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3519-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3520-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3521-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3522-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3524-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3526-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3527-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3529-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3531-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3532-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3534-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3538-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3542-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3544-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3548-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3549-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3552-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3553-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3555-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3556-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3558-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3560-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3561-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3562-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-A6-2672-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-A6-2676-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3516-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3518-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3525-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3543-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3554-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00A-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00D-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00E-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00F-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00J-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00K-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00L-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00Q-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00R-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00U-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00W-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00Z-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01F-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01G-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01Q-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A004-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00N-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A00O-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A010-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A017-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01D-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01I-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01K-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A024-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A029-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A02F-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A02H-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A02J-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A02W-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3664-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3666-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3667-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3672-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3673-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3678-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3679-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3680-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3681-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3684-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3685-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3688-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3692-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3693-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3695-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3696-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3715-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3812-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3814-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3818-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3819-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3831-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3833-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3837-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3848-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3852-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3854-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3856-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3858-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3860-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3875-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-A6-3807-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-A6-3810-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3530-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3710-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3811-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3821-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3842-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3844-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3845-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3846-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3850-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3851-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3855-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3864-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3866-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3867-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3869-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3870-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3872-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3877-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3930-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3939-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3941-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3947-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3949-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3952-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3955-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3956-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3971-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3972-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3973-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3975-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3976-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3977-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3979-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3982-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3984-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3986-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3989-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3966-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-3994-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AY-4070-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AY-4071-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01P-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01R-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01S-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01T-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01V-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01X-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A01Z-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A022-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A02O-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A02Y-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A03F-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AA-A03J-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3901-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3898-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AF-2692-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A026-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3882-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3894-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3896-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AF-2689-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3909-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A011-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3601-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3593-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3587-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3892-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A016-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3999-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3611-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A01W-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3726-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3598-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3608-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3902-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AF-3400-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A032-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3581-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3600-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-4007-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3890-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A002-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3727-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3887-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-4015-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A025-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3578-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A020-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AF-2691-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A01Y-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3881-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A01L-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3878-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3582-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3580-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3605-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-4008-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3612-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A02N-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-4001-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A00C-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3574-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-4005-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AF-3913-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3584-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A015-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A008-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A02X-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3594-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3883-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3609-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A00H-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A02G-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3602-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3575-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3583-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3893-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A014-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3586-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-A00Y-01","studyId":"coadread_tcga"},{"sampleId":"TCGA-AG-3599-01","studyId":"coadread_tcga"}],"studyIds":["coadread_tcga"]}' --compressed

**Comment by kalletlak** [comment]
@alisman looks like either `sampleIdentifiers` or `studyIds` should be present not both
