### ISSUE TITLE
Making marker file for GISTIC

### ISSUE THREAD

**Issue by beginner984** [cBioPortal/cbioportal#6931]
Hello

Long time I am trying to make a marker file for GISTIC but I failed.

I have called copy number with scatngs and made this segmentation file

https://www.dropbox.com/s/3tas61p4ecglso8/segmentationfile.txt?dl=0

[segmentationfile (1).txt](https://github.com/cBioPortal/cbioportal/files/3979699/segmentationfile.1.txt)

Please can somebody help me to make marker file for this segmentation file?

scatngs has given list of 2 millions SNP used for copy number calling 

I have this file here but I don't know how to use that

https://www.dropbox.com/s/rtf49om1ov31hh3/SNP.txt?dl=0

Please somebody kindly help me in making a marker file for running GISTIC on my segmentation file

Thank you

**Comment by inodb** [comment]
@beginner984 were u able to find a solution? Sorry we missed this question

**Comment by jjgao** [comment]
@beginner984 I am closing this one. Please contact us at cbioportal@googlegroups.com if you have additional questions.
