### ISSUE TITLE
Plots tab configuration (axis) should be driven by URL params

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6932]
As part of refactor of plots tab to handle generic assay data, we want to keep the current state of the plots tab (the axis configuration) in the URL.  This means that any update to the state by the UI occurs by editing the URL.  The view layer reacts to changes in the URL.   As a model, you can see how oncoprint controls edit the URL.  Also, this will be documented on wiki

**Comment by adamabeshouse** [comment]
all of them? it would be this times 2 - our URL is starting to get huge again
![image](https://user-images.githubusercontent.com/636232/74191840-5660b980-4c22-11ea-8747-56c1448b8bd9.png)

**Comment by inodb** [comment]
@alisman Any clue?

**Comment by jjgao** [comment]
As usually not all fields have data, is it possible to trim it to the ones with data for each session?

Also, it is important that we consider this type of states (non-query parameters) optional so that we will be able to load the session even if some fields are missing .

**Comment by adamabeshouse** [comment]
as we start to do this for more and more tabs its going to start to rub against the URL limit. is it time to start moving these to the hash? @alisman
