### ISSUE TITLE
docker documentation -- not clear where to find cgds.sql

### ISSUE THREAD

**Issue by johnyaku** [cBioPortal/cbioportal#6939]
docs/docker/README.md says...

> Download the SQL schema (cgds.sql) and the seed database (seed-cbioportal.sql.gz) from the cBioPortal Datahub, and use the command below to upload both to the server started above.

... but it is not clear where to find cgds.sql. It is not in the datahub repo although I did locate it in cbioportal/db-scripts/src/main/resources

Also not clear if the schemas in this file match the version of cBioPortal in the latest docker image.

**Comment by jjgao** [comment]
Thanks @johnyaku for the pull request to fix it. Any remaining questions?
