### ISSUE TITLE
issues with gene panels in patient view

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6941]
There are several problems in how gene panels are currently utilized in patient view that are leading to mutations and copy number events not being shown.

1) (previously reported in #6890) For patients with multiple samples with different gene panels, we should be showing all events by default, not just the events in genes shared between the gene panels.

2) (previously reported in #6891) For patients with multiple samples with different gene panels, events that are called in samples that are not on a gene panel are listed but it is not shown which samples they were called in.

3) (new in this issue) For patients with a single sample, when an event is called in a gene that is not part of the gene panel, the event is not shown. This is currently best visualized with CDKN2A in IMPACT-468 in GENIE (where there is currently an issue where CDKN2A is not part of the gene panel. This is a separate issue, and is under investigation, so don't worry about this here).

Sample with deep deletion in CDKN2A. Deletion is not listed in patient view:
https://genie.cbioportal.org/patient?studyId=genie_public&caseId=GENIE-MSK-P-0023638

Sample with mutation in CDKN2A. Mutation is not listed in patient view:
https://genie.cbioportal.org/patient?studyId=genie_public&caseId=GENIE-MSK-P-0031513

All of these issues together mean we are hiding events in patient view that should be displayed. In OncoPrint, we deal with these issues by showing the calls and providing information that the gene was not part of the gene panel, which allows a user to interpret the data as they see fit. I think this is the better solution.

**Comment by alisman** [comment]
@tmazor thanks tali.  will get on this one.

**Comment by tmazor** [comment]
thanks @alisman !

**Comment by Sjoerd-van-Hagen** [comment]
For 3, it seems the panel was not loaded correctly.

MSK-IMPACT468
Number of genes: 467

It seems one gene is missing. Could this be CDKN2A?

**Comment by alisman** [comment]
@Sjoerd-van-Hagen you are right.  CDKN2A, entrez=1029, is missing from the panel.  i'll as why

**Comment by ritikakundra** [comment]
We do see it in datahub panels https://media.githubusercontent.com/media/cBioPortal/datahub/master/reference_data/gene_panels/data_gene_panel_myb_impact468.txt

Checking with rob to check on the database import

**Comment by inodb** [comment]
@tmazor it seems all these issues are resolved, can you confirm?

**Comment by alisman** [comment]
@tmazor i think we now have all 3 fixed.  can you confirm #3?

**Comment by inodb** [comment]
i noticed another minor loading issue related to waiting for gene panel to be available. It briefly shows something wasn't profiled and then it gets removed:

![gene_panel_show_briefly](https://user-images.githubusercontent.com/1334004/72382547-7bc3db80-36e7-11ea-9c1b-2f6318454817.gif)

**Comment by alisman** [comment]
@inodb I make another ticket for your last comment https://github.com/cBioPortal/cbioportal/issues/7090
and will close this
