### ISSUE TITLE
making timeline expandable 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6953]
e.g. diagnosis track can be expanded to primary diagnosis and metastatic diagnosis. Treatment track can be expanded to different types (chemo, immuno, etc) and chemo can be expanded to drugs.

... similar to expandable tracks in lollipop plot.

@alisman @Luke-Sikina @inodb

**Comment by jjgao** [comment]
This is still desirable. We will need to come up with a way to define the hierarchy, e.g. `treatment.immunotherapy.pembrolizumab`

**Comment by inodb** [comment]
we should still do this

**Comment by alisman** [comment]
@inodb we actually already have this built in.  it just needed a style tweak.  i'll make a PR
