### ISSUE TITLE
PathwayMapper spacing issues

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#6956]
There’s some weird spacing issues - for example here, there’s a ton of whitespace between “activated oncogenes”, “senescence” and “apoptosis” and the respective arrows. and also the arrow for “apoptosis” is practically invisible (select GBM-2008 pathway https://cbioportal-f-rgtemze-ma-mvzepo.herokuapp.com/results/pathways?session_id=5df7f33ee4b05f1dfb8ae07e)

![pm_spacing_issues](https://user-images.githubusercontent.com/3604198/71491125-e5457e00-27fc-11ea-940a-9a02745626bb.png)

(reported by @tmazor)

**Comment by ugurdogrusoz** [comment]
Now that our nodes do not have to be of a uniform dimension, let's  resize all processes in all samples appropriately (in the .txt sample files)

**Comment by ugurdogrusoz** [comment]
@onursumer @tmazor I think this is fixed now. Please review and close.
