### ISSUE TITLE
PathwayMapper color coding explanation and problems

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#6957]
- [x] 1. What does the color coding mean? Why does RB1 not have an alteration precentage? What types of alterations are included in the alteration percentage? There needs to be a legend or description of all this information. (screenshot from Cell Cycle pathway https://cbioportal-f-rgtemze-ma-mvzepo.herokuapp.com/results/pathways?session_id=5df7f492e4b05f1dfb8ae081)

![pm_color_coding_and_alteration](https://user-images.githubusercontent.com/3604198/71491323-0d81ac80-27fe-11ea-8f5f-ca85b613c8bd.png)

(reported by @tmazor)

RB1 is defined as a *family*, not *gene*. We should add an explanation for these in Help in the toolbar.

"... with the alteration frequencies *of selected genetic profiles* of the chosen study overlaid on a TCGA pathway *using a white to red color scale (the more frequently altered a gene is, the more red it's shown)*."

- [x] 2. Perhaps more importantly, why does a gene with 0.0 alteration percentage is more red than the one with 1.1 alteration percentage?

**Comment by ugurdogrusoz** [comment]
@onursumer @tmazor I think this is fixed now. Please review and close.
http://cbio-pm.herokuapp.com/

**Comment by tmazor** [comment]
Thanks @ugurdogrusoz , most of this issue looks fixed. However I don't see a description/explanation in the site about RB1 being a "family" and not a gene. What is the definition of a family? Which genes are part of the RB1 family?

**Comment by ugurdogrusoz** [comment]
@tmazor The notation is explained in PathwayMapper readme. So, let's add the following to Help after the first paragraph:

Refer to documentation [here](https://github.com/iVis-at-Bilkent/pathway-mapper) for the notation used.

**Comment by tmazor** [comment]
One tiny thing - can the link to documentation please open in a new window by default? @onursumer @ugurdogrusoz

**Comment by ugurdogrusoz** [comment]
OK let' open it in a new tab.

**Comment by tmazor** [comment]
Looks good!
