### ISSUE TITLE
Inset box isn't working correctly

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#6958]
I assume it’s supposed to show the same content, but smaller, and with the blue overlay to show which part is in view. However, it doesn’t show the same content - in this example I can see just one of the genes in the inset box.

https://cbioportal-f-rgtemze-ma-mvzepo.herokuapp.com/results/pathways?session_id=5df7eb2ae4b04836b8ae3482

![pm_broken_inset_box](https://user-images.githubusercontent.com/3604198/71491416-913b9900-27fe-11ea-94f0-6c15b52bb7ab.png)

(reported by @tmazor)

**Comment by ugurdogrusoz** [comment]
This is probably due to [this extension bug](https://github.com/cytoscape/cytoscape.js-navigator/issues/41), happens on small canvas size. Will fix when/if the extension fixes it.
