### ISSUE TITLE
PathwayMapper compound with a title saying undefined

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#6960]
Why does this say “undefined”? To replicate, select TP53 pathway here https://cbioportal-f-rgtemze-ma-mvzepo.herokuapp.com/results/pathways?session_id=5df7eb2ae4b04836b8ae3482

![pm_undefined_compound](https://user-images.githubusercontent.com/3604198/71491579-70c00e80-27ff-11ea-8153-2f4a61cbc73f.png)

(reported by @tmazor)

**Comment by ugurdogrusoz** [comment]
In Network > TCGA > PanCanAtlas > TP53, rename the family appropriately

**Comment by ugurdogrusoz** [comment]
@onursumer @tmazor I think this is fixed now. Please review and close.
http://cbio-pm.herokuapp.com/
