### ISSUE TITLE
enforce java code styling (similar to prettier on frontend)

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6961]
we could e.g. use 

https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html

There's also 

https://github.com/jhipster/prettier-java

The idea would be to run this as part of continuous integration. Ideally on CircleCI, see:

https://github.com/cBioPortal/cbioportal/blob/master/.circleci/config.yml

On the frontend we are running prettier already so we can try to do something similar (search for the prettier rule):

https://github.com/cBioPortal/cbioportal-frontend/blob/master/.circleci/config.yml

Over there we are running it only on the files changed in the PR, but if that's too complicated and running it on all the files is fast enough (e.g. a few minutes) we could also run it on all the files instead.

CC: @sheridancbio @n1zea144

**Comment by rahul799** [comment]
@inodb I will like to work on this issue, please assign this to me.

**Comment by inodb** [comment]
Hi @rahul799 - please go ahead!
