### ISSUE TITLE
Mutations Tab: Download TSV file not working

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6963]
Example:
http://bit.ly/36lBLDD

Copy to clipboard works, but download as TSV does not.

**Comment by alisman** [comment]
@schultzn it seems to work for me.  What occurs for you?  
![image](https://user-images.githubusercontent.com/186521/71674736-0f8dc300-2d4a-11ea-93e0-27b59591b7d4.png)

**Comment by schultzn** [comment]
Hmm.. working now.
