### ISSUE TITLE
Refactor Oncoprint to work with fusion data from structural variant endpoint

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6965]
The data is already being loaded by fusion tab, so we can look that as an example

**Comment by inodb** [comment]
Might be good to have it temporarily support both i.e. (1) fusion data from structural variant endpoint and (2) fusion data coming from the current mutations endpoint. Only pull fusion data from (2), if (1) doesn't exist or is empty. Ideally we should fix the data but this will take a bit
