### ISSUE TITLE
Populate structural variant (SV) case list after importing mutation data

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6966]
Before fully switching to using the structural_variant table for fusions (https://github.com/cBioPortal/cbioportal/issues/6611) we will have an in-between phase where some studies might have proper structural variant data in the new format and some studies have structural variant data in the mutations table. This will be in 3.2.0.

The current issue in the release 3.2.0 branch is the following. As part of the db migration we provide some sql statements to create a structural variant case lists with those cases that have a fusion in the mutation event table: https://github.com/cBioPortal/cbioportal/blob/release-3.2.0/db-scripts/src/main/resources/migration.sql#L797-L831.  However, on reimporting mutation data, the case list does not get filled again. To get around this issue we propose to run something similar right after importing mutation data that recomputes the structural variant case lists if there are fusion events in the mutation table. The same SQL as mentioned before could be used, but instead of running on all studies, run it on a single study (the study that is currently being imported). We already have some step where we compute the mutation count clinical attribute after import, so we could add another step after that were we compute the structural variant case lists:

https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportExtendedMutationData.java#L476-L483

We will have to remove this implementation later once we completely move over to the structural_variant table. Might be good to add some comments in the code what parts can be removed.

**Comment by n1zea144** [comment]
For clarification, the structural variant case list is required to show/hide the SV table on the study summary?

**Comment by inodb** [comment]
@n1zea144 yes 👍 - there might be some easier/alternative ways to handle this than what's proposed in the issue but this is what Kelsey, Rob and me came up with when we were discussing it.

**Comment by khzhu** [comment]
Hi @n1zea144 ,@ino, @rob, @aaron I got the fusion backfilling issue resolved by modifying the GenetidProfileReader.java class to add a few lines which insert a new structural variant profile for Fusions. Since Fusions still need to be inserted into the mutation_event table, ImportFusionData will still use the Mutation Profile as before.
```
+                // add a new genetic profile for fusions
+                GeneticProfile gp = new GeneticProfile(geneticProfile);
+                gp.setGeneticAlterationType(GeneticAlterationType.STRUCTURAL_VARIANT);
+                gp.setStableId(gp.getStableId().replace("mutations","fusion"));
+                DaoGeneticProfile.addGeneticProfile(gp);
+                // return mutation profile since fusions are stored in the mutation_event table
                 geneticProfile.setGeneticProfileId(existingGeneticProfile.getGeneticProfileId());
                 return geneticProfile;
```

**Comment by khzhu** [comment]
as for the case list, the migration script will backfill them. When re-importing fusion data, we should update our document and ask users to supply a cases_fusion.txt file which will be something like below.
```
cancer_study_identifier: breast_msk_2018
stable_id: breast_msk_2018_fusion
case_list_name: Sequenced Tumors
case_list_description: All (Next-Gen) sequenced samples (1918 samples)
case_list_category: all_cases_with_sv_data
case_list_ids: P-0000058-T01-IM3        P-0000104-T02-IM6 ...
```

**Comment by khzhu** [comment]
@n1zea144 @inodb 
> the structural variant case list is required to show/hide the SV table on the study summary?

a structural variant genetic type profile is required for the visibility of the SV/Fusion gene table on the study summary view

**Comment by inodb** [comment]
@khzhu Thanks for clarifying!

Why do we need this check for the study view fusion table?

> a structural variant genetic type profile is required for the visibility of the SV/Fusion gene table on the study summary view

wouldn't it suffice to check whether there is a case list and if so show the table? That avoids the requirement for the genetic type profile

**Comment by khzhu** [comment]
Hi @inodb @dippindots, 
I appreciate Gaofei's hard work. Personally, i do not think it is a good idea to run a huge bulk of sql statements in the java persistent layer. 

Here is my solution to solve the fusion case list backfilling issue by adding the following logic to the SampleServiceImpl class:

- if the Fusion case list is supplied (great), then use it to check if the fusion is profiled or not for that particular sample
- if not then check if the study has fusion data or not, if it does, then use the sequenced case list to mark the sample that has been profiled for fusion, which is the original proposal from @jjgao and the same logic is used by the migration script. 

I will add this to my PR 6968 and check in the code tomorrow for review.
```
if (!structuralVariantSampleIdsMap.isEmpty()) {
    sample.setProfiledForFusions(structuralVariantSampleIdsMap.get(sample.getCancerStudyIdentifier()).contains(sample.getStableId()));
} else if (!molecularProfilesMap.isEmpty() && 
    molecularProfilesMap.get(sample.getCancerStudyIdentifier()).contains(MolecularAlterationType.FUSION)) {
    sample.setProfiledForFusions(sequencedSampleIdsMap.get(sample.getCancerStudyIdentifier())
        .contains(sample.getStableId()));
}
```

**Comment by khzhu** [comment]
that is a a good question, @inodb.
> wouldn't it suffice to check whether there is a case list and if so show the table? That avoids the requirement for the genetic type profile

frontend uses the availability of genetic profiles to control the visibility of the gene summary table.

**Comment by inodb** [comment]
We have decided to change the service layer to return the case lists for structural variants if the study has a structural variant profile but no case list as can be seen here: https://github.com/cBioPortal/cbioportal/pull/6968.

**Comment by dippindots** [comment]
fixed by https://github.com/cBioPortal/cbioportal/pull/6968
