### ISSUE TITLE
Make requested fixes for ASCN frontend PR

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#6967]

**Comment by averyniceday** [comment]
PR here: https://github.com/cBioPortal/cbioportal-frontend/pull/2762

**Comment by jjgao** [comment]
@averyniceday fyi - it would be a good idea to use [closing keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) in the pr so that the issue can be closed automatically when the pr is merged.

**Comment by averyniceday** [comment]
Didn't know about this, thanks @jjgao !

**Comment by averyniceday** [comment]
Waiting for review. Also rebased to the front of `master` again.
