### ISSUE TITLE
New feature: Expand download data button on study view

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6979]
Can we expand the download data button on the study view? Currently it allows users to download the clinical data for the selected patients, but it would be great to add additional items here (in order of priority):
1 - Download mutation data
2 - Copy-number changes (if available)
3 - Fusions  (if available)
4, 5, 6 - ... all other available data

![image](https://user-images.githubusercontent.com/11892704/71767468-9a052c80-2eda-11ea-8472-f59f6ddf3f25.png)

**Comment by jjgao** [comment]
Should we just have one button to download all data on the page (tarball if possible)?

@schultzn for mutation, cna, and fusion, is it for download the sample level data, e.g. MAF?

**Comment by jjgao** [comment]
An related issue: https://github.com/cBioPortal/cbioportal/issues/5550

**Comment by schultzn** [comment]
People may not want all the data, but just a specific subset. So I suggest to at least separate clinical and mutation data.

And yes, this would be to download all genomic data for the subset of patients selected, so for example just the MAF file for the subselection of samples. No gene sub-selection would be taken into account here.

**Comment by jjgao** [comment]
@schultzn sounds good. It may also make sense to allow downloading sample level data in individual charts, e.g. Mutated Genes table.

For mutations, we can use MAF. For fusion, we can use the SV format.

For CNAs, should we use the same format as data_cna.txt (sample vs gene matrix of -2, -1, 0, 1, 2)? Would it make sense to define a more user-friendly format? Should we include -1 and 1?

**Comment by alisman** [comment]
@kalletlak if we do decide we want to generate multiple files batched in a single download (all in client side js), it seems this is possible with use of a library like https://stuk.github.io/jszip/

**Comment by jjgao** [comment]
Maybe we can have an option of `Download all` in addition to individual downloads. Also let's use the cBioPortal staging data format for the download files.

**Comment by jjgao** [comment]
Should we also consider add a limit of samples, otherwise the data can be very big?

**Comment by kalletlak** [comment]
Similar to https://github.com/cBioPortal/cbioportal/issues/7463
