### ISSUE TITLE
show timeline on genomic evolution tab?

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6985]
Love the genomic evolution tab! One minor UX thing: I currently find myself clicking back and forth between summary and genomic evolution to see the timeline. We could always show the timeline on the genomic evolution tab. If that's too overwhelming, maybe some way too show/hide it? (CC: @jjgao @adamabeshouse @tmazor )

**Comment by jjgao** [comment]
Good point. Maybe it's time to implement a simplified timeline - e.g. collapsed into one line. Before we have that, I am ok with show/hide.

**Comment by tmazor** [comment]
Good idea - I think we should still do this
