### ISSUE TITLE
EllipsisTextTooltip doesn't work as expected on Level column of OncoKbSummaryTable

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#6993]
Currently there is a workaround on the higher level component (div) to enable ellipsis, but the tooltip is not working.

**Comment by onursumer** [comment]
related to #6996, might have been fixed already. 

@zhx828 does the text in the Level column always get wrapped now instead of getting truncated?

**Comment by zhx828** [comment]
@onursumer I'm not sure about Level column, but I think they should be wrapped. Even for #6996 I think the alteration column should be wrapped instead of tooltip
