### ISSUE TITLE
The long text should have a tooltip in oncokb treatment table

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#6996]
![Screen Shot 2019-08-05 at 10 39 40 AM](https://user-images.githubusercontent.com/5400599/62472773-7001df80-b76d-11e9-8a77-b16f5f669d87.png)

**Comment by onursumer** [comment]
@zhx828 is this still an issue for OncoKB card?

**Comment by zhx828** [comment]
@onursumer I don't think it still an issue for alteration column. I created a threshold to shorten the text. 
![Screen Shot 2020-04-15 at 10 45 28 AM](https://user-images.githubusercontent.com/5400599/79351112-486f3380-7f06-11ea-9a1c-681943429ae6.png)

And for the cell itself, it's wrapped.
I think we can close this ticket.
