### ISSUE TITLE
Debugging / IDE

### ISSUE THREAD

**Issue by ihorvath64** [cBioPortal/cbioportal#70]
Hi,

Quick question: what do you guys use to debug cBio?
Do you run it in an IDE (Spring Tool Suite / Eclipse)?

Thanks,

  Istvan

**Comment by inodb** [comment]
Hi Istvan,

Different people prefer different tools. It also depends what part of the cBioPortal stack one is working on. For JavaScript I use the Firefox/Chrome debugger, for Java I use Netbeans.

Best,
Ino
