### ISSUE TITLE
Error: Invalid value for <rect> attribute x="Infinity"

### ISSUE THREAD

**Issue by zhanxw** [cBioPortal/cbioportal#7006]
In the sample summary page (attached, I am using the latest Docker image), the cna plot is not shown.
The javascript console shows the error "Error: Invalid value for <rect> attribute x="Infinity"" repeated 52 times. 
I searched Google and found this (https://www.sencha.com/forum/showthread.php?159196-getting-error-as-Error-Invalid-value-for-lt-rect-gt-attribute-y-quot-Infinity-quot-on-chart) may be relevant.
Can you please fix? Thanks. 

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/157832/72481620-b9486780-37c0-11ea-9c26-dea0d2639431.png">

**Comment by zhanxw** [comment]
I noticed that this problem happened in the latest version of cBioportal. It is not a problem for 3.0.1 version. 
The Safari version is v13.0.04. Thanks.

**Comment by jjgao** [comment]
@zhanxw thanks for reporting this to us. Is this your internal dataset? Would you be able to reproduce in the public portal? It would be difficult for us to fix this without reproducing the issue.

**Comment by zhanxw** [comment]
Thanks @jjgao . This issue could be different, as I do not see this error on public portal ( the the issue #7008 points to #2991, and #2991 provides the link https://www.cbioportal.org/patient?studyId=prad_mpcproject_2018&caseId=MPCProject_EDCDTqcM and the link works without problem on my side).

My guess is that when there are lots of CNA mutations (as you can see from the screenshot, almost the whole genome is altered, 99.8%), some graphing parameters passed to raphael.js becomes infinite.

**Comment by jjgao** [comment]
@zhanxw it would be hard for us to figure out the issue without data. I am wondering if you can help debugging on your side and try to find the cause of the issue? (I also accept pull requests from community :))

**Comment by zhanxw** [comment]
Happy to contribute to cbioportal to my best skill. 
Can you point me to the relevant code/file to draw the cna segments?
Thanks.

**Comment by jjgao** [comment]
@zhanxw thanks! @inodb, @alisman could you please give @zhanxw pointers? Thanks.

**Comment by kalletlak** [comment]
@zhanxw what's the cBioPortal version are you using?. Before digging into the code, I would prefer to check if the issue still exists with latest release(v3.1.11 or later)

**Comment by zhanxw** [comment]
@kalletlak I can confirm that 3.1.11 fixed this issue. Thanks!
