### ISSUE TITLE
Study View CNA table is slow

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#701]
When you go to study view, the CNA table takes a long time to load. We did some profiling and a huge part of the delay is caused by the backend. In our 2000 sample test-study about 30 seconds is spent querying. This should be improved.

**Comment by aderidder** [comment]
Running the query for our 10.000 sample study took about 5 minutes. One improvement may be adding an index to sample_cna_event's cna_event_id, which decreased the time to about 10 seconds.

**Comment by aderidder** [comment]
The query also uses a file called cbio_cancer_genes.txt
Is the reason this file is used instead of a database table that it's easier to update and distribute?

**Comment by jjgao** [comment]
cbio_cancer_genes.txt should only be loaded once in static variable when the app starts. We are going to connect to OncoKb for the cancer gene list in the future.

**Comment by pieterlukasse** [comment]
@aderidder : I made a [prototype implementation](https://github.com/thehyve/cbioportal/tree/701_proto) to let the method CnaJSON.processGetCnaRequest work in a similar way as is done in MutationsJSON.java . This speeds up the backend code ~2x and the message that it produces is also ~2x smaller. This leads to a good improvement in the performance of the CNA part as shown in figures below from Fiddler: 

###Test with 2,000 samples:
OLD
![image](https://cloud.githubusercontent.com/assets/2900303/12299789/d7de5724-ba18-11e5-905f-7fc4c6315393.png)
unzipped message size: 10MB

NEW
![image](https://cloud.githubusercontent.com/assets/2900303/12299800/e195557e-ba18-11e5-9e5c-786573ca3ade.png)
unzipped message size : 5MB

###Test with 10,000 samples
OLD (24s)
![image](https://cloud.githubusercontent.com/assets/2900303/12299836/04612a1a-ba19-11e5-8bdf-cf9e28661952.png)
unzipped message size : 53MB

NEW(10s)
![image](https://cloud.githubusercontent.com/assets/2900303/12299843/0a3db12e-ba19-11e5-9455-a37db75edca4.png)
unzipped message size : 26MB

With 10,000 samples the bottleneck is now at the frontend, and my guess is that it is the part that processes the JSON responses. But maybe you should merge your work in https://github.com/thehyve/cbioportal/tree/study_view_performance first?

**Comment by pieterlukasse** [comment]
related to #475

**Comment by aderidder** [comment]
The original CnaJSON processGetCnaRequest returns 12 fields whereas the new version only returns 5 fields. genomic_event_observer depends on some of the missing ones as does determineOverviewCNAs in cna.jsp, so we'd have to fix that first

**Comment by pieterlukasse** [comment]
@zhx828 no, this branch was never continued. So CNA table is still quite slow.
