### ISSUE TITLE
Support other types of survival plots

### ISSUE THREAD

**Issue by rmadupuri** [cBioPortal/cbioportal#7019]
Currently, we only show os and dfs survival plots. It would be useful to support other types. In the long run we would like to support [dynamic survival analysis](https://github.com/cBioPortal/cbioportal/issues/7043). For this round, let's support other survival plot by utilizing clinical data and extending the current implementation.

The current implementation is looking for two pairs of clinical attributes: (OS_STATUS, OS_MONTHS) for overall survival analysis and (DFS_STATUS, DFS_MONTHS) for disease-free survival analysis. An easy extension would be looking for pairs of (_STATUS, _MONTHS) with common prefix and make them a survival plot. 

We have three places to display the survival plots, including Results page, Comparison page, and Study view. In all three place, we display both survival plots if they are available. It may be a good idea to display only one and provide option to switch to different ones (e.g. quick buttons).

Note: There are a couple of studies (eg: tcga pancan) with PFS data. Once this is implemented, we should see three types of plots: os, dfs, and pfs for tcga pancan studies.

**Comment by jjgao** [comment]
Just to add an example, in [tcga breast pancan](https://www.cbioportal.org/study/summary?id=brca_tcga_pan_can_atlas_2018), both dfs and pfs data exist but only dfs survival is supported.

![image](https://user-images.githubusercontent.com/840895/73075664-6f2f4800-3e8a-11ea-9323-3093099daa80.png)

@cBioPortal/product

**Comment by jjgao** [comment]
I have updated the description above.

**Comment by leexgh** [comment]
it’s feasible to do in a generic way (Looking for pairs of (_STATUS, _MONTHS) with common prefix), but we still need to define some constants, like the types of survival plots we have, plot title, xy axis labels text and value to indicate positive or negative, basically we need to pre-define all text-related things

**Comment by schultzn** [comment]
Good point - any way we can add all these labels into the description of the _STATUS entry, by using a pre-defined format?

I am not sure what you mean by negative values? The time intervals should be >=0.

**Comment by leexgh** [comment]
@schultzn by negative I mean values like `DECEASED` `Recurred` or `CENSORED`.

We probably don't need to add these labels into the description of the _STATUS entry, @jjgao suggested using _STATUS attribute name on plot title(e.g. for overall survival plot, the name is `Overall Survival Status`), and we could do same on all other places, we only need to define one constant to indicate what value for this survival plot is considered as "negative"(e.g. `DECEASED` in Overall Survival plot)

**Comment by leexgh** [comment]
@jjgao could you confirm the types of survival plots we have?

- OS([tcga breast pancan](https://www.cbioportal.org/study/summary?id=brca_tcga_pan_can_atlas_2018))
- DFS([tcga breast pancan](https://www.cbioportal.org/study/summary?id=brca_tcga_pan_can_atlas_2018))
- DFS([tcga breast pancan](https://www.cbioportal.org/study/summary?id=brca_tcga_pan_can_atlas_2018))
- DSF([tcga breast pancan](https://www.cbioportal.org/study/summary?id=brca_tcga_pan_can_atlas_2018))
- EFS([cscc_hgsc_bcm_2014](https://www.cbioportal.org/study/summary?id=cscc_hgsc_bcm_2014))

some attributes i'm not sure about:
- PF_MONTHS and PF_STATUS([nbl_amc_2012](https://www.cbioportal.org/study/summary?id=nbl_amc_2012))
- PLATINUM_OS_MONTHS and PLATINUM_OS_STATUS([egc_msk_2017](https://www.cbioportal.org/study/summary?id=egc_msk_2017))
- PLATINUM_PFS_MONTHS and PLATINUM_PFS_STATUS([egc_msk_2017](https://www.cbioportal.org/study/summary?id=egc_msk_2017))

**Comment by leexgh** [comment]
![image](https://user-images.githubusercontent.com/16869603/76018129-bc70f180-5eed-11ea-8cbf-af5ef44dbe3a.png)

**Comment by leexgh** [comment]
comments from @schultzn 
A couple of thoughts:

1. For AACR Project GENIE, we can expect dozens of different outcome measures for each study, so having them all show up in the current format might be tricky. Maybe we can show them in a pull down menu once there are >= 10 outcome measures? These could be prioritized by the outcome measures for which more data are available (as we start showing outcome for specific therapies. the data will get sparse and there may be only a few patients with outcome information), similar to what we are already doing in other places for the availability of clinical attributes (OncoPrint, study view).
2. The description of each outcome measure could be shown in a separate line in black (not bold) on a new line right under the header).
3. The survival plots on the study view are a little too small…  They would work if they had smaller (or no) axis labels. And can we add an option to make them larger (to the size they used to be)?

**Comment by jjgao** [comment]
Good idea to discuss here.

@leexgh based on comments above, can we do the followings?

- [ ] add the info icon to the km plots in study view page
- [ ] The description of each outcome measure could be shown in a separate line in black (not bold) on a new line right under the header)
- [ ] remove axis labels

Supporting many plots is captured [here](https://github.com/cBioPortal/cbioportal/issues/7292). Let's do it in a separate pr.

Resizing charts is captured [here](https://github.com/cBioPortal/cbioportal/issues/7293)
