### ISSUE TITLE
error downloading fusion data on msk_impact_2017

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7020]
My guess is the download tab does not work for old style fusion data? Maybe disable for now and only show the download for new style structural variant format?

To reproduce:

- query alk and sos1 in msk_impact_2017:
- click download tab & try to download fusions data

https://www.cbioportal.org/results/download?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=msk_impact_2017&case_set_id=msk_impact_2017_cnaseq&data_priority=0&gene_list=ALK%2520SOS1&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&profileFilter=0&tab_index=tab_visualize

(Note: saw this show up in screenshot test, see https://circleci.com/gh/cBioPortal/cbioportal-frontend/59775#tests/containers/0)

EDIT: maybe we can disable download of Fusion data completely for now? Let's discuss if there's no easy frontend or backend fix to solve this

**Comment by dippindots** [comment]
@inodb, are we fetching the `fusion` data from `Structural Variant` endpoint now? I think maybe it is because we still get data from the `Molecular Data` endpoint.

**Comment by kalletlak** [comment]
@inodb @dippindots just an update. This issue looks similar to https://github.com/cBioPortal/cbioportal/issues/7024. I have a pr to fix it https://github.com/cBioPortal/cbioportal-frontend/pull/3000. It just fixes expression and copy-number data but not other fusion and structural variant data

@dippindots `molecular-data` api doesn't support `Fusion` and `Structural Variant` data.

**Comment by dippindots** [comment]
@kalletlak Thanks for the update and fix!

**Comment by dippindots** [comment]
@inodb could you confirm whether we can close this issue?

**Comment by inodb** [comment]
@dippindots i guess it works, but this solution is slightly confusing because there is no fusion data (everything is NA). All the fusions are in the mutations file for this example. It might be easier to fix this once we have actually migrated all the data from mutation fusion -> new style fusions
