### ISSUE TITLE
Error querying /api/molecular-data/fetch api

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#7024]
User reported issue: https://groups.google.com/forum/#!topic/cbioportal/FHeYv1wGvnU

![Screen Shot 2020-01-21 at 10 10 05 AM](https://user-images.githubusercontent.com/12956870/72816489-37c85d80-3c36-11ea-9440-437a883e2106.png)

**Comment by alisman** [comment]
@kalletlak how did you verify that this fixes problem?

**Comment by kalletlak** [comment]
Example https://www.cbioportal.org/results/download?Action=Submit&cancer_study_list=coadread_tcga_pan_can_atlas_2018&case_set_id=coadread_tcga_pan_can_atlas_2018_all&gene_list=APC%0ATP53&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pan_can_atlas_2018_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pan_can_atlas_2018_mutations&tab_index=tab_visualize

When you try to download expression data files. It throws the above error.

This should be fixed in my pr. Example https://deploy-preview-3000--cbioportalfrontend.netlify.com/results/download?Action=Submit&cancer_study_list=coadread_tcga_pan_can_atlas_2018&case_set_id=coadread_tcga_pan_can_atlas_2018_all&gene_list=APC%0ATP53&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pan_can_atlas_2018_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pan_can_atlas_2018_mutations&tab_index=tab_visualize
