### ISSUE TITLE
Add a descriptive version page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7025]
Currently when you click on the version in the footer you see the output of the api version endpoint.

It would be nice if we had a separate page on the frontend that describes the version in more detail, using information from that endpoint. E.g. the address could be www.cbioportal.org/version, which would show some page like this:

# cBioPortal Version
cBioPortal consist of many software components all with their own version. See the [architecture docs](https://docs.cbioportal.org/2.1-deployment/architecture-overview) for more information. There are also regular updates to the data, see Data Version Section below.

## Software Version

| Component | Commit | GitHub URL |
| --- | --- | --- |
| frontend | 123213 | link |
| backend | 123213 | link |
| session-service | aef23 | link |

## Data Version

Perhaps in this section we could add some update information about the studies? On www.cbiooprtal.org we could also point to raw data files on datahub. 

## External Services
cBioPortal calls various external services:

| Component | Commit | GitHub URL |
| --- | --- | --- |
| OncoKB | 213ff | link |
| Genome Nexus | ase3 | link |

**Comment by neelesh17** [comment]
I am interested in working on this issue.

**Comment by inodb** [comment]
Hi @neelesh17 - thanks so much for your interest! Please go ahead! This is in the frontend repo so you might want to look at how to run it: https://github.com/cBioPortal/cbioportal-frontend. Let us know if you have any questions!

**Comment by jimil749** [comment]
Is it fine if I look into this issue?

**Comment by inodb** [comment]
Hello @jimil749 👋! Welcome! It's perfectly fine to look at this issue as well. These "first label" issues are mainly to get familiarity with the project so it's fine if multiple people try to solve them. The main goal is for new contributors to get familiar with the process of how to run the development environment and submit a pull request. Solving the issue is second. It is not a big deal if someone else ends up solving it first. We definitely appreciate you contributing your time!

Just wanted to let you know as well @neelesh17 👆

Note that if you'd like you can work together as well. If you have other questions about the issue you can ask them here or on https://slack.cbioportal.org such that you're both aware. It also helps to submit e.g. documentation update PRs if you notice errors in the documentation while you are working on this issue. Thanks!
