### ISSUE TITLE
Data is entered as integers but graph displays x-axis in decimals

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#7038]
Data attribute for a field was all integers but the summary page graph represents x-axis in decimals:
<img width="464" alt="Screen Shot 2020-01-23 at 12 38 52 AM" src="https://user-images.githubusercontent.com/12007862/73008114-dc63be80-3e33-11ea-910f-99abed70db3f.png">

**Comment by jjgao** [comment]
@onursumer @kalletlak I am wondering if it's possible to improve the binning logic?
