### ISSUE TITLE
Proxied oncokb endpoint returns "invalid chunked" error (only on mskcc portal)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7039]
https://cbioportal.mskcc.org/proxy/oncokb/utils/cancerGeneList

![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/80150224-9385-4d57-bc01-e234448dfe38)

TODO:

- [x] Verify if this issue is on only on MSKCC portal. Try e.g. genie portal or private portal. Can also try to connect directly to the port

**Comment by alisman** [comment]
@onursumer see if you can figure this out on

**Comment by onursumer** [comment]
The issue is most likely related to Apache configuration. Public portals are running on nginx servers whereas private portals are behind an Apache server.

This might be helpful: https://www.apachelounge.com/viewtopic.php?t=8320

**Comment by inodb** [comment]
@alisman @onursumer Has this been solved now? I saw some DM on slack

**Comment by onursumer** [comment]
@inodb we have temporarily updated all private portals to point to the public portal OncoKB proxy.

**Comment by alisman** [comment]
@inodb we have temporarily solve problem by using public portal's proxy for all portals (with token configured).  As we have not yet publicized token, this means only internal portals.  So, we are now using latest oncokb api for all our portals.   We still need to solve the problem with proxy for other portal installers. @n1zea144 has said his team will look at this.
