### ISSUE TITLE
Study View File Attachments

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7045]

**Comment by pieterlukasse** [comment]
@jjgao you could use the feature implemented by The Hyve for study meta data. It is flexible and allows for an unlimited number of attributes. 
- https://github.com/cBioPortal/cbioportal/pull/4563
- https://github.com/cBioPortal/cbioportal-frontend/pull/1709

**Comment by jjgao** [comment]
@pieterlukasse good point - forgot about that. Thanks!

@alisman @adamabeshouse let's keep this in mind when design the sample/patient file viewer - hopefully the same component can be used here.
