### ISSUE TITLE
GENIE public portal only show MUT vs CNA chart by default

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7046]
We (@tmazor and I) noticed that only MUT vs CNA chart was shown by default for the [genie study](https://genie.cbioportal.org/study/summary?id=genie_public). Reset charts will get charts back.

@kalletlak any thoughts on this?

cc'ing @n1zea144 @tmazor

**Comment by kalletlak** [comment]
@jjgao this is because of the recent study-view filter cleanup where all the chart ids are updated.

**Comment by jjgao** [comment]
@inodb can help remove old user settings in sessions service.

**Comment by inodb** [comment]
@jjgao Just ran @karthik's command to drop all settings: `db.settings.drop();`. That should fix this issue

**Comment by kalletlak** [comment]
Still need to be fixed for other portal
