### ISSUE TITLE
LazyMobxTable unexpected behaviour after re-render

### ISSUE THREAD

**Issue by Rgtemze** [cBioPortal/cbioportal#7071]
This problem is detected during the examination of PathwayMapper integrated into cBioPortal. The problem is reported in 4th and 5th bullet point of the following issue https://github.com/cBioPortal/cbioportal/issues/6959. 

When the selected pathway is changed [by clicking the radio button](https://github.com/Rgtemze/cbioportal-frontend/blob/816024fcf69b46b0cf54a3ff202315b498ae7d5b/src/pages/resultsView/pathwayMapper/PathwayMapperTable.tsx#L67), the table is rendered again due to this [line](https://github.com/Rgtemze/cbioportal-frontend/blob/816024fcf69b46b0cf54a3ff202315b498ae7d5b/src/pages/resultsView/pathwayMapper/PathwayMapperTable.tsx#L66) which marks the radio button of current pathway as checked. However, after re-rendering, table does not remember if the "Show More" is clicked or which page it has left off and it resets back to initial setting. Selected pathway is sent from PathwayMapper as a property. The table is rendered [there](https://github.com/iVis-at-Bilkent/pathway-mapper/blob/47f9e3e227f19338e46e003931dc9006645ed8bc/src/ui/Ranking.tsx#L79).

Image of table with radio buttons:
![image](https://user-images.githubusercontent.com/8372277/73346559-1ea75880-4297-11ea-8205-890bd296ac7e.png)

**Comment by onursumer** [comment]
The fix is included in cBioPortal/cbioportal-frontend/pull/3037
