### ISSUE TITLE
Optimization of StudyViewController & MutationServiceImpl

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#7072]
GOAL: try to recover the performance of study view page when we first enabled Ehcache ... page renders in seconds.

As part of the effort to improve GENIE study view performance, we will optimize code recently introduced behind the /mutated-genes/fetch endpoint.

In particular, the sorting/iteration code within [StudyViewController.fetchMutatedGenes](https://github.com/cBioPortal/cbioportal/blob/master/web/src/main/java/org/cbioportal/web/StudyViewController.java#L255)

Note, this also affects
[StudyViewController.fetchFusion](https://github.com/cBioPortal/cbioportal/blob/master/web/src/main/java/org/cbioportal/web/StudyViewController.java#L292)
[StudyViewController.fetchCNAGenes](https://github.com/cBioPortal/cbioportal/blob/master/web/src/main/java/org/cbioportal/web/StudyViewController.java#L329)

and additional logic doing data manipulation within [MutationServiceImpl.getSampleCountInMultipleMolecularProfiles](https://github.com/cBioPortal/cbioportal/blob/master/service/src/main/java/org/cbioportal/service/impl/MutationServiceImpl.java#L111)

**Comment by sheridancbio** [comment]
Profiling by Avery identified the service layer as the biggest bottleneck. We started to focus there.
There is a call to utility function ProfiledCasesCounter.calculate() which consumes the largest time.
In calculate(), the largest time use is a loop near the end:
for all genes:
- look up the list of gene panels which it is a member of
- aggregate lists of cases which were profiled on those panels
- however, some cases get included even though they are not on any panel (somehow)

aggregating the list of cases involves iterating through a large list of structures which connect ids to a boolean flag (profiled or not). So counting the number of samples which were profiled for a gene under a gene panel involves order(n) string operations and set insert operations. This is expensive when the inner loop iterates over hundreds of thousands of cases.

**Comment by sheridancbio** [comment]
It was recognized at scrum today that although the outer loop iterates through tens of thousands of genes, only 680 genes are present in the output. This may be low hanging fruit for optimization.

**Comment by sheridancbio** [comment]
Another area which needs to be optimized is an earlier function call inside calculate() ... a call to GenePanelService.fetchGenePanelDataInMultipleMolecularProfiles(profiles, samples) was observed to take 10-20 seconds (compared to 100-200 seconds for the profiled case list nested loop mentioned above).

Still, a 10-20 second processing time is not really acceptable on a function call triggered by a user click on a clinical attribute value in the pie charts.
