### ISSUE TITLE
Front-End README needs details on yvm

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#7077]
The current Front-end README file mentions the use of nvm (node version manager), but does not mention the need for yvm (yarn version manager).  According to @Luke-Sikina, the following instructions are first needed to get things running:

```
yvm use 1.21.1
nvm use 8.12.0
```

then:

```
export BRANCH_ENV=master
yarn install --frozen-lockfile
yarn run buildDLL:dev
yarn run start
```

If @alisman agrees, I can try to update the docs.

**Comment by Luke-Sikina** [comment]
Hey Ethan, just saw this. I made a PR for this already and it looks like it got merged: https://github.com/cBioPortal/cbioportal-frontend/pull/3018
