### ISSUE TITLE
Can't find survival data 

### ISSUE THREAD

**Issue by suekn** [cBioPortal/cbioportal#7081]
Hello, I am looking at the [TCGA](https://www.cbioportal.org/study/summary?id=coadread_tcga) colorectal adenocarcinoma (Firehose Legacy)

When I download the dataset, I cannot find a file for the survival data. However, on the [web interface](https://www.cbioportal.org/study/summary?id=coadread_tcga) for the dataset, I am able to plot survival for different patients, so the data obviously exists. 

Where can I download the survival data? I would like to do survival analysis on my own computer.

**Comment by jjgao** [comment]
Hi @suekn the survival data reside in the data_clinical_patient.txt file, specifically the columns of OS_STATUS, OS_MONTHS, DFS_STATUS, and DFS_MONTHS.

Please feel free to contact us at cbioportal@googlegroups.com for additional questions.
