### ISSUE TITLE
Find permanent solution for hosting of coexpression service (if it should in fact be independent)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7086]
We split off the coexpression endpoint on public portal to separate pod (master.cbioportal) in order to handle its load separately.  this is not a permanent solution because deployment is not synchronized.  we need to settle on a permanent solution

**Comment by inodb** [comment]
FYI - Ben mentioned their team would look further into coexpression optimization. Maybe ok to wait with finding a permanent solution for this.
