### ISSUE TITLE
construction of modeled object lists sometimes unnecessary

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#7093]
There are places in the code where performance penalties become unacceptable for large studies [genie], and one type of unnecessary performance hit is when a large collection of modeled objects is created / assembled solely for the purpose of scanning the collection in order to extract a small set of strings (such as stable ids).

Instead, a set of strings might be directly extracted from the basis of finding the collection elements without forming the collection itself.

For example, in GenePanelServiceImpl the function createSampleMap is used to construct a map which maps identifiers to modeled Sample objects. However, the only use of this large collection of modeled Samples is to extract the patientId string for particular samples. A populated Sample object contains a populated Patient which contains a populated CancerStudy. Rather than allocating the memory for hundreds of thousands of Samples, we might instead create a service (and if more efficient a repository) which will supply the patient_id (string) for a given sample_id / study_id string pair (or for a list).

**Comment by jjgao** [comment]
keep this open?
