### ISSUE TITLE
Front End README is unclear on how to run unit tests

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#7095]
In the current Front End README file, it says:

> To run unit/integration tests (need to have API URL defined in .env)

But, I am not sure what this means:

* What is .env?  Do we create one locally?
* What is the API URL used for?
* What value should we set for API URL?

Am happy to update the docs to explain, but I don't know the answers to the above.

Tagging @alisman @Luke-Sikina for help.

**Comment by Luke-Sikina** [comment]
> To run unit/integration tests (need to have API URL defined in .env)
@inodb you added the quoted line about 3 years ago. I don't have a `.env` and tests pass for me. Does `.env` still serve a purpose?

**Comment by inodb** [comment]
.env is legacy. Can be removed

**Comment by ecerami** [comment]
Ok, I am update the README to remove .env.  But, I still can't get the unit tests to run to the end.  See #7096.  Once I figure that out, I can circle back here and update the README docs.
