### ISSUE TITLE
Front End Circle CI Badge Seems to be Off

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#7097]
If you look at the README for the front end repo, the Circle CI for the Master Branch is currently = Red/Failed.  

But, when you click the badge, and go to:  https://circleci.com/gh/cBioPortal/cbioportal-frontend/tree/master

You can see that the top/most recent build is actually green.

Perhaps, the badge is just off?

Not sure who might now this, but tagging @inodb

**Comment by inodb** [comment]
@ecerami in this case it actually seems correctly indicating an error. If you go to the workflow link it is more clear that the last workflow failed (a workflow is like a collection of test jobs with their own error statuses): https://circleci.com/gh/cBioPortal/workflows/cbioportal-frontend/tree/master. I updated the README links accordingly. 

Note that CircleCI badges haven't been working well for a while: https://discuss.circleci.com/t/workflow-status-badge-and-e-mail-support/14818. I'm not entirely sure if it's fixed now as mentioned in the thread and correctly indicating the status of the last workflow, but based on this it seems to be working? Let's keep this issue open until confirmed

**Comment by inodb** [comment]
Filed an issue for the failing screenshot: https://github.com/cBioPortal/cbioportal/issues/7098

**Comment by ecerami** [comment]
@inodb since we expect the E-2-E tests to mostly fail (due to random issues, which @alisman has now explained to me), perhaps another option is just to remove the Circle CI badges entirely?

Or, just show the Circle CI test for unit tests only?

I say this because new people that we want to contribute may come to the page, and immediately see a Red badge, and think things are off.  A green badge or no badge might be better signal to these people.

**Comment by inodb** [comment]
@ecerami yeah that's a good point. We could remove it

Splitting it up would be nice like

unit ✅
api sync ✅

but i don't think the circlceci badge supports that currently.

The target audience for these checks is prolly core developers. Newcomers shouldn't have to worry about it

It's just that when you submit a pull request you immediately might get a bunch of red crosses. That's not very welcoming. Would be nice if we could indicate that they might not be related to your PR e.g. here: https://github.com/cBioPortal/cbioportal-frontend/blob/master/.github/PULL_REQUEST_TEMPLATE.md. Some explanation of our testing setup and expectations around would be good. Can maybe be a separate Markdown file. We can point there from both the README and the PULL_REQUEST_TEMPLATE

**Comment by inodb** [comment]
@ecerami maybe this works otherwise: https://github.com/cBioPortal/cbioportal-frontend/pull/3061. Just a link instead of a badge. Still easy access from the README to test results if u want it. But not immediately a blinking red badge. We can also remove it completely if u prefer

**Comment by ecerami** [comment]
+1 for the link instead of the badge.

**Comment by ecerami** [comment]
@inodb has now removed badge and added links instead.  closing.
