### ISSUE TITLE
Discussion - OncoKB proxy: genome nexus vs cbioportal

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7111]
There are two related issues related too oncokb ploxy:

a. Only use Basic endpoint for OncoKB (not premium) #7102
b. Integration OncoKB annotation in Genome Nexus: https://github.com/genome-nexus/genome-nexus/issues/17

Maybe b could be useful for a?

@zhx828 @inodb @leexgh @onursumer

**Comment by inodb** [comment]
We thought about this and it seems like there won't be duplicate labor between a & b. Once a is done we can also easier switch to using Genome Nexus. The cBioportal backend proxy is not avoidable with the current setup
