### ISSUE TITLE
create group for virtual cohort that shows up in oncoprint

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7113]
It currently is not possible to create a group for a virtual cohort that shows up in the oncporint. This is an example of groups in the oncoprint:

![Screen Shot 2020-05-15 at 10 53 19 AM](https://user-images.githubusercontent.com/1334004/82064084-50073100-969a-11ea-8c85-e35eacf651cb.png)

E.g. try creating a metastatic group for this virtual cohort consisting of breast cases: https://www.cbioportal.org/study/summary?id=5ebead6fe4b09b05466ca9d3

![Screen Shot 2020-05-15 at 10 59 59 AM](https://user-images.githubusercontent.com/1334004/82064827-47fbc100-969b-11ea-8a9d-a2041f2552ae.png)

Then query e.g. TP53 in oncoprint and try to add a group. The Metastatic Breast cancer cases group is missing:

![Screen Shot 2020-05-15 at 11 00 48 AM](https://user-images.githubusercontent.com/1334004/82064951-6d88ca80-969b-11ea-8b01-1982a3e85b32.png)

TODO:

- [ ] allow one to create a group for a virtual cohort that shows up in the oncoprint

**Comment by jjgao** [comment]
@inodb Not sure if I understand but I was able to create a group in a virtual study...

![image](https://user-images.githubusercontent.com/840895/74106054-4c12c280-4b31-11ea-8a05-97f245aa098e.png)

Could you give an example for the other issue?

**Comment by adamabeshouse** [comment]
I think the problem here is that the oncoprint is creating groups based on the study not the virtual study. should we do both or only the virtual study?

**Comment by inodb** [comment]
@adamabeshouse I think both would be nice. Only thing is that you might get a lot of grayed out ones when you combine many studies (the ones that have 0% Freq). Maybe we can show the ones with Freq > 0% at the top?
