### ISSUE TITLE
Broken links on cBioportal/contribution.md

### ISSUE THREAD

**Issue by jimil749** [cBioPortal/cbioportal#7115]
Couple of links in contribution.md doc are broken.

Links which won't work :

[backend code organisation](https://github.com/cBioPortal/cbioportal/blob/master/Backend-Code-Organization.md)
[backend development guidelines](https://github.com/cBioPortal/cbioportal/blob/master/Backend-Development-Guidelines.md)

**Comment by ecerami** [comment]
@jimil749 Thanks for reporting this.  Working on a fix now.

**Comment by ecerami** [comment]
@inodb I am working to fix the links in here.

But, also just noticed that the Contribution.md also has links to:

https://rc.cbioportal.org/

But, that links returns a 503 error.

Is that still maintained, or should I remove the link?

**Comment by inodb** [comment]
@ecerami thanks a lot! It was temp disabled. It's back online now

**Comment by ecerami** [comment]
thanks @inodb!
