### ISSUE TITLE
Gene sets disappeared from the query page

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#7116]
The study_es_0 contains gene sets but somehow the functionality to select them on the query page has disappeared:
![Captura de pantalla 2020-02-05 a les 12 22 21](https://user-images.githubusercontent.com/20278013/73837654-32603b00-4812-11ea-8eb9-ceff59594675.png)

**Prior to version 3.1.4**, this was the query page, with the functionality to select gene sets: 
![Captura de pantalla 2020-02-05 a les 11 48 11](https://user-images.githubusercontent.com/20278013/73837497-e7debe80-4811-11ea-8242-6c1c45962e4a.png)

I guess that the code has been removed by mistake, is that possible? @pvannierop is sure that removing this functionality would have broken tests...

**Comment by alisman** [comment]
Hi guys, 

I will take look at this first thing tomorrow.

**Comment by alisman** [comment]
@oplantalech @pvannierop, is it possible you are testing without the skin_show_gsva property turned on in portal.properties?   This is off by default.   I can see in the local e2e tests that we force it on using code.  
```function showGsva() {
    browser.execute(function() {
        window.frontendConfig.serverConfig.skin_show_gsva = true;
    });
}```
When I run fe locally and switch default, things seem to work fine
