### ISSUE TITLE
Display extended (namespace) annotations

### ISSUE THREAD

**Issue by arnaudceol** [cBioPortal/cbioportal#7121]
Hi,

I would like to show custom annotations extracted from the maf in the mutation table. I've specified a custom namespace both in the meta and maf file, and the columns are correctly imported in the DB as ANNOTATION_JSON (e.g.:  {"mynamespace": {"refseq": "NM_000059.3", "canonical": "YES", "consequence": "missense_variant"} ).

Nevertheless, I don't understand how to allow the user to show this information online.

Any clue?

Thanks a lot, 

Arnaud

**Comment by arnaudceol** [comment]
If it can help, this is an example where we added a few fields to a "ieo" namespace for testing: ieo.refseq, ieo.canonical, ieo.consequence

This is the header of the meta_mutations_extended.txt : 

```
cancer_study_identifier:TESTDATASET_20200115
genetic_alteration_type:MUTATION_EXTENDED
datatype:MAF
data_filename:data_mutation_extended.txt
stable_id:mutations
show_profile_in_analysis_tab:true
profile_description:Mutation data from whole exome sequencing.
profile_name:Mutations
namespaces: ieo
```

and of data_mutation_extended.txt


```
#version 2.4
Hugo_Symbol     Entrez_Gene_Id  Center  NCBI_Build      Chromosome      Start_Position  End_Position    Strand  Variant_Classification  Variant_Type    Reference_Allele        Tumor_Seq_Allele1       Tumor_Seq_Allele2       dbSNP_RS        dbSNP_Val_Status        Tumor_Sample_Barcode    Matched_Norm_Sample_Barcode     Match_Norm_Seq_Allele1  Match_Norm_Seq_Allele2  Tumor_Validation_Allele1        Tumor_Validation_Allele2        Match_Norm_Validation_Allele1   Match_Norm_Validation_Allele2   Verification_Status     Validation_Status
       Mutation_Status Sequencing_Phase        Sequence_Source Validation_Method       Score   BAM_File        Sequencer       Tumor_Sample_UUID       Matched_Norm_Sample_UUID        HGVSc   HGVSp   HGVSp_Short     Transcript_ID   Exon_Number     t_depth t_ref_count
     t_alt_count     n_depth n_ref_count     n_alt_count     all_effects     Allele  Gene    Feature Feature_type    ieo.Consequence cDNA_position   CDS_position    Protein_position        Amino_acids     Codons  Existing_variation      ALLELE_NUM      DISTANCE        STRAND_VEP      SYMBOL  SYMBOL_SOURCE   HGNC_ID BIOTYPE ieo.CANONICAL   CCDS    ENSP    SWISSPROT       TREMBL  UNIPARC ieo.RefSeq      SIFT    PolyPhen        EXON    INTRON  DOMAINS AF      AFR_AF  AMR_AF  ASN_AF  EAS_AF  EUR_AF  SAS_AF  AA_AF   EA_AF   CLIN_SIG
        SOMATIC PUBMED  MOTIF_NAME      MOTIF_POS       HIGH_INF_POS    MOTIF_SCORE_CHANGE      IMPACT  PICK    VARIANT_CLASS   TSL     HGVS_OFFSET     PHENO   MINIMISED       ExAC_AF ExAC_AF_AFR     ExAC_AF_AMR     ExAC_AF_EAS     ExAC_AF_FIN     ExAC_AF_NFE     ExAC_AF_OTH     ExAC_AF_SAS     GENE_PHENO      FILTER  flanking_bps    variant_id      variant_qual    ExAC_AF_Adj     ExAC_AC_AN_Adj  ExAC_AC_AN      ExAC_AC_AN_AFR  ExAC_AC_AN_AMR  ExAC_AC_AN_EAS  ExAC_AC_AN_FIN  ExAC_AC_AN_NFE  ExAC_AC_AN_OTH  ExAC_AC_AN_SAS  ExAC_FILTER
     gnomAD_AF       gnomAD_AFR_AF   gnomAD_AMR_AF   gnomAD_ASJ_AF   gnomAD_EAS_AF   gnomAD_FIN_AF   gnomAD_NFE_AF   gnomAD_OTH_AF   gnomAD_SAS_AF

```

**Comment by jjgao** [comment]
@arnaudceol we haven't finished the work to support ANNOTATION_JSON. I am curious where you found the information about it?

**Comment by arnaudceol** [comment]
Hi @jjgao , I followed the doc for loading extended maf annotations (https://github.com/cbioportal/cbioportal/blob/master/docs/File-Formats.md). Not understanding why they were not displayed, I just checked the source code for the last version (3.2).

**Comment by arnaudceol** [comment]
Is there any other way to display custom annotations?

**Comment by jjgao** [comment]
Hi @arnaudceol, we currently don't have the bandwidth to finish this part of the work. We will work on it but it'll take some time. I am wondering if you would be interested in contributing if you need this feature urgently? @zhx828 do we have a list of tasks?

Also somehow, I couldn't find any text about `ANNOTATION_JSON ` in https://github.com/cbioportal/cbioportal/blob/master/docs/File-Formats.md. I am still puzzled how you found it out...

**Comment by arnaudceol** [comment]
@jjgao I learnt about json just digging the source code. On the other end, the usage of namespaces is documented: https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats although I don't understand how it is used, and how the imported annotations are displayed.

**Comment by jjgao** [comment]
@arnaudceol Thanks for the explanation. It may take us some time before we can restart this work. We will need to finish the backend PR #6457 and then follow up with a frontend PR.

**Comment by Cala3len** [comment]
Hi @jjgao @arnaudceol,

I got the same issue, is it now possible to show custom annotations online ?

Thanks a lot
