### ISSUE TITLE
Add comprehensive test suite for downloading of data from the download tab

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7124]
Would be nice to create some test that downloads data from the download tab (I don't think we have anything like that).

Ideally a test that tries to download the data from the download tab for all these:

https://www.cbioportal.org/results/download?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations

We could extend the test by storing the downloaded files in the repo and checking whether they are still identical.

**Comment by agandolf** [comment]
@inodb Hello! I am a student in a software engineering class, and I would be interested in contributing to this issue as part of an assignment we have. Is this test suite still a relevant need?

**Comment by inodb** [comment]
Hello @agandolf 👋! It would be awesome if you could help with this, we still lack testing for the download tab

Note that the tricky part is that there are no API endpoints to download the data, rather the frontend puts it together. So you would need to script some frontend interaction that downloads the file: https://github.com/cbioportal/cbioportal-frontend#run-of-remote-e2e-tests. We haven't tried the downloading of files yet using [wdio](https://webdriver.io/docs/gettingstarted.html), so you'll have to evaluate whether that's even feasible. My thought was to make an end to end test that:

1. goes to the download tab
2. downloads a file
3. compare the downloaded file with a file already in the cbioportal-frontend repo and see if the output is still the same

Hope that helps!

**Comment by agandolf** [comment]
@inodb Just to clarify, this test will go in to the frontend repo correct? My partner and I are still getting situated with the architecture, and it is a bit confusing with this issue being in the backend repo.
