### ISSUE TITLE
Consider end-to-end test options for DOM v. screenshot tests

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#7134]
I am not exactly sure how to solve this, but putting it out there for @inodb and @alisman 

Here's a quick summary:  as a newbie to the whole front-end process, I followed the front-end README.  I can now compile and run things.  But, the section on remote end-to-end testing is still a bit confusing.  As a newbie, I would expect that if I followed the end-to-end testing instructions, that all the tests would pass.

But, as I have learned from @inodb, there are actually two kinds of end-to-end tests:  DOM tests and screenshot tests.  DOM tests should pass when run locally, but the screenshot tests are unlikely to pass, because the reference screenshots are based on screenshots generated by Circle CI, and are also unlikely to be the same anyway, because of browser differences, screen resolution, etc.

Therefore, to a newbie, when you run end-to-end tests, you get screen fulls of failed tests.  And, I really have no way of knowing what's going on.  But, as far as I know, this is actually the expected behavior.

As a possible solution, perhaps we can make it easier to run DOM tests v. screenshot tests.  Perhaps, this option already exists, and I missed it?

Anyway, possible options:

Option 1:  webdriver-manager.conf.js has an option to exclude certain files.  If users wanted to run just DOM tests, they could `export SPEC_FILE_PATTERN=./remote/specs/**/*.spec.js` and then add another exclusion pattern to exclude screenshot tests.

Option 2:  (which I think is cleaner, but requires more work):  we rename all the end-to-end tests to be either XX.screenshot.spec.js or XX.dom.spec.js.  Then, you could easily create SPEC_FILE_PATTERN to include all tests, just screenshots, or just DOM tests.

**Comment by inodb** [comment]
Good points! I like the idea of only running DOM tests. Should be easy to fix

Off topic: to add some context. We are also considering using localdb e2e tests more. That should be the default for new people starting out imo. Better to not run tests against production & production data. Unless you're writing monitoring tests for production instances. Running those localdb tests could still use some more work tho to improve DX.

**Comment by alisman** [comment]
The screenshot and DOM tests are really the same beast.  They differ only in how an assertion gets made.  We sometimes keep them separate but really I think it's valid and valuable to use them together as part of the same test. 

The fundamental problem is that in order to write/debug the tests, you need to be working locally with your own browser.  @inodb that will be true even as we move more tests to the localdb strategy.  

So I would propose that we work on the README to set the right expectation: running the tests locally should be done ONLY for the purpose of writing new tests or debugging old ones, not for validating existing tests.  That must be done remotely (or in docker container).

**Comment by ecerami** [comment]
I agree with @alisman on rewriting the README to set the right expectations.  As a newbie, I just want to know that my new code won't mess things up or break any existing tests.  When it's complicated to run those tests, it's hard to know if I messed things up.  Happy to update the README if you guys provide some best practices on what each developer should be doing.

**Comment by alisman** [comment]
@ecerami i agree, it's still too painful to fire up e2e either "remote" tests or "local".    I think we can write some scripts to make things a bit easier.   And I will write an intro for e2e testing that conveys the above.

**Comment by alisman** [comment]
@ecerami  https://github.com/cBioPortal/cbioportal/issues/7139

**Comment by ecerami** [comment]
great.  Thanks @alisman!  should I also close this issue?

**Comment by alisman** [comment]
yes i think we can do so.

**Comment by ecerami** [comment]
Closing this issue in favor of #7139.
