### ISSUE TITLE
Questions regarding front end:  end-to-end local testing set-up

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#7137]
I am trying to make my way through the front end README on setting up end-to-end local db testing.

A few questions as I go along:

1.  Instruction:  `Add export BACKEND=cbioportal:rc (or other backend branch) to /env/custom.sh`.  If I want to recreate what's happening within Circle CI, what should I set this to?
2.  Instruction:  `export DB_DATA_DIR=/tmp/mysql`.  What is the meaning of this variable?  What should I set it to?
3.  Instruction:  `eval "$(./setup_environment.sh)"`.  Can I just run `./setup_environment.sh` instead?
4.  There is a set of instructions, labelled "Setup a local docker container environment", but then the instructions after that apply to both local system and docker.  Perhaps, this section should be called:  "Setup local environment" instead?
5.  Under `docker environment (best for making reference screenshots)`, in which directory should I be running these yarn commands?  
6.  Under `docker environment (best for making reference screenshots)`, it says `export CBIOPORTAL_URL='http://cbioportal:8080'`, but since this is a local docker, shouldn't I point to localhost?

Sorry @inodb for all the additional questions :-)

**Comment by pvannierop** [comment]
@ecerami 
@1. Depends. When your branch is part of a PR you do not have to set this param (the backend branch is derived from the target branch of the PR). When running outside of a PR, you have to specify the backend branch in the `cursom.sh`.
@2. Can be any directory of you liking. The mysql service will use it to park its contents.
@3. No
@4. You are right, this section is mislabeled.
@5. In the root of the cbioportal-frontend repo.
@6. No, the url refers to the name of the cbioportal service. It is only accessible on the `cbio-net` docker network and has nothing to do with localhost.

**Comment by inodb** [comment]
Thanks @pvannierop !

**Comment by ecerami** [comment]
thanks @pvannierop.  I will try the above and report back!
