### ISSUE TITLE
Study View: the fusion table can not filter the result

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#7145]
If you select samples by using fusion table, the study will be filtered.
Tested in https://www.cbioportal.org/study/summary?id=msk_impact_2017

**Comment by n1zea144** [comment]
Have we been getting reports from users on this issue?  I wonder if we can wait for [6688](https://github.com/cBioPortal/cbioportal/pull/6688) instead of merging [7148](https://github.com/cBioPortal/cbioportal/pull/7148)

**Comment by kalletlak** [comment]
@n1zea144 not sure on public instance but on pedcbioportal have users reported the issue. I think it would be better to merge 7148 and cleanup it up after 6688 is merged (since the temporary changes added is minimal and easy to cleanup)

**Comment by n1zea144** [comment]
Fair enough.  In light of 7148, I think you may be in a better position to help merge 6688 since there is quite a bit of overlap.  I'm going to switch back to slack to continue conversation.
