### ISSUE TITLE
Database server CPU 100%

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7152]
This happened on 2/10 right around the time of a hand-on workshop

![image.png](https://images.zenhubusercontent.com/568302fa638e718c995fb230/f51ca2ba-010c-4b9a-940f-791420911e0a)

TODO:

- [ ] Maybe try to recreate by doing the first step of the workshop x 20 people

**Comment by n1zea144** [comment]
Moving elastic RDS config to separate card.

**Comment by sheridancbio** [comment]
Keep issue alive
