### ISSUE TITLE
Add missing documentation for the MUT != functionality (i.e. NOT logic)

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#7157]
e.g. OQL is able to do MUT != V600E to exclude that mutation, as well as MUT != V600 to exclude mutations at position 600. We accidentally left this out when documenting it.

**Comment by jjgao** [comment]
This is very useful. One caveat is that we can only exclude one mutation, e.g. `BRAF: MUT!=V600 MUT!=K601` will include all mutations since it's OR logic. I am wondering if we can use AND logic for NOT, e.g.

- `BRAF: MUT!=V600 MUT!=K601` => BRAF mutations other than V600 and K601
- `BRAF: MUT=V600 MUT!=K600E` => V600 mutations other than V600E
- `BRAF: DRIVER MUT!=V600` => BRAF driver mutations other than V600

@cBioPortal/product

**Comment by adamabeshouse** [comment]
@jjgao ah yes. I think introducing different logics is a little complicated both from implementation and user standpoint. what about just having the syntax `MUT!=V600,K601`. theres never commas in protein change codes, right?

**Comment by adamabeshouse** [comment]
@jjgao @inodb @tmazor what are your thoughts thoughts about my proposed solution to the AND/OR logic issue: allow this syntax `MUT != V600,K601` we could also add a warning if they use more than one `MUT!=`

**Comment by tmazor** [comment]
The comma definitely could work. We also did sort of introduce the concept  of 'and' with the underscore that we use for driver/germline/somatic.

So some options might be:
MUT != V600_K601
MUT != V600,K601
MUT != (V600, K601)

But these kind of solutions don't enable @jjgao 's example of BRAF V600 mutations except V600E. I agree with @adamabeshouse that I'd be worried about having different logic for different OQL. But perhaps this could be a separate expansion of OQL to allow linking of phrases, e.g.
(EXP<2 and EXP>3) or (MUT=V600E and MUT != V600E)
If we want to implement this as a larger feature, maybe it's ok to just allow users to exclude a single mutation for now.

**Comment by adamabeshouse** [comment]
I think _ is more of a modifier, rather than an "AND" linker

I don't know what you mean -@jjgao s example could still be implemented with `MUT=V600 MUT!=V600E`

I don't think we should get into it too much right now with adding logic. Maybe we can just add the ability, to both `MUT=` and `MUT!=`, to list multiple comma-delimited options. What do you think?

**Comment by tmazor** [comment]
Won't `MUT=V600 MUT!=V600E` find the union of V600 and !V600E and that ends up being everything?

**Comment by jjgao** [comment]
@adamabeshouse @tmazor I am wondering if we should table it and release/document the NOT logic until we fully implement the AND/OR/NOT logic? Or @tmazor do you see any major use case by using the current NOT logic?

**Comment by adamabeshouse** [comment]
ah, good point @tmazor

**Comment by tmazor** [comment]
I think the current not logic is still useful -- for example, I can imagine a query for EGFR mutations except T790M being useful. I think I would vote to document what we have and just be very explicit about the limitations. And then separately we can think about how to expand OQL.

**Comment by tmazor** [comment]
I just made a PR with an attempt at documenting this but clearly defining the limitations. Let me know what you think: https://github.com/cBioPortal/cbioportal/pull/7216

**Comment by jjgao** [comment]
@tmazor @adamabeshouse what would be a good next step on this?

**Comment by adamabeshouse** [comment]
@jjgao I guess the next step would be to decide what we want to do. do we want to expand OQL with more complex logic?

**Comment by jjgao** [comment]
Let's close this one and revisit when needs arise.
