### ISSUE TITLE
MutationMapper.getSampleCountInMultipleMolecularProfiles optimization

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#7161]
Time and time again, this routine appears at the top of the AWS-RDS [performance insights dashboard](https://console.aws.amazon.com/rds/home?region=us-east-1#performance-insights:resourceId=db-MT5ERFY4WF4YBI6EYVET2AKY2Q;resourceName=cbioportal-public-devdb) for taking the most time to complete.   Quite often its a query against ccle_broad_2019_mutations (see below).  Unfortunately, the dashboard doesn't provide the entire query (I think if you download it does), but I imagine its against all the samples in the study.

In any event, a brief glimpse at this query in [MutationMapper.xml](https://github.com/cBioPortal/cbioportal/blob/master/persistence/persistence-mybatis/src/main/resources/org/cbioportal/persistence/mybatis/MutationMapper.xml#L282) reveals room for optimization.

I would start here and perhaps work our way up the stack to find further optimizations.

Done : we understand the logic behind this mybatis xml construct ... what is does and why. We highlight suspect bottlenecks / performance hits for targeting our performance improvement efforts.

mybatis logging can show the complete SELECT statement which is passed to mysql.

![image.png](https://images.zenhubusercontent.com/570fd610bf93871ccd99739b/8d3eae87-e02f-438d-ae6e-ce9cae621cae)

**Comment by averyniceday** [comment]
Going to leave notes of my understanding of what the code is doing here...

For the first iteration I am going to skip the additional *IF blocks* under `whereInMultipleMolecularProfiles`:

- function is `getSampleCountInMultipleMolecularProfiles`
- returns `MutationCountByGene` (but I believe it can also return `CopyNumberCountByGene`)
- sets `entrezGeneId`, `hugoGeneSymbol`, `totalCount`, and `numberOfAlteredCases`

`totalCount` is:

`numberOfAlteredCases is`:

**Comment by averyniceday** [comment]
In addition to noticing potential unneeded joins (e.g patient, additional mutation/sample join?), we also simplified the query by removing the subquery in `whereInMultipleMolecularProfiles` (additional `WHERE IN` check). This shortened query time to `4.89647000` from `9.22198300`.

New query: 
```
SELECT
    mutation.ENTREZ_GENE_ID AS entrezGeneId,
    gene.HUGO_GENE_SYMBOL AS hugoGeneSymbol,
    COUNT(*) AS totalCount,
    COUNT(DISTINCT(mutation.SAMPLE_ID)) AS numberOfAlteredCases
            FROM sample
               INNER JOIN mutation ON mutation.SAMPLE_ID = sample.INTERNAL_ID
               INNER JOIN mutation_event ON mutation_event.MUTATION_EVENT_ID = mutation.MUTATION_EVENT_ID AND mutation_event.MUTATION_TYPE != 'Fusion'
               INNER JOIN gene ON mutation.ENTREZ_GENE_ID = gene.ENTREZ_GENE_ID
               INNER JOIN patient ON sample.PATIENT_ID = patient.INTERNAL_ID
               INNER JOIN genetic_profile ON patient.CANCER_STUDY_ID = genetic_profile.CANCER_STUDY_ID
            WHERE genetic_profile.STABLE_ID = "genie_private_mutations" AND sample.STABLE_ID
                IN ([sample list]) ) GROUP BY mutation.ENTREZ_GENE_ID;
```

**Comment by mandawilson** [comment]
Making a few tweaks and joining the gene table after the GROUP BY reduces the query to `3.9` seconds (it goes down to `3.3` if you don't do the `IN([sample_list])` but query by study id instead):

`SELECT
    data.entrezGeneId,
    gene.HUGO_GENE_SYMBOL AS hugoGeneSymbol,
    data.totalCount,
    data.numberOfAlteredCases
FROM gene
INNER JOIN (
SELECT
    mutation.ENTREZ_GENE_ID AS entrezGeneId,
    COUNT(*) AS totalCount,
    COUNT(DISTINCT(mutation.SAMPLE_ID)) AS numberOfAlteredCases
    FROM sample
    INNER JOIN patient ON sample.PATIENT_ID = patient.INTERNAL_ID
    INNER JOIN genetic_profile ON patient.CANCER_STUDY_ID = genetic_profile.CANCER_STUDY_ID AND genetic_profile.STABLE_ID = "genie_private_mutations"
    INNER JOIN mutation ON mutation.SAMPLE_ID = sample.INTERNAL_ID
    INNER JOIN mutation_event ON mutation_event.MUTATION_EVENT_ID = mutation.MUTATION_EVENT_ID AND mutation_event.MUTATION_TYPE != 'Fusion'
    WHERE sample.STABLE_ID IN ([sample list]
) GROUP BY mutation.ENTREZ_GENE_ID
) AS data ON data.entrezGeneId=gene.ENTREZ_GENE_ID
    ORDER BY data.entrezGeneId;
`

**Comment by jjgao** [comment]
Should we keep this open?
