### ISSUE TITLE
Some pathways do not load

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#7165]
- Go to https://deploy-preview-3037--cbioportalfrontend.netlify.com/results/pathways?session_id=5e45bc9fe4b0ff7ef5fd64a2
- Select the pathway named `LUSC-2012-RTK-RAS-PI...` from the pathways table

`PathwayMapper` fails to load this pathway. There might be more problematic pathways like this, this is just one example that I found. This is more likely an issue within the `react-pathway-mapper` library itself.

**Comment by Rgtemze** [comment]
For some reason, in the json file that keeps track of pathways; pathway name in the key and value pair did not match https://github.com/iVis-at-Bilkent/pathway-mapper/blob/558b5f0c05284a73cecf5af82363ab5b432d9e22/src/data/pathways.json#L1040
and thus pathway could not be loaded.

**Comment by onursumer** [comment]
fixed by https://github.com/iVis-at-Bilkent/pathway-mapper/commit/aea10d0059e9de39395205e2ce39f24ee9c4bc15
