### ISSUE TITLE
Too much going on in the mutation table w/i study view

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#7183]
I noticed this while fixing #6752.

When you mouse over a MutSig or GISTIC icon, three things actually happen all at the same time:

1. A check box appears, which shifts what you are pointing at.
2. A tooltip for OncoKB appears.
3. A tooltip for MutSig or GISTIC appears.

Example URL:  https://www.cbioportal.org/study/summary?id=ucec_tcga_pub

Example screencast:

![screencast](https://p15.f3.n0.cdn.getcloudapp.com/items/d5u08y7X/Screen+Recording+2020-02-15+at+08.16.09.58+PM.gif?v=4604805568eeadd974525163dffaeeb2)

Here is a possible solution:

1.  The checkbox is always shown by default, preferably to the left of the gene, so that they are lined up.
2.  We add [T] or [O] icons if the gene is a tumor supressor or oncogene, as determined by OncoKB.  When you roll over these, you get the OncoKB tooltip.

If we did the above, then there would only be one action at a time, instead of three.

Tagging @zhx828 @tmazor @jjgao for thoughts.

**Comment by jjgao** [comment]
> 1. The checkbox is always shown by default, preferably to the left of the gene, so that they are lined up.

It may be confusing to alway have two check boxes in each row. Maybe we can move to the left of the gene but only show them when hovering over or selected. We can try to leave some space to align the genes.

> 2. We add [T] or [O] icons if the gene is a tumor supressor or oncogene, as determined by OncoKB. When you roll over these, you get the OncoKB tooltip.

👍
