### ISSUE TITLE
redirect ln?q=tp53 to "Curated non-redundant set"

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7184]
This was requested by [user](https://groups.google.com/forum/#!topic/cbioportal/eIWdVkSOYdE)

Currently ln url (e.g. http://cbioportal.org/ln?q=TP53:MUT) redirect to query for TCGA PanCancer Atlas Studies, it would be more useful if the query is redirected to "Curated non-redundant set". Note that "Curated non-redundant set" will keep changing so a fixed virtual study will not work.

**Comment by jjgao** [comment]
unstale

**Comment by alisman** [comment]
@adamabeshouse so, the way the ln path currently works is it just points at a virtual study that has all TCGA studies.  As JJ pointed out, we want the curated set of non-redundant studies 
![image](https://user-images.githubusercontent.com/186521/88719613-91cc4300-d0f1-11ea-8766-cf1d5528d2ea.png)
We need to example where that list of studes comes from and figure out how we can target it.
