### ISSUE TITLE
Homepage: query by pathwaymapper pathways

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7200]
The current pathway queries are manually curated:

<img width="832" alt="Screen Shot 2020-02-18 at 3 32 14 PM" src="https://user-images.githubusercontent.com/1334004/74775529-e24a9500-5263-11ea-9812-e50cc617b4a4.png">

Would be nice to pull these from pathwaymapper.org same as we do for the new pathwaymapper tab

**Comment by jjgao** [comment]
Maybe we could just manually curate a list of pathways/gene sets?
