### ISSUE TITLE
cbioportalImporter.py should use proper sub commands

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7201]
Currently `--command` is an option to the `cbioportalImporter.py` script. We should change this such that each possible command is a proper subcommand with its own options. E.g. you can do

`cbioportalImporter.py remove-study --help`

`cbioportalImporter.py import-cancer-type --help`

For each of the possible commands: 

https://github.com/cBioPortal/cbioportal/blob/c545a4ad1593f2778bd88d821e3d4363c1ef66cf/core/src/main/scripts/importer/cbioportalImporter.py#L50-L54

**Comment by mdhvprasad** [comment]
Hi @inodb @jjgao, is this issue still open? I am currently enrolled in a CS course where our project is to make an open-source github contribution, so I was wondering if I could work on this issue. Thanks!

**Comment by inodb** [comment]
Hello @mdhvprasad 👋 ! Yes it would be great if you could work on this!

`argparse` has some functionality to add subcommands: https://docs.python.org/dev/library/argparse.html#sub-commands

**Comment by inodb** [comment]
@mdhvprasad an alternative might be to use click: https://click.palletsprojects.com/en/7.x/. Seems more feature rich than argparse

**Comment by mdhvprasad** [comment]
Awesome i'll look into it, thanks!

**Comment by mdhvprasad** [comment]
@inodb I ended up going with argparse for the sake of simplicity, but I can do it using click if you would prefer. I'm mentioning you here because I'm not able to assign reviewers to the PR

**Comment by inodb** [comment]
@mdhvprasad argparse sounds good
