### ISSUE TITLE
disconnect intragenic deletion with fusion annotation

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7210]
For example, in [this patient](https://www.cbioportal.org/patient?sampleId=P-0004860-T01-IM5&studyId=msk_impact_2017), ERBB4-intragenic (fusion) is annotated as oncogenic because (I guess) it was matched to the ERBB4 fusion annotation.

We should disconnect intragenic deletions with fusion annotation but match them to deletion/truncation mutations.

Note: once we disconnect, EGFR-intragenic will no longer be annotated as oncogenic. Currently they are matched to "EGFR fusion" but they should really be matched to VIII, VII, ....

**Comment by zhx828** [comment]
@jjgao this is already the logic. I think the problem is the mutation type. I can do a fix in portal that ignore the mutation type when it's intragenic variant.

**Comment by zhx828** [comment]
Westil need this.
