### ISSUE TITLE
Do not create / request study view treatments chart if no PRISSMM data

### ISSUE THREAD

**Issue by Luke-Sikina** [cBioPortal/cbioportal#7222]
Leverage new study metadata to determine whether or not to create the chart depending on whether or not the treatments data meets the PRISSMM standard.

**Comment by jjgao** [comment]
unstale

**Comment by Luke-Sikina** [comment]
Don't unstale this. I forgot this ticket exists, but it is complete. This is covered by `/api/treatments/display`
