### ISSUE TITLE
500 error on patient/samples endpoint

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7232]
500 error on 
https://www.cbioportal.org/api/studies/hnsc_tcga_pub/patients/TCGA-CV-7254-01/samples?projection=DETAILED

This produces SQL error

This happens somewhat frequently and not just for this study:
http://www.cbioportal.org/api/studies/brca_tcga_pub/patients/TCGA-BH-A0BG-01/samples?projection=DETAILED

**Comment by kalletlak** [comment]
Looks like sample id is passed instead of patient id.
