### ISSUE TITLE
500 error on api endpoint exposes SQL code in error message

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7233]
I noticed that the endpoint returns actual errant SQL code in error message.   NOTE: there is another ticket #7232 to fix the error, this ticket is about error reporting content in response.

https://www.cbioportal.org/api/studies/hnsc_tcga_pub/patients/TCGA-CV-7254-01/samples?projection=DETAILED

![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/24038e32-d0d0-4f85-882c-013762d9a9e0)

**Comment by n1zea144** [comment]
Will put on pipelines scrumboard.

**Comment by alisman** [comment]
@Luke-Sikina seems like this should be a pretty simple fix, right?  like some error page?

**Comment by Luke-Sikina** [comment]
Yup, I think this is a pretty quick fix. Here's something I prototyped quickly: https://github.com/cBioPortal/cbioportal/pull/7875
