### ISSUE TITLE
Update DB schema to handle resources

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#7234]
Add following tables:

**resource_definition**
RESOURCE_ID   
DISPLAY_NAME  
DESCRIPTION (optional) 
RESOURCE_TYPE (STUDY | PATIENT | SAMPLE) 
OPEN_BY_DEFAULT (boolean)
PRIORITY (defines order in table/in tabs)
CANCER_STUDY_ID

**resource_sample**
ID (auto_increment)
INTERNAL_ID
RESOURCE_ID
URL

**resource_patient**
ID (auto_increment)
INTERNAL_ID
RESOURCE_ID
URL

**resource_study**
ID (auto_increment)
INTERNAL_ID
RESOURCE_ID
URL

**Comment by kalletlak** [comment]
`CANCER_STUDY` -> `CANCER_STUDY_ID`
