### ISSUE TITLE
samples with mutations but not in sequenced case list

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#724]
There are samples with mutations but are not included in the sequenced case list.

|

- [ ]  Sample_ID | Study_ID |
- [ ] | --- | --- |
- [ ] | TCGA-22-0940-01 | lusc_tcga_pub |
- [ ] | TCGA-22-4594-01 | lusc_tcga_pub |
- [ ] | TCGA-33-4589-01 | lusc_tcga_pub |
- [ ] | TCGA-34-2605-01 | lusc_tcga_pub |
- [ ] | TCGA-33-4579-01 | lusc_tcga_pub |
- [x] | DU145 | prad_mskcc |
- [x] | CWR22Ru1 | prad_mskcc |
- [x] | DU145T | prad_mskcc |
- [x] | LAPC14-5748 | prad_mskcc |
- [x] | LAPC14-5749 | prad_mskcc |
- [x] | LAPC17 | prad_mskcc |
- [x] | LAPC23 | prad_mskcc |
- [x] | LAPC25 | prad_mskcc |
- [x] | LAPC4-1T | prad_mskcc |
- [x] | LN-m971 | prad_mskcc |
- [x] | LNCaP-104S | prad_mskcc |
- [x] | LuCAP35T | prad_mskcc |
- [x] | 585268 | sclc_jhu |
- [x] | 588421 | sclc_jhu |
- [x] | 637122 | sclc_jhu |
- [x] | 636776 | sclc_jhu |
- [x] | 639170 | sclc_jhu |
- [x] | 588419 | sclc_jhu |
- [x] | 631057 | sclc_jhu |
- [x] | 631069 | sclc_jhu |
- [x] | 631073 | sclc_jhu |
- [x] | TCGA-BR-8362-01 | stad_tcga_pub |
- [ ] | TCGA-BJ-A291-01 | thca_tcga_pub |
- [ ] | TCGA-CE-A481-01 | thca_tcga_pub |
- [ ] | TCGA-DJ-A3V3-01 | thca_tcga_pub |
- [ ] | TCGA-DJ-A4UQ-01 | thca_tcga_pub |
- [ ] | TCGA-E8-A432-01 | thca_tcga_pub |
- [ ] | TCGA-E8-A438-01 | thca_tcga_pub |
- [ ] | TCGA-EL-A3ZP-01 | thca_tcga_pub |
- [ ] | TCGA-EL-A3ZS-01 | thca_tcga_pub |
- [ ] | TCGA-ET-A2MX-01 | thca_tcga_pub |
- [ ] | TCGA-ET-A40R-01 | thca_tcga_pub |
- [ ] | TCGA-ET-A40T-01 | thca_tcga_pub |
- [ ] | TCGA-FY-A40N-01 | thca_tcga_pub |
- [ ] | TCGA-KS-A4ID-01 | thca_tcga_pub |
- [ ] | TCGA-BJ-A0ZF-01 | thca_tcga_pub |
- [ ] | NA | nccrcc_genentech_2014 |
- [ ] | NA | all_stjude_2015 |
- [ ] | NA | tet_nci_2014 |
- [x] | NA | es_dfarber_broad_2014 |
- [x] | NA | ccrcc_utokyo_2013 |
- [ ] 

Here is the SQL:

``` sql
select distinct sample_id, s.stable_id, cs.cancer_study_identifier
from mutation m, sample s, patient p, cancer_study cs
where m.sample_id=s.internal_id
  and s.patient_id=p.internal_id
  and p.cancer_study_id=cs.cancer_study_id
  and sample_id not in (
    select patient_id
    from patient_list l, patient_list_list ll
    where l.list_id=ll.list_id
    and l.stable_id like "%_sequenced"
  );
```

**Comment by ritikakundra** [comment]
@jjgao: are the NA's sample IDs?

**Comment by jjgao** [comment]
@ritikakundra yes they are sample ids. We need to figure that out too.

**Comment by jjgao** [comment]
@ritikakundra any update on this?

**Comment by jjgao** [comment]
@ritikakundra update?

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/datahub #308](https://github.com/cBioPortal/datahub/issues/308) via [**ZenHub**](https://www.zenhub.com/)
