### ISSUE TITLE
study view gene tables are too quick to reset search results

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7246]
On Study View, the Mutated/CNA/Fusion Genes tables have a search feature. If I search for something, and then select a gene, the search box remains populated but the table resets to all genes.

This is a new behavior - it used to display the search results until actively cleared by the user, even after selecting a gene. Can we revert to the old behavior for these tables?

**Comment by kalletlak** [comment]
Looks like similar to https://github.com/cBioPortal/cbioportal/issues/7214
