### ISSUE TITLE
Selection for fusion-positive samples not working in study view

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#7249]
Selection of fusion positive samples will show the breadcrumb but won't actually select the samples. 

![image](https://user-images.githubusercontent.com/11892704/75581634-ea5ebd80-5a37-11ea-8e2d-19b6b7dae5a9.png)

**Comment by zhx828** [comment]
@schultzn we have fixed the issue in https://github.com/cBioPortal/cbioportal/pull/7148. Once we make the new release which is gonna happen either today or next Monday, the issue should be gone.

**Comment by zhx828** [comment]
@schultzn this is now fixed in production.
