### ISSUE TITLE
pathway mapper - move % after number

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7251]
![image](https://user-images.githubusercontent.com/10508276/75588364-7d065900-5a46-11ea-9a83-c833d99465b5.png)

In "alteration frequency" tooltop -- for consistency, please put the % after the number rather than before.

**Comment by ugurdogrusoz** [comment]
Let's check whether we have this in other places (help, tooltips, etc.) as well.

**Comment by tmazor** [comment]
That's definitely worth a second set of eyes, but I did look and didn't find it anywhere else

**Comment by tmazor** [comment]
Looks good!
