### ISSUE TITLE
Optimize mutation count calculation during import of mutation data

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#7253]
[The DaoMutation.calculateMutationCountByKeyword(...)](https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportExtendedMutationData.java#L518) - [calculateMutationCountByKeyword(..)](https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/dao/DaoMutation.java#L189) adds a significant amount of time during import for large MAF files (>11 hrs during GENIE import).  Lets look for ways to speed up this computation.

**Comment by ao508** [comment]
PR: https://github.com/cBioPortal/cbioportal/pull/7895
