### ISSUE TITLE
Custom driver annotation is not deselectable

### ISSUE THREAD

**Issue by jensreeder** [cBioPortal/cbioportal#7255]
Hi,

we are running a local instance of cBio@v3.1.11 and integrated it with some custom driver annotations. This works indeed very well, however we are not able to deselect the checkbox  in the "Annotate Data" menu at the top of the oncoprint pages.  We can do that for "oncoKB driver" and HotsSpots, so I hope it will be available for custom drivers as well.

![Screen Shot 2020-03-02 at 11 22 08 AM](https://user-images.githubusercontent.com/2548288/75709925-7b23dc00-5c78-11ea-932c-2e25cf6bc4c7.jpg)

Could you comment on wether this is a bug or wether there is maybe a misconfiguration somewhere on our side? 

thanks
Jens

**Comment by mjn138** [comment]
I've got the same issue.  I'm wondering if we are doing something wrong or there is an issue with the code as well.  Is anyone able to comment?

**Comment by jjgao** [comment]
This should have been fixed.
