### ISSUE TITLE
SV: Custom Selection should not support grouping

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#7257]
Before having the Groups feature, we could use the Custom Selection to specify the groups. But now we should remove that feature which causes lots of confusion.
Addition to that, we should also support comma as the separator among sample ids. Niki and Ben was trying to copy/paste the list of sample ids separated by the comma but wasn't able to get it work. The warning message is also not so informative.

![image](https://user-images.githubusercontent.com/840895/94960274-9c73d180-04c0-11eb-9ed0-5835dd8b817c.png)

**Comment by jjgao** [comment]
@zhx828 sounds good!

**Comment by zhx828** [comment]
We still need this

**Comment by jjgao** [comment]
@zhx828  do you still plan to work on this or should we get some help from others?

**Comment by zhx828** [comment]
@jjgao I unassigned myself

**Comment by adamabeshouse** [comment]
@zhx828 I'm confused as to what still needs to be done. it looks like there is already something in there for 'disableGrouping'. do you want me to just take out the info message?

**Comment by jjgao** [comment]
@adamabeshouse removing the `data format` button may be enough. The current code also accept the group_name column - should we clean up that code?

**Comment by zhx828** [comment]
@adamabeshouse yeah as JJ mentioned, I think this component should not support grouping anymore. If it already has the `disableGrouping`, then when it's true, we should update the description in `Data Format`.

**Comment by jjgao** [comment]
@adamabeshouse maybe simply removing the `data format` button?
