### ISSUE TITLE
Empty "CNA Genes" panel

### ISSUE THREAD

**Issue by zhanxw** [cBioPortal/cbioportal#7262]
Hello, I am running cBioportal v3.1.11 on docker. My cancer study has many CNA genes, but there are not shown in the cBioportal.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/157832/75903993-097a9800-5e08-11ea-8025-67468cbf44c0.png">

The left part is the empty CNA genes panel, which is not correct.
As the right part shown many samples have ~1 genome altered, I expect many genes should pop up on the left plot.

I used Safari and found the web request (http://OUR_WEB_SERVER/api/cna-genes/fetch) returns "[]". I have also tried to re-import the study (as suggested by #6647), the console showed the following messages:

```
Reading data from:  /study/data_cnv_discrete.txt
Recaching...
Finished recaching...
--> profile id:  8452
--> profile name:  discrete CNV
--> genetic alteration type:  COPY_NUMBER_ALTERATION
--> total number of samples: 88
--> total number of data lines:  30110
--> records inserted into `sample_profile` table: 88
--> records inserted into `genetic_alteration` table: 30123
--> total number of data entries skipped (see table below):  5

```
I assume that means the CNA data were successfully imported. 

At this stage, I guess it is a backend issue. But I do not know where to start debugging.
Can you give some help? Thanks.

**Comment by zhanxw** [comment]
Based on the codes (https://github.com/cBioPortal/cbioportal/blob/3f597e1af00751e3c9669ea630c4f0645bdeae9f/web/src/main/java/org/cbioportal/web/StudyViewController.java#L354), does the CNA gene panels list the -2 and 2 values (-2 = homozygous deletion, 2 = high level amplification)?

**Comment by kalletlak** [comment]
@zhanxw Only amplifications and deep deletions are shown in CNA Genes table. There were performance issues in the backend when showing all the alterations.

CC: @jjgao

**Comment by jjgao** [comment]
It was also due to too many -1 and 1's if we include them.

**Comment by lconde-ucl** [comment]
Hi @zhanxw, did you ever find out what the problem was? I cannot see the CNA genes either, even though the import seems to be successful:

```
Reading data from:  /study/gcgr/data_CNA.txt
Recaching...
Finished recaching...
--> profile id:  16
--> profile name:  Putative copy-number alterations from ASCAT
--> genetic alteration type:  COPY_NUMBER_ALTERATION
--> total number of samples: 31
--> total number of data lines:  90
--> records inserted into `sample_profile` table: 31
--> records inserted into `genetic_alteration` table: 88
--> records inserted into `sample_cna_event` table: 169
--> total number of data entries skipped (see table below):  2
```

Thanks
Lucia

**Comment by zhanxw** [comment]
I roughly recall that it is related to a js graph that is not robust to the boundaries inputs. The solution is probably to update to a newer version of cbioportal.

**Comment by lconde-ucl** [comment]
Hi @zhanxw,

many thanks for replying, really appreciated. We installed cbioportal this week with the latest release from git (version 3.6.7), so it's not an issue with an older version. I am also uploading a very small CNA data file, only ~90 genes that had at least one -2 or 2 alteration, as it was also suggested that it could be an issue with having too many alterations. So I'm not sure what else to do. Weird thing is the CNA data shows fine in the individual Patients, is only empty in the summary tab. 

@kalletlak @jjgao sorry to mention you, but if you have any other suggestions please let me know.

Regards
Lucia

**Comment by lconde-ucl** [comment]
Dear all, 
just wanted to let you know that reinstalling cbioportal (same version as before) fixed the problem. I am suspecting that the problem was that hg38 was not enabled originally, and my study was using reference hg38. Reinstalling cbioportal making sure that hg38 was enabled seemed to fix the problem.
Best
Lucia

**Comment by Cala3len** [comment]
Dear @lconde-ucl,

I am facing the same issue with cbioportal v3.6.7 and so on with later versions. I defined the following variables on my portal.properties file : 

# species and genomic information
species=human
ncbi.build=38
ucsc.build=hg38

But it still do not work. Maybe I am missing something. How did you enabled hg38 in your case ?

Best,
Clément

**Comment by berguner** [comment]
Hi,
I am also having the same issue on our internal cBioPortal instance. I downloaded a public dataset (msk_access_2021) from the data hub and imported it to check if the problem was related to our study data but CNA genes panel is also empty for the public study. Have you found a solution to this @clbenoit ?

Cheers,
Bekir

**Comment by lconde-ucl** [comment]
@clbenoit apologies, for some reason your message slipped through the cracks and I didn't see it until now. Probably too late now but in any case, when I said that I enabled hg38 I meant that when deploying via docker, I ran data/init_hg38.sh (instead of data/init.sh), but although I suspected this fixed the problem in my case, I'm not 100% sure.

@berguner, check if both the study and your cbioportal installation are using the same assembly. If they differ, that could be the reason. If not, then I don't know, there isn't a clear answer as to why this keeps happening

**Comment by berguner** [comment]
Thanks for the feedback @lconde-ucl , my issue is solved with the latest seedDB https://github.com/cBioPortal/datahub/pull/1998 .

**Comment by vsmicrogenomics** [comment]
Hi,

I am using cBioPortal Version 6.0.20 and seed database version 2.13.1. My cancer study contains many CNA genes, but they are not displayed on the cBioPortal summary page. However, they are visible when checking the sample-wise plots.

Could you please help me troubleshoot this issue? Let me know if you need any additional information.

Thanks!

<img width="291" alt="Image" src="https://github.com/user-attachments/assets/90f70ac0-1d8b-46fe-9e45-e5c6e13759d8" />

**Comment by fishcakess** [comment]
Hey Guys, 

I'm also having the same problem as above. Only CNA's showing are where the values are set to 2 (I have no -2 in my datasets but lots of -1, 0 and 1)

Running two verisons on hg19, studies are set to 37 / hg19 - doesnt work on 5.4.7, just downloaded it again to my local machine and on latest version from github https://github.com/cBioPortal/cbioportal-docker-compose has the same issue. Looks like this version should have the correct seedDB?

Is this still a limitation on display as mentioned at the top of this thread?

Thank you <3
