### ISSUE TITLE
Fix client side error handling

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7269]
# Patient view
- [ ]  OncoKB cancer gene list failure results in broken UI
- [ ] Should //www.cbioportal.org/api/cosmic-counts/fetch endpoint failure cause error screen?

# Results View
- [ ] Should genome nexus failure result in error screen? https://www.genomenexus.org//cancer_hotspots/genomic
- [ ] Oncokb failure should show warning message
- [ ] https://www.genomenexus.org//ensembl/transcript causes break of mutations tab
- [ ] https://v1.genomenexus.org/annotation/genomic?isoformOverrideSource=uniprot&fields=annotation_summary&fields=hotspots fails silently on mutaiton tab

**Comment by jjgao** [comment]
@alisman should we keep this open?
