### ISSUE TITLE
error in genie/query/comparison/mutations

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7274]
User reported bug: https://groups.google.com/forum/#!topic/cbioportal/dIt9qvDZC18

Go to this query on the GENIE portal: http://bit.ly/3auTpX5
Click on Comparison/Mutations and you get an error:
![image](https://user-images.githubusercontent.com/10508276/76089023-fc37e780-5f86-11ea-8423-d345367a926a.png)

**Comment by adamabeshouse** [comment]
looks like a backend issue, passing it on to @kalletlak

**Comment by kalletlak** [comment]
Looks like number of altered cases is more than number of profiled cases in a subset of cases
Virtual study: https://genie.cbioportal.org/study/summary?id=5e628cace4b0ff7ef5fd9702
Frequency for gene NUTM1 is > 100%
<img width="413" alt="Screen Shot 2020-03-06 at 12 48 53 PM" src="https://user-images.githubusercontent.com/12956870/76108665-0074fc80-5fa9-11ea-8bb2-d11b5c8dcfae.png">

**Comment by zhx828** [comment]
@tmazor @kalletlak what I found out is that there are three samples in this study are sequenced for gene NUTM1 but without any alteration. They are all in panel `WAKE-CA-NGSQ3`
```
GENIE-WAKE-C1288-01
GENIE-WAKE-C1437-01
GENIE-WAKE-C1498-01
```

Four samples showing up in the table are 
```
GENIE-DFCI-036594-74732
GENIE-DFCI-053407-250241
GENIE-DFCI-091132-350765
GENIE-DFCI-111640-664210
```
They all have NUTM1 missense mutations and associated with panel `DFCI-ONCOPANEL-3`
But the panel `DFCI-ONCOPANEL-3` does not include gene NUTM1.

@tmazor Does `DFCI-ONCOPANEL-3` include NUTM1?

**Comment by tmazor** [comment]
@kalletlak @zhx828 NUTM1 is not profiled for exonic mutations, so it does not appear in the gene panel list. But some intronic regions are included to look for structural rearrangements -- and I guess that intronic coverage is enough to occasionally find an exonic mutation. 

I'm not sure what the best way to deal with this situation is.

cc: @jjgao @schultzn

**Comment by jjgao** [comment]
Should mutations outside of the panel be filtered out?

**Comment by inodb** [comment]
Closing this for now b/c it's a data issue. Let's follow up with a card to address the data issue
