### ISSUE TITLE
quick edit is causing typos with the OQL validation

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7275]
If I use the quick edit box to add OQL, the auto-validation is hyperactive and causes typos. I think it might be because it is highlighting the location of errors, whereas the box in the main query submission doesn't automatically highlight the error.

Quick add:
![Mar-06-2020 10-40-56](https://user-images.githubusercontent.com/10508276/76098184-006c0100-5f97-11ea-926c-31ed2456b5c6.gif)

Regular query:
![Mar-06-2020 10-42-09](https://user-images.githubusercontent.com/10508276/76098274-285b6480-5f97-11ea-9bc5-19a38bf42e33.gif)

The gene entry box in study view has the same issue as the quick add.

**Comment by ecerami** [comment]
Good catch...  Confirming that I see this too...
