### ISSUE TITLE
Group comparison - Clinical tab: switch to Horizontal Bars by default

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7279]
I find it hard to read the current bar plot in the Clinical tab, esp when there are many categories in a row/attribute.

example: 
https://www.cbioportal.org/comparison/clinical?sessionId=5de691e5e4b05f1dfb8ac568

Option 1 - current:
![image](https://user-images.githubusercontent.com/840895/76864732-fae4a580-6837-11ea-9716-577a1caad882.png)

Option 2 - "Horizontal Bars" & 100% stacked bar char by default:

![image](https://user-images.githubusercontent.com/840895/76864783-0fc13900-6838-11ea-98a0-7ba48fc8c6df.png)

Option 3 - "Horizontal Bars" & sample count stacked bar chart by default:

![image](https://user-images.githubusercontent.com/840895/76864842-249dcc80-6838-11ea-85ed-04e70287be0f.png)

Another potential improvement is to provide different options to order:
i. based on the difference between groups (p-value?)
ii. based on the total number of samples
iii. based on their frequencies in different groups (the categories that are more frequent in the first group goes first, then send group, etc). 

If the order above are the same, order them alphabetically.

@kalletlak @schultzn @tmazor

**Comment by tmazor** [comment]
I agree the current plot can be overwhelming, but I actually like it. You can see all the data at once, and you actually get additional information that is lost in some of the other plots (for example, in the horizontal bars plot, you have no information about how common each metastatic site is - could be 1 case or hundreds - but that information is clear in the stacked bar chart)

But I do like the idea of having some logic in the category order, as long as we keep the orderconsistent across the bars. I think it makes sense to have larger categories at the bottom.

**Comment by jjgao** [comment]
@tmazor good point.

**Comment by jjgao** [comment]
I made some change to the description above - added option 3, and thought it could be a good default. If we cannot agree on this, I would suggest put this on hold until we see a request.
