### ISSUE TITLE
Possibility to share created groups when sharing the study

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#7280]
For both physical study and virtual study, should we provide a way to share groups when user is trying to share the study? This request is coming from Niki and wondering whether that's easy to implement.

We tested and it's not supported at the moment.

**Comment by jjgao** [comment]
It can be potential confusing, e.g. if I have a list of groups in msk_impact_2017 and than @schultzn send me his version, would his groups be added to mine? Should I be notified and have a choice? How can Niki decide whether to send the groups or not? What if there is a name clash? 

@schultzn could you elaborate your use case a little more?

**Comment by schultzn** [comment]
I tried to share a virtual cohort with a set of groups pre-defined with somebody the other day. It would have been nice if the shared virtual cohort had also contained my groups. But I understand now that this is potentially difficult. 

I am sure it will come up again, but maybe it is ok to not support this for the moment.

**Comment by jjgao** [comment]
Maybe we can add another button "Share" after "Filter"?

![image](https://user-images.githubusercontent.com/840895/76541722-5db1f780-645a-11ea-94e2-daeb2f0b15c3.png)

The "Share" button will create a link to the study with the selected groups to share, e.g.

https://www.cbioportal.org/study/summary?id=msk_impact_2017#sharedGroups=group1,group2

When a user open a link like this, the two groups will be added to their groups.

Naming clash is probably fine as long as they all have different IDs...

Any technical thoughts, @kalletlak @zhx828 ?

**Comment by jjgao** [comment]
related: https://groups.google.com/forum/#!topic/cbioportal/Caix7Pw3quo

**Comment by kalletlak** [comment]
How should we handle
1. invalid groups?
2. groups belonging to other study(studies) which are not part queried studies?

**Comment by jjgao** [comment]
@kalletlak 

1. For invalid group, I think we can ignore them. How are we dealing with invalid group when a group is loaded now?

2. I think if the URL was constructed by the UI, this scenario is not possible - is that right? Of course, when a user manually change the URL, this could happen. In that case, I think we should just ignore the group when opening.

**Comment by kalletlak** [comment]
> @kalletlak
> 
> 1. For invalid group, I think we can ignore them. How are we dealing with invalid group when a group is loaded now?

Currently we have no mechanism to to deal with them as they are not used directly.

> 2. I think if the URL was constructed by the UI, this scenario is not possible - is that right? Of course, when a user manually change the URL, this could happen. In that case, I think we should just ignore the group when opening.

Yes and yes

**Comment by kalletlak** [comment]
From discussion with @jjgao 

- [ ] Allow group creation whether the user is logged in or not
    - [ ] For logged in users -> groups would be saved to his account
    - [ ] For non-logged in users-> created groups would have page scope
- [ ] Always show shared groups in groups panel
    - [ ] For logged in users-> shared groups are saved to his account and are highlighted
- [ ] Groups panel should be visible by default on page load if there are any shared groups in the url
