### ISSUE TITLE
Disable Genome Nexus annotations when reference genome is hg38

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#7283]
Disable Genome Nexus annotations when configured genomenexus reference genome is not same as portal’s default reference genome

Currently genome nexus only supports hg19, not hg38. We should disable annotating with Genome Nexus on all pages when the study we are looking at has annotations based on the hg38 reference.

In the future we prolly want to be able to use a different Genome Nexus URL for hg38, since in the current setup hg38 and hg19 would run on different URLs

**Comment by inodb** [comment]
this is fixed
