### ISSUE TITLE
Issues with mRNA Continuous data

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#7285]
I encountered two problems related to mRNA continuous data:

1. If a study only has mRNA continuous data, without Z-scores, it treats it as Z-scores.
2. If a study contains mRNA continuous data and Z-scores, the continuous profile disappears and it is not available, e.g. for heatmaps. See acc_tcga example: https://www.cbioportal.org/results/oncoprint?Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=acc_tcga_cnaseq&gene_list=MYC%2520EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=acc_tcga_gistic&cancer_study_list=acc_tcga)

**Comment by oplantalech** [comment]
@jjgao Do you know if there have been changes recently in mRNA profiles and who did them?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao looks like the data coming back from the API is fine and the problem is in the front end interpretation of the response.

**Comment by jjgao** [comment]
For 1, which part are you referring? Query, oncoprint, heatmap,...

For 2, I thought we alway have zscores of mrna for heatmap?

**Comment by Sjoerd-van-Hagen** [comment]
1. It treats it as z-scores means that they show up on the query page and can be added to the oncoprint which should not be possible.
2. What would be the point of being able to load 'raw' mRNA expression if not to display in the heat map?

**Comment by jjgao** [comment]
1. Could you check if `show_profile_in_analysis_tab` in profile meta file was set to true or false? That controls whether the profile shows up in query page.

2. It's useful in the plots tab and Expression tab before we had heatmap. It may be a good idea to show them in heatmap as well if we can implement a color scheme (I think currently it's fixed based on zscores). However, it will not add too much value since zscores profiles should already capture the info for heatmap since zscores are just linear transformation.

**Comment by Sjoerd-van-Hagen** [comment]
@oplantalech can you double check JJ's suggestion? I think we checked it and it was correctly set but I am not sure.

@jjgao so you are saying that you would be happy if we would implement this?

**Comment by inodb** [comment]
maybe @rmadupuri knows more about this?

**Comment by jjgao** [comment]
> @jjgao so you are saying that you would be happy if we would implement this?

yes,  always :) @Sjoerd-van-Hagen

**Comment by rmadupuri** [comment]
@jjgao quickly parsing through all raw mRNA expression profiles on datahub, the `show_profile_in_analysis_tab` is correctly set to `False` for all studies except one study `utuc_cornell_baylor_mdacc_2019` which we can update quickly. 

Not sure if this is a data related issue.  @oplantalech @Sjoerd-van-Hagen could you give us some studies where this `If a study only has mRNA continuous data, without Z-scores, it treats it as Z-scores.` is seen? Thanks!

**Comment by Sjoerd-van-Hagen** [comment]
@rmadupuri it was a private study from a client, not one from datahub.
