### ISSUE TITLE
Managing failed VEP CLI child processes

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#7288]
We know that when a VEP wrapper-VEP CLI process fails, the CLI doesn't properly clean child processes.  We need a way to kill these processes before resources are exhausted.

**Comment by sheridancbio** [comment]
This work will be part of the genome-nexus-vep code base. Closing this issue here, and relocating to here: 
https://github.com/genome-nexus/genome-nexus-vep/issues/6
