### ISSUE TITLE
Save cluster checkbox state for genomic evolution

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7294]
Currently when clicking through multiple patients the cluster state doesn't get remembered:
<img width="524" alt="Screen Shot 2020-03-12 at 10 07 15 AM" src="https://user-images.githubusercontent.com/1334004/76529870-4585ac80-6449-11ea-8bf0-36980744cb9b.png">
Would be sweet if we could fix this :)

**Comment by jjgao** [comment]
Maybe we can save it to localstorage so that it can be even remembered from session to session?

**Comment by adamabeshouse** [comment]
@jjgao we could do it that way or alternatively we could put it in the URL, and persist it when clicking through patients. thoughts?

**Comment by inodb** [comment]
both seems nice:

- save the default with localStorage
- allow to share state with people using URL

but either works as long as clicking thru patients the state remains the same

**Comment by jjgao** [comment]
I guess the question is whether we want to maintain it for different sessions...
