### ISSUE TITLE
Structural Variant: Migrate Fusions from mutation/mutation_event to structural_variant table

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#7295]
| structural_variant columns            | mapped columns             | remaining columns                     |
| ----------- | ----------- | ----------- |
| GENETIC_PROFILE_ID             | mutation.GENETIC_PROFILE_ID             | mutation.ENTREZ_GENE_ID                     |
| SAMPLE_ID                      | mutation.SAMPLE_ID                      | mutation.SEQUENCER                          |
| SITE1_ENTREZ_GENE_ID           |                                         | mutation.MUTATION_STATUS                    |
| SITE1_ENSEMBL_TRANSCRIPT_ID    |                                         | mutation.VALIDATION_STATUS                  |
| SITE1_EXON                     |                                         | mutation.TUMOR_SEQ_ALLELE1                  |
| SITE1_CHROMOSOME               |                                         | mutation.TUMOR_SEQ_ALLELE2                  |
| SITE1_POSITION                 |                                         | mutation.MATCHED_NORM_SAMPLE_BARCODE        |
| SITE1_DESCRIPTION              |                                         | mutation.MATCH_NORM_SEQ_ALLELE1             |
| SITE2_ENTREZ_GENE_ID           |                                         | mutation.MATCH_NORM_SEQ_ALLELE2             |
| SITE2_ENSEMBL_TRANSCRIPT_ID    |                                         | mutation.TUMOR_VALIDATION_ALLELE1           |
| SITE2_EXON                     |                                         | mutation.TUMOR_VALIDATION_ALLELE2           |
| SITE2_CHROMOSOME               |                                         | mutation.MATCH_NORM_VALIDATION_ALLELE1      |
| SITE2_POSITION                 |                                         | mutation.MATCH_NORM_VALIDATION_ALLELE2      |
| SITE2_DESCRIPTION              |                                         | mutation.VERIFICATION_STATUS                |
| SITE2_EFFECT_ON_FRAME          |                                         | mutation.SEQUENCING_PHASE                   |
| NCBI_BUILD                     | mutation_event.NCBI_BUILD               | mutation.SEQUENCE_SOURCE                    |
| DNA_SUPPORT                    |                                         | mutation.VALIDATION_METHOD                  |
| RNA_SUPPORT                    |                                         | mutation.SCORE                              |
| NORMAL_READ_COUNT              |                                         | mutation.BAM_FILE                           |
| TUMOR_READ_COUNT               |                                         | mutation.TUMOR_ALT_COUNT                    |
| NORMAL_VARIANT_COUNT           |                                         | mutation.TUMOR_REF_COUNT                    |
| TUMOR_VARIANT_COUNT            |                                         | mutation.NORMAL_ALT_COUNT                   |
| NORMAL_PAIRED_END_READ_COUNT   |                                         | mutation.NORMAL_REF_COUNT                   |
| TUMOR_PAIRED_END_READ_COUNT    |                                         | mutation.AMINO_ACID_CHANGE                  |
| NORMAL_SPLIT_READ_COUNT        |                                         | mutation.ANNOTATION_JSON                    |
| TUMOR_SPLIT_READ_COUNT         |                                         | mutation_event.ENTREZ_GENE_ID               |
| ANNOTATION                     |                                         | mutation_event.CHR                          |
| BREAKPOINT_TYPE                |                                         | mutation_event.START_POSITION               |
| CENTER                         | mutation.CENTER                         | mutation_event.END_POSITION                 |
| CONNECTION_TYPE                |                                         | mutation_event.REFERENCE_ALLELE             |
| EVENT_INFO                     |                                         | mutation_event.TUMOR_SEQ_ALLELE             |
| CLASS                          |                                         | mutation_event.PROTEIN_CHANGE               |
| LENGTH                         |                                         | mutation_event.MUTATION_TYPE                |
| COMMENTS                       |                                         | mutation_event.FUNCTIONAL_IMPACT_SCORE      |
| EXTERNAL_ANNOTATION            |                                         | mutation_event.FIS_VALUE                    |
| DRIVER_FILTER                  | mutation.DRIVER_FILTER                  | mutation_event.LINK_XVAR                    |
| DRIVER_FILTER_ANNOTATION       | mutation.DRIVER_FILTER_ANNOTATION       | mutation_event.LINK_PDB                     |
| DRIVER_TIERS_FILTER            | mutation.DRIVER_TIERS_FILTER            | mutation_event.LINK_MSA                     |
| DRIVER_TIERS_FILTER_ANNOTATION | mutation.DRIVER_TIERS_FILTER_ANNOTATION | mutation_event.STRAND                       |
|                                                   |                                         | mutation_event.VARIANT_TYPE                 |
|                                                   |                                         | mutation_event.DB_SNP_RS                    |
|                                                   |                                         | mutation_event.DB_SNP_VAL_STATUS            |
|                                                   |                                         | mutation_event.ONCOTATOR_DBSNP_RS           |
|                                                   |                                         | mutation_event.ONCOTATOR_REFSEQ_MRNA_ID     |
|                                                   |                                         | mutation_event.ONCOTATOR_CODON_CHANGE       |
|                                                   |                                         | mutation_event.ONCOTATOR_UNIPROT_ENTRY_NAME |
|                                                   |                                         | mutation_event.ONCOTATOR_UNIPROT_ACCESSION  |
|                                                   |                                         | mutation_event.ONCOTATOR_PROTEIN_POS_START  |
|                                                   |                                         | mutation_event.ONCOTATOR_PROTEIN_POS_END    |
|                                                   |                                         | mutation_event.CANONICAL_TRANSCRIPT         |
|                                                   |                                         | mutation_event.KEYWORD                      |

**Comment by kalletlak** [comment]
@n1zea144 I am planning to start writing migration script for fusion->structural variant. I need some help in mapping fields.

**Comment by n1zea144** [comment]
HI @kalletlak, @jjgao There is not much to do here and what there is to do might not be so easy/accurate to do.  The main issue is due to the structure of the [fusion record](https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#fusion-data), which is mirrored in the [FusionRecord](https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/maf/FusionRecord.java#L42) java class and that is the Fusion field.   We do give a description/suggestion to the format, but there really is no defined structure to it.  Looking at MSK data Fusion fields come in two flavors:

>BRD4-intragenic
>WBSCR27-RB1 fusion

For example, we could try to WBSCR27 to Site1_Gene and RB1 to Site2_Gene by parsing MUTATION_EVENT.PROTEIN_CHANGE (this is where the Fusion field from the file ends up), but I think the best we could do is simply map MUTATION.ENTREZ_GENE_ID to STRUCTURAL_VARIANT.SITE1_ENTREZ_GENE_ID.

In general my feeling is that it would be safer to attempt this in a tool that works outside the database which converts fusion data to SV data before import.  This way we can allow the user to manually inspect the data after the tool is run before importing it into the db.

Having said that, I think this mapping may be better understood by looking at the [ImportFusionData.importData()](https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportFusionData.java#L136).

For all mutation records with MUTATION_EVENT.MUTATION_TYPE "Fusion":

GENETIC_PROFILE_ID -> GENETIC_PROFILE_ID
SAMPLE_ID->SAMPLE_ID
CENTER->CENTER

It doesn't look like we do anything with the following fields from the fusion file:
DNA_support
RNA_support
Method
Frame

We can discuss more during planning.

**Comment by jjgao** [comment]
@kalletlak do we need to keep this open?

**Comment by kalletlak** [comment]
@jjgao let's close it for now and reopen if need
