### ISSUE TITLE
Remove outdated timeline & patient view pages (jsp)

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#7302]
- [ ] We should remove the timeline page in the backend, we've already moved it to frontend at [here](https://github.com/cBioPortal/cbioportal-frontend/blob/d03421c3cc5b0087dc184cd34dca662146981a04/src/pages/patientView/timeline/legacy.js)
- [ ] try to remove whole patient view folder in the backend: https://github.com/cBioPortal/cbioportal/tree/master/portal/src/main/webapp/WEB-INF/jsp/patient_view

**Comment by jjgao** [comment]
@dippindots I think we will remove the whole portal module at certain point: https://github.com/cBioPortal/cbioportal/issues/4837
