### ISSUE TITLE
Question re:  MutationAligner

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#7303]
(This is for the cBioPortal Manual).

Domains within the mutation lollipop reference both PFAM and Mutation Aligner. 
e.g. http://mutationaligner.org/domains/PF01030

@jjgao:  Are we actually using mutation aligner for anything specifically in the domain/lollipop diagram?  Or, is this just a link out?

**Comment by jjgao** [comment]
@ecerami it's just a linkout.

**Comment by ecerami** [comment]
tx @jjgao
