### ISSUE TITLE
Question re:  PFAM domains

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#7305]
Does anyone recall exactly how we get the PFAM domains for each protein?

I thought it was based on the UniProt canonical sequence.

But, if you compare:

http://bit.ly/2U5UA8U

with https://pfam.xfam.org/protein/P00533

you can notice some of the domains don't line up exactly, e.g. look at the kinase domain.

@jjgao @tmazor any ideas?

**Comment by inodb** [comment]
@ecerami we are still on an older version of PFAM: https://github.com/genome-nexus/genome-nexus-importer/issues/26

**Comment by ecerami** [comment]
ah, tx @inodb --> closing
