### ISSUE TITLE
Investigation: find all vocabulary for existing survival types

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#7311]
Find all vocabulary for existing survival types:

Find out the vocabulary we are using in both public portal and private portal.

**Comment by dippindots** [comment]
@jjgao @ritikakundra @leexgh Here is my observation:

**Public portal:**

1. Survival types
- OS
- DFS
- PFS
- DSS
- EFS
- PF
- PLATINUM_OS
- PLATINUM_PFS

2. vocabulary for survival types
- OS: `DECEASED` `LIVING`
- DFS: `Recurred/Progressed` `Recurred` `DiseaseFree`
- PFS: `1` `0` `PROGRESSION` `CENSORED` `Not Progressed` `Progressed` `Event` `Censor` `Yes` `No` `Unknown/NA`
- DSS: `DEAD WITH TUMOR` `ALIVE OR DEAD TUMOR FREE` `1` `0`
- EFS: `Censored` `Event` `No Relapse` `Metastatic Relapse` `Localized Relapse`
- PF: `Progressed` `Progression free` `Event` `Censure`
- PLATINUM_OS: `1` `0` 
- PLATINUM_PFS: `1` `0`

**Private portal:**
1. Survival types
- OS
- DFS
- PFS
- DSS
- EFS
- PF
- PLATINUM_OS
- PLATINUM_PFS

other possible types:
-BCFI
-BRAIN_RECU
-DOR
-DRFS
-IDFS
-LOCO_REG
-RFS

2. vocabulary for survival types
- OS: `DECEASED` `LIVING` `NA` `unknown` `ALIVE` `UNSPECIFIED`
- DFS: `Recurred/Progressed` `Recurred` `DiseaseFree` `Progressed` `NA` ` ` `0` `No` `Yes`
- PFS: `ProgressionFree` `Progressed`
`Recurred/Progressed` `DiseaseFree` `unknown` `NO PROGRESSION` `PROGRESSION` `No` `Yes` `Not Progressed` `1` `0` `CENSORED` `Event` `Censor` `Unknown/NA`
- DSS: `unknown` `LIVING` `DECEASED` `No` `Yes` `ALIVE OR CENSORED` `DEAD OF MELANOMA` `0` `1` `ALIVE OR DEAD TUMOR FREE` `DEAD WITH TUMOR`
- EFS: `Censored` `Event` `No Relapse` `Metastatic Relapse` `Localized Relapse`
- PF: `Progressed` `Progression free` `Event` `Censure` `yes` `no`
- PLATINUM_OS: `1` `0` 
- PLATINUM_PFS: `1` `0`

other possible types:
-BCFI: `Yes` `No`
-BRAIN_RECUR: `Yes` `No`
-DOR: `0`
-DRFS: `Yes` `No`
-IDFS: `Yes` `No`
-LOCO_REG: `unknown` `0` `1`
-RFS: `1` `0` `Yes` `No` `Unknown/NA` `NED` `Recurred`

**Comment by dippindots** [comment]
Values that should be removed when migrating: `NA` `unknown` `Unknown/NA` `UNSPECIFIED` and `""`(empty string)

Values mapping by type:
**OS:** 
- `DECEASED` -->1
- `LIVING` `ALIVE` -->0
**DFS:** 
- `Recurred/Progressed` `Recurred` `Progressed` `Yes` `1`(if `1` exist, which is not showing in the database) -->1, 
- `DiseaseFree` `No` `0` -->0
**PFS:**
- `Progressed` `Recurred/Progressed` `PROGRESSION` `Yes` `1` `Event`-->1
- `ProgressionFree` `DiseaseFree` `NO PROGRESSION` `No` `Not Progressed` `0` `CENSORED` `Censor`-->0
**DSS:** 
- `DECEASED` `Yes` `DEAD OF MELANOMA` `1` `DEAD WITH TUMOR` -->1, 
- `LIVING` `No` `ALIVE OR CENSORED` `0` `ALIVE OR DEAD TUMOR FREE` -->0
**EFS:** 
- `Event` `Metastatic Relapse` `Localized Relapse` -->1
- `Censored` `No Relapse` -->0
**PF:** 
- `Progressed` `Event` `yes` -->1
- `Progression free` `Censure` `no` -->0
**PLATINUM_OS:** 
- `1` -->1
- `0`-->0
**PLATINUM_PFS:**
- `1` -->1
- `0`-->0

Other uncertain types:
**BCFI:**
- `Yes` -->1
- `No`-->0
**BRAIN_RECUR:** 
- `Yes` -->1
- `No`-->0
**DOR:** 
- `1`(if `1` exist, which is not showing in the database) -->1
- `0`-->0
**DRFS:** 
- `Yes` -->1
- `No`-->0
**IDFS:** 
- `Yes` -->1
- `No`-->0
**LOCO_REG:** 
- `1` -->1
- `0`-->0
**RFS:**
- `1` `Yes` `Recurred` -->1
- `0` `No` `NED`-->0

**Comment by leexgh** [comment]
I think we also need to find a generic way to handle the text on tooltip, for example the last line we have `Time of Death` for `OS_SURVIVAL`, and `Time of relapse` for `DFS_SURVIVAL`, it is a brief explanation for x-axis
![image](https://user-images.githubusercontent.com/16869603/76232167-b2583700-61fc-11ea-92fe-683c341eaef9.png)
