### ISSUE TITLE
SAML local logout not working (saml.logout.local=true)

### ISSUE THREAD

**Issue by amirineni1** [cBioPortal/cbioportal#7313]
Property **saml.logout.local=true** is not including (/saml/logout?**local=true**) query parameter in logout link. My IDP doesn't support single logout so want to enable local logout. Signout link supposed to include local=true in the logout link when I set saml.logout.local property to true. 

I noticed header_bar.jsp considered the property but react UI simply returning saml/logout for signout link under logged in user button.

**Comment by n1zea144** [comment]
Hi @amirineni1 Thank you for this issue.  Does setting saml.logout.url address this issue:

> saml.logout.url=/login.jsp?logout?local=true

This is one of the properties found on the [SAML setup page](https://docs.cbioportal.org/2.2-authorization-and-authentication/authenticating-users-via-saml#modifying-configuration):

**Comment by amirineni1** [comment]
On click of "Sign Out" button in the UI by default redirects "/saml/logout" without considering property value "saml.logout.local". It supposes to build url as "/saml/logout?local=true" in order to perform local logout instead of single logout.

Upon local logout, page will redirect to saml.logout.url

Please look at the url construction in the one of the jsp page by considering saml.logout.local property value. This functionality is not part of the "Sign Out" button in the react app.

https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/WEB-INF/jsp/global/header_bar.jsp

**Comment by n1zea144** [comment]
@amirineni1 Thanks for pointing this out.  Is there a required change to the frontend code?

**Comment by amirineni1** [comment]
@n1zea144 Yes, please find another pull request associated with the issue. Both should go together in order to SAML local logout function properly.
