### ISSUE TITLE
Co-expression tab is not displayed properly

### ISSUE THREAD

**Issue by kjamrog** [cBioPortal/cbioportal#7315]
I have local instance of cBioPortal set up. When entering Co-expression tab in the query view, the ui crashes with an error: `Cannot read property 'cytoband' of undefined`

One thing which is unusual in my setup is that I have uploaded custom gene annotations using Ensembl Ids (their numerical part, to be precise) as gene identifiers. Is it possible that this is the source of the problem?

**Comment by jjgao** [comment]
@kjamrog would you please contact cbioportal@googlegroups.com for a prompt response? Thanks.
