### ISSUE TITLE
oncoprint: color promoter mutations orange

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#732]
http://bit.ly/1Po4yqn

**Comment by adamabeshouse** [comment]
How does this interact with the new purple fusion color? 
https://github.com/cBioPortal/cbioportal/issues/971

**Comment by jjgao** [comment]
@adamabeshouse good catch. Maybe use another color. How about orange?

**Comment by adamabeshouse** [comment]
Sounds good to me. Do you think dark or light? Maybe dark orange for recurrent, light for non-recurrent?

**Comment by jjgao** [comment]
@adamabeshouse normal orange. Don't worry about recurrence.

**Comment by jjgao** [comment]
@adamabeshouse any update on this?

**Comment by adamabeshouse** [comment]
@jjgao Sorry none yet, but I'll get to it now.

How do I tell whether a mutation is a promoter mutation? It doesn't seem to be a mutation type in mutation_event (only 2 mutations with type `promoter`). Is it `Translation_Start_Site`?

**Comment by adamabeshouse** [comment]
@jjgao @schultzn Where in the sort order should promoter mutations go? And should I add a `PROMOTER` command to OQL?

**Comment by schultzn** [comment]
They could go right before missense variants. Would be nice to have in the OQL.

Thanks!

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1533
