### ISSUE TITLE
Timeline zoom not always zooming to right location

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7326]
For this case: https://deploy-preview-2950--cbioportalfrontend.netlify.com/patient?studyId=lgg_ucsf_2014&caseId=P18
If I click-and-drag to zoom in from 0-1y, what appears is only 0-~6months

Similarly for P15 when clicking + dragging to zoom in between year 9 and 10, it shows the following (not sure if this is a different issue, reported by arjun):

![image](https://user-images.githubusercontent.com/1334004/77369518-34844780-6d35-11ea-829a-2d622f02484d.png)

CC: @Luke-Sikina

**Comment by alisman** [comment]
Fixed in Timeline 2.0
