### ISSUE TITLE
manually generate example data for one patient in new resource format

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#7331]
- [x] generate sample input files for [paitent](https://www.cbioportal.org/patient/summary?caseId=TCGA-BK-A0CC&studyId=ucec_tcga_pub) in the current resource format (including the pathology report and tissue image.)

related pathology report URL logic in frontend: https://github.com/cBioPortal/cbioportal-frontend/blob/6493a961cb87af634c07609e4a3974f42ad77547/src/pages/patientView/clinicalInformation/PatientViewPageStore.ts#L442-L488

tissue image URL logic: `https://cancer.digitalslidearchive.org/index.html?patientId=?`

**resource definition data**
`RESOURCE_ID`: PATHOLOGY_REPORT
`DISPLAY_NAME`: Pathology Report
`DESCRIPTION`: The pathology report for the sample
`TYPE`: SAMPLE
`OPEN_BY_DEFAULT`: TRUE
`PRIORITY`: 1

`RESOURCE_ID`: TISSUE_IMAGE
`DISPLAY_NAME`: Tissue Image
`DESCRIPTION`: The tissue image for the patient
`TYPE`: PATIENT
`OPEN_BY_DEFAULT`: TRUE
`PRIORITY`: 1

**Comment by jjgao** [comment]
Pathology slides or pathology reports?

**Comment by dippindots** [comment]
@jjgao Should be pathology report, @inodb @adamabeshouse I also add another resource definition data for the tissue image, could you take a look again?

**Comment by inodb** [comment]
@dippindots looks good to me!

**Comment by adamabeshouse** [comment]
@dippindots looks good!
