### ISSUE TITLE
Timeline zoom style adjustments

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7332]
- [x] Similar to the “Click + drag to zoom” message, there should be a message that reads “Click + drag to pan” after zooming
- [x] “Zoom out” should look like a button. And if we don’t offer +/- zoom buttons, maybe we should call the button “Reset zoom”?
- [x] Can we allow zooming directly on the timeline too (the actual time axis)? Panning works there, but zooming does not. (this might be tricky, if so we can move it to a separate issue)
- [x] Do we need to put the message and buttons into a different location so that they don’t overlap any data? See screenshot

![image (13)](https://user-images.githubusercontent.com/1334004/78171110-f9170680-7421-11ea-8f4c-30bc6f96fc46.png)

**Comment by Luke-Sikina** [comment]
All fixes in this PR for clinical repo:
https://github.com/cBioPortal/clinical-timeline/pull/128/files
