### ISSUE TITLE
Support for mutation background 

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#734]
cBioPortal currently doesn't have a way of storing information that a particular position was found to be not mutated or equal to reference. When there is no row in mutation table for a particular gene we don't know whether it's because there was no mutation or because it wasn't sequenced.

More generally it would be useful to store information if a sample was sequenced using a gene panel or with limited coverage. Particularly for multi center collaborations - different labs can use different gene panels, whole exome, whole genome sequencing. When querying a set of genes it would be useful to limit samples only to those which had this set of genes sequenced.

**Comment by jjgao** [comment]
We try to solve this by recording the gene panel info with pull https://github.com/cBioPortal/cbioportal/pull/254.

**Comment by jjgao** [comment]
#426

**Comment by pieterlukasse** [comment]
@j-hudecek is this solved now? Gene panel functionality seems to cover this.
