### ISSUE TITLE
Study identifier with / passes import but breaks study

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#7342]
Study with study identifier containing a '/' (forward slash) character passes validation and import successfully but patient view is inaccessible as the character is not escaped properly. For example for study identifier ``1/2`` the frontend sends requests to ``https://server/api/studies/1/2`` which return 404.

**Comment by inodb** [comment]
@j-hudecek thanks for reporting! I think slashes might be tricky in the study id. I imagine it can cause issues in other parts of the code (e.g. API & other parts of url navigation). Do you think the validator should throw an error when it finds a slash in the name? This prolly also goes for sample names

**Comment by j-hudecek** [comment]
Why not both?

**Comment by inodb** [comment]
![image](https://user-images.githubusercontent.com/1334004/78034656-00f97c80-7336-11ea-8677-f1daafa49f8e.png)

**Comment by jjgao** [comment]
@j-hudecek would you help send a pull request on this? :)
