### ISSUE TITLE
cannot download generic assay (treatment response) data on download tab

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#7354]
Currently, we cannot download generic assay data on the download tab since it's using the generic assay endpoints.

Discussion:
1. The data can be downloaded on the oncoprint tab as Heatmap data, should we also support download on the download tab?
2. If we should support download on the download tab, should we download all entities?

**Comment by dippindots** [comment]
Hi @jjgao, this ticket is created since we got this question from a user: https://groups.google.com/d/msgid/cbioportal/CABbxrZNEHNAqPkMStFyENK8R3znq_%3DBYV65J9Jm8Q41S%3DL4fXg%40mail.gmail.com.

Could you give me some comments about the two questions in the description? Thanks!

I replied Mireia directly earlier but it seems like that email will not be posted on google group automatically. So I paste it here:

Email:
Hi Mireia,

Sorry about the inconvenience, this is a bug for TREATMENT_RESPONSE data, those data are not supported to be downloaded on the download tab now.
I created an issue for you to track the status of this bug: https://github.com/cBioPortal/cbioportal/issues/7354

As a workaround, you can download treatment response data on oncoprint tab:
1. select a treatment profile
![image](https://user-images.githubusercontent.com/15748980/78591923-33154d80-7812-11ea-93c4-034c4f5e2961.png)

2. select treatments (you can select "Select all" if you want to download data for all treatments)
![image](https://user-images.githubusercontent.com/15748980/78591955-3dcfe280-7812-11ea-8f7c-e65386ea43d7.png)

3. select "Add Treatment Responses to Heatmap"
![image](https://user-images.githubusercontent.com/15748980/78591971-44f6f080-7812-11ea-8fae-d36d1d503a6c.png)

4. you should see new tracks on oncoprint, then choose download as "Tabular"
![image](https://user-images.githubusercontent.com/15748980/78591990-4d4f2b80-7812-11ea-90d2-e34034a6581d.png)

I wish this would help!
Please let me know if you have any questions, thanks for reaching out!

Best,
Gaofei

**Comment by jjgao** [comment]
Thanks, @jjgao . I replied to the email and suggested that they can use the Plots tab to download the data. Please feel free to add your answer too.
