### ISSUE TITLE
External service installation and configuration 

### ISSUE THREAD

**Issue by Mohammedhusen** [cBioPortal/cbioportal#7362]
Hi Team,

Could you help us on installing and configuring below service with cbio.

OncoKB
CIVIC
Genome Nexus
G2S
If you have any document please share that would be very helpful.
Thank you.

**Comment by jjgao** [comment]
@Mohammedhusen would you please send an email to cbioportal@googlegroups.com? Please also elaborate how you are installing cBioPortal, e.g. whether docker is used? And which step are you stuck in.. Thanks.
