### ISSUE TITLE
Treatment data missing in download tab

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7364]
@dippindots the following came from a user.  See @pvannierop's analysis below.  

**User:**
"I am Mireia Palomar, PhD student at Karolinska Institutet. I have performed a query search in cbioportal selecting the dataset “Cancer Cell Line Encyclopedia (Broad, 2019)” and query by gene: TP53.

When I go to plots I can plot mutation type vs treatment response for one drug. I would like to download all the IC50 values from all the compounds, not only one. So I go to Download tab and download the “Treatment response: IC50” in both Tab delim text and Matrix transpose, but the files don’t contain any IC50 values, only NA values (check screenshot attached). So, where could I find the IC50 values for all drugs?"

**Pim:**
The cause of this is that code in ResultsViewPageStore.ts ( nonSelectedDownloadableMolecularData method) only considers gene-linked data (which Generic Assay data are not). This is worth creating an issue for on GitHub.

**Comment by jjgao** [comment]
duplicate with #7363
