### ISSUE TITLE
Survival data migration steps (Target June 4 release)

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#7370]
To migrate survival data from their custom vocabulary to "0 / 1", we should do the following steps:

**all pull requests should go to RC**
1. merge database migration script (DO NOT DELETE null data)
2. merge `survival data migration script`
3. merge backend pr (new importer and new data validator)
4. update frontend to uses "0: / 1:".
5. update RedCAP library / pipeline used internally.

**RELEASING** 
**for msk:**

- [x] database migration on copied database (run on a copy of `cgds_gdac`)
- [x] check and validate data before real database migration
- [x] survival data files migration ([PR 1129](https://github.com/cBioPortal/datahub/pull/1129)) (after file migration, check data files for correctness)
- [x] create PR for survival data file [migration tool](https://github.com/cBioPortal/cbioportal/pull/7468/files)
- [x] database migration - run migration script on all database.  Migration script can be found in the [3.4.0 branch](https://github.com/cBioPortal/cbioportal/tree/release-3.4.0)
- [x] build/deploy new importers.
- [x] re-enable import scripts in crontab, and notify curators that triage is running again

**for others:**
1. database migration (run migration script on all database)
2. if necessary (have other survival data), survival data files migration

**Comment by jjgao** [comment]
@dippindots please modify this based on the new requirement. Thanks.

**Comment by dippindots** [comment]
@jjgao Updated! @n1zea144 Can I get your opinions on these procedures?

**Comment by jjgao** [comment]
@dippindots is this still up to date?

**Comment by sheridancbio** [comment]
This card is part of the pipelines team scrum board. For sprint progress tracking purposes, we will keep the card open, but in the "Done" pipeline on the ZenHub planning board. It will be closed at the end of of he current sprint (2020_06_10)
