### ISSUE TITLE
OQL issue - "EGFR: Driver" returns gains

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7376]
It looks like gains are returned as drivers: https://bit.ly/3aXqStZ

![image](https://user-images.githubusercontent.com/840895/78946415-a88e5180-7a90-11ea-85d7-bee27fa89a35.png)

There are two issues:

1. I don't think we should return gains if we don't specifically ask for them in the oql.
2. Not sure if we should annotate GAIN and HETLOSS.

@schultzn thoughts?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao I found a bug which I think may be related: #7388. This would mean that the bug was introduced after the screenshot was made, which may help in hunting it down.

**Comment by adamabeshouse** [comment]
@jjgao @schultzn the DRIVER command just returns anything annotated as a driver, which in this case apparently these gains and hetlosses are oncokb drivers.

to just get what you're looking for, you could do
EGFR: AMP_DRIVER HOMDEL_DRIVER

**Comment by jjgao** [comment]
@adamabeshouse since `EGFR` only queries for AMP and HOMDEL, I think `EGFR: DRIVER` should do the same thing...
