### ISSUE TITLE
My Cancer Genome annotation have errors which may slow down the mutation/cna APIs

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#738]
Errors:
Cannot process KRAS http://www.mycancergenome.org/content/disease/lung-cancer/kras/

**Comment by jjgao** [comment]
Don't understand why it's slow down the mutation/cna APIs? 

My Cancer Genome annotation is only grab once.

**Comment by zhx828** [comment]
Yeah, I figured it out. Only the first time will slow down the API
