### ISSUE TITLE
Overlap in groups reported where there should be none (news page example)

### ISSUE THREAD

**Issue by Sjoerd-van-Hagen** [cBioPortal/cbioportal#7388]
I clicked the link in the latest news item: Extended the Comparison tab to support the comparison of altered samples per gene or alteration.

It gave me a result different from the screenshot in the sense that it reports overlapping samples while there should be none. This is the [link](https://www.cbioportal.org/results/comparison?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=msk_impact_2017&case_set_id=msk_impact_2017_Non-Small_Cell_Lung_Cancer&comparison_createdGroupsSessionId=5e8a2d4ae4b0ff7ef5fdd7d0&comparison_selectedGroups=%5B%22EGFR%3A%20AMP%20%26%20MUT%22%2C%22EGFR%3A%20MUT%20only%22%2C%22EGFR%3A%20AMP%20only%22%5D&comparison_subtab=survival&data_priority=0&gene_list=EGFR%253AAMP%250AEGFR%253AMUT_DRIVER&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&profileFilter=0&tab_index=tab_visualize&comparison_overlapStrategy=Include)

I suspect this may be related to this issue reported by @jjgao: #7376

**Comment by jjgao** [comment]
It was b/c the overlapping patients were selected somehow. If you open the original link in the news, it should still the same.

![image](https://user-images.githubusercontent.com/840895/79257873-4353ab00-7e58-11ea-8e7c-41062b161885.png)

**Comment by Sjoerd-van-Hagen** [comment]
But the groups are supposed to be disjunct is what I mean.

**Comment by jjgao** [comment]
In this case, there are no overlapping **samples** between the groups, but some patients have multiple samples that belonged to different groups.

**Comment by Sjoerd-van-Hagen** [comment]
I see. Still very confusing I think.

**Comment by jjgao** [comment]
There are 10 patients who had multiple samples sequenced. Each of them has at least one sample with both AMP & MUT EGFR and one sample with MUT EGFR only. 

![image](https://user-images.githubusercontent.com/840895/79764426-5997b600-82f3-11ea-84e2-f55a3407edc5.png)

If you choose to "include overlapping patients and samples" (the upright dropdown menu), these 10 patients should be put into this own group for survival analysis...

**Comment by Sjoerd-van-Hagen** [comment]
Yes, I understand. I mean confusing for the user.
