### ISSUE TITLE
Oncokb token is not accessible if deploy via docker 

### ISSUE THREAD

**Issue by leexgh** [cBioPortal/cbioportal#7395]
Similar to this issue: https://groups.google.com/forum/#!topic/cbioportal/H-5G97YFpX4

Properties are set to:
`show.oncokb=true`
`oncokb.token=real token here`
Got 403 error if deploy with docker:
![image](https://user-images.githubusercontent.com/16869603/79245604-5198cb80-7e46-11ea-8c3e-178dbb592fc5.png)

According to @zhx828, using local tomcat app is fine.

**Comment by inodb** [comment]
@leexgh for the production portal we provide it like this (with `-D` flag to java): https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/blob/master/cbioportal/cbioportal_spring_boot.yaml#L125. Is it only not working when using docker and the token is provided in a `portal.properties` file?

**Comment by leexgh** [comment]
@inodb yes, but I didn't try other approaches

**Comment by inodb** [comment]
@leexgh 👌 we should def fix this one, because we officially recommend people to deploy with docker and using a portal.properties file

**Comment by inodb** [comment]
@leexgh i do wonder if it this is specific to docker? Maybe it doesn't read the variable from `portal.properties` when supplied dynamically at runtime using `PORTAL_HOME` variable. Note that the properties file can be supplied at compile time and dynamically at runtime using `PORTAL_HOME` variable. The latter is what we do in the docker approach. But for production on internal servers we compile a war with a portal.properties file and then deploy it to tomcat. So maybe it's the dynamically reading of portal.properties that is not working

**Comment by leexgh** [comment]
@inodb other variables in `portal.properties` are accessible, for example `show.oncokb` is always fine. I tried to set `show.oncokb=false` and the error was gone, so for me it seems like only `oncokb.token` is not read properly.
