### ISSUE TITLE
mRNA tab in Comparison does not include the query gene

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#7402]
https://bit.ly/3cmtJg4

TCGA lung adenocarcinoma 2014 study
Query: RIT1: MUT AMP
Comparison: mRNA

RIT1 does not show up in the mRNA gene list - but it probably should (and used to). 

Report from a user:
Recently I was poking around on cBioPortal and happened to try to replicate an analysis I did for one of my post-docs. We noticed something funny and it might be a bug. 

I was demo-ing the “enrichments” tab, which I see is now called “Comparison.” Specifically, I was pulling differentially expressed mRNA from an “altered” and “unaltered” group of samples. What was weird is that the mRNA genes provided included all genes EXCEPT the gene in my oncoquery. 

Literally - the matrix I downloaded yesterday was one row shorter than the matrix I downloaded in September, and the only difference was that my gene in the query was missing.

**Comment by adamabeshouse** [comment]
Is that not how we want it? The cooccurence would be 100% by definition, no?

**Comment by kalletlak** [comment]
@schultzn @jjgao we filter out the queried genes from the enrichment data tables. And looks like nothing was updated recently https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/pages/resultsView/ResultsViewPageStoreUtils.ts#L762

**Comment by schultzn** [comment]
Not if you run a query for say mutations or copy-number changes. For example, you run a query for EGFR mutations: The comparison between EGFR mutant and non-mutant should include EGFR, as you may want to know whether the expression levels of EGFR itself are different depending on mutations status.
