### ISSUE TITLE
Clean up property parsing in oncokb proxy controller

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7404]
The current implementation copied some methods from GlobalProperties to parse properties in this order (see https://github.com/cBioPortal/cbioportal/pull/7400):

1. -D parameters
2. PORTAL_HOME/portal.properties
3. compile time portal.properties (i.e. properties.EXAMPLE when none is provided as is the case for the docker image)
4. default values defined in GlobalProperties.java or with spring ${variableName:default}

Ideally we could do all this using Spring configuration and not have to use `GlobalProperties` methods, something like:

https://github.com/cBioPortal/cbioportal/blob/a7186f5a37e0f7067b03f831ad7fc788ffda4b0d/web/src/main/resources/applicationContext-proxy.xml#L18-L27

**Comment by jjgao** [comment]
@inodb @zhx828 do we need to keep this open?
