### ISSUE TITLE
Timeline download

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7406]
This PR introduced TSV download of timeline data: https://github.com/cBioPortal/cbioportal-frontend/pull/2950. But currently it does not output the data inside the tooltip tables (only name of the tracks). It would be good if the outputted TSV was in the same format as the input for cBioPortal: https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#timeline-data.

See for example: https://www.cbioportal.org/patient?studyId=lgg_ucsf_2014&caseId=P04. The data in the tooltip tables is not included in the download currently

Related: https://github.com/cBioPortal/cbioportal/issues/1783

**Comment by jjgao** [comment]
@alisman I added this to the timeline refactoring epic.
