### ISSUE TITLE
NCBI gene link is no longer available

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#741]
The link we have is http://www.ncbi.nlm.nih.gov/gene/(gene) (e.g., http://www.ncbi.nlm.nih.gov/gene/BRAF) but NCBI only reference the page with gene ID, for above example, it changed to http://www.ncbi.nlm.nih.gov/gene/673

We may be able to link to their search page (e.g., http://www.ncbi.nlm.nih.gov/gene/?term=BRAF)

**Comment by jjgao** [comment]
On which page? On patient view, we link with entrez gene id.

**Comment by zhx828** [comment]
Ah, I think I changed it to hugo symbol instead of entrez gene id in OncoKB connector. I will fix that.
