### ISSUE TITLE
Evaluate upgrading to new Java version

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7412]
The VS code java plugin is starting to require java 11 jdk as minimum. Maybe it’s time to upgrade? Eclipse on which the java vscode plugin depends is going to require java 11 from September

Might be good to move over genome nexus first. Most of our production deploys there are already based on docker for which it will be trivial to switch

**Comment by jjgao** [comment]
Maybe a good topic for the engineering meeting?
