### ISSUE TITLE
CNSegments on study page: for large study, data doesn't render until user selects a chromosome

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7416]
https://www.cbioportal.org/study/cnSegments?id=msk_impact_2017

<img width="1401" alt="cn_segments_whole_genome" src="https://user-images.githubusercontent.com/3604198/79795735-62ec4700-8322-11ea-82b2-350e73f8a24c.png">

This bug also exists in the results page for the `Whole Genome` view for large studies.

**Comment by onursumer** [comment]
Apparently as of IGV [version 2.2.16](https://github.com/igvteam/igv.js/releases/tag/v2.2.16)

> Display of whole genome view is now limited to tracks with < 100,000 features.

A quick debug shows that the length of the features array for the example above is `628,174` which is way over this threshold.

**Comment by onursumer** [comment]
Seems like this limit has been increased to `500,000` in a later release, but it is still hardcoded:
https://github.com/igvteam/igv.js/blob/2962eec3a3d4f7681f5cd0736574a1dfeb82d746/js/feature/featureSource.js#L155
