### ISSUE TITLE
error in specific group comparison with GENIE data

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7418]
User reported issue: https://groups.google.com/forum/#!topic/cbioportal/3ECW08wuD0A

Error appears on Mutations tab for this comparison session:
https://genie.cbioportal.org/comparison/mutations?sessionId=5e9e305ae4b0ff7ef5fe074a

![image](https://user-images.githubusercontent.com/10508276/79866597-041ee000-83ab-11ea-87c9-ce0466152296.png)

**Comment by onursumer** [comment]
Exception seems to happen in this line:
https://github.com/cBioPortal/cbioportal/blob/dc519c6addba3cb783406fe6eda150fe8ca72c8a/service/src/main/java/org/cbioportal/service/util/AlterationEnrichmentUtil.java#L115

**Comment by kalletlak** [comment]
@tmazor @onursumer looks like an issue similar to https://github.com/cBioPortal/cbioportal/issues/7274. Altered cases is more than profiled cases for a subset of group

**Comment by jjgao** [comment]
@kalletlak would it be possible to skip the genes that are not part of the gene panel for comparison analysis?

**Comment by alisman** [comment]
@jjgao they would be skipped by the service?  I.e. it would just ignore genes that weren't part of panel as opposite to erroring as now?

**Comment by jjgao** [comment]
@alisman @kalletlak let's simplify this. Maybe we can capture the error [here](https://github.com/cBioPortal/cbioportal/blob/master/service/src/main/java/org/cbioportal/service/util/AlterationEnrichmentUtil.java#L115) and return Double.NaN?

**Comment by kalletlak** [comment]
@jjgao you mean to set pValue = 1 for this scenario?

**Comment by jjgao** [comment]
@kalletlak I am wondering if it's possible to set it to NA or empty/null? If not, it's ok to set it to 1.

**Comment by jjgao** [comment]
Alternatively, if the above the hard, we could just ignore the gene when there is an error when calculating p-value.
