### ISSUE TITLE
GRch38/37 combined warnings + info

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7422]
- [ ] on query page when selecting multiple studies with different ref genome show warning
- [ ] on mutations tab show reference genome column
- [ ] on results page at the top show warning banner that studies with diff ref genome were combined

Maybe later b/c complicated:
- [ ] on study view show pie chart reference genome. Show count per sample having reference genome of grch38 and grch37
- [ ] how to handle CN segments tab on study view?

**Comment by SRodenburg** [comment]
Hi @inodb 
Do I understand from this thread correctly that multiple genome support is underway?
I know it's already implemented in the backend. How is the frontend development coming along?  One of the problems was also that Genome Nexus only supports a single genome per instance. How is that dealt with?
