### ISSUE TITLE
add cytoband in the co-expression table

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#743]
Also add the Query gene itself to the table with corr=1 so that its cytoband can be displayed as well.

Here is the original user request:

"For co-expression, could you list chromosome (and position) of the query gene and co-expressed genes? Nearly all are just nearby genes. Bonus for making it sortable or filterable (to exclude nearby genes)."

**Comment by jjgao** [comment]
@yichaoS update?

**Comment by yichaoS** [comment]
https://github.com/cBioPortal/cbioportal/pull/1036

**Comment by yichaoS** [comment]
https://github.com/cBioPortal/cbioportal/pull/1036
