### ISSUE TITLE
option to exclude any samples that are not profiled in all query genes

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7441]
This option can be added to the global setting.

based on discuss in https://github.com/cBioPortal/cbioportal/issues/6051

- [ ] Add an option to "Exclude samples that are not profiled for one or more genes in any of the profiles"
- [ ] The option should be NOT selected by default
- [ ] This option should be implemented for multi-study query too
![image](https://user-images.githubusercontent.com/840895/80540759-ea1b6980-8977-11ea-87d5-8f27d5d8cb2e.png)

**Comment by adamabeshouse** [comment]
@jjgao this applies to every tab?

**Comment by adamabeshouse** [comment]
@jjgao which molecular profiles do we consider in this computation?

**Comment by jjgao** [comment]
> @jjgao this applies to every tab?

Yes. 

> @jjgao which molecular profiles do we consider in this computation?

All queried profiles.

Also, in addition to the global parameter, how about adding the option to the query page as well? This way, samples will be properly selected based on the query profiles and genes. (We can even remove the complex logic in the frontend for selecting case lists based on profiles and always select all samples by default). @schultzn @tmazor @cBioPortal/product 

![image](https://user-images.githubusercontent.com/840895/80423207-9c3a2f00-88ad-11ea-9c15-1e2009bcc1ba.png)

**Comment by jjgao** [comment]
More thoughts - not sure if it's too complex:

- maybe by default, the option is `Include only samples with data in all selected profiles above` (**selected** by default). 
- When we detect there are gene panels in the selected profiles, we add another option `Include only samples that are profiled for all genes below in all selected profiles (some profiles are based on gene panels)` (**unselected** by default)

**Comment by jjgao** [comment]
Here is a new proposal after discussion with @schultzn 

- [ ] Let's add an option to "include only samples with data in all selected profiles."
  - The option should be selected by default
  - When the option is true/selected AND at least one sample is excluded, add a message "xx samples are excluded due to lack of data in at least one selected profile."
  - For existing sessions that are missing this option, we should treat it as false
![image](https://user-images.githubusercontent.com/840895/80539531-a889bf00-8975-11ea-8328-4356f8aaa246.png)
- [ ] Add an option to "Exclude samples that are not profiled for one or more genes in any of the profiles" (unselected by default)
![image](https://user-images.githubusercontent.com/840895/80540759-ea1b6980-8977-11ea-87d5-8f27d5d8cb2e.png)

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao are you sure it is a good idea to set this to true on default? As I see it, a common use case is to look at alteration frequencies for genes. If I would put something like this in my OQL:
TP53 : MUT
MYC
and the box is ticked I am not getting mutation frequency for TP53 across the cohort, but across the samples for which MYC also has CNA. This could lead to problems if there is a bias in the samples that are profiled, for instance when based on a measurement the decision is made to run a larger panel.

I am also wondering why you would add a checkbox and not an option to the dropdown menu, and why this option is duplicated in the filter menu while the others are not. 

In any case, the text in the filter menu should read "... any of the _selected_ profiles

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen Thanks for the comments. These are two different options. 

The first checkbox in the query page is for selecting samples just based on whether a sample is in all selected profiles. This will address inaccurate frequencies when one selects a case list that contains samples that are not profiled in some profiles.

The second checkbox also considers whether a gene is profiled (e.g. when a profile is based on gene panel). By default, it is deselected as proposed above. This is to address the use case that one would like to include samples that are "completely" profiled for the query genes as suggested in https://github.com/cBioPortal/cbioportal/issues/6051.

**Comment by jjgao** [comment]
I have created another ticket to discuss the option in the query page. For this ticket, let's focus on the one in the global setting (updated in the description) to address the issue @tmazor brought up.

**Comment by adamabeshouse** [comment]
@jjgao @Sjoerd-van-Hagen @inodb how do we handle patient filtering? the normal way we do it is include a patient which has at least one sample included, but given the way this filtering works I was wondering if we should instead only include a patient who has all samples included.
