### ISSUE TITLE
Bug in ad and ldap Authentication

### ISSUE THREAD

**Issue by gatksun** [cBioPortal/cbioportal#7447]
Occasionally, I found the below bug from my local instance.
In my local instance, I used first ad ac authentication, now changed to ldap.
Both ad and ldap are based on our active directory.
Recently, I found its authentication with a deadly bug. When I log in, my cbioportal does not care of any password either by ad or ldap.
That means anyone can log in as long as the one know any username with anything as password.
I do not know if this bug exists in the other authentication. This bug exists cbioportal 3.1.1,3.2.14.
Please test your cbioportal using all possible authentications. One thing confirmed, no this issue in our active directory by our own website based on .asp or non java security-spring.

**Comment by jjgao** [comment]
Please contact cbioportal@googlegroups.com
