### ISSUE TITLE
Incorrect study link in comparison page

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#7450]
<img width="663" alt="Screen Shot 2020-04-28 at 9 54 23 AM" src="https://user-images.githubusercontent.com/12956870/80495855-7016c080-8936-11ea-9feb-360d2e06ab30.png">

On clicking `Multiple studies` link, it opens https://www.cbioportal.org/comparison/study?id=prad_mskcc_2014,prad_tcga,prad_cpcg_2017 instead of https://www.cbioportal.org/study?id=prad_mskcc_2014,prad_tcga,prad_cpcg_2017

**Comment by jjgao** [comment]
Maybe fix at the same time: https://github.com/cBioPortal/cbioportal/issues/7446

**Comment by adamabeshouse** [comment]
@kalletlak I can't reproduce this
