### ISSUE TITLE
Investigate if data export from portal charts can be generalized

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7452]
And if not, start epic and specify list of charts which are missing download

**Comment by jjgao** [comment]
related: https://github.com/cBioPortal/cbioportal/issues/5314

**Comment by jjgao** [comment]
a related user question: https://groups.google.com/forum/#!topic/cbioportal/oZBLsQQItQ8

**Comment by jjgao** [comment]
another one: https://github.com/cBioPortal/cbioportal/issues/7486

**Comment by alisman** [comment]
This spreadsheet lists all charts with available export options:
https://docs.google.com/spreadsheets/d/13wh0QHgHm5uFAW0WPYYXZubiYXu4Y9g7EubdWCzCDL8/edit#gid=0

**Comment by alisman** [comment]
Epic started: #7519
