### ISSUE TITLE
upgrade node version to 12.16 LTS

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7465]
We are still at 8 in the frontend repo (https://github.com/cbioportal/cbioportal-frontend) and some new things aren't compatible anymore

Let's upgrade:

- [ ] package.json
- [ ] jitpack (pom.xml)
- [ ] netlify (netlify.toml)
- [ ] circleci (.circleci/)
- [ ] Github actions? (.github/)

Not sure if im missing anything (CC @alisman )

**Comment by nr23730** [comment]
How about updating yarn to 1.22.4?

**Comment by inodb** [comment]
Thanks for the suggestion @nr23730! Happened to run into some issue with yarn today and decided to upgrade: https://github.com/cBioPortal/cbioportal-frontend/pull/3207

**Comment by jjgao** [comment]
I have moved this to to-do. Please move it back if we need to work on it soon.
