### ISSUE TITLE
download.cbioportal.org stucks when downloading a dataset

### ISSUE THREAD

**Issue by Genarito** [cBioPortal/cbioportal#7477]
Hi!

I'm developing a tool to automatize the downloading of some of your datasets to work with them. But I've realised that sometimes the download of the datasets gets stucked. I though it was a problem of my code, but then when tried downloading it from Chrome it stucked again.

Is it a server downtime problem? Server configuration? Was there any similar report in the past?

Thanks in advance and sorry about my English

**Comment by jjgao** [comment]
@inodb do you know if we have solved this?

**Comment by inodb** [comment]
@jjgao we should discuss. For `cBioPortalData` we set up a mirror on S3 for faster downloads. We could move download.cbioportal.org over completely, but there is a higher cost b/c you pay for hosting as well as outgoing traffic. I haven't looked yet at improving/fixing download speeds on our internal server. That would be another option

**Comment by jjgao** [comment]
@inodb maybe we can find a way to allow downloading from datahub directly? e.g. using https://downgit.github.io

https://downgit.github.io/#/home?url=https://github.com/cBioPortal/datahub/tree/master/public/acbc_mskcc_2015

**Comment by inodb** [comment]
We discussed this, need to get some estimation of costs and development plan for switching to S3

**Comment by jjgao** [comment]
@inodb I am wondering downgit has any other downsides besides the current R client cannot download from it directly?

**Comment by inodb** [comment]
@Genarito this should be fixed now

**Comment by Genarito** [comment]
Cool! Thank you so much!
