### ISSUE TITLE
OncoPrint: Downloaded MutationsSpectrum data is [object]

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7478]
Can we add the data? One option would be to create 6 rows for the data.

**Comment by adamabeshouse** [comment]
How about the column looking like this:
column header = (C>A)(C>G)(C>T)(T>A)(T>C)(T>G)
data for a row = (1)(0)(0)(2)(5)(5) 

This problem is coming up also in downloading oncoprint data into oncoprinter mode - it would be nice to implement stacked bar chart clinical tracks in oncoprinter

**Comment by jjgao** [comment]
@adamabeshouse I think it may be better to create 6 columns so that one can sort by them.

**Comment by adamabeshouse** [comment]
what should the column headers be? Mutation_Spectrum_A>C ? @jjgao
