### ISSUE TITLE
RPPA data missing for many phospho antibodies

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#748]
- [x] convert the files from MDA (see below) into Firehose format.
 - [x] add them to tcga-override directory.
 - [ ] modify importer code to allow conversion of one data type (JJ).

**Comment by jjgao** [comment]
[RPPA antibody List for Pan Can January2016.txt](https://github.com/cBioPortal/cbioportal/files/101418/RPPA.antibody.List.for.Pan.Can.January2016.txt)

[TCGA_RPPA_diseases_twoOrMoreBatches.zip](https://github.com/cBioPortal/cbioportal/files/101420/TCGA_RPPA_diseases_twoOrMoreBatches.zip)

**Comment by jjgao** [comment]
@ritikakundra could you help me on this? We can discuss in person.

**Comment by ritikakundra** [comment]
@jjgao: Sure, let me know when

**Comment by ritikakundra** [comment]
[list.xlsx](https://github.com/cBioPortal/cbioportal/files/149078/list.xlsx)

**Comment by jjgao** [comment]
@ritikakundra: I think there is a line shift on row 15. Could you fix that?

**Comment by ritikakundra** [comment]
In list.xlsx?

**Comment by jjgao** [comment]
yes

**Comment by ritikakundra** [comment]
[list (2).txt](https://github.com/cBioPortal/cbioportal/files/151528/list.2.txt)

Made a tab file. cant find the line shift in excel file. maybe this will help

**Comment by ritikakundra** [comment]
Made a tab file. cant find the line shift in excel file. maybe this will help
[list.2.txt](https://github.com/cBioPortal/cbioportal/files/151535/list.2.txt)

**Comment by jjgao** [comment]
I think there is a mismatch between genes and antibodies starting from line 15. ATM should be on line 16.

![image](https://cloud.githubusercontent.com/assets/840895/13405155/1684e83e-deeb-11e5-860f-c81199464469.png)

**Comment by ritikakundra** [comment]
Oh thats because they are not mapped to column A. Some just happened to align. These are just enlisted directly from files.

**Comment by ritikakundra** [comment]
[MAPPED_LIST.txt](https://github.com/cBioPortal/cbioportal/files/151693/MAPPED_LIST.txt)
Here is the mapped list. Not all can be mapped

**Comment by jjgao** [comment]
Thanks, @ritikakundra! Could you do one more analysis to find out which antibodies have no data in all files? You can concat all the files together and find if all are NA.

```
cat TCGA-RPPA*.txt >> out
```

**Comment by ritikakundra** [comment]
[RESULT.xlsx](https://github.com/cBioPortal/cbioportal/files/153810/RESULT.xlsx)


The output of cat and numbers in the first sheet

**Comment by jjgao** [comment]
Great! Thanks. Could you remove the all-NA antibodies from MAPPED_LIST.txt?

**Comment by ritikakundra** [comment]
[MAPPED_LIST_UPDATED.txt](https://github.com/cBioPortal/cbioportal/files/155504/MAPPED_LIST_UPDATED.txt)

Updated list with 215 all-NA antibodies removed. I kept the ones which were NA in a few tumor types but had values in other tumor types

**Comment by ritikakundra** [comment]
[data_rppa_brca.txt](https://github.com/cBioPortal/cbioportal/files/161637/data_rppa_brca.txt)
[data_rppa_coadread.txt](https://github.com/cBioPortal/cbioportal/files/161638/data_rppa_coadread.txt)
[data_rppa_crc.txt](https://github.com/cBioPortal/cbioportal/files/161639/data_rppa_crc.txt)
[data_rppa_gbm.txt](https://github.com/cBioPortal/cbioportal/files/161640/data_rppa_gbm.txt)
[data_rppa_blca.txt](https://github.com/cBioPortal/cbioportal/files/161641/data_rppa_blca.txt)

**Comment by ritikakundra** [comment]
[data_rppa_hnsc.txt](https://github.com/cBioPortal/cbioportal/files/161648/data_rppa_hnsc.txt)
[data_rppa_kirc.txt](https://github.com/cBioPortal/cbioportal/files/161650/data_rppa_kirc.txt)
[data_rppa_kirp.txt](https://github.com/cBioPortal/cbioportal/files/161651/data_rppa_kirp.txt)

**Comment by jjgao** [comment]
They look good. Thanks Ritika! Please add them to the overrides.
-jj
