### ISSUE TITLE
p-value for survival analysis when there are 3 or more groups

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7484]
Currently, p-value is only provided when comparing 2 groups.

**Comment by jjgao** [comment]
@kalletlak maybe we can add a matrix of pairwise p-values?

**Comment by jjgao** [comment]
@kalletlak I am wondering if we can give another try? It looks like Xena can calculate p-value for 3 or more groups...

https://xena.ucsc.edu/kaplan-survival-analysis/
https://github.com/ucscXena/kaplan-meier/blob/master/js/index.js

**Comment by adamabeshouse** [comment]
@jjgao so we just want one single p-value that represents the null hypothesis that they all have the same survival? isnt that kind of vague?

**Comment by jjgao** [comment]
@adamabeshouse It seems typical (null hypothesis that they all have the same survival) when testing 3 or more groups, e.g. https://www.graphpad.com/guides/prism/7/statistics/comparing_three_or_more_groups.htm. Maybe you can find out how others (e.g. in R) are doing this?

I think one option we have is to report an overall p value that represents the null hypothesis that they all have the same survival, but also calculate the pair-wised p values and display them on the page.

**Comment by adamabeshouse** [comment]
@jjgao okay, I guess now that I think about it more, if you're doing a group comparison based on a clinical attribute, then it does still make sense because its like you're asking "does values of this clinical attribute relate to survival?" when it comes to the pairwise P-values, Im no longer sure I see the utility. what do you think?

**Comment by jjgao** [comment]
@adamabeshouse agreed - "does values of this clinical attribute relate to survival?"

I think the pair-wise p-values are still useful to include for identifying significantly different pairs. Maybe we can include a pair-wise table of p-values below the km plot?

**Comment by adamabeshouse** [comment]
@jjgao sounds good. q-values?

**Comment by jjgao** [comment]
@adamabeshouse yes, q-value should be added as part of https://github.com/cBioPortal/cbioportal/issues/7805.

**Comment by adamabeshouse** [comment]
ah, I meant qvalues for the pairwise pvalues

**Comment by jjgao** [comment]
@adamabeshouse good question! I think we should add q-value to the pairwise table too, but I am wondering if it would be confusing seeing two sets of q-values... How about let's add the q-values for now and then get some input from biostatisticians?
