### ISSUE TITLE
Alteration Bar Chart Should Have CSV As Export Option

### ISSUE THREAD

**Issue by DarioS** [cBioPortal/cbioportal#7486]
Using the new quick search tool, which is in beta, I searched for CDKN2A and got a bar chart. There's a download icon in the top-right of the plot, but it only has SVG, PNG and PDF options. It would be convenient to be able to get TSV or CSV for import into R and style customisation. Also, with most Plotly plots, it's possible to click on elements of the legend to make those categories excluded or included. My use case is click on Mutation and Fusion to remove them and make the plot copy number centric. Multiple Alterations would no longer be needed in the legend, since Amplification and Deep Deletion are mutually exclusive.

**Comment by DarioS** [comment]
I am still hopeful of seeing this feature added.

**Comment by jjgao** [comment]
@DarioS it was fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/3322. Sorry we forgot to close this one.
