### ISSUE TITLE
"Table 'cbioportal.mutation_event' doesn't exist" by migrate_db.py

### ISSUE THREAD

**Issue by likelet** [cBioPortal/cbioportal#7487]
I tried to deploy cbioportal locally by following the   [Step 4 - Migrate database to latest version](https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker), when  I run the step 4, it returns an error like this: 
`(1146, "Table 'cbioportal.mutation_event' doesn't exist")`
 any suggestions or solutions for this?
Thanks

**Comment by jjgao** [comment]
Please contact cbioportal@googlegroups.com. Please make sure database `cbioportal` exists.

**Comment by likelet** [comment]
Thanks for your reply, the problem has been fixed by the reboot of the machine.
