### ISSUE TITLE
Data Sets page: Change term "Sequenced" and update data update note

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#7489]
The term "Sequenced" should be changed to "Mutations" 

And the data source sentence under the study should be changed:

"Data sets of published studies were curated from literature. Data sets of legacy TCGA studies were downloaded from the Broad Institute Firehose and updated quarterly."

"Data sets of published studies were curated from literature. Data sets of legacy TCGA studies were downloaded from the Broad Institute Firehose, last updated xx/xx/xxxx."

![image](https://user-images.githubusercontent.com/11892704/81680932-ebda3800-9421-11ea-9ae6-016e4d0381dd.png)

**Comment by alisman** [comment]
@schultzn Do you mean the column header "Sequenced"?

![image](https://user-images.githubusercontent.com/186521/82497120-c1d8e380-9abb-11ea-89a6-15294e21445b.png)

This column contains data from study api property "sequencedSampleCount".   I just want to make sure this is appropriate.  Should we change the api property name?

**Comment by schultzn** [comment]
Yes, the name of that column should be “Mutations”.

**Comment by inodb** [comment]
@schultzn we were discussing this at standup, can we remove this part:

```
"Data sets of published studies were curated from literature. Data sets of legacy TCGA studies were downloaded from the Broad Institute Firehose, last updated xx/xx/xxxx."
```

Since this info is already in the description of the respective studies

**Comment by schultzn** [comment]
Sure, that works.
