### ISSUE TITLE
delete "mutation summary"-related code in plots tab

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#7494]
We used to have a "mutation summary" coloring in the plots tab, where if you were plotting data from different genes then you could color points by "mutated in gene 1, mutated in gene 2, mutated in both, mutated in neither." This is obsolete now that plots tab lets you choose which gene to color by, and it seems in the code that this is never used. We should remove all related code.

Tagging everyone who has edited the PlotsTab file - @dippindots @pvannierop @Luke-Sikina @ngocnn1104 @oplantalech @kalletlak  please speak now or forever hold your peace :D

**Comment by Luke-Sikina** [comment]
So the code in question represents a subset of the new feature that you have implemented, and it doesn't work any more? Removing it seems like a good idea to me.

**Comment by adamabeshouse** [comment]
Actually the code in question hasn't been in use since prior to the work I'm currently doing, but I noticed it just now.
