### ISSUE TITLE
Pearson correlation R/p-value not included in data table of co-expression plot

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#7495]
Related to this Google Groups [question](https://groups.google.com/forum/#!topic/cbioportal/dnAdAnD9SRs).

##  Problem
Pearson correlation statistics are shown in the co-expression plot, but are not included in the downloaded data table.

## Possible solutions
- Add the Pearson correlation coefficient and p-value to the data download, or
- Do not show the Pearson correlation in the plot legend if considered unreliable

Now its is just mixed signals on whether or not Pearson is supported/endorsed.

**Comment by jjgao** [comment]
Pearson is not reliable as you mentioned, but it sometimes still useful to look at one plot. I think we will keep the current solution unless more users are asking for it.
