### ISSUE TITLE
3D Protein not displaying

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#75]
![screen shot 2015-06-10 at 11 55 31 am](https://cloud.githubusercontent.com/assets/1334004/8087296/012116e6-0f68-11e5-84ac-5ea24deb2911.png)

**Comment by onursumer** [comment]
Which portal is this? I have tried public, private, and mskcc portals, everything looks fine on those.

**Comment by inodb** [comment]
URL:
https://cbioportal.mskcc.org/index.do?cancer_study_list=pbl_cbe_mellingi_5667_ProvA&cancer_study_id=pbl_cbe_mellingi_5667_ProvA&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=pbl_cbe_mellingi_5667_ProvA_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=pbl_cbe_mellingi_5667_ProvA_cna&data_priority=0&case_set_id=pbl_cbe_mellingi_5667_ProvA_all&case_ids=&gene_set_choice=user-defined-list&gene_list=PIM1&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit
 
Web browser: Explorer (I guess this one is not supported anymore so that might be the issue)
 
Gene: PIM1

**Comment by inodb** [comment]
Closed this because issue can't be reconstructed. Prolly related to using an older version of IE
