### ISSUE TITLE
allow filter by dbsnp column not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7500]

**Comment by onursumer** [comment]
@jjgao dbsnp is a lazy loaded column. I don't think `LazyMobXTable` supports searching for lazy loaded columns.

There two ways we can achieve this:

- We can start fetching the data as soon as user types something. But data related to `MyVariantInfo` columns take really long to fetch, so the search won't be accurate until loading completes. This will probably confuse the user. You can actually see how long it takes to load `MyVariantInfo` info columns. In Signal we don't use LazyMobxTable, we load everything at once, so for example see gnomad and clinvar columns [here](https://www.signaldb.org/gene/BRCA2) to get an idea

- We can remove the `MyVariantInfo` frontend cache and load everything at once like we do in Signal. But first we should probably figure out why MyVariantInfo calls take too long. This data shouldn't take too long to load once it is cached, there might be something wrong with the way we handle this in GenomeNexus.

CC'ing @inodb in case he would like to comment.

**Comment by jjgao** [comment]
@onursumer once the column is loaded, is it possible to enable search?

**Comment by onursumer** [comment]
@jjgao short answer: yes, with some tweaks. 

Long answer: The column is not fully loaded for the initial rendering, we only load the visible page a.k.a lazy loading. We don't load the rest of the column data unless the user clicks on the column header to sort the column or clicks the download button. We need to change that behavior to fully load the data in the background as soon as the mutation table starts rendering. That would make the search fully functional once the full column data is there.

**Comment by jjgao** [comment]
@onursumer I think lazy loading is ok, but once the user click to show the column, that new column should be available for search. Would that be easier than trying to search for data that are not loaded?

**Comment by onursumer** [comment]
@jjgao I am okay with that. But, would it still be `lazy loading` if we loaded all the column data as soon as the column becomes visible? By lazy loading I mean loading only the visible page data for a certain column. 

Loading all the column data at once simplifies a lot of things though. We can get rid of our custom frontend cache, for example.

**Comment by jjgao** [comment]
@onursumer not sure if I understand. I think we should still do lazy loading. But is it possible to query the lazy-loaded columns after they are shown? Currently, even if I select dbSNP, I am still not able to query for them.

**Comment by onursumer** [comment]
@jjgao I think the term lazy loading is confusing here. 

With the current design, you cannot query for the dbSNP column even if you select it because we only load the visible page. Beyond the visible page there is no data to query.

If we would like to be able to query a certain column, we need to load the data for the entire column instead of the current page only. Of course we can (and should) defer the loading until the user makes the column visible. This is still sort of lazy loading, but less granular compared to the current design which only fetches the data for the visible page.
