### ISSUE TITLE
R-API + Keycloak + UUID configuration

### ISSUE THREAD

**Issue by tweep** [cBioPortal/cbioportal#7502]
Hello Cbioportal, 

I'm running v3.1.11 of cbioportal with a working keycloak configuration; I like to also use the R-API - so I went trough the docs and added this config to my properties file to support UUIDs / token; however, the R API returns a 401 when supplying the token to the host / api endpoint.

My properties config: 
```
# data access token settings
dat.unauth_users=anonymousUser
dat.method=uuid
dat.ttl_seconds=2592000
dat.uuid.max_number_per_user=1
dat.uuid.revoke_other_tokens=true
dat.jwt.secret_key=
``````

So when I use the R API with the UUID token ( from web or database table data_access_tokens ) I get a 401 error: 

```
my = CGDS("https://mydomain.com/cbioportal/",verbose=TRUE,ploterrormsg=TRUE,token='8f3d155b-9d2f-4202-8bf0-c4d521556434') 
test(my) 
https://mydomain.com/cbioportal/webservice.do?cmd=getCancerStudies& 
Error in processURL.CGDS(x, url) : Unauthorized (HTTP 401).
``````

**Notes** 
- i can access the endpoint queried by R trough the browser after i authenticate against keycloak 
https://myserver/cbioportal/webservice.do?cmd=getCancerStudies&   OK ( here the authentication method is probably read from the cookie from the web browser ) 

**Questions**
- how can i use the R api with a valid keycloak configuration ? is the UUID way the correct way or am I mixing 2 different authentication methods here ? 
- Shouldn't the R API take a client id / client secret + token to work with keycloak ? ( if it uses the same endpoint as the swagger api ? ) ( this would explain why the webservice.do works )

**Comment by inodb** [comment]
@tweep there are a few PRs open related to this

Note that `webservice.do` will be deprecated. See https://github.com/cBioPortal/cbioportal/pull/7490. There is the new OpenAPI spec API that we recommend to use in the future: https://www.cbioportal.org/api/swagger-ui.html. Of course `webservice.do` will remain usable for a while. I'm not sure if the token implementation works with `webservice.do`

For keycloak integration and API tokens there is still an open PR: https://github.com/cBioPortal/cbioportal/pull/6999. This will prolly be released in the next couple of weeks

**Comment by tweep** [comment]
@inodb, thanks for the quick reply, this answers all my questions.
