### ISSUE TITLE
Mutation mapper can't recognize chromosome 23 and 24

### ISSUE THREAD

**Issue by leexgh** [cBioPortal/cbioportal#7504]
Only `X` and `Y` are accepted in mutation mapper.
1. In mutation mapper tool
paste this data to mutation mapper tool will show an error message
```
Sample_ID	Cancer_Type	Chromosome	Start_Position	End_Position	Reference_Allele	Variant_Allele
P-0006170-T01-IM5	Colon Adenocarcinoma	23	63411678	63411678	G	A
```
![image](https://user-images.githubusercontent.com/16869603/82007502-667ca080-9638-11ea-801b-81d16a752835.png)
However changing chromosome from 23 to X will show results as expected.

2. After enabling transcript dropdown in results view page, some mutations are missing in the mutation table. It is because we do the filtering and transcript match when transcript dropdown is added, in the filter we are looking for certain genomic locations, in which we don't recognize chromosome 23 and 24, only `X` and `Y` are supported

**Comment by jjgao** [comment]
let's support both x, y and 23, 24
