### ISSUE TITLE
Give warning for max number of patients that can be selected for viewing in patient view from study view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7506]
When clicking on "view selected patients" a hash is generated. Occasionally this hash can get too long for the browser to handle, see e.g. https://genie-private.cbioportal.org/study/summary?id=genie_private. It then opens a tab at URL `about:blank#blocked`. It is prolly not really a use case to select that many patients, but might still be good to disable the "view selected patients" button when too many cases are selected and give some warning in a tooltip on mouseover

**Comment by jjgao** [comment]
Wondering if we can just put the list to localstorage?

**Comment by dippindots** [comment]
We proposed to solve this issue by using `client posted data`:
1. Set a limit for numbers of patients can exist in url (the limit is 2000 patients).
2. For number of patients larger than 2000, using `client posted data` to pass the data, do not put patient ids in url anymore.
3. For number of patients smaller than 2000, still put the ids in url.
