### ISSUE TITLE
Logged as in username disappears in cBioportal v3.3.3 after logged in

### ISSUE THREAD

**Issue by gatksun** [cBioPortal/cbioportal#7511]
I just upgraded my local cbioportal to v3.3.3.
my cBioportal uses ad as authentication that works from v1.x till v.3.3.2.
However , it is the most annoying that " Logged as in username" disappears after an user logged in .
If I reload the page,  "Logged as in username" shows as expected.
I found v3.3.3 changed something in applicationContext-security.xml.
hopefully fix it asap.

**Comment by kalletlak** [comment]
@gatksun what authentication method is used?

**Comment by gatksun** [comment]
I used ad , same bug in v3.3.3 and 3.3.5.
I do not think this bug is related to specific authentication.
