### ISSUE TITLE
review api endpoints

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7517]
Goals:

- decide the final public end point list
- any tweaks (names, parameters, etc) need to be made?

**Comment by inodb** [comment]
Docs here: https://docs.google.com/document/d/1KC07Rl_oD6jYUyYahv4UrS-GIuLWnr4biaWop826U1Y/edit. Added it to the epic here: https://github.com/cBioPortal/cbioportal/issues/7258
