### ISSUE TITLE
Should we bring back survival curves for pan-cancer study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7518]
We removed survival curves in the study view when there are multiple cancer types because it was misleading to compare survival across cancer types. Now that we are not comparing survival data between selected and unselected patients, should we bring the survival curves back? I find it's useful to know the data availability.

@cBioPortal/product

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao I think it makes sense. Although a pie chart that indicates data availability would also work, nothing says 'survival data available' like a KM-plot :-)

**Comment by tmazor** [comment]
Agreed, let's bring it back!

**Comment by Sjoerd-van-Hagen** [comment]
Resurrection of the survival plot :-)

**Comment by adamabeshouse** [comment]
maybe someone else who's more familiar with study view survival can take this?
