### ISSUE TITLE
rppa data for brca_tcga_pub2015 is not complete

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#752]
We should curate it from the publication page:

https://tcga-data.nci.nih.gov/docs/publications/brca_2015/TCGA-BRCA-RBN-v2_0_BRCA817freeze.txt

**Comment by ritikakundra** [comment]
will this need a manual curation?

**Comment by jjgao** [comment]
@ritikakundra yes, I'll get more data and discuss with you.
