### ISSUE TITLE
OQL for querying mutations in a range

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7529]
something like:

```
TP53: MUT_(95-255)
TP53: MUT_(1-94)
TP53: MUT_(256-)
TP53: MISSENSE_(95-255)
TP53: DRIVER_(95-255)
TP53: GERMLINE_(95-255)
TP53: GERMLINE_MISSENSE_(95-255)
```

@cBioPortal/product @adamabeshouse

**Comment by schultzn** [comment]
Yes, that would be great to have. Maybe also allow the combination of ranges, e.g.:
TP53: MUT_95-105,126-200

?

**Comment by jjgao** [comment]
`,` is now used to separate genes. Combination of ranges can be supported by `TP53: MUT_95-105 MUT_126-200`

**Comment by jjgao** [comment]
@adamabeshouse would it be also possible to support "TP53: MISSENSE_95-255"  etc added in the description above?

Please comment if you have better suggestions for the format.

**Comment by adamabeshouse** [comment]
yeah that seems fine to me :+1:

**Comment by adamabeshouse** [comment]
@jjgao given a mutation with protein coords startP-endP, and an oql specification startO-endO, do we select that mutation if startP-endP overlaps with startO-endO, or only if startP-endP is totally contained in startO-endO?

**Comment by schultzn** [comment]
Good question.

Can we make one the default (I would vote for any overlap), but add syntax to limit to only completely overlapping events?

Or is that too complicated?

**Comment by adamabeshouse** [comment]
@schultzn that sounds good. how about adding an exclamation point means totally overlapping? i.e. `MUT_(2-10)!` vs `MUT_(2-10)`

**Comment by adamabeshouse** [comment]
I implemented it here https://github.com/cBioPortal/cbioportal-frontend/pull/3241

We can easily change the syntax for "totally overlapping" if we decide something different.
