### ISSUE TITLE
Adding Compare button to pie chart hoverover?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7533]
e.g. after "Deselect all" button

![image](https://user-images.githubusercontent.com/840895/82689898-39785100-9c29-11ea-888d-489d0bae90d3.png)

@cBioPortal/product

**Comment by Sjoerd-van-Hagen** [comment]
Is there a need to make it more visible i.e. people cannot find it?

This would also be a good spot to add the 'invert selection' button. Maybe the UI controls in the popup should be limited to selection controls?

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen I think it's not easy to find the Comparison feature in the current UI.

**Comment by Sjoerd-van-Hagen** [comment]
Do you have a reason to believe people cannot find it? Do we have any
statistics that the comparison is underused?

I haven't seen any questions on the Google groups that suggest that users
cannot find it.

You could be right of course. That we can find it easily does not mean
others can, but it seems a bit of a guess without supporting data.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen It's just my intuition. I appreciate the reasoning behind the idea of data-driven design, but I am not sure if it is feasible if we need (or have the bandwidth) to collect data to justify every UI improvement. Also, only a small fraction of our feature dev and UI improvements were based on questions from users.

In this case, I think a small change of adding a new "Compare" button (while still keeping it in the menu) will make this important feature more upfront, especially for new users to cBioPortal and Study View. Again, this is just my intuition. @Sjoerd-van-Hagen I am wondering if there are any issues of adding the button that I missed?

**Comment by Sjoerd-van-Hagen** [comment]
I don't think there are any issues but we should always take care when
adding more UI elements. You can also have too many elements and the user
does not know where to look.

For this case A/B testing would be awesome. Half of the users get the
button, other half don't and we see if there is a significant difference in
times they use the comparison.

--

E.   sjoerd@thehyve.nl

T.   +31(0)30 700 9713

W.  www.thehyve.nl

**Comment by jjgao** [comment]
A/B testing would be awesome, but we don't have everything in place yet to do that. In this case, maybe we can add the button and compare the visits to the comparison page before and after. I just took a look at the current usage - below. There may be some room to improve.

![image](https://user-images.githubusercontent.com/840895/91208929-fc64a480-e6d8-11ea-93d9-1d470b7c18fa.png)

**Comment by Sjoerd-van-Hagen** [comment]
Seems like people already know how to find the comparison page. I would not
expect the comparison page to move up in this list, since you would always
have to come through the study page or the oncoprint to get there. We can
give it a shot though.

--

E.   sjoerd@thehyve.nl

T.   +31(0)30 700 9713

W.  www.thehyve.nl

**Comment by jjgao** [comment]
The one we try to improve is # 10 above. It's good to see that the Comparison tab in Results page is already been used a lot (# 4). 

We'll give it a try if no one objects.

**Comment by jjgao** [comment]
@alisman I remember you had some really nice design when hovering over the pie chart. I am wondering if you can revive that design when working on this?
