### ISSUE TITLE
Expression data discrepancy between comparison page and download

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7535]
Data discrepancy between expression data on comparison tab and in download
 
Click gene mdm2 (or probably any gene).  Do a query against study and download data for RNA Seq V2 RSEM.   It seems values are complete different.  

https://www.cbioportal.org/comparison/mrna?sessionId=5e881f9ce4b030a3bfcff7fb

https://www.cbioportal.org/results/download?Action=Submit&cancer_study_list=gbm_tcga&case_set_id=gbm_tcga_all&gene_list=MDM2&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=gbm_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=gbm_tcga_mutations&tab_index=tab_visualize

Reported by user here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/LphVx5_mfHY/IQdJYVzhBQAJ

**Comment by alisman** [comment]
@kalletlak I'm gessing this is probably a similar issue to the one we fixed before (relating to sort order difference MySQL v java.

**Comment by kalletlak** [comment]
@alisman looks like values in comparison page box plot are log2 value. Should we indicate that in the plot and downloaded data or replace it with raw values?
