### ISSUE TITLE
Adding Plots tab to multi-study query

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7537]
Currently, Plots tab is only available when one study is queried. It would be good to expand it to multi-study query. We can group the profiles in the same logic as the Download tab in Results and Profiles table in Study View.

**Comment by tmazor** [comment]
I see there was some earlier discussion on the topic of data availability -- I think this is a really important issue to work out. This is a problem throughout results view in a multi-study query, but I think it is particularly important and hidden on the Plots tab. I can easily select values on my x & y axes that exist in different studies, which will result in no data to plot, but also no clear indication to the user of why.

Were there any ideas from your previous discussion of how to deal with this? @dippindots @jjgao

**Comment by jjgao** [comment]
@tmazor we only discussed about which samples to include (the intersection between x and y axes). It would be good to show the data availability, including each axis, the intersection, (and the coloring data?).
