### ISSUE TITLE
GSVA data and is missing Z-Score expression error

### ISSUE THREAD

**Issue by Mohammedhusen** [cBioPortal/cbioportal#7566]
Hi Team,

While loading study data in our local instance we are getting below error even though we below file presents.

meta_RNA_Seq_v2_mRNA_median_Zscores.txt
data_expression_zscores_file.txt

Does GSVA required a separate Zscore file?

ERROR: -: Study contains GSVA data and is missing Z-Score expression file. Please add a Z-Score expression file calculated from the same expression file used to calculate GSVA scores

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen any insights?

**Comment by Sjoerd-van-Hagen** [comment]
@Mohammedhusen did you set the 'source_stable_id' field in the GSVA meta file?

**Comment by Mohammedhusen** [comment]
Thank you @Sjoerd-van-Hagen ...

After adding source_stable_id: rna_seq_mrna in RNA meta-file resloves this error.
However, I still have the error regarding the geneset version [https://github.com/cBioPortal/cbioportal/issues/7593], Could you pls check this also.

Thanks a lot for your quick reply!
