### ISSUE TITLE
.editorconfig causes auto formatting issue

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#757]
trim_trailing_whitespac, nsert_final_newline have been set to true which will cause lots of auto formatting issue (e.g. pull request #755 )

Can I change them to false? @jjgao @aderidder @pieterlukasse

**Comment by jjgao** [comment]
What/where is .editorconfig?

**Comment by zhx828** [comment]
@jjgao https://github.com/cBioPortal/cbioportal/blob/master/.editorconfig This is the file to define and maintain consistent coding styles between different editors and IDEs.

**Comment by jjgao** [comment]
I am fine with that.

**Comment by pieterlukasse** [comment]
@zhx828 @jjgao : this looks like a nice solution to the discussion we had some weeks ago regarding white spaces and tabs. Are we all using this now? To me this is new, maybe I missed this in the conversation. Let me know if this is the way to go and we will comply to it.

**Comment by zhx828** [comment]
@pieterlukasse I drafted and recommended to use this file. There isn't an official discussion about this yet. Should we talk about this some day? @jjgao

**Comment by pieterlukasse** [comment]
@zhx828 : nice, thanks. We can start using it if that helps in convincing more people to use it ;)

**Comment by jjgao** [comment]
we have another discussion about follow Google's style. Maybe someone can present in the week call on this topic.
