### ISSUE TITLE
Add Treatments Tables to Study View (Frontend)

### ISSUE THREAD

**Issue by Luke-Sikina** [cBioPortal/cbioportal#7578]

**Comment by Luke-Sikina** [comment]
![Screenshot from 2020-06-26 14-21-48.png](https://images.zenhubusercontent.com/5d7933c4ce6e6a000126f83a/39cfbcb3-5e4e-43f5-869f-1f594053c6e1)
Progress.
Filters aren't showing up in UI. Everything else seems to work.

**Comment by jjgao** [comment]
@Luke-Sikina how was False calculated? Was drug combo considered?

**Comment by Luke-Sikina** [comment]
![patient-treatments.gif](https://images.zenhubusercontent.com/5d7933c4ce6e6a000126f83a/954f199f-010d-4557-825e-7d84576e2e29)
- removed false
- added some code sharing between sample treatments and sample patients

TODO
- some buggy behavior with the selections showing up
