### ISSUE TITLE
Error when opening gene panel popup in patient view page

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#7579]
Example, for https://www.cbioportal.org/patient?studyId=all_stjude_2013&caseId=SJHYPO009
<img width="533" alt="Screen Shot 2020-06-03 at 4 53 54 PM" src="https://user-images.githubusercontent.com/12956870/83688239-118ad500-a5bb-11ea-8c98-0edce601918e.png">

on clicking `WXS` throws

<img width="456" alt="Screen Shot 2020-06-03 at 4 56 05 PM" src="https://user-images.githubusercontent.com/12956870/83688310-30896700-a5bb-11ea-919b-9778b2a589c9.png">

**Comment by jjgao** [comment]
Maybe WXS should not be hyperlinked?
