### ISSUE TITLE
Enrichment scores (GSVA) are link to samples (Patient-Sample) instead of to the barcode 

### ISSUE THREAD

**Issue by Mohammedhusen** [cBioPortal/cbioportal#7581]
Hi Team,

The Enrichment scores (GSVA) are link to samples (Patient-Sample) instead of to the barcode (Patient-Sample-Pipeline) which is confusing as GSVA is done on RNAseq expression, not on the sample directly. Especially if we have 2 or more RNA pipelines, which one was used for GSVA is unclear.

**Comment by jjgao** [comment]
Not sure if I understand this, but we don't have a way to model the relationship between different profiles/pipelines. You might want to just add it to the description of the GSVA profile.

@Sjoerd-van-Hagen any thoughts on this?

**Comment by Sjoerd-van-Hagen** [comment]
If you have multiple RNA pipelines you should have multiple RNA expression profiles in cBioPortal to reflect that. You can then also create two GSVA profiles that point the the respective RNA profile, using 'source_stable_id' in the GSVA meta file.
