### ISSUE TITLE
GENIE cBioPortal Registration Process

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#7589]
AACR feels something may be wrong with first time user registration to the public portal.  Can we check that the auto registration/email is working propertly (I recall we have some google doc macro running every minute - not sure if that is broken). 

Also, can we add [text to the login page](https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/blob/master/cbioportal/cbioportal_backend_genie_public.yaml#L93) that states that after registration an email will be sent with login information (should we specify a timeframe for this email?).

**Comment by ao508** [comment]
pr here: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/pull/77
