### ISSUE TITLE
Exception in catalina.out

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#759]
![image](https://cloud.githubusercontent.com/assets/840895/12355668/391e50ee-bb6c-11e5-98ca-fa4dbe7c96f6.png)

**Comment by fedde-s** [comment]
Is this still an issue?

**Comment by jjgao** [comment]
Not sure. I am closing this since we are walking away from the servlet that is causing the issue. It may not worth the effort to investigate this.
