### ISSUE TITLE
Reproduce old custom presentation logic for timeline

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7594]
- [x] Genie study: Status --> Med Onc Assessment
- [x] Genie study:  coloring of Med Onc Assessment based on status detection
- [x]  Genie study: color of image events based on status
- [x] Order and label specimin's according to SampleManager.  
- [x] Color metastatic sample red
- [x] for isMskImpactJuneTestStudy, derive DECEASED event from clinical data
- [x] handle splitting based on event types through configuration
- [x] Scale points on PSA tracks which are LAB_TEST > TEST type based on result value

**Comment by inodb** [comment]
I think this was just discussed on a call, so gonna assume a conclusion has been reached
