### ISSUE TITLE
Fusion events do not show up in mutation table if there is no mutation genetic profile also present in study.

### ISSUE THREAD

**Issue by ao508** [cBioPortal/cbioportal#7612]
Same patient with fusion events in a study that has both a fusion genetic profile and a mutation genetic profile.
![image](https://user-images.githubusercontent.com/15623749/84516874-6bb32680-ac9c-11ea-8347-d312d2216d9d.png)

Same patient with fusion events in a study that has only a fusion genetic profile
![image](https://user-images.githubusercontent.com/15623749/84516971-969d7a80-ac9c-11ea-8652-50f9d958f932.png)

**Comment by inodb** [comment]
@ao508 would a possible fix be to include a "fake" mutation profile instead of handling on the frontend?

**Comment by ao508** [comment]
@inodb that's what we were using before to get the events displayed but they aren't showing up anymore with the new filtering.

**Comment by ao508** [comment]
I believe I found a related issue as well. The `mskimpact` study summary page only shows "mutations" and "cna" as the genomic profiles available for the study. The structural variant/fusions profile doesnt show up here - shouldnt it be present?

![image](https://user-images.githubusercontent.com/15623749/84819628-531d7600-afe6-11ea-8a6e-572352c55d27.png)

I also confirmed the API is returning all 3 expected profiles for mskimpact:

| profile | molecular alteration type | datatype | stable id |
| ------- | ---------------------------- | --------- | ---------- |
| CNA  | COPY_NUMBER_ALTERATION | DISCRETE | "_cna" |
| Mutations | MUTATION_EXTENDED | MAF | "_mutations" |
| Fusions | STRUCTURAL_VARIANT | FUSION | "_fusion" |






On the other hand, the ARCHER only cohort *does* show "fusions" as an available genomic profile. This is also the cohort for which we are importing the fusions as a "fake" mutations genomic profile. 

![image](https://user-images.githubusercontent.com/15623749/84819755-8d871300-afe6-11ea-92b2-97bca2184df9.png)

Here is what the API is returning for this cohort:

| profile | molecular alteration type | datatype | stable id |
| ------- | ---------------------------- | --------- | ---------- |
| Fusions | MUTATION_EXTENDED | FUSION | "_mutations" |

**Comment by onursumer** [comment]
I think structural variant frontend work is still in progress. Frontend should be still relying on the mutation profile for most of the implementation.

cc'ing @kalletlak in case he wants to add more insight to this.

**Comment by ao508** [comment]
Thanks @onursumer, I brought this issue up here in case some of the same filtering logic might be used both in the study summary page and for displaying fusion/structural variant events in the patient view mutation table

**Comment by kalletlak** [comment]
@ao508 only the profiles have count>0 would be shown in `Genomic Profile Sample Counts` table. I am bit confused with a ARCHER profile, isn't the fusion profile stable id have suffix `_fusion`?

**Comment by ao508** [comment]
@kalletlak Yes it should be this is a work around that we needed to implement in order to get the `data_fusions.txt` (1) imported and (2) to get the genomic profile to display in the study summary page and (3) to be visualized in the patient view mutation table (which is no longer happening).

In any case though the mskimpact cohort isn't showing the structural variant profile in the "Genomic Profiles" table on the study summary page and it definitely has data for that profile for several patients/samples/genes.

**Comment by kalletlak** [comment]
@ao508 I don't have access to msk internal portal. And I think importing fusions as mutations won't work.

Was there any backend api call to fetch the mutations? If it is, was there an error or empty list response?
