### ISSUE TITLE
Cohort button on study view is not properly disabled (while awaiting)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7625]
This button should be disabled (not clickeable) until the patient list on which it depends is fully loaded.  It presently allows clicking but has no action, creating confusion.

![image](https://user-images.githubusercontent.com/186521/84823157-e5744880-afeb-11ea-8a2e-fdaaad115e29.png)

**Comment by jjgao** [comment]
@alisman is this a good first issue for Luke's intern?
