### ISSUE TITLE
Oncoprint bug when re-adding clustered mRNA trackgroup when GSVA trackgroup present

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#7629]
# Problem

When removing and re-adding a clustered heatmap track group (for instance of mRNA data), oncoprint 'crashes'. 

![Peek 2020-06-17 06-41](https://user-images.githubusercontent.com/745885/84856682-a97ec900-b067-11ea-9adf-7a0f0f06283d.gif)

The following error is shown in the console:

```
0.06cb55e722e7c5289e46.chunk.js:32 jQuery.Deferred exception: Cannot read property 'pos_array' of undefined TypeError: Cannot read property 'pos_array' of undefined
    at t.getTrackBuffers (https://localhost/reactapp/0.06cb55e722e7c5289e46.chunk.js:49:246693)
    at t.renderAllTracks (https://localhost/reactapp/0.06cb55e722e7c5289e46.chunk.js:49:241739)
    at t.setTrackGroupOrder (https://localhost/reactapp/0.06cb55e722e7c5289e46.chunk.js:49:251991)
    at t.setTrackGroupOrder (https://ec2-18-157-159-210.eu-central-
...

0.06cb55e722e7c5289e46.chunk.js:32 jQuery.Deferred exception: Cannot read property 'sort' of undefined TypeError: Cannot read property 'sort' of undefined
    at t.computeVertexPositionsAndVertexColors (https://localhost/reactapp/0.06cb55e722e7c5289e46.chunk.js:49:248841)
    at t.sort (https://localhost/reactapp/0.06cb55e722e7c5289e46.chunk.js:49:252828)
...

```
This problem only occurs when:
- a Gene Set (GSVA) trackgroup is present (see Examples below).
- the mRNA track is sorted (see Examples below).

# Steps to reproduce

1. Goto [this URL](https://ec2-18-157-159-210.eu-central-1.compute.amazonaws.com/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=gbm_tcga&case_set_id=gbm_tcga_cnaseq&data_priority=0&gene_list=CDKN2A%2520MDM2%2520MDM4%2520TP53&geneset_list=VERHAAK_GLIOBLASTOMA_CLASSICAL%20VERHAAK_GLIOBLASTOMA_MESENCHYMAL%20VERHAAK_GLIOBLASTOMA_PRONEURAL%20CAHOY_NEURONAL%20HINATA_NFKB_IMMU_INF%20HALLMARK_E2F_TARGETS%20HALLMARK_G2M_CHECKPOINT%20HALLMARK_INTERFERON_ALPHA_RESPONSE&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=gbm_tcga_gistic&genetic_profile_ids_PROFILE_GENESET_SCORE=gbm_tcga_gsva_scores&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=gbm_tcga_mutations&oncoprint_cluster_profile=gbm_tcga_mrna_U133_Zscores&oncoprint_sortby=cluster&profileFilter=0&tab_index=tab_visualize&heatmap_track_groups=gbm_tcga_mrna_U133_Zscores%2CCDKN2A%2CMDM2%2CMDM4%2CTP53).
2. Add a mRNA trackgroup from the heatmap menu
3. Cluster the mRNA trackgroup
4. Delete the mRNA trackgroup
5. Add a mRNA trackgroup from the heatmap menu

# Examples

1.  Re-adding of clustered mRNA trackgroup in presence of GSVA track fails when mRNA trackgroup is sorted.
![Peek 2020-06-17 06-41](https://user-images.githubusercontent.com/745885/84856682-a97ec900-b067-11ea-9adf-7a0f0f06283d.gif)

2. Re-adding of clustered mRNA trackgroup in presence of GSVA track works correctly when mRNA trackgroup is not sorted.
![Peek 2020-06-17 06-40](https://user-images.githubusercontent.com/745885/84856662-97048f80-b067-11ea-9724-668a32fd1132.gif)

3. Re-adding of clustered mRNA trackgroup in absence of GSVA track works correctly
![Peek 2020-06-17 06-42](https://user-images.githubusercontent.com/745885/84856564-5ad12f00-b067-11ea-9b48-a3a0ea7d89bc.gif)

Note: the link provided above provides access to our demo server that has a dataset loaded with GSVA data. This can be used to debug the issue.

**Comment by adamabeshouse** [comment]
@pvannierop there is something wrong with the link's SSL certificate and chrome isn't letting me visit it

**Comment by pvannierop** [comment]
@adamabeshouse You have to ignore this error. I did not set a valid certificate.

**Comment by adamabeshouse** [comment]
@pvannierop no matter what I do, it's not letting me on. can you set it to allow http?

**Comment by adamabeshouse** [comment]
I think it's fixed by this

**Comment by jjgao** [comment]
I am closing this. @pvannierop please feel free to reopen if the problem persists.

**Comment by adamabeshouse** [comment]
wait @pvannierop has been on vacation so he cant review it, lets wait until he gets back
