### ISSUE TITLE
data inconsistency in brca_tcga_pub2015

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#763]
We should probably re-curate the data based on Giovanni's snapshot (http://cbio.mskcc.org/cancergenomics/tcga/brca_tcga/) and the publication page (https://tcga-data.nci.nih.gov/docs/publications/brca_2015/). 

 - [ ] the number of samples does not match. The manuscript has 817 tumors, but the study has 1105.
 - [ ] rppa data are different

**Comment by jjgao** [comment]
@chenh4 could you look into this?

**Comment by chenh4** [comment]
http://dashi-dev.cbio.mskcc.org:28080/triage/study.do?cancer_study_id=brca_tcga_pub2015#clinical

will import into MSK portal tomorrow (4/7).

**Comment by chenh4** [comment]
Done!
