### ISSUE TITLE
updating genes and gene aliases : error setting gene length/start/end

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#7632]
We attempted to install a database from the seed database. When we reached the steps which set gene length and start and end fields in the gene table, these fields were not set appropriately (even though the log output from the command said that the record was being updated.

gencode.v25lift37.annotation.gtf

This file contains records of gene exon content for various transcripts. There is a mixture of "HAVANA" genes and "ENSEMBL" genes. When looking at example records for ENSEMBL, we have records such as this one:

chr1	ENSEMBL	exon	29386934	29386996	.	+	.	gene_id "ENSG00000159023.19_2"; transcript_id "ENST00000356093.6_1"; gene_type "protein_coding"; gene_status "KNOWN"; gene_name "EPB41"; transcript_type "protein_coding"; transcript_status "KNOWN"; transcript_name "EPB41-202"; exon_number 13; exon_id "ENSE00001065029.1_1"; level 3; protein_id "ENSP00000348397.3"; transcript_support_level 5; tag "basic"; havana_gene "OTTHUMG00000003644.5_2"; remap_original_location "chr1:+:29060422-29060484"; remap_status "full_contig";

When running this step from the instructions (https://docs.cbioportal.org/3.-cbioportal-maintenance/updating-gene-and-gene_alias-tables) :

This line:

./importGenes.pl --genes /data/manda/HGNC-dump-in-NCBI-format.txt --gtf /data/manda/hgnc-tmp/gencode.v25lift37.annotation.gtf --genome-build GRCh37

Gave error messages for HAVANA lines, such as:
23179. Unable to retrieve gene by symbol: snoZ6; 4x
23180. Unable to retrieve gene by symbol: snosnR60_Z15; 2x
23181. Unable to retrieve gene by symbol: snosnR66; 1x

But ENSEMBL lines seemed to give valid output, such as:
--> update reference genome gene: EPB41
 updateLength--> cytoband of the gene: chr1p35.3

However, the reference_genome_gene record for this gene had no start, end, or length set

**Comment by inodb** [comment]
@sheridancbio which instructions requires one to set the gene length etc? Is this to create a new seed database?

I think when using the docker based install you can use one of the provided 37+38 combined seed databases: https://github.com/cBioPortal/datahub/tree/master/seedDB_hg38. See step here: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker#step-2-run-mysql-with-seed-database. Not sure if that's helpful?

**Comment by sheridancbio** [comment]
Sorry Ino, I accidentally submitted the issue before I had completed the description. We were importing a new 37-only database from the seeddb

**Comment by sheridancbio** [comment]
Clarification : this issue came up *after* the seed data had been imported. The following step was to run the script which updates the genes and gene aliases (includes cytoband, length, start, end)

**Comment by inodb** [comment]
@SRodenburg do u have any thoughts on this? Thank you!

**Comment by SRodenburg** [comment]
From my experience, `importGeneData` is indeed a bit buggy sometimes. It requires a specific format for the gencode gene table. After loading some information from this file, the program tries to get additional genomic information from the GTF file.

My guess is that one of the files is inconsistent in format, or some gene symbols are not present in either the gene table or the GTF.

You could check out importGeneData.java to gain a bit understanding how it loops through the files and which fields are expected.

**Comment by inodb** [comment]
Thanks @SRodenburg !

@sheridancbio I'm actually still slightly confused. Where does it mention to update the gene and gene alias table? This page: https://docs.cbioportal.org/3.-cbioportal-maintenance/updating-gene-and-gene_alias-tables? I believe that update is only necessary if you're trying to build a new seed database. Maybe that's goal, but just double checking

**Comment by SRodenburg** [comment]
@inodb you are right, updating the genes is a step in the creation of a new seed db. I guess I can also be used to load custom genes.

**Comment by sheridancbio** [comment]
@inodb @SRodenburg Our use case was building a database with a custom selection of genes and gene aliases. We did not want to include all of the genes with entrez gene ids ... in particular, we wanted to limit the set of defined genes to those which are defined in HGNC (via https://www.genenames.org/download/statistics-and-files/). This is part of our attempt to move to a non-ambiguous gene database (avoiding duplication of a gene symbol in two different entrez gene ids, or ambiguous aliases)

So, part of this process was taking the latest seed database and wiping the gene table, then loading in genes (and aliases) from HGNC. cc: @mandawilson @averyniceday

**Comment by inodb** [comment]
@sheridancbio gotcha, makes sense, thanks!

**Comment by jjgao** [comment]
Can we get rid of length/start/end now? Previously we were using length in the Mutated Genes tab in study view but that tab has been removed. AFAIK, we are not using them in other places unless I may have missed something.

**Comment by jjgao** [comment]
@sheridancbio any plan on this? Should we just remove length/start/end? I don't they are used in frontend anymore.
