### ISSUE TITLE
Study view chart of non-ranged integer should be on tick

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7635]
Try e.g.: https://www.cbioportal.org/study/summary?id=msk_impact_2017

and add extra custom bin 0 to mutation count chart:

<img width="397" alt="Screen Shot 2020-06-18 at 9 48 22 AM" src="https://user-images.githubusercontent.com/1334004/85028356-f8505f80-b148-11ea-80bd-2efe9781e08c.png">

None of these bars should represent ranges since mutation count is an integer and each bar represents a single number. It would be better if the bars are centered on the ticks instead of in-between the ticks. Not sure how hard this would be

**Comment by jjgao** [comment]
@zhx828 @kalletlak @onursumer comments?

**Comment by zhx828** [comment]
@jjgao @inodb this is not so difficult. We have the feature already for bar charts have less than 5 categories. The key is to calculate all data points to make sure they all integer which we do not differentiate in database. @onursumer implemented this feature so can comment more on this.

**Comment by onursumer** [comment]
@jjgao @inodb @zhx828 I think this is not too difficult to change. But, do we always want to show discrete chart if all of the values are integer? What if we have 1000 different values all integers? If we are going to change the threshold (currently 5) instead, which new number are we going to pick? Do we have a one-size-fits-all solution?

**Comment by inodb** [comment]
@onursumer it should only show all integers when the number of values as small. Most histogram functions allow you to specify number of bins, which i think makes sense in this case. If number of values <= to number of bins then it should be one tick per integer, otherwise the ticks can be ranged
