### ISSUE TITLE
add banners to pathways tab

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7637]
When I apply a filter (VUS or germline), other tabs have a banner warning that mutations have been filtered out. The pathways tab does not have these banners although it does appear to respect the filters when they are applied.

![image](https://user-images.githubusercontent.com/10508276/85075898-32435500-b18d-11ea-86db-d75322991f6a.png)

vs

![image](https://user-images.githubusercontent.com/10508276/85075909-37a09f80-b18d-11ea-9d88-f77dd0e6c7af.png)

https://bit.ly/30TAweG

**Comment by adamabeshouse** [comment]
I think the pathways tab didn't used to use actual data, it used to just use the query genes, right? but now it actually does use query data?

**Comment by jjgao** [comment]
@adamabeshouse yes, it's using the oncoprint data, I think.
