### ISSUE TITLE
Mutation mapper error

### ISSUE THREAD

**Issue by Choaping** [cBioPortal/cbioportal#7638]
Hi all,

I'm not sure if you've experienced this but i've been getting this error message that says JobID must be numerical every time i try to submit a job. I have even tried to use the examples in the help section for input into the system but it still gives me that same JobID must be numerical error. I was wondering if I have done or not done the right thing? Many thanks.

regards,

Choaping (CP)

**Comment by jjgao** [comment]
@Choaping would you please contact cbioportal@googlegroups.com and let us know which browser you are using? Thanks.
