### ISSUE TITLE
how to compare RNAseq data in the TCGA pancan studies (batch-corrected normalized data) with other data in cbioportal

### ISSUE THREAD

**Issue by dingying85** [cBioPortal/cbioportal#7644]
Hi,

The unit of RNAseq data in the TCGA pancan studies are not TPM, when I sum up all the expression for a given sample for all genes are around 20 million. This makes it hard to compare with other studies that are not TCGA pancan studies (for example, when I look at other studies, the sum of all expression for a give sample only sum up to be 300000).

Is there a way to compare a given gene across different studies? I thought if all studies use TPM,then that will be more comparable? Thanks.

Yours,
Ying

**Comment by jjgao** [comment]
Hi Ying,

We don't have an answer for this. Comparing expression data between TCGA and non-TCGA studies would require batch correction, but our data were not batch corrected (except across the TCGA pancancer studies).

Please feel free to contact us at cbioportal@googlegroups.com from prompt response.

-jj
