### ISSUE TITLE
Set limit for how many generic assay entities can be added as heatmap track to oncoprint

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#7650]
One `Generic Assay` profile can contain lots of entities (sometimes over 1000), that will consume lots of resources to render that amount of tracks on oncoprint, we should set a limit for how many generic assay entities can be added as heatmap track to oncoprint.

Is `50` a reasonable limit number?

**Comment by jjgao** [comment]
Maybe 100 for now? We can implement it in the new UI #7656

**Comment by dippindots** [comment]
Closing this issue since it's captured in #7656
