### ISSUE TITLE
Adding generic assay data to Comparison page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7654]
We can have additional tabs per generic assay profile, e.g. "Drug response" and "Microbiome signature"

**Comment by dippindots** [comment]
@jjgao Could I get some suggestions from you on how we show the data in those new tabs?

**Comment by jjgao** [comment]
@dippindots for continuous data, it should be the same as Expression and Protein tab.

**Comment by jjgao** [comment]
@dippindots maybe it's a good idea to add Methylation tab as an excise first (https://github.com/cBioPortal/cbioportal/issues/7683)? We can release the Methylation tab first once it's done. @kalletlak and @adamabeshouse can give you pointers.
