### ISSUE TITLE
Add data download option to cancer type summary chart

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7655]
The following chart does not have `data` download option.  

https://www.cbioportal.org/results/cancerTypesSummary?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations

**Comment by jagnathan** [comment]
@jjgao requested to remove rows where y=0. this has been done now.
