### ISSUE TITLE
redesign the UI for pulling generic assay data (treatment response, microbiome) in OncoPrint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7656]
The current UI is challenging: there are three interaction sections: the buttons, the text input, and the dropdown. Can we consolidate the three into one? One idea is to develop a UI that is similar to the Gmail (see below).

We should also put a limit of the number of tracks we can support (100 tracks): #7650

![image](https://user-images.githubusercontent.com/840895/85598373-80d37200-b619-11ea-9418-35caecf22be6.png)

![image](https://user-images.githubusercontent.com/840895/85598893-022b0480-b61a-11ea-806b-719fc10191b7.png)

**Comment by alisman** [comment]
@jjgao can you send me the query you used to produce the screenshot?

**Comment by dippindots** [comment]
@alisman Here is a similar example for treatment data: http://www.cbioportal.org/results/oncoprint?genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ccle_broad_2019_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=ccle_broad_2019_cna&cancer_study_list=ccle_broad_2019&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=ccle_broad_2019_cnaseq&gene_list=TP53&geneset_list=%20&tab_index=tab_visualize&Action=Submit

![image](https://user-images.githubusercontent.com/15748980/85616826-46270500-b62c-11ea-9041-84e7385639c4.png)

**Comment by dippindots** [comment]
@alisman @jjgao I made a prototype, do you like this design?
![image](https://user-images.githubusercontent.com/15748980/85775507-d711e500-b6ed-11ea-8f4f-34ef1579847b.png)

**Comment by jjgao** [comment]
@dippindots @alisman here is the link the the example: https://bit.ly/3gaqgmI
