### ISSUE TITLE
Dataset validator 

### ISSUE THREAD

**Issue by colinmiller20** [cBioPortal/cbioportal#7660]
I am deploying an instance of cbioportal with Docker. To use the dataset validator, it says to go to the importer folder <cbioportal_source_folder>/core/src/main/scripts/importer. However, I do not have these folders in my directory. Is the dataset validator for use only with the "Deploy without Docker" option? Otherwise, how should I access this importer folder that is necessary for the dataset vaildation?

**Comment by jjgao** [comment]
Hi @colinmiller20, after you clone the code, it should be available in the directory in the folder.
```
https://github.com/cBioPortal/cbioportal/tree/master/core/src/main/scripts/importer
```

Please feel free to contact cbioportal@googlegroups.com if you have additional questions.
