### ISSUE TITLE
remove clinicalTrialKeywords from API

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7661]
`clinicalTrialKeywords` is no longer useful.

- [x] remove from API

Should still be removed from database as well: https://github.com/cBioPortal/cbioportal/issues/7820

**Comment by Luke-Sikina** [comment]
TODO: Branch off Ino's branch, cherry pick your commits, make PR.

**Comment by jagnathan** [comment]
This has been merged into the PR that Ino created.https://github.com/cBioPortal/cbioportal/pull/7821

**Comment by inodb** [comment]
Let's release database migrations in one go

- [ ] check if there are other database migrations necessary for public release of API (see public API epic)
- [ ] we could use rc for testing
- [ ] schedule migration with backend team
