### ISSUE TITLE
Tooltips and scrolling of bar chart of Cancer Type Summary are broken

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#7662]
In the bar chart of Cancer Type Summary I experienced the following problems.

## Problem 1

The tooltips that appear when hovering a plus symbol in the x-axis are misplaced. I expect these to show over the icon that is hovered (see image).

##  Problem 2

There is no apparent way to scroll the Cancer Type Summary plot when the horizontal space is exceeded by the plot (see image). This occurs when there are many cancer types in the analysis such as with PanCancer TCGA and selecting the _Cancer type detailed_ option.

This behavior van be reproduced with [this URL](https://www.cbioportal.org/results/cancerTypesSummary?genetic_profile_ids_PROFILE_MUTATION_EXTENDED=laml_tcga_pan_can_atlas_2018_mutations&cancer_study_list=laml_tcga_pan_can_atlas_2018%2Cacc_tcga_pan_can_atlas_2018%2Cblca_tcga_pan_can_atlas_2018%2Clgg_tcga_pan_can_atlas_2018%2Cbrca_tcga_pan_can_atlas_2018%2Ccesc_tcga_pan_can_atlas_2018%2Cchol_tcga_pan_can_atlas_2018%2Ccoadread_tcga_pan_can_atlas_2018%2Cdlbc_tcga_pan_can_atlas_2018%2Cesca_tcga_pan_can_atlas_2018%2Cgbm_tcga_pan_can_atlas_2018%2Chnsc_tcga_pan_can_atlas_2018%2Ckich_tcga_pan_can_atlas_2018%2Ckirc_tcga_pan_can_atlas_2018%2Ckirp_tcga_pan_can_atlas_2018%2Clihc_tcga_pan_can_atlas_2018%2Cluad_tcga_pan_can_atlas_2018%2Clusc_tcga_pan_can_atlas_2018%2Cmeso_tcga_pan_can_atlas_2018%2Cov_tcga_pan_can_atlas_2018%2Cpaad_tcga_pan_can_atlas_2018%2Cpcpg_tcga_pan_can_atlas_2018%2Cprad_tcga_pan_can_atlas_2018%2Csarc_tcga_pan_can_atlas_2018%2Cskcm_tcga_pan_can_atlas_2018%2Cstad_tcga_pan_can_atlas_2018%2Ctgct_tcga_pan_can_atlas_2018%2Cthym_tcga_pan_can_atlas_2018%2Cthca_tcga_pan_can_atlas_2018%2Cucs_tcga_pan_can_atlas_2018%2Cucec_tcga_pan_can_atlas_2018%2Cuvm_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=all&gene_list=KRAS%253A%2520MUT%2520%253D%2520G12D&geneset_list=%20&tab_index=tab_visualize&Action=Submit
). 
![image](https://user-images.githubusercontent.com/745885/86097100-7a7b4500-bab4-11ea-9a1a-74f95eb89f78.png)

**Comment by alisman** [comment]
@pvannierop there should actually be horizontal scrolling, with scroll bar at bottom.  i just tested it and it worked.  i do see problem with tooltip placement.

Another problem with scroll is that scrollbar is at bottom where it is hard to see.  @jtquach1 maybe you can use the strategy that @adamabeshouse used here:
https://github.com/cBioPortal/cbioportal-frontend/pull/3414

Would be nice if we could standardize this for all our charts.

**Comment by jtquach1** [comment]
> @pvannierop there should actually be horizontal scrolling, with scroll bar at bottom. i just tested it and it worked. i do see problem with tooltip placement.
> 
> Another problem with scroll is that scrollbar is at bottom where it is hard to see. @jtquach1 maybe you can use the strategy that @adamabeshouse used here:
> [cBioPortal/cbioportal-frontend#3414](https://github.com/cBioPortal/cbioportal-frontend/pull/3414)
> 
> Would be nice if we could standardize this for all our charts.

Thanks Aaron, I'll check Adam's solution out.

**Comment by alisman** [comment]
@pvannierop tooltips are now fixed.  scroll bar is just difficult to see.   for another chart, we were able to move scrollbar to top.  this is not native behavior unfortunately.   but we should be able to accomplish this generally for all charts.  will open another issue.
