### ISSUE TITLE
Cannot read property 'uniquePatientKey' of null Error 

### ISSUE THREAD

**Issue by cannin** [cBioPortal/cbioportal#7665]
Using the cBioPortal 3.4.0 as a Docker image. I tried loading the "chol_nccs_2013" site from GitHub datahub. After selecting genes (KRAS specifically, in the dataset) and submitting a query for Query by Gene. I end up with a white screen with the following error: 

Cannot read property 'uniquePatientKey' of null

See screenshot for full error. The dataset was imported with some warnings but no errors. Is there a better way to present the error with instructions on dealing with it? 

<img width="1392" alt="Screen Shot 2020-07-01 at 10 08 12 AM" src="https://user-images.githubusercontent.com/790284/86254164-72d6a180-bb83-11ea-8a83-2ee74d9b281d.png">

**Comment by jjgao** [comment]
@cannin I am wondering if you have figured out the issue?

**Comment by cannin** [comment]
@jjgao I have not. At a minimum if @alisman could try to replicate the error with Docker and the described dataset that would be nice. Is it just me? I'm using the Dockerized method for installing and a datahub dataset. To make it easier, I put my Docker commands and portal.properties here: https://gist.github.com/cannin/638ae8f2c4c77151a562052c5852f453
