### ISSUE TITLE
versioning of seed DB

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#767]
It would be nice to have some information about the date of when the seed database (https://github.com/cBioPortal/cbioportal/wiki/Downloads#seed-database) was generated. It would also be nice if previous versions remain available for a while.

**Comment by pieterlukasse** [comment]
Assigned to @sheridancbio just because he was the last one to change the page mentioned above. @jjgao : please comment on this, maybe it is something you are already working on?

**Comment by zheins** [comment]
We're working on this. See Issue #517

**Comment by coursera-test** [comment]
Would it be useful to use liquibase (http://www.liquibase.org/) for versioning the database? Issue #517 is just about cleaning up.

**Comment by Sjoerd-van-Hagen** [comment]
How about using Liquibase (http://www.liquibase.org/) for versioning the database? Issue #517 is just about cleaning, not about versioning.

**Comment by pieterlukasse** [comment]
@zheins: there is still only one link in https://github.com/cBioPortal/cbioportal/wiki/Downloads#seed-database. It would be nice to label this download link with some extra information like: what cBioPortal release is this (e.g. 1.1.0 or 1.2.0...) and what other data has been updated in the seed (e.g. latest gene information has been added, new pfam regions, etc). Having well prepared and up to date seed db available is useful for people installing cBioPortal. But maybe this is something to be addressed via docker images now that we are dockerizing the solution (see also #925)?
@jjgao : what do you think?

**Comment by jjgao** [comment]
@pieterlukasse good idea about some labeling. Ideally, we should support multiple versions.

**Comment by ecerami** [comment]
For now, I would vote for the simplest option that we can do quickly.  e.g. it seems that once we merge all of the hyve's lastest work from rc to master, "regular" users will not be able to follow the wiki steps, because the seed database will be out of sync.

**Comment by pieterlukasse** [comment]
@jjgao : is this something you and your team could do? I.e. make a new release of the seed DB for 1.2.1? And perhaps update the `gene` and `gene_alias` (and related tables) in the seed as well? (Regarding this last part, I'm not so sure how to deal with revoked/removed genes. Do you keep them to support old datasets?)

**Comment by jjgao** [comment]
@pieterlukasse we will do that when we build the new database very soon.

**Comment by jjgao** [comment]
closing this since it's too old.
