### ISSUE TITLE
Store chromosome length elsewhere?

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7674]
Had a few times now that http://hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/hg19.chrom.sizes was down, which is used by the validator. It just contains chromosome length and the files are pretty small, so we might as well store it in the repo? Or maybe it makes sense to have these lengths in the database?

**Comment by jjgao** [comment]
@inodb maybe we can add them to genome nexus? could be just in our git repo?

**Comment by inodb** [comment]
@jjgao looks like @SRodenburg just fixed this in #7796. It puts the JSON in the cBioPortal repo + adds a script to update it. It gets bundled with the container. Since it's pretty small, I think it's ok to store a copy

**Comment by jjgao** [comment]
sounds good.
