### ISSUE TITLE
Study View Clinical Attribute Data Download does not include NA samples

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#7675]
I found the issue in https://cbioportal.mskcc.org/study/summary?id=mskimpact
If you search
mskimpact:P-0048017-T03-IM6
mskimpact:P-0048148-T03-IM6

The download of Oncotree Code does not include anything.

Is this the intention or a bug?
@jjgao

**Comment by jjgao** [comment]
I think it's data issue. About 2% of the samples do not have an oncotree code.

![image](https://user-images.githubusercontent.com/840895/86953683-c23c4500-c122-11ea-9130-ee7a28fff45d.png)
