### ISSUE TITLE
TypeError: can't access property "map", t[e.studyId] is undefined

### ISSUE THREAD

**Issue by hissingpanda** [cBioPortal/cbioportal#7676]
When importing a custom study, the study passes validation and is imported successfully and the summary page shows data correctly, but upon going to the clinical data tab of the study no results are shown as in the attached screenshot. The javascript console gives the following error: "TypeError: can't access property "map", t[e.studyId] is undefined"

![cbio](https://user-images.githubusercontent.com/7660115/86953886-f3f4e200-c109-11ea-97ec-a9722bb073ab.png)
![cbio3](https://user-images.githubusercontent.com/7660115/86954767-6b774100-c10b-11ea-838d-2362a48326bd.png)
 
Any ideas as to what might be wrong with the import? Studies from datahub are working correctly. I'm using only the meta_study, meta_clinical and data_clinical files.

**Comment by alisman** [comment]
@hissingpanda , I think our best bet is to jump on a screen share to debug what's going on.   Let me know your availability tomorrow or next week.

**Comment by hissingpanda** [comment]
@alisman Thanks so much! I solved it by adding a meta_mutations and an empty mutations_extended files and the data table now shows.  So I'm assuming it has something to do with the patient and sample ID links to mutation data breaking when there is no mutation data. Happy to go over this on a screen share anytime Monday or Wednesday next week if that shouldn't be the expected functionality.

**Comment by jjgao** [comment]
@hissingpanda we definitely require some molecular data profiles.
