### ISSUE TITLE
Replace toast with banner in Pathways tab

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#7677]

**Comment by ugurdogrusoz** [comment]
@msalihaltun a couple of issues with the banner:
- [ ] 1. There are actually more than 3 genes in this case that is not valid but we only list 3 and truncate the rest; need a scrollbar (which shouldn't increase the height of the banner much and should definitely not *shift* toolbar, pathway name and the canvas):
<img width="700" alt="Screen Shot 2020-12-17 at 19 23 24" src="https://user-images.githubusercontent.com/3874988/102514296-5b419580-409d-11eb-9184-73f726bb05b3.png">

- [ ] 2. When a new message appears as a banner, should we remove existing one(s)? For instance, after the above message, if you switch to a pathway which requires loading alteration data, we get a green banner for a while on top of this one and when done, this one becomes visible again.

**Comment by ugurdogrusoz** [comment]
@onursumer This should be good to go.
