### ISSUE TITLE
RFC for adding expression data from normal samples

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7687]
https://github.com/cBioPortal/cbioportal/issues/7528

**Comment by kalletlak** [comment]
@jjgao here is the RFC https://docs.google.com/document/d/1YdS3b3qJLHXnsS84qjDWlfWPCClLP9bhxA7mj5xXhv4

**Comment by jjgao** [comment]
@kalletlak I have updated the proposal sections with mockups. Kicking back to you for the implementation part :)
