### ISSUE TITLE
Copy number Gain not shown in oncoprint

### ISSUE THREAD

**Issue by sophie2046** [cBioPortal/cbioportal#7688]
Hi there,

I am not seeing the copy number GAIN (i.e., gistic cna=1 instead of amplification where gistic cna value is 2) being shown in the oncoprint in the current version. I somehow remember it used to be displayed in older version though. Since the samples with copy number gain are shown in the plot tab, can we also show it in the oncoprint? 

Update: 
To make it more clear, I installed my own instance of cbioportal locally. I would like to make it like https://www.cbioportal.org/oncoprinter  that can show the gain and shallow deletion. Please let me know how to turn this feature on in my local copy.

**Comment by jjgao** [comment]
Hi @sophie2046, gain nd shallow deletion are not shown in OncoPrint by default. You would have to use OQL (https://www.cbioportal.org/oql) to show them, e.g. "TP53: HETLOSS" or "EGFR: GAIN".
