### ISSUE TITLE
tutorials: add back link to google drive folder

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7711]
It looks like in re-designing the Tutorials/Webinars page, we lost the link to the google drive folder where the slides live. Given that we provide PDFs to download its not super important, but I think it's a nice option to provide. Can we add that back?

Link: https://drive.google.com/drive/folders/0B9KTQJAGhFhhRi1qaTdUWmpLQTA

**Comment by inodb** [comment]
@tmazor where should we add it e.g. here (bottom right)?

<img width="759" alt="Screen Shot 2020-08-03 at 2 29 49 PM" src="https://user-images.githubusercontent.com/1334004/89215026-dc3c3c80-d595-11ea-93b7-a8d703705085.png">

**Comment by tmazor** [comment]
@inodb I think that works - but how about using this for the text: "View slides" and "Download PDF"
