### ISSUE TITLE
Create users based on LDAP

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#7712]
We have an internal cBioPortal server in an institution of about 3000 users. We would like to publish studies that would be accessible to all of them. Currently we would have to query LDAP, create a record in users table for each user and do this everytime there is a change in users (in principle every day).
 
Is it possible to configure LDAP so that if a user successfully authenticates (against LDAP or other provider) cBioPortal would automatically create the user so that they can access the public studies on the instance?

**Comment by jjgao** [comment]
@j-hudecek Currently not possible. For some of our local instances, we have cron-job to insert the records. If you would like to remove that process, it would require some code change, e.g. allow all users to access studies with group of PUBLIC (or maybe make the group name configurable).
