### ISSUE TITLE
Plots tab error when querying multiple studies

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7713]
I selected all TP53 mutated samples in all TCGA PanCancer Atlas project and query TP53. The [OncoPrint tab](https://www.cbioportal.org/results?Action=Submit&data_priority=0&plots_coloring_selection=%7B%7D&plots_horz_selection=%7B%7D&plots_vert_selection=%7B%7D&session_id=5e9f6e08e4b0ff7ef5fe0ba4&tab_index=tab_visualize) works, but not the [Plots tab](https://www.cbioportal.org/results/plots?Action=Submit&data_priority=0&plots_coloring_selection=%7B%7D&plots_horz_selection=%7B%7D&plots_vert_selection=%7B%7D&session_id=5e9f6e08e4b0ff7ef5fe0ba4&tab_index=tab_visualize)

![image](https://user-images.githubusercontent.com/840895/88307307-c6975f00-ccd9-11ea-90b4-a3f020cbcea8.png)

**Comment by dippindots** [comment]
I will take a look this error today.
