### ISSUE TITLE
Plots tab: support methylation and protein for cross-study query

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7715]
... and maybe generic assay too.

**Comment by dippindots** [comment]
@jjgao Based on the discussion with @kalletlak today on the meeting, should we remove this issue from this sprint and save this issue for the future?

**Comment by jjgao** [comment]
@dippindots this is different - we discussed it for Comparison tab. For Plots tab, we should still support them.

**Comment by dippindots** [comment]
@jjgao Oh I see, this is for the plots tab. I think the current implementation can support cross-study query for `Methylation` and `Generic Assay`. For example, this is a [link](http://www.cbioportal.org/results/plots?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=acc_tcga%2Cbrca_tcga&case_set_id=all&data_priority=0&gene_list=CDKN2A%2520MDM2%2520MDM4%2520TP53&geneset_list=%20&plots_coloring_selection=%7B%7D&plots_horz_selection=%7B%22dataType%22%3A%22PROTEIN_LEVEL%22%7D&plots_vert_selection=%7B%7D&profileFilter=0&tab_index=tab_visualize) for `Methylation`.

**Comment by jjgao** [comment]
ah, thanks! I think I was trying pancan studies and they don't even have protein or methylation data (:slapping-face)
