### ISSUE TITLE
Importing a mutation sample without clinical data causes issues

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#772]
If mutation data contains samples which are not listed in the clinical data file cBioPortal counts mutations in the sample but doesn't add them to the total. This causes genes to have (on study view) mutation frequency > 100% and when a gene is mutated only in these samples selecting it in the mutated genes view results in 0 samples selected. 

Importing mutation sample without clinical data should be an error.

**Comment by jjgao** [comment]
@zheins we should add this to the validator.
