### ISSUE TITLE
Implementation plan for Adding mutations and CNA gene charts to study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7727]
Start by creating the CNA pie chart. Later we can figure out what we want to do for the mutations
chart.
1. Add a CNA filter to the StudyViewFilter
1. Add logic to the StudyViewFilterApplier. Mock services, do not implment them.
1. Create a mock API by fully implementing the controller classes, and calling the mock services
1. Create the pie chart in the frontend
1. Implement the service, repo, and mapping layer

**Comment by Luke-Sikina** [comment]
Start by creating the CNA pie chart. Later we can figure out what we want to do for the mutations
chart.
1. Add a CNA filter to the StudyViewFilter
1. Add logic to the StudyViewFilterApplier. Mock services, do not implment them.
1. Create a mock API by fully implementing the controller classes, and calling the mock services
1. Create the pie chart in the frontend
1. Implement the service, repo, and mapping layer

**Comment by inodb** [comment]
See https://github.com/cBioPortal/cbioportal/issues/6759
