### ISSUE TITLE
Add additional info when you click on waypoints

### ISSUE THREAD

**Issue by Luke-Sikina** [cBioPortal/cbioportal#7734]
For now, let's make a div that goes to the left of the map that contains the following information in a list:
- Org name
- City
- Bio
The div can be there before anything is clicked, just leave it blank.

**Comment by Luke-Sikina** [comment]
Looks done to me

**Comment by jtquach1** [comment]
Before clicking on waypoint: 
![image.png](https://images.zenhubusercontent.com/5efcdc21bf8df70aecbb4b57/246f46ab-1113-448c-9408-b8642305ae43)

After:
![image.png](https://images.zenhubusercontent.com/5efcdc21bf8df70aecbb4b57/94627ddb-502d-4058-a319-8fcfc12e5a1b)
