### ISSUE TITLE
Mutations found in overview, but 0 mutations shown in gene query

### ISSUE THREAD

**Issue by NikdAK** [cBioPortal/cbioportal#7740]
Hi,
I am working with a mouse database (seed mm10_v2.3.1) and successfully imported some mutation data. 

Here is the study summary overview 
(including the two genes I will use an examples below; Rrs1 and Zfp981):
![0](https://user-images.githubusercontent.com/39265538/88811084-6cedd380-d1b6-11ea-88b8-e10457694bbb.png)

If I query for specific genes I will find mutations in the OncoPrint and top-right summary ("query gene altered in..."):
![4](https://user-images.githubusercontent.com/39265538/88811655-1fbe3180-d1b7-11ea-82e3-2c2d1d0dad6f.png)

BUT, in the mutation tab there are "0 mutations" found. This happens for all known genes, not only this example.
![1](https://user-images.githubusercontent.com/39265538/88811792-47ad9500-d1b7-11ea-970a-7fce58f818e1.png)

Interestingly for some genes (without found transcripts) I get this:
![3](https://user-images.githubusercontent.com/39265538/88811911-6d3a9e80-d1b7-11ea-9f51-fc69737d8c5f.png)

Further, if I try to download the mutation data, the matrix will contain only NAs for Rrs1 but "C192Y" for Zfp981.
How can this happen? Any suggestions?

I attached the input mutation data for those 2 genes here: [issue_maf_example.txt](https://github.com/cBioPortal/cbioportal/files/4995400/issue_maf_example.txt)

Thank you very much!
Cheers

**Comment by inodb** [comment]
Thanks for reaching out @NikdAK! You might have found a bug. Could you let us know what version of cBioPortal you are using? You can find it on /api/info of your cBioPortal instance, e.g. https://www.cbioportal.org/api/info

**Comment by NikdAK** [comment]
I am using 3.4.4 in general, with:
portalVersion	"3.4.4-dirty-SNAPSHOT"
dbVersion	"2.12.6"
gitBranch	"1b28db39c73df445d6a8f50a2a1bbddef30be3a6"

and mm10_v2.3.1


Regarding your suggestion: I created a new instance with v3.4.2 and it works as expected
![fix342](https://user-images.githubusercontent.com/39265538/89273662-237f0780-d640-11ea-867e-82e2f4074954.png)



For my main database, I can wait until this bug is fixed. Can I provide you more information to help you solve this issue?

**Comment by leexgh** [comment]
@NikdAK Yes that would be great, please provide us more information, thank you!

**Comment by NikdAK** [comment]
@leexgh 
Well, it would be great to know what kind of information you need. 

The problem is apparently in the new version 3.4.4 combined with the mouse seed database. 

Mouse with 3.4.2 works, and my human hg19 seed database works normal with the newest 3.4.4.

**Comment by leexgh** [comment]
@NikdAK Thanks, could you provide console errors and genome nexus query URLs from network?

**Comment by inodb** [comment]
@NikdAK Some more questions:

1. Are you running your own mouse instance of genome nexus (see https://github.com/genome-nexus/genome-nexus)? We currently don't host a mouse instance of genome nexus ourselves. If you are using the v1.genomenexus.org instance (which is the default), the transcript visualization is based on the human transcript. Maybe that's ok for your use case, but I imagine it might result in some issues
2. We recently merged a fix that might address your issue. You can try it on your instance by typing in the browser console `localStorage.netlify = 'master--cbioportalfrontend'`. This will load the latest frontend version. (this is the PR that might have fixed it https://github.com/cBioPortal/cbioportal-frontend/pull/3341)

**Comment by NikdAK** [comment]
Sorry for the confusion, I am using a local docker container, based on https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker.
Therefore I can not supply any nexus error logs. 

Is there a way to anyways use your solution based on localStorage.netlify? 
Thanks

**Comment by inodb** [comment]
@NikdAK No worries! Loading the new frontend using `localStorage.netlify` should work with that docker container setup. When you open your local docker version of cBioPortal in e.g. Chrome, you can open up the console with `View > Developer > Developer Tools`. Then you should be able to type in the console: `localStorage.netlify = 'master--cbioportalfrontend'`. You should see something like:

<img width="976" alt="Screen Shot 2020-08-04 at 4 12 04 PM" src="https://user-images.githubusercontent.com/1334004/89340254-7327f800-d66d-11ea-93e1-295083821cb4.png">

You can disable it again by clicking "clear".

**Comment by inodb** [comment]
But yeah note that the transcript you are seeing in the mutations tab when you follow the default instructions is the human one. To get proper mouse transcripts you would have to set up a genome nexus instance for mouse, see https://github.com/genome-nexus/genome-nexus. We haven't fully documented how to do that yet. Only the mutations tab has that issue afaik, the other pages and tabs should work fine

**Comment by NikdAK** [comment]
This works, thank you very much! After opening the console (Control+Shift+J) and changing localStorage.netlify I get the desired view with mutations and lollipop plot. Is there a way to set this as default for "non-dev" users? 

Are you planning to (soon) implement mouse transcripts to the version I am currently using or do you recommend to switch to nexus?
Also why do I miss the transcript change drop-down menu (below the gene name in mutations view)?

**Comment by leexgh** [comment]
@NikdAK For your last question, we hide transcript change dropdown by default, you can turn it on by adding this(or uncomment it if it's already in the file) to your `portal.properties` file:
```
show.transcript_dropdown=true
```
@inodb Could you help with other questions?

**Comment by inodb** [comment]
@NikdAK Glad to hear this solves the issue! The PR should be included in 3.4.6: https://github.com/cBioPortal/cbioportal/releases/tag/v3.4.6. So if you upgrade to that version it should be fixed.

We are unfortunately not planning to host the mouse transcripts version of genome nexus ourselves soon. I would recommend to set up your own version of genome nexus

**Comment by inodb** [comment]
@NikdAK closing this, because I think the original issue has been solved. Feel free to re-open if you are still experiencing issues. Thanks for reporting!
