### ISSUE TITLE
Add download option to lollipop plot (on mutation tab)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7742]
The lollipop plot on mutation tab currently has no download data option.  The data should be same as is available in mutation table below.  Lets just access that same data.

![image](https://user-images.githubusercontent.com/186521/88834036-39547e80-d1a1-11ea-902f-8a9c3e18975b.png)

https://www.cbioportal.org/results/mutations?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations

**Comment by jagnathan** [comment]
Comments: The download functionality has to be implemented in the pages and not the component. Study name should be visible along with study Id.

**Comment by jagnathan** [comment]
[https://app.zenhub.com/files/32481543/203c7b59-837a-42c6-9532-263e5a902d13/download](https://app.zenhub.com/files/32481543/203c7b59-837a-42c6-9532-263e5a902d13/download)

**Comment by jagnathan** [comment]
Attached the sample download file

**Comment by inodb** [comment]
Supporting same download as mutations table was too tricky. Decided not to support data download for this chart instead

**Comment by jagnathan** [comment]
https://github.com/jagnathan/cbioportal-frontend/commit/879b725803e79e7362ab571642420a9746e58073

The above commit has all the changes required to have the raw Mutation data in TSV format. In addition, the study name column has been added.
