### ISSUE TITLE
When there a single day has more than one event (in a single track) show small number above datapoint

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7749]
![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/24acf100-6d93-4f56-b9ce-18c4422027cf)

**Comment by adamabeshouse** [comment]
how do we handle this if there are multiple items with different specific render functions? @alisman

**Comment by adamabeshouse** [comment]
done in https://github.com/alisman/cbioportal-frontend/pull/31
