### ISSUE TITLE
Validator Entrez Gene Id issue 

### ISSUE THREAD

**Issue by colinmiller20** [cBioPortal/cbioportal#7763]
I am loading in mutation data. Currently the loaded study is missing significant data, even though the gene ids agree with those at NCBI

WARNING: data_mutations_extended.maf: lines [2, 3, 4, (1440 more)]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; values encountered: ['23224', '9496', '242', '(1037 more)']

I can include the other warnings if it is helpful, but I thought the one above was responsible for the data missing: 

WARNING: data_mutations_extended.maf: lines [81, 134, 234, (9 more)]: Gene symbol not known to the cBioPortal instance. This record will not be loaded.; values encountered: ['UGT2A1;UGT2A2', 'LOC100506127', 'TMEM189;TMEM189-UBE2V1', '(6 more)']

WARNING: data_mutations_extended.maf: lines [447, 755, 898, (6 more)]: No Amino_Acid_Change or HGVSp_Short value. This mutation record will get a generic "MUTATED" flag

INFO: data_mutations_extended.maf: Validation of file complete
INFO: data_mutations_extended.maf: Read 1456 lines. Lines with warning: 1456. Lines with error: 0

Please let me know if I can include anything else to help resolve this issue!

**Comment by jjgao** [comment]
Hi @colinmiller20 for mutation data / MAF, we recommend annotate the file with https://github.com/genome-nexus/genome-nexus-annotation-pipeline/, which will hopefully resolve most of the issues.
