### ISSUE TITLE
Error in tracking_include.jsp

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#7765]
User reported: https://groups.google.com/forum/#!topic/cbioportal/YY3T45Ws2A4

This might be related to https://github.com/cBioPortal/cbioportal/pull/6861 which is released in [v3.4.6](https://github.com/cBioPortal/cbioportal/releases/tag/v3.4.6)

**Comment by jjgao** [comment]
@kalletlak I added it to the sprint-backlog since you add it to this sprint. Are you working on it or do we need help from @Luke-Sikina and @alisman ?

**Comment by kalletlak** [comment]
@jjgao just created pr
