### ISSUE TITLE
genie v8 is slow

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7769]
GENIE data keeps growing and we've gotten slow again :(

IDH1, IDH2, TET2 in all samples: https://bit.ly/3fxhaQk
3min 20sec for first load
2min 20sec for reloading
2min 20sec for reloading again

NRAS in all samples: https://bit.ly/33Ca1fp
1min 20sec for first loading
2min 10 sec for reloading
4min 30 for reloading again
2min 50sec for reloading again

Study view
2min 40sec for first load
1min 40sec for reloading
1min 40sec for reloading again

**Comment by jjgao** [comment]
From Ben: "We’re working on it - as you know we are planning a thorough effort to improve backend.  For GENIE we are in the middle of introducing REDIS as persistence cache, but we put that on hold to get the Sage authentication working for BPC.  We’ll pick that up in a few weeks."

**Comment by jjgao** [comment]
@tmazor is this one related to https://github.com/cBioPortal/cbioportal/issues/8026?

**Comment by tmazor** [comment]
Potentially @jjgao  - I didn't look at the breakdown of why requests were so slow when I made this ticket, but upload speed could certainly have been part of it

**Comment by n1zea144** [comment]
Closing issue.  This is #8026 and addressed by #8099
