### ISSUE TITLE
Timeline should redraw on window resize 

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7771]
Right now, if you make window smaller, we get scrollbar on timeline data pane.  THat's ok.   But when we make window larger, it doesn't expand to fill.  Probably best thing would be just to redraw on window resize.  I don't even think we need to persist zoom state

**Comment by jjgao** [comment]
I added this to the next milestone. Please change it if you plan to work on it sooner.

**Comment by adamabeshouse** [comment]
fixed in https://github.com/alisman/cbioportal-frontend/pull/31
