### ISSUE TITLE
junit testreport potentially misses some tests?

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7777]
https://junit-history.herokuapp.com/?branch=master shows 469 tests:

![Screen Shot 2020-08-11 at 8 55 50 AM](https://user-images.githubusercontent.com/1334004/89901010-76ae0880-dbb2-11ea-97f5-ea457cfa0de3.png)

But in this last run there are 472:

![Screen Shot 2020-08-11 at 9 09 28 AM](https://user-images.githubusercontent.com/1334004/89900966-672ebf80-dbb2-11ea-8767-f196321dd6b9.png)

https://app.circleci.com/pipelines/github/cBioPortal/cbioportal-frontend/1459/workflows/4f8c625d-7ffa-4bb2-b385-d3c63a4cc317/jobs/78788/tests

There are also two failures in that run, whereas the dashboard shows one

Maybe because the name of the test is identical?

`gives a submit error if protein oql is inputted and no protein profile is available for the study`

(EDIT note that these tests were just disabled: https://github.com/cBioPortal/cbioportal/issues/7776)

**Comment by jjgao** [comment]
@alisman @inodb should we keep this open?
