### ISSUE TITLE
Hide/show timeline track groups

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7784]
We need to add ability to collapse/expand groups of timeline tracks.   I see this working in two ways:

1. Tracks that have children can have standard +/- icon that allows user to expand children.  When a track is collapsed only the parent shows.  We might want to add some very feint text to the track to show that it is hidden

2. The above leaves the parent track showing.  Perhaps we also want to have a dropdown checklist that allows user to actually remove parent tracks entirely.  They can then restore them using the dropdown.

**Comment by inodb** [comment]
@alisman Just to double check: these aren't mutually exclusive, right? You are proposing we could do both? I.e. one option for collapsing/expanding groups. One option to show/hide tracks?
