### ISSUE TITLE
Add CNSegments and coexpression tab localdb test

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7787]
The CNSegments and coexpression tab haven't been working when the frontend is served from inside the war even before v3.4.0. We might be able to avoid this by adding tests to localdb. I am not sure whether the localdb test on the backend repo uses the frontend included in the war, but if so we can use that.

Add localdb tab tests for:

- CNSegments
- Coexpression

**Comment by jjgao** [comment]
@adamabeshouse could you help with this?

**Comment by adamabeshouse** [comment]
@inodb I cant get the coexpression tab to appear in any localdb query, any advice?
