### ISSUE TITLE
refactored timeline comments

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7794]
The new timeline is awesome @alisman ! There are so many little improvements that I love in this new version.

Here are a few things I've noticed in comparing to the old timeline. Some of these changes may have been done on purpose and that's fine, but I wanted to make note of any difference that I found.

1. - [x] Tooltips are white text on a black background - but tooltips everywhere else on the site are black text on a white background
2. - [x] Looks like the new timeline doesn't extend to the date of death/last follow up?
![image](https://user-images.githubusercontent.com/10508276/90084365-1d91c200-dce3-11ea-8c4a-b224bb9efe0a.png)
3. - [x] When the timeline is compressed and has that zigzag thing, the old timeline allows a user to click on the zigzag and show the full timeline, but the new one doesn't let me do that
![image](https://user-images.githubusercontent.com/10508276/90084339-05ba3e00-dce3-11ea-8ce0-40286ab693da.png)
4. - [x] Tooltips towards the right of the timeline extend beyond the window
![image](https://user-images.githubusercontent.com/10508276/90084315-fc30d600-dce2-11ea-8b27-03104765589c.png)
5. - [x] Looks like we are forcing title case on the therapy names? In the screenshot below, TMZ, CCNU & XRT should all be full uppercase (they are correct in the tooltips)
![image](https://user-images.githubusercontent.com/10508276/90084453-5df14000-dce3-11ea-9394-41380e7ebc8d.png)
![image](https://user-images.githubusercontent.com/10508276/90084599-bf191380-dce3-11ea-9c93-9398b4962152.png)
6. - [x] Not sure if this is data or UI, but the tooltip says this is XRT, but it's listed as "Other"
![image](https://user-images.githubusercontent.com/10508276/90084718-17e8ac00-dce4-11ea-8fc1-35802e56b626.png)
https://www.cbioportal.org/patient?caseId=P04&studyId=lgg_ucsf_2014
7. - [x] Looks like the dot for Imaging Assessment is colored blue whenever there are multiple? This makes it a bit harder to get a sense of the overall progression - could the color instead be representative of the status of the multiple assessments? e.g if all assessments are the same status, then this dot could also be that status color, and if the multiple events are discordant, it could be yellow for mixed?
![image](https://user-images.githubusercontent.com/10508276/90086528-a19a7880-dce8-11ea-8a8d-e04094d15cad.png)
8. - [x] Is this real data? The tooltip here doesn't make sense - "Image Overall" says no mention of cancer, but "Image CA" says there is evidence of cancer. Or maybe I just don't understand what those fields are supposed to represent. If this is real & accurate data, then there might be an opportunity here to label some of these fields more clearly.
![image](https://user-images.githubusercontent.com/10508276/90086876-749a9580-dce9-11ea-8dff-738c6c8696a7.png)
https://genie-private.cbioportal.org/patient?caseId=GENIE-MSK-P-0009680&studyId=genie_bpc_test
9. - [x] Timeline label is cutoff on the right edge
![image](https://user-images.githubusercontent.com/10508276/90087205-35207900-dcea-11ea-97ec-37a7660dd59d.png)
https://genie-private.cbioportal.org/patient?caseId=GENIE-MSK-P-0009680&studyId=genie_bpc_tes
10. - [x] PDF download doesn't look good [ ADAM NOTE: I think this is because I'm using the CSS transform attribute everywhere instead of the SVG element transform attribute ]
![image](https://user-images.githubusercontent.com/10508276/90087261-541f0b00-dcea-11ea-8606-d10d75097b15.png)
11. - [ ] This is more of a new feature request, but it might be nice to include a legend in the downloads to explain the colors of the dots in the Med Onc/Imaging Assessment rows

**Comment by alisman** [comment]
@jjgao @tmazor on #8 above, yes that is real data.  so, would need to be addressed in data
![image](https://user-images.githubusercontent.com/186521/90259476-16200500-de18-11ea-851d-ef2bfa9f17d1.png)

**Comment by alisman** [comment]
@jjgao @inodb @tmazor  for #2, regarding date of death, we decided we were going to do this in data, instead of hacking in from clinical data.

**Comment by tmazor** [comment]
Follow-ups on the above:
2. Makes sense as a data update - I would just add that it would be nice to have the data updates in place before going live with this, since those death/last follow up dates are important in a timeline
3. Still doesn't work, but I guess the code isn't merged yet?
8. Good to know that's real data. I'm not super familiar with PRISSMM output, but this does seems like an opportunity to improve how we're presenting the output. @jjgao do you know what those fields are supposed to mean?
Everything else's that's checked off looks good to me!

And two more small things:
12. Minor, but it would be nice to make this tooltip wider so more of the first column can be in a single line
![image](https://user-images.githubusercontent.com/10508276/90447026-7630d880-e0b0-11ea-955d-9ed093296fbe.png)
https://www.cbioportal.org/patient?caseId=P02&studyId=lgg_ucsf_2014#
13. There's a big gap in the timeline markings after the zig-zag
![image](https://user-images.githubusercontent.com/10508276/90448249-ffe1a580-e0b2-11ea-8b73-76b3064f2f2e.png)
https://www.cbioportal.org/patient?caseId=P15&studyId=lgg_ucsf_2014
