### ISSUE TITLE
Study with clinical data only fails to load since v3.2.11

### ISSUE THREAD

**Issue by AndyBlake** [cBioPortal/cbioportal#7800]
Hiya
I have a study that only contains clinical patient data which loads and displays fine on 3.2.10 but some change in v3.2.11has broken the study summary page as shown in pictures.
![3 2 10](https://user-images.githubusercontent.com/1448122/90252593-ac175800-de37-11ea-9941-cf055cf454eb.PNG)
3.2.10 everything fine
![3 2 11](https://user-images.githubusercontent.com/1448122/90252600-af124880-de37-11ea-8624-9aa3452d0ff1.PNG)
3.2.11 sample and patient numbers fail to load and the group panel also fails
![3 4 8](https://user-images.githubusercontent.com/1448122/90252611-b2a5cf80-de37-11ea-9d59-f6cb57dd7091.PNG)
3.4.8 same issue
Can this be fixed please?

**Comment by inodb** [comment]
@AndyBlake seems like an issue with the session-service connection.

Some thoughts/questions:

- Could you check the network tab in your browser and see what error it gives?
- It might also help to check the logs in the session-service
- If it's only that specific study that's failing it might be related to specific data for that study in the session-service database. You could try to deploy a session service with an empty database to see if that makes the issue go away?

Maybe @kalletlak has some more thoughts on how to debug

**Comment by AndyBlake** [comment]
Thanks for getting back to me - I'll check and get that info to you. Perhaps we are seeing a problem with the lack of genomic data causing the summary to fail rendering the genomic summary panel which then has knock on effect on the rest of the js causing the session setup to fall over? The session service works fine on other studys. Just a guess really. - I'll add some mutations to that study to see if it fixes everything as a way to isolate the issue.

**Comment by AndyBlake** [comment]
Hiya
I added a mutation to one of the samples and it fixes everything.
![with one mutation added](https://user-images.githubusercontent.com/1448122/90274353-51dabf00-de58-11ea-9b34-f3d1cb8e3c56.PNG)

**Comment by inodb** [comment]
Thanks for sharing @AndyBlake - so I guess the issue is that the study view doesn't work if it only contains clinical data?

**Comment by AndyBlake** [comment]
Yeah - I guess not your typical use case but cbioportal is really good for
viewing clinical and summary data before the genomic data is available.
Could a check be added to make it fail less terminally in this case? Thanks
for your time.
Kind regards
Andy

**Comment by inodb** [comment]
@AndyBlake Def - thanks for reporting!

**Comment by jjgao** [comment]
I created an issue and see if we can support study view w/o profiles: https://github.com/cBioPortal/cbioportal/issues/7814
