### ISSUE TITLE
Add a table of survival types to Survival tab in Comparison

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7805]
The AACR GENIE BPC cohort may contain dozens of different types of survival data. The current interface of the survival tab (see below) in Comparison may not work well when showing many survival types. 

Here is a proposal:

- [x] Get rid of the current Survival Types selection section
![image](https://user-images.githubusercontent.com/840895/90559587-c751d280-e16b-11ea-8b44-9d322a31d761.png)
- [x] When there are more 2 or more survival types, add a table to the left of the survival plot (similar to Clinical tab), with the following columns: `Survival Type`, `# Patients`, `p-Value`, `q-Value`
  - note: we may have to pull all data to the frontend upfront since p-values are calculated in the frontend
- [x] Click each row will show the survival plot. (by default, the first one is selected)
- [x] Allow changing x-axis depending on x-range (should be some option), right now all of them have the same length

@cBioPortal/product

current layout:
![image](https://user-images.githubusercontent.com/840895/90559853-3fb89380-e16c-11ea-9e6d-c0220c081c91.png)

**Comment by jjgao** [comment]
I forgot we haven't added p-values for survival analysis with 3 or more groups. @kalletlak has done some research in #7484 and it was not an easy task.

Maybe we can compute the pair-wise p-values and list the most significant ones? (not sure if q-value still holds - maybe we should not try to calculate q-values). We can also list some more data in the table, e.g. number of total cases and number of cases with event.

@kalletlak thoughts?

**Comment by schultzn** [comment]
Why not show all p-values, so the p-value for each pair? Just trying to understand why this isn’t an easy task?

**Comment by jjgao** [comment]
@schultzn we don't have the code to calculate p-values for three or more groups. Currently, the calculation is in frontend. We'll look into this more.

**Comment by adamabeshouse** [comment]
@jjgao as far as the interface, maybe we should keep the current interface when there's only 2 survival types, like most studies? otherwise it will be a lot of wasted space..

**Comment by jjgao** [comment]
> @jjgao as far as the interface, maybe we should keep the current interface when there's only 2 survival types, like most studies? otherwise it will be a lot of wasted space..

Good point. I think it's useful to have the p-values displayed even when there are only 2 types... Let's add the table first and see if we need to tweak when there are only a small number of survival curves (in most cases)?

**Comment by jjgao** [comment]
@adamabeshouse some additional product requests from @schultzn 

- [ ] Adding two columns per group (before the p-value column): `# in [group name]`, `median survived in [group name]`.
  - When there are many groups, this could get really wide. Should we consider a different layout of the tab? Or should we hide the group-specific columns by default? @schultzn 
- [ ] Add a filter that shows only comparisons with at least x patients (default 10) have data
  - For UI, maybe borrow from Cancer Types Summary page (minimum # total cases in each group: 10)?
  - This will affect q-value
- [ ] Add a configuration to display p/q-values in the table (on by default, but off for genie private portal)
  - p values should always be displayed in the plot as now.
- [ ] Add warning to the Survival tab: "Interpret all outcome results with caution, as they can be confounded by many different variables that are not controlled for in these analyses. Consider consulting a statistician."

**Comment by adamabeshouse** [comment]
Adding these from @alisman:

- [ ] put the survival data table, which is below the chart, inside the dashed border
- [ ] fixed with on the survival type table

**Comment by adamabeshouse** [comment]
okay @jjgao @schultzn all of the requested changes have been made
