### ISSUE TITLE
Move the Add Chart UI as another card in the Study View

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7807]
I'd like to propose to consider moving the `Add Chart` UI (see below) as another card/chart in the study view, to address two issues:

- The `Add Chart` menu is not predominant and people may not realize there are more clinical/genomic features they can add. Now that we are adding more and more features, e.g. gene-level and custom data, it would be good to promote the feature.
- It would be nice if we can select samples based on clinical data availability in the table. Currently, to select samples with certain clinical data, we have to select all the non-NA samples from each chart.

@cBioPortal/product @alisman @kalletlak @zhx828 @inodb 

===
Current Add Chart UI:
![image](https://user-images.githubusercontent.com/840895/90562805-cec7aa80-e170-11ea-972a-88f1b79804e7.png)

**Comment by alisman** [comment]
@jjgao I like this idea but I think it might need to be the first item in order to guarantee visibility?  Would it the same UI as in the current dropdown?  Or would we have a simple button call to action (Add Chart) in a 2x2 block?

**Comment by jjgao** [comment]
Closing this. @alisman will work out something better :)
