### ISSUE TITLE
Merging Expression tab into Plots tab?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7808]
Now that we support cross-study analysis (#7537), it is possible to reproduce the Expression tab analysis in Plots tab. The benefit of merging the Expression tab features into Plots tab is that we can support mRNA/protein/methylation vs any clinical attributes (Expression tab only support mRNA vs study). But the implementation of Plots tab needs to be improved. 

Here is a proposal:
To-do:
~- [] Move the horizontal scroll bar to the bottom~
- [x] Move "Sort Categories by Median" to Horizontal Axis
- [x] When there are few categories (e.g. cna vs mrna), is it possible to increase the boxplot width (similar to previously)?
- [x] add `mRNA vs Study`
- [x] select log scale by default for rna-seq (for any chart)
- [x] add redirection from Expression tab to Plots tab (mRNA vs Study)

Done:
- [x] Support selection of a subset of categories, e.g. cancer types (https://github.com/cBioPortal/cbioportal-frontend/pull/3427)
- [x] The x-axis in Expression tab is more compact - see below (https://github.com/cBioPortal/cbioportal-frontend/pull/3417) 
- [x] Adding Sort By options (for axis of categorical data): alphabetically, or by median value of the other axis (y-axis in this case) if the other axis is numerical (https://github.com/cBioPortal/cbioportal-frontend/pull/3416) 
  - q: where to put this option in the UI?
- [x] Fix the scrolling issue https://github.com/cBioPortal/cbioportal/issues/6698 (https://github.com/cBioPortal/cbioportal-frontend/pull/3414) 

@cBioPortal/product @alisman @dippindots @inodb @adamabeshouse 

====
Current Expression tab:
![image](https://user-images.githubusercontent.com/840895/90566541-ab076300-e176-11ea-928b-6afce80f4481.png)

Current Plots tab:
![image](https://user-images.githubusercontent.com/840895/90566716-f4f04900-e176-11ea-8bd9-b0165c5eb06a.png)

**Comment by adamabeshouse** [comment]
is it correct that you could currently use plots tab as an expression tab, minus all of the settings you mentioned above?

**Comment by jjgao** [comment]
@adamabeshouse that's correct.

**Comment by Sjoerd-van-Hagen** [comment]
> Support selection of cancer types (categories)
Is already possible.
> Can/should we add option of "Cancer Study" in the drop down?
I noticed a study of origin option, is that it?

The other suggestions look good to me.

Do you want compactness to be a user option, or automatic depending on the number of bins for the box plot? In the latter case it may be more difficult to look into more detail (eg when coloring the samples).

**Comment by adamabeshouse** [comment]
@jjgao what UI do you think for selecting specific categories?

**Comment by jjgao** [comment]
@adamabeshouse I think the UI can be in the axis setting (in the example above horizontal axis) with a searchable multi-checkbox?

**Comment by adamabeshouse** [comment]
@jjgao great idea, I think we have the space for it as well

**Comment by adamabeshouse** [comment]
@jjgao do we need to show it for other plot types besides box plot?
