### ISSUE TITLE
support study view without any profiles

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7814]
There have been a couple of requests for visualizing clinical data in a study without any profiles, e.g. https://github.com/cBioPortal/cbioportal/issues/7800.

**Comment by AndyBlake** [comment]
Hiya
If there is anything I can help with in terms of testing or anything really for this fix please let me know.
Kind regards
Andy

**Comment by jjgao** [comment]
@AndyBlake Thanks for following up. Unfortunately, I don't think we will have the bandwidth currently to work on this. If you have programming skills and would like to give it a try, please feel free to work on this. We can provide some pointers if needed.
