### ISSUE TITLE
Make PTM track compatible with Uniprot Feature data 

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#7815]
Currently, PTM track implementation relies on the data structure based on dbPTM data, but we would like to support Uniprot PTM data, which can be obtained via the uniprot features API. 

An example API query: https://www.ebi.ac.uk/proteins/api/features/P04637?categories=PTM

**Comment by inodb** [comment]
- [ ] First release in Genome Nexus website (both dbPTM and Uniprot support)
- [ ] Make sure all cancer genes have a mapping from ensembl transcript id to uniprot id
