### ISSUE TITLE
Follow up on the fix of issue #7616 in docker

### ISSUE THREAD

**Issue by RJWANGbioinfo** [cBioPortal/cbioportal#7817]
Hi,

I noticed that my previous issue ([#7616](https://github.com/cBioPortal/cbioportal/issues/7616)) on custom driver annotation has been closed, and the fix ([#3290](https://github.com/cBioPortal/cbioportal-frontend/pull/3290)) has been merged to master. 

However, I've tested this issue through redeploying the lasted dockers from dock hub including:
1. cbioportal/cbioportal:master
2. cbioportal/cbioportal:lastest
3. cbioportal/cbioportal:3.4.9

None of the above seems to fix the issue (see the screenshot below). Could you confirm it has been fixed in the docker? If so, which docker should I use to fix this issue? Thanks in advance!

![image](https://user-images.githubusercontent.com/51307984/90844976-244bb500-e333-11ea-85c0-9f42da3b95cc.png)

![image](https://user-images.githubusercontent.com/51307984/90845013-388fb200-e333-11ea-8269-590c4cb48f96.png)

**Comment by pvannierop** [comment]
@RJWANGbioinfo Indeed the solution to this problem has been merged. You have to wait for the next release that contains this fix. Releases (and DockerHub images based on these) lag a bit behind from master branch updates.
