### ISSUE TITLE
oncotree clinical track sorting

### ISSUE THREAD

**Issue by zheins** [cBioPortal/cbioportal#782]
Patients with multiple samples do not sort correctly when sorting by clinical tracks. Happens when samples collapsed by patient and when all samples are shown.
![screen shot 2016-01-22 at 5 02 50 pm](https://cloud.githubusercontent.com/assets/10240498/12524322/3bed2ee4-c12a-11e5-846c-5f47f24a7261.png)

**Comment by zheins** [comment]
probably related to N/A

**Comment by adamabeshouse** [comment]
@zheins it's been a while but, do you know how I might replicate this issue to check if it's been fixed in the new implementation - what study was this?

**Comment by zheins** [comment]
@adamabeshouse This was from mskimpact with a hepatocellular subset. You should be able to replicate it using the current hepatocellular samples.

**Comment by adamabeshouse** [comment]
thanks @zheins , confirmed working in new oncoprint
