### ISSUE TITLE
 Trying to run without docker.

### ISSUE THREAD

**Issue by SungJun9212** [cBioPortal/cbioportal#7826]
I downloaded session-services in cbioportal folder.

I installed session-service and used the following command right inside.
'mvn package -Dpackaging.type=jar && java -Dspring.data.mongodb.uri=mongodb://ip_address:27017/session-service -jar target/session_service-0.2.0.jar'

Then I used the following command in the cbioportal folder location.
'java -jar -Dauthenticate=noauthsessionservice portal/target/dependency/webapp-runner.jar --port 28080 portal/target/cbioportal.war'

The portal.properties file has been moved to the cbioportal location and the settings in it are being modified.
How should I set session.service.url?

**Comment by nr23730** [comment]
Hi, please make sure that cBioPortal actually finds the portal.properties file. It uses the environment variable `PORTAL_HOME` for this.

session.service.url can be set using the portal.properties file or using the startup command by adding `-Dsession.service.url=http://127.0.0.1:5000/api/sessions/my_portal/`

**Comment by SungJun9212** [comment]
Thank you for your comment.

This is my portal home and file location.
![image](https://user-images.githubusercontent.com/31676950/91127944-35554700-e6e2-11ea-9627-aa12c206bf4f.png)

I am trying to add session-service-url using portal.properties file
What are port 5000 and my_portal in the command?

**Comment by nr23730** [comment]
Sorry. Took that call from the Docker command where the Session-Service runs on that port. I assue that you are running cBioPortal on Port 28080 and session-service on Port 8080?

Seems like the path is also a bit different when running without docker:
`http://localhost:8080/session_service/api/sessions/my_portal/`
The `my_portal` with any string that identifies your instance. A single session-service could handle multiple cBioPortal instances.

**Comment by SungJun9212** [comment]
Thank you.
I understood the port
So where do you set the name my_portal?

**Comment by kalletlak** [comment]
Format for session-service url is
`http://localhost:<port>/<context-path>/api/sessions/<source>/`

Looks like in your case
`port` is `8080`
`context-path` is `session_service`
`source` can be anything (you could leave it as is i.e, `my_portal`). it is to identify from which portal (if there are multiple cbio instances using same session-service) the request has been made.
