### ISSUE TITLE
docker-entrypoint.sh check for ssl

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7829]
Currently ssl is not supported with the new docker-entrypoint.sh script:

https://github.com/cBioPortal/cbioportal/pull/7693

User reported: https://groups.google.com/g/cbioportal/c/TjpXTpAqQIA/m/WoAXRDlwBQAJ

**Comment by jjgao** [comment]
@inodb should we keep this in backlog?

**Comment by inodb** [comment]
yes

**Comment by jjgao** [comment]
@inodb mentioned that there is a workaround. Please add some comments about the workaround.

**Comment by inodb** [comment]
You can avoid running the entrypoint script with

`--entrypoint /bin/bash`

**Comment by skarlupka** [comment]
I'll taking a look now to add a fix.
