### ISSUE TITLE
SV: survival outcome charts improvement

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#7830]
This is a follow-up issue for the pr: https://github.com/cBioPortal/cbioportal-frontend/pull/3372.

1. Revert https://github.com/cBioPortal/cbioportal-frontend/pull/3372.
2. Decide whether to show the survival plot by default: get reserved priority from `StudyViewConfig` or use the priority from related `STATUS` clinical attribute, hide the chart if priority is 0.
3. Change the km plot chart name to `KM Plot: NAME` (e.g. `Overall Survival` -> `KM Plot: Overall Survival`).
![image](https://user-images.githubusercontent.com/15748980/91193991-c4a03180-e6c5-11ea-9b47-f22aab209803.png)

**Comment by jjgao** [comment]
I think the "survival status" piechart can still be useful, for example, without it, there is no way to select deceased patients... Maybe we can simply change the KM plot selection attribute from "Overall Survival" to "KM Plot: Overall Survival" so that one can search "KM plot"?

**Comment by dippindots** [comment]
@jjgao Sure, It's easy to make this change. I can make this happen today. And how should we decide whether we want to show the chart by default?

**Comment by jjgao** [comment]
Maybe we can show the KM charts based on the priorities of the Survival Status attributes?

**Comment by dippindots** [comment]
> Maybe we can show the KM charts based on the priorities of the Survival Status attributes?

@jjgao That's a good idea! @kalletlak @ritikakundra Do you have any suggestions about which number of priority should I use to decide whether we want to show the chart by default?

**Comment by jjgao** [comment]
@dippindots @ritikakundra I think the priority should be decided in the data...

**Comment by kalletlak** [comment]
@jjgao I think we can utilize the priority set for that clinical attributes.

**Comment by ritikakundra** [comment]
@jjgao with genie we have so many survival curves, especially within regimens. We can update the top 10 regimens as a higher priority?

**Comment by jjgao** [comment]
@ritikakundra is it possible to hide all the drug base survive curves? (Is it just to set priority=0?)

**Comment by ritikakundra** [comment]
@dippindots @jjgao Sure, I will create a proposed list to hide treatment curves

**Comment by jjgao** [comment]
@ritikakundra maybe we can hide all curves by default?

**Comment by inodb** [comment]
Let's have a separate issue in datahub for this one to indicate what charts to show

**Comment by jjgao** [comment]
Created the data related ticket in datahub: https://github.com/cBioPortal/datahub/issues/1266
