### ISSUE TITLE
Bar chart on x-axis is not responsive

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#7836]
Seems like when resizing the bar chart on x-axis, it's not responsive. This is 5*2
![Screen Shot 2020-08-26 at 11 26 07 AM](https://user-images.githubusercontent.com/5400599/91323612-182a8200-e78f-11ea-9822-b72077e2c6ee.png)

**Comment by jjgao** [comment]
@Luke-Sikina I am wondering if this is something that @jtquach1 can help with?

**Comment by Luke-Sikina** [comment]
@jjgao Yes. Assigned.
