### ISSUE TITLE
Swagger documentation

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#7837]
The swagger docs for Data Access Tokens contains more endpoints than usual.  Seems that swagger annotations are misconfigured since the introduction of Keycloak token support.

![image](https://user-images.githubusercontent.com/366003/91323842-5aec5a00-e78f-11ea-918a-324b59a4873d.png)

https://www.cbioportal.org/api/swagger-ui.html?urls.primaryName=internal#/Data_Access_Tokens

**Comment by jjgao** [comment]
@pvannierop could you help fix this?

cc @inodb

**Comment by jjgao** [comment]
@pvannierop would you please check if this issue was introduced by https://github.com/cBioPortal/cbioportal/pull/6999? Thanks.

**Comment by jjgao** [comment]
We should also hide the Data Access Tokens endpoints in the public portal if possible.

**Comment by pvannierop** [comment]
I have provided a PR with a fix. The docs now look like this:

![image](https://user-images.githubusercontent.com/745885/123058889-88cf1900-d409-11eb-9ae9-b8eab0fd0e84.png)

**Comment by jjgao** [comment]
Thanks, @pvannierop !
