### ISSUE TITLE
Mutation types definition for Comparison page, tab of Mutation/CNA/SV

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#7847]
@jjgao this is the map that I am using:

- **Missense**: missense_mutation, missense, missense_variant
- **Frameshift Insertion**: frame_shift_ins, frameshift_insertion
- **Frameshift Deletion**: frame_shift_del, frameshift_deletion
- **Frameshift**: frameshift, de_novo_start_outofframe, frameshift_variant
- **Nonsense**: nonsense_mutation, nonsense, stopgain_snv, stop_gained
- **Splice**: splice_site, splice, splicing, splice_site_snp, splice_site_del, splice_site_indel, splice_region_variant, splice_region
- **Nonstart**: translation_start_site, initiator_codon_variant, start_codon_snp, start_codon_del
- **Nonstop**: nonstop_mutation, stop_lost
- **Inframe Deletion**: inframe_del, inframe_deletion, in_frame_del, in_frame_deletion, indel
- **Inframe Insertion**: inframe_ins, inframe_insertion, in_frame_ins, in_frame_insertion
- **Inframe**: nonframeshift_deletion, nonframeshift, nonframeshift_insertion, inframe
- **Truncating**: truncating, feature_truncation
- **Fusion**: fusion
- **Silent**: silent, synonymous_variant
- **Other**: targeted_region, any, other

**Comment by jjgao** [comment]
@oplantalech Thanks for the list. Here is my proposal for the hierarchy. I think we should move fusions to the top level (later, we'll switch to the SV table). For both inframe and frameshift ins/del, it's more complex than I thought b/c of types such as "indel". Maybe we can just allow users to select "Inframe" (which includes both ins/del) but not select specifically for ins or del. @cBioPortal/product 

- **Mutations**
  - **Missense**: missense_mutation, missense, missense_variant
  - **Inframe**: indel, nonframeshift, inframe, **Inframe Deletion** (inframe_del, inframe_deletion, in_frame_del, in_frame_deletion, nonframeshift_deletion), **Inframe Insertion** (inframe_ins, inframe_insertion, in_frame_ins, in_frame_insertion, nonframeshift_insertion)
  - **Truncating**: truncating, feature_truncation, and all subtypes below
    - **Nonsense**: nonsense_mutation, nonsense, stopgain_snv, stop_gained
    - **Frameshift**: frameshift, frameshift_variant, **Frameshift Insertion** (frame_shift_ins, frameshift_insertion), **Frameshift Deletion**: (frame_shift_del, frameshift_deletion)
    - **Nonstart**: translation_start_site, initiator_codon_variant, start_codon_snp, start_codon_del, de_novo_start_outofframe
    - **Nonstop**: nonstop_mutation, stop_lost
    - **Splice**: splice_site, splice, splicing, splice_site_snp, splice_site_del, splice_site_indel, splice_region_variant, splice_region
  - **Other**: silent, synonymous_variant, targeted_region, any, other, (or any other types)
- **Structural variants / Fusions**
- **Copy number alterations**
  - **Amplification**
  - **Deletion**

**Comment by jjgao** [comment]
@yichaoS @rmadupuri I am wondering if you can help run an sql to find the unique list of mutation types in our databases (public, genie, and private/msk)?

**Comment by jjgao** [comment]
We are tracking the mutation types in this issue: https://github.com/cBioPortal/datahub/issues/247 - @yichaoS just updated it.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao I think this can be closed now, right?

**Comment by jjgao** [comment]
Yes

**Comment by lincj1994** [comment]
> @oplantalech Thanks for the list. Here is my proposal for the hierarchy. I think we should move fusions to the top level (later, we'll switch to the SV table). For both inframe and frameshift ins/del, it's more complex than I thought b/c of types such as "indel". Maybe we can just allow users to select "Inframe" (which includes both ins/del) but not select specifically for ins or del. For truncating, I am wondering if we have any "truncating" or "feature_truncation" in our database?
> 
> * **Mutations**
>   
>   * **Missense**: missense_mutation, missense, missense_variant
>   * **Inframe**: indel, nonframeshift, inframe, **Inframe Deletion** (inframe_del, inframe_deletion, in_frame_del, in_frame_deletion, nonframeshift_deletion), **Inframe Insertion** (inframe_ins, inframe_insertion, in_frame_ins, in_frame_insertion, nonframeshift_insertion)
>   * **Truncating**: truncating, feature_truncation, and all subtypes below
>     
>     * **Nonsense**: nonsense_mutation, nonsense, stopgain_snv, stop_gained
>     * **Frameshift**: frameshift, frameshift_variant, **Frameshift Insertion** (frame_shift_ins, frameshift_insertion), **Frameshift Deletion**: (frame_shift_del, frameshift_deletion)
>     * **Nonstart**: translation_start_site, initiator_codon_variant, start_codon_snp, start_codon_del, de_novo_start_outofframe
>     * **Nonstop**: nonstop_mutation, stop_lost
>     * **Splice**: splice_site, splice, splicing, splice_site_snp, splice_site_del, splice_site_indel, splice_region_variant, splice_region
>   * **Other**: silent, synonymous_variant, targeted_region, any, other, (or any other types)
> * **Structural variants / Fusions**
> * **Copy number alterations**
>   
>   * **Amplification**
>   * **Deletion**
> 
> @cBioPortal/product

Hi. How about Stop_Codon_Del, Stop_Codon_Ins, De_novo_Start_IN_Frame, and De_novo_Start_Out_Frame? Which node of the hierarchy should they be added?
Best,
