### ISSUE TITLE
Filtering on custom driver annotation still doesn't work after updating docker.  (Related to issue #7616) 

### ISSUE THREAD

**Issue by RJWANGbioinfo** [cBioPortal/cbioportal#7848]
Hi,

Thanks for fixing the issue of  [#7616](https://github.com/cBioPortal/cbioportal/issues/7616) and released the fix in the latest updating.

I've updated my docker to the latest version, and tested this fix:
1) The tiers can be unchecked now

2) However, the filtering of custom driver annotation ties still doesn't work, whenever the tier is selected or unselected, the mutations will still be displayed in view (see screenshot below). It seems only selected/unselected gets fixed other than both select/unselect + filter. Could you confirm this? If so, could you help us to fix this? Thanks in advance!

![image](https://user-images.githubusercontent.com/51307984/91750735-9329d900-eb91-11ea-9ef3-825d2bf6a0d7.png)

![image](https://user-images.githubusercontent.com/51307984/91750890-d5ebb100-eb91-11ea-9b00-bfc55966ef79.png)

**Comment by Sjoerd-van-Hagen** [comment]
Looks like the hotspots box is checked in both screenshots and the mutation is marked with the hotspots icon so it should be included. What happens if the hotspots box is unchecked? @RJWANGbioinfo

**Comment by RJWANGbioinfo** [comment]
Hi @Sjoerd-van-Hagen ,

Thanks for pointing this out! It works now, thanks a ton!
