### ISSUE TITLE
custom range for MSI_SCORE_MANTIS and MSI_SENSOR_SCORE in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7854]
We are integrating the msisensor and matis scores (https://github.com/cBioPortal/datahub/pull/1236). The current bins on study view is not ideal.

Can we change it to the following as default?

- For MSI_SENSOR_SCORE: <4, 4-10, >10
- For MSI_SCORE_MANTIS: <0.4, 0.4-0.6, >0.6

@zhx828 @kalletlak @onursumer

**Comment by zhx828** [comment]
@jjgao do I change the MSI_SCORE from internal mskimpact study to this range as well?

**Comment by zhx828** [comment]
And due to the nature of the bar grouping, I can only do <=4. 4-10, >10 without making major changes. Is it ok?

**Comment by jjgao** [comment]
@zhx828 sounds good. Let's change the internal one to this range too.
