### ISSUE TITLE
Separate splice mutations from truncation mutaitons

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7857]
I think we should render splice mutations in its own category. For example in [this query](http://www.cbioportal.org/beta/results/plots?session_id=5bd3ccdf498eb8b3d56887fb), the samples with TP53 truncating mutations are all very low except for the splice mutations.

![image](https://user-images.githubusercontent.com/840895/47598714-2d091500-d96e-11e8-8d5d-5376c6bd4592.png)

- [x] define color for splice mutations 
- [x] separate in oncoprint
- [x] separate in mutations tab
- [ ] oncoprinter
- [ ] oql

discussion:
- We may also want to do that in OncoKB -- will discuss with OncoKB team.

@schultzn @tmazor thoughts?

**Comment by adamabeshouse** [comment]
should we color them the same and just separate them for plots tab? or are we adding a mutation category to oncoprint as well?

**Comment by jjgao** [comment]
We are adding a separate category. Could you try and see if it's possible to find new colors (one for driver and one for vus)?

**Comment by adamabeshouse** [comment]
what should be the render priority of splice? current priority is promoter > trunc > inframe > missense

**Comment by jjgao** [comment]
maybe  promoter > trunc > splice > inframe > missense?
