### ISSUE TITLE
Sample Numbering should be based on procurement date

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#786]
Two studies have raised this issue of having samples numbers allotted alphabetically rather than what was procured first causing confusion during comparison. Sometime the Primary Vs Met is also not allotted right.

https://cbioportal.mskcc.org/case.do?cancer_study_id=egc_mskcc_2015_janjigiany&case_id=YJ-egc-049

https://cbioportal.mskcc.org/case.do?cancer_study_id=egc_mskcc_2015_janjigiany&case_id=YJ-egc-090#nav_case_ids=YJ-egc-090

**Comment by ritikakundra** [comment]
@inodb

**Comment by inodb** [comment]
This issue exists because we changed from using `SpecimenReferenceNumber` to `SPECIMEN_REFERENCE_NUMBER` as clinical attribute. I changed the code to support both, but it makes more sense I think to convert all occurences of `SpecimenReferenceNumber` in the data to `SPECIMEN_REFERENCE_NUMBER`

**Comment by jjgao** [comment]
@ritikakundra @inodb : maybe we should convert all `SpecimenReferenceNumber` and `SPECIMEN_REFERENCE_NUMBER` to `SAMPLE_ID`?

**Comment by inodb** [comment]
That works for me as well. In some cases it's the same as `OTHER_SAMPLE_ID` instead of `SAMPLE_ID` but that does not seem terribly confusing

**Comment by jjgao** [comment]
Maybe we should always normalize it to `SAMPLE_ID` when importing the data?

**Comment by inodb** [comment]
Makes sense

**Comment by jjgao** [comment]
@inodb what's the status on this?

**Comment by inodb** [comment]
Basically all the `SPECIMEN_REFERENCE_NUMBER` and `SpecimenReferenceNumber` in the databases have to be changed to `SAMPLE_ID`. In the mean time I made a PR that supports all of them: https://github.com/cBioPortal/cbioportal/pull/887. After the changes to the database have been made we can do the `OTHER_SAMPLE_ID` to `SAMPLE_ID` normalization in the importer.

**Comment by ritikakundra** [comment]
Agreed to above

**Comment by ritikakundra** [comment]
@inodb All SPECIMEN_REFERENCE_NUMBER and SpecimenReferenceNumber have been changed to SAMPLE_ID. They have been pushed to mercurial. Do we need to re-import them in the portal?

**Comment by inodb** [comment]
Looks like everything is replaced now. For testing purposes the triage portal needs to be updated to the latest version. There was an issue with the timeline not showing up, because the triage portal is outdated. Once all these changes to the db are in public and the mskcc portal I can then continue to remove all references to `SPECIMEN_REFERENCE_NUMBER` and `SpecimenReferenceNumber` from the front end code. @zheins, could you help update triage?

**Comment by zheins** [comment]
@inodb done!

**Comment by inodb** [comment]
Great, thanks a lot!
