### ISSUE TITLE
Oncoprinter: file upload not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#787]
But pasting in the input box works.

[T_OncoPrinter.txt](https://github.com/cBioPortal/cbioportal/files/101707/T_OncoPrinter.txt)

**Comment by adamabeshouse** [comment]
There's something weird with that file where the line breaks aren't registering - the server echos it back with no line breaks, but when I went into the file and deleted and then hit enter on all the lines to make sure there's a line break, it works.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1203
