### ISSUE TITLE
Tweaks of structural variants option in query page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7881]
- use plural and add fusions, ie. `Structural Variants/Fusions`
- select "Structural Variants\rusions" by default

![image](https://user-images.githubusercontent.com/840895/92966676-f9421600-f445-11ea-91a0-b60f024f7b5f.png)

**Comment by kalletlak** [comment]
> * use plural and add fusions, ie. `Structural Variants/Fusions`

@jjgao these names reflects whats present in data files. they needs to be updated.
CC: @ritikakundra 

~~> * select "Structural Variants\rusions" by default~~
> 
> ![image](https://user-images.githubusercontent.com/840895/92966676-f9421600-f445-11ea-91a0-b60f024f7b5f.png)
