### ISSUE TITLE
Timeline track collapse functionality

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7887]
When a user collapses tracks, show all enclosed events merged in parent row
e.g. like Domains & Sites on https://www.uniprot.org/uniprot/Q96S44/protvista

There is obvious issue about how to render points of mixed type.  I think the events need a reference to their parent track so they can look up their render method.

**Comment by inodb** [comment]
Blocked by the hyve PR due to expectation of conflicts
