### ISSUE TITLE
VAF plot tasks

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7907]
- [x]  On Genomic Evolution tab, wire up the table and plot selection state (AARON)
- [x]  Implement sequential mode in Timeline widget (or fake it at data level)  (DIANA)
- [x]  Implement y axis (DIANA)
- [x]  Handle track labels when grouping functionality is enabled (use existing Timeline track labels?) (PIM)
- [x] Fix height calculation issues (AARON)
- [x] Fix height calculation when we're in log mode (AARON)
- [x] Fix visible labels rule
- [x] Use no color for plot when only one group after groupBy
- [x] Fix view boxes for groupBy tracks
- [x] Fix row highlight for groupBy tracks
- [x] Make sure the tickmarks in the y-axis header line up with the right border (PIM)
- [x] Do not force CAPITALIZATION legend label (PIM)
- [x] Make legend as narrow as possible (PIM)
- [x] remove 'VAF' label (PIM)
- [x] Make empty area at left of VAF plot dynamic (hidden when timeline is not shown) (AARON)
- [x] Make timeline and VAF plot the same width (AARON)
- [x] Fix clipping issues for groupBy Tracks when sequential mode is active (AARON)

**Comment by pvannierop** [comment]
- [] Use no color for plot when only one group after groupBy
- [] Fix view boxes for groupBy tracks
- [] Fix row highlight for groupBy tracks
- [] Discuss: do not force CAPITALIZATION for group names in track header?
