### ISSUE TITLE
Adding warning messages for GENIE private portal 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7908]
Warning messages for GENIE private portal - adding a similar banner as msk portal. There are the list of checkboxes. We are thinking of allow the user to dismiss it for 30 days (this could apply to the banner for msk portal as well).

- Data visualizations within cBioPortal the GENIE-BPC data are provided to help users understand how genomic markers relate to clinical outcomes and should be used for descriptive analyses and hypothesis generation only.
- Cohort entry is based on many factors, including NGS profiling in specific years.  These selection criteria could affect the ability to generalize to the entirety of patients with the specific cancer type. Genomic profiling is not always performed at diagnosis and therefore may lead to several forms of bias, including immortal time bias.
- Investigators who wish to test specific hypotheses should work with a statistician to perform analyses that account for limitations of observational data. Failure to do so may result in incorrect inferences.

**Comment by alisman** [comment]
@jjgao @schultzn I need a message for the alert banner:

![image](https://user-images.githubusercontent.com/186521/95509760-e823f080-0982-11eb-813b-2be63bd933c8.png)

**Comment by schultzn** [comment]
How about "Caution: Caveats of AACR Project GENIE BPC data and considerations for its use"?
