### ISSUE TITLE
cytoband values disappear when downloading tsv file from CNA table on patient view page

### ISSUE THREAD

**Issue by ao508** [cBioPortal/cbioportal#7911]
see user-reported issue here: https://groups.google.com/g/cbioportal/c/Op44hFlFHhM/m/UHWO9iThAgAJ

**Comment by Luke-Sikina** [comment]
Link to patient page in google groups screenshot: https://www.cbioportal.org/patient?studyId=prad_su2c_2019&caseId=1115015
It also seems like the `cohort` column is missing its values.

**Comment by onursumer** [comment]
Technically, most of the columns that do not have an explicit `download` function are expected to have an empty download value. We do not provide a default download function for every column. If it is critical for all columns to have a non-empty download data by default, then we need to redesign our table component.

For now we need to define an explicit `download` function for any column that we want to see a non-empty download value.

**Comment by Luke-Sikina** [comment]
Proposed solution: do not show columns in TSV if they do not have a download function.
