### ISSUE TITLE
reset chart layout data for BPC cohort in genie-private

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7915]
Once https://github.com/cBioPortal/cbioportal/issues/7830 & https://github.com/cBioPortal/datahub/issues/1266 are done, we should reset/remove the chart layout data in session service for **the BPC cohort in genie-private portal**. This will be one time and will not affect many users. Maybe we can do it manually to the session service?

**Comment by inodb** [comment]
This should be done now, I ran this

```
db.settings.remove({"source":"genie_private_portal","data.origin": { $all: ["nsclc_genie_bpc"] }})
```
