### ISSUE TITLE
Update PharmacoDB integration RFC

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7916]
[RFC](https://docs.google.com/document/d/1M7sBu3ee_8UQRJPRAIc9DOToQOlH0SdbzldgGWi9yUQ/edit)

- [x] update RFC document with feedback
- [x] implement in CNA table

**Comment by jagnathan** [comment]
RFC document updated. Implementation will be done in cbioportal.ca for CNA table initially in first phase.
