### ISSUE TITLE
Comparison page "Select enriched groups" dropdown tweak

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7917]
We could use the header of the last column since we are actually filtering based on that column, i.e.:

- Change text "Select enriched groups" to "Enriched in ..." for categorical data comparison (mutations, copy-number)
- Change text "Select enriched groups" to "High [expression/methylation] in ..." for categorical data comparison (mutations, copy-number)

![image](https://user-images.githubusercontent.com/840895/94602624-1b6bce80-0263-11eb-9930-c2b503313fc2.png)

**Comment by alisman** [comment]
@jjgao playing with this feature a little more, it seems to me that it could be achieved simply by making the columns sortable.  Is there an reason to filter out the rows entirely?

**Comment by jjgao** [comment]
@alisman I think we would like to still sort by p-value and filter the table for one group. If we can sort by multiple columns (which we don't currently), that might work for 2 groups, but it'll become tedious when there are many groups - you will have to go to the page of the group of interest.

**Comment by jjgao** [comment]
@alisman for this issue, it's really just about changing the text and make it more clear.
