### ISSUE TITLE
Oncoprint gene name/percent not aligned properly with tracks after download

### ISSUE THREAD

**Issue by zheins** [cBioPortal/cbioportal#792]
Slightly misaligned in the browser, but its worse after download. Happens with both svg and pdf.
![misaligned](https://cloud.githubusercontent.com/assets/10240498/12585705/2f0b6076-c41b-11e5-8e3f-8f2d0c74161a.png)

**Comment by adamabeshouse** [comment]
Fixed in new oncoprint
