### ISSUE TITLE
When importing a MAF file as part of a study, importer doesn't recognize 'GRCh38' as a valid value of the 'NCBI_Build' column

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [cBioPortal/cbioportal#7924]
Hello all,

According to:
https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#extended-maf-format:

```
NCBI_Build (Required)1: The Genome Reference Consortium Build is used by a variant calling software. It must be "GRCh37" or "GRCh38" for a human, and "GRCm38" for a mouse.
```

However, when I try to import a study via the `cBioPortal` docker image, I get the following error:
```
$ docker-compose run --rm cbioportal metaImport.py -u http://cbioportal:8080 -s study/mystudy/ -o

... rest of message omitted ...
ERROR: 001_Sample_PRE_DNA.maf: lines [25, 26, 27, (29201 more)]: column 4: Value in column 'NCBI_Build' is invalid; value encountered: 'GRCh38'
```

Any help is appreciated!

**Comment by leexgh** [comment]
@kurt-mueller-osumc Could you try adding `-ncbi 38` to your command? Which would be:
```
 $ docker-compose run --rm cbioportal metaImport.py -u http://cbioportal:8080 -s study/mystudy/ -o -ncbi 38
```
Other parameters can be found by `./metaImport.py -h` or  here: https://docs.cbioportal.org/5.1-data-loading/data-loading/using-the-metaimport-script#importing-data-into-cbioportal

Hope it helps!

**Comment by leexgh** [comment]
@kurt-mueller-osumc Please let me know if it works or not 🙂

**Comment by kurt-mueller-osumc** [comment]
It worked! Thank you @leexgh for your help! I really appreciate the time you took to respond to me. Thanks again!

**Comment by leexgh** [comment]
@kurt-mueller-osumc You are welcome!

**Comment by Cala3len** [comment]
Hi,
 
With the command 
```
docker-compose run --rm \
    -v "${CBIODIR}/import_reports:/report" \
    -v "${PORTAL_INFO}:/portalinfo:ro" \
    cbioportal \
    metaImport.py -ncbi 38 -o -p /portalinfo -s study/WP2_2_study -o --html=/report/report.html
```
the -ncbi 38 option seems to be confused with the -n argument. It gives 

`metaImport.py: error: argument -n/--no_portal_checks: ignored explicit argument 'cbi'
`

I am running the v3.6.7 of cbioportal.

Thanks for help

**Comment by Cala3len** [comment]
Same thing with the 3.7.10 version
