### ISSUE TITLE
(Oncoprint) Merge Heatmap, Clinical and other track into one dropdown in control menu

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#7934]
This is for supporting more data types using categorical generic assay data (e.g. binary mutational signature) as specified in [this RFC](https://github.com/cbioportal/cbioportal/issues/7920).

- Merge Heatmap, Clinical and other track into one dropdown in control menu. Change dropdown name to `Add Tracks`
- Having a sub-tab per "Generic Assay" type (e.g. `Mutational Signatures`)

![Screen Shot 2020-10-05 at 11 53 48 AM](https://user-images.githubusercontent.com/15748980/95217634-689af380-07c1-11eb-9949-bcaff7a2f5fc.png)

Currently:

![image](https://user-images.githubusercontent.com/840895/95229650-d0a40680-07ce-11eb-8af3-c04aee78da4e.png)

**Comment by jjgao** [comment]
@dippindots I update the description above. Could you also add the numbers of clinical tracks and available profiles for heatmap into the corresponding header in the new design?

**Comment by dippindots** [comment]
@jjgao Ok, I will keep the number in those headers.

**Comment by inodb** [comment]
@cBioPortal/product could you help review this?
