### ISSUE TITLE
Refresh of query page with clinical tracks

### ISSUE THREAD

**Issue by zheins** [cBioPortal/cbioportal#794]
Refresh of query page (or attempting to go back from a patient/sample page) causes 404 when clinical tracks are activated.
![screen shot 2016-01-26 at 1 30 55 pm](https://cloud.githubusercontent.com/assets/10240498/12590442/0f3f1d6c-c431-11e5-9477-887abdde460d.png)

**Comment by jjgao** [comment]
@zheins that's because the query are on custom case list with POST. I'll make some change so that you won't get 404 at least.

**Comment by jjgao** [comment]
duplicate with #1547
