### ISSUE TITLE
comparison is not working for treatment response data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7942]
https://www.cbioportal.org/comparison/generic_assay_treatment_response?sessionId=5dd6ddf8e4b05f1dfb8ab237

![image](https://user-images.githubusercontent.com/840895/95252271-c3951080-07ea-11eb-9994-1dd5c82f0282.png)

**Comment by dippindots** [comment]
@jjgao This may not a bug, @kalletlak and I found out this while we were developing this feature. It's because of the data availability (treatment response data not available for all `treatments`, lots of `NA` in the matrix), maybe @kalletlak can elaborate more on this?

**Comment by jjgao** [comment]
I am surprised that none of the drugs have data (in two or more groups) given that all samples are included...

@kalletlak @dippindots what's the logic when a row is included/excluded?
