### ISSUE TITLE
installation map feedback

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7947]
The map looks awesome @jtquach1 ! Here's some feedback:

- [x] 1. Might be worth a minor wording change on the homepage. In this text: "Have you installed and used cBioPortal? Fill out the survey here to have your lab featured on the map!"  instead of "your lab" might be better to say "your installation"
- [x] 2. How about replacing "Selected instance details" with "Details" and when nothing is selected, put text underneath to say "Select an instance in the table or map to see additional information"
- [x] 3. Not sure if this is just me, but I find it slightly counter-intuitive to have the selected waypoint on the map as a lighter color than all the others.
- [x] 4. I think coordinates can be removed from the details table
- [x] 5. When zoomed in to a level where states/provinces are visible, can the country borders be thicker or somehow distinct from state borders? For example when I zoom in on Europe, it would be nice to still know where the country lines are:
 ![image](https://user-images.githubusercontent.com/10508276/95373623-41205580-08ab-11eb-8858-155ac9588152.png)
- [x] 6. @pieterlukasse noted earlier that the Netherlands has lines drawn at the city(?) level rather than at the province level
- [ ] 7. we should add some human QC of the data in the spreadsheet before showing it in the map, just in case people enter inappropriate content. There are probably many ways to do this, but one suggestion is to add a column where one of us has to enter "yes" or "ok" before the data can load in the map
- [x] 8. for consistency, replace "installations" with "instances"
![image](https://user-images.githubusercontent.com/10508276/95629039-2f76b380-0a4d-11eb-89d9-f581850d68b4.png)

**Comment by jtquach1** [comment]
Thanks Tali! 

1. just pushed this change here: https://github.com/cBioPortal/cbioportal-frontend/pull/3410/commits/51f028578bbb18873c9fd1d55a21c4bee1c9576d

To-do: rest of suggestions

**Comment by jtquach1** [comment]
Hm, that explains why the Netherlands looks so granulated. I'll try to find a map that has the lines drawn at the province level

**Comment by jtquach1** [comment]
For 3), I had the table row and Marker be light blue when selected (they're actually very close shades of blue, but the row's blue has the same darkness as its gray rows). Sjoerd suggested to pick a more contrasting color for the highlight on the map. 

So, making the markers light blue by default (with dark blue highlight) might lead to the contrast issue Sjoerd mentioned. I played around with the cBioPortal colors using [coolors](https://coolors.co/cb123d-0c783f-3786c2-c0bfc0-000000) and wondered if I should use a shade of light blue that's more saturated?

**Comment by tmazor** [comment]
@jtquach1 your proposed color update with 2C609C looks good to me!

**Comment by tmazor** [comment]
@jtquach1 for 2, sorry I think my request wasn't clear - I was imagining something like this:
![image](https://user-images.githubusercontent.com/10508276/95628653-7c0dbf00-0a4c-11eb-88fb-e1ef81b53adf.png)
This way the header never changes, and the second line with text can just be replaced by the table when something gets selected.

**Comment by jtquach1** [comment]
> @jtquach1 your proposed color update with 2C609C looks good to me!

I forgot to mention, I try to keep the marker highlight and table row highlight the same (for consistency), so this is the current view: 
![image](https://user-images.githubusercontent.com/33106214/95628817-c68f3b80-0a4c-11eb-814a-b0db7251f98f.png)

**Comment by jtquach1** [comment]
I like "Selected instance details" more (that suggestion was from JJ) since "Details" alone feels kind of general- I'm not sure..

**Comment by tmazor** [comment]
@jtquach1 now that I see it in your screenshot, I agree, let's call it "Selected Instance Details" and then keep the line of text I proposed below it. All the other updates are looking great!

**Comment by tmazor** [comment]
Also @jtquach1  - I like the idea of animating the markers when they are selected. I'm not sure I know exactly what that means, but I like doing something to help the user find their marker of interest.

**Comment by jtquach1** [comment]
Here is the current view with animated highlighted markers and a darker highlight:
![marker_grow_2](https://user-images.githubusercontent.com/33106214/96146759-a5a76a00-0ed4-11eb-926c-f7e1525b6a2b.gif)

**Comment by jtquach1** [comment]
I've just revised the highlighted marker animation so it only grows and shrinks back to original size once:
![marker_grow_4](https://user-images.githubusercontent.com/33106214/96273509-6c86fc80-0f9d-11eb-8082-f89680a4af01.gif)

**Comment by tmazor** [comment]
awesome @jtquach1 !
