### ISSUE TITLE
Survival tab issues and improvements

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7952]
https://genie-private.cbioportal.org/comparison/survival?sessionId=5f7fa3bce4b015b63e9c2200

- [x] add `median survived in [group name]` as hidden columns
- [x] issue: the `# in group` columns are all 0:
![image](https://user-images.githubusercontent.com/840895/95630439-d4928b80-0a4f-11eb-8dcb-66134fa4db34.png)
- [x] issue: some row has no data to plot...
![image](https://user-images.githubusercontent.com/840895/95630939-bda06900-0a50-11eb-9c3e-0232b2af7551.png)

**Comment by adamabeshouse** [comment]
@jj for the first point, do you mean median survival? I'm not sure what median survived would mean

**Comment by jjgao** [comment]
@adamabeshouse yes, median survival time, the ones in the table below the KM plot.
