### ISSUE TITLE
Move several API endpoints to internal only

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7958]
From: https://docs.google.com/document/d/1KC07Rl_oD6jYUyYahv4UrS-GIuLWnr4biaWop826U1Y/edit

- [x] clinical-attributes/counts should be private (put in section clinical attribute counts) - Created a new controller
- [x] clinical-events move to private (prone to change) - Moved entire controller to internal
- [x] Move mutation-counts-by-position (maybe can be made private or organized by page?) - Create a new controller
- [x] /discrete-copy-number-counts (part of patient view page section?) - Create a new internal controller
- [x] Add description to internal page that they are prone to change
- [x] Add description to public endpoints that we intend to keep backwards compatibility (after 1.0 release)
- [x] Reference Genome Genes - Move to private
- [x] Resource Definitions - Move to private for now
- [x] Resource Data - Move to private for now

**Comment by jagnathan** [comment]
https://www.cbioportal.org/api/swagger-ui.html?urls.primaryName=internal

**Comment by jagnathan** [comment]
Public API : 
 "cBioPortal web Public API [Beta]",
            "A web service for supplying JSON formatted data to cBioPortal clients. " +
                "Please note that this API is currently in beta and subject to change.",
            "1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)",
       
Internal API:
  "cBioPortal web Internal API [Beta]",
            "A web service for supplying JSON formatted data to cBioPortal clients. " +
                "Please note that interal API is currently in beta and subject to change.",
            "1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)",

**Comment by jagnathan** [comment]
@jjgao , the google doc mentions many more changes that need to be moved to private. Can you please confirm it?

**Comment by Luke-Sikina** [comment]
From standup today: do not move Structural Variants to private
