### ISSUE TITLE
Data gets duplicated in 'mutation' table

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#796]
If I run org.mskcc.cbio.portal.scripts.ImportProfileData twice on the same data, the data gets duplicated in DB table 'mutation'. 

How can we fix this for now? Which would be the correct fields to bundle into a UQ constraint? 
Perhaps: 
- MUTATION_EVENT_ID, ENTREZ_GENE_ID, GENETIC_PROFILE_ID and SAMPLE_ID
or should another field(s) be added as well?

**Comment by pieterlukasse** [comment]
@jjgao , @n1zea144 : can you please comment on this one?

**Comment by n1zea144** [comment]
I think those are the correct fields for the constraint, although ENTREZ_GENE_ID is captured in the mutation event and may not be required.

We never ran into this situation as we typically remove the study before importing/updating the data.

**Comment by pieterlukasse** [comment]
Ok, I will add this constraint. 
The current mutation import process apparently supports adding new records to existing study data. I think this is a nice feature in case you have a study to which new samples are still being added after the study has been made available in the portal. This constraint prevents wrong data in such a scenario.

@jjgao : what is the way to ensure DB updates are deployed? It would be nice to link the application to a specific DB version. Then at startup, this could be checked and an error could be given if the DB is not at the correct version (Galaxy - usegalaxy.org - had a process like this and it worked quite well).

**Comment by pieterlukasse** [comment]
is part of `cgds.sql` and `migration.sql` now. So ticket can be closed.
