### ISSUE TITLE
Mutation mapper gives input error parsing error when trying to annotate ADAMTS13 variant

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7966]
Try on https://www.cbioportal.org/mutation_mapper:

```
Sample_ID	Cancer_Type	Chromosome	Start_Position	End_Position	Reference_Allele	Variant_Allele
Test	Lung Adenocarcinoma	9	136319670	136319670	C	T
```

Gives

```
Error processing the input. Please review your input and try again.
```

Reported by user: https://groups.google.com/g/cbioportal/c/AlxbBxHnW8U

It would seem that there is a response from VEP:

http://grch37.rest.ensembl.org/vep/human/hgvs/9:g.136319670C%3ET?content-type=application/json

So not sure why it doesn't pick the `ADAMTS13` variant, response is simply empty for genome nexus:

```
{
"variant": "9:g.136319670C>T",
"successfully_annotated": false,
"annotation_summary": {
"variant": "9:g.136319670C>T",
"genomicLocation": {
"chromosome": null,
"start": null,
"end": null,
"referenceAllele": null,
"variantAllele": null
},
"transcriptConsequences": [],
"transcriptConsequenceSummaries": []
}
}
```
See: https://www.genomenexus.org/annotation/9:g.136319670C%3ET?fields=annotation_summary&isoformOverrideSource=uniprot

**Comment by onursumer** [comment]
@inodb This seems working fine now. The response is not empty anymore. Maybe it was a temporary issue with Genome Nexus service?

**Comment by inodb** [comment]
Oh weird, well great when issues solve themselves :)
