### ISSUE TITLE
Make download.cbioportal.org URL configurable thru property

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7967]
Currently we only support zip files download on the public portal. It would be nice if we could offer some property to change that URL to another location.

The URL can be found here: https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/shared/api/urls.ts#L325

Note that this solution would still require people to host the zipped studies somewhere themselves, but that's perhaps ok for now.

User request: https://groups.google.com/g/cbioportal/c/l14Wbtx6xPs

**Comment by jjgao** [comment]
Maybe we can import the url per study as part of the Files&Links feature?

**Comment by inodb** [comment]
User solved this in a different way by adding the download link to the studies' description instead. We do not know yet how we will be hosting files in the future, so closing it for now.
