### ISSUE TITLE
Craniopharyngioma oncotree abbreviations inconsistent

### ISSUE THREAD

**Issue by jharenza** [cBioPortal/cbioportal#7968]
Below are two subtypes of Craniopharyngioma:
Craniopharyngioma, Adamantinomatous Type (ACPG)
Craniopharyngioma, Papillary Type (PCGP)

It looks like the code for Craniopharyngioma, Papillary Type should be PCPG instead of PCGP (the G and P were inverted).

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/oncotree #220](https://github.com/cBioPortal/oncotree/issues/220) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jharenza** [comment]
thanks!
