### ISSUE TITLE
Offline validation of LINC01297 in maf leads to error

### ISSUE THREAD

**Issue by AlexJanse** [cBioPortal/cbioportal#7970]
Dear all,

**My issue**
While trying to perform an offline validation of my data, I encountered an error (see below) while the validation was performed on the MAF file: 
```
File "/cbioportal/core/src/main/scripts/importer/validateData.py", line 871, in checkGeneIdentification
    '/'.join(self.portal.hugo_entrez_map[gene_symbol]),
TypeError: sequence item 0: expected str instance, int found
```
I found that it had issues with handling LINC01297 and that the warning message which was supposed to be created tried to join a list of two Entrez IDs to a string which caused the error. 
The strange thing is when I use the online validation I do not encounter this error.
So this error is caused by a bug in the code however the command near line 871 said that the execution of this code should never occur.
After comparing online and offline validation I found that the online validation doesn't use LINC01297 (as seen in the localhost:8080/api/genes) while the offline does (as seen in the portal info genes.json) and therefore will reach the bug.

While looking further into [issue #799](https://github.com/cBioPortal/cbioportal/issues/799) (which was also mentioned near the bug) I saw that the idea is that every Hugo links to one Entrez ID however LINC01297 has two entries in https://github.com/cBioPortal/datahub/raw/master/seedDB_hg38/seed-cbioportal_hg19_hg38_v2.11.0.sql.gz 

**My question/proposal**
So my question is why LINC01297 got two entries in the seed db and why is the offline different than the online validation?
I propose to fix the bug by changing rule 871 into something like this:  
`'/'.join([str(id) for id in self.portal.hugo_entrez_map[gene_symbol]])`
And if possible change the seed to only contain one LINC01297 (Entrez id: [115694671](https://www.ncbi.nlm.nih.gov/gene/?term=115694671%5Buid%5D)) as the second Entrez id [106146148](https://www.ncbi.nlm.nih.gov/gene/?term=106146148) links to PSLNR.

**How to recreate my problem:**

1. Install cBioPortal according to the [documentation §2.1.1](https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker) (I have tested it on version 3.4.10 and 3.4.12 and using HG38)
2. Enter the running cbioportal_container:
```
docker exec -it cbioportal_container bash
```
3. Create the portal info files needed for the offline validation:
```
mkdir /tmp/portalinfo
cd /cbioportal/core/src/main/scripts/
./dumpPortalInfo.pl /tmp/portalinfo
```
4. Export the data to the host machine:
```
exit
docker cp cbioportal_container:/tmp/portalinfo .
```
5. Run the offline validation:
```
docker run --network="host" --rm  -v /portalinfo/:/cbioportal_db_info/ -v /cbioportal-docker-compose/config/portal.properties:/cbioportal/portal.properties -v /cohortData/:/study/cohortData cbioportal/cbioportal:3.4.12 metaImport.py -p /cbioportal_db_info -s /study/cohortData -ucsc hg38 -ncbi GRCh38
```
6. During validation of the MAF file containing LINC01297* you ("hopefully") encounter the following error:
```
Traceback (most recent call last):
File "/usr/local/bin/metaImport.py", line 129, in <module>
  exitcode = validateData.main_validate(args)
File "/cbioportal/core/src/main/scripts/importer/validateData.py", line 5413, in main_validate
  validate_study(study_dir, portal_instance, logger, relaxed_mode, strict_maf_checks)
File "/cbioportal/core/src/main/scripts/importer/validateData.py", line 5303, in validate_study
  validator.validate()
File "/cbioportal/core/src/main/scripts/importer/validateData.py", line 410, in validate
  self._validate_file()
File "/cbioportal/core/src/main/scripts/importer/validateData.py", line 544, in _validate_file
  self.checkLine(fields)
File "/cbioportal/core/src/main/scripts/importer/validateData.py", line 1469, in checkLine
  normalized_gene = self.checkGeneIdentification(hugo_symbol, entrez_id)
File "/cbioportal/core/src/main/scripts/importer/validateData.py", line 871, in checkGeneIdentification
    '/'.join(self.portal.hugo_entrez_map[gene_symbol]),
TypeError: sequence item 0: expected str instance, int found
```
 
7. If you run the online validation, you will (hopefully) not encounter the error:
```
docker-compose run -v "/cohortData:/report"  -v "/cohortData:/study/cohortData" cbioportal metaImport.py -u http://cbioportal:8080 -s /study/cohortData --html=/report/report.html -ucsc hg38 -ncbi GRCh38
```
*The MAF file was created with [vcf2maf](https://github.com/mskcc/vcf2maf) version 1.6.16 tool. In the MAF file, the Entrez column contained the value 0 when the gene was LINC01297

**End note**
I hope someone could tell me more about this problem.
_Disclaimer: This is my first time writing an issue so feel free to give feedback and let me know if I missed a convention. 😇_

**Comment by jjgao** [comment]
@AlexJanse Thanks for writing this! It is great - clear and detailed :) We will look into this. 

For the moment on your side, maybe manually remove the incorrect entrez id from the database?

**Comment by AlexJanse** [comment]
@jjgao Thanks for the kind reply! 
Yes, I have removed it from the database and now it is working fine. (^__^)
