### ISSUE TITLE
Copy Number Data Summary Tab issue

### ISSUE THREAD

**Issue by Mohammedhusen** [cBioPortal/cbioportal#7979]
Hi Team,
 
Recently we try to load the Copy Number Data into one of our local study after successful loading of data on the summary tab it shows the below error.
Could you please help us to rectify this issue?

![image](https://user-images.githubusercontent.com/42175932/96291952-82261180-0ff1-11eb-8248-ead6213fbca2.png)

**Comment by jjgao** [comment]
@Mohammedhusen could you show us some of the meta files you have?

**Comment by Mohammedhusen** [comment]
Hi @jjgao ,

These are the metafiles we have.

meta_resource_sample.txt
meta_RNA_Seq_v2_mRNA_median_Zscores.txt
meta_RNA_Seq_mRNA.txt
meta_clinical_patient.txt
meta_clinical_sample.txt
meta_gsva_bindea_score.txt
meta_gsva_bindea_p_value.txt
meta_mutations_extended.txt
meta_resource_definition.txt
meta_cna_hg19_seg.txt
meta_CNA.txt
meta_study.txt

**Comment by jjgao** [comment]
Hi @Mohammedhusen, I saw that you have also email. let's continue the conversation there.
