### ISSUE TITLE
Error handlign: call to genomenexus ensemble endpoint failure breaks site, but we don't handle the error

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7981]
https://v1.genomenexus.org/ensembl/transcript

**Comment by jjgao** [comment]
@alisman not sure how urgent is this... Is there an example query?

**Comment by alisman** [comment]
It's not urgent but something that should be fixed by my on-going project to fix this in a proper generalized way.  It's not taking anyone's time so ..
