### ISSUE TITLE
Ambiguous Hugo gene symbols in `gene` table

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#799]
A few (~43 of the ~58,000) of the hugo gene symbols found in the `gene` table actually map to 2 or more Entrez_gene_id values. See:

```sql
SELECT 
 HUGO_GENE_SYMBOL, 
 count(*) nr_entrez_gene_ids, 
 GROUP_CONCAT(ENTREZ_GENE_ID) as entrez_gene_ids 
FROM cbioportal.gene
group by HUGO_GENE_SYMBOL
order by count(*) desc
```
**Shouldn't we have 1 hugo mapping to 1 entrez?**

I checked a few of the results from the query above and noticed that the extra entrez items refer to other (sub)species, i.e. not *Homo sapiens (human)*. E.g.

Hugo: 'TRNL', has 4 Entrez Ids: '8923214,8923186,6775086,6775067'
When I check these on http://www.ncbi.nlm.nih.gov/gene/, I get:
Gene ID: 8923214, updated on 27-Nov-2012  
trnL [ Homo sapiens ssp. Denisova (Denisova hominin) ]
Gene ID: 8923186, updated on 27-Nov-2012
trnL [ Homo sapiens ssp. Denisova (Denisova hominin) ]
Gene ID: 6775086, updated on 10-Oct-2014
trnL [ Homo sapiens neanderthalensis (Neandertal) ]
Gene ID: 6775067, updated on 10-Oct-2014
trnL [ Homo sapiens neanderthalensis (Neandertal) ]

Hugo: 'ATP6', has 3 Entrez Ids: '8923188,4508,6775074'
When I check these on http://www.ncbi.nlm.nih.gov/gene/, I get:
Gene ID: 8923188, updated on 28-Oct-2015
ATP6 ATP synthase F0 subunit 6 [ Homo sapiens ssp. Denisova (Denisova hominin) ]
Gene ID: 4508, updated on 16-Jan-2016
MT-ATP6 mitochondrially encoded ATP synthase 6 [ Homo sapiens (human) ]
Gene ID: 6775074, updated on 26-Jun-2015
ATP6 ATP synthase F0 subunit 6 [ Homo sapiens neanderthalensis (Neandertal) ]

**Comment by pieterlukasse** [comment]
@jjgao , @n1zea144 : maybe you can comment on this?

**Comment by pieterlukasse** [comment]
One additional comment/hint: when I look at the file from NCBI ftp://ftp.ncbi.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz I find also non human genes such as 6775067 in there. But these are clearly indicated to be from another taxonomy (see first column `tax_id` in file). Maybe when creating the seed database you forgot to filter out the rows from this file where tax_id != 9606 ?

**Comment by pieterlukasse** [comment]
**Update:** when removing items that are not human, the following ambiguous items still remain:
Hugo, count, entrez ids:
'HBD', '2', '3045,100187828'
'LSAMP-AS1', '2', '100506708,101926903'
'MEMO1', '2', '51072,7795'
'MMD2', '2', '221938,100505381'
'RNR1', '2', '6052,4549'
'RNR2', '2', '4550,6053'
'SFPQ', '2', '6421,654780'
'TEC', '2', '7006,100124696'

**Comment by ecerami** [comment]
HUGO Symbols should uniquely map to Entrez Gene IDs.

For example, in the RNR1 example above, we get:

http://www.ncbi.nlm.nih.gov/gene/?term=6052 (HUGO = RNR1)
http://www.ncbi.nlm.nih.gov/gene/?term=4549 (HUGO = MT-RNR1)

But, it could be that the gene mapping file in our seed database is old.  As next step, I would suggest reimporting genes by importing the NCBI gene_info file directly.  Then, check to see if any duplicates still exist.

**Comment by jjgao** [comment]
@ecerami we are updating the gene info about twice a year.

@pieterlukasse thanks for looking into this. To summarize, there are two issues.

1. The gene_info file we grab from NCBI may contain non-human genes.
1. The same symbol may be assigned to different entrez id.

We can solve the first one by filter out non-human genes (tax_id != 9606), but the second one is tricky. For exmaple, MMD2 is still assigned to two entrez ids in NCBI: http://www.ncbi.nlm.nih.gov/gene/?term=221938%2C100505381.

Since we are using Hugo Symbols as the main identifiers for the user, maybe we should use HGNC as our primary resource. They seem to have very nice annotation and format and contain all the info we need.

ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/locus_groups/protein-coding_gene.txt

@pieterlukasse @ecerami what do you think?

**Comment by ecerami** [comment]
hi @jjgao:  We may have a single gene symbol that matches to the different Entrez Gene IDs.  But, *HUGO* gene symbols should match unambiguously to 1 Entrez Gene ID.  In the example of MMD2 you just pasted, there is only one hit to official HUGO MMD2.  The second hit has MMD2, but it's not HUGO.

**Comment by jjgao** [comment]
@ecerami you are right. We are grabbing the wrong column for the symbol. Column K should be used instead of column C -- see below. I'll make the change.

![image](https://cloud.githubusercontent.com/assets/840895/12731462/1b36e154-c8ff-11e5-991e-6017de93f1f9.png)

**Comment by ecerami** [comment]
@jjgao thanks!  yes, that would fix it.

**Comment by aderidder** [comment]
hi @jjgao 
I was wondering whether there is an issue with updating the gene table with the ftp://ftp.ncbi.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz
Won't that file be based on hg38 and the map_location may have changed for a gene?

**Comment by jjgao** [comment]
@aderidder: that is possible. We would need to find a better solution than Homo_sapiens.gene_info.gz.

**Comment by pieterlukasse** [comment]
@jjgao another file that could be considered during the ImportGeneData script is will this maybe help: ftp://ftp.ncbi.nih.gov/gene/DATA/gene_history.gz, see also https://www.biostars.org/p/151574/

**Comment by pieterlukasse** [comment]
@jjgao @ecerami @priti88 : I wrote a small documentation page to help people update their gene table. Let me know your comments: https://github.com/thehyve/cbioportal/wiki/Updating-gene-and-gene_alias-tables

**Comment by jjgao** [comment]
I am closing this issue. Updating gene info can be logged in another issue if necessary.
