### ISSUE TITLE
Standalone Dockerfile

### ISSUE THREAD

**Issue by bollig** [cBioPortal/cbioportal#800]
FYI, I setup a Dockerfile following your installation guide to produce a minimal instance of cBioPortal with the brca-example data. Feel free to integrate it into your project. 

To run: 
        docker run -it bollig/cbioportal 
        firefox http://localhost:8080

Details here: https://github.com/bollig/docker-cbioportal

**Comment by ecerami** [comment]
Thanks @bollig for doing this!

One overall question:  how does this docker instance relate to releases of cBioPortal, e.g. is the docker instance static, or can it be auto-updated each time we generate a new release?

**Comment by bollig** [comment]
It's static at the moment. But each release can be tagged to match your
release schedule. The current tag is

bollig/cbioportal:latest

When you push to dockerhub, just swap latest for the new version number.

Also, a little warning about pushing to dockerhub: since the image layers
are pretty big, you'll likely need to push multiple times before all layers
make it up. Dockerhub will overfill a memory buffer while receiving the
layers. reattempting the push continues with the next unfinished layer, and
dockerhub's load balancer will send it to a fresh recipient. It took me
about 10 attempts to get all layers posted.

Cheers,
-E

On Wednesday, February 3, 2016, ecerami <notifications@github.com> wrote:

> Thanks @bollig <https://github.com/bollig> for doing this!
>
> One overall question: how does this docker instance relate to releases of
> cBioPortal, e.g. is the docker instance static, or can it be auto-updated
> each time we generate a new release?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cBioPortal/cbioportal/issues/800#issuecomment-179273936>
> .
>


-- 
-Evan Bollig
bollig@gmail.com
boll0107@umn.edu

**Comment by jjlaisnoopy** [comment]
I have encountered following errors, please help me to solve it.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Portal Master ...................................... SUCCESS [ 17.801 s]
[INFO] Portal Business Layer .............................. SUCCESS [03:26 min]
[INFO] Portal Core ........................................ SUCCESS [02:37 min]
[INFO] Portal Web Layer ................................... SUCCESS [ 32.505 s] 
[INFO] cBioPortal ......................................... FAILURE [ 18.046 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:13 min
[INFO] Finished at: 2016-06-21T03:18:05+00:00
[INFO] Final Memory: 261M/2620M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war) on project cbioportal: Error assembling WAR: IOException when zipping WEB-INF/lib/log4j-1.2.16.jar: No space left on device -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cbioportal
The command '/bin/sh -c /usr/local/maven/bin/mvn-DskipTests clean install' returned a non-zero code: 1

Best Regards,
Chun-Chi

**Comment by alexsigaras** [comment]
This issue has been resolved in release-1.5.0
