### ISSUE TITLE
Allow user to pass arguments to the jvm when importing a study

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [cBioPortal/cbioportal#8000]
Allow users to pass arguments to the jvm when running the `metaImport.py` script. I'm trying to import a study with a 26gb mutation file, and I get the following error:

```
java.lang.OutOfMemoryError: Java heap space
```

I'd like to pass jvm args to the import script, specifically the `-Xms` and `-Xmx` args so I can bump up the amount of memory java is allowed to access. 

Here's my current command:

```
docker-compose run cbioportal metaImport.py -u http://cbioportal:8080 -s study/mystudy/ -ncbi 38 -o
```

An example command:

```
docker-compose run cbioportal metaImport.py -u http://cbioportal:8080 -s study/mystudy/ -ncbi 38 -o -java_args "-Xms2g -Xmx4g"
```

 Thanks all.

**Comment by jjgao** [comment]
@kurt-mueller-osumc thanks for adding this issue. Please feel free to send us a pull request to add the option.
