### ISSUE TITLE
patient view fails to load

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8001]
I tried to enter patient view for all patients in brca_mbcproject_wagle_2017 (https://www.cbioportal.org/study/summary?id=brca_mbcproject_wagle_2017), but the page fails to load and I see these errors in the console:

![image](https://user-images.githubusercontent.com/10508276/97051430-2d344f00-154d-11eb-840f-8352299a187a.png)

**Comment by jjgao** [comment]
This is probably the same as https://github.com/cBioPortal/cbioportal/issues/8317.

**Comment by adamabeshouse** [comment]
should this be closed now @jjgao @alisman ?
