### ISSUE TITLE
CCLE treatment response data

### ISSUE THREAD

**Issue by bynjh007** [cBioPortal/cbioportal#8002]
Hi,

I am using CCLE data (Broad 2019) deposited in cBioPortal to associate genomic feature with treatment response.

Maybe I missed it, but I cannot find the information how treatment responses (AUC, IC50, ZScore) for CCLE cell lines has been obtained. It is said the data was downloaded from CCLE database but I cannot find that information in the database (https://portals.broadinstitute.org/ccle/data)

Braod drug response data was generated by CTRPv2 most recently, but the list of the drug is not matched to CCLE ones, so I would like to know more about the treatment response data that I am using now.

Best

**Comment by jjgao** [comment]
@bynjh007 for questions regarding data, would you please contact cbioportal@googlegroups.com. Thanks.
