### ISSUE TITLE
installation map feedback

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8003]
Before release:
- [x] Change the language for the link to the form: "Are you running a local instance of cBioPortal, public or private? Complete the survey here to add your installation to the map."
- [x] Add a description of what the map is about in the large map (upper left?)
  - e.g. "This map shows the public and private local instances of the cBioPortal. If you are running a local instance that is not included in this list, please complete [this survey] to add it to the map"
- [x] Use different marker for multiple installations
  - Moved to before release. This is low hanging fruit, and I think it will make the map a lot clearer.

Future work:
- [ ] Display more information, e.g. names, contact, and links to the sites (after consenting with the users)
- [ ] Color based on type (hospital, academic, commercial). (maybe also by whether it's public)

**Comment by jtquach1** [comment]
Related PRs:
- [3410](https://github.com/cBioPortal/cbioportal-frontend/pull/3410)
