### ISSUE TITLE
Timeline not showing numbers for samples when in single sample view mode

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8013]
Try e.g. https://genie-private.cbioportal.org/patient/summary?studyId=nsclc_genie_bpc&sampleId=GENIE-DFCI-011116-116358

<img width="539" alt="Screen Shot 2020-10-28 at 12 03 19 PM" src="https://user-images.githubusercontent.com/1334004/97462941-a0571000-1915-11eb-87a9-20ca5fd46425.png">

**Comment by adamabeshouse** [comment]
@inodb what would be the desired behavior?
