### ISSUE TITLE
Error installed on Windows (without Docker)

### ISSUE THREAD

**Issue by hungfitvn** [cBioPortal/cbioportal#8021]
I followed all steps to install without docker on my windows server 2012 R2. But when I ran mvn -Dskiptests clean install, I got this error

[ERROR] Failed to execute script: Cannot run program "./version.sh": CreateProcess error=193, %1 is not a valid Win32 application -> [Help 1]

Please advise.

**Comment by jjgao** [comment]
@hungfitvn we do not support Windows. You might want to consider docker.

**Comment by jeffm14** [comment]
@hungfitvn I think it should work with the windows subsystem for Linux if you're running on Windows.
