### ISSUE TITLE
GENIE performance - upload speed

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8026]
## Problem
GENIE was being super slow for me today, so I did a little poking around (with some help from @Luke-Sikina ). Perhaps you are already aware of this, but I found that most of the time was spent on the request upload: this is the gene-panel-data API call, which was the slowest component of loading the Cancer Types Summary page
![image](https://user-images.githubusercontent.com/10508276/97909746-b3ebe780-1d16-11eb-8795-18438220be8f.png)
(https://bit.ly/38hPy1R)

Several other API calls also took several minutes, and for all of them the time was almost all spent on sending the request.

Granted, my upload speed was particularly terrible at the time I was doing this, but, I still want to flag this as we think about performance improvements for GENIE.

## Proposed Solution
The poor performance that Tali was seeing was due to her low upload speed and the large size of some of our request bodies. 

### Short Term (Will close this issue)
- [x] Create a Filter that will wrap incoming http requests if they are a post and the content encoding is gzipped
  - [x] Simple implementation
  - [x] Verification
  - [x] Make sure you can't zip bomb us too easily
  - [x] Tests
  - [x] Code cleanup (Right now we have to read the whole request input stream, which means we have to parse the args ourselves. I'd rather not do this.)
  - [x] Documentation: portal.properties.example, and any markdown files that seem relevant 
- [x] Figure out how to gzip the body of select request on the frontend
- [x] Make configurable
### Long Term
Why do we have to send such large request bodies? This information originated in the backend, so can't we have a shared, abbreviated representation of the data that we can pass?

**Comment by jjgao** [comment]
@n1zea144 maybe it's time to implement your idea of removing the needs to sending back the huge list of samples IDs in request. One option is to cache them in the backend.
