### ISSUE TITLE
Check API responses private vs Public

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8030]
Currently the API response for a missing study is always 403 when auth is enabled I believe b/c we didn't want people to be able to determine what studies are missing vs which ones are available. In the public portal we do use 404 for missing. Let's investigate for at least all public facing endpoints what the status responses are and whether they make sense for public vs authenticated portals. There might also be some cases where we return an empty response if the user doesn't have access. Let's make sure all these responses are consistent for all public facing endpoints

**Comment by jagnathan** [comment]
https://docs.google.com/spreadsheets/d/1WKI5074ZfrGp1qjKRUQQAHJyQioEE5QY-NDCDR1vUug/edit?usp=sharing
