### ISSUE TITLE
401 when importing study (SAML authentication)

### ISSUE THREAD

**Issue by weberc2-tempus** [cBioPortal/cbioportal#8033]
The metaImport.py script is getting a 401 when trying to import a study. My installation of CBioPortal uses SAML authentication, and metaImport.py doesn't seem to take any authentication parameters. Is there a workaround? I didn't see anything documented.

**Comment by inodb** [comment]
@weberc2-tempus not sure if you got an answer but there is a workaround: https://docs.cbioportal.org/5.1-data-loading/data-loading/using-the-dataset-validator#example-4-generating-the-portal-info-folder. If you generate the portal info you can use that to validate against. Hope that fixes your issue!
