### ISSUE TITLE
Installation map - allow moderation before adding to map

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8038]
We should moderate the submitted entries before adding to the map since there could be spam or duplicate submission. 

I added one column `Approved`, please only pull the rows when it is a `Yes` for that column. Please also repopulate the current map as a couple of duplicate submissions were removed.

**Comment by jtquach1** [comment]
The quickstart.py file handles filtering of entries with a "Yes" for the Approved column, so repopulating the map with the correct entries is a manner of deleting the current waypoints.json file in the production installation map repo.
