### ISSUE TITLE
redirect /data_sets.jsp isn't working

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8042]
Frontend does seem to correctly redirect:

```
            <Redirect from={'/data_sets.jsp'} to={'/datasets'} />
```
https://github.com/cBioPortal/cbioportal-frontend/blob/6b053383a5e0f8450b4fe5b40fb6d3cafd2657de/src/routes.jsx#L402

Guess error is at the backend layer b/c this gives 404:
https://www.cbioportal.org/data_sets.jsp

**Comment by jjgao** [comment]
I am wondering if we still need to support it? Maybe it's ok to remove this redirection?

**Comment by jjgao** [comment]
@inodb I am closing this. Please feel free to reopen if this is still necessary.
