### ISSUE TITLE
Hotspot lollipop annotations don't match oql DRIVER logic

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8043]
Maybe this is on purpose but just wanted to check, try e.g. https://bit.ly/32mJIbG

without filtering there is 831 3d hotspot mutation (5 hotspots in total):
<img width="1085" alt="Screen Shot 2020-11-08 at 10 20 01 AM" src="https://user-images.githubusercontent.com/1334004/98469183-15df9d80-21ac-11eb-9372-807948aab850.png">
with filtering:

with oql filtering that mutation is gone (only 4 hotspots show up):
<img width="1092" alt="Screen Shot 2020-11-08 at 10 20 09 AM" src="https://user-images.githubusercontent.com/1334004/98469181-15470700-21ac-11eb-9ab9-37abb11bba22.png">

I thought maybe OQL only looks at linear hotspots and not 3D ones, but some 3D ones do show up e.g.:

<img width="1070" alt="Screen Shot 2020-11-08 at 10 23 57 AM" src="https://user-images.githubusercontent.com/1334004/98469295-9b634d80-21ac-11eb-8b58-5dfa7a7a68b7.png">

**Comment by jjgao** [comment]
@inodb

**Comment by jjgao** [comment]
@inodb it was b/c oncokb that the 3d hotspots (H893 & P753) were included, but R831 was not oncogenic per oncokb.

![image](https://user-images.githubusercontent.com/840895/99006388-5de62380-2510-11eb-81f0-eb47935f5a0f.png)
