### ISSUE TITLE
Namespaces feature does not work

### ISSUE THREAD

**Issue by Sjoerd-van-Hagen** [cBioPortal/cbioportal#8050]
Adding columns using namespaces as described [here](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#mutation-data) does not work because the validator rejects the study.

This is the error message:
Study has been validated with errors: Validation failed. Error code: 1; ERROR: data_mutations_extended.txt: ns namespace defined but MAF does not have any matching columns
ERROR: data_mutations_extended.txt: Invalid column header, file cannot be parsed

**Comment by Sjoerd-van-Hagen** [comment]
To reproduce, take http://download.cbioportal.org/paac_jhu_2014.tar.gz

Replace the mutation metadata with:
`cancer_study_identifier: paac_jhu_2014
genetic_alteration_type: MUTATION_EXTENDED
stable_id: mutations
datatype: MAF
show_profile_in_analysis_tab: true
profile_description: Mutation data from whole exome sequencing of 23 pancreatic carcinomas with acinar differentiation and their matched normals.
profile_name: Mutations
data_filename: data_mutations_extended.txt
namespaces: ns`

and mutation data with:
`Hugo_Symbol	Entrez_Gene_Id	Center	NCBI_Build	Chromosome	Start_Position	End_Position	Strand	Consequence	Variant_Classification	Variant_Type	Reference_Allele	Tumor_Seq_Allele1	Tumor_Seq_Allele2	dbSNP_RS	dbSNP_Val_Status	Tumor_Sample_Barcode	Matched_Norm_Sample_Barcode	Match_Norm_Seq_Allele1	Match_Norm_Seq_Allele2	Tumor_Validation_Allele1	Tumor_Validation_Allele2	Match_Norm_Validation_Allele1	Match_Norm_Validation_Allele2	Verification_Status	Validation_Status	Mutation_Status	Sequencing_Phase	Sequence_Source	Validation_Method	Score	BAM_File	Sequencer	t_ref_count	t_alt_count	n_ref_count	n_alt_count	HGVSc	HGVSp	HGVSp_Short	Transcript_ID	RefSeq	Protein_position	Codons	Hotspot	n_depth	t_depth NS.test1
CACNA1H	0	John_Hopkins	GRCh37	16	1248690	1248692	+	inframe_deletion	In_Frame_Del	DEL	TCT	TCT	-	NA	NA	ACINAR01	NA	NA	NA					NA	NA	NA	NA	NA	NA	NA	NA	Illumina HiSeq	.	.	.	.	ENST00000348261.5:c.724_726del	p.Phe242del	p.F242del	ENST00000348261	NM_021098.2	240	gTCTtc/gtc	0	0	0   value1`

**Comment by pvannierop** [comment]
@ino @Sjoerd-van-Hagen I have fixed this feature (which was not implemented as described in the docs) for the LOH mutation status (RFC57). Let's discuss merging this backend to fix this.

**Comment by Sjoerd-van-Hagen** [comment]
@inodb @pvannierop how are we doing on this one?

**Comment by Sjoerd-van-Hagen** [comment]
@inodb @pvannierop this should be a relatively easy fix, right?

**Comment by Sjoerd-van-Hagen** [comment]
@inodb This work is already done. Let's get it merged.
