### ISSUE TITLE
Results page: Error downloading data from Download tab

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#8052]
Reported by user: https://groups.google.com/g/cbioportal/c/sIp7ciW7vL8

There is an error downloading data from `Type of Genetic Alterations Across All Samples` table

Example link to reproduce this issue: [example](https://www.cbioportal.org/results/download?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=kirc_tcga&case_set_id=kirc_tcga_cnaseq&data_priority=0&gene_list=TP53&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=kirc_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=kirc_tcga_mutations&profileFilter=0&tab_index=tab_visualize)

**Comment by dippindots** [comment]
@kalletlak @adamabeshouse I took a brief look at this issue, looks like this is related to our recent change in this pr: https://github.com/cBioPortal/cbioportal-frontend/pull/3491.
