### ISSUE TITLE
custom charts PR feedback

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8057]
I hit a bug pretty quickly so didn't get very far in testing, but I think I also need some additional details on what custom charts can do before I can really test this.

1) When I tried to add a custom chart, it seems to have frozen on "Saving" - this view never changed and the chart never added
![image](https://user-images.githubusercontent.com/10508276/98867923-5dc92380-243d-11eb-8918-8d8b20fea17c.png)

And these console errors appeared:
![image](https://user-images.githubusercontent.com/10508276/98868302-e6e05a80-243d-11eb-83ed-dced144b9e1d.png)

2) Related to first screenshot above - if the chart is in the process of being saved, it's confusing to have a check mark there. When adding a gene-level chart, I think there's a little loading animation - could we use something like that here also?

3) To help me make sure I know what to test once this bug is fixed, I'm going to list out a bunch of things that might be possible for custom data charts - can you confirm which are existing features, which are new features for this PR (so not currently in production), and if there's anything I'm missing?
A chart can be saved to a user profile when user is logged in and will be present the next time a user logs in
A chart can be saved when a user is not logged in (although I'm not sure what "saving" means in this context)
A chart can be used to filter study view
A saved chart can be shared with another user
A saved chart can be deleted
A saved chart can be hidden from study view (deselected in the Charts menu) but will still exist for the user and can be re-selected at any point

If it's easier, I'm also happy to talk rather than do this through GitHub. But I'm realizing there's a lot that's theoretically possible for these charts and I've lost track of what is implemented.

Also, I can't log in when testing with the heroku instance listed in the PR - depending on your answers to the list above, I think testing while logged in will be necessary, and I don't know how to do that.

**Comment by kalletlak** [comment]
> I hit a bug pretty quickly so didn't get very far in testing, but I think I also need some additional details on what custom charts can do before I can really test this.
> 
> 1. When I tried to add a custom chart, it seems to have frozen on "Saving" - this view never changed and the chart never added
>    ![image](https://user-images.githubusercontent.com/10508276/98867923-5dc92380-243d-11eb-8918-8d8b20fea17c.png)
> 
> And these console errors appeared:
> ![image](https://user-images.githubusercontent.com/10508276/98868302-e6e05a80-243d-11eb-83ed-dced144b9e1d.png)

heroku session-service might be down at that moment. I would take couple of minutes to be back.

> 2. Related to first screenshot above - if the chart is in the process of being saved, it's confusing to have a check mark there. When adding a gene-level chart, I think there's a little loading animation - could we use something like that here also?

sure.

> 3. To help me make sure I know what to test once this bug is fixed, I'm going to list out a bunch of things that might be possible for custom data charts - can you confirm which are existing features, which are new features for this PR (so not currently in production), and if there's anything I'm missing?
>    A chart can be saved to a user profile when user is logged in and will be present the next time a user logs in
>    A chart can be saved when a user is not logged in (although I'm not sure what "saving" means in this context)
>    A chart can be used to filter study view
>    A saved chart can be shared with another user
>    A saved chart can be deleted
>    A saved chart can be hidden from study view (deselected in the Charts menu) but will still exist for the user and can be re-selected at any point
> 

Existing features.

- Custom chart are saved to user page settings only when the user is logged in and the chart is visible. Only these will be present the time a user logs in
- Sharing is not possible
- Filtering on these charts work, but sharing filter url would include filtered samples without chart information
- To delete chart, hide it from study view

New features
- Custom charts can be created with or without user logs in. If the user is logged in those charts are saved to user profile
- It can be shared/deleted (logged in or not), similar to groups
- Filtering would be similar to other charts, i.e, filters would be applied to appropriate custom charts
- And yes, a saved chart can be hidden from study view (deselected in the Charts menu) but will still exist for the user and can be re-selected at any point for logged in users



> If it's easier, I'm also happy to talk rather than do this through GitHub. But I'm realizing there's a lot that's theoretically possible for these charts and I've lost track of what is implemented.
> 
> Also, I can't log in when testing with the heroku instance listed in the PR - depending on your answers to the list above, I think testing while logged in will be necessary, and I don't know how to do that.

I'll have to check with @inodb and see if it is possible to enable auth

**Comment by tmazor** [comment]
This looks great @kalletlak ! I think I've testing everything I can without being logged in - is there any update on how to test with login?

1) I love how the charts menu automatically opens when following a shared chart link - however, the message says the chart has been saved to my profile, even though I'm not currently logged in. Won't it only save if logged in? Can we have 2 different messages depending on if the user is logged in or not?
![image](https://user-images.githubusercontent.com/10508276/99576899-94a4b980-29a8-11eb-8986-7f6926987c6b.png)

Note: Highlighted rows are shared custom data. They have been saved to your profile. [there's a missing space between the two sentences]
Note: Highlighted rows are shared custom data. Log in to save custom data charts to your profile.

2) Can we add Select/Deselect All buttons like the Clinical & Genomic charts tabs have?

3) I applied a filter, then used the Custom Data tab to create a new chart based on the currently selected samples. I then clicked "currently unselected" to create that chart, but when I tried to add it, the page broke - console errors below. FWIW, this is also not working right in production right now and I made a separate ticket about that (#8077)

![image](https://user-images.githubusercontent.com/10508276/99578168-6d4eec00-29aa-11eb-8635-dbe46f4638a1.png)

4) Can we update this text for deleting charts:
Note: Deleted charts will be permanently removed when this menu is closed. Any active filters based on deleted charts will also be removed.
![image](https://user-images.githubusercontent.com/10508276/99579573-57dac180-29ac-11eb-9695-0e9523557605.png)

**Comment by tmazor** [comment]
1. If I repeat the steps in 3 (above), it behaves much better now in that it filters down to 0 samples and gives a warning. However, 2 things could still be improved:
    - Can we remove the whole loading/rendering thing? It makes it seem like despite the warning above, some data may appear
![image](https://user-images.githubusercontent.com/10508276/101503734-6a5b7180-3940-11eb-8ddd-89b599998d0f.png)
    - There's still an error in the console
![image](https://user-images.githubusercontent.com/10508276/101503975-b0183a00-3940-11eb-81fd-62ac5b1fd547.png)

2. When logged in, the charts menu says "Note: They have been saved to your profile"
![image](https://user-images.githubusercontent.com/10508276/101505159-09cd3400-3942-11eb-8295-f180e6ab2dea.png)
Can the message be a bit clearer, eg "Note: Custom charts are saved to your profile."

3. After logging in, I open a new tab with the same study to confirm that my saved chart would be present. It was, however the menu also showed a bunch of custom charts that I had created and deleted prior to logging in.

The screenshot above is what the one chart I had when I logged in. The screenshot below is what I saw after loading a new tab:
![image](https://user-images.githubusercontent.com/10508276/101505721-a8f22b80-3942-11eb-925e-0aedc5cb2923.png)

Also the menu says "primary pie chart is removed" at the bottom when it really shouldn't have any message because all I've done is load the page.

4. Also just a general comment - there's a lot happening in this menu. Can we improve the layout somehow? eg put more space or a horizontal line between the "add custom chart" section and the "list of custom charts" section? Maybe @alisman has some thoughts?

**Comment by kalletlak** [comment]
> 1. If I repeat the steps in 3 (above), it behaves much better now in that it filters down to 0 samples and gives a warning. However, 2 things could still be improved:
>    
>~~* Can we remove the whole loading/rendering thing? It makes it seem like despite the warning above, some data may appear~~
 
> ![image](https://user-images.githubusercontent.com/10508276/101503734-6a5b7180-3940-11eb-8ddd-89b599998d0f.png)
>    * There's still an error in the console
>      ![image](https://user-images.githubusercontent.com/10508276/101503975-b0183a00-3940-11eb-81fd-62ac5b1fd547.png)

This might be a different issue. Not related to this

>~~2. When logged in, the charts menu says "Note: They have been saved to your profile"
>    ![image](https://user-images.githubusercontent.com/10508276/101505159-09cd3400-3942-11eb-8295-f180e6ab2dea.png)
>    Can the message be a bit clearer, eg "Note: Custom charts are saved to your profile."~~
> 3. After logging in, I open a new tab with the same study to confirm that my saved chart would be present. It was, however the menu also showed a bunch of custom charts that I had created and deleted prior to logging in.
> 
> The screenshot above is what the one chart I had when I logged in. The screenshot below is what I saw after loading a new tab:
> ![image](https://user-images.githubusercontent.com/10508276/101505721-a8f22b80-3942-11eb-925e-0aedc5cb2923.png)

Unable to reproduce it.
> 
> Also the menu says "primary pie chart is removed" at the bottom when it really shouldn't have any message because all I've done is load the page.

May be this chart was not present in previously saved user setting. No loading it might be removed. Or it might be a previous operation (content of dropdown is not reset).
> 
> 4. Also just a general comment - there's a lot happening in this menu. Can we improve the layout somehow? eg put more space or a horizontal line between the "add custom chart" section and the "list of custom charts" section? Maybe @alisman has some thoughts?

**Comment by tmazor** [comment]
@kalletlak to reproduce 3:

While not logged in, go to study view: https://cbioportal-fix-7726-bs0ipkcana.herokuapp.com/study/summary?id=glioma_msk_2018

Create charts - here I just selected all samples and created 3 identical custom charts:
![image](https://user-images.githubusercontent.com/10508276/101786052-79225f80-3acb-11eb-90d1-40aa503fe085.png)

Deselect one of the charts:
![image](https://user-images.githubusercontent.com/10508276/101786153-99eab500-3acb-11eb-9f38-76675e066256.png)

Now delete 2 of those charts:
![image](https://user-images.githubusercontent.com/10508276/101786207-aa9b2b00-3acb-11eb-9a43-0bbfcede6b9d.png)

Log in:
![image](https://user-images.githubusercontent.com/10508276/101786294-c0105500-3acb-11eb-8bda-9df555c71705.png)

Open a new tab, go to the same study view page and look at the custom charts - the deleted charts are present:
![image](https://user-images.githubusercontent.com/10508276/101786421-e930e580-3acb-11eb-976b-ee0464e10257.png)
Actually I think you can just reload the same page and you'll see the same behavior.

This time that message at the bottom didn't persist to the new tab, so I guess I also can't reproduce that. But actually that message sticks around longer than it should in the original window - as soon as I deleted 'all 2', the message about removing 'all 2' should have disappeared. I don't know if this would make things easier or harder, but I would be ok with those kinds of messages disappearing as soon as the Charts menu is closed.

**Comment by tmazor** [comment]
@kalletlak The issue above is working great now. I just came across one new thing:
I was not logged in, in study view, for a study where I have previously saved custom data charts (but I suspect this would apply for any study with saved settings for which charts are visible)
I created a new custom chart ("new3"), which then also applied a filter for that chart
I logged in. This changed the visible charts to be the saved view, including removing the new chart, but the filter for the new chart was still applied:
![image](https://user-images.githubusercontent.com/10508276/102241656-34316b00-3ec7-11eb-8446-df753b137bd1.png)
So the end result is a filter applied for a chart that isn't visible, which we shouldn't have.

**Comment by kalletlak** [comment]
@tmazor This might be a bug related to chart visibility and filters when user log in. I'll try to fix it.

**Comment by jjgao** [comment]
@kalletlak if a user add some custom data without log in, I am wondering if it is possible to add that custom data into user's profile automatically when they log in?

**Comment by kalletlak** [comment]
@jjgao yes it does.

**Comment by kalletlak** [comment]
@tmazor @jjgao updated pr to it. If there are any filters then chart will be always shown

**Comment by tmazor** [comment]
looks good to me @kalletlak !

**Comment by tmazor** [comment]
oh - well actually the only remaining thing is that I still think we can probably improve the layout of this menu - perhaps with some space or something to separate the two main functions within this menu (adding a custom chart and managing existing custom charts) but that doesn't need to delay deployment. @alisman any ideas?

**Comment by jjgao** [comment]
Agreed with @tmazor. We can use some of @alisman's magic touch on the UI.
