### ISSUE TITLE
Genomic evolution feature: highlight only partially works when splitting samples

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#8058]
In the example below, when hovering over a mutation, the chart only highlights the variant in the biopsy samples, not the cfDNA, when splitting by sample class

![image](https://user-images.githubusercontent.com/11892704/98962641-d7602080-24d4-11eb-9905-0baa06e8d253.png)

**Comment by pvannierop** [comment]
@schultzn @jjgao Can you give us the study and patient id that was used to create this image?

**Comment by jjgao** [comment]
@pvannierop thanks for looking into this. I was able to reproduce it in the public portal:

1. open https://www.cbioportal.org/patient/genomicEvolution?caseId=P27&studyId=lgg_ucsf_2014
2. check `Show samples in sequential mode`
3. select `Sample type` for the `Group by` dropdown
4. click the IDH1 mutation in the table

![image](https://user-images.githubusercontent.com/840895/101514533-5d904b00-394b-11eb-9702-afc4ab7e007a.png)

**Comment by dianab0** [comment]
Fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/3794
