### ISSUE TITLE
(Patient view) Mutational Signatures category color change

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#8076]
This is a follow up of https://github.com/cBioPortal/cbioportal/issues/7804. We should use the same color category code as CVR is using.

tasks:
- [x] contact with CVR team to figure out the color code they are using
- [ ] change our color

Update our category and color mapping to:
Cat | Sign
-- | --
Aging | Signature.1
APOBEC | Signature.13
APOBEC | Signature.2
HRD | Signature.3
MMR | Signature.15
MMR | Signature.20
MMR | Signature.26
MMR | Signature.6
Unknown | Signature.12
Unknown | Signature.16
Unknown | Signature.17
Unknown | Signature.18
Unknown | Signature.19
MMR | Signature.21
Aristolochic acid | Signature.22
Unknown | Signature.23
Aflatoxin | Signature.24
Unknown | Signature.25
Unknown | Signature.27
Unknown | Signature.28
Unknown | Signature.30
OTHER | Signature.5
OTHER | Signature.8
IGHV | Signature.9
POLE | Signature.10
MMR | Signature.14
Smoking | Signature.4
TMZ | Signature.11
Tobacco | Signature.29
UV | Signature.7

Cat | Color
-- | --
Aging | #3B99D4
APOBEC | #8ED14B
HRD | #F06B49
MMR | #D92B45
POLE | #19413E
Smoking | #B221E8
TMZ | #076B82
Tobacco | #50136D
UV | #FFEC00
Unknown | #E8E8E8
Aflatoxin | #E8E8E8
Aristolochic acid | #E8E8E8
IGHV | #E8E8E8

**Comment by jjgao** [comment]
Cat | Sign
-- | --
AGEING | Signature.1
APOBEC | Signature.13
APOBEC | Signature.2
BRCA | Signature.3
MMR | Signature.15
MMR | Signature.20
MMR | Signature.26
MMR | Signature.6
OTHER | Signature.12
OTHER | Signature.16
OTHER | Signature.17
OTHER | Signature.18
OTHER | Signature.19
OTHER | Signature.21
OTHER | Signature.22
OTHER | Signature.23
OTHER | Signature.24
OTHER | Signature.25
OTHER | Signature.27
OTHER | Signature.28
OTHER | Signature.30
OTHER | Signature.5
OTHER | Signature.8
OTHER | Signature.9
POLE | Signature.10
POLE/MMR | Signature.14
SMOKING | Signature.4
TMZ | Signature.11
TOBACCO | Signature.29
UV | Signature.7


Cat | Color
-- | --
AGEING | black
APOBEC | #8ED14B
BRCA | #F06B49
MMR | #D92B45
OTHER | #E8E8E8
POLE | #19413E
POLE/MMR | #0AB4C0
SMOKING | #B221E8
TMZ | #076B82
TOBACCO | #50136D
UV | #FFEC00

**Comment by dippindots** [comment]
Got feedback from CRV and updated color for `AGEING` category, other colors are correct.
