### ISSUE TITLE
currently unselected custom chart does not work right

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8077]
Steps to reproduce:
In lgg_ucsf_2014, apply filter for sample type = Primary
Create & add custom chart for selected samples ("Primary")
Now create and add a custom chart for currently unselected samples ("Not Primary") -- the chart adds and the header claims that filters are currently being applied for both custom charts, even though that should result in 0 samples remaining... 

![image](https://user-images.githubusercontent.com/10508276/99578407-cc146580-29aa-11eb-8f7b-8a49f5be4d9e.png)

**Comment by tmazor** [comment]
@kalletlak is this released on production? I'm still able to get to the same state:
![image](https://user-images.githubusercontent.com/10508276/101503088-bc4fc780-393f-11eb-8b42-8e13b7e68fe5.png)

**Comment by kalletlak** [comment]
@tmazor this is fixed but not yet released to production

**Comment by tmazor** [comment]
ok thanks @kalletlak! I saw it was merged a week ago so assumed it would be live by now, but I can be patient
