### ISSUE TITLE
Session service not configured warning message is no longer showing up

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8088]
We used to have a warning when you don't specify `-Dsession.service.url=`

When using EXAMPLE file properties and:
```
mvn -DskipTests clean install && java      -Dauthorization=false -Dauthenticate=false -Dapp.name='public-portal' -Ddbconnector=dbcp -jar portal/target/dependency/webapp-runner.jar   --port 9090 portal/target/cbioportal.war
```
I get a frontend error in the console saying something about `Nodelist`, but not the screen we used to have that indicates session service needs to be set up with a link to the docs

**Comment by alisman** [comment]
@inodb confirmed on production and genie portals using 
localStorage.frontendConfig = JSON.stringify({ serverConfig:{ sessionServiceEnabled: false } });
