### ISSUE TITLE
OncoPrinter: User-specified drivers should not be the default setting

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#8089]
User-specified drivers should not be the default setting in OncoPrints. We should turn driver v passenger off, or use OncoKB by default.

![image](https://user-images.githubusercontent.com/11892704/100290359-22ece280-2f49-11eb-91ed-f87a60f4bcd8.png)

**Comment by adamabeshouse** [comment]
@schultzn just want to make sure you are aware that it is only on by default if there are any user-specified drivers in the data, as in the example data. when there are no user-specified drivers then that option is gone from the mutation menu altogether.

**Comment by jjgao** [comment]
@schultzn it is selected by default b/c the user-specific drivers were included in the input. When there is no user-specific drivers in the input, OncoKB will be selected by default. Maybe we should have some warning message?
