### ISSUE TITLE
Issue when trying to throw error message

### ISSUE THREAD

**Issue by nr23730** [cBioPortal/cbioportal#8091]
I just set up a new instance of cBioPortal and forgot to set the `session.service.url`. Instead of showing me the desired error message the frontend crashes and prints the following error message that seems to be related to clipboard.js on the console:

```
Uncaught TypeError: First argument must be a String, HTMLElement, HTMLCollection, or NodeList
```

**Comment by inodb** [comment]
Thanks for sharing, just noticed that as well: https://github.com/cBioPortal/cbioportal/issues/8088

**Comment by jjgao** [comment]
closing this and track in #8088
