### ISSUE TITLE
Separate OncoKB Card as an independent component so other projects can use

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#8094]
The request comes from MPath group that they like to use the OncoKB Card in their system.

**Comment by onursumer** [comment]
@zhx828 Would it be useful if we just exported the component in `react-mutation-mapper` as a quick workaround? Other projects could then do `import {OncoKbCard} from 'react-mutation-mapper'`.

**Comment by jjgao** [comment]
Not sure if this is still needed... Maybe we can reopen it if/when the need arises again?
