### ISSUE TITLE
Wiki Documentation Needed for New Validator and Importer Scripts

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#810]
We need Wiki Documentation for the New Validator and Importer Scripts.

@priti88 @pieterlukasse:  is this already in the works somewhere?

**Comment by pieterlukasse** [comment]
@ecerami : yes, you can find the draft page at The Hyve's fork: https://github.com/thehyve/cbioportal/wiki/Using-the-dataset-validator

The following pages also need to be added:
- [ ] loading a study
- [ ] removing a study

**Comment by pieterlukasse** [comment]
assigning to @aderidder as he is updating the documentation for 
- [ ] timeline data
- [ ] gistic amp/del
- [ ] mutsig 

Once #808 is finished, then:
- [ ] the respective clinical data documentation should also be adjusted accordingly

**Comment by aderidder** [comment]
I added some documentation about gistic and mutsig last week. Gistic still needs some more information about the "massaging", but hopefully using the cbioportal-pipelines will be easier with the #873 
Timeline data documentation is nearly finished. Some small questions remain and are being discussed with Ino.

Front page for the data loading: https://github.com/thehyve/cbioportal/wiki/Data-Loading
I'm also following the links defined there and checking what still needs to be added.
