### ISSUE TITLE
Linking OncoKB to MSI_TYPE instead of MSI_SCORE

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8100]
Currently, OncoKB is linked based on MSI_SCORE>10 (https://github.com/cBioPortal/cbioportal-frontend/pull/3469). It would be good to link to MSI_TYPE instead so that it can be called with different method. Another reason is that even if the score is >10, MSI_TYPE can be "Do not report" in the MSK IMPACT cohort.

**Comment by inodb** [comment]
We need to check vocabulary for MSI_TYPE

**Comment by inodb** [comment]
Same issue for TMB (maybe we can use high or some other vocabulary, this will require some more discussion)
