### ISSUE TITLE
Gene alteration frequencies in Results tab are incorrect (<0.1%)

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#8102]
https://bit.ly/3qAqfOV

The frequency here should be <1%

**Comment by alisman** [comment]
@schultzn i'm confused. right now i see:

![image](https://user-images.githubusercontent.com/186521/102280897-f69b0500-3efb-11eb-8310-7874db8a0d17.png)

should be displaying this as <1%. ?

**Comment by jjgao** [comment]
@alisman it's the top right ones:

![image](https://user-images.githubusercontent.com/840895/102384554-df5f2480-3f9a-11eb-91a0-f57510bf18c4.png)

**Comment by alisman** [comment]
got it.  fixing it right now
