### ISSUE TITLE
Indicate in help message that there are multiple cbioportal instances

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8111]
Occasionally people forget that there are multiple cBioPortal instances and visit the wrong URL. Maybe we can mention something about this when a study is not found e.g.

- [ ] in the query page when searching for a study and the result is empty. 
     ![Screen Shot 2020-12-16 at 9 14 56 AM](https://user-images.githubusercontent.com/1334004/102359760-31924c80-3f7f-11eb-8feb-0d76722bd376.png)
    *Proposed*
    
    There are no studies matching your filter.
    
    Note: If you believe a particular study is not showing up, make sure you are visiting the cBioPortal URL that has this study (this is URL_NAME, see other instances at INSTALLATION_MAP_URL). If you would like to propose a study to be curated, please reach out EMAIL

- [ ] in the quick search bar:
    ![Screen Shot 2020-12-16 at 9 18 48 AM](https://user-images.githubusercontent.com/1334004/102360213-bb421a00-3f7f-11eb-86cc-3ef1685794f9.png)
    *Proposed*

    No results.

    Note: If you believe there should be a result, make sure you are visiting the correct cBioPortal URL (this is URL_NAME, see other instances at INSTALLATION_MAP_URL)."

CC @tmazor - do you think something like this makes sense?

**Comment by koolgax99** [comment]
can you please assign me this issue @inodb

**Comment by inodb** [comment]
Thanks for looking into it @koolgax99 !

**Comment by koolgax99** [comment]
@inodb as i am a beginner can you please guide me how to proceed. I took this issue to gain some confidence and also good first issue.
