### ISSUE TITLE
Pitfalls with the new genome version check ("specified reference genome does not correspond with the reference genome")

### ISSUE THREAD

**Issue by NikdAK** [cBioPortal/cbioportal#8113]
I had some difficulties with the new way of handling the genome version. 
Previously one would give -ucsc and -ncbi to the metaImport.py call. Now this is changed to look for the study meta file or the portal-properties. 

Some comments:

The "reference_genome" is marked as optional in the files formats information site, but for hg38 it will not work without this information ("specified reference genome does not correspond with the reference genome"). 
This is probably due to the fact, that there are some hard-coded lines in the docker-compose portal.properties:  
ncbi.build=37
ucsc.build=hg19

Additionally the docker-compose readme states that one should "... set reference_genome_id: hg38" but the actual command text should be reference_genome instead of reference_genome_id

Would be nice to fix this pitfalls, but it is working fine with "reference_genome: hg38" in the study_meta.txt.

Thank you for the nice work.

**Comment by jjgao** [comment]
@NikdAK thanks for reporting this. We will look into it. Please also feel free to send a pull request :)

**Comment by NikdAK** [comment]
Sure no problem! 

I now noticed that this is an issue for the cbioportal-docker-compose repo, sorry for this confusion. 
I created a pull request there: https://github.com/cBioPortal/cbioportal-docker-compose/pull/8
