### ISSUE TITLE
Support for Gene Lists for Targeted Sequencing

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#812]
Do we have documentation on how to import gene lists, e.g. for targeted sequencing?

Do we currently visualize (in the OncoPrint) whether a gene is WT v. not sequenced.

@priti88:  do you know the answer to either of these?

**Comment by priti88** [comment]
@ecerami Currently we cannot differentiate between gene being WT vs not sequnced.

**Comment by jjgao** [comment]
@ecerami we have a pull request we haven't been able to finish. We have the backend component and front component in oncoprint. Zack will try to connect the two pieces. We also need to change the statistics in the study view.

https://github.com/cBioPortal/cbioportal/pull/254

**Comment by jjgao** [comment]
duplicate with #426
