### ISSUE TITLE
On study page, progress indicator shows "rendering" while gene panel data is still loading

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8215]
Here we see that we're in render stage, but actually the gene panel endpoint is still pending.  
![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/c36a9b2c-6920-4d25-8b68-6f42d2edcb8a)

**Comment by onursumer** [comment]
@alisman Actually the developer console is misleading. It is not gene panel data but sample count data. Seems like more promises added later on into `StudyViewPageStore.loadingInitialDataForSummaryTab` but `SummaryTab.getProgressItems` was not updated.
