### ISSUE TITLE
Genes missing in overview table but shown in plots and data

### ISSUE THREAD

**Issue by NikdAK** [cBioPortal/cbioportal#8222]
Hi,
I noticed some genes were missing in the overview gene table. 
So I build a testing set with just a single gene to see what is happening.

For A1BG there are no entries in the table:
![p1](https://user-images.githubusercontent.com/39265538/98831785-49385b80-243c-11eb-9408-3ad4cf7f573f.png)

Anyways, if I try to download the data right there, I get the expected mutations:

```
Gene	MutSig(Q-value)	# Mut	#	Profiled Samples	Freq	Is Cancer Gene (source: OncoKB)
A1BG		3	3	42	7.1%	No
```

Additionally the plot for this gene are also correct:
![p2](https://user-images.githubusercontent.com/39265538/98831896-708f2880-243c-11eb-9612-02609678a201.png)

Any idea why the table is empty?

I am working on a local hg38 portal version 3.4.17 from docker-compose and the DB schema 2.12.6

Thank you very much!
Cheers

**Comment by jjgao** [comment]
@NikdAK it was b/c of the OncoKB filter.

![image](https://user-images.githubusercontent.com/840895/102650823-7c57c400-4139-11eb-8d10-65bfb5ce283d.png)

**Comment by jjgao** [comment]
@cBioPortal/product I am wondering if we should consider turning off the filter by default? We can also remember the setting in cookies.

**Comment by inodb** [comment]
Thoughts @tmazor @schultzn ?

Let's at least have one user setting in `localStorage` to remember whether people have the oncokb filter enabled or disabled on the study view page (this applies to the whole website)

**Comment by schultzn** [comment]
I like the idea of a user setting

**Comment by tmazor** [comment]
I agree, a user setting is a good idea

**Comment by schultzn** [comment]
Thinking about it some more, maybe the user setting is not necessary. We could just turn the filter off by default, and users who are aware of the filter can just turn it on manually as needed.

**Comment by inodb** [comment]
To summarize: we won't be saving this for users. For all our portals we want the default to be to not filtered by OncoKB
