### ISSUE TITLE
alteration filter in study view feedback

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8227]
1. Will there be a setting/option to hide this button? I suspect we're going to want to hide this in the public portal until there is data to enable using it. I think I would propose that the button should only appear for studies that have custom annotations. @jjgao @schultzn thoughts?

2. Gene tables are not loading for this study that doesn't have custom filters:
![image](https://user-images.githubusercontent.com/10508276/102822787-b5956b80-43a7-11eb-934e-12e73d43d779.png)

3. Proposed updates to text in the menu (although this may change depending on the answer to the questions below):

Select the types of alterations to count in the Mutated Genes, CNA Genes and Fusion Genes tables:

Germline/Somatic Status (mutations only)    [tooltip: Germline/somatic annotations are based on data provided during study upload]
- Germline
- Somatic
- Unknown

Driver Annotation    [tooltip: Driver/passenger annotations are based on Custom driver annotation data. ]
- Putative drivers
- Putative passengers
- Unknown

Categorical Annotation     [tooltip: Alteration categories are based on Custom driver annotation tier annotations. ]
- Class 1
- Class 2
- Class 3
- Class 4
- Unknown

4. In the menu above, can you explain which text will change depending on the custom annotations provided? I can't tell what's hard coded and what will change depending on the custom annotations for a particular study. 

5. If a study only has drivers or only has tier custom annotations, will those be the only options that appear in the menu? Will germline/somatic appear when a study doesn't have that annotation or only has somatic data?

6. Is it possible to provide a study with more annotated alterations? And also share that data? It's going to be really hard to test with the limited number of alterations in the test study, and I can't verify that anything is behaving correctly without knowing what the underlying data is.

**Comment by jjgao** [comment]
Re 1: good point. I don't think we should show it if a study has no custom driver data.

**Comment by jjgao** [comment]
7. Change the warning icon to filter icon (same one as the gene column?) and add it to the # column for all three tables
![image](https://user-images.githubusercontent.com/840895/102921065-c30b2e00-4459-11eb-82d8-1ca34eb390e5.png)
8. How can we know which Alteration filters were applied? For example, in [this link](https://bit.ly/34T0tfV), driver filter was applied, but I couldn't figure out based on the UI what was applied. Maybe we can add the filter icon in the in the row that the filter was applied which a hover-over to explain what was applied? We could also add the hover to the breadcrumbs as well.
9. In the link above, after turning on filter in the Gene column and then turning off, it take a moment to have the filtered rows (ABLIM1 and OR11H1) back.

**Comment by pvannierop** [comment]
@jjgao @tmazor 

@1 Yes there is an option to hide the menu from portal properties. In fact, it will only show when turned on in portal properties via `skin.show_settings_menu=true`. However, be aware that this menu also has filter options for ermline and somatic (so, mutation status), which is available for your studies. There is value for switching it on your portal even when there is no custom driver data loaded yet. The sections in the menu relating to driver filtering a hidden when the study (or studies) shows does not have custom driver annotations.

@2 This is a problem that needs to be fixed. I'll keep you posted.

@3 I will update the text as per your suggestion

@4 Sections Driver Annotation and Categorical Annotation will only show when the study has custom driver annotaions loaded (see @1)

@5 The driver and tier section will show when driver annotations and tier data has been loaded, respectively. I do not do a check ATM for germline/somatic data for the mutation status section. The mutation status section always shows (same as the `exclude germline` checkbox in results view settings menu.

@6 I will ask sjoerd. I can use the OncoKB import script on a public study, but I have to create one. Also here, I will notify you when I have such a study loaded.

**Comment by tmazor** [comment]
@pvannierop I realized this ticket has been sitting for a while and just wanted to check in to make sure I haven't missed anything. Has there been progress on the outstanding issues here? Is there a dataset with more custom annotations available for testing?

**Comment by pvannierop** [comment]
@tmazor No, I think all is ok. Thnx for reaching out!
