### ISSUE TITLE
Validator Issue : Handle Gene Symbols within cBioPortal

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#823]
Validator throws error for Gene Symbol alias when Entrez lD is present and being used for import. 
Proposal : Handle Validation of gene similar to the cbioportal importer. The importer loads the gene based on Entrez ID. If Entrez ID is not present, it tries to use the gene symbol and unambiguously tries to map it to single gene. Hence, validator should also validate based on Entrez ID and if Entrez ID is not present, then it should check for HUGO Symbol. A warning can be thrown if the gene symbol is not an official HUGO Symbol.

Example : Currently validator is throwing error for :
 Entrez_Gene_Id Hugo_Symbol
 4297 MLL

 Error : Gene symbol not known to the cBioPortal instance; found in
 file:[MLL]

 But, import for the above line just replaces MLL with official HUGO Symbol
 "KMT2A".

**Comment by pieterlukasse** [comment]
@priti88 : we actually plan to remove functionality in the loader step you mentioned (i.e. the ignoring of the given HUGO and the mapping to some other HUGO). We believe this is not the task of the loading script. The less we have of such “advanced logic”  and “autocorrections” the clearer the loading process becomes. We want to turn it into a no-brainer step :)  This means that all smart stuff should occur before this step. With this, I would like to propose to keep current validation.

**Comment by ecerami** [comment]
Consensus:  if a user specified an Entrez Gene ID and a HUGO Symbol, then validator will check that Entrez Gene ID matches either HUGO Symbol or Alias.  And, if no match is found, that would be reported as an error.

**Comment by pieterlukasse** [comment]
@priti88 : what @ecerami describes is already implemented in our branch. I made PR #827 so you can review and merge the code to test again.

**Comment by priti88** [comment]
@pieterlukasse :+1: works great.
I will close this issue.
Thanks
