### ISSUE TITLE
incorrect percentage in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8232]
In [this link](https://bit.ly/3rmLWCM), TP53 should be mutated in 100% of the samples, but the table says 99.5%. 

![image](https://user-images.githubusercontent.com/840895/102935696-a7615100-4474-11eb-8e43-c61adc424cf0.png)

**Comment by inodb** [comment]
Let's wait for fusion migrations to be done

**Comment by kalletlak** [comment]
This should be resolved now
