### ISSUE TITLE
results view header link doesn't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8238]
If I remember correctly, clicking the number of patients/samples in the header of results view (eg "507 patients/samples" in screenshot below) would open up study view filtered down to just those patients/samples. That no longer appears to be the case - clicking on that link just brings me to study view for all samples in the study.

Am I misremembering or is that feature broken?

![image](https://user-images.githubusercontent.com/10508276/103228444-db1dfa00-48fe-11eb-938a-9e2c95ee9c2f.png)

https://www.cbioportal.org/results/oncoprint?genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_pan_can_atlas_2018_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_pan_can_atlas_2018_gistic&cancer_study_list=lgg_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=lgg_tcga_pan_can_atlas_2018_cnaseq&gene_list=IDH1%2520EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit

**Comment by jjgao** [comment]
It seems that this has been fixed.
