### ISSUE TITLE
oncoprint now labels CNA as driver vs VUS

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8239]
The colors are the same, but the legend now distinguishes Amp/Del as driver vs VUS. Is this a new feature?

![image](https://user-images.githubusercontent.com/10508276/103230269-0276c600-4903-11eb-8b64-c23b61e29772.png)

**Comment by adamabeshouse** [comment]
@tmazor based on git history, it looks like changes made by @forus introduced this difference, maybe he can give insight

**Comment by jjgao** [comment]
@pvannierop I am wondering if you have any insights?

**Comment by jjgao** [comment]
@tmazor @cBioPortal/product maybe we should come up with VUS colors for VUS deletions and amplifications? Then we should do it for vus fusions too?

**Comment by pvannierop** [comment]
@tmazor @jjgao @adamabeshouse Yes, this was introduced with the passenger/driver for CNA feature. And I agree that it would make sense to provide different color coding of CNA driver and VUS.

**Comment by jjgao** [comment]
@adamabeshouse could you help find colors for vus amp, vus del, and vus fusions?

**Comment by adamabeshouse** [comment]
@jjgao it's tough... on top of the fact that we already have a ton of colors, the approach we usually take for vus, adding a light tint, would leave vus amp very close to gain, and vus del close to hetloss...

**Comment by jjgao** [comment]
@adamabeshouse good point. @tmazor @schultzn @cBioPortal/product any thoughts? Here are the current colors for CNAs:

![image](https://user-images.githubusercontent.com/840895/108536681-b57ff200-72aa-11eb-9abd-505816b38336.png)

**Comment by schultzn** [comment]
Hmm. Can we implement it in a way that users can either show Driver vs VUS OR distinguish between different levels of CNA, but not both?

**Comment by jjgao** [comment]
@schultzn not sure how that'd work from the UI... 

Alternatively, we could come up with a shade between AMP and Gain for AMP VUS? And a lighter one for Gain VUS? Similarly for deletions...

**Comment by schultzn** [comment]
We can try that...

Here is a thought about UI for my proposed model: Showing low level amps and shallow losses is rare and requires the use of OQL. When the use of either of those two OQL commands is detected, we can disable color-coding copy-number events by oncogenicity and instead show a warning that indicates that this feature is not available when using hetloss and gains? We don't have OncoKB annotations for these events anyway.

**Comment by Sjoerd-van-Hagen** [comment]
How about using a color that is not a lighter tint but a color that is generally perceived as a friendlier/softer version or the red and blue for the VUS. Something like orange/pink for amp/gain and cyan/mint for (deep) deletions?

**Comment by schultzn** [comment]
That might work. But many colors are already taken, since the different mutation types, as well as rearrangements, need to be visible on top of the copy-number call.

**Comment by tmazor** [comment]
ooo this is a tough one. To @schultzn 's suggestion, I would worry about having the same color mean different things in different contexts - it seems likely to cause confusion. If it's possible to come up with a third shade between Amp/Gain and DeepDel/ShallowDel, I think that would be my vote. Do we need to worry about Driver vs VUS for Gain/ShallowDel or can we just keep all Gain/ShallowDel the same color?

**Comment by schultzn** [comment]
Good point. At this point, we don’t have driver annotations for gain and het loss, so maybe we don’t need an additional color for those.

Agreed that the there might be some confusion if we have the same color mean different things.

**Comment by inodb** [comment]
Let's only show one glyph for AMP+DEL (no driver distinction)
