### ISSUE TITLE
Validator Issue : Handle Amino acid Change for mutation data

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#824]
Error is thrown for null Amino Acid column. This should be optional as the mutation can be a Splice Site.
Maybe throw a warning for null columns.

**Comment by pieterlukasse** [comment]
@priti88 : @onursumer checked the code and the column seems to be required. See also #806

Also, the column will be called HGVSp_Short, according to this same #806 . 

Some possible solutions: 
- make an exception when column 'Variant_Classification' = 'Splice_Site' 
- require the value to be 'NA' when amino acid change is 'not applicable' or cannot be inferred
- maybe combine both points above?

Are there any other 'Variant_Classification' values (or other cases) that need a similar as exception?

**Comment by pieterlukasse** [comment]
a solution for  'Splice_Site' is implemented in #806  (see https://github.com/cBioPortal/cbioportal/issues/806#issuecomment-185780600)

The `HGVSp_Short` detailed validation is taken up in #1249 

Therefore, closing this ticket.
