### ISSUE TITLE
Annotation column sort should take disabled annotations into account

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#8247]
When some of the annotations (for example OncoKB) programmatically disabled, sorting for annotation column is still performed as if all annotations are enabled. We should exclude disabled annotations when generating a sort value.

**Comment by jjgao** [comment]
@inodb maybe this can be addressed as part of the annotation redesigning effort? https://github.com/cBioPortal/cbioportal/issues/8345
