### ISSUE TITLE
Validate mutation and cnv data independent of clinical file

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#825]
Currently, validator stops if there is error in clinical file.

**Comment by pieterlukasse** [comment]
@priti88 : still an issue?

**Comment by pieterlukasse** [comment]
@fedde-s could you close this one if it is solved? I believe it is.

**Comment by fedde-s** [comment]
I believe the underlying problem that led to this request was solved by 626495d8b652a0caf569dd9ad40679520607fe0e, which has been merged into the release candidate. Molecular data is still skipped if there is no parseable sample data file at all, but the process can now gracefully deal with incorrect attribute definition headers in these clinical data files and continue to parse them. @priti88, is this still an issue or can it be closed?

**Comment by pieterlukasse** [comment]
some scenarios will still stop the validation, like inconsistent number of columns over multiple line in the sample clinical file. But the number of scenarios is less now. It is also reduced with the split between patient and sample files (i.e. the patient file can be messed up and it will still validate other files).

Scenarios where the validation will still stop:
- logger.error('No valid study file detected')
- logger.error('No sample attribute file detected')
- logger.error("Sample file could not be parsed. .. (basically the column problems I listed above)

Closing the issue assuming this is acceptable. @priti88 feel free to reopen if you want to discuss more.
