### ISSUE TITLE
Change from vcf2maf to genome nexus annotator

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8267]
Since we have switched to genome nexus annotator, should we switch to GN in [our documentation](https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#creating-an-extended-maf-file-with-vcf-2-maf-or-maf-2-maf) and [here](https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#data-file-5) for local installations?

@sheridancbio I am wondering if we already have documentation since GENIE has already switched?

EDIT: There are multiple parts to this question:

- [x] recommend to use genome nexus to annotate MAF (let's use Java client)
- [ ] for annotating VCFs we can recommend
- [ ] replace all references to vcf2maf

**Comment by inodb** [comment]
@jjgao I think for the second item, conversion from vcf to maf, we might still want to recommend to use vcf2maf? Or we can try to generalize the GENIE vcf2maf conversion tool more: https://github.com/genome-nexus/annotation-tools (CC @ao508 )
