### ISSUE TITLE
update colors for drivers vs VUS in plots

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8281]
This color scheme is confusing, because it uses the colors for amp/del to mean driver vs VUS:

![image](https://user-images.githubusercontent.com/10508276/104768189-3b080380-573b-11eb-9de2-6db81a3b20dd.png)
https://bit.ly/3ihDvnR

Could we use dark green/light green instead? That would be more consistent with OncoPrint colors.

**Comment by adamabeshouse** [comment]
good point @tmazor . any ideas on what colors we should use instead?

**Comment by adamabeshouse** [comment]
good idea, I'll do that
