### ISSUE TITLE
Using only TCGA PanCancer Atlas by default for Pahtways tab in Results and Patient views

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8286]
Can we add an option to use the set of pathways from the TCGA PanCancer Atlas by default? Maybe allow user to switch to all TCGA pathways as another option?

![image](https://user-images.githubusercontent.com/840895/105088455-e7165b00-5a69-11eb-999a-e97021baf939.png)

**Comment by ugurdogrusoz** [comment]
@jjgao How about like this (checked by default):
<img width="449" alt="Screen Shot 2021-01-20 at 09 15 39" src="https://user-images.githubusercontent.com/3874988/105135134-9271ef00-5b00-11eb-9e8d-7c6340e7ec31.png">

**Comment by jjgao** [comment]
@ugurdogrusoz good idea!

**Comment by inodb** [comment]
@schultzn @tmazor Could you take a look? We plan to merge this by Monday - thanks!

**Comment by tmazor** [comment]
Looks good! But I have a data question that I came across while testing. I'm not super knowledgeable about the HIPPO pathway, but I thought YAP & TAZ were major components of it, and that's not what's appearing here: 

![image](https://user-images.githubusercontent.com/10508276/107088047-5d38f280-67ca-11eb-9337-eccd38d05fc8.png)

@schultzn you know this better than I do - thoughts?

**Comment by schultzn** [comment]
Good catch @tmazor, this is the wrong pathway... probably a curation issue on the Pathway Mapper side? The pathway should look like the one below.
![image](https://user-images.githubusercontent.com/11892704/107103574-25db3d80-67ec-11eb-8c61-5fdb96de669c.png)

**Comment by ugurdogrusoz** [comment]
@tmazor thanks for noticing this. @schultzn these were curated by Konnor La at the time. @msalihaltun tried to draw it [here](http://www.pathwaymapper.org/?id=c42ea59f-e13c-4c21-beb6-bdc78bc53c48). Please check and correct if needed. When you give it a go, we'll update the pathway.
