### ISSUE TITLE
genie comparison tab slowness

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8287]
After 10+ min of loading, this is as far as the page has loaded:
![image](https://user-images.githubusercontent.com/10508276/105095095-3d3bcc00-5a73-11eb-8daf-5fb850ed1bf0.png)

https://genie-private.cbioportal.org/results/comparison?cancer_study_list=genie_private&tab_index=tab_visualize&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=genie_private_mutations&case_set_id=genie_private_all&Action=Submit&gene_list=BRAF%253A%2520MUT%253DV600%253B

There are no pending requests in the network tab, so I'm not sure what's happening.

@Luke-Sikina verified that he sees similar behavior, so I don't think this is related to my internet slowness issues

**Comment by jjgao** [comment]
I think the comparison of so many samples is challenging. Not sure if we can find a good solution. Maybe we should limit the size of total samples?
