### ISSUE TITLE
Oncoprinter tool currently does not support splice

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8290]
The new splice support in oncoprinter does not seem to be in the oncoprinter tool yet:

<img width="910" alt="Screen Shot 2021-01-20 at 8 38 45 AM" src="https://user-images.githubusercontent.com/1334004/105182355-ef6aa680-5afa-11eb-843d-50a7645d99b0.png">

seeing this after trying to open https://bit.ly/3peI2dL in the oncoprinter (download>open in oncoprinter)

**Comment by adamabeshouse** [comment]
ah good catch. yeah that was an oversight
