### ISSUE TITLE
Custom data does not show in oncoprint for virtual cohort in mskcc portal

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8291]
When creating a virtual cohort (e.g. astrocytoma in lgg_ucsf_2014 https://cbioportal.mskcc.org/study/summary?id=6008341fe4b015b63e9d5e14) and adding custom data. In the private portal the custom charts don't show up in oncoprint:

<img width="591" alt="Screen Shot 2021-01-20 at 8 51 22 AM" src="https://user-images.githubusercontent.com/1334004/105183876-b4697280-5afc-11eb-8beb-59703b194d7c.png">

But in the public portal they do:

<img width="1138" alt="Screen Shot 2021-01-20 at 8 53 57 AM" src="https://user-images.githubusercontent.com/1334004/105184179-0e6a3800-5afd-11eb-9be6-4c87bdf260ae.png">

It seems that in the mskcc portal somehow showing custom data from virtual cohorts in the oncoprint does not work. It does work to add custom data to non virtual cohorts and show it in the oncoprint

**Comment by alisman** [comment]
@inodb to clarify: the custom data shows up on study page, but NOT in oncoprint, right?

**Comment by alisman** [comment]
@adamabeshouse @kalletlak looks to me like the problem is that on oncoprint, for a virtual study, we fetch custom data using physical study ids rather than virtual study id.  This is a familiar problem from study view.  
https://cbioportal.mskcc.org/study/summary?id=6008341fe4b015b63e9d5e14

**Comment by kalletlak** [comment]
@alisman I can take a look at it
