### ISSUE TITLE
user can access small set of studies when authority is "app-name:"

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#8299]
We observed that when a user in the authorities table was given an authority of the form "app-name:" (with an empty string for the cancer_study_identifier), it is possible for the user to access a small set of cancer studies (but not all, and not the public study set)

We are not clear on why this is or what set is retrieved, but there seems to be a bug in the cancer_study_permission_evaluator code, or the @prefilter logic.

In this test case, the cgds_gdac database is the source of data for the su2c.cbioportal.org website. When a user has no authorities, they see no studies in the website, and when they have authority "su2c-portal:all" they see over a thousand studies. But when they are given authority "su2c-portal:" they see 66 cancer studies. We also noticed that there are 71 studies in the database where the cancer_study record has an empty string in the field "groups" and there are 5 studies in that set which have status set to 1.

**Comment by jjgao** [comment]
@sheridancbio will this be added to the pipelines scrum board?
