### ISSUE TITLE
Cleanup option breaks development builds

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#830]
The changes in cd7557aff1c66f95723a21497295e73d234129ed to clean-up the artifacts breaks development environments where the artifacts should stay:

```xml
	<profiles>
		<profile>
			<id>heroku</id>
			<build>
				<plugins>
					<!-- remove core temp build files -->
					<plugin>
						<artifactId>maven-clean-plugin</artifactId>
						<version>2.5</version>
						<executions>
							<execution>
								<id>clean-artifacts</id>
								<phase>install</phase>
								<goals><goal>clean</goal></goals>
								<configuration>
									<excludeDefaultDirectories>true</excludeDefaultDirectories>
									<filesets>
										<fileset>
											<directory>target</directory>
										</fileset>
									</filesets>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
```

It would be nice to add a `skip` flag inside `<configuration>` tag to allow skipping this step. Something like: 

```xml
...
<configuration>
     <!--skip cleanup if -DskipCleanup -->
     <skip>${skipCleanup}</skip>
....
</configuration>
...
```
We need this in `core/pom.xml` and in `portal/pom.xml`

**Comment by pieterlukasse** [comment]
@inodb : do you think the proposed solution above will work? Or do you maybe have a better idea for this?

**Comment by inodb** [comment]
Which files are deleted exactly? The idea of that change was to only delete the files if you run with the heroku profile i.e. `mvn -Pheroku`. By default the used profile is public (https://github.com/cBioPortal/cbioportal/blob/master/pom.xml#L73). If somehow the artifacts are still deleted I think we should change the code so it works as I originally intended.

**Comment by pieterlukasse** [comment]
@inodb it is cleaning up the `portal/target/portal`  folder. Apparently our mvn command is not looking at the profile id in the XML...not sure why. We just run `mvn -DskipTests clean install` . The workaround with `skipCleanUp` should work I think.

**Comment by inodb** [comment]
Ok, yeah I see there's no profile specified in `portal/pom.xml`, just fixed that, will sent PR shortly. I remember now that I didn't make that specific to the heroku profile because I could't think of a use case when you would actually need the extracted war. Whichever tomcat you use will extract it afaik. Could you elaborate?

I don't think adding an extra `skipCleanUp` parameter is necessary unless there's a use case other than heroku for wanting to get rid of the built files.

**Comment by pieterlukasse** [comment]
hi @inodb , thanks for the help. We use the extracted war to simplify frontend development. So we edit js, jsp and html files in our IDE and a synchronization script sends them automatically to the extracted war location. Then all we need to get our new code is refresh the browser (instead of building a new .war). But I will be glad to learn from you if there is an easier and better way to do this.

**Comment by inodb** [comment]
I see, thanks for the explanation. That's a good argument for not removing the extracted war. Let's merge the PR.

For frontend development I usually edit the extracted war files directly, but that does create the possibility of accidentally overwriting the edits when recompiling so sounds like your method is more secure.

**Comment by inodb** [comment]
It's in hotfix now
