### ISSUE TITLE
Add tooltip for the annotation column in the mutations table

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#8305]
1. With more resources added into the annotation column, it will be great if we could add some descriptions explaining each resource.
- [x] [OncoKB](https://www.oncokb.org): a precision oncology knowledge base and contains information about the effects and treatment implications of variants in cancer ([Chakravarty et al. 2017.](https://pubmed.ncbi.nlm.nih.gov/28890946/)).
- [x] [CiVIC](https://civicdb.org/): a community knowledgebase for expert crowdsourcing the clinical interpretation of variants in cancer ([Griffith et al 2017](https://pubmed.ncbi.nlm.nih.gov/28138153/))
- [x] [MyCancerGenome](https://www.mycancergenome.org): a precision cancer medicine knowledge resource (data version Mar 2016)
- [x] [CancerHotspots](https://www.cancerhotspots.org): statistically significant recurrent mutational hotspots in cancer ([Chang et al. 2018](https://pubmed.ncbi.nlm.nih.gov/29247016/)).
- [x] [3DHotspots](https://www.3dhotspots.org/): statistically significant recurrent 3D clustered hotspots in cancer ([Gao et al. 2017](https://pubmed.ncbi.nlm.nih.gov/28115009/)).
2. Align sources icon with their data (wait for oncokb to render and add white space between oncokb and civic if there are multiple oncokb icons)
3. Add tooltip for all annotation columns in 
- [x] results view page
- [x] patients view page
    - [x] Mutation table
    - [x] Structural Variants table
    - [x] Copy Number Alterations table
- [x] mutation mapper tool

**Comment by jjgao** [comment]
@zhx828 I updated the description above.

@cBioPortal/product I am wondering if it's time to remove MyCancerGenome?

**Comment by leexgh** [comment]
Eventually we will only have one OncoKB icon, but now we still have multiple, should we leave white space between OncoKB and CiVIC now?
![image](https://user-images.githubusercontent.com/16869603/122274975-2a59e600-ceb1-11eb-99bd-28f054dca312.png)

**Comment by leexgh** [comment]
![image](https://user-images.githubusercontent.com/16869603/122455847-dadfec80-cf7a-11eb-8a81-aca78072031b.png)

**Comment by jjgao** [comment]
@leexgh we should make a decision whether we would like to keep the individual columns. If so, maybe we could add an icon for the columns too, e.g. for sensitivity tx.

![image](https://user-images.githubusercontent.com/840895/122586229-6795b380-d02a-11eb-9615-74886df64cc0.png)

**Comment by Luke-Sikina** [comment]
Approved, ready to merge, do not merge until after webdriver merges.
