### ISSUE TITLE
cbioportal install using docker and authenticating using ldap

### ISSUE THREAD

**Issue by Kevin-cruk** [cBioPortal/cbioportal#8306]
Hi
I am a Linux system admin trying to install cbioportal using docker. I managed to achieve this and it produces the webpage but now need to authenticate against ldap. I have followed the instructions on the web page https://docs.cbioportal.org/2.2-authorization-and-authentication/authenticating-users-via-ldap
to modify the portal.properties file. But I am unsure of the next step running this java command to install the war file. I do not have portal/target/dependancy or portal/target folders

java \
    -Dauthenticate=ldap \
    -jar \
    portal/target/dependency/webapp-runner.jar \
    portal/target/cbioportal.war

I installed the docker image into my home folder, and its contents are : config  data  docker-compose.yml  init_hg38.sh  init.sh  README.md  study

Any help would be grateful

Thanks
Kevin

**Comment by inodb** [comment]
@Kevin-cruk you can change the webapp-runner command here: https://github.com/cBioPortal/cbioportal-docker-compose/blob/512fa3afde23d0645b4dabe6ce6c60984e87b22d/docker-compose.yml#L20. Hope that helps! Free feel to re-open if it doesn't
