### ISSUE TITLE
Opening html validator report in Chrome fails with security error

### ISSUE THREAD

**Issue by jochemb** [cBioPortal/cbioportal#831]
The error message:
Uncaught SecurityError: Failed to execute jquery.mobile-1.4.4.js:2932  'replaceState' on 'History': A history state object with URL '/validation_rapport.html' cannot be created in a document with origin 'null'.

Opening it in Safari works fine.

**Comment by pieterlukasse** [comment]
@priti88 : can you please check this? I think it is some bug in the libraries you used for the report styling.

**Comment by priti88** [comment]
@pieterlukasse I saw this issue too while trying to open the html in Chrome. I will take a look why this is happening.

**Comment by fedde-s** [comment]
Implemented a fix in thehyve/cBioPortal@5e864a1d579e8aea75b73d33ce3cd2e43f228b58.
