### ISSUE TITLE
Change casing on timeline

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8310]
Can we change to using: "Lowercase And Uppercase" for the axis labels in the timeline?

<img width="163" alt="Screen Shot 2021-01-28 at 1 00 04 PM" src="https://user-images.githubusercontent.com/1334004/106179255-c4bac680-6168-11eb-8997-689bd1ed0d56.png">

Request from Niki

EDIT: let's use the data as given by the curators as is

**Comment by alisman** [comment]
I believe the data is inconstistent, so we decided to just use UC.   I'm sure we could easily switch to initial caps. @schultzn?

**Comment by inodb** [comment]
Maybe we can use the data as is and fix the data?
