### ISSUE TITLE
Implementation plan for Color chooser for user-defined groups in Study View (RFC 55)

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#8316]
## Telco dd 28-01-2021
Attendees: @jjgao @alisman @kalletlak @Sjoerd-van-Hagen @pvannierop 

## Topic
Agree on a way to allow user-defined colors for comparison groups without modifying the group data persisted with session service.

@kalletlak 
Group colors are already passed from study view to group comparison. This is done when starting a comparison session from any chart. Group colors as show in respective chart are included in the session POST request.

@alisman 
I think it would be best when there is a global way to update/force group colors in comparison view.

@jjgao 
I disagree because this will become very complicated (many overrides created for many studies) and confusing (users losing track of factors determining the observed color).

@pvannierop
Colors selected by the user for custom groups can be persisted in the user session of study view.

@Sjoerd-van-Hagen 
A consequence of packaging the colors in the comparison request is that the colors of a particular session cannot be updated via the menu after the comparison was created. Is this not confusing to a user?

@pvannierop @jjgao 
No, we do not think so. Normally the route towards the comparison is always via study view so the user is aware of the colors at that time. When entering the session via a url to the session we do not expect the user to associate this perse with the ability to choose colors.

@jjgao 
In the future we might think about adding the color chooser functionality to the group comparison view.

## Conclusion
1. Custom user colors can be selected in study view. Custom colors are persisted in the user session of study view.
2. When defined, user-defined colors are passed as request parameter in the way already implemented for chart-derivedd group colors.

**Comment by Sjoerd-van-Hagen** [comment]
Discussion was done. Feature has been merged.
