### ISSUE TITLE
Decide whether we should always label at least one lollipop in mutation diagram

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#8319]
Looks like it might be confusing when we don't label any of the lollipops. See the related thread here: https://groups.google.com/g/cbioportal/c/ZorcBL7YPcA/m/sT5yNbtyAAAJ

Should we always label at least one lollipop for consistency?

Choose exactly one mutation. It should:
- Have the highest mutation count
- If there is a tie, pick the one that is in a domain
- If there is a tie, pick the one closest to the center of the diagram.

**Comment by jjgao** [comment]
ok to always label one by default. This could be done as part of https://github.com/cBioPortal/cbioportal/issues/5220.

**Comment by Luke-Sikina** [comment]
- If there is a domain, pick the first mutation in the domain
- Else pick the middle most mutation by position
