### ISSUE TITLE
Patient pathways view altered gene borders incorrect

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#8326]
In pathways view of the Patient view, we highlight altered genes with *thick* borders. Looks like this is lost once you change the default pathway from the table view.

https://user-images.githubusercontent.com/3874988/106716696-ccb6b280-660f-11eb-922b-01267f612119.mp4

**Comment by ugurdogrusoz** [comment]
Looks fixed to me. @onursumer please check as well.

**Comment by onursumer** [comment]
Looks good to me, too. Thanks @ugurdogrusoz @msalihaltun!
