### ISSUE TITLE
Add separate category for splice mutations in the mutations tab

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8335]
Now that splice mutations are a separate category in the oncoprint we should also make them a separate on in the mutations tab:

Here there is a different color for splice in the oncoprint:
https://www.cbioportal.org/results/oncoprint?cancer_study_list=lusc_tcga_pan_can_atlas_2018%2Cnsclc_mskcc_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=all&gene_list=MET&geneset_list=%20&tab_index=tab_visualize&Action=Submit

<img width="914" alt="Screen Shot 2021-02-05 at 10 13 47 AM" src="https://user-images.githubusercontent.com/1334004/107051789-dddffa80-679a-11eb-861f-72e2969807d9.png">

But on the mutations tab we are still categorizing them as truncating (even though splice mutations could be either inframe or truncating):

<img width="1408" alt="Screen Shot 2021-02-05 at 10 12 27 AM" src="https://user-images.githubusercontent.com/1334004/107051627-ad985c00-679a-11eb-9636-9189400b0b03.png">

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/cbioportal/issues/8334. Let's take the oppotunity to add driver vs vus colors too.
