### ISSUE TITLE
Redesign annotation column

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8345]
There are many sources now, we should come up with a new design

- [x] create mockup
- [ ] implement header changes on annotation column

**Comment by leexgh** [comment]
mockup: https://docs.google.com/presentation/d/1WNfDmI8cC8cMZ4t8JsFEB2mqR7GmGp2tOY9W0mzAuv4/edit#slide=id.gd261ae0ce9_1_5

**Comment by inodb** [comment]
duplicate
