### ISSUE TITLE
modification to postLoadForMskCIS()

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#8353]
Can [window.postLoadForMskCIS()](https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/appBootstrapper.jsx#L97) be updated so that yellow "WARNING" bar is hidden?  This is not required in CIS environment as URL is not displayed to user.

![cis](https://user-images.githubusercontent.com/366003/107816960-751cf300-6d43-11eb-82c8-f1915361a171.png)

**Comment by inodb** [comment]
@n1zea144 i think this should be fixed now, could you help confirm?
