### ISSUE TITLE
Review updated pathways tutorial

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#8354]
I updated the tutorial for the option "Show TCGA PanCancer Atlas Pathways Only". Please review (see highlighted parts in slides 5 & 8).

**Comment by tmazor** [comment]
@ugurdogrusoz I modified the text a bit to include a link to the pancan atlas pathways publication. let me know if it looks ok to you and i can update the live version of the slides.

**Comment by ugurdogrusoz** [comment]
@tmazor thanks. I removed the highlights, it's good to go. Please close after making it live.
