### ISSUE TITLE
Mobx research projects

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8368]
1. I'm curious if we can monkey with mobx promise to log out (or send event to loggly) when result property is referenced before isLoaded = true.    I just want to know if that is something that happens a lot or not that muc

2. I would also like to be able to detect unnecessary render cycles.  I think there are tool out there for doing that.  See what you can find.

**Comment by adamabeshouse** [comment]
is it time to move mobxpromise into our project as a lerna package?
