### ISSUE TITLE
Gene panel endpoint returns blank response under some condition

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8370]
There is some data issue which is causing this to return blank response body.  It should return either [] or an error. 

I have asked the data team to look into data issue but we should also handle this properly in code.

[curl.txt](https://github.com/cBioPortal/cbioportal/files/6031547/curl.txt)

**Comment by alisman** [comment]
@onursumer could you look into why this returns empty?  @ritikakundra says that gene panel data has not changed recently

**Comment by inodb** [comment]
@alisman looks like latest backend with latest frontend fixes it: https://cbioportal.mskcc.org/beta/study/summary?id=msk_spectrum

use 

```
localStorage.netlify = 'master--cbioportalfrontend'
```

**Comment by inodb** [comment]
@alisman it also works with an older version of the frontend that we currently have in production: https://frontend.cbioportal.org. So one option is to only upgrade the backend

**Comment by alisman** [comment]
hmmm
