### ISSUE TITLE
Don't show bar charts for survival attributes only KM plot

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8373]
E.g. here: https://www.cbioportal.org/study/summary?id=msk_impact_2017

Don't show:
![Screen Shot 2021-02-24 at 4 58 53 PM](https://user-images.githubusercontent.com/1334004/109071358-9f669d00-76c1-11eb-9de5-ad90f088c60a.png)

Only:
![Screen Shot 2021-02-24 at 4 58 43 PM](https://user-images.githubusercontent.com/1334004/109071361-9f669d00-76c1-11eb-960b-d4cd5fc8fe77.png)

**Comment by dippindots** [comment]
@inodb should I also hide the `status` pie chart?
