### ISSUE TITLE
Cancer Studies Chart

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8376]
The cancer studies chart is not particularly useful when looking at a single study. We are currently hiding it, but might be better to remove completely.

![Screen Shot 2021-02-25 at 9 31 01 AM](https://user-images.githubusercontent.com/1334004/109167848-3415dd00-774c-11eb-95c4-e39f8c24c37d.png)

If it's complicated to remove then at the very least we could update the tooltip to have a description. Maybe:

```
The cancer study id for each sample in the cohort
```

**Comment by Luke-Sikina** [comment]
Stand up discussion: we are not sure why this needs to be removed. This seems like it is still useful when we have multiple studies. @inodb

**Comment by dippindots** [comment]
@inodb Oh, I see, do you mean for a single study query, we should remove this chart, but keep it in multiple studies query, right?

**Comment by jjgao** [comment]
Good idea to update the tooltip, but maybe let's keep the chart as long as it's hidden for a single study (for code simplicity)?

**Comment by inodb** [comment]
Sounds good - let's only update the tooltip
