### ISSUE TITLE
Adjustments to custom "Survival" KM plots

### ISSUE THREAD

**Issue by alexbaras** [cBioPortal/cbioportal#8378]
The title to the KM plot should just have "(months)" not "Survival (months)" as we are not always looking at survival in these time to event analyses. Similarly on mouse over, it should be something like "fraction / proportion event free" and "time of event"

![image](https://user-images.githubusercontent.com/8574243/109177950-57de2080-7756-11eb-9373-09fe9bcb44ac.png)

**Comment by jjgao** [comment]
Thanks, @alexbaras. Good points.

@dippindots could you help with this? We should use the same header and tooltip as what we use in Comparision page.

**Comment by dippindots** [comment]
@jjgao Sure!

**Comment by alexbaras** [comment]
Thanks for looking into this. But I am not sure that what you have in the comparison km plots is exactly righth either.

The two last rows are simply showing the "x & y" here of a KM plot which generally speaking
x=time interval (censored or not)
y=fraction of the given cohort / subgroup that is event free up to that time point x

I am not sure as to the exact text but I think that is what it should convey

![image](https://user-images.githubusercontent.com/8574243/109352347-b1267c80-7848-11eb-9943-06e804a84798.png)

**Comment by jjgao** [comment]
Thanks, @alexbaras. You are right. The text in the comparison page can also be improved. 

@dippindots let's change "Time of Death" to "Time of event"

@alexbaras For Y-axis, our current text is not perfect but fraction and estimate are slightly different terminologies. I am wondering if you have any suggestions of an accurate term to use? 

![image](https://user-images.githubusercontent.com/840895/109353907-019ed980-784b-11eb-886f-1e762097ef6b.png)

**Comment by alexbaras** [comment]
To me

x-axis: really just a time interval, i.e. 5 months

y-axis: Probability event free, i.e. 70%

I think in KM analysis the y-axis is the KM estimate of the probability of being event free through interval t

I defer to a real biostats person though, as I just play one on TV ;-)

https://en.wikipedia.org/wiki/Kaplan-Meier_estimator
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3059453/

**Comment by jjgao** [comment]
@dippindots let's do the following for the tooltip for both study view and comparison.

- change "Time of Death" to "Time of event" for all survival types
- change "xxx estimate" to "% event free"

**Comment by MatthijsPon** [comment]
Hey @jjgao and @dippindots, I found that the current custom KM plots still have `survival (months)` in the title. Was this done deliberately? I was unable to find further discussion on the title

**Comment by dippindots** [comment]
@MatthijsPon Could you check the public portal, this issue should be fixed now.
