### ISSUE TITLE
Comparison Survival Fixes

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8380]
- [x] Dropdown box broken
![Screen Shot 2021-02-25 at 11 31 39 AM](https://user-images.githubusercontent.com/1334004/109184563-1f8e1080-775d-11eb-81ef-b798c359dc9e.png)
https://genie-private.cbioportal.org/comparison/survival?sessionId=6037d03de4b0242bd5d3f1c7

- [x] It should not be possible for users to unselect Survival Type in that dropdown

- [x] Median survival needs units (e.g. months)

**Comment by dippindots** [comment]
Separate Confidence Interval into a new issue: https://github.com/cBioPortal/cbioportal/issues/8427
