### ISSUE TITLE
Redesign slider for patients > 10 on survival comparison Tab

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8381]
On https://genie-private.cbioportal.org/comparison/survival?sessionId=6037d03de4b0242bd5d3f1c7

- [x] Remove 'Patients >10' from   searchbox and explore adding a slider so that the user can specify a minimum sample size
- [x] Require at least 10 patients per group in order to display the log rank test. The KM curves will be shown regardless of sample size

**Comment by jjgao** [comment]
Maybe we should consider column-based filter? This could be useful for other columns too. https://github.com/cBioPortal/cbioportal/issues/7918

**Comment by adamabeshouse** [comment]
@jjgao what do you mean?
