### ISSUE TITLE
alterations tab results inconsistency

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8383]
sample-level enrichments looked ok, but when i switched to patient-level, the results got very different:
results for the first gene (KRT12) look the same except for q-value.
all other genes seem to have totally different results

https://www.cbioportal.org/results/comparison?cancer_study_list=lgg_ucsf_2014&tab_index=tab_visualize&case_set_id=lgg_ucsf_2014_all&Action=Submit&gene_list=SMARCA4&comparison_subtab=mutations&patient_enrichments=true
![image](https://user-images.githubusercontent.com/10508276/109221346-77417180-7787-11eb-95b3-180a07e2bfbf.png)

https://master.cbioportal.org/results/comparison?cancer_study_list=lgg_ucsf_2014&tab_index=tab_visualize&case_set_id=lgg_ucsf_2014_all&Action=Submit&gene_list=SMARCA4&comparison_subtab=alterations&patient_enrichments=true
![image](https://user-images.githubusercontent.com/10508276/109221543-81fc0680-7787-11eb-8586-74bbdfb72bc4.png)

**Comment by kalletlak** [comment]
@tmazor it looks like a bug in production. Results on master portal seems right to me.

**Comment by alisman** [comment]
@alisman we need to confirm this

**Comment by jjgao** [comment]
Agreed with @kalletlak. The production seems incorrect - there are only 22 patients in the unaltered group. Somehow the production site uses the number of samples for unaltered group (but correctly uses the number of patients for altered group)...

![image](https://user-images.githubusercontent.com/840895/109341462-761c4d00-7838-11eb-92a9-f9eec6b9ab26.png)

@kalletlak the pattern diagram is incorrect in `master` though - there shouldn't be any NA cases...

**Comment by tmazor** [comment]
Sorry for the potentially silly question but I want to confirm something --  I understand that production isn't correct, but when comparing prod to master, the first gene (KRT12) has the same p-value but different q-value, and I'm confused by that. Given that the analysis is only mutations, the tables have the same number of genes, and the p-value is the same, I thought that would make the q-value the same? Or am I missing something about how the q-value gets calculated?

**Comment by kalletlak** [comment]
q-values are based on Benjamini–Hochberg procedure. All genes p-values are considered for calculating p-values. since some of the genes p-values have changes I would expect q-values to be different.

**Comment by tmazor** [comment]
ok thanks!
