### ISSUE TITLE
alterations table name should be consistent with tab name

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8387]
This study doesn't have CNA data which is reflected in the tab name and the list of alteration types but the table name still includes 'CNAs'

![image](https://user-images.githubusercontent.com/10508276/109224600-2e3eec80-778a-11eb-8583-28284e96898d.png)

https://master.cbioportal.org/results/comparison?cancer_study_list=lgg_ucsf_2014&tab_index=tab_visualize&case_set_id=lgg_ucsf_2014_all&Action=Submit&gene_list=SMARCA4&comparison_subtab=alterations&patient_enrichments=true

**Comment by alisman** [comment]
We have changed this to the generic "Genomic Alterations"
