### ISSUE TITLE
Genomic Alteration Comparison performance issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8398]
For [this query](https://master.cbioportal.org/comparison/alterations?sessionId=6038203d577c3071fd22c788), when both mutations and cnas are selected, it's slow. When only one type is selected, it's fast.

**Comment by kalletlak** [comment]
Observed difference in performance/response time for combined and split query based on molecular alteration type(mutation and cna)
https://gist.github.com/kalletlak/f10119b63d685c31bb838b059b5ef3b0

**Comment by pvannierop** [comment]
Yes, the cause for the slow down appears to be the creation of a temporary table that hods the UNION. SO, how about creating two SQL statements that returns a list of sample/patient ids for mutations and CNA to the java layer. The Java layer will derive counts from the occurrence of unique ids in the two lists. This approach will scale nicely with the new struct var implementation.
