### ISSUE TITLE
genomic alterations gene panel patient-level counts are wrong

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8399]
ACVR1 is only profiled for a subset of samples/patients. But the patient-level counts shows all patients in the comparison:

![image](https://user-images.githubusercontent.com/10508276/109529960-3184f180-7a84-11eb-8d13-041e621617db.png)

Sample-level counts look correct:
![image](https://user-images.githubusercontent.com/10508276/109530197-76108d00-7a84-11eb-8ca7-70aac5f3e835.png)

https://master.cbioportal.org/comparison/alterations?sessionId=6038203d577c3071fd22c788&patientEnrichments=false

**Comment by kalletlak** [comment]
Fixed in https://github.com/cBioPortal/cbioportal/pull/8372
