### ISSUE TITLE
Genomic Alterations Comparison: patient-level CNA issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8400]
https://master.cbioportal.org/comparison/alterations?sessionId=5cf89323e4b0ab413787436c

![image](https://user-images.githubusercontent.com/840895/109530167-701aac00-7a84-11eb-8192-481815622566.png)

**Comment by kalletlak** [comment]
Fixed in https://github.com/cBioPortal/cbioportal/pull/8372
