### ISSUE TITLE
genomic alterations discrepancy

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8404]
This gene appears in master but not in prod. It also doesn't have a cytoband which may or may not relate?

prod:
![image](https://user-images.githubusercontent.com/10508276/109553294-dc0b0d80-7aa0-11eb-8860-8bbbf09cbf99.png)
https://www.cbioportal.org/results/comparison?cancer_study_list=gbm_tcga_pan_can_atlas_2018%2Clgg_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=all&gene_list=IDH1%2520TP53%2520EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit&comparison_subtab=cna

master
![image](https://user-images.githubusercontent.com/10508276/109553363-ef1ddd80-7aa0-11eb-95c1-954db4e3ea19.png)
https://master.cbioportal.org/results/comparison?cancer_study_list=lgg_tcga_pan_can_atlas_2018%2Cgbm_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=all&gene_list=IDH1%2520TP53%2520EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit&comparison_subtab=alterations

**Comment by kalletlak** [comment]
Fixed in https://github.com/cBioPortal/cbioportal/pull/8372
