### ISSUE TITLE
how to deal with samples that are not profiled in comparison tab

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8411]
In the query below, there are some samples that are not profiled for mutation or copy number:
![image](https://user-images.githubusercontent.com/10508276/109745307-a9950980-7ba1-11eb-8b8a-f5861b7f70bb.png)

On the comparison tab, the sum of samples in the altered+unaltered groups is 521+613=1134, so all samples in the query are assigned to a group.
![image](https://user-images.githubusercontent.com/10508276/109745355-bdd90680-7ba1-11eb-8d31-26ad615c2079.png)

From this, I presume that the samples that are not profiled are being counted as unaltered. Is that the correct behavior? I think  those samples should probably be in a third group ('not profiled')

@cBioPortal/product thoughts?

https://www.cbioportal.org/results/oncoprint?cancer_study_list=lgg_tcga%2Cgbm_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=all&gene_list=EGFR%2520TP53&geneset_list=%20&tab_index=tab_visualize&Action=Submit&show_samples=true

**Comment by tmazor** [comment]
This is also an issue for gene panels -- see this query for a gene which is only on one of the two gene panels:
https://www.cbioportal.org/results/comparison?genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&cancer_study_list=msk_impact_2017&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=msk_impact_2017_cnaseq&gene_list=ACVR1&geneset_list=%20&tab_index=tab_visualize&Action=Submit

**Comment by jjgao** [comment]
I think it makes sense to separate the `not profiled` cases into a group and maybe by default, they should not be selected for comparison? 

They should also be excluded from the unaltered group in Download tab. Any other tabs?

![image](https://user-images.githubusercontent.com/840895/116310398-f519fd00-a777-11eb-98e1-47c6f8fb2b09.png)

**Comment by jjgao** [comment]
@adamabeshouse maybe you can help with this? It's not a priority.

**Comment by adamabeshouse** [comment]
would unprofiled samples be those unprofiled in *any* gene & profile, or unprofiled in *every* gene & profile? @tmazor @jjgao

**Comment by jjgao** [comment]
@adamabeshouse it would be those unprofiled in every gene & profile.

**Comment by tmazor** [comment]
Group comparison updates look good @adamabeshouse ! But it looks like the unaltered samples list in download tab isn't updated? We should probably also update sample matrix on download tab - maybe -1 for not profiled?

**Comment by adamabeshouse** [comment]
@tmazor  I was going to do that in a future PR - is it alright to split those changes up?

**Comment by tmazor** [comment]
sorry i totally missed this comment - yes ok to split @adamabeshouse !

**Comment by Sjoerd-van-Hagen** [comment]
> @adamabeshouse it would be those unprofiled in every gene & profile.

@jjgao are you sure about this? The idea of not including unprofiled samples in unaltered is because you may inadvertently be including altered samples. This could still happen if you would define unprofiled as unprofiled in every gene and profile, as opposed to any gene or profile.

**Comment by tmazor** [comment]
@Sjoerd-van-Hagen @jjgao : @adamabeshouse & I have been discussing this in the PR https://github.com/cBioPortal/cbioportal-frontend/pull/3760

We're proposing to actually allow users to select how to define unprofiled (any gene/profile vs all genes/profiles)
