### ISSUE TITLE
group counts are wrong when samples aren't profiled

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8412]
In the query below, not all samples are profiled for mutations. In the comparison tab, it looks like the sample count per group is correctly not including unprofiled samples when there is one or more altered samples, but when there are 0 altered samples, the group size is the full group, including the unprofiled samples.

Note the 'unaltered' count in the tooltip for IDH1 vs STAG2 and that there are no unprofiled samples in the unaltered group in the co-occurrence figure:

![image](https://user-images.githubusercontent.com/10508276/109746524-84a19600-7ba3-11eb-96bd-842bd3f7bb9d.png)

![image](https://user-images.githubusercontent.com/10508276/109746542-8c613a80-7ba3-11eb-96db-0d0d20f0c9a9.png)

This also happens for the altered group:
![image](https://user-images.githubusercontent.com/10508276/109746782-f4178580-7ba3-11eb-8f93-e2ab0b23bfa5.png)

And also for copy number:
![image](https://user-images.githubusercontent.com/10508276/109746947-45277980-7ba4-11eb-9d69-a991cd7f27a4.png)
![image](https://user-images.githubusercontent.com/10508276/109746963-4b1d5a80-7ba4-11eb-8eb0-d1d96e641592.png)

https://master.cbioportal.org/results/comparison?cancer_study_list=gbm_tcga%2Clgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=all&gene_list=EGFR%2520TP53%250AMTAP&geneset_list=%20&tab_index=tab_visualize&Action=Submit&comparison_subtab=alterations

Actually this appears to be an existing bug on production - see same query here:
https://www.cbioportal.org/results/comparison?cancer_study_list=lgg_tcga%2Cgbm_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=all&gene_list=EGFR%2520TP53%250AMTAP&geneset_list=%20&tab_index=tab_visualize&Action=Submit&show_samples=true&comparison_subtab=mutations

**Comment by kalletlak** [comment]
Fixed in #8372
