### ISSUE TITLE
multiple reference genomes: human and mouse

### ISSUE THREAD

**Issue by NikdAK** [cBioPortal/cbioportal#8428]
Hi,
I would like to have a mouse and also a human cbioportal running on my server.

I already found this tutorial regarding multiple genomes, but apparently it is not recommended to have both human and mouse in the same instance: https://github.com/cBioPortal/cbioportal/blob/master/docs/Support-multiple-reference-genomes.md
Is this still up-to-date? 

If yes, the only solution would probably be two independent docker images/containers. 
What should I take into account when doing this? 
I can imagine that renaming the images/containers and changing the port in the docker-compose.yml could cause problems somewhere down the line.

Thank you very much for the help!

**Comment by jjgao** [comment]
@NikdAK Sorry for the late response. We recommend not to have both human and mouse in the same instance - in fact, the site won't work if you do that. Regarding running multiple instances with docker, if you haven't figure it out and need support, please contact cbioportal@googlegroups.com. Thanks.
