### ISSUE TITLE
OncokB seems slow...

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8429]
It took 1.4 minutes to annotate TP53 mutations in msk_impact_2017: https://bit.ly/3bsp5Qf

![image](https://user-images.githubusercontent.com/840895/110372870-cf486580-801c-11eb-9e36-1abeef7873c3.png)

**Comment by zhx828** [comment]
The main issue is the tumor type summary generation. No much of the improvement I can do for a quick fix. Need to spend more time investigating.

**Comment by zhx828** [comment]
@jjgao I was able to shorten the request to 20s from 60s. But I think 20s is the best I can do at the moment for this request.

**Comment by jjgao** [comment]
Thanks, Hongxin. That's a great improvement.

**Comment by zhx828** [comment]
@jjgao we deployed the caching feature. The initial call to this query takes about 20s. But the second hit only takes about 4s. I think we can close this ticket?
