### ISSUE TITLE
Invalid symbols in resources/cbio_cancer_genes.txt

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#843]
The following entries are giving errors (at least since last update of NCBI hugo/entrez mapping):

```
0.  C12ORF9 93669 in the cbio cancer gene list config file [resources/cbio_cancer_genes.txt] is not a HUGO gene symbol. You should either update this file or update the `gene` and `gene_alias` tables to fix this.; 1x
1.  CDKN2AP14ARF in the cbio cancer gene list config file [resources/cbio_cancer_genes.txt] is not a HUGO gene symbol. You should either update this file or update the `gene` and `gene_alias` tables to fix this.; 1x
2.  CDKN2AP16INK4A in the cbio cancer gene list config file [resources/cbio_cancer_genes.txt] is not a HUGO gene symbol. You should either update this file or update the `gene` and `gene_alias` tables to fix this.; 1x
3.  EGFRVIII in the cbio cancer gene list config file [resources/cbio_cancer_genes.txt] is not a HUGO gene symbol. You should either update this file or update the `gene` and `gene_alias` tables to fix this.; 1x
```

@jjgao, @schultzn  Can we remove them from this configuration file?

**Comment by jjgao** [comment]
@pieterlukasse please remove C12ORF9 but not the other three. They are being used in our clinical lab. We should probably make this file configurable, ie, every instance can have it's own cancer genes.

**Comment by pieterlukasse** [comment]
Hi @jjgao  : can we add the other three as an *alias* to a valid gene? E.g. EGFRVIII could be an alias to EGFR, and EGFRVIII be seen a type of mutation (maybe we should add support for a new alteration type to account for these cases?). Or is this actually what your are doing already (i.e. adding EGFRVIII as an alias to EGFR)? For now I am assuming you are adding EGFRVIII to you `gene` table, but please correct me if I'm wrong.

**Comment by jjgao** [comment]
@pieterlukasse: unfortunately we cannot add them as aliases. They are conceptually different genes. It's a hacky way to support the special isoforms.

**Comment by pieterlukasse** [comment]
@jjgao  now that I look closely I see indeed that CDKN2AP14ARF and CDKN2AP16INK4A are "normal"(?) transcript isoforms of the gene CDKN2A. Regarding your comment: do you mean that these two extra codes are a workaround for showing isoform specific expression data? Maybe at some point we need to introduce a table `transcript` that works for transcript data in a similar way the table `gene` works for genes?
