### ISSUE TITLE
Study Page GENIE public loads too slow user experience

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8430]
Take an easy use case on https://genie.cbioportal.org/study/summary?id=genie_public:

- show most frequently mutated genes in lung adeno

It takes 30-40 seconds to load the page to a point where one can select the cancer type. Then selecting "Lung Adeno" responds pretty fast, but then the user again has to wait a couple of seconds before the mutated genes table shows up. In total it takes around 50 seconds to get an answer to that question. It probably takes longer for someone new to the website that might wait for the full page to load before selecting a cancer type of interest

Can we get this down?

Apart from optimizing the current endpoints and frontend, here are some other ideas:

- it seems like we always load everything for cancer type, mutated genes etc. I wonder if it would be faster to e.g. list only top 20 and fire another request that pulls in the rest
- In a similar vein: for larger cohorts I wonder if we should minimize what we display on first load. Especially in cohorts with mixed cancer types, you usually want to navigate to your cancer type of interest as quickly as possible

**Comment by jagnathan** [comment]
Discussed a few options with Ino and Aaron and listed them in this google sheet.
https://docs.google.com/spreadsheets/d/1kAPHRJBFr-lhRxmeTwzoevbU2noJBEyJfAmxrVQrrBs/edit?usp=sharing

**Comment by jjgao** [comment]
The site seems very fast now. Anything to follow up in the list above? @inodb
