### ISSUE TITLE
Create indexes in the cbioportal DB to improve performance

### ISSUE THREAD

**Issue by jagnathan** [cBioPortal/cbioportal#8435]
Analyze the tables and columns that need indexing based on DB usage and queries

Already exists
gene_panel table STABLE_ID column
sample_list table STABLE_ID column
genetic_profile table STABLE_ID column

Track performance statistics before and after adding indexes for different sizes of data

- [ ] sample table STABLE_ID column
- [ ] patient table STABLE_ID column
- [ ] genetic_entity table STABLE_ID column

**Comment by jagnathan** [comment]
CREATE INDEX idx_stable_id_sample ON sample (`STABLE_ID`);
CREATE INDEX idx_stable_id_patient ON patient (`STABLE_ID`);
CREATE INDEX idx_stable_id_genetic_entity ON genetic_entity (`STABLE_ID`);

**Comment by jagnathan** [comment]
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/37613906/112571069-a4e8fd00-8dbd-11eb-8c33-df5797c769a5.png">

**Comment by jagnathan** [comment]
Average time for the gene-panel fetch API query is about 4.5 minutes. This is about 2 minutes without new indexes and 6 minutes with the new indexes.

**Comment by jagnathan** [comment]
Query which is time consuming:
SELECT `gene_panel` . `STABLE_ID` AS `genePanelId` , `sample` . `STABLE_ID` AS `sampleId` , `patient` . `STABLE_ID` AS `patientId` , `cancer_study` . `CANCER_STUDY_IDENTIFIER` AS `studyId` , `genetic_profile` . `STABLE_ID` AS `molecularProfileId` FROM `sample_profile` LEFT JOIN `gene_panel` ON `sample_profile` . `PANEL_ID` = `gene_panel` . `INTERNAL_ID` INNER JOIN `genetic_profile` ON `sample_profile` . `GENETIC_PROFILE_ID` = `genetic_profile` . `GENETIC_PROFILE_ID` INNER JOIN `sample` ON `sample_profile` . `SAMPLE_ID` = `sample` . `INTERNAL_ID` INNER JOIN `patient` ON `sample` . `PATIENT_ID` = `patient` . `INTERNAL_ID` INNER JOIN `cancer_study` ON `patient` . `CANCER_STUDY_ID` = `cancer_study` . `CANCER_STUDY_ID` WHERE ( `sample` . `STABLE_ID` , `genetic_profile` . `STABLE_ID` ) IN ( (...) /* , ... */ )

**Comment by jagnathan** [comment]
Discussing with Rob about the specification of the test VM vs production VM of the Database mysql server.

**Comment by jagnathan** [comment]
From @sheridancbio : The public portal rds database node is DB instance class db.m5.4xlarge 16 vCPU, 64GB RAM
The genie portal rds database node is DB instance class db.m5.2xlarge, 8vCPU, 32GB RAM
The performance-test ec2 instance running mysql is instance class t3.2xlarge, 8vCPU, 32GB RAM (t3 class is "burstable" with a credit system for granting allocating vCPU above the base limit for short periods of time

**Comment by jagnathan** [comment]
T3 = 2.5 GHz Intel Scalable Processor ( xeon); M5 = Up to 3.1 GHz Intel Xeon Platinum Processor

**Comment by inodb** [comment]
Let's figure out a better way to have people access the database and do performance analysis. We prolly need some environment that anyone can access (we could use the performance environment for this)

**Comment by jagnathan** [comment]
<img width="1090" alt="Query Plan without Index" src="https://user-images.githubusercontent.com/37613906/113172119-20133e80-9216-11eb-9edf-56e612da8bfd.png">
<img width="1097" alt="Query Plan with Index" src="https://user-images.githubusercontent.com/37613906/113172123-21446b80-9216-11eb-9734-b747f92f5748.png">

**Comment by jagnathan** [comment]
Query cost decreases with new indexes.

**Comment by jagnathan** [comment]
Query explanation chart  after new indexes
<img width="1097" alt="Query Plan with Index" src="https://user-images.githubusercontent.com/37613906/113172123-21446b80-9216-11eb-9734-b747f92f5748.png">

**Comment by jagnathan** [comment]
New query with two pairs in where clause

SELECT 
    `gene_panel`.`STABLE_ID` AS `genePanelId`,
    `sample`.`STABLE_ID` AS `sampleId`,
    `patient`.`STABLE_ID` AS `patientId`,
    `cancer_study`.`CANCER_STUDY_IDENTIFIER` AS `studyId`,
    `genetic_profile`.`STABLE_ID` AS `molecularProfileId`
FROM
    `sample_profile`
        LEFT JOIN
    `gene_panel` ON `sample_profile`.`PANEL_ID` = `gene_panel`.`INTERNAL_ID`
        INNER JOIN
    `genetic_profile` ON `sample_profile`.`GENETIC_PROFILE_ID` = `genetic_profile`.`GENETIC_PROFILE_ID`
        INNER JOIN
    `sample` ON `sample_profile`.`SAMPLE_ID` = `sample`.`INTERNAL_ID`
        INNER JOIN
    `patient` ON `sample`.`PATIENT_ID` = `patient`.`INTERNAL_ID`
        INNER JOIN
    `cancer_study` ON `patient`.`CANCER_STUDY_ID` = `cancer_study`.`CANCER_STUDY_ID`
WHERE
    (`sample`.`STABLE_ID` , `genetic_profile`.`STABLE_ID`) IN (('GENIE-DFCI-000424-11147' , 'genie_erbb2_cna'),('GENIE-GRCC-02010027-m1','genie_erbb2_mutations'))

**Comment by jagnathan** [comment]
Query execution plan without indexes for 2 pairs in where clause

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/37613906/113336315-398ab800-92f4-11eb-80e5-fb3eb13f559e.png">

**Comment by jagnathan** [comment]
Query execution plan with indexes for 2 pairs in where clause

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/37613906/113336551-95edd780-92f4-11eb-8f91-e292a9af1e21.png">

**Comment by jagnathan** [comment]
Query execution plan without indexes for 1000 pairs in where clause

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/37613906/113339186-1d891580-92f8-11eb-9af7-b1af964ed53d.png">

**Comment by jagnathan** [comment]
Query execution plan with indexes for 1000 pairs in where clause

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/37613906/113339464-7bb5f880-92f8-11eb-849c-61d805ab5e1c.png">

**Comment by jagnathan** [comment]
However time taken for query with indexes is 0.7 seconds and without indexes is 0.2 seconds. The result is opposite of cost calculations.

**Comment by jagnathan** [comment]
Indexes for  sample table STABLE_ID column
  patient table STABLE_ID column are working fine.

Index for gene_panel table STABLE_ID column is not improving performance.
