### ISSUE TITLE
KM plot: add confidence interval area

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#8442]
Draw Confidence Interval area on the plot
![image](https://user-images.githubusercontent.com/15748980/110160167-a83e2980-7db9-11eb-8718-6d629d44733b.png)

**Comment by jjgao** [comment]
Just remembered that we had another one ticket on this: https://github.com/cBioPortal/icebox/issues/90

**Comment by dippindots** [comment]
Should we close this one and use that one?

**Comment by jjgao** [comment]
duplicate
