### ISSUE TITLE
Exclude certain attributes from the clinical comparison page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8445]
For GENIE we want to exclude certain clinical attributes from the comparison page (https://genie-private.cbioportal.org/comparison/clinical?sessionId=5f85e2c2e4b0242bd5d253d0&unselectedGroups=%5B%5D) e.g.:

- [x] `Age (years) at last known alive date` (`AGE_LAST_FU_YEARS`) Cannot be compared outside of survival analysis
- [x] `DOB to last known alive date (months)` Cannot be compared outside of survival analysis
- [x] `Year of birth` (`BIRTH_YEAR`)

For some we might not want to show a p value:

- [ ] Comparison of `Sequence Assay ID`

I believe we use the priority attribute for the study page to indicate what's hidden. Maybe we can use that for the attribute page? Alternatively we can add another meta attribute for the clinical attributes that indicates whether we want to allow comparisons on them, since we might need to adjust the schema for https://github.com/cBioPortal/cbioportal/issues/8377 as well

**Comment by jjgao** [comment]
Not sure how to handle this. I don't think we should keep hardcoding in either code or configuration. Maye we need to curate this data, e.g. in clinical data file?

Also, do you think it's a priority? @inodb

**Comment by inodb** [comment]
I don't think the priority is super high. Let's just hard code for now as you proposed and if we keep getting the same request we can do a more sustainable implementation
