### ISSUE TITLE
Sonarcloud runs fail on the main branch

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8446]
Sonarcloud fails consistently on the `master` branch: https://github.com/cBioPortal/cbioportal/runs/2077904094

It works fine for PRs. Any clue? 

We could maybe disable sonarcould for non PRs

**Comment by inodb** [comment]
Looks like we expect sonarcloud to fail, b/c there are many issues with our code quality. On PRs it succeeds if it's not making things worse. Do note that in the linked github action run there is simply some error with jitpack.

**Comment by inodb** [comment]
actually now that the jitpack error is not showing up I do still see a configuration error:

```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project master: Please add the secret GITHUB_TOKEN as an environment variable to your GitHub Actions workflow. See sonarsource/sonarcloud-github-action for more details. -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1
```

**Comment by jjgao** [comment]
@inodb @sheridancbio @averyniceday  do we need to reopen this?
