### ISSUE TITLE
Mapping of tissue images from TCGA samples to DSA is no longer working

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8447]
Fixed: https://www.cbioportal.org/patient/tissueImage?caseId=TCGA-05-4382&studyId=luad_tcga_pan_can_atlas_2018

Still wrong: https://www.cbioportal.org/patient/tissueImage?studyId=brca_tcga_pan_can_atlas_2018&caseId=TCGA-E9-A5FL

It currently shows some slide image but not the one for this specific case. Can we:

- [ ] Figure out what API endpoint we were using before to determine what sample maps to the slide id
- [ ] Recommend a plan for how David Gutman could fix the API

**Comment by jjgao** [comment]
@alisman could you help with this?

**Comment by alisman** [comment]
@inodb @jjgao i sent an email to Gutman.   All we do is a call an api with patientid and if there is a response, we show iframe with following url:

https://cancer.digitalslidearchive.org/index.html?patientId=TCGA-05-4382

So, there isn't really any mapping going on.  Something seems to have changed on their end with their handling of that parameter.

**Comment by alisman** [comment]
David Gutman says he is fixing this on their end.

**Comment by jjgao** [comment]
This one still has wrong patient mapped: https://www.cbioportal.org/patient/tissueImage?studyId=brca_tcga_pan_can_atlas_2018&caseId=TCGA-E9-A5FL

**Comment by jjgao** [comment]
@alisman Let's find a solution on our end?
