### ISSUE TITLE
Garbled x button in study view -> custom bin

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8458]
![image](https://user-images.githubusercontent.com/840895/112191976-ea9a9f80-8bdc-11eb-91ea-09896b8a9339.png)

**Comment by alisman** [comment]
@inodb i think this is our old friend Jitpack mutilating some unicode.  perhaps it's time to move on from jitpack, i think we concluded before there was not way to fix this.   not hugely urgent but lets discuss what it would take.

**Comment by inodb** [comment]
maybe we can replace with X character as a quick solution
