### ISSUE TITLE
(Generic Assay) Support patient level and normal sample data

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#8459]
Based on the discussion: https://github.com/cBioPortal/cbioportal/issues/8450#issuecomment-804297016

We want to accomplish this by duplicating data to tumor sample level. (e.g. If we have data for `patient_1`, and `patient_1` has two samples (`sample_1` and `sample_2`), we need to find out that those two samples are related and duplicate data for both `sample_1` and `sample_2`).

- [x] Update validator
- [x] Change database scheme to introduce a new bool field `PATIENT_LEVEL` (e.g. PATIENT_LEVEL: `1` / `0`) into genetic_profile
- [x] Update importer to allow new type of data to be imported (if data is patient level or normal sample, adding data for all related tumor samples)
- [x] (Backend) Comparison endpoints: for patient data, return patients level calculation, not samples level calculation
- [x] (Frontend) Study view: select and filter by selected patients
- [x] Update `File-Formats.md`

**Comment by jjgao** [comment]
@dippindots about `DATATYPE`, I have a second thought. I think the information of PATIENT or SAMPLE is different from the current `DATATYPE` and it's probably better to handle them in a different field. What's the reason you would like to merge them? Is it for avoid database migration?

**Comment by dippindots** [comment]
@jjgao I think it's ok to have a new field to store information of PATIENT or SAMPLE. My only concern is we would need to set a default value `SAMPLE` for all default profiles, I am not sure if that makes sense. If we can add `SAMPLE` for all previous profiles, I think have a new field is a better idea.

**Comment by dippindots** [comment]
If we all agreed to use a new field, do you like to use `RECORD_TYPE` as the new field's name to store `PATIENT` or `SAMPLE` in `genetic_profile` table?

**Comment by jjgao** [comment]
@dippindots agreed - it should be default to `SAMPLE`. Since this field is missing in all current meta data, maybe we make this field option in the meta data file? In the database, it can default to `SAMPLE` (https://www.w3schools.com/sql/sql_default.asp). 

I couldn't think of a good field name... @n1zea144 @inodb @kalletlak any idea?

**Comment by Luke-Sikina** [comment]
Suggestion: `SOURCE` or if it's a boolean value just `PATIENT_LEVEL`
