### ISSUE TITLE
Allow overriding (or ignoring) of clinical attribute properties

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#846]
When using importer from #798 we get errors when attributes already exist in the database with different properties (display name, description, priority, type,...). That is useful to know. It would be handy to have a mechanism (comand line option?) to handle the situation when there is an attribute with the same id but different properties in the database.
There could be an option with values: 

A) Force overwrite of the properties of the attribute in the database
B) Ignore the new properties and just use the existing attribute with its properties
C) (default) throw an error

**Comment by fedde-s** [comment]
As the attribute was loaded as part of a previous study, and that study was loaded assuming that the attribute has a certain meaning, overwriting it sounds like a very bad idea unless you remove all previously loaded studies that use the attribute. Ignoring the new definitions may be feasible, but it would be confusing (especially to new users) and encourage incorrect data. I would strongly prefer just  making it possible to leave the definition out if you do not want to define it.

**Comment by fedde-s** [comment]
However, the idea to implement a way to somehow find out which studies use the current definition of an attribute (without having to manually consult the DBMS) sounds like it might be useful. Another option would be study-specific clinical attributes intended to never be harmonised, for instance by prefixing them with the study id, but I imagine that will eventually only lead to regret.

**Comment by fedde-s** [comment]
Right, this issue has been made irrelevant by pull request #1746 making clinical attributes study-specific altogether; harmonising attributes between studies is no longer required.
