### ISSUE TITLE
study view sv table tweaks

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8472]
The SV table name should include the number of profiled samples, like Mutations & CNA tables do.

Also the name of the second column (# Alt) isn't intuitive to me -- I assume it stands for # Alterations? On prod it is called # Fusions. Maybe it can be '# SV' instead? @jjgao any thoughts?

beta
![image](https://user-images.githubusercontent.com/10508276/113036663-948ca580-9162-11eb-9633-a80781ed16ab.png)

prod
![image](https://user-images.githubusercontent.com/10508276/113036768-aa9a6600-9162-11eb-9441-ace7afd249bd.png)

**Comment by kalletlak** [comment]
Renamed it to `# SV`
Fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/3358

**Comment by tmazor** [comment]
Looks good! But the alignment of the column header vs data is a bit off - could "# SV" appear over the data?

![image](https://user-images.githubusercontent.com/10508276/113613017-99e46700-961e-11eb-8f34-14c1719ce93f.png)

**Comment by kalletlak** [comment]
@tmazor thanks for testing it out. It should be fixed now.

**Comment by tmazor** [comment]
looks good - thanks @kalletlak !
