### ISSUE TITLE
cancer types summary for un-profiled gene

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8474]
existing issue on prod, but found while testing the structural variant updates -- in this query, EML4 is altered in most samples as the partner to ALK, but is not a profiled gene (see oncoprint) -- cancer types summary graph doesn't deal well with a gene that is not profiled in any queried samples

https://bit.ly/39vQS0O

![image](https://user-images.githubusercontent.com/10508276/113047554-737e8180-916f-11eb-922b-5a3dda312091.png)

**Comment by jjgao** [comment]
Maybe we should show data not available message here? @tmazor
