### ISSUE TITLE
plots: don't use all caps for structural variant data

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8478]
Can all axis labels & legend say 'Fusion' and 'Intragenic' rather than all caps?

![image](https://user-images.githubusercontent.com/10508276/113053810-b5f78c80-9176-11eb-8c34-f8615d9f84d7.png)

https://beta.cbioportal.org/results/plots?exclude_germline_mutations=false&hide_unprofiled_samples=false&comparison_subtab=alterations&comparison_overlapStrategy=Include&comparison_selectedGroups=%5B%22ALK%22%2C%22EML4%22%5D&plots_horz_selection=%7B%22dataType%22%3A%22STRUCTURAL_VARIANT%22%7D&plots_vert_selection=%7B%22selectedGeneOption%22%3A6098%2C%22dataType%22%3A%22STRUCTURAL_VARIANT%22%7D&plots_coloring_selection=%7B%7D&mutations_gene=ALK&mutations_transcript_id=ENST00000431873&tab_index=tab_visualize&Action=Submit&session_id=6063863ce4b0242bd5d45b20

**Comment by kalletlak** [comment]
This data is directly coming from database. I think data needs to be fixed
cc: @jjgao

**Comment by inodb** [comment]
@tmazor we might leave this as is for now, because it's complex to fix the data and kind of a hack to do it in the frontend. We can follow up once we fully migrate the fusion data. Does that work?

**Comment by kalletlak** [comment]
@inodb looks like this is coming from the `VariantType` enum https://github.com/cBioPortal/cbioportal/pull/7597/files#diff-dd0543c032ab4520a7c62ed8fbfde84f94c593297edfd950924d1f0c4d2ac63e
I'll update it send camelcase

**Comment by inodb** [comment]
@kalletlak ah ok - even better - thank!

**Comment by kalletlak** [comment]
Fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/3358
