### ISSUE TITLE
comparison tab resets alteration types when changing groups

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8479]
Go to comparison tab. De-select Mutations in Alteration Types. Then select/deselect a group and watch Mutations get re-selected.

I thought this was fixed during testing of Genomic Alterations, but perhaps it slipped through.

Changing from sample-level to patient-level enrichments also resets the Alteration Types selections.

**Comment by alisman** [comment]
fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/3666/ which should be merged shortly

**Comment by tmazor** [comment]
awesome thanks for the update @alisman
