### ISSUE TITLE
Data Loading Script : Standardize exit code and error handling 

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#848]
The cbioportalImporter.py should be able to catch any errors in the java classes that it triggers to import data. Currently these different classes in the `core/org.mskcc.cbio.portal.scripts` package do not have a standard way of working. Some will report an error in stderr others will give a stack trace. Stderr is also not a reliable source as a lot of success messages are also printed there.

So it is important to standardize the way the individual java Import* classes behave and agree on the exit codes returned in case of error or success.

**Comment by pieterlukasse** [comment]
A test version is now available at https://github.com/thehyve/cbioportal/tree/fix_848.
Following classes still need to be reviewed and/or refactored:
- IMPORT_STUDY_CLASS = "org.mskcc.cbio.portal.scripts.ImportCancerStudy"
- REMOVE_STUDY_CLASS = "org.mskcc.cbio.portal.scripts.RemoveCancerStudy"
- IMPORT_CANCER_TYPE_CLASS = "org.mskcc.cbio.portal.scripts.ImportTypesOfCancers"
- IMPORT_CASE_LIST_CLASS = "org.mskcc.cbio.portal.scripts.ImportSampleList"
- ADD_CASE_LIST_CLASS = "org.mskcc.cbio.portal.scripts.AddCaseList"
- VERSION_UTIL_CLASS = "org.mskcc.cbio.portal.util.VersionUtil"

**Comment by pieterlukasse** [comment]
Items above now also refactored. Solution is ready for testing and merging on top of #1020

**Comment by sambrightman** [comment]
Could this be extended to the `metaImport.py` and `validateData.py`? It looks like a small number of `sys.exit(exitcode)` statements could be added to allow more easily checking import status programmatically. For example, one in `validateData.py` when running standalone and two in `metaImport.py` when there are errors or warnings with no override. I can submit a PR if you like.

**Comment by pieterlukasse** [comment]
Hi @sambrightman , I believe this has been done already in `metaImport.py` for the scenario you mentioned. But maybe you can make a PR indeed to show the specific part of the code you mean.

**Comment by sambrightman** [comment]
Sure, #1629 shows what I mean. Submitted against `rc`, which I think is what is expected (even though I'm actually having the problem in Docker, and would like to see it merged and rebuilt with such a change). Currently I get validation errors, shown on the console and in the HTML report, but exit code 0. My import scripts detects a successful import due to the 0 exit code.
