### ISSUE TITLE
group comparison genomic alteration tab bug

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#8484]
[User](https://groups.google.com/u/1/g/cbioportal/c/EqC1x7t65Ps) reported.

- [x] For [this comparison session](https://www.cbioportal.org/comparison/alterations?sessionId=6063db85e4b015b63e9e3734&overlapStrategy=Include), the orange group does not show. After deselecting CNA, the orange group shows up.

- [ ] it was chosen to include overlapping samples/patients, but there is still a warning message about excluding samples. Apply for each tab.

![image](https://user-images.githubusercontent.com/840895/113453406-e5570500-93d3-11eb-874a-79161ec90706.png)

after deselection CNAs:
![image](https://user-images.githubusercontent.com/840895/113453675-7cbc5800-93d4-11eb-947d-d3ff6aca3f27.png)

**Comment by priti88** [comment]
user also reported that if they de-select CNV and SV the bar reappears.

**Comment by jjgao** [comment]
@pvannierop or @kalletlak could you help look into this (maybe next sprint)? I worry this reflects a bigger underlying issue on how we merge data.

cc'ing @alisman

**Comment by inodb** [comment]
@priti88 could you review if this looks ok?

**Comment by priti88** [comment]
> @priti88 could you review if this looks ok?

@inodb Looks good to me.  Thank you

**Comment by kalletlak** [comment]
Fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/3709
