### ISSUE TITLE
Group comparison: Download button is not working for GENIE portals

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#8485]
The download button for the genomic alterations table is not working for GENIE portal (https://genie.cbioportal.org/comparison/alterations?sessionId=60664081e4b0242bd5d46323)

**Comment by alisman** [comment]
@dippindots  ![image](https://user-images.githubusercontent.com/186521/120526428-31f49780-c3a7-11eb-9970-9cf7df5b413a.png)
