### ISSUE TITLE
oncoprint tooltip missing oncokb for SV

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8487]
OncoPrint tooltip on beta:
![image](https://user-images.githubusercontent.com/10508276/113621743-ff8a2080-9629-11eb-9b7c-4eca891ba9e3.png)

Same patient on prod:
![image](https://user-images.githubusercontent.com/10508276/113621777-0e70d300-962a-11eb-8a4a-f5507f344354.png)

But mutations tab on beta does correctly annotate with OncoKB:
![image](https://user-images.githubusercontent.com/10508276/113621813-1af52b80-962a-11eb-8848-d38dc0a79744.png)

https://beta.cbioportal.org/results/oncoprint?cancer_study_list=lgg_ucsf_2014%2Clgg_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Cgistic&case_set_id=all&gene_list=EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit&show_samples=true

**Comment by zhx828** [comment]
In the beta instance, we use entrez gene id rather hugo symbol when annotating with oncokb. But the default gene symbol of the gene `SEPT14` is `SEPTIN14`, so OncoKB cannot return proper annotation. I will fix on OncoKB end.

**Comment by tmazor** [comment]
Thanks @zhx828  -- but I'm realizing now that we are inconsistent within the Mutations page also:
![image](https://user-images.githubusercontent.com/10508276/113719021-352b1a00-96bb-11eb-8999-7effa4c4f855.png)

The protein change column uses 'SEPT14' but the gene name up top is 'SEPTIN14'. And is that perhaps related to why there is no transcript found?

https://beta.cbioportal.org/results/mutations?cancer_study_list=gbm_tcga_pan_can_atlas_2018&tab_index=tab_visualize&case_set_id=gbm_tcga_pan_can_atlas_2018_all&Action=Submit&gene_list=SEPTIN14&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Cgistic&geneset_list=%20

**Comment by tmazor** [comment]
@jjgao any thoughts on this? I'm not sure where the gene names in various parts of the Mutations tab get pulled from, but is there a reason for the inconsistency in SEPT14 vs SEPTIN14 ?

**Comment by kalletlak** [comment]
@tmazor tooltip issue should be fixed now

**Comment by tmazor** [comment]
thanks @kalletlak - the tooltip looks good now

**Comment by inodb** [comment]
@tmazor these inconsistencies will be fixed once we migrate the fusion data from the mutation table to the new SV format

**Comment by inodb** [comment]
going to close this for now
