### ISSUE TITLE
sv testing - plots not profiled color is changed?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8488]
Not profiled for CNA is darker on prod. On beta, it looks the same as diploid.

Legend on beta:
![image](https://user-images.githubusercontent.com/10508276/113721955-f64a9380-96bd-11eb-998d-72139e3ca469.png)
https://beta.cbioportal.org/results/plots?cancer_study_list=luad_tcga%2Cluad_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Cgistic&case_set_id=all&gene_list=ALK%2520ROS1%2520RET%2520EGFR%2520EZR%2520EML4&geneset_list=%20&tab_index=tab_visualize&Action=Submit&plots_horz_selection=%7B%22dataType%22%3A%22MUTATION_EXTENDED%22%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D

Legend on prod:
![image](https://user-images.githubusercontent.com/10508276/113722023-05314600-96be-11eb-8fdc-7a58d8087306.png)
https://www.cbioportal.org/results/plots?cancer_study_list=luad_tcga%2Cluad_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=0&case_set_id=all&gene_list=ALK%2520ROS1%2520RET%2520EGFR%2520EZR%2520EML4&geneset_list=%20&tab_index=tab_visualize&Action=Submit&data_priority=0&plots_horz_selection=%7B%22dataType%22%3A%22MUTATION_EXTENDED%22%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D

**Comment by adamabeshouse** [comment]
I pushed a fix to the main branch, let me know if the problem is fixed and we can close this issue @tmazor

**Comment by tmazor** [comment]
Looks good to me - thanks @adamabeshouse
