### ISSUE TITLE
sv testing - plots no data message is wonky

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8489]
Prod correctly just says 'No data to plot':
![image](https://user-images.githubusercontent.com/10508276/113723221-234b7600-96bf-11eb-99fa-35c9060f15a8.png)

The same plot on beta says 1027 samples have data, and then shows the 'No data to plot message'. If you look in the tooltip, the calculation is off, which is presumably why that message is showing.
![image](https://user-images.githubusercontent.com/10508276/113723286-32322880-96bf-11eb-860c-4d7057c747e9.png)

https://beta.cbioportal.org/results/plots?cancer_study_list=luad_tcga%2Cluad_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Cgistic&case_set_id=all&gene_list=ALK%2520ROS1%2520RET%2520EGFR%2520EZR%2520EML4&geneset_list=%20&tab_index=tab_visualize&Action=Submit&plots_horz_selection=%7B%22selectedGeneOption%22%3A238%2C%22dataType%22%3A%22METHYLATION%22%7D&plots_vert_selection=%7B%22selectedGeneOption%22%3A-2%2C%22dataType%22%3A%22MRNA_EXPRESSION%22%2C%22selectedDataSourceOption%22%3A%22rna_seq_v2_mrna%22%2C%22logScale%22%3A%22true%22%7D&plots_coloring_selection=%7B%22colorByMutationType%22%3A%22true%22%2C%22colorByCopyNumber%22%3A%22false%22%2C%22colorBySv%22%3A%22false%22%7D

**Comment by kalletlak** [comment]
Yes, this was recently fixed in prod. merging master branch to sv branch should resolve this.

**Comment by kalletlak** [comment]
Should be now fixed on beta.
