### ISSUE TITLE
Is it possible to load all mutated genes in study view?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#849]
In the current Mutations tab, we only load a subset. Is it possible to load all?

![image](https://cloud.githubusercontent.com/assets/840895/13118241/5d0a5b00-d571-11e5-8c6f-02715e42da09.png)

IN the Mutated Genes table, are we doing the same? If so, can we load all? Similarly for CNA?

**Comment by zhx828** [comment]
This has been proved that it will take too much time to get all mutated genes. Close for now.
