### ISSUE TITLE
sv testing - genomic alterations results are different

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8490]
Same query, alteration types & groups selected but totally different results. Is that expected from the SV changes?

beta:
![image](https://user-images.githubusercontent.com/10508276/113725486-5c84e580-96c1-11eb-9e39-4dfa3f434d2c.png)
https://beta.cbioportal.org/results/comparison?cancer_study_list=luad_tcga%2Cluad_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Cgistic&case_set_id=all&gene_list=ALK%2520ROS1%2520RET%2520EGFR%2520EZR%2520EML4&geneset_list=%20&tab_index=tab_visualize&Action=Submit&plots_horz_selection=%7B%22dataType%22%3A%22clinical_attribute%22%2C%22selectedGeneOption%22%3A1956%2C%22selectedDataSourceOption%22%3A%22CANCER_STUDY%22%2C%22logScale%22%3A%22true%22%7D&plots_vert_selection=%7B%22selectedGeneOption%22%3A1956%2C%22dataType%22%3A%22MRNA_EXPRESSION%22%2C%22selectedDataSourceOption%22%3A%22rna_seq_v2_mrna%22%2C%22logScale%22%3A%22true%22%7D&plots_coloring_selection=%7B%7D&mutations_gene=EML4&comparison_selectedGroups=%5B%22ALK%22%2C%22ROS1%22%5D&comparison_subtab=alterations

prod:
![image](https://user-images.githubusercontent.com/10508276/113725531-660e4d80-96c1-11eb-9eda-4e9fbf2b847b.png)
https://www.cbioportal.org/results/comparison?cancer_study_list=luad_tcga%2Cluad_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=0&case_set_id=all&gene_list=ALK%2520ROS1%2520RET%2520EGFR%2520EZR%2520EML4&geneset_list=%20&tab_index=tab_visualize&Action=Submit&data_priority=0&plots_horz_selection=%7B%22dataType%22%3A%22clinical_attribute%22%2C%22selectedGeneOption%22%3A1956%2C%22selectedDataSourceOption%22%3A%22CANCER_STUDY%22%2C%22logScale%22%3A%22true%22%7D&plots_vert_selection=%7B%22selectedGeneOption%22%3A1956%2C%22dataType%22%3A%22MRNA_EXPRESSION%22%2C%22selectedDataSourceOption%22%3A%22rna_seq_v2_mrna%22%2C%22logScale%22%3A%22true%22%7D&plots_coloring_selection=%7B%7D&mutations_gene=EML4&comparison_selectedGroups=%5B%22ALK%22%2C%22ROS1%22%5D&comparison_subtab=alterations

**Comment by tmazor** [comment]
The above query is in 2 studies. If I modify the query to be in either of the two studies alone, then I get identical results between prod & beta. I picked these two studies to query because one has SV data and the other doesn't - maybe that's part of the issue?

**Comment by kalletlak** [comment]
Might be related https://github.com/cBioPortal/cbioportal/issues/8484
