### ISSUE TITLE
genomic alterations tooltip stays visible

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8491]
Once this tooltip appears, it sticks around, long after the mouse is no longer hovering over the button. I haven't had this with other tooltips, but for some reason this one consistently stays.

![Apr-06-2021 10-22-12](https://user-images.githubusercontent.com/10508276/113726228-0c5a5300-96c2-11eb-8af6-7044f52e3369.gif)

**Comment by alisman** [comment]
@leexgh i'm pretty sure this is due to the fact that the button is disabled.  apparently disabled buttons don't have a mouseout event?    if you check a gene, the button becomes enabled and the problem goes away.  perhaps google some solution?
