### ISSUE TITLE
GENIE first example query returns only not profiled

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8493]
Try the first example query:

<img width="298" alt="Screen Shot 2021-04-07 at 9 06 15 AM" src="https://user-images.githubusercontent.com/1334004/113871087-8a7d2f00-9780-11eb-973c-29785a0e76cc.png">

or URL:

https://genie.cbioportal.org/results?cancer_study_list=genie_public&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=genie_mutations&data_priority=0&case_set_id=genie_public_all&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=KRAS%0D%0ANRAS%0D%0AHRAS%0D%0ABRAF&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false

This gives 0 profiled cases:

<img width="439" alt="Screen Shot 2021-04-07 at 9 11 50 AM" src="https://user-images.githubusercontent.com/1334004/113871930-63732d00-9781-11eb-8fe2-455028a6b924.png">

But in the study view you can clearly see there should be several (I removed the exact counts):
<img width="402" alt="Screen Shot 2021-04-07 at 9 05 50 AM" src="https://user-images.githubusercontent.com/1334004/113872584-0166f780-9782-11eb-9396-0015202f8328.png">

<img width="401" alt="Screen Shot 2021-04-07 at 9 05 43 AM" src="https://user-images.githubusercontent.com/1334004/113872768-2ce9e200-9782-11eb-85e9-199f0c3fb527.png">

**Comment by inodb** [comment]
Looks like it is related to using a `case_set_id` of `genie_mutations` vs `genie_public_all`

**Comment by inodb** [comment]
I can do a quick fix for the examples, just changing the URLs. But curious why the `*_mutations` case id list doesn't work anymore

**Comment by kalletlak** [comment]
@inodb problem is with molecular profile. `genie_mutations` doesn't exits. replacing it with `genie_public_mutations` should fix it.
Here is the updated url https://genie.cbioportal.org/results?cancer_study_list=genie_public&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=genie_public_mutations&data_priority=0&case_set_id=genie_public_all&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=KRAS%0D%0ANRAS%0D%0AHRAS%0D%0ABRAF&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false

**Comment by inodb** [comment]
@kalletlak Gotcha - thanks! 

It feels slightly odd that we see N/P when the profile doesn't exist. Maybe we should show some error instead?
