### ISSUE TITLE
Change error message when user does not have access to study or study does not exist

### ISSUE THREAD

**Issue by mandawilson** [cBioPortal/cbioportal#8500]
Can we "polish" the error message returned when a user does not have access to a study (see below). Maybe something like:

"The study you are trying to access does not exist, or you do not have access to the study".

It looks like the frontend is querying the backend with a empty list of studies (knowingly) and just returning the error response from the backend api. We are thinking we should stop the queries to the backend when we see an "empty list" and return a clearer error. 

![3e6acc48-8e6f-454d-9db3-a60add8d4edb](https://user-images.githubusercontent.com/1458628/114040749-d365de00-987b-11eb-82c2-e451f8a8ad87.png)

@alisman

**Comment by Sjoerd-van-Hagen** [comment]
@dianab0 as part of this RFC: https://docs.google.com/document/d/1NkNhBG1sk0ZvCOwk3XtiuRT9a_tKkFCgXC9I3XT-Ye4/edit we need to replace this error with a page that either provides the message that @mandawilson indicated or the message as indicated in the RFC. Can you start by making the required changes to resolve the issue that Manda raised? When the RFC is finalized we can improve upon it.

@alisman I removed you as assignee but if you have any input to provide, please do.

As a first design, I think we can take the current error page, replace the Ooops part with the message suggested by Manda, and remove everything else except the link back to the homepage. Agreed @cBioPortal/product ?
