### ISSUE TITLE
Copy Number Segments Takes too long on mskimpact (OutOfMemory)

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8502]
There are a few out of memory exceptions on sentry related to copy number segments e.g.

https://sentry.io/organizations/memorial-sloan-kettering/issues/2321437332/?project=236782&referrer=slack

Let's limit the number of samples you can view (e.g. 20K):

- [ ] Text can be 'Too many samples too in copy number segmentation view, make a selection on Summary tab first'

Alternatively we can do some pagination, where we pull the results in batches

CC @jjgao @onursumer

**Comment by jjgao** [comment]
It makes sense to limit the number of samples. Are we loading all chromosomes?
