### ISSUE TITLE
Broken link in Documentation --> Datasets

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#8505]
On this page

https://docs.cbioportal.org/5.1-data-loading/data-loading#example-studies

the link to the cBioPortal data sets is broken. It links to https://www.cbioportal.org/data_sets.jsp insteas of https://www.cbioportal.org/datasets

**Comment by inodb** [comment]
i fixed the link, but we might want to add the JSP redirect as well CC @alisman

**Comment by jjgao** [comment]
I think it might be ok without redirecting since the jsp pages are so long ago...
