### ISSUE TITLE
Add actual numbers to downloadable results on Cancer Types Summary tab

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#8508]
The Cancer Types Summary tab allows users to download the percentages via the download button ("Data" option). 

It would be great to add additional columns to this file that indicate the numbers the frequencies were calculated from.

**Comment by dippindots** [comment]
Example link: https://www.cbioportal.org/results/cancerTypesSummary?cancer_study_list=metastatic_solid_tumors_mich_2017&tab_index=tab_visualize&case_set_id=metastatic_solid_tumors_mich_2017_all&Action=Submit&gene_list=TP53

**Comment by dippindots** [comment]
Add `Alteration Count` column
