### ISSUE TITLE
sv testing - genomic alterations differences in profiled samples

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8515]
Only SV/Fusions are selected as alteration types. Prod & beta show differences in which samples are profiled (see co-occurrence pattern column), resulting in different frequencies per group and different p/q-values:

prod:
![image](https://user-images.githubusercontent.com/10508276/114754121-3517c380-9d26-11eb-889e-44b925659fd9.png)
https://www.cbioportal.org/results/comparison?cancer_study_list=luad_tcga%2Cluad_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=0&case_set_id=all&gene_list=ALK%2520ROS1%2520RET%2520EGFR%2520EZR%2520EML4&geneset_list=%20&tab_index=tab_visualize&Action=Submit&data_priority=0&plots_horz_selection=%7B%22dataType%22%3A%22clinical_attribute%22%2C%22selectedGeneOption%22%3A1956%2C%22selectedDataSourceOption%22%3A%22CANCER_STUDY%22%2C%22logScale%22%3A%22true%22%7D&plots_vert_selection=%7B%22selectedGeneOption%22%3A1956%2C%22dataType%22%3A%22MRNA_EXPRESSION%22%2C%22selectedDataSourceOption%22%3A%22rna_seq_v2_mrna%22%2C%22logScale%22%3A%22true%22%7D&plots_coloring_selection=%7B%7D&mutations_gene=EML4&comparison_selectedGroups=%5B%22ALK%22%2C%22ROS1%22%5D&comparison_subtab=alterations&comparison_selectedEnrichmentEventTypes=%5B%22fusion%22%5D

beta:
![image](https://user-images.githubusercontent.com/10508276/114754157-406aef00-9d26-11eb-8b4c-3b6b5e93850a.png)
https://beta.cbioportal.org/results/comparison?cancer_study_list=luad_tcga%2Cluad_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Cgistic&case_set_id=all&gene_list=ALK%2520ROS1%2520RET%2520EGFR%2520EZR%2520EML4&geneset_list=%20&tab_index=tab_visualize&Action=Submit&plots_horz_selection=%7B%22dataType%22%3A%22clinical_attribute%22%2C%22selectedGeneOption%22%3A1956%2C%22selectedDataSourceOption%22%3A%22CANCER_STUDY%22%2C%22logScale%22%3A%22true%22%7D&plots_vert_selection=%7B%22selectedGeneOption%22%3A1956%2C%22dataType%22%3A%22MRNA_EXPRESSION%22%2C%22selectedDataSourceOption%22%3A%22rna_seq_v2_mrna%22%2C%22logScale%22%3A%22true%22%7D&plots_coloring_selection=%7B%7D&mutations_gene=EML4&comparison_selectedGroups=%5B%22ALK%22%2C%22ROS1%22%5D&comparison_subtab=alterations&comparison_selectedEnrichmentEventTypes=%5B%22structural_variant%22%5D

**Comment by kalletlak** [comment]
Looks like results in beta instance are correct. Prod includes samples from `luad_tcga` even if it doesn't have fusion/structural variant profile

**Comment by tmazor** [comment]
Gotcha. But in that case, shouldn't the Co-occurrence Pattern graphs on beta be showing some samples as not profiled?

**Comment by kalletlak** [comment]
@tmazor yes. it should be fixed now

**Comment by tmazor** [comment]
The plot looks better now, thanks @kalletlak 

But I wanted to try to verify the sample numbers, and I can't seem to do that. Here's what I did:
I used the overlap tab to save groups identical to ALK (63 samples) and ROS1 (56 samples) from this query.
Then I opened up the combined study in study view, and filtered to my ALK group (link below)
On the study view page, it's showing 41 samples as profiled for SV:
![image](https://user-images.githubusercontent.com/10508276/114935812-a3818200-9e09-11eb-843e-885b13bff297.png)
But the genomic alterations tab tooltip shows 35 profiled samples:
![image](https://user-images.githubusercontent.com/10508276/114935895-bac06f80-9e09-11eb-8d7b-879b99e9b61e.png)

I can do the same for ROS1, and I get 36 samples profiled for SV in study view, but the tooltip shows 30.

Am I doing something wrong in my attempt to replicate this? Or is there a data inconsistency somewhere?



https://beta.cbioportal.org/study/summary?id=luad_tcga%2Cluad_tcga_pan_can_atlas_2018#filterJson={"sampleIdentifiers":[{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-44-7667-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-67-6216-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-17-Z043-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-44-4112-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-44-6777-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-91-6836-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-55-1592-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-17-Z001-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-MP-A5C7-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-55-7728-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-05-4397-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-17-Z031-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-MP-A4T4-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-05-4410-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-44-2656-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-73-A9RS-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-55-7995-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-67-6215-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-44-6776-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-38-4626-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-78-7163-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-50-5946-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-17-Z025-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-44-7662-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-78-7220-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-97-7938-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-L9-A8F4-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-05-4432-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-MP-A4TI-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-55-7994-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-64-5781-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-55-8089-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-55-8205-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-78-7154-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-17-Z036-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-55-6978-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-50-8460-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-05-4382-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-44-7670-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-50-5930-01"},{"studyId":"luad_tcga_pan_can_atlas_2018","sampleId":"TCGA-86-A4P8-01"},{"studyId":"luad_tcga","sampleId":"TCGA-44-7667-01"},{"studyId":"luad_tcga","sampleId":"TCGA-L9-A7SV-01"},{"studyId":"luad_tcga","sampleId":"TCGA-38-4627-01"},{"studyId":"luad_tcga","sampleId":"TCGA-44-6776-01"},{"studyId":"luad_tcga","sampleId":"TCGA-44-6777-01"},{"studyId":"luad_tcga","sampleId":"TCGA-44-4112-01"},{"studyId":"luad_tcga","sampleId":"TCGA-55-1592-01"},{"studyId":"luad_tcga","sampleId":"TCGA-44-7662-01"},{"studyId":"luad_tcga","sampleId":"TCGA-97-7938-01"},{"studyId":"luad_tcga","sampleId":"TCGA-55-7728-01"},{"studyId":"luad_tcga","sampleId":"TCGA-55-8092-01"},{"studyId":"luad_tcga","sampleId":"TCGA-05-4432-01"},{"studyId":"luad_tcga","sampleId":"TCGA-55-7994-01"},{"studyId":"luad_tcga","sampleId":"TCGA-64-5781-01"},{"studyId":"luad_tcga","sampleId":"TCGA-95-7043-01"},{"studyId":"luad_tcga","sampleId":"TCGA-05-4410-01"},{"studyId":"luad_tcga","sampleId":"TCGA-78-7154-01"},{"studyId":"luad_tcga","sampleId":"TCGA-44-2656-01"},{"studyId":"luad_tcga","sampleId":"TCGA-73-A9RS-01"},{"studyId":"luad_tcga","sampleId":"TCGA-44-7671-01"},{"studyId":"luad_tcga","sampleId":"TCGA-44-7670-01"},{"studyId":"luad_tcga","sampleId":"TCGA-05-4382-01"}]}

**Comment by kalletlak** [comment]
@tmazor there are 9 samples the overlap in both groups which are excluded. Counts should match if they are included in analysis
<img width="1420" alt="Screen Shot 2021-04-16 at 1 22 56 PM" src="https://user-images.githubusercontent.com/12956870/115061229-e8172700-9eb6-11eb-8492-bf5612cb9bf9.png">

**Comment by tmazor** [comment]
🤦‍♀️     thanks @kalletlak, that does indeed fix it
