### ISSUE TITLE
sv testing - comparison tab has error and goes blank

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8516]
In this example, I have 2 groups, which correspond to 2 different studies. One study has SV data, the other does not.

When I set the Genomic Alteration tab to only SV, then I get a blank page and this error in the console:
![image](https://user-images.githubusercontent.com/10508276/114759904-bd996280-9d2c-11eb-847f-23225a1dbf94.png)
https://beta.cbioportal.org/comparison/alterations?comparisonId=6077320de4b0242bd5d483e6&selectedEnrichmentEventTypes=%5B%22structural_variant%22%5D

Copy number data is also only available in one of the studies, but when I set the alteration types to copy number, the page loads with a nice 'no data' message:
![image](https://user-images.githubusercontent.com/10508276/114760173-0c46fc80-9d2d-11eb-806f-0909c38a8500.png)
https://beta.cbioportal.org/comparison/alterations?comparisonId=6077320de4b0242bd5d483e6&selectedEnrichmentEventTypes=%5B%22HOMDEL%22%2C%22AMP%22%5D

**Comment by kalletlak** [comment]
@tmazor thanks for testing. It should be fixed now.
