### ISSUE TITLE
sv testing - fusion vs other on mutations tab

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8518]
On prod, EGFR-intragenic is counted under 'Fusion' on the Mutations tab:
![image](https://user-images.githubusercontent.com/10508276/114763674-11a64600-9d31-11eb-91e4-15d76732f81c.png)
https://www.cbioportal.org/results/mutations?plots_horz_selection=%7B%22selectedGeneOption%22%3A1956%2C%22dataType%22%3A%22MUTATION_EXTENDED%22%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D&tab_index=tab_visualize&data_priority=0&Action=Submit&session_id=607738f3e4b0242bd5d48402&mutations_gene=EGFR

On beta, those same events are counting under 'Other':
![image](https://user-images.githubusercontent.com/10508276/114763769-2da9e780-9d31-11eb-8d8c-41682b33bae8.png)
https://beta.cbioportal.org/results/mutations?plots_horz_selection=%7B%22selectedGeneOption%22%3A1956%2C%22dataType%22%3A%22MUTATION_EXTENDED%22%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D&tab_index=tab_visualize&Action=Submit&session_id=607738f8e4b015b63e9e5fed&clinicallist=CANCER_STUDY%2CNUM_SAMPLES_PER_PATIENT%2CPROFILED_IN_COPY_NUMBER_ALTERATION&mutations_gene=EGFR

For consistency, should we continue to group all of those under 'Fusion' ? And maybe rename 'Fusion' to 'SV' to better match OncoPrint?

@jjgao @schultzn thoughts?

**Comment by kalletlak** [comment]
@tmazor updated to show all SV's under Fusion

**Comment by schultzn** [comment]
Thanks. Should “Fusion" be renamed to "Fusion/SV”?

**Comment by onursumer** [comment]
There is an ongoing effort to improve the filtering by type (#8437). We may want to wait for that work to finish in order to avoid potential conflicts.

**Comment by kalletlak** [comment]
Fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/3358
