### ISSUE TITLE
study view: column plot not working with outliers

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#852]
Maybe set the min/max (left/right) numbers to 5% and 95% percentiles.

![image](https://cloud.githubusercontent.com/assets/840895/13123207/32c57b50-d589-11e5-8ec3-2031f4ad36e2.png)

**Comment by zhx828** [comment]
@jjgao but how do you want to select the outliers if you shorten the range?

**Comment by jjgao** [comment]
@zhx828 the outliers will be in two groups (left and right). Please prioritize this.

**Comment by jjgao** [comment]
@zhx828 you can use this one to detect ourliers instead of using 5% and 95%: https://onlinecourses.science.psu.edu/stat200/node/135
