### ISSUE TITLE
  Save Column Visibility & Add "Reset Columns" Button

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8521]
We want to be able to store the columns that a user selected (e.g. chrom/pos/ref/alt).

- [ ] store current column selection in localStorage (so when switching genes on mutations tab it will keep the same state)
- [ ] maybe have some way to indicate that you want to persist the current column selection (instead of always saving). Those setting can then be saved in session service

Discussion points:
- Alternatively we always save in session service to avoid having to build the UI for that
- store patient view table and mutations tab user settings separately?

The more long term goal with this is to be able to also store specific annotations that have been selected.

**Comment by jjgao** [comment]
I think it makes sense to have separate settings for the mutations tab and patient view.

Saving to localstorage seems like an easy option to go... It doesn't seem to be a critical setting that would warranty saving to the user profile or session/url...
