### ISSUE TITLE
study view colors change after filtering

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8524]
I'm pretty sure we fixed this once before, but it seems to be a problem again - the color associated with a particular value changes after filtering.

Go here: https://www.cbioportal.org/study/summary?id=luad_tcga%2Cluad_tcga_pan_can_atlas_2018

See Cancer Studies chart:
![image](https://user-images.githubusercontent.com/10508276/114934680-328d9a80-9e08-11eb-9408-3a327bdc581c.png)

Now filter for Microbiome Signatures, which is only available in the PanCan study, and then look at Cancer Studies chart again:
![image](https://user-images.githubusercontent.com/10508276/114934743-4e913c00-9e08-11eb-8d72-f0f27fde1928.png)

The PanCan study has switched from red to blue. Colors should be consistent after filters are applied.

**Comment by jjgao** [comment]
@kalletlak @zhx828 do you remember if we have fixed this?

**Comment by kalletlak** [comment]
@jjgao looks like this not working just for `Cancer Study` chart
