### ISSUE TITLE
Downloading RNA expression data does not work for TCGA

### ISSUE THREAD

**Issue by gregpoore** [cBioPortal/cbioportal#8528]
I'm trying to download mRNA Expression, RSEM (Batch normalized from Illumina HiSeq_RNASeqV2) data for TCGA PanCancer Atlas studies across 51 genes ([cBioPortal link here](https://www.cbioportal.org/results/download?data_priority=0&tab_index=tab_visualize&Action=Submit&session_id=6053e4d8e4b015b63e9e1369&plots_horz_selection=%7B%22dataType%22%3A%22clinical_attribute%22%2C%22selectedDataSourceOption%22%3A%22CANCER_TYPE_DETAILED%22%2C%22selectedGeneOption%22%3A7422%2C%22logScale%22%3A%22true%22%7D&plots_vert_selection=%7B%22selectedGeneOption%22%3A7422%2C%22logScale%22%3A%22true%22%2C%22dataType%22%3A%22MRNA_EXPRESSION%22%2C%22selectedDataSourceOption%22%3A%22rna_seq_v2_mrna%22%7D&plots_coloring_selection=%7B%7D)). However, all mRNA files downloaded from cBioPortal only have "NA" listed in their entries despite being shown under the Plots tab. This issue goes away, though, if I only select one TCGA cancer type e.g. [Bladder Cancer cBioPortal Link](https://www.cbioportal.org/results/download?genetic_profile_ids_PROFILE_MRNA_EXPRESSION=blca_tcga_pan_can_atlas_2018_rna_seq_v2_mrna_median_Zscores&cancer_study_list=blca_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=blca_tcga_pan_can_atlas_2018_rna_seq_v2_mrna&gene_list=VEGFA%250ASLC2A1%250APGAM1%250AENO1%250ALDHA%250ATPI1%250AP4HA1%250AMRPS17%250ACDKN3%250AADM%250ANDRG1%250ATUBB6%250AALDOA%250AMIF%250AACOT7%250AMCTS1%250APSRC1%250APSMA7%250AANLN%250ATUBA1B%250AMAD2L2%250AGPI%250ATUBA1C%250AMAP7D1%250ADDIT4%250ABNIP3%250AMRGBP%250AHILPDA%250AGAPDH%250AMRPL13%250ACHCHD2%250AYKT6%250APNP%250ACORO1C%250ASEC61G%250AANKRD37%250AESRP1%250APFKP%250ASHCBP1%250ACTSV%250AKIF20A%250ASLC25A32%250AUTP11%250ASLC16A1%250AMRPL15%250AKIF4A%250ALRRC42%250APGK1%250AHK2%250AAK4%250ACA9&geneset_list=%20&tab_index=tab_visualize&Action=Submit).

It appears that something has broken on the download function for the TCGA PanCancer Atlas. Do you know what this is?

If useful, the list of genes I am trying to query is as follows:

```
VEGFA
SLC2A1
PGAM1
ENO1
LDHA
TPI1
P4HA1
MRPS17
CDKN3
ADM
NDRG1
TUBB6
ALDOA
MIF
ACOT7
MCTS1
PSRC1
PSMA7
ANLN
TUBA1B
MAD2L2
GPI
TUBA1C
MAP7D1
DDIT4
BNIP3
MRGBP
HILPDA
GAPDH
MRPL13
CHCHD2
YKT6
PNP
CORO1C
SEC61G
ANKRD37
ESRP1
PFKP
SHCBP1
CTSV
KIF20A
SLC25A32
UTP11
SLC16A1
MRPL15
KIF4A
LRRC42
PGK1
HK2
AK4
CA9
```

**Comment by jjgao** [comment]
@dippindots could you prioritize this one?

**Comment by dippindots** [comment]
@jjgao Yes, I will fix this first.
