### ISSUE TITLE
add 'deselect all' to charts menu

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8541]
Sometimes I just want to clear the page and populate study view with charts of my choice - eg I just pulled up study view for the curated list of non-overlapping studies, and study view is populated with tons of charts that are mostly NA. I wanted to just remove them all and add back the ones I cared about but the only way to do that is delete each chart individually. Let's add a 'Deselect all' button:

![image](https://user-images.githubusercontent.com/10508276/115789846-c8d73880-a393-11eb-8e03-287f8a470568.png)

**Comment by Luke-Sikina** [comment]
@Rajat-Sirohi I can't assign this to you until we add you to the org, but this is your first ticket.
