### ISSUE TITLE
Timeline Data in pop over not ordered

### ISSUE THREAD

**Issue by AndyBlake** [cBioPortal/cbioportal#8545]
Hiya
When you have extra columns added to your timeline data when you hover over to show them on the timeline view the columns aren't ordered in any way (seems random)  - can they be ordered alphabetically so the display can be configured to show the most important data first by altering the column names?
Cheers
Andy

**Comment by AndyBlake** [comment]
Bump

**Comment by alisman** [comment]
Will give this a try.  Sorry it's sat around
