### ISSUE TITLE
patient view: bug if no mutation data is present

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#855]
I have a study which has no mutation data. I went to the patient view and it gives an
Uncaught ReferenceError: mutTableIndices is not defined
The problematic line is "aTargets": [mutTableIndices["annotation"]], in cna.json

What seems to happen is that patient_view.jsp checks whether there is a mutation profile, and if there is not, it does not include mutations.jsp
mutation.jsp has the mutTableIndices definition.

**Comment by aderidder** [comment]
Discussed with Sjoerd. We can probably fix this when we tackle #701, since that will require updates to the cna.jsp and other files involved in the patient view as well

**Comment by pieterlukasse** [comment]
Steps to reproduce: 
- go to TCGA Mesothelioma study overview: http://www.cbioportal.org/study.do?cancer_study_id=meso_tcga
- go to the [samples overview page](http://www.cbioportal.org/case.do?cancer_study_id=meso_tcga&case_id=TCGA-3H-AB3K#nav_case_ids=TCGA-3H-AB3K,TCGA-3H-AB3L,TCGA-3H-AB3M,TCGA-3H-AB3O,TCGA-3H-AB3S,TCGA-3H-AB3T,TCGA-3H-AB3U,TCGA-3H-AB3X,TCGA-3U-A98D,TCGA-3U-A98E,TCGA-3U-A98F,TCGA-3U-A98G,TCGA-3U-A98H,TCGA-3U-A98I,TCGA-3U-A98J,TCGA-LK-A4NW,TCGA-LK-A4NY,TCGA-LK-A4NZ,TCGA-LK-A4O0,TCGA-LK-A4O2,TCGA-LK-A4O4,TCGA-LK-A4O5,TCGA-LK-A4O6,TCGA-LK-A4O7,TCGA-MQ-A4KX,TCGA-MQ-A4LC,TCGA-MQ-A4LI,TCGA-MQ-A4LJ,TCGA-MQ-A4LM,TCGA-MQ-A4LP,TCGA-MQ-A4LV,TCGA-MQ-A6BL,TCGA-MQ-A6BN,TCGA-MQ-A6BQ,TCGA-MQ-A6BR,TCGA-MQ-A6BS,TCGA-NQ-A57I,TCGA-NQ-A638,TCGA-SC-A6LM,TCGA-SC-A6LN,TCGA-SC-A6LP,TCGA-SC-A6LQ,TCGA-SC-A6LR,TCGA-SC-AA5Z,TCGA-SH-A7BC,TCGA-SH-A7BD,TCGA-SH-A7BH,TCGA-SH-A9CT,TCGA-SH-A9CU,TCGA-TS-A7OU,TCGA-TS-A7OY,TCGA-TS-A7OZ,TCGA-TS-A7P0,TCGA-TS-A7P1,TCGA-TS-A7P3,TCGA-TS-A7P6,TCGA-TS-A7P7,TCGA-TS-A7P8,TCGA-TS-A7PB,TCGA-TS-A8AF,TCGA-TS-A8AI,TCGA-TS-A8AS,TCGA-TS-A8AV,TCGA-TS-A8AY,TCGA-UD-AABY,TCGA-UD-AABZ,TCGA-UD-AAC1,TCGA-UD-AAC4,TCGA-UD-AAC5,TCGA-UD-AAC6,TCGA-UD-AAC7,TCGA-UT-A88C,TCGA-UT-A88D,TCGA-UT-A88E,TCGA-UT-A88G,TCGA-UT-A97Y,TCGA-XT-AASU,TCGA-YS-A95B,TCGA-YS-A95C,TCGA-YS-AA4M,TCGA-ZN-A9VO,TCGA-ZN-A9VP,TCGA-ZN-A9VQ,TCGA-ZN-A9VS,TCGA-ZN-A9VU,TCGA-ZN-A9VV,TCGA-ZN-A9VW)

This gives the error:

![image](https://cloud.githubusercontent.com/assets/2900303/14636301/e1706aa8-062a-11e6-9450-2608d304634d.png)

**Comment by jjgao** [comment]
Yes, it's a critical issue. This is on @inodb's list #995, but feel free to fix it if you like (please coordinate with @inodb so that no duplicated work would be done). Please send separate pull request for this to hotfix branch. Thanks!

**Comment by pieterlukasse** [comment]
Hi @jjgao , thanks for the update. @aderidder has a local branch with some tentative fixes for this (not complete though). But he will only be back on Thursday. Maybe it is best to let @inodb fix it and then let @aderidder review it. 

The problem is quite simple actually, `mutTableIndices` element is only added when mutation data is present, but it is referenced in a global javascript function regardless of that. A quick fix should be easy. A proper fix involved some more refactoring...

**Comment by inodb** [comment]
I'll have a look

**Comment by inodb** [comment]
Made a quickfix in https://github.com/cBioPortal/cbioportal/pull/1081
