### ISSUE TITLE
driver icon on mutations tab too visible

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8560]
From Niki: can we change the icon to be a bit less visible?

<img width="143" alt="Screen Shot 2021-04-30 at 3 27 35 PM" src="https://user-images.githubusercontent.com/1334004/116744729-b2029880-a9c8-11eb-91b9-28599f31d019.png">

Maybe we can put the info icon behind it and put the blue button in a tooltip? We can reuse this one:

<img width="359" alt="Screen Shot 2021-04-30 at 3 28 39 PM" src="https://user-images.githubusercontent.com/1334004/116745121-d8c0cf00-a9c8-11eb-8df1-54423a4f9d70.png">

Text in tooltip can maybe be "Change driver filtering in < blue button />"

**Comment by leexgh** [comment]
Our decision is hiding driver setting icon by default, and show the icon when hovering legend panel
