### ISSUE TITLE
Allele frequency display issue

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#8568]
AF shows up as number for patient with one sample, but shows up as bar for patient with 2 samples (even when one sample is selected).
Can the display be number when single sample is selected. 
Example: https://www.cbioportal.org/patient?studyId=lgg_ucsf_2014&sampleId=P01_Pri

**Comment by zhx828** [comment]
The issue has been fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/3931 and https://github.com/cBioPortal/cbioportal-frontend/pull/3950
