### ISSUE TITLE
Study View Mutations Table shows incorrect number of samples when based on case list _all

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#857]
I uploaded a very simple study with just two patients, one sample per patient and one mutation for each sample. My _all case-list contains the two samples and I use no other case-list.
According to the mutations table I have 3 profiled samples:
![image](https://cloud.githubusercontent.com/assets/9414840/13254145/52735c04-da40-11e5-98ff-171cf0fabe69.png)

I did some digging in StudyViewProxy and the third sample is an empty string. 
The issue seems to be line 235
`allSampleIds = _parts[4].split(' '); `

**Comment by pieterlukasse** [comment]
steps to reproduce:
- study with only mutation data
- just one case list, i.e. the "_all"

**Comment by aderidder** [comment]
[fileToReproduce.zip](https://github.com/cBioPortal/cbioportal/files/144730/fileToReproduce.zip)

**Comment by zheins** [comment]
Related to PR #841

**Comment by pieterlukasse** [comment]
thanks for the heads up @zheins !  @aderidder : can you verify this fixes your problem? Then we can close this issue.

**Comment by aderidder** [comment]
Yes. We can close it.
