### ISSUE TITLE
incorrect number of driver SV/Fusion

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8571]
https://bit.ly/3hbuHkS

![image](https://user-images.githubusercontent.com/840895/117187350-d20bd080-ada9-11eb-87bb-76d0322f1b9f.png)

**Comment by inodb** [comment]
Also oncoprint annotations seem to be missing oncokb:

![Screen Shot 2021-05-13 at 10.43.25 AM.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/a859c5f6-449e-4f16-9cfc-fd2eadcbc66a)

**Comment by inodb** [comment]
Te issue is that the annotation only works if the first gene is ALK

**Comment by jjgao** [comment]
@leexgh all of them should be drivers as annotated in the mutations tab, but I guess they were not correctly annotated in OncoPrint... @zhx828 could you help look into this?

**Comment by inodb** [comment]
Solved 🙌 - thanks all!

![Screen Shot 2021-05-21 at 4.58.00 PM.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/6e4c7957-0fd9-4402-aeb6-58345b71396b)
