### ISSUE TITLE
Mutations tab: improve legend selection 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8572]
Currently, the first click will select one type and deselect all others. I think we can simplify the UI and just make every click to toggle for one type, which will be more intuitive.

**Comment by onursumer** [comment]
Does this mean that we don't want to support multiple selection? We won't be able to, for example, "show missense and splice mutations, filter out everything else".

**Comment by jjgao** [comment]
@leedonghn4 yes, looks good!

**Comment by leexgh** [comment]
Just want to double check with @jjgao and @schultzn, do both of you like this idea? Because @inodb and @onursumer mentioned we had some discussions about what to show with "first selection"

**Comment by schultzn** [comment]
To be honest, I just got used to our current implementation and am not so sure we should change it again. But maybe @jjgao can convince me?

**Comment by jjgao** [comment]
Had a discussion with @schultzn and he agreed that it's good to change. @leexgh I realized that my description above wasn't very clear, so let's discuss one more time (in standup) before you implement.
