### ISSUE TITLE
selection of binning not working 

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8573]
https://genie-private.cbioportal.org/study/summary?id=nsclc_genie_bpc

Try selecting >0 here:

<img width="407" alt="Screen Shot 2021-05-05 at 2 11 57 PM" src="https://user-images.githubusercontent.com/1334004/117189248-f8327000-adab-11eb-9825-6500c9281ab6.png">

Somehow it doesn't get selected when I try

**Comment by onursumer** [comment]
@inodb I don't see the `Number of mammographies` chart for this study. Do you think this is a data issue or an access restriction?

![genie_nsclc_genie_bpc](https://user-images.githubusercontent.com/3604198/117475688-58e7b700-af2a-11eb-9938-355bd2f978ac.png)
