### ISSUE TITLE
Unclear to user that MutationJSON returns filtered data

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#859]
The issue I ran into, is that for a very small test set with just 2 samples and 1 mutation per sample the study view gave me just a single mutation.
It turns out that MutationJSON first checks whether a mutation occurs more than once and next checks for cbio cancer genes. In my small set only one of the genes was a cbio cancer gene and as it has only mutation, it was not shown.

Suggested solution: provide information about which criteria are used to show mutations in e.g. the study view

**Comment by pieterlukasse** [comment]
I would suggest to add a tool tip to the mutations table saying how it is populated.
