### ISSUE TITLE
clinical data import: warning/error "Couldn't find sample"

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#860]
When I import clinical data, the importer tells me "Couldn't find sample <some sample id>". I was confused by this, as I am importing that sample and my clinical data definitely has data for it. The cause seems to be:

ImportClinicalData.java, addSampleToDatabase
`Sample sample = DaoSample.getSampleByCancerStudyAndSampleId(cancerStudy.getInternalId(), sampleId);` 

```
  public static Sample getSampleByCancerStudyAndSampleId(int cancerStudyId, String stableSampleId)
    {
        Map<String, Sample> samples = byCancerStudyIdAndStableSampleId.get(cancerStudyId);
        if (samples==null) {
            ProgressMonitor.logWarning("Couldn't find sample "+stableSampleId+" in study "+cancerStudyId);
            return null;
        }

        return samples.get(stableSampleId);
    }
```

So for the first sample for our clean study samples will be null and it will log a warning. By returning null addSampleToDatabase will add the sample. 
For the second sample for our clean study samples will not be null, no warning, but it will still return null, which still adds the sample.

**Comment by pieterlukasse** [comment]
@aderidder : I pushed up a pacht to our validator improvements branch (https://github.com/thehyve/cbioportal/tree/validator_and_loader_prelastrc). Could you please test this and close the issue if fixed?

**Comment by aderidder** [comment]
@pieterlukasse tested; the confusing message is gone.
