### ISSUE TITLE
CNV and fusions not shown when mutations are missing

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8612]
- [ ] reproduce the issue using the docker compose setup
- [ ] fix the issue if we can reproduce

Reported by a user:https://groups.google.com/g/cbioportal/c/7IZMH-BPbJw/m/E0GPqI_iAgAJ

**Comment by jjgao** [comment]
... when there is no mutations profile or when there are no mutations in a patient? @inodb
