### ISSUE TITLE
Address latency of oncokb calls in proxy

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8613]
OncoKB public website has redis setup. But in order to cache the annotation endpoints, we need to add redis to OncoKB Core.
The core app is under spring MVC. It has some difficulties to upgrade to spring boot to utilize the default jcache implementations. I need to write my own cache manager.

- [x] add redis to OncoKB Core
- [x] Enable caching for gene list http://localhost:8090/proxy/oncokb/utils/cancerGeneList
- [x] Enable caching for annotation endpoints

**Comment by jjgao** [comment]
@alisman fyi - I moved it into `In Progress` since the current sprint was assigned.

**Comment by inodb** [comment]
Next steps: figure out how to cache the OncoKB API

**Comment by zhx828** [comment]
The caching for annotation endpoints/cancer gene list etc have been enabled. There are few minor issues still need to be solved listed under https://github.com/oncokb/oncokb/issues/2589. But I think we can close this ticket.
