### ISSUE TITLE
_filteredAndAnnotatedMolecularDataReport invoke executing multiple times in single result view load

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8618]
From what I can tell, the following mobxpromise (resultsviewpagestore) is invoking multiple times when it would seem it should only be once.  The actual fetch is only happening once (probably due to our client side cache?) but this is still not great.  Lets figure it out why.

_filteredAndAnnotatedMolecularDataReport

**Comment by adamabeshouse** [comment]
I can't reproduce this - I tried it on a small query and on genie, and on both I only see invoke being called once for that. What query were you on?
