### ISSUE TITLE
Investigate gzip on upload behavior repercussions

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8620]
This kind of funny, but i noticed that sending gzip upload seems to cause the server to take a much longer time to respond.    I found this just by toggling on and off the gzip post behavior.   See below.

Possible explainations:
1. un-gzipping takes a really long time on server? (seems unlikely)
2. gzipping causes some caching to fail on server?

Short upload, but long server side
![image](https://user-images.githubusercontent.com/186521/119052172-3033d880-b992-11eb-9e54-1d94b3889d5b.png)

Long upload, but quick server side
![image](https://user-images.githubusercontent.com/186521/119051826-aedc4600-b991-11eb-8d34-82265b3b4d7c.png)

**Comment by alisman** [comment]
@Luke-Sikina it also makes no sense that content download would take so much longer for the first one than last one.  I mean, download should be the same, right?

**Comment by alisman** [comment]
You can see this in action [:](https://demo-quantum-portal-1610712338.cbioportal.org/results/oncoprint?cancer_study_list=genie_private&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Ccna&case_set_id=genie_private_cnaseq&gene_list=EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit)

**Comment by Luke-Sikina** [comment]
Notes:
- Gzipped bodies are taking longer to respond.
- Gzipping is just slow. It's not skipping any caches or doing anything crazy. The gzip wrapper is just slow
- I tried cutting out the logic that counts the bytes outputted by the gzip stream, that did basically nothing
- The underlying gzip stream takes 1.7s to unzip a request body my local copy of gunzip takes 0.03s to inflate.
