### ISSUE TITLE
Investigate why we call clinical data endpoint on results view oncoprint tab

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8621]

**Comment by kalletlak** [comment]
Looks like this is used for setting tumor type while fetching structural variant oncokb data.

@jjgao do we want this?

**Comment by jjgao** [comment]
@kalletlak How about mutations and cna? If not, why is SV data requires tumor type for oncokb?

**Comment by kalletlak** [comment]
it is not used for mutations and cna on oncoprint. But I think it is used elsewhere. I remember adding tumor type to sv oncokb as a part of fusion-sv migration

**Comment by jjgao** [comment]
For Mutations tab, we definitely need tumor types, but for OncoPrint, we don't. Could you remove that requirement for sv for oncoprint?

**Comment by kalletlak** [comment]
sure
