### ISSUE TITLE
CDSA slide viewer doesn't work for a few studies

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8661]
I checked for all pancan studies I found another issue, so these studies don't work atm:

- [ ] coadread
- [ ] laml

For non pancan studies, there is also issues with:

- [ ] https://deploy-preview-3779--cbioportalfrontend.netlify.app/study/summary?id=lgggbm_tcga_pub
- [ ] https://deploy-preview-3779--cbioportalfrontend.netlify.app/study/summary?id=nsclc_tcga_broad_2016

**Comment by inodb** [comment]
one option would be to at least disable it for these studies

**Comment by alisman** [comment]
David Guttman has promised to ask his devs to work on this.   They need to fix api so that it accurately reflects the availability of slides for a given patient.  They also need to fix their app so that it notifies user that has no slides rather than defaulting to another patient.

**Comment by inodb** [comment]
let's maybe disable this completely for now (JJ found an issue with another case)

**Comment by jjgao** [comment]
It was this one: https://www.cbioportal.org/patient/tissueImage?studyId=brca_tcga_pan_can_atlas_2018&caseId=TCGA-E9-A5FL

btw, should we close https://github.com/cBioPortal/cbioportal/issues/8447?
