### ISSUE TITLE
What is proper cbioportal database connection parameters for ssl connection?

### ISSUE THREAD

**Issue by mgcarrel50** [cBioPortal/cbioportal#8670]
I am getting this error message when starting up cbioportal:
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (TLS version used does not meet minimal requirements for this server. Please use a higher TLS version and retry.)

The database connection used to work to Azure, but after some linux OS updates to the kernel & openssl, it is failing.

My portal.properties file is configured like below: (key items x'd out)
# database
db.user=cbio_user@test-xxxxxxxxxxxxxxxx
db.password=yyyyyyyyyyyyyyy
db.host=test-xxxxxxxxxxxxxxxx.mysql.database.azure.com:3306
db.portal_db_name=cbioportal
db.driver=com.mysql.jdbc.Driver
db.connection_string=jdbc:mysql://test-xxxxxxxxxxxxxxxx.mysql.database.azure.com:3306/
db.suppress_schema_version_mismatch_errors=false
db.use_ssl=true

Anybody having the same issue?

Thanks,
Mike

**Comment by mgcarrel50** [comment]
An alternative question for this is How can we get cbioportal to work with TLS 1.2? It used to work when the database was using TLS 1.1 for connections, but since the mysql database minimum TLS version has been increased to 1.2, it doesn't work. Is there a database connection parameter that could be added to the portal.properties configuration file? Or is there something more involved that has to be done?

**Comment by jjgao** [comment]
@mgcarrel50 sorry for the late response. Were you able to find the answers to your questions? If not, please contact cbioportal@googlegroups.com for support.
