### ISSUE TITLE
Unify options in `importGenes.pl` to import mouse and human genes

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#8678]
When populating `reference_genome_table` using `importGenes.pl`

(1) the command options for mouse is seemingly incorrect and the format is inconsistent with importing human genes. We should clean this up. See @sheridancbio 's command [here](https://github.com/cBioPortal/cbioportal/pull/8460#discussion_r638854808) in this [PR](https://github.com/cBioPortal/cbioportal/pull/8460) for details.

(2) Does the mouse gene needs to be unzipped after download [here](https://github.com/cBioPortal/cbioportal/blob/master/docs/Updating-gene-and-gene_alias-tables.md#mouse-genes)? It is not clear. This whole process needs to be checked again.

**Comment by sheridancbio** [comment]
Yes .. I have a strong feeling that providing the *.gz filename as input data in the command `./importGenes.pl --genes <Mus_musculus.gene_info.gz> --gtf <gencode.v25.annotation.gtf> --genome-build <GRCh37>` will fail. The code seems to expect only a "plain" uncompressed file input. This command should be tested and the documentation should be revised if necessary.
