### ISSUE TITLE
filtering by genes is broken in v3.6.19

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8690]
<img width="1050" alt="Screen Shot 2021-06-15 at 1 53 26 PM" src="https://user-images.githubusercontent.com/1334004/122100401-2363a280-cde1-11eb-91d6-5f81c67e8896.png">

Can see the issue in master env here: https://bit.ly/3xtvrXL

**Comment by inodb** [comment]
@pvannierop @kalletlak - not entirely sure what the cause of this bug is but I'm guessing it's either https://github.com/cBioPortal/cbioportal/pull/8647 or https://github.com/cBioPortal/cbioportal/pull/8671 - any clue?

**Comment by pvannierop** [comment]
@inodb @kalletlak The strange thing is that at first load the page errors out. However, when pressing reload the page loads fine.
