### ISSUE TITLE
We no longer detect error condition in OQL

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8696]
Following test is broken:
'gives a submit error if protein oql is inputted and no protein profile is available for the study'

Go to homepage

Select study  prad_tcga_pub

Enter this OQL into gene box:
BRCA1: PROT>1

We should see some kind of error because study doesn't have expression profile.  Instead it submits.

**Comment by alisman** [comment]
@onursumer this error is detected in e2e test.   My guess is it has to do with change made to fetch molecular profiles as part of optimization.

**Comment by onursumer** [comment]
@alisman Actually https://www.cbioportal.org/api/molecular-profiles/fetch returns `PROTEIN_LEVEL` profile for `prad_tcga_pub`. Maybe this is not a bug but data update?

![prad_tcga_pub_profiles](https://user-images.githubusercontent.com/3604198/122593042-13430180-d033-11eb-9a53-ac3e3c0f7588.png)
