### ISSUE TITLE
Remove redundant items from study view

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#870]
Since the improvements of the study view page, there are now redundant items in this view. The old items could be removed and the study name could be moved into summary tab or perhaps the new items should move to the top (so they are visible when user is in other tabs as well). 

![image](https://cloud.githubusercontent.com/assets/2900303/13349934/1970b17e-dc7d-11e5-8987-fb02dd05698b.png)

**Comment by zhx828** [comment]
@pieterlukasse @jjgao I'm trying to solve the issue #976 but found out this is related. Should we discuss about this?

**Comment by jjgao** [comment]
@pieterlukasse good point.

I'd vote to move them up so that we can sync Clinical Data tab too.

@schultzn @ecerami what do you think?

**Comment by zhx828** [comment]
This issue should be solved in https://github.com/cBioPortal/cbioportal/pull/1405
The header layout has been updated in here https://github.com/cBioPortal/iViz/pull/274/commits/3ef5522d0785c56175790e991987d47815628d7d
