### ISSUE TITLE
Error: nested exception is java.lang.NumberFormatException

### ISSUE THREAD

**Issue by kronik22** [cBioPortal/cbioportal#8700]
I have converted the docker compose deployment into a kubernetes version using the latest versions of the containers, db schema, and db seed.

cbioportal container: v3.6.7
cgds.sql version 2.12.8 @ https://github.com/cBioPortal/cbioportal/blob/master/db-scripts/src/main/resources/cgds.sql
seed.sql version 2.12.8 @ https://github.com/cBioPortal/datahub/blob/master/seedDB/seed-cbioportal_hg19_v2.12.8.sql.gz
studies @ https://github.com/cBioPortal/datahub/tree/master/public
gene panels @ https://github.com/cBioPortal/datahub/tree/master/reference_data/gene_panels

I ran the cgds.sql and seed.sql import process, bulk imported the gene panels, bulk imported the studies and ran a gene query against the Cholangiocarcinoma TCGA PanCancer study and got the error below. This is the second rebuild of the db that i have done thinking that the initial version that started with v2.7.3 caused a problem. I get this error:

Jun 18, 2021 11:51:00 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [api] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NumberFormatException: For input string: ""] with root cause
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.cbioportal.service.impl.MolecularDataServiceImpl.getMolecularDataInMultipleMolecularProfiles(MolecularDataServiceImpl.java:158)

I get this error for queries against specific studies even if I reimport the study. I suspect that there is improperly formatted data in one of the imported study files or that the study import utility is dropping data as it filter warning records that breaks the query search.

Have you seen this error before? Is there a known resolution? Does the development team test importing all the studies with new releases of the schema and seed data?

This error/issue is turning into a make or break scenario for us using the cbioportal software, since we need to search all studies with regards to pathogenic genes.

**Comment by inodb** [comment]
@kronik22 Thanks for reporting this! All the studies should import, they have been recently reimported

If you are able to import your own studies but only have an issue with importing the ones from datahub one option might be to use the latest mysql dump which should have all of them loaded:

http://download.cbioportal.org/mysql-snapshots/mysql-snapshots-toc.html

Note that we recently changed seed database (like a week or so ago), so it's possible that this is related, but I'm hoping that using the public dump will solve your issue regardless for now

If you prefer using kubernetes over docker compose we also have some of our production config files here for reference: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment

**Comment by kronik22** [comment]
@inodb I was successful in getting my deployment to work once I removed the Pan Can Atlas studies which produced the java error (studies listed below). I will take a look at downloading and restoring with latest version of the db. The kubernetes deployment in the link you provided has a significant amount of customizations that adds deployment complexity. For my deployment I used the same 4 docker containers in the docker compose deployment, created a kubernetes service per container, configured the container connection strings to use the fqdn of the kubernetes cluster service names, i.e. cbioportal-service-frontend.cbioportal-namespace.svc.cluster.local. The knowledgesystems manifests did come in helpful for setting the java args for the frontend container. And, lastly I setup ingress to the frontend service on the cluster. It runs really well! Very quick when accessing single studies at a time. I may be able to share the Kubernetes code for the 4 container deployment. At the moment I have to get department approval to share the code. I am hopeful that I can. 

I encountered the java.lang.NumberFormatException with the studies listed below. The study import must add a field value in one of the database tables that the front end can't process. And, it seems to be restricted to the Pan Can Atlas studies. I have had success importing 275 of the 313 studies. I still have to do some research on a few additional studies that did not import.

Just glad to get a stable cbioportal kubernetes deployment running. The software is amazing! Everyone on the team is excited to have our own deployment of cbioportal. Thank you for responding to my issues. Please take care and stay safe.

acc_tcga_pan_can_atlas_2018.tar.gz
blca_tcga_pan_can_atlas_2018.tar.gz
brca_tcga_pan_can_atlas_2018.tar.gz
chol_tcga_pan_can_atlas_2018.tar.gz
coadread_tcga_pan_can_atlas_2018.tar.gz
dlbc_tcga_pan_can_atlas_2018.tar.gz
esca_tcga_pan_can_atlas_2018.tar.gz
gbm_tcga_pan_can_atlas_2018.tar.gz
lgg_tcga_pan_can_atlas_2018.tar.gz
hnsc_tcga_pan_can_atlas_2018.tar.gz
kich_tcga_pan_can_atlas_2018.tar.gz
kirc_tcga_pan_can_atlas_2018.tar.gz
kirp_tcga_pan_can_atlas_2018.tar.gz
luad_tcga_pan_can_atlas_2018.tar.gz
lihc_tcga_pan_can_atlas_2018.tar.gz
lusc_tcga_pan_can_atlas_2018.tar.gz
stad_tcga_pan_can_atlas_2018.tar.gz
laml_tcga_pan_can_atlas_2018.tar.gz
prad_tcga_pan_can_atlas_2018.tar.gz
thca_tcga_pan_can_atlas_2018.tar.gz
ucec_tcga_pan_can_atlas_2018.tar.gz

**Comment by jjgao** [comment]
@kronik22 Thanks for the update - great to hear! If possible, would you please take [this survey](https://docs.google.com/forms/d/e/1FAIpQLSflQdN956q7Xh5caO8z8jIaF6uMLBkKrSxFvPi8OhNBWB247w/viewform) to add your instance to the [cBioPortal Installation Map](https://www.cbioportal.org/installations)?
