### ISSUE TITLE
Incorrect profiled samples count for gene alteration count api's for multi-study queries

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#8701]
Example, for https://www.cbioportal.org/study/summary?id=msk_impact_2017%2Chnsc_tcga `CDKN2A-DT` in CNA genes table 

| Query      | Altered Samples | Profiled Samples     |
| :---        |    :----:   |          ---: |
| https://www.cbioportal.org/study/summary?id=msk_impact_2017       | -       | -  |
| https://www.cbioportal.org/study/summary?id=msk_impact_2017%2Chnsc_tcga      | 158       | 522  |
| https://www.cbioportal.org/study/summary?id=msk_impact_2017%2Chnsc_tcga      | 158       | 11,467  |

only `hnsc_tcga` study has data for `CDKN2A-DT` gene. So for muti-study query profiled sample count should be 522 instead of 11,467

**Comment by Luke-Sikina** [comment]
TODO: Wait for image to build, then @inodb will deploy.
