### ISSUE TITLE
Row height in cancer type detailed tables on study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#871]
Looks like the bug is back :(

![image](https://cloud.githubusercontent.com/assets/840895/13356562/dc9c89d4-dc73-11e5-86c3-ecd6937f678b.png)

**Comment by zhx828** [comment]
I may use ReactTable to replace it. Do you still want me to fix this issue?

**Comment by jjgao** [comment]
If it is an easy fix, yes.
