### ISSUE TITLE
Settings for multiple vs single OncoKB icon in annotation column 

### ISSUE THREAD

**Issue by leexgh** [cBioPortal/cbioportal#8710]
We want to have a setting for choosing between single or multiple oncokb icons:

- [ ] at the app level we want to control the default column visibility maybe something like `show.default_annotation_columns="oncokb_drug,oncokb_diagnostics,etc.."`. That way we can enable the mutiple oncokb icons on the MSK portal to have it be consistent with the clinical PDF report that shows the same icons. On the public portal we can show a single item
- [x] a user should be able to choose themselves what columns to show (e.g. only one oncokb icon or more)
- [x] ideally, a user could persist their choice between sessions (either thru localStorage or session-service) by clicking on some button that indicates "make current column visibility my default" and e.g. "reset to default column visibility". Maybe we can use a similar UX flow for study view (where it also might be nice to opt in to persist the current chart selection rather than always saving it as we do now)

Note: there might be some overlap with other tickets here in terms of saving user settings, so make sure to avoid duplicate work

**Comment by tmazor** [comment]
@jjgao what's the timeline for going back to a single icon for oncokb? Does it require this settings feature to be developed first, or can we go back to a single icon and then add these setting later?

**Comment by inodb** [comment]
Let's leave the first item here undone until someone requests this
