### ISSUE TITLE
feedback: clinical data in mutations tab

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8716]
This is awesome @Rajat-Sirohi !

I have just a few comments:

1. This is super minor, but the header looks very squat
![image](https://user-images.githubusercontent.com/10508276/123141292-3cde9d00-d426-11eb-9158-0fc65bed1a42.png)

compared to OncoPrint
![image](https://user-images.githubusercontent.com/10508276/123141343-4962f580-d426-11eb-92ec-14483cf3c595.png)

or study view
![image](https://user-images.githubusercontent.com/10508276/123141389-567fe480-d426-11eb-8bf5-9dbcb6760b41.png)

Can you add a bit more space above/below 'Clinical' and 'Mutations'?

2. In the Clinical Data tab in Study View, there's a tooltip with the description of the clinical data element:
![image](https://user-images.githubusercontent.com/10508276/123144346-998f8700-d429-11eb-91f8-f064f6f39454.png)

Could we do something similar here?

And just to put all the feedback in one place, here are @jjgao's comments from slack:

3. Do we need a “reset to default” button? (right now we can refresh the page to reset)

4. It would be good to remember the columns when switching genes, but that could be a separate effort as discussed on Monday.

I agree with both of those suggestions, and will just add that 3 becomes essential once we do 4. I'd be ok with 3 as a follow-up task if that makes more sense, but we should definitely do both.

**Comment by inodb** [comment]
feedback has been addressed, will be released as part of #3846
