### ISSUE TITLE
How to ovverride variables in portal.propties file or values

### ISSUE THREAD

**Issue by advissor** [cBioPortal/cbioportal#8725]
Hi, 
Trying to launch the CBIO portal outside of the docker-compose
Volumes are not available, so I can only mount the whole folder 

So, if I mount a volume to  /cbioportal/ with cusomt portal.properties file, it erases the files in the original Docker image

If, I export the  $PORTAL_HOME variable, then there is only a portal.properties file in that folder, but all other bundled scripts are missing and exits with an error

Tried to -Ddb.host  & -Ddb.connection_string, no success

Are there are another ways to overwrite the values in the default portal.properties file?

I want to keep the original docker image & don't want to create own custom one.

**Comment by jjgao** [comment]
@advissor would you please contact cbioportal@googlegroups.com for questions? Please feel free to report issues on github. Thanks!
