### ISSUE TITLE
Option to show full sample IDs in mutation tab

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#8727]
A collaborator from MDAnderson was asking if we could display full sample IDs in the mutation tab? He said it is important for them upcoming paper. Here is the study/link he is talking about: https://cbioportal.mskcc.org/results/mutations?cancer_study_list=mixed_msk_mdanderson_2[…]ixed_msk_mdanderson_2020_all&Action=Submit&gene_list=CDK12

@onursumer Suggested adding an option to toggle it. 
<img width="251" alt="Screen Shot 2021-06-29 at 12 58 49 PM" src="https://user-images.githubusercontent.com/5973438/123838969-963d4500-d8da-11eb-9308-26ddcab3ac33.png">

**Comment by onursumer** [comment]
@inodb @yichaoS I tried enabling the existing column resize functionality for the sample id column, but it doesn't by default truncate long sample ids. It is not possible to resize any narrower than the actual length of the string, and adding the style `text-overflow: ellipsis;` doesn't seem to fix the issue. We probably need more tricks to make this work as desired.

![resize_very_long_sample_id](https://user-images.githubusercontent.com/3604198/123984669-d102b400-d992-11eb-9b4e-248fff241f94.png)

**Comment by onursumer** [comment]
We have a problem with the tooltip for truncated text. Its position is calculated wrt the full length of the original text.

![truncated_cell_tooltip](https://user-images.githubusercontent.com/3604198/124022953-76ca1900-d9bb-11eb-86de-8a3eb229b36e.png)
