### ISSUE TITLE
Seems like heatmap tab has disappeared on study view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8730]
Not sure if related to v3.6.19 release but tested remote e2e tests before releasing and it worked fine: https://103269-66571349-gh.circle-artifacts.com/0/imageCompare.html

**Comment by alisman** [comment]
@inodb this looks to me like a coincidental problem on MDAnderson's end. 

We make this this GET to determine existience of heatmap:

https://bioinformatics.mdanderson.org/study2url?studyid=laml_tcga

The response is now empty for this study and many other tcga studies i checked. 

Do we have contact there?

**Comment by jjgao** [comment]
@ChrisWakefield would you please look into this? Thanks.

**Comment by ChrisWakefield** [comment]
@jjgao Yes.  I think it is an issue with our "study2url".

**Comment by ChrisWakefield** [comment]
I believe it's fixed now.  Can you please confirm?  If so, this issue can be closed.
Thanks!

**Comment by jjgao** [comment]
It's working on cbioportal. Thanks, @ChrisWakefield !
