### ISSUE TITLE
exon column shows ERROR instead of exon number

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8739]
https://cbioportal.mskcc.org/results/mutations?cancer_study_list=mskimpact&tab_index=tab_visualize&case_set_id=mskimpact_all&Action=Submit&gene_list=MET

**Comment by leexgh** [comment]
The link in description cannot be reproduced, here is another one with the same problem:
https://cbioportal.mskcc.org/results/mutations?plots_horz_selection=%7B%7D&plots_vert_s[…]isualize&Action=Submit&session_id=60ddc4b6e4b015b63e9f2cdd

**Comment by leexgh** [comment]
https://cbioportal.mskcc.org/results/mutations?cancer_study_list=mskimpact&tab_index=tab_visualize&case_set_id=mskimpact_all&Action=Submit&gene_list=MET
One failed annotation:
```
7,116339769,116340321,TTGCATTCGATATCAGTGAGAAGGCTAAAGGAAACGAAAGATGGTTTTATGTTTTTGACGGACCAGTCCTACATTGATGTTTTACCTGAGTTCAGAGATTCTTACCCCATTAAGTATGTCCATGCCTTTGAAAGCAACAATTTTATTTACTTCTTGACGGTCCAAAGGGAAACTCTAGATGCTCAGACTTTTCACACAAGAATAATCAGGTTCTGTTCCATAAACTCTGGATTGCATTCCTACATGGAAATGCCT,-
```
