### ISSUE TITLE
curious splice mutation annotations for OncoKB

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8740]
- I believe currently all X1010_splice mutations in MET are annotated as level 1 in lung. Curious if all these MET X1010_splice events are  actually exon 14 skipping since some of the positions are quite different (majority are around 116412046). 

    <img width="1197" alt="Screen Shot 2021-07-08 at 10 10 57 AM" src="https://user-images.githubusercontent.com/1334004/124937072-0d5a9380-dfd5-11eb-939e-3f0fe10b9aee.png">

- if they are different, we could maybe use genome nexus to actually annotate only the other mutations as exon 14 skip and then in OncoKB check for the presence of exon 14 skip 

- CTNNB1 splice events should be annotated as skipping in some way (currently only inframe mutations are annotated as driver, even though the splice ones are prolly similar in terms of effect)

- KIT exon 11 might be a nice example of how we should convert splice mutations to inframe deletions using genome nexus and annotate accordingly using OncoKB

**Comment by jjgao** [comment]
@inodb I guess this can be part of the splice mutation project? We should try to call the effect of the splice mutations in GN and we can then fix the annotation in OncoKB.

**Comment by jjgao** [comment]
@inodb I have created an issue in GN repo and will close this here. Let's follow up in GN meeting. Maybe we can start scheduling the work as part of GN?
