### ISSUE TITLE
HTML Validator:  Align Left

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#876]
Small tweak in the HTML validator: I think all the text should be aligned to the left, rather than centered.

**Comment by ecerami** [comment]
here's an example of center alignment.

![screenshot_712](https://cloud.githubusercontent.com/assets/1009066/13415133/59cb4148-df26-11e5-8d76-9417f6d34d9e.png)

**Comment by fedde-s** [comment]
Done in thehyve/cbioportal@12032a8bf547f2637a5869cad8e05583bd83d40e

**Comment by fedde-s** [comment]
![screen shot 2016-03-18 at 17 25 19](https://cloud.githubusercontent.com/assets/4929431/13884542/bc8f58a8-ed2e-11e5-98f7-13be290c7b76.png)

**Comment by fedde-s** [comment]
This has been improved upon in #1080 and merged into the release candidate.
