### ISSUE TITLE
HTML Validator Header

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#877]
In the HTML Validator header, we currently say:

study in '/Users/priti/Documents/secure/cbio-one/validator_test/profile_out/'
See this page for the data formats documentation.

Two suggestions:

first line should say something more explicit, e.g. "Study directory:  XXX"

second line does not have any obvious hyperlinks or underlines.  Suggest text should also say:  "For details, please see the [cBioPortal file format documentation]".

**Comment by fedde-s** [comment]
![screen shot 2016-03-18 at 17 25 19](https://cloud.githubusercontent.com/assets/4929431/13884542/bc8f58a8-ed2e-11e5-98f7-13be290c7b76.png)

**Comment by ecerami** [comment]
@fedde-s @pieterlukasse:  can you please revise/finalize the text for each category?

**Comment by fedde-s** [comment]
See #878 for a screenshot of the fix.

**Comment by fedde-s** [comment]
This has been improved upon in #1080 and merged into the release candidate.
