### ISSUE TITLE
HTML Validator:  Legend is missing

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#878]
In the current HTML validator, we seem to be using color coding, but we need a legend that explains what each color is, e.g. RED = ERROR, etc.

**Comment by fedde-s** [comment]
Added a legend in thehyve/cbioportal@17cadf5a6e8bd98b472cd7afd9f823d5884958ef

**Comment by fedde-s** [comment]
![screen shot 2016-03-18 at 17 25 19](https://cloud.githubusercontent.com/assets/4929431/13884542/bc8f58a8-ed2e-11e5-98f7-13be290c7b76.png)

**Comment by fedde-s** [comment]
Revised the phrasing as requested in issue #877:

![screenshot](https://cloud.githubusercontent.com/assets/4929431/14042501/becd27ac-f27a-11e5-94c5-393f07738811.png)

**Comment by fedde-s** [comment]
This has been improved upon in #1080 and merged into the release candidate.
