### ISSUE TITLE
buttons styling study view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8785]
- [x] select samples button slightly misaligned
- [x] structural variant should also have compare groups button (like mutations table)

**Comment by adamabeshouse** [comment]
what alignment is desired?

![image](https://user-images.githubusercontent.com/636232/128259318-4d800556-d02e-44bc-a035-3d0e89add8af.png)

**Comment by adamabeshouse** [comment]
Link to issue: https://www.cbioportal.org/study/summary?id=msk_impact_2017

![Screen Shot 2021-08-10 at 11.39.22 AM.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/25eb0eb6-f9bb-4193-b6b7-11efd0b31bfb)

left wrapping
right missing comparison
