### ISSUE TITLE
HTML Validator:  Line Numbers are missing

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#879]
We sometimes have missing line and column numbers, e.g.  

![screenshot_712](https://cloud.githubusercontent.com/assets/1009066/13415086/efca7d90-df25-11e5-84c4-b04c0c836c84.png)

This looks like an error.  But, it's not.  In cases where we are just reporting information, line and column numbers should be set to "--".

**Comment by fedde-s** [comment]
![screen shot 2016-03-18 at 17 25 19](https://cloud.githubusercontent.com/assets/4929431/13884542/bc8f58a8-ed2e-11e5-98f7-13be290c7b76.png)

**Comment by fedde-s** [comment]
This has been improved upon in #1080 and merged into the release candidate.
