### ISSUE TITLE
Mutations tab: issue with Download in MSK portal

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8794]
In this query (https://bit.ly/3iZuFMy), when I tried to download, it stuck on the screen below.

![image](https://user-images.githubusercontent.com/840895/127536012-32e01289-e539-465f-aef0-e92c480b1e2f.png)

There was some js error:

![image](https://user-images.githubusercontent.com/840895/127536107-5ed83bab-a282-411b-a061-ecd18a982bf1.png)

**Comment by adamabeshouse** [comment]
Looks like we're running into an issue with certain return types from the genomenexus API. It's expecting every VariantAnnotation to have an `annotation_summary` member, and it's getting an error when it doesn't. [This PR](https://github.com/cBioPortal/cbioportal-frontend/pull/3896) just handles that case gracefully. However there is still an error, though it doesn't prevent downloading:

![image](https://user-images.githubusercontent.com/636232/127906511-bc72fd37-dabd-4f55-b57a-429cee87ac42.png)
