### ISSUE TITLE
Fix broken study view test

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8805]
"when adding chart with categories more than the pie2Table threshold, the pie chart should be converted to table"

this test is failing pretty constistently

**Comment by inodb** [comment]
This is a bug that's showing up in many places - would be good to fix. Try e.g. going to https://www.cbioportal.org/study/summary?id=laml_tcga and adding "Other Sample ID"

**Comment by inodb** [comment]
I temporarily reverted PR that introduced the issue in a separate branch and deployed that https://github.com/cBioPortal/cbioportal-frontend/commit/1c6b3954f6e4498b0780ff239d25864b69fbe9c6

**Comment by dippindots** [comment]
**Here is what I found:**
We are trying to get clinical data counts from cache:
https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/pages/studyView/StudyViewPageStore.ts#L3709-L3714

But our cache is being populated at the same time in `newlyAddedUnfilteredClinicalDataCount `:
https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/pages/studyView/StudyViewPageStore.ts#L3569-L3576

**Tried but not working**
1.  Change `newlyAddedUnfilteredAttrsForNonNumerical` to from `@computed` to `RemoteData`
2. Move logic from `onResult` to `invoke`

**Comment by alisman** [comment]
@dippindots @kalletlak @adamabeshouse 
My guess is that this problem is a race condition which was somehow exposed by changes in @pvannierop's PR.  I can only reproduce it if I throttle my CPU (you can do it in performance panel of Chrome debugger).  

I was able to stop the problem by preventing [code from removing chart ](https://github.com/cBioPortal/cbioportal-frontend/pull/3911) from the newlyAddedChart collection from the onResults handler of various mobx promises.  Mutating the chart array (observable) appears to cause promises to re-invoke and resolve empty, which I think is why the chart goes empty.   I'm pretty sure this is an anti-pattern.   I.e. we should not be updating observable state from onResult.  So we should figure out whether we refactor the "newlyAdded" business logic to avoid doing this.  I'm not familiar enough why why we track newly added charts this way.
