### ISSUE TITLE
Adding hyperlinks for samples/patients in Clinical Data View

### ISSUE THREAD

**Issue by chenh4** [cBioPortal/cbioportal#881]
![screen shot 2016-03-01 at 10 53 02 am](https://cloud.githubusercontent.com/assets/11667643/13432755/f511c994-df9c-11e5-9451-3faee04fd0e7.png)

Hi Hongxin, can you add hyperlinks for samples/patients here to link to their individual sample/patient information as the old version? 

Thank you!

**Comment by zhx828** [comment]
@chenh4 could you take a look whether this function works properly in here: https://rc-881.herokuapp.com/study.do?cancer_study_id=acc_tcga#clinical Thanks.
