### ISSUE TITLE
Add Mass-Spec Proteomics Column to Datasets Page

### ISSUE THREAD

**Issue by cannin** [cBioPortal/cbioportal#8818]
Currently, it is difficult to identify datasets with proteomics information that is not RPPA. There are several datasets, such as CCLE and TCGA pan-cancer ovarian/breast, that have CPTAC mass-spec proteomics data. A new column on the Datasets page (https://www.cbioportal.org/datasets) would help identify them

**Comment by Sjoerd-van-Hagen** [comment]
@dianab0 can you check the effort to implement this? Sander will be able to help you understand what needs to be done.
