### ISSUE TITLE
Unable to load seed database

### ISSUE THREAD

**Issue by essiea** [cBioPortal/cbioportal#8835]
Having the following error when I try to manually upload seed.sql.gz to cbioportal mysql database; RROR 1054 (42S22) at line 275: Unknown column 'CYTOBAND' in 'field list

**Comment by dippindots** [comment]
@essiea please let us know if this is still an issue for you. You can reach out to us on Google group (cBioPortal for Cancer Genomics Discussion Group) if you still need help.
