### ISSUE TITLE
bug in import gistic_genes_amp and _del?

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#884]
Hi,

I was looking at "Select Genes from Recurrent CNAs (Gistic)" in the brca provisional on cbioportal.org 
I looked at the genes_in_region from the staging file data_gistic_genes_amp and compared it to the values given in the popup. 
For some it seems ok. For example, DDAH1 has a qvalue of 4.1251e-13
For others genes are missing. For example, for the qvalue 2.7818e-43 the popup says there are 0 genes. According to the file there is quite a list:
```
SNORA40|ENSG00000253047.1,RN7SL600P,RN7SL473P,C1orf138,LINC00568,CTSS,ECM1,ENSA,MCL1,RPRD2,ADAMTSL4,GOLPH3L,TARS2,HORMAD1,MIR4257,
```

We checked some other values, and it looks like it only add genes until it encounters the pipe symbol at which point it seems to fail?

**Comment by pieterlukasse** [comment]
@zheins , @n1zea144 could you please take a look at this and let us know what is the best way to fix this?
