### ISSUE TITLE
Fusion events not recognized as drivers in OncoPrint when using "DRIVER" in OQL

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#8855]
In this example, OQL should detect all fusions as drivers, but they are not shown in the OncoPrint. Maybe we forgot to update OQL to include the new fusions data type?

https://bit.ly/3yUQ8go

![image](https://user-images.githubusercontent.com/11892704/129787642-50793991-162b-4c32-bed5-2451ada6702f.png)

**Comment by inodb** [comment]
CC @zhx828 @kalletlak - any clue?

**Comment by zhx828** [comment]
@schultzn @inodb am I missing anything, it looks all driver to me.

**Comment by schultzn** [comment]
See the bottom 3 rows of the OncoPrint: the fusions are driver events but do not show up when using the OQL DRIVER command.
