### ISSUE TITLE
ERROR: -: Cancer type of study is neither known to the portal nor defined in a cancer_type file; value encountered: 'difg'

### ISSUE THREAD

**Issue by saimukund20** [cBioPortal/cbioportal#8887]
**_I am trying to load cbioportal on a gcloud instance. I am using the the cbioportal test dataset to load it initially. I ran these following steps_**
- git clone https://github.com/cBioPortal/cbioportal-docker-compose.git
- cd cbioportal-docker-compose
- ./init.sh
- docker-compose up
- docker-compose run cbioportal metaImport.py -u http://35.208.99.100:8080 -s study/lgg_ucsf_2014/ -o

**I get the following error while validating the input dataset. Can someone please help me rectify this error.**
Creating cbioportal-docker-compose_cbioportal_run ... done
Starting validation...
INFO: meta_clinical_patient.txt: Validation of meta file complete
INFO: meta_clinical_sample.txt: Validation of meta file complete
INFO: meta_mutations_extended.txt: Validation of meta file complete
INFO: meta_study.txt: Validation of meta file complete
INFO: meta_study.txt: No reference genome specified -- using default (hg19)
INFO: meta_timeline_specimen.txt: Validation of meta file complete
INFO: meta_timeline_status.txt: Validation of meta file complete
INFO: meta_timeline_surgery.txt: Validation of meta file complete
INFO: meta_timeline_treatment.txt: Validation of meta file complete
**_ERROR: -: Cancer type of study is neither known to the portal nor defined in a cancer_type file; value encountered: 'difg'_**
INFO: data_clinical_sample.txt: Validation of file complete
INFO: data_clinical_sample.txt: Read 66 lines. Lines with warning: 0. Lines with error: 0
INFO: case_lists/cases_sequenced.txt: Validation of meta file complete
INFO: case_lists/cases_all.txt: Validation of meta file complete
INFO: -: Validation of case list folder complete
WARNING: data_clinical_patient.txt: Columns DFS_MONTHS and/or DFS_STATUS not found. Disease free analysis feature will not be available for this study.
INFO: data_clinical_patient.txt: Validation of file complete
INFO: data_clinical_patient.txt: Read 28 lines. Lines with warning: 0. Lines with error: 0
WARNING: data_mutations_extended.txt: line 1: Including the SWISSPROT column is recommended to make sure that the UniProt canonical isoform is used when drawing Pfam domains in the mutations view
WARNING: data_mutations_extended.txt: lines [2, 3, 5, (10190 more)]: Gene symbol not known to the cBioPortal instance. This record will not be loaded.; values encountered: ['ANK2', 'ATRX', 'BDP1', '(6423 more)']
INFO: data_mutations_extended.txt: lines [4, 13, 19, (4957 more)]: Line will not be loaded due to the variant classification filter. Filtered types: [Silent, Intron, 3'UTR, 3'Flank, 5'UTR, 5'Flank, IGR, RNA]; values encountered: ['Silent', 'Intron', '5'Flank', '(4 more)']
WARNING: data_mutations_extended.txt: lines [10624, 14171]: Entrez gene id not known to the cBioPortal instance. This record will not be loaded. Might be new or deprecated Entrez gene id.; value encountered: '7006'
INFO: data_mutations_extended.txt: Validation of file complete
INFO: data_mutations_extended.txt: Read 15156 lines. Lines with warning: 10196. Lines with error: 0
INFO: data_timeline_specimen.txt: Validation of file complete
INFO: data_timeline_specimen.txt: Read 61 lines. Lines with warning: 0. Lines with error: 0
INFO: data_timeline_status.txt: Validation of file complete
INFO: data_timeline_status.txt: Read 42 lines. Lines with warning: 0. Lines with error: 0
INFO: data_timeline_surgery.txt: Validation of file complete
INFO: data_timeline_surgery.txt: Read 55 lines. Lines with warning: 0. Lines with error: 0
INFO: data_timeline_treatment.txt: Validation of file complete
INFO: data_timeline_treatment.txt: Read 21 lines. Lines with warning: 0. Lines with error: 0
INFO: -: Validation complete
#######################################################################
One or more errors reported above. Please fix your files accordingly
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: 1

_**The only funny part is when I do the same thing (start a cbioportal instance) on my local computer, it works perfectly fine without giving this error. Why does this error come when I run it on a virtual machine on a google cloud instance.?**_

**Comment by jjgao** [comment]
@saimukund20 sorry for not getting back to you earlier. If you still have the issue, please contact cbioportal@googlegroups.com.
