### ISSUE TITLE
MutationMapper document issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#891]
when I am uploading my list of mutations, the lollipops don’t generate unless the table has a minimum of 4 columns (with any headers). This is not what it says in the instructions which state that only the Hugo_Symbol and Protein_Change headers are required.

**Comment by onursumer** [comment]
I cannot reproduce this bug. The user input might have some invalid/incompatible values. For example, the input below works fine with the current standalone version.

Hugo_Symbol | Protein_Change
------------------- | ---------------------
AR | L729I
AR | R832*
AR | L185P
BRCA1 | Q1395fs
BRCA1 | E1345fs
BRCA1 | E116*
BRCA1 | C47W
