### ISSUE TITLE
downloading of mutations table not working for specific case

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8944]
https://cbioportal.mskcc.org/patient?studyId=mixed_cbe_kunga_AK_pedpdx&caseId=p_C_000733

Keeps hanging on "Downloading Table Data" modal

**Comment by jjgao** [comment]
saw an error message:
![image](https://user-images.githubusercontent.com/840895/137644352-709c0df9-2b14-49d3-bb1a-d93ab8295e10.png)
