### ISSUE TITLE
mutationfilter 5'Flank TERT

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#895]
The mutationfilter filters lots of mutations, which we now also skip in the validator to decrease the number of (in this case irrelevant) messages. The mutationfilter.java contains one exception for the filtering of the 5'Flank mutations: TERT

`whiteListGenesForPromoterMutations.add(Long.valueOf(7015)); // TERT`

```
if( safeStringTest( mutation.getMutationType(), "5'Flank" ) ) { 
   if (whiteListGenesForPromoterMutations.contains(mutation.getEntrezGeneId())){
      mutation.setProteinChange("Promoter");
   } else {
...
```

Note: the validator does **not** take TERT into account and skips validation of all 5'Flank mutations.

It may be better if this type of change happens is handled by e.g. vcf2maf?

**Comment by jjgao** [comment]
Just FYI -- we may want to import silent and non-coding mutations in the future.

**Comment by pieterlukasse** [comment]
@jjgao : thanks for the info. The important point to consider here is that such filtering would ideally be done by another script *before* validation and loading. Do you think we should add this to **vcf2maf** and then remove all filtering done in loading step?

**Comment by jjgao** [comment]
@pieterlukasse I don't think we can add the filtering to vcf2maf. vcf2maf should not be limited to non-silent mutations.

**Comment by jjgao** [comment]
@aderidder @pieterlukasse: maybe we don't have to worry about filtering by mutation type in the validator, because we are likely to import all mutations into our database in the future.

**Comment by pieterlukasse** [comment]
@jjgao: the problem is that too many records currently don't comply with the rules we discussed in #806... these issues would have to be solved first, otherwise you will be importing mutation records that are not usable since they lack basic information, right?
