### ISSUE TITLE
Timeline: add black dot for status=deceased event in status track

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8973]
For track type STATUS, when we detect an attribute with key=status and value=deceased (both case INSENITIVE), lets display it as a black diamond. 

this patient has such an event:
https://www.cbioportal.org/patient?studyId=gbm_columbia_2019&caseId=gbm_columbia_2019_100

**Comment by jjgao** [comment]
I am not sure if we hsould do this. I think it's better to add the survival data into timeline data manually... (one reason is that the survival data and timeline data may have different time 0)
