### ISSUE TITLE
validator Info level does not collapse messages

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#900]
When running the validator with -v, the generated info messages are not collapsed:
![image](https://cloud.githubusercontent.com/assets/9414840/13571143/48891930-e473-11e5-9276-eca4aebe0590.png)

**Comment by fedde-s** [comment]
I intended the use of `INFO` messages for status updates on what the validator is doing, to be flushed immediately without waiting for collapsing. These messages may be better classified as `DEBUG`, especially if there is now a reason for a level of messages about the data lower than `WARNING`.

**Comment by jjgao** [comment]
Has this been fixed?

**Comment by fedde-s** [comment]
Yes, this has been addressed back in commit 6740d908c02ac5497bd7d67555059758e3d3ad84, in the way I suggested in [my comment above](https://github.com/cBioPortal/cbioportal/issues/900#issuecomment-194305025).
