### ISSUE TITLE
importing into public DB failed on mutation profile

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#9022]
Studies failed importing to public DB on mutation profiles:

Rob listed possible cause:
- New row for `data_mutations.txt` is added in the wrong place in configuration sheet `datatype` tab. (was at the last and after fusion type)

**Comment by sheridancbio** [comment]
mutation row was repositioned and import of the 6 studies was restarted

**Comment by sheridancbio** [comment]
Import took a long time (11 hours) due to the presence of a generic assay profile in study gbm_cptac_2021, but the imports completed successfully.
