### ISSUE TITLE
calling cbioportalImporter.py to import cancer-type gives an error

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#903]
For the manual I was testing the import-cancer-type command, which gives an error:

```
./cbioportalImporter.py -c import-cancer-type -meta /vagrant/smallStudy/meta_cancer_type.txt
/app/portal/target/portal/WEB-INF/lib/core-1.1.0-SNAPSHOT.jar

Exception in thread "main" java.io.IOException: Cancer type file '/vagrant/smallStudy/meta_cancer_type.txt' is not a five-column tab-delimited file
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.load(ImportTypesOfCancers.java:72)
at org.mskcc.cbio.portal.scripts.ImportTypesOfCancers.main(ImportTypesOfCancers.java:60)
```

It does not seem to be using the data file specified in the meta file

**Comment by fedde-s** [comment]
This is specific for the single-file CLI and does not occur when loading a study at once: I did not change the old command when the cancer type file got its own key-value metadata file for consistency. This interface still expects the cancer type file itself to be supplied as the 'meta file'.

**Comment by jjgao** [comment]
Should this remain open?

**Comment by fedde-s** [comment]
I don't think this it does, as it is an issue with the documentation or naming of a command that has been [deprecated](https://github.com/cBioPortal/cbioportal/blob/master/docs/Importer-Tool.md) over 1½ years ago. @aderidder, please reopen if you disagree.
