### ISSUE TITLE
Why loading meta data of all studies in single study view page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#9039]
https://www.cbioportal.org/study/summary?id=msk_impact_2017

![image](https://user-images.githubusercontent.com/840895/140992683-7053e77e-658f-4610-8c9e-1153cf76d607.png)

**Comment by alisman** [comment]
@jjgao at minimum we are using physical study list to identify virtual studies.  if there is an id which is NOT in the list of studies, we check if it's a virtual study.
