### ISSUE TITLE
jQuery and Bootstrap security issues, outdated versions 

### ISSUE THREAD

**Issue by mike-gabriel-fci** [cBioPortal/cbioportal#9040]
Our security scans detected medium vonerabilites for jqery and bootsrap libraries related to outdated versions. I have attached screenshots from the scan for more details. 
Looks like the issue is related to files below: 
../reactapp/prefixed-bootsrap-min.css
../reactapp/common.bundle.js

![react_bootstrap](https://user-images.githubusercontent.com/44902131/141213006-96cab850-7c2a-4bf0-bf23-832054207027.png)
![react_jquery](https://user-images.githubusercontent.com/44902131/141213009-c43102aa-d17b-45e3-b407-4563b4307c26.png)

**Comment by alisman** [comment]
Hi Mike,

We will upgrade.   Should be in  v3.7.15 in a couple weeks.  I will let you
know.

--Aaron
