### ISSUE TITLE
Change whiskers in new Plotly plots

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#905]
Can we change the whiskers in the new Plotly RNA-Seq plots? It looks like they indicate the max and min, which is not too useful, since all data points are visible. Does Plotly offer other options here? It would be nice if we could make them look like the old plots.

![image](https://cloud.githubusercontent.com/assets/11892704/13617260/d1ccf2c4-e54b-11e5-80e6-17831bef89fb.png)

**Comment by yichaoS** [comment]
You are right. I just found out they do have this option and changed it. This is how it looks now.
![screen shot 2016-03-08 at 5 07 10 pm](https://cloud.githubusercontent.com/assets/5973438/13618145/757bf6c8-e550-11e5-9612-7679d3f38cd8.png)
