### ISSUE TITLE
cbioportal and session docker Image, mysql db schema file, and seed data file version deployment matrix

### ISSUE THREAD

**Issue by kronik22** [cBioPortal/cbioportal#9057]
I have deployed cbioportal by creating a Kubernetes derivative of the cbioportal-docker-compose files. I am at a stage where I would like to test out the newer releases of the cbioportal images; however, there is no matrix that I can find which shows the cbioportal docker image version, cbioportal docker session image version, cgds.sql file version, and seed.sql.gz version that are compatible together for a stable deployment.

I attempted to update my deployment with cbioportal/cbioportal:3.7.9, cbioportal/session-service:0.5.0, and database version v2.12.8 as per the cbioportal-docker-compose latest release. However, I get an error for a missing db field value which I found in the db migration.sql for db version v2.12.10. The missing field causes the gene query to fail for the "Select Genomic Profiles" which I suspect is not working in the cbioportal-docker-compose latest release.

So, if you are able to share a deployment matrix for the cbioportal docker image, session docker image, database schema, and database seed versions which work together with hyperlinks to the appropriate file releases it would be greatly appreciated. Otherwise, i have to deep dive into the repo code in order to figure out which version work together and usually some trial and error. This kind of information is usually found in a support/deployment matrix.

**Comment by kronik22** [comment]
I was able to get it to work by updating the database to 2.12.10, but i had to delete the **SAMPLE** table foreign key for the **TYPE_OF_CANCER_ID** column so that i could run the migrate_db.py with a modified migration.sql file that only contained the 2.12.9 and 2.12.10 sql database updates.

The deployment matrix would still be helpful so that one knows the compatibility of the db version with the cbioportal front end and the session versions.

**Comment by inodb** [comment]
@kronik22 Thanks for reaching out and good point - we don't really have such a matrix. Unf it might not be that straightforward to reconstruct. Best bet is to use whatever is here https://github.com/cBioPortal/cbioportal-docker-compose/blob/master/docker-compose.yml. That is usually the latest stable version. Hope that helps!
