### ISSUE TITLE
"Comparison/Survival" (comparison) tab excluded from disabled_tabs option

### ISSUE THREAD

**Issue by AHTARazzak** [cBioPortal/cbioportal#9064]
Of possible values (and their corresponding tabs) which can be disabled within portal.properties to hide within CBP GUI the comparison tab is not listed as a possible value nor can it be disabled if "comparison" is added to disabled_tabs.

**Comment by pvannierop** [comment]
@alisman We are looking into this problem and will propose a fix.

**Comment by AHTARazzak** [comment]
As of version 3.7.21 the comparison tab can now be configured.
