### ISSUE TITLE
Oncoprint GUI renders as white screen if oncokb.hotspots.default is set to false

### ISSUE THREAD

**Issue by AHTARazzak** [cBioPortal/cbioportal#9065]
Within the portal.properties if oncoprint.hot.spots.default is set to false the oncoprint window renders as  a blank page.

**Comment by inodb** [comment]
@AHTARazzak we will try to address this in January if that works for you, thanks for reporting!

**Comment by adamabeshouse** [comment]
I'm sorry @AHTARazzak I was not able to reproduce this.
