### ISSUE TITLE
Mutation table download file does not include OncoKB resistance info

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#9067]
For instance for the EGFR in the MSK IMPACT study, for all T790M alterations, the download file should have R1 info in the annotation column. 
https://www.cbioportal.org/results/mutations?cancer_study_list=msk_impact_2017&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Ccna&case_set_id=msk_impact_2017_cnaseq&gene_list=EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit

**Comment by jjgao** [comment]
@leexgh @onursumer could you help with this?
