### ISSUE TITLE
metaImport.py expects jar file

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#907]
While testing metaImport, I encountered the following issue. When running:
`./metaImport.py -s /vagrant/smallStudy -u http://localhost:8080/cbioportal -html myReport.html -v`

I get the following error:

```
usage: metaImport.py [-h] -s STUDY_DIRECTORY
                     [-u URL_SERVER | -p PORTAL_INFO_DIR] -jar JAR_PATH
                     [-html HTML_TABLE] [-v] [-o]
metaImport.py: error: argument -jar/--jar_path is required
```

As I have my PORTAL_HOME set, shouldn't it be able to find the jar file? (cf validataData.py)

**Comment by jjgao** [comment]
Should this remain open?

**Comment by jjgao** [comment]
@aderidder ?

**Comment by aderidder** [comment]
Hi JJ, 
So... I haven't a clue, as I haven't done any cbioportal development in a long time. 
@pieterlukasse ?
