### ISSUE TITLE
metaImport type of cancer exception

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#908]
My test has a new type of cancer. By now, however it does exist in the database. Running metaImport.py:

> Everything looks good. Importing study now
> 
> Exception in thread "main" org.mskcc.cbio.portal.dao.DaoException: Duplicate entry 'crc' for key 'PRIMARY'
> at org.mskcc.cbio.portal.dao.DaoTypeOfCancer.addTypeOfCancer(DaoTypeOfCancer.java:68)

Perhaps the validator should check whether the cancer type exists and give an error?

**Comment by jjgao** [comment]
Should this remain open?

**Comment by jjgao** [comment]
@aderidder ?

**Comment by aderidder** [comment]
Hi JJ, 
So... I haven't a clue, as I haven't done any cbioportal development in a long time. 
@pieterlukasse ?
