### ISSUE TITLE
user reported: comparison page error, will not load

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9084]
User reported: https://groups.google.com/g/cbioportal/c/lDIpbTnk2JA

Comparison page fails to load:
https://www.cbioportal.org/comparison/alterations?comparisonId=61a12cf9f8f71021ce576cb2&unselectedGroups=%5B%5D
Console error:
![image](https://user-images.githubusercontent.com/10508276/144313746-c87947db-c0e8-47e2-91ae-0741a3b5d7d8.png)

**Comment by tmazor** [comment]
Another user reported what looks like the same bug: https://groups.google.com/g/cbioportal/c/m15MkeB8k24
https://www.cbioportal.org/comparison/alterations?comparisonId=61a84842f8f71021ce578c5c

**Comment by alisman** [comment]
https://sentry.io/organizations/memorial-sloan-kettering/issues/2829185385/?project=236782&query=is%3Aunresolved++NotPositiveException&statsPeriod=14d

**Comment by dippindots** [comment]
@tmazor @alisman This issue is solved. Also notified these two users by email.
