### ISSUE TITLE
move DB vs portal version check in cbioImporter.py to the Java layer

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#910]
In current rc branch the DB vs portal version check was introduced (by #700). The check is a good thing to do, but it should be implemented in the Java layer. Currently it is implemented twice: in the portal Java code (see https://github.com/cBioPortal/cbioportal/blob/rc/core/src/main/java/org/mskcc/cbio/portal/servlet/QueryBuilder.java#L260) and the cbioImporter.py code (see https://github.com/cBioPortal/cbioportal/blob/rc/core/src/main/scripts/cbioportalImporter.py#L170). The python implementation introduces a dependency on an extra .properties file and a python mysql library which would both not be necessary if the python script would do the check by calling a Java class to check this.

**Comment by pieterlukasse** [comment]
The best solution would be 
1- to move the check that now occurs in https://github.com/cBioPortal/cbioportal/blob/rc/core/src/main/java/org/mskcc/cbio/portal/servlet/QueryBuilder.java#L260) to a place as deep as possible, like https://github.com/cBioPortal/cbioportal/blob/rc/core/src/main/java/org/mskcc/cbio/portal/dao/JdbcUtil.java#L105
2- write a java wrapper script that calls this same check (to be) done in JdbcUtil.java and call this new java class from cbioImporter.py to check the version compatibility (in this way the call to this java class can be done just like the calls to the various Import*.java classes is done).

:warning: Important request: *please* do this in a branch from our validator improvements branch (https://github.com/thehyve/cbioportal/tree/validator_and_loading_improvements). This is important to make later merging with rc easier (one reason is that we moved the cbioImporter.py file to a new location in this branch).

**Comment by pieterlukasse** [comment]
hi @jjgao , as discussed today I made the issue (and a solution proposal). Could you please check this with @zheins ? Thanks for your support!

**Comment by zheins** [comment]
PR associated with this in the hyve fork.
