### ISSUE TITLE
Downloading Table Data...broken

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#9104]
A [google group user](https://groups.google.com/g/cbioportal/c/PgBrAMIOTP4) is having an issue downloading mutation table data.  After executing the following steps, the page sits on "Downloading Table Data..." without ever completing.

```
select "TCGA PanCancer Atlas Studies"
query "CYSLTR2"
submit query
switch to Mutations tab (there are now 90 mutations)
click the "cloud arrow" download button labeled "Download TSV"
```

After a quick look at the browser debugging, a call to v1.genomenexus.org/annotation never completes, which may be the culprit:
![image](https://user-images.githubusercontent.com/366003/145494963-cb4c0a9e-c49b-456f-aea2-8af5ada24175.png)

Update - after about 10 minutes, the download does complete, but with a "Download Error!" modal dialog.  The file does seem to have the correct number of rows.

![image](https://user-images.githubusercontent.com/366003/145495756-12f57394-143e-4ffe-a696-d9cc4399e529.png)

**Comment by onursumer** [comment]
Looks like the problem is that we query Genome Nexus for the mutation assessor data which is very slow. We should probably disable mutation assessor annotation in cBioPortal until we find a better solution.

**Comment by onursumer** [comment]
This seems to be fixed after disabling mutation assessor for the public cBioPortal
