### ISSUE TITLE
Detect data which is all numbers and assign it the 'number' datatype

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#912]
Some clinical attributes, for example CRDB_OFF_STUDY_DAYS, are marked as the 'string' datatype, but are actually all numbers (or not available). Is it possible to detect this and mark the datatype as 'number' instead? 

It would be helpful in the oncoprint, because right now it's seeing the 'string' datatype annotation and displaying these tracks as categorical type using hundreds of discrete categories, one for each number value, but instead we could display it as a bar chart.

**Comment by jjgao** [comment]
@n1zea144 @sheridancbio do you know if this has been implemented?

**Comment by jjgao** [comment]
@n1zea144 @sheridancbio ?

**Comment by adamabeshouse** [comment]
I still think this would be good. thoughts?

**Comment by jjgao** [comment]
Maybe instead of detecting and converting them in importer, we should detect them in the validator and output a warning?

@ritikakundra @rmadupuri thoughts?

**Comment by ritikakundra** [comment]
@jjgao validator already catches that.

**Comment by jjgao** [comment]
@ritikakundra thanks!
