### ISSUE TITLE
Study View : javascript SVG manipulation warning

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#915]
on page: http://www.cbioportal.org/study.do?cancer_study_id=brca_tcga#summary

While navigating the lower tabs (click "Clinical Data" then "Study Summary") the browser javascript console shows warnings such as:
'SVGElement.offsetWidth' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.

This suggests proper rendering may break in the next few weeks. This effect may occur elsewhere across web pages.

**Comment by zhx828** [comment]
This issue should be solved in https://github.com/cBioPortal/cbioportal/pull/1405
