### ISSUE TITLE
Optimizing dropdown menu for generic assays

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#9155]
When there are many entities, the dropdown menus to select one (e.g. in study view, oncoprint, plots tab) are slow. 

https://www.cbioportal.org/study/summary?id=gbm_cptac_2021

![image](https://user-images.githubusercontent.com/840895/147100127-7e3fcfc2-324b-4f67-b661-edd3ceb21789.png)

A related user question: https://groups.google.com/g/cbioportal/c/vfKAjNH6va4/m/_pdVDy97EwAJ?utm_medium=email&utm_source=footer

We also plan to use generic assays for hosting the prob-level methylation data, which may contain up to 100k entries.

A couple of ideas/options:
- Anyway to improve the responsiveness of the dropdown? Currently both selection and scrolling are slow.
- Don't load all entries by default
- Only load a subset, e.g. methylation probs or phosphoproteomics data that are associated with the query genes, or the ones chosen by the user previously (saved in local storage)
- Allow search (a search API is needed) - any only return part of the results, e.g. top 100

**Comment by dippindots** [comment]
Related ticket: https://github.com/cBioPortal/cbioportal/issues/8729

**Comment by dippindots** [comment]
@jjgao I think I can try the first option: `Improve the responsiveness of the dropdown`, I found some solutions that can improve select component performance. I can give them a try, what do you think? Or if you prefer other options, I can try one of those too.
