### ISSUE TITLE
remove interaction table

### ISSUE THREAD

**Issue by jagnathan** [cBioPortal/cbioportal#9191]
remove interaction table and dependencies

sql files

- [x] core/src/test/resources/seed_mini.sql
- [x] db-scripts/src/main/resources/cgds.sql
- [x] db-scripts/src/main/resources/migration.sql

Java files

- [x] core/src/main/java/org/mskcc/cbio/portal/dao/DaoInteraction.java
- [x] core/src/test/java/org/mskcc/cbio/portal/dao/TestDaoInteraction.java
- [x] core/src/main/java/org/mskcc/cbio/portal/network/NetworkIO.java
- [x] core/src/main/java/org/mskcc/cbio/portal/graph/NetworkOfInterest.java
- [x] core/src/test/java/org/mskcc/cbio/portal/graph/TestNetworkOfInterest.java
- [x] core/src/main/java/org/mskcc/cbio/portal/scripts/ImportSif.java
- [x] core/src/main/java/org/mskcc/cbio/portal/scripts/ImportPathwayCommonsExtSif.java
- [x] core/src/main/java/org/mskcc/cbio/portal/scripts/ResetDatabase.java
- [x] core/src/main/java/org/mskcc/cbio/portal/scripts/ImportHprd.java
- [x] core/src/main/java/org/mskcc/cbio/portal/scripts/drug/AbstractDrugInfoImporter.java
- [x] core/src/main/java/org/mskcc/cbio/portal/scripts/drug/internal/PiHelperImporter.java

**Comment by inodb** [comment]
merged in release-4.0.0
