### ISSUE TITLE
study summary page (clinical tab): round TMB scores

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#9196]
Round TMB scores displayed to 2 significant digits. 
Example: "TMB field" in https://www.cbioportal.org/study/clinicalData?id=gbm_cptac_2021
![image](https://user-images.githubusercontent.com/5973438/148848583-e8066e68-2d83-438a-9991-bd9454b722d7.png)
This is to fix issue mentioned in review of PR https://github.com/cBioPortal/cbioportal/pull/9176 
"the significant digits is not consistent across the computed TMB values (at least in the example). Also is it necessary to have some many significant digits in the TMB value? A quick check of the impact clinical sample data file, it seems like the clinical impact tmb is rounded to 2 significant digits."

**Comment by jjgao** [comment]
We can generalize the solution and reduce # of digits in the whole table...
