### ISSUE TITLE
frontend repo size too large for jitpack

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9199]
Jitpack can't build anymore (https://jitpack.io/com/github/cbioportal/cbioportal-frontend/v3.7.23/build.log):

> Git error. Retrying.
Git error. Max repo size 500MB exceeded

Our current repo size is >1GiB:

```
$ git count-objects -vH
count: 2258
size: 27.49 MiB
in-pack: 399634
packs: 29
size-pack: 1.12 GiB
prune-packable: 282
garbage: 0
size-garbage: 0 bytes
```

Let's find out some way to make it smaller:

- [x] delete branches that are no longer used
- [x] remove previous screenshots from history

Alternatively we can change jitpack's checkout:

- [x] there is a custom build command (didn't work, jitpack uses the github api to determine repo size before cloning)

**Update**: I have been able to reduce the repo size from >1GB to <70MB doing this:

```
bfg --delete-files *.png
bfg --strip-blobs-bigger-than 1M
```

This will however require to force push to the main repo and will change all commit ids. Rebasing PRs is not too tricky though. First squash your PR. Then you can do this:

```
git fetch origin # if origin points to the main fork
git checkout origin/master -b my-feature-branch-rebased
git cherry-pick cad5809388a91580c1cfb31c1bd638b4f16aa8f1 # hash of your squashed commit from your feature branch
```

**Comment by zhx828** [comment]
I recently used https://github.com/newren/git-filter-repo. Another option if you want to clean up the history.
