### ISSUE TITLE
Team sections on About tab are out of date

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/cbioportal#921]

**Comment by sheridancbio** [comment]
Need to add and adjust to make current to all centers. Other updates may be needed on page.

**Comment by ecerami** [comment]
@schultzn @sheridancbio:  just checking if this is now done?  can we close?  tx.

**Comment by sheridancbio** [comment]
Yes, this was completed. Niki made the update a long time ago --- so possibly it is time again for a review / update now. I think we do have new team members since the update. Niki updated the github wiki page last time, but I think we have a new protocol for making updates to these pages (rather than direct edits on the wiki page)  But I'll close this issue now, and mention that we might want to do another update soon during an upcoming group meeting.
