### ISSUE TITLE
Cross Cancer Tab, x-labels get truncated

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#922]
x-labels get truncated...

![screenshot_767](https://cloud.githubusercontent.com/assets/1009066/13731548/4dff86f0-e942-11e5-846c-5bebd0d4a501.png)

**Comment by aderidder** [comment]
Hi @ecerami, 
I've added some code which changes the left padding and the height based on the length of the text. It now looks like this if you have a very long cancer type:
![image](https://cloud.githubusercontent.com/assets/9414840/13746396/98e61de4-e9f3-11e5-95c1-b238e67ffa91.png)

Is this ok?

**Comment by ecerami** [comment]
thanks @aderidder.  looks much better!

**Comment by pieterlukasse** [comment]
It also happens in the regular multi-study cross-cancer histogram (see screenshot). 
Maybe @JiaoJiao123 can apply the same fix there since she is working on #802 ? 

![image](https://cloud.githubusercontent.com/assets/2900303/13807062/84371192-eb5f-11e5-85e1-50fa2455cde7.png)

**Comment by JiaoJiao123** [comment]
@pieterlukasse 
Thank you for letting me know. I will fix it on my pull request
