### ISSUE TITLE
renaming "Log Ratio" to "Log2 Ratio"

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#9227]
https://www.cbioportal.org/comparison/mutations?sessionId=5cf89323e4b0ab413787436c

![image](https://user-images.githubusercontent.com/840895/149595006-8fc27bd4-bb25-40d2-936d-ab70f978752a.png)

**Comment by AkashKalala** [comment]
opened a PR for this in cbioportal-frontend.

https://github.com/cBioPortal/cbioportal-frontend/pull/4221

**Comment by aaryahjolia** [comment]
Is this issue still open? If yes, I guess the graph code is modified because it is different from the image attached.
What should I do next?

**Comment by jjgao** [comment]
fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/4221
