### ISSUE TITLE
comparison overlap chart won't download as PDF

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9251]
user reported: https://groups.google.com/g/cbioportal/c/ocqrg9iNmEI

Downloading as SVG works, but PDF fails
https://www.cbioportal.org/comparison?comparisonId=61c194bef8f71021ce57f32f

Error in console:
![image](https://user-images.githubusercontent.com/10508276/151007135-83834d20-607c-455f-ae8a-f141e052352a.png)

**Comment by jfkonecn** [comment]
I made a PR to fix this in the [svg2pdf.js](https://github.com/cBioPortal/svg2pdf.js) repo
