### ISSUE TITLE
Methylation Generic Assay Enhancement

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#9253]
These are the updates needed, for adding methylation data to TCGA pan-can studies, as generic assay

TODO items listed below, are from testings and comments of https://github.com/cBioPortal/datahub/pull/1582

- Oncoprint 
   - [x] show the full probe ID in the tooltip when hovering over the gene symbol
   - [x] populate the dropdown with just the probes that belongs to the query genes
- plots tab
   - [x] dropdown menu title change to "Gene / Probe"
   - [x] select the first probe from the gene that matches what's on the other axis.
   - [x] bring all probes related queried genes to the front in dropdown 
- dropdown menu performance issue:
   - [x] improving loading speed
   - [x] add some kind of loading / spinning indicator to let the user know that something is happening
- [x] generic assay entities were NOT deleted from Database after corresponding studies were removed. 
- [x] combined studies summary view: entities from different studies but with the same stable_ID are loaded twice in summary view "add chart" dropdown (see screenshot)
![image](https://user-images.githubusercontent.com/5973438/151062867-16b5193d-3f0c-49e0-bdba-5a73667b9f2a.png)

**Tali's comments:**

- [x] In Charts/Add Tracks menus, change text 'Search for Methylations' to 'Search for gene/probe'

![image](https://user-images.githubusercontent.com/10508276/151068164-bc348660-29c4-4e20-96af-23606f29ec18.png)

- [x] Remove duplicates in the gene regions (eg just show Body once per probe).

![image](https://user-images.githubusercontent.com/10508276/151068555-babdf6a2-a493-4cee-8021-bed22e44c680.png)

- [ ] What annotations are the basis of the gene regions? I was assuming it's the Illumina-provided annotations, but if I take cg07054526 (which shows up above as NA), and look it up in the file I downloaded from Illumina's website, it's annotated as Body/5'UTR.

- [x] Change the methylation tracks to use light blue (low methylation) to dark blue (high methylation).

![image](https://user-images.githubusercontent.com/10508276/151070779-4cd0d207-fdc8-4cf3-a00e-c3398236f7dd.png)

- [x] General thought for the future: can we add a way to remove multiple tracks at once from OncoPrint? I added a bunch of DNA methylation tracks, and then wanted to get rid of them, but the only way to do that is to delete them one-by-one -- which is tedious and slow, especially because OncoPrint has to reload after each deletion.

- [ ] (bug) after deleting the last track as described above, all the tracks returned. 

![Jan-25-2022 17-41-38](https://user-images.githubusercontent.com/10508276/151071968-a63be659-307b-41f9-87dd-f61c65d825ce.gif)

**Comment by dippindots** [comment]
Adding @tmazor's comment to this ticket: https://github.com/cBioPortal/datahub/pull/1582#issuecomment-1021681013

**Comment by dippindots** [comment]
Feedback from demo session:

**Global:**
- [ ] Rename tab name to `Methylation`
- [ ] Still show `Search for Gene / Probe` in the search placeholder

**OncoPrint**
- [ ] Oncoprint search enable search the whole options set, brings related/queried options to the front

**Comparison tab**
- [ ] Use Gene and Probe name on yaxis of chart, table and tooltip
- [ ] Entity Name in table header should be dynamic (Gene/Probe)
