### ISSUE TITLE
remove EXONIC_LENGTH in reference_genome_gene

### ISSUE THREAD

**Issue by jagnathan** [cBioPortal/cbioportal#9257]
remove EXONIC_LENGTH in reference_genome_gene

SQL files

- [x] cgds.sql
- [x] migration.sql
- [x] cgds-test.sql
- [x] seed_mini.sql
- [x] persistence/persistence-mybatis/src/test/resources/testSql.sql

Java Files

- [x] core/src/main/java/org/mskcc/cbio/portal/dao/DaoReferenceGenomeGene.java
- [x] core/src/main/java/org/mskcc/cbio/portal/model/ReferenceGenomeGene.java
- [x] core/src/main/java/org/mskcc/cbio/portal/scripts/ImportGeneData.java
- [x] model/src/main/java/org/cbioportal/model/ReferenceGenomeGene.java
- [x] persistence/persistence-mybatis/src/test/java/org/cbioportal/persistence/mybatis/DiscreteCopyNumberMyBatisRepositoryTest.java
- [x] web/src/test/java/org/cbioportal/web/ReferenceGenomeGeneControllerTest.java

Other files

- [x] persistence/persistence-mybatis/src/main/resources/org/cbioportal/persistence/mybatis/ReferenceGenomeGeneMapper.xml
- [x] docs/Updating-gene-and-gene_alias-tables.md
- [x] pom.xml

**Comment by inodb** [comment]
merged in release-4.0.0
