### ISSUE TITLE
Study view user selected filter is not always accurate

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#9266]
In study view, the displayed value for the selected filter at the top of the page is not always correct with respect to the actual filter state. For example see the bar chart selection and the mutation count filter displayed at the top.

Bar chart selection:
<img width="402" alt="BarChartSelection" src="https://user-images.githubusercontent.com/3604198/151547754-d3b321e4-7086-4eab-866f-ba09a21481ac.png">

User selection displayed at the top of the page:
<img width="545" alt="UserSelections" src="https://user-images.githubusercontent.com/3604198/151547799-70e90884-cc87-48a5-b1e9-1d7ad1abc169.png">

Here we should display `≥14` instead of `>14`.

**Comment by aswin2108** [comment]
@onursumer is this issue still open? I would like to work on this issue, can you assign this issue to me?
