### ISSUE TITLE
SV Conversion issues

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9267]
We should check:

- Group Comparison
  - Alterations Tab (SV selection) PROBLEM IDENTIFIED
  
- Results View 
  - Mutual Exclusivivity PROBLEM FIXED
  - Plots tab Discrepancy 
  - Does grouping work when making a group based on SVs. This happens in Results View altered vs unaltered.
  - As well as when you make a track with multiple genes in Oncoprint.   [SEEMS TO WORK FINE](https://www.cbioportal.org/results/oncoprint?cancer_study_list=msk_impact_2017&tab_index=tab_visualize&case_set_id=msk_impact_2017_all&Action=Submit&gene_list=%255BTMPRSS2%2520ERG%255D&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&geneset_list=%20)
- Study View
  - Make groups based on SV table. SEEMS TO WORK EXCEPT FOR SLIGHT COUNT DISCREP SAME AS GENE TABLE
- Downloads
  - Download of OncoPrint DIFFED OUTPUT OF TSVs MATCHED
  - Downloads Tab SV Data
- Tools
  - OncoPrinter Tool (how do you submit SVs?)
  - MutationMapper Tool does not really need SVs, but should confirm it doesn't break either

TODO:

- [x] Need to add `SV Status` column to SV table in frontend for indicating germline
    - [x] sort out typing issue

**Comment by adamabeshouse** [comment]
Looks like the endpoint is not returning any structural variants:

![image](https://user-images.githubusercontent.com/636232/153236335-8ce6ce4e-40e5-4f57-a6eb-889ab23defb9.png)

![image](https://user-images.githubusercontent.com/636232/153236368-d146d6a2-d89f-4470-9bd6-5494f999f4d8.png)

**Comment by alisman** [comment]
NEW:
![image](https://user-images.githubusercontent.com/186521/156621863-64211b17-e4dc-46d5-be28-9bf7bbec09ac.png)

OLD:
![image](https://user-images.githubusercontent.com/186521/156621972-73ba7d38-0d5d-4359-95f2-a81c621564f2.png)
