### ISSUE TITLE
Mismatch between cross-cancer histogram and related oncoprint when using OQL

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#929]
When using OQL expressions in a query over multiple studies the cross-cancer histogram, the mutation view and the linked-out oncoprint all show different results. 

**_Example1:**_
- in query select  "Colorectal Adenocarcinoma (TCGA, Provisional)" and "Colorectal Adenocarcinoma (TCGA, Nature 2012)"
- in genes box set: `KRAS: MUT`

You will get the following:
- in cross-cancer histogram there are 95 + 90 mutated cases (Screenshot1)
- in mutations tab there are 185 mutations in the table, but only 67+10+1+2+2+1+1+2+9=95 in lollipop view (so only first study?) (Screenshot2)
- in oncoprint linked out from histogram (when clicking ["click to view details" link](http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_cna_seq&case_ids=&gene_list=KRAS:%20MUT&gene_set_choice=user-defined-list&Action=Submit)) there are 95 and 90 cases

**_Example2:**_
- in query select  "Colorectal Adenocarcinoma (TCGA, Provisional)" and "Colorectal Adenocarcinoma (TCGA, Nature 2012)"
- in genes box set: `KRAS: MUT=G12`

You will get the following:
- in cross-cancer histogram there are 67 + 62 mutated cases 
- in mutations tab there are 185 mutations in the table, but only 67+10+1+2+2+1+1+2+9=95 in lollipop view (**so only first study  in lollipop and no OQL filtering applied?**) 
- in oncoprint linked out from histogram (when clicking ["click to view details" link](http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_cna_seq&case_ids=&gene_list=KRAS:%20MUT=G12&gene_set_choice=user-defined-list&Action=Submit)) there are 67 and 62 cases

**_Example3:**_
- in query select  "Colorectal Adenocarcinoma (TCGA, Provisional)" and "Colorectal Adenocarcinoma (TCGA, Nature 2012)"
- in genes box set: `KRAS: MUT!=G12`  (**notice the != here**)

You will get the following:
- in cross-cancer histogram there are **still** 67 + 62 mutated cases (**which is wrong as this is the same as for =G12**)
- in mutations tab there are 185 mutations in the table, but only 67+10+1+2+2+1+1+2+9=95 in lollipop view (**so only first study in lollipop and no OQL filtering applied?**) 
- in oncoprint linked out from histogram (when clicking ["click to view details" link](http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_cna_seq&case_ids=&gene_list=KRAS:%20MUT!=G12&gene_set_choice=user-defined-list&Action=Submit)) there are 28 and 28 cases (screenshot3)

**_Example4:**_
- in query select  "Colorectal Adenocarcinoma (TCGA, Provisional)" and "Colorectal Adenocarcinoma (TCGA, Nature 2012)"
- in genes box set: `KRAS: MUT=G12; KRAS:MUT=G13`  

You will get the following:
- in cross-cancer histogram there are **still** 67 + 62 mutated cases (**which is wrong as this is the same as for =G12**)
- in oncoprint linked out from histogram (when clicking ["click to view details" link](http://www.cbioportal.org/index.do?tab_index=tab_visualize&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_cna_seq&case_ids=&gene_list=KRAS:%20MUT=G12;%20KRAS:%20MUT=G13%20%20%20%20&gene_set_choice=user-defined-list&Action=Submit)) there are 0 and 0 cases on 2 oncoprint lanes

Screenshot1:
![image](https://cloud.githubusercontent.com/assets/2900303/13785151/a43dcf22-ead2-11e5-90ca-1b1fa182ea72.png)

Screenshot2:
![image](https://cloud.githubusercontent.com/assets/2900303/13785116/6e28d0c6-ead2-11e5-8440-e034f32ee14f.png)

Screenshot3:
![image](https://cloud.githubusercontent.com/assets/2900303/13785736/fb5b1c22-ead4-11e5-8c5c-575d5cca0bf8.png)

**Comment by pieterlukasse** [comment]
@jjgao : what do you think? 
Possibly there is a mismatch between [this backend code](https://github.com/cBioPortal/cbioportal/blob/72acaf5e0a8719dd763750f8d2b8418bcb991bc4/core/src/main/java/org/mskcc/cbio/portal/servlet/CrossCancerJSON.java#L281) and the more recent frontend version of OQL(?)

**Comment by jjgao** [comment]
@pieterlukasse: Thanks for the thorough examples!

For ***Example1***, we count non-redundant sample IDs in the lollipop. The colorectal provisional and public studies share almost the same mutation data. We don't want to over-count them in the lollipop. We plan to support different version of data per study/sample -- which may partially solve the problem.

For ***Example2***, the mutations tab is not synchronized the OQL, ie. mutations tab always loads up all mutations. We have been thinking of filtering based on OQL in mutations tab but haven't spec out yet. 

For ***Example3***, '!=' is not officially supported yet :) In the single study oncoprint, we are using Adam's front end OQL (which supports '!='), but in the cross-cancer query, we are still using backend OQL (which does nto support '!='). Our plan to move all the functionality of cross cancer query to single cancer query page once we support merging studies.

For ***Example4***, the reason is we never designed to support the same gene on different rows. But I think we should support that. (@adamabeshouse)

We should fix ***Example4*** (@adamabeshouse, #1033) , spec ***Example2*** (@onursumer, #1034). ***Example1*** and ***Example3*** would be a big task but we will be there.

**Comment by pieterlukasse** [comment]
Hi @jj, thanks for the reply. Could we perhaps support ***Example3*** by just patching the backend OQL for now?

**Comment by jjgao** [comment]
@pieterlukasse: The backend OQL is an ancient behemoth I am a little uncomfortable to touch -- we plan to take it out for good. If you can wait, we would rather solve it in the front end. Do you have a pressing need?

**Comment by pieterlukasse** [comment]
Hi @jj, the thorough examples are mostly provided by @awernibi . He would like to have this solved soon. Maybe I can try to provide a fix for the backend OQL part. I will let you know.

**Comment by jjgao** [comment]
@pieterlukasse: sure, please feel free to do that.

**Comment by pieterlukasse** [comment]
Ok, answer for _example1_ makes sense, although I think a warning message in the lollipop view would be nice.  _example2_ 3 and 4 are solved! 
Nice @jjgao !

**Comment by pieterlukasse** [comment]
@awernibi just to let you know this is solved now :)
