### ISSUE TITLE
XvY categorical v numerical feedback

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9297]
I am loving this feature! A few suggestions below, all relatively minor.

- [x] 1. Instead of ‘Add violin plot table’, should it be ‘Add violin/box plot table’?
- [x] 2. Axis labels at the right are overlapping
![image](https://user-images.githubusercontent.com/10508276/153241607-6bb394d9-4342-438b-ac5e-cb4ae7cdaf42.png)
https://www.cbioportal.org/study/summary?id=lgg_tcga_pan_can_atlas_2018
- [x] 3. Outlier dots remain even when I remove both violin & box plots. I can't remember how the conversation yesterday ended, but if outlier dots are only relevant to/calculated from the box plot, then should the outlier dots disappear when box plot is deselected?
- [x] 4. When toggling log scale, the axis labels momentarily show some long values before resetting to the actual labels.
![Feb-09-2022 11-17-55](https://user-images.githubusercontent.com/10508276/153242944-adb6803a-4162-47ce-8d2f-395ff0b7b1c4.gif)
- [x] 5. The fact that a user can make the chart bigger to see new columns is a very hidden feature, especially since no other charts work like that. One thought on how to make it known - when a user adds a chart, maybe add a sentence after the 'chart added' to say something like 'Widen the chart to view additional data.' or 'Widen the chart to view median and quartile bounds.'
![image](https://user-images.githubusercontent.com/10508276/153243687-ae268702-3bbc-408a-9e67-7fc1dab500f6.png)
- [x] 6. Probably can limit axis labels to fewer (2?) decimals (0.74 vs 0.7416)
![image](https://user-images.githubusercontent.com/10508276/153244360-d3dd2e30-31c5-4ac0-82bd-c7041f8353ce.png)
- [x] 7. If I add a chart where one attribute has no data, it says 'No data.', which is great, but it also shows what I think is a blurry 'Infinity'  where the axis label would be:
![image](https://user-images.githubusercontent.com/10508276/153246538-f90701ac-20e1-457c-899f-7a50301a1d2c.png)
Can that be cleaned up a bit?
~- [ ] 8. One of the things that's missing in the add menu is the availability of data for each clinical attribute. We have it in the 'Clinical' subtab, but not in these dropdown menus. I realize that it's probably a much bigger tasks to get that data in the dropdown, but would be nice to have someday (and would hopefully also benefit the Plots tab dropdowns).~
(This requires backend work, we'll do this in the future - Adam)

**Comment by schultzn** [comment]
Great work - this is such a nice feature!

A couple of observations:

1.  am seeing the overlapping x axis labels on the left side of the plot too.
![image](https://user-images.githubusercontent.com/11892704/153308840-49cd75a3-c40e-4e5c-9fdb-d357451a815e.png)

2.  Tooltips that show the median and maybe some other summary data would be nice. 
3. Tooltips for the category name could be useful too when they are truncated. Or better yet, allow column resizing of that is possible.
4.

**Comment by adamabeshouse** [comment]
Sorry for the delay! Some questions:
@tmazor 
#8: What makes this more complicated is that the availability is 2-dimensional - we're looking at how many samples have data for both of the selected attributes. So it's really a UI question of how we would want to handle that - do we show individual availability if neither selected, then when one is selected show dual availability in the other dropdown?

@schultzn
#2: What would be hovered to show those tooltips?
#3: The table library doesn't have a built-in column resizing functionality, so I hacked together a prototype (with a UI that would be replaced with the mutation table column resize UI). It works pretty well but I'm noticing that resizing the column won't even be enough, as you can see here. How should we handle these very long names? Should we change the font size? Wrap the names?

![violin-resizing](https://user-images.githubusercontent.com/636232/156673988-710c1634-6f0b-4b2e-934a-09ea4d955c9f.gif)


CC: @alisman @jjgao @inodb

**Comment by schultzn** [comment]
Thanks @adamabeshouse - the column resize functionality looks great! To make a column even wider, as user could first make the entire chart wider, correct?

And regarding question 2: We could do the same we are doing in box plots in the comparison view, where a hover over the box shows the summary data. We should probably also add this functionality in the Plots Tab, and reduce the number of significant digits. 

<img width="374" alt="image" src="https://user-images.githubusercontent.com/11892704/156696840-2261f59a-5942-4e16-8aaa-9e47302d958a.png">

**Comment by tmazor** [comment]
@adamabeshouse I think what you suggested makes sense for data availability
