### ISSUE TITLE
Patient view: refactoring genomic overview with igv.js

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#9311]
We should replace the current implementation with igv.js. There was a prototype by a summer student. 

@JiaoJiao123 could you please fill in some more information here, e.g. where the code is, and previous discussions with igv?

TODO:

- [x] Show sample labels in the front
- [x] Controls at the top kinda overwhelming (maybe hide?)
- [x] Mutation count + FGA numbers at the end of genomic overview
- [ ] Clicking on mutations + CNA not super obvious that it zooms in in IGV
- [x] Tooltip showed sample key
- [x] Show right reference genome version depending on study's reference genome version
- [x] how are gene panels handled (see e.g. [this case](https://www.cbioportal.org/patient?studyId=msk_impact_2017&caseId=P-0000377))
- [x] Increase spacing between sample tracks
- [x] Disable right-click context menu for tracks
- [x] Relocate VAF Plot
- [x] Make the chromosome row more compact if possible
- [x] Get rid of more whitespace if possible
- [ ] Find better way and location to display reset zoom and advanced view buttons
- [ ] Display tooltip on hover, not click, if possible

**Comment by onursumer** [comment]
Seems like IGV team added mutation track support for cBioPortal data. See https://github.com/igvteam/igv.js/issues/811#issuecomment-815449253.

Now we can start working on this again.

**Comment by inodb** [comment]
demo on Tuesday
