### ISSUE TITLE
Mutations tab in provisional TCGA breast cancer is not showing mutations

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#933]
Two users reported this today. Below are two example links. Assigning to JJ, who can reassign.

http://www.cbioportal.org/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=rna_seq_v2_mrna_median_Zscores&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_3way_complete&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=RB1&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit

http://www.cbioportal.org/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=gistic&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_cnaseq&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=CTCF%0D%0ACDH1%0D%0AGATA3&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit

**Comment by jjgao** [comment]
It was data issue. The profile stable ids were incorrect -- missing study id.
