### ISSUE TITLE
Need to clarify upload policy better

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9341]
See: https://www.cbioportal.org/visualize

We do not host private datasets unless the intention is to make it public if I understand correctly. Prolly good to extend this documentation a bit. Note that the email address is incorrect: https://github.com/cBioPortal/cbioportal/issues/9334

See also user question: https://groups.google.com/g/cbioportal/c/GPav33Zx_L0/m/EvRqQWRAEwAJ

**Comment by jjgao** [comment]
Should we also update the contact us email to the google groups email?
