### ISSUE TITLE
Is the Pan-Cancer Studies list cached?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#9368]
On my browser (Chrome):
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/840895/156896417-e6acee02-7568-448d-bf9b-f08dd77f8cfd.png">

Incognito mode:
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/840895/156896432-c0b5ae96-ea4d-4dbe-9b2a-c452a9f62f40.png">

**Comment by alisman** [comment]
@jjgao can you try clearing your localstorate?   that list is set in configuration and the only way i can think this could happen is if for some reason you had the configuration overriden in localstorage.  so, lets try that first.  ```localStorage.clear()```

**Comment by jjgao** [comment]
@alisman that worked. Thanks! I am wondering if this would affect other users?
