### ISSUE TITLE
Following Docker Setup does not result in working instance

### ISSUE THREAD

**Issue by GaryFrewin** [cBioPortal/cbioportal#9369]
Is most likely my mistake, but I followed the instruction on the docker page and several steps are not working. 

1. Under quick start, `./init.sh` does not run, the ./ needs removing (but this could be wrong too?)
2. Both quick start and comprehensive start instruction result in a constantly restarting cbioportal-container, so localhost:8080 just returns an invalid response. 
3. Is ./config/portal.properties supposed to be blank after running init.sh? The docmentation makes it seem like this file should be populated after running init.sh, but it is blank. Perhaps some clarity in the readme would also help here. 

Additionally, even though the database container seems to be running. I cannot connect to it from mysql workbench. Would appreciate some guidance here as a way to open the db and view the schema/table diagram.

**Comment by inodb** [comment]
@GaryFrewin Thanks for reaching out!

1. What OS are you using to run this? On Linux/Mac if the execution bit is set (`chmod +x init.sh`), which it should be, then `./init.sh` would work
2. Yeah figuring out what goes wrong when reading the logs can be tricky. The first time it takes a few minutes to build the seed database before the container can start. However if that doesn't happen something else is going wrong which can usually be spotted in the logs
3. Hmm that's weird - yeah it should be populated. Could be a bug
4. There is some documentation on how to connect from mysql workbench here: https://github.com/cBioPortal/cbioportal-docker-compose#run-cbioportal-using-docker-compose

**Comment by GaryFrewin** [comment]
@inodb 
Thanks for the response. 
1. I'm on windows, maybe that is the issue. 
2. If I leave it running for half an hour, nothing changes. The cBioportalContainer logs just keep spitting out the following over and over:
cbioportal-container                   | Using database config:
cbioportal-container                   | Using database config:
cbioportal-container                   | Using database config:
cbioportal-container                   | Using database config:
cbioportal-container                   | Using database config:
cbioportal-container exited with code 1
3. This command still gives a blank file for me. 
4. Thanks, I'll take a look at this today. :)

**Comment by dippindots** [comment]
@GaryFrewin @inodb I will close this because this issue is from 2022, @GaryFrewin please feel free to reach out to us on Google group (cBioPortal for Cancer Genomics Discussion Group) if you still need help.
