### ISSUE TITLE
Plots tab discrepancy for new structural variant implemenation

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9377]
Compare the following on public and sv instances.  There is a big discrepancy

https://sv.cbioportal.aws.mskcc.org/results/plots?cancer_study_list=msk_impact_2017&tab_index=tab_visualize&case_set_id=msk_impact_2017_all&Action=Submit&gene_list=TMPRSS2%250AERG&plots_horz_selection=%7B%22dataType%22%3A%22STRUCTURAL_VARIANT%22%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%22colorByMutationType%22%3A%22true%22%2C%22colorByCopyNumber%22%3A%22true%22%7D

**Comment by alisman** [comment]
New:
![image](https://user-images.githubusercontent.com/186521/157538083-e2289953-ad8d-4ea9-b257-cddc0eb77363.png)

Old:
![image](https://user-images.githubusercontent.com/186521/157538125-1f8f549b-8608-4c81-b126-00ed7cd6e0bb.png)

**Comment by alisman** [comment]
Old:
![image](https://user-images.githubusercontent.com/186521/157972260-240a7850-37c6-4cf6-b69e-5f6bb13ca5ca.png)

New:
![image](https://user-images.githubusercontent.com/186521/157971905-e4b18c5a-ad84-4c93-a4f6-0cf1fa8d104b.png)

**Comment by adamabeshouse** [comment]
Discrepancy has been determined to be caused by new data
