### ISSUE TITLE
Mutation table discrepancy in structural variant count

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9386]
https://sv.cbioportal.aws.mskcc.org/results/mutations?cancer_study_list=msk_impact_2017&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=structural_variants&case_set_id=msk_impact_2017_cnaseq&gene_list=TMPRSS2%250AERG&geneset_list=%20&tab_index=tab_visualize&Action=Submit

**Comment by alisman** [comment]
@averyniceday @mandawilson 

Discrepancy is due to this fetch:
https://www.cbioportal.org/api/structural-variant/fetch

When submited with msk_impact_2017_fusion, we get 401 results. (401 is a count not a status code : )

When sumbitted with msk_impact_2017_structural_variants, we only get 99 results.

I tried to diff the results to see what was missing in the latter of it was a duplication of data in the original service, but it seems there are just events that are flat out missing:  for example, this event "ABCG1-TMPRSS2" fusion is just flat out missing in the new response.

**Comment by alisman** [comment]
@averyniceday found this is due to data.  @ritikakundra looking into it

**Comment by averyniceday** [comment]
waiting on feedback from Angelica about why a check was added - this check is dropping a significant amount of records from the converted files curation is providing
