### ISSUE TITLE
One-side or two-side tests

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#9388]
In both the Mutual Exclusivity tab and the Comparison page/tab, we use 1-side Fisher's Exact test. [A user](https://groups.google.com/g/cbioportal/c/WbPzItsK_Vc/m/wlTdzmf3AQAJ) asked us whether a 2-side test is more appropriate. Let's consult statisticians.

**Comment by inodb** [comment]
Got some feedback on this and raised a new ticket: https://github.com/cBioPortal/cbioportal/issues/9943. Turns out two-sided is more appropriate
