### ISSUE TITLE
SV discrepancy with study blca_nmibc_2017

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9435]
http://hgnc.cbioportal.aws.mskcc.org/results/mutations?cancer_study_list=blca_nmibc_2017&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=structural_variants&case_set_id=blca_nmibc_2017_cnaseq&gene_list=FGFR3%250ATACC3&geneset_list=%20&tab_index=tab_visualize&Action=Submit&comparison_subtab=alterations&comparison_selectedEnrichmentEventTypes=%5B%22structural_variant%22%5D

If you compare the above with same query on public portal, you'll see there are more SV events in the "old" portal (4 to 1) than the new.

**Comment by alisman** [comment]
The is occurring because mutations tab has sub-tabs by gene, and we're not counting them in both places.  Should we?

**Comment by inodb** [comment]
verify that this is fixed
