### ISSUE TITLE
switch to front end svg2pdf lib

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#944]
https://github.com/yWorks/svg2pdf.js/tree/master

**Comment by adamabeshouse** [comment]
This plugin doesn't work with the latest build of jsPDF, and there's no replacement yet. For now, we'll stick with building pdfs on the backend if the svg is within 2 MB (the POST limit), otherwise we alert the user that it's too big and advise they download an SVG instead.

**Comment by morungos** [comment]
Just FYI, I've done well with pdfkit. It's not directly using SVG, but SVG commands map across nicely, so it's doable.
