### ISSUE TITLE
Loader allows you to load a patient attribute which is actually a sample attribute in the database

### ISSUE THREAD

**Issue by aderidder** [cBioPortal/cbioportal#945]
If I define a new attribute as a sample attribute and upload my data, the attribute get stored as a sample attribute in the clinical_attribute table and my data gets stored in clinical_sample.
If I have made a mistake and change the attribute to a patient attribute in my data file and reupload my study, the data gets stored in clinical_patient. However, in the clinical_attribute table it will still be labeled as a sample attribute. The loader does not give a warning, nor does it give an error.
This implies that studies may think they're using sample attributes which are actually patient attributes and vice versa, which I think may affect e.g. the study view.

Desired solution: loader should check whether a patient attribute is also stored in the database as a patient attribute and the same for a sample attribute. 

The validator will also intercept this, but the loader should at least provide a warning or an error here.

**Comment by jjgao** [comment]
Closing this since we have meta data per study now.
