### ISSUE TITLE
Clean up Mutations end point

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#9461]
I think it's safe to remove these fields: `fisValue`, `functionalImpactScore`, `linkMsa`, `linkPdb`, `linkXvar`, `refseqMrnaId`. 

Backend files:

- [x] core/src/main/java/org/mskcc/cbio/portal/dao/DaoMutation.java
- [x] core/src/main/java/org/mskcc/cbio/portal/model/ExtendedMutation.java
- [x] core/src/main/java/org/mskcc/cbio/portal/scripts/ImportExtendedMutationData.java
- [x] core/src/main/java/org/mskcc/cbio/portal/util/ExtendedMutationUtil.java

- [x] core/src/main/java/org/mskcc/cbio/portal/web_api/GetMutationData.java

- [x] core/src/test/java/org/mskcc/cbio/portal/dao/TestDaoMutation.java

- [x] model/src/main/java/org/cbioportal/model/Mutation.java

- [x] persistence/persistence-mybatis/src/test/java/org/cbioportal/persistence/mybatis/MutationMyBatisRepositoryTest.java

- [x] web/src/test/java/org/cbioportal/web/MutationControllerTest.java

- [x] web/src/main/java/org/cbioportal/web/mixin/MutationMixin.java

- [x] web/src/main/java/org/cbioportal/web/parameter/sort/MutationSortBy.java

XML 

- [x] persistence/persistence-mybatis/src/main/resources/org/cbioportal/persistence/mybatis/MutationMapper.xml

SQL

- [x] cgds.sql
- [x] cgds-test.sql
- [x] testSql.sql
- [x] core/src/test/resources/seed_mini.sql

Currently:
```json
[
  {
    "alleleSpecificCopyNumber": {
      "ascnIntegerCopyNumber": 0,
      "ascnMethod": "string",
      "ccfExpectedCopies": 0,
      "ccfExpectedCopiesUpper": 0,
      "clonal": "string",
      "expectedAltCopies": 0,
      "minorCopyNumber": 0,
      "totalCopyNumber": 0
    },
    "aminoAcidChange": "string",
    "center": "string",
    "chr": "string",
    "driverFilter": "string",
    "driverFilterAnnotation": "string",
    "driverTiersFilter": "string",
    "driverTiersFilterAnnotation": "string",
    "endPosition": 0,
    "entrezGeneId": 0,
    "fisValue": 0,
    "functionalImpactScore": "string",
    "gene": {
      "entrezGeneId": 0,
      "geneticEntityId": 0,
      "hugoGeneSymbol": "string",
      "type": "string"
    },
    "keyword": "string",
    "linkMsa": "string",
    "linkPdb": "string",
    "linkXvar": "string",
    "molecularProfileId": "string",
    "mutationStatus": "string",
    "mutationType": "string",
    "namespaceColumns": {
      "additionalProp1": {},
      "additionalProp2": {},
      "additionalProp3": {}
    },
    "ncbiBuild": "string",
    "normalAltCount": 0,
    "normalRefCount": 0,
    "patientId": "string",
    "proteinChange": "string",
    "proteinPosEnd": 0,
    "proteinPosStart": 0,
    "referenceAllele": "string",
    "refseqMrnaId": "string",
    "sampleId": "string",
    "startPosition": 0,
    "studyId": "string",
    "tumorAltCount": 0,
    "tumorRefCount": 0,
    "uniquePatientKey": "string",
    "uniqueSampleKey": "string",
    "validationStatus": "string",
    "variantAllele": "string",
    "variantType": "string"
  }
]
```

**Comment by jagnathan** [comment]
oncotatorProteinPosStart and oncotatorProteinPosEnd are used for sorting in MutationSortBy Enum

**Comment by jagnathan** [comment]
core/src/main/java/org/mskcc/cbio/portal/util/ExtendedMutationUtil.java uses getOncotatorVariantClassification.  Therefore not removing getOncotatorVariantClassification.

**Comment by jagnathan** [comment]
New issue to remove oncotator and dbSnp related fields #9779
