### ISSUE TITLE
Installation map script not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#9472]
https://github.com/cBioPortal/installation-map/actions

![image](https://user-images.githubusercontent.com/840895/164071242-f60dd2bb-100c-4cfd-921e-655ae8bc6138.png)

**Comment by Luke-Sikina** [comment]
![Screenshot from 2022-04-21 14-25-31.png](https://images.zenhubusercontent.com/5d7933c4ce6e6a000126f83a/24f6b65b-f1a6-415a-b27a-c1a7093e6656)
