### ISSUE TITLE
Excessive bloat in the war files with shaded jars

### ISSUE THREAD

**Issue by morungos** [cBioPortal/cbioportal#948]
The war file built by Maven is immense. I've built a single war which works fine for the main web application that's about 60Mb, but the standard one is 150Mb. Mainly this seems to be because the core and business jars are shaded and contain a lot of the same stuff, and many of these components are also embedded in the war itself. So there are three copies of some dependencies in the final package, at least. 

It's not really clear why these get shaded, or why the shaded versions are deployed in the war.

**Comment by ecerami** [comment]
@morungos @jjgao :  have you already started to work on this?  was thinking that Ersin could consider working on, as first step in learning the maven / spring build system.  Thoughts?

**Comment by jjgao** [comment]
@ecerami sounds like a good project for Ersin.

**Comment by morungos** [comment]
Oh, just saw the comments here which I'd missed. Here's a proposed strategy anyways...

Adding a new scripts component which will initially be dependent on the core component, but which will generate a runnable and shaded jar through pom.xml magic.

The original core component will become non-shaded, and any missing war dependencies added as appropriate. 

Using dependency-management at top-level to ensure dependency versions are handled consistently

The result will be a new scripts-nnn.jar file which is executable, to replace using the core-nnn.jar as an executable (if that’s what currently happens and I think it is.

I’d also suggest de-shading business-nnn.jar, as I have no idea what that could be independently used for.

That would slim down the war file and build an executable which could eventually allow for refactoring too, but doesn’t have to. The new scripts component would not need any code or testing, since it’s a repackaging based on dependencies.

**Comment by morungos** [comment]
If Ersin wants to work on this fine: I'm happy to review and/or collaborate. Just so long as it doesn't get bumped to an infinite milestone.

**Comment by ecerami** [comment]
I think Ersin will first be busy fixing the unit tests first.  So, don't want to block you.  We can always circle back with you after the unit tests are fixed.

**Comment by morungos** [comment]
Sounds good to me.

**Comment by morungos** [comment]
So far, all I've done is removing the shading from the business and core, and added a new scripts component which depends on core and then shades it. This actually seems to work pretty well, but I haven't deployed a war to test. The scripts jar does work standalone, and the core and business jars are now reasonably sized.

**Comment by morungos** [comment]
The next issue is we get:

```
IllegalStateException: Duplicate fragment name: spring_web for jar:file:/Users/stuartw/git/cbioportal-upstream/portal/target/portal/WEB-INF/lib/core-1.1.0-SNAPSHOT.jar!/META-INF/web-fragment.xml and jar:file:/Users/stuartw/git/cbioportal-upstream/portal/target/portal/WEB-INF/lib/business-1.1.0-SNAPSHOT.jar!/META-INF/web-fragment.xml
```

This is because both business.jar and core.jar get `META-INF/web-fragment.xml`, because they're both getting all the dependencies, which isn't right. We need to convert the top level to `dependencyManagement` and only use the right dependencies in the right places.
