### ISSUE TITLE
Changed API for CIViC

### ISSUE THREAD

**Issue by mbenary** [cBioPortal/cbioportal#9485]
When exploring the mutations of a single sample (e.g. https://www.cbioportal.org/patient?sampleId=P-0001237-T01-IM3&studyId=crc_dd_2022) the annotation for CIViC is not available. The error message reads "Error fetching Civic data". 

Beginning of April CIViC changed to a GraphQL API (https://civicdb.org/welcome), which might be connected with the issue.

**Comment by inodb** [comment]
@mbenary it seems to have started working again - is this what you see as well?

**Comment by Luke-Sikina** [comment]
Relevant: https://github.com/griffithlab/civic-server/issues/701#issuecomment-1095196552

**Comment by inodb** [comment]
filed a new ticket for CIViC
