### ISSUE TITLE
htan patient timeline comments

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9496]
I'm not sure if these are data or UI, but I noticed a few things looking at the HTAN patient timeline:

- [ ] Labtest/IHC tooltips don't include the gene:
![image](https://user-images.githubusercontent.com/10508276/165826504-a5101c7f-2497-47f5-9add-a718dfd62451.png)

- [ ] The first few entries for Molecular Test are actually IHC results (and here the gene is displayed):
![image](https://user-images.githubusercontent.com/10508276/165826764-cc05adab-f9ad-4ac7-a2c4-4577aa193c58.png)

- [x] For CEA, it looks like there are 2 dates with 2 scores, and those just appear at the top and aren't connected to the rest (at least I think that's what's happening). This is confusing to interpret:
![image](https://user-images.githubusercontent.com/10508276/165826998-657605ea-2d79-466e-945e-f2f41d6c533a.png)

- [ ] I'm also just kinda confused by the Molecular Test row - is this different results than the CNA table below?
![image](https://user-images.githubusercontent.com/10508276/165827512-3bb4d0a3-3824-4677-b1c6-71a04edaf2ac.png)

https://www.cbioportal.org/patient?studyId=brca_hta9_htan_2022&caseId=HTA9_1#navCaseIds=brca_hta9_htan_2022:HTA9_1

**Comment by alisman** [comment]
@ritikakundra can you look at 1, 2 and 4 above?  they look to be data issues.

**Comment by alisman** [comment]
@tmazor for #3 above, yeah, it's b/c there are two values from same day. what do you think is the appropriate treatment for that?l.    i guesws we could plot the two points and then not connect them with lies at all?

**Comment by tmazor** [comment]
@alisman ideally the line would include those points somehow, since they are part of whatever trend is happening. what about plotting the average of the 2, with the little 2 indicator still there to indicate there are multiple values? or plot the two points individually but have the line connect at the average of the two?

**Comment by alisman** [comment]
@tmazor #3 should now be fixed.  the "stack" of concurrent events should appear at the average y value.

**Comment by tmazor** [comment]
thanks @alisman  - it looks great now
