### ISSUE TITLE
Why don't +/-1s (gains and losses) show up in copy number data?

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#95]
I have a dataset with copy number data which happens not to have any 2s nor -2s (amplifications and homozygous deletions). cBioPortal shows no alterations at all. I've checked the code and it seems to happen (among other places) here CrossCancerJSON:

                        boolean isAnyCnaChanged = isAnyCnaUp || isAnyCnaDown;
                        if(isAnyMutated && !isAnyCnaChanged)
                            noOfMutated++;
                        else if(isAnyMutated && isAnyCnaChanged)
                            noOfOther++;
                        else if(isAnyCnaUp)
                            noOfCnaUp++;
                        else if(isAnyCnaDown)
                            noOfCnaDown++;
                        else if(isAnyCnaGain)
                            noOfCnaGain++;
                        else if(isAnyCnaLoss)
                            noOfCnaLoss++;

Why does it ignore isCnaLoss and isCnaGain?

**Comment by jjgao** [comment]
+1 and -1 are usually arm level events contains many genes. They would make the data/visualization very noisy.
