### ISSUE TITLE
Invalid use of reserved word as identifier in SQL

### ISSUE THREAD

**Issue by morungos** [cBioPortal/cbioportal#951]
In `DaoGeneticAlteration#addGeneticAlterations`, the reserved word `VALUES` is used as an identifier. It needs identifier escaping. This throws an error in MySQL, at least on my system -- and this is documented as being expected so it ought to be amended to use identifier escaping.

**Comment by fedde-s** [comment]
I wondered why nobody else seemed to have any trouble with that unquoted column… Figured that the parsing logic was different in the version of MySQL I was running, from a release repo of a GNU/Linux distro. Those tend to lag behind patches that are not security-related especially if they affect interfaces.

**Comment by fedde-s** [comment]
Ah, @pieterlukasse knew why it wasn’t an issue for more people: when loading data from files, the function contacts the database via `MySQLbulkloader.insertRecord(String...)` and never gets to this SQL statement. So presumably it’s only used in unit tests.

**Comment by pieterlukasse** [comment]
can be closed, right?
