### ISSUE TITLE
mutations tab performance

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9516]
I'm trying to troubleshoot a user question about KRAS mutations in GENIE vs the curated non-redundant study list and it's taking forever because of significant performance issues on the Mutations tab. It takes forever for the page to load. Once it finally loads, I've been applying and removing filters, and each reset takes a long time too. And chrome has complained that the page isn't responding several times along the way also. Might be time to think about trying to improve this page.

**Comment by jjgao** [comment]
https://genie.cbioportal.org/results/mutations?cancer_study_list=genie_public&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Ccna&case_set_id=genie_public_cnaseq&gene_list=KRAS&geneset_list=%20&tab_index=tab_visualize&Action=Submit

**Comment by jjgao** [comment]
Misty island performance issue? 
<img width="980" alt="image" src="https://user-images.githubusercontent.com/840895/167485844-67ada2b2-b162-4537-926d-e1b72cfc7f2c.png">

**Comment by alisman** [comment]
@zhx828 yes.  ```localStorage.oncokbOverride = "/proxy/oncokb"```

**Comment by alisman** [comment]
@onursumer @jjgao there is a very significant delay before we even send requests to oncokb.  i think this is caused by loliplot rendering.  did we recently change how much we render in lolliplot?
