### ISSUE TITLE
mutations disappear with change in transcript

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9517]
User reported: https://groups.google.com/g/cbioportal/c/Am93Ex23cKw

Query KRAS in GENIE v11:
https://genie.cbioportal.org/results/mutations?cancer_study_list=genie_public&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations&case_set_id=genie_public_all&gene_list=KRAS&geneset_list=%20&tab_index=tab_visualize&Action=Submit

There are 20270 mutations:
![image](https://user-images.githubusercontent.com/10508276/167479952-501076bc-2c06-42fd-9720-09ef232ffcd4.png)

If I filter to G12V, there are 4457 mutations:
![image](https://user-images.githubusercontent.com/10508276/167480007-8ab2dc78-405a-48bc-a394-c53d6f749c03.png)

Now switch to the second transcript in the list (NM_004985) - total mutations drops to 14937
![image](https://user-images.githubusercontent.com/10508276/167479680-4df9525e-cae6-434f-bce2-8fba4dbdd0de.png)

And again filter to G12V and there are only 56 mutations
![image](https://user-images.githubusercontent.com/10508276/167479710-bce25a32-9cc0-4744-a2a0-a9daabe1c5c3.png)

I don't know how much these 2 transcripts differ, so maybe this is expected, but I did notice that the 56 G12V mutations after switching transcripts are almost exclusively from GRCC & UHN, and there's only ~3 from DFCI/MSK -- given the overall numbers of samples per site, this struck me as very odd. Could there be a data-related reason for that bias in mutations after switching transcripts?

**Comment by tmazor** [comment]
Sorry, realized I left out a key detail - this doesn't happen if you query for KRAS in curated non-redundant studies in public portal - for public portal query, changing transcripts results in basically the same number of mutations:
 https://www.cbioportal.org/results/mutations?tab_index=tab_visualize&Action=Submit&session_id=627e5a200934121b56df4047&plots_horz_selection=%7B%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D&mutations_transcript_id=ENST00000311936

**Comment by inodb** [comment]
@ritikakundra

Could you help address this case list issue for GENIE? It looks like the number of mutations is different for:

- All samples (121221 patients / 136096 samples) - 20284 mutations in KRAS
- Samples with CNA and mutation (85703 patients / 94789 samples) - 14062 mutations in KRAS

**Comment by leexgh** [comment]
Query KRAS in GENIE v11:
https://genie.cbioportal.org/results/mutations?cancer_study_list=genie_public&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations&case_set_id=genie_public_all&gene_list=KRAS&geneset_list=%20&tab_index=tab_visualize&Action=Submit
![screenshot-genie cbioportal org-2022 07 05-14_27_10](https://user-images.githubusercontent.com/16869603/177392753-292b8d7a-a6a9-4eb4-8300-3557cd845fea.png)
![screenshot-genie cbioportal org-2022 07 05-14_32_46](https://user-images.githubusercontent.com/16869603/177393153-e90bcd60-21af-49be-8a9c-92e609e43a57.png)

**Comment by inodb** [comment]
@leexgh it seems like this is both a data issue and an issue in how we are handling genome nexus queries on the frontend. Like it shouldn't fail to map back after normalization of the genomic change, is there any way we can adjust the code to accommodate for this? I believe we had a solution for this because we had the same issue with the command line annotator

**Comment by leexgh** [comment]
This pr should fix the problem: https://github.com/genome-nexus/genome-nexus/pull/620
Genome nexus will return annotation for both 
```
12-25398283-25398284-AC-AA
```
and 
```
12-25398284-25398284-C-A
```
