### ISSUE TITLE
filter status inconsistency for gene tables in study view

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9553]
As best I can tell, when I load a study for the filter time, the cancer genes filter on the genes tables is off, so all tables show all genes.

However, if I am logged in and have access to the 'Reset Charts' button, clicking that button will turn the filter on. This results in genes 'disappearing' without a user realizing what's happening (we've had a user question about this, and I've been caught by it too).

I think the Reset Charts button needs to set charts to the same state as on initial load, which in this case means the filter should be off.

**Comment by alisman** [comment]
@tmazor i'm not sure what you mean be "cancer genes filter" ?    Is this in the Hyve's alteration filter menu?  Are you guys using that feature?

**Comment by tmazor** [comment]
Sorry for confusion @alisman, I mean the little filter icon next to the 'Gene' column name:
![image](https://user-images.githubusercontent.com/10508276/189186724-1e2e9ca8-ada2-4059-9e1d-445b31b30c0e.png)
