### ISSUE TITLE
genomenexus.url is being ignored

### ISSUE THREAD

**Issue by ghost** [cBioPortal/cbioportal#9556]
similarly to #9503, genomenexus.url does not seem to be picked up from the portal.properties file

**Comment by leexgh** [comment]
After testing, the `genomenexus.url` is being used properly. Please double check `portal.properties` to make sure it has the correct genomenexus.url setting (it's not in protal.properties.EXAMPLE by default, if you copy this file and want to change genomenexus.url, you need to add it manually in your protal.properties).
