### ISSUE TITLE
timeline improvements

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9590]
- [ ] add a legend for the timeline
- [x] the tooltips on the right hand are not legible (they appear to the right of the [timeline](https://www.cbioportal.org/patient?studyId=lgg_ucsf_2014&caseId=P04))
   <img width="105" alt="Screen Shot 2022-05-31 at 3 35 40 PM" src="https://user-images.githubusercontent.com/1334004/171270500-37d97dd0-fca6-4f5e-a631-5f39b5a9e7df.png">

**Comment by alisman** [comment]
@inodb fixed the tooltip issue.  for the legend, can you expand on the idea there?
