### ISSUE TITLE
Add support for OpenID Connect to applicationContext-security.xml

### ISSUE THREAD

**Issue by morungos** [cBioPortal/cbioportal#961]
We use OpenID Connect at UHN, and I fully expect others to some day. It's very similar to Google+ authentication (and in fact, Google+ authentication is actually OpenID Connect) but there are differences in the URLs used. However, the basic approach is identical: a new Spring profile can be added for OpenID Connect along the lines of that added for Google+ authentication. Note that OpenID Connect is nothing at all like OpenID. 

Spring Social doesn't support OIDC out of the box. We did manage to make Spring Security work with the Mitre OIDC implementation, but without using Spring Social. So we could port that, or we could try with the newer `GenericOAuth2ConnectionFactory` (OIDC is a layer on top of OAuth2).

**Comment by morungos** [comment]
Just a follow-up, now that Google+ (and most others) are actually OIDC, there's merit in the self-configuration provided by OIDC. It does allow the provider to change their deployment URL layout without needing to change Java code. It also makes deployment testing a dream, as the URL (and secrets) can simply change for test from production, not Java classes. So I'd personally favour a true OIDC profile. Thoughts?

**Comment by n1zea144** [comment]
Hi @morungos.  I prefer a clear separation between security protocols and their spring configurations.  So I'm in favor of a true OIDC profile.

On a related note, one of the areas I'd like to address as we re-architect the backend is looking at integrating a pluggable framework like OSGi or JPF (the latter of which I was just made aware of by a GSOC proposal - I'll get to that in a minute).  There are a few reasons why I think it would be good to do this but one of them is because it's painful to add or customize security code for one's institution.  I think having the ability to dynamically add a security module into the codebase would be useful.

I proposed this as a GSOC project [Plugin framework-Authentication](https://github.com/cBioPortal/GSoC/issues/20) and we got quite a few hits, but because it looks like we might get only 1-2 students via GSOC, this project may lose out.

**Comment by morungos** [comment]
I totally agree, @n1zea144. I did actually make a fork to refactor authentication into a separate Spring component and Maven subproject, so I could put that up pretty fast. That decouples Spring authentication entirely from core, which is probably a good place to start, even if it isn't full-on OSGI. 

I don't want to have to wait for OSGI to do this, though, as it's blocking updates at UHN right now.

**Comment by morungos** [comment]
I'm just gonna ramble a bit now, because I have my coffee, and I want to get something down. I think one of the special issues for authentication/authorization as a "plugin" in any sense of OSGI/JPF is ideal, but the current demands of authentication/authorization aren't really consistent with anything that complex. I did manage to refactor it, as above, and then even Spring Security could handle it. 

Mainly, we probably need to distinguish authentication from authorization better. Authentication is a web-layer issue, so plugins don't help much. Authorization should be more integrated, but is currently almost a single permission. 

I should comment that I have significant reservations about Spring Security. It's fine-grained permissions system is actually pretty terrible. However, the whole point in a plugin model is that we should be able to swap out the security framework even if we use Spring elsewhere. My other recent Java app did this with Apache Shiro as its security layer, even within Spring DI, just not Spring Security. Shiro makes fine-grained permissions very easy. 

The problem is the where the authorization logic belongs. At the moment, it's essentially separate, in that all it really does is allow a filtered list of authorized studies, in many instances, the AccessControl instance isn't even used where it is injected. For us, in the very near future, we'll want finer permissions control than that. 

The primary method I use in Shiro is an `isPermitted` method on a user, where the parameter is a colon-delimited set of tokens. For example `user.isPermitted("IMPACT:read")` could mark read access to the IMPACT study. A second `user.isPermitted("IMPACT:clinical")` can guard clinical data, and so on. 

So for me, the preferred option for authorization would be to make a plugin-type system that exposed a way to get the current user (this will be a thread local in Shiro, and probably Spring too) and ensure this method can be used to detect permissions. As such, it'll essentially replace the nasty `SpringUtil.getAccessControl()` calls, but return a slightly more powerful thing, that doesn't just do `getCancerStudies` and `isAccessibleCancerStudy`. 

Personally, I'd recommend dropping Spring Security at the same time. Here''s my Spring config for Shiro, which does very nearly as much as the cBio applicationContext-security.xml, but I think you'll see it's much simpler and easier, plus it provides for the fine-grained permissions we need.

**Comment by n1zea144** [comment]
I thought using security services was a good way to motivate a plugin architecture for a few reasons, but mainly to get away from the ugliness we have to go through to add support for a new protocol, customizations for institute specific requirements, and how its all globbed together at runtime.

Currently, yes, the authorization piece is readability by dataset and nothing more.

I just checked out the Shiro demo.  I like its ease of configuration.  I haven't checked, but I would hope it supports the protocols we all use now.

Related to where the authorization logic belongs is how easily it is to authorization use of the web service.  At the time, I couldn't find a way to do this easily using spring-security.

I like your use case when describing the isPermitted method.  Along those lines, as we move closer to virtual cohorts, having the ability to provide authorization per patient or sample would be a nice feature too.

The shiro configuration is more readable.  I'm certainly open to discussing the idea of using shiro more (I still know very little about it).

**Comment by jjgao** [comment]
Closing this. Please reopen if work remains to be done.
