### ISSUE TITLE
MSK-IMPACT SV counts differ

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9630]
prod:
![image](https://user-images.githubusercontent.com/10508276/175135841-4fe93b91-4e3f-4362-a58e-b2d8d1a86d9d.png)

beta:
![image](https://user-images.githubusercontent.com/10508276/175135863-66861d45-e9d6-4dc9-a653-64c1139139e6.png)

ERG, ALK, EML4 and others have slightly different counts

https://beta.cbioportal.org/study/summary?id=msk_impact_2017

**Comment by alisman** [comment]
This is fixed in data that hasn't yet been imported into the beta database.
