### ISSUE TITLE
download tab is missing eventInfo for SV data

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9631]
patients 36, 47, 58 show '-' or 'antisense fusion' but should show the gene partners as they do in prod

prod:
![image](https://user-images.githubusercontent.com/10508276/175141539-3d6d8678-bf07-438e-9b08-d714f933324c.png)

beta:
![image](https://user-images.githubusercontent.com/10508276/175141499-2b75381a-e478-4a01-8a10-180c4d8fbf61.png)

https://beta.cbioportal.org/results/download?cancer_study_list=msk_impact_2017&tab_index=tab_visualize&case_set_id=msk_impact_2017_all&Action=Submit&gene_list=TMPRSS2%250AERG%250AEGFR%250AEWSR1%250AALK%250ABRAF%250AROS1%250AEML4&show_samples=true&plots_horz_selection=%7B%22dataType%22%3A%22COPY_NUMBER_ALTERATION%22%2C%22selectedDataSourceOption%22%3A%22cna%22%2C%22mutationCountBy%22%3A%22MutationType%22%2C%22structuralVariantCountBy%22%3A%22MutatedVsWildType%22%2C%22logScale%22%3A%22false%22%7D&plots_vert_selection=%7B%22dataType%22%3A%22STRUCTURAL_VARIANT%22%2C%22selectedDataSourceOption%22%3A%22structural_variants%22%2C%22mutationCountBy%22%3A%22MutationType%22%2C%22structuralVariantCountBy%22%3A%22MutatedVsWildType%22%2C%22logScale%22%3A%22false%22%7D&plots_coloring_selection=%7B%7D&mutations_gene=EML4&comparison_subtab=alterations&comparison_selectedEnrichmentEventTypes=%5B%22structural_variant%22%5D

**Comment by alisman** [comment]
@sbabyanusha this got overlooked when we released.   
There are some SVs with eventInfo of type "Antisense fusion" and others with "ROS1-TMEM181 Fusion".    Where they used to be the same in the old fusion data.

**Comment by alisman** [comment]
@tmazor appears fixed in production
