### ISSUE TITLE
SV oncoprint tooltip - NA vs fusion

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9632]
Tooltip in prod includes 'Fusion' but tooltip in beta has 'NA'

prod:
![image](https://user-images.githubusercontent.com/10508276/175143554-d20782a9-f941-4a12-8007-e6af77447407.png)

beta:
![image](https://user-images.githubusercontent.com/10508276/175143515-50edc714-40a0-47a7-bd19-c17898fea34c.png)

https://www.cbioportal.org/results?cancer_study_list=past_dkfz_heidelberg_2013&tab_index=tab_visualize&case_set_id=past_dkfz_heidelberg_2013_all&Action=Submit&gene_list=BRAF%250AKIAA1549%250ANTRK2

https://beta.cbioportal.org/results?cancer_study_list=past_dkfz_heidelberg_2013&tab_index=tab_visualize&case_set_id=past_dkfz_heidelberg_2013_all&Action=Submit&gene_list=BRAF%250AKIAA1549%250ANTRK2

**Comment by alisman** [comment]
When value is NA in tooltip, do not show it
