### ISSUE TITLE
SV testing: plots tab shows 'NA' but should show 'Fusion' on x-axis

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9633]
possibly the same underlying issue as #9632 
also pretty sure this is something I found previously in another study, so I'm guessing it's data related

plots tab shows 'NA' but should show 'Fusion' on x-axis

prod:
![image](https://user-images.githubusercontent.com/10508276/175144036-e79d0e57-b411-4cec-956b-156e33f511e2.png)

beta:
![image](https://user-images.githubusercontent.com/10508276/175144069-4e8ac2da-4f07-46ee-a3c9-a678323b2263.png)

https://beta.cbioportal.org/results/plots?cancer_study_list=past_dkfz_heidelberg_2013&tab_index=tab_visualize&case_set_id=past_dkfz_heidelberg_2013_all&Action=Submit&gene_list=BRAF%250AKIAA1549%250ANTRK2&plots_horz_selection=%7B%22structuralVariantCountBy%22%3A%22VariantType%22%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D

https://www.cbioportal.org/results/plots?cancer_study_list=past_dkfz_heidelberg_2013&tab_index=tab_visualize&case_set_id=past_dkfz_heidelberg_2013_all&Action=Submit&gene_list=BRAF%250AKIAA1549%250ANTRK2

**Comment by alisman** [comment]
It is no longer possible via UI to reach this as the option for group by variant is removed when variantClass=NA is detected
