### ISSUE TITLE
samples gains ROS1 SV in beta

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9635]
https://beta.cbioportal.org/patient?studyId=luad_mskcc_2020&caseId=P-0019111
![image](https://user-images.githubusercontent.com/10508276/175155249-5847996b-a8e4-4ee4-8941-8c8157e04576.png)

vs
https://www.cbioportal.org/patient?studyId=luad_mskcc_2020&caseId=P-0019111
![image](https://user-images.githubusercontent.com/10508276/175155523-febf3189-21e7-4c4d-a180-26671e3a5608.png)

**Comment by sbabyanusha** [comment]
This issue is fixed in the database.
