### ISSUE TITLE
Cross study RNA expression analysis should be disabled in plots tab

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9644]
To avoid users making the mistake of comparing expression between different studies we should disable it in plots tab

Reported by @tmazor

**Comment by jjgao** [comment]
Actually we intentionally enabled it for TCGA studies... Maybe add a note? @inodb @tmazor

**Comment by inodb** [comment]
duplicate of https://github.com/cBioPortal/cbioportal/issues/9865
