### ISSUE TITLE
Genomic Alteration tab crashes on local

### ISSUE THREAD

**Issue by leexgh** [cBioPortal/cbioportal#9648]
Only crashes on localhost or `localdev`, not on production.
https://www.cbioportal.org/comparison/alterations?comparisonId=61791fa92e3200072db9b64e

<img width="580" alt="image" src="https://user-images.githubusercontent.com/16869603/176553061-47656dd7-dd44-4c60-a77d-cbb6a7defe71.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/16869603/176553127-7ece6dd3-69b2-40ab-89c2-16d2e427d0bb.png">

**Comment by inodb** [comment]
This is b/c the component is declared as make observable but there are no observables for that component
