### ISSUE TITLE
getPatientSampleMapping in webservice.do is not working with case_list 

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#965]
The following servlet doesn't work: http://www.cbioportal.org/webservice.do?cmd=getPatientSampleMapping&cancer_study_id=ucec_tcga_pub&case_list=TCGA-AP-A0L9,TCGA-AP-A05O,TCGA-AP-A05D

But get full list of mapping is working: http://www.cbioportal.org/webservice.do?cmd=getPatientSampleMapping&cancer_study_id=ucec_tcga_pub&case_set_id=ucec_tcga_pub_all

**Comment by zhx828** [comment]
Looks like the only place using cmd=getPatientSampleMapping method is study view. But the new version no longer needs this anymore. Should we make this method deprecated? @jjgao

**Comment by jjgao** [comment]
Good idea to deprecate / remove it.

**Comment by zhx828** [comment]
I think the webservice.do has been removed. This ticket can be closed.
