### ISSUE TITLE
add back new user section to user guide

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9650]
There's a New Users page here: https://github.com/cBioPortal/cbioportal/tree/master/docs/user-guide
But it doesn't show up in the docs site. Can we please add it?

**Comment by inodb** [comment]
@tmazor it seems like these are here now: https://docs.cbioportal.org/user-guide/

**Comment by tmazor** [comment]
I don't see them @inodb - where do you see them?

**Comment by tmazor** [comment]
@alisman @inodb any update on this?
