### ISSUE TITLE
resource descriptions don't appear anywhere

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9660]
The resource data definition file has a 'description' field, but this doesn't appear anywhere in the portal. Can this be added as a column in the Resource table?
![image](https://user-images.githubusercontent.com/10508276/177611709-2557ca2e-6744-4995-9060-f3c1c7c0683d.png)

**Comment by alisman** [comment]
@gblaih We can use this to work against:
https://cbioportal.mskcc.org/patient/filesAndLinks?studyId=msk_spectrum&caseId=P-0039615#navCaseIds=msk_spectrum:P-0027793,msk_spectrum:P-0034272,msk_spectrum:P-0039384,msk_spectrum:P-0039615,msk_spectrum:P-0039726,msk_spectrum:P-0039734,msk_spectrum:P-0040154,msk_spectrum:P-0040521,msk_spectrum:P-0040980,msk_spectrum:P-0041572,msk_spectrum:P-0042164,msk_spectrum:P-0042350,msk_spectrum:P-0042351,msk_spectrum:P-0042353,msk_spectrum:P-0042548,msk_spectrum:P-0042738,msk_spectrum:P-0042757,msk_spectrum:P-0042815,msk_spectrum:P-0043569,msk_spectrum:P-0043571,msk_spectrum:P-0043587,msk_spectrum:P-0043617,msk_spectrum:P-0044011,msk_spectrum:P-0044078,msk_spectrum:P-0044084,msk_spectrum:P-0044136,msk_spectrum:P-0044784,msk_spectrum:P-0044919,msk_spectrum:P-0045312,msk_spectrum:P-0045494,msk_spectrum:P-0045578,msk_spectrum:P-0045589,msk_spectrum:P-0045643,msk_spectrum:P-0045771,msk_spectrum:P-0045890,msk_spectrum:P-0045998,msk_spectrum:P-0046401,msk_spectrum:P-0046443,msk_spectrum:P-0046857,msk_spectrum:P-0046940,msk_spectrum:P-0047453,msk_spectrum:P-0047883,msk_spectrum:P-0047947,msk_spectrum:P-0048452,msk_spectrum:P-0048524,msk_spectrum:P-0048525,msk_spectrum:P-0048554,msk_spectrum:P-0048670,msk_spectrum:P-0048695,msk_spectrum:P-0048755,msk_spectrum:P-0048923,msk_spectrum:P-0049265,msk_spectrum:P-0049483,msk_spectrum:P-0049560,msk_spectrum:P-0050204,msk_spectrum:P-0050400,msk_spectrum:P-0050669,msk_spectrum:P-0051015,msk_spectrum:P-0051066,msk_spectrum:P-0051130,msk_spectrum:P-0051447,msk_spectrum:P-0052089,msk_spectrum:P-0052274,msk_spectrum:P-0052359,msk_spectrum:P-0052385,msk_spectrum:P-0052808,msk_spectrum:P-0053010,msk_spectrum:P-0053495,msk_spectrum:P-0054073,msk_spectrum:P-0054338,msk_spectrum:P-0054406,msk_spectrum:P-0055809,msk_spectrum:P-0055908,msk_spectrum:P-0056102,msk_spectrum:P-0056224,msk_spectrum:P-0056533,msk_spectrum:P-0056721,msk_spectrum:P-0056938,msk_spectrum:P-0056958,msk_spectrum:P-0057608,msk_spectrum:P-0057731,msk_spectrum:P-0057840,msk_spectrum:P-0058190,msk_spectrum:P-0058350,msk_spectrum:P-0058975,msk_spectrum:P-0059044,msk_spectrum:P-0059227,msk_spectrum:P-0059499,msk_spectrum:P-0059577,msk_spectrum:P-0059583,msk_spectrum:P-0059753,msk_spectrum:P-0059822,msk_spectrum:P-0059884,msk_spectrum:P-0059972,msk_spectrum:P-0060204,msk_spectrum:P-0060366,msk_spectrum:P-0060511,msk_spectrum:P-0060588,msk_spectrum:P-0060627,msk_spectrum:P-0060931,msk_spectrum:P-0061206,msk_spectrum:P-0061288,msk_spectrum:P-0061784,msk_spectrum:P-0062858,msk_spectrum:P-0063035,msk_spectrum:P-0063198,msk_spectrum:P-0063481,msk_spectrum:P-0063680
