### ISSUE TITLE
Question about repo [cbioportal-frontend] - [oncoprintjs]

### ISSUE THREAD

**Issue by JunqiaoDuan** [cBioPortal/cbioportal#9661]
Sorry, I have a question about repo [cbioportal-frontend] - [oncoprintjs]. I download the project and want to run it as a single module in my project. I just want to use oncoprintjs without other packages. This is my step to build and run the package [oncoprintjs].
1. I download the archived repo [cBioPortal/oncoprintjs]
2. I modify the file [webpack.config.js] to export oncoprint-bundle.js and geneticrules.js
3. I run [node server.js] to run the server
4. It runs in localhost:3000, but I got some errors in Chrome.

Here is my webpack.config.js file content:
`
const path = require('path');
const WebpackShellPlugin = require('webpack-shell-plugin');
// const WebpackShellPlugin = require('@purtuga/esm-webpack-plugin');

module.exports = env => ({
    entry: path.resolve(__dirname, 'src/js/oncoprint.ts'),
    // entry: path.resolve(__dirname, 'rules/geneticrules.ts'),
    // entry: path.resolve(__dirname, 'src/js/main.js'),
    // mode: 'development',
    module: {
        rules: [
            {
                test: /\/*/,
                use: [{
                    loader: 'url-loader',
                }]
            },
            {
                test: /src\/js\/workers\/*/,
                use:[{
                    loader: 'worker-loader',
                    options: { inline:true, fallback: false }
                }]
            },
            {
                test: /src\/js\/*/,
                use: 'ts-loader',
                exclude: /node_modules/
            }
        ]
    },
    plugins: [
        new WebpackShellPlugin(
        {
            // onBuildStart:['mkdir -p '+path.resolve(__dirname, 'dist')]
        })
    ],
    resolve: {
        extensions: [ '.tsx', '.ts', '.js' ]
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'oncoprint-bundle.js',
        library: 'oncoprintjs',
        libraryTarget: 'commonjs-module'
    },
    // output: {
    //     path: path.resolve(__dirname, 'dist'),
    //     filename: 'geneticrules.js',
    //     library: 'geneticrules',
    //     libraryTarget: 'commonjs-module'
    // },
    // output: {
    //     path: path.resolve(__dirname, 'dist'),
    //     filename: 'main.js',
    //     library: 'main',
    //     libraryTarget: 'var'
    // },
    optimization: {
        minimize: false
        // (!env || (env.DEV !== "true"))
    }
});
`

Here is my exported oncoprint-bundle.js file:
`
(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
module.exports=function(C){var g={};function I(A){if(g[A])return g[A].exports;var l=g[A]={i:A,l:!1,exports:{}};return C[A].call(l.exports,l,l.exports,I),l.l=!0,l.exports}return I.m=C,I.c=g,I.d=function(C,g,A){I.o(C,g)||Object.defineProperty(C,g,{enumerable:!0,get:A})},I.r=function(C){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(C,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(C,"__esModule",{value:!0})},I.t=function(C,g){if(1&g&&(C=I(C)),8&g)return C;if(4&g&&"object"==typeof C&&C&&C.__esModule)return C;var A=Object.create(null);if(I.r(A),Object.defineProperty(A,"default",{enumerable:!0,value:C}),2&g&&"string"!=typeof C)for(var l in C)I.d(A,l,function(g){return C[g]}.bind(null,l));return A},I.n=function(C){var g=C&&C.__esModule?function(){return C.default}:function(){return C};return I.d(g,"a",g),g},I.o=function(C,g){return Object.prototype.hasOwnProperty.call(C,g)},I.p="",I(I.s=0)}([function(C,g){C.exports="data:video/mp2t;base64,aW1wb3J0ICcuL3BvbHlmaW...
`

Here is my exported geneticrules.js file:
`
(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
module.exports=function(I){var C={};function g(A){if(C[A])return C[A].exports;var V=C[A]={i:A,l:!1,exports:{}};return I[A].call(V.exports,V,V.exports,g),V.l=!0,V.exports}return g.m=I,g.c=C,g.d=function(I,C,A){g.o(I,C)||Object.defineProperty(I,C,{enumerable:!0,get:A})},g.r=function(I){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(I,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(I,"__esModule",{value:!0})},g.t=function(I,C){if(1&C&&(I=g(I)),8&C)return I;if(4&C&&"object"==typeof I&&I&&I.__esModule)return I;var A=Object.create(null);if(g.r(A),Object.defineProperty(A,"default",{enumerable:!0,value:I}),2&C&&"string"!=typeof I)for(var V in I)g.d(A,V,function(C){return I[C]}.bind(null,V));return A},g.n=function(I){var C=I&&I.__esModule?function(){return I.default}:function(){return I};return g.d(C,"a",C),C},g.o=function(I,C){return Object.prototype.hasOwnProperty.call(I,C)},g.p="",g(g.s=0)}([function(I,C){I.exports="data:video/mp2t;base64,aW1wb3J0ICogYXMgJCBmcm9tICJqcXVl...
`
I want to run oncoprintjs/server.js successfully, but I failed. 
I got the error in Chrome:
`
Uncaught TypeError: window.Oncoprint is not a constructor
    at HTMLDocument.<anonymous> (oncoprint-glyphmap.js:11:17)
    at fire (jquery-1.11.3.js:3148:30)
    at Object.fireWith [as resolveWith] (jquery-1.11.3.js:3260:7)
    at Function.ready (jquery-1.11.3.js:3472:13)
    at HTMLDocument.completed (jquery-1.11.3.js:3503:10)
`
I use it in Windows, does it matter?
How can I run the test index.html successfully?
Waiting for your reply.
Thank you.

**Comment by onursumer** [comment]
@JunqiaoDuan You should not need to build the package yourself. The archived [oncoprintjs](https://github.com/cBioPortal/oncoprintjs) repo has not been maintained anymore. The best way to include the oncoprintjs package in your own project is to add it to your project's `package.json` as a dependency. The latest published version on npm is [v6.0.1](https://www.npmjs.com/package/oncoprintjs/v/6.0.1).

On the other hand if all you need is actually to `run` the oncoprintjs as a standalone tool with your own data then you can just use [Oncoprinter](https://www.cbioportal.org/oncoprinter).

`oncoprintjs/server.js` and `index.html` might be outdated at the moment. I'll see if I can find a quick fix for it, but I am not sure if that's what you really need to run.

**Comment by JunqiaoDuan** [comment]
@onursumer I just want to run the oncoprintjs as a standalone page in my project use my api data. Could you please fix the oncoprintjs/server.js then I want to know how to use it. Thanks very much.

**Comment by onursumer** [comment]
@JunqiaoDuan It doesn't seem easy to fix the outdated `server.js` setup. Instead, I have a created a new repo using the same oncoprint example within a react app: https://github.com/onursumer/oncoprintjs-demo

Can you try building and running this repo instead?

**Comment by JunqiaoDuan** [comment]
@onursumer Thank you very much, I'll try it.

**Comment by inodb** [comment]
Closing this for now but feel free to reach out if you need more help
