### ISSUE TITLE
Fix study view filter editing 

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9667]
Doesn't submit input

![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/b5cb7f9b-0259-4707-a25e-b6839f433423)

**Comment by onursumer** [comment]
This seems related to the latest changes in the `StudyViewPageStore.updateCustomBins` function. 
```
StudyViewPageStore.ts:3358 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'binSize')
    at StudyViewPageStore.updateCustomBins (StudyViewPageStore.ts:3358:33)
```
https://github.com/cBioPortal/cbioportal-frontend/blob/4adb61e1174d43c2ba1d04d7d37567c68456d371/src/pages/studyView/StudyViewPageStore.ts#L3358.
