### ISSUE TITLE
Sometimes incorrect sample id shown in IGV on patient view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9683]
![Screen Shot 2022-07-19 at 9.40.40 AM.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/db209241-c69d-4cc8-bfba-5daf04f3c53b)

From Ritika:

> ... when I select sample names on the patient view IGV viewer, weird text props up on the right side.

Looks like the unique sample key instead of the sample id

**Comment by ritikakundra** [comment]
@onursumer link to the above issue: http://www.cbioportal.org/patient?studyId=msk_impact_2017&caseId=P-0000004
