### ISSUE TITLE
Clinical Data Tab Empty for MSK study

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9702]
https://cbioportal.mskcc.org/study/clinicalData?id=mskimpact_test_june

All table data shows up empty:
![Screen Shot 2022-07-22 at 2 46 42 PM](https://user-images.githubusercontent.com/1334004/180504102-c862f244-1b9c-4598-8bd9-95cee1531fec.png)

Follow up:
This is a chrome browser issue, we need to find a way to better address this.
Currently we can have a warning and ask users to limit the patients/samples size based on `samples x attributes`

**Comment by pvannierop** [comment]
@inodb I have seen this before. It happens with studies with large sample counts. When the download for sample or patient clinical data exceeds ~500Mb Chrome silently drops the response. It shows HTTP code 200 in DevTools, but the frontend code receives _null_. This appears to be a Chrome limitation that is not reported much (but see [here](https://support.google.com/chrome/a/thread/28233217/chrome-80-seems-to-enforce-a-new-limit-on-post-response-size-of-around-300mb-is-this-by-design?hl=en)). Opening Clincal Tab in FireFox worked fine in my case.

**Comment by pvannierop** [comment]
I have been discussing solutions to this problem with a client involving e.g. pagination. There are more area's that break/become unusable when you  process large studies btw.

**Comment by inodb** [comment]
@pvannierop Thanks for letting us know! Do you happen to have some list of other places where this is a problem? Sounds like this would require quite a big rework of management of the clinical data
