### ISSUE TITLE
patient page should indicate when no genomic data exists

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9708]
I'm not sure if there's an example in the public portal of a sample that only has clinical data, but we have some in our internal portal. For these patients, the Summary & Pathways tabs on Patient page just shows no alterations:
![image](https://user-images.githubusercontent.com/10508276/180831240-0528365d-866d-42d8-a616-fb325c0db1dd.png)

![image](https://user-images.githubusercontent.com/10508276/180830600-7c51647b-44f8-4e16-a489-fb7db1ee1f9e.png)

However, this is misleading because there might be alterations, we just don't know. Can we replace the content on these tabs with a message that says something like 'Patient/Sample has no genomic data available' ? (or if not replace the content, at least add a warning message at the top?)

We have a version of this for patients with some but not all profiles, eg:
![image](https://user-images.githubusercontent.com/10508276/180831592-f368ac7b-453d-4112-8560-fbf395fff516.png)
https://www.cbioportal.org/patient?studyId=lgg_ucsf_2014&caseId=P01

But that doesn't seem to work when a sample completely lacks any genomic data.

**Comment by tmazor** [comment]
Here's an example in public portal - patient has 2 samples, one of which has no sequencing data:
https://www.cbioportal.org/patient?sampleId=RP-1532_PCProject_0013_BLOOD_v1_WGS_OnPrem&studyId=mpcproject_broad_2021

![image](https://user-images.githubusercontent.com/10508276/180833197-722b1ba8-100f-4055-9a9b-bcc2e9e35b66.png)

I guess because the other sample has mut/CNV but not SV, this sample also appears with empty tables for mut/CNV and a 'no SV' message. However it would be better if both Summary & Pathways clearly showed 'no genomic data available'

**Comment by alisman** [comment]
@tmazor from what i can tell, this is all based on the presence of profiles in the study.   If there is no profile, we show the desired message.   But it would seem then that in your private portal, there ARE profiles?  If that's the case then it seems right to show empty tables?  

You can validate this by running the following command in your browser console on the patient page:

```patientViewPageStore.molecularProfilesInStudy.result```

This should output the profiles for the study at hand.

**Comment by tmazor** [comment]
@alisman I guess my point was that this logic should be applied at the sample/patient level, not the study level. Just because a study has profile data doesn't mean that all samples were profiled - and we can do a better job of representing when a particular patient/sample has not been profiled (even if other samples in that same study have been profiled). Like in OncoPrint, where we have tracks to show which samples have been profiled for mutations, CNA, etc -- we should be clear in patient/sample view when a patient/sample is not profiled. Does that make sense?

**Comment by alisman** [comment]
@dippindots @gblaih per Tali's comment above, this ticket is about the case when a there ARE molecular profiles but particular patient/samples are NOT profiled.  @gblaih will need help with how to determine if a sample is profiled.  @dippindots please explain the idea profiling.

**Comment by alisman** [comment]
Cases:
1. Study have no profiles for given alteration type: "Study has no [type] data"
2. Study HAS profile, but sample is NOT profiled: "[Sample|Patient] is not profiled" depending on whether we are in sample or patient mode.

**Comment by alisman** [comment]
We will follow up with better treatment of scenario with two samples where only one is profiled.
