### ISSUE TITLE
Color and glyph changes for OncoPrints

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#971]
Adam,

JJ and I just brainstormed on colors for the OncoPrints, and we came up with the following proposal.

We only need to show recurrence for missense and inframe events. Recurrent missense mutations will remain dark green (008000), and non-recurrent ones get a lighter green (53D400). Recurrent Inframe events change to a slightly nicer grey (708090), and non-recurrent ones become A9A9A9. 

Truncating variants remain unchanged at 000000.

JJ also noticed that the fusion icon does not work well when zooming out. We propose to change its shape to a larger rectangle (not covering the entire height) in purple (8B00C9). 

Everything is shown in the attached PDF.

We should also think about showing two or more mutations in the same sample. See the PDF as well... but this should wait.

Thanks!
[Oncoprint_color_ideas.pdf](https://github.com/cBioPortal/cbioportal/files/194434/Oncoprint_color_ideas.pdf)

**Comment by schultzn** [comment]
![image](https://cloud.githubusercontent.com/assets/11892704/14126431/efb47804-f5de-11e5-9a15-da13e5c83d2b.png)

**Comment by jjgao** [comment]
@adamabeshouse as we discussed, we will have a few different color schema for the users to select:

- uniformly -- green only
- by mutation type
- by recurrence -- green (recurrent) and light green (non-recurrent)
- by mutation type and recurrence (as defined above)
- by oncokb (TBD)

**Comment by adamabeshouse** [comment]
Sounds great, thanks for laying it out so clearly! I'll get right to it.

**Comment by adamabeshouse** [comment]
@schultzn @jjgao Question: what should be shown in the tooltip in the case of multiple types of mutations? Should they be distinguished, in two different lists, or perhaps one list with (non-)recurrent ones italicized?

**Comment by jjgao** [comment]
@adamabeshouse: good questions. Maybe we should put the number of samples with the same mutation in the tooltip?

**Comment by adamabeshouse** [comment]
@jjgao: that too. Right now I just list the mutations, with their multiplicities (e.g. Mutation: G12D,G12D,G12K).

What I'm wondering in addition is if we should denote whether the mutations are recurrent/non-recurrent, in the case that a patient has one of each. Should it be Mutation: <b>G12D</b>,.. or Recurrent Mutations: G12D<br> Non-recurrent Mutations: ...

I like just italicizing or bolding the recurrent ones in the single list.

**Comment by adamabeshouse** [comment]
@jjgao @schultzn How does this interact with sorting by/not sorting by mutation type?

**Comment by jjgao** [comment]
@adamabeshouse in the tooltip, maybe we can use the same words as in the legend, e.g. "Missense Mutation (recurrent): G12D", "Amplification" etc. That may simplify your code.

For sorting/grouping, maybe we can do the same thing as mutation types by providing two options: grouping by all mutations and grouping different different colors. @schultzn?

**Comment by adamabeshouse** [comment]
@schultzn @jjgao 
Suppose a case has two mutations in the same gene, a truncating, which is non-recurrent, and a missense, which is recurrent. Currently, we prioritize displaying truncating, but we'd probably want to prioritize the recurrent mutation, right?

So, two questions
(1) Do we prioritize the recurrent missense over non-recurrent truncating if recurrent mutation mode is selected?
(2) If so, do we also prioritize it if recurrent mutation mode is not selected?

**Comment by schultzn** [comment]
I think it is ok to always prioritize the truncating variant.

We will solve the issue when we support the display of multiple mutations in a sample.

Niki.

**Comment by adamabeshouse** [comment]
The code to do this is ready, we just need to nail down the interface. Right now I have a working interface just as a prototype/placeholder but it's not pretty.

![image](https://cloud.githubusercontent.com/assets/636232/14438808/eec86a9c-fff5-11e5-96a7-64b6e1ea258a.png)

**Comment by jjgao** [comment]
@adamabeshouse maybe we should re-implement the menu bar with a proper menu, e.g. http://www.tutorialrepublic.com/codelab.php?topic=bootstrap&file=dropdowns-within-buttons

**Comment by schultzn** [comment]
This will get even more complex once we have the following options:
 - OncoKB
 - show multiple mutations
 - distinguish germline from somatic

So I am not sure a simple menu will work, as listing all possible combinations will become very difficult.

Can we get together tomorrow to discuss?



On April 12, 2016 at 10:03:44 PM, JianJiong Gao (notifications@github.com) wrote:

@adamabeshouse maybe we should re-implement the menu bar with a proper menu, e.g. http://www.tutorialrepublic.com/codelab.php?topic=bootstrap&file=dropdowns-within-buttons

**Comment by adamabeshouse** [comment]
Here's how it looks with the new color scheme
![image](https://cloud.githubusercontent.com/assets/636232/14904705/1e2097f8-0d78-11e6-864a-ee9900bd8aa8.png)

**Comment by adamabeshouse** [comment]
Here it is, sorted by recurrence
![image](https://cloud.githubusercontent.com/assets/636232/14904720/3ab1a4c0-0d78-11e6-97d3-8f8005a391ab.png)

**Comment by schultzn** [comment]
Thanks Adam. This looks nice!

I forgot what we decided - will there also be sorting by mutation type? Truncating first, then inrlame indels, then missense? That would make sense for some genes…

The legends at the bottom are still slightly off, not quite centerer vertically on the glyph.

N

**Comment by adamabeshouse** [comment]
Sorting by mutation type is indeed an option, in the order you've described above.

The legend label alignment is addressed in https://github.com/cBioPortal/cbioportal/pull/1173

I will loop in @zhx828 to help with styles

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/1203
