### ISSUE TITLE
Improve tooltips for Altered and Unaltered group columns on comparison page

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9718]
[Example query](https://www.cbioportal.org/results/comparison?cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&comparison_subtab=alterations)

The frequencies listed in the Altered group and Unaltere group columns are percentage would appear to be a percentage of the overall number of samples in these respective groups.  In fact, they are a percentage of samples what are profiled for the gene (corresponding to each row).   For this reason, the denominator may change by row and the percentages can't always be compared row by row.  We need to

- [ ] Edit the tooltip of the column headers to indicate this:
Altered group: Number (percentage) of samples in Altered group that are profiled for, and altered in, listed gene.

- [ ] Add tooltip to each cell in row that indicates the same but prints the actual gene. E.g.:
"Number (percentage) of samples in Altered group that are profiled for, and altered in, EGFR"

![image](https://user-images.githubusercontent.com/186521/181273606-04457c4a-a5ae-47f1-8acf-c7a72320fd58.png)

**Comment by alisman** [comment]
@jjgao please assign

**Comment by jjgao** [comment]
Good idea to make the tooltips more clear.

Here is a better example - genes with different denominators: https://bit.ly/45SpUMp - click Gene column to order. 

I think we can add the denominators in the tooltip for the row, similar to the co-occurrence column.

![image](https://github.com/cBioPortal/cbioportal/assets/840895/2bde0b0c-a437-4394-8d9a-4c69c485e0a3)
