### ISSUE TITLE
Swagger Page Inaccessible (redirect old swagger page to /api/swagger-ui.html)

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#9754]
Has the swagger page been accidentally dropped?  The link referenced on the [API and API Clients page](https://docs.cbioportal.org/web-api-and-clients/): [https://www.cbioportal.org/api/swagger-ui.html](https://www.cbioportal.org/api/swagger-ui.html) no longer works.

**Comment by inodb** [comment]
@n1zea144 the URL changed https://www.cbioportal.org/api/swagger-ui/index.html

Would be nice to redirect `/api/swagger-ui.html` -> `/swagger-ui/index.html` if possible

**Comment by inodb** [comment]
@n1zea144 i did just update the [API documentation page](https://github.com/cBioPortal/cbioportal/blob/master/docs/web-API-and-Clients.md) to the correct link
