### ISSUE TITLE
Demo about module [MutationMapper]

### ISSUE THREAD

**Issue by JunqiaoDuan** [cBioPortal/cbioportal#9771]
Hello, I learn that the project [VisualizeYourData - MutationMapper] is very good to visualize Mapping between mutations and protein. But I don't know how to use it in my own project as a single-alone page.
Is there any demo or documents about it, thanks very much.

**Comment by leexgh** [comment]
@JunqiaoDuan Hi! We have an individual package for mutation mapper: https://www.npmjs.com/package/react-mutation-mapper, you can find documentation on the npm page too. Hope this helps. Let us know if you have more questions.
