### ISSUE TITLE
SLF4J warning when loading a study with metaImport.py

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#9775]
When loading a study with metaImport.py, instead of showing the Java logs, this warning is raised multiple times throughout the loading process:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Even though it is not blocking the load of a study it might be very confusing for some users as it reports a failure.

**Comment by Luke-Sikina** [comment]
@oplantalech Thanks for reporting this; what portal version are you using?
