### ISSUE TITLE
oncoprint config user session feedback

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9777]
This is a great addition. A few thoughts:

1) 'Save tracks' button is active when I'm not logged in, but the button does nothing. The button should be inactive and the tooltip should tell users to log in

2) Behavior around logging in and updating the view needs to be improved. While logged out, I added some clinical tracks. I then realized I was logged out and logged in to save those clinical tracks, but the page reloaded and I lost my clinical tracks.

We have a nice approach to this in Study View. I believe how it works is: if I am logged out, and customize the layout, and then log in, one of two things will happen. If I don't already have a saved layout, then the layout I generated while logged out stays and will be saved. If I already have a saved layout, then this message appears and I can actively chose what layout to view:
![image](https://user-images.githubusercontent.com/10508276/187268616-5a984e96-5af7-4197-8f62-ada96f35f0f1.png)

I think we need to adopt logic like this for OncoPrint as well.

3) We should update the login page text to mention OncoPrint

4) I think the tooltip text can be slightly clearer. Instead of
![image](https://user-images.githubusercontent.com/10508276/187270263-1a4ff151-495a-43ce-ac3c-3d9d7fde391d.png)
what if we do something like:
Save clinical tracks. The currently visible clinical tracks will be automatically applied to future queries in the same study/studies.

**Comment by inodb** [comment]
Some thoughts:

- > Save clinical tracks. The currently visible clinical tracks will be automatically applied to future queries in the same study/studies.
  
  "Save clinical tracks. The currently visible clinical tracks will be shown by default for future queries in the same study/studies."

- A reset button would be good. In the study view you can reset your settings which will also remove your stored preferences.
   ![Screen Shot 2022-08-29 at 4 43 42 PM](https://user-images.githubusercontent.com/1334004/187295343-dee82d18-0cfd-4794-bb30-11464259c587.png)

**Comment by pvannierop** [comment]
@tmazor @inodb Thanks for the feedback! We will get to work to address these issues.

**Comment by BasLee** [comment]
@tmazor @inodb: In [8a35d8a](https://github.com/cBioPortal/cbioportal-frontend/pull/4230/commits/8a35d8a1b2858e10ddede844eae803e20503660f) I tried to make the changes as you suggested:
- when not logged in, the tooltip is disabled and it shows the new message
- when changes were made before logging in a menu is shown with buttons to discard or restore the previous changes 
- when no session service is available the button is hidden

@inodb: the reset charts buttons would be a nice new feature. The current PR is already quite large, so I would like to suggest to address it in a follow up PR?

**Comment by tmazor** [comment]
Looks great @BasLee ! Just one thing in terms of the behavior around logging in: if I add clinical tracks while not logged in, then log in, the message appears about whether to keep saved track or revert to previous tracks - that's great if I have previously saved tracks. However, if my query is in a study where I have not previously saved tracks, it would be better if the message simply doesn't appear, and the view remains as it was with the tracks I added prior to logging in. This is how study view works, and I think that behavior is preferable.
