### ISSUE TITLE
Remove dbSnp* and Oncotator* related fields in frontend and backend

### ISSUE THREAD

**Issue by jagnathan** [cBioPortal/cbioportal#9779]
Remove OncotatorProteinPosStar, OncotatorProteinPosEnd, getOncotatorRefseqMrnaId fields in frontend and backend

The changes require both frontend and backend changes. Frontend can be release ahead of backend or both releases have to happen in sync.

OncotatorProteinPosStart
OncotatorProteinPosEnd
refseqMrnaId - Has some frontend code as well

 Removing oncotator fields

Backend changes:
- [x] web/src/main/java/org/cbioportal/web/mixin/MutationMixin.java
- [x] web/src/main/java/org/cbioportal/web/parameter/sort/MutationSortBy.java

- [x] core/src/test/java/org/mskcc/cbio/portal/dao/TestDaoMutation.java

- [x] core/src/main/java/org/mskcc/cbio/maf/MafRecord.java
- [x] 	core/src/main/java/org/mskcc/cbio/maf/MafUtil.java
- [x] 	core/src/main/java/org/mskcc/cbio/portal/dao/DaoMutation.java
- [x] 	core/src/main/java/org/mskcc/cbio/portal/model/ExtendedMutation.java
- [x] core/src/main/java/org/mskcc/cbio/portal/scripts/ImportExtendedMutationData.java
- [x] core/src/main/java/org/mskcc/cbio/portal/util/ExtendedMutationUtil.java
- [x] model/src/main/java/org/cbioportal/model/Mutation.java
- [x] persistence/persistence-mybatis/src/test/java/org/cbioportal/persistence/mybatis/MutationMyBatisRepositoryTest.java
- [x] persistence/persistence-mybatis/src/main/resources/org/cbioportal/persistence/mybatis/MutationMapper.xml

SQL

- [x]   cgds.sql
- [x]   cgds-test.sql
- [x]   testSql.sql
- [x]   core/src/test/resources/seed_mini.sql

**Comment by jagnathan** [comment]
this issue is related to #9461

**Comment by jagnathan** [comment]
ONCOTATOR_DBSNP_RS and ONCOTATOR_UNIPROT_ENTRY_NAME are always null in the cbioportal.org database.

**Comment by jagnathan** [comment]
-- not empty ONCOTATOR_REFSEQ_MRNA_ID								  
-- not empty ONCOTATOR_CODON_CHANGE   
-- not empty ONCOTATOR_UNIPROT_ACCESSION
-- not empty ONCOTATOR_PROTEIN_POS_START 
-- not empty ONCOTATOR_PROTEIN_POS_END
-- not empty DB_SNP_RS
-- not empty DB_SNP_VAL_STATUS

Above fields have data and therefore not removing them.

**Comment by jagnathan** [comment]
All columns that start with ONCOTATOR_ prefix replaced with MUTATION_ prefix.

**Comment by jagnathan** [comment]
In the file portal/src/org/mskcc/portal/model/MafRecord.java the prefix oncotator is replaced with prefix maf.

**Comment by dippindots** [comment]
This is included in the `v5.3.0`, we can close this now.
