### ISSUE TITLE
Circular reference in docs

### ISSUE THREAD

**Issue by Luke-Sikina** [cBioPortal/cbioportal#9780]
https://docs.cbioportal.org/deployment/docker/using-keycloak/

> Finally, configure Keycloak and cBioPortal as explained in the [Keycloak documentation](https://docs.cbioportal.org/deployment/docker/using-keycloak/). Remember to specify port 8180 for the Keycloak server, wherever the guide says 8080.

Should probably link to [https://docs.cbioportal.org/deployment/authorization-and-authentication/authenticating-and-authorizing-users-via-keycloak/](https://docs.cbioportal.org/deployment/authorization-and-authentication/authenticating-and-authorizing-users-via-keycloak/)

**Comment by inodb** [comment]
@Luke-Sikina thanks for reporting! Really fixed it now I think in https://github.com/cBioPortal/cbioportal/commit/984525825b51ef629054f95aa8bde4a29f9aa134
