### ISSUE TITLE
Improve the performance of clinical data load in client js

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#979]
The client code to load clinical seems to be significantly slower than the previous code using the old API.

**Comment by adamabeshouse** [comment]
Server-side optimization attempts (pulling some attribute fetching out of the SQL query and putting it into the data in the Java layer) made it 2x slower....

Not sure if it will be possible to improve this with the currently fetched attributes besides database refactoring, which I think wouldn't be so bad an idea.

**Comment by jjgao** [comment]
@hon

**Comment by zhx828** [comment]
As I mentioned, I made some changes on the clinical attribute API. I will send a pull request to review ASAP.

**Comment by jjgao** [comment]
@adamabeshouse I assume this has been fixed for now.

**Comment by adamabeshouse** [comment]
@jjgao I haven't touched it since my last comment, but it looks like Hongxin's pull request addressed it
