### ISSUE TITLE
Fix localdb screenshot involving heatmap gradient (after premature merge  of 4361)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9796]
This screenshot needs to be fixed

https://output.circle-artifacts.com/output/job/2d49508d-9a2a-4b3b-9953-53f4cb6b7644/artifacts/0/imageCompare.html

**Comment by BasLee** [comment]
Should be fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/4369
