### ISSUE TITLE
p/q values overlap in comparison view in chrome on genie portal

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9822]
<img width="1074" alt="Screen Shot 2022-09-27 at 8 31 53 AM" src="https://user-images.githubusercontent.com/1334004/192527219-fc13e886-8900-4de3-9295-aee16dc59ab9.png">

https://genie-private.cbioportal.org/results/comparison?cancer_study_list=bladder_genie_bpc&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Ccna&case_set_id=bladder_genie_bpc_cnaseq&gene_list=EGFR&geneset_list=%20&tab_index=tab_visualize&Action=Submit&comparison_subtab=clinical

**Comment by alisman** [comment]
@gblaih 
This can also be seen on public portal here:

https://www.cbioportal.org/results/comparison?cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&comparison_subtab=clinical
