### ISSUE TITLE
genie portal shows NA for some centers in comparison view despite all data available

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9824]
All data is here https://genie-private.cbioportal.org/study/summary?id=bladder_genie_bpc:

<img width="267" alt="Screen Shot 2022-09-27 at 9 27 48 AM" src="https://user-images.githubusercontent.com/1334004/192539352-371c2796-06e7-4650-886e-4750c2a6ec71.png">

Yet we see in NA in comparison:

<img width="168" alt="Screen Shot 2022-09-27 at 9 29 30 AM" src="https://user-images.githubusercontent.com/1334004/192539764-46039d5e-3044-486e-980f-426546a2aa2f.png">

https://genie-private.cbioportal.org/comparison/clinical?comparisonId=632caa9002558d441fb7ff30

**Comment by leexgh** [comment]
![screenshot-genie-private cbioportal org-2022 09 28-14_14_32](https://user-images.githubusercontent.com/16869603/192858800-5ef24a5c-b959-478c-9fcb-30bbf667997a.png)

**Comment by leexgh** [comment]
Select `Include overlapping samples and patients` on the top then “NA” disappears
![Sep-30-2022 11-52-48](https://user-images.githubusercontent.com/16869603/193378779-147d3b68-f38d-4f71-ae04-4064cfb248f7.gif)
