### ISSUE TITLE
Putative driver info is not loaded and hotspots annotation failed in this query

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#9831]
Originally found by Niki. These annotations are not turn on by default and can not be turned on again.
<img width="295" alt="image" src="https://user-images.githubusercontent.com/5400599/193278106-969a060a-28d3-48f6-b83f-cd996da034db.png">

I took a brief look. The only unusually seems to be one of the genomic API call to GN failed. All proxy calls finished properly. 
Query link: https://bit.ly/3E7pUwr

**Comment by alisman** [comment]
@inodb @leexgh @onursumer 

Call to Genome Nexus is 404'ing, resulting in this.

**Comment by leexgh** [comment]
Seems other GN cancer hotspots calls are fine, I'll look into it

**Comment by daikomyo** [comment]
Not sure if this has anything to do with this issue but we've noticed that when we query by a single gene at a time, the annotations are on but when we include the same gene in a multi-gene search, they are sometimes turned off.

![Snag_64d8d754](https://user-images.githubusercontent.com/1226429/193953490-60c2673e-b86e-4333-9e78-3a8603834d79.png)
![Snag_64d902e8](https://user-images.githubusercontent.com/1226429/193953511-a3e1f61b-2763-4ab7-9486-a316bef67cfe.png)

**Comment by leexgh** [comment]
It got 404 because of two same mutations:
[{
    "chromosome": "7",
    "start": 55242467,
    "end": 55242486,
    "referenceAllele": "AATTAAGAGAAGCAACATCT",
    "variantAllele": "AT"
},
{
    "chromosome": "7",
    "start": 55242468,
    "end": 55242486,
    "referenceAllele": "ATTAAGAGAAGCAACATCT",
    "variantAllele": "T"
}]

**Comment by leexgh** [comment]
@zhx828 @schultzn @daikomyo The problem should be fixed, could you help to confirm? Thanks!

**Comment by schultzn** [comment]
Thank you - confirming that the issue is fixed!
