### ISSUE TITLE
risk tables for survival charts on comparison page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9841]
It would be great if we can show risk tables on the comparison page:
![image](https://user-images.githubusercontent.com/1334004/193913432-88291542-9ea6-4755-ab40-b8a3414cc7f2.png)

Especially for left truncation work it might be nice to show adjusted + unadjusted

**Comment by peteroke75** [comment]
Apparently, it was great efforts put in the analysis, am in agreement with this post if the risk table is available, it will give a broader view of the whole prediction.

**Comment by inodb** [comment]
this is fixed
