### ISSUE TITLE
Study-search box makes cBioPortal crash when typing or

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#9849]
If you write _or_ in the study-search box (main page), cBioPortal crashes.

**Comment by alisman** [comment]
@oplantalech which version of the portal are you looking at? changes were made recently, so I want to make sure you're looking at newest release. in my testing, it doesn't crash, but it seems to auto-delete the word or sometimes when i type it.

**Comment by oplantalech** [comment]
@alisman I can reproduce the error right now in cbioportal.org (version 5.1.3).

**Comment by BasLee** [comment]
Is fixed in PR https://github.com/cBioPortal/cbioportal-frontend/pull/4394
