### ISSUE TITLE
Lollipop OncoKB track does not show ALK resistant mutation G1202R

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9900]
See: 

https://bit.ly/3hNhOjn

<img width="106" alt="Screen Shot 2022-11-18 at 11 12 53 AM" src="https://user-images.githubusercontent.com/1334004/202750490-8323f636-090d-4d88-b747-bbe5ad03c948.png">

**Comment by onursumer** [comment]
@inodb @zhx828 looks like we filter out resistant mutations by default. So only `oncogenic` mutations end up in the track.

https://github.com/cBioPortal/cbioportal-frontend/blob/5e9f19863ebc953c67dbe561408149a5e6488c16/packages/oncokb-frontend-commons/src/util/OncoKbUtils.ts#L119

Should we go ahead and also include `resistance` in the filter?

**Comment by zhx828** [comment]
> @inodb @zhx828 looks like we filter out resistant mutations by default. So only `oncogenic` mutations end up in the track.
> 
> https://github.com/cBioPortal/cbioportal-frontend/blob/5e9f19863ebc953c67dbe561408149a5e6488c16/packages/oncokb-frontend-commons/src/util/OncoKbUtils.ts#L119
> 
> Should we go ahead and also include `resistance` in the filter?

thanks for looking into, yes please.
