### ISSUE TITLE
Group Comparison Lollipop Improvements

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9901]
High priority
- [x] Show which %/# is currently selected (put this state in URL)
    <img width="116" alt="Screen Shot 2022-11-18 at 11 31 35 AM" src="https://user-images.githubusercontent.com/1334004/202754425-a23cd25b-a175-4a2e-a520-b4d0c63bb265.png">
- [x] Selected gene should be in URL
- [x] Percentage is incorrect (divide per group). E.g. in this [GRM3 example](https://genie.cbioportal.org/comparison/mutations?comparisonId=62fcec4a67dd38077635abd2&groupOrder=%5B%22Pre-Crizotinib%22%2C%22Post-Crizotinib%22%5D&featureFlags=group_comparison_mutations_lollipop_plot). Should be 1 mutation / 26 total samples in group B (3.8% instead of 8.4% as it is now). Also good to mention in the tooltip we are showing # of samples rather than # of patients e.g. `3.8% mutation rate (1/26 samples)`

Others:
- [x] Show Driver vs VUS icons like on results view
    - [x] For the driver annotation source selector let's place it at the top somewhere close to the gene selector, so it is clear it stays enabled when selecting different genes
    <img width="278" alt="Screen Shot 2022-11-18 at 11 33 56 AM" src="https://user-images.githubusercontent.com/1334004/202754930-cf2b9a23-c3af-4652-a484-72e9edbace1d.png">
- [x] Show counts separately for each group
- [x] Figure out gene selector (show either on same line as highest frequencies or show top frequencies in dropdown)
- [x] Highest frequency should show only "Mutations" highest frequency (rather than Mut+SV+CNA)
- [x] Don't show genes without mutations in dropdown (if possible we can potentially sort the dropdown by frequency (i guess we should have these numbers from genomics alterations tab filtered by mutations only)
- [x] Show absolute counts of mutations into tooltip even when in frequency mode
- [x]  When hovering over a lollipop which exists in both groups, show both tooltips at once

![image](https://user-images.githubusercontent.com/186521/205363213-c6c4a4d7-b38a-431c-bd9c-372471da15bf.png)

**Comment by tmazor** [comment]
This is such a great feature to have! Nice work!

I agree with all the comments above, and have some additional comments:

1) y-axis labels are overlapping in multiple ways:
![image](https://user-images.githubusercontent.com/10508276/202857356-fa3ad999-2285-4b49-b7a9-3220c66e0ddf.png)
https://www.cbioportal.org/comparison/mutations?comparisonId=6138b02de6ebe01a6ee2de0b&featureFlags=group_comparison_mutations_lollipop_plot&unselectedGroups=%5B%22NA%22%2C%22LGG_IDHwt%22%5D 

2) Everywhere else in group comparison we refer to groups with (A) xxxxx and (B) yyyyy, and almost always with consistent coloring also
![image](https://user-images.githubusercontent.com/10508276/202857464-19f8cc20-d038-4bfd-98f5-2e1c26710790.png)
![image](https://user-images.githubusercontent.com/10508276/202857469-a6121684-01a7-48cc-b65f-3bf3448eaf54.png)
At a minimum, I think the (A), (B), etc need to be added to the y-axis labels to help with quickly understanding which group is which (group names can be long and very similar to each other, making it hard to quickly grasp). If there's a way to bring in the color too, that'd be even better.

3) On the Mutations tab, if I add annotation tracks (eg OncoKB, Hotspots), those tracks remain visible as I switch between genes. It would be great to have that behavior here also.

4) It would be nice if the tooltip could show both # and %, regardless of the current settings for the y-axis
![image](https://user-images.githubusercontent.com/10508276/202857816-8f0dfb7f-80d3-48ea-8d21-bac35e40b474.png)

**Comment by inodb** [comment]
i think all these are solved. Looks like there is a separate issue for the "only" logic
