### ISSUE TITLE
Detect and better visualize related clinical data types in study view

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9904]
There are groups of clinical data types (e.g. [metastatic site](https://genie.cbioportal.org/study/summary?id=nsclc_public_genie_bpc)) which are not well served by serial pie charts.  They should be showing as rows in a single table with some visualization (heatmap, stacked bar chart) showing the distribution of various values/categories.  

This visualization provides a rough example of this idea:
![image](https://user-images.githubusercontent.com/186521/203162900-15fa045e-fa7c-4af9-a7c4-ed39f389ada7.png)

**Comment by dippindots** [comment]
close and open a new ticket: https://github.com/cBioPortal/cbioportal/issues/9951
