### ISSUE TITLE
Detect presence of grouped clinical data types in study view and create new chart type for them

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9905]
We can detect presence of these grouped types by matching against the clinical data type.  

This study for example: 
https://genie.cbioportal.org/study/summary?id=nsclc_public_genie_bpc

Has a set of DMETS_DX_ types which should be grouped.

![image](https://user-images.githubusercontent.com/186521/203163764-8a5997ee-9829-4463-84f4-97aaeecfaf09.png)

- [ ] The patterns for matching against these IDs should be configurable with array of matching expressions. E.g. for the above
```config.studyViewGroupedClinicalData = ["^DMETS_DX_"]```
- [ ] Create a new chart for each grouping.  It should be a table in which rows are the matched clinical data types.

Visualization for each row will be in another ticket.

**Comment by dippindots** [comment]
Close this and open a new ticket: https://github.com/cBioPortal/cbioportal/issues/9951
