### ISSUE TITLE
horizontal scroll bar still get displayed when only few studies are selected in cross cancer histogram

### ISSUE THREAD

**Issue by JiaoJiao123** [cBioPortal/cbioportal#991]
![image](https://cloud.githubusercontent.com/assets/13951023/14180572/9fa974c8-f731-11e5-857d-20069f509ce4.png)

**Comment by JiaoJiao123** [comment]
@adamabeshouse Could you help to fix this? since I saw you had the pull request-made the bar width fixed

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/993
