### ISSUE TITLE
Profiling bug in MSK Impact 

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9920]
https://cbioportal.mskcc.org/results/oncoprint?cancer_study_list=mskimpact&tab_index=tab_visualize&case_set_id=mskimpact_all&Action=Submit&gene_list=NRG1

**Comment by alisman** [comment]
https://cbioportal.mskcc.org/results/oncoprint?cancer_study_list=mskimpact&tab_index=tab_visualize&case_set_id=mskimpact_all&Action=Submit&gene_list=NRG1

The reason these patients show up profiled for mutations is they have samples that do not have gene panels associated with them.  They are therefor considered profiled for ALL genes.  

Note that the second sample does not have a genePanelId.  

![image](https://user-images.githubusercontent.com/186521/205737064-f52a316c-5323-4935-9f03-1f4ffce459fb.png)

The reason they show up with structural variants is that NRG1 was detected as fusion partner of a gene which is profiled:

![image](https://user-images.githubusercontent.com/186521/205737450-d90bc318-7430-463c-ad32-eeb1a7d482c8.png)

**Comment by sbabyanusha** [comment]
@alisman thank you for looking into this. This is fixed by adding the missing profiled sample id's to the gene panel matrix file.
