### ISSUE TITLE
on data sets page rename "mass spec" -> "Protein Mass Spectrometry"

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9925]
![image](https://user-images.githubusercontent.com/1334004/206553181-ef975021-104d-4588-99d3-85e622b4de1b.png)

From Chris:

> mass spec is a method. not a data item
> and fuzzy, as mass spec can also measure metabolites

**Comment by manik-dhanjal** [comment]
Hi @inodb, I am interested to resolve this issue can you please assign it to me.
