### ISSUE TITLE
comparison survival tab has data in KM plot but nothing in table

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#9991]
The Survival tab in Group Comparison shows a KM plot, so there's clearly some outcomes data, but the table to the left shows nothing. It's a multi-study group comparison, which might be the issue?

https://www.cbioportal.org/comparison/survival?comparisonId=63d442c6d9f4971d767d090d

![image](https://user-images.githubusercontent.com/10508276/216066531-8f688741-a16b-466d-b2aa-e3f6731697bb.png)

**Comment by onursumer** [comment]
Looks like the default threshold value is coming from the server config: https://github.com/cBioPortal/cbioportal-frontend/blob/2169f4138f2e5049d5f0f8c83f49054436e39ff9/src/pages/resultsView/survival/SurvivalPrefixTable.tsx#L269-L270

And we apply this threshold to `every` group, so there is an `AND` logic here. 
https://github.com/cBioPortal/cbioportal-frontend/blob/2169f4138f2e5049d5f0f8c83f49054436e39ff9/src/pages/resultsView/survival/SurvivalPrefixTable.tsx#L129


The `NA` group doesn't satisfy this condition so everything else is filtered out. Not sure if this is the intended behavior.

**Comment by onursumer** [comment]
For this specific example, `# Patients per Group` is as follows:

```
(A) Female: 18123
(B) Male: 17301
(C) NA: 1
```

It's not very clear to me why we need to filter the table by `# Patients per Group`? We hide the  `# Patients per Group` columns by default. It would make more sense to me if this filter was applied to the `Number of Patients` column instead.

![image](https://user-images.githubusercontent.com/3604198/217644871-f78f768e-f995-4f5f-97cf-ae8a4ac56b52.png)

**Comment by tmazor** [comment]
Thanks for the investigation @onursumer. I have a vague memory that this filtering was prompted by the GENIE stats group - @inodb do you remember?

**Comment by inodb** [comment]
@tmazor yes this was requested by stats team. Not sure how to best address this. Maybe some banner indicating that one of the groups has fewer samples than the minimum threshold? Or filter out the groups that are below the threshold?

**Comment by tmazor** [comment]
What was the actual request/concern from the stats team @ino? Because it seems really confusing to me that by default we would filter all results out of the table, but we're still showing the OS KM plot. I think regardless of what approach we take, we need more consistency between the table and the plot.

I like the idea of filtering out groups rather than OS as a whole - like in this example, 2 groups are huge and an outcomes analysis between those groups seems totally reasonable. And I also like adding a banner or note somewhere to say that there is a filter applied, since I clearly missed that.

**Comment by onursumer** [comment]
https://deploy-preview-4511--cbioportalfrontend.netlify.app/comparison/survival?comparisonId=63d442c6d9f4971d767d090d

@tmazor what do you think about this solution? Basically, we just hide the plot initially. Instead we display a warning message and ask the user to adjust the filters to see some results.

**Comment by tmazor** [comment]
That's great @onursumer !
